### ISSUE TITLE
o command with fd doesn't switch to selected file descriptor

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#10022]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 32, OSX High Sierra
| File format of the file you reverse (mandatory)      | ELF, Mach-O
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 18091 @ darwin-x86-64 git.2.5.0-181-g3783a50b2; commit: 3783a50b246e230407f641cc9e078441880414fc build: 2018-05-06__11:25:45

### Expected behavior
`o 3` should switch to file descriptor 3

### Actual behavior
radare2 keeps the same file opened.

### Steps to reproduce the behavior 
1. r2 /bin/ls
2. `o /bin/cat`
3. `o` -> correctly stated that the current file is `bin/cat`
4. switch to fd 3: `o 3`
5. `o` - radare2 keeps informing that the file is still `bin/cat`

https://asciinema.org/a/9Pf4mJD17hqvBZ1ijai9mXcac

### Additional Logs, screenshots, source-code,  configuration dump, ...
N/A

### Potential workaround
Looks like using `oi` command with an index instead of fd switches the file but not sure yet if that actually means something for rest of the commands (but at least the '*' moves to the selected file).
I'll do some more code analysis of this issue later.

**Comment by radare** [comment]
no. that behaviour changed 1 year ago

its just the help message is wrong. use op for this

**Comment by pawlos** [comment]
thanks for the info, `op` also gives some strange results but I'll describe them in a separate ticket once I understand what's going on.
