### ISSUE TITLE
print commands append a space to output

### ISSUE THREAD

**Issue by vdf-git** [radare/radare2#10039]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | arm/16 (ie. thumb-2)
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 18109 @ linux-x86-64 git.2.5.0-198-ge216f08 commit: e216f088261f39a4709dd4c2a363995c6cd13e19 build: 2018-05-07__13:25:59

### Expected behavior

Various commands that have a text output appends a spurious space to the output. E.g. the command 
wa ldr r0, [pc, \`?v 0x4 + $$ % 0x4\`]
should (at a word aligned address) assemble the command 
ldr r0, [pc, 0x4]
ie.
0148
### Actual behavior
after evaluating the backtick it attempts to assemble the command
ldr r0, [pc, 0x4 ]
NB: There is a " " between "0x4" and "]". This fails for the thumb-2 assembler (and quite possibly for other instruction sets as well)

### Steps to reproduce the behavior 
The binary (and a link to it) cannot be shared. However, any thumb-2 code will do: ensure that asm.arch=arm and asm.bits=16 and attempt executing
wa ldr r0, [pc, \`?v 0x4 + $$ % 0x4\`]

**Comment by pawlos** [comment]
this is actually not a space but a new line (\xA) character and it's produced by [cmd_help.c:604](https://github.com/radare/radare2/blob/master/libr/core/cmd_help.c#L603). Removing the `\n` there generates a version that covers the result with the r2 prompt. I'll check if maybe this additional space can be removed only in case this is done in ``.

**Comment by radare** [comment]
i think this space is on purpose , but the assembler should handle such syntax , extra spaces before a bracket shouldnt be a problem
