### ISSUE TITLE
Remove Sd command

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#10064]
`Sd` doesn't work anymore and It is a duplicate of `iO d/S/.text` thus it should be removed.

**Comment by Maijin** [comment]
Probably need also to add something in `iO d/S/` to specify when we went it raw instead of hex

**Comment by radare** [comment]
why 2.7 and not 2.6?

the whole S command must die, not just Sd

**Comment by Maijin** [comment]
Oh because there is probably enough to do in 2.6.0
