### ISSUE TITLE
r2/debugger messages are not sent to TCP r2pipe

### ISSUE THREAD

**Issue by Darkkey** [radare/radare2#10097]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 1 @ windows-x86-64 git.commit: 562bd8f65ac9bcfb30ea2d2da95b6178776471a8 build: Tue 04/10/2018__ 8:26:07.70

### Expected behavior

When running radare2 in debug mode using TCP pipe all debug messages should go to that pipe.

### Actual behavior

On the contrary, they are going to radare2 stderr, instead of TCP pipe. 

### Steps to reproduce the behavior 
- launch notepad.exe
- radare2.exe -qc.:9080 -d <notepad.exe PID>
- nc localhost 9080 and type 'dc'

### Additional Logs, screenshots, source-code,  configuration dump, ...

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/3229276/40048271-1cb0f460-5832-11e8-83d8-f6f2f040bffe.png">

dark_k3y, [15 May 2018, 11:17:39]:
why theads info is in console, not in tcp port?

pancake, [15 May 2018, 11:17:40]:
because its an eprintf
that goes to stder

dark_k3y, [15 May 2018, 11:18:17]:
any chance to fix it?

pancake, [15 May 2018, 11:18:31]:
yeah its just s/eprintf/r_cons_printf

**Comment by radare** [comment]
no need for r2pipe or tcp to reproduce this just `dc > foo.txt` is enough
