### ISSUE TITLE
Doesn't install on High Sierra?

### ISSUE THREAD

**Issue by bferguson3** [radare/radare2#10096]
The package opens fine
The install completes fine
When the install is done, the app and files are nowhere to be found on my system.

Poked around for half an hour, couldn't figure this out.

**Comment by pawlos** [comment]
I'm on High Sierra and have no issues. Just typing `r2` in the cmd executes radare2. Do you install it from git according to the [README.md](https://github.com/radare/radare2#install)?

**Comment by bferguson3** [comment]
No, I installed it from the .pkg. I assumed it was a GUI based tool at first, and was trying "radare2" not "r2".

Is 65xx architecture not or no longer supported? That was my entire purpose for installing it.

**Comment by Maijin** [comment]
_dAe  8 16       6502        LGPL3   6502/NES/C64/Tamagotchi/T-1000 CPU
is here
