### ISSUE TITLE
Move lang_python3.c

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10112]
Saw [](https://github.com/radare/radare2/commit/4d61d66e29131bd532647eb55cde073c7161caf2) and thought that moving lang_python.c here is a good option too, since Python is de-facto standard scripting language in ITsec and RE communities and "lang-python" doesn't require python bindings, just python itself installed. Could be a configure option or so. IMHO, this one should be out of the box (at least on Linux systems where Python is omnipresent).

**Comment by radare** [comment]
where is this lang_py3?

**Comment by XVilka** [comment]
Here https://github.com/radare/radare2-bindings/blob/master/libr/lang/p/python.c

**Comment by radare** [comment]
This adds the python dependency which is a mess. I prefer to keep it outside
