### ISSUE TITLE
Add usb sniffing capability to radare2

### ISSUE THREAD

**Issue by RKX1209** [radare/radare2#10128]
Does radare2 have the capability to sniff usb communication like [libusbsniff](https://github.com/radare/radare/tree/master/libusbsniff)?
It can be useful for debugging over usb connection to embedded systems.

**Comment by Maijin** [comment]
that should probably go in r2-extras

**Comment by XVilka** [comment]
@RKX1209 r2 supports opening PCAP files with a plugin from extras. And USB sniffers able to produce PCAP files. So you may want to try to extend it or create a script/plugin on top of it.

**Comment by radare** [comment]
Nowadays i would probably use r2frida for this

**Comment by RKX1209** [comment]
Hmm. I want to implement Nintendo Switch debugger for radare2. 
It requires usb connection between r2 and switch to exchange debug packets. 
So I'd like to add capability of usb communication with some third party library like libusb.
What do you think?

**Comment by radare** [comment]
you can do that with an IO plugin using libusb, but this must go into extras

**Comment by RKX1209** [comment]
Sure Thx!

**Comment by XVilka** [comment]
@RKX1209 you can check the implementation of remote GDB io and debug plugins as an example. It basically uses the similar network capabilities.

**Comment by radare** [comment]
There are easier plugins to look at. R2frida dor example also uses debug.io to run debug commands thru the io interface
