### ISSUE TITLE
afv commands do not work

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#10122]
```
$ r2 ./r2r/bins/elf/analysis/ls-alxchk
> aaa
> s main
```

`afvR` and `afvW` do not return anything.
`afvR local_10h` gives `See afv?, afvb?, afvr? and afvs?`. 

I think both results are wrong.

**Comment by ret2libc** [comment]
my bad, probably some libraries were old

**Comment by XVilka** [comment]
Please send a PR to radare2-regressions.
