### ISSUE TITLE
`dmh` commands are not working properly on Fedora 28

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10127]
Probably because of moving to glibc 2.27 - [changelog](https://abi-laboratory.pro/tracker/changelog/glibc/2.27/log.html)
```
r2 -d /bin/ls
Process with PID 363597 started...
= attach 363597 363597
bin.baddr 0x55f85fb0c000
Using 0x55f85fb0c000
asm.bits 64
 -- You see it, you fix it!
[0x7f5bc1d0ff60]> db main
[0x7f5bc1d0ff60]> dc
hit breakpoint at: 55f85fb0fe50
[0x55f85fb0fe50]> dmhj
[0x55f85fb0fe50]> dmhg
Heap Layout
┌────────────────────────────────────┐    ┌────────────────────────────────────────────────────┐
│    Malloc chunk @ 0x55f861330000   │    │  Top chunk @ 0x0                                   │
│ [corrupted] size: 0x251            │    │ [brk_start:0x55f861330000, brk_end:0x55f861351000] │
│  fd: 0x0, bk: 0x0                  │    └────────────────────────────────────────────────────┘
│ Heap graph could not be recovered  │
└────────────────────────────────────┘
[0x55f85fb0fe50]> db sym.imp.free
[0x55f85fb0fe50]> dc
hit breakpoint at: 55f85fb0f740
[0x55f85fb0f740]> dmh

  Top chunk @ 0x0 - [brk_start: 0x55f861330000, brk_end: 0x55f861351000]

[0x55f85fb0f740]> dmhj
[0x55f85fb0f740]> dmhg
Heap Layout
┌────────────────────────────────────┐    ┌────────────────────────────────────────────────────┐
│    Malloc chunk @ 0x55f861330000   │    │  Top chunk @ 0x0                                   │
│ [corrupted] size: 0x251            │    │ [brk_start:0x55f861330000, brk_end:0x55f861351000] │
│  fd: 0x0, bk: 0x0                  │    └────────────────────────────────────────────────────┘
│ Heap graph could not be recovered  │
└────────────────────────────────────┘
[0x55f85fb0f740]> 
```

**Comment by roboman2444** [comment]
I'm experiencing the same issues... On Arch's glibc 2.27

**Comment by radare** [comment]
There are 0 heap allocations when you stop in the main. Thats obvious and not an issue. Use dcu insteas of the boring db+dc.

Btw this was working for me yesterday in archlinux for x86-64. Didnt tried qith other distros

**Comment by XVilka** [comment]
@radare note, I stopped at "free", so there should be at least one allocation before, but the layout is still same.

**Comment by roboman2444** [comment]
I also stopped after running multiple malloc's and a few free calls.

Note, DMH has a different result when attaching to an already running process...
`
[0x00000000]> dmh

  Malloc chunk @ 0x559280775000 [corrupted]
   size: 0xffffffffffffffff
   fd: 0xffffffffffffffff, bk: 0xffffffffffffffff

  Top chunk @ 0xffffffffffffffff - [brk_start: 0x559280775000, brk_end: 0x559280796000]
`



But when starting a process with r2 (eg: r2 -d ./test), the dmh commands still fail to work
`
:> dmhg
Heap Layout
┌────────────────────────────────────┐    ┌────────────────────────────────────────────────────┐
│    Malloc chunk @ 0x56338d3d5000   │    │  Top chunk @ 0x0                                   │
│ [corrupted] size: 0x251            │    │ [brk_start:0x56338d3d5000, brk_end:0x56338d3f6000] │
│  fd: 0x0, bk: 0x1000000000000      │    └────────────────────────────────────────────────────┘
│ Heap graph could not be recovered  │
└────────────────────────────────────┘
:> 
`

**Comment by radare** [comment]
enotime for this now, if you can spent some time invesgating and improving the heap analysis i’ll appreciate

**Comment by XVilka** [comment]
@soez while you are on it, can you please check this one too?

**Comment by radare** [comment]
they fixed the issue yesterday, can you try again pls?

**Comment by soez** [comment]
I think that when the tcache lists are also implemented, everything is fatal ... that's new in glibc 2.27, right? In radare2 is still not implemented ... patience

**Comment by javierprtd** [comment]
It is already implemented by @morbith-dqtz :)

**Comment by XVilka** [comment]
Yes, it is fixed.
