### ISSUE TITLE
Parameter names

### ISSUE THREAD

**Issue by gu10ng1t** [radare/radare2#10143]
I'd like to know how to see the parameter names of well known functions (libc, Win32 API, etc.).
See below an example of such thing in Ollydbg:

![](https://i.stack.imgur.com/XeAoA.png)

I searched in the book but couldn't find it, neither in the issues list.

**Comment by sivaramaaa** [comment]
Hey hi @gu10ng1t 

* If u just want just want to see the parameter names of well known functions , u can just use `aaaa` : 

![func_name](https://user-images.githubusercontent.com/18589720/40288617-b4904a44-5cd1-11e8-987d-6c27e8a6e5b8.png)

* If u want it's value while debugging , just enable `e dbg.funcarg = true`, and u can see this display while u step into a call instruction
 
![visual_arg](https://user-images.githubusercontent.com/18589720/40288628-bc2f9598-5cd1-11e8-9774-3ba9f0e0c77d.jpg)

**Comment by gu10ng1t** [comment]
Thank you @sivaramaaa  you make a great work here!

But anyway, let me just try clarify my idea here:

What you see below is what I see with `e dbg.funcarg = true` enabled:
![dbg funcarg](https://user-images.githubusercontent.com/25881395/40290089-5458f020-5c92-11e8-95a5-64bd8b7f0a8b.png)

But what I would like (and I guess, some others ;) is:
![parameters comment](https://user-images.githubusercontent.com/25881395/40290125-7e77626a-5c92-11e8-8304-fa97fc55d998.png)

man mmap:
```
void *mmap(void *addr, size_t length, int prot, int flags,
                  int fd, off_t offset);
```
strace binary:
`mmap2(0x74772000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_SHARED|MAP_FIXED|MAP_ANONYMOUS, 0, 0) = 0x74772000`

I wonder if that process could be automated sometime in the future =)

**Comment by gu10ng1t** [comment]
Well, I don't know what we should expect from functions like scanf, but I got:
![scanf](https://user-images.githubusercontent.com/25881395/40291051-e0702f5a-5c98-11e8-8d69-ca27dd9b8950.png)
strcmp seems to be working:
![strcmp](https://user-images.githubusercontent.com/25881395/40291065-f3aa9a10-5c98-11e8-943e-5ec366b88ff0.png)
>  it seems that just mmap function signature is missing from r2 database
Users like me should update that database manually? How that process does works?

**Comment by sivaramaaa** [comment]
>  strcmp seems to be working:

good to hear :) 

> Well, I don't know what we should expect from functions like scanf, but I got:

u should be able to see a format string and a memory address, but this thing is still in WIP, so yeah it should be improved 

>it seems that just mmap function signature is missing from r2 database
>> Users like me should update that database manually? How does this process work?

Once this command is complete, it should not be necessary to do it manually , but as a workaround  u can load ur own function signature using `tk` command , see `libr/anal/d/types.sdb.txt`

Also feel free to send a PR to update function signature , look at `libr/anal/d/` for missing signatures :)
