### ISSUE TITLE
LGTM alerts

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10152]
See the report at https://lgtm.com/projects/radare/radare2/alerts/?mode=list.

Moreover, this thing can be integrated in master builds and pull requests: see https://lgtm.com/help/lgtm/using-lgtm-analysis-continuous-integration

**Comment by xarkes** [comment]
Page not found for me.

**Comment by radare** [comment]
Can we get those tips as “one per day in the irc”? Maybe this will make people contribute or discuss them

**Comment by Maijin** [comment]
ping1

**Comment by Maijin** [comment]
all the issues are in the javascript/html of the radare2-webui embedded in the source or some of the sparsed .py; it doesn't work with the C files so it's useless to add that in the PR 👎

**Comment by XVilka** [comment]
@Maijin no, somehow it skips the C files in the report for radare2, on the other hand it took them from radare2 while checking cutter. So there are still useful warnings. Probably need some better setup.

**Comment by sjvs** [comment]
Hi team — apologies for being late to the party! Results for C/C++ analysis are now available for radare2 on LGTM.com: https://lgtm.com/projects/g/radare/radare2/alerts/.

I'd especially like to urge you to take a close look at the four results for "Potentially overflowing call to snprintf": these look potentially dangerous to me, and have in other projects resulted in CVEs (e.g. https://lgtm.com/blog/rsyslog_snprintf_CVE-2018-1000140)

As @XVilka mentioned, LGTM offers automated code review for pull requests; you can enable it here: https://lgtm.com/projects/g/radare/radare2/ci/. That page also contains some badges that you can add to your `README.md` if you like.

Let me know if you have any comments/suggestions/questions. Happy to help!

(Full disclosure: I'm part of the team that built LGTM.com)

**Comment by mscherer** [comment]
I guess the analysis broke around the 10th of august with this: https://lgtm.com/projects/g/radare/radare2/logs/rev/dcb481122c62eb293f28774eb8d077532785e307/lang:cpp/stage:Build%20child%20(dcb4811) 

I am not sure if there is something to do on the code side, because while the reports are useful, they are also out of date, and lots of issues seems to have been fixed already.

**Comment by XVilka** [comment]
@sjvs it seems like some network problem on LGTM side, since it doesn't allow us to clone the capstone during the build.

**Comment by Maijin** [comment]
Git submodule aren't included in the release packages (zip. tar.gz) generated by github, I have asked for work-around to github team but so far haven't received any answer.

**Comment by sjvs** [comment]
That's weird. I hope GitHub get back to you soon!

Suggestion:
- Use Git submodules to make day-to-day work on your repository easier (and LGTM will happily use them)
- Tweak your build script: 
  - if the directory `capstone` directory already exists (with contents), it'll have been initialised by the git submodules. No need for any cloning.
  - if the `capstone` directory doesn't exist: do a `git clone` using the url from `.gitmodules`. That'll be part of the zip file as well.

**Comment by Maijin** [comment]
I think there are more issues than this, @radare can provide more insight on what are the problem with git submodules

**Comment by sjvs** [comment]
Alternative: rather than doing a `git clone` to fetch in a particular `capstone` revision, you could do a simple `wget` which (I think) should work with LGTM. E.g.:

`wget https://github.com/aquynh/capstone/archive/970df19f6e6eca5d86f0deea84005ed6ff8a97a1.zip`

(where `970df19.....zip` is the SHA of the revision you need)

**Comment by XVilka** [comment]
So, @radare @ret2libc @xarkes so what do you think about optionally wget capstone as a configure/meson option

**Comment by radare** [comment]
wget wat if there's no release

**Comment by XVilka** [comment]
@radare not a release, just zipped commit.

**Comment by radare** [comment]
how do y ou get a zipped commit from github without a tag?

**Comment by radare** [comment]
oh nice. sounds like an option, but when i do ./configure ; make it pisses me a bit to have an wget in the middle because it breaks the trustness of origin, thats why package managers exist and why releases are useful for..

**Comment by Maijin** [comment]
Please see my comment on sub-tree here https://github.com/radare/radare2/issues/11730#issuecomment-427764425

**Comment by XVilka** [comment]
@radare it wont change any time soon. Neither capstone nor LGTM. So the only option is to either wget or nothing here.

**Comment by XVilka** [comment]
@ret2libc what do you think?

**Comment by ret2libc** [comment]
It seems reasonable to have LGTM, though as always then it's a matter of how many people will look at those warnings. We already have coverity for example...

WRT sub-modules/sub-tree/etc. that's an ongoing discussion for so long :) I'm ok with both sub-modules and sub-trees.

**Comment by XVilka** [comment]
@ret2libc no, I meant maybe we should just introduce a condition, that enabled set a capstone downloads as a zip archive, rather than through git fetch.

LGTM warnings are different from Coverity (for now is offline, I will restore the builds ASAP).

**Comment by Maijin** [comment]
@XVilka  -  #11730

**Comment by ret2libc** [comment]
I'm against other workarounds when we could just use subtrees (or even submodules, if it wasn't for GH problems)

**Comment by XVilka** [comment]
@ret2libc subtree or submodules might not happen for 3 more years, while workaround can be done in less than one day.

**Comment by ret2libc** [comment]
Is this done?

**Comment by XVilka** [comment]
Yes, thanks!
