### ISSUE TITLE
latest 2.6.0 release fails to build

### ISSUE THREAD

**Issue by david-geiger** [radare/radare2#10159]
Hi,

I tried on Mageia Cauldron to build latest 2.6.0 release but this one fails to build, see:

> gcc -fvisibility=hidden  -shared -dynamiclib -o libr.so  \
	.libr/*.o \
	../shlr/gdb/lib/libgdbr.a ../shlr/java/libr_java.a \
	../shlr/zip/librz.a \
	../shlr/libr_shlr.a ../shlr/ar/libr_ar.a ../shlr/grub/libgrubfs.a ../shlr/windbg/libr_windbg.a ../shlr/qnx/lib/libqnxr.a ../shlr/bochs/lib/libbochs.a -lcapstone
gcc: error: ../shlr/zip/librz.a: No such file or directory
make[3]: *** [Makefile:94: libr.so] Error 1
make[3]: Leaving directory '/home/iurt/rpmbuild/BUILD/radare2-2.6.0/libr'
make[2]: *** [Makefile:105: libr.so] Error 2
make[1]: *** [Makefile:37: all] Error 2
make: *** [Makefile:59: all] Error 2
error: Bad exit status from /home/iurt/rpmbuild/tmp/rpm-tmp.2Aifyn (%build)

http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20180522134555.daviddavid.duvel.419/log/radare2-2.6.0-1.mga7/build.0.20180522134606.log

This seems similar as https://github.com/radare/radare2/pull/10153

**Comment by david-geiger** [comment]
Note that I already apply a patch from #10153 

http://svnweb.mageia.org/packages/cauldron/radare2/current/SOURCES/radare2-2.6.0-fix-for-build-with-syscapstone.patch?view=markup&pathrev=1231516

And also this patch is needed to link with system libmagic:

http://svnweb.mageia.org/packages/cauldron/radare2/current/SOURCES/0001-fix-FTBFS-for-as-needed.patch?view=markup&pathrev=1230585

**Comment by radare** [comment]
@david-geiger HELLO?

**Comment by radare** [comment]
nvm its merged, closing until someone else complains again
