### ISSUE TITLE
Dietline missing support for word boundaries

### ISSUE THREAD

**Issue by mcd1992** [radare/radare2#10161]
In a default readline setup (emacs mode) any shortcuts that affect words will treat anything non-alphanumeric as the boundary. In radare2's dietline it treats whitespace as the only word boundary.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux AMD64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 18090 @ linux-x86-64 git.2.5.0-271-gcd6416667 commit: cd6416667efe538aeb8d14c66cede179aff864ee build: 2018-05-16__08:48:13

### Expected behavior
In a bash terminal type out something with slashes or  periods.
`echo cd /test/directory/file.txt`
Hitting meta+b or meta+backspace will move/delete up to the periods or slashes

```
backward-word (M-b)
Move back to the start of the current or previous word. Words are composed of letters and digits.
```

### Actual behavior
In radare2 the meta+b / meta+backspace will move/delete up to the last whitespace character.

**Comment by XVilka** [comment]
@cyanpencil could you please add it to the list?

**Comment by mcd1992** [comment]
I was working on implementing it and figured out my initial thoughts aren't fully correct. The dietline has support for readline style word separation but there seems to be a bug somewhere thats causing it to only break on whitespace. Planning to dig into it more tomorrow.

**Comment by cyanpencil** [comment]
@mcd1992 thanks for trying to fix this yourself!
But keep us updated, if you can't find the time to work on this let me know and I'll look into it.

**Comment by mcd1992** [comment]
So digging into it more, its kinda complicated whats doing what. 

In vanilla readline the `rl_unix_word_rubout` function (ctrl+w) is operating based on whitespace only `#define whitespace(c) (((c) == ' ') || ((c) == '\t'))
` which is what is being done in dietline but only for space and not tab.

The meta+f|b cases in dietline aren't using the word detection functions defined and instead are just checking for a space character whereas readline's `rl_forward_word` checks for anything non-alphanumeric as a seperator `_rl_walphabetic`. (The function is called walphabetic but it checks for alphabetical, numerical, and `pathname_alphabetic_chars = "/-_=~.#$"`)

So its feasable to fix and make dietline more readline-like, but I'm wondering why bother. Is there a reason why we don't just dynlink the system readline or static link against a compiled version of readline in shlr for systems without it?

**Comment by radare** [comment]
Readline is 20k LOC. Its quite huge. And its not available on all systems. R2 only depends on libc,thats why i implemented my own tiny implementation. Feel free to fix it and submit a pr

**Comment by mcd1992** [comment]
Makes sense. I started to fix up dietline to have the more readline-like word actions, I'll create a PR for that and later on see if there's a decent way to get readline working with just a libc requirement.

**Comment by radare** [comment]
There was a —with-readline working at some point

**Comment by XVilka** [comment]
@mcd1992 @cyanpencil see also this https://github.com/radare/radare2/issues/9269
