### ISSUE TITLE
Compact references in graph mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10165]
Some nodes can get enormous amount of code or data references.
We need to think on more compact form of representing them, folding or cutting them, or even just hiding them.
![screenshot_20180523_145559](https://user-images.githubusercontent.com/203261/40408408-00767cac-5e9a-11e8-80b1-810d50329b53.png)

**Comment by radare** [comment]
this should be fixed, the idea of maxrefs is to show them like they are by default unless there are more than X in there, in that case then just show the counter

**Comment by cyanpencil** [comment]
@XVilka do you think that fixing `asm.maxrefs` would solve this issue? (see screenshots above)

**Comment by XVilka** [comment]
Yes. I do think so.

**Comment by cyanpencil** [comment]
Ok, I'll work on this then
