### ISSUE TITLE
agj prints graphs for every single function when run at offset 0

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#10162]
### Expected behavior
agj should behave at offset 0 like everywhere else: print the graph of a function at the current offset if there is any.

### Actual behavior
The graph for every single existing function is printed in the json array, which can take forever for a higher number of functions.

### Steps to reproduce the behavior 
- Open /bin/ls for example
- `aaa`
- `agj@0` or even worse: `agJ@0`

### Reason/Fix
Cause is here:
https://github.com/radare/radare2/blob/6da28493f5c186cc7f4b7413b66ca13042602060/libr/core/canal.c#L2700-L2786
`addr == 0` is used as the condition for whether to print at addr or to print between `graph.from` and `graph.to`. This is bad imo, because you could very well have a function at 0. Also in Cutter, it can freeze the UI for minutes if you just seek to 0.

I would suggest to either use `addr == RVA_MAX` as the condition or (as I would prefer) add another bit to the opts parameter. The only remaining question is: How do we then expose the `graph.from`/`graph.to` functionality to the user? Additional commands maybe?

**Comment by radare** [comment]
Theres already an issue for this and its been addressed by @cyanpencil

**Comment by thestr4ng3r** [comment]
I see, then this is a duplicate of https://github.com/radare/radare2/issues/9716
