### ISSUE TITLE
pdf and pdfj differ

### ISSUE THREAD

**Issue by Toizi** [radare/radare2#10170]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18269 @ linux-x86-64 git.2.6.0-24-g36a3fa5 commit: 36a3fa526a964b5c076852ab2ab5a1813133a463 build: 2018-05-23__17:03:45

### Expected behavior
```
r2 fla_test_opt.elf
s main; af
pdf
...
│      ││   0x004005c6      5b             pop rbx
│      ││   0x004005c7      5d             pop rbp
│      ││   0x004005c8      c3             ret
...
pdfj~{} | grep ret
"opcode": "ret",
"disasm": "ret",
```
### Actual behavior
```
r2 fla_test_opt.elf
s main; af
pdf
...
│      ││   0x004005c6      5b             pop rbx
│      ││   0x004005c7      5d             pop rbp
│      ││   0x004005c8      c3             ret
...
pdfj~{} | grep ret

```

### Steps to reproduce the behavior
Binary: [fla_test_opt.zip](https://github.com/radare/radare2/files/2031676/fla_test_opt.zip)

Binary is compiled with o-llvm 4 using the flattening pass.
Also notice how the size of the function is wrong.
```
(fcn) main 126
?X 0x00400540 + 126
4005be
```
This is most likely why pdf and pdfj differ, since the last opcode from pdf is at `0x004005d0`, which is greater than fcn + size

**Comment by Toizi** [comment]
Some additional info:
The function contains alignment bytes directly between regular opcodes. This most likely leads to the discrepancy between reported size and linear size.
The `ops` from `pdfj` contain the correct `fcn_last` address of `0x4005d1`, so the size is being detected correctly. From a quick look at the `pdfj` code, it seems like it tries to use the linear/contiguous size (calling `tmp_get_contsize`) but it ends up returning 126 in this case, i.e. the real size. `pdf` on the other hand uses `f->_size`, which seems to be the linear size.

**Comment by radare** [comment]
Can you do a PR?

**Comment by XVilka** [comment]
Please also make a regression test for this one.

**Comment by sivaramaaa** [comment]
@Toizi  add the test under `new/db/cmd/cmd_pd` , so that we can close this issue !
