### ISSUE TITLE
Unable to Properly Install R2

### ISSUE THREAD

**Issue by takuter** [radare/radare2#10172]
I am running Ubunutu 16.04 32-bit and trying to install R2 but it keeps running into an error before it finishes

Full Log here: https://pastebin.com/e8Xw6KPs

This is the erroror problems it gives at the end 
Makefile:88: recipe for target 'libr.so' failed
Makefile: 100: recipe for target 'libr.so' failed
Makefile:28: recipe for target 'all' failed
Makefile:55: recipe for target 'all' failed

I have tried resetting my VM and installing again, always pulling from the github and doing sys/install.sh but it keeps popping up with this error. How can I fix this?

**Comment by radare** [comment]
Can anyone reproduce?

**Comment by datafanatic** [comment]
I'm getting the same problem. 
System information: Linux debian 4.9.0-6-686 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) i686 GNU/Linux
GCC:  Using built-in specs. gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
Make: GNU Make 4.1

Running in a VM with Virtual Box.

I'm currently with a very bad connection so I can't seem to be able to post the logs to pastebin, but it's pretty much the same as the OP, with the exception that I also get this:

`__x86.get_pc_thunk.bx' referenced in section `.text' of .libr/libr_util.o: defined in discarded section `.text.__x86.get_pc_thunk.bx[__x86.get_pc_thunk.bx]' of .libr/libr_util.o

A couple thousand times before 
Makefile:88: recipe for target 'libr.so' failed
make[3]: *** [libr.so] Error 1
Makefile:100: recipe for target 'libr.so' failed
make[2]: *** [libr.so] Error 2
Makefile:28: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:55: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by radare** [comment]
should be fixed in master. merged libr is not build by default now

**Comment by datafanatic** [comment]
Apologies about the delayed response. I just cloned the repository and attempted to install it, and it works fine. Thanks a lot.
