### ISSUE TITLE
Failed to write instruction (ELF 32bit ARM shared library)

### ISSUE THREAD

**Issue by MaxXor** [radare/radare2#10182]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF 32-bit LSB shared object ARM, EABI5 version 1 (SYSV), dynamically linked
| Architecture/bits of the file (mandatory)            | ARM 32bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0 0 @ linux-x86-64 git.2.6.0 commit: HEAD build: 2018-05-23__01:38:10

### Expected behavior
`Successful write`

### Actual behavior
`Failed to write`

### Steps to reproduce the behavior 
- Open ELF 32bit ARM shared library
- Try to change an instruction with `wa mov r0, 1`
- I can provide the library if needed in private

**Comment by radare** [comment]
Did you opened qith -w? Did you tried with rasm2?

**Comment by MaxXor** [comment]
It's also not working when I start radare2 with `r2 -A -w <file>`... I'm sure it worked before with ARM 32bit files as I've did it before. Never used rasm2.

**Comment by MaxXor** [comment]
I've tested patching files with files of other architectures and it seems to be working. Only ARM seems to be affected.

**Comment by MaxXor** [comment]
I've digged a little bit into this issue and I found out that the writing of ARM instructions is working in radare version 2.3.0.

**Comment by sivaramaaa** [comment]
@MaxXor , @radare i think i found the issue here !

#### With Analysis (not working)
```
$ r2 -A -w arm-bin
[x] Analyze all flags starting with sym. and entry0 (aa)
...
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[0x00014348]> wa mov r0, 1
Failed to write
```

#### Without analysis (Works fine)

```
$ r2  -w arm-bin
[0x00014348]> wa mov r0, 1
Written 4 byte(s) (mov r0, 1) = wx 0100a0e3

[0x00014348]> pd 1
0x00014348      0100a0e3       mov r0, 1
```

**Comment by radare** [comment]
cant repro on mach0-x86-64

**Comment by radare** [comment]
in fact i cant repro on elf-arm binary either, can you share this bin? or try again?

**Comment by MaxXor** [comment]
I've tested again with latest commit https://github.com/radare/radare2/commit/e3d11b989c869f8f0c9ba89b1e2292dc0a6491b8 and now when I run `r2 -A -w arm-bin` I get a segmentation fault. Will send you the binary later via mail.

**Comment by radare** [comment]
wtf? which version of r2 do you have? do u have more than one r2 installed? see r2 -V

**Comment by MaxXor** [comment]
I tested with radare2 2.6.0 release build as you can read in the first post of this issue and now tried again by compiling it from the latest commit where I get the segmentation fault at the end of the analysis.

**Comment by radare** [comment]
test against git, we dont fix bugs in releases

**Comment by radare** [comment]
can you share the binary?

**Comment by MaxXor** [comment]
Sent you the library on the mail mentioned on your github profile.

**Comment by radare** [comment]
works perfectly fine, the problem is in your installation, run `make purge` to remove all installations or messy files from old r2 setups and then `sys/install.sh`

**Comment by MaxXor** [comment]
You are right, just tested the latest commit in a clean environment & it's working again.
