### ISSUE TITLE
The output of 'rax2 -s' is not wrapped

### ISSUE THREAD

**Issue by gh0stZerO** [radare/radare2#10186]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0 0 @ darwin-x86-64 git.2.6.0 commit: HEAD build: 2018-05-25__23:38:17

### Expected behavior
```sh
$ rax2 -s 414243
ABC
$
```
### Actual behavior
```sh
$ rax2 -s 414243
ABC$
```

**Comment by radare** [comment]
Not sure if expected. That will add a newline at the end so the output will not match the input data

**Comment by sivaramaaa** [comment]
Yup , if u want a newline u can  use `rax2 -s 4142430a`

If u have any particular use-case share with us and we shall think, for now closing the issue!
