### ISSUE TITLE
arm64: offset of tbz and tbnz instructions wrongly disassembled if negative

### ISSUE THREAD

**Issue by Siguza** [radare/radare2#10197]
Not sure if this issue is part of #8087, please excuse if it is.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.12.6 (16G1314), x86_64h
| File format of the file you reverse (mandatory)      | Raw
| Architecture/bits of the file (mandatory)            | arm64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18197 @ darwin-x86-64 git.2.6.0-43-gf7c43fcfa commit: f7c43fcfad3567fc8f992e468cdbe88d362d5371 build: 2018-05-26__15:09:23

### Actual behavior

Consider the following hexdump of raw arm64 machine code (also attached as binary file):

    000040B4 000080B4 000040B5 000080B5 000002B6 000004B6 000002B7 000004B7

Using `r2 -aarm -b64 -m 0x100000000 -c 'pd 8' a`, this disassembles to:

        ,=====< 0x100000000      000040b4       cbz x0, 0x100080000
        |  :`=< 0x100000004      000080b4       cbz x0, 0xfff00004
        |  :,=< 0x100000008      000040b5       cbnz x0, 0x100080008
        |  `==< 0x10000000c      000080b5       cbnz x0, 0xfff0000c
        |  ,==< 0x100000010      000002b6       tbz x0, 0x20, 0x100004010
        | ,===< 0x100000014      000004b6       tbz x0, 0x20, 0x4ffff8014
        | ,===< 0x100000018      000002b7       tbnz x0, 0x20, 0x100004018
        |,====< 0x10000001c      000004b7       tbnz x0, 0x20, 0x4ffff801c

Each instruction is present twice, first with an offset which has nothing but the second-highest bit set (i.e. positive), and second with an offset that has nothing but the highest bit set (i.e. negative).

### Expected behavior

I'd expect the second `tbz` and `tbnz` instructions to resolve to `0xffff8014` and `0xffff801c` rather than `0x4ffff8014` and `0x4ffff801c`, respectively. It seems that, somehow when the highest bit in the offset is set, the resulting address gets an `0x400000000` OR-ed into it.

### Sample binary

[a.zip](https://github.com/radare/radare2/files/2041903/a.zip)

**Comment by radare** [comment]
This is a bug in capstone. Not r2

**Comment by radare** [comment]
can you try again with latest r2 from master and add a test in r2r repo?

**Comment by radare** [comment]
HELLO?

**Comment by radare** [comment]
so the bug is not fixed yet. capstone fault
```
    ╭─────< 0x100000000      000040b4       cbz x0, 0x100080000
    │  ⋮╰─< 0x100000004      000080b4       cbz x0, 0xfff00004
    │  ⋮╭─< 0x100000008      000040b5       cbnz x0, 0x100080008
    │  ╰──< 0x10000000c      000080b5       cbnz x0, 0xfff0000c
    │  ╭──< 0x100000010      000002b6       tbz x0, 0x20, 0x100004010
    │ ╭───< 0x100000014      000004b6       tbz x0, 0x20, 0x4ffff8014
    │ ╭───< 0x100000018      000002b7       tbnz x0, 0x20, 0x100004018
    │╭────< 0x10000001c      000004b7       tbnz x0, 0x20, 0x4ffff801c
```

**Comment by Siguza** [comment]
Done, hope I put the files in appropriate enough directories.

**Comment by radare** [comment]
as i said, this is a bug in capstone. so let's continue the discussion in there https://github.com/aquynh/capstone/issues/1144

**Comment by radare** [comment]
i would close the issue here because it's a capstone bug, not in r2

**Comment by mrmacete** [comment]
now fixed in capstone: https://github.com/aquynh/capstone/pull/1213
