### ISSUE TITLE
Can only paste 1 character of text into radare2 on Windows

### ISSUE THREAD

**Issue by riverar** [radare/radare2#10198]
### Environment

Windows 10 x64 17134.48
radare2 2.7.0-git 18226 @ windows-x86-32 git.2.6.0-41-g7965a7737
commit: 7965a77373f72f532db8ad2673a6ee1c3a0397e7 build: Fri 05/25/2018__13:59:23.19

### Expected behavior

Full paste support, supported by the console host

### Actual behavior

All data is lost, except for the last character in the buffer.

### Steps to reproduce the behavior 
- `radare2 -`
- Copy some sample text into the clipboard and paste it into the console via right-click, or other method. (`CTRL+V` works but is unnatural in this environment.)
- Note only the last character makes it

(e.g. pasted in `testing one two three`)
![image](https://user-images.githubusercontent.com/475132/40582352-5ae2212e-6128-11e8-89f0-e82aa9dd035f.png)

NOTE: Happens regardless of legacy/new console host.

---

@WithinRafael in the radare2 Telegram group, if you need to chat.

**Comment by XVilka** [comment]
This bug looks familiar.

**Comment by XVilka** [comment]
Looks like https://github.com/radare/radare2/issues/3936 strikes again.

**Comment by radare** [comment]
Use ^C and ^V. that works fine. the problem is when you use the mouse beacuse that sends events to r2 and results in that missbehaviour. @skuater may have a look at this

**Comment by skuater** [comment]
problem solved ;)

**Comment by radare** [comment]
🤘

**Comment by riverar** [comment]
Can confirm working here on latest `master`. Thanks!
