### ISSUE TITLE
x86 Instruction not correctly assembled

### ISSUE THREAD

**Issue by MaxXor** [radare/radare2#10195]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF 32-bit LSB pie executable Intel 80386, version 1 (SYSV), dynamically linked,
| Architecture/bits of the file (mandatory)            | x86 32-bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0 0 @ linux-x86-64 git.2.6.0 commit: HEAD build: 2018-05-23__01:38:10

### Expected behavior
`Written 5 byte(s) (rol byte [edi + ecx -1], 5) = wx c0440fff05`

### Actual behavior
`Written 3 byte(s) (rol byte [edi + ecx -1], 5) = wx c00705`

### Steps to reproduce the behavior 
- Open ELF 32-bit binary
- Try to write instruction `wa rol byte [edi + ecx - 1], 5`

**Comment by radare** [comment]
I have fixed this. but errors are not handled properly yet.

```
rasm2 -b32 'rol byte [eai + ecx -1], 5'
ff05
```
