### ISSUE TITLE
Rabin2 invalid json output on Windows

### ISSUE THREAD

**Issue by wavvs** [radare/radare2#10207]
### Actual behavior
For example, run `rabin2 -e -j <binary>`
Output:
`}{"entries":[{"vaddr":4201661,"paddr":4285,"baddr":4194304,"laddr":0,"haddr":264,"type":"program"}]`
Works fine on Linux.

Don't know much internals, but maybe problem is here, r_cons_print instead printf?
https://github.com/radare/radare2/blob/bb4f61580e75778a9b5999127163dcd9d5d2e7b3/binr/rabin2/rabin2.c#L1113

**Comment by radare** [comment]
yes this is a problem, not sure if there are more, im closing this until you provide a way to reproduce or you confirm the fix. Next time you can try sending a pullreq, it's just pressing the pencil button in github, no need to touch the console or use git at all
