### ISSUE TITLE
Paths with parentheses can't be accepted in LDFLAGS

### ISSUE THREAD

**Issue by wavvs** [radare/radare2#10214]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10

### Actual behavior
I tried build with sys/msvc.bat.
For example
![image](https://user-images.githubusercontent.com/30052411/40626694-dd3fdb98-62c2-11e8-9549-13a05cda1abf.png)
https://github.com/radare/radare2/blob/452f1ae3db8f3f5ac1137992b141095d9c723b31/shlr/tcc/Makefile#L48

Maybe solution is escape parentheses in LDFLAGS somehow?
Also I had some troubles with CLRF in files, then I saved files with LF and it worked.

**Comment by XVilka** [comment]
For CRLF - just use conversion when perform checkout.

**Comment by radare** [comment]
FUCK WINDOWS, parenthesis in the paths is even more evil than spaces

**Comment by wavvs** [comment]
@radare ping? How to build with linux then? Readme in repo outdated :(

**Comment by radare** [comment]
Did you tried with meson?

**Comment by wavvs** [comment]
@radare Another sh*t happens 
![image](https://user-images.githubusercontent.com/30052411/40749119-a3f5e3fa-646b-11e8-9aea-075d4fa89fd9.png)

**Comment by radare** [comment]
dont you have sys/time.h in your machine?

ive pushed a fix for this , please git pull and confirm the fix

**Comment by wavvs** [comment]
don't have sys/time on win 10, tried with mingw, but now cfgmgr32.h missing, aaaa

**Comment by radare** [comment]
how are you building r2 exactly? we have different machines building every single commit of r2 on windows without any issue

**Comment by riverar** [comment]
Builds great here on Windows with meson; sounds like a local issue.
Parentheses and spaces are supported in environment variables.

**Comment by XVilka** [comment]
@wavvs is this issue still reproducible?

**Comment by radare** [comment]
Probably, because nobody fixed it

**Comment by wavvs** [comment]
@XVilka Can't check right now, I'll try to build as soon as possible. But I guess that it is still present.

**Comment by riverar** [comment]
@radare @XVilka @wavvs I tested this with no issue back in August, I would just close this?
