### ISSUE TITLE
map raw files with offset/size

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#10228]
Hello.
I dont know, may be I do something wrong, but I didnt find anything way to open file with offset like this:
`o memdump.dmp 0xBASE 0xOFFSET 0xSIZE`

Problem.
I have physical memory dump. I make dump virtual memory of some process through **volatility**.
But volatility dont support minidump/corefile format and dump all pages one by one. Also **volatility** takes memmap - virtual pages index file.
It was very good, if r2 support load parts of raw memory file like a:
`o memdump.dmp 0xBASE 0xOFFSET 0xSIZE`
As rule process has thousand of virtual memory pages (100k in my example) and I need to create on file for each one. But it is a huge load for a filesystem...

| OS/arch/bits (mandatory)                             | Linux kali 4.6.0-kali1-amd64
| File format of the file you reverse (mandatory)      | blob
| Architecture/bits of the file (mandatory)            | x86/32
radare2 2.6.0-git 17895 @ linux-x86-64 git.2.5.0-24-g7b2752880
commit: 7b27528807b5d6ecfac6ef9d0498a8eefbabb31d build: 2018-04-13__23:29:57

### Expected behavior
I want to load many memory pages from one file.

### Steps to reproduce the behavior 
volatility -f physical_mem.dmp memmap -p PID > memmap.txt
volatility -f physical_mem.dmp memdump -p PID > memdump.dmp
r2 -
o memdump.dmp 0x401000 0 4096
o memdump.dmp 0x402000 4096 10000
...

**Comment by radare** [comment]
open != map

use om to map anything anywhere, open the file with ‘o’ and no arguments, and then create the maps on top of that fd

**Comment by s0i37** [comment]
```
o ./process_memdump.dmp
om 4 0x401000 0x1000 0x21000
```
Its seems work! Great. Thank you.
