### ISSUE TITLE
[JSON output] Incorrect output from pdfj

### ISSUE THREAD

**Issue by redmed666** [radare/radare2#10223]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18238 @ darwin-x86-64 git.2.4.0-706-g9539d3219 commit: 9539d32193e5436db03fde1dd7f19c5c04ac8387 build: 2018-05-30__10:05:10

### Expected behavior
`pdfj @ <offset>` should give a correct JSON

### Actual behavior
['ops'] field is malformed.
Example:
`{"name":"fcn.eip","size":16407,"addr":4199468,"ops":[,{"offset":4199468, <output truncated>`

As you can see, there is a "," just before the first ops which leads to an incorrect JSON object.

### Steps to reproduce the behavior
By replacing '/path/to/binary' and offset by your values in this snippet: 
```python
r2p = r2pipe.open('/path/to/binary')
r2p.cmd('af @ {0}'.format(offset))
r2p.cmdj('pdfj @ {0}'.format(offset))
```
you should receive an error from r2pipe.

**Comment by redmed666** [comment]
Found the issue:
in libr/core/cmd_print.c, one condition is messed up in line 4267:
```c
					r_list_foreach (f->bbs, locs_it, b) {
						if (!first) {
							first = false;
						} else {
							r_cons_print (",");
						}
                                                  //...
                                          }
```
It should not be !first but first.
I will prepare a commit for that :)

**Comment by redmed666** [comment]
Pull request created: #10225

**Comment by redmed666** [comment]
Another incorrect output in ops:
`"bytes":"e995850000","family":"cpu","type":"jmp","type_num":1,"type2_num":0,"jump":6022720},,,{"offset":6022720,`
As you can see, there are 3 times ',' but should have only 1

**Comment by radare** [comment]
can you send another pr fixing this and add tests cases to avoid this thing ot happen again?
