### ISSUE TITLE
Add backtrace information to dbtj

### ISSUE THREAD

**Issue by fcasal** [radare/radare2#10227]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | 16.04.1 Ubuntu x86_64
| File format of the file you reverse      |  -
| Architecture/bits of the file            | -
| r2 -v          | radare2 2.7.0-git 18421 @ linux-x86-64 git.2.6.0-80-gd5aa66a commit: d5aa66ae8a852a9b652badbaba825000ab8d11fa build: 2018-05-30__12:27:26
| r2 -V | https://gist.github.com/fcasal/75b79f13ad691d3145cdd7b8b1c4b73a

## Observed behaviour
The json version of `dbt` only shows the offsets:

```
$ r2 -d /bin/ls
[0x7fbdf3bf2c30]> dcu main
Continue until 0x00402a00 using 1 bpsize
hit breakpoint at: 402a00
[0x00402a00]> dbt
0  0x402a00           sp: 0x0                 0    [??]  main section_end..plt.got+8
1  0x7fbdf3626830     sp: 0x7ffe8ad8dab8      0    [??]  r11+240 
2  0x4049c9           sp: 0x7ffe8ad8db78      192  [??]  entry0+41
 
[0x00402a00]> dbtj
[4205056,140453808859184,4213193]
```

## Expected behaviour
Include `dbt` data in `dbtj`

**Comment by radare** [comment]
Thats easy to solve. Can you try to send a pr implementing it?

Thanks
