### ISSUE TITLE
m68k instruction differs between screens

### ISSUE THREAD

**Issue by MikeColeGuru** [radare/radare2#10238]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04.1 / amd64 / 64 bits <br>running under VMWare Player 12.5.9 build-7535481
| File format of the file you reverse (mandatory)      | reconstructed 
| Architecture/bits of the file (mandatory)            | m68k/16 bits
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18273 @ linux-x86-64 git.2.6.0-111-gcd043ac<br>commit: cd043ac676a8ef71a415ea31bc03b7bd1de0007e build: 2018-06-01__07:11:50

### Expected behavior

To show the same instruction in the function viewer as in visual disassembly
<CODE>bhi.w 0x623a8</CODE>

### Actual behavior

It shows a different address when viewing function
<CODE>bhi.w 0x62332</CODE>

### Steps to reproduce the behavior 
[memorydump.zip](https://github.com/radare/radare2/files/2062758/memorydump.zip)

<pre>
$ r2 -n -a m68k -b 16 ./memory.dump
[0x00000000]> e asm.cpu=68040
[0x00000000]> s 0x62330
[0x00062330]> aaa

Note: many block size warnings.. I have tried to change the block size to no aval

[ WARNING : block size exceeding max block size at 0x0000000e
[+] Try changing it with e anal.bb.maxsize

[0x00062330]> v
p
Note: you can see the first instruction is bhi.w 0x623a8
v
Note: you will see the first instruction is now bhi.w 0x62332
</pre>

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

![visual1](https://user-images.githubusercontent.com/19918682/40842509-b8abb65e-6573-11e8-817f-d7ab6eef7073.png)

![visual2](https://user-images.githubusercontent.com/19918682/40842513-be06f1c2-6573-11e8-8c28-e53d021ef9b7.png)

**Comment by radare** [comment]
cant reproduce

**Comment by MikeColeGuru** [comment]
Let me know how else I can help.

**Comment by MikeColeGuru** [comment]
I decided to try it on another system outside of a VM

radare2 2.7.0-git 18274 @ linux-x86-64 git.2.6.0-112-gf4973a9
commit: f4973a93d410705652205a6863cdcd46a154cc81 build: 2018-06-01__21:52:58

At first, it didn't show any function at all

![function-not-showing](https://user-images.githubusercontent.com/19918682/40869813-1a920490-65e7-11e8-9ee9-611e4834bc68.png)

Then I resized the window and the function appeared but with the same issue with addresses

![function-expanded-showing](https://user-images.githubusercontent.com/19918682/40869817-490c0c58-65e7-11e8-886d-bf42d0f29255.png)

What are you seeing @radare ?

**Comment by MikeColeGuru** [comment]
I'm sure this is correct either.  Look at the jump and fail.

<pre>
[0x00062330]> ao
address: 0x62330
opcode: bhi.w 0x623a8
mnemonic: bhi.w
prefix: 0
id: 13
bytes: 62000076
val: 0x00000000
ptr: 0x00000000
refptr: 0
size: 4
type: cjmp
jump: 0x00000000
fail: 0x00062332
stack: null
cond: al
family: cpu
stackop: null
</pre>

**Comment by radare** [comment]
Thats wrong. But i dont know if the bug is in r2 or capstone. Do you want to try to fix this bug?

**Comment by MikeColeGuru** [comment]
I will certainly look into it further and see if I can find the bug

**Comment by radare** [comment]
the bug was in r2. i have fixed some of those isntructions but we need to do the same for all the other instructions.

https://github.com/radare/radare2/commit/1f903954a650b117546c1b4b3dd1340bdd131308

if you want to contribute on this, check out this commit and send a PR improving the analysis information for the rest of m68k instructions

Thanks!
