### ISSUE TITLE
structs fields detect

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#10248]
Hello.
I have simple program with simple structure like this:
```
struct Test {
  int a;
  char b;
  char *c;
};
void main(void){
  test.a = 6;
  test.b = 'A';
  test.c = "test\n";
```
After link this struct r2 dont recognize it fields:

![r2_wtf](https://user-images.githubusercontent.com/22872513/40887952-b7920064-6769-11e8-8738-89a222b9f9bf.png)

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u1 (2017-06-18) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18327 @ linux-x86-64 git.2.6.0-32-g3c8d7d5
commit: 3c8d7d53fa5cb438f7462ff2403b4dfe4d33ddef build: 2018-06-03__19:49:36

### Expected behavior
I expected that r2 recognize struct fields like a "afvt" for vars.

### Actual behavior
r2 dont recognize fieldf of struct

### Steps to reproduce the behavior 
to test.h
tl Test obj.test

**Comment by radare** [comment]
this is not done yet. that’s why its not working. @sivaranamaa is working on this in the GSoC

**Comment by s0i37** [comment]
Ok. Good luck)

**Comment by sivaramaaa** [comment]
@s0i37 hey hi sorry for the delayed replay , recently i have fixed few issues in struct offset propagation , so hopefully it should work for u now 

Steps to be taken :
```
[0x000005fa]> aaa
[0x000005fa]> to test.h
[0x000005fa]> tl Test = address
```
It would be great if u have a look at it and give me feedback , if there is any issue i could re-open the issue and fix it :)

**Comment by s0i37** [comment]
Very good! But... I notice some strange behavior:
if I make:
```
to test.h
tl Test = obj.test
```
All right. 
But if I make (leave function scope during linking type):
```
to test.h
s obj.test
tl Test = obj.test
s-
```
then fields of a type will not recognize.

**Comment by sivaramaaa** [comment]
Thanks for the feedback , can u share the binary file here , so that i can take a look at it !

**Comment by sivaramaaa** [comment]
@s0i37 actually `tl` command  only propagates  struct fields at function present at current offset 
If u want to detect struct field outside function , then u have to use `taa` command : 
```
[0x000005fa]> aaa
[0x000005fa]> to test.h
[0x000005fa]> s obj.test
[0x8049704]>  tl Test = obj.test
[0x8049704]> taa fnc-addr or taa (command to propgate struct feild explicitly)
[0x8049704]> s-
```

**Comment by sivaramaaa** [comment]
Yup looks like an issue, hence re-opening this , i would take a look at it !

**Comment by sivaramaaa** [comment]
Hey hi , i have a few changes and submitted a PR , u could test this once it's merged 

```
|           0x0000058d      53             push ebx
|           0x0000058e      51             push ecx
|           0x0000058f      83ec10         sub esp, 0x10
|           0x00000592      e85d000000     call sym.__x86.get_pc_thunk.ax
|           0x00000597      05691a0000     add eax, 0x1a69
|           0x0000059c      8d9020000000   lea edx, [eax + 0x20]       ; "\\x18"
|           0x000005a2      8955f4         mov dword [local_ch], edx

```


Steps to be taken :
 
```
[0x00000580]> aa
[0x00000580]> s main
[0x00000580]> "td struct Test { int a; int  b; char *c;};"
[0x00000580]> ahr 0x00000597 @ 0x00000592 (setting hint for return value)
[0x00000580]> tl Test = 0x00002020
```
The important thing here is using ahr command ,

`ahr return-value @ func-call-addr`

 since emulating a call instruction is atm not possible u have to set return value of that function call manually as a hint so that we could use it to porpagate struct offset properly !

**Comment by sivaramaaa** [comment]
Ping @s0i37 , My PR has been merged u can try the above steps to solve the issue !

**Comment by s0i37** [comment]
Yes. Sorry for my long time answer. Now it is working well.
Thank you!
