### ISSUE TITLE
Compact xrefs

### ISSUE THREAD

**Issue by radare** [radare/radare2#10253]
```
[0x10000443a]> pdf
╭ (fcn) sym.imp.__error 6
│   sym.imp.__error ();
│           ; CALL XREF from 0x100001da0 (sym.func.100001b44 + 604)
│           ; CALL XREF from 0x100001db0 (sym.func.100001b44 + 620)
│           ; CALL XREF from 0x100001db8 (sym.func.100001b44 + 628)
│           ; CALL XREF from 0x100002eaa (sym.func.100002aad + 1021)
╰           0x10000443a      ff25080c0000   jmp qword [0x100005048]    ; [0x100005048:8]=0x10000464e
[0x10000443a]>
```

in this example we can find that there are 2 function xrefs, one of them with 3 xrefs.

we can compact the xrefs in verbose mode if we use a syntax like this:

```
; CALL XREF from sym.func.0x100001b44 (..1da0, ..1db0, ..2eaa)
; CALL XREF from sym.func.100002aad (0x100002eaa)
```

maybe its more readable?

pls discuss

**Comment by radare** [comment]
cc @cyanpencil

**Comment by XVilka** [comment]
Certainly agree,

**Comment by cyanpencil** [comment]
I agree too, I have only some doubts on the ellipsis representation `(..1da0, ..1db0, ..2eaa)`, 
because I'm very used to select an address with the mouse by double clicking and pasting, maybe I would prefer like this `(0x100001da0, 0x100001db0, 0x1000012eaa)`,
but those are only my two cents...

**Comment by XVilka** [comment]
I think if we do `; CALL XREF from sym.func.0x100001b44 (+44, +56, +b0, +ea)` it may save us more space. But it is harder to calculate for a human... So I am not sure.

**Comment by radare** [comment]
yes i also prefer full address
