### ISSUE TITLE
Failing to do CFG recovery of bf interpreter

### ISSUE THREAD

**Issue by felberj** [radare/radare2#10259]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS HighSierra arm 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18339 @ darwin-x86-64 git.2.6.0-130-ga20078d17
commit: a20078d17137e3bc9930e47c51c4674da3c39f83 build: 2018-06-04__20:29:14

### Expected behavior

the basic block at `0xf34` jumps to `fcn.00001144`, as it is the last instruction of it.

### Actual behavior

The basic block ends there.
### Steps to reproduce the behavior 

- radare2 ./[Echo](https://github.com/radare/radare2/files/2069522/Echo.zip)
- aaa
- s main
- VV
- find the BB in question, there is only one BB between the entry of main and the one in question.

### Additional Logs, screenshots, source-code,  configuration dump, ...

[Echo.zip](https://github.com/radare/radare2/files/2069522/Echo.zip)

**Comment by XVilka** [comment]
Please create a pull request to https://github.com/radare/radare2-regressions with a testcase.

**Comment by felberj** [comment]
Done https://github.com/radare/radare2-regressions/pull/1339

**Comment by radare** [comment]
aab works fine. This issue appears in just “aa”

**Comment by felberj** [comment]
Are you sure? If I modify the test to do "aab" at the beginning, the output stays the same.

**Comment by radare** [comment]
Just do aab. Nothing more. Maybe i checked a different issue in the cfg. But aa was producing bad results indeed. Whwres this bin from? It have some strange constructions

**Comment by felberj** [comment]
The binary is from asictf 2018 and contains a brainfuck interpreter. Just to be sure: You ran the regression test and it passes?

**Comment by felberj** [comment]
Update: You are right, it works. I must have been fixed in the last few days. I will look at it again!

**Comment by felberj** [comment]
Update2: If I do
```
aab
```
it works

if I do

```
aaa
aab
```

it does not work

**Comment by felberj** [comment]
Ok, so I found the next problem:

```
aab
aaa
s 0x00001025
```
It does not handle the `jmp rax`. Should I update the regression test? If so, how (what is the expected output?)?
<img width="251" alt="image" src="https://user-images.githubusercontent.com/6639926/41092113-6b96ba24-6a48-11e8-994e-976d01cf954e.png">

**Comment by radare** [comment]
it should do if you enable anal.jmptbl=true

**Comment by felberj** [comment]
It does not, I just tried it:
```
anal.jmptbl=true
aab
aaa
s 0x00001025
afb.
VV
```

**Comment by radare** [comment]
why did you run aaa after aab? i said to just run aab, nothing more , anyway it’s a bug and must be fixed, also which compiler generated this bin or where it is coming from ? it have some strange constructions

**Comment by felberj** [comment]
> why did you run aaa after aab?

Because I have never used radare2 and have no clue what I am doing. Currently waiting for an r2 developer that is coming to my place to manually analyze this program.

> also which compiler generated this bin or where it is coming from ?

It was a challenge from  ASIS CTF Quals 2018: https://ctftime.org/task/6033

**Comment by felberj** [comment]
I am interested on how I could fix this manually. My idea was to use `afu` to manually resize the function and run the analysis. 
IDA claims that main goes until 0x0001162.
If I try to resize `main` with `afu 0x0001162` the functions between main and  0x0001162 are still there. Any hints how to fix it? Do I need to edit the basic blocks (adding jumps to it?)?

**Comment by radare** [comment]
<img width="1184" alt="screen shot 2018-06-24 at 20 48 41" src="https://user-images.githubusercontent.com/917142/41822447-015ac3c0-77f0-11e8-9253-64909d23ebb9.png">

@cyanpencil ^ can you have a look at this edge layout glitch? (run aaa and then `s 0x1025`)

**Comment by radare** [comment]
I have fixed this analysis bug in this pr https://github.com/radare/radare2/pull/10475

**Comment by ret2libc** [comment]
`| aab                 aab across bin.sections.rx`

The help message is not really helpful to understand what this command does.
