### ISSUE TITLE
Syscall number database is pretty incomplete

### ISSUE THREAD

**Issue by radare** [radare/radare2#1025]
vfork for example is very important and its not handled in all the dbs. we need to write scripts to parse kernel/libc include files to generate an sdb with all the syscall definitions. See `libr/syscall/d/*`.

**Comment by Maijin** [comment]
* [x]  Syscall linux-x86-32
* [x]  Syscall-x86-64

**Comment by Maijin** [comment]
Note to add the 0x10 bios interrupt somewhere

**Comment by XVilka** [comment]
@Maijin You mean for DOS images or for stuff inside the old legacy BIOS images?

**Comment by Maijin** [comment]
@XVilka https://en.wikipedia.org/wiki/BIOS_interrupt_call#Interrupt_table used by MSDOS and bootloader mainly.
And I've used int10 in my first assembly course at UNI.

**Comment by XVilka** [comment]
We need a better summary (task list) for this one.

**Comment by Maijin** [comment]
y
