### ISSUE TITLE
Can't use rarun2 on Fedora

### ISSUE THREAD

**Issue by M3rcurio** [radare/radare2#10262]
Hi,
i've recently updated my version of radare2 but now when i try to use rarun2 it doesn't work. it always prints `Cannot open '/proc/pid/maps': No such file or directory`.
radare has the same behavior with every binary.
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 27 x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18299 @ linux-x86-64 git.2.6.0-132-gcc3a5ddfe commit: cc3a5ddfe7ee5a533a6aa78bda73f529fdcadff6 build: 2018-06-04__20:39:01

### Expected behavior
it should load my rr2 file

### Actual behavior
`Cannot open '/proc/2820/maps': No such file or directory
Unable to find filedescriptor 3
Unable to find filedescriptor 6
Unable to find filedescriptor 3
Unable to find filedescriptor 6
Cannot open '/proc/2820/maps': No such file or directory
`
### Steps to reproduce the behavior 
`r2 -e dbg.profile=whatever.rr2 -d mybinary`

### Additional Logs, screenshots, source-code,  configuration dump, ...
![schermata del 2018-06-04 21-49-24](https://user-images.githubusercontent.com/7453810/40938146-391d69ca-6841-11e8-994f-7e2159b5c3a7.png)

**Comment by radare** [comment]
Do this proc path exists at all? It seems more like a problem with selinux than r2 itself

Missing capability?

**Comment by M3rcurio** [comment]
@radare 
Nope, it doesn't exist. I've tried  the same thing on an ubuntu virtual machine and it didn't work too.
Anyway debug works perfectly if i don't try to load rr2 files.

**Comment by XVilka** [comment]
No, it is unrelated. Just checked on my installation (Fedora 28) - issue still the same. There is no "/proc" entry for the created process. E.g. it shows created process with PID 65043, but there is only a process with PID 65042 (radare2 itself).

**Comment by radare** [comment]
Ah ok so its just trying to trace rarun2’s pid instead of the execve’d one

**Comment by radare** [comment]
still? not fixed? can you try again?

**Comment by M3rcurio** [comment]
It seems fixed to me.
