### ISSUE TITLE
Rename ?d into aod

### ISSUE THREAD

**Issue by radare** [radare/radare2#10263]
get opcode descriptions is something unrelated to help or evaluating numbers, it doesnt makes much sense to have it under ?d imho. its better as a subcommand of `ao`

**Comment by Maijin** [comment]
Will need to check this change is applied in cutter too @xarkes

**Comment by VivekBhatt007** [comment]
@radare, I would like to start contributing with this issue. Can you please explain about that changes and where should i start looking into the code?

**Comment by xarkes** [comment]
The idea is to rename the command `?d`. Currently the command is in `libr/core/cmd_help.c:366`. It would be great to delete `?d` command and move that to `ao` which is in `libr/core/cmd_anal.c`

**Comment by VivekBhatt007** [comment]
I have added new switch case in ao with 'd' option and moved code from libr/core/cmd_help.c:366 to libr/core/cmd_anal.c file. Please let me know if there is any test case to verify this changes.

**Comment by Maijin** [comment]
Do a Pull Request, you will see which tests are failing

**Comment by Maijin** [comment]
i see only one test that needs to be fixed "cmd_help: ?vi-8"
