### ISSUE TITLE
heap-buffer-overflow (WRITE of size 4) in r_utf_block_list [libr/util/utf8.c:678]

### ISSUE THREAD

**Issue by geeknik** [radare/radare2#10261]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x64
| File format of the file you reverse (mandatory)      | data
| Architecture/bits of the file (mandatory)            | Unknown
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18274 @ linux-x86-64 git.2.6.0-112-gf4973a93d commit: f4973a9 build: 2018-06-01__14:57:12

### Expected behavior
No crash.

### Actual behavior
```
Warning: failed to init section header
=================================================================
==21428==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000273d4 at pc 0x7fe4098a1811 bp 0x7ffc9c468810 sp 0x7ffc9c468808
WRITE of size 4 at 0x6020000273d4 thread T0
    #0 0x7fe4098a1810 in r_utf_block_list /root/radare2/libr/util/utf8.c:678:12
    #1 0x7fe40fb62c5a in _print_strings /root/radare2/libr/core/cbin.c:331:18
    #2 0x7fe40fb4baf0 in bin_strings /root/radare2/libr/core/cbin.c:450:2
    #3 0x7fe40fb4baf0 in r_core_bin_info /root/radare2/libr/core/cbin.c:3335
    #4 0x55ec79f09f87 in main /root/radare2/binr/rabin2/rabin2.c:1072:2
    #5 0x7fe40884a2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #6 0x55ec79e318a9 in _start (/root/radare2/binr/rabin2/rabin2+0x238a9)

0x6020000273d5 is located 0 bytes to the right of 5-byte region [0x6020000273d0,0x6020000273d5)
allocated by thread T0 here:
    #0 0x55ec79ed8ae3 in malloc /b/build/slave/linux_upload_clang/build/src/third_party/llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:98:3
    #1 0x7fe4098a12e3 in r_utf_block_list /root/radare2/libr/util/utf8.c:654:14
    #2 0x7fe40fb62c5a in _print_strings /root/radare2/libr/core/cbin.c:331:18
    #3 0x7fe40fb4baf0 in bin_strings /root/radare2/libr/core/cbin.c:450:2
    #4 0x7fe40fb4baf0 in r_core_bin_info /root/radare2/libr/core/cbin.c:3335
    #5 0x55ec79f09f87 in main /root/radare2/binr/rabin2/rabin2.c:1072:2
    #6 0x7fe40884a2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/radare2/libr/util/utf8.c:678:12 in r_utf_block_list
```
### Steps to reproduce the behavior 
1. Compile from source using `-fsanitize=address`.
2. ./rabin -z test053.dat

### Additional Logs, screenshots, source-code,  configuration dump, ...
[test053.zip](https://github.com/radare/radare2/files/2069766/test053.zip)

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
the thing is that those bins only crash if you run iz, so it doesnt crashes with aaa or so, which is what we do for the bins/fuzz
