### ISSUE TITLE
AVR: Error messages on load (Invalid command)

### ISSUE THREAD

**Issue by abatchy17** [radare/radare2#10269]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04.3 LTS x64
| File format of the file you reverse (mandatory)      | AVR binary
| Architecture/bits of the file (mandatory)            | AVR
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18311 @ linux-x86-64 git.2.6.0-139-g08d9dfc commit: 08d9dfcfcd69fbdfbcf69bda17320cb5f3a1d2ca build: 2018-06-05__21:57:43

### Expected behavior

Loading example code from [this ](https://github.com/radareorg/r2con/tree/master/2016/trainings/05-avr-explotation/materials)spits errors. 

Not sure what functionality it might be messing with but I didn't notice anything "broken".

### Actual behavior
Upon loading any AVR binary, I get these exact error messages:

```
|ERROR| Invalid command '{f r17:r16 1 0x00000000' (0x7b)
|ERROR| Invalid command ',f r0 1 0x00000000' (0x2c)
```
### Steps to reproduce the behavior 

Just load them into R2.

```bash
abatchy@ubuntu:~/Desktop/tmp$ wget https://github.com/radareorg/r2con/raw/master/2016/trainings/05-avr-explotation/materials/ex1.1/hello.bin
abatchy@ubuntu:~/Desktop/tmp$ wget https://github.com/radareorg/r2con/raw/master/2016/trainings/05-avr-explotation/materials/ex1.2/blink.bin
abatchy@ubuntu:~/Desktop/tmp$ wget https://github.com/radareorg/r2con/raw/master/2016/trainings/05-avr-explotation/materials/ex3.1/ex3.1.bin
abatchy@ubuntu:~/Desktop/tmp$ wget https://github.com/radareorg/r2con/raw/master/2016/trainings/05-avr-explotation/materials/ex3.4/ex3.4.bin

abatchy@ubuntu:~/Desktop/tmp$ r2 -a avr blink.bin 
 -- Change the graph block definition with graph.callblocks, graph.jmpblocks, graph.flagblocks
|ERROR| Invalid command '{f r17:r16 1 0x00000000' (0x7b)
|ERROR| Invalid command ',f r0 1 0x00000000' (0x2c)
[0x0000008c]> q
abatchy@ubuntu:~/Desktop/tmp$ r2 -a avr hello.bin 
 -- Error: cannot yank negative sleep
|ERROR| Invalid command '{f r17:r16 1 0x00000000' (0x7b)
|ERROR| Invalid command ',f r0 1 0x00000000' (0x2c)
[0x0000008c]> q
abatchy@ubuntu:~/Desktop/tmp$ r2 -a avr ex3.1.bin 
 -- See you at the defcon CTF
|ERROR| Invalid command '{f r17:r16 1 0x00000000' (0x7b)
|ERROR| Invalid command ',f r0 1 0x00000000' (0x2c)
[0x00000158]> q
abatchy@ubuntu:~/Desktop/tmp$ r2 -a avr ex3.4.bin 
 -- Everything up-to-date.
|ERROR| Invalid command '{f r17:r16 1 0x00000000' (0x7b)
|ERROR| Invalid command ',f r0 1 0x00000000' (0x2c)
[0x0000008e]> q

```

**Comment by radare** [comment]
its fixed in my pr, waiting for travis
