### ISSUE TITLE
Broken r_core.pc causes oddities (crashes, wrong analysis) in R2 library user programs

### ISSUE THREAD

**Issue by MiroslavR** [radare/radare2#10266]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian testing x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ELF, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18308 @ linux-x86-64 git.2.6.0-132-gcc3a5ddfe commit: cc3a5ddfe7ee5a533a6aa78bda73f529fdcadff6 build: 2018-06-05__14:43:50

### Expected behavior

I have a program that depends on the _r_core_ library and uses _pkg-config_ when building. I expected to load the provided binary, perform analysis on it and not crash.

### Actual behavior

My program crashes when analyzing the provided binary (while the R2 CLI does not).

### Steps to reproduce the behavior 
- Make a Radare2 user installation via `sys/user.sh` (I used a different `HOME` because I wanted it to be installed elsewhere).
- Download [my_program.zip](https://github.com/radare/radare2/files/2072526/my_program.zip) and extract it somewhere. It contains:
  - `binary`: A binary that my program will be analyzing (via the `r_core` library).
  - `env.sh`: Environment specifying R2 installation prefix (needs to be changed).
  - `build.sh`: Build script for my program. It uses pkg-config files from the R2 installation.
  - `run.sh`: Run script for my program.
  - `Main.cpp`: Source code of my program that sets up R2 core, loads `binary` and calls `aaa` for auto-analysis.
- Change `R2_INSTALL_PREFIX` in `env.sh`.
- Run `build.sh`.
- Run `run.sh`.
- Crash.

### Additional Logs, screenshots, source-code,  configuration dump, ...
- GDB backtrace: [gdb_backtrace.txt.zip](https://github.com/radare/radare2/files/2072566/gdb_backtrace.txt.zip)
- The R2 CLI seems to work fine when analyzing the binary.
- This was originally reported to the Cutter project: https://github.com/radareorg/cutter/issues/512. Cutter is also affected by this issue.

### Solution
I have actually tracked this down to `r_core.pc` (pkg-config file) adding dependency on my system capstone via _-lcapstone_ for some reason. I believe the built-in capstone from Radare2 and the system capstone forced to be linked against my program were somehow conflicting. Removing capstone from `r_core.pc` solves this issue.

**Comment by radare** [comment]
that only happens if you build r2 —with-syscapstone, my r_core.pc doesnt have that -lcapstone. so imho the problem is in your side, not in r2

**Comment by MiroslavR** [comment]
> that only happens if you build r2 —with-syscapstone

I didn't specify `—with-syscapstone`, unless the build script did it automatically. However, I see capstone being built and `ldd` on R2 libraries shows they do not depend on system capstone.

**Comment by radare** [comment]
can you do a PR to fix this?

**Comment by MiroslavR** [comment]
If you're referring to me, I'm not experienced enough to know how to fix it properly. What comes to mind, however:
 * Using `--atleast-version=4.0` for pkg-config [here](https://github.com/radare/radare2/blob/7083c3385ae08d7a118a88927574ffe792e652ce/configure#L438) and respecting `USE_R2_CAPSTONE` just like the build script does [here](https://github.com/radare/radare2/blob/d46164497790599bc50b3847757d7d45924df2ad/sys/build.sh#L68-L70). The version of my system capstone is actually only 3.0.4 so that's why the build script didn't use `—with-syscapstone`.

* Reverting 75066808c779d1541a0ccf42f46b8e60863f8ec3 (I really don't understand why my application should be linked against capstone if I'm not using it, but I could be missing something here.)

**Comment by radare** [comment]
R2 should build against the ancient cs3 without any problem. But default builds should use our own fork of it

**Comment by radare** [comment]
cc @ret2libc

**Comment by ret2libc** [comment]
Could you try using this patch https://pastebin.com/xPHJiN5t and check if it works?

**Comment by MiroslavR** [comment]
When trying to apply the patch I get this error message: `error: corrupt patch at line 28`. What version is the patch for? I'm on master.

**Comment by ret2libc** [comment]
```
From 9633b5be47035c977db04973553a3fa23a31c628 Mon Sep 17 00:00:00 2001
From: Riccardo Schirone <sirmy15@gmail.com>
Date: Sun, 23 Sep 2018 16:54:56 +0200
Subject: [PATCH] configure: unset CAPSTONE_* vars when it is not used

Signed-off-by: Riccardo Schirone <sirmy15@gmail.com>
---
 configure     | 4 +++-
 configure.acr | 2 ++
 2 files changed, 5 insertions(+), 1 deletion(-)

diff --git a/configure b/configure
index 719b1f909..5cd60178d 100755
--- a/configure
+++ b/configure
@@ -451,7 +451,9 @@ if [ 11 = "$WITH_CAPSTONE$HAVE_PKGCFG_CAPSTONE" ]; then
 
 USE_CAPSTONE="1"
 else
-USE_CAPSTONE="0"; fi
+USE_CAPSTONE="0"
+CAPSTONE_CFLAGS=""
+CAPSTONE_LDFLAGS=""; fi
 check_library HAVE_LIB_Z z 0
 check_library HAVE_LIB_ZIP zip 0
 if [ 11 = "$HAVE_LIB_Z$USE_ZIP" ]; then
diff --git a/configure.acr b/configure.acr
index be06434f0..f7f7a3d8f 100644
--- a/configure.acr
+++ b/configure.acr
@@ -34,6 +34,8 @@ IFAND WITH_CAPSTONE HAVE_PKGCFG_CAPSTONE {
 	USE_CAPSTONE = 1 ;
 }{
 	USE_CAPSTONE = 0 ;
+	CAPSTONE_CFLAGS = '' ;
+	CAPSTONE_LDFLAGS = '' ;
 }
 
 CHKLIB z
-- 
2.15.2 (Apple Git-101.1)

```

**Comment by MiroslavR** [comment]
That does seem to fix the crashes. The generated `r_core.pc` no longer references capstone.

**Comment by ret2libc** [comment]
Perfect, thanks for testing this! I will push the fix on master ASAP.
