### ISSUE TITLE
Patch Keyboard Input

### ISSUE THREAD

**Issue by mojtabamarashee** [radare/radare2#10270]
Hi
Im Pathching a binary file that listen to keyboard input in background, I want when the key "a" is pressed it is repalced with "e".
How I can find read keyboard routine in assembly?

**Comment by Maijin** [comment]
That is not a radare2 issue.

**Comment by mojtabamarashee** [comment]
So How I can do it?
Could you please help?

**Comment by Maijin** [comment]
No. You have to search/learn/work/study etc. You can ask on dedicated Reverse Engineering chats/forums but not in here.
