### ISSUE TITLE
Fail to open SWF file  

### ISSUE THREAD

**Issue by R3vrseShell** [radare/radare2#10273]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 9.4 (x64)
| File format of the file you reverse (mandatory)      | swf
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18315 @ linux-x86-64 git.2.6.0-141-g4e57af452
commit: 4e57af4521bdb3cbaab015839c49bf1af47a1414 build: 2018-06-06__13:20:04

### Expected behavior

Load swf file on r2 

### Actual behavior

Fail to load the binary (memory corruption) (log bellow) 

### Steps to reproduce the behavior 
- Load swf file with the last version of r2 and the swf plugin (` r2pm -i swf` ) 

### Additional Logs, screenshots, source-code,  configuration dump, ...
```
*** Error in `r2': malloc(): memory corruption: 0x00005584d168e8a0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7fdddd173bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7fdddd179fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x79089)[0x7fdddd17c089]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fdddd17df64]
/lib/x86_64-linux-gnu/libc.so.6(__strdup+0x1a)[0x7fdddd1833ba]
/home/XXXX/.local/share/radare2/plugins/bin_swf.so(+0x20c3)[0x7fdddbcdf0c3]
/usr/lib/libr_bin.so(r_bin_object_set_items+0x5ba)[0x7fdde07421e8]
/usr/lib/libr_bin.so(r_bin_object_new+0x41e)[0x7fdde0741c15]
/usr/lib/libr_bin.so(r_bin_file_new_from_bytes+0x1f8)[0x7fdde07402bd]
/usr/lib/libr_bin.so(r_bin_load_io_at_offset_as_sz+0x4e6)[0x7fdde07333af]
/usr/lib/libr_bin.so(+0x1f42b)[0x7fdde073342b]
/usr/lib/libr_bin.so(r_bin_load_io+0x44)[0x7fdde0732ec0]
/usr/lib/libr_core.so(+0xe8ea9)[0x7fdde13e1ea9]
/usr/lib/libr_core.so(r_core_bin_load+0x2a4)[0x7fdde13e264e]
r2(+0x6193)[0x5584d0dcb193]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fdddd1232e1]
r2(+0x31da)[0x5584d0dc81da]
```

**Comment by radare** [comment]
where's the file to reproduce this? :P

**Comment by XVilka** [comment]
No file - no fix.

**Comment by radare** [comment]
Also this issue should be in r2e
