### ISSUE TITLE
Cleaner jump lines

### ISSUE THREAD

**Issue by radare** [radare/radare2#10276]
Large graphs with jmptables result on some really (cool to see) but wrong edges layout.
<img width="1609" alt="screen shot 2018-06-04 at 23 43 41" src="https://user-images.githubusercontent.com/917142/41043082-6836914c-69a3-11e8-8ddb-5b3ae34d3b3a.png">

**Comment by radare** [comment]
pls @cyanpencil

**Comment by XVilka** [comment]
@cyanpencil wasn't this fixed already?

**Comment by radare** [comment]
not fixed, but improved. moving to 2.8 for now

**Comment by radare** [comment]
I think current lines are way better than the ones in the screenshot
