### ISSUE TITLE
radiff2 -g not working as expected after upgrading from 2.6.0 1 to 2.6.0 9

### ISSUE THREAD

**Issue by MKuijpers** [radare/radare2#10282]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10, x64 64 bit
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radiff2 2.6.0 9 @ windows-x86-32 git. commit: dbc87f223471ff9bd7c28fbcc2afaeda3736651d build: Mon 05/21/2018__18:19:30.39

### Expected behavior
When running `radiff2 -g entry0 ForLoopSquared.exe InputTest.exe` _(files found below)_ I expect a correct call graph from the entry0 point to be generated in dot format, which was working correctly in the following version: 
`radiff2 2.6.0-git 1 @ windows-x86-32 git.`
`commit: 562bd8f65ac9bcfb30ea2d2da95b6178776471a8 build: Tue 04/10/2018__ 8:26:09.94`

### Actual behavior
Instead I get the following errors in my command line 13 times:
`CreateProcess: The system cannot find the file specified.`
Below these error a dot file is generated which contains empty code blocks and differences in the assembly code. _See graphs.zip_

#### Correct graph:
Place the binaries `ForLoopSquared.exe` and `InputTest.exe` into the same folder.
Have the following version installed:
`radiff2 2.6.0-git 1 @ windows-x86-32 git.`
`commit: 562bd8f65ac9bcfb30ea2d2da95b6178776471a8 build: Tue 04/10/2018__ 8:26:09.94`
Run the following command with this version installed: `radiff2 -g entry0 ForLoopSquared.exe InputTest.exe`
This will print the dot file in console without any errors shown. When compiling this dot file, the wanted graph is shown.

#### Faulty graph:
Place the binaries `ForLoopSquared.exe` and `InputTest.exe` into the same folder.
Have the following version installed:
`radiff2 2.6.0 9 @ windows-x86-32 git.`
`commit: dbc87f223471ff9bd7c28fbcc2afaeda3736651d build: Mon 05/21/2018__18:19:30.39`
Run the following command with this version installed: `radiff2 -g entry0 ForLoopSquared.exe InputTest.exe`
This will first throw some errors of not being able to find some file, afterwards a dot file is printed in the console. When compiling this dot file, a lot of code blocks are empty and code blocks don't correspond to the original code.

### Additional Logs, screenshots, source-code,  configuration dump, ...
radiff2 binary:
[radiff2.zip](https://github.com/radare/radare2/files/2077775/radiff2.zip)
ForLoopSquared.exe and InputTest.exe binary files (exe):
[test_files.zip](https://github.com/radare/radare2/files/2077788/test_files.zip) 
Correct and faulty graphs (png+dot)
[graphs.zip](https://github.com/radare/radare2/files/2077798/graphs.zip)
_(Had the problem with other files as well, but I will include the files mentioned in the issue as well. The graphs below were generated with these files as well)_

**Comment by radare** [comment]
if its fixed in git then we can close this issue. a new release will happen at the end of this month

**Comment by radare** [comment]
ping

**Comment by Maijin** [comment]
Closing until new answers.
