### ISSUE TITLE
r2 -H vars should start by R2_

### ISSUE THREAD

**Issue by radare** [radare/radare2#10290]
currently we have:
```
> r2 -H
R2_PREFIX=/usr/local
MAGICPATH=share/radare2/2.7.0-git/magic
PREFIX=/usr/local
INCDIR=/usr/local/include/libr
LIBDIR=/usr/local/lib
LIBEXT=dylib
RCONFIGHOME=/Users/pancake/.config/radare2
RDATAHOME=/Users/pancake/.local/share/radare2
RCACHEHOME=/Users/pancake/.cache/radare2
LIBR_PLUGINS=/usr/local/lib/radare2/2.7.0-git
USER_PLUGINS=/Users/pancake/.local/share/radare2/plugins
USER_ZIGNS=/Users/pancake/.local/share/radare2/zigns
```

* [x] R2_PREFIX
* [x] MAGICPATH
* [ ] PREFIX
* [ ] INCDIR
* [ ] LIBDIR
* [ ] LIBEXT
* [x] RCONFIGHOME
* [x] RDATAHOME
* [x] RCACHEHOME
* [x] LIBR_PLUGINS
* [x] USER_PLUGINS
* [x] USER_ZIGNS

**Comment by radare** [comment]
this is gonna be picky for radare2-extras and radare2-pm, but will pay off

**Comment by radare** [comment]
this is the place to discuss better names for all those. post your proposals

**Comment by XVilka** [comment]
I don't think it should land in 2.7.0 - it might need a lot of changed in r2e and r2pm for a week.

**Comment by radare** [comment]
agree

**Comment by Maijin** [comment]
@radare the following:

PREFIX
INCDIR
LIBDIR
LIBEXT

already have R2_PREFIX, R2_INCDIR, etc. counterpart. Not very sure what to do here. but I've converted the others:

```
R2_PREFIX=/usr/local
R2_MAGICPATH=/usr/local/share/radare2/2.9.0-git/magic
PREFIX=/usr/local
INCDIR=/usr/local/include/libr
LIBDIR=/usr/local/lib
LIBEXT=dylib
R2_RCONFIGHOME=/Users/maijin/.config/radare2
R2_RDATAHOME=/Users/maijin/.local/share/radare2
R2_RCACHEHOME=/Users/maijin/.cache/radare2
R2_LIBR_PLUGINS=/usr/local/lib/radare2/2.9.0-git
R2_USER_PLUGINS=/Users/maijin/.local/share/radare2/plugins
R2_USER_ZIGNS=/Users/maijin/.local/share/radare2/zigns
```
👍

**Comment by radare** [comment]
we have R2_PREFIX and PREFIX here… not sure if we shuold change some more because r2pm depends on them (libext, prefix and incdir at least)

**Comment by Maijin** [comment]
Well some of the one I changed, already required changes to R2PM and extras which i did issue with the remaining one is that they are all duplicated PREFIX, R2_PREFIX, R2_INCDIR, INCDIR etc.

**Comment by radare** [comment]
cc @ret2libc what do you think about this? keep LIBDIR, LIBEXT, INCDIR, PREFIX? or prefix them with R2_? may break r2pm and such, but for consistency it makes sense to me

**Comment by ret2libc** [comment]
Yeah the R2_ ones seem good.
