### ISSUE TITLE
rasm2 incorrect assembly

### ISSUE THREAD

**Issue by Tanjmaxalb** [radare/radare2#10303]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | ArchLinux 4.16.12-1 x86-64
| File format of the file you reverse      | machine instruction
| Architecture/bits of the file            | x86-32
| rasm2 -v full output     | rasm2 2.6.0 0 @ linux-x86-64 git.2.6.0 commit: HEAD build: 2018-05-23__01:38:10

### Expected behavior
```
rasm2 "mov eax, [eax * 2 + 8]"
8b044508000000
rasm2 -d "8b044508000000"
mov eax, dword [eax*2 + 8]
```
### Actual behavior
```
rasm2 "mov eax, [eax * 2 + 8]"
8b040808000000
rasm2 -d "8b040808000000"
mov eax, dword [eax + ecx]
or byte [eax], al
add byte [eax], al
```
I think that there is an incorrect assembling of the SIB part. SIB must be `45` because `ss = 01` (register + sbyte), `index = 000` (eax) and `base = 101` (disp32 i.e. 8). But in actual `ss = 00` (register), `index = 000` (eax) and `base = 100` (ecx) that is false.

**Comment by felberj** [comment]
I think this is a capstone issue:

```python
>>> from capstone import *
>>> CODE = b"\x8b\x04\x08\x08\x00\x00\x00"
>>> md = Cs(CS_ARCH_X86, CS_MODE_64)
>>> for i in md.disasm(CODE, 0x1000):
...  print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
... 
0x1000:	mov	eax, dword ptr [rax + rcx]
0x1003:	or	byte ptr [rax], al
0x1005:	add	byte ptr [rax], al
```

**Comment by Tanjmaxalb** [comment]
Problem is in assembling, but not disassembling, it is full true.

**Comment by PaoloMonti42** [comment]
In commit #10177 I basically rewrote the assembling logic for`mov [reg], imm`, it should be easy enough to reuse the same code for this fix

**Comment by radare** [comment]
Capatone doesnt assemble

**Comment by Maijin** [comment]
http://radare.today/posts/radare2-capstone/

**Comment by Tanjmaxalb** [comment]
Keystone haven't problem with assemble:
```
>>> from keystone import *

>>> ks = Ks(KS_ARCH_X86, KS_MODE_32)
>>> encoding, _ = ks.asm(b'mov eax, [eax * 2 + 8]')
>>> [hex(x) for x in encoding]
['0x67', '0x8b', '0x4', '0x45', '0x8', '0x0', '0x0', '0x0']
```
The only exception is 0x67 prefix that overrides address

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/tree/master/new/db/asm** (See https://github.com/radare/radare2-regressions/blob/master/new/README.md) You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```
