### ISSUE TITLE
Improvements to dm. and related commands

### ISSUE THREAD

**Issue by mcd1992** [radare/radare2#10323]
Currently `dm.` prints just the name of the map. I feel it would be more useful to show everything that you would normally see under just `dm`. Is there any known backwards-compatibility issues that might arise from making `dm.` output more than just the name? Also I feel like `dm` would be more useful with a header row explaining what each column is representing. Any known issues with these ideas?

If not I'm willing to add it in and also would try to add in: `dm=.` and `dmj.` for completeness.
As I wrote this digging through the code I just realized that the 3rd column in `dm` is a asterisk if you're seek'd within the maps boundary. All the more reason for headers on some output! I've seen quite a few times where a command spits out a bunch of rows with no headers to understand what columns what.

```
:> dm.
Start Address        End Address      In Range Type  Size ? Perm   Map Name            Map File              Flag Name
0x00007fdfa23db000 # 0x00007fdfa2400000  *     usr   148K s r-x    /usr/lib/ld-2.27.so /usr/lib/ld-2.27.so ; map.usr_lib_ld_2.27.so.r_x

```

**Comment by radare** [comment]
agree, we must change that, but probably not that verbose. we have `dmq`already, but there’s no `dmq.`

i like to be able to use backticks to seek to the begining of a map for example s `dm.` ; so we may probably have to type s `dm.~[0]` instead or just s `dmq.`

the header is anoying because it breaks the ability to be reused by other commands.

**Comment by mcd1992** [comment]
I guess you have custom flags for the filepaths? For me the `s dm.` (is it not possible to escape backticks in github markdown?) tries to seek to the map name/filepath as a flag which isn't defined by any default analyses I can see. Now I do see that `s dmm.~[0]` works how you're intending but targets the address and not a flag. `s dmm.~[1]` would work like `s dm.` currently does if you're using custom flags.

Most of the other `.`/current address commands seem to spit out the same output as their non `.` friends which makes sense to me. But I do see that changing `dm.` output could break existing use cases and isn't backwards-compatible for anything that depends on it currently. I guess the best options are to either create a new command like `dmmf`/`dmmf.` which will output the debug memorymap modules filename[s] like `dm.` currently does which would give existing scripts and simple change to remain compatible. Or create a new command like `dmv.` which will output a verbose version of `dm.` and let the current `dm.` stay the same.

`dmq` is in code but doesn't have a help line with what its supposed to output. Not sure if this was intended as a developer command or what but I can add a helptext to it and a `dmq.` command if needed.

As for the headers there might be a way to detect if the current command[s] are being parsed by grep/`~` and if so skip printing the header.

**Comment by radare** [comment]
well those custom flags for the filepaths is done with .dm*

i dont want to overengineer this with dmv or dmmf because you have already dm* and we should have dm.* and dmq. dont worry about breaking old scripts, if changes make sense go for it.

also, most scripts people use are for static analysis, not when debugging

do you want to make those changes in a PR?

thanks!

**Comment by mcd1992** [comment]
Yea I'll be making PR for this request once I get it all figured out and done. Just trying to avoid breaking anyone's workspace with changes beforehand.

Thanks!
