### ISSUE TITLE
A debug print / log level system for output

### ISSUE THREAD

**Issue by mcd1992** [radare/radare2#10324]
Right now it seems that eprintf is the only method we have for outputting to the console that isn't intended for 'proper' program use. So when developing something or debugging something I'm seeing eprintf being used for debug output and then commented out or removed before commit.

I think a syslog style logging system would be useful for debugging/development. Could add a extra argument flag to the rbin programs to enable file output in a syslog format or to the console itself. Radare itself could use a scr.loglevel variable to select output to the console (not sure how it would work in visual mode).

Then from a programming standpoint we could have some sort of LOG singleton with LOG.warn/error/info ect. which would output (if matching loglevel) to the console or a file.

Let me know if theres any qualms or better ideas. I'm really just wanting a good way to enable debug level output temporarily for development or debugging issues.

**Comment by radare** [comment]
there’s r_log_ api in r_util. , but its not used anywhere, and can be improved in several ways. glib logging system is not bad either. but a bit overengineerd imho. having the ability to change the loglevel from an eval var seems like a good idea.

**Comment by mcd1992** [comment]
Dug through the glib one and it looks like it would require some dependencies other than libc. I did find two potentially usable libraries though. I'll give both a try at some point and see which works best, on paper zf_log seems to fit radare's use-case the best.

#### Possible Libraries
* [zf_log](https://github.com/wonder-mice/zf_log) MIT License
    * Debug logging is reduced to no-op in release builds:
    * No "unused" warning for variables used in log statements only:
    * Arguments are not evaluated when the message is not logged:
    * Log a memory region as HEX and ASCII:
    * Compiler warnings when format string and arguments don't match:
    * Conditional logging of sensitive information (also known as Personally Identifiable Information or PII):
    * Custom output functions
    * Custom log message formats
    * Compile time configuration of logging level
    * Run time configuration of logging level
    * Optional built-in support for Android log and Apple system log (iOS, OS X)
    * Reasonably cross-platform (OS X, iOS, Linux, Android, other Unix flavors, POSIX platforms and Windows)
    * No external dependencies
    * Compact call site (smaller executables)
    * Thread safe
    * Library size is under 10Kb (when compiled for x86_64)
    * Can be used privatly in libraries

* [zlog](https://github.com/HardySimpson/zlog) LGPL License
    * syslog model, better than log4j model
    * log format customization
    * multiple output destinations including static file path, dynamic file path, stdout, stderr, syslog, user-defined ouput
    * runtime manually or automatically refresh configure(safely)
    * high-performance, 250'000 logs/second on my laptop, about 1000 times faster than syslog(3) with rsyslogd
    * user-defined log level
    * thread-safe and process-safe log file rotation
    * microsecond accuracy
    * dzlog, a default category log API for easy use
    * MDC, a log4j style key-value map
    * self debuggable, can output zlog's self debug&error log at runtime
    * No external dependencies, just based on a POSIX system and a C99 compliant vsnprintf.

**Comment by mcd1992** [comment]
Related: https://github.com/radare/radare2/issues/10546

**Comment by Maijin** [comment]
See @radare comment that goes in the same direction of your proposal:

```
i dont see the point on changing ove r9000 eprintf for another macro that does the same. i would personally prefer to use an api similar to glib, which requires 3 arguments. and in fact. before doing such big PR is probably better to discuss things to not loose time doing changes that get conflicts all the time

    context of the log message (module, plugin, file, etc)
    level of the issue (warning, debug, error, fatal ,...)
    format string with message

There are different problems in such api.

    this may work on threads. this is, knowing which thread spits an error is important, and common data structures cant be shared without mutexing and such
    this adds a lot of complexity for just spitting out an error
    the already existing r_log api allows to redirect the output to a different file descriptor, socket or file
    doing such change requires even more engineering
    release builds probably need some debug and assert-level log messages to go away from the binary
    tasks need to capture the associated error messages, like its done for r_cons output
    each error should probably come with a timestamp to make benchmarks with logs possible, and give proper timeline information

And this is just what i though in 5min after checking this pr. there are probably more things to consider. so i'm not really in the mood to accept this change yet because it feels wrong and overengineered. and we should probably answer many questions before deciding the right way to go without having another monster API inside r2.

also if we do so i would probably go for changing few strategic eprintfs for testing and understanding the real needs for capturing and managing those messsages
```

**Comment by mcd1992** [comment]
Right now I do have a working implementation in my feature branch: https://github.com/mcd1992/radare2/tree/zflogging

Right now the only issue with it is how I'm using r2 configuration variables, there's probably a better way but I'm not sure yet.
