### ISSUE TITLE
Fix gcc8 warnings

### ISSUE THREAD

**Issue by radare** [radare/radare2#10338]
http://xvilka.me/radare2/gcc8_radare2.builderrors.log

**Comment by XVilka** [comment]
Updated the warnings log.

**Comment by XVilka** [comment]
@MaskRay you might want to check those too, if you are in the mood.

**Comment by sajattack** [comment]
I'd like to take a stab at this one if that's ok.

**Comment by ret2libc** [comment]
Yes please feel free to go ahead with it! Very appreciated :)

**Comment by ret2libc** [comment]
@sajattack are you still working on this? Just asking because otherwise I can work on it.

**Comment by sajattack** [comment]
@ret2libc Go ahead.
