### ISSUE TITLE
Implement a documentation generator and improved comments (doxygen/sphinx)

### ISSUE THREAD

**Issue by mcd1992** [radare/radare2#10343]
Currently only the r2bindings code has documentation generation, using vapigen/vala. Implementing a comment standard for future code and slowly adding in comments to older code with something like doxygen/sphinx would allow for dynamic documentation to be generated. This would make it much easier for new developers to understand the existing code and could even help power-developers debug issues and see how everything intermingles. Plus it would make the motto 'radare2 is self documenting' even more factual!

Doxygen has been the leader for C documentation for a while so its tried and true but as of recent the [Linux kernel has moved over to Sphinx](https://www.kernel.org/doc/Documentation/doc-guide/sphinx.rst) for documentation which seems worth looking into.

Related issue https://github.com/radare/radare2/issues/924

[Doxygen](https://www.stack.nl/~dimitri/doxygen/)
[Sphinx](http://www.sphinx-doc.org)

**Comment by radare** [comment]
make vdoc does that

**Comment by mcd1992** [comment]
It does in the bindings repo, I'm referring to the r2 base code. Right now there's a lot of global struct/classes and functions in libr that aren't well commented or documented.

I don't expect everyone to go back and start documenting old code but would like to see a *recommendation* to use [Doxygen style comments](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html) in new code if possible. I'm willing to put in the time (once I finish some other issues I've opened) to doxygen comment stuff I read through. But this decision is something that kind of has to be agreed on with all developers not just one person.

If possible I'm really just hoping to get a decision on whether we could update the CONTRIBUTING.md to talk about using Doxygen to comment/describe classes or functions. Or have a separate directory for documentation using sphinx+reStructuredText files if we don't want to document in the actual C area. We can use both at the same time if we want, see [how Linux does it](https://01.org/linuxgraphics/gfx-docs/drm/index.html). I'm not looking for anything like a gun-to-head YOU MUST COMMENT ALL CODE  THIS WAY change, just some writing to state that radare2 supports doxygen comments and/or written documentation in a directory which can be built with sphinx or something.
