### ISSUE TITLE
Disable http messages

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10379]
When using the http server, i keep getting these messages and i can't figure out how to turn them off.

```
[0x00400470]> [HTTP] 127.0.0.1:34848 /cmd/T
```

I know these are the commands I'm doing. However, in this case, I'd like to simply not show them.

**Comment by radare** [comment]
e http.log=false

**Comment by bannsec** [comment]
Gotcha. I had tried that after starting the http server before. Looks like it has to be set prior to starting the server.
