### ISSUE TITLE
VVV not functioning correctly

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10383]
Looks like either the help documentation is wrong, or `VVV` is not behaving correctly.

From the `?` screen:
```
| V                       visual mode (V! = panels, VV = fcngraph, VVV = callgraph)
```

However, when I do `VVV` i just drop into the `VV` mode instead.

**Comment by radare** [comment]
the help message is wrong. the behaviour changed. a callgraph is a very expensive operation for some binaries. which makes it a problem for some users, so i preferred to drop it
