### ISSUE TITLE
r2 crash after using 'dmh' command. 

### ISSUE THREAD

**Issue by Goyo2600** [radare/radare2#10387]
| OS/arch/bits                              | Ubuntu amd 64, Ubuntu x86 64
| Architecture/bits of the file         | x86/64 etc.
| r2 -v full output                         | radare2 2.7.0-git 18568 @ linux-x86-64 git.2.6.0-278-gc1cdc7a
commit: c1cdc7a8b6e221d716de72aa54d2e4fa21765b59 build: 2018-06-18__11:19:20

Load binary in debug mode for testing 'dmh' command: (I want to see heap content)

goyo@linux:~/Descargas/pwnable/secret$ r2 -Ad prueba2
Process with PID 21025 started...
= attach 21025 21025
bin.baddr 0x08048000
Using 0x8048000
asm.bits 32
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
= attach 21025 21025
21025
 -- Bindings are mostly powered by tears.
[0xf7f6ca20]> dcu main
Continue until 0x0804846b using 1 bpsize
hit breakpoint at: 804846b
:> dmh
Warning: glibc library with symbol main_arena could not be found. Is libc6-dbg installed?
:> *** Error in `r2': free(): invalid pointer: 0x00007fb8a8b34b98 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fb8a87e77e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fb8a87f037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fb8a87f453c]
/usr/lib/libr_util.so(r_list_pop_head+0x9c)[0x7fb8a8da93ff]
/usr/lib/libr_core.so(r_core_task_schedule+0x7a)[0x7fb8acb37291]
/usr/lib/libr_core.so(r_core_task_continue+0x1d)[0x7fb8acb375aa]
/usr/lib/libr_core.so(+0x591d7)[0x7fb8aca221d7]
/usr/lib/libr_cons.so(r_cons_is_breaked+0x23)[0x7fb8ac34e462]
/usr/lib/libr_cons.so(r_line_readline_cb+0x1e4)[0x7fb8ac355dff]
/usr/lib/libr_cons.so(r_line_readline+0x13)[0x7fb8ac355c19]
/usr/lib/libr_core.so(r_core_fgets+0x6c)[0x7fb8aca20ff3]
/usr/lib/libr_cons.so(r_cons_fgets+0xa2)[0x7fb8ac35921a]
/usr/lib/libr_core.so(r_core_visual_prompt+0xad)[0x7fb8acacb782]
/usr/lib/libr_core.so(r_core_visual_prompt_input+0x8f)[0x7fb8acacb681]
/usr/lib/libr_core.so(r_core_visual_cmd+0x36ed)[0x7fb8acad3051]
/usr/lib/libr_core.so(r_core_visual+0x634)[0x7fb8acad53f9]
/usr/lib/libr_core.so(+0xe8df9)[0x7fb8acab1df9]
/usr/lib/libr_core.so(r_cmd_call+0x1c9)[0x7fb8acaff2c8]
/usr/lib/libr_core.so(+0xed4dd)[0x7fb8acab64dd]
/usr/lib/libr_core.so(+0xea054)[0x7fb8acab3054]
/usr/lib/libr_core.so(r_core_cmd+0x3b3)[0x7fb8acab8bb6]
/usr/lib/libr_core.so(r_core_prompt_exec+0x2b)[0x7fb8aca23d42]
r2(+0x7687)[0x564a23a75687]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fb8a8790830]
r2(+0x3329)[0x564a23a71329]
======= Memory map: ========
564a23a6e000-564a23a78000 r-xp 00000000 08:06 799239                     /home/goyo/radare2/binr/radare2/radare2
564a23c77000-564a23c78000 r--p 00009000 08:06 799239                     /home/goyo/radare2/binr/radare2/radare2
564a23c78000-564a23c79000 rw-p 0000a000 08:06 799239                     /home/goyo/radare2/binr/radare2/radare2
564a23c79000-564a23cda000 rw-p 00000000 00:00 0
564a24e14000-564a2bda8000 rw-p 00000000 00:00 0                          [heap]
7fb8a0000000-7fb8a0021000 rw-p 00000000 00:00 0
7fb8a0021000-7fb8a4000000 ---p 00000000 00:00 0
7fb8a7a34000-7fb8a7a4a000 r-xp 00000000 08:06 528720                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7fb8a7a4a000-7fb8a7c49000 ---p 00016000 08:06 528720                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7fb8a7c49000-7fb8a7c4a000 rw-p 00015000 08:06 528720                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7fb8a7c4a000-7fb8a7c4c000 r-xp 00000000 08:06 528863                     /lib/x86_64-linux-gnu/libutil-2.23.so
7fb8a7c4c000-7fb8a7e4b000 ---p 00002000 08:06 528863                     /lib/x86_64-linux-gnu/libutil-2.23.so
7fb8a7e4b000-7fb8a7e4c000 r--p 00001000 08:06 528863                     /lib/x86_64-linux-gnu/libutil-2.23.so
7fb8a7e4c000-7fb8a7e4d000 rw-p 00002000 08:06 528863                     /lib/x86_64-linux-gnu/libutil-2.23.so
7fb8a7e4d000-7fb8a7e50000 r-xp 00000000 08:06 528706                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fb8a7e50000-7fb8a804f000 ---p 00003000 08:06 528706                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fb8a804f000-7fb8a8050000 r--p 00002000 08:06 528706                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fb8a8050000-7fb8a8051000 rw-p 00003000 08:06 528706                     /lib/x86_64-linux-gnu/libdl-2.23.so
7fb8a8051000-7fb8a8159000 r-xp 00000000 08:06 528752                     /lib/x86_64-linux-gnu/libm-2.23.so
7fb8a8159000-7fb8a8358000 ---p 00108000 08:06 528752                     /lib/x86_64-linux-gnu/libm-2.23.so
7fb8a8358000-7fb8a8359000 r--p 00107000 08:06 528752                     /lib/x86_64-linux-gnu/libm-2.23.so
7fb8a8359000-7fb8a835a000 rw-p 00108000 08:06 528752                     /lib/x86_64-linux-gnu/libm-2.23.so
7fb8a835a000-7fb8a8367000 r-xp 00000000 08:06 790636                     /home/goyo/radare2/libr/socket/libr_socket.so
7fb8a8367000-7fb8a8566000 ---p 0000d000 08:06 790636                     /home/goyo/radare2/libr/socket/libr_socket.so
7fb8a8566000-7fb8a8567000 r--p 0000c000 08:06 790636                     /home/goyo/radare2/libr/socket/libr_socket.so
7fb8a8567000-7fb8a8568000 rw-p 0000d000 08:06 790636                     /home/goyo/radare2/libr/socket/libr_socket.so
7fb8a8568000-7fb8a856f000 r-xp 00000000 08:06 791143                     /home/goyo/radare2/libr/lang/libr_lang.so
7fb8a856f000-7fb8a876e000 ---p 00007000 08:06 791143                     /home/goyo/radare2/libr/lang/libr_lang.so
7fb8a876e000-7fb8a876f000 r--p 00006000 08:06 791143                     /home/goyo/radare2/libr/lang/libr_lang.so
7fb8a876f000-7fb8a8770000 rw-p 00007000 08:06 791143                     /home/goyo/radare2/libr/lang/libr_lang.so
7fb8a8770000-7fb8a8930000 r-xp 00000000 08:06 528682                     /lib/x86_64-linux-gnu/libc-2.23.so
7fb8a8930000-7fb8a8b30000 ---p 001c0000 08:06 528682                     /lib/x86_64-linux-gnu/libc-2.23.so
7fb8a8b30000-7fb8a8b34000 r--p 001c0000 08:06 528682                     /lib/x86_64-linux-gnu/libc-2.23.so
7fb8a8b34000-7fb8a8b36000 rw-p 001c4000 08:06 528682                     /lib/x86_64-linux-gnu/libc-2.23.so
7fb8a8b36000-7fb8a8b3a000 rw-p 00000000 00:00 0
7fb8a8b3a000-7fb8a8b52000 r-xp 00000000 08:06 528828                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7fb8a8b52000-7fb8a8d51000 ---p 00018000 08:06 528828                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7fb8a8d51000-7fb8a8d52000 r--p 00017000 08:06 528828                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7fb8a8d52000-7fb8a8d53000 rw-p 00018000 08:06 528828                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7fb8a8d53000-7fb8a8d57000 rw-p 00000000 00:00 0
7fb8a8d57000-7fb8a8e34000 r-xp 00000000 08:06 790619                     /home/goyo/radare2/libr/util/libr_util.so
7fb8a8e34000-7fb8a9034000 ---p 000dd000 08:06 790619                     /home/goyo/radare2/libr/util/libr_util.so
7fb8a9034000-7fb8a9036000 r--p 000dd000 08:06 790619                     /home/goyo/radare2/libr/util/libr_util.so
7fb8a9036000-7fb8a9045000 rw-p 000df000 08:06 790619                     /home/goyo/radare2/libr/util/libr_util.so
7fb8a9045000-7fb8a904f000 rw-p 00000000 00:00 0
7fb8a904f000-7fb8a9067000 r-xp 00000000 08:06 791251                     /home/goyo/radare2/libr/crypto/libr_crypto.so
7fb8a9067000-7fb8a9266000 ---p 00018000 08:06 791251                     /home/goyo/radare2/libr/crypto/libr_crypto.so
7fb8a9266000-7fb8a9267000 r--p 00017000 08:06 791251                     /home/goyo/radare2/libr/crypto/libr_crypto.so
7fb8a9267000-7fb8a9268000 rw-p 00018000 08:06 791251                     /home/goyo/radare2/libr/crypto/libr_crypto.so
7fb8a9268000-7fb8a9279000 rw-p 00000000 00:00 0
7fb8a9279000-7fb8a928b000 r-xp 00000000 08:06 798520                     /home/goyo/radare2/libr/egg/libr_egg.so
7fb8a928b000-7fb8a948a000 ---p 00012000 08:06 798520                     /home/goyo/radare2/libr/egg/libr_egg.so
7fb8a948a000-7fb8a948b000 r--p 00011000 08:06 798520                     /home/goyo/radare2/libr/egg/libr_egg.so
7fb8a948b000-7fb8a948c000 rw-p 00012000 08:06 798520                     /home/goyo/radare2/libr/egg/libr_egg.so
7fb8a948c000-7fb8a9493000 r-xp 00000000 08:06 791111                     /home/goyo/radare2/libr/flag/libr_flag.so
7fb8a9493000-7fb8a9692000 ---p 00007000 08:06 791111                     /home/goyo/radare2/libr/flag/libr_flag.so
7fb8a9692000-7fb8a9693000 r--p 00006000 08:06 791111                     /home/goyo/radare2/libr/flag/libr_flag.so
7fb8a9693000-7fb8a9694000 rw-p 00007000 08:06 791111                     /home/goyo/radare2/libr/flag/libr_flag.so
7fb8a9694000-7fb8a96a6000 r-xp 00000000 08:06 791042                     /home/goyo/radare2/libr/magic/libr_magic.so
7fb8a96a6000-7fb8a98a5000 ---p 00012000 08:06 791042                     /home/goyo/radare2/libr/magic/libr_magic.so
7fb8a98a5000-7fb8a98a6000 r--p 00011000 08:06 791042                     /home/goyo/radare2/libr/magic/libr_magic.so
7fb8a98a6000-7fb8a98a7000 rw-p 00012000 08:06 791042                     /home/goyo/radare2/libr/magic/libr_magic.so
7fb8a98a7000-7fb8a98b2000 r-xp 00000000 08:06 790948                     /home/goyo/radare2/libr/hash/libr_hash.so
7fb8a98b2000-7fb8a9ab1000 ---p 0000b000 08:06 790948                     /home/goyo/radare2/libr/hash/libr_hash.so
7fb8a9ab1000-7fb8a9ab2000 r--p 0000a000 08:06 790948                     /home/goyo/radare2/libr/hash/libr_hash.so
7fb8a9ab2000-7fb8a9ab3000 rw-p 0000b000 08:06 790948                     /home/goyo/radare2/libr/hash/libr_hash.so
7fb8a9ab3000-7fb8a9ab7000 r-xp 00000000 08:06 791182                     /home/goyo/radare2/libr/syscall/libr_syscall.so
7fb8a9ab7000-7fb8a9cb6000 ---p 00004000 08:06 791182                     /home/goyo/radare2/libr/syscall/libr_syscall.so
7fb8a9cb6000-7fb8a9cb7000 r--p 00003000 08:06 791182                     /home/goyo/radare2/libr/syscall/libr_syscall.so
7fb8a9cb7000-7fb8a9cb9000 rw-p 00004000 08:06 791182                     /home/goyo/radare2/libr/syscall/libr_syscall.so
7fb8a9cb9000-7fb8aa23c000 r-xp 00000000 08:06 795928                     /home/goyo/radare2/libr/asm/libr_asm.so
7fb8aa23c000-7fb8aa43c000 ---p 00583000 08:06 795928                     /home/goyo/radare2/libr/asm/libr_asm.so
7fb8aa43c000-7fb8aa4d0000 r--p 00583000 08:06 795928                     /home/goyo/radare2/libr/asm/libr_asm.so
7fb8aa4d0000-7fb8aa775000 rw-p 00617000 08:06 795928                     /home/goyo/radare2/libr/asm/libr_asm.so
7fb8aa775000-7fb8aa893000 rw-p 00000000 00:00 0
7fb8aa893000-7fb8aa8c7000 r-xp 00000000 08:06 791506                     /home/goyo/radare2/libr/fs/libr_fs.so
7fb8aa8c7000-7fb8aaac6000 ---p 00034000 08:06 791506                     /home/goyo/radare2/libr/fs/libr_fs.so
7fb8aaac6000-7fb8aaac7000 r--p 00033000 08:06 791506                     /home/goyo/radare2/libr/fs/libr_fs.so
7fb8aaac7000-7fb8aaac9000 rw-p 00034000 08:06 791506                     /home/goyo/radare2/libr/fs/libr_fs.so
7fb8aaac9000-7fb8aaad4000 rw-p 00000000 00:00 0
7fb8aaad4000-7fb8aab3b000 r-xp 00000000 08:06 791265                     /home/goyo/radare2/libr/io/libr_io.so
7fb8aab3b000-7fb8aad3a000 ---p 00067000 08:06 791265                     /home/goyo/radare2/libr/io/libr_io.so
7fb8aad3a000-7fb8aad3b000 r--p 00066000 08:06 791265                     /home/goyo/radare2/libr/io/libr_io.so
7fb8aad3b000-7fb8aad4a000 rw-p 00067000 08:06 791265                     /home/goyo/radare2/libr/io/libr_io.so
7fb8aad4a000-7fb8aad53000 rw-p 00000000 00:00 0
7fb8aad53000-7fb8aad58000 r-xp 00000000 08:06 791080                     /home/goyo/radare2/libr/bp/libr_bp.so
7fb8aad58000-7fb8aaf57000 ---p 00005000 08:06 791080                     /home/goyo/radare2/libr/bp/libr_bp.so
7fb8aaf57000-7fb8aaf58000 r--p 00004000 08:06 791080                     /home/goyo/radare2/libr/bp/libr_bp.so
7fb8aaf58000-7fb8aaf59000 rw-p 00005000 08:06 791080                     /home/goyo/radare2/libr/bp/libr_bp.so
7fb8aaf59000-7fb8aaf63000 r-xp 00000000 08:06 790990                     /home/goyo/radare2/libr/reg/libr_reg.so
7fb8aaf63000-7fb8ab162000 ---p 0000a000 08:06 790990                     /home/goyo/radare2/libr/reg/libr_reg.so
7fb8ab162000-7fb8ab163000 r--p 00009000 08:06 790990                     /home/goyo/radare2/libr/reg/libr_reg.so
7fb8ab163000-7fb8ab164000 rw-p 0000a000 08:06 790990                     /home/goyo/radare2/libr/reg/libr_reg.so
7fb8ab164000-7fb8ab62f000 r-xp 00000000 08:06 791882                     /home/goyo/radare2/libr/anal/libr_anal.so
7fb8ab62f000-7fb8ab82e000 ---p 004cb000 08:06 791882                     /home/goyo/radare2/libr/anal/libr_anal.so
7fb8ab82e000-7fb8ab846000 r--p 004ca000 08:06 791882                     /home/goyo/radare2/libr/anal/libr_anal.so
7fb8ab846000-7fb8abaa0000 rw-p 004e2000 08:06 791882                     /home/goyo/radare2/libr/anal/libr_anal.so
7fb8abaa0000-7fb8abba4000 rw-p 00000000 00:00 0
7fb8abba4000-7fb8abbd4000 r-xp 00000000 08:06 799129                     /home/goyo/radare2/libr/debug/libr_debug.so
7fb8abbd4000-7fb8abdd3000 ---p 00030000 08:06 799129                     /home/goyo/radare2/libr/debug/libr_debug.so
7fb8abdd3000-7fb8abdd4000 r--p 0002f000 08:06 799129                     /home/goyo/radare2/libr/debug/libr_debug.so
7fb8abdd4000-7fb8abdd6000 rw-p 00030000 08:06 799129                     /home/goyo/radare2/libr/debug/libr_debug.so
7fb8abdd6000-7fb8abf36000 r-xp 00000000 08:06 791879                     /home/goyo/radare2/libr/bin/libr_bin.so
7fb8abf36000-7fb8ac135000 ---p 00160000 08:06 791879                     /home/goyo/radare2/libr/bin/libr_bin.so
7fb8ac135000-7fb8ac137000 r--p 0015f000 08:06 791879                     /home/goyo/radare2/libr/bin/libr_bin.so
7fb8ac137000-7fb8ac140000 rw-p 00161000 08:06 791879                     /home/goyo/radare2/libr/bin/libr_bin.so
7fb8ac140000-7fb8ac145000 r-xp 00000000 08:06 791023                     /home/goyo/radare2/libr/config/libr_config.so
7fb8ac145000-7fb8ac345000 ---p 00005000 08:06 791023                     /home/goyo/radare2/libr/config/libr_config.so
7fb8ac345000-7fb8ac346000 r--p 00005000 08:06 791023                     /home/goyo/radare2/libr/config/libr_config.so
7fb8ac346000-7fb8ac347000 rw-p 00006000 08:06 791023                     /home/goyo/radare2/libr/config/libr_config.so
7fb8ac347000-7fb8ac365000 r-xp 00000000 08:06 791077                     /home/goyo/radare2/libr/cons/libr_cons.so
7fb8ac365000-7fb8ac564000 ---p 0001e000 08:06 791077                     /home/goyo/radare2/libr/cons/libr_cons.so
7fb8ac564000-7fb8ac565000 r--p 0001d000 08:06 791077                     /home/goyo/radare2/libr/cons/libr_cons.so
7fb8ac565000-7fb8ac566000 rw-p 0001e000 08:06 791077                     /home/goyo/radare2/libr/cons/libr_cons.so
7fb8ac566000-7fb8ac569000 rw-p 00000000 00:00 0
7fb8ac569000-7fb8ac56f000 r-xp 00000000 08:06 791066                     /home/goyo/radare2/libr/search/libr_search.so
7fb8ac56f000-7fb8ac76e000 ---p 00006000 08:06 791066                     /home/goyo/radare2/libr/search/libr_search.so
7fb8ac76e000-7fb8ac76f000 r--p 00005000 08:06 791066                     /home/goyo/radare2/libr/search/libr_search.so
7fb8ac76f000-7fb8ac770000 rw-p 00006000 08:06 791066                     /home/goyo/radare2/libr/search/libr_search.so
7fb8ac770000-7fb8ac7a7000 r-xp 00000000 08:06 791546                     /home/goyo/radare2/libr/parse/libr_parse.so
7fb8ac7a7000-7fb8ac9a6000 ---p 00037000 08:06 791546                     /home/goyo/radare2/libr/parse/libr_parse.so
7fb8ac9a6000-7fb8ac9a7000 r--p 00036000 08:06 791546                     /home/goyo/radare2/libr/parse/libr_parse.so
7fb8ac9a7000-7fb8ac9a8000 rw-p 00037000 08:06 791546                     /home/goyo/radare2/libr/parse/libr_parse.so
7fb8ac9a8000-7fb8ac9c9000 rw-p 00000000 00:00 0
7fb8ac9c9000-7fb8acba1000 r-xp 00000000 08:06 799214                     /home/goyo/radare2/libr/core/libr_core.so
7fb8acba1000-7fb8acda1000 ---p 001d8000 08:06 799214                     /home/goyo/radare2/libr/core/libr_core.so
7fb8acda1000-7fb8acda2000 r--p 001d8000 08:06 799214                     /home/goyo/radare2/libr/core/libr_core.so
7fb8acda2000-7fb8acdb5000 rw-p 001d9000 08:06 799214                     /home/goyo/radare2/libr/core/libr_core.so
7fb8acdb5000-7fb8acdb9000 rw-p 00000000 00:00 0
7fb8acdb9000-7fb8acddf000 r-xp 00000000 08:06 528654                     /lib/x86_64-linux-gnu/ld-2.23.so
7fb8acf93000-7fb8acfac000 r--s 00000000 08:06 796149                     /home/goyo/radare2/libr/asm/d/x86.sdb
7fb8acfac000-7fb8acfba000 rw-p 00000000 00:00 0
7fb8acfd3000-7fb8acfd4000 rw-p 00000000 00:00 0
7fb8acfd4000-7fb8acfd8000 r--s 00000000 08:06 791132                     /home/goyo/radare2/libr/syscall/d/linux-x86-32.sdb
7fb8acfd8000-7fb8acfdc000 r--s 00000000 08:06 791132                     /home/goyo/radare2/libr/syscall/d/linux-x86-32.sdb
7fb8acfdc000-7fb8acfde000 r--s 00000000 08:06 785866                     /home/goyo/Descargas/pwnable/secret/prueba2
7fb8acfde000-7fb8acfdf000 r--p 00025000 08:06 528654                     /lib/x86_64-linux-gnu/ld-2.23.so
7fb8acfdf000-7fb8acfe0000 rw-p 00026000 08:06 528654                     /lib/x86_64-linux-gnu/ld-2.23.so
7fb8acfe0000-7fb8acfe1000 rw-p 00000000 00:00 0
7ffd7ce98000-7ffd7ceb9000 rw-p 00000000 00:00 0                          [stack]
7ffd7cfdc000-7ffd7cfdf000 r--p 00000000 00:00 0                          [vvar]
7ffd7cfdf000-7ffd7cfe1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Abortado (`core' generado)

**Comment by thestr4ng3r** [comment]
Right now I can't reproduce it. Can you share the binary?

**Comment by radare** [comment]
try building with asan.

**Comment by thestr4ng3r** [comment]
@Goyo2600 ping

**Comment by Goyo2600** [comment]
it's a simple 32bits binary 
[prueba2.gz](https://github.com/radare/radare2/files/2112166/prueba2.gz)

**Comment by radare** [comment]
aka: just run sys/asan.sh

**Comment by Goyo2600** [comment]
yes, dmh is perfect now with sys/asan.sh
:+1:

**Comment by radare** [comment]
asan is way more picky. it should crash more than without asan.. so my guess is that you have built it wrongly somehow, try with sys/install.sh and if its not crashing then close the issue

**Comment by Goyo2600** [comment]
I've built it from a clean installation with sys/install.sh, and dmh is running correctly.
