### ISSUE TITLE
The implemented ROR and ROL algorithms are actually Shift (Right | Left)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#10408]
Using `woD ror ...` or `woD rol ...` performs [**logical** shifts](https://en.wikipedia.org/wiki/Logical_shift) and not [**circular** shifts](https://en.wikipedia.org/wiki/Circular_shift).
i.e it's not the equivalent of the `ROR` and `ROL` instructions.

The [current implementation](https://github.com/radare/radare2/blob/ef233e2bd5b7eaa5d75fe075881a98b1be0a4c39/libr/crypto/p/crypto_ror.c#L23) is simply a shift:
```
static void ror_crypt(struct ror_state *const state, const ut8 *inbuf, ut8 *outbuf, int buflen) {
	int i;
	for (i = 0; i < buflen; i++) {
		outbuf[i] = inbuf[i] >> state->key[i%state->key_size];
	}
}
```

While we expect something similar to this:
```
static void ror_crypt(struct ror_state *const state, const ut8 *inbuf, ut8 *outbuf, int buflen) {
	int i;
	for (i = 0; i < buflen; i++) {
		outbuf[i] = (inbuf[i] << key[i % state->key_size]) | (inbuf[i] >> (32 - key[i % state->key_size]));
	}
}
```

**Comment by radare** [comment]
why do you expect this? the help message states it clearly

| wor [val]                     >>= shift right
| wol [val]                     <<= shift left


shift != rotate

i would do worr and woll to implement the <<< and >>> bit rotation.

can u send a PR implementing this? it’s already done for ESIL

**Comment by ITAYC0HEN** [comment]
I'm not talking about `wor` and `wol` but on `woD`:

```
[0x00000000]> woD
Usage: woD [algo] [key] [IV]
Currently supported hashes:
  md5
  ...
  ...
  ...
Available Encoders/Decoders: 
  base64
  ...
  ...
Currently supported crypto algos:
  ...
  ...
  ror    <-------
  rol    <-------
  rot
  ...
  ...
```

It is saying "ror" and "rol" which stands for Rotate Right|Left. 
Also, the function's name is `ror_crypt` and not "shift_right_crypt" or something...

**Comment by radare** [comment]
right this is wrong. can you send a PR fixing libr/crypto/p/crypto_ror.c ?
