### ISSUE TITLE
Graph view doesn't handle unaligned opcodes

### ISSUE THREAD

**Issue by io12** [radare/radare2#10420]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux / x86_64 / 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18486 @ linux-x86-64 git.2.6.0-308-g3feb95079
commit: 3feb95079e7a28a43e0f5bbabc04405e0337da94 build: 2018-06-20__03:53:51

### Expected behavior

Expected behavior is for jumps/calls to unaligned opcodes to display the correct opcodes in the graph view.

### Actual behavior

Although doing `s <address_jumped_to>` works great in visual mode, in the graph view, the node after the jump shows the closest aligned opcode.

### Steps to reproduce the behavior 
```
radare2 888
aaaa
VV
gAb
# The selected node contains the incorrect opcode
<Space>
# Visual mode shows what it should be
```
[888.zip](https://github.com/radare/radare2/files/2117856/888.zip)

**Comment by io12** [comment]
Also there is this node in graph view:

```
╭─────────────────────────────────╮
│  0x8048247 ;[gv]                │
│ push 0x18149275                 │
│ sub dword [esp], 0x10101010     │
│ call 0x8048259;[gAb]            │
╰─────────────────────────────────╯
```

Running `ab` to show the basic block information of the called function:

```
[0x0804823f]> ab 0x8048259
jump: 0x080481db
fail: 0x0804825a
addr: 0x08048258
size: 2
inputs: 2
outputs: 2
ninstr: 1
traced: false
[0x0804823f]> 
```
Notice that the `addr` field is wrong.

**Comment by io12** [comment]
I investigated further and apparently the problem is with basic block analysis in `core_anal_bbs()`. The function iterates through the opcodes one by one to compute the basic blocks, which doesn't handle the case where there is a jump to the middle of an opcode.

**Comment by radare** [comment]
Works fine qith aab and other analysis loops. Theres another issue to trafk this already. Do you have time to fix it?

**Comment by io12** [comment]
I can try to fix it but I don't know the r2 codebase so well yet. Apparently `af` is the command that causes the problem.

**Comment by radare** [comment]
A quick test case for this issue:

```
wx b8210000c1ebfdbb2c0000000
af
agf
... crap happens ...
```
