### ISSUE TITLE
wrong esil for mov in v850

### ISSUE THREAD

**Issue by radare** [radare/radare2#10427]
```
0000           mov r0, r0
--->
zero,zero,=
```

**Comment by radare** [comment]
is r0 wired to the ground and always 0 like in mips? because everytime i see r0 in v850 i see zero in the esil.. which should 0, not zero, and anyways, this can be easily identified as a nop

**Comment by slovak194** [comment]
> is r0 wired to the ground and always 0 like in mips?

Yes, it is a "zero register" according to documentation.

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/11320

**Comment by radare** [comment]
do you mean that r0 is a zero register which is always 0? like in mips?

is the disasm wrong? or is r0 and zero the same register?

i did a PR adding support for wired-to-ground registers
