### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [radare/radare2#10435]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say? Also tell me if you want something. I can design.

**Comment by radare** [comment]
We already have a logo for radare. Thanks for the offer but thats not an issue for us right now

**Comment by XVilka** [comment]
I think maybe logo for radeco https://github.com/radareorg/radeco-lib can
be helpful.
