### ISSUE TITLE
System hangs while analysis

### ISSUE THREAD

**Issue by sivaramaaa** [radare/radare2#10443]
Recently I have noticed that analysis has become pretty slow and found that even a simple `aa` command utilizes 100% CPU and 100% of my RAM, I have to reboot my system to quit analysis :{

```
$ r2 ./vim (the bin from my attachment below)
[0x00055a40]> aaa
```
```
$ r2 ./issue_bin
[0x00404d88]> aaa
```

[issue_bins.zip](https://github.com/radare/radare2/files/2124684/issue_bins.zip)

It would be great if someone could re-produce this and verify the issue !

(**NOTE:** It was working fine a month ago !)

**Comment by radare** [comment]
Can u idntify which commit, or aproximated time this changed? We probably need a benchmark suite

**Comment by sivaramaaa** [comment]
I used `valgrind --tool=massif r2 ./vim` to check memory allocation and it seems most of memory consumption is from `setxrefs()` function

![r22](https://user-images.githubusercontent.com/18589720/41816804-e17a6c98-77ab-11e8-85f8-4a29be6960cd.png)

@ret2libc , check this thing whenever u have time (currently i am running out of time , so i couldn't get my hands dirty here sorry :{ ) : 

[log.txt](https://github.com/radare/radare2/files/2130550/log.txt)
[massif.out.16650.txt](https://github.com/radare/radare2/files/2130551/massif.out.16650.txt)

**Comment by sivaramaaa** [comment]
>We probably need a benchmark suite

@radare, yup definitely that's what i was talking about in tg :) 

I will try to implement this thing after gsoc !

**Comment by radare** [comment]
aab takes 20s, but sets 0 xrefs

**Comment by radare** [comment]
aar = 8s, and sets 67k xrefs,

**Comment by radare** [comment]
it doesnt seems that slow here, at least for issue_bin.

**Comment by sivaramaaa** [comment]
@radare sorry , but plsss **check `vim` bin** , that's what causing the computer to hang

> it doesnt seems that slow

also plss check the memory usage , i have 3GB RAM , and as it occupies the whole RAM  , my computer gets **hanged** , IMHO it's not really about speed rather about memory usage which ultimately causes system to hang

**Comment by radare** [comment]
Yes it takes 2.5gb of ram in here. Its a big binary so its not that strange to eat a lot of memory but i would probably think this is related to a memleak rather than acusing xrefs. Csn u share the memgrind logs and see if theres any?

**Comment by sivaramaaa** [comment]
>  i would probably think this is related to a memleak rather than acusing xrefs

yeah , it could be !

> Csn u share the memgrind logs and see if theres any?

Sure , I will try to look when i am free (Currently working on type inference)

**Comment by radare** [comment]
If anyone have time to chk this i would appreciate. Just having some logs may be enough for me to test

**Comment by sivaramaaa** [comment]
Isuue bin

[vim.zip](https://github.com/radare/radare2/files/2141796/vim.zip)

Logs

**Valgrind- memcheck log**

[memecheck_log.txt](https://github.com/radare/radare2/files/2141785/memecheck_log.txt)

**Valgrind - massif (a heap profiler)** -- this log shows large amount of GB used !

[massif_log.txt](https://github.com/radare/radare2/files/2141805/massif_log.txt)

@radare , i couldn't find any large amount of leak using the logs , so if u think it's just due to large no of xrefs and a normal behaviour , feel free to close the issue !

**Comment by sivaramaaa** [comment]
@Maijin i am reopening this coz it's just that i couldn't find any huge leak , but definetly there is a problem , even few people in #radare irc reported the same problem , so let's wait for @radare or @ret2libc to verify this issue ! (or in worst case i could check this after gsoc or so :} ...)

**Comment by radare** [comment]
I think its fixed in my aav pr. Nneed to finish it

**Comment by sivaramaaa** [comment]
Wow that's awesome <3

**Comment by Maijin** [comment]
ping @radare ? Isn't that done?

**Comment by XVilka** [comment]
@sivaramaaa can you please recheck it?

**Comment by radare** [comment]
im testing this right now and it does takes forever, but everything can be improved of course.

the slowest command here is `afta`. which is a "regression" introduced by the analysis improvements by @sivaramaaa . if we do more its obviously taking more time, but wen can probably find ways to optimize all that stuff

**Comment by XVilka** [comment]
Sounds right.

**Comment by ret2libc** [comment]
There's definitely something that can be done in many places to improve performances, but I'm ok with closing this and maybe just keep the binary for future testing.
