### ISSUE TITLE
Constrained types support

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10458]
Some types semantically have very limited set of possible values. Storing such kind of types can be beneficial for radare2 types and variables analyis. For example like "int < 250" or "char* [< 100]" where first is a type of integer that always less than 250, and a second - string which length is always less than 100 characters.
Especially those can be useful for initial analysis, when some library functions (or system calls) are known to return values limited somehow. Will make further autoanalysis easier.

**Comment by XVilka** [comment]
@sivaramaaa FYI

**Comment by radare** [comment]
Good idea. Are you using the sign information as hints too?

**Comment by sivaramaaa** [comment]
> @sivaramaaa FYI

yup this idea sounds great, i will check this once we have a decent type inference !

> Are you using the sign information as hints too?

@radare No not yet , but it's definitely planned for the next  PR !

**Comment by Maijin** [comment]
@sivaramaaa can you make a PR to try this with true?
