### ISSUE TITLE
bug with '-' on Visual Mode

### ISSUE THREAD

**Issue by XYlearn** [radare/radare2#10456]
Make sure you are testing using the latest git version of radare2 before submitting any issue.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu18.04 x86 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 3126 @ linux-x86-64 git.2.6.0-338-g31eeef02 commit: 31eeef0279fb934fc8fca8d9e89f0e543be1c51c build: 2018-06-23__22:02:27

### Expected behavior
visual mode zoom out

### Actual behavior
segmentation fault (core dumped)

### Steps to reproduce the behavior
[CrackMe.zip](https://github.com/radare/radare2/files/2129986/CrackMe.zip)
```
r2 -A CrackMe.exe
> VV
and then type '-'
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
all configurations is as default

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
Cant reproduce. My guess is that you have fuckedup your r2 installation

Can u make purge and sys/install again and if it crashes report q backtrace or crashlog at least to give us a hint

**Comment by XYlearn** [comment]
I `make uninstall` and `make purge`. then `sys/install.sh` to rebuild. but it still failed. The full log is a segmentation fault. I tried to debug it with gdb and get the final snapshot
Is it relative to my os?
```
$ uname -a
Linux l1nk.com 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
![image](https://user-images.githubusercontent.com/20752088/41816453-2b4768ce-77b8-11e8-9f9f-91c7c53c050e.png)

**Comment by cyanpencil** [comment]
> Is it relative to my os?

No, I can reproduce it too.
However it was a very easy fix, sending a pr to take care of it
