### ISSUE TITLE
Enable asm.imm.str by default?

### ISSUE THREAD

**Issue by radare** [radare/radare2#10473]
It's still not fully working, but in many cases, the strings are encoded as immediates

<img width="599" alt="screen shot 2018-06-24 at 23 02 00" src="https://user-images.githubusercontent.com/917142/41823598-9f365b38-7802-11e8-9b48-b2900d9ff4f8.png">

**Comment by radare** [comment]
also notice the screenshot, many strings are not detected

**Comment by radare** [comment]
cc @kazarmy

**Comment by radare** [comment]
bin is echo-bin

**Comment by kazarmy** [comment]
movabs insns don't have comments ... probably two separate issues here

**Comment by kazarmy** [comment]
oh only 1 issue here

**Comment by kazarmy** [comment]
If `asm.imm.str` is on by default, I think there is a need to differentiate between string comments that are the immediate value itself and string comments that are from dereferencing (i.e. `char []` vs `char *`). I think this can be done by showing dereferenced string comments as follows (no semicolon in the middle):
```
mov edi, str.Hello_World    ; 0x4005c4 "Hello World"
```
instead of:
```
mov edi, str.Hello_World    ; 0x4005c4 ; "Hello World"
```

**Comment by kazarmy** [comment]
lgtm ... not sure whether it's worth the extra 3 chars though

**Comment by kazarmy** [comment]
```
mov edi, str.Hello_World    ; 0x4005c4 &"Hello World"
```

hmmm ... a bit ugly ... i think i like the arrow better

**Comment by kazarmy** [comment]
nvm ... just found out that `asm.imm.str` strings use single quotes while dereferenced strings use double quotes ... that should be difference enough

**Comment by radare** [comment]
Yep sgtm

**Comment by radare** [comment]
ok
