### ISSUE TITLE
Improve display of switch / case flags in disasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#10474]
<img width="882" alt="screen shot 2018-06-24 at 22 43 09" src="https://user-images.githubusercontent.com/917142/41823612-e2332c90-7802-11e8-91d3-75db7b5b3558.png">

**Comment by radare** [comment]
i think we shuold check if flag statrs with 'case.' and then display ranges of values and display as a comment the address of the jmp, in this case, many jmptables are referencing the same basic block

**Comment by XVilka** [comment]
Agree with radare, showing it as `case [4-49]` instead makes much more sense. No even need for an address - since it is obviously the current one.
