### ISSUE TITLE
rahead2 and ratail2 tools

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10484]
Simple wrappers but very useful for day to day binary files inspection.
Rahead2 is supposed to behave as a `head -n` for example, printing hexdump for unknown files or disasm for recognized formats (or `rahead2 -nn` to always show hexdump).
Same for tail - to monitor the files change and print it in hexdump on a screen.

**Comment by XVilka** [comment]
why?

**Comment by Maijin** [comment]
You can add that in r2pm to add some alias in your path, imho enough cluttering core :S, we just successful got rid of ragg2-cc not to add more crap

**Comment by xarkes** [comment]
Yes I think we don't need to add another tool in core, maybe r2pm is a good option.

**Comment by XVilka** [comment]
@xarkes head/tail cannot handle hexdata, using xxd | tail is uberslow on big binaries. If every linux has xxd/hexdump, why to have hexview in radare2 then?

**Comment by xarkes** [comment]
I meant `head | xxd` or `tail | xxd`, I often use that and it suits my needs, that's why I see no point in having rahead2. Imho ratail2 is more interesting because it monitors file changes.
Anyway I still agree with Maijin, I don't think it's good to clutter Core more.

**Comment by radare** [comment]
If u want this implement head/tail as r2 commands and use r2 -qc to do that. But i dont think we want full posix system commands on top of r2

**Comment by XVilka** [comment]
Well, for head I use an alias like `r2 -qc "px 50"`, but for tail currently it is impossible, will require some changes in the core afaik.

**Comment by radare** [comment]
Why impossible?

Use ‘px 64@$s-64’

**Comment by XVilka** [comment]
OK, closing
