### ISSUE TITLE
rafind2 recursive search ability

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10485]
To search for hex sequences or expressions in all files in the directory, like `find .`

**Comment by radare** [comment]
Agree that will be useful

**Comment by sivaramaaa** [comment]
Can we close this issue , if it's implemented with this PR [#10552](https://github.com/radare/radare2/pull/10552)

**Comment by Maijin** [comment]
@sivaramaaa don't ask close it next time ;)

**Comment by sivaramaaa** [comment]
okk :)
