### ISSUE TITLE
Skip thready code if there's only 1 task running

### ISSUE THREAD

**Issue by radare** [radare/radare2#10506]
We may save a bunch of cycles with this
cc @thestr4ng3r

**Comment by radare** [comment]
also we want to reduce the amount of calls to r_cons_is_breaked() i think we can get rid of some

**Comment by thestr4ng3r** [comment]
Good point. I already have something in mind to reduce it, but I still have to think it through a bit.

**Comment by thestr4ng3r** [comment]
By the way, right now scheduling alway happens in a cyclic way in each r_cons_is_breaked() call, which can be extremely often.

It might be better to do it time-based, i.e. only schedule if the last scheduling is already some time ago. This could be easily implemented by saving the last scheduling time and checking the delta with r_sys_now() in r_core_task_schedule() and if it is still below a certain value, simply do nothing and go on. However, that would add a call to gettimeofday() each time. I am not sure how expensive that is.
