### ISSUE TITLE
what is going on in op

### ISSUE THREAD

**Issue by radare** [radare/radare2#10507]
<img width="473" alt="screen shot 2018-06-27 at 00 41 51" src="https://user-images.githubusercontent.com/917142/41943219-eade6cc8-79a2-11e8-86b9-db9602675a29.png">

**Comment by radare** [comment]
| op [fd]                   prioritize given fd (see also ob)

**Comment by radare** [comment]
only happens with 3, the other fds are set properly

**Comment by radare** [comment]
current problem is that only have lot of maps everytime we change the priority of a file with associated bininfo. the bug is in ob code (we also need to decide proper syntax for ob, obb and obo.

Comments are welcome

**Comment by radare** [comment]
cc @ret2libc @condret 

this is also very related to the RIOSection killification

**Comment by radare** [comment]
and the thing is. why we want to have multiple maps with the exact same info? i vote for avoiding dupped maps
<img width="570" alt="screen shot 2018-06-27 at 13 47 10" src="https://user-images.githubusercontent.com/917142/41973128-638cb69a-7a14-11e8-92bc-0ea30e784d14.png">

**Comment by ret2libc** [comment]
What's the test binary?
Anyway, I see a use case for duplicated maps, but they shouldn't be created for no reason. I think the user should be able to explicitly duplicated a map, but in this case it seems just a bug.

**Comment by radare** [comment]
> On 27 Jun 2018, at 14:34, Riccardo Schirone <notifications@github.com> wrote:
> 
> What's the test binary?
> 
Happens in any binary

> Anyway, I see a use case for duplicated maps, but they shouldn't be created for no reason. I think the user should be able to explicitly duplicated a map, but in this case it seems just a bug.
> 

Well its calling to reload all the bininfo which implies creating maps
