### ISSUE TITLE
Choosing basic block in minigraph VV.

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#10558]
Hello.
I want to suggest to add a feature for select basic block in minigraph-mode in "VV". For example via 1-9 key.
It will be very usable if we have a huge function graph. But now I need to choose some basic block through "tab" in sequence order.

**Comment by radare** [comment]
Its akready there. Just see the g thing.. but thats probably not shown minigraph view

**Comment by Maijin** [comment]
g is shown in minimap so it's already there :)

**Comment by Maijin** [comment]
You mean in the current basic block then ok then it makes sense to re-open.

**Comment by s0i37** [comment]
For example, its a /bin/true, and I want to jump to a BB in yellow circle:
![1](https://user-images.githubusercontent.com/22872513/42339593-dc924b7a-80a6-11e8-8df8-db81074101b5.png)
in same time my current BB is the top of this function. And I dont known gXX-number

**Comment by radare** [comment]
Cc @cyanpencil

**Comment by s0i37** [comment]
What? I have no any effect.
