### ISSUE TITLE
afl.

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10567]
It would be helpful to have a command `afl.` that behaved in the same way that `CC.` does, returning only those function definitions at the current position. Further, it would be beneficial also to have `afl.j` that would return the function definition in json for the current position.

**Comment by Maijin** [comment]
I believe you mean, the function informations not function definition as this is unrelated to afl role

**Comment by radare** [comment]
So you want to have afl. as an alias for afi, right?
