### ISSUE TITLE
MIPS function analysis works correctly in small example but not on longer binary

### ISSUE THREAD

**Issue by pastcompute** [radare/radare2#1057]
Hiya

I have been trying to do some more digging on that regression (#1039) I managed to introduce twice...
To recap, I have a binary that will not properly analyse and detect all functions, but it does when I hacked `fcn_recurse()` to keep going instead of returning after analysing a branch condition. But as you discovered, when that hack is in place, it seems to break analysis for all other files.

So I tried to isolate one of the functions that fails to detect properly.
Using the following with `radare2 -m 0x8060b5f8 malloc://144`:

    e asm.arch=mips
    e asm.bits=32
    e anal.depth=2
    wx 0000000000000000002e0500032e05000f00801021100000492d1808000082900800e003211080000000829007004010000000000016020003160200f8ff451000000000482d180801008424211000000800e003000000000000a290050040100100a524000082a00000a290552d1808010084240800e003000080a0000000000000000000000000
    af
    pdf

Produces correct output for this disassembly:

    [0x8060b5f8]> pd 36
                0x8060b4f8    00000000     nop
                0x8060b4fc    00000000     nop
    / (fcn) fcn.8060b500 80
    |           0x8060b500    002e0500     sll a1, a1, 0x18
    |           0x8060b504    032e0500     sra a1, a1, 0x18
    |       ,=< 0x8060b508    0f008010     beqz a0, 0x8060b548 ; (fcn.8060b500)
    |       |   0x8060b50c    21100000     move v0, zero
    |      ,==< 0x8060b510    492d1808     j 0x8060b524 ; (fcn.8060b500)
    |      ||   0x8060b514    00008290     lbu v0, 0(a0)
    |    .----> 0x8060b518    0800e003     jr ra
    |    | ||   0x8060b51c    21108000     move v0, a0
    |   .-----> 0x8060b520    00008290     lbu v0, 0(a0)
    |   ||,`--> 0x8060b524    07004010     beqz v0, 0x8060b544 ; (fcn.8060b500)
    |   ||| |   0x8060b528    00000000     nop
    |   ||| |   0x8060b52c    00160200     sll v0, v0, 0x18
    |   ||| |   0x8060b530    03160200     sra v0, v0, 0x18
    |   |`====< 0x8060b534    f8ff4510     beq v0, a1, 0x8060b518 ; (fcn.8060b500)
    |   | | |   0x8060b538    00000000     nop
    |   `=====< 0x8060b53c    482d1808     j 0x8060b520 ; (fcn.8060b500)
    |     | |   0x8060b540    01008424     addiu a0, a0, 1
    |     `---> 0x8060b544    21100000     move v0, zero
    |       |   ; JMP XREF from 0x8060b508 (fcn.8060b500)
    |       `-> 0x8060b548    0800e003     jr ra
    \           0x8060b54c    00000000     nop
    / (fcn) fcn.8060b550 36
    |           0x8060b550    0000a290     lbu v0, 0(a1)
    |  ,       ; JMP XREF from 0x8060b564 (fcn.8060b550)
    |- loc.8060b554 32
    | .,======< 0x8060b554    05004010     beqz v0, loc.8060b56c
    | ||        0x8060b558    0100a524     addiu a1, a1, 1
    | ||        0x8060b55c    000082a0     sb v0, 0(a0)
    | ||        0x8060b560    0000a290     lbu v0, 0(a1)
    | `=======< 0x8060b564    552d1808     j loc.8060b554
    |  |        0x8060b568    01008424     addiu a0, a0, 1
    |  |        ; JMP XREF from 0x8060b554 (fcn.8060b550)
    |- loc.8060b56c 8
    |  `------> 0x8060b56c    0800e003     jr ra
    \           0x8060b570    000080a0     sb zero, 0(a0)
                0x8060b574    00000000     nop
                0x8060b578    00000000     nop
                0x8060b57c    00000000     nop
                0x8060b580    00000000     nop
                0x8060b584    00000000     nop

FWIW, the second function there appears to be an implementation of `strcpy()`

However, when I instead load the entire binary and run `aa` the relevant section of disassembly fails to properly detect that `strcpy()` function, despite there presumably being calls to it detected as denoted by the `CALL XREF FROM` notations.

                0x8060b4f8    00000000     nop
                0x8060b4fc    00000000     nop
                ; CALL XREF from 0x8060bd1c (fcn.8060bb40)
                ; CALL XREF from 0x8060bbb4 (fcn.8060bb40)
                ; CALL XREF from 0x8060b830 (fcn.8060b620)
                ; CALL XREF from 0x8060b8dc (fcn.8060b620)
                ; CALL XREF from 0x8060b9b4 (fcn.8060b620)
                ; CALL XREF from 0x8060b6a4 (fcn.8060b620)
                ; CALL XREF from 0x80607f34 (fcn.8060793c)
    / (fcn) fcn.8060b500 80
    |           0x8060b500    002e0500     sll a1, a1, 0x18
    |           0x8060b504    032e0500     sra a1, a1, 0x18
    |       ,=< 0x8060b508    0f008010     beqz a0, 0x8060b548 ; (fcn.8060b500)
    |       |   0x8060b50c    21100000     move v0, zero
    |      ,==< 0x8060b510    492d1808     j 0x8060b524 ; (fcn.8060b500)
    |      ||   0x8060b514    00008290     lbu v0, 0(a0)
    |    .----> 0x8060b518    0800e003     jr ra
    |    | ||   0x8060b51c    21108000     move v0, a0
    |   .-----> 0x8060b520    00008290     lbu v0, 0(a0)
    |   ||,|    ; JMP XREF from 0x8060b510 (fcn.8060b500)
    |   ||,`--> 0x8060b524    07004010     beqz v0, 0x8060b544 ; (fcn.8060b500)
    |   ||| |   0x8060b528    00000000     nop
    |   ||| |   0x8060b52c    00160200     sll v0, v0, 0x18
    |   ||| |   0x8060b530    03160200     sra v0, v0, 0x18
    |   |`====< 0x8060b534    f8ff4510     beq v0, a1, 0x8060b518 ; (fcn.8060b500)
    |   | | |   0x8060b538    00000000     nop
    |   `=====< 0x8060b53c    482d1808     j 0x8060b520 ; (fcn.8060b500)
    |     | |   0x8060b540    01008424     addiu a0, a0, 1
    |     `---> 0x8060b544    21100000     move v0, zero
    |       |   ; JMP XREF from 0x8060b508 (fcn.8060b500)
    |       `-> 0x8060b548    0800e003     jr ra
    \           0x8060b54c    00000000     nop
    |           ; CALL XREF from 0x8060ba74 (fcn.8060b620)
    |           ; CALL XREF from 0x8060b91c (fcn.8060b620)
                0x8060b550    0000a290     lbu v0, 0(a1)
      .,======< 0x8060b554    05004010     beqz v0, 0x8060b56c
      ||        0x8060b558    0100a524     addiu a1, a1, 1
      ||        0x8060b55c    000082a0     sb v0, 0(a0)
      ||        0x8060b560    0000a290     lbu v0, 0(a1)
      `=======< 0x8060b564    552d1808     j 0x8060b554
       |        0x8060b568    01008424     addiu a0, a0, 1
       `------> 0x8060b56c    0800e003     jr ra
                0x8060b570    000080a0     sb zero, 0(a0)
                0x8060b574    00000000     nop
                0x8060b578    00000000     nop
                0x8060b57c    00000000     nop

I suspect there is some subtle bug in either `fcn_recurse()` or in `mips_anal.c` but I haven't found it yet...

**Comment by Maijin** [comment]
@pastcompute statut?

**Comment by radare** [comment]
ping @pastcompute

**Comment by radare** [comment]
hello? anyone here?

**Comment by pastcompute** [comment]
Hi, I haven't had occasion to use r2 for quite some time, so I don't know if this is still a problem or not. I'd suggest closing the bug if thats what you need, and a new one can be opened if the problem recurs
