### ISSUE TITLE
aflqj as ints

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10572]
Command `aflqj` outputs the integer values as hex strings in the list. For example:

```
aflqj
["0x0040000","0x0040020", ... ]
```

Given the JSON format, it would generally be preferable for the value to be in the actual integer values, not strings.

**Comment by radare** [comment]
Wonder if afljq

**Comment by radare** [comment]
Thats because who change that was using js :p

**Comment by radare** [comment]
You can send a one line pr from the github website instead of opening an issue
