### ISSUE TITLE
Hex data long literals

### ISSUE THREAD

**Issue by elouet** [radare/radare2#10608]
Please forgive my ignorance, but I could not find the answer anywhere in the documentation. I would like to know how to input arbitrary length hex binary literals on the command line. 
For instance, if you wish to compare a known SHA1 to a value some place in memory, it would be nice to be able to input something like
[0x00000468]> c \x43e1808e4308baf093556946552f4fabc05278d8
instead of having to insert \x all the way
[0x00000468]> c \x43\xe1\x80\x8e\x43\x08\xba\xf0\x93\x55\x69\x46\x55\x2f\x4f\xab\xc0\x52\x78\xd8

**Comment by vergil-SI** [comment]
I think you are looking for the cx command.

cx 43e1808e4308baf093556946552f4fabc05278d8

**Comment by elouet** [comment]
Right, sorry if that I missed it.
