### ISSUE TITLE
How to connect to GDB Server within r2 instance

### ISSUE THREAD

**Issue by SpenserStyles** [radare/radare2#10611]
Simple question.  I have created a project and have opened it in r2.  Within that instance how can I attach to a GDB server? I know I can connect at launch with "r2 -D gdb gdb://localhost:2331" but how can I do that within an r2 instance?

**Comment by radare** [comment]
Yes. In fact yoy dont need to use -D at all

In the shell use o gdb://... and then dL gdb. Asi set e cfg.debug=true

**Comment by XVilka** [comment]
Please write here, if there is something wrong with it. Closing the question as answered now.
