### ISSUE TITLE
ARM 32-bit Stack Alignment Emulation Errors

### ISSUE THREAD

**Issue by SpenserStyles** [radare/radare2#10631]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac 10.13.5 64-bit
| File format of the file you reverse (mandatory)      | BIN
| Architecture/bits of the file (mandatory)            | arm 32-bit cortex
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.9 18640 @ darwin-x86-64 git.2.6.9 commit: 159d16b34550f4a83ee496839981c8316339ac4d build: 2018-07-03__09:48:34

### Expected behavior
1. push instruction to store values in 4-byte aligned memory.

### Actual behavior
The push instruction stores register values in 64-byte aligned memory

### Steps to reproduce the behavior 
Emulate a push instruction for a arm 32-bit processor
```
ae -8,sp,=,r1,lr,2,sp,=[*]
```

This is caused by the #define BYTE_SIZE shown below

```
static int esil_poke_some(RAnalEsil *esil) {
	int i, ret = 0;
	int regsize;
	ut64 ptr, regs = 0, tmp;
	char *count, *dst = r_anal_esil_pop (esil);
// #define BYTES_SIZE 64   // THIS CAUSES THE error
#define BYTES_SIZE 4  // FIX for it work with ARM 32-bit Cortex-M
	if (dst && r_anal_esil_get_parm_size (esil, dst, &tmp, &regsize)) {
		// reg
		isregornum (esil, dst, &ptr);
		count = r_anal_esil_pop (esil);
		if (count) {
			isregornum (esil, count, &regs);
			if (regs > 0) {
				ut8 b[BYTES_SIZE];
				ut64 num64;
				for (i = 0; i < regs; i++) {
					eprintf("esil_poke ptr: 0x%X \n", ptr);
					char *foo = r_anal_esil_pop (esil);
					if (!foo) {
						// avoid looping out of stack
						free (dst);
						free (count);
						return 1;
					}
					isregornum (esil, foo, &num64);
					/* TODO: implement peek here */
					// read from $dst
					eprintf("esil_poke num: 0x%X \n", num64);
					r_write_ble (b, num64, esil->anal->big_endian, regsize);
					ret = r_anal_esil_mem_write (esil, ptr, b, BYTES_SIZE);
					if (ret != BYTES_SIZE) {
						//eprintf ("Cannot write at 0x%08" PFMT64x "\n", ptr);
						esil->trap = 1;
					}
					ptr += BYTES_SIZE;
					free (foo);
				}
			}
			free (dst);
			free (count);
			return 1;
		}
		free (dst);
	}
	return 0;
}

```

I fixed it for my current emulation of ARM by setting BYTE_SIZE to 4.  I think the proper fix is to make this BYTE_SIZE a configuration parameter or infer it from the arch.

**Comment by radare** [comment]
Dont paste code here just press the pencil button and make a pullreq so we can review and comment

**Comment by Maijin** [comment]
Use https://help.github.com/articles/editing-files-in-your-repository/
