### ISSUE TITLE
Add an option to disable aslr when debugging

### ISSUE THREAD

**Issue by Alkeryn** [radare/radare2#10640]
I'm running v2.7.0
the issue when debugging is that once the program is terminated, the whole file is "invalid"
ex main function etc

and the only way to "refresh" it is to do "oo" 
the issue with that is that we lose all breakpoints and debug utily
so isn't there a way to (optionally) disable aslr for debuging purpose
or doing auto reload and syncing previous breakpoints and data on the reloaded file ?

**Comment by radare** [comment]
Its already there

**Comment by ret2libc** [comment]
Use `rarun2` profiles or `radare2 -R aslr=no -d /bin/ls`

**Comment by Alkeryn** [comment]
Thanks
Though would be nice to be able to switch it from inside radare
Or even to debug with aslr enabled
But when you finished debuging
It reloads the file and paste the breakpoints of the previous file into the reopened one
