### ISSUE TITLE
r_core not found when installing r2pm plugin

### ISSUE THREAD

**Issue by cryptax** [radare/radare2#10642]
I am trying to install r2frida this time in a Docker container which is based on an Ubuntu 16.04.
I did `r2pm init`, `r2pm update`. Then I try `r2pm -i r2frida`. And it fails pretty quickly complaining it cannot find `r_core`. (see log below)

To my understanding, those are the radare2 core libraries? Why aren't they finding them? They're obviously there ;)

Home dir for radare2: `/opt/radare2`
That's what I have in `~/.local/share/radare2/r2pm`:
```
db  git  pkg
```

I tried to install another plugin (not r2frida) , and it seemed to work ok.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04.2 LTS
| File format of the file you reverse (mandatory)      | -
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | rradare2 2.7.0-git 18677 @ linux-x86-64 git.2.6.9-38-gb9ce57d commit: b9ce57d68d57c9e9689859baae7fae972d2f5351 build: 2018-07-06__11:37:48

### Expected behavior

Install r2frida. Though in that case, the issue seems to be with r2pm?

### Actual behavior

```
# r2pm -i r2frida
Already up-to-date.
Install Done For r2frida
Makefile:1: config.mk: No such file or directory
./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr/local'
checking for c compiler... gcc
checking for c++ compiler... g++
ERROR: Cannot find PKGCONFIG pkg-config
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... no
This package is required
Makefile:128: recipe for target 'config.mk' failed
make: *** [config.mk] Error 1
ERROR: Build failed
```

### Steps to reproduce the behavior 

In a Docker container, clone radare2. Then install with `sys/install.sh`. Then `r2pm init`, then `r2pm -i r2frida`

**Comment by radare** [comment]
It cant find rcore because you don’t have pkgconfig installed

**Comment by cryptax** [comment]
ah yes - sorry. Stupid :(

**Comment by fr33k3v1n0** [comment]
i have the same error and pkg-config is already installed

**Comment by trufae** [comment]
How did you installed r2? Distros use to ship the pkgconfig files separately

**Comment by fr33k3v1n0** [comment]
hello. it work now. i deinstalled radare2  and reinstall it from GitHub.
Thank you very much . Good bless you.
