### ISSUE TITLE
pd output incorrect with default disassembler

### ISSUE THREAD

**Issue by Alvinna** [radare/radare2#10665]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | arch x86 64
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            |  x86/64
|  full output, **not truncated** (mandatory)     | radare2 2.6.0 0 @ linux-x86-64 git.2.6.0
commit: HEAD build: 2018-05-23__01:38:10

### Expected behavior

;run pd @main 
;should output something like below

push rbp
mov rbp,rsp
mov edx,0x1000000
mov esi 0x90

### Actual behavior

|           0x00000615      55             push rbp
|           0x00000616  ~   4889e5         mov rbp, rsp
            ;-- section_end..symtab:
|           0x00000618      e5ba           in eax, -0x46
|           0x0000061a      0000           add byte [rax], al
|           0x0000061c      0001           add byte [rcx], al
|           0x0000061e      be90000000     mov esi, 0x90               ; int c

;The byte 'e5' is repeated, which result in incorrect result.
;The output of px is correct.

### Steps to reproduce the behavior 

Use r2 to open the binary, and run pd @main.
asm.arch is x86
asm.bits is 64

### Additional Logs, screenshots, source-code,  configuration dump, ...

[dummy.zip](https://github.com/radare/radare2/files/2173341/dummy.zip)

I'm new to r2 so if it's not a bug plz tell me. >_>
Really hope it can be an opensource alternative to IDA Pro in the future.  ♡♡♡

**Comment by radare** [comment]
you can remove the flags with f-section*

**Comment by Alvinna** [comment]
Well, removing the flags produce the correct output. :)
So it's the problem of misplacing section_end ?
Even it is on the edge of a section, should this happened ? I mean repeating bytes ?
\>_>

**Comment by radare** [comment]
well the section_end flags should be killed because now flags have a size attribute, and that should be enough for those uses. dunno if theres an issue opened, but i remember discussing this a year ago or so

wanna try sending a patch for this?

**Comment by Alvinna** [comment]
Well, actually I never look into the source code of radare2, only trying out using it. I don't think I'll be able to do that at this moment \<_<

**Comment by radare** [comment]
I did a pr removing the end flags already

**Comment by kazarmy** [comment]
Reproducible via:
```
$ r2 zip://dummy.zip//dummy
 -- We are surrounded by the enemy. - Excellent, we can attack in any direction!
[0x00000530]> f sym.corrupted @ 0x618
[0x00000530]> pd 6 @ main
            ;-- main:
            0x00000615      55             push rbp
            0x00000616  ~   4889e5         mov rbp, rsp
            ;-- sym.corrupted:
            0x00000618      e5ba           in eax, 0xba
            0x0000061a      0000           add byte [rax], al
            0x0000061c      0001           add byte [rcx], al
            0x0000061e      be90000000     mov esi, 0x90
```
Reopening.

**Comment by ret2libc** [comment]
I'm not sure how we should consider this... what's the real issue? It is a "feature" that if you have a flag in the middle, it tries to realign (because `asm.flags.middle=2`). If you don't want that you can set asm.flags.middle=0 or 1.

**Comment by kazarmy** [comment]
Oh ok then.
