### ISSUE TITLE
V! disassembly window not updating

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10670]
From the lastest docker build, when I open a binary for debugging and do `V!`, then step using `F8`, the main disassembly window does not update. The side panels will update and r2 is clearly stepping, but the disassembly window (the main one in `V!`) does not update anymore.

**Comment by radare** [comment]
Works for me if i step wirh the s key

**Comment by Vane11ope** [comment]
done for F keys too

https://github.com/radare/radare2/pull/10680
