### ISSUE TITLE
Selecting "Info", "Sections", "Database", etc in visual panels breaks panels

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10681]
It doesn't place the information in the panel, also it doesn't redraw the panel, which produces crap on the screen.
![screenshot_20180709_150809](https://user-images.githubusercontent.com/203261/42435717-f98cce4a-8389-11e8-9302-aa476fc84229.png)

**Comment by Vane11ope** [comment]
guess this has been done with this which was already merged.

https://github.com/radare/radare2/pull/10707

**Comment by cyanpencil** [comment]
Can confirm that this is fixed now thanks to #10707. Closing.
