### ISSUE TITLE
rasm2 x86 encoding problems

### ISSUE THREAD

**Issue by skuater** [radare/radare2#10697]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x86 32,
| File format of the file you reverse (mandatory)      | 
| Architecture/bits of the file (mandatory)            | inte,l x86/32, x86/64 
| r2 -v full output, **not truncated** (mandatory)     | rasm2 2.8.0-git 18906 @ windows-x86-32 git.0.9.9-10545-g4d91eb25e commit: 4d91eb25e1eded7698d7d7146ca7fb533668aa79 build: 09/07/2018__19:31:51,37

### Expected behavior
rasm2 -a x86 -b 32 "rep movsd"
f3a5

rasm2 -a x86 -b 32 "rep movsb"
f3a4

rasm2 -a x86 -b 32 "rep movsw"
f366a5

rasm2 -a x86 -b 32 "mov [eax],0"
c70000000000

### Actual behavior
rasm2 -a x86 -b 32 "rep movsd"
Cannot assemble 'rep movsd' at line 3
invalid

rasm2 -a x86 -b 32 "rep movsb"
Cannot assemble 'rep movsb' at line 3

rasm2 -a x86 -b 32 "rep movsw"
Cannot assemble 'rep movsw' at line 3
invalid

rasm2 -a x86 -b 32 "mov [eax],0"
Cannot assemble 'mov [eax],0' at line 3
invalid

### Notes

Last example work if we use: 
  rasm2 -a x86 -b 32 "mov dword [eax],0"
  c70000000000

Actual state made unusable last years r2warriors, we need define how must be encode.

**Comment by radare** [comment]
this is important, and it's a regression
