### ISSUE TITLE
When open an editor for types with `to -` set filetype

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10701]
To get the syntax highlight in case of vim or nano for example. Easiest way I think is to add ".h" file extension when create tmp file.

**Comment by sivaramaaa** [comment]
nice idea :+1:  :)

**Comment by radare** [comment]
fixed in https://github.com/radare/radare2/pull/10703

**Comment by sivaramaaa** [comment]
> fixed in #10703 

Awesome <3
