### ISSUE TITLE
Some nop operations break fcnlines

### ISSUE THREAD

**Issue by cyanpencil** [radare/radare2#10711]
![issue](https://user-images.githubusercontent.com/3428362/42608410-ddc2f1d0-8587-11e8-9787-555086b49a51.png)

Open any binary to test. Not every "nop" operation will break them, but it happens quite frequently.

**Comment by XVilka** [comment]
Afaik @radare said it was maid on purpose, but yes, it indeed not very beautiful.

**Comment by radare** [comment]
This is known and on purpose because those nops are not covered by any basic block.

**Comment by cyanpencil** [comment]
Oh, ok.
But, it happens to only some of them. If you see the screen, there are some nops that don't break them

**Comment by cyanpencil** [comment]
(deleted my latest message bc I didn't understand what you wrote)
Thanks, and sorry for the trouble, I'll close the issue then!
