### ISSUE TITLE
Line graph not correctly

### ISSUE THREAD

**Issue by d4em0n** [radare/radare2#10719]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 32bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18877 @ linux-x86-64 git.2.7.0-20-g8db9631c9 commit: 8db9631c98b7792199c366bbda5cc3a6d5db6762 build: 2018-07-12__16:54:01

### Expected behavior
radare2 show line from `jle 0x804851f` to `0x804851f [gj]` graph blocks
![screenshot_20180712_202013](https://user-images.githubusercontent.com/29397847/42636019-e4475fac-8611-11e8-8c98-8dfd3877dd62.png)

### Actual behavior
![screenshot_20180712_202013](https://user-images.githubusercontent.com/29397847/42635735-0cde246a-8611-11e8-845c-4565857d8831.png)

### Steps to reproduce the behavior 
```
$ r2 -A ./check
:> s 0x8048550
:> VV
```
### Additional Logs, screenshots, source-code,  configuration dump, ...
[check.zip](https://github.com/radare/radare2/files/2188740/check.zip)

**Comment by radare** [comment]
the analysis info seems correct and i can reproduce the same bug with different analysis algorithms, so it seems like a render issue, but didnt had time to dig further. maybe @cyanpencil can have a look at it
