### ISSUE TITLE
[DEBUGGER] Get address of a library symbol

### ISSUE THREAD

**Issue by andreafioraldi** [radare/radare2#10726]
Hi, how can i print the address of a library symbol?
For example i loaded /bin/ls in the debugger and i want to know the address of printf in the libc.

**Comment by radare** [comment]
see the dmi command

i think it’s documented in the book. @xvilka can you confirm all this is there?

**Comment by andreafioraldi** [comment]
Thanks!

> i think it’s documented in the book.

I didn't find it in the book, but I can be wrong.

**Comment by XVilka** [comment]
It will be :)
