### ISSUE TITLE
Error: "trace_pc: cannot read memory at 0xffffffffs (afta)"

### ISSUE THREAD

**Issue by yasong** [radare/radare2#10724]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux Ghost 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | PPC
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 0 @ linux-x86-64 git.2.8.0-git commit: HEAD build: 2018-07-13__07:33:57

### Actual behavior
```
[trace_pc: cannot read memory at 0xffffffffs (afta)
trace_pc: cannot read memory at 0xffffffff
trace_pc: cannot read memory at 0x0
trace_pc: cannot read memory at 0xffffffff
trace_pc: cannot read memory at 0xffffffff
trace_pc: cannot read memory at 0x0
trace_pc: cannot read memory at 0x4
trace_pc: cannot read memory at 0x8
trace_pc: cannot read memory at 0xc
trace_pc: cannot read memory at 0xffffffff
trace_pc: cannot read memory at 0x0
trace_pc: cannot read memory at 0x4
trace_pc: cannot read memory at 0x8
trace_pc: cannot read memory at 0xc
trace_pc: cannot read memory at 0x10
trace_pc: cannot read memory at 0x14
trace_pc: cannot read memory at 0x18
trace_pc: cannot read memory at 0x1c
```
### Steps to reproduce the behavior 
r2 -AA [PPC elf File]

**Comment by sivaramaaa** [comment]
Hey hi , i will try to fix this issue today !
