### ISSUE TITLE
Segfault notification in visual

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10731]
So when you are manually stepping (in my case, F8), in `V!` and `VV` mode, when you hit a signal (Segfault), the only indication you get is that the step doesn't continue. It would be nice if there were some indication to the user that this happened.

When stepping or running via the command line, this happens through the user getting a text warning of the segfault. However, that warning doesn't show when stepping in visual modes.

**Comment by radare** [comment]
it can be improved by moving this logic intot he visual mode status line, feel free to add comments, suggest better ideas or submit fixes for it

thanks
