### ISSUE TITLE
r2 periodically tries to open sysregs sdb that doesn't exist

### ISSUE THREAD

**Issue by pelijah** [radare/radare2#10737]
https://github.com/radare/radare2/blob/master/libr/syscall/syscall.c#L120

**Comment by Maijin** [comment]
Link to https://github.com/radare/radare2/issues/8467

**Comment by ret2libc** [comment]
I'm closing this. Please reopen if it's still wrong.

**Comment by Maijin** [comment]
It's still problem as far i know @ret2libc

**Comment by radare** [comment]
yes it is, and cant be fixed for 3.0, but must be fixed soon or late because it will speedup emulation and many other actions that end up resulting in many sdb reloads

**Comment by radare** [comment]
just put a printf there and you'll see

**Comment by ret2libc** [comment]
I tried to reload only when something actually changes (only if arch or os or bits, etc. change) but it is reloaded a couple of times at least anyway. I'll do a PR.
