### ISSUE TITLE
Add --asan to sys/meson.py

### ISSUE THREAD

**Issue by radare** [radare/radare2#10745]
To set some vars like

```
CFLAGS="-O0 -ggdb -fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-O0 -ggdb -fsanitize=address -fno-omit-frame-pointer" CPPFLAGS="-O0 -ggdb -fsanitize=address -fno-omit-frame-pointer" CXXFLAGS="-O0 -ggdb -fsanitize=address -fno-omit-frame-pointer" meson build
```

see sys/asan.sh for more details

**Comment by ret2libc** [comment]
or just a meson target or a meson option, without the need for a separate helper script.

**Comment by radare** [comment]
Or do both things

**Comment by ret2libc** [comment]
The problem with doing the same thing in multiple ways is that you either automatically test both configuration *always* or you'll end up easily with one configuration that works and the other that is outdated, creating even more confusion IMHO.

**Comment by radare** [comment]
Wtf?

Im refering to have this in meson as a target as u said and just handle the —asan flag to make that happen in the meson land. Theres onlh 1 implementation here

**Comment by ret2libc** [comment]
ok then.

**Comment by maxsond** [comment]
I was looking at taking this task since it was a good first issue, but it looks like you beat me to the punch: 

https://github.com/radare/radare2/commit/f04057cae467cc9597a30cdc46113216dda4464e#diff-fe95da098868b2377f9962e9d43be6b8

Anything left to do on this one, or should it be closed?

**Comment by radare** [comment]
This must be done in the meson.build and call it from the py like -D asan

Cc @ret2libc

**Comment by radare** [comment]
Sounds good to me if it works. Didnt knew about it

Also wonder why a build system should have builtin features that depend on compiler and system :D

**Comment by ret2libc** [comment]
> Hmm what about meson's builtin -Db_sanitize=address option?

Wow, I didn't know about it!

**Comment by Maijin** [comment]
@pelijah can you add that in a PR?

**Comment by MaskRay** [comment]
I think `sys/asan.py` should just be removed.

Under GCC, `-fsanitize=address` used as a link option adds `-lasan` and pulls in `libasan_preinit.o`. `-lasan` should not be used by the user.

**Comment by pelijah** [comment]
@Maijin You can already use this option.

meson:
`meson . build -Db_sanitize=address`

sys/meson.py
`python sys/meson.py --options b_sanitize=address`

**Comment by radare** [comment]
Feel free to improve the meson.py to include those flags
