### ISSUE TITLE
r2 -q - - - vs r2 - - -

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#10753]
`r2 - - -`
[0x00000000]> o
 3 * rwx 0x00000200 malloc://512
`r2 -q - - -`
(type o and enter)
 3 - rwx 0x00000200 malloc://512
 4 - rwx 0x00000200 malloc://512
 5 * rwx 0x00000200 malloc://512

wtf https://www.youtube.com/watch?v=3sXQoGcMN1U

**Comment by radare** [comment]
man r2

**Comment by radare** [comment]
Sorry missread :D

**Comment by Maijin** [comment]
lol

**Comment by radare** [comment]
Fixed
