### ISSUE TITLE
Visual panel for C output mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10754]
Should show C output panel from r2dec or radeco-lib.
This way we can even reuse `shlr/tcc` for parsing and highlighting the C code

**Comment by XVilka** [comment]
@cyanpencil if you have any suggestions here - please write them.

**Comment by Vane11ope** [comment]
https://github.com/radare/radare2/pull/10781
https://github.com/radare/radare2/pull/10788

they would do the job so im closing this.
