### ISSUE TITLE
Implement x86 asm cdq

### ISSUE THREAD

**Issue by elicn** [radare/radare2#10776]
The x86 assembly instruction `cdq` (opcode 99h; extending `eax` to `edx:eax`) is not recognized by r2, and ESIL marks it as TODO.

**Comment by NotSoOld** [comment]
Could you please provide binary where this issue appears?

**Comment by radare** [comment]
Just assemble cdq

**Comment by Maijin** [comment]
it's 99h as already said

**Comment by Maijin** [comment]
ok so that's neither an assembly nor disassembly issue as it's recognized by both. That's only ESIL issue (TODO)
