### ISSUE TITLE
Function listing (afl) is (sometimes) too slow

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#10770]
`afl` calls `fcnlist_gather_metadata` which computes the number of references, and this can take a lot of time.
Imho the number of references should be saved somewhere, and only be updated when needed.

**Comment by Maijin** [comment]
afl vs afll, you can probably move that to only afll

**Comment by radare** [comment]
It was easier to fix than to fill an issue

**Comment by xarkes** [comment]
Yes but I didn't know moving it to `afll` was a good idea or not.

**Comment by radare** [comment]
a PR will do
