### ISSUE TITLE
When stoped the analysis cannot be relaunched

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#1078]
On this binary when performing a : `r2 ls` then `aa` then `^C` then `aa` the analysis is not relaunched.

http://www.speedyshare.com/JJT8S/ls
`c8f5032c2dce807c9182597082b94f01a3bec495` (ls)

**Comment by XVilka** [comment]
@radare lemonboy branch RIP.

**Comment by XVilka** [comment]
@Maijin Can you please recheck and craft a testcase based on that?

**Comment by XVilka** [comment]
Sorry, you right, depends on sdbtization heavily.

**Comment by Maijin** [comment]
Yep this doesn't seem reproducible.
