### ISSUE TITLE
x86 string operations prefix taken as instruction mnemonic

### ISSUE THREAD

**Issue by elicn** [radare/radare2#10800]
x86 string operations prefixes are erroneously taken as the instruction mnemonic; for example:
In `repe cmpsb byte [rsi], byte ptr [rdi]`, the `repe` prefix is taken as the instruction mnemonic instead of `cmpsb`. This can be observed by executing `aoj` on such an instruction, or executing: `r2 -a x86 -b 64 -c "a8 f3 a6" -Q --`

**Comment by radare** [comment]
Good spot

**Comment by elicn** [comment]
Speaking of which, string operations are the only place where a `ptr` token follows the memory access qualifier [`byte`, `qword`, `xmmword`, etc.]; to be exact, it is only on the 2nd operand - see the example above. Although this inconsistency is not a functional bug, it could break parsers that won't expect it.

**Comment by radare** [comment]
You can use the opex field of aoj. Please confirm this is correct

**Comment by elicn** [comment]
`aoj` opex seems to work fine; however `aoj` also consists of:

> "opcode": "repe cmpsb byte [rsi], byte **ptr** [rdi]",
> "disasm": "repe cmpsb byte [rsi], byte **ptr** [rdi]",
> "mnemonic": "repe",
>

**Comment by radare** [comment]
can you please add a test case for this? cc @Maijin
