### ISSUE TITLE
[META] Improvements for people with eyesight problems

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10825]
As it is known radare2 has some userbase who chose it because of easiness to use with braille screens, high-contrast setups and speech recognition. In this bug we will collect all complains and suggestions on how improve those users experience.

- [x] Use "t" and "f" labels for graph edge lines in case of conditional jumps.

**Comment by XVilka** [comment]
@cyanpencil can you please return "t" and "f" hights for the graph edges. Maybe that can be disabled with "e graph.hints=false"

**Comment by XVilka** [comment]
@Maijin why close it? It is supposed to be big META issue, to be extended and expanded, preferably by the target audience.

**Comment by Maijin** [comment]
There is nothing there todo anymore please add checkboxes and stuff to do then reopen otherwise it's just adding up on the 1k issues.
