### ISSUE TITLE
Checksum Mismatch! Could not connect to windbg Segmentation fault

### ISSUE THREAD

**Issue by visce** [radare/radare2#10833]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | 4.17.9-1-ARCH arm 64
| File format of the file you reverse (mandatory)      | sudo r2 -a x86 -b 32 -D windbg windbg:///tmp/win10.pipe
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     |   radare2 -v radare2 2.8.0-git 18851 @ linux-x86-64 git.2.7.0-164-g79bfcd8f6 commit: 79bfcd8f6efa2efaa14fb9662eef658e4a9f2e2d build: 2018-07-27__11:23:10
### Expected behavior
I expected a prompt for debugging. This is also a fresh install.
### Actual behavior
$ sudo r2 -a x86 -b 32 -D windbg windbg:///tmp/win10.pipe 
[sudo] password for *****
Opened pipe /tmp/win10.pipe with fd 0x6
Checksum mismatch!
Could not connect to windbg
Segmentation fault

### Steps to reproduce the behavior 
Start up virtual machine, and use  sudo r2 -a x86 -b 32 -D windbg windbg:///tmp/win10.pipe to connect to the pipe. Debugging is enabled.

### Additional Logs, screenshots, source-code,  configuration dump, ...
![r2 windbgerror](https://user-images.githubusercontent.com/38126953/43335362-b8fd08d4-91be-11e8-9ec4-a1060d840a52.png)
![virtualbox serial port information](https://user-images.githubusercontent.com/38126953/43335386-bde9d17e-91be-11e8-8be6-6b26e3f9a614.png)

**Comment by radare** [comment]
Wheres the crashlog?

You can just use -d windbg://... no need to use -D plugname plugname://path

**Comment by visce** [comment]
What's the command to check the crashlog?

**Comment by radare** [comment]
Compile r2 with asan or run it with valgrind or gdb to show the backtrace, regstateetc

**Comment by visce** [comment]
I left the $ sudo r2 -a x86 -b 32 -d windbg:///tmp/win10.pipe
going for about an hour, and a half. It still didn't finish to the error whilst being debugged. Here is the only bt I could get before the error. Thanks for the help!
(gdb) bt
#0  0x00007fba5f550197 in select () from /usr/lib/libc.so.6
#1  0x00007fba61e4ee2f in iob_pipe_read (p=0x6, buf=0x556af0cf5041 "", 
    count=49103, timeout=100) at iob_pipe.c:84
#2  0x00007fba61e4c36f in iob_read (fp=0x6, buf=0x556af0cf2010 "", 
    buf_len=61440) at transport.c:87
#3  0x00007fba61e4f243 in kd_read_packet (fp=0x6, p=0x7ffc6e775590) at kd.c:97
#4  0x00007fba61e4c894 in windbg_wait_packet (ctx=0x556af0cd9a90, type=6, 
    p=0x0) at windbg.c:217
#5  0x00007fba61e4db7e in windbg_sync (ctx=0x556af0cd9a90) at windbg.c:655
#6  0x00007fba62ee6224 in r_debug_windbg_attach (dbg=0x556af0c68220, pid=-6)
    at p/debug_windbg.c:116
#7  0x00007fba62ed3e65 in r_debug_attach (dbg=0x556af0c68220, pid=-6)
    at debug.c:429
#8  0x00007fba63d6e703 in cmd_debug_pid (core=0x556aeeb71580 <r>, 
    input=0x556af0cd80d1 "pa -6") at cmd_debug.c:1050
#9  0x00007fba63d874b3 in cmd_debug (data=0x556aeeb71580 <r>, 
    input=0x556af0cd80d1 "pa -6") at cmd_debug.c:4665
#10 0x00007fba63e43ee1 in r_cmd_call (cmd=0x556af0c37fd0, 
    input=0x556af0cd80d0 "dpa -6") at cmd_api.c:237
#11 0x00007fba63dfa336 in r_core_cmd_subst_i (core=0x556aeeb71580 <r>, 
    cmd=0x556af0cd80d0 "dpa -6", colon=0x0, tmpseek=0x7ffc6e776c16)
    at cmd.c:2911
#12 0x00007fba63df6e96 in r_core_cmd_subst (core=0x556aeeb71580 <r>, 
    cmd=0x556af0cd80d0 "dpa -6") at cmd.c:1940
#13 0x00007fba63dfca9b in r_core_cmd (core=0x556aeeb71580 <r>, 
    cstr=0x7ffc6e776d20 "dpa -6", log=0) at cmd.c:3615
#14 0x00007fba63dfd1a3 in r_core_cmdf (user=0x556aeeb71580 <r>, 
    fmt=0x7fba63ecb3f7 "dpa %d") at cmd.c:3773
#15 0x00007fba63e19bc9 in r_core_setup_debugger (r=0x556aeeb71580 <r>, 
    debugbackend=0x556af0cbc360 "windbg", attach=true) at cio.c:24
#16 0x0000556aee96dd11 in main (argc=7, argv=0x7ffc6e778238, 
    envp=0x7ffc6e778278) at radare2.c:1216

**Comment by radare** [comment]
This seems more like a sigpipe than a sigsegv. Run cont and wait for the segfault to happen or build with sys/asan.sh or sys/meson.sh —asan

**Comment by visce** [comment]
What would be the process of debugging with meson? I've never used it to debug before. Unless you're talking about building radare2 again with meson, then grabbing the debug build, and posting it. Just need a little more elucidation on the issue, thanks!

**Comment by radare** [comment]
Meson is a build system, alternative to make. Not a debugger. Just build with asan like i said and paste the crashlog after connecting to the windbg target

**Comment by radare** [comment]
PING

**Comment by visce** [comment]
Thanks for your help I've gotten the issue resolved now. I had to install vmware-workstation instead of virtualbox, and it works.

**Comment by yssource** [comment]
It is the problem about virtualbox, isn't it?
The same issue happened to me also, and I ran it with virtualbox.

My guest machine is winXP 32bit.

![iii](https://user-images.githubusercontent.com/3756334/45833701-e35a5880-bd37-11e8-8633-2ee7b215e29f.png)

**Comment by Maijin** [comment]
@yssource This has been closed on August 3rd, open a new issue please.
