### ISSUE TITLE
V not working when running with background tasks

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10839]
I'm writing a plugin for r2. It kicks off a background process to monitor redis and update via http coms the main process. For some reason, even apparently without the background process having any interaction, `V`, `VV`, `VVV`, and `V!` all stop working. They work for the first few seconds of execution, but then they simply don't work. No errors. No nothing, just return without going into visual mode.

Any thoughts on why this would be happening? How to debug why `V` doesn't return anything? `V?` doesn't either.

**Comment by thestr4ng3r** [comment]
The entrypoint for `V` commands is https://github.com/radare/radare2/blob/master/libr/core/cmd.c#L1282-L1301
What exactly are you executing in a task?

**Comment by radare** [comment]
hello? @bannsec

**Comment by bannsec** [comment]
Complicated. Effectively I'm implementing an integration into revsync (
https://github.com/lunixbochs/revsync). Revsync is the core process I'm
running in a background process. Effectively it monitors redis and sends
and receives updates. In this, even without an update something was
happening that caused V series of commands to not work.

**Comment by radare** [comment]
@thestr4ng3r i think scripts cant run in background , you can verify this behaviour like this:
```
$ cat p.py
import r2pipe
import time
r2=r2pipe.open()
while True:
        print r2.cmd("?e jiji")
        time.sleep(1)
$ r2 /bin/ls
[0x100001200]>& . p.py
..
```

now try to type commands, and notice the lag, press V and nothing happens, gets stuck forever

**Comment by thestr4ng3r** [comment]
I missed we had a specific issue (#10843) for the background python issue. This one here is about V.

**Comment by thestr4ng3r** [comment]
@bannsec Please try again with the current master. Visual mode now generally works with a python script in the background. If it doesn't, it's probably something specific to your case and we need more info. You can also try debugging around https://github.com/radare/radare2/blob/8786d57aa51d696cd3ae8f11d8d14f2a01f7178f/libr/core/cmd.c#L1296-L1315 to see what exactly fails.

**Comment by radare** [comment]
ping

**Comment by bannsec** [comment]
Unfortunately, due to #10851 I cannot even re-test this issue at the moment. The integration code for revsync is effectively blocked until resolution of the slurp errors, to including not being able to test changes on this issue.

**Comment by thestr4ng3r** [comment]
@radare As said, V in general does work with background tasks now. I do this regularly myself and don't have any issues. So right now I have no way to reproduce this particular problem.

**Comment by radare** [comment]
Closing then
