### ISSUE TITLE
Move all `plugins list` commands under `L` namespace

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10849]
Currently every contains different commands in different places:
 - `iL` to list RBin plugins
 - `oL` to list RIO plugins
 - `dL` to list RDebug plugins
...
Currently `L` command is almost useless. Would be consistent to place all those under this namespace.
Moreover, to unify the output.

**Comment by radare** [comment]
What about core olugins?

**Comment by XVilka** [comment]
Same

**Comment by radare** [comment]
I would also keep the current iL, oL...but add aliases under L
