### ISSUE TITLE
Running (python) scripts does not play well with tasks

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10843]
I'm trying to use this new background task feature for python, but it's simply blocking waiting for python to return instead of actually backgrounding.

For instance:
```
& #!python script.py
```

The above will just block until script returns.

**Comment by radare** [comment]
Use . Instead of #!python. Otherwise you will have to quote it or will be considwred a comment. Dunno if that kind of task will work

**Comment by bannsec** [comment]
So it does run actually. My assumption was I could kick off a python command that would continue to do things, and as a background task the foreground would not UI would not block. At present, if you simply have a "sleep(20)" command in a python file and kick it off as a background task, the UI will pause until the sleep(20) is completed.

**Comment by thestr4ng3r** [comment]
Comment from #10839 by @radare:
> @thestr4ng3r i think scripts cant run in background , you can verify this behaviour like this:
>```
>$ cat p.py
>import r2pipe
>import time
>r2=r2pipe.open()
>while True:
>        print r2.cmd("?e jiji")
>        time.sleep(1)
>$ r2 /bin/ls
>[0x100001200]>& . p.py
>..
>```
>
>now try to type commands, and notice the lag, press V and nothing happens, gets stuck forever
