### ISSUE TITLE
http sandbox off == double commands

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#10844]
When I disable the http sandbox, every command i send over http gets received twice. This is causing excessive command executions.

**Comment by bannsec** [comment]
Possibly related, with sandbox off i also get the following errors:

```
slurp /tmp/r2.cmd.824jyo fails
```

**Comment by radare** [comment]
Please provide test case and optionally an asciinema

**Comment by Maijin** [comment]
Use the template for reporting issue @bannsec

**Comment by bannsec** [comment]
unfortunately i cannot reliably reproduce right now.. gonna close this for now until i have a reliable test case.

**Comment by chengxuncc** [comment]
> Possibly related, with sandbox off i also get the following errors:
> 
> ```
> slurp /tmp/r2.cmd.824jyo fails
> ```

Also have this error with sandbox off. 
```
> radare2 -v
radare2 3.5.0-git 21238 @ windows-x86-64 git.3.5.0-git
commit: 1c279c6081bc1877fabd533a8314eb527e32c66c build: Wed 04/10/2019__10:52:39.32
```
