### ISSUE TITLE
Fix Cd. command

### ISSUE THREAD

**Issue by pelijah** [radare/radare2#10856]
Defining data:
`[0x00005850]> Cd 4 2 @0x00005854`

Ok
```
[0x00005854]> pd 2
|           0x00005854      .dword 0x89485ed1
|           0x00005858      .dword 0xe48348e2
```

Can't use address with `Cd.` like it does `CC.` Command gives no output.
`[0x00005850]> Cd.0x00005854`

Lets seek. Why it returns `2`?! Should be `4`.
```
[0x00005850]> s 0x00005854
[0x00005854]> Cd.
2
```
`2` again
```
[0x00005854]> s 0x00005858
[0x00005858]> Cd.
2
```
`Cd` return correct info but only for the whole file
```
[0x00005854]> Cd
.................
0x00005854 data Cd 4
0x00005858 data Cd 4
```

**Comment by pelijah** [comment]
Related: https://github.com/radareorg/cutter/pull/602

**Comment by XVilka** [comment]
Please add also tests for this - this is the core feature.

**Comment by pelijah** [comment]
```
[0x00005850]> Cd 4
[0x00005850]> pd 2
|           ;-- entry0:
|           ;-- rip:
|           0x00005850      .dword 0x8949ed31
|           0x00005854      d15e48         rcr dword [rsi + 0x48], 1
[0x00005850]> Cd.
rip
```

**Comment by pelijah** [comment]
Wtf `Cd..` gives correct info. So why is `Cd.` is necessary?

**Comment by kazarmy** [comment]
Both `Cd.` and `Cd..` are not actually implemented (and are undocumented). What you saw was accidental behavior due to nonexistent error checking.

> So why is Cd. necessary?

It's shorter and aligned with `Cs.` and `CC.` in terms of behavior.

**Comment by kazarmy** [comment]
The code for the current behavior of `Cd..` was added in #8689 but that PR wasn't about `Cd..`
