### ISSUE TITLE
Identify main's argc and argv automatically

### ISSUE THREAD

**Issue by elicn** [radare/radare2#10850]
r2 knows where `main` function resides. Instead of generating generic `int arg1` and `int arg2` arguments for `main`, it could set them to `int argc` and `char** argv` respectively.
Many lib functions' signatures are recognized automagically; perhaps the same mechanism could be used to describe also the default signature of `main`.

**Comment by elicn** [comment]
Normally, from my experience, main's arguments are not recognized appropriately. I attached a simple snippet which queries `argc` and prints out `argv[1]`, as follows:
```
#include <stdio.h>

int main(int argc, char** argv)
{
	if (argc > 1)
	{
		printf("argv[1]: %s", argv[1]);
	}

	return 0;
}
```
The file is compiled with `-m64` and `-O2`, and then analyzed by r2 as follows:
![scr](https://user-images.githubusercontent.com/10291650/43414971-f5f74a62-943c-11e8-919c-8600e892fdc4.png)
You could see that `arg1` (i.e. `argc`) is not recognized, while `arg2` (i.e. `argv`) is tagged as `int`. Anyway, both args are never called "argc" and "argv", but just "arg1" and "arg2".

Source code and Makefile archived here:

[args.zip](https://github.com/radare/radare2/files/2242362/args.zip)

**Comment by sivaramaaa** [comment]
@elicn hi , the main problem here is the compiler optimzation (`-O2` flag ) , see below for same source file but with no optimization !

![arg_o0](https://user-images.githubusercontent.com/18589720/43444010-487cbadc-94c0-11e8-9f7c-ae5abfab34b7.png)

[arg_O0.zip](https://github.com/radare/radare2/files/2244146/arg_O0.zip)

**Comment by elicn** [comment]
That is exactly my point: main's arguments may be assumed to be `argc` and `argv` without resorting to a complicated analysis. At the end of the day we use r2 to analyze optimized binaries too, so I would not go for this kind of explanation.

That being said, I am failing to understand why the first argument wasn't recognized on the _optimized_ version: `edi` is used on the very first instruction of the function. Moreover, in the _non-optimized_ version the arguments are still called "arg1" and "arg2"; why aren't they called "argc" and "argv", if this is known to be `main`?

**Comment by radare** [comment]
What about envp? Nobody thinks about envp ever? :_____________

**Comment by sivaramaaa** [comment]
> That is exactly my point: main's arguments may be assumed to be argc and argv without resorting to a complicated analysis

@elicn  yes u are right , actually i already had this idea in my mind , i just needed to do littile more resarch to confirm , if this is the case on all archs/os etc  ... , and i will try to implement this soon !

> I am failing to understand why the first argument wasn't recognized on the optimized version: edi

oops yes that seems to be a bug to me , sorry i didin't notice , will look into it , thanks for reporting !

> What about envp? Nobody thinks about envp ever? :_____________

@radare , as @elicn say's if we just assume main arguments to be `(int argc , char **argv , char **envp )` then yes I will include `envp` too , but as far as now the reason for envp not being detected is , it's never accessed , hence never recovered !
