### ISSUE TITLE
ag command hasn't feature to export graph to given file

### ISSUE THREAD

**Issue by pelijah** [radare/radare2#10857]

**Comment by pelijah** [comment]
Related https://github.com/radareorg/cutter/issues/242

**Comment by Maijin** [comment]
@cyanpencil ^

**Comment by flareriderdash** [comment]
You can just do a command like agf FUNCTION_NAME > FILE_NAME.
or for web images you can just do agfw FUNCTION_NAME and it should save a file a.gif into your
home/ or root directory

**Comment by Maijin** [comment]
@flareriderdash that's not the point of this issue, cutter needs a way to do `agfw FUNCTION_NAME PATH`, this is fixed by this PR https://github.com/radare/radare2/pull/10860
