### ISSUE TITLE
Just a question about Visual modes in debugger

### ISSUE THREAD

**Issue by flareriderdash** [radare/radare2#10854]
I'm sorry to tread off the beaten path, but I have become interested in your graph renderings of disassembled functions. I would simply like just a few references to files from your source code to help me understand and maybe even implement in my own home scripts for other debugging needs regarding gdb. And possibly if you could give me a run down of abstractions you use for generating these graphs (including not only the terminal interactive/ascii graphs but also the web gif images) and the ways you think about them to make them work reliably and so the end-user can understand. If you wish that I reference you in my project of which I will probably place on my github repo I am more than willing. Thanks my mates.

**Comment by Maijin** [comment]
- Graph: https://github.com/radare/radare2/blob/master/libr/core/graph.c
- Conversion to dot: https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L5715 more in this file.
- Conversion to gif/svg etc. is made using xdot/dot: https://github.com/radare/radare2/blob/master/libr/core/cconfig.c#L2293
