### ISSUE TITLE
Slow to analyze some crafted ELF, Mach-o and PE

### ISSUE THREAD

**Issue by HongxuChen** [radare/radare2#10865]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF, Mach-o, MS OMF
| Architecture/bits of the file (mandatory)            | -
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18863 @ linux-x86-64 git.2.7.0-192-g72fd97738 commit: 72fd9773844d416197ec0fa99df5fbf338a2e749 build: 2018-07-31__11:35:08

### Expected behavior
r2 exits.

### Actual behavior
r2 hangs (different from #10444, which can quit by pressing `q`, these inputs make r2 hangs there, which can be verified by running `r2 $FILE`).

### Steps to reproduce the behavior 
- Download one of the files inside [this directory](https://github.com/ntu-sec/pocs/tree/master/radare2-18863/hangs);
- run `r2 -Q $FILE`.

**Comment by radare** [comment]
my pr fixes only the hang_01. the other hangs havent been fixed yet. btw, its not a hang. its just taking a long time. it will eventually finish, but its clearly wrong. thanks for reporting
