### ISSUE TITLE
move some shlr/* folders outside of shlr

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#10888]
I think some folders should be moved out of `shlr`, because they are not external dependencies and they can't even be compiled independently (they heavily depend on r_ libraries)

I think we should move:
- [ ] ar
- [ ] arm
- [ ] bochs
- [ ] gdb
- [ ] heap
- [ ] java
- [ ] qnx
- [ ] rar
- [ ] windbg

**Comment by xarkes** [comment]
I agree.

**Comment by ret2libc** [comment]
The other question is... where to move them to?

**Comment by XVilka** [comment]
Why, imho it is not important at all - additional burden without any
benefits. I would keep it as is. It is much more important to improve
shlr/java for example - see thousands of broken tests.

**Comment by radare** [comment]
shlr is suposed to contain code that is shared between different modules. which may be unique, or ripped from external sources. some of them without modifications, like zip/sdb/.. but others like tcc have deep changes that make them not generic outside r2land.

The arch/related i would move them into libr/asm/p/*

and make the anal plugin find the code in the asm directory like its done for other archs.

we may eventually merge asm and anal apis

**Comment by radare** [comment]
the idea is also that this code can be completely independent packages of software, but thee ffort to maintain them separately is big enough to not make much sense to move them out.

**Comment by XVilka** [comment]
By the way `shlr/tcc` is not really external dependency either - current code would not work outside radare2 and I stripped all unrelated code to C parsing.

**Comment by ret2libc** [comment]
> the idea is also that this code can be completely independent packages of software, but thee ffort to maintain them separately is big enough to not make much sense to move them out.

That's what I thought too, but most of the software there depends on other libs/headers defined in libr_* libraries, so they are not at all independent packages.

> Why, imho it is not important at all - additional burden without any benefits. I would keep it as is

Alright, fair enough!
