### ISSUE TITLE
Unintended sign-extension for 32b PPC to 64b

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#10884]
[Apparently]( https://twitter.com/marcan42/status/1024677435000803328 ), radare2 is sign-extending 32-bit PowerPC addresses to 64 bits, thus breaking all xrefs on targets in the upper half of the address space.

**Comment by Maijin** [comment]
from @marcan

**Comment by Maijin** [comment]
Dup of https://github.com/radare/radare2/issues/10885
