### ISSUE TITLE
Debug mode not working on Ubuntu

### ISSUE THREAD

**Issue by rafonsecad** [radare/radare2#10900]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.1 LTS
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            | x86/64.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18880 @ linux-x86-64 git.2.7.0-200-gdcdb33bda commit: dcdb33bda344e37e2cd6981b902dd2e71b71b806 build: 2018-07-31__18:05:15

### Expected behavior

Should load the program in debug mode

### Actual behavior

Appears the error: 
Cannot open '/proc/2851/maps': No such file or directory

### Steps to reproduce the behavior 
- At the terminal load the radare2 in debug mode with a program
`$r2 -d a.out`
- The output:
`Hello world!= attach 2851 2851`
`Cannot open '/proc/2851/maps': No such file or directory`
`Hello world!asm.bits 64`
`Cannot open '/proc/2851/maps': No such file or directory`
`[0x00000000]>`

**Comment by ret2libc** [comment]
Can you try with latest commit?

**Comment by rafonsecad** [comment]
Thanks @ret2libc !, It's working fine now.
