### ISSUE TITLE
Implement motions to interactive dissasembling (in edit mode)

### ISSUE THREAD

**Issue by Shaddy** [radare/radare2#10908]
As a vim user, it feels weird to not support basic vim motions. For example, using 8j while editing to move 8 positions down. It is supposed there will not be any collision with other commands, but please comment on this.

In Visual Mode (V) and disassembly mode (p), while moving with edit mode (EDIT: cursor mode) (c) it would be helpful to have [number][motion].

**Comment by Maijin** [comment]
The number are already used for jumping in the various part of the disassembly see [1], [2], this will be a collision with other commands and huge regressions of functionnality

**Comment by radare** [comment]
Yesterday i was trying to work like this on r2 and find out that actions like `3dw` to define 3 words in visual mode would be useful indeed.

Repetitions, like `3x` in the shell are handy, but expect the command to temporarily seek after each command.

in visual we can make this stuff work only when cursor is enabled. so it doesnt follow jumps when the cursor is there

**Comment by Maijin** [comment]
ok then only if cursor enabled could be ok.

**Comment by Shaddy** [comment]
Yes, it is supposed to work only with cursor enabled (I said edit mode dunno why), are there any collisions?

**Comment by Maijin** [comment]
In cursor mode I don't see any

**Comment by XVilka** [comment]
@Shaddy you can help this by crafting test cases for different commands, having it tested only on one command is not enough, preferably from different types of the modules.

**Comment by radare** [comment]
Testcases in visual?

**Comment by radare** [comment]
this is supported already
