### ISSUE TITLE
Determine columns configuration on startup

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10904]
Maybe its time to increase the column where the comments are shown, because it looks pretty bad by default. and… for <80 col terminals we shuold put them on top of the line instead of right by default… but i dont want to make this dynamically defined, so not sure what would be the best solution .. maybe checking at startup time? // by @radare

**Comment by radare** [comment]
this is done by scr.responsive=1

**Comment by radare** [comment]
setting this in your r2rc fixes the problem?
