### ISSUE TITLE
Slow to analyze some crafted files

### ISSUE THREAD

**Issue by HongxuChen** [radare/radare2#10903]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | Mach-o, Dalvik, ELF, Java Class, mdmp, etc (according to `file`)
| Architecture/bits of the file (mandatory)            | -
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18917 @ linux-x86-64 git.2.7.0-236-ge6796bf81 commit: e6796bf8129f614a4f3b91d1e00b79b1e9a8eaca build: 2018-08-03__11:04:57

### Expected behavior
r2 exits.

### Actual behavior
r2 takes long to analyze.

### Steps to reproduce the behavior 
- Download files from [this directory](https://github.com/ntu-sec/pocs/tree/master/radare2-18917/hangs).
- run `r2 -Q $FILE`

**Comment by ret2libc** [comment]
The java files were not fixed yet.

**Comment by radare** [comment]
can you tel the files or names missing?

**Comment by ret2libc** [comment]
`slow_{17,18,26,27}` still needs to be fixed, but they all probably have the same problem.

**Comment by radare** [comment]
Nothing to fix here, those slow_17,18,26,27 are analyzed in a portion of a second already. i have also fixed some r_list_append null asserts
