### ISSUE TITLE
Binary is corrupted by analysis when opened in Write mode

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#10916]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 64-bit (wsl), Arch Linux 64-bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86-64 
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18943 @ linux-x86-64 git.2.7.0-244-gc66112c13 commit: c66112c13bd59ecb1dcaaadea8106b6b44164f0c build: 2018-08-04__00:08:43

When opening a file in write-mode (`r2 -w filename`) and executing `aaa` some portions of the file are overridden and corrupting the binary.

```
beet:/tmp$ file echo
echo: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=057373f1356c861e0ec5b52c72804c86c6842cd5, stripped
beet:/tmp$ ./echo abcdef
abcdef
beet:/tmp$ r2 -w echo
 -- Set 'e bin.dbginfo=true' to load debug information at startup.
[0x00001c50]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Type matching analysis for all functions (afta)
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x00001c50]> q
beet:/tmp$ file echo
echo: data
beet:/tmp$ ./echo abcdef
bash: ./echo: cannot execute binary file: Exec format error
```

This is not happening on `aa` .

**io.cache result:** https://pastebin.com/p2299Pvb

**Comment by radare** [comment]
a mach0 bin is modified like this:
```
$ radiff2 /bin/ls ls
0x00004ce7 20 => 00 0x00004ce7
0x00004ce9 7072696e7463 => 000000000000 0x00004ce9
0x000054f0 ffffffffffffffff => 0000000000000000 0x000054f0
```

**Comment by radare** [comment]
i have fixed this by enabling io.cache in afta. there must be a better way to handle that. because io needs stacks of caches to support this properly

**Comment by radare** [comment]
cc @sivaramaaa
