### ISSUE TITLE
Allow searching of visual mode help

### ISSUE THREAD

**Issue by io12** [radare/radare2#10926]
The help menu accessed with `?` in visual mode should allow searching with `/` to easily find forgotten keybindings.

**Comment by radare** [comment]
/ in visual highlights, not searches

**Comment by io12** [comment]
I remember it working in the past I think

**Comment by cyanpencil** [comment]
Yes in the past it was working, I'm bisecting to see where it was broken

**Comment by radare** [comment]
it searchs in current block if yo uhave the cursor enabled in visual. is this what are you looking for?

**Comment by Maijin** [comment]
@radare stop use mail to reply, you already merged the PR and the issue is fixed/closed already.
