### ISSUE TITLE
Rename inclusion-only .c files to .inc

### ISSUE THREAD

**Issue by MaskRay** [radare/radare2#10920]
When inclusion-only .c files are compiled alone, there will be a plethora of `-Wunused-function` warnings. Renaming them to `.inc` (or whatever) will make the intention clear. `libr/core/cmd_*.c` and some arch|bin files are examples of such inclusion-only files.

Some files are both standalone and included, e.g. `libr/bin/p/bin_pe.c`. Such usage is bad and should be discouraged.

An Emacs/Vim respected mode line as an example
```c
// vim: ft=c -*- C -*-
```

Some editors may have bad time detecting the language (vscode, but I'm not sure). I don't think we should do anything special for them.

**Comment by radare** [comment]
We shouldnt include c files. But that simplifies a lot the building issues with visibility and such. If we merge asm and anal we wouldnt need to do this stuff in there. In core, i think we may find better solutions now that we are using the visibility attributes properly and enforcing them at least for gcc and clang

**Comment by radare** [comment]
you already did this in a pr and its merged, and yes, many editors (all of them?) have issues detecting the filetype without the extension. and the `// vim: ft=c -*- C -*-` command basically doesnt work unless you configure vim differently from the vanila defaults, so its not a good solution imho.

what about `.inc.c` ?
