### ISSUE TITLE
Opening a file that doesnt exist creates no maps

### ISSUE THREAD

**Issue by radare** [radare/radare2#10947]
```
> r2 -w 404
[0x00000000]> o
 3 * rwx 0x00000000 404
[0x00000000]> om
[0x00000000]>
```

**Comment by condret** [comment]
empty files cause empty maps, and empty maps may not exist, this is wanted API design.

**Comment by radare** [comment]
i think the expected behaviour for the user is to be able to write at offset 0 and get a resized file with a map in there. if no map is found, siol will not trigger the fd.

maybe time to bring back io.raw?

**Comment by radare** [comment]
we need a way in siol to tie a map size to an fd. maybe with an attribute to update them when a file is resized?

**Comment by condret** [comment]
no, empty maps cannot exist. think about them as snippets of paper, if the snippet has the lenght of 0, it doesn't exist.

We could turn io.va off, when the first opened file is empty.

**Comment by radare** [comment]
e io.va <http://io.va/>=0 is enough to make this work

we should make this change when the file doesnt exist
