### ISSUE TITLE
adf and adfg need documentation

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#10960]
adf and adfg need documentation

ping @radare

**Comment by radare** [comment]
what documentation?

adf = mark as dwords all the data references found in the current function
adfg = find the gaps between basic blocks in a function and mark them as data (useful when the function mixes data and code)

**Comment by Maijin** [comment]
Well this documentation 👍

**Comment by radare** [comment]
add an issue and copypaste my answer or do it yourself. enotime now

**Comment by Maijin** [comment]
That was not for the book, it's for the r2 internal help. Those are important that we need to discuss integration in aaX

**Comment by Maijin** [comment]
It's documented in help now
