### ISSUE TITLE
aa creates functions for switch cases

### ISSUE THREAD

**Issue by io12** [radare/radare2#10966]
`aa` marks each switch case as a function, which causes the disassembly to be less clear and breaks the graph view.

**Comment by Maijin** [comment]
Can you use the template to create issue and provide your version, examples, screenshots/paste etc. please?

**Comment by io12** [comment]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux/x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18995 @ linux-x86-64 git.2.7.0-266-g6059a709b commit: 6059a709b6b08f9ae55723901cc3cdc9ff83da21 build: 2018-08-06__18:54:01

### Expected behavior

When I run `aa` on the binary bomb, the switch cases in sym.phase_3 shouldn't be detected as functions.

### Actual behavior

They are not detected as functions with `af`, but they are with `aa`. This causes the disassembly to be less clear and breaks the graph view.

### Steps to reproduce the behavior 

```
r2 bomb
aa
s sym.phase_3
pdf
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

![image](https://user-images.githubusercontent.com/7348004/43745080-f9cac89e-99aa-11e8-8716-74b890bb59c1.png)

```
│       │   ;-- switch.0x08048bd6:                                             
│       │   0x08048bd6      ff2485e89704.  jmp dword [eax*4 + 0x80497e8]    ; s
╰       │   0x08048bdd      8d7600         lea esi, [esi]                      
╭ (fcn) fcn.08048be0 42                                                        
│   fcn.08048be0 ();                                                           │       │   ; var int local_18h @ ebp-0x18                                     
│       │   ; var unsigned int local_5h @ ebp-0x5                              
│       │   ; var unsigned int local_4h @ ebp-0x4                              
│       │   ; CODE XREF from sym.phase_3 (0x8048bd6)                           
│       │   0x08048be0      b371           mov bl, 0x71                ; 'q' ; 
│       │   0x08048be2      817dfc090300.  cmp dword [local_4h], 0x309    ; [0x
│      ╭──< 0x08048be9      0f84a0000000   je 0x8048c8f                ;[2]    
│      ││   0x08048bef      e808090000     call sym.explode_bomb       ;[3]    
│     ╭───< 0x08048bf4      e996000000     jmp 0x8048c8f               ;[2]          │││   0x08048bf9      8db426000000.  lea esi, [esi]                      
╭ (fcn) fcn.08048c00 39                                                        
│   fcn.08048c00 ();                                                           │     │││   ; var unsigned int local_4h @ ebp-0x4                              
│     │││   ; CODE XREF from sym.phase_3 (0x8048bd6)                           
```

Drag and drop zip archives containing the Additional info here, don't use external services or link.
[bomb.zip](https://github.com/radare/radare2/files/2264396/bomb.zip)

**Comment by d4em0n** [comment]
Can't reproduce here.
```
radare2 2.9.0-git 19406 @ linux-x86-64 git.2.8.0-236-geb0e046
commit: eb0e0462a29080b68866322499f739e85d2e0e55 build: 2018-08-28__20:35:39
```
![image](https://user-images.githubusercontent.com/29397847/44726830-cfd61c00-ab02-11e8-8e18-d2e8a8f57b02.png)

**Comment by io12** [comment]
I can still reproduce the bug
```
radare2 2.9.0-git 19337 @ linux-x86-64 git.2.8.0-239-gb4d37e99a
commit: b4d37e99a041ac5a6d54beb152d95aef6662e292 build: 2018-08-28__13:09:48
```

**Comment by radare** [comment]
I doubt this got broken in the 3 commits of difference you two report

**Comment by ret2libc** [comment]
Could you try run radare2 with `-e anal.jmptbl=true`?

**Comment by radare** [comment]
Thatsalready the default unless he hVe a custom r2rc

**Comment by radare** [comment]
works for me in master

**Comment by radare** [comment]
Can you show an asciinema or make a testcase?

**Comment by io12** [comment]
https://asciinema.org/a/R0MERGqQJ9ewDxV7jvML4PlSo

**Comment by io12** [comment]
Apparently removing these lines from my radare2rc fixes the problem:
```
e anal.jmptbl = true
e anal.ijmp = true
e anal.datarefs = true
```

**Comment by XVilka** [comment]
I think it might be 'anal.ijmp'. it helps in some cases but still
experimental.

**Comment by radare** [comment]
Probably because of anal.ijmp
