### ISSUE TITLE
context disasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#11003]
* pd X disassembles N instructions forward
* pd -X disassembles N instructions backward

but 90% of the time we want to see a disasm of X instructions around the current offset, maybe we should have a syntax for this instead of having to use something that cryptic:

* pd 6 @i:-3 should work but it doesnt

<img width="556" alt="screen shot 2018-08-09 at 13 47 28" src="https://user-images.githubusercontent.com/917142/43896941-c98ac418-9bda-11e8-9c9a-7fb549c42ddc.png">

**Comment by radare** [comment]
this exposes a bug in @i: btw :P

**Comment by radare** [comment]
Probably the bug in @i is related to arm64 only. so fails too.

Will be good to define 'i' or 'o' and use @o or si instead for consistency

<img width="185" alt="screen shot 2018-08-09 at 13 52 40" src="https://user-images.githubusercontent.com/917142/43897178-8a0d2668-9bdb-11e8-8c66-66afe004d565.png">

**Comment by ret2libc** [comment]
Note that this should work correctly (on x86 at least) if you do analysis. That's because once you have analyzed the binary, you know where instructions are and you can easily do the "@i:-X"

**Comment by kazarmy** [comment]
> maybe we should have a syntax for this

- pd -X- disassembles X/2 instructions forward and backward

**Comment by kazarmy** [comment]
> - pd -X- disassembles X/2 instructions ~~forward and backward~~

- pd -X- disassembles X/2 instructions before and after current seek

**Comment by radare** [comment]
Done in pd—
