### ISSUE TITLE
enable codecov.io in travis

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#11014]
We should measure coverage when running r2r, to know how much of our codebase is covered by tests and which parts need more love.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/08912e2e67ed3c7343b89b0ea9792f81531ef908#diff-354f30a63fb0907d4ad57269548329e3 see we used to have coveralls support

**Comment by Maijin** [comment]
yeah if it works :S
