### ISSUE TITLE
Console input broken again on Windows 10

### ISSUE THREAD

**Issue by riverar** [radare/radare2#11024]
## Environment
Windows 10 x64 17134.191 (RS4)
radare2 2.9.0-git 19136 @ windows-x86-32 git.2.8.0-28-ge434a5938
commit: e434a5938bc8af4a69a89ec87c4fe4e719d78458 build: Fri 08/10/2018__ 4:21:49.23

## Expected behavior
Basic console input support, supported by the console host

## Actual behavior
(See gif.)

![r2](https://user-images.githubusercontent.com/475132/43989653-5182a15a-9d03-11e8-83c7-98259dccfeef.gif)

## Steps to reproduce the behavior
1. radare2 -
2. Type some text
3. Note unexpected behavior

cc: @skuater 

----

@WithinRafael in the radare2 Telegram group, if you need to chat.

**Comment by skuater** [comment]
fixed :) plz try it and let us know if work correctly for u

**Comment by riverar** [comment]
@skuater thanks for the quick response, works here.

I'll need to open a feature request on VT support (e.g. `e scr.color=3`). Windows 10 users shouldn't be required to `set ANSICON=1` manually.
