### ISSUE TITLE
Debugger - watchpoint issue(s)

### ISSUE THREAD

**Issue by AsFaBw** [radare/radare2#11029]
With last release I added watchpoint (dbw) support, unfortunately without fully testing it.

First issue is with write watchpoints. It will not be removed correctly due to following typo:

```
	case R_BP_PROT_WRITE : {
 		if (set)
 			gdbr_set_hww (desc, b->addr, "", 1);
 		else
 			gdbr_remove_hwbp (desc, b->addr, 1);
 		break;
 	}
```

Should read gdbr_remove_hww instead. Will further test and do a fix on it.

**Comment by AsFaBw** [comment]
sorry had no time up to now.

Not sure if I understand your question. The dbw is setting hardware watches for data access instead of instruction execution (either on data read or data write or read/write(access)). The normal instruction execution breakpoint is set with the already existing db command according to my understanding. But I am still in understanding and learning phase. Tested on a cortex-m4 connected via segger debugger.

(created pull request  #11132 to fix this issue.)

**Comment by radare** [comment]
moving for 3.x

**Comment by AsFaBw** [comment]
the corresponding pull request #11132 was merged already. From my point of view this issue can be closed.
