### ISSUE TITLE
Integrate TIV in r2

### ISSUE THREAD

**Issue by radare** [radare/radare2#11039]
To visualize BMP in memory, also useful as another zoom-like visualization tool. No need to support multiple image types. Maybe via r2pm we can support the glib-pixbuf version of the same command to visualize images from memory, finding them with /m and then showing them with the command that uses tiv to render

https://github.com/radare/tiv

**Comment by Maijin** [comment]
That could be useful for dealing with PE resources

**Comment by radare** [comment]
We must add a command to print the buffer in data: format for web integration too converting the buffer into a png or so

**Comment by radare** [comment]
related to https://github.com/radare/radare2/pull/12765

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/12765
