### ISSUE TITLE
Is there a feature like "(gdb) ptype"?

### ISSUE THREAD

**Issue by SnowI5Me** [radare/radare2#11047]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            |  x86/64 etc.
| r2 -v full output     |  radare2 2.9.0-git 19019 @ linux-x86-64 git.2.8.0-19-g3353519bc commit: 3353519bceb000cdfdeb3ab479db7824851defd1 build: 2018-08-10__00:05:17

### Question about radare2 function.

There is one question.
Does "radare2" have the same function as "(gdb)ptype"?

```
(gdb) ptype Player
type = class Player : public Actor, public IPlayer {
  private:
    uint32_t m_characterId;
    std::string m_playerName;
    std::string m_teamName;
    uint8_t m_avatarIndex;
    uint32_t m_colors[4];
    std::map<IItem*, ItemAndCount, std::less<IItem*>, std::allocator<std::pair<IItem* const, ItemAndCount> > > m_inventory;
    bool m_admin;
    bool m_pvpEnabled;
    bool m_pvpDesired;
    float m_pvpChangeTimer;
    int32_t m_pvpChangeReportedTimer;
    bool m_changingServerRegion;
    std::string m_currentRegion;
    std::string m_changeRegionDestination;
    std::set<std::basic_string<char>, std::less<std::basic_string<char> >, std::allocator<std::basic_string<char> > > m_aiZones;
    int32_t m_mana;
```

**Thanks in advance for your reply.**

**Comment by XVilka** [comment]
Currently not (for C++ classes/types), but for C structs/types there are `t` commands, and `tp` for your case.

**Comment by XVilka** [comment]
For the C++ part it depends when https://github.com/radare/radare2/issues/10905 and https://github.com/radare/radare2/issues/6851 are finished.
