### ISSUE TITLE
Assembly - mov eax,r12d

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11040]
### Expected behavior

rasm2 -a x86 "mov eax, r12d"
4489e0

### Actual behavior

rasm2 -a x86 "mov eax, r12d"
89e0

https://github.com/radare/radare2-regressions/commit/a0747ebcf92e32981886ae13f11ef4e99a3776ef

**Comment by radare** [comment]
Can you check this one? cc @PaoloMonti42

**Comment by PaoloMonti42** [comment]
Sure, but not very soon

**Comment by PaoloMonti42** [comment]
Well, the fix to this specific case seems to be very simple.
Too bad that, for some reason, a->bits is equal to 32, even if the -b 64 option is specified.
Is that a known issue?

**Comment by radare** [comment]
Default should be R_SYS_BITS if not its a bug

**Comment by PaoloMonti42** [comment]
Looks like that parseReg overwrites it when it encounters an extended register.
This seems like a mistake, I cannot find any reason for it.

https://github.com/radare/radare2/blob/4c0f24fb3f01737b44422046e10fb5eb16f075ae/libr/asm/p/asm_x86_nz.c#L4164-L4170

Overwriting a->bits when detecting some registers can make sense, but only if it makes it higher, not independently of the previous value.

I will try pushing the fix, hoping not to cause regressions everywhere.
