### ISSUE TITLE
ESIL emulation: ldrh instruction emulates incorrectly

### ISSUE THREAD

**Issue by yfuchs-c2a** [radare/radare2#11052]
ldrh (Load register halfword) instruction is expected to read half word but it reads the entire word (32 bit)

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Arm 32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19009 @ linux-x86-64 git.2.8.0-7-ga93d33d23
commit: a93d33d23f48ed9d9330f90093f96112cb4c3e7b build: 2018-08-08__08:52:02

for example address has 0x004f8810:
### Expected behavior
ESIL reads 0x8810

### Actual behavior
ESIL reads 0x4f8810
![selection_001](https://user-images.githubusercontent.com/37180015/44000000-6fb4351c-9e20-11e8-8896-bf7e9b0f9655.png)

i can't upload the binary, but it's easily reproduced by emulating ldrh instruction.

**Comment by radare** [comment]
Provide the bytes at least and a oneliner to execute it and the expected behaviour

Pastr the esil expression here and maybe you can also fix that if you know what is doing and what is expected

**Comment by yfuchs-c2a** [comment]
i compiled a binary that you can simulate on it.
[a.zip](https://github.com/radare/radare2/files/2280873/a.zip)

r2 a.out
aaa
s sym.main
pdf
e asm.esil=true
pdf

when i'm emulating instruction one by one (aeso) i also get the same result.

![screenshot from 2018-08-12 13-48-48](https://user-images.githubusercontent.com/37180015/44001210-77c83df0-9e36-11e8-9da1-ca7c5f691164.png)

as you can see in address 0x00010438:
0x00010438      b030d3e1       ldrh r3, [r3]               ; arg4 ; r3=0x10001 -> 0x1464c45
0x00010438      b030d3e1       0,r3,+,0xffffffff,&,[4],r3,= ; arg4 ; r3=0x10001 -> 0x1464c45
r2 = 0x10001 instead of 0x0001

**Comment by yfuchs-c2a** [comment]
it seems to work now. both the binary i uploaded and the one i had are now working properly.
but running this
r2 -a arm -b 32 -c 'wx b030dfe10101010141424344' -qc 'aes;dr r3’ -
doesn't print anything for me.
am i running it wrong?

**Comment by Maijin** [comment]
@yfuchs-c2a Please notice that one of the ' is wrong character in @radare message:

Command-line should be:
```
 r2 -a arm -b 32 -c 'wx b030dfe10101010141424344' -qc 'aes;dr r3' -
```

**Comment by Maijin** [comment]
Can you try this?

**Comment by radare** [comment]
sorry use dr?r3 instead of dr r3

**Comment by yfuchs-c2a** [comment]
yes, i got 0x00004241.

**Comment by radare** [comment]
can you add a test in r2r for this?

thanks

**Comment by Maijin** [comment]
It's here - https://github.com/radare/radare2-regressions/commit/a0b3217ebfdddeaeb755e096eec7cb9b656cfdc3

At this time master has the following:

```
r2 -a arm -b 32 -c 'wx b030dfe10101010141424344' -qc 'aes;dr r3' -
0x44434241
```

Thus  I marked the test as broken.

**Comment by radare** [comment]
Why mark as broken? Its fixed

**Comment by Maijin** [comment]
@radare you say it should be "0x00004241" or currently it's 0x44434241

**Comment by radare** [comment]
i said it should be 0x00004241, which is the current output

$ r2 -a arm -b 32 -c 'wx b030dfe10101010141424344' -qc 'aes;dr r3' -

0x00004241

**Comment by Maijin** [comment]
i removed the broken
