### ISSUE TITLE
Console UI issue with asm.offset and asm.cmt.right

### ISSUE THREAD

**Issue by dmknght** [radare/radare2#11062]
`e asm.offset = false` displays weird space and `e asm.tabs = <number_of_tab>` does not work with `e asm.cmt.right = false`
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Parrot Security OS 4.1 amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19081 @ linux-x86-64 git.2.8.0-70-g8a2397e4b
commit: 8a2397e4b1b6bdbfb23c84f02a5abe6a5fa80149 build: 2018-08-13__14:46:52

1. `e asm.offset = false` display
-  radare2 display with `e asm.offset = true`
![screenshot at 2018-08-13 15-08-03](https://user-images.githubusercontent.com/29118926/44020013-b3d1b4e6-9f0a-11e8-81bc-bb25f07cdb94.png)

- radare2 display with `e asm.offset = false`
![screenshot at 2018-08-13 15-11-09](https://user-images.githubusercontent.com/29118926/44020143-2298d6e8-9f0b-11e8-85cd-4e90efa9a2c3.png)
In my opinion, disasm code should display from left side without space (green highlight)
- VV mode does not have this issue
![screenshot at 2018-08-13 15-13-47](https://user-images.githubusercontent.com/29118926/44020248-83114406-9f0b-11e8-8785-aa926f82da88.png)

2. `e asm.tabs` does not work with `e asm.cmt.right = false`
- Here is how radare2 display with `e asm.cmt.right = true` and `e asm.tabs = 16`
![screenshot at 2018-08-13 15-15-24](https://user-images.githubusercontent.com/29118926/44020336-c674b124-9f0b-11e8-9d18-1a5457598b4e.png)

- Set `asm.cmt.right = false`, display space will disappear. (It looks super weird without  offset and cmt.right)
![screenshot at 2018-08-13 15-16-14](https://user-images.githubusercontent.com/29118926/44020377-e767ec52-9f0b-11e8-8378-2749ed57f6a7.png)
(`VV` mode set `asm.cmt.right = false` by default i think so nothing changes in this mode)

**Comment by XVilka** [comment]
Please craft testcases

**Comment by ITAYC0HEN** [comment]
I dig into this and the spaces are caused by `asm.marks`, so by default there'll be 5 blank spaces to be filled with `b`, `*`, etc. Disable `asm.marks` and you should be fine.

With `asm.marks` and `asm.tabs.off` set to true:

```
/ (fcn) fcn.00401000 31
|   fcn.00401000 ();
|           ; var int local_8h @ ebp-0x8
|           ; var int local_4h @ ebp-0x4
|                     push ebp
|                     mov  ebp, esp
|                     sub  esp, 8
|                     nop
|                     mov  eax, 0x402000
|                     mov  dword [local_4h], eax
|                     mov  eax, dword [local_4h]
|                     mov  dword [local_8h], eax
|                     mov  eax, dword [local_8h]
|                     call eax
|                     leave
\                     ret
```

With `asm.marks` set to false and `asm.tabs.off` true:

```
/ (fcn) fcn.00401000 31
|   fcn.00401000 ();
|           ; var int local_8h @ ebp-0x8
|           ; var int local_4h @ ebp-0x4
|                push ebp
|                mov  ebp, esp
|                sub  esp, 8
|                nop
|                mov  eax, 0x402000
|                mov  dword [local_4h], eax
|                mov  eax, dword [local_4h]
|                mov  dword [local_8h], eax
|                mov  eax, dword [local_8h]
|                call eax
|                leave
\                ret
```

With `asm.marks` and `asm.tabs.off` set to false:

```
/ (fcn) fcn.00401000 31
|   fcn.00401000 ();
|           ; var int local_8h @ ebp-0x8
|           ; var int local_4h @ ebp-0x4
|           push ebp
|           mov  ebp, esp
|           sub  esp, 8
|           nop
|           mov  eax, 0x402000
|           mov  dword [local_4h], eax
|           mov  eax, dword [local_4h]
|           mov  dword [local_8h], eax
|           mov  eax, dword [local_8h]
|           call eax
|           leave
\           ret
```

Sadly I have no time to fix it soon - it requires a rethinking of using the marks in this space. 

This is the function which is responsible for printing the marks:
https://github.com/radare/radare2/blob/2b2c901da776520f76fe95c59629630470575d44/libr/core/disasm.c#L1353

Below line # 1363  we can put something like this:
```
if (!p && !q && !ds->hasMidflag {
	break;
}
```

But, while it solves the problem you described and removes the extra spaces, it'll create a new problem that in cases where `p || q || ds->hasMidflag` are true, the instructions with breakpoints, cursor or midFlag will be pushed and would not be aligned with the rest of the code. You'll get something like this (notice the little 'b' before `mov  dword [local_4h], eax`):

```
/ (fcn) fcn.00401000 31
|   fcn.00401000 ();
|           ; var int local_8h @ ebp-0x8
|           ; var int local_4h @ ebp-0x4
|           push ebp
|           mov  ebp, esp
|           sub  esp, 8
|           nop
|           mov  eax, 0x402000
|           b    mov  dword [local_4h], eax
|           mov  eax, dword [local_4h]
|           mov  dword [local_8h], eax
|           mov  eax, dword [local_8h]
|           call eax
|           leave
\           ret
```

And with offsets:

```
/ (fcn) fcn.00401000 (32 bits) 31
|   fcn.00401000 ();
|           ; var int local_8h @ rbp-0x8
|           ; var int local_4h @ rbp-0x4
|           0x00401000      55             push rbp
|           0x00401001      89e5           mov ebp, esp
|           0x00401003      81ec08000000   sub esp, 8
|           0x00401009      90             nop
|           0x0040100a      b800204000     mov eax, 0x402000
|           0x0040100f      b    8945fc         mov dword [local_4h], eax
|           0x00401012      8b45fc         mov eax, dword [local_4h]
|           0x00401015      8945f8         mov dword [local_8h], eax
|           0x00401018      8b45f8         mov eax, dword [local_8h]
|           0x0040101b      ffd0           call rax
|           0x0040101d      c9             leave
\           0x0040101e      c3             ret
```

**Comment by dmknght** [comment]
Hi! I tried disable asm.marks as Mr. ITAYC0HEN said and tested in debug mode (without editing any line of code) and found this problem:
- Debug mode, set random break point with `asm.makrs` and `asm.offset`
![screenshot at 2018-08-13 19-26-01](https://user-images.githubusercontent.com/29118926/44031622-bd036478-9f2e-11e8-9129-6f36e84e0958.png)
- After disable `asm.marks` and `asm.offset`, break point mark was removed
![screenshot at 2018-08-13 19-27-44](https://user-images.githubusercontent.com/29118926/44031709-0870fb8c-9f2f-11e8-864c-2d3eebf51c95.png)

This is more complicated than i think and looks like `asm.marks` shouldn't be disabled.

p/s: I understand that i must give more information but this problem happens to all case (any ELF file) so i don't know how to make it clear @@

**Comment by ITAYC0HEN** [comment]
Obviously it'll be removed since `asm.marks` is the one which responsible to show this.

**Comment by radare** [comment]
isnt this fixed already @cyanpencil ?

**Comment by cyanpencil** [comment]
No, I am afraid this is not yet fixed.
