### ISSUE TITLE
Rasm2 assembly 32 bug

### ISSUE THREAD

**Issue by securitykitten** [radare/radare2#11074]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86_64
| File format of the file you reverse (mandatory)      | raw
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19335 @ linux-x86-64 git.2.8.0-89-g915b3de commit: 915b3deeb19767f1b2fabd20a884752e6c1b4688 build: 2018-08-13__16:56:04

### Expected behavior
```
rasm2 -b 32 'add  [eax + 0x409578], al'
008078954000
```
### Actual behavior
```
rasm2 -b 32 'add  [eax + 0x409578], al'
Error: mismatched operand sizes
Error: mismatched operand sizes
Error: mismatched operand sizes
Cannot assemble 'add  [eax + 0x409578], al' at line 3
invalid
```

### Steps to reproduce the behavior 
```
rasm2 -b 32 'add  [eax + 0x409578], al'
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
Interestingly enough, testing Rasm2 the other way works
```
rasm2 -d 008078954000
add byte [eax + 0x409578], al
```

**Comment by securitykitten** [comment]
When adding the byte prefix this now correctly assembles.  Is this just a rule of the assembler syntax?
```
add byte [eax + 0x409578], al
```
rather than 
```
add [eax + 0x409578], al
```

**Comment by radare** [comment]
Yes, the assembler is quite strict but we should make it more flexible in those situations, do you want to try to fix this issue in x86.nz?
