### ISSUE TITLE
ood command can't reopen files with spaces (windows) or if an argument has a `/` (linux)

### ISSUE THREAD

**Issue by BlackYoup** [radare/radare2#11075]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Exherbo / Windows x86_64
| File format of the file you reverse (mandatory)      | PE, ELF
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19121 @ linux-x86-64 git.2.7.0-400-g915b3deeb commit: 915b3deeb19767f1b2fabd20a884752e6c1b4688 build: 2018-08-14__00:13:45 (same commit for the Windows binary)

### Expected behavior

`ood` should be able to:
- reopen binaries that have spaces in them or in the path (Windows)
- reopen binaries with a `/` in the given arguments (Linux)

### Actual behavior

Currently, `ood`
- Fails at parsing the path of the binary and gives a wrong path to `CreateProcess` (Windows)
- Fails at parsing the path of the binary and gives a wrong path to `execvp` (Linux)

#### Windows

- open a binary that's in a folder having spaces (open it in debug or not, doesn't matter)
- try to `ood`
- `CreateProcess` will fail because it can't find the file

##### Linux

- open a binary
- try to `ood /tmp/wedontcare`
- `execvp` will fail at finding the binary 

### Additional Logs, screenshots, source-code,  configuration dump, ...

`ood` works for most cases but some edge cases are not correctly handled, mostly because of https://github.com/radare/radare2/blob/915b3deeb19767f1b2fabd20a884752e6c1b4688/libr/core/cmd_open.c#L880

Merging the `path` and `arguments` here lead to further (quite hard) parsing which could be avoided. I think it  would make more sense to pass both the current debugged file and arguments in two separate arguments instead of merging them into one `cmd`. Something like `static int fork_and_ptraceme(RIO *io, int bits, const char *binpath, char **arguments) {}` for example (not sure about the signature, you get the idea).

Unless something is preventing this and this is why it's currently done like this? That's something I'm willing to do in any case if I can help

**Comment by radare** [comment]
we merged a PR fixing this, considering it correct now, pls complain if not
