### ISSUE TITLE
Failed to install with the latest version on Ubuntu 16.04 x86_64

### ISSUE THREAD

**Issue by cq674350529** [radare/radare2#11077]
First, thanks for your great job about `radare2`. 
I clone the repository and run `sys/install.sh --without-pull` to install it. There are some errors as below:

    # some info ignored
    export USE_R2_CAPSTONE=
    ... 
    Nothing to sync because of --without-pull
    /bin/sh: 1: cd: can't cd to capstone
    Makefile:262: recipe for target 'capstone-build' failed
    make[1]: *** [capstone-build] Error 2
    make[1]: *** Waiting for unfinished jobs....
    ...
    Makefile:57: recipe for target 'all' failed
    make: *** [all] Error 2

Does it mean I need to install `capstone` first? My machine(`ubuntu 16.04, x86_64`) have some modules related to `capstone`: 

    $ pip list | grep capstone
    capstone                           3.0.4 
    $ dpkg -l | grep capstone
    ii  libcapstone-dev                            3.0.4-0.2                                    amd64        lightweight multi-architecture disassembly framework - devel files
    ii  libcapstone3                               3.0.4-0.2                                    amd64        lightweight multi-architecture disassembly framework - library

Any advice? Thanks in advance!

**Comment by XVilka** [comment]
Unless capstone 4.0 released (see here https://github.com/aquynh/capstone/issues/1096 ) 3.0.x versions are too old, poorly maintained, deprecated and contain many bugs fixed in the git version. So please remove system capstone first, undef USE_R2_CAPSTONE and remove `--without-pull` flag.

**Comment by cq674350529** [comment]
It works. Thanks!
