### ISSUE TITLE
pdf cuts the function in ldrls pc instruction

### ISSUE THREAD

**Issue by yfuchs-c2a** [radare/radare2#11099]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64.
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            | arm 32.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19122 @ linux-x86-64 git.2.8.0-97-g7b3764c6f
commit: 7b3764c6fea48a5e6dd43a5e0c1c8fe92f732e4f build: 2018-08-15__08:58:13

### Expected behavior
the function doesn't end at ldrls pc instruction.
### Actual behavior
![selection_001](https://user-images.githubusercontent.com/37180015/44141972-5be024ec-a087-11e8-9d90-424f57b008af.png)
![selection_002](https://user-images.githubusercontent.com/37180015/44141990-69301698-a087-11e8-989b-26261accb71e.png)

it seems like there is switch statement here.
but for some reason it's not recognized.
i saw other functions with switch cases that worked OK.

### Steps to reproduce the behavior 
i can't share the binary, but i did:
aa
pdf @ function_name

since i can't share the binary, do you need more info? (hard to compile a binary to reproduce this)

**Comment by radare** [comment]
Because ldr pc, xx is a jump

**Comment by radare** [comment]
can you provide the bin? it would be easier to implement the jump table , and then the test

**Comment by yfuchs-c2a** [comment]
i can't upload the binary.
but i have few binaries that i see this happening in some of them (switch jump table not recognized).
i noticed now that when im running aaa.
r2 outputs something about it:
[anal.jmptbl] Missing cjmp bb in predecessor at 0x00022e18

then 
pdf @ |   0x00022df4
|           0x00022df4      00482de9       push {fp, lr}
|           0x00022df8      04b08de2       add fp, sp, 4
|           0x00022dfc      80d04de2       sub sp, sp, 0x80
|           0x00022e00      80000be5       str r0, [local_80h]         ; 0x80 ; 128
|           0x00022e04      84100be5       str r1, [local_84h]         ; 0x84 ; 132
|           0x00022e08      80301be5       ldr r3, [local_80h]         ; 0x80 ; 128
|           0x00022e0c      343093e5       ldr r3, [r3, 0x34]          ; arg4
|           0x00022e10      013043e2       sub r3, r3, 1
|           0x00022e14      040053e3       cmp r3, 4                   ; 4
\           0x00022e18      03f19f97       ldrls pc, [pc, r3, lsl 2]   ; loc._d_355 ; [0x22e20:4]=0x22e34 loc._a_191 ; "4.\x02"

maybe it will help?
i think that every time it misses switch jump table it outputs
[anal.jmptbl] Missing cjmp bb in predecessor at xxx

**Comment by yfuchs-c2a** [comment]
what does it mean exactly?

**Comment by radare** [comment]
It means that this jump table is not supported yet and without the binary i cant do too much. If u have any other bin to reproduce this issue i can have a look

**Comment by yfuchs-c2a** [comment]
i could try to compile a bin..
but i didn't understand what is the difference between this switch table to a "regular" one?

**Comment by XVilka** [comment]
There are many different jump table types for different architectures. Not
the one or two - many.

**Comment by yfuchs-c2a** [comment]
it's not exactly the same but this elf has similar behavior
[switch_table.zip](https://github.com/radare/radare2/files/2301791/switch_table.zip)
aa
pdf @ sym.input_handler2

0x000105b0]> pdf @ sym.input_handler2
|           ;-- $a:
/ (fcn) sym.input_handler2 20
|   sym.input_handler2 ();
|           ; CALL XREF from sym.main (0x103c0)
|           0x000105b0      010040e2       sub r0, r0, 1               ; .//main.c:42
|           0x000105b4      060050e3       cmp r0, 6                   ; 6
|           0x000105b8      00f18f90       addls pc, pc, r0, lsl 2
\       ,=< 0x000105bc      0d0000ea       b loc.000105f8
[0x000105b0]> 

objdump output:
000105b0 <input_handler2>:
   105b0:	e2400001 	sub	r0, r0, #1
   105b4:	e3500006 	cmp	r0, #6
   105b8:	908ff100 	addls	pc, pc, r0, lsl #2
   105bc:	ea00000d 	b	105f8 <input_handler2+0x48>
   105c0:	ea000005 	b	105dc <input_handler2+0x2c>
   105c4:	ea000005 	b	105e0 <input_handler2+0x30>
   105c8:	ea000006 	b	105e8 <input_handler2+0x38>
   105cc:	ea000006 	b	105ec <input_handler2+0x3c>
   105d0:	ea000006 	b	105f0 <input_handler2+0x40>
   105d4:	ea000006 	b	105f4 <input_handler2+0x44>
   105d8:	ea000001 	b	105e4 <input_handler2+0x34>
   105dc:	eaffffb6 	b	104bc <input_1>
   105e0:	eaffffb9 	b	104cc <input_2>
   105e4:	eaffffcc 	b	1051c <input_7>
   105e8:	eaffffbb 	b	104dc <input_3>
   105ec:	eaffffbe 	b	104ec <input_4>
   105f0:	eaffffc1 	b	104fc <input_5>
   105f4:	eaffffc4 	b	1050c <input_6>
   105f8:	e12fff1e 	bx	lr

**Comment by Maijin** [comment]
@yfuchs-c2a Can you use markdown syntax for code so your paste look more readable?

<img width="133" alt="image" src="https://user-images.githubusercontent.com/1408600/44339823-200a0a00-a483-11e8-9164-28c64f0025a8.png">

**Comment by yfuchs-c2a** [comment]
no problem, edited my comment.

**Comment by jacobrosenthal** [comment]
Is this related? I get tons of those Missing cjmp messages on macos x86 64 binary
https://github.com/radare/radare2/files/2270677/go.zip
```
[0x01057890]> aaaa
[[anal.jmptbl] Missing cjmp bb in predecessor at 0x0152369e
[anal.jmptbl] Missing cjmp bb in predecessor at 0x015236a4
[anal.jmptbl] Missing cjmp bb in predecessor at 0x015236f2
...
[0x01057890]> s 0x0152369e
[0x0152369e]> e asm.xrefs=false
[0x0152369e]> pd--4
            0x0152368e      86691a         xchg byte [rcx + 0x1a], ch
            0x01523691  ~   00ff           add bh, bh
            ;-- imp.CFArrayGetValueAtIndex:
            0x01523692      ff2588691a00   jmp qword [reloc.CFArrayGetValueAtIndex] ; [0x16ca020:8]=0
            ;-- imp.SecKeychainItemExport:
            0x01523698      ff258a691a00   jmp qword [reloc.SecKeychainItemExport] ; [0x16ca028:8]=0
/ (fcn) sym.imp.CFDataGetBytePtr 6
|   sym.imp.CFDataGetBytePtr ();
\           0x0152369e      ff258c691a00   jmp qword [reloc.CFDataGetBytePtr] ; [0x16ca030:8]=0
/ (fcn) sym.imp.CFDataGetLength 6
|   sym.imp.CFDataGetLength ();
\           0x015236a4      ff258e691a00   jmp qword [reloc.CFDataGetLength] ; [0x16ca038:8]=0
            ;-- imp.CFDataAppendBytes:
            0x015236aa      ff2590691a00   jmp qword [reloc.CFDataAppendBytes] ; [0x16ca040:8]=0
            ;-- imp.CFRelease:
            0x015236b0      ff2592691a00   jmp qword [reloc.CFRelease] ; [0x16ca048:8]=0
[0x0152369e]> 
```

**Comment by Maijin** [comment]
@jacobrosenthal I see x86-64 in your paste, not arm.

**Comment by radare** [comment]
Those are warnings and they are there for debugging you can safely ignore them.

They are related to the assumption that a jmp reg should be after a cmp to restrict the boundaries of the precompiled table jump table

**Comment by Maijin** [comment]
Closed issue is definitely the WORSE place to ask. Better IRC/Telegram or new issue. Now I will lock here
