### ISSUE TITLE
`iz` command does not provide some strings

### ISSUE THREAD

**Issue by kriw** [radare/radare2#11107]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | 4.17.14-arch1-1-ARCH
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19405 @ linux-x86-64 git.2.8.0-103-g5b93b354a commit: 5b93b354ac8a3b35d5e61cda68e8c4f7291b019b build: 2018-08-16__16:05:41

### Expected behavior
```
[0x00001139]> iz
000 0x00002004 0x00002004   3   4 (.rodata) ascii %d\n
[0x00001139]>
```

### Actual behavior
```shell
[0x00001139]> iz

[0x00001139]>
```
### Steps to reproduce the behavior 
1. `r2 yo`
2. execute `iz`

### Additional Logs, screenshots, source-code,  configuration dump, ...

Source code
```c
#include <stdio.h>
void write_strlen(const char *str) {
    const char *iter = str;
    while (*iter) iter++;
    printf("%d\n", iter - str);
}

int main() {}
```

Disassembled code

```
/ (fcn) sym.write_strlen 69
|   sym.write_strlen (const char *s);
|           ; var int local_18h @ rbp-0x18
|           ; var int local_8h @ rbp-0x8
|           ; arg int arg1 @ rdi
|           0x00001139      55             push rbp
...
|           0x0000116a      488d3d930e00.  lea rdi, [0x00002004]       ; "%d\n" ; const char *format
...
\           0x0000117d      c3             ret
```

Drag and drop zip archives containing the Additional info here, don't use external services or link.
[buggy.zip](https://github.com/radare/radare2/files/2292759/buggy.zip)

**Comment by radare** [comment]
Thats expected. See bin. Eval vars and rabin2 manpage and you’ll see there are length filters

**Comment by kriw** [comment]
`bin.minstr` is found. Thank you.
