### ISSUE TITLE
We have to choose between: perms, flags, srwx

### ISSUE THREAD

**Issue by radare** [radare/radare2#11112]
maps, sections, ... use different names for the same thing

**Comment by radare** [comment]
yes, everyone thumbs up, but no one shares their thoughs on which should be the right word to use

**Comment by Maijin** [comment]
My opinion on this:

- flags will be confusing with existing flags definitely no
- srwx is not verbose enough and could introduce confusion
- perms to me is the best bet

**Comment by ret2libc** [comment]
perms +1

**Comment by xarkes** [comment]
perms +1

**Comment by radare** [comment]
working on this

**Comment by XVilka** [comment]
perms +1

**Comment by Maijin** [comment]
much better
