### ISSUE TITLE
Add coreinfrastructure best practices

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11116]
https://bestpractices.coreinfrastructure.org/en/projects/741

**Comment by XVilka** [comment]
Also @jvoisin please update it.

**Comment by jvoisin** [comment]
What do you want me to update?

**Comment by Maijin** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/1408600/44351201-94ec3c80-a4a1-11e8-9e4b-89fe5eb3036f.png">

and 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/1408600/44351203-9ae21d80-a4a1-11e8-8cca-df68d5a08491.png">


i guess?

**Comment by jvoisin** [comment]
Sure, done.

**Comment by XVilka** [comment]
Fixed in https://github.com/radare/radare2/commit/483495787fca574b5cd09eafb26178fa7d8e8dd7
