### ISSUE TITLE
e search.in=<tab> not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#11111]
i think this was working fine a while ago

**Comment by radare** [comment]
cc @wargio

**Comment by wargio** [comment]
Thanks!! :D

**Comment by Vane11ope** [comment]
btw is this something like 

e search.in=?

but like autocomplete the options by tab and not enter? 

if that's the case then i might need like a week or so the longest.

**Comment by wargio** [comment]
i think it's `e search.in=<tab>`

**Comment by Vane11ope** [comment]
https://github.com/radare/radare2/pull/11287
