### ISSUE TITLE
$SS and $S are 0x0 when using maps instead of sections, aaaa/aae doesnt work

### ISSUE THREAD

**Issue by jacobrosenthal** [radare/radare2#11127]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macos, x86 64 high sierra
| File format of the file you reverse (mandatory)      | raw bin
| Architecture/bits of the file (mandatory)            | arm 16
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19272 @ darwin-x86-64 git.2.8.0-120-g54f0a30ae
commit: 54f0a30ae3b77c361106ab31cb54228b87810c4e build: 2018-08-17__17:01:24

### Expected behavior
I have maps not sections
```
[0x00000000]> S=
[0x00000000]> om=
00* 0x00000000 |#----------------------------------------------------------------------------------------------------| 0x00001000 r-x 11 mbr
01  0x00001000 |#----------------------------------------------------------------------------------------------------| 0x00018000 r-x 11 softdevice
02  0x00018000 |#----------------------------------------------------------------------------------------------------| 0x0003b000 r-x 11 app
03  0x0003b000 |#----------------------------------------------------------------------------------------------------| 0x00040000 r-x 11 boot
04* 0x00000000 |#----------------------------------------------------------------------------------------------------| 0x00040000 --- 11 flash
05  0x10000000 |-------#---------------------------------------------------------------------------------------------| 0x10000100 r-- 10 ficr
06  0x10001000 |-------#---------------------------------------------------------------------------------------------| 0x10001100 r-- 9 uicr
07  0x20000000 |--------------#--------------------------------------------------------------------------------------| 0x20002000 rw- 8 softdevice_ram
08  0x20002000 |--------------#--------------------------------------------------------------------------------------| 0x20007560 rw- 7 mem.app_ram
09  0x20007560 |--------------#--------------------------------------------------------------------------------------| 0x20008000 rw- 6 stack_dummy
10  0x40000000 |----------------------------#------------------------------------------------------------------------| 0x40080000 rw- 5 io
11  0x50000000 |------------------------------------#----------------------------------------------------------------| 0x50080000 rw- 4 gpio
12  0xe0000000 |----------------------------------------------------------------------------------------------------#| 0xe0100000 rw- 3 cortex
=>  0x00000000 |^----------------------------------------------------------------------------------------------------| 0x00000100
[0x00000000]> 
```
`aae` step of `aaaa` doesnt find anything successfully I believe because it doesnt understand maps
Similarly `aae $SS @ $S` doesnt work because $SS and $S are 0x0
```
[0x00000000]> ?$
$$      0x00000000
$$$     0x00000000
$?      0x00000000
$b      0x00000100
$B      0xffffffffffff0000
$F      0x00000000
$Fj     0x00000000
$Ff     0x00000000
$FB     0x00000000
$Fb     0x00000000
$Fs     0x00000000
$FE     0x00000000
$FS     0x00000000
$FI     0x00000000
$c      0x000000b5
$r      0x0000002a
$D      0x00000000
$DD     0x00000000
$e      0x00000000
$f      0xffffffffffffffff
$j      0xffffffffffffffff
$Ja     0xffffffffffffffff
$l      0x00000002
$m      0xffffffffffffffff
$M      0x00000000
$o      0x00000000
$p      0x0000cce7
$P      0x00000000
$s      0x00040000
$S      0x00000000
$SS     0x00000000
$v      0xffffffffffffffff
$w      0x00000002
```
aae It does work with a hacky `aae $s @ 0x0` though that too sucks because aee doesnt support anal.in

**Comment by radare** [comment]
Io sections must die. Wanna help to kill them?

**Comment by radare** [comment]
we must change r_io_section for r_bin_section in libr/core/core.c

wanna help on this @rlaemmert ?

**Comment by radare** [comment]
we should have $M and $MM for maps, can yo uadd them too @rlaemmert ? (we have already $M, but no $MM

**Comment by jacobrosenthal** [comment]
Should be any raw bin where you manually define maps instead of sections, but same one from other issue will work here

https://github.com/radare/radare2/files/2316829/BLE_Beacon2.NRF51822_OTA.bin.zip

```
# r2 -i BLE_Beacon2.NRF51822_OTA.r2 --
# configure the project
e bin.baddr = 0x16000
e asm.arch = arm
e asm.cpu = cortex
e asm.bits = 16

# radare now supports s110 softdevice as an 'os' so it can annotate syscalls to softdevice
e asm.os = s110

on malloc://0x1000 0x0 r-x
omn 0x0 mbr

on malloc://0x00015000 0x1000 r-x
omn 0x1000 softdevice

on BLE_Beacon2.NRF51822_OTA.bin 0x00016000 r-x
omn 0x00016000 app

on malloc://0x2000 0x20000000 rwx
omn 0x20000000 softdevice_ram

# hardcode esil to use the app stack space?
aeim 0x20002000 0x2000 app_ram

on malloc://0x80000 0x40000000 rw-
omn 0x40000000 io

on malloc://0x80000 0x50000000 rw-
omn 0x50000000 gpio

# load and annotate all the memory sections
# note all on and om commands are 'in order' so the priority ends up stacking correctly
on malloc://0x100000 0xe0000000 rw-
omn 0xe0000000 cortex

# initialize esil vm, some analysis and syscalls specifically use it
# also one of the analyses overly flags without esil setup I think.. not sure which yet
# since we made two aeim above maybe use esil.stack to 'select' the app?? stack top 0x20004000
e esil.stack.addr = 0x20002000
e esil.stack.size = 0x2000

```

**Comment by jacobrosenthal** [comment]
Not sure I understand. Are you saying theres a commit that changed
something? That $MM commit?
This is current readout. $SS and $S still 0 but $M and $MM commit have
stuff. Is $SS going to be patched out of here and the documentation?
```
$$      0x00016238
$$$     0x00016238
$?      0x00016238
$b      0x00000100
$B      0x00010000
$F      0x00016238
$Fj     0xffffffffffffffff
$Ff     0xffffffffffffffff
$FB     0x00016238
$Fb     0x00016238
$Fs     0x00000012
$FE     0x0001624a
$FS     0x00000012
$FI     0x00000009
$c      0x000000b5
$r      0x0000002c
$D      0x00000000
$DD     0x00000000
$e      0x00000000
$f      0xffffffffffffffff
$j      0xffffffffffffffff
$Ja     0xffffffffffffffff
$l      0x00000002
$m      0x00016258
$M      0x00016000
$MM     0x00002684
$o      0x00016238
$p      0x0000290e
$P      0x00000000
$s      0x00100000
$S      0x00000000
$SS     0x00000000
$v      0xffffffffffffffff
$w      0x00000002
```

Note this is upstream master with my arm-thumb-syscalls branch that
currently does find and flag syscalls with aae (not your open PR)

hacked aae working
```
aae $s @ 0x0
0    0 * imports
1    0 * symbols
2 1523 * functions
3  420 * strings
4  183 * syscalls
```
standard aae not working
```
aae @e:anal.in=io.maps.x
 -- command not found: calc.exe
0    0 * imports
1    0 * symbols
2 1523 * functions
3  365 * strings
```

**Comment by radare** [comment]
Thats ibvious and expected

$S depends on section information, this session have 0 sessions. So the result is 0.

The $M is for the maps. So it works there. But that will not cover a debugger session.

More importantly. The aae etc shouldnt care about $S and such because it should honor anal.in

**Comment by jacobrosenthal** [comment]
Well Aae doesn't work

**Comment by radare** [comment]
how are you asnwering mails to get all the quotd replies appened to each answer you do? this is getting really anoying

btw, i have removed $SS and $S from aae in aaa

**Comment by jacobrosenthal** [comment]
With that patch `aaaa` and `aae` and `aae @e:anal.in=io.maps.x` still dont locate syscalls and put them in flags. Manual `aae $s @ 0x0` does though So I think it still needs work.

BTW that same file libr/core/cmd_anal.c file uses $S and $SS like 6 more times, take another look to see if those need to be removed as well.

Also "VdR" uses $S here https://github.com/radare/radare2/blob/master/libr/core/vmenus.c#L3075

Also aae usage still mentions sections
https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L1941

**Comment by radare** [comment]
if you have time feel free to send a pr for review

**Comment by radare** [comment]
ping?

**Comment by jacobrosenthal** [comment]
Opened up that old binary with current master. bare `aaaa` appears to find 24 of syscalls that /c finds (the remaining could be a false result) So seems good?
```
[0x00000000]> fs
    0 * classes
  155 * functions
    0 * relocs
    0 * sections
    0 * segments
    0 * symbols
   24 * syscalls
```

**Comment by jacobrosenthal** [comment]
Of note, $SS and $S are still 0x0, i presume the modern aae algorithm just doesnt use that anymore
[0x00000000]> ?$
$$      0x00000000
$$$     0x00000000
$?      0x00000000
$b      0x00000100
$B      0x00000000
$F      0x00000000
$Fj     0x000160e4
$Ff     0x000160e0
$FB     0x00000000
$Fb     0x00000000
$Fs     0x000160e0
$FE     0x000160fc
$FS     0x000160fc
$FI     0x0000b07b
$c      0x00000080
$r      0x0000001b
$D      0x00000000
$DD     0x00000000
$e      0x00000000
$f      0xffffffffffffffff
$j      0xffffffffffffffff
$Ja     0x000160f4
$l      0x00000002
$m      0xffffffffffffffff
$M      0x00000000
$MM     0x00001000
$o      0x00000000
$p      0x00004488
$P      0x00000000
$s      0x00002684
$S      0x00000000
$SS     0x00000000
$v      0xffffffffffffffff
$w      0x00000002
[0x00000000]>

**Comment by radare** [comment]
thats expected $S and $SS is only about sections. and sections can only be defined by RBin. if you want maps use $M and $MM
