### ISSUE TITLE
Visual assembler doesn't save changes

### ISSUE THREAD

**Issue by ichung** [radare/radare2#11137]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian Linux x86_64 (inside a VM)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19186 @ linux-x86-64 git.2.8.0-127-g87a360f8e commit: 87a360f8ed513fb4cda895a4274c34eb15ca9c94 build: 2018-08-18__18:08:43

### Expected behavior

`A` command in visual disassembly mode should save changes

### Actual behavior

`A` command does not change anything

### Steps to reproduce the behavior 

```
$ git clone https://github.com/monosource/radare2-explorations-binaries.git
$ cd radare2-explorations-binaries/tut1-patchme
$ make
$ cp patchme patchme_fix
$ r2 -Aw patchme_fix
> s main - 0xf
> f target_function
> s main + 0xd
> V
```
In visual mode:
- Press `p` to enter disassembly view
- Press the `A` key
- Type `call target_function`
- Press `Enter`
- Press `Y` (in response to the "Save changes? (Y/n)" prompt)

Observe that the `nop` instructions are still there and have not been replaced by the `call` instruction.  On the other hand, using the `a` key (or the `wa` command in non-visual mode) instead of `A` works fine.

**Comment by smiglo** [comment]
Seems it started working in:
`
radare2 3.0.0-git 19357 @ linux-x86-64 git.2.9.0-8-gbe913de0f
commit: be913de0f43a39c3fd17592bb61333ae4a2315a0 build: 2018-09-05__14:49:50
`

**Comment by Maijin** [comment]
ok closing then.
