### ISSUE TITLE
broken wasm anal when use aaa instead of aa

### ISSUE THREAD

**Issue by KosBeg** [radare/radare2#11134]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64 64
| File format of the file you reverse (mandatory)      | wasm
| Architecture/bits of the file (mandatory)            | wasm
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19168 @ linux-x86-64 git.2.8.0-127-g87a360f commit: 87a360f8ed513fb4cda895a4274c34eb15ca9c94 build: 2018-08-18__19:30:27

### Expected behavior
![](https://i.imgur.com/zewlYV2.png)

### Actual behavior
![](https://i.imgur.com/7cxjPuV.png)

### Steps to reproduce the behavior 
```
r2 any.wasm
aa
afl
s fn_name
pdf or pdb
```
-> all is ok

```
r2 any.wasm
aaa
afl
s fn_name
pdf or pdb
```
-> all instructions is invalid

Some WASM binaries for testing
[WASM.zip](https://github.com/radare/radare2/files/2299722/WASM.zip)

**Comment by radare** [comment]
See the output of om

**Comment by KosBeg** [comment]
```
[0x00000092]> om
 6 fd: 3 +0x00000000 0x00000000 - 0x00000285 r-x 
 5 fd: 3 +0x0000000a 0x0000000a - 0x00000023 --- fmap.type
 4 fd: 3 +0x00000027 0x00000027 - 0x00000069 --- fmap.import
 3 fd: 3 +0x0000006d 0x0000006d - 0x00000075 --- fmap.function
 2 fd: 3 +0x00000079 0x00000079 - 0x00000088 --- fmap.export
 1 fd: 3 +0x0000008d 0x0000008d - 0x00000284 --- fmap.code
```
this?

**Comment by radare** [comment]
There r 2 overlapping maps. Delete the kast ine and u should see the code again. The reason for this to halpen is probably aeim. But yry to run the subcommands of aaa one by one until u get the issue

**Comment by radare** [comment]
i think this  should be working now. please try again

**Comment by radare** [comment]
(tested, i cant repro anymore) pls comment if not

**Comment by radare** [comment]
this last issue is fixed in  a pr of me. ill merge soon
