### ISSUE TITLE
Kill R_ASM_BUFSIZE

### ISSUE THREAD

**Issue by radare** [radare/radare2#11141]
<img width="982" alt="screen shot 2018-08-19 at 05 35 23" src="https://user-images.githubusercontent.com/917142/44305178-bb12bf00-a371-11e8-80e7-95b39e2ff5dc.png">

**Comment by MaskRay** [comment]
Use `sizeof op->txt` in these cases?

**Comment by radare** [comment]
Nope. There must be no fixed size buffers at all. They are evil and limit us to do nice things. I mean they make sense for some things but not for that case. Because is better to use accessor methods to hide this complexity like i did in my pr

**Comment by radare** [comment]
cc @wargio

**Comment by wargio** [comment]
i'm ok with that.

**Comment by radare** [comment]
just use RStrBuf instead of fixed stack buffers
