### ISSUE TITLE
Text disassembly to rendered graphs

### ISSUE THREAD

**Issue by flareriderdash** [radare/radare2#11158]
During my CTF training and during my own uses of radare2 I continualy run into the annoyance of having to disassemble functions in stripped binaries that I can only obtain by doing a command like "x/64i 0xXXXXXXXX" in gdb and other similar commands provided in other debuggers. Id suggest allowing the graph renderer, both the web image generator and the interactive graphs to take in these disassembly texts  and to let me use the oh so useful graph system in radare2, I also recommend this as the automatic function detection (that is 'aaa' or 'aaf' ) of r2 does not usually map all real functions, due to the stripping.

I also think its a good idea to keep in mind all the (at least the most common) disassembly syntaxes and allow for support for many debugger disassembly outputs (ex. "x/64i 0xXXXXXXXX"). This is just for compatibility's sake

-flareriderdash

**Comment by radare** [comment]
i dont understand half of your argumetnation, so please, be more concise, what do “text disassembly” means in the context of “rendered graphs”?

and x/64i works as expected in r2, even if its a shitty gdb command i added support for it because gdbisms are hard to recover from

**Comment by flareriderdash** [comment]
What I mean by "text disassembles" I mean this 
   0x08048e44 <+0>:     push   ebp
   0x08048e45 <+1>:     mov    ebp,esp
   0x08048e47 <+3>:     sub    esp,0x28
   0x08048e4a <+6>:     mov    DWORD PTR [ebp-0xc],0x0
   0x08048e51 <+13>:    jmp    0x8048ec9 <get_expr+133>
   0x08048e53 <+15>:    mov    DWORD PTR [esp+0x8],0x1
   0x08048e5b <+23>:    lea    eax,[ebp-0xd]
   0x08048e5e <+26>:    mov    DWORD PTR [esp+0x4],eax
   0x08048e62 <+30>:    mov    DWORD PTR [esp],0x0
   0x08048e69 <+37>:    call   0x806e6d0 <read>
   0x08048e6e <+42>:    cmp    eax,0xffffffff
   0x08048e71 <+45>:    je     0x8048ed1 <get_expr+141>
   0x08048e73 <+47>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048e77 <+51>:    cmp    al,0xa
   0x08048e79 <+53>:    je     0x8048ed1 <get_expr+141>
   0x08048e7b <+55>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048e7f <+59>:    cmp    al,0x2b
   0x08048e81 <+61>:    je     0x8048eb3 <get_expr+111>
   0x08048e83 <+63>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048e87 <+67>:    cmp    al,0x2d
   0x08048e89 <+69>:    je     0x8048eb3 <get_expr+111>
   0x08048e8b <+71>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048e8f <+75>:    cmp    al,0x2a
   0x08048e91 <+77>:    je     0x8048eb3 <get_expr+111>
   0x08048e93 <+79>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048e97 <+83>:    cmp    al,0x2f
   0x08048e99 <+85>:    je     0x8048eb3 <get_expr+111>
   0x08048e9b <+87>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048e9f <+91>:    cmp    al,0x25
   0x08048ea1 <+93>:    je     0x8048eb3 <get_expr+111>
   0x08048ea3 <+95>:    movzx  eax,BYTE PTR [ebp-0xd]
   0x08048ea7 <+99>:    cmp    al,0x2f
   0x08048ea9 <+101>:   jle    0x8048ec9 <get_expr+133>
   0x08048eab <+103>:   movzx  eax,BYTE PTR [ebp-0xd]
   0x08048eaf <+107>:   cmp    al,0x39
   0x08048eb1 <+109>:   jg     0x8048ec9 <get_expr+133>
   0x08048eb3 <+111>:   mov    eax,DWORD PTR [ebp-0xc]
   0x08048eb6 <+114>:   lea    edx,[eax+0x1]
   0x08048eb9 <+117>:   mov    DWORD PTR [ebp-0xc],edx
   0x08048ebc <+120>:   mov    edx,eax
   0x08048ebe <+122>:   mov    eax,DWORD PTR [ebp+0x8]
   0x08048ec1 <+125>:   add    edx,eax
   0x08048ec3 <+127>:   movzx  eax,BYTE PTR [ebp-0xd]
   0x08048ec7 <+131>:   mov    BYTE PTR [edx],al
   0x08048ec9 <+133>:   mov    eax,DWORD PTR [ebp-0xc]
   0x08048ecc <+136>:   cmp    eax,DWORD PTR [ebp+0xc]
   0x08048ecf <+139>:   jl     0x8048e53 <get_expr+15>
   0x08048ed1 <+141>:   mov    edx,DWORD PTR [ebp-0xc]
   0x08048ed4 <+144>:   mov    eax,DWORD PTR [ebp+0x8]
   0x08048ed7 <+147>:   add    eax,edx
   0x08048ed9 <+149>:   mov    BYTE PTR [eax],0x0
   0x08048edc <+152>:   mov    eax,DWORD PTR [ebp-0xc]
   0x08048edf <+155>:   leave  
   0x08048ee0 <+156>:   ret

and what i want to do with this is to basically have radare use the graph renderers to turn the above into
something more useful. Also when I referenced the gdb command in the last post I meant that the command was executed IN GDB not through radare. I hope this gives you a better understanding now.

+-----------------------+              +-------------------------+             +-------------------------------+
| Text Disassembly | --------> | Radare renderer(s) | --------> | The pretty radare graph|
+-----------------------+              +-------------------------+              |(Via the "VV" command)|
                                                                                              +-------------------------------+

**Comment by radare** [comment]
what do you get in the graphs? because graphs nodes are suposed to have the disasm inside., i dont see the difference or problem you are having yet

**Comment by radare** [comment]
you can create your own radare ascii art graphs by hand using the agn/age/agg commands. but youill need to analyze code, to do that, so you end up needing r2, i dont understand why doing that from gdb is that important, when gdb is way inferior to r2 in interface and analysis features.

you cant analyze text, just dump the bytes, but them inside an r2 buffer and let it do the magic , but youll miss many other information in context like emulation and data refernces that are outside the block you are disassembling

**Comment by flareriderdash** [comment]
the problem i have is when i try to get rendered graphs (the ascii node disassembled function things)  from address that radare didnt mark as a function with fcn.*

**Comment by flareriderdash** [comment]
It just doesnt disassemble into nodes

**Comment by flareriderdash** [comment]
So I want to be able to turn some disassembled memory (like above) into these node graphs. Thats all i'm saying.

**Comment by radare** [comment]
you need to analuze code to get a graph, thats a requirement to underastand the basic blocks and such.

no tool is able to magically convert text of a disasm into a graph without analying or assembling the code in there. you’ll get so many wrong things if you try to do it this way

**Comment by flareriderdash** [comment]
jeez idk crap. umm well, I guess I can only say that the reason I have had to use gdb is because when I do the aa* commands it maps only some of functions and when there is a function at a specific offset that isnt mapped I try to generate a graph with the VV command and i get no where. So i just jumped to gdb to get the assembly and hoped i could possibly with as little hassle as possible generate a flow graph and breakup the wall of text a little bit

**Comment by Maijin** [comment]
You can analyze using `af`:

```
af @ 0x08048e44
VV @ 0x08048e44
```
Will give visual mode of this disassembly, if that's what you are looking for.

Also make sure you are using radare2 from git, since you did not follow the template for creating issue we can't check if there is a problem on that side.

**Comment by flareriderdash** [comment]
thanks
