### ISSUE TITLE
Provide/Document script to fix style in patches

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#11170]
It would be great to have a way to automatically fix a patch/commit for style, so both reviewers and contributors don’t have to check for those stuff but can just use that script

**Comment by Maijin** [comment]
that's ./sys/indent.sh

**Comment by ret2libc** [comment]
@Maijin as already said on telegram that fixes an entire file, which is not exactly what we want. Also, afaik it doesn’t work well on all files (iirc there’s a whitelist of files where it can run successfully)

**Comment by Maijin** [comment]
The whitelist files are the one that have been entirely processed and reviewed. It works on all files. but yes then what solution do you suggest?

**Comment by ret2libc** [comment]
Again, an approach that allows contributor to just run that on each commit to prettify them. So only code that is touched by a contributor is style-fixed. If you look at how prs are reviewed you’ll see that there are tons of style fixes that could be reported just by saying “use script xxx”

**Comment by MaskRay** [comment]
Can you just move `doc/clang-format` to `.clang-format` so that clang-format editor plugins will use the file?

**Comment by ret2libc** [comment]
@MaskRay i'm doing that in https://github.com/radare/radare2/pull/11261, but consider that the clang-format file is not enough unfortunately. In particular, the main problem is that we *do not* use a space before parenthesis when declaring/defining functions, but we *do* use a space when calling functions. This does not seem to be supported by clang-format.

**Comment by ret2libc** [comment]
fixed with https://github.com/radare/radare2/commit/58ae11607a359c8f8cfaa67f400f2ab38043db4b
