### ISSUE TITLE
`r_fmt` function as a define to `sdb_fmt`

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11186]
I think we need `r_fmt` function as a define to `sdb_fmt`. Because using `sdb_fmt` just for formatting strings outside of database usage context confuses a little, since it has nothing to do with database. So just a simple alias would solve this semantic problem.

**Comment by ret2libc** [comment]
Imho it would be super cool to have a separate util project used by both sdb and radare

**Comment by radare** [comment]
Lets just add two more dependencies 🎉🎉

**Comment by XVilka** [comment]
@ret2libc simple define is enough to close the bug, no need for such a heavyweight solution. It might be more beautiful, but with almost 1k other bugs/issues it is of very low priority.

**Comment by ret2libc** [comment]
Well, if you are worried about sdb_fmt you should be worried about sdblist too or sdbht because they are functions/data structures that have nothing to do with database.

**Comment by radare** [comment]
Nothing to do... well a database without them wouldnt work. And the reason for having there is for consistency. And yes, the plan was to kill rlist and use sdblist instead.

**Comment by radare** [comment]
This should be moved into sdb
