### ISSUE TITLE
Add Jump keys in memory operands

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#11204]
Hello.
I have a bit suggestion. 
May you please to add "fast jump" keys into global variables ("V" and "VV" modes).
I mean all addressable memory in operands of instructions:

![temp](https://user-images.githubusercontent.com/22872513/44485154-32de3380-a669-11e8-8edf-2197fe78cfe4.png)
In my experience it will be very usefull. Manual entering address of some variable is a little bit not convenient.

**Comment by Maijin** [comment]
That will clutter the view, imho we shouldn't do that, at least not by default.

**Comment by radare** [comment]
Theres. Akey to toggle between code and data references for hot keys. Just use it

**Comment by Maijin** [comment]
Ah yes true `r`

**Comment by s0i37** [comment]
Indeed!
Thank you.

**Comment by s0i37** [comment]
But seems it doesn't work in "VV" mode...

**Comment by radare** [comment]
works now, just press the 'r' key

**Comment by s0i37** [comment]
from "VV" help:
r            - refresh graph
No?

**Comment by radare** [comment]
maybe i didn't updated the help. but it works

**Comment by s0i37** [comment]
Yes. I updated r2.
