### ISSUE TITLE
Add eval configurator in V!

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11205]
Add eval configurator (`Ve`) in `V!` ping @Vane11ope.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/11215

**Comment by radare** [comment]
we can just reuse the one in Ve/Vbe, or you want something inside a panel?

**Comment by Maijin** [comment]
The issue is to have a menu selection with this, reusing Ve/Vbe yep

**Comment by radare** [comment]
We have already V!be

**Comment by radare** [comment]
Ve must be deprecated imho

**Comment by Maijin** [comment]
Yes but V! still need an access to Vbe then

**Comment by radare** [comment]
it was already there V!be works too

**Comment by Maijin** [comment]
Yep now it's fixed thanks
