### ISSUE TITLE
esil expression cmp bug

### ISSUE THREAD

**Issue by yfuchs-c2a** [radare/radare2#11219]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 32
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            | arm 32.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19172 @ linux-x86-64 git.2.8.0-149-g6ae0c86f8
commit: 6ae0c86f846a8df5d9cd151ddbd92a9c2c0e715f build: 2018-08-23__14:07:38

![selection_004](https://user-images.githubusercontent.com/37180015/44527311-1be22480-a6ef-11e8-82e7-2f4045cdcdd0.png)

### Expected behavior
cmp should set the cf too.

### Actual behavior
the cmp expression is wrong or am i missing something?
it should also set the cf i believe.
after that there is a bls instruction that checks the cf (and zf) and so the emulation is wrong

**Comment by radare** [comment]
See asm_arm_cs.c and find the _INS_CMP to find the esil expression. Just fix it and type make to test. Shouldnt be difficult. Its easier to fix than understand the issue :)
