### ISSUE TITLE
aeim uses flagspace as a database

### ISSUE THREAD

**Issue by jacobrosenthal** [radare/radare2#11223]
https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3714
```
[0x00000000]> aeim 0x20002000 0x5560 app_ram
[0x00000000]> f~aeim
0x20002000 21856 aeim.stack
0x00000007 1 aeim.fd
```
and since its pointless it looks like shit when i visualize
```
            0x00000000      c007           lsls r0, r0, 0x1f
            0x00000002      0000           movs r0, r0
            0x00000004      d106           lsls r1, r2, 0x1b
            0x00000006  ~   0000           movs r0, r0
            ;-- aeim.fd:
            0x00000007      00             unaligned
            0x00000008      d100           lsls r1, r2, 3
```

Presumably this code is pre sdb and most people dont have stuff at 0x0 so nobody cared about polluting flagspace, but I do and sdb exists. Whats a db in the aeim lifecycle I could stuff this in instead?

aeim.stack is less annoying so I dont have opinions on if that should go as well. Thoughts?

**Comment by radare** [comment]
Yep. You can use the global sdb with the k command to save this fd instead of a flag. Feel free to send a pr with this change. Sounds legit
