### ISSUE TITLE
rasm2 flag change proposal

### ISSUE THREAD

**Issue by radare** [radare/radare2#11237]
```
 -o [offset]  Set start address for code (default 0)
 -O [file]    Output file name (rasm2 -Bf a.asm -O a)
```

my proposal is to use this:

```
-o [file]
-@ [offset]
```

this way is in sync with rabin2

**Comment by MaskRay** [comment]
This requires either changes in r2 or new/bin/r2r.js: `! ....... @` isn't supported yet.

**Comment by radare** [comment]
Yep.. but is ppl happy with this change? Imho it makes more sense than abusing lower and uppercase o

**Comment by radare** [comment]
lets wait after r2con to do this change. can you update r2r with this?
