### ISSUE TITLE
Change currently selected file?

### ISSUE THREAD

**Issue by jrozner** [radare/radare2#11250]
Is there a way to change the currently selected file with respect to the files listed as the output for "o"? I was attempting to re-open the binary I was working on as writable using "oo+" but it was having no effect because the currently selected file was some malloced one that was opened after it. Digging through the helps within the "o" options I didn't find anyway to do this and ended up having to go into the project I was working on and manually edit the rc file. Did I miss something or is there no way to do this?

**Comment by radare** [comment]
op

**Comment by jrozner** [comment]
Ah, that worked. Is changing the help text from "prioritize given fd" to something like "select the given fd as current file" something that could be done? The wording is a little confusing who doesn't already know how it all works.

**Comment by radare** [comment]
Make a PR improving help messages and we can discuss that in there. if you dont want to git clone and such, just press the pencil button
