### ISSUE TITLE
call + pop esi references not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#11309]
on 32bit mac binaries strings are referenced using this technique which basically makes all references to fail.

<img width="1075" alt="screen shot 2018-08-29 at 21 54 39" src="https://user-images.githubusercontent.com/917142/44811924-2bbda500-abd6-11e8-814d-e24ca49c71a2.png">

**Comment by ret2libc** [comment]
Isn’t this just a type of PIC? It doesn’t seem specific to mac.

**Comment by XVilka** [comment]
Can you craft a testcase?

**Comment by radare** [comment]
yes it is, can give more details, but i will provide a test and a fix hopefully today.

i just filled the issue as a reminder

**Comment by radare** [comment]
i provided a fix, but cant provide a test, and it seems to introduce other issues. also this code is only used in the asm.emu comments. not in the standard emulation routines, which imho is fine, but must check why its red
