### ISSUE TITLE
radare2 disassembly commands doesn't work properly.

### ISSUE THREAD

**Issue by hdarwin** [radare/radare2#11325]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ubuntu 18.04 x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0 0 @ linux-x86-64 git.2.8.0 commit: HEAD build: 2018-08-30__08:44:19

I get [binary](https://github.com/radare/radare2/files/2339269/bin.zip) from some ctf. it is obfuscated by o-llvm. and control flow flattening makes it's function too big. what I want to do is de-obfuscate the binary. but radare2's function boundary aware commands doesn't handle it properly. disassembly emit invalid at some point.
```
root@ubuntu:~# r2 -A bin
[0x00000a40]> pdf @sym.parse__IO_FILE~invalid
| |||||||   0x000027c3      0f             invalid
[0x00000a40]> pd 1 @0x000027c3
|       ,=< 0x000027c3      0f8f59070000   jg 0x2f22
[0x00000a40]> b
0x100
[0x00000a40]> b 50M
[0x00000a40]> pdf @sym.parse__IO_FILE~invalid
| |||||||   0x000027c3      0f             invalid
```
I checked pdf, pdr, pdj, pdfs, pif doesn't work for it. I compared result with IDA. I confirmed that IDA can award function boundary and disassemble the function well.

**Comment by mendax47** [comment]
![image](https://user-images.githubusercontent.com/6140928/44914347-c8f11880-ad51-11e8-9d7d-ed20abc179c3.png)

Working Fine With Windows..

**Comment by radare** [comment]
pdf is the wrong command to use when disassembling obfuscated or non linear functions, so its expected to have invalids in there. use pdr or the graph view to visualize
