### ISSUE TITLE
Unnecessary brace around a single simple statement

### ISSUE THREAD

**Issue by MaskRay** [radare/radare2#11347]
The current r2 coding style mandates all `if/while/for` statement bodies to be enclosed in braces, this is even true for single simple statements, e.g. `return NULL;` `continue;` `break;`. Sometimes review comments are overwhelmed by such style changes that are near the code authors have touched.

If you have some time to mess around during r2con and don't have a more meaningful topic, or you just want to debate something... This talks about single simple statements, so "dangling else" is out of scope.

```c
		if (da->capacity < abbr_code) {
			return NULL;
		}
...
		if (fd != -1 && map->fd != fd) {
			continue;
		}
```

The most common argument for mandatory braces is that it is more fool-proof. If you add a second statement you don't need to remember adding the curly braces.
* Perl `if` statement
* [Apple's SSL/TLS bug](https://www.imperialviolet.org/2014/02/22/applebug.html)

The downside is that it brings visual noise and increases the number of lines from 1 or 2 to 3. These patterns are very common in r2, every little makes a mickle, the wasted number of lines is usually large and harms readability.

(a)
```c
if (da->capacity < abbr_code) return NULL;
```

(b)
```c
if (da->capacity < abbr_code)
  return NULL;
```

(c)
```c
if (test)
    foo();
else
    bar();
```

I strongly support `(b)`, weakly support `(a)` (for `break;` `continue;`), and think `(c)` is acceptable (when one branch is enclosed by braces, the other should also be enclosed)

**Comment by nsajko** [comment]
(c) is such a bad idea, and leaving out braces is a bad idea in general: it causes bugs where somebody thinks he is adding statements to the block, but actually they are coming after the block. (Though this kind of bug can be caught by compilers' misleading indentation warnings, at least in a project that already has consistent indentation.)

**Comment by devnexen** [comment]
@MaskRay I guess that comes from your BSD tastes (style 9) ? :-) a would not fit the general style, b maybe as long there is no nested blocks ... But I think the style is ok as is (even though sometimes difficult to remember, navigating between so many projects and styles...).

**Comment by MaskRay** [comment]
@devnexen And you know, it is especially frustrating when you have a PR lingering long before, then someone does change like 4a722e80d8f7924cfbe2ddf72a55e2f36f1e23ac and next, some collaborator jumps out and asks you to rebase.
