### ISSUE TITLE
Add C11 (or C99) compile options

### ISSUE THREAD

**Issue by MaskRay** [radare/radare2#11346]
There have been many PRs changing `for (int` just to appease GCC<5 on some Linux distributions and/or MSVC without explicit C language setting. The latest is https://github.com/radare/radare2/pull/11324

```diff
- for (int i=0; i < TCACHE_MAX_BINS; i++) {
+ int i;
+ for (i = 0; i < TCACHE_MAX_BINS; i++) {
```

It compiles on some systems while fails on others because the GCC C language mode:

* GCC 4.7 started to support -std=gnu11
* GCC 5/clang 3.6 switch the default for C from `-std=gnu89` to `-std=gnu11`

These changes could be avoided if r2 enabled explicit C language setting, e.g. `-std=gnu11` for GCC/clang. This issue is probably in vain because a predecessor was very quickly closed https://github.com/radare/radare2/pull/8183/files
But toolchains (MSVC included) are evolving. What are considered important or take a significant amount of mark share may not worth considering after one year. It may be time to revisit this change.

**Comment by radare** [comment]
`+ for (0; i < TCACHE_MAX_BINS; i++) {`

this statement compiles but it does the wrong thing

```
a.c:4:6: warning: expression result unused [-Wunused-value]
```

**Comment by radare** [comment]
Before doing -std=gnu11 i would go for -std=c99 which makes more sense and it's a standard. I did some tests on different toolchains and seems to be only needed by gcc. msvc and clang support `for (int` by default.

Must try on some old machines i have which will probably not work on compilers before supporting c99. But i assume there must be newer toolchains for them already. The funny thing is that clang handles this even if you force it with -std=c89

**Comment by MaskRay** [comment]
No you should try `-std=gnu99` first if you are not sure if `-std=gnu11`, though I also prefer `-std=c99` `-std=c11`. `-std=gnu11` is actually very safe because *all users with GCC>=5 or clang>=3.6 are testing in this mode*. But GCC>=4.7 might be a portability issue you'd like to consider.

```
% diff =(fclang -std=c99 -xc /dev/null -E -dM) =(fclang -std=gnu99 -xc /dev/null -E -dM)
229d228
< #define __STRICT_ANSI__ 1
347a347,348
> #define linux 1
> #define unix 1
```

**Comment by Escapingbug** [comment]
+1 for that for loop scope kinda thing.

**Comment by Maijin** [comment]
I’m +1 for moving to what @MaskRay proposed or another solution is to force the usage of -std=c89 and if not respected display error in Travis. That should end-up these “for (int”, “restrict” endless and pointless discussions in PRs and Telegram

**Comment by xarkes** [comment]
So what's wrong with going on with `-std=c99` `-std=c11`? I think that'd be the best solution if I understood correctly.

**Comment by nsajko** [comment]
> So what's wrong with going on with -std=c99 -std=c11? I think that'd be the best solution if I understood correctly.

That would require fixing some errors for r2 to compile; mind that most people are using the default option, which is '-std=gnu17'.

**Comment by nsajko** [comment]
I think the choice right now is between '-std=gnu99' and '-std=gnu11', where the former would be chosen if compatibility with old versions of GCC is wanted.

**Comment by XVilka** [comment]
So what do we do? @xarkes we can't do `-std=c11` because MSVC is very bad at C11. C99 is a best option, imho.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/95d92d12dcd9bc88be84bfa883952359ef297383

**Comment by XVilka** [comment]
Fixed now.
