### ISSUE TITLE
Visual Graph doesn't show function argument comments

### ISSUE THREAD

**Issue by mohe2015** [radare/radare2#11342]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.1 LTS x86_64
| File format of the file you reverse (mandatory)      | ELF 64-bit LSB shared object
| Architecture/bits of the file (mandatory)            | x86-64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19300 @ linux-x86-64 git.2.8.0-281-g5c0eaa71f
commit: 5c0eaa71f1f7c20f05bf0302eecd8da3b8d7663d build: 2018-09-01__09:43:20

### Expected behavior
Visual mode (`VV`) shows the comment with the arguments of the memset function
### Actual behavior
You can only see that comment if you use `pdf`

### Steps to reproduce the behavior 
[libnative-lib.zip](https://github.com/radare/radare2/files/2342167/libnative-lib.zip)
https://asciinema.org/a/ZC1Qmp8oHShOKwENOYTaJlJrW
```
r2 ~/Downloads/lib/x86_64/libnative-lib.so
aa
s sym.Java_com_example_myapplication_MainActivity_stringFromJNI
pd 1 @ 0x0000df71
VV
```
- Or even better, create a Pull-Request for the https://github.com/radare/radare2-regressions containing the test case examples can be found in the t/ folder see for example https://github.com/radare/radare2-regressions/blob/master/t/cmd_search#L7

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by mohe2015** [comment]
I'm trying to fix it

**Comment by cyanpencil** [comment]
@mohe2015 are you still trying to fix it? 
If not, I will work on this

**Comment by mohe2015** [comment]
@cyanpencil No, I'm not and I woukd really appreciate it if you could work on it :)

**Comment by radare** [comment]
this one is important to get fixed before the tomorrow's release imho.

**Comment by Maijin** [comment]
thanks for fixing that before r2con 👍
