### ISSUE TITLE
Visual Mode Disassembly View paints slow until `di` command

### ISSUE THREAD

**Issue by TobalJackson** [radare/radare2#11352]
### Work environment
Arch Linux x86_64
-> % r2 -v     
radare2 2.9.0-git 19366 @ linux-x86-64 git.2.8.0-283-gf538120c0
commit: f538120c04b9dedde7a2f616bd96cef39a2327ea build: 2018-09-01__17:08:06

### Expected behavior
using `r2 /bin/ls`
followed by `Vpp`
should have a usable visual mode, allowing user to scroll up and down 
### Actual behavior
Visual mode is painted extremely slowly, rendering it nearly unusable.  Using `:di` command fixes the issue.
### Steps to reproduce the behavior 
`r2 /bin/ls`
`Vpp`
<use up/down arrows to try navigating disassembly. Experience slowness>

**Comment by radare** [comment]
This is a linux specific issue
