### ISSUE TITLE
axtj hangs (doesn't seem consistent)

### ISSUE THREAD

**Issue by yfuchs-c2a** [radare/radare2#11374]
pull request #11143 

https://github.com/radare/radare2/blob/762ea6e98809d2615b94649ddd930349969116c6/libr/core/cmd_anal.c#L5432-L5438

something about it make it sometimes hang (infinite loop?)

if i change the line to how to it was originally then it works:
`r_parse_filter (core->parser, core->flags, 
 	r_asm_op_get_asm (&asmop), str, sizeof (str), core->print->big_endian);`

i'm not sure if this is the right fix..

thanks

**Comment by radare** [comment]
thanks for pointing out. should be fixed now in master
