### ISSUE TITLE
rahash2 provides incorrect hash when given multiple files

### ISSUE THREAD

**Issue by geekscrapy** [radare/radare2#11370]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| OS/arch/bits (mandatory)                             | Kbuntu 64 4.15.0-33-generic
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.3.0-git 17078 @ linux-x86-64 git.2.2.0-271-g5ff5a67; commit: 5ff5a676438f0cec7cdd242d03807c8b92678ff9 build: 2018-01-22__12:02:30

### Expected behavior
Provide the correct md5 as per md5sum
```
$ md5sum *
60b725f10c9c85c70d97880dfe8191b3  a
3b5d5c3712955042212316173ccf37be  b
2cd6ee2c70b0bde53fbe6cac3c8b8bb1  c
```

### Actual behavior
The md5 is given from the first file only
```
$ rahash2 -a md5 * 
a: 0x00000000-0x00000001 md5: 60b725f10c9c85c70d97880dfe8191b3
b: 0x00000000-0x00000001 md5: 60b725f10c9c85c70d97880dfe8191b3
c: 0x00000000-0x00000001 md5: 60b725f10c9c85c70d97880dfe8191b3
```
### Steps to reproduce the behavior 
$ echo a > a
$ echo b > b
$ echo c > c
$ md5sum *
60b725f10c9c85c70d97880dfe8191b3  a
3b5d5c3712955042212316173ccf37be  b
2cd6ee2c70b0bde53fbe6cac3c8b8bb1  c
$ rahash2 -a md5 * 
a: 0x00000000-0x00000001 md5: 60b725f10c9c85c70d97880dfe8191b3
b: 0x00000000-0x00000001 md5: 60b725f10c9c85c70d97880dfe8191b3
c: 0x00000000-0x00000001 md5: 60b725f10c9c85c70d97880dfe8191b3

**Comment by geekscrapy** [comment]
Issues still exists in
```
rahash2 2.9.0-git 19337 @ linux-x86-64 git.2.8.0-310-gb9250fa
commit: b9250fae43709eb52e095dbc607e60d321eeb2d1 build: 2018-09-03__11:26:44
```

**Comment by Maijin** [comment]
Hello @geekscrapy , thanks for reporting, here are locations+examples for creating tests on rahash2 - https://github.com/radare/radare2-regressions/blob/master/new/db/tools/rahash2
