### ISSUE TITLE
Can`t restore offset when loading project

### ISSUE THREAD

**Issue by zmeyt** [radare/radare2#11385]
Windows Cutter 1.7.1 64b

Project loads with zero data offset.
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Gentoo PPC 32  Big
| File format of the file you reverse (mandatory)      |  raw kernel image(memory map) from uImage
| Architecture/bits of the file (mandatory)            | PPC/32
| r2 -v full output, **not truncated** (mandatory)     |  r2-2.8.0-189-gf82b28982
### Expected behavior
When loading project it must restore loaded file offset 

### Actual behavior
Data loaded at ZERO offset

### Steps to reproduce the behavior 
start r2, load image with offset, save project, load saved project - now we have loaded image without offset.

**Comment by radare** [comment]
provide test with r2, not cutter otherwise we cant test/reproduce
