### ISSUE TITLE
Arithmetic shift right/left

### ISSUE THREAD

**Issue by bodgergely** [radare/radare2#11381]
#radare2 -v
radare2 2.7.0-git 19168 @ linux-x86-64 git.2.6.0-43-gf7c43fcfa
commit: f7c43fcfad3567fc8f992e468cdbe88d362d5371 build: 2018-09-03__14:14:46

Arithmetic shitft left/right calculations made with the '?'  

Based on https://radare.gitbooks.io/radare2book/first_steps/expressions.html

[0x00019f97]> ?vi 8 > 3
[0x00019f97]> ?vi 8>3
8
[0x00019f97]> ?vi 8<3
8

Using the << works okay:

[0x00019f97]> ?vi 256<<2
1024

Shift left >> work weird:

[0x00019f97]> ?vi 1024>>2
[0x00019f97]>

or 

[0x00019f97]> ?vi 1024>2
[0x00019f97]>

**Comment by radare** [comment]
use quotes, otherwise you are writing files
```
> "?vi 1024>>2"
256
```
