### ISSUE TITLE
r_str_encode_utf16 doesn't work as expected

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#11395]
```
file     /tmp/Здравствуйте
```
```
"file":"/tmp/\u00d0\u0097\u00d0\u00b4\u00d1\u0080\u00d0\u00b0\u00d0\u00b2\u00d1\u0081\u00d1\u0082\u00d0\u00b2\u00d1\u0083\u00d0\u00b9\u00d1\u0082\u00d0\u00b5"
```
While it should be something like:
```
"file":"/tmp/\u0417\u0434\u0440\u0430\u0432\u0441\u0442\u0432\u0443\u0439\u0442\u0435"
```
at least for the json output.

Please if I don't fix it, add unit tests to that. Thanks.
This is more or less related: https://github.com/radareorg/cutter/issues/589

**Comment by radare** [comment]
Please provide a test script to reproduce this issue, do you want to do this fix?

**Comment by xarkes** [comment]
```sh
#!/bin/sh

filename=$(printf "/tmp/\u0417\u0434\u0440\u0430\u0432\u0441\u0442\u0432\u0443\u0439\u0442\u0435")
touch "${filename}"
r2 -qc 'ij' "${filename}"
```

It seems to yield the correct output if the filename is shorter though.
I won't have time to look at it soon.

**Comment by radare** [comment]
is this fixed with latest pr on sdb?

**Comment by xarkes** [comment]
Just tried with
```
radare2 3.0.0 20348 @ linux-x86-64 git.3.0.0
commit: 13e3ebd2aa6653eb5b6bdd65a93dcddf3550fcfa build: 2018-10-16__02:02:51
```
the output is still the same.

**Comment by thestr4ng3r** [comment]
Depends on what `r_str_utf16_encode()` is even supposed to do. The name makes pretty much no sense in my opinion. We should probably kill it. In the case of `ij`, it can be replaced by `r_str_escape_utf8 (str, false, true)`.
