### ISSUE TITLE
Dietline features in the HUD mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11396]
Hotkeys like in usual CLI.
For example if you enter `f~...` it will show the HUD, but the usual dietline key bindings do not work, e.g. `Ctrl-w` or `Alt-b`.

**Comment by radare** [comment]
Please explain this issue in more detail. it's not clear what are you asking for or what's needed to be done

**Comment by XVilka** [comment]
@deepakchethan please see this one for the dietline too.
