### ISSUE TITLE
Intel MCS-96 support

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1140]
The [Intel MCS-96]( https://en.wikipedia.org/wiki/Intel_MCS-96 ) is a family of microcontrollers (MCU) commonly used in embedded systems. The family is often referred to as the 8xC196 family, or 80196, the most popular MCU in the family. These MCUs are commonly used in hard disk drives, modems, printers, pattern recognition and motor control.

**Comment by condret** [comment]
basic support is done now
