### ISSUE TITLE
Easy way of changing the return type for the function

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11404]
Like we easily can change the arguments types with `afvt`, maybe `afrt`, or something like this.

**Comment by sivaramaaa** [comment]
It needs more discussion, moving to 3.3 !

**Comment by XVilka** [comment]
@radare do you have any suggestions for this? Just to be able to change only return type ("tr int"), not to type the whole "td int main(int argc, char** argv);"

**Comment by radare** [comment]
afsr maybe? Afs! Opens vim we can just add this subcommand to it

**Comment by radare** [comment]
Thats easy issue for @oxcabe

**Comment by radare** [comment]
ping @oxcabe

**Comment by oxcabe** [comment]
Will do before release, after DWARF

**Comment by radare** [comment]
fyi the release is this sunday

**Comment by XVilka** [comment]
@radare he didn't mention before what release though...

**Comment by radare** [comment]
that should be very easy to do because its just adding 1 command for something that is already possible. shouldnt take more than 15min to do
