### ISSUE TITLE
Feature request: renaming offsets in instructions

### ISSUE THREAD

**Issue by securisec** [radare/radare2#11411]
Recently, a question was asked on TG by oddcoder if this was possible: 

Rename this 
`mov dword [0x401234], eax`
into `mov dword [some_name] eax`

A suggested solution using flags isnt exactly what was hoped for, ` f myglobal=0x401234`

This would be a really neat feature if this was possible inside in the disassembly.

**Comment by XVilka** [comment]
What do you mean by "inside the disassembly"? You mean to substitute the offset with the flag name automatically?

**Comment by securisec** [comment]
Automatically, or on demand. 

![image](https://user-images.githubusercontent.com/22226823/45138246-c3dd0080-b179-11e8-91ea-67c10204c268.png)

It would be cool if the yellow box could be renamed to something that the user defines.
