### ISSUE TITLE
Do not show types/vars comments in the hexadecimal mode view

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11427]
```
r2 /bin/ls
aaa; s main; VpP
```
then press '|' and type `pd` then press enter.

They do not make any sense in the hexdump mode and can clog the output:
![image](https://user-images.githubusercontent.com/203261/45175213-7034ea80-b23f-11e8-94c3-a8f3ab9b1025.png)

**Comment by radare** [comment]
px vs pxc, they are useful, but maybe not when using the column mode thing

**Comment by radare** [comment]
please provide commands u type to get this

**Comment by XVilka** [comment]
Added.

**Comment by radare** [comment]
i think the correct fix should be to chop the output at specific column.
