### ISSUE TITLE
GitHub project license is LGPL v3.0

### ISSUE THREAD

**Issue by rryan** [radare/radare2#11422]
The GitHub project says the license is LGPL 3.0, which I believe is incorrect?

<img width="1006" alt="screen shot 2018-09-06 at 9 04 09 am" src="https://user-images.githubusercontent.com/26527/45170206-2c48d380-b1b4-11e8-88ca-d75fd4bc2538.png">

**Comment by radare** [comment]
r2 is LGPL3, why do you think it’s incorrect?

**Comment by radare** [comment]
just curious, which license do you think it is? :D

**Comment by rryan** [comment]
Oh huh, isn't the text of `COPYING` the GPLv3?

**Comment by rryan** [comment]
Oh, I didn't see `COPYING.LESSER`. Sorry for the noise :).
