### ISSUE TITLE
penel mode: `b` is not shown unless you move

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#11433]
Issue:
When I am in panel mode (`V!`), and I press F2 to set a breakpoint, the `b` near the instruction is not visible. To make it visible I have to move one line below and then go up again. After that, i can see the `b`.

Expected behaviour:
The expected behaviour is of course that as soon as I press F2, the disassembly is refreshed and the `b` is visible.

**Comment by radare** [comment]
PENEL jijiji

**Comment by Vane11ope** [comment]
i'm on it right now
