### ISSUE TITLE
pd/pD does not correctly show invalid opcodes

### ISSUE THREAD

**Issue by 0ki** [radare/radare2#11434]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | AMD x86-64 architecture
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0 19349 @ linux-x86-64 git.2.9.0-1-g00144a3 commit: 00144a348c47802f203e5de9add609ea1b0808e4 build: 2018-09-05__11:25:21

### Expected behavior
```
[0x555555554f12]> x 4
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x555555554f12  553f cfc4                                U?..
[0x555555554f12]> pD 4
            ;-- section_end..text:
            ;-- section.c0de:
            ;-- rdi:
╭ (fcn) fcn.555555554f12 2
│   fcn.555555554f12 ();
│           ; CALL XREFS from main (0x555555554d82, 0x555555554ddd, 0x555555554de9)
│           ; DATA XREF from entry2.init (0x555555554e0f)
│           0x555555554f12      55             push rbp                ; [15] -r-x section size 101 named c0de
│           ;-- rip:
│           0x555555554f13      3f             invalid
            0x555555554f14      cf             iretd
            0x555555554f15      c4             invalid
```

### Actual behavior
```

[0x555555554f12]> x 4
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x555555554f12  553f cfc4                                U?..
[0x555555554f12]> pD 4
            ;-- section_end..text:
            ;-- section.c0de:
            ;-- rdi:
╭ (fcn) fcn.555555554f12 2
│   fcn.555555554f12 ();
│           ; CALL XREFS from main (0x555555554d82, 0x555555554ddd, 0x555555554de9)
│           ; DATA XREF from entry2.init (0x555555554e0f)
│           0x555555554f12      55             push rbp                ; [15] -r-x section size 101 named c0de
│           ;-- rip:
│           0x555555554f13      **55**             invalid
            0x555555554f14      cf             iretd
            0x555555554f15      **cf**             invalid
```

### How to reproduce
$ r2 -qc "woR; px 10; pd 10" -

**Comment by 0ki** [comment]
Seems this is a bug in x86 architecture.

**Comment by 0ki** [comment]
Seems like a bug specific to working with x86 arch.

**Comment by 0ki** [comment]
#11462 
pancake has really good memory, doesn't he?

**Comment by radare** [comment]
bytes are not shown when invalid

<img width="829" alt="screen shot 2018-09-10 at 16 51 20" src="https://user-images.githubusercontent.com/917142/45305043-c93f9f80-b519-11e8-9f93-e8214d5f2cff.png">

**Comment by radare** [comment]
inherting dupped bytes on invalid

<img width="677" alt="screen shot 2018-09-10 at 16 53 18" src="https://user-images.githubusercontent.com/917142/45305183-0d32a480-b51a-11e8-902e-949ff4b84f93.png">

**Comment by radare** [comment]
onelinered tests

```
$ r2 -qc'wx 60;pd 2' -
            0x00000000                 invalid
            0x00000001      0000       add byte [rax], al
$ r2 -qc'wx 906090;pd 3' -
            0x00000000      90         nop
            0x00000001      90         invalid
            0x00000002      90         nop
$
```

**Comment by radare** [comment]
the worst thing is that...
```
$ rasm2 -d 60
pushal
```

**Comment by kazarmy** [comment]
```
$ rasm2 -b 64 -d 60
invalid

$ rasm2 -b 32 -d 60
pushal

$ rasm2 -b 16 -d 60
pushaw
```

doesn't seem that there's much to worry about here except that Intel officially uses PUSHAD for 32-bit and PUSHA for 16-bit

**Comment by radare** [comment]
Yep missed that thats why i removed the comment. Anyway the problem seems related to my rstrbuf refactoring unifying binary buf with hex one

**Comment by kazarmy** [comment]
You mean this line? https://github.com/radare/radare2/commit/6d05365f30a76770dcd74cd6cce39621620f70b3#diff-7b45b46dd8a84a924b91f34c2b1e6309R2926

**Comment by radare** [comment]
Yes
