### ISSUE TITLE
Add hash in zignatures

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11431]
Add a hash of the bytes as a Zignature field see r2con @cmatthewbrooks talk

**Comment by xermicus** [comment]
I'm working on this one, so far I've got an MD5 hash of the fcn bytes:
```[0x00005ae0]> zaf
[0x00005ae0]> z
entry0:
  bytes: f30f1efa31ed4989d15e4889e24883e4f050544c............48............48............ff..........f4
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x00005ae0
  hash: e932e07eb237e3026699c31b0c3f2f5c
[0x00005ae0]> za entry0 h foo
[0x00005ae0]> z
entry0:
  bytes: f30f1efa31ed4989d15e4889e24883e4f050544c............48............48............ff..........f4
  graph: cc=1 nbbs=1 edges=0 ebbs=1
  offset: 0x00005ae0
  hash: acbd18db4cc2f85cedef654fccc4a4d8
```
I'm going to implement a hash of the strings used inside a function as well. Any other additional ideas?

**Comment by Maijin** [comment]
Yep, first makes sure you don't do a massive commit. If you already have the md5 you should already PR now.

You can also add the information missing indicated here - https://github.com/radare/radare2/issues/6947 for examples the arguments/locals that you can find under `afvn` or `afi`. The function size, call convention, etc. you can find under `afi`, the comments and the local flags.

Mattbrooks also shown the strings hash and the call chain hash, you can use `pdsf` and afi and other aX to get this information 👍

**Comment by xermicus** [comment]
Sure, I'll finish it (adapt help,and check CONTRIBUTING.md again etc.) and PR before adding more. Thx for the feedback! Will have look into 6947 and call chain hashes.

**Comment by cmatthewbrooks** [comment]
So string set and call chain hashes are a bit experimental. I'd let me get a little bit further with those before writing core code for them.

After the talk and similar-ish to the md5 approach, @thomasdullien pointed me to similar work (much further along and better suited to scale) hosted at https://github.com/googleprojectzero/functionsimsearch. I'm not sure if it should be a filed as a separate issue but it may be worth exploring either a plugin or core code changes to integrate that approach.

**Comment by thomasdullien** [comment]
Hey there,

I know essentially nothing about radare's codebase, but if I can be of help
integrating, I will gladly do so :)
The interface to functionsimsearch is pretty simple; the C++ code in the
python bindings (PySimHasher__calculate_hash)
demonstrates how it can be used.

Cheers,
Thomas

Am Do., 13. Sep. 2018 um 02:34 Uhr schrieb Matt Brooks <
notifications@github.com>:

**Comment by xermicus** [comment]
@Maijin good point. What about turning the hash field into a struct that can contain various different types of hashes (based on this data)?

**Comment by Maijin** [comment]
@xermicus make sense

**Comment by Maijin** [comment]
(please note my earlier comments was for adding variables/locals not as a hash but as content of the zignature)

**Comment by XVilka** [comment]
@sivaramaaa you might want to help with types and variables information in these.

**Comment by radare** [comment]
uhmf? wasnt this done already?

**Comment by XVilka** [comment]
No

**Comment by radare** [comment]
@Maijin says it is

**Comment by radare** [comment]
whats missing? because the PR was merged

**Comment by XVilka** [comment]
Ah, I thought you were asking about types in signatures.

**Comment by Maijin** [comment]
hash in zignature is done, let's close here.
