### ISSUE TITLE
visual flicker on input commandline or comment

### ISSUE THREAD

**Issue by rlaemmert** [radare/radare2#11430]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux x64
| File format of the file you reverse (mandatory)      | tested elf and PE
| Architecture/bits of the file (mandatory)            | 32/64 bit x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19804 @ linux-x86-64 git.2.9.0-19-g85d69039c
commit: 85d69039c6dc7508e2a41c89ee903abd170fb8ed build: 2018-09-07__09:04:56

### Expected behavior
Constant visual screen without any affects when i start typing in comment or commandline mode.

#### Comments
Starting to comment in visual with ; . When i start typing the command input field jumps to the bottom of the screen
#### Commandline
Starting with : . When i start typing visual flickers and the jump targets on visual dissappear.

### Steps to reproduce the behavior 
- Open binary
- Vp
- : or ; 
- start typing

### Additional Logs, screenshots, source-code,  configuration dump, ...
This behaviour seems to be related to resizing the window. It is introduced with this commit:
b0436220dcb14d4cfb59500972313305b826f784

**Comment by ret2libc** [comment]
I can reproduce.

**Comment by ret2libc** [comment]
CC @nsajko 

could you have a look?

**Comment by rlaemmert** [comment]
Fixed so ill close this
