### ISSUE TITLE
Android native build is broken

### ISSUE THREAD

**Issue by pavelkrcma** [radare/radare2#11442]
Android native build is broken because a lot of things in NDK was changed since API level 21.

## Quick fix
To make it work again with latest NDK just add this to sys/ndk-gcc:
<code>
CFLAGS="${CFLAGS} -I${PLATFORM_PATH}/include -I${PROGDIR}/sysroot/usr/include -I${PROGDIR}/sysroot/usr/include/${NDKPFX}"
</code>
and increase API level to 28 (latest), now non-logically in variable ANDROID_LOLIPOP

## Final solution
Currently, this problem is solved by so-called standalone toolchain (see https://developer.android.com/ndk/guides/standalone_toolchain). I would recommend switch from link to NDK to link to standalone toolchain generated by an user according real needs. It solves a lot of issues and makes most of scripts related to android obsolete.

**Comment by radare** [comment]
Can you provide the fix in a PR?

**Comment by pavelkrcma** [comment]
Done in branch  fix-androidbuild-11442
