### ISSUE TITLE
"?" does not work on commands without subcommands

### ISSUE THREAD

**Issue by 0ki** [radare/radare2#11459]
Since defining separate help outputs for every command will never™ happen, we should refactor help code to do the following:

Try to find help for abcdef? and display if possible.
If not, do something along the lines of abcde?~abcdef automatically.

**Comment by 0ki** [comment]
And if the last one doesn't display anything as well, probably it'd be nice to show an error. #11460

**Comment by cyanpencil** [comment]
There is already a command for this, `?*` lists all help, so you can do `?*~abcdef` to find help for abcdef, or even better `?*~...` for interactive search in the help

**Comment by radare** [comment]
Let us know if you find more commands that behave like this, or send a PR fixing them if you want.

Thanks

**Comment by radare** [comment]
Proper fixing of this issue depends on refactoring the whole way commands are parsed and there's an issue for that already

**Comment by 0ki** [comment]
Which issue is that?

**Comment by radare** [comment]
https://github.com/radare/radare2/issues/7967
