### ISSUE TITLE
Not able to exit input mode when ascii column is selected in visual hex mode

### ISSUE THREAD

**Issue by kbeckmann** [radare/radare2#11467]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux x86_64
| File format of the file you reverse (mandatory)      | Any file (affects hex editor)
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19415 @ linux-x86-64 git.2.9.0-47-g57024df5f commit: 57024df5f318ad3e1f4735cd6493f75c50ca1620 build: 2018-09-09__11:34:43

### Expected behavior
Should be able to exit the input mode when the ascii column is selected in visual hex edit mode.

### Actual behavior
Not able to exit input mode when ascii column is selected in visual hex mode

### Steps to reproduce the behavior 
r2 -
V
c
i
`<tab>`
`<esc><esc>`

Now we should leave insert mode but it doesn't work. Need to press `<tab>` to select hex column and then press `<esc><esc>` or `q`.

I looked in the source and tried to fix it but couldn't find a simple fix. Got stuck in the translation function in input.c:108 where `<esc>` is translated into the `q` character, but since we're in the ascii column this becomes a problem.

Also sorry if this is a duplicate, I searched but couldn't find it reported already.

**Comment by radare** [comment]
Yep thats expected because the way to quit is using the q key and in ascii mode its inserted as a valid char

**Comment by kbeckmann** [comment]
Alright, thanks for looking into it!
