### ISSUE TITLE
We need a way to customize content of panels permanently

### ISSUE THREAD

**Issue by 0ki** [radare/radare2#11461]
It is currently possible to customize panels in radare: V! and then press e in a panel.
However this is reset every time panel mode is launched. 
We need a way to change this permanently and per-session.

Having variables for this would solve both problems. Something like:
panel1.name
panel1.cmd
panel2.name
panel2.cmd
panel3.name
panel3.cmd
...

For example `e panel1.cmd=px 40 @rdx`

**Comment by radare** [comment]
NOTHING IS PERMANENT

**Comment by XVilka** [comment]
Except death.

**Comment by Vane11ope** [comment]
this has been done already.

**Comment by 0ki** [comment]
Some info / documentation?
