### ISSUE TITLE
Radare states no canary when there is.

### ISSUE THREAD

**Issue by m0rv4i** [radare/radare2#11477]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux 4.17.0-kali3-amd64 #1 SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19531 @ linux-x86-64 git.2.9.0-49-g8dd9045ea commit: 8dd9045eafd68de273ccea3e10fec2a87956d690 build: 2018-09-10__10:15:49

### Expected behavior

If a binary has a stack protector then the **canary** flag is set to **true**.

### Actual behaviour

The attached binary has a stack protector but the **canary** flag is set to **false**.

### Steps to reproduce the behavior 
* Open the attached binary in radare with analysis `r2 -AAA binary`
* Run `i` to view the file information:
```
[0x00400f9e]> i
blksz    0x0
block    0x100
fd       3
file     binary
format   elf64
iorw     false
mode     r-x
size     0xdd7c7
humansz  885.9K
type     EXEC (Executable file)
arch     x86
baddr    0x400000
binsz    907207
bintype  elf
bits     64
canary   false
class    ELF64
crypto   false
endian   little
havecode true
lang     c
linenum  true
lsyms    true
machine  AMD x86-64 architecture
maxopsz  16
minopsz  1
nx       true
os       linux
pcalign  0
pic      false
relocs   true
rpath    NONE
static   true
stripped false
subsys   linux
va       true
```
* Seek to a function, e.g. `s main`
* `pdf` to view the function and observe the presence of a stack protector.
```
...snip...
|  ||`--`=< 0x0040179f      e91dfdffff     jmp 0x4014c1
|  ||       ; CODE XREF from main (0x401760)
|  `------> 0x004017a4      e857ce0300     call sym.__stack_chk_fail   ; void __stack_chk_fail(void)
|   |       ; CODE XREF from main (0x40175e)
|   `-----> 0x004017a9      488b5df8       mov rbx, qword [local_8h]
|           0x004017ad      c9             leave
\           0x004017ae      c3             ret
[0x004013fa]>
```
### Additional Logs, screenshots, source-code,  configuration dump, ...

Binary: 
[binary.zip](https://github.com/radare/radare2/files/2366812/binary.zip)

**Comment by radare** [comment]
do checksec.sh finds it?

**Comment by m0rv4i** [comment]
Yeah:

```
./checksec -f ./binary
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      Symbols         FORTIFY Fortified       Fortifiable  FILE
Partial RELRO   Canary found      NX enabled    No PIE          No RPATH   No RUNPATH   2114 Symbols    Yes     2               46      /root/binary

```

**Comment by Maijin** [comment]
For info the code is here - https://github.com/radare/radare2/blob/master/libr/bin/p/bin_elf.inc#L1030

**Comment by Maijin** [comment]
Yes ok there is no imported listed in the binary thus this code doesn't find the canary, maybe the check should be done on the symbols rather than the imports

**Comment by Maijin** [comment]
and the import fixed to be displayed anyhow

**Comment by ret2libc** [comment]
> and the import fixed to be displayed anyhow

@Maijin there is no import list because the binary is statically linked. So yes, I do think the check should be done on the symbol list instead of the import one.

**Comment by Maijin** [comment]
yes my bad, too fast ;), so yeah my patch should do the trick then 👍

**Comment by radare** [comment]
see my comment in the other issue

**Comment by Maijin** [comment]
I tried on this bin which have like 3k symbols, it's negligeable when you open:

```
 maijin@Slash  ~/Documents/Projects/radare2   check_canary_w_symbols  time r2 -qc "" /Users/maijin/Downloads/binary
Warning: Cannot initialize dynamic strings
r2 -qc "" /Users/maijin/Downloads/binary  0.11s user 0.02s system 95% cpu 0.138 total
 maijin@Slash  ~/Documents/Projects/radare2   check_canary_w_symbols 
```

This is something that should be fixed with sdbization i think

**Comment by ret2libc** [comment]
> This is something that should be fixed with sdbization i think

How? How sdb would solve this? :/

**Comment by Maijin** [comment]
@ret2libc aren't they method for sdb for checking if an element is in the list?

**Comment by radare** [comment]
yes, but we didnt sdbized rbin yet, n fact the event model approach by condret would also work, but none of those things are in master

**Comment by m0rv4i** [comment]
Awesome, thanks all, confirmed fixed!
Two bugs in two days and two immediate fixes, I love this project 😄 
I had opened it up to have a look but I'm pretty slow at C, will get up to speed though as would love to contribute.
