### ISSUE TITLE
r2 keeps asking for glibc path after changing interpreter and rpath using patchelf.

### ISSUE THREAD

**Issue by Zzorz** [radare/radare2#11471]
I changed the interpreter and rpath by using patchelf:
```
        linux-vdso.so.1 (0x00007ffc1c368000)
	libc.so.6 => /glibcs/libc-2.27/lib/libc.so.6 (0x00007fe90ff27000)
	/glibcs/libc-2.27/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe9104e2000)
```
Hoping to run program with my custom ld and libc(with debug symbol), but  find strange behavior that r2 keeps asking me for glibc path like this:
```
         "Is a custom library? (LD_PRELOAD=..) Enter full path glibc: "
```
And this appears everytime when I get into heap status using `dmh` or `dmht`.
Is there any solution?

**Comment by morbith-dqtz** [comment]
Since commit 1ee0b587091ca68993f0b56bd28a020220bff21e, you can set a debug file via 

e dbg.libc.dbglib = /path/to/yourfile

When you set this config it will not ask you again
