### ISSUE TITLE
Shared plugins can't be loaded on Windows

### ISSUE THREAD

**Issue by pelijah** [radare/radare2#11487]
Shared plugins can't be loaded on Windows because plugin DLL doesn't export `radare_plugin` sym.

Now (doesn't work): `RLibStruct radare_plugin = {`
Should be: `RLibStruct __declspec(dllexport) radare_plugin = {`

**Comment by radare** [comment]
is `R_API RLibStruct radare_plugin = {} ` working as expected?

**Comment by radare** [comment]
if so the fix is easy, wanna send a PR?
