### ISSUE TITLE
Wrong decoding for x86 instruction cmp r/m32, imm8

### ISSUE THREAD

**Issue by elicn** [radare/radare2#11496]
It looks like the immediate value that appears in a certain `cmp` variant, opcode 83h, is wrong. This opcode is used to compare a register or a memory location to an 8-bits immediate value. For some reason, the value gets sign-extended to 64 bits.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | PE (DLL)
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19678 @ linux-x86-64 git.2.9.0-64-g08f8e48ca commit: 08f8e48ca10829ffdb6fa340c0e805cd8e76d242 build: 2018-09-12__16:16:56

### Expected behavior
Immediate values specified in the `cmp` instruction whose opcode is 83h, are 8 bits values. For example, the sequence `83 f8 80` should be decoded to `cmp eax, 0x80`.
### Actual behavior
Immediate values are sign-extended to 64 bits, even though it is a 32 bits file. In the aforementioned example, the observed output is `cmp eax, 0xffffffffffffff80`. The problem is easily noticeable if the last byte of the sequence (i.e. the immediate 8-bits value) is changed to 70h, where the MSB is cleared.

### Steps to reproduce the behavior 
`rasm2 -a x86 -b 32 -d "83 f8 80"`

**Comment by radare** [comment]
Blame capstone, not r2. We dont decode instructions.

**Comment by Maijin** [comment]
Can you open an issue here https://github.com/aquynh/capstone/issues/new ?
