### ISSUE TITLE
afta to silent seek instead of creating history

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11505]
afta to use silent seek instead of creating history see
- r2 -qc "aa ; afta ; sj~{}" /bin/ls

**Comment by radare** [comment]
i dont think its afta fault at all

**Comment by radare** [comment]
its just 'aa' the one introducing new seeks. we should just reset the seek history before entering the shell loop

**Comment by Maijin** [comment]
try aa then check seek, then try afta and check seek, you'll see tons of new entries after afta

**Comment by radare** [comment]
Before and after aa theres seek history changes too

**Comment by Maijin** [comment]
Yes

**Comment by ret2libc** [comment]
3.2 for this too?

**Comment by radare** [comment]
Nope. Its easy to fix and the sivaramaa is assigned

**Comment by Maijin** [comment]
Still there

**Comment by radare** [comment]
pls  @sivaramaaa
