### ISSUE TITLE
Missing cjmp bb in predecessor at 0x1006aa416

### ISSUE THREAD

**Issue by EvanCarroll** [radare/radare2#11511]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x86_64
| File format of the file you reverse (mandatory)      | PE64
| Architecture/bits of the file (mandatory)            | x86/64 
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19458 @ linux-x86-64 git.2.7.0-708-g35bd0fbf0
commit: 35bd0fbf06862526e50914608ceab9c440c726bc build: 2018-09-12__22:53:20

### Expected behavior

No messages.

### Actual behavior

> Missing cjmp bb in predecessor at 0x1006aa416

### Steps to reproduce the behavior 

1. Open dll in [dll.zip](https://github.com/radare/radare2/files/2379612/dll.zip)
2. run `aaa`

**Comment by Maijin** [comment]
Thanks for reporting but this is a warning, not an error it is caused by the analysis of jump tables in your binary.
