### ISSUE TITLE
Reading from stdin not working

### ISSUE THREAD

**Issue by pyllyukko** [radare/radare2#11566]
Radare2 should read stuff from stdin with the ```=``` parameter. Reading doesn't seem to work at least when looking at the hexdump output.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Slackware x86 64
| File format of the file you reverse      | Text
| r2 -v full output     | radare2 3.0.0-git 19678 @ linux-x86-64 git.2.9.0-142-g8128571c8 commit: 8128571c80ba06277b9f7d4e0b1522225894962d build: 2018-09-17__19:05:48

### Expected behavior

```
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  4845 4c4c 4f0a ffff ffff ffff ffff ffff  HELLO...........
```

### Actual behavior

```
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  ffff ffff ffff ffff ffff ffff ffff ffff  ................
```

### Steps to reproduce the behavior 

```bash
echo HELLO | r2 -c 'x' =
```

**Comment by radare** [comment]
for me it takes 100% cpu usage, so it doesnt read from stdin at all
