### ISSUE TITLE
ARM, missing main substitution in disassembly

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11585]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Arm32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior
```
...
ldr r0, main
```

### Actual behavior

```
...
ldr r0, [0x000083ec]
```

### Steps to reproduce the behavior 

See test - https://github.com/radare/radare2-regressions/commit/cc3c914f09c44d758f026ba18e628e9ced8b8b3a

basically:
aaa
pdf @ entry0

**Comment by radare** [comment]
Maybe aav.addrofhit.flagnameitpointsto

**Comment by radare** [comment]
what about adding a prefix to this `main` ? because its the exception, together with the entry0* maybe we can use `entry.main` and then have `entry.init` `entry.fini` and `entry.point`

**Comment by radare** [comment]
wanna have a look at this @alvarofe ?

**Comment by alvarofe** [comment]
```
ldr r0, [0x000083ec]        ; [0x83ec:4]=0x8470 main ; func main
```
relsub should pick this up to perform the substitution iirc

**Comment by radare** [comment]
can you try again?

**Comment by radare** [comment]
also try with emu.str=1

**Comment by radare** [comment]
fixed in a pr
