### ISSUE TITLE
Cannot examine the 32-bit binary's heap on 64-bit linux (amd64)

### ISSUE THREAD

**Issue by conghiaa** [radare/radare2#11589]
# It works fine with 64bit binary but when working with 32bit it always shows an error and sometimes crashing
`[0x08048a3b]> dmh
Warning: glibc library with symbol main_arena could not be found. Is libc6-dbg installed?

[0x08048a3b]> dmha
Warning: glibc library with symbol main_arena could not be found. Is libc6-dbg installed?
`
Of course, I have installed libc6-dbg.

**Comment by morbith-dqtz** [comment]
libc6-dbg doesn't include x86 dbg libraries in a x86_64 (debian/ubuntu), you should install libc6-dbg-i386-cross and then reference the debug library with

e dbg.libc.dbglib = /usr/i686-linux-gnu/lib/debug/lib/i386-linux-gnu/libc-2.27.so

you also probably need to adjust main_arena offset and first chunk offset

e dbg.glibc.ma_offset = 0x1d2000

**Comment by conghiaa** [comment]
> libc6-dbg doesn't include x86 dbg libraries in a x86_64 (debian/ubuntu), you should install libc6-dbg-i386-cross and then reference the debug library with
> 
> e dbg.libc.dbglib = /usr/i686-linux-gnu/lib/debug/lib/i386-linux-gnu/libc-2.27.so
> 
> you also probably need to adjust main_arena offset and first chunk offset
> 
> e dbg.glibc.ma_offset = 0x1d2000

Where did you get 0x1d2000? .Another issue is that I've been using ubuntu 16.04  so it uses libc-2.23 and there's no libc6-dbg-i386-cross package available =)) I installed a version which is for 18.04 so is it okay to having the mismatched gdb libc(libc-dbg-2.27) installed?

**Comment by conghiaa** [comment]
I've found a way to fix it. Just install libc6-dbg:i386 and everything works fine. Thanks you

**Comment by radare** [comment]
May be worth documenting this in the book or make r2 spit more helpful messages when this happens.
