### ISSUE TITLE
drj command returns negative values

### ISSUE THREAD

**Issue by Wenzel** [radare/radare2#11637]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | n/a
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19759 @ linux-x86-64 git.2.9.0-194-ga36534b9f commit: a36534b9f380905bd6d561bea4c552b3937ed117 build: 2018-09-24__13:29:53

### Expected behavior

`drj ` command should return positive values

### Actual behavior
`drj` command returns negative values for some registers in some case:
![drj-r2](https://user-images.githubusercontent.com/964610/45953386-9239b580-c012-11e8-8caf-c2426146435a.png)

Using this in Python leads to invalid values:

Example for the `r8` register here:
![drj](https://user-images.githubusercontent.com/964610/45953408-a54c8580-c012-11e8-9e5d-b2197b262ec1.png)

### Steps to reproduce the behavior
I only faced this problem while working on my plugin.
I don't know how to reproduce it on a standard binary.

I don't think it's an implementation issue in my plugin, since `dr` output is valid.

Thanks.

**Comment by Wenzel** [comment]
Just the register to a too big value to trigger the bug:

script.r2
~~~
dr rax=0xfffffa8004cc6b30
drj
~~~

`r2 -i script.r2 -d /bin/ls`
~~~
Process with PID 26778 started...
= attach 26778 26778
bin.baddr 0x557c668c9000
Using 0x557c668c9000
asm.bits 64
0x00000000 ->0xfffffa8004cc6b30
{"rax":-6047233447120,"rbx":0,"rcx":0,"rdx":0,"r8":0,"r9":0,"r10":0,"r11":0,"r12":0,"r13":0,"r14":0,"r15":0,"rsi":0,"rdi":0,"rsp":140734326383200,"rbp":0,"rip":139793504882832,"rflags":512,"orax":59}
~~~

**Comment by radare** [comment]
Fixing it is easier than reporting it. Pls send a pr
