### ISSUE TITLE
Bug when analyzing access information about registers

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [radare/radare2#11649]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Max OS
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19896 @ darwin-x86-64 git.2.9.0-200-g17f2f3abf commit: 17f2f3abf1fed2f2966a17a19f24c85ce95ae2d9 build: 2018-09-25__12:45:28

### Expected behavior

```bash
> s 0x00400aa0
> pd 1
    0x00400aa0      b8bf406000     mov eax, 0x6040bf
> aear # should be no result
```

### Actual behavior

```bash
> s 0x00400aa0
> pd 1
    0x00400aa0      b8bf406000     mov eax, 0x6040bf
> aear # generate wrong results
    rax
```

### Steps to reproduce the behavior 
- Simply type `r2 mcf_strip` 
- Following the steps I mentioned in behavior. 

### Additional Logs, screenshots, source-code,  configuration dump, ...

The bug caused by ESIL, IMO. For ESIL, `mov eax, 0x6040bf` will be translated into `6308031,eax,=,0xffffffff,rax,&=`, which indicates the instruction has read the data from `rax`. But actually the high bits of `rax` are cleared by CPU, without any reading actions. I am not so sure how ESIL is generated, but `0x0,rax,=,6308031,eax,=` might be a better solution.

The binary is attached. Actually, I think there is no need for a specific binary. I guess all these instruction should have this problems.

[mcf_strip.zip](https://github.com/radare/radare2/files/2416231/mcf_strip.zip)

**Comment by Maijin** [comment]
This request is coming from radeco.

**Comment by radare** [comment]
cant reproduce
