### ISSUE TITLE
Wrong r2 emulate ARM

### ISSUE THREAD

**Issue by GH0st3rs** [radare/radare2#11648]
I compiled source code from this [Article](http://www.mien.in/2018/08/15/emulating-decryption-function-with-radare2/) to arm x32 architecture

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | docker radare/radare2
| File format of the file you reverse (mandatory)      | ELF.
| Architecture/bits of the file (mandatory)            | arm 32 le.
| $ r2 -v                                                           | radare2 3.0.0-git 1 @ linux-x86-64 git.3.0.0-git
commit: 17f2f3abf1fed2f2966a17a19f24c85ce95ae2d9 build: 2018-09-25__11:36:56
### Steps to reproduce the behavior 
$ r2 ./decode
```
[0x00008110]> e asm.emu=true
[0x00008110]> ar0
[0x00008110]> s sym.is_valid
[0x00008218]> aei
[0x00008218]> aeim
[0x00008218]> aeip
[0x00008218]> w oSekma @ sp
[0x00008218]> aer r0=sp
[0x00008218]> aes; aer ; pxW 50 @ sp ; pd 10 @ pc
```
- Next I trace the program use next command: `aes; aer ; pxW 50 @ sp ; pd 10 @ pc`
- Look at the next souce:
```
            0x00008244      0030a0e3       mov r3, 0                   ; r3=0x0
            0x00008248      24300be5       str r3, [fp, -0x24]         ; sym.__libc_tsd_CTYPE_TOLOWER
            0x0000824c      24301be5       ldr r3, [fp, -0x24]         ; sym.__libc_tsd_CTYPE_TOLOWER ; r3=0x0
            0x00008250      050053e3       cmp r3, 5                   ; 5 ; zf=0x0
        ,=< 0x00008254      1d0000ca       bgt 0x82d0                  ; pc=0x82d0 -> 0xe55b301d ; likely
```
 - Then I trace to position `0x00008250` I have the next station:
```
sb = 0x00000000
sl = 0x00000000
fp = 0x00177ffc
ip = 0x00178000
sp = 0x00177fd8
lr = 0x00000000
pc = 0x00008250
r0 = 0x00178000
r1 = 0x00000000
r2 = 0x00000000
r3 = 0x00000000
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00177ffc
r12 = 0x00178000
r13 = 0x00177fd8
r14 = 0x00000000
r15 = 0x00008250
cpsr = 0x00000000
blank = 0x00000000
```
As you can see `R3 = 0`. But radare2 on next instruction `0x00008254      1d0000ca       bgt 0x82d0` make jump to `0x82d0` anyway. Its wrong because 0<5

### Additional Logs, screenshots, source-code,  configuration dump, ...
Archive contains screenshots, source-code and compiled binary file
[decode.zip](https://github.com/radare/radare2/files/2415922/decode.zip)

**Comment by GH0st3rs** [comment]
### Expected behavior
`CMP r3, 5` must change `zf, nf, vf` registers, but these registers remain unchanged

**Comment by XVilka** [comment]
Please craft a regression test in https://github.com/radare/radare2-regressions

**Comment by radare** [comment]
Can you update the esil expression for the cmp or bgt instruction? Esil have internal state vars. So its possible to have them without updating those vars implicitly

**Comment by GH0st3rs** [comment]
[ESIL for arm x32 CMP](https://github.com/radare/radare2/blob/17f2f3abf1fed2f2966a17a19f24c85ce95ae2d9/libr/anal/p/anal_arm_cs.c#L1590-L1592) is deffer them [ESIL for arm 64 CMP](https://github.com/radare/radare2/blob/17f2f3abf1fed2f2966a17a19f24c85ce95ae2d9/libr/anal/p/anal_arm_cs.c#L1135) and I fix it:
```
case ARM_INS_CMP:
        r_strbuf_appendf (&op->esil, "%s,%s,-,$z,zf,=,$s,nf,=,$b16,cf,=,$o,vf,=", ARG(1), ARG(0));
        break;
```

> $b16 - Cause I didn't found analog for function arm64_reg_width()

**Comment by XVilka** [comment]
Please send a pull request.

**Comment by Maijin** [comment]
The fix proposed is messing up with 4 tests and I'm not familiar enough with ARM to determine what's going on, @mrmacete maybe?

**Comment by mrmacete** [comment]
nice, at a first sight the fix seems correct. but according to the tests indeed it's setting the N and S flags also when it shouldn't. have to dig more on this.

**Comment by radare** [comment]
Why cmp is using substraction? We have == and we should use $ prefixed numbers to avoid flags to be updated by accident

**Comment by GH0st3rs** [comment]
> Why cmp is using substraction? We have == and we should use $ prefixed numbers to avoid flags to be updated by accident
Because [CMP-INSN](http://sourceware.org/cgen/gen-doc/arm-thumb-insn.html#insn-cmp) I think it's correctly
