### ISSUE TITLE
axj != axtj

### ISSUE THREAD

**Issue by radare** [radare/radare2#11667]
Output is different

<img width="663" alt="screen shot 2018-09-26 at 10 42 26" src="https://user-images.githubusercontent.com/917142/46098311-f5455c80-c178-11e8-8a12-ed3146bf12ba.png">

**Comment by kazarmy** [comment]
> Output is different

@radare So you want `opcode`, `fcn_addr` and `fcn_name` in axj?

**Comment by radare** [comment]
the disasm should be filtered to show flagnames and such imho
