### ISSUE TITLE
Memory Leak in rabin2 path variable

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#11687]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19571 @ linux-x86-64 git.2.9.0-235-g354a40836 commit: 354a40836aa12df0ed3fb3ffa90e800e6dd49294 build: 2018-09-28__20:26:49

### Expected behavior
No memory leak

### Actual behavior
Memory leak

### Steps to reproduce the behavior 
Simply running rabin2 encounters a memory leak. Specifically, line 577 in `/binr/rabin2/rabin2.c`.

```c
path = r_sys_getenv (R_LIB_ENV);
```

That path variable is malloc'd but never free'd.

**Comment by radare** [comment]
can you send a PR fixing this? its easier than reporting

**Comment by bannsec** [comment]
Yep, it's under PR #11688. Was using this for tracking purposes.
