### ISSUE TITLE
Perhaps r_bin_wr_scn_resize should also resize underlying segment?

### ISSUE THREAD

**Issue by wdworks** [radare/radare2#11708]
Hello!
Maybe i'm missing the point here, but `r_bin_wr_scn_resize` and as a result `rabin2 -O r` only resizes the section and not the underlying segment as a result changes won't be mapped unless program header manually changed.
Am i missing the point it's intended to be used for or my logic is flawed somewhere? Thanks in advance for the great work supporting the r2!

**Comment by radare** [comment]
Thats up to the file format but probably yes to ease its usage

**Comment by wdworks** [comment]
Yeah, right, this is ELF specific. Haven't thought about it right away.
Btw i think it was in mind initially because i can see `bool is_segment` in
`RBinSection` But never referenced in libr.
Also as far as i can tell there is no R_API to resize RBinMap right?
I'm willing to try commit on this one myself.

**Comment by radare** [comment]
Nope thrres no such thing
