### ISSUE TITLE
dmh* commands (e.g. dmh, dmhm) don't respect eco (theme) settings

### ISSUE THREAD

**Issue by mkopec3** [radare/radare2#11701]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19670 @ linux-x86-64 git.2.9.0-245-g883abe417 commit: 883abe417f48e4f1803ecd2238418d45f061b3dd build: 2018-09-30__17:23:10

### Expected behavior

dmh, dmha, dmhb, dmhbg, dmhc, dmhf, dmhg, dmhi, dmhm, dmht family of commands should produce theme colorized output (according to the current eco setting)

### Actual behavior

The above commands always produce colorized output using the same color palette (orange, blue, green, red), whatever the eco setting is

### Steps to reproduce the behavior 
- e scr.color = 2
- eco twilight
- run one from the above dmh* commands during debug run: r2 -d ./some_binary (step through some heap related functions calls e.g malloc() beforehand, to make dmh* command produce some reasonable output)

### Additional Logs, screenshots, source-code,  configuration dump, ...

![dmh_eco](https://user-images.githubusercontent.com/25580985/46259366-c1e83200-c4d8-11e8-9845-4bf5b29d4a14.png)

**Comment by Vane11ope** [comment]
im taking this (saying this just to avoid dup work

**Comment by mkopec3** [comment]
I'm working on a patch now

**Comment by mkopec3** [comment]
PR is ready #12960
