### ISSUE TITLE
In vertical split PageDown doesn't work

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#11714]
If you open a file `r2 /bin/ls` then go to the visual hex mode with `VP`, then press `|` to do a vertical split and type `px` for `cmd.cprompt`, you press "PageUp" a couple times, it scrolls up successfully, but with "PageDown" button nothing happens.

**Comment by wdworks** [comment]
Somehow can't reproduce this one

**Comment by radare** [comment]
i can reproduce
