### ISSUE TITLE
doc/fortunes.tips - improper entry

### ISSUE THREAD

**Issue by mkopec3** [radare/radare2#11736]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | N/A
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19724 @ linux-x86-64 git.2.9.0-278-g831c23641
commit: 831c23641672ab767f6da2ac578e76a735a9028c build: 2018-10-04__21:18:06

### Expected behavior

doc/fortunes.tips file will contain valuable tips only (no. joking stuff)

### Actual behavior

_doc/fortunes.tips_ contains the below entry: 
**For a full list of commands see `strings /dev/urandom`**
which should belong to _doc/fortunes.fun_ only

### Steps to reproduce the behavior 

user@host:/usr/local/src/radare2$ grep urandom doc/fortunes.tips

**Comment by radare** [comment]
Just press the pencil button and make a pullreq instead of an issue
