### ISSUE TITLE
Bad JSON generated by r2 crashes r2dec

### ISSUE THREAD

**Issue by rfc2119** [radare/radare2#11739]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Debian Stretch x86-32
| File format of the file you reverse      | ELF
| Architecture/bits of the file| x86/32
| r2 -v full output | radare2 3.0.0-git 19600 @ linux-x86-32 git.2.9.0-271-g237e6c294 commit: 237e6c2947599c90a1dc76b986044e642d270386 build: 2018-10-03__21:47:18

### Actual behavior
Analyzing any function then issuing `pdd` crashes r2dec. This is probably a regression [`asciinema`](https://asciinema.org/a/ooyFPcrHPmQel8WNONMg9Jrcg)
Here's /bin/ls for convinence: [ls.zip](https://github.com/radare/radare2/files/2449216/ls.zip)

**Comment by Maijin** [comment]
This must be opened on r2dec repository - https://github.com/wargio/r2dec-js/issues

**Comment by wargio** [comment]
afvj is broken on r2. so it is not a r2dec bug. @Maijin @radare this is the bug.
