### ISSUE TITLE
Fix PE files call to sym.imp if aan is disabled

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11759]
In many PE the `aan` is absolute necessity to be able to analyze but it shouldn't be that way if the mechanism of propagating `sym.imp.xxx` would be working correctly.

`aaa` with `aan` (`e anal.autoname=true`):
![image](https://user-images.githubusercontent.com/1408600/46582690-53aced80-ca4b-11e8-97c7-58c630af564b.png)

`aaa` without `aan` (`e anal.autoname=false`):
![image](https://user-images.githubusercontent.com/1408600/46582689-4859c200-ca4b-11e8-994d-f4f47a3742e4.png)

But following the first call of this function the function is clearly identified:
![image](https://user-images.githubusercontent.com/1408600/46582691-5b6c9200-ca4b-11e8-83f1-39c62a947b58.png)

The expected is to have the output without `aan` required:

`call sub.kernel32.dll_FindResourceA` for example

See example below:
[f15985a91b12e015812f7f960eb0abe03d0cd401f54d0088f75cb087776a297c.zip](https://github.com/radare/radare2/files/2453964/f15985a91b12e015812f7f960eb0abe03d0cd401f54d0088f75cb087776a297c.zip) (password: "infected")

Other tools for comparison:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1408600/52788565-f4638780-3093-11e9-9a34-477e038c2cdc.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/1408600/52788613-13621980-3094-11e9-8bf7-4449fb0fff7e.png">

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1408600/52788692-4efce380-3094-11e9-8012-355a952a80d3.png">

**Comment by Maijin** [comment]
@sanguinawer maybe an idea for fixing this?

**Comment by kazarmy** [comment]
Sorry, only realized that @pelijah was working on this only after I've finished my pr.

**Comment by ITAYC0HEN** [comment]
yay :)
