### ISSUE TITLE
Implement c output format for all t commands

### ISSUE THREAD

**Issue by radare** [radare/radare2#11756]
So we can tc > foo.h and then to foo.h

See my previous commits in tu, ts, te.. to handle json

* [x] ttc
* [x] tec
* [x] tsc
* [x] tuc

**Comment by radare** [comment]
Cc @sivar

**Comment by radare** [comment]
Cc @sivaramaaa

**Comment by ret2libc** [comment]
@radare 3.2 for this?

**Comment by radare** [comment]
I would love to have tsc before the release (sunday) can you @a-meth implement it in time?

thanks!

**Comment by radare** [comment]
@ret2libc 3.1 is totally fine. tuc is a copypasta of tsc just changing the type name. the only  issue i can imagine is recursive struct definitions, but printing a struct shouldnt recurse at all

**Comment by radare** [comment]
No pr yet so moving to 3.2

**Comment by Maijin** [comment]
Reopening as it is missing `tc` and the help for `tsc` and `tuc`

**Comment by radare** [comment]
Which command to use to list callcint cnventions? Do we have any dupped? @sivaramaa

**Comment by Maijin** [comment]
@sivaramaaa *

**Comment by radare** [comment]
too late, i have already checked the code and replied and merged
