### ISSUE TITLE
Compilation destroys changes to files outside of radare2 source directories

### ISSUE THREAD

**Issue by sbingner** [radare/radare2#11750]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX targeting iphone arm64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | N/A

### Expected behavior
Compile the tarball release of 2.7.0 available from http://radare.mikelloc.com/get/2.7.0/radare2-2.7.0.tar.gz without it wiping out changes in all other files in a git repository that this build happens to sit inside of.

### Actual behavior
Compiling causes all changes in the parent git repo (there is no git repo existant because it is from the tarball) to be completely wiped.  If my backups had not been working properly a large amount of code would have been lost.  Granted I should commit to git more often, but you should also not clobber my changes just because you don't have your own git repo available.

### Steps to reproduce the behavior 
- Create a git repo, commit some files, and make some changes without committing them
- Compile the tarball in any subdirectory of that git repo

**Comment by radare** [comment]
Why 2.7? is this issue reproducible in 2.9 or in git?

**Comment by radare** [comment]
is this also a problem with the tarballs from the github release page?

**Comment by radare** [comment]
i can reproduce

**Comment by radare** [comment]
```
wget -c  http://radare.mikelloc.com/get/2.7.0/radare2-2.7.0.tar.gz
tar xzf radare2-2.7.0.tar.gz
rm -rf gitrepo
mkdir gitrepo
cd gitrepo
git init
:> README.md
git add README.md
git commit -a -m "initial commit"
echo Something >> README.md
mv ../radare2-2.7.0 .
cd radare2-2.7.0
echo "Building in background ... "
./configure > /dev/null
make > log.txt &
while : ; do
	if [ -z "`git diff`" ]; then
		echo "BUG REPRODUCED see log.txt"
		pkill make
	fi
	sleep 1
done
```

**Comment by radare** [comment]
Sorry for the bug :( You may want to apply this patch on top of the tarball or wait for the next week release
