### ISSUE TITLE
Call to unsafe "system"

### ISSUE THREAD

**Issue by zadlg** [radare/radare2#11783]
https://github.com/radare/radare2/blob/d856b609a50262b29a3647acf5d8afcf2480c728/libr/util/sandbox.c#L152

`system` is unsafe, it's better to use `execve` (syscall)

**Comment by radare** [comment]
why system(x) is less secure than exec("sh -c", x) ?

**Comment by xarkes** [comment]
I think he didn't mean to use `exec("sh -c", x)` but `exec(x)`.
Otherwise as you stated, it doesn't make much sense.

**Comment by zadlg** [comment]
system is insecure because it just does a fork and a sleep, moreover it relies on PATH.
