### ISSUE TITLE
Arena Leak

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#11789]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | Core
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19738 @ linux-x86-64 git.2.9.0-333-gd07bcf61f commit: d07bcf61f7e5a7daecdac377207c376a96cf15ea build: 2018-10-10__21:36:42

### Expected behavior
No leak

### Actual behavior
Mem leak

### Steps to reproduce the behavior 
- `r2 core`
- `exit`

### Additional Logs, screenshots, source-code,  configuration dump, ...
```==4577==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 168 byte(s) in 1 object(s) allocated from:
    #0 0x55eb53cbaa58 in calloc (/home/angr/opt/radare2/binr/radare2/radare2+0xe6a58)
    #1 0x7fb8151bf132 in r_reg_arena_new /home/angr/opt/radare2/libr/reg/arena.c:169:24
    #2 0x7fb8151bf5e0 in r_reg_arena_push /home/angr/opt/radare2/libr/reg/arena.c:228:18
    #3 0x7fb8151c61f3 in r_reg_set_profile_string /home/angr/opt/radare2/libr/reg/profile.c:220:2
    #4 0x7fb815acfe79 in r_anal_set_reg_profile /home/angr/opt/radare2/libr/anal/anal.c:202:4
    #5 0x7fb815acfcfd in r_anal_use /home/angr/opt/radare2/libr/anal/anal.c:178:5
    #6 0x7fb818000239 in r_core_init /home/angr/opt/radare2/libr/core/core.c:2368:2
    #7 0x55eb53cf2ef5 in main /home/angr/opt/radare2/binr/radare2/radare2.c:533:2
    #8 0x7fb810ce5b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
```

Tried to track it down, but it's not clear to me where the correct place to free this memory would actually be.
[core.zip](https://github.com/radare/radare2/files/2466602/core.zip)

**Comment by radare** [comment]
i can reproduce

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/11825
