### ISSUE TITLE
This core file freezes r2

### ISSUE THREAD

**Issue by mkopec3** [radare/radare2#11785]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali Rolling arm 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19673 @ linux-x86-64 git.2.9.0-331-gc7a9ab9d7 commit: c7a9ab9d74576b5b1cc4c307e551a523ab0c9c70 build: 2018-10-10__20:47:34

### Expected behavior

No freeze. If core file is malformed, then throw an error/exception

### Actual behavior

r2 freezes after loading this particular core file

### Steps to reproduce the behavior 

0) unzip core
$ unzip core.zip

1) run r2, by selecting any file
$ r2 /bin/ls

2) load the attached core file from r2 cli
oc ./core 

r2 should hang after that...

### Additional Logs, screenshots, source-code,  configuration dump, ...

[core.zip](https://github.com/radare/radare2/files/2466181/core.zip)

**Comment by radare** [comment]
oc is not the command you are looking for, the help message is misleading.

you should be able to just do `r2 core`. this works fine. the hang i sbeause of having multiple core instances and the new changes in the thread management.

thanks for spotting it
