### ISSUE TITLE
Use radare2 to analysis ARM binaries

### ISSUE THREAD

**Issue by valour01** [radare/radare2#11806]
I am new to radare2 and seems it is a great framework to analysis the arm binaries. 
I have already installed the newest version of radare2 but I don't know where to start.
I have the following requirement. Given a ARM binary, 
I hope to get the 
- instruction boundary(all the instruction's address and its mode)`
- function boundary(function start address)
- function signature(parameters and return values)
- control flow graph 
- call graph.

I am not sure whether radare2 support all of these feature. If so, any suggestions on where to start? Many Thanks.

**Comment by Maijin** [comment]
Greetings @valour01,

You can find the various information you are looking for in all the documentation available such as and radare2

* The radare2book https://radare.gitbooks.io/radare2book/content/
* The internal doc with ?
* The youtube videos and documentation that can be found on the official website https://rada.re/r/docs.html and https://rada.re/r/talks.html
* The IRC chat available on freenode called #radare, or the telegram group https://t.me/radare

Many information are also available on the internet and via a simple search on google:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/1408600/46907915-b2c2a480-cf1a-11e8-8c5c-bc74ce874f08.png">

Best Regards,

**Comment by Maijin** [comment]
instruction boundary(all the instruction's address and its mode)` - aoj or ao
    function boundary(function start address) - afl or afll or aflj
    function signature(parameters and return values) afcf or pdf 
    control flow graph - ag?
    call graph. - ag?

**Comment by valour01** [comment]
@Maijin  Thank you so much for your help. I would like to try immediately.
