### ISSUE TITLE
Detect "pure" functions

### ISSUE THREAD

**Issue by radare** [radare/radare2#11833]
afi should show this information.

Identify if the function depends on external variables or functions that are not pure.

Usually pure functions can be interesting to look at (crypto stuff, etc)

**Comment by bart1e** [comment]
It may be very hard or even impossible to do (see answer 2 in [link](https://stackoverflow.com/questions/8760956/can-a-compiler-automatically-detect-pure-functions-without-the-type-information).
However, it's definitely worth doing for some simpler functions. If you don't mind, I would like to work on this issue.

**Comment by radare** [comment]
Sure, go for it!
