### ISSUE TITLE
dmh puts "No Heap section" error msg twice, if main arena is not detected

### ISSUE THREAD

**Issue by mkopec3** [radare/radare2#11856]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali arm 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0 19759 @ linux-x86-64 git.2.9.0-397-g856f8bcc8 commit: 856f8bcc8e85a1afe6125900aa7bb7e108437a80 build: 2018-10-18__17:49:51

### Expected behavior

Error message "_No Heap section_" is shown **once**, if heap main arena is not detected

### Actual behavior

Error message "_No Heap section_" is shown **twice**, if heap main arena is not detected

### Steps to reproduce the behavior 

1) Run r2 in debugging mode on /bin/touch
$ r2 -d /bin/touch 

2) From r2 cli run dmh:
> dmh

### Additional Logs, screenshots, source-code,  configuration dump, ...

![dmh](https://user-images.githubusercontent.com/25580985/47168492-520fdf00-d301-11e8-83b2-35224356019a.png)

**Please check my PR for the bug fix proposal**

**Comment by radare** [comment]
ok :)
