### ISSUE TITLE
XREF in local variables

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11865]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86 
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0 19966 @ darwin-x86-64 git.2.9.0-395-g9beda2f60 commit: 9beda2f60f97a35f3e20c2c5f6933241bb78afbf build: 2018-10-18__11:04:28

### Expected behavior

- Get file [ch2.zip](https://github.com/radare/radare2/files/2494822/ch2.zip)
- aaa
- axt @ local_ch # But needs to be able to select function though

Should display something like:

```
main 0x0804831a [DATA] mov dword [local_ch], str.john
main 0x08048366 [DATA] mov eax, dword [local_ch]
```

### Actual behavior

Display nothing

**Comment by ret2libc** [comment]
Just for completeness, as a temporary workaround I think users could use `afvR` and `afvW`.
```
| afvR [varname]                list addresses where vars are accessed (READ)
| afvW [varname]                list addresses where vars are accessed (WRITE)
```

**Comment by radare** [comment]
Imho global and local xrefs are different things. Thats why they are in separate commands. But maybe we can move afvR into axv or something like that or make an statement about that difference

**Comment by Maijin** [comment]
`axt` doesn't have global/local distinction in the "a x t" I think we could have the local_10 also shown in the `axt` and then maybe create specific commands for local and global xrefs. Having axt doing both  would ease the workflow

**Comment by radare** [comment]
the var xrefs depend on function, the global ones does not. so its different behaviour. also, you can have a flag with the same name as a local var with different meaning. so i dont like the thing of having one command for both things. but we can discuss

**Comment by XVilka** [comment]
Agree with @radare that we should keep these commands separate - unlike in the source code in binaries those two are too different entities. On the other hand we should unify commands between them. So lets propose syntax/commands changes.

**Comment by Maijin** [comment]
Maybe in command line separation, but we probably want to have it under `x` in visual mode though (and same for cutter).

**Comment by ITAYC0HEN** [comment]
+1 for the feature :) 

I also prefer `axt local_10h` instead of playing with other commands.

In the implementation level, it should check for the right context of the local variable. Aka, to show all references to this variable in the function which is in the current\temp seek.

**Comment by xarkes** [comment]
We already have so many commands, I think `axt` should just do what one expects, show all the xref to the specified address.
Now if you want to separate those commands, I think you could do it, but imho `axt` should still call the two underlying commands (local and global refs)

**Comment by sivaramaaa** [comment]
> ITAYC0HEN :  I also prefer axt local_10h instead of playing with other commands.
In the implementation level, it should check for the right context of the local variable. Aka, to show all references to this variable in the function which is in the current\temp seek.

I totally agree with @ITAYC0HEN , `axt local_10h` should list result of `afvR` and `afvW` for variables in the function at current seek !

> radare : the var xrefs depend on function, the global ones does not. so its different behaviour

IMHO , global and local refs comes into picture only with respect to flags , until now we only have local variable so why should we worry about global refs ?

> radare : also, you can have a flag with the same name as a local var with different meaning

yup this could be a problem , we have to think a solution for this !

**Comment by radare** [comment]
theres nothing that impeds a local var have the same name of a function. also the var xrefs depend on current offset to identify the function.

**Comment by XVilka** [comment]
Agree with @radare. The only proper way to address local variables is using `function_name.var_name` or something like that.
