### ISSUE TITLE
Missing XREF iOS binary

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#11879]
Reported in Cutter - https://github.com/radareorg/cutter/issues/857#issuecomment-431560941

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac OS x64
| File format of the file you reverse (mandatory)      | iOS MachO
| Architecture/bits of the file (mandatory)            | x64 - ARM
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0 19966 @ darwin-x86-64 git.2.9.0-395-g9beda2f60 commit: 9beda2f60f97a35f3e20c2c5f6933241bb78afbf build: 2018-10-18__11:04:28

### Expected behavior

XREF for strings 11652 0x0035eeb6 0x10035eeb6  13  14 (4.__TEXT.__cstring) ascii I love Google``

at the following offsets after aaa:

```
0x1001AC58C
0x1001AC590
```

### Actual behavior

No xrefs

### Steps to reproduce the behavior 
- https://github.com/radareorg/cutter/files/2497950/DVIA-v2.zip
- aaa
- axt @ 0x10035eeb6

**Comment by Maijin** [comment]
Fixed with `aae`, so will check to add aae in aaa on arm and maybe more archs

**Comment by radare** [comment]
Yes aae is very importsnt for arm and arm64. As well as for mips. Though it was already there. Thats why i never use aaa :D
