### ISSUE TITLE
Bad varsub with bold theme

### ISSUE THREAD

**Issue by radare** [radare/radare2#11889]
<img width="1248" alt="screenshot 2018-10-21 at 14 46 34" src="https://user-images.githubusercontent.com/917142/47267167-2cbce400-d540-11e8-8e0a-3d1f2c7d7c2c.png">

bin is mojave's /bin/ls

**Comment by XVilka** [comment]
Probably because of the bold ESC sequences and matching of the numbers to substitute.

**Comment by radare** [comment]
yeah i think the bold ansi attr is not stripped proerly when messing with that string..
