### ISSUE TITLE
Missing things in Visual Panels

### ISSUE THREAD

**Issue by radare** [radare/radare2#11890]
* [x] shift+tab not working in tty (maybe use 'n' and 'p' to go next/prev)
* [x] the '/' key should prompt to set the scr.hightlight variable
* [x] Menus with sub-menus doesnt have any indicator
* [x] 'x' key should do the same as in visual (show xrefs to seek there) .. maybe its cool to have a command to open one split
* [x] '0'-'9' keys must follow jumps/calls like in normal visual
* [x] remove the press_any_key in panels help because its using r_cons_less already
* [x] Visual hud should run from visual panels when pressing '_', imho i would kill the "sentence" commands (but this is something to discuss).. or at least make it available with a different key.
* [x] The window mode is confusing and may result in wrong layouts
* [x] Closing a frame in zoom mode results in fuckedup layouts
* [x] : key not working when menubar is selected/open
* [ ] ... more to come

**Comment by Vane11ope** [comment]
i'm on them :)

**Comment by XVilka** [comment]
@Vane11ope please also update the book/embedded radare2 help also then (otherwise nobody will knew these features exist)

**Comment by Vane11ope** [comment]
@XVilka 

i will update them and you know what, planning to write a blog post which i do time to time and now is about the time i guess. 

also doing real-time live V! demo sometimes which japanese people like :)

**Comment by SajjadPourali** [comment]
In BB-OFF mouse mode, users can debug on cfg, I think it's will better if this mode can work on visual panels.
Something like this:
![screen shot 2018-10-25 at 9 57 08 pm](https://user-images.githubusercontent.com/20374762/47522084-31590380-d884-11e8-8260-672f7ff0bec5.png)


Also reset to default panel items can be helpful.

**Comment by Vane11ope** [comment]
Hello @SajjadPourali 

let me think about it first, but thank you for the suggestion.

And about reset to default panel items, you can do it already. 

git pull first and get the latest version, then go to menu by pressing 'm' and manipulate the pointer by hjkl and go to File->Load Layout->Default would do the job :)

**Comment by Vane11ope** [comment]
About the window mode, probably is ugly solution so I need to improve a lot but definitely not for this version, so i will move this to next version.

**Comment by Vane11ope** [comment]
...which I don't even know how, so could you move this to next release @radare ?

**Comment by radare** [comment]
It was not even for this release

**Comment by radare** [comment]
all the issues listed here are gone! thanks @Vane11ope !!
