### ISSUE TITLE
Incorrect help messages

### ISSUE THREAD

**Issue by guedou** [radare/radare2#11927]
### Expected behavior

Python is started.

### Actual behavior

Python does not start

### Steps to reproduce the behavior 

```
[0x00000000]> #!python
Invalid hashbang. See '#!' for help.
```

### Additional information

The curren help message
```
[0x00000000]> #?
|Usage #!interpreter [<args>] [<file] [<<eof] 
|  #                     comment - do nothing
|  #!                    list all available interpreters
|  #!python              run python commandline
|  #!python foo.py       run foo.py python script (same as '. foo.py')
|  #!python arg0 a1 <<q  set arg0 and arg1 and read until 'q'
```

Starting python with `#!pipe` works fine:
```
[0x00000000]> #!pipe python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

Is updating the help message in` cmd_hash.c ` enough to fix this issue?

**Comment by radare** [comment]
#!python only works if you build+install the rlang plugin

otherwise it will use the #!pipe. python when interpreting a .py file

**Comment by radare** [comment]
One solution would be to run #!pipe XXX, when it cant find a plugin with that name. but this will hide the understanding if rlang is loaded into the running instance,  but this can be checked later from the code.

What do you think about this option?

**Comment by guedou** [comment]
I think that if `#!python` only works when the python `rlang` plugin is installed, the best fix is to modify the help message. For example, we can remove the `#!python` lines or use examples that are built with `r2` like `c2pipe`. We could also modify the message "Invalid hashbang. See '#!' for help.\n" with something more explicit like ""Invalid hashbang. Please install the corresponding rlang plugin".

If I understand `r2lang` correctly, silently falling back to `#!pipe. python` will not allow me to access `r2` API. So this not a good fix.

**Comment by radare** [comment]
Then go for it and send a pr
