### ISSUE TITLE
RList asserts in /R

### ISSUE THREAD

**Issue by radare** [radare/radare2#11925]
`r2 -qc/R /bin/ls`

problem:

in. cmd_search.c:971

```
-> 971 			r_list_append (localbadstart, (void *) (intptr_t) idx);
```

using intptr_t is a bad usage of the api because if idx==0 the element will not be added

**Comment by ret2libc** [comment]
Ok I will solve this with the `ht` implementation, since actually `badstart` is just a map to check which addresses needs to be skipped and the ht data structures handle well NULLs/0s. Also, it will be much more efficient.

**Comment by ret2libc** [comment]
fixed with https://github.com/radare/radare2/commit/08422752f2e5eeca09a1bb70f3571833ccbe426a
