### ISSUE TITLE
Support for Kam1n0?

### ISSUE THREAD

**Issue by E3V3A** [radare/radare2#11937]
Is there already, or any plans to support the [Kam1n0](https://github.com/McGill-DMaS/Kam1n0-Community)?

An issue was raised and closed as described [here](https://github.com/McGill-DMaS/Kam1n0-Community/issues/24), suggesting that adapting it to Radare2 should be easy and straightforward...

**Comment by radare** [comment]
First time i hear about this project. The issue makes more sense in their repo than here. Feel free to ask whatever you need to get it working

**Comment by XVilka** [comment]
If there is nothing specific from radare2 is required - we should close this issue.
