### ISSUE TITLE
Fix the r_print_colorize_opcode () in libr/util/print.c

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1195]
See the mess https://github.com/radare/radare2/blob/master/libr/util/print.c#L912

I'll fix that, opening bug as a reminder

**Comment by radare** [comment]
@XVilka any chance?

**Comment by radare** [comment]
removing milestone. tired of waiting

**Comment by XVilka** [comment]
@cyanpencil you may want to look at this one by the way

**Comment by radare** [comment]
i think we can close this, the code changed a lot since 2014. please be more specific in the coloring issue
