### ISSUE TITLE
axg doesn't print a graph

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#11969]
### Expected behavior

Print some pretty call graph

### Actual behavior

Prints only the addresses (and in a weird way)

### Steps to reproduce the behavior 

`r2 /bin/ls -c "aaa; s main; axg"`

**Comment by radare** [comment]
Done in. d6e98f23384fc56e9ebfedb31cd9961430947ac9

**Comment by radare** [comment]
if you dont tell the destination, axg will find no path. this is all paths from main to main.

to somthing like axg sym.imp.printf to find from main to printf
