### ISSUE TITLE
Wrong resource names in PE files

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#11981]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64, wsl, Arch Linux x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86_32 x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 20010 @ linux-x86-64 git.3.0.1-80-g6080edf
commit: 6080edf13b207d23d7b3faf09b96aa10dffd6cc2 build: 2018-10-29__15:31:34

### Expected behavior

While executing `iR` or `iRj`, the right resource name should be shown

### Actual behavior
Currently, radare2 wrongfully parses the resource name from the PE resource directories. More accurately, he passes the ID of the resource instead of parsing the relevant name from the table

### Steps to reproduce the behavior 
 - Open a PE file (`r2 file.exe`)
 - Execute `iR` or `iRj~{}`
 - Compare the shown resource name to the name as shown in another resource parser (e.g Resource Hacker)
 - radare2 shows a wrong name

### Additional Logs, screenshots, source-code,  configuration dump, ...

r2 output "2874":
![image](https://user-images.githubusercontent.com/20182642/47654803-4d1a1d80-db94-11e8-9263-ffcc3051e3fd.png)

Expected Name "MAINICON":
![image](https://user-images.githubusercontent.com/20182642/47654841-61f6b100-db94-11e8-82f2-7a752822dac6.png)

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by a1ext** [comment]
Seems like the timestamps of resources are being displayed in local time zone:
![image](https://user-images.githubusercontent.com/14978853/47665467-3b477300-dbb2-11e8-89ce-72a633b27cd9.png)

**Comment by Maijin** [comment]
ping @blenk92 ^

**Comment by Maijin** [comment]
See this one @koffiedrinker ^

**Comment by koffiedrinker** [comment]
Yes, I can do this one 👍

**Comment by ITAYC0HEN** [comment]
woohoo :)
