### ISSUE TITLE
dbt takes 5s to finish in Linux

### ISSUE THREAD

**Issue by radare** [radare/radare2#12022]
in mac and windows takes almost no time, there must be something wrong in the linux backend here.

**Comment by davidpolverari** [comment]
I don't have enough free time to look at this now, but from a cursory glance, the delay seems to stem from the semaphore on `ptrace_wrap()` from the homonymous library. I think @thestr4ng3r could tell if this could be faster in Linux or not.

**Comment by thestr4ng3r** [comment]
Yes indeed, the frequent calls to ptrace seem to be slowed down a lot by the synchronization overhead. But I already have an idea how to fix this.
