### ISSUE TITLE
Handle pP stack print format rotation in Vpp"c

### ISSUE THREAD

**Issue by radare** [radare/radare2#12021]
Its working in Vppc, but not in Vpp"c, the problem is that " is the split mode, uses different code to choose how to print the stack and ignores that new setup.

**Comment by radare** [comment]
to add more details in here.. pressing 'p' or 'P' when the cursor mode is pointing at the stack when using the columns split view for that debugger view is not doing anything right now, should do the same as without the '"' columns mode

<img width="906" alt="screenshot 2019-02-13 at 14 40 13" src="https://user-images.githubusercontent.com/917142/52715659-47a6de80-2f9d-11e9-8eab-2aabd2bcdc69.png">

**Comment by radare** [comment]
Also integrate the dri output in here

**Comment by Vane11ope** [comment]
i'm on this now

**Comment by radare** [comment]
please @Vane11ope updates on this
