### ISSUE TITLE
Radare2's cursor in visual mode goes wrong place when in hex data block

### ISSUE THREAD

**Issue by ikey4u** [radare/radare2#12034]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04.3 LTS 
| File format of the file you reverse (mandatory)      | ELF 64-bit LSB executable
| Architecture/bits of the file (mandatory)            | x86-64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 19888 @ linux-x86-64 git.3.0.1-99-g03996cb commit: 03996cb944d4f76254bab129b43360be7f602ac1 build: 2018-10-30__14:05:28

The code I use is 
```
#include <stdio.h>
#include <string.h>

int main(int argc, char **argv)
{
    char str[1024];

    strcpy(str, argv[1]);
    printf("%s\n", str);

    return 0;
}
```
and compile it using `gcc main.c -o main` with gcc version 5.4.0.

I want to check the `.rela.plt` section manually, the steps are as follows:

1. Execute the following command in r2 shell `r2 -A -d main` -> `s section..rela.plt` -> `V` -> `p`, and I went here

![image](https://user-images.githubusercontent.com/12681575/47843694-62dd4c00-ddfb-11e8-996e-6979b959314e.png)

2. In visual mode, I press `c` to toggle the cursor and move to 0x400400, then I press `dd`, r2 gives me following

![image](https://user-images.githubusercontent.com/12681575/47843800-a5068d80-ddfb-11e8-947a-3a0b3af33c48.png)

3.  Now, the cursor is at 0x400400, when I press `j` to move the cursor down, it goes here

![image](https://user-images.githubusercontent.com/12681575/47844800-4e4e8300-ddfe-11e8-9277-b629c3809298.png)

It does not jump to the next line, but several lines! Beside that, when you move around the hex data, you will see the cursor appears in wrong places, for example:

![image](https://user-images.githubusercontent.com/12681575/47845308-a1750580-ddff-11e8-84ec-cb6d27afb042.png)

The unexpected cursor location mess up the analysis, hope some one will fix this bug

**Comment by deepakchethan** [comment]
This seems to have been fixed, It is going to the next block as it does for the disarm. Please close if it is the expected behavior or let me know what is to be done.

**Comment by deepakchethan** [comment]
ping @radare @XVilka
