### ISSUE TITLE
header of dos .exe file (MZ) is treated as part of the loaded image

### ISSUE THREAD

**Issue by p2mate** [radare/radare2#12033]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86 64
| File format of the file you reverse (mandatory)      | MZ
| Architecture/bits of the file (mandatory)            | x86/16
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0 19855 @ linux-x86-64 git.2.9.0-389-g55bdcbb94 commit: 55bdcbb94c5423182d0972f34e5e56ff6d838507 build: 2018-10-28__17:04:57

### Expected behavior

entry point is  CS:IP where IP is the header field at offset 0x14 and  CS is the header field at offset 0x16. This is assuming the binary is 'loaded' at segment 0.

### Actual behavior

entry point is CS:IP + 0x20 (size of MZ header) + 0x10 (size of the relocation table)

### Steps to reproduce the behavior 

radare2 -b 16 hello.exe 
ie

### Additional Logs, screenshots, source-code,  configuration dump, ...

[hello.zip](https://github.com/radare/radare2/files/2536611/hello.zip)

**Comment by Maijin** [comment]
The current entrypoint is:

```
[0000:00aa]> ie
[Entrypoints]
vaddr=0x000000aa paddr=0x000000aa baddr=0xffffffffffffffff laddr=0x00000000 haddr=-1 type=program

1 entrypoints

[0000:00aa]>```

What should be expected one? Can you make a fake output of what you expect?

**Comment by radare** [comment]
Witht the answers you did you can just patch the code and fix the issue in a pr so we can discuss that change in there

**Comment by p2mate** [comment]
I would expect:

[0000:007a]> ie
[Entrypoints]

vaddr=0x0000007a paddr=0x0000007a baddr=0xffffffffffffffff laddr=0x00000000 haddr=-1 type=program

1 entrypoints

[0000:007a]>

this would match what eg dos debug.exe or IDA do.

![debug_001](https://user-images.githubusercontent.com/28183857/47880060-e7938e80-de2a-11e8-9eae-a1522ceb8a2d.png)

**Comment by Maijin** [comment]
Can you do a Pull request instead of pasting a diff like @radare indicated? That way it will get run against our testsuite.

Thanks in advance

**Comment by p2mate** [comment]
I'm not convinced this should be merged, as it creates other problems as mentioned. What do you think?

**Comment by Maijin** [comment]
Open a Pull-Request so we can assess.

**Comment by radare** [comment]
ping

**Comment by p2mate** [comment]
was fixed in https://github.com/radare/radare2/commit/d29085336a7d7843287db6152890ff9698e5b336#diff-3b98a85702df1141692acf8e523272b3
