### ISSUE TITLE
alcatel radare2 from website linker error (PIE)

### ISSUE THREAD

**Issue by gnarf-xx** [radare/radare2#12042]
hardware: alc4tel, unrooted
radare-version: current radare2 from website linker error (PIE)

no further text. (Installer works, Phone is from 2015)

spekulatius: Makefile should support PIE?

**Comment by Maijin** [comment]
Follow the bug report template, this issue does not make any sense.

**Comment by radare** [comment]
May i assume he is installing the android app from the playstore? Just use termux

**Comment by gnarf-xx** [comment]
https://www.idealo.de/preisvergleich/OffersOfProduct/4927421_-one-touch-pixi-4-4-alcatel-mobile-phones.html

@Xvika, Maijin: no time for such a long template, why are you spamming the issues with useless questions?

@radare: I will try when I will have internet, I have used termux before and liked it. Thanks for the pointer.

**Comment by Maijin** [comment]
@gnarf-xx no time to guess what you want then.

**Comment by radare** [comment]
Xvilka and maijin are right. This report had no sense at all and was completely useless. I just made a random guess. Try to be more structured when reporting issues because i still dont understand whats the problem u have, the version of r2 you are testing or which arch is the target
