### ISSUE TITLE
asm.flags.inbytes not working with graphs

### ISSUE THREAD

**Issue by radare** [radare/radare2#12046]
try debugging or emulating and press 's', no "rip" appears anywhere until we set it back to 0

```
 e asm.flags.inbytes =1
```

**Comment by ret2libc** [comment]
3.2 for this too, unless @cyanpencil has already a good fix for this ready?

**Comment by radare** [comment]
He told me the solution a week ago in the chat its 2 lines. I was expecting the pr. I can fix later because enopatience
