### ISSUE TITLE
fflush (stdin) is undefined in C

### ISSUE THREAD

**Issue by lzutao** [radare/radare2#12053]
In line https://github.com/radare/radare2/blob/a0844ef2c3a2e2852e975634686f0eca4a447093/libr/cons/input.c#L254. `fdin` is only assigned by `stdin`, so `fflush (fdin)` is actually `fflush (stdin)`.  In standard C, `fflush` works only with output/update stream, not input stream.

Reference:
- https://stackoverflow.com/questions/18170410/what-is-the-use-of-fflushstdin-in-c-programming

**Comment by radare** [comment]
Can you send a pr?
