### ISSUE TITLE
Incorrect/unclear function boundaries offset and minbound

### ISSUE THREAD

**Issue by JulianSchuette** [radare/radare2#12065]
Either it's me not grasping the difference between a function's `minbound` and its `offset` or a bug in radare2. Consider this function (output of `aflj`):

```
    {
        "offset": 4549740,
        "name": "sym.tightdb::TableViewBase::sync_distinct_view_unsignedlong",
        "size": 2394,
        "realsz": 4598,
        "stackframe": 1200,
        "calltype": "(null)",
        "cost": 4425,
        "cc": 103,
        "bits": 16,
        "type": "fcn",
        "nbbs": 213,
        "edges": 298,
        "ebbs": 9,
        "minbound": "4267940",
        "maxbound": "4552134",
        ...
    }
```

The following information is unexpected/inconsistent:

When I do `pdf @4549740` (print function at `offset`), radare2 starts to print at `0x456644` (=`4548164`), which is none of the values above.

I would expect that `offset` always points to the begin of the function's first basic block. Indeed, this seems to be the case here, as `offset` + `realsize` = `maxbound`. But `maxbound - minbound = 284194` and this is clearly much longer than the function should be.

So, what does `minbound` indicate and how does it differ from `offset`? 

<a href="https://drive.google.com/file/d/1SEk4raES0tpMLxrJfhUVmwuTaGJkQskK/view?usp=sharing">Example binary</a>

radare2 version:
```
radare2 3.1.0-git 19773 @ linux-x86-64 git.3.0.1-17-g567cdb1fc
commit: 567cdb1fcfc4a643fd39fc1237c3a0734b4231fa build: 2018-10-23__07:31:40
```

**Comment by radare** [comment]
see size and realsz too

its basically the boundaries of the function, aka the minimum address of any bb contained by this function.

**Comment by ITAYC0HEN** [comment]
executing `pdf @ 4549740` printed from the wrong offset for me too

**Comment by JulianSchuette** [comment]
Makes sense, thank you.
