### ISSUE TITLE
Multiple evaluation in r_num_abs(x) macro

### ISSUE THREAD

**Issue by lzutao** [radare/radare2#12060]
https://github.com/radare/radare2/blob/865ec593b18b874924cae43f2d46bd2448262095/libr/include/r_util/r_num.h#L5

Macro `r_num_abs(x)` evaluated `x` two times. Consider that if we called  `r_num_abs(x++)`, it would expand to `x++>0?x++:-x++`?

Why not use [`llabs`](https://www.freebsd.org/cgi/man.cgi?query=llabs&sektion=3&apropos=0&manpath=FreeBSD+11.2-RELEASE+and+Ports) function instead?

Note that this macro is only used in `r_io_shift`.

**Comment by radare** [comment]
is llabs available in windows?

**Comment by lzutao** [comment]
[It is](https://msdn.microsoft.com/en-us/library/kw1ee768.aspx) (From VS2015).

**Comment by radare** [comment]
then lgtm to switch, but i would do that by replacing the macro covered with an #if, so we can easilly switch back if there’s any issue in any specific target

**Comment by lzutao** [comment]
If target conforms to ISO C99, then `llabs` could be used without any problems.

Btw, is `r_num_abs(x)` type generic? If it is, type of arguments passed to r_num_abs should be stored somewhere.

**Comment by radare** [comment]
No it is not
