### ISSUE TITLE
Infinite loop when opening r2 on some PE32

### ISSUE THREAD

**Issue by Hyask** [radare/radare2#12082]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Debian Stretch x86_64
| File format of the file you reverse      | PE
| Architecture/bits of the file            | x86/32
| r2 -v     | radare2 3.0.0-git 20000 @ linux-x86-64 git.2.9.0-208-g0ceca0b07101   commit: 0ceca0b07101698a3f72d1a4101607eaad65a6d3 build: 2018-11-07__17:21:38
| File | [Aspnet_perf.dll.zip](https://github.com/radare/radare2/files/2558253/Aspnet_perf.dll.zip)

### Expected behavior

Get the r2 shell.

### Actual behavior

`radare2` hanging with its process taking 100% of a CPU. Need to kill it.

### Steps to reproduce the behavior 

Just open the attached binary with `r2` without particular arguments.

### Additional Logs, screenshots, source-code,  configuration dump, ...

We found that by just trying to download PDBs for a Windows filesytem. Other binaries are able to reproduce the same bug.  
We can easily make the PR with this file in `radare2-regressions`, but I don't know if you accept Microsoft's files. Maybe generating a custom one able to reproduce would be better for `r2`.

[Aspnet_perf.dll.zip](https://github.com/radare/radare2/files/2558253/Aspnet_perf.dll.zip)

**Comment by radare** [comment]
This is a big regression

**Comment by radare** [comment]
Unless it wasnt catched before but must be fixed before release

**Comment by radare** [comment]
Can you send a pr in the r2r repo adding this bin in bins/fuzzed ? thanks!
