### ISSUE TITLE
Modify Section

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [radare/radare2#12083]
Hi to all,
I am trying to modify the permission on sections, reading documentation I should use the S command, but r2 returns error that is invalid.
Can someone explain to me with an example how to do it and what I should use to refer to a particular section (e.g. name or the number in the list or other things)

**Comment by radare** [comment]
You cant modify sections with the S command. It was removed exactly for thia reason. To avoid confussions.

If you want to modify the section in the binary use rabin2 -O

If you want to modify the segment loaded in memory associated with the bin sections use om

Press any key to continue

**Comment by GiuseppeLaurenza** [comment]
how it is possible to modify the permission of sections through r2pipe in python?

**Comment by radare** [comment]
Using rsyscmdf api call and run rabin2 -O...
