### ISSUE TITLE
RISC-V architecture support

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1208]
>RISC-V (pronounced "risk-five") is a new instruction set architecture (ISA) that was originally designed to support computer architecture research and education, which we now hope will become a standard open architecture for industry implementations. RISC-V was originally developed in the Computer Science Division of the EECS Department at the University of California, Berkeley.

Istruction Set - http://riscv.org/download.html#tab_isaspec

**Comment by XVilka** [comment]
@aquynh what do you think about this? This is important, since [lowRISC](http://www.lowrisc.org/) is getting bigger these days, and soon to be released.

**Comment by aquynh** [comment]
yes if RISC-V has disassembler, it will be easy to support that in Capstone.
(note that tablegen only ensure assembler, but not disassembler)

otherwise, for those architectures do not have support from LLVM, you can still port them to Capstone like what M68K did recently.

**Comment by radare** [comment]
Already done in master
