### ISSUE TITLE
Add an option to always confirm on quit

### ISSUE THREAD

**Issue by radare** [radare/radare2#12099]
Sometimes we are doing stuff in many r2 sessions and you end up cloaing the wrong one by accident. Being able to “protect” some sessions from quitting by setting a var will be useful to avoid such accidents.

This happens when no project or debugger session.

**Comment by r00tten** [comment]
Hey, I would like to implement this feature, if it is still wanted.

**Comment by radare** [comment]
Imho the way to go here is to add a new config variable `scr.confirmquit` or `scr.quitprompt` or something like this (im open to suggestions here). Being set to false by default.

When the user goes to quit r2 (prompt_repl) it must chk if scr.interactive is set and if this var is set, then ask for confirmation (like its done when quitting a debugging sesion).

Yes. it's still in the wishlist :) looking forward the PR.

assigned to @r00tten
