### ISSUE TITLE
Double free in Graph View

### ISSUE THREAD

**Issue by skvl** [radare/radare2#12091]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Manjaro Linux 18.0.0, 4.14.79-1-MANJARO x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.1 0 @ linux-x86-64 git.3.0.1
commit: HEAD build: 2018-10-22__23:17:27

### Expected behavior
Show function graph view.

### Actual behavior
Double free.

### Steps to reproduce the behavior 
* Download: [iphlpapi.zip](https://github.com/radare/radare2/files/2560686/iphlpapi.zip)
* Seek function with `s pdb.AllocateAndGetAdaptersAddresses`
* Define function in visual mode `df`
* Show graph `VV`
* Scale down with `-` multiple times
* Move the graph with `hjkl` or arrows

### Additional Logs, screenshots, source-code,  configuration dump, ...

* Valgrind output: [radare-crash.log.zip](https://github.com/radare/radare2/files/2560700/radare-crash.log.zip)
* Asciinema: [radare2-crash.cast.zip](https://github.com/radare/radare2/files/2560717/radare2-crash.cast.zip)

**Comment by radare** [comment]
Can you write a script to reproduce the crash without the scrolling around step?

I can repro this issue from 2.9 i think but never find a reliable way to reproduce it

**Comment by skvl** [comment]
Hello @radare ,

How to write a script for this? Is it possible to record keys pressed during session in _radare2_?

**Comment by skvl** [comment]
@radare, I have recorded the session with _stdin_. You could check all keys pressed in "i" events (see [doc](https://discourse.asciinema.org/t/does-asciinema-record-the-passwords-i-type-during-recording-session/23)).

[r2-crash-stdin.cast.zip](https://github.com/radare/radare2/files/2571470/r2-crash-stdin.cast.zip)

**Comment by radare** [comment]
the valgrind logs are generated with a stripped build of r2-3.0.1, so it's not very useful for us. Can you reproduce this issue with the last version in git? default build comes with symbols so we have at least linenumber info

**Comment by radare** [comment]
can you confirm the crash is still there? couldnt reproduce yet

**Comment by skvl** [comment]
I didn't work with that task since then. Fill free to close the bug if You wish.

**Comment by radare** [comment]
So the bug is gone?

**Comment by skvl** [comment]
> So the bug is gone?
I don't know. I didn't test it since then.

I have just report the issue I have seen. If nobody could see it then may be it is gone.

**Comment by radare** [comment]
it can be related to one bug i blindfixed 2 weeks ago. thats why i was asking if this fix was making this issue gone too
