### ISSUE TITLE
esil.stack.(addr|size|depth) have the same description string

### ISSUE THREAD

**Issue by gordon-quad** [radare/radare2#12103]
### Work environment
Any.
Validated against d2c72751556fe04733f170aa21861941a155ad50 commit

### Expected behavior
```
e? esil.stack.addr
e? esil.stack.size
e? esil.stack.depth
```
should return different descriptions based on the config option in question

### Actual behavior
All three return "Number of elements that can be pushed on the esilstack".

### Steps to reproduce the behavior 
```
e? esil.stack.addr
e? esil.stack.size
e? esil.stack.depth
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
See https://github.com/radare/radare2/blob/d2c72751556fe04733f170aa21861941a155ad50/libr/core/cconfig.c#L2483-L2485

**Comment by EvenCode** [comment]
#12422 PR.

**Comment by radare** [comment]
use "Fix #.... - description" syntax in the commit message to close the issues automatically
