### ISSUE TITLE
iS= documentation

### ISSUE THREAD

**Issue by EvanCarroll** [radare/radare2#12111]
`iS=` is not documented. There is no `iS?`, and it's not under `i?`. Also, the screenshot on the website mentions `iS` https://rada.re/r/pics.html That seems to be the modern equivalent of `iS=`.

**Comment by radare** [comment]
+1 for this. The ? Is not handled in any i subcommand

**Comment by radare** [comment]
```
[0x1000011ec]> iS?
| iS [entropy,sha1]  Sections (choose which hash algorithm to use)
| iS.                Current section
| iS=                Show ascii-art color bars with the section ranges
| iSS                List memory segments (maps with om)
[0x1000011ec]>
```
