### ISSUE TITLE
Support variable length arrays in 'pf'

### ISSUE THREAD

**Issue by radare** [radare/radare2#1215]
We need support to variable length arrays in `pf`. This is, instead of using `pf 3xx` be able to determine the number by the contents of a memory address or a flag name (resolved by rnum) ...

This is up to discussion, but we can do something like `pf {ctr}xx` where 'ctr' is a flag.. another option would be to use {[ptr]}xx ..

**Comment by Hyask** [comment]
exactly as array already work in pf, I propose to use

    pf.struct x[flag]w[0x4dd23553]

how does rnum works, btw?

**Comment by radare** [comment]
What if we want to chain struct fields and use them as varlength arrays?

The syntax looks good to me, but i think that rnum should be able to resolve offset of fields in structs and values of binded structs with a special syntax. That way the [flag] could be anything, a number, a flag, a expression or just the field of another struct.

**Comment by XVilka** [comment]
@Hyask any updates on this?

**Comment by radare** [comment]
ping @Hyask

**Comment by XVilka** [comment]
@radare @Hyask closing this issue, right?
