### ISSUE TITLE
ood not working

### ISSUE THREAD

**Issue by JacobPimental** [radare/radare2#12167]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Manjaro x64
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 19954 @ linux-x86-64 git.3.0.1-169-ga88fc63da commit: a88fc63da35ab842e8e1cdedbe7ff8ff62223b99 build: 2018-11-08__01:37:5

### Expected behavior
Radare2 to reopen the current file in debug mode.

### Actual behavior
Radare2 does not reopen file. Output:
```
$ r2 ch25.bin 
 -- Remember to maintain your ~/.radare_history
[0x08048890]> ood
Could not execvp: No such file or directory
Could not execvp: No such file or directory
r_core_file_reopen: Cannot reopen file: dbg://ch25.bin  with perms 0x0007, attempting to open read-only.
[0x00000000]> 
```

### Steps to reproduce the behavior 
1. Open any file in radare2
2. Use the ood command
3. See error
[ch25.zip](https://github.com/radare/radare2/files/2583445/ch25.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...
It does look like ood is appending an extra space to dbg://filename which may be causing the issue.

**Comment by bet4it** [comment]
Sorry, this is a regression introduced in #12023.

The extra space was added by:
https://github.com/radare/radare2/blob/a88fc63da35ab842e8e1cdedbe7ff8ff62223b99/libr/core/cmd_open.c#L890
But it's harmless.
