### ISSUE TITLE
pdc mangles data

### ISSUE THREAD

**Issue by gordon-quad** [radare/radare2#12190]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Gentoo x86_64 hardened (ssp+pie)
| File format of the file you reverse (mandatory)      | ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, stripped
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 19959 @ linux-x86-64 git.3.0.1-260-g712fca842 commit: 712fca842cdbece5e9859de452957d17f4050abd build: 2018-11-15__22:16:08

### Expected behavior
pdc should not modify data.

### Actual behavior
after pdc px shows zeros instead of data.

### Steps to reproduce the behavior 
```
$ r2 -A libc-2.27.so
[0x00021c00]> s sym.gnu_dev_major
[0x00103ed0]> px
```
[observe real data]
```
[0x00103ed0]> pdc
[0x00103ed0]> px
```
[observe zeros]

### Additional Logs, screenshots, source-code,  configuration dump, ...
https://asciinema.org/a/J3K7w1BbARGY2r9et5FtZAMW9 (sorry, i ran -A there so it's a bit longer than it should)
[libc.zip](https://github.com/radare/radare2/files/2587297/libc.zip)

**Comment by XVilka** [comment]
Please craft a test for radare2-regressions.

**Comment by radare** [comment]
Pdc is pretty buggy in many situations. I dont. Doing aa in libc is totally ujnecesary. Just af the function you see this problem.

I would recommend you to try to find a reproducer in a smaller bin or provide a simpler way to test.

Also, i would encourage you to use r2dec instead

Also you cant disassemble data. And pdc will “decompile” anything u throw at it, even if its data

**Comment by radare** [comment]
without analyzing the contents of this function are valid instructions. so this is not a problem with the pdc command at all, also the issue you are complaining about was fixed already in master, so pls try again because i cant reproduce
