### ISSUE TITLE
afta can't run in debugger mode.ions (afta)

### ISSUE THREAD

**Issue by Th3R4nd0m** [radare/radare2#12229]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali Linux 2018.4
| r2 -v full output 
radare2 3.1.0-git 20119 @ linux-x86-64 git.3.0.1-289-gc042d3e13
commit: c042d3e136d43ac3b8f989fef12e7fced2de1670 build: 2018-11-19__20:07:25
[rev50_linux64-bit.zip](https://github.com/radare/radare2/files/2596789/rev50_linux64-bit.zip)

When I try to run it in debug mode, it gives me this:

r2 -d rev50_*
Process with PID 3170 started...
= attach 3170 3170
bin.baddr 0x55f3805ef000
Using 0x55f3805ef000
asm.bits 64
 -- Default scripting languages are NodeJS and Python.
[0x7fca1a759210]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
**[TOFIX: afta can't run in debugger mode.ions (afta)**
[x] Type matching analysis for all functions (afta)
[x] Use -AA or aaaa to perform additional experimental analysis.
= attach 3170 3170
3170
[0x7fca1a759210]> ood
Wait event received by different pid 3170
Process with PID 3172 started...
File dbg:///root/Downloads/rev50_linux64-bit  reopened in read-write mode
= attach 3172 3172
**WARNING: bin_strings buffer is too big (0xffffaa1b9247d198). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)**
**WARNING: bin_strings buffer is too big (0xffffaa1b9247c160). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)**
3172
[0x7f55c5398210]>

**Comment by Maijin** [comment]
Should now be fixed, please retry with latest r2 from git.
