### ISSUE TITLE
Invalid instruction errors while performing an analysis

### ISSUE THREAD

**Issue by samrg472** [radare/radare2#12234]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | MacOS Mojave 10.14.1 / x86_64 / 64
| File format of the file you reverse (mandatory)      | MACH064
| Architecture/bits of the file (mandatory)            | x86 / 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 20115 @ darwin-x86-64 git.3.0.1-287-g23fb5bc19 commit: 23fb5bc197ded5a9179f54cf502945332932c38e build: 2018-11-19__09:04:25

### Expected behavior
```
[0x100000f90]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Enable constraint types analysis for variables
```

### Actual behavior
```
[0x100000f90]> aaaa
[Invalid instruction (possibly truncated) at 0x100001fe8
Invalid instruction (possibly truncated) at 0x100001fe4
Invalid instruction (possibly truncated) at 0x100001f72
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Enable constraint types analysis for variables
```

### Steps to reproduce the behavior 
1. Load the binary with `r2 ./a.out`
2. Run command `aaaa`

### Additional Logs, screenshots, source-code,  configuration dump, ...

This is not a dupe of issue #12112, it might seem related but the error here always occurs during an analysis regardless of debugging. Commit 4a5048f appears to be the cause as this is when the error started appearing.

#### Binary
[a.out.zip](https://github.com/radare/radare2/files/2596298/a.out.zip)

#### Compiler information
```
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

# xcode version
10.1 beta 3 (10O45e)
```

#### Code
```c++
#include <iostream>

using namespace std;

int main(int argc, char const *argv[]) {
  cout << "test" << endl;
  return 0;
}
```

#### Compile options
```
$ clang++ test.cpp
```

**Comment by radare** [comment]
we should probably remove those warnings so ppl can stop worrying about them

**Comment by radare** [comment]
its all fixed now
