### ISSUE TITLE
VpX is not working as expected

### ISSUE THREAD

**Issue by radare** [radare/radare2#12230]
X should show refs from the current FUNCTION, not the current address.
x is behaves the same.. so imho we should change the behaviour too.

in fact those actions should depend if the cursor is enabled or not.

if enabled -> find refs from/to the current address
else find refs/xrefs of function

**Comment by Maijin** [comment]
The current behavior is what's expected for most users, we already discussed this and it got refactored by @xarkes last year on GSOC. x shows current ref for current address same for X otherwise it's super confusing.

@XVilka

**Comment by radare** [comment]
Should honor the cursor mode.

**Comment by Maijin** [comment]
Yes that I agree with

**Comment by ret2libc** [comment]
3.2 IMHO. Only 2 days before release.... it's not even clear we really want the behaviour described in the first comment of the issue. I agree with @Maijin that current behaviour seems fine (though as said it should honor cursor)

**Comment by radare** [comment]
It was already honoring cursor but it was ignoring function. Which is in my workflow very useful and all i care when i work with xrefs. This pr doesnt changes the behaviour it just honors the function refs when theres a function so its not that bad at least.

**Comment by ret2libc** [comment]
> It was already honoring cursor

Actually, from a quick test it seems when you follow a XREF with the cursor, it doesn't work very well, it goes to another address and not the one you want.

> but it was ignoring function. Which is in my workflow very useful and all i care when i work with xrefs. This pr doesnt changes the behaviour it just honors the function refs when theres a function so its not that bad at least.

I also agree with @Maijin that the way you want to do it, seems super confusing. Cursor or not, users should always expect to get the xref/ref of the *current* address. And by *current* address we mean the one in the first line or the one selected by the cursor. Having two different behaviours is just confusing, IMHO.

So, again, let's just talk a bit more about this and delay at least to 3.2.
