### ISSUE TITLE
Vdi should set to dword first

### ISSUE THREAD

**Issue by radare** [radare/radare2#12240]
Vdi doesnt works without Vdd

**Comment by ret2libc** [comment]
3.2 IMHO. It's not a blocking thing, no need to hurry a fix for this, given it was like this for a long time afaik.

**Comment by radare** [comment]
its a 1 line fix and its easy to fix. being like this for a long time is not an excuse for not fixing it. its just not intuitive

**Comment by radare** [comment]
oh nvm :D this is wrong, because imm applies to the instruction if its not data. my bad. maybe the  best way to avoid this confusion to happen is by showing a warning, but meh, we can probably rethink this when we support tab in disasm cursor mode
