### ISSUE TITLE
Questions about binary analysis

### ISSUE THREAD

**Issue by yasong** [radare/radare2#12268]
I have some questions about the binary reverse. IDA Pro can't identify the type function in the some stripped binaries. Now I would like to construct a already reversed functions database. I have known the name and the function of the assembly function in one version.  So, I want to find the function in the binary of other versions. 
For example:
```
    I know sub_30008000 is strcpy() in version 1.2 of stripped binary. 
    I want find the strcpy() in version 1.3 of stripped binary. 
    Bindiff is one choice. But it must compare both the .idb file which takes a very long time if the size of stripped binary is large.
```
I wonder how to extract the signatures of the function and quickly locate the function in the other binary. I appreciate that if you would like to help me. Thank you.

**Comment by Maijin** [comment]
Greetings,

You can read the signatures section of the radare2book - https://radare.gitbooks.io/radare2book/signatures/zignatures.html and watch associated talks from past r2con like - https://www.youtube.com/watch?v=kR_2yKSeHT8

Best Regards,
