### ISSUE TITLE
Fails to create a function at program's entry point

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#12273]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x64, Windows 10 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19660 @ linux-x86-64 git.2.9.0-321-ga38a3bd01  commit: a38a3bd01191de5c91e69ee492f4387dca09a03e build: 2018-11-22__12:08:29

### Expected behavior
radare2 should succeed with making a function in the program's entry point it detected.

### Actual behavior

Although radare2 detects the entrypoint, it fails to make a function out of it. It also fails to create a function when manually executing `af @ entry0`.

### Steps to reproduce the behavior 
 - Open the binary in radare2
 - Analyze the binary
 - Execute `f~entry0` and see the entrypoint detected. 
 - Execute `afl` and see that radare2 failed to detect functions
 - Try to manually define a function using `af @ entry0`. This will fail as well

[EsetCrackme2015.zip](https://github.com/radare/radare2/files/2608015/EsetCrackme2015.zip)

```
$ r2 EsetCrackme2015.dll 
[0x10000226]> aa
[Cannot find function 'entry0' at 0x10000226 entry0 (aa)
[x] Analyze all flags starting with sym. and entry0 (aa)

[0x10000226]> f~entry0
0x10000226 1 entry0

[0x10000226]> afl
[0x10000226]> 
[0x10000226]> af @ entry0
[0x10000226]> afl
[0x10000226]> 
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
IDA is able to recognize this function:
![image](https://user-images.githubusercontent.com/20182642/48902347-fb964300-ee60-11e8-8aef-05e98892dcb3.png)

**Comment by radare** [comment]
type omfg

**Comment by radare** [comment]
its because the map have no exec permissions

**Comment by radare** [comment]
ping?

**Comment by ITAYC0HEN** [comment]
executing `omfg +x` works
how can we avoid this?

**Comment by radare** [comment]
should be fixed in my  pr

**Comment by radare** [comment]
can you add a test?

**Comment by radare** [comment]
should be fixed now please submit a test
