### ISSUE TITLE
typedefed structs fail to load with to

### ISSUE THREAD

**Issue by radare** [radare/radare2#12272]
``` 
$ cat findus.h

typedef struct {
    const char* name;
    const char* signature;
    void*       fnPtr;
} JNINativeMethod;
$ r2 -
[0x00000000]> t-*
[0x00000000]> to findus.h
[0x00000000]> tk
JNINativeMethod=typedef
struct.{=name,signature,fnPtr
struct.{.fnPtr=void *,8,0
struct.{.fnPtr.meta=4
struct.{.name=const char *,0,0
struct.{.name.meta=4
struct.{.signature=const char *,4,0
struct.{.signature.meta=4
typedef.JNINativeMethod=struct <anonymous>
{=struct
[0x00000000]> ts
{
[0x00000000]>
```

**Comment by sivaramaaa** [comment]
@XVilka pls have a look at this issue , my closed PR [here](https://github.com/radare/radare2/pull/12320)

**Comment by XVilka** [comment]
It is a part of shlr/tcc update, it takes longer than I thought, moving to 3.3.0, fix will be in the same PR as bitfields support and other TCC improvements.

**Comment by radare** [comment]
this is important

**Comment by radare** [comment]
status update?

**Comment by kazarmy** [comment]
I think the situation in https://github.com/radare/radare2/pull/13006#issuecomment-460922946 shouldn't happen with normal human-written code so I'm closing this issue.

**Comment by kazarmy** [comment]
... as fixed.
