### ISSUE TITLE
Docker radare/radare2: "r2pm -i www-m" failed: make[1]: yarn: Command not found

### ISSUE THREAD

**Issue by asukakenji** [radare/radare2#12287]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Docker Container (Linux c3943e97b53a 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux), downloaded by `docker pull radare/radare2`
| File format of the file you reverse (mandatory)      | (N/A)
| Architecture/bits of the file (mandatory)            | (N/A)
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 1 @ linux-x86-64 git.3.1.0-git commit: e2542082f1f73670f23813fc8d261d6944dd40a7 build: 2018-11-22__16:46:19

### Expected behavior

The `www-m` (Material web UI) package should be installed successfully.

### Actual behavior

The `www-m` (Material web UI) package failed to build. Other packages were successfully built. It complained that `yarn` is not found.

### Steps to reproduce the behavior 

```
r2@c3943e97b53a:~$ r2pm -i www-enyo
(... Finished successfully ...)

r2@c3943e97b53a:~$ r2pm -i www-m
Already up-to-date.
Install Done For www-m
make -C www/m build
make[1]: Entering directory '/home/r2/.local/share/radare2/r2pm/git/radare2-webui/www/m'
yarn
make[1]: yarn: Command not found
Makefile:4: recipe for target 'build' failed
make[1]: *** [build] Error 127
make[1]: Leaving directory '/home/r2/.local/share/radare2/r2pm/git/radare2-webui/www/m'
Makefile:22: recipe for target 'material' failed
make: *** [material] Error 2

r2@c3943e97b53a:~$ r2pm -i www-p
(... Finished successfully ...)

r2@c3943e97b53a:~$ r2pm -i www-t
(... Finished successfully ...)
```

**Comment by radare** [comment]
you have to install this tool, yarn is not packaged by r2pm

**Comment by Maijin** [comment]
You can u

**Comment by radare** [comment]
?
