### ISSUE TITLE
x86-16 far call follows wrong address

### ISSUE THREAD

**Issue by BlaCoiso** [radare/radare2#12284]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows/x86/64
| File format of the file you reverse (mandatory)      | none| Architecture/bits of the file (mandatory)            | x86/16
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 20216 @ windows-x86-64 git.3.0.1-333-ge2542082f commit: e2542082f1f73670f23813fc8d261d6944dd40a7 build: 22/11/2018__16:39:38,22
### Expected behavior
far call follows correct address (segment*16 + offset)
### Actual behavior
far call follows wrong address (segment)
### Steps to reproduce the behavior 
far jump address: `wx ea34002001;?v $j` (`ljmp 0x120:0x34`)
far call jump address: `wx 9a34002001;?v $j` (`lcall 0x120:0x34`)
(both should be the same, first command outputs 0x1234, second command outputs 0x120)

**Comment by XVilka** [comment]
Add a regression test please

**Comment by BlaCoiso** [comment]
I made a PR for the regression test and I also managed to fix it and opened another PR with the fix
