### ISSUE TITLE
Wrong xrefs on some x86 binaries

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#12300]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux/x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 21678 @ linux-x86-64 git.3.0.1-347-g2308897b3 commit: 2308897b3aaed562163caafaac9695b69021ce59 build: 2018-11-23__13:43:10

### Expected behavior
```
entry0 0x40488d [DATA] mov rdi, main
```

### Actual behavior
```
main 0x40298d [CODE] jmp 0x4029a5
main 0x402b62 [CODE] jmp 0x402b10
main 0x402c1b [CODE] jmp 0x402b10
main 0x402d9b [CODE] jmp 0x402b10
...
main 0x404687 [CODE] jmp 0x4032db
main 0x4046ec [CODE] jmp 0x4046c4
main 0x40470a [CODE] jmp 0x403dd5
main 0x404737 [CODE] jmp 0x4040c2
main 0x4047c6 [CODE] jmp 0x404409
main 0x4047ce [CODE] jmp 0x4047e5
main 0x4047f5 [CODE] jmp 0x404835
main 0x404800 [CODE] jmp 0x404409
main 0x404867 [CODE] jmp 0x40446b
entry0 0x40488d [DATA] mov rdi, main
```

### Steps to reproduce the behavior 
```
$ ./binr/radare2/radare2 -A -c "axt main;q" -q ../radare2-regressions/bins/elf/analysis/ls-linux-x86_64-zlul
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

Regression introduced in commit 68122dc27e0c8ad227ad5a2d4d9c92ac59a38867 .
Applying this patch fixes the issue:
```patch
diff --git a/libr/anal/fcn.c b/libr/anal/fcn.c
index 3533c3673..40596db4e 100644
--- a/libr/anal/fcn.c
+++ b/libr/anal/fcn.c
@@ -1580,8 +1580,7 @@ R_API void r_anal_trim_jmprefs(RAnal *anal, RAnalFunction *fcn) {
 	const bool x86 = anal->cur->arch && !strcmp (anal->cur->arch, "x86"); // HACK
 
 	r_list_foreach (refs, iter, ref) {
-		if (ref->type == R_ANAL_REF_TYPE_CODE && r_anal_fcn_is_in_offset (fcn, ref->addr)
-		    && (!x86 || !r_anal_fcn_is_in_offset (fcn, ref->at))) {
+		if (ref->type == R_ANAL_REF_TYPE_CODE && r_anal_fcn_is_in_offset (fcn, ref->addr)) {
 			r_anal_xrefs_deln (anal, ref->at, ref->addr, ref->type);
 		}
 	}
```

**Comment by ret2libc** [comment]
See https://github.com/radare/radare2-regressions/pull/1560

**Comment by ret2libc** [comment]
BTW, it was working in 3.0.1.

**Comment by kazarmy** [comment]
That was before 68122dc27e0c8ad227ad5a2d4d9c92ac59a38867.

**Comment by ret2libc** [comment]
Yes, everything before https://github.com/radare/radare2/commit/68122dc27e0c8ad227ad5a2d4d9c92ac59a38867 , 3.0.1 included, was working well. I just wanted to explicitly states that it would be a regression introduced in this very release, so it wouldn't be good to go out with a new release with this bug.

**Comment by radare** [comment]
You see it you fix it

**Comment by kazarmy** [comment]
If anal->dict_xrefs should actually be of type HT_<ut64>_<RList <ut64> > (gotta love those angle brackets), then I suppose the fastest way to unblock this would be to do like @ret2libc suggests and apply the reverting patch.

**Comment by kazarmy** [comment]
wait a minute, I can just use HtUP with P pointing to a RList/RVector

**Comment by ret2libc** [comment]
I don't think the problem is in refs, but in the fact that the anal code is adding wrong references. The kind of storage used to store xrefs seems irrelevant to me for this issue.

**Comment by kazarmy** [comment]
yeah, you're right
