### ISSUE TITLE
"Oops at ..." reported when running aoj

### ISSUE THREAD

**Issue by HongxuChen** [radare/radare2#12301]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64 etc
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 20190 @ linux-x86-64 git.3.0.1-349-gc82049aaa commit: c82049aaad191c61991f58b2f5815113945aa0d3 build: 2018-11-23__22:44:08

### Expected behavior
r2 runs without warning

### Actual behavior
r2 runs with warning message like 'Oops at 0x004006e4 (61 73 68 ...)'.

### Steps to reproduce the behavior 
- run `r2 hw.out`and enter the shell
- type `aoj 0x00400430~{}` where 0x00400430 is the entry address (other addresses similarly)

### Additional Logs, screenshots, source-code,  configuration dump, ...
![2018-11-23-224734_340x257_scrot](https://user-images.githubusercontent.com/843267/48949303-7ef38980-ef72-11e8-9a60-2a6dacfc330b.png)

tested ELF:[hw.zip](https://github.com/radare/radare2/files/2611083/hw.zip)

**Comment by radare** [comment]
That means invalid instruction

**Comment by HongxuChen** [comment]
@radare But this is fully generated by clang and I haven't modified anything in it.

**Comment by HongxuChen** [comment]
Sorry I was using the wrong way, should be something like `aoj 1 @ 0x00400430`.
The error message however is confusing.

**Comment by HongxuChen** [comment]
Ok, will close it. Sorry about that.
