### ISSUE TITLE
Wrong PE resource Timestamp

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#12327]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0 20218 @ darwin-x86-64 git.3.1.0 commit: c033496ebc7034e52a84be9cdb2d2dfad6a4cfac build: 2018-11-26__10:29:06

### Expected behavior

[e15040beca2635a66eb395162f39db9f23468e7bf9f00c9c62dd5913cd5f3850.zip](https://github.com/radare/radare2/files/2615829/e15040beca2635a66eb395162f39db9f23468e7bf9f00c9c62dd5913cd5f3850.zip)
(It's malware, password is "infected")

`iR`

```
Resource 0
  name: 1
  timestamp: Sat May 19 09:15:04 2012
  vaddr: 0x004a2f04
  size: 308
  type: CURSOR
  language: LANG_ENGLISH
```

### Actual behavior

`iR`

```
Resource 0
  name: 1
  timestamp: Tue May 25 14:28:02 2004
  vaddr: 0x004a2f04
  size: 308
  type: CURSOR
  language: LANG_ENGLISH
```

**Comment by Maijin** [comment]
From https://twitter.com/JusticeRage/status/1066030635721113600

**Comment by JusticeRage** [comment]
Here is the code I use for these timestamps (dosdate format): https://github.com/JusticeRage/Manalyze/blob/b606b3002b95195af76ecf631ab1f35bc4a90438/manape/utils.cpp#L172

It is worth mentioning that they are _sometimes_ in traditional posix format, depending on the compiler, which makes it hard to decode them reliably. A good heuristic is to compare that date with the PE compilation date, and if they're close enough (12h of difference tops), you're on the right track.

**Comment by koffiedrinker** [comment]
@alvarofe If you want, I can work on this. :)

**Comment by Maijin** [comment]
@koffiedrinker please do 👍

**Comment by alvarofe** [comment]
go ahead low priority for me since busy with other matters.
