### ISSUE TITLE
ARM5 x32 | Err: Selected processor does not support ARM mode `bkpt $0

### ISSUE THREAD

**Issue by unixfreaxjp** [radare/radare2#12334]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm5
| File format of the file you reverse (mandatory)      | -.
| Architecture/bits of the file (mandatory)            | -
| r2 -v full output, **not truncated** (mandatory)     |  (build error)

### Expected behavior

build success

### Actual behavior

build error/failed

### Steps to reproduce the behavior 

See bug report in: https://github.com/unixfreaxjp/dev/blob/master/r2-v3.1-ARMv5_builderr.md

Reported by: @unixfreaxjp

**Comment by unixfreaxjp** [comment]
@radare Thinking over,I think I'd better open issue for this one. The workaround works but it is a bad solution to lend other's bp flag values..

**Comment by radare** [comment]
Can you share the output of this command?

echo | gcc -dM -E -

Thanks

**Comment by unixfreaxjp** [comment]
> Can you share the output of this command?

Pls wait until `mipsel` is finished, will answer w/update in here.

**Comment by unixfreaxjp** [comment]
> Can you try if teq $0,$0 works as an alternative to bpkt?

Will git pull the duplicated ifdef fix first. And remake to see whether it is fixed that way.

**Comment by radare** [comment]
it should fail to build, the error was related to bkpt, and this is still there

**Comment by unixfreaxjp** [comment]
> Can you try if teq $0,$0 works as an alternative to bpkt?
It is added to the test task.

**Comment by unixfreaxjp** [comment]
@radare Applying the commit 260a9e64cc9bf1ff55b508cd2dccca92a607daf3
and the problem looks solved, thank's for the effort!

>Can you try if teq $0,$0 works as an alternative to bpkt?

Not even trying this one.

Test result:
```asm
 :
make[1]: Leaving directory `/test/radare2/libr/anal/d'
cd libr && make install-symlink
make[1]: Entering directory `/test/radare2/libr'
make[2]: Entering directory `/test/radare2'
for FILE in r_anal.pc r_asm.pc r_bin.pc r_bp.pc r_config.pc r_cons.pc r_core.pc r_crypto.pc r_debug.pc r_egg.pc r_flag.pc r_fs.pc r_hash.pc r_io.pc r_lang.pc r_magi\
                ln -fs "/test/radare2/pkgcfg/$FILE" "/usr/lib/pkgconfig/$FILE" ; done
make[2]: Leaving directory `/test/radare2'
make[1]: Leaving directory `/test/radare2/libr'
cd binr && make install-symlink
make[1]: Entering directory `/test/radare2/binr'
cd .. && \
        mkdir -p "/usr/bin" && \
        for BINARY in rax2 rasm2 rabin2 rahash2 radiff2 radare2 rafind2 rarun2 ragg2 r2agent ; do ln -fs "/test/radare2/binr/$BINARY/$BINARY" "/usr/bin/$BINARYe
cd .. && ln -fs "/test/radare2/binr/r2pm/r2pm" "/usr/bin/r2pm"
cd .. && rm -rf "/usr/share/radare2/3.1.0/r2pm"
cd .. && mkdir -p "/usr/share/radare2/3.1.0/"
#ln -fs "/test/radare2/binr/r2pm/d" "/usr/share/radare2/3.1.0/r2pm"
cd .. && ln -fs "/usr/bin/radare2" "/usr/bin/r2"
cd .. && ln -fs "/test/radare2/binr/preload/libr2.so" "/usr/lib/libr2.so"
cd .. && cd "/usr/lib" && \
                mv libr2.so libr2.so.3.1.0 && \
                ln -fs libr2.so.3.1.0 libr2.so
make[1]: Leaving directory `/test/radare2/binr'
cd shlr && make install-symlink
make[1]: Entering directory `/test/radare2/shlr'
mkdir -p "/usr/lib"
#cd tcc ; for FILE in libr_tcc* ; do \
        #       ln -fs `pwd`/$FILE /usr/lib/$FILE ; done
make[1]: Leaving directory `/test/radare2/shlr'
mkdir -p "/usr/bin"
ln -fs "/test/radare2/sys/indent.sh" "/usr/bin/r2-indent"
ln -fs "/test/radare2/sys/r2-docker.sh" "/usr/bin/r2-docker"
mkdir -p "/usr/share/radare2/3.1.0/hud"
ln -fs "/test/radare2/doc/hud" "/usr/share/radare2/3.1.0/hud/main"
#mkdir -p "/usr/share/radare2/3.1.0/flag"
#ln -fs /test/radare2/libr/flag/d/tags.r2 "/usr/share/radare2/3.1.0/flag/tags.r2"
cd "/usr/lib/radare2/" ;\
                rm -f last ; ln -fs 3.1.0 last
cd "/usr/share/radare2/" ;\
                rm -f last ; ln -fs 3.1.0 last
mkdir -p "/usr/share/radare2/3.1.0/"
/bin/sh sys/ldconfig.sh
/bin/sh ./configure-plugins --rm-static //usr/lib/radare2/last/
configure-plugins: Loading ./plugins.cfg ..
Removed 0 shared plugins that are already static
test@debian-armel:~/radare2$ r2 -v
radare2 3.1.0 20293 @ linux-arm-32 git.3.1.0-13-g260a9e6
commit: 260a9e64cc9bf1ff55b508cd2dccca92a607daf3 build: 2018-11-27__14:55:49
test@debian-armel:~/radare2$ date&&git describe --all --long
Tue Nov 27 16:13:55 UTC 2018
heads/master-0-g260a9e6
test@debian-armel:~/radare2$
```

**Comment by unixfreaxjp** [comment]
Memo: In relation to this breakpoint macro on non Intel CPU @radare fixed bp ifdef on MIPS cpu too at this commit: 81583efa05f8d3dd7a17435334327e793d41280a
