### ISSUE TITLE
ARM aav interprets data as address and break thumb mode

### ISSUE THREAD

**Issue by sylvainpelissier** [radare/radare2#12340]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux arm 32
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM, EABI5
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0 20233 @ linux-x86-64 git.3.1.0-14-g13d5fcdd8 commit: 13d5fcdd87a7f824e4dde826b142264a135a10b2 build: 2018-11-27__17:43:56

### Steps to reproduce the behavior 

Compile
```
const int a = 0x000103c9;

int main()
{
		int b;
		b = 2;
		b = b + a;
        return 0;
}
```

with arm-linux-gnueabi-gcc

- Binary:
[thumb.zip](https://github.com/radare/radare2/files/2621715/thumb.zip)

`r2 -aa thumb` will work fine. But after `aav` command, the main function is interpreted in thumb instructions.

```
  :::::::   ;-- main:
  :::::::   ; UNKNOWN XREF from entry0 (+0x34)
  :::::::   ; UNKNOWN XREF from main (+0x38)
  :::::::   ; UNKNOWN XREF from section..rodata (+0x4)
  :::::::   0x000103c8      04b0           add sp, 0x10
  :`======< 0x000103ca      2de5           b 0xfe28
  : :::::   0x000103cc      00b0           add sp, 0
  :,======< 0x000103ce      8de2           b 0x108ec
  ========< 0x000103d0      0cd0           beq 0x103ec
  ========< 0x000103d2      4de2           b 0x10870
  :|:::::   0x000103d4      0230           adds r0, 2
  ========< 0x000103d6      a0e3           b 0x10b1a
  :|:::::   0x000103d8      0830           adds r0, 8
  :|::`===< 0x000103da      0be5           b 0xfdf4
  :|:: ::   0x000103dc      1c20           movs r0, 0x1c
  `=======< 0x000103de      9fe5           b 0xff20
   |:: ::   0x000103e0      0830           adds r0, 8
   |`=====< 0x000103e2      1be5           b 0xfe1c
   | : ::   0x000103e4      0230           adds r0, 2
   | :,===< 0x000103e6      83e0           b 0x104f0
   | :|::   0x000103e8      0830           adds r0, 8
   | `====< 0x000103ea      0be5           b 0xfe04
  --------> 0x000103ec      0030           adds r0, 0
   | ,====< 0x000103ee      a0e3           b 0x10b32
   | ||::   0x000103f0      0300           movs r3, r0

```

Other tool:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/1408600/49111823-7f9d6000-f291-11e8-92ee-38223f4de6de.png">

**Comment by radare** [comment]
cc @alvarofe

**Comment by alvarofe** [comment]
assign to me, otherwise might forget

**Comment by radare** [comment]
Cant assign to you if you dont have commit access. Check the invite. Also if you have commit access you can also assign the issues to yourself

**Comment by alvarofe** [comment]
done

**Comment by radare** [comment]
try setting a higher base address when loading the bin if you can

**Comment by radare** [comment]
i think aav should also check if the value is inside af ucntion or not. to reduce false positives

**Comment by sylvainpelissier** [comment]
The problem is now solved on this binary.
