### ISSUE TITLE
How to install it on Win10

### ISSUE THREAD

**Issue by baddate** [radare/radare2#12345]
Should I follow this [docs](https://radare.gitbooks.io/radare2book/content/first_steps/compilation_portability.html)?
I tried it, but it doesn't working.
Anyone can give me some advice？

**Comment by XVilka** [comment]
What **exactly** didn't work?

**Comment by baddate** [comment]
The _Compile Radare2 Code_ section
run `meson install -C build --no-rebuild`

**Comment by baddate** [comment]
> What **exactly** didn't work? See https://radare.gitbooks.io/radare2book/content/first_steps/windows_compilation.html

The _Compile Radare2 Code_ section
run `meson install -C build --no-rebuild`

**Comment by XVilka** [comment]
@baddate you also didn't provide a log of the exact error why `meson` failed.

**Comment by Maijin** [comment]
Greetings,

For windows you don't need to compile if you don't want to contribute, you can just use the following:

http://radare.mikelloc.com/get/3.1.0/radare2_installer-msvc_32-3.1.0.exe
or
http://radare.mikelloc.com/get/3.1.0/radare2_installer-msvc_64-3.1.0.exe

This is also described in the page you mentionned - https://radare.gitbooks.io/radare2book/content/first_steps/windows_compilation.html.
