### ISSUE TITLE
Segfault d_print_comp cp-demangle.c

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#12350]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac OS Mojave
| File format of the file you reverse (mandatory)      | Mach-O 64-bit executable 
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0 20239 @ darwin-x86-64 git.3.1.0-21-gbd4bfbc6f commit: bd4bfbc6f31019562dfe1254587907bf13f36d90 build: 2018-11-28__20:38:54

Segfault see ASAN - https://pastebin.com/fRb0ynnk
Binary is on Telegram -> r2-bins/Dolphin

**Comment by radare** [comment]
This issue affects GNU binutils, it's an stack exhaustion bug.. but i cant reproduce any crash with their code. so im gonna update it again. btw this is the symbol name that makes it crash:

`__ZN5mpark3lib5cpp147forwardIZN13ConfigLoaders21BaseConfigLayerLoader15LoadFromSYSCONFEPN6Config5LayerEEUlRT_E_EEOS8_RNSt3__116remove_referenceIS8_E4typeE`
