### ISSUE TITLE
Undo seek does no longer work when seeking via xref in visual mode

### ISSUE THREAD

**Issue by astuder** [radare/radare2#12359]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0 20130 @ linux-x86-64 git.2.9.0-838-g7d8bfc462 commit: 7d8bfc462ed8527bca10158d446220c303bc72a0 build: 2018-11-29__13:23:53

### Expected behavior

after seek to xref, u returns to location from where x was entered

### Actual behavior

u returns to location from where last conventional seek was issued. I'm pretty sure that this is a recent regression.

### Steps to reproduce the behavior 

```
r2 /bin/ls
aa
```
location is 0x5430
```
s 0x5560
```
location is 0x5560
```
vp
x
0
```
location is 0x403b
```
u
```
location is 0x5430, instead of expected 0x5560

**Comment by XVilka** [comment]
Make sense also to do test for this behaviour.

**Comment by astuder** [comment]
With this patch, it returns to the correct location after pressing u twice, The first press of u does nothing.

**Comment by astuder** [comment]
Correction: The first u does nothing, the second u seeks one undo step too far.

**Comment by astuder** [comment]
Feels like it's downhill with every commit :-) Now (2ebe4db8b8f824133c86bd79aa3d4bac19d8727a) seek via Vx doesn't work for me at all.

**Comment by radare** [comment]
what about now?

**Comment by astuder** [comment]
Nope. Still the same: Seek via x no longer works in visual mode. It stays at the same location. Tried different binaries, same effect.
Tried will pull, make as well as /sys/install.sh.

**Comment by astuder** [comment]
https://asciinema.org/a/lFqC9GODwrQwi6fM74a545668
It's not clear from the video. But I try to jump to xref by pressing enter. But it stays at origin address.

**Comment by radare** [comment]
try again, sorry for the noise. i reproduced your issue after seeing the vid., should be fixed in master

**Comment by astuder** [comment]
Everything works as expected again. Thanks!
