### ISSUE TITLE
hexagon pc-realted jumps are absolute

### ISSUE THREAD

**Issue by jane-hopper** [radare/radare2#12352]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | hexagon
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0 20237 @ linux-x86-64 git.3.1.0 commit: c033496ebc7034e52a84be9cdb2d2dfad6a4cfac build: 2018-11-28__16:38:53

### Expected behavior
as hexagon programer referese says:

Syntax | Operation
-- | --
jump label | Direct jump.  								Branch to address specified by label. Label is encoded as PC-relative signed immediate value.
jumpr Rs | Indirect jump. Branch to address contained in general register Rs.
if ([!]Ps) jump label if ([!]Ps) jumpr Rs | Conditional jump. Perform jump if predicate expression evaluates to true.

### Actual behavior

all jumps are direct

### Steps to reproduce the behavior 

<img width="1098" alt="default" src="https://user-images.githubusercontent.com/45401230/49179475-6c5ac500-f363-11e8-91b1-a497e732b45c.png">

i can send image, if there no legal iusses with that 

### Additional Logs, screenshots, source-code,  configuration dump, ...

as i think there need to be like that `op->jump = op->addr + hi->ops[0].op.imm;`
but it autogenerated
https://github.com/radare/radare2/blob/master/libr/anal/arch/hexagon/hexagon_anal.c#L534

**Comment by Maijin** [comment]
Can you make a Pull-Request? You can use the github pencil button

**Comment by Maijin** [comment]
@XVilka please^

**Comment by jane-hopper** [comment]
no, wait, it does not convert to signed so jump to lower adresses does not working

**Comment by XVilka** [comment]
I invited @jane-hopper to the corresponding repo.

**Comment by Maijin** [comment]
@jane-hopper did you fix it in the hexagon repository @XVilka access to? Can we close this?

**Comment by XVilka** [comment]
It is now public: https://github.com/radareorg/r2hexagon

**Comment by XVilka** [comment]
And it should be very similar to : https://github.com/radareorg/r2hexagon/commit/2d4830bb613e2c31b3eecab150dd4011a0d59953 + https://github.com/radare/radare2/commit/09f7a03123c6311845d77d87a868b68c3275d9b8
I just have no time to check the instruction set what instructions should be fixed exactly.

**Comment by XVilka** [comment]
@Rot127 send a pull request please

**Comment by XVilka** [comment]
Fixed.
