### ISSUE TITLE
Add command to search for infinite loop instructions

### ISSUE THREAD

**Issue by radare** [radare/radare2#12378]
Maybe set them to FAMILY_INFINITE when spotting a jmp $$

**Comment by radare** [comment]
All yours

**Comment by ITAYC0HEN** [comment]
ping @bart1e

**Comment by bart1e** [comment]
Not yet, but will be in few days.

**Comment by ITAYC0HEN** [comment]
Okay, great! This issue is in the next milestone :)

**Comment by bart1e** [comment]
I’ll try to send it tomorrow. If I don’t finish until then, I’ll let you know.

**Comment by radare** [comment]
Feel free to ask any question

**Comment by bart1e** [comment]
I’ll be rather busy untill tuesday and I don’t want to block this issue, so feel free to work on it. And I’m sorry for the delay.

**Comment by radare** [comment]
i could do it quickly  but i  prefer to move the issue because enotime irl and i prefer to focus on stability and testing for past-tomorrow release

**Comment by radare** [comment]
which  command  would  u use for this?

**Comment by bart1e** [comment]
Something like “aj”, which would mean something like “analyse jmps”.

**Comment by ITAYC0HEN** [comment]
I disagree. Should be under "/" for searching

**Comment by bart1e** [comment]
Seems I misunderstood the issue. I thought it was about detecting infinite loops, thus analysing every unconditional jump. By the way, what are the other infinite loop instructions you mentioned? (I know it can even be “ret” or conditional jump, but considering every case would be very complicated)

**Comment by radare** [comment]
An unconditional jmp can be also used for this. Probably its enough to just check any analop->jump == analop->addr. No need to find multi instruction infinite loops. For calls. Thst wont work on x86. But bl on arm, mips is also another way to achieve the same.

**Comment by radare** [comment]
i think infinite loop instructions should be listed with a different color than a jmp, maybe use the trap color because its kind of int3
