### ISSUE TITLE
Fix the clang-scan build bugs

### ISSUE THREAD

**Issue by radare** [radare/radare2#12392]
http://ci.rada.re/job/radare2-scan-build/6312/clangScanBuildBugs/

**Comment by dav1901** [comment]
Updated link: http://ci.rada.re/job/radare2-scan-build/6365/clangScanBuildBugs/

**Comment by radare** [comment]
Aaaand its gone! the server is down and we need to generate new logs in local.

**Comment by XVilka** [comment]
We will setup new server, no worries, once the infrastructure is up and
running.
