### ISSUE TITLE
PDB fails to load properly with big structs

### ISSUE THREAD

**Issue by BlaCoiso** [radare/radare2#12438]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows/x86/64
| File format of the file you reverse (mandatory)      | PE / PDB
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     |  radare2 3.2.0-git 20376 @ windows-x86-64 git.3.1.3-15-g2cd65e45b commit: 2cd65e45b131ca650307c67af852c6c8c612e153 build: 06/12/2018__15:29:24,29
### Expected behavior
PDB loads without errors
### Actual behavior
`<string>:1: error: '}' expected (got "86")` and similar error messages
### Steps to reproduce the behavior 
`idp`
### Additional Logs, screenshots, source-code,  configuration dump, ...
https://github.com/radare/radare2/blob/fb55a230e3aa8c5e34844e03de2ff8f1ed93b08a/libr/core/cmd_type.c#L973
apparently `idp` just executes `.idpi*`

**Comment by XVilka** [comment]
Missing file to reproduce.

**Comment by Wenzel** [comment]
Hi,

i have the same issue here when loading `win32k.sys` pdb file


~~~
[0xfffff97fff077010]> idp
<string>:1: error: invalid number

<string>:1: error: '}' expected (got "3")
<string>:1: error: declaration expected

[0xfffff97fff077010]> 
~~~

Please find the file [here](https://drive.google.com/open?id=1P_MViVvZLF-HsSBr1DdF5ZvFWpKTbE4j)

**Comment by XVilka** [comment]
@GustavoLCR @pelijah FYI
