### ISSUE TITLE
Regression: "continue" (dc, dcu...) not working on debug+analysis

### ISSUE THREAD

**Issue by davidpolverari** [radare/radare2#12437]
# Regression: "continue" (dc, dcu...) not working on debug+analysis

When using `r2 -dA /bin/true` (or any system or non-system binary), using any "continue" command (`dcu`, `dc` after setting a breakpoint, etc) fails with the message `TODO continue`.

It used to work fine before, once system ASLR was disabled, and was a very useful feature for debugging. Seems regression took place after bbebd7ed86bce843e42a0108215370f8c56491f6.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 9 (Stretch) x86/64 (Kernel 4.9.0-8-amd64)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20351 @ linux-x86-64 git.3.1.3-19-gfb55a230e commit: fb55a230e3aa8c5e34844e03de2ff8f1ed93b08a build: 2018-12-09__12:06:46

### Expected behavior
```
$ r2 -dA /bin/true
...
[0x7f1a87370c20]> dcu main
Continue until 0x55b672c465c0 using 1 bpsize
hit breakpoint at: 55b672c465c0
[0x55b672c465c0]>
```

### Actual behavior
```
$ r2 -dA /bin/true
...
[0x7f065fe4ec20]> dcu main
Continue until 0x5654d86b15c0 using 1 bpsize
TODO continue
[0x00000000]>
```

### Steps to reproduce the behavior
- Open the binary with `r2 -dA`
- Set a breakpoint with `db` and use `dc` or use `dcu $ADDR`
- r2 fails with message `TODO continue`

### Additional Logs, screenshots, source-code,  configuration dump, ...
Attached follows the zipped Debian default `/bin/true` binary used for testing.
[true.zip](https://github.com/radare/radare2/files/2660684/true.zip)

**Comment by radare** [comment]
NEVER pass flags after -d.. use -Ad if you want to pass -A, but analyzing the code in the dbeugger at startup time is quite silly because it will be analyzing the code in the runtime linker, not the program, which is not yet loaded at this point. so imho is a bad practice to use -Ad

i read your conversation in the chat, and seems like this is a regression. can you point out which version or commit was working ?

thanks

**Comment by davidpolverari** [comment]
The last commit where this worked was on 5df3872b9dbde2b4f18e39560a7523142f1a802d. After bbebd7ed86bce843e42a0108215370f8c56491f6, it stopped working.

**Comment by mug896** [comment]
I have the same  problems debugging does not working any more :(

```
[0x7f700a383090]> db main
[0x7f700a383090]> dc
TODO continue
[0x00000000]> 
```

**Comment by r00tb3** [comment]
I'm facing the same problem with other binaries... pls suggest a solution ASAP.

**Comment by Maijin** [comment]
Apparently it was working before the commit https://github.com/radare/radare2/commit/bbebd7ed86bce843e42a0108215370f8c56491f6, looks like you changed behavior in aaa with pcache @radare

**Comment by Maijin** [comment]
@radare if you check I can add a test after you fix this

**Comment by radare** [comment]
is that thing related to https://github.com/radare/radare2/commit/bbebd7ed86bce843e42a0108215370f8c56491f6
?

**Comment by Maijin** [comment]
Yes see previous messages

**Comment by rebe11ion** [comment]
It works using `aa` only.
```assembly
┌─[root@parrot]─[/home/rebellion/Desktop/Workshop2015-master/IOLI-crackme/bin-linux]
└──╼ #radare2 -d crackme0x06
Process with PID 6867 started...
= attach 6867 6867
bin.baddr 0x08048000
Using 0x8048000
asm.bits 32
glibc.fc_offset = 0x00148
 -- When in doubt, try 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa; pd;'
[0xf7f570b0]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0xf7f570b0]> s main
[0x08048607]> dcu main
Continue until 0x08048607 using 1 bpsize
hit breakpoint at: 8048607
[0x08048607]> pdf
            ;-- main:
            ;-- eip:
┌ (fcn) sym.main 99
│   sym.main (int argc, char **argv, char **envp);
│           ; var int local_78h @ ebp-0x78
│           ; arg int arg_10h @ ebp+0x10
│           ; var int local_4h @ esp+0x4
│           ; DATA XREF from entry0 (0x8048417)
│           0x08048607      55             push ebp
│           0x08048608      89e5           mov ebp, esp
│           0x0804860a      81ec88000000   sub esp, 0x88
│           0x08048610      83e4f0         and esp, 0xfffffff0
│           0x08048613      b800000000     mov eax, 0
│           0x08048618      83c00f         add eax, 0xf
│           0x0804861b      83c00f         add eax, 0xf
│           0x0804861e      c1e804         shr eax, 4
│           0x08048621      c1e004         shl eax, 4
│           0x08048624      29c4           sub esp, eax
│           0x08048626      c70424638704.  mov dword [esp], str.IOLI_Crackme_Level_0x06 ; [0x8048763:4]=0x494c4f49 ; "IOLI Crackme Level 0x06\n"
│           0x0804862d      e886fdffff     call sym.imp.printf         ; int printf(const char *format)
│           0x08048632      c704247c8704.  mov dword [esp], str.Password: ; [0x804877c:4]=0x73736150 ; "Password: "
│           0x08048639      e87afdffff     call sym.imp.printf         ; int printf(const char *format)
│           0x0804863e      8d4588         lea eax, [local_78h]
│           0x08048641      89442404       mov dword [local_4h], eax
│           0x08048645      c70424878704.  mov dword [esp], 0x8048787  ; [0x8048787:4]=0x7325
│           0x0804864c      e847fdffff     call sym.imp.scanf          ; int scanf(const char *format)
│           0x08048651      8b4510         mov eax, dword [arg_10h]    ; [0x10:4]=-1 ; 16
│           0x08048654      89442404       mov dword [local_4h], eax
│           0x08048658      8d4588         lea eax, [local_78h]
│           0x0804865b      890424         mov dword [esp], eax
│           0x0804865e      e825ffffff     call sym.check
│           0x08048663      b800000000     mov eax, 0
│           0x08048668      c9             leave
└           0x08048669      c3             ret
[0x08048607]> 
```

**Comment by Maijin** [comment]
@radare - If I revert the commit then NSO is broken according to your commit message 😕

**Comment by Abr0g4n5** [comment]
I experience the same issue using the same work environment as @davidpolverari . It makes debugging impossible.

**Comment by davidpolverari** [comment]
-dA is working now. Don't know whether bfa3462866670931cb2efe9ae87f57ed2c477063 or 87c837361c7c1ba987c47f99c19c3a1946e60808 solved this issue, but I think this one can be closed. Thanks @radare and @Maijin!
