### ISSUE TITLE
Binvis related improvements

### ISSUE THREAD

**Issue by radare** [radare/radare2#12463]
http://binvis.io/#/

We can achieve the same with  pze and something similiar with p=e, but we have no p-e  (https://github.com/radare/radare2/issues/12461). and the usage is a b it confusing, this issue aims to improve the whole situation of binary visualization techniques in r2.

**Comment by radare** [comment]
Linear-minded

**Comment by radare** [comment]
Ive been thinking in adding a command to search for entropy but /e and /E are taken and /hentropy doesnt seems to work as expected

Also will be good to have a way to autodefine sections depending on the entropy level changes setting flags here and there. That would be useful and easy to do

**Comment by XVilka** [comment]
@radare see also https://github.com/radareorg/cutter/issues/453

**Comment by XVilka** [comment]
@radare also visualizing relative entropy (https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence) might be useful, I found it is useful to reduce the false positives of compressed blobs. See also https://stats.stackexchange.com/questions/78240/interpreting-shannon-entropy and https://en.wikipedia.org/wiki/Maximum_entropy_probability_distribution

**Comment by radare** [comment]
* https://github.com/wapiflapi/binglide

**Comment by radare** [comment]
i implemented prc= which does that
