### ISSUE TITLE
Implement p-e

### ISSUE THREAD

**Issue by radare** [radare/radare2#12461]
This is the same as p- but  showing only  entropy info of each block instead of flags/symbols/functions/comments/strings info. using proper colors maybe we can use fg and bg colors in ansi showing background the permissions of the page and fg for the entropy rainbow

**Comment by oxcabe** [comment]
Fixed in https://github.com/radare/radare2/commit/2bbcfd908c888e466551fb9ca88e21ec990d505d

**Comment by radare** [comment]
Thanks!
