### ISSUE TITLE
rabin2 -qqzzz /bin/ls doesnt work

### ISSUE THREAD

**Issue by radare** [radare/radare2#12474]

**Comment by Maijin** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1408600/49938324-d766d880-fed9-11e8-84f1-6ea84373c0ed.png">
Wut?

**Comment by radare** [comment]
uhm maybe it was the other binary..

i found another issue:

$ rabin2 -qqzzz /bin/ls

**Comment by radare** [comment]
ping @AdamVanScyoc

**Comment by AdamVanScyoc** [comment]
Disregard last commit; still working on it.

**Comment by radare** [comment]
https://github.com/radare/radare2/pull/12653 <-
