### ISSUE TITLE
[PE Binaries] call -> jump creating fcn.* instead of meaningful function name

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#1249]
On some PE binaries http://rghost.net/private/57707106/9b5855273ddd26b6e2b15ea6cabf7ded (malware).

Some analysed `fcn` are in fact a `jmp` to a reloc :

```
    ╒ (fcn) fcn.00405534 6
    │          0x00405534    ff257c224100 jmp dword [reloc.kernel32.dll_Sleep]
```

Creating a lot of meaningful fcn.* that could be renamed according to this reloc.

**Comment by Maijin** [comment]
The Issue is still present

**Comment by radare** [comment]
First sample bin no longer exists

**Comment by Maijin** [comment]
@radare I can't find the binary back unfortunately, I'll provide anothe example and maybe @XVilka has some too. But still there you can see that in the http://rghost.net/private/7cw6Vc4qT/251ca883f01c18bb624289f0b8124937

**Comment by radare** [comment]
I did it with http://rghost.net/private/7cw6Vc4qT/251ca883f01c18bb624289f0b8124937

**Comment by Maijin** [comment]
@radare first function called "fcn.00402ff8" if follow: " jmp dword [sym.imp.kernel32.dll_GetStdHandle]"  http://radare.tv/a/66

**Comment by Maijin** [comment]
AH you need to use "aaa" ok

**Comment by radare** [comment]
Run aaa or .afna@fcn.00402ff8 to get autonamed functions

**Comment by Maijin** [comment]
@radare ok but `aaa` should be the behavior of radare2 -A

**Comment by jvoisin** [comment]
Why aren't we merging `aa` and `aaa` again?

**Comment by Maijin** [comment]
=> https://github.com/radare/radare2/issues/2641

**Comment by radare** [comment]
Not sure. Iiirc aaa is what bokken does by default, so maybe yep. Feel free to send a pullreq, it will probably break a test or two. Anyways i never do -A or aa :p

**Comment by jvoisin** [comment]
But most people do, and expect it to analyze as much as possible.
I might issue a PR tonight if I don't forget about it :dancer:
