### ISSUE TITLE
Mouse clicks trigger seemingly random actions

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#12493]
Using the mouse buttons triggers some sort of shortkey mode in radare2's Visual mode, so pressing a key button after a mouse click triggers seemingly random (to those who are unfamiliar with this functionality) events.

This is particularly frustrating when I try to copy-paste things out of visual mode using the mouse and then later come back to radare2 and trigger a random action on first key press due to r2 still "remembering" my mouse button input.

### Work environment

Linux
xterm/Konsole

### Expected behavior

Using the mouse buttons shouldn't trigger any weird behavior by default.

### Actual behavior

Seemingly random actions are triggered when using a mouse button and then pressing certain keyboard keys.

### Steps to reproduce the behavior 

* radare2 /usr/bin/ls
* Vp
* Left-lick anywhere and press "arrow-up"
* Observe some weird "[VA:0]" thing pop up at the top (instead of just scrolling up by one line)

**Comment by neobrain** [comment]
This issue is actually worse than I thought, since I now found another way to trigger similar behavior, but without using the mouse at all:

* radare2 /usr/bin/ls
* Vp
* /asd
* When prompted for pressing "any key", press "arrow-up"
* Observe some weird "[VA:0]" thing pop up at the top (instead of just exiting the "press any key" prompt)

**Comment by radare** [comment]
e scr.wheel=false

**Comment by neobrain** [comment]
That's a well hidden fix, but it does indeed resolve both issues. Are there any plans on providing more user-friendly defaults for this in the future and/or making this fix more discoverable?

**Comment by radare** [comment]
Of course. You can try to fix it or just wait until someone from r2land have some time to check it out.

We want to have full mouse support but there are some terminal compat issues that must be tested properly but yeah its suposed to improve soon or late

**Comment by neobrain** [comment]
I wish I could dedicate more time to coming up with a fix myself, but for now I'll be eagerly waiting on a fix then :)

Thanks again for the help!

**Comment by radare** [comment]
should be fixed now
