### ISSUE TITLE
Test "? -1" failing.

### ISSUE THREAD

**Issue by GustavoLCR** [radare/radare2#12553]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x64
| File format of the file you reverse (mandatory)      | n.a.
| Architecture/bits of the file (mandatory)            | n.a.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20547 @ linux-x86-64 git.3.1.3-136-g930dfcd11 commit: 930dfcd110c81a7d348ad2b7e86427d15c3aa295 build: 2018-12-24__06:05:11

### Expected behavior
Test succeeds.

### Actual behavior
Test fails as it expects:
`unit    16.0E`
And encounters:
`unit    16E`

### Steps to reproduce the behavior 
run `make tests`

**Comment by radare** [comment]
Fix the test. The current output lgtm

Also this is an issue in r2r, not r2
