### ISSUE TITLE
Invalid characters in output of "pdj" for "bts dword [esp], eax"

### ISSUE THREAD

**Issue by minexew** [radare/radare2#12575]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86 64
| File format of the file you reverse (mandatory)      | PE, flat, doesn't seem to matter
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20537 @ linux-x86-64 git.3.1.3-157-g9889cc27d
commit: 9889cc27dec0bb385cc74caf363d5c316844c432 build: 2018-12-28__10:21:08

### Expected behavior

Disassemble the instruction and return valid JSON, or, if the instruction is invalid, properly signal an error

### Actual behavior

JSON output contains an un-escaped control character which in turn triggers an exception in r2pipe.cmdj when called from Python

### Steps to reproduce the behavior 

```
echo \X0f\Xab\X04\X24 > fail.bin
r2 -q -a x86 -c "pdj 1" fail.bin > fail.json
```

fail.json now contains invalid character \x04 at column 113.

Note that this is from semi-blindly disassembling in the middle of a PE executable; I am not sure if the instruction encoding is actually valid.

**Comment by radare** [comment]
cc @kazarmy

**Comment by kazarmy** [comment]
Repro'd with:
```
echo -e \\x0f\\xab\\x04\\x24 > fail.bin
r2 -q -a x86 -c "pdj 1" fail.bin > fail.json
```
`fail.json` contains:
```
[{"offset":0,"esil":"$0,cf,=,32,eax,%,1,<<,32,eax,/,rsp,+,[4],&,?{,$1,cf,=,},32,eax,%,1,<<,32,eax,/,rsp,+,^D=[124]","refptr":false,"fcn_addr":0,"fcn_last":0,"size":4,"opcode":"bts dword [rsp], eax","disasm":"bts dword [rsp], eax","bytes":"0fab0424","family":"cpu","type":"null","type_num":0,"type2_num":0}]
```

**Comment by kazarmy** [comment]
Repro'd with:

```
echo -e -n \\x0f\\xab\\x04\\x24 > fail.bin
r2 -q -a x86 -c "pdj 1" fail.bin > fail.json
```
fail.json contains:
```
[{"offset":0,"esil":"$0,cf,=,32,eax,%,1,<<,32,eax,/,rsp,+,[4],&,?{,$1,cf,=,},32,eax,%,1,<<,32,eax,/,rsp,+,^D=[124]","refptr":false,"fcn_addr":0,"fcn_last":0,"size":4,"opcode":"bts dword [rsp], eax","disasm":"bts dword [rsp], eax","bytes":"0fab0424","family":"cpu","type":"null","type_num":0,"type2_num":0}]
```

**Comment by kazarmy** [comment]
Repro'd with:

```
echo -e -n \\x0f\\xab\\x04\\x24 > fail.bin
r2 -q -a x86 -b 32 -c "pdj 1" fail.bin > fail.json
```
fail.json contains:
```
[{"offset":0,"esil":"$0,cf,=,32,eax,%,1,<<,32,eax,/,esp,+,[4],&,?{,$1,cf,=,},32,eax,%,1,<<,32,eax,/,esp,+,^D=[124]","refptr":false,"fcn_addr":0,"fcn_last":0,"size":4,"opcode":"bts dword [esp], eax","disasm":"bts dword [esp], eax","bytes":"0fab0424","family":"cpu","type":"null","type_num":0,"type2_num":0}]
```
