### ISSUE TITLE
radare2 cannot debug on macOS 10.14.2

### ISSUE THREAD

**Issue by TrungNguyen1909** [radare/radare2#12587]
*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.14.2
| File format of the file you reverse (mandatory)      | Mach-O
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20626 @ darwin-x86-64 git.3.1.3-168-gd05a11908
commit: d05a119081577e3d6901da34e35a1623220876ca build: 2018-12-30__08:51:31

I try to sign the binary, but It simply doesn't work.
Certificate is trusted in System
I have the same issue with gdb but [this program](http://os-tres.net/blog/2010/02/17/mac-os-x-and-task-for-pid-mach-call/) still works for me after codesign the same way in `makefile macossign`
`codesign -dvvv radare2`
```
codesign -dvvv radare2
Executable=/Users/trung/radare2/binr/radare2/radare2
Identifier=org.radare.radare2
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=643 flags=0x0(none) hashes=13+5 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=96adf2884730664f41f49a440e9eabf5be8d2de9
Hash choices=sha256
CDHash=96adf2884730664f41f49a440e9eabf5be8d2de9
Signature size=1626
Authority=org.radare.radare2
Signed Time=Dec 30, 2018 at 2:56:38 PM
Info.plist entries=6
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=9
Internal requirements count=1 size=96
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
Console log when run
[radare2.log](https://github.com/radare/radare2/files/2717004/radare2.log)

**Comment by radare** [comment]
Did you followed the steps described in the documentarioj to create a certificate to sign the binaries? If you have the aame problem with gdb... does it work with lldb? If not maybe its related to having sip enabled

**Comment by TrungNguyen1909** [comment]
I did followed. Debugging with lldb works OOB. Pretty sure that there shouldn't be any problems with the certificate as I used it to sign the task_for_pid demo provided.

**Comment by radare** [comment]
did  you used sys/install.sh to build and install r2?

**Comment by TrungNguyen1909** [comment]
I did.


> did you used sys/install.sh to build and install r2?
> […](#)

**Comment by TrungNguyen1909** [comment]
by the way, When I start debugging anyway, there was this message:
```
default	17:18:02.635856 +0700	kernel	macOSTaskPolicy: (radare2) (pid: 3694) not (yet) allowed to go invalid
default	17:18:02.635877 +0700	kernel	warning: radare2(3694) performed out-of-band resume on pid 3695
```

**Comment by radare** [comment]
same behavour if you do this as root?

**Comment by TrungNguyen1909** [comment]
Yes

> same behavour if you do this as root?
> […](#)

**Comment by TrungNguyen1909** [comment]
Although I got the messages about not yet allowed to go invalid and out-of-band resume, the debugging seems to work?
ERRR, I figured it out, the issue only occured when use
`r2 -AAd` or `r2 -Ad`
When use `r2 -d`, It seems to works. Sorry.
But I can 
```
#include <stdio.h>
int main(){
	char a[30];
	gets(a);
	puts(a);
}
```
> and you have sip disabled? which program are you trying to debug?
> […](#)

**Comment by radare** [comment]
Thats a known regression in -A. Tracked in a different issue. And its totally unrecommended to use -A and -d together because you probably dont want to analyze the code in ld.so which is what it does

**Comment by TrungNguyen1909** [comment]
At least for now, debugging works when not doing any analysis
> Thats a known regression in -A. Tracked in a different issue. And its totally unrecommended to use -A and -d together because you probably dont want to analyze the code in ld.so which is what it does
> […](#)
> On 30 Dec 2018, at 13:34, TrungNguyen1909 ***@***.***> wrote: Although I got the messages about not yet allowed to go invalid and out-of-band resume, the debugging seems to work? ERRR, I figured it out, the issue only occured when use r2 -AAd or r2 -Ad When use r2 -d, It seems to works. Sorry. But I can #include <stdio.h> int main(){ char a[30]; gets(a); puts(a); } and you have sip disabled? which program are you trying to debug? … — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
