### ISSUE TITLE
Radare2 Disassembly

### ISSUE THREAD

**Issue by valour01** [radare/radare2#12599]
Hi. I am using radare2 to disassembly on ARM binaries.

I use command `radare2 ./target_bin` to load the binary first.

I noticed that radare2 will bring me to the entry point and wait for my coming commands. 
However, what I need is to disassemble all the codes including the .text, .init, .plt and .fini section. I know that using pd N would disassemble N instructions. 

However, how to set the number N? 

Besides, .plt and .init used to have lower address compared with entry point, should I seek to the offset by myself? 

All I want is just like a objdump style disasssembly output. Are there any scripts or commands that could do this automatically using radare2? Many Thanks

**Comment by radare** [comment]
pD $SS @ $S

Please, use the irc/telegram channel for those questions. Also, this is explained in the book and i bet there are many blogposts explaining how to achieve the same
