### ISSUE TITLE
Implement pulling class info from bin to anal

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#12600]
Bin classes, accessible using `ic`, are static info recovered from for example symbol names. They are not editable and provide only a single source for class information.

There should be a command that takes this info and pulls it into anal classes (`aC`), so the classes can be manually edited, enhanced with more information, etc.

**Comment by radare** [comment]
ic*

**Comment by radare** [comment]
i dont see how to specify fields of classes using `ac`. also its not possible to sspecify visibility or other attributes to those methods/fields. see the pr `.ic**`

**Comment by thestr4ng3r** [comment]
Yes. these things are not yet supported. Please open separate issues.
