### ISSUE TITLE
ih should print the hash of the whole bin

### ISSUE THREAD

**Issue by radare** [radare/radare2#12614]
Right now ih ==  iH, and there's no way to get the hash of the bin without running `!rahash2 -a md5 $R2_FILE`, so will be good to alias that with internal r2 apis into the ih command: `ih sha256`

**Comment by XVilka** [comment]
Why not just use `h` namespace then? It is currently unused.

**Comment by radare** [comment]
Right no we have this  info in  file.md5 nd  file.sha256  which dosnt  scale  and its totally  not the  place (eval vars are suposed to be  used as user configuration, not r2 output), moving to 3.3 beacuse thats a breaking change and needs proper discussion/design.

We can probably add bin.hash var with a list of hashes to compute and show them in the   `i` command. but as long as they are related to the file itself, not the bin, we can show them in `oh` : 🤔
