### ISSUE TITLE
[anal][AVR] SBRS+RJMP combo gets partially skipped

### ISSUE THREAD

**Issue by dogtopus** [radare/radare2#12612]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux, x86_64
| File format of the file you reverse (mandatory)      | ELF, ROM
| Architecture/bits of the file (mandatory)            | AVR
| r2 -v full output, **not truncated** (mandatory)     | `radare2 3.2.0-git 20633 @ linux-x86-64 git.3.1.3-194-ge325b3c6d`<br/>`commit: e325b3c6def46f47104b69c55eb5e866cc6d7435 build: 2019-01-02__23:06:25`

### Expected behavior

RJMP behind SBRS gets included in the analyzed function block.

Or
```
"f main 62 0x00000196"
"af+ 0x00000196 main s n"
afc (null) @ 0x00000196
afb+ 0x00000196 0x00000196 16 0x000001a6 0xffffffffffffffff b
afb+ 0x00000196 0x000001a6 8 0x000001ae 0xffffffffffffffff b
afb+ 0x00000196 0x000001ae 6 0x000001c2 0x000001b4 n
afb+ 0x00000196 0x000001b4 2 0x000001b8 0x000001b6 n
afb+ 0x00000196 0x000001b6 2 0x000001be 0xffffffffffffffff n
afb+ 0x00000196 0x000001b8 6 0x000001ae 0xffffffffffffffff n
afb+ 0x00000196 0x000001be 4 0x000001ba 0xffffffffffffffff n
afb+ 0x00000196 0x000001c2 4 0x000001ae 0x000001c6 n
afb+ 0x00000196 0x000001c6 14 0x000001a6 0xffffffffffffffff n
```

### Actual behavior

RJMP behind SBRS and code blocks pointed by the RJMP instruction do not get included in the function block. The function bracket (Not sure what it is called. The line displayed in the leftmost side.) in the disassembly view (`V`) skips these instructions although the instructions themselves still display fine. These instructions also do not get displayed in the flow chart (`VV`) view and `pdf`.

Or
```
"f main 62 0x00000196"
"af+ 0x00000196 main s n"
afc (null) @ 0x00000196
afb+ 0x00000196 0x00000196 16 0x000001a6 0xffffffffffffffff b
afb+ 0x00000196 0x000001a6 8 0x000001ae 0xffffffffffffffff b
afb+ 0x00000196 0x000001ae 6 0x000001c2 0x000001b4 n
afb+ 0x00000196 0x000001b4 2 0x000001b8 0xffffffffffffffff n
afb+ 0x00000196 0x000001b8 6 0x000001ae 0xffffffffffffffff n
afb+ 0x00000196 0x000001c2 4 0x000001ae 0x000001c6 n
afb+ 0x00000196 0x000001c6 14 0x000001a6 0xffffffffffffffff n
```
### Steps to reproduce the behavior 

"Minimal" test file with source code (compiled using Arduino 1.8.8 with gcc-avr 8.2.0):  [sketch_jan02a.zip](https://github.com/radare/radare2/files/2722700/sketch_jan02a.zip)

```
$ r2 -A sketch_jan02a/sketch_jan02a.ino.elf
s main
# instructions show as ...
pdf
# Disassembly view - broken lines
V
# Flowchart - not included in flowchart
V
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

Disassembly view (notice that 0x1be and 0x1b6 are not included in the bracket and show as broken lines)
![disasm](https://user-images.githubusercontent.com/3405234/50622749-222aad80-0ee6-11e9-9789-4c3f2c30712e.png)

The flowchart view (again notice that 0x1be and 0x1b6 never shows up)
![graph](https://user-images.githubusercontent.com/3405234/50622752-2b1b7f00-0ee6-11e9-84e8-dcab90560f34.png)

**Comment by dogtopus** [comment]
Found the problem, already sent a PR.

BTW How do I create a test in r2r for basic-block-related cases like this?

**Comment by radare** [comment]
With the afb command
