### ISSUE TITLE
How to add a new cli command without touching existing code?

### ISSUE THREAD

**Issue by wavvs** [radare/radare2#12611]
The problem is that I want to add a command similar to dcs command without touching existing cmd_debug code. I can't do it with r2pipe, etc. I did't find plugin system for it. Is it intentional decision? Are there any plans for this feature?

**Comment by radare** [comment]
Do a plugin for RCore, see libr/core/p/*, there are some in radare2-extras too.

you can also use the $ command to do an alias and run an r2pipe script with a shorter name
