### ISSUE TITLE
An error during radare2 compilation on Windows10

### ISSUE THREAD

**Issue by Coamoo** [radare/radare2#12627]
Hi,
I'm trying to compilate radare2 on windows and run it under  Visual studio 2017. I did almost everything like int this article https://radare.gitbooks.io/radare2book/content/first_steps/windows_compilation.html and changed only the part with `meson build --buildtype debug --backend vs2015 --prefix %cd%\dest` to `python sys\meson.py --backend vs2017 --project --prefix %CD%\dest`. When i use `msbuild build\radare2.sln /p:Configuration=Debug /m` i've got the following error
```
C:\Users\User\Desktop\radare2\build\radare2.sln.metaproj : error MSB4126: 
The specified solution configuration "Debug|x86" is invalid. 
Please specify a valid solution configuration using the Configuration and Platform 
properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") 
or leave those properties blank to use the default solution configuration. 
[C:\Users\User\Desktop\radare2\build\radare2.sln]
```

When i tried to run radare2.sln in Visual Studio 2017 everything was good until i started debugging. When i pressed the button this error has occured:
```
C:\Users\User\Desktop\radare2\build\shlr\.\libr2capstone.a is not correct Win32 application.
```
Is this a bug? or am i doing smth wrong ?

**Comment by GustavoLCR** [comment]
Inside the radare2 solution you have to select which Project (radare2, rabin2, etc.) to use as the StartUp.
Right click on the project or hover to the Project tab with it open.

You probably will encounter a few .dll missing errors, but a quick and dirty fix is to just copy all dll files in the solution to the folder of the built project.

![sol](https://user-images.githubusercontent.com/23562137/50657797-43d37580-0f76-11e9-90d3-72feecf1de1f.jpg)

**Comment by Coamoo** [comment]
Ok thanks it's working :D
