### ISSUE TITLE
Crash  in bg webserver

### ISSUE THREAD

**Issue by radare** [radare/radare2#12644]
`$ r2 -c'=h&' -cVp /bin/ls`

**Comment by lowlyw** [comment]
cannot repro, close, or push to next milestone?

**Comment by radare** [comment]
build with asan, i can repro  100%

**Comment by radare** [comment]
The problem is that we are relaying on RCons-> values during the execution of a function that should not be allowing other functions to run meanwhile. as long ast he webserver change the global RConsInstance the whole thing gets messed up and a glitch is the least of the problems we can see

**Comment by radare** [comment]
https://github.com/radare/radare2/pull/12683 this  pr is related but not enough

**Comment by radare** [comment]
still not solved, in fact its hanging randomly, other times is crashing, and in the best of luck its glitching
