### ISSUE TITLE
Glitchy visual with bg webserver

### ISSUE THREAD

**Issue by radare** [radare/radare2#12645]
Terminal 1:
```
r2 -e http.verbose=0 -c'=h&' -cV /bin/ls
```

in  anotehr terminal:

```
$ while : ; do curl http://localhost:9090/cmd/T ; done 
```
r2
then t ry t o scrolla round in the visual

**Comment by lowlyw** [comment]
bg webserver is interleaving some output in the r2 console

![image](https://user-images.githubusercontent.com/20349928/50744362-5b5d6900-11d7-11e9-8a2c-2609e1ebc359.png)
left is r2 console, right is curl output

**Comment by radare** [comment]
e http.verbose=false

**Comment by radare** [comment]
Yes this issue was filled by me too two days ago

**Comment by radare** [comment]
yep thats the issue

**Comment by thestr4ng3r** [comment]
The http code is quite scary. To fix this cleanly, there should be task-local temporary eval vars first.

**Comment by radare** [comment]
the http code is not more than 500 LOC and there's an async impl too :P

config vars are dependant on core

**Comment by thestr4ng3r** [comment]
By scary I meant ugly and broken for concurrency.

**Comment by radare** [comment]
i think this is fixed now after your last changes, pls confirm and close @thestr4ng3r

**Comment by thestr4ng3r** [comment]
I think there are still some issues, but I have to re-check.

**Comment by radare** [comment]
i can confirm this is fixed now, at least not anoying or glitchy and its completely usable. thanks
