### ISSUE TITLE
Adjust anal.from/to search.from/to ... depending on a flag

### ISSUE THREAD

**Issue by radare** [radare/radare2#12663]
Add a command or rconfig magic to automatically set the boundaries with 1 line

**Comment by radare** [comment]
cc @brainstorm

**Comment by radare** [comment]
Add anal.in=flagsize or anal.in=flag (to work too with search.in)

**Comment by radare** [comment]
this way we can run a command on all flags and use the flagsize to define boundaries instead of having to change the blocksize all the time

**Comment by brainstorm** [comment]
Isn't `anal.from` & `anal.to` enough? I don't see the need for this one, tbh, it just clogs my radare2 cognitive mental space :_S

**Comment by brainstorm** [comment]
Ahh, sorry, this should go hand-in-hand with the entropy flagging feature? Not sure how those two would combine/work though :/

**Comment by radare** [comment]
related to the @@@ issue 
https://github.com/radare/radare2/issues/13319

**Comment by radare** [comment]
This is done ini r2frida with the .\e/ command

**Comment by radare** [comment]
Solved in https://github.com/radare/radare2/pull/13749
