### ISSUE TITLE
Heap corruption in izzzq~+ with scr.highlight.grep=true

### ISSUE THREAD

**Issue by GustavoLCR** [radare/radare2#12667]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSL Debian x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20676 @ linux-x86-64 git.3.1.3-229-gbd84d0a83 commit: bd84d0a83dde10ffa9724a51f527ede3bbea11a6 build: 2019-01-06__02:27:10

### Expected behavior
The command runs without dying.
### Actual behavior

![tmp](https://user-images.githubusercontent.com/23562137/50732562-442d6580-115c-11e9-9812-83485496ea3c.jpg)

### Steps to reproduce the behavior 
`r2 test.exe`
`e scr.highlight.grep=true`
`izzzq~+t`

### Additional Logs, screenshots, source-code,  configuration dump, ...

[test.zip](https://github.com/radare/radare2/files/2730193/test.zip)

**Comment by enovella** [comment]
Found some memory corruption too https://github.com/radare/radare2/issues/12397#issuecomment-450558691

**Comment by radare** [comment]
i can reproduce

**Comment by radare** [comment]
i have a fix

**Comment by radare** [comment]
Should be fixed in  
https://github.com/radare/radare2/pull/12677
