### ISSUE TITLE
RCons.grep support for ANSI escape sequences

### ISSUE THREAD

**Issue by radare** [radare/radare2#12679]
The RCons grep doesnt plays well with color strings, we must skip the ansi escape chars.

```
e scr.color=3
px~1m
```

**Comment by deepakchethan** [comment]
Is this issue specific to a terminal, I'm unable to reproduce it 
<img width="561" alt="Screen Shot 2019-08-11 at 9 32 17 AM" src="https://user-images.githubusercontent.com/20895544/62829432-02492e00-bc1b-11e9-860a-f788c3e15224.png">

**Comment by radare** [comment]
I think thats only happening with scr.highlight but i have no keybaord to chk here

**Comment by XVilka** [comment]
@radare please provide steps on how to reproduce

**Comment by radare** [comment]
cant repro
