### ISSUE TITLE
ARM aarch64 assemble "b ." ("b 0x0") to wrong  result(00000017)

### ISSUE THREAD

**Issue by SimonTheCoder** [radare/radare2#12691]
**Issue:**
$>rasm2 -a arm -b 64 "b ."
00000017
But the result should be: **00000014**

**Analyze:**
In file:
libr/asm/arch/arm/armass64.c

In function: 
static ut32 branch(ArmOp *op, ut64 addr, int k)

When resolving unconditional branch to current address ("b ."):
(Line: 421):
> 			if (n > addr) { 
> 				n -= addr;
> 			} else {
> 				n -= addr;
> 				n = n & 0xfffffff;
> 				k |= 3;
> 			}

The code dose not resolve  n == addr condition correctly.
**_Should be:_**

> 			if (n >= addr) { 
> 				n -= addr;
> 			} else {
> 				n -= addr;
> 				n = n & 0xfffffff;
> 				k |= 3;
> 			}

**Comment by radare** [comment]
If you have the patch send a pr not open an issue. And if you are lazy to create a branch and such just clicke the pencil button in github

**Comment by radare** [comment]
Also can you submit some tests?

**Comment by SimonTheCoder** [comment]
OK. I will send a pr and submit a test case.

**Comment by radare** [comment]
thanks!
