### ISSUE TITLE
RFE: Implement ax.

### ISSUE THREAD

**Issue by radare** [radare/radare2#12690]
Should be an alias for axt+axf, or just axt?

**Comment by Maijin** [comment]
since it's ax, it should glob everything.

**Comment by radare** [comment]
@Maijin @ITAYC0HEN can you solve this issue?

**Comment by r4dix10** [comment]
So, ax. [addr] should effectively do axt [addr] and axf [addr] ?

**Comment by radare** [comment]
yes, this is just 1 line of code, can someone do this? or should i just commit it? im trying to drop those easy issues public just to allow new people to contribute, but if 1 line takes more than a week to happen im really tempted to close that by myself

**Comment by deepakchethan** [comment]
I will start working on this now.

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
Fixed
