### ISSUE TITLE
RFE: flag priority

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#12704]
**Is your feature request related to a problem? Please describe.**
AFAIK flags do not have any order nor priority right now, so it could happen that a section flag would be retrieved first instead of a symbol one or a string one. Often tests fail as soon as you change a little thing in flags, because flags are stored in a different/random order.

**Describe the solution you'd like**
It would be cool to be able to set the priority of a flag/flagspace programmatically, so that e.g. a section flag would not be the first one for a given offset (we would like to have for example, `entry0` as a very high priority flag, while `section..text` or other possible flags as a lower priority).

**Comment by radare** [comment]
yep, agree, right now those priorities are hrdcoded nd depending on the way the flag is constructed (starts with sym? have a dot?) which is a bit hacky and weak. i would probably go for setting a priority in the flagspaces, to reduce memory and complexity.

**Comment by ret2libc** [comment]
> i would probably go for setting a priority in the flagspaces, to reduce memory and complexity.

I thought the same, though having priority between flags in the same space would be very useful too (e.g. sym.main should have higher priority than sym.XXXX, or sym.YYY defined by user should have higher priority than anything else defined by ourselves)

**Comment by ret2libc** [comment]
@radare I will start by implementing priorities at the RSpace level. However, this means that the spaces defined by radare2 itself (e.g. "symbols", "strings", "functions", "sections", etc.) will have some default priority that needs to be defined somewhere.

Right now spaces are created "on the fly" as soon as some parts of the code calls `r_flag_space_set` or `r_flag_space_push`, however this makes it hard to find a spot where to set the priority of the flag space. I'd like to create those standard flag spaces when RCore is initialized and always make them available, so it will be easier to define priorities for them.

**Comment by radare** [comment]
what about different solution for this? i would like to have some discussion on.

* flags associated to a binfd 
* add visibility bit (show/hide)
* how to handle duplicated flag names

**Comment by ret2libc** [comment]
> what about different solution for this?

Another solution I could think of is to define something like:
```C
RSpace r_core_flagspace_set(RFlag *f, cons char *name) {
     RSpace *s = r_flag_space_get (f, name);
     if (!s) {
           if (!strcmp(name, "symbols") {
                  return r_flag_space_set_prio (f, name, SYMBOLS_DEFAULT_PRIO);
           } else if (!strcmp(name, "functions") {
                  return r_flag_space_set_prio (f, name, FUNCTIONS_DEFAULT_PRIO);
           } else if (!strcmp(name, "sections") {
                  return r_flag_space_set_prio (f, name, SECTIONS_DEFAULT_PRIO);
           } else if ....
...
     }
     r_flag_space_set (f, name);
}
```

And use this function instead of directly calling `r_flag_space_set` in RCore, so that we have one place where to define the priority.

> i would like to have some discussion on.
> * flags associated to a binfd
> * add visibility bit (show/hide)
> * how to handle duplicated flag names

Though interesting discussions, I think they are not related at all to this change.

**Comment by ret2libc** [comment]
Ongoing work at https://github.com/radare/radare2/pull/13138

**Comment by ret2libc** [comment]
PR has been merged, this is live! Not perfect yet, but we'll see how it goes.
