### ISSUE TITLE
pxa flag position on hex.compact is incorrect

### ISSUE THREAD

**Issue by radare** [radare/radare2#12711]

**Comment by radare** [comment]
having the flags pointing at the right byte basically, did you tried it?

**Comment by r4dix10** [comment]
greped repo for 'hex.compact' instances.
I did:
s sym.main
pxa

it prints hexdump, works fine.

not sure what is meant by <flags pointing at the right byte> ?

**Comment by r4dix10** [comment]
does "pointing at the right byte" mean; for a string in binary such as "abcd" when sym.main is pxa(ed) the it points at 61 as a start of the string ?

**Comment by radare** [comment]
wat 61, the "patata" thing is not a string, its a flag, and it points to the byte 0x89, the compact variable is the one that handles this extra spacing. The code you have to look is at libr/util/print.c in the hexdump() function. The fix is just 1 line (an extra if with that compact variable)

**Comment by r4dix10** [comment]
"The code you have to look is at libr/util/print.c in the hexdump() function. "

I looked through libr/util/print.c and found r_print_hexdump ().

How to figure this piece of info in future I mean I skimmed through the switch case of pxa (in libr/core/cmd_print.c line 5251) and it just calls annotated_hexdump() which nowhere makes any call to r_print_hexdump(). Although there were calls to r_print_hexdump in other switch cases, but the pxa case breaks out of switch after calling annotated_hexdump().

by the "patata" thing you mean hex.compact ?
what is the "patata" thing ? and what is the significance of pointing to 0x89 ?

**Comment by radare** [comment]
test case:

```
f patata @ 8
pxa
e hex.compact=1
pxa
```

**Comment by radare** [comment]
i have fixed the thing because it seems like we should be spending too much time describing the issue. it's probably easier to just see the fix so you can understand the problem and how its fixed.

Do you want to submit a test for r2r?

**Comment by r4dix10** [comment]
"Do you want to submit a test for r2r?"

Of course anything.

**Comment by radare** [comment]
Anything?
