### ISSUE TITLE
afi should display if the function has been executed or not

### ISSUE THREAD

**Issue by radare** [radare/radare2#12738]
we have trace information at instruction level using the `dt` command. but will be good to have this info available in `afll` for grepping /sorting/coloring those who have been executed during an emulation/run.

**Comment by r4dix10** [comment]
so, afi should have a "function execution state" attribute. which would cover 3 cases namely:

Executed n : where n represents number of times a function has been executed.
case 1: n = 0: never executed.
case 2: n > 0: executed n times.
case 3: n < 0: in execution (if a breakpoint is set and a function is stopped at some point in execution.)

**Comment by Maijin** [comment]
Well case 3 can also contain several execution though :/ so maybe could have something like.
Executed: 3 (current) to be discussed

**Comment by r4dix10** [comment]
@Maijin yeah that makes more sense.

**Comment by r4dix10** [comment]
trace info would be taken from dt so, if dbg.trace is not set then afi should display:
function execution state: (set dbg.trace)

**Comment by Maijin** [comment]
I'd just hide it completly when not in use, @radare thoughts?

**Comment by radare** [comment]
that will make listing faster because i think that the tracing info shouldnt be updated in the function info, a quick impl can be a r_anal_get_function_coverage() tha iterates over all the basic blocks, and for each basic block checks if each instruction is being traced or not, and compute a % of coverage for it. this will be "slow", but correct and we shouldnt be querying this info all the time. we can think in future optimizations later.

**Comment by r4dix10** [comment]
below queries are not related to last 2-3 comments, they concern the implementation approach:

only if a function is being traced can we tell if a function has been executed or not. is this correct ?
so while dbg.trace is 0, and function xyz is executed. we won't count that. does this make sense ?

**Comment by radare** [comment]
nope. the tracing is at instruction level. it doesnt cares about analysis information at all, its detached

**Comment by r4dix10** [comment]
> nope. the tracing is at instruction level. it doesnt cares about analysis information at all, its detached

yeah tracing doesn't care about analysis.

below is what we want to achieve:
>**afi** should have a "function execution state" attribute. which would cover 3 cases namely:

>Executed n : where n represents number of times a function has been executed.
>case 1: n = 0: never executed.
>case 2: n > 0: executed n times.
>case 3: n < 0: in execution (if a breakpoint is set and a function is stopped at some point in execution.)


now i mean to ask that in order to determine if a function has been executed it must be being traced ? so that we can get info from "dt". is that correct ?

if the above is correct then if a function is not being traced and is executed how can we know about that ?

**Comment by radare** [comment]
If a function is executed the first insteuction should be enough to check that unless the execution flow is not standard :p

**Comment by r4dix10** [comment]
a little elaboration on how "the first instruction should be enough" to check if function is executed or not ?

**Comment by radare** [comment]
what else do you need to know? all functions have a single entrypoint, so just chk if the first instruction has been traced and say so in the afi output. this should be faster, so i dont see it as a real issue, but the coverage thing is the problem because it requires chking the tracing info for all the instructions in a function
