### ISSUE TITLE
afvn args should be swapped imho

### ISSUE THREAD

**Issue by radare** [radare/radare2#12737]
![image 2019-01-10 19 31 10](https://user-images.githubusercontent.com/917142/50988913-4aca2d00-150e-11e9-95e1-db2277748d2e.jpg)

...

![image 2019-01-10 19 31 19](https://user-images.githubusercontent.com/917142/50988915-4f8ee100-150e-11e9-968d-1e48a68d9628.jpg)

**Comment by sivaramaaa** [comment]
Okk will do it, but it was like that only before until someone in twitter asked about it and u guys decided to change the syntax , so that it would be consistent with function renaming syntax !

**Comment by radare** [comment]
Uhm i think the reaosn was for consistency with other commands that work with 1 arg.

Do afvn work if u r on an insteuction using a specific var?

🤔

**Comment by sivaramaaa** [comment]
Yup same question arised that time too :) and afair the afvn work with one arg it tries to rename the var at curseek

**Comment by radare** [comment]
Ok then lets keep it like this. We can also fallback to make the command work with any order of aeguments xD
