### ISSUE TITLE
`af @@ sym.*` much slower than `aa`

### ISSUE THREAD

**Issue by kieran-lemayai** [radare/radare2#12740]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM 32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20539 @ linux-x86-64 git.3.1.3-191-g31c3750 commit: 31c37508278475088e1fe8c5932d69770149f22e build: 2019-01-02__14:02:23

### Expected behavior

According to the docs and `aa?`, `aa` is an alias for `af@@ sym.*;af@entry0;afva`. Accordingly, only running a part of that (`af @@ sym.*`) should take less time.

### Actual behavior

On my machine, it takes under two seconds to execute `aa`, but over 24 to execute `af @@ sym.*`, for the attached binary file. The issue is reproducible on a number of other binary files; seems to be more pronounced the longer the file is. Is this an error in the docs?

### Steps to reproduce the behavior

Binary for analysis:
[irc-server.o.tar.gz](https://github.com/radare/radare2/files/2746836/irc-server.o.tar.gz)

Speedtest script using r2pipe and Python:
[test_aa.py.tar.gz](https://github.com/radare/radare2/files/2746846/test_aa.py.tar.gz)

**Comment by Maijin** [comment]
You can use aF @@ sym.* to have the same speed as aa.

**Comment by kieran-lemayai** [comment]
I see, so by default aa uses anal.depth=1. Problem solved, thanks! Help pages should probably be updated, though.

**Comment by Maijin** [comment]
Can you send a Pull-request for that? You can use the github pencil

**Comment by Maijin** [comment]
You can use github edit button - https://help.github.com/articles/editing-files-in-your-repository/
