### ISSUE TITLE
RFE: show file-format specific details

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#12746]
**Is your feature request related to a problem? Please describe.**
I often go back to readelf just because it shows info that are not displayed in radare2, mainly because radare2 tries to generalize things for all file formats and in the process we lose some detail that sometimes are important.

**Describe the solution you'd like**
A command under `i` to show the details for the particular file format, in case the bin plugin allows it.

**Describe alternatives you've considered**
Use readelf.

**Comment by radare** [comment]
use iH and improve it because its a known thing

**Comment by Maijin** [comment]
What needs to be done in ih is described here - https://github.com/radare/radare2/issues/4530.
see `ih` must be simplified to use `pf.`

**Comment by ret2libc** [comment]
Ah ok, thanks!
