### ISSUE TITLE
Structure offset is not autorecognized in the SUB instruction register offset

### ISSUE THREAD

**Issue by d-we** [radare/radare2#12750]
**Is your feature request related to a problem? Please describe.**
When e.g. structs or pointers are hold in registers for a long time, I would find it helpful if i could annotate this using the registers name. E.g. renaming "rbx" to "important_struct_ptr" for a specific part of the binary.

**Describe the solution you'd like**
A command, which takes 2 addresses (start, end of annotation range), the register name and the new name, would be great.

**Describe alternatives you've considered**
If there is any other clever way to annotate such things, which not involves commenting every line by hand, please let me know.

**Comment by radare** [comment]
This is not register renaming. Its binding a variable into a register or a memory address. This way the disassembly understands the meaning of those registers

**Comment by radare** [comment]
Use types

Cc @sivaramaa

**Comment by Maijin** [comment]
@sivaramaaa

**Comment by d-we** [comment]
Hey @sivaramaaa,
this sounds great and I tried it, but I can not reproduce it. 
When I enter 
`afvr rdi important_struct_ptr`
 nothing changes in the disassembly view.

**Comment by sivaramaaa** [comment]
Hey hi , can u paste the output before and after executing the command ?

**Comment by Maijin** [comment]
and also please provide the output r2 -v

**Comment by d-we** [comment]
![r2_01](https://user-images.githubusercontent.com/31281970/51340256-b3755480-1a8e-11e9-8ed0-a58dca653fdf.png)
after entering: `afvr rdi important_struct`
![r2_02](https://user-images.githubusercontent.com/31281970/51340259-b4a68180-1a8e-11e9-988b-0040927cf22a.png)



```
$ r2 -v  
radare2 3.3.0-git 20812 @ linux-x86-64 git.3.2.1-100-gc3bf8d161
commit: c3bf8d161b4835e59d7923aafe6d44de3b5234d0 build: 2019-01-17__19:13:08

```

**Comment by sivaramaaa** [comment]
hey @d-we , sorry my bad 1'st method won't work u won't be able to rename the register in disassembly yet!

But u can try the second method i suggested i.e linking the struct to address (try to emulate until ur desired instruction which contains `rdi` register, from pic i could suggest until address `0x401236` and fetch rdi value) and follow below instruction

```
to def.h  // load the struct 
tl addr = 0xdeadbeef //  link ur struct to an address
```

**Comment by d-we** [comment]
hey @sivaramaaa for some instructions this seems to work in a nice way, but it does not work on some instructions (e.g. 'sub'):
![r2](https://user-images.githubusercontent.com/31281970/52351688-8bdd3080-2a2b-11e9-8c28-089ae8808c1e.png)

I annotated both structs in the same way using `tl _person = $(aes rdi)` and `tl _person = $(aes rsi)`

For this small example I initialized the ESIL VM at the start of the main. But how do I handle this for larger binaries? When I just initialize the ESIL VM at the start of the function, where I want to annotate things, this results in wrongs results. When I initialize it right infront of the arguments being moved to the argument-registers the results are not 100% correctly either. At which point to I need to start emulating to get this annotation right?

**Comment by radare** [comment]
anal hints can be used to change the disassembly of any string, but this is too low level to solve this problem, but will be good to have some regex that apply to a range

**Comment by XVilka** [comment]
It is just missing the immediate analysis in SUB instruction, not the interface issue

**Comment by XVilka** [comment]
I need an example - if you have it

**Comment by radare** [comment]
@XVilka can we merge this ? there are a bunch of failing tests that i guess they are fine

**Comment by XVilka** [comment]
No, needs more testing, let's keep it for 3.7.1
