### ISSUE TITLE
Remove verbosity information and Warnings on analysis

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#12767]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | Latest

Currently, when analyzing binaries, radare2 could output tons of information to the console. The user is flooded with information they can't\won't really do something with. This is scary and can cause the user to feel that the tool is buggy.

This information should be removed from the console and if you want to keep it, it should be enabled by a Verbosity flag or to be logged into a log file.

**Example unique outputs:**

```
WARNING: r_io_pread_at: assertion 'io && buf && len > 0' failed (line 273)
WARNING: r_anal_fcn_cc: assertion 'result > 0' failed (line 2039)
Warning: invalid bb jump/fail pair at ...
Task 1 finished
Task 2 finished
WARNING: r_io_pread_at: assertion 'io && buf && len > 0' failed (line 273)
No virtual tables found
Invalid instruction of X bytes at Y

````

**Screenshots:**

![image](https://user-images.githubusercontent.com/20182642/51087013-6cb5f080-1756-11e9-8ef3-bf2e75d4ebeb.png)

---

![image](https://user-images.githubusercontent.com/20182642/51087085-22813f00-1757-11e9-8bae-454e5afbdba6.png)

---

![image](https://user-images.githubusercontent.com/20182642/51097995-f1455500-17d0-11e9-821b-40f83fb59de5.png)

**Comment by Maijin** [comment]
Those are my thoughts on this:

* Asserts are rare and should be reported by the users on the tracker so I would not removed those, maybe added a better disclaimer and standardize the output. "warning/Warning/WARNING -> should only be one"
* For anal.jmptbl, we should display it one time with a more meaningful description and allow the vebosity to be changed in an eval and a way for the user to report the given case (a la `pddi`)
* For truncated instruction same and allow the vebosity to be changed in an eval.

**Comment by radare** [comment]
which bin

**Comment by radare** [comment]
imho we are fine for now on having such warnings because they must be addressed or improved, so its not something we can fix in 1 week

**Comment by radare** [comment]
Should be improved now, but those bbjmp things are false positives or lack of support for specific jump tables, so please provide the binary like i asked for a month ago. Otherwise i cant determine if thats a bug or not.. also i added anal.verbose to hide those

**Comment by radare** [comment]
i think we are done with this if not just ping me again
