### ISSUE TITLE
Rethink the support for multiple decompilers

### ISSUE THREAD

**Issue by radare** [radare/radare2#12772]
We need to define an API to work with the decompilers, this way we can have the following features:

* [ ] cache the results, faster decompilation times
* [ ] query by function name + line -> addr
* [ ] simpler generic commands to use instead of hooking the RCore.cmd

Decompiler plugins can be also 'weak'. this is.. we just define which command to call and define subcommands that modify its behaviour. for example right now we have pdc and pdd, and we can setup an external decompiler using the e cmd.pdc to overwrite the behaviour of pdc.. which is a bit hacky but works for now. we should have pdc call the selected decompiler and cache the results.

**Comment by rfc2119** [comment]
For API definition, we need to know decompiler commands people use. The most common ones I am thinking of (and the ones I regularly use)
| function | desc |
| -----------|--------|
|decompile function| decompiler runs its own analysis/passes and spits out high-level code|
|decompile function recursively| self-explanatory|

A couple of additional points:
* every decompiler has options  and modifiers (retdec has many that I am ignorant of). This could specified in, say `pdd.opts` and passed to the decompiler
* I don't know if every decompiler is like r2dec in the sense of using all user-defined flags/comments/hints, but enabling user-defined stuff to decompilers would be a plus

**Comment by radare** [comment]
cutter will benefit from this too, so comments frmo cutterland are welcome too :)

**Comment by rfc2119** [comment]
> Related (for retdec):
> 
> * https://hackmd.io/pyBoYdQLTvi-jisaKrgu7Q#
> * https://github.com/PeterMatula/r2-retdec

[https://github.com/securisec/r2retdec](r2retdec) already does this in node, what's the difference ?

**Comment by radare** [comment]
One is online and the other offline

**Comment by rfc2119** [comment]
unless I am missing something, both require retdec to be installed locally. Perhaps the major difference would be in exporting more information to retdec

**Comment by radare** [comment]
Nope. Unless we are talking about different thingns. There r two retdec plugins for r2 afaik:

* local (requires retdec local install)
* remote (requires token key..)

**Comment by radare** [comment]
related 
https://github.com/radare/radare2/issues/13462

**Comment by radare** [comment]
```
[0x1000011e8]> e cmd.pdc=`e cmd.pdc=?~:3`
[0x1000011e8]> e cmd.pdc
#!pipe r2ghidra
[0x1000011e8]> e cmd.pdc=?
r2dec
pdc
#!pipe r2retdec
#!pipe r2ghidra
[0x1000011e8]>
```

**Comment by radare** [comment]
@Vane11ope can we have a menu to select the default decompiler in panels?

**Comment by radare** [comment]
all this stuff is ready in panels <3 and can be solved with commands and such, not in visual though
