### ISSUE TITLE
Wrong pe x86 detection

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#12781]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | pe x86
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20776 @ darwin-x86-64 git.3.2.0-72-gea92c06e1 commit: ea92c06e1ac1df8ce7e087ab392cb6a1bc5bebbc build: 2019-01-14__14:42:50

### Actual behavior
```
r2 ~/Downloads/xul.dll
WARNING: Plugin bios should implement load_buffer method instead of load_bytes.
 -- ESIL: The Aftersleep
[f000:fff0]> i
blksz    0x0
block    0x100
fd       3
file    ~/Downloads/xul.dll
format   bios
iorw     false
mode     r-x
size     0x2464ea8
humansz  36.4M
type     bios
arch     x86
```

### Steps to reproduce the behavior 
```
r2 xul.dll
```

This file is a library from old version of Firefox x86.

### Additional Logs, screenshots, source-code,  configuration dump, ...

[xul.dll.zip](https://github.com/radare/radare2/files/2755607/xul.dll.zip)

```
$ file ~/Downloads/xul.dll
xul.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```

**Comment by dukebarman** [comment]
It works. Thanks! Maybe should create the test?

**Comment by Maijin** [comment]
If you have a small sample sure 👍

**Comment by dukebarman** [comment]
Nope :( Only this sample
