### ISSUE TITLE
R2 immense slowdown using cmd.cprompt: dmhg

### ISSUE THREAD

**Issue by d-we** [radare/radare2#12792]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux, 64 bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20772 @ linux-x86-64 git.3.2.0-78-g57e63d8f8 commit: 57e63d8f8297f015f6915fb11036641d9c5e878c build: 2019-01-15__10:50:28

### Expected behavior
When using cmd.cprompt with "dmhg @ <main_arena_addr>" in visual-mode the debugger was not slowed down before.

### Actual behavior
r2 will slow down immense, hence the visual-mode is almost unusable.

### Steps to reproduce the behavior 
1: open the following binary in debug-mode: [r2_heap.gz](https://github.com/radare/radare2/files/2759166/r2_heap.gz)

2: enter 'dcu 0x401161'
3: enter 'dmha' and copy the addr of main_arena (referred as <main_arena>)
4: enter 'v'
5: enter ' "e cmd.cprompt = dmhg @ <main_arena>" ' 
6: r2 should be slow downed now

**Comment by radare** [comment]
Thats expected. Dmhg is a slow command

**Comment by d-we** [comment]
I was not aware of that, because in the past in was way faster. Closing this.

**Comment by radare** [comment]
well, we can improve on that, in fact, part of the visual gadgets feature aims to support running tasks in background and showing the results when ready in a frame anywhere in the screen and we can make dmh run faster too
