### ISSUE TITLE
Exports not seen

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#12800]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32, 64 etc.
| r2 -v full output, **not truncated** (mandatory)     | rabin2 3.3.0-git 20686 @ linux-x86-64 git.3.2.0-41-g2f0b73d64
commit: 2f0b73d649e9ffbb7c4f639663d3cb0515b338d1 build: 2019-01-11__08:51:02

### Expected behavior
Show all exports

### Actual behavior
No exports shown

### Steps to reproduce the behavior 
rabin2 -E report.dll

### Additional Logs, screenshots, source-code,  configuration dump, ...
I use pecheck and peframe.  Both these apps show the export information from the dll:

pecheck
~~~
[IMAGE_EXPORT_DIRECTORY]
0x60608    0x0   Characteristics:               0x0       
0x6060C    0x4   TimeDateStamp:                 0x0        [Thu Jan  1 00:00:00 1970 UTC]
0x60610    0x8   MajorVersion:                  0x0       
0x60612    0xA   MinorVersion:                  0x0       
0x60614    0xC   Name:                          0x198050  
0x60618    0x10  Base:                          0x1       
0x6061C    0x14  NumberOfFunctions:             0x4       
0x60620    0x18  NumberOfNames:                 0x4       
0x60624    0x1C  AddressOfFunctions:            0x1C3448  
0x60628    0x20  AddressOfNames:                0x1C3438  
0x6062C    0x24  AddressOfNameOrdinals:         0x1C3430  

Ordinal      RVA         Name
3          0x0005FE2Ch    TMethodImplementationIntercept
2          0x000108E4h    __dbk_fcall_wrapper
4          0x001824C8h    bogus
1          0x00192640h    dbkFCallWrapperAddr
~~~

peframe
~~~
Export function
------------------------------------------------------------
TMethodImplemen 0x45fe2c
__dbk_fcall_wra 0x4108e4
bogus           0x5824c8
dbkFCallWrapper 0x592640
~~~

hash on the file is d1d00cd0a395179659bf91932f65d7adbff2a47832d9cce7f0132b5033b9d503.  Thank you.

**Comment by radare** [comment]
he provided the hash, thats fine

**Comment by Maijin** [comment]
@koffiedrinker if you want the file let me know I can forward it to you on telegram as it's malicious binary.

**Comment by SonsOfMyra** [comment]
Hi, the problem is into /libr/bin/format/pe/pe.c:2683 when export are processed if dll name cant be retrieved the function exit without extract export names.

To solve we need set dllname to null and continue.

here is a diff:
[fix_exports.diff.txt](https://github.com/radare/radare2/files/2864944/fix_exports.diff.txt)

**Comment by sanguinawer** [comment]
Hi, the problem is into /libr/bin/format/pe/pe.c:2683 when export are processed if dll name cant be retrieved the function exit without extract export names.

To solve we need set dllname to null and continue.

here is a diff:
[fix_exports.diff.txt](https://github.com/radare/radare2/files/2864944/fix_exports.diff.txt)

**Comment by DigiAngel** [comment]
Worked wonderfully:
~~~
Warning: read (dll name)
[Exports]
Num Paddr      Vaddr      Bind     Type Size Name
000 0x00191a40 0x00592640 GLOBAL   FUNC    0 _dbkFCallWrapperAddr
001 0x0000fce4 0x004108e4 GLOBAL   FUNC    0 ___dbk_fcall_wrapper
002 0x0005f22c 0x0045fe2c GLOBAL   FUNC    0 _TMethodImplementationIntercept
003 0x001818c8 0x005824c8 GLOBAL   FUNC    0 _bogus
~~~
Thank you!
