### ISSUE TITLE
r_bin_file_at()

### ISSUE THREAD

**Issue by radare** [radare/radare2#12813]
make this new api to return which binobj is mapped in a specific memory address. this is useful when many binfiles are loaded..lets call them binobj maybe? @ret2libc pls dont loose the focus on rbin, and let's finish discussing all those things

**Comment by ret2libc** [comment]
there may be more than one binobj in a specific memory address though, is that right?

**Comment by radare** [comment]
Yes its expected. I would allow to define a prio like its done in siol. But for most siutations that will work fine because the bins may be loaded on non overlapping addresses

**Comment by radare** [comment]
So my idea is to have a list of rbinobj, the user can pick one to query or use as default

**Comment by radare** [comment]
This is implemented in master
