### ISSUE TITLE
Registers not loading properly when analyzing N64 rom

### ISSUE THREAD

**Issue by Boigahs** [radare/radare2#12837]
### Work environment
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Funtoo x86-64
| File format of the file you reverse (mandatory)      | N64 Rom (.z64)
| Architecture/bits of the file (mandatory)            | MIPS, Not entirely sure (see below
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20610 @ linux-x86-64 git.3.2.1-100-gc3bf8d161 commit: c3bf8d161b4835e59d7923aafe6d44de3b5234d0 build: 2019-01-18__16:08:01

### Expected behavior
```
[0x80000400]> dr
zero = 0x00000000
at = 0x00000000
v0 = 0x00000000
v1 = 0x00000000
a0 = 0x00000000
a1 = 0x00000000
a2 = 0x00000000
a3 = 0x00000000
t0 = 0x00000000
t1 = 0x00000000
t2 = 0x00000000
t3 = 0x00000000
t4 = 0x00000000
t5 = 0x00000000
t6 = 0x00000000
t7 = 0x00000000
s0 = 0x00000000
s1 = 0x00000000
s2 = 0x00000000
s3 = 0x00000000
s4 = 0x00000000
s5 = 0x00000000
s6 = 0x00000000
s7 = 0x00000000
t8 = 0x00000000
t9 = 0x00000000
k0 = 0x00000000
k1 = 0x00000000
gp = 0x00000000
sp = 0x00000000
fp = 0x00000000
ra = 0x00000000
pc = 0x80000400
t = 0x00000000
```
### Actual behavior
```
[0x80000400]> dr
hi = 0x00000000
lo = 0x00000000
```
### Steps to reproduce the behavior 
Load an n64 rom, type dr

### Additional Logs, screenshots, source-code,  configuration dump, ...
I've tracked the issue down to this commit 3adf272f6da85ad32b6fe8e364dc22582b05730e
Reverting this change fixes the issue, but he does sort of have a point, so I am not sure if simply undoing it is the correct solution.

**Comment by radare** [comment]
Type dr 32

**Comment by Maijin** [comment]
See the file https://github.com/radare/radare2/blob/master/libr/anal/p/anal_mips_cs.c#L1061 feel free to send a Pull-request with the suggested fixes 👍

**Comment by Maijin** [comment]
See model here for changing the bits https://github.com/radare/radare2/blob/master/libr/anal/p/anal_x86_cs.c#L2859
