### ISSUE TITLE
Segfault on Set debugger handler

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#12855]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux 64bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 64
| r2 -v full output, **not truncated** (mandatory)     | rradare2 3.3.0-git 20779 @ linux-x86-64 git.3.2.1-91-gadab5e430
commit: adab5e43023ac75066fc14e6c37b8895d4bb2597 build: 2019-01-17__09:09:53

### Expected behavior
Debugger handler should be set

### Actual behavior
**Segfault**

![image](https://user-images.githubusercontent.com/20182642/51441067-65eb2880-1cd6-11e9-8d4b-92b40da8ae9a.png)

### Steps to reproduce the behavior 

```
$ r2 -d ls
...
...
asm.bits 64
 -- I'm in your source securing your bits.

[0x7f6900966000]> dL bf
Segmentation fault (core dumped)

```

**Comment by mkopec3** [comment]
`dL bochs` also causes segfault. 
I will investigate it more when I will have some spare time

**Comment by radare** [comment]
tired of waiting, the fix is in here https://github.com/radare/radare2/pull/13145
