### ISSUE TITLE
Improve ragg2

### ISSUE THREAD

**Issue by radare** [radare/radare2#12862]
* [x] ragg2 -S string -> to append a string into the buffer
* [x] rax2 -S "hello\x00world" -> \x00 is literally translated, we should probably escape the input

More suggestions are welcome

**Comment by Maijin** [comment]
Yep - `binr/ragg2.c`

**Comment by ret2libc** [comment]
`rax2 -S "hello\x00world" -> \x00 is literally translated, we should probably escape the input` fixed with with https://github.com/radare/radare2/commit/be654b89d33676ff079177e6d74c48364c68a384

**Comment by deepakchethan** [comment]
Append string feature for ragg2 is added too. with #13007. This issue can be closed.

**Comment by Maijin** [comment]
thanks

**Comment by Maijin** [comment]
There are more ragg2 issues - https://github.com/radare/radare2/labels/ragg2 and more rax2 issues https://github.com/radare/radare2/labels/rax2
