### ISSUE TITLE
Improve default theme colors

### ISSUE THREAD

**Issue by radare** [radare/radare2#12873]
i always use a theme lately, and it was not like this a while ago, so this may mean that the default colors are not good anymore

<img width="904" alt="screenshot 2019-01-22 at 11 15 30" src="https://user-images.githubusercontent.com/917142/51528494-18d29800-1e37-11e9-83ed-e1d24750f21f.png">

**Comment by wargio** [comment]
maybe we should just switch to another one.

**Comment by crowell** [comment]
i vote for zenburn

**Comment by XVilka** [comment]
Well, almost all terminals now support 256 colors and even 16M colors: https://gist.github.com/XVilka/8346728

If some terminal doesn't - it is probably a very small fraction of user base, that can choose another, simpler theme.

**Comment by ITAYC0HEN** [comment]
Can we have a fallback theme in case where the terminal only supports basic ANSI?

**Comment by radare** [comment]
Linux tty does not

**Comment by radare** [comment]
i think is fine to close this issue, we are improving themes from time to time and there's no need to handle that in here, just to get some feedback
