### ISSUE TITLE
Parse Rich header

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#12889]
**Is your feature request related to a problem? Please describe.**
Ability to output the Rich Header from PE File with ih or iH and the json output for Cutter

**Additional context**

The Rich header is an undocumented structure that appears in most of the PE files generated with the ‘LINK.EXE’ tool by Microsoft.

Here are some example of implementation/documentation:

* https://securelist.com/the-devils-in-the-rich-header/84348/
* https://github.com/voidm4p/unformbook/blob/master/perichheaderparser.py

**Comment by Maijin** [comment]
ping @koffiedrinker

**Comment by koffiedrinker** [comment]
I'll check it out.

**Comment by Maijin** [comment]
More recent one https://github.com/RichHeaderResearch/RichPE

**Comment by Maijin** [comment]
ping @koffiedrinker o/
