### ISSUE TITLE
Improvements of iS//iSj

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#1289]
- [x]  Add `vsz` and `idx` in iSj
- [x]  Get Sections Entropy in iS/iSj
- [x]  Get Sections md5/sha1 in iS/iSj
- [x]  Possibility to do rabin2 -K entropy,md5,sha1 -jS $FILE // To get both md5,sha1 and entropy in the same command

-----

- [ ]  Get those informations on the Web-UI

It could be nice to get common hashing of Sections (md5,sha1) with or without an option in `iS` and `iSj` as well as entropy to quickly compare malicious Sections and quickly see if a Section is packed like already existing tools/website (VirusTotal, AVCaesar...)

**VirusTotal**

![pe_section_vt](https://cloud.githubusercontent.com/assets/1408600/4153691/4d9113fc-345b-11e4-8fde-d643bdd6d2d8.png)

**AVCaesar**

![pe_section_avcaesar](https://cloud.githubusercontent.com/assets/1408600/4153698/60e03816-345b-11e4-93d0-18ad6eb6ac30.png)

**Comment by alvarofe** [comment]
Only remains the webui

**Comment by radare** [comment]
Also, add an option to disable hashing this, or try it with a big binary or invalid section information.

**Comment by alvarofe** [comment]
iS doesn't hash nothing by the default, it's the same as before. You have to specify the algorithm to use. I'll try with fuzzed binaries from r2r

**Comment by radare** [comment]
Everything is done now, right? can we close this issue?
