### ISSUE TITLE
call <reg>/jmp <reg>

### ISSUE THREAD

**Issue by condret** [radare/radare2#1290]
Does the debugger track values of 'reg' every time, when `call reg` or `jmp reg` is executed?

if not, we should implement this for debugging and esil-emulation.

**Comment by radare** [comment]
skuater will work on that, must be ready for the release. If not, i'll do it, its quite simple/quick to do.

* log in sdb like we do with sdb traces the destination address on every RAnalOp.type= UJMP || UCALL
* Show the values in disasm.c with an autocomment somehow

**Comment by radare** [comment]
right now, esil tracks this if you enable asm.emu=true for debugging, for the debugger this can be implemented with `:> "dbc 0x7fff5fc0104e CC `?v rax`"`
