### ISSUE TITLE
Arrow keys on visual text insert mode insert hjkl instead of moving around

### ISSUE THREAD

**Issue by BlaCoiso** [radare/radare2#12921]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows/x86/64
| File format of the file you reverse (mandatory)      | none
| Architecture/bits of the file (mandatory)            | none
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20935 @ windows-x86-64 git.3.2.1-187-g168299ba0 commit: 168299ba0f9c0eeb3ee0ec9ad5cbca37c911847c build: 26/01/2019__19:09:11,93
### Expected behavior
Arrow keys can be used to move around on the visual hex editor, text mode (`Vi`)
### Actual behavior
Arrow keys just insert hjkl
### Steps to reproduce the behavior 
`r2 -cVi -`
Press [tab] twice to select the ASCII mode
Press arrow keys
### Additional Logs, screenshots, source-code,  configuration dump, ...
https://github.com/radare/radare2/blob/168299ba0f9c0eeb3ee0ec9ad5cbca37c911847c/libr/cons/input.c#L87
https://github.com/radare/radare2/blob/168299ba0f9c0eeb3ee0ec9ad5cbca37c911847c/libr/cons/input.c#L336

**Comment by Maijin** [comment]
Can you send a Pull-request?

**Comment by XVilka** [comment]
@deepakchethan check this one too please, once you are working with vi-mode

**Comment by XVilka** [comment]
@GustavoLCR can you please check, if this happens still on Windows? Because I cannot reproduce it on Linux. If doesn't - please close.

**Comment by GustavoLCR** [comment]
Still happens
