### ISSUE TITLE
Use util/spaces in RFlag instead of copy-paste code

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#12929]
Right now there is a RFlagSpace in RFlag, however this does the same thing the RSpaces object in util/space.c does.

The dupped implementation in flag/spaces.c should be removed and the one in util/spaces.c should be used.

**Comment by radare** [comment]
Are you up for this? It is used anywhwre?

**Comment by ret2libc** [comment]
RSpaces (defined in util/spaces.c) is used for meta and for zign spaces. It should be used for flags as well and yes, I will do it, but i'm filing the issue just to remember :)
