### ISSUE TITLE
Hexagon Calls are absolute

### ISSUE THREAD

**Issue by RusEm** [radare/radare2#12938]
Calls address must be not absolute
For example. r2 show this code:
0x43167220      allocframe (0x238)
0x43167224      R1   = 0x0
0x43167228      call 0x210

but call address must be 0x43167434. 
Like 0x43167224 + 0x210 = 0x43167434

**Comment by XVilka** [comment]
Can you please craft a test case for radare2-regressions?

**Comment by jane-hopper** [comment]
hexagon asm/anal are really broken, not only in this case (wrong imm values/ wrong jumps/ etc). i am writing wrapper over objdump for discover all bugs

**Comment by XVilka** [comment]
I will publish the Python script used for generating this code tonight

**Comment by XVilka** [comment]
@RusEm @jane-hopper see https://github.com/XVilka/hexagon
