### ISSUE TITLE
Floating point exception (core dumped) when running "p- h"

### ISSUE THREAD

**Issue by JavierYuste** [radare/radare2#12934]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20945 @ linux-x86-64 git.3.2.1-193-g254c33c46 commit: 254c33c466322eff5edd6e23176c40b475950cf8 build: 2019-01-28__23:13:39

### Expected behavior
When running *p- foo* (note the space before *foo*), radare2 should state that that is not a valid command or do nothing at all.

### Actual behavior
When running *p- foo*, it crashes and exits, reporting **Floating point exception (core dumped)**. *foo* is whatever. *p- h*, *p- j*, *p- a*, they all crash.

### Additional Logs, screenshots, source-code,  configuration dump, ...
**NOTE: The binary is a malicious executable**
[Dexter_.zip](https://github.com/radare/radare2/files/2805199/Dexter_.zip)

**Comment by radare** [comment]
Fixing this takes less time than reporting. Can you submit a PR?

**Comment by JavierYuste** [comment]
Sure, I have just submitted it #12936
