### ISSUE TITLE
. /<tab> breaks the path

### ISSUE THREAD

**Issue by radare** [radare/radare2#12948]

**Comment by wargio** [comment]
just trim for each tab pressed?

**Comment by radare** [comment]
? if u press tab the whole path you typed disapears instead of autocompleting

**Comment by ret2libc** [comment]
Is this still a bug? Could you provide a full reproducer?
It does seem to work correctly right now.

**Comment by radare** [comment]
I can still repro. Its not fixed

**Comment by ret2libc** [comment]
Reproducer please.
