### ISSUE TITLE
Implement /ri to find all usages of an immediate value (and json equivalent)

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#12942]
Opening this issue from the chat because probably the person who raised this request won't open it.

**Problem:**
Currently, there is no command to quickly get all instructions where a specific immediate value was used.

**Solution:**
For a given range (`e search.from`, `e search.to`), find all instructions that are using a specific immediate value.
For example -- `/ri 0x300` would find:
```
push 0x300
mov eax, 0x300
add ecx, 0x300
```

`/rij` would return a JSON result.

**What IDA does?**
IDA has an API for this which can be used like this:
```
from = 0
value = 0x300
idaapi.find_imm(from , idc.SEARCH_DOWN, value )
```

As far as I understand, the API is searching only in detected instructions (and not everywhere in the file) and searches only for immediate values which are part of these instructions. The search happens very fast.

**Comment by radare** [comment]
Maybe /ci ?

**Comment by ITAYC0HEN** [comment]
Yeah I don't mind
