### ISSUE TITLE
Cmake build failing because of wrong struct type

### ISSUE THREAD

**Issue by deepakchethan** [radare/radare2#12943]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Mac OSX x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | **radare2 3.3.0-git 20799 @ darwin-x86-64 git.3.2.1-171-g6b3535ca3
commit: 6b3535ca36dc83f4272a48915ef365548a2653c0 build: 2019-01-29__21:22:27**

### Expected behavior
The build must be successful
### Actual behavior
Getting an error message like
```
/Users/i506629/Git/radare2/libr/anal/p/anal_h8300.c:740:23: error: variable has incomplete type 'struct r_lib_sturct_t'
struct r_lib_sturct_t radare_plugin = {
```
### Steps to reproduce the behavior 

Build the project on CLion

### Additional Logs, screenshots, source-code,  configuration dump, ...

<img width="1680" alt="screen shot 2019-01-29 at 9 45 25 pm" src="https://user-images.githubusercontent.com/20895544/51923197-7acf6680-2410-11e9-9bc8-c995aae53557.png">

### Possible fix

The bug can be fixed by fixing the typo of the struct 
Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
Sturct? Please send a pr but we dont use cmake

**Comment by deepakchethan** [comment]
I already made a PR and referred to this issue.

**Comment by Maijin** [comment]
Thanks

**Comment by ivanstepanovftw** [comment]
@deepakchethan 

> I already made a PR and referred to this issue.

Ref?

**Comment by radare** [comment]
just read the github page messages. its here

https://github.com/radare/radare2/pull/12944
