### ISSUE TITLE
"Cannot compute hash" (regression?) on r2 build 2019-02-04__22:40:42

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#12987]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX Mojave 10.14.3
| File format of the file you reverse (mandatory)      | Anritsu MS2127B firmware memdump
| Architecture/bits of the file (mandatory)            | SuperH SH4
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20712 @ darwin-x86-64 git.1.0.2-7756-g7a3dfdb4b commit: 7a3dfdb4b0b4a0b139fd7331bb6a9eb3fb38d939 build: 2019-02-04__22:40:42

### Expected behavior

In this past release:

```
radare2 3.3.0-git 20689 @ darwin-x86-64 git.1.0.2-7733-gef0f71abb
commit: ef0f71abbb21964ca0b0d1854cf1320c960a243d build: 2019-02-04__22:36:39
```

There was no "Cannot compute hash" for my memdump when loading radare2.

### Actual behavior

On the newer git version above, it does fail like this:

```
$ r2 -m 0x0f91c9a0 anritsu.mem
WARNING: using oba to load the syminfo from different mapaddress.
TODO: Must use the API instead of running commands to speedup loading times.
WARNING: bin_strings buffer is too big (0x03f80284). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
Cannot compute hash
 -- Pass '-j' to rabin2 to get the information of the binary in JSON format.
[0x0f91c9a0]> aaaa
```

**Comment by brainstorm** [comment]
Depending on `#define SLURP_LIMIT (10*1024*1024)` under `libr/core/cconfig.c`... so yeah, that file uncompressed is 64MB.

Would it make sense to just bump that limit up or do you have strong opinions on this?

**Comment by brainstorm** [comment]
@devnexen, git blame points at you for this one :)

**Comment by radare** [comment]
Hashing by blocks and reading by chunks should be the way to do that. Slurping huge files is not the way to go

**Comment by brainstorm** [comment]
Being handled by https://github.com/radare/radare2/pull/12989, closing.

**Comment by radare** [comment]
imho this should be happening by default, and only computed when rabin2 -t is used or the it command
