### ISSUE TITLE
'G' in visual mode doesn't work properly

### ISSUE THREAD

**Issue by jody-frankowski** [radare/radare2#1298]
When doing 'G' in visual mode, the visual frame is moved almost the to EOF, it's missing a few lines.

**Comment by jjdredd** [comment]
this is due to additional lines printed on top like this:
```
[0x00000000 0% 400 /bin/ls]> x @ section.phdr0                                    
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF 
```
they take up space and bottom lines aren't printed in this terminal frame. not sure how to fix that.

**Comment by ikey4u** [comment]
Request to reopen this issue. It appears in the following version of radare2:

```
radare2 3.2.0-git 20457 @ darwin-x86-64 git.3.1.3-107-gd95f8ac76
commit: d95f8ac76848df8dee89fbc643971e039953c0b1 build: 2018-12-19__12:49:45

```

[main.elf.zip](https://github.com/radare/radare2/files/2693315/main.elf.zip)

To reproduce the issue:

1. using `r2 -nn main.elf` to open the binary
2. press `v` to enter visual mode, then press `G` to go to the end
3. you can examine that the location is not the end
