### ISSUE TITLE
REvent should not assume R_EVENT_MAX

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#12981]
When implementing REvent, I have assumed the event types would have been `REventType` as defined in r_event.h, but this is not scalable. Event types can be different per "context", as done in r_spaces.h.

This issue is about adjusting the REvent implementation in event.c to not assume the only events available are from 0 to R_EVENT_MAX.

**Comment by thestr4ng3r** [comment]
I wanted to discuss this exact issue too. I see two solutions:
* Only use a single global REvent instance and just pass the pointer around (probably not what we want)
* Make `r_event_new()` take a min/max for example. Optionally the REventType enum could also be split into multiple different enums.

**Comment by ret2libc** [comment]
The other solution is to just create the pvector in the `callbacks` ht whenever it is used, instead of initializing all vectors in the `r_event_new` function. This is the solution I was thinking to implement actually.

@thestr4ng3r what do you think?

**Comment by thestr4ng3r** [comment]
That would certainly work, but then we either have to disable hooking to R_EVENT_ALL or again let r_event_new() take a min/max.

**Comment by ret2libc** [comment]
Or we could do:
```
R_API void r_event_send(REvent *ev, int type, void *data) {
	RPVector *cbs = ht_up_find (ev->callbacks, type, NULL);
	r_pvector_foreach (cbs, it) {
		cb (ev, type, ev->user, data);
	}

        RPVector *cbs = ht_up_find (ev->callbacks, R_EVENT_ALL, NULL);
	r_pvector_foreach (cbs, it) {
		cb (ev, type, ev->user, data);
	}
}
```

would this work? (it just came to my mind)

**Comment by ret2libc** [comment]
And when doing a `hook (EVENT_ALL,...)` instead of adding the cb to every existing hashtable entry, you would add it to a special R_EVENT_ALL entry in the hashtable.

**Comment by thestr4ng3r** [comment]
Of course! I didn't think about that too. But maybe instead of adding a hashtable entry for all, we should add the RVector directly as a member of REvent, so the lookup is even lighter, since it has to be done on every send anyway.

**Comment by ret2libc** [comment]
Yep, too ;)

**Comment by ret2libc** [comment]
Done
