### ISSUE TITLE
Arbitrary Bytes Read Json

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#13017]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Basically, i'm trying to get an arbitrary length byte array back from radare2. At the moment, I can do pv1248, and px, but i can't ask for an arbitrary number of bytes (that i can find at least). The closes I've seen is:

```
px/10xb
```

However, while I can adjust the number, I cannot add a `j` at any point to return it to my r2pipe as json byte list. This is effectively what I'm looking for

```
px/10xbj
```

Where `10` is just an example, but could handle any number and any gdb designation (for instance, hex words instead of hex bytes).

**Describe alternatives you've considered**
I can have manual logic right now to iterate calls to r2 until I get enough data.

**Comment by radare** [comment]
just use `pxj 10` or `p8j 10`, this px/10 thing is just a gdbism, dont use that
