### ISSUE TITLE
Cannot set asm.bits to 16 for arm arch

### ISSUE THREAD

**Issue by laqieer** [radare/radare2#13019]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux instance-1 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u3  x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM/16 Thumb
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20868 @ linux-x86-64 git.3.2.1-271-g54f841a4d commit: 54f841a4d30add4ca70463991849bbb1ee17906d build: 2019-02-08__09:01:02
### Expected behavior
set asm.bits to 16
### Actual behavior
it always returns to 32
### Steps to reproduce the behavior 
- set asm.arch to arm
- set asm.cpu to v4t
- set asm.bits to 16
- asm.bits returns to 32

### Additional Logs, screenshots, source-code,  configuration dump, ...

![image](https://user-images.githubusercontent.com/8841957/52469159-a8ad6b80-2bc5-11e9-8ec7-d1fa34d04888.png)

**Comment by radare** [comment]
try ahb 16

**Comment by laqieer** [comment]
It works. Thanks.
