### ISSUE TITLE
Can not scroll properly using webmode inside disassembly window

### ISSUE THREAD

**Issue by rahulsangwn** [radare/radare2#13023]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x86 64
| File format of the file you reverse (mandatory)      | ELF64 
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20779 @ linux-x86-64 git.3.2.1-244-g7a3dfdb4b commit: 7a3dfdb4b0b4a0b139fd7331bb6a9eb3fb38d939 build: 2019-02-04__15:19:37

### Expected behavior
Properly covering both top and down edges of the page while scrolling in disassembly window.
### Actual behavior
While try to navigate in disassembly windows towards top(first screenshot) or bottom using web mode of radare2, the disassembly window automatically get navigated towards the assembly code present in the middle(second screenshot).
### Steps to reproduce the behavior 
`r2 -c=H binary`
![scn](https://user-images.githubusercontent.com/14253888/52489312-f20eb280-2be7-11e9-9d1f-d6a4273449a9.png)
![scn2](https://user-images.githubusercontent.com/14253888/52489313-f20eb280-2be7-11e9-97f6-a50886c8504c.png)

**Comment by radare** [comment]
We have a separate repository for the webuis. Please reopen the issue in there
