### ISSUE TITLE
Change order of ? And i output

### ISSUE THREAD

**Issue by radare** [radare/radare2#13022]
That will break a bunch of tests.. but trying to use r2 on small screens results on having to scroll and look around a while to get the info that matters. For example i should show filename type and size first

And ? Must show base 10 and base8,16 first, not randomly placed

**Comment by radare** [comment]
```
[0x00000000]> i
blksz    0x0
block    0x100
fd       3
file     malloc://512
format   any
iorw     true
mode     rwx
size     0x200
humansz  512
```

should be:
```
[0x00000000]> i
fd       3
file     malloc://512
size     0x200
humansz  512
mode     rwx
format   any
iorw     true
blksz    0x0
block    0x100
```

**Comment by radare** [comment]
```
[0x00000000]> ? 123
hex     0x7b
octal   0173
unit    123
segment 0000:007b
int32   123
string  "{"
binary  0b01111011
fvalue: 123.0
float:  0.000000f
double: 0.000000
trits   0t11120

```

should be:
```
[0x00000000]> ? 123
int32   123
hex     0x7b
octal   0173
unit    123
segment 0000:007b
string  "{"
fvalue: 123.0
float:  0.000000f
double: 0.000000
binary  0b01111011
trits   0t11120
```

not sure if fvalue makes sense..

**Comment by ITAYC0HEN** [comment]
Agree more or less, makes sense

**Comment by git-kale** [comment]
If the issue is still unsolved ,I'd like to work on this issue as my first issue in radare.

**Comment by radare** [comment]
Yeah this is not resolved, i was just expecting some more feedback, but if 1/2000 ppl answers the `question`-labeled issues then i can assume this is a must to go.

So yeah all yours :) as first contrib is a good issue

you will have to update the tests in r2r.
