### ISSUE TITLE
pdc String display off by one error

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#13034]
Cf issue here: https://github.com/radareorg/cutter/issues/1151

**Comment by radare** [comment]
way to reproduce?

**Comment by xarkes** [comment]
Check the linked issue above, there are the binaries and commands needed to reproduce.
```
r2 ./spi2k7 -AA -s main -qc 'pdc'
```

**Comment by radare** [comment]
Passing args aftee the filename is against the posix getopt. Thats a bad practice if u care about portability 

Can you  upload the bin in here?

**Comment by xarkes** [comment]
> Passing args aftee the filename is against the posix getopt. Thats a bad practice if u care about portability

I know but I don't care, and I usually never change the filename while I change the arguments. So doing one or two `Alt+B` and `^W` from my shell is easier than spamming the keys to get to the first arguments (or `^A` whatever), while I understand the convention, it sucks imho.
Here is the new command if you prefer:
```
r2 -AA -s main -qc 'pdc' ./spi2k7 
```

> Can you upload the bin in here?

It's already in the other issue, but okay let's just duplicate things.
![2019-02-10-192957_maim](https://user-images.githubusercontent.com/10772605/52537745-45107300-2d6a-11e9-8592-e9d4cd08e9a9.png)

[spi2k7.zip](https://github.com/radare/radare2/files/2849216/spi2k7.zip)
