### ISSUE TITLE
Segfault in r_core_cmdf

### ISSUE THREAD

**Issue by t00sh** [radare/radare2#13033]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 4.9.130-2, AMD 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20782 @ linux-x86-64 git.3.2.1-277-g8c022deef commit: [8c022de](https://github.com/radare/radare2/commit/8c022deef84e0658394fca8746a7cbf1a13438e5) build: 2019-02-09__12:58:03

### Actual behavior

There is a segfault in the `r_core_cmdf` function.

### Steps to reproduce the behavior 

- Compile with ASAN
- Run `aa` followed by `pifjA` in the radare2 shell

### Additional Logs, screenshots, source-code,  configuration dump, ...

Here is the ASAN trace : 

```
==25813==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000041 (pc 0x7f577bcc75b2 bp 0x7ffec25b2df0 sp 0x7ffec25b2528 T0)
    #0 0x7f577bcc75b1  (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xd85b1)                                                               
    #1 0x7f577bc79731  (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x8a731)                                                               
    #2 0x7f577bc7b61d in __interceptor_vsnprintf (/usr/lib/x86_64-linux-gnu/libasan.so.3+0x8c61d)                                     
    #3 0x7f577b1e18d9 in r_core_cmdf /XXX/radare2-src-asan/libr/core/cmd.c:3903
    #4 0x7f577b2b6c2c in cmd_print /XXX/radare2-src-asan/libr/core/cmd_print.c:4496
    #5 0x7f577b4683cf in r_cmd_call /XXX/radare2-src-asan/libr/core/cmd_api.c:235
    #6 0x7f577b338856 in r_core_cmd_subst_i /XXX/radare2-src-asan/libr/core/cmd.c:3
012             
    #7 0x7f577b1dc220 in r_core_cmd_subst /XXX/radare2-src-asan/libr/core/cmd.c:202
1                                         
    #8 0x7f577b1ddea7 in r_core_cmd /XXX/radare2-src-asan/libr/core/cmd.c:3745
    #9 0x7f577b11875b in r_core_prompt_exec /XXX/radare2-src-asan/libr/core/core.c:
2751             
    #10 0x55a87fef472f in main /XXX/radare2-src-asan/binr/radare2/radare2.c:1463
    #11 0x7f57749922e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)                                              
    #12 0x55a87fefa1e9 in _start (/XXX/radare2-src-asan/binr/radare2/radare2+0x121e
9) 
```
The problem is in the function `cmd_print` in the file `libr/core/cmd_print.c` : 

```C
case 'f': // "pif"                                                                                                    
    if (input[2] == '?') { // "pif?"                                                                      
        /* ... */
     } else if (input[2] == 'j') {
        r_core_cmdf (core, "pdfj%s", input[3]);
```

Here `input[3]` is of type `char` but a type `char*` is expected for the format `%s`. ("pdf%s" is a string passed to `vsnprintf`).

**Comment by radare** [comment]
cant reproduce, which file?
