### ISSUE TITLE
Add tf subcommand to list/modify calling conventions

### ISSUE THREAD

**Issue by radare** [radare/radare2#13052]
Right now its in afc which depends on function analysis, tf should modify the k anal/fcns/name.cc=

**Comment by XVilka** [comment]
Duplicate of https://github.com/radare/radare2/issues/6856 ?

**Comment by radare** [comment]
Not exactly duplicate but yeah i can fix this pretty quickly

**Comment by XVilka** [comment]
@radare the one I mentioned it harder to fix, since will require changing TCC parser.

**Comment by radare** [comment]
No need to use the tcc parser for this. Such syntax is not even C. And can be easily parsed with custom code. In fact i was doing that yesterday by hand tweaking the sdb keys

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/commit/76c48193795c74436030ed6697188a816915a346
