### ISSUE TITLE
anal/cc args starting by 1 instead of 0 wtf

### ISSUE THREAD

**Issue by radare** [radare/radare2#13077]
<img width="525" alt="screenshot 2019-02-13 at 13 03 52" src="https://user-images.githubusercontent.com/917142/52710543-e0366200-2f8f-11e9-807f-578091747fcd.png">

**Comment by lowlyw** [comment]
to me this makes sense. when you see a function

`fun(a, b, c, d)`

you would say " a is the first argument "

not " a is the zeroth argument "

**Comment by sivaramaaa** [comment]
@radare , what do you say ??

"1" or "0" ?

IMO to be consistent we can change it to 0 , for example in function signature sdb we have `func.printf.arg.0=` !

**Comment by radare** [comment]
Im +1 for 0 :p

I like things starting at 0
