### ISSUE TITLE
Setting dbg.execs to true doesn't work on OSX

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#13101]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  OSX
| File format of the file you reverse (mandatory)      | machO
| Architecture/bits of the file (mandatory)            | x86/64 
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 21269 @ darwin-x86-64 git.3.2.1-351-g3af32f95e commit: 3af32f95e4f83f6a7d6d57cb7495aff95e7d48e0 build: 2019-02-14__08:48:43

### Expected behavior
Setting `e dbg.execs = true` should break radare2 in debug mode when execv is executed.

### Actual behavior
Break does not happen on OSX.

### Steps to reproduce the behavior 
- compile [a.c](https://gist.github.com/pawlos/6c6e65528d12e047854d4b558f452cab) -> a and [b.c](https://gist.github.com/pawlos/d14bb1699848b514835d34a784172323) -> b
- run `r2 -d ./a`
- set `e dbg.execs = true`
- continue execution `dc`

On OSX the break does not happen when execv is executed. It does break on Ubuntu.

### Additional Logs, screenshots, source-code,  configuration dump, ...
N/A

**Comment by lowlyw** [comment]
that would be because the feature is only implemented on linux.

`PTRACE_O_TRACEEXEC` is a feature that linux has, but macOS doesn't.

**Comment by pawlos** [comment]
Yeah I was digging a little bit and expected that might be the case. Not an expert but reading about `ptrace` on OSX give this:

> PT_TRACE_ME   
>                   This request is one of two used by the traced process; it declares that the process
>                    expects to be traced by its parent.  All the other arguments are ignored.  (If the
>                    parent process does not expect to trace the child, it will probably be rather con-
>                    fused by the results; once the traced process stops, it cannot be made to continue
>                    except via ptrace().)  **When a process has used this request and calls execve(2) or
>                    any of the routines built on it (such as execv(3)), it will stop before executing
>                    the first instruction of the new image.**  Also, any setuid or setgid bits on the exe-
>                    cutable being executed will be ignored.

(bold by me)

Couldn't that be used instead? And if not, maybe those OS specific features should warn about not working when used on not-supported OSes?

**Comment by radare** [comment]
We should show a warning when a specific feature is not supported. Can you send a pr adding this eprintf?

**Comment by pawlos** [comment]
@radare yes, I think so. let me work on that

**Comment by pawlos** [comment]
@radare I've noticed that there are some OS specific flags so maybe instead of doing `eprintf` it makes more sens to restrict this flag just to linux?

    #if __linux__
	SETCB ("dbg.execs", "false", &cb_dbg_execs, "Stop execution if new thread is created");
    #endif

**Comment by radare** [comment]
I want config vars to be the same for all OS. In the callback when setting it should print the message or we should find a way to implement this in userland by setting breakpoints and such instead of depending on a kernel primitive. Because this can be implemented in different ways
