### ISSUE TITLE
Analysis takes forever even for small binaries when using -dA

### ISSUE THREAD

**Issue by davidpolverari** [radare/radare2#13136]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 9.8 amd64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 21140 @ linux-x86-64 git.3.2.1-381-g86e086210 commit: 86e08621035d2346bcbbed9609d2b37aaa14bb4f build: 2019-02-17__18:17:54

### Expected behavior
- That r2 finishes analysis not so long after calling it with -dA and a small binary.

### Actual behavior
- r2 takes forever to analyze even /bin/true on a default Debian install.

### Steps to reproduce the behavior 
- Open the binary in r2 using `r2 -dA /bin/true`.

### Additional Logs, screenshots, source-code,  configuration dump, ...

N/A.

**Comment by radare** [comment]
i can reproduce on mac too, would be good to know when this issue was introduced. also i think that we should set search.in and anal.in to dbg.maps.x when cfg.debug is set to true

**Comment by radare** [comment]
Its a regression introduced after increasing anal.bb.maxsize to 1M. Use this command as a workaround for now: `e anal.bb.maxsize=1K`

**Comment by davidpolverari** [comment]
Thanks! I had no time to investigate the cause of the issue before. And, as always, thank you for such great work!

**Comment by radare** [comment]
This needs to be fixed before the next release. It will speedup analysis

**Comment by ret2libc** [comment]
I have used valgrind on radare2 and it appears a lot of time is spent in ptrace_wrap @thestr4ng3r . The 4 functions where most of the time is spent are: __new_sem_wait_slow, ptrace_wrap, do_futex_wait and sem_post. Then it comes ptrace. So, of course there is some slowness involved because ptrace is used (probably a lot and probably without any cache), but by removing ptrace-wrap the time is reduced considerably (

@thestr4ng3r could you take a look when you have some spare time, please?

With USE_PTRACE_WRAP=0:
```
$ time ./binr/radare2/radare2 -d -q -c "s main;af;q" /bin/true
real    0m6.400s
user    0m1.569s
sys     0m4.818s
```
With USE_PTRACE_WRAP=1:
```
$ time ./binr/radare2/radare2 -d -q -c "s main;af;q" /bin/true
real    1m10.713s
user    0m16.143s
sys     1m21.776s
```

**Comment by radare** [comment]
also analyzing in debugger is MUCH slower without my maxbb PR. can you help on this?

**Comment by ret2libc** [comment]
@radare are you saying that analysis on debugger is slower if you set anal.bbmaxsize=1M vs 1K?

**Comment by radare** [comment]
without my branch, yes. in fact without the debugger is slow too, but the debugger backend is much slower than posix io

**Comment by ret2libc** [comment]
This one https://github.com/radare/radare2/pull/13223 ?

**Comment by radare** [comment]
Yes

**Comment by thestr4ng3r** [comment]
Should probably be easy to fix. It is now possible to also push entire functions to the ptrace thread, so the synchronization does not need to happen all the time.

**Comment by radare** [comment]
i fixed this
