### ISSUE TITLE
pm cant identify MZ header ##magic

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#13131]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch 64bit, Win10 6 4bit
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20898 @ linux-x86-64 git.3.2.1-372-gc55d8e4 commit: c55d8e4b9cd792fef52a2b02dcbce318b390d8a9 build: 2019-02-17__08:03:05

### Expected behavior

`/m` should show detected magic headers in the binary

### Actual behavior
On a random PE file:
![image](https://user-images.githubusercontent.com/20182642/52910370-3d3b5c00-329f-11e9-9951-52442adaac7b.png)

I am getting either wrong Magic or an empty one (if json). In any way, it didn't detect the MZ header of a PE though no doubt it is in libmagic.

### Steps to reproduce the behavior
As shown in the image above.

**Comment by radare** [comment]
Use pm to test libmagic. Are you sure there are MZ signatures in libr/magic/d ?

**Comment by ITAYC0HEN** [comment]
ah I see now. I think it doesn't detect MZP header since regular MZ header in another file is detected by `/m`. See: https://github.com/radare/radare2/blob/master/libr/magic/d/default/microsoft
radare2 (`i` command) and the `file` command detects the file with the `MZP` header as a PE, as should be.

**Comment by radare** [comment]
Feel free to update the magic file to find a better rule.. try to not introduce many fase positives

**Comment by ITAYC0HEN** [comment]
this is not a bug, clsoing
