### ISSUE TITLE
How to behave with invalid function names

### ISSUE THREAD

**Issue by radare** [radare/radare2#13155]
![image 2019-02-19 12 55 12](https://user-images.githubusercontent.com/917142/53013261-993fe500-3445-11e9-837a-d68ae206ab42.jpg)

what would u expect it to happen

when u do "afn regname" ?

* not set any name
* prefix fcn
* use fcn.addr

**Comment by XVilka** [comment]
I think using `fnc.addr` is the most sane way to behave here.

**Comment by Maijin** [comment]
I also vote for `fcn.addr`

**Comment by ret2libc** [comment]
I agree on `fcn.addr`

**Comment by radare** [comment]
thats what i did already in master, so we dont have to change anything and we can close this issue
