### ISSUE TITLE
Change program arguments easily like in r1

### ISSUE THREAD

**Issue by gozes** [radare/radare2#1317]
it be nice if the r2 bin had flags to pass arguments by argv and stdin to a binary being debug. I know you can do it with rarun2 but that seams like a jumping through hoops for something as simple as passing arguments to program so that execution can continue.

**Comment by radare** [comment]
Maybe add `ooa` to reopen with different arguments? (keeping argv0 progname)?

**Comment by jvoisin** [comment]
Sounds great to me.

**Comment by Maijin** [comment]
ood arg1 arg2 arg3 
has been implemented in https://github.com/radare/radare2/issues/3359
