### ISSUE TITLE
Fail to build using WSL

### ISSUE THREAD

**Issue by iGr33k** [radare/radare2#13185]
### Work environment
| Questions  | Answers |
| ------------- | ------------- |
| OS/arch/bits (mandatory)| WSL Ubuntu 18.04 LTS  |

### Expected behavior
Build finishes successfully

### Actual behavior
Build Cannot be finished

[image](https://user-images.githubusercontent.com/36838572/53302874-7877f500-3874-11e9-8aa9-6bc40d54998a.png)

### Steps to reproduce the behavior
Run the sys/install.sh script

#### Console output

[sys install log.txt](https://github.com/radare/radare2/files/2898178/sys.install.log.txt)

**Comment by pawlos** [comment]
I think this is not longer happening. I've tried on latest code and don't see this issue

![image](https://user-images.githubusercontent.com/1296768/53488707-5b6b3e00-3a8f-11e9-99dd-a79ef5bc716a.png)

**Comment by Maijin** [comment]
thanks 👍 , please retry with latest from git @iGr33k and let us know we will reopen if necessary

**Comment by iGr33k** [comment]
Everything working now, thanks.
