### ISSUE TITLE
merge anal.jmp vars

### ISSUE THREAD

**Issue by radare** [radare/radare2#13201]
we should make those be anal.jmp.* 

```
:> e anal.jmp
anal.jmpabove   anal.jmpmid     anal.jmpref     anal.jmptbl
```

but we have also other unrelated jmpcommands that must be also renamed

```
:> e anal.~jmp
anal.afterjmp = true
anal.cjmpref = false
anal.eobjmp = false
anal.ijmp = false
```

do anal.jmp.after, anal.jmp.eob . anal.jmp.cref and anal.jmp.imm make sense to you too?

**Comment by Maijin** [comment]
Yes +1

**Comment by XVilka** [comment]
Agrreee

**Comment by SakiiR** [comment]
You forgot to update the documentation https://radare.gitbooks.io/radare2book/content/analysis/code_analysis.html
