### ISSUE TITLE
anal.maxreflines -> asm.lines.maxref

### ISSUE THREAD

**Issue by radare** [radare/radare2#13219]
or a better name, proposals?

**Comment by deepakchethan** [comment]
+1 for anal.lines.maxref. It enables us to maintain a consistent naming, given that we changed the `anal.jmp.*`

**Comment by radare** [comment]
Can you do a pr and update the tests?

**Comment by radare** [comment]
Any other comment? Btw you can 👍 the issue too

**Comment by radare** [comment]
This code is done in anal. But only used in core/disasm. Thats why i think it makes more sense in asm

**Comment by deepakchethan** [comment]
> This code is done in anal. But only used in core/disasm. Thats why i think it makes more sense in asm
> […](#)

Okay @radare, I will change it to `asm.lines.maxref` and make a pr

**Comment by radare** [comment]
fixed
