### ISSUE TITLE
Hint jumps

### ISSUE THREAD

**Issue by radare** [radare/radare2#13213]
One interesting feature for esil would be to ignore the conditional jumps and just follow the one hinted by the user. This way we can select a bunch of nodes from a graph and reach it there by just stepping in.

This can be done by reusing the abt command to find the path between 2 points in the code

**Comment by radare** [comment]
This can be implemented with the new cmd.esil.step

**Comment by a1ext** [comment]
Will be good for automation purposes

**Comment by radare** [comment]
anybody on this? its easy to do and pretty useful

**Comment by radare** [comment]
this can be done by just using ahe and ahj
