### ISSUE TITLE
bug in run webserver multiple times in one session

### ISSUE THREAD

**Issue by MaorNr** [radare/radare2#13234]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 8.1
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     |

radare2 3.3.0 1 @ windows-x86-32 git.3.3.0
commit: 5a9127d2599c8ff61d8544be7d4c9384402e94a3 build: Tue 02/19/2019__12:55:07.31

I would like to run a plugin during a reversing session.
so I run =h 80 to open a webserver, I run the plugin eveything works nice, then I use Ctrl-C to close the webserver and return to my session but when I run =h 80 again no plugin works and radare2 outputs:
"Invalid http headers received from client"

### Expected behavior
I want to be able to reopen the webserver multiple times during one session .

### Actual behavior
after ^C I cant use the webserver a second time

### Steps to reproduce the behavior 

```

C:\Users\Rakach\AppData\Local\Programs\radare2>radare2 -p calc
[anal.jmptbl] Missing predecesessor cjmp bb at 0x1400032ad
[anal.jmptbl] Missing predecesessor cjmp bb at 0x14000e0f4
Do you want to print 9874 lines? (y/N) n
 -- Do you want to print 333.5K chars? (y/N)
[0x1400014b8]> =h 80
Starting http server...
open http://localhost:80/
r2 -C http://localhost:80/cmd/
{ctrl+c} pressed.
Invalid http headers received from client
[0x1400014b8]> =h 80
Starting http server...
open http://localhost:80/
r2 -C http://localhost:80/cmd/
Invalid http headers received from client
Invalid http headers received from client
Invalid http headers received from client
Invalid http headers received from client

```

**Comment by radare** [comment]
This is a windows specific issue. Works fine on linux and mac

**Comment by MaorNr** [comment]
A lot of things are not compatible for windows and not working and there is no really any support. If I want to use r2pipe in windows without http how do I do it? All guises uses ‘/bin/ls’ which has no meaning in windows
