### ISSUE TITLE
Cannot use '.' in format names

### ISSUE THREAD

**Issue by radare** [radare/radare2#1324]
As long as we use '.' for field separator token in the format names. we cannot use 'elf.header' as struct name, we should find a better way to specifcy structname and field name. maybe using ':' or trying to figure out better which part is field and which one is struct name.

/cc @hyask

**Comment by Hyask** [comment]
this is very quick to fix, but it need a bit of discussion. What symbol should be used to naviguate though nested structs?

**Comment by radare** [comment]
What about using : ? It shouldnt conflict with flags or sdb

**Comment by Hyask** [comment]
so calling a specific field though nested structs should look like this:

    pf.struct:nestedstr:field

Or should we also remove the dot after pf like this:

    pf:struct:nestedstr:field

**Comment by jvoisin** [comment]
Or, we could keep the `.` symbol, like in almost every language that supports structures, and forbid it in fields name. 'elf_header' isn't that awful, nor is "elf:header".

**Comment by XVilka** [comment]
@jvoisin :+1:  I also agree to use dot symbol for accessing structs.

**Comment by Hyask** [comment]
the dot symbol also seems logical to me...

**Comment by radare** [comment]
yep. the dot syntax is the more consistent, but then we should forbid
using dots in struct names.. which is right for C, but not for flags. as
long as flags are more permissive than struct names this shoudlnt be an
issue. what do you think?

**Comment by Hyask** [comment]
what is the real use of dot symbol in flags? is it really necessary?

**Comment by radare** [comment]
all flags from rbin contain a flag, and only flags with dot are filtered
in the disasm for correct reading

so yep. its pretty important thing

**Comment by Hyask** [comment]
yes, but how are those flags used with pf? could you give an example?

**Comment by radare** [comment]
nope, they are not used, only relation with pf is the existence of pf*
which will print flags for the struct field. but as long as C/pf names
are more restrictive than flags that shouldnt be a problem

**Comment by Hyask** [comment]
okay, so we just have to forbid the use of dot in struct and field names

**Comment by radare** [comment]
yep that would be fine, underscore should be fine here

**Comment by Hyask** [comment]
okay, then I'll do that tonight :)
