### ISSUE TITLE
x86.nz: cannot assemble BSF/BSR instructions

### ISSUE THREAD

**Issue by edigaryev** [radare/radare2#13244]
Unsuccessful attempt to assemble BSF instruction using `x86.nz` (default assembler):

```
[0x00000000]> e asm.arch=x86
[0x00000000]> e asm.bits=32
[0x00000000]> e asm.assembler=x86.nz
[0x00000000]> wa bsf eax, ebx
Cannot assemble 'bsf eax, ebx' at line 3
```

Same instruction, but with `x86.as` assembler:

```
[0x00000000]> e asm.arch=x86
[0x00000000]> e asm.bits=32
[0x00000000]> e asm.assembler=x86.as
[0x00000000]> wa bsf eax, ebx
Written 3 byte(s) (bsf eax, ebx) = wx 0fbcc3
```

**Comment by radare** [comment]
Can you make a pr adding support for it? Shouldnt be difficult to encode it

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/tree/master/new/db/asm** (See https://github.com/radare/radare2-regressions/blob/master/new/README.md) You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```

**Comment by edigaryev** [comment]
Apparently this still works only partially using the latest version:

```
[0x00000000]> e asm.arch=x86
[0x00000000]> e asm.bits=32
[0x00000000]> e asm.assembler=x86.nz
[0x00000000]> wa bsf eax, ebx
operands_count=2, 0t=67174656, 1t=67633408
operands_count=2, 0t=67174656, 1t=67633408
operands_count=2, 0t=67174656, 1t=67633408
Written 2 byte(s) (bsf eax, ebx) = wx 0fbc
[0x00000000]> pd1 
            0x00000000      0fbc00         bsf eax, dword [eax]
[0x00000000]> wa bsr eax, ebx
Cannot assemble 'bsr eax, ebx' at line 3
[0x00000000]> pd 1
            0x00000000      0fbc00         bsf eax, dword [eax]
```

```
$ r2 -v
radare2 3.4.0-git 21087 @ linux-x86-64 git.3.3.0-55-g10548ca4d
commit: 10548ca4dba37ea9a2c3a5e6ae8fe65a1232fe49 build: 2019-03-07__18:41:07
```
