### ISSUE TITLE
cant remove no-return link after it is made

### ISSUE THREAD

**Issue by MaorNr** [radare/radare2#13247]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | 

radare2 3.3.0 1 @ windows-x86-32 git.3.3.0
commit: 5a9127d2599c8ff61d8544be7d4c9384402e94a3 build: Tue 02/19/2019__12:55:07.31

### Expected behavior
I want to be able to remove no-return marks.

### Actual behavior
they persist in the face of my commands

### Additional Logs, screenshots, source-code,  configuration dump, ...

:> tna 8
:> tn
0xffffffffffbfedf2
0x8
0x40120e
:> tn- 0x8
:> tn- 0x8
:> tn-*
:> tn
0xffffffffffbfedf2
0x8
0x40120e
:>

as u can see, I cant undo the "tna 8"

**Comment by radare** [comment]
tnn seems to fail too, we need tests for this

**Comment by radare** [comment]
Can you add some tests and close this issue? https://github.com/radare/radare2-regressions/issues/1723

thanks!
