### ISSUE TITLE
ec graph.truefae #000000 Invalid color graph.truefae

### ISSUE THREAD

**Issue by MaorNr** [radare/radare2#13248]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 8.1
| File format of the file you reverse (mandatory)      | PE,
| Architecture/bits of the file (mandatory)            | x86/3
| r2 -v full output, **not truncated** (mandatory)     | 
radare2 3.3.0 1 @ windows-x86-32 git.3.3.0
commit: 5a9127d2599c8ff61d8544be7d4c9384402e94a3 build: Tue 02/19/2019__12:55:07.31
### Expected behavior
I want to be to set the color for graph.truefae

### Actual behavior
it says invalid color

```
Press <enter> to return to Visual mode.-------------.  |
:> ec graph.truefae rgb:fff
Invalid color graph.truefae
:> r2 -v
radare2 3.3.0 1 @ windows-x86-32 git.3.3.0
commit: 5a9127d2599c8ff61d8544be7d4c9384402e94a3 build: Tue 02/19/2019__12:55:07.31
:>
```

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
Its named trufae not truefae. Thats why u get the error, because that doesnt exist

**Comment by MaorNr** [comment]
Thanks
