### ISSUE TITLE
asm.var.summary=true when numvars > screenheight? :D

### ISSUE THREAD

**Issue by radare** [radare/radare2#13259]
at least something funky for scr.responsive

**Comment by radare** [comment]
We may want to have asm.var.compact too and group vars by type like this:

int32_t var0, var1, var2, var3; ...

**Comment by XVilka** [comment]
Very good idea! Totally agree.

**Comment by radare** [comment]
any of you (the ones assigned) may be able to do this

**Comment by Vane11ope** [comment]
if any of you guys don't do this then I probably can do this before the ROP gadgets improvement, but don't know shit about the code around this issue so I need time to read code first though.

**Comment by kazarmy** [comment]
I'm currently on a slow and flaky internet connection and will be travelling soon so I'll wait
