### ISSUE TITLE
Misaligned symbols when inspecting a running Windows XP kernel

### ISSUE THREAD

**Issue by Wenzel** [radare/radare2#13251]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 29 64 bits
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21232 @ linux-x86-64 git.3.3.0-26-ga7518c7d0 commit: a7518c7d0cb47e541408db3b0bb581a209923af7 build: 2019-02-26__20:55:26

### Expected behavior

The symbols should be aligned with the content of the Windows XP kernel in memory

### Actual behavior

The symbols are misaligned, there is a `0xef` offset between the `radare2` addresses and the real addresses reported by `WinDBG`

### Steps to reproduce the behavior 
- Setup a Windows XP VM
- Debug it with [pyvmidbg](https://github.com/Wenzel/pyvmidbg)
- run `radare2`: `r2 -d gdb://192.168.121.165:5000 -b 32`
- load the `ntoskrnl.exe` at the base address given by `pyvmidbg`
- Find the symbol of `NtOpenFile`
- Compare with what WinDBG says

### Additional Logs, screenshots, source-code,  configuration dump, ...

1. Load Windows kernel at kernel base address `0x804d7000` with `oba`, print 10 instructions at `NtOpenFile`, and see that it's not aligned
![print_address_radare](https://user-images.githubusercontent.com/964610/53701463-036d6800-3dfe-11e9-8c81-b181ac1e0bc4.png)

2. print addresses in `WinDBG`
![print_address_windbg](https://user-images.githubusercontent.com/964610/53701474-29930800-3dfe-11e9-8854-454afb827fe7.png)

3. Compute offset
![offset](https://user-images.githubusercontent.com/964610/53701477-30ba1600-3dfe-11e9-978b-f5bc1d4135d3.png)

4. reload the kernel at kernel base address + offset
![kernel_base_offset](https://user-images.githubusercontent.com/964610/53701482-3b74ab00-3dfe-11e9-8993-2459830b1a36.png)

The addresses matches now !

Note Inspecting the file without using the VM's memory works:
![screenshot_20190303_214216](https://user-images.githubusercontent.com/964610/53701513-4e877b00-3dfe-11e9-9f53-4587076303fa.png)

**Comment by Wenzel** [comment]
Problem is solved.
I was using the wrong kernel.

Windows XP has multiple kernels depending on your processor configuration.
- `ntoskrnl.exe`
- `ntkrnlpa.exe` (if PAE extension is enabled)

Sorry for the false bug report

Thank you !

**Comment by Maijin** [comment]
Thanks for letting us know @Wenzel ;)
