### ISSUE TITLE
RFE: afll argument to specify which column use to sort the rows

### ISSUE THREAD

**Issue by radare** [radare/radare2#13278]
<img width="677" alt="screenshot 2019-03-06 at 00 17 27" src="https://user-images.githubusercontent.com/917142/53844185-3b62df80-3fa5-11e9-9971-43571bfe3eea.png">

**Comment by c-urly** [comment]
I am thinking of making different comparators for each argument. For ex. cmpfcnaddr, cmpfcnsz, cmpfcnbbs and like. If theres a more better way do tell me.

**Comment by radare** [comment]
We have ~$ to sort the output of a command by a column

**Comment by c-urly** [comment]
So afll ~$3 output should be sorted list based on value of nbbs?

**Comment by radare** [comment]
yes, didnt tried, but it should..will be good to have it documented in the book and maybe write some tests

**Comment by c-urly** [comment]
I am first parsing afll cost ,so it will sort on cost column. For it i am using r_core_cmd_str(core,"afll ~$5"). This will rerun the command and return the output of "afll ~$5" and then i am putting that output in core->cons.context->buffer. This will do?

**Comment by radare** [comment]
Theres an api in rcons to get the buffer you dont need to dereference it. But yeah. Seems reasonable that we reuse the column sorting code instead of reimplementing it for each data structure

**Comment by c-urly** [comment]
Just a question, See if we use the coulmn sorting code we have to implement a whole command but if we just implement a compare functions and sort the buffer that will also do the job. So which is better, i just want to know how can i make the decision of which thing is good?

**Comment by radare** [comment]
Done also in afls in a PR
