### ISSUE TITLE
Shorter name for #!pipe python ..

### ISSUE THREAD

**Issue by radare** [radare/radare2#13302]
the problem is that when we use cmd.esili.* the commands get executed with 2 numeric arguments, so we can't use '.' because it will honor the spaces as part of the filename. the solution would be to add a new command `..` to interpret a file using r2pipe via #!pipe .. thiis is. just chopping for the first argument and ignoring the arguments.

Another option can be to implement the `#!.` command whiich does the same as `.` but launching via r2pipe and accepting parameters, this is chopping the filename by the first space

**Comment by radare** [comment]
cc @a1ext

**Comment by a1ext** [comment]
Yeah, these three months I'm very busy at work -___-, I don't think I will be free to implement this

**Comment by radare** [comment]
i just did it, i was pinging you to get some feedback on which command use, etc, but i decided to use .*

**Comment by a1ext** [comment]
Thanks :)

чт, 7 марта 2019 г. в 2:41, radare <notifications@github.com>:
