### ISSUE TITLE
Kill libr/include/msvc

### ISSUE THREAD

**Issue by radare** [radare/radare2#13316]

**Comment by pelijah** [comment]
@radare can you please update `sdb`?

**Comment by radare** [comment]
done

**Comment by radare** [comment]
msvc is still there, but maybe we can remove it and nothing will break, can you do a PR for this?

**Comment by radare** [comment]
nvm i did that pr, lets wait for it

**Comment by radare** [comment]
https://github.com/radare/radare2/pull/13416

**Comment by radare** [comment]
done already
