### ISSUE TITLE
@@@ improvements

### ISSUE THREAD

**Issue by radare** [radare/radare2#13319]
@@ thoughs
==========

Comments

Common actions
--------------
* dump in files all search results
* disasm the whole file
* dump the whole bin (pd for exec sections, px for data ..)

Unexpected behaviours
---------------------

* hexdump all maps: x$MM@@=`om~[4]`
    * omq should just list the first offset of each map, not fd and index which is useless
    * $MM should be unnecessary if we use @@@
* @@@ doesnt work with JSON output

**Comment by Maijin** [comment]
See also #5353

**Comment by radare** [comment]
let's move to next release and think properly on how and what to support in here, i was expecting some feedback or proposals from anyone except me

**Comment by Maijin** [comment]
@radare I already proposed stuff in #5353

**Comment by radare** [comment]
i know, this is why im delaying that

**Comment by radare** [comment]
i can do what i had in mind tonight and we can continue improving and discussing later, because afaik nobody uses @@@ now

**Comment by Maijin** [comment]
@radare yep and I wouldn't rush for that same reason 👍

**Comment by radare** [comment]
"We have 3 flags and we want to do thebsame as done in aaF but generic for any command"

from https://github.com/radare/radare2/issues/12986

**Comment by XVilka** [comment]
@radare it is documented in the book though, but largely a duplicate of `@@`. So I think we can change behavior easily, just don't forget to update r2book.

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/13749
