### ISSUE TITLE
Implement load_buffer in all RBin plugins

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#13349]
When loading a binary, RBin checks if the RBinPlugin implements load_buffer, load_bytes and load in this order. Many plugins have all three implementations because that was done progressively, but nowadays only `load_buffer` should be used.

On the other hand, many plugins still use `load_bytes`/`load` and do not provide a implementation of `load_buffer`, which should be preferred.

This issue is about tracking the move from `load/load_bytes` to `load_buffer` and from `check_bytes` to `check_buffer`.

- [x] bin_any.c
  - [ ] check_buffer
  - [x] load_buffer
  - [x] remove load_bytes/load
  - [ ] remove check_bytes
- [x] bin_art.c
  - [x] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_avr.c
  - [x] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_bf.c
  - [x] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_bflt.c
  - [x] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_bios.c
  - [x] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_bootimg.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_cgc.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_coff.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_dbginfo_dex.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_dbginfo_elf64.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_dbginfo_elf.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_dex.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_dol.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [x] bin_dyldcache.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_elf64.c
  - [ ] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_elf.c
  - [ ] check_buffer
  - [x] load_buffer
  - [x] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_fs.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_java.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_ldr_linux.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_mach064.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_mach0.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_mbn.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_mdmp.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_menuet.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_mz.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_nes.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_nin3ds.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_ninds.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_ningba.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_ningb.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_nro.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_nso.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_omf.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_p9.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_pe64.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_pebble.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_pe.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_psxexe.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_qnx.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_sfc.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_smd.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_sms.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_spc700.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_symbols.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_te.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_vsf.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_wasm.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_write_elf64.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_write_elf.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_write_mach064.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_write_mach0.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_write_pe64.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_write_pe.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_xbe.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_xnu_kernelcache.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_xtr_dyldcache.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_xtr_fatmach0.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_xtr_pemixed.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_z64.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes
- [ ] bin_zimg.c
  - [ ] check_buffer
  - [ ] load_buffer
  - [ ] removee load_bytes/load
  - [ ] removee check_bytes

**Comment by radare** [comment]
What about rewriting rbin in json or xml instead of C ? XD every change in all the plugins is a pain

**Comment by ret2libc** [comment]
I know, but that's something that needs to be done :/ RBuffer in RBin is an essential change IMHO for consistency and performance reasons. It also automatically allows to load binaries from memory (or from wherever else).

**Comment by radare** [comment]
Yes i know. I promoted this change and did a lot of it in the past same goes for asm with rbufstr, tiring and boring but necessary, so im totally +1 for this change. But not for all those chkboxes. Bettet do the.whole thing in a single pr and before 2 weeks

**Comment by ret2libc** [comment]
Eheh, right, I just wanted to keep track of things in a clean way, for me mainly.

**Comment by radare** [comment]
is this list updated? whats left

**Comment by radare** [comment]
ping ^

**Comment by ret2libc** [comment]
The list should be mostly updated. @Maijin was supposed to go ahead with some of these plugins. However, I will probably help him once I finish with https://github.com/radare/radare2/pull/13473

**Comment by Maijin** [comment]
Well was more like a best-effort for me

**Comment by radare** [comment]
impossible to finish this in less than a week. moving to 3.5

**Comment by ret2libc** [comment]
yeah :D

**Comment by Maijin** [comment]
That's fixed.
