### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by ickromwerk** [radare/radare2#13351]
Trying to build on Raspberry Pi Zero with sys/user.sh

uname -a
`Linux raspberrypi 4.14.93+ #1191 Wed Jan 16 11:39:44 GMT 2019 armv6l GNU/Linux`

git status
```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

[log here](https://gist.github.com/ickromwerk/e13493161f58ebebf32ff96185f30de9)

**Comment by radare** [comment]
which version of capstone are you linking to? we support capstone 3 and 4. i think this is tested in travis too @ret2libc

**Comment by ickromwerk** [comment]
You right, I have old capstone in libr folder. I used old repository and started build with sys/user.sh
Looks like this script does not updated capstone or I built it by hands earlier.

Cloned repository anew and it builds like a charm. I need to apologize for disturbing you.

**Comment by radare** [comment]
capstone shoulkd be in shlr, not libr

can you fix the user.sh script? no need to apologize, its a bug :)

**Comment by radare** [comment]
ping?

**Comment by ickromwerk** [comment]
Hi. I'm here. I thought a lot about this issue and come to the conclusion. As I said before -- it was a mistake to open this ticket.

I have remembered that when I built r2 first time I have got some compile errors in capstone. Probably because of that I have built it manually. Yeap, your right about folder -- it situated here(shlr). I remembered that it was strange folder with 'r' at the end and did not checked my assumption before mentioning "libr".

Anyways, I already deleted that repository and made fresh install. So its almost impossible to reproduce that situation.

It probably worth checking build script about capstone repository updating and I think I have to do it now.

**Comment by ickromwerk** [comment]
@radare, you were right. That's a bug.

I can't check it right now because I'm already in pajamas but that's some steps to reproduce it:

1. Clone repository
2. Start a build
3. Build must fail in capstone directory by any means
4. Go and build capstone in place from release by hands but in place(shlr/capstone)
5. I probably used USE_R2_CAPSTONE(now obsolete) because it looks familiar

At this place you must have r2 from got and shlr/capstone without .git, so shlr/capstone.sh will not update capstone properly next time

**Comment by radare** [comment]
Should be fixed in here https://github.com/radare/radare2/pull/14043

**Comment by radare** [comment]
Closing, pls report any other issue if you can repro after 3.5
