### ISSUE TITLE
`vbg` last line drown with off-by-one position

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#13367]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 29 x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 22180 @ linux-x86-64 git.3.3.0-138-g0c9ccb45d

### Expected behavior
Proper 
### Steps to reproduce the behavior 
```
r2 /bin/ls
> aaa
> s main
> vbg
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
![image](https://user-images.githubusercontent.com/203261/54267823-e03c7880-45b4-11e9-937d-59f9ecb4e761.png)

Drag and drop zip archives containing the Additional info here, don't use external services or link.
[fedora29_bin_ls.zip](https://github.com/radare/radare2/files/2960689/fedora29_bin_ls.zip)

**Comment by radare** [comment]
shuold be fixed after 
https://github.com/radare/radare2/pull/13472

can you confirm?

**Comment by XVilka** [comment]
It wasn't fixed and now even worse:
![image](https://user-images.githubusercontent.com/203261/54896780-b6fae100-4f00-11e9-9766-9c3d52cc5cb2.png)

**Comment by radare** [comment]
? Wat

**Comment by radare** [comment]
Aaah i though you were refering to the bug that was before the pr that the disasm was using the offset one row off the one you had selected. That was fixed :p
