### ISSUE TITLE
Script with same name as binary not run when using -d

### ISSUE THREAD

**Issue by dutt** [radare/radare2#13363]
**I'll fix this one next week**

I have a binary to analyse, crackme0x04 in my case. I have a script crackme0x04.r2 in the same directory with two short lines, "dcu main" and "s main".

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 32
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21113 @ linux-x86-64 git.3.3.0-136-ge6d871523 commit: e6d871523c0fb31e429ae596b88f97b5e24857b4 build: 2019-03-12__21:07:16

### Expected behavior

I expect to be asked whether to run this script when I start in debugger mode (-d)

### Actual behavior

I don't get the question to run the script with -d, I do get it without -d though.

### Steps to reproduce the behavior 

Use any binary, create any script with same name but with .r2 extension. Run the binary, "r2 -A -d binary" and you won't get the question to run the script.

**Comment by radare** [comment]
I dont think cutter needs this at all
