### ISSUE TITLE
[Question] Disassembly Error Detection

### ISSUE THREAD

**Issue by mingwayzhang** [radare/radare2#13364]
I am wondering if I could use r2 to provide me the disassembly quality.

In particular, I would like a summary of: 1) the percentage of code disassembled. (all executable code sections in an ELF code segment, assuming there is section table); 2) disassembly errors (like number of invalid). 3) gaps between function boundaries.

Currently, from looking at the r2 API and manual, I could only do it manually using r2pipe.

Thanks.
-Mingwei

**Comment by radare** [comment]
1) aai
2) pD $SS~invalid?
3) no such thing but aaF is related, and you can write an r2pipe script to do that

**Comment by henry3379** [comment]
Thanks.

aai seems provide some information as follows on my "ls" program:

fcns    272
xrefs   9761
calls   0
strings 412
symbols 119
imports 111
covrage 46901
codesz  122916
percent 38%

I wonder what does the covrage mean here? codesz means the size of code segment which is fine and coverage seems to be covrage/codesz.

pD $SS is too much and seems like disassemble the whole binary.

**Comment by radare** [comment]
coverage is the sum of all the bbs of all the functions compared with the size of the executable sections mapped

$SS = section size, you can do the same for all the maps with executable permissions to just grep for the invalid ones. but use pid or pi because its faster than pd

**Comment by Maijin** [comment]
I'm closing here as the answers from @radare seem to have answered your questions

**Comment by Maijin** [comment]
Feel free to reopen a new issue if necessary
