### ISSUE TITLE
Install Failing on "lib/libbochs.a"

### ISSUE THREAD

**Issue by TimothyFDavison** [radare/radare2#13372]
Hey all,

Thanks for putting this tool together -- it's outstanding and has helped me on several projects. I'm currently trying to run an install in an isolated environment (Ubuntu x86/64) without internet access, and accordingly have been pulling in dependencies through a controlled import process one by one. 

### The Issue

Running "sys/install.sh" is failing on something involving "bochs" leaving this in the middle of the trace:

>>>>
Native Build SDB
>>>>

CC cdb.c
CC buffer.c
CC cdb_make.c
CC ls.c
r - src/libbochs.o
ar: could not create temporary file whilst writing archive: No more archived files
Makefile:41: recipe for target 'lib/libbochs.a' failed
make[2]: *** [lib/libbochs.a] Error 1
Makefile:161: recipe for target 'bochs' failed
make[1]: *** [bochs] Error 2
make[1] *** Waiting for unfinished jobs....
...
<more CC ___.c>
...
AR libsdb.a
ar: creating libsdb.a
Makefile:57: recipe for target 'all' failed
make *** [all] Error 2

<end>

Is "Bochs" a dependency as well? Is this referring to the PC emulator?
Thanks!

**Comment by Bhuvanamitra** [comment]
fatal: Not a git repository (or any parent up to mount point /home) 
I get this message when I ran git clean -xdf inside sys folder

**Comment by radare** [comment]
so you are not building r2 from git, which is the source of the thing you are compiling?

**Comment by Bhuvanamitra** [comment]
https://github.com/radare/radare2
I have downloaded as Zip from here

**Comment by radare** [comment]
That builds fine for me. Can you scroll up a bit and pste the real error which says why libbochs is not compiled?

**Comment by Bhuvanamitra** [comment]
>>>>>>>>>>>>>>>>
TARGET BUILD SDB
>>>>>>>>>>>>>>>>

CC cdb.c
CC buffer.c
CC cdb_make.c
CC ls.c
CC sdbht.c
CC ht_uu.c
CC sdb.c
CC num.c
CC base64.c
CC match.c
CC json.c
CC ns.c
CC lock.c
CC util.c
CC disk.c
CC query.c
CC array.c
CC fmt.c
CC journal.c
CC dict.c
CC ht_pp.c
CC ht_up.c
AR libsdb.a
ar: creating libsdb.a
Makefile:57: recipe for target 'all' failed
make: *** [all] Error 2

This is the exact error.

**Comment by radare** [comment]
there's no error here, scroll up

**Comment by Bhuvanamitra** [comment]
>>>>>>>>>>>>>>>>
NATIVE BUILD SDB
>>>>>>>>>>>>>>>>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Makefile:268: recipe for target 'capstone-4.0.1.tar.gz' failed
make[1]: *** [capstone-4.0.1.tar.gz] Error 35
make[1]: *** Waiting for unfinished jobs....
ar: creating lib/libbochs.a
a - src/libbochs.o
CC cdb.c
CC buffer.c
CC cdb_make.c
CC ls.c
CC sdbht.c
CC ht_uu.c
ar: creating libr_windbg.a
CC sdb.c
CC num.c
CC base64.c
CC match.c
CC json.c
CC ns.c
CC lock.c
CC util.c
CC disk.c
CC query.c
CC array.c
CC journal.c
CC fmt.c
CC dict.c
CC ht_pp.c
CC ht_up.c
CC main.c
AR libsdb.a
ar: creating libsdb.a
BIN sdb

**Comment by Bhuvanamitra** [comment]
I tried to do following steps: 
----------------------------------------------------------------------------------------
~ $ wget https://github.com/radare/radare2/archive/3.3.0.tar.gz
~ $ tar xzvf 3.3.0.tar.gz
~ $ cd radare2-3.3.0/
~/radare2-3.3.0 $ ./configure --prefix=/usr
~/radare2-3.3.0 $ make -j8
~/radare2-3.3.0 $ sudo make install
----------------------------------------------------------------------------------------
Gets the same error:

curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Makefile:269: recipe for target 'capstone-4.0.1.tar.gz' failed
make[1]: *** [capstone-4.0.1.tar.gz] Error 35
make[1]: *** Waiting for unfinished jobs....

Please help me resolve this.

**Comment by TimothyFDavison** [comment]
Hey Bhuvanamitra, 

I was actually getting the same capstone-4.0.1 issue as well, but I resolved it by downloading that version of capstone from https://www.capstone-engine.org/download.html, and building it in the environment where I am trying to install Radare. 

@Radare, I also was building from a Zip file, which I had brought into the network-isolated environment (because that environment does not have git installed). Accordingly I'm unfortunately unable to run git clean -xdf. The only error messages I got from the build were those which I copied to my original comment. Is there by chance another way to check what's missing?

Thanks again!

**Comment by Bhuvanamitra** [comment]
> building it in the environment where I am trying to install Radare
Can you please tell me how to do this?
I actually have capstone 4.0.1 in my python installation, but still i am getting this error

**Comment by TimothyFDavison** [comment]
Capstone 4.0.1 was released with build instructions for Linux systems here: 
https://github.com/aquynh/capstone/blob/master/COMPILE.TXT
If I remember correctly, I just used the makefile which came packaged with the repository.

**Comment by Bhuvanamitra** [comment]
>  https://www.capstone-engine.org/download.html

I have downloaded capstone from this link

> If I remember correctly, I just used the makefile which came packaged with the repository.

Used make file and installed. (./make.sh )
But still the problem occurs. What am I doing wrong here?

**Comment by radare** [comment]
Use the tarball from the mikelloc site. The github tarballs dont contain capstone so u have to install it from outside or have network connectivity to let sys/install downlod and build it for u

**Comment by TimothyFDavison** [comment]
Excellent, thank you! Everything's up and running.

**Comment by Bhuvanamitra** [comment]
> Use the tarball from the mikelloc site

This solved the problem. Thank you.
