### ISSUE TITLE
Search Memory in Running Process

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#13388]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 1 @ linux-x86-64 git.3.4.0-git commit: 8e1da330b64f4c83b8f0cc9697ba635304ce1ce6 build: 2019-03-08__06:10:25

### Expected behavior
When a process is open for debugging, i'd expect search to actually search the full memory space (including those mapped to loaded librarys/stack/etc).

### Actual behavior
It does not appear to do this.

### Steps to reproduce the behavior 
- Load up some program
- Break point on main
- Find a unique string on the stack (px/s whatever)
- Try to use `/` to find that string

It does not appear to find those strings.

**Comment by radare** [comment]
e search.in=??

**Comment by bannsec** [comment]
Ok. Setting that to dbg maps worked. It is a bit confusing since IDA and company default their string searches to the entire memory space when in debug mode.

**Comment by radare** [comment]
browsing on the entire memory by default is imho a pretty bad idea imho
