### ISSUE TITLE
Add compiler name in iI

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#13393]
**Is your feature request related to a problem? Please describe.**

The compiler name is missing from `iI` command.

**Describe the solution you'd like**

Some internal functions already checks for compiler name example MSVC for example in PE but the information is not exposed in `iI`:
- https://github.com/radare/radare2/blob/master/libr/bin/format/pe/pe.c#L57
- https://github.com/radare/radare2/blob/master/libr/bin/format/pe/pe.c#L311

The information should be displayed in `iI` when available.

Example of output for `iI` after the fix

```
...
compiler    msvc
...
```

**Comment by RomeuG** [comment]
Hey, how would I achieve this if I wanted to work on it?

**Comment by radare** [comment]
it's there now
