### ISSUE TITLE
Types Xrefs

### ISSUE THREAD

**Issue by radare** [radare/radare2#13401]
Usually we think about code or data references... but hey! types can be also be fit in this concept because types are used from function signatures or variables. So let's define a couple of features taht will be useful in r2land:

* find which functions use a given type (xrefs)
* find which types are used in a function (refs)
* show types/function graph (using agn/age)
* find which types are used in all the functions analyzed (or in a range)
* show aflm style (all functions + their types)

My suggestion here is to add the `tx` command as in `type-xrefs` like this:

* axt int = 
* axf int = which functions use `int` in their signature
* ax* = age/agn graph
* axm = output like aflm
* axj = in json

In addition we can think of more features here, for example

* find which variables (instead of functions) are of a specific type.
* find which types use a given type (nested struct resolution) (type-type refs)
* ...

**Comment by radare** [comment]
related to https://github.com/radare/radare2/pull/13400

**Comment by radare** [comment]
![IMAGE 2019-03-17 11:22:13](https://user-images.githubusercontent.com/917142/54488856-ea0cf700-48a6-11e9-9fb9-4912d42b9f01.jpg)

**Comment by radare** [comment]
Another idea is to show which kind of use for a type the function does:

* return type?
* argument?
* variable?

**Comment by XVilka** [comment]
In general idea is good. I will add my comments when I have time. Not for this release though.

**Comment by radare** [comment]
@sivaramaaa already implemented some of this stuff, and shouldnt be hard to finish that before sunday (end of rfe-cycle)

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/13855
