### ISSUE TITLE
Change the folded BB marking

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#13412]
I think instead of interrupting function line it should not.
Maybe show `[+]` characters instead? And align the text with addresses column.
Moreover remove empty lines with just `|` character, they reduce the amount of information available on the screen.
Probably something like this:
```
|    [+] Unfold BB [0x0007b; 0x00105]
```
Where 0x0007b is basic block start, 0x00105 is basic block end.

![image](https://user-images.githubusercontent.com/203261/54509601-11d28c80-4985-11e9-9ff1-35a9e5692bd4.png)

**Comment by radare** [comment]
yeah that can be improved indeed. i like the [+] idea maybe we should use that for folding functions too

**Comment by radare** [comment]
like this?

<img width="1558" alt="Screenshot 2019-03-18 at 11 17 44" src="https://user-images.githubusercontent.com/917142/54523297-7a167380-496f-11e9-9bbd-f4b5295d32ca.png">

**Comment by radare** [comment]
![IMAGE 2019-03-18 11:24:42](https://user-images.githubusercontent.com/917142/54523706-6d464f80-4970-11e9-88c8-b061e134d62b.jpg)

![IMAGE 2019-03-18 11:24:53](https://user-images.githubusercontent.com/917142/54523711-73d4c700-4970-11e9-9848-63803e98e2c2.jpg)
