### ISSUE TITLE
pad does not respect asm.pseudo

### ISSUE THREAD

**Issue by wasamasa** [radare/radare2#13429]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux 64bit
| File format of the file you reverse (mandatory)      | chip8
| Architecture/bits of the file (mandatory)            | chip8
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21356 @ linux-x86-64 git.3.3.0-173-gd16b0903d commit: d16b0903d5a180151f334914156e2d033e108f48 build: 2019-03-18__22:29:12

### Expected behavior

`pad d348` => `drw(v3, v4, 0x8)`

### Actual behavior

`pad d348` => `drw v3, v4, 0x8`

### Steps to reproduce the behavior

```
$ r2 -a chip8 -q -c 'pad d348' -
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

`pd` behaves as expected and uses `r_core_print_disasm` with the pseudo settings retrieved from the current core, `pad` uses `r_asm_mdisassemble_hexstr` with the pseudo settings retrieved from a `RAsm` object defaulting to none. The latter is only used from `rasm2` so far where you can only get pseudo-disassembly by setting an input/output filter with `-F`. I have no idea how to even start fixing this, ideas are welcome.

**Comment by radare** [comment]
this is just 1 line to fix, do you want to do it?

**Comment by radare** [comment]
90% of the issues take longer to report/explain than fix them

**Comment by wasamasa** [comment]
Sure, I'm asking about the how because it's unclear to me. Which one is it going to be?

- Giving `r_asm_mdisassemble_hexstr` a filter based on the current core's settings
- Using `r_core_print_disasm`
- Something entirely different

**Comment by radare** [comment]
i would go for r_core_print_disasm, if this is whats called from 'pad' ?

**Comment by wasamasa** [comment]
It's not, that's the problem. `r_core_print_disasm` appears to be designed for disassembling a chunk of memory while `r_asm_*` stuff is designed for files and strings.
