### ISSUE TITLE
Though cygwin/mingw was killed already..

### ISSUE THREAD

**Issue by radare** [radare/radare2#13430]
```
$ git grep CYGWIN|wc -l
      34
```
and
```
$ git grep MINGW|wc -l
      54
```

cc @XVilka

**Comment by XVilka** [comment]
@radare if you search for CYWGIN it appears only in
- imported SDB code, which probably should work with Cygwin still
- imported capstone and other libs in shlr
- imported binutils code (libiberty)
- libmagic

So I prefer not to touch those.

**Comment by radare** [comment]
Its fine then. For libmagic i dont know how 
much we want to continue modifying it or just keep our own fork as long as its not in shlr
