### ISSUE TITLE
aflqj seems broken

### ISSUE THREAD

**Issue by JavierYuste** [radare/radare2#13448]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04, x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21523 @ linux-x86-64 git.3.3.0-209-gb0ac77881 commit: b0ac77881e8e83c834e8b6564629b2000e709573 build: 2019-03-20__20:49:44

### Expected behavior
aflqj should return a json object of functions addresses
### Actual behavior
aflqj does not return json, but something like _7642180164218640421904042192164220112422011842201244220130422013642201424220148[]_
### Steps to reproduce the behavior 
r2 "binary"
aaa
aflqj

**Comment by radare** [comment]
Thats expected

**Comment by JavierYuste** [comment]
I may have not understood you correctly, is that expected behavior?

**Comment by radare** [comment]
Yes. The q makes it quiet and just shows the address where each function starts

**Comment by JavierYuste** [comment]
But it should return them as json, while currently its is returning a string of numbers. For instance, running _"iSj"_ returns the following:
_[{"name":".text","size":24576,"vsize":24576,"perm":"-rwx","paddr":3072,"vaddr":4198400},{"name":".data","size":9728,"vsize":16384,"perm":"-rw-","paddr":29184,"vaddr":4222976},{"name":".rsrc","size":30208,"vsize":32768,"perm":"-r--","paddr":40448,"vaddr":4239360},{"name":".reloc","size":2560,"vsize":4096,"perm":"-r--","paddr":72192,"vaddr":4272128}]_

More than 10 days ago, _"aflqj"_ did return a json containing the same information as _"aflq"_. I have updated r2 today and that has changed, so this must have been introduced recently. I think that it is not expected behavior, is it?

![Screenshot from 2019-03-20 23-58-00](https://user-images.githubusercontent.com/35402702/54724582-0b523980-4b6c-11e9-99b0-11de4b41767c.png)

**Comment by radare** [comment]
Use aflj is you want more than just the offset
