### ISSUE TITLE
Improvements in aaa

### ISSUE THREAD

**Issue by radare** [radare/radare2#13445]
* [x] Include aao on objc binaries
* [ ] Sometimes aaF is much better
* [x] aav is problematic on ARM-Thumb binaries

**Comment by Maijin** [comment]
aav is problematic on ARM-Thumb binaries but that's where it is the most useful too, not sure what you want to do here.
Sometimes aaF is much better, where, which file format/type/arch?
For aao I just created a PR here https://github.com/radare/radare2/pull/13476

**Comment by Maijin** [comment]
For the aav, @radare has a wip for aaF we need for info

**Comment by radare** [comment]
i plan to push it before tomorrow. must finish some more stuff i have in wip first and test it properly and see if my theory applies to the reality

**Comment by Maijin** [comment]
Great!

**Comment by radare** [comment]
i fixed aav. and i think aaF makes no sense to be in aaaa, so lets close it
