### ISSUE TITLE
Wrong detect function for iOS macho binary

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#13466]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | iOS x32
| File format of the file you reverse (mandatory)      | macho
| Architecture/bits of the file (mandatory)            | arm
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21532 @ darwin-x86-64 git.3.3.0-225-g9f840c630 commit: 9f840c6306b853e98eab75ed2fa9522f7e2dae98 build: 2019-03-22__16:31:20

### Expected behavior

- I think name for function should be `sym.func.0000c02a`
- And have xref from:
```
[0x0000c02a]> axt sym.func.0000c02a
sym.func.0000bce9 0xbf6a [DATA] add r2, pc
[0x0000c02a]>
```

### Actual behavior

We have two problems:

- Wrong name for function (I suppose) - `sym.func.0000c02b`

![image](https://user-images.githubusercontent.com/1186777/54825010-8e36d980-4cbd-11e9-85a0-55b7e1e1941b.png)

- We don't see xrefs to function:
```
[0x0000c02a]> axt sym.func.0000c02b
[0x0000c02a]> axt 0x0000c02a
[0x0000c02a]>
```

But! We have xref to address 0x0000c02b
```
[0x0000bf6a]> axt 0x0000c02b
sym.func.0000bce9 0xbf6a [DATA] add r2, pc
[0x0000bf6a]>
```

### Steps to reproduce the behavior 

Open and analyze file: [geod.zip](https://github.com/radare/radare2/files/2996613/geod.zip) (it is from iOS 10.2 firmware)

### Additional Logs, screenshots, source-code,  configuration dump, ...

Same piece of code in another disassemblers.

Hopper:

![image](https://user-images.githubusercontent.com/1186777/54824847-284a5200-4cbd-11e9-8056-8072d2165730.png)

Comment wrong but clicking follows to right function - sub_c02a

IDA:

![image](https://user-images.githubusercontent.com/1186777/54825210-0ef5d580-4cbe-11e9-9539-3da751d6bc00.png)

**Comment by radare** [comment]
Dat zumb
