### ISSUE TITLE
not all strings get xrefed

### ISSUE THREAD

**Issue by condret** [radare/radare2#1346]
see this code:
`````
#include <stdio.h>

static void a()
{
	printf ("This ");
}

static void b()
{
	printf ("is ");
}

static void c()
{
	printf ("an ");
}

static void d()
{
	printf ("example ");
}

static void e()
{
	printf ("usecase ");
}

static void f()
{
	printf ("for ");
}

static void g()
{
	("xrefs ");
}

static void h()
{
	printf ("in ");
}

static void i()
{
	printf ("r2\n");
}

int main ()
{
	a();
	b();
	c();
	d();
	e();
	f();
	g();
	h();
	i();
	return 1;
}
`````

r2 does not create data-refs for every-string here

**Comment by Maijin** [comment]
15-09-2015: Still not fixed :(

**Comment by radare** [comment]
Is not that simple. Sometimes strigs refs can only be fiund by emulating the code

**Comment by Maijin** [comment]
@radare in that example, the string are recognised as code that's why it doesn't work mostly

**Comment by radare** [comment]
I dont see any binary here. Compiling this program with different flags or arch targets will result in different results

**Comment by Maijin** [comment]
http://rghost.net/private/7wF7LKcCj/4221e2c500e3ac43f14892e2823975dc

a: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=3ebd28c900d7d2e2fc31a4402aea5d9eb0c132c3, not stripped

**Comment by Maijin** [comment]
```
            a:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, str.This                                        ; "This " @ 0x400724                                                                                                                                                    
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            b:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, 0x40072a                                                                                                                                                                                                                
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            c:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, 0x40072e                                                                                                                                                                                                                
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            d:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, str.example                                     ; "example " @ 0x400732                                                                                                                                                 
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            e:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, str.usecase                                     ; "usecase " @ 0x40073b                                                                                                                                                 
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            f:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, str.for                                         ; "for " @ 0x400744                                                                                                                                                     
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            g:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            h:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, 0x400749                                                                                                                                                                                                                
              mov eax, 0                                                                                                                                                                                                                       
              call sym.imp.printf                                      ;[1]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
            i:                                                                                                                                                                                                                                 
              push rbp                                                                                                                                                                                                                         
              mov rbp, rsp                                                                                                                                                                                                                     
              mov edi, 0x40074d                                                                                                                                                                                                                
              call sym.imp.puts                                        ;[2]                                                                                                                                                                    
              pop rbp                                                                                                                                                                                                                          
              ret                                                                                                                                                                                                                              
```

**Comment by Maijin** [comment]
```
╒ (fcn) sym.a 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x00400638 (sym.a)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, str.This                                        ; "This " @ 0x400724                                                                                                                                                    
│             mov eax, 0                                                                                                                                                                                                                       
│             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.b 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x00400642 (sym.b)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, 0x40072a                                                                                                                                                                                                                
│             mov eax, 0                                                                                                                                                                                                                       
│             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.c 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x0040064c (sym.c)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, 0x40072e                                                                                                                                                                                                                
│             mov eax, 0                                                                                                                                                                                                                       
│             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.d 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x00400656 (sym.d)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, str.example                                     ; "example " @ 0x400732                                                                                                                                                 
│             mov eax, 0                                                                                                                                                                                                                       
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.e 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x00400660 (sym.e)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, str.usecase                                     ; "usecase " @ 0x40073b                                                                                                                                                 
│             mov eax, 0                                                                                                                                                                                                                       
│             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.f 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x0040066a (sym.f)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, str.for                                         ; "for " @ 0x400744                                                                                                                                                     
│             mov eax, 0                                                                                                                                                                                                                       
│             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.g 6                                                                                                                                                                                                                                
│           ; CALL XREF from 0x00400674 (sym.g)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.h 21                                                                                                                                                                                                                               
│           ; CALL XREF from 0x0040067e (sym.h)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, 0x400749                                                                                                                                                                                                                
│             mov eax, 0                                                                                                                                                                                                                       
│             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret                                                                                                                                                                                                                              
╒ (fcn) sym.i 16                                                                                                                                                                                                                               
│           ; CALL XREF from 0x00400688 (sym.i)                                                                                                                                                                                                
│             push rbp                                                                                                                                                                                                                         
│             mov rbp, rsp                                                                                                                                                                                                                     
│             mov edi, 0x40074d                                                                                                                                                                                                                
│             call sym.imp.puts                                        ;[2]                                                                                                                                                                    
│             pop rbp                                                                                                                                                                                                                          
╘             ret

**Comment by radare** [comment]
Is this because the strings are too short?



> On 16 Sep 2015, at 18:42, Maijin <notifications@github.com> wrote:
> 
> ╒ (fcn) sym.a 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x00400638 (sym.a)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, str.This                                        ; "This " @ 0x400724                                                                                                                                                    
> │             mov eax, 0                                                                                                                                                                                                                       
> │             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.b 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x00400642 (sym.b)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, 0x40072a                                                                                                                                                                                                                
> │             mov eax, 0                                                                                                                                                                                                                       
> │             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.c 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x0040064c (sym.c)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, 0x40072e                                                                                                                                                                                                                
> │             mov eax, 0                                                                                                                                                                                                                       
> │             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.d 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x00400656 (sym.d)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, str.example                                     ; "example " @ 0x400732                                                                                                                                                 
> │             mov eax, 0                                                                                                                                                                                                                       
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.e 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x00400660 (sym.e)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, str.usecase                                     ; "usecase " @ 0x40073b                                                                                                                                                 
> │             mov eax, 0                                                                                                                                                                                                                       
> │             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.f 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x0040066a (sym.f)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, str.for                                         ; "for " @ 0x400744                                                                                                                                                     
> │             mov eax, 0                                                                                                                                                                                                                       
> │             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.g 6                                                                                                                                                                                                                                
> │           ; CALL XREF from 0x00400674 (sym.g)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.h 21                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x0040067e (sym.h)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, 0x400749                                                                                                                                                                                                                
> │             mov eax, 0                                                                                                                                                                                                                       
> │             call sym.imp.printf                                      ;[1]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> ╒ (fcn) sym.i 16                                                                                                                                                                                                                               
> │           ; CALL XREF from 0x00400688 (sym.i)                                                                                                                                                                                                
> │             push rbp                                                                                                                                                                                                                         
> │             mov rbp, rsp                                                                                                                                                                                                                     
> │             mov edi, 0x40074d                                                                                                                                                                                                                
> │             call sym.imp.puts                                        ;[2]                                                                                                                                                                    
> │             pop rbp                                                                                                                                                                                                                          
> ╘             ret                                                                                                                                                                                                                              
> —
> Reply to this email directly or view it on GitHub.
>

**Comment by Maijin** [comment]
"xrefs" is 5 chars whereas "for " is only 4 chars

**Comment by yetmorecode** [comment]
Looks to me like "xrefs" is not actually in the binary?! (g() is actually missing the printf (typo?)). Then b, c, h and i on the other hand only having length 3 strings.

**Comment by Maijin** [comment]
Yep in fact you right it's probably size stuff
