### ISSUE TITLE
m68k registers only partially working

### ISSUE THREAD

**Issue by fabrice-martinez** [radare/radare2#13461]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | m68k
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21249 @ windows-x86-64 git.3.3.0-222-g4000e7bf7 commit: 4000e7bf72249bc8a1d82a6d2f28a57d514ad01a build: 22/03/2019__ 9:11:32,53

### Expected behavior

drl, dr and drj commands all output a list of registers.

### Actual behavior

drl works as expected but dr and drj give empty answers. 
This results under Cutter in an empty register window.

[0x00000000]> drl  
d0  
d1  
d2  
d3  
d4  
d5  
...
(abridged)
...
[0x00000000]> dr
[0x00000000]> drj
{}

### Steps to reproduce the behavior 

Load any file with architecture set to m68k, type the commands.

**Comment by radare** [comment]
What happens if you specify the bitsize as argument? Dr 16 drj 16?

**Comment by fabrice-martinez** [comment]
dr 32 works but drj 32 is still empty. The m68k architecture is always 32 bits (register size) and big endian.

[0x00000000]> dr
[0x00000000]> dr 16
[0x00000000]> dr 32
d0 = 0x00000000
d1 = 0x00000000
d2 = 0x00000000
d3 = 0x00000000
d4 = 0x00000000
d5 = 0x00000000
...
(abridged)
...
[0x00000000]> drj 32
{}

**Comment by radare** [comment]
do you want to try to fix this?

**Comment by fabrice-martinez** [comment]
It works by specifying -b 32 on the command line.
I did not understand that I have to specify the bit size since m68k is always 32.
This is a bit confusing but it works fine that way.
Thanks!

Now to implement ESIL...

**Comment by fabrice-martinez** [comment]
Reopening briefly.

This is fixed easily by changing all instances of ".bits = 16 | 32," to ".bits = 32," in both libr/anal/p/anal_m68k_cs.c and libr/asm/p/asm_m68k_cs.c

Do you want me to submit a pull request for that ?

**Comment by radare** [comment]
yes

**Comment by fabrice-martinez** [comment]
Pull request submitted, thanks for your help!
