### ISSUE TITLE
Cannot resolve type 'type.96'

### ISSUE THREAD

**Issue by radare** [radare/radare2#13507]
```
[0x00000000]> cat mipi.h
struct mipi_dsi_cmd {
 int size;
 char *payload;
 int word;
};
[0x00000000]> to mipi.h
[0x00000000]> ts
mipi_dsi_cmd
[0x00000000]> tl mipi_dsi_cmd = $$
[0x00000000]> pd 20
Cannot resolve type 'type.96'
(mipi_dsi_cmd)
 payload : 0x00000000 = ""
    word : 0x00000001 = 0
            0x0000000c      0000           add byte [rax], al
            0x0000000e      0000           add byte [rax], al
            0x00000010      0000           add byte [rax], al
```

**Comment by XVilka** [comment]
It is an interesting bug. If you change the name of the `int size` type to anything else, e.g. `int ssize` it works.
The explanation is because it creates SDB key `struct.mipi_dsi_cmd.size` which is reserved for storing size of the structure.

**Comment by sivaramaaa** [comment]
OMG it's scary ,  so what do suggest @XVilka ??

**Comment by XVilka** [comment]
@sivaramaaa just rename `.size` to something illegal in C, e.g. `.0size`.

**Comment by sivaramaaa** [comment]
:) OK , @radare are ok with this approach !

**Comment by radare** [comment]
I would go for a special char. Something like ! Or : what do you think? Will read better than 0

**Comment by sivaramaaa** [comment]
Yup sgtm , then we can go with `!size`         :+1:

**Comment by radare** [comment]
this is important

**Comment by XVilka** [comment]
Using `!size` breaks too many things, I fallback to `0size`. This can be fixed later.

**Comment by radare** [comment]
Ok

**Comment by XVilka** [comment]
No worries, I made `!size` work too.

**Comment by XVilka** [comment]
Closed by https://github.com/radare/radare2/commit/726e15054cf15dd95cb2bd88d404e3fc9b1fa840
