### ISSUE TITLE
check r_assert warnings on all commits

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#13515]
Before, we didn't enable r_assert warnings tests in travis on all commits (`CFLAGS="-DR2_ASSERT_STDOUT=1"`) because there were many many errors, but right now it should be safe to assume we don't have those errors anymore or, if there are, they should be fixed.

**Comment by radare** [comment]
do you have a link for those logs?

**Comment by ret2libc** [comment]
Done in https://github.com/radare/radare2/commit/aaea46bdbc1cee6ec954b37c7593789c09d04994
