### ISSUE TITLE
Kernelcache plugin skips kernel entry point

### ISSUE THREAD

**Issue by Siguza** [radare/radare2#13519]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.12, x86_64h
| File format of the file you reverse (mandatory)      | Mach-O (Kernelcache plugin tho)
| Architecture/bits of the file (mandatory)            | arm64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21446 @ darwin-x86-64 git.3.3.0-269-g3f4580b03 commit: 3f4580b0319ec4a4bcaa2fc8fbd608be948ec054 build: 2019-03-26__21:35:31

### Expected behavior

Running `r2 -F kernelcache` against an arm64 iOS kernel finds all kext entry points, as well as that of the main kernel, which is also the default seek address.

### Actual behavior

r2/kernelcache finds all kexts entry points, but "forgets" the main kernel one's (doesn't appear in `ie` command). Default seek address is just the entry point of the first kext.

### Steps to reproduce the behavior

Run `r2 -F kernelcache` against the binary in here: [kernel.zip](https://github.com/radare/radare2/files/3010852/kernel.zip) (iPhone XR, iOS 12.2)  
Entry point for that particular bin would be `0xfffffff0079d0190`.

**Comment by mrmacete** [comment]
yeah so apparently the right way to get the main entrypoint is to properly parse the `LC_UNIXTHREAD` command, fixing!
