### ISSUE TITLE
"o" in "V" mode is broken

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#13534]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 183 @ linux-x86-64 git.3.4.0-git commit: 555de8d086a6c202cb22a91ee593a48004bbd2cf build: 2019-03-28__12:50:24

### Expected behavior
When I press `o` while in `V` mode, it should prompt me for a seek location.

### Actual behavior
It does not.

### Steps to reproduce the behavior 
- Open any binary
- `V`
- `s` (nothing happens)

**Comment by radare** [comment]
its now 'g', like iit iis in ghidra, ida, binary ninja, ollydbg, x64dbg and others, check the help message and you'll see

**Comment by radare** [comment]
(and cutter)
