### ISSUE TITLE
Isolate `pf` parser and separate from printing of the format

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#13559]
To be able to provide different types of the output:
- [x] default one
- [x] r2 commands
- [x] JSON output
- [x] C output (so would be able to produce C type back from type parsed into `pf` format)

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
[0x1000011e8]> pfj xxi foo bar cow
[{"name":"foo","type":"x","offset":4584,"value":-443987883},{"name":"bar","type":"x","offset":4588,"value":1447122753},{"name":"cow","type":"i","offset":4592,"value":1413567809}]
[0x1000011e8]>

**Comment by radare** [comment]
its just C whats needed, json was already there

**Comment by radare** [comment]
we also have flags output format:

```
[0x1000011e8]> pf* xxi foo bar cow
f foo=0x1000011e8
fl 4 @ 0x1000011e8
Cd 4 @ 0x1000011e8
f bar=0x1000011ec
fl 4 @ 0x1000011ec
Cd 4 @ 0x1000011ec
f cow=0x1000011f0
fl 4 @ 0x1000011f0
Cd 4 @ 0x1000011f0
[0x1000011e8]>
```

**Comment by radare** [comment]
in the testsuite we should have back and forth tests to ensure the format string into C and that go back into pf, maybe what it will be good to have is pf to sdb to be reused by types

**Comment by radare** [comment]
Thanks @oxcabe !!
