### ISSUE TITLE
Interrupt handler function can't be renamed

### ISSUE THREAD

**Issue by BlaCoiso** [radare/radare2#13557]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04/x86/32
| File format of the file you reverse (mandatory)      | none
| Architecture/bits of the file (mandatory)            | x86/16
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21421 @ linux-x86-32 git.3.3.0-302-g20b56ef commit: 20b56efda8ec2f138db2f8f83ddeef1cd44030be build: 2019-03-29__20:00:16

### Expected behavior
analysing interrupt handlers works properly and the function can be renamed

### Actual behavior
`Cannot find function 'name' at 0x00000000` is displayed when trying to rename the function

### Steps to reproduce the behavior 
`r2 -ax86 -b16 -c'wx cf;af name' -`

### Additional Logs, screenshots, source-code,  configuration dump, ...
https://github.com/radare/radare2/blob/20b56efda8ec2f138db2f8f83ddeef1cd44030be/libr/core/cmd_anal.c#L2211

**Comment by radare** [comment]
This is fixed
