### ISSUE TITLE
New write command to assemble instruction and fill with nops

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#13586]
**Is your feature request related to a problem? Please describe.**

Currently, when overwriting an instruction using the `wa` command, we sometime want to write an instruction which is shorter that the already existing one. Say, replace a 6 bytes instruction with a 5 bytes instruction. The 6th byte if the previous instruction would still be there and will cause an invalid disassembly. 

**Describe the solution you'd like**

A popular solution is to fill the gaps with NOP instruction(s). The new command will write the instruction and follow these steps:
1. If the new instruction is larger than it will fails 
2. If the new instruction is shorter, fill the gaps with NOP instructions (either before or after the new instruction) 
3. If both instructions have the same size, simple replace the old one with the new

For example,say I have the following instruction that has 6 bytes:

```
12 34 56 78 90 00              jo 0x1234
```

And I want to replace it with a new instruction which have only 5 bytes:

```
12 34 56 78 00              jmp 0x1234
```

Than we have an extra byte that we need to fill with NOP.

**Comment by radare** [comment]
im working on this

**Comment by ITAYC0HEN** [comment]
While you at it, there's a famous OllyDbg feature for patching an instruction with NOPs. Called "fill with NOPs" so it takes the instruction to be patched and replaces it with X NOP(s) where X is the length of the instruction

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/13588

**Comment by radare** [comment]
Can you add some tests please?

**Comment by ITAYC0HEN** [comment]
Yup :) will probably do this tomorrow

**Comment by radare** [comment]
Too late.

**Comment by radare** [comment]
Nvm :) thanks!
