### ISSUE TITLE
aflm and aflmj seem broken

### ISSUE THREAD

**Issue by JavierYuste** [radare/radare2#13590]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21333 @ linux-x86-64 git.3.3.0-325-gf8dec8396 commit: f8dec83968ac5ea14cb1d432f9d6c06976961265 build: 2019-03-31__21:11:26

### Expected behavior
It should list functions in makefile style

### Actual behavior
It crashes (segmentation fault)

### Steps to reproduce the behavior 
![image](https://user-images.githubusercontent.com/35402702/55295182-67d61400-540a-11e9-8918-e61da6bcc1c8.png)

**Comment by radare** [comment]
thats a regression. just fixed it now. thanks

**Comment by radare** [comment]
i have pushed a test to verify that it doesnt gets broken

**Comment by JavierYuste** [comment]
Nice! Thanks for fixing it
