### ISSUE TITLE
What about adding some newlines

### ISSUE THREAD

**Issue by radare** [radare/radare2#13607]
<img width="1677" alt="Screenshot 2019-04-01 at 23 54 19" src="https://user-images.githubusercontent.com/917142/55362179-8a832e00-54d9-11e9-8de7-674f6707a852.png">

i understand the lack of newlines in function definitions. but for structs and enums it will be doable

**Comment by StephaneLeveugle** [comment]
Hi, I'm going to work on this :)

**Comment by radare** [comment]
Solved already
