### ISSUE TITLE
Add command to list all the functions with no registered signature

### ISSUE THREAD

**Issue by radare** [radare/radare2#13617]
We are adding types by hand when we need them. but we are missing many times because there's no way to see whats missing until we spot the wrong disasm. THe idea for this issue is to add a command to list all the functions (maybe just imports) that have no function signature registered.

**Comment by sivaramaaa** [comment]
@radare I think this can be closed ,  We have this functionality already 

Set this `e anal.types.verbose = true ` and on every analysis `aaa`  you will get loads of function signature missing output

AFAIR @Maijin  actually created huge list of function missing signature cases using this config var !

**Comment by radare** [comment]
thanks! didnt knew that! will add some more missing function signatures now :)
