### ISSUE TITLE
cmd.hexcursor not working fine with selections

### ISSUE THREAD

**Issue by radare** [radare/radare2#13628]
notice the current cursor have is not properly pointed, also its executed on every row

![Screenshot 2019-04-04 at 17 35 54](https://user-images.githubusercontent.com/917142/55568534-268e7e80-5700-11e9-9ceb-5beb5d07dd96.png)

**Comment by radare** [comment]
ping @deepakchethan

**Comment by deepakchethan** [comment]
ping back @radare, I will work on it tomorrow since I definitely have to pass tomorrows exam. Could you tell me how to reproduce this?

**Comment by radare** [comment]
e cmd.hexcursor=?E hihi
v
c # toggle cursor
JJJ # select some
