### ISSUE TITLE
Nested unions are listed as struct in tuc

### ISSUE THREAD

**Issue by StephaneLeveugle** [radare/radare2#13633]
# Nested unions are listed as struct in tuc

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21292 @ windows-x86-64 git.3.4.1-21-g29b4a5e31 commit: 29b4a5e31afa2c2b8b647ccd59463e88eaa5f11a build: 05/04/2019__ 6:21:29,29

### Steps to reproduce the behavior
```
[0x140001753]> "td union foo { int a; union bar { float b; int c; }; };"
[0x140001753]> tuc
union bar {float b; int32_t c;};
union foo {int32_t a; struct bar ;};
```
### Expected behavior

Inside foo bar is listed as struct, but it's a union

**Comment by radare** [comment]
ping, will be good for 3.6
