### ISSUE TITLE
Is it possible to determine the number of parameters in binary function?

### ISSUE THREAD

**Issue by yasong** [radare/radare2#13658]
In binary, parameters can be passed by register or stack. Is it possible to determine the parameters number in binary function? Are  there some binary analysis tools that can do this?
I want to know the accurate parameters number of binary function to do some security analysis. 
Thank you.

**Comment by radare** [comment]
Yes. R2 does that

**Comment by yasong** [comment]
@radare Sorry for bothering you. Could you tell me the tool used in R2? Thank you.
