### ISSUE TITLE
Null pointer dereference in objc_build_refs()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#13659]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04 x64
| File format of the file you reverse (mandatory)      | Mach-O
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21318 @ linux-x86-64 git.3.4.1-32-g44eb2e26e commit: 44eb2e26e4fef1dd15a877019f417ea0922ea13b build: 2019-04-08__15:03:54

### Expected behavior

Dissasembly of file or error message.

### Actual behavior

SIGSEGV in ASAN build.

### Steps to reproduce the behavior 
- Download: https://github.com/radare/radare2-regressions/pull/1778
- Run r2 with file `r2 -A r2_nullptr_objc_build_refs`

### Additional Logs, screenshots, source-code,  configuration dump, ...

```
==12290==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7fd4f2794e19 bp 0x7ffeb5c65490 sp 0x7ffeb5c651e0 T0)
==12290==The signal is caused by a READ memory access.
==12290==Hint: address points to the zero page.
    #0 0x7fd4f2794e18 in objc_build_refs radare2/libr/core/anal_objc.c:110:35
    #1 0x7fd4f2794e18 in objc_find_refs radare2/libr/core/anal_objc.c:174
    #2 0x7fd4f2794e18 in cmd_anal_objc radare2/libr/core/anal_objc.c:240
    #3 0x7fd4f245a280 in cmd_anal_all radare2/libr/core/./cmd_anal.c:7980:5
    #4 0x7fd4f245a280 in cmd_anal radare2/libr/core/./cmd_anal.c:8803
    #5 0x7fd4f267d3d0 in r_cmd_call radare2/libr/core/cmd_api.c:246:10
    #6 0x7fd4f2516b3f in r_core_cmd_subst_i radare2/libr/core/cmd.c:3040:12
    #7 0x7fd4f241ee22 in r_core_cmd_subst radare2/libr/core/cmd.c:2026:9
    #8 0x7fd4f2415a4a in r_core_cmd radare2/libr/core/cmd.c:3774:9
    #9 0x7fd4ee0c095c in r_main_radare2 radare2/libr/main/radare2.c
    #10 0x7fd4ed882b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #11 0x5634aa273219 in _start (/usr/local/bin/radare2+0x1d219)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV radare2/libr/core/anal_objc.c:110:35 in objc_build_refs
==12290==ABORTING
```

**Comment by radare** [comment]
thanks its fixed now
