### ISSUE TITLE
Android: CANNOT LINK EXECUTABLE "r2": library "libr_main.so" not found

### ISSUE THREAD

**Issue by RusJJ** [radare/radare2#13654]
Using the latest radare2 from Google Play. Android 9, rooted. Termux or console.
Trying to use WebView/Browser, but it shows radare2 webserver failed to start.

**Comment by radare** [comment]
google play version was deprecated 3 years ago, just use termux. and this one works fine

**Comment by radare** [comment]
if you use the termux pkg from adb you will have to set a bunch of env vars because its not a statically linked build, you can do a static build too
