### ISSUE TITLE
Rename aa* into aaS or aass or aas2

### ISSUE THREAD

**Issue by radare** [radare/radare2#13669]
maybe that affects aaa?

**Comment by Maijin** [comment]
aa* is not used in aaa

**Comment by radare** [comment]
which name do you think is best for this? proposals?

**Comment by Maijin** [comment]
No idea what does aa* right now but it doesn't output aa in r2 commands. For the name i don't know.

**Comment by radare** [comment]
thats why it should be renamed. its not consistent with the use of '*'

**Comment by radare** [comment]
i did that already
