### ISSUE TITLE
Windows binaries missing for 3.4.x

### ISSUE THREAD

**Issue by schlamar** [radare/radare2#13675]
There are no binary releases for 3.4.x at http://radare.mikelloc.com/list and at https://github.com/radare/radare2/releases.

**Comment by radare** [comment]
Fixed the issue in here https://github.com/radare/radare2-release/commit/1cb7b53a81e6b14ca63d4528e43d71672313e899

Windows build in here http://radare.mikelloc.com/get/3.4.1/radare2-msvc_64-3.4.1.zip
