### ISSUE TITLE
Including r2's headers

### ISSUE THREAD

**Issue by ivanstepanovftw** [radare/radare2#13679]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Manjaro 18.0.4, pacman
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0 0 @ linux-x86-64 git.3.3.0 commit: HEAD build: 2019-03-06__21:50:39

### Expected behavior
Include header and use radare functions in C++ project.

### Actual behavior
Compile-time error
```
/usr/include/libr/r_bin.h:4:10: fatal error: r_util.h: No such file or directory
 #include <r_util.h>
          ^~~~~~~~~~
```

### Steps to reproduce the behavior 
C++
```cpp
#include <libr/r_bin.h>
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
I'd like to suggest to use full library path, eg instead
```c
#include <r_util.h>
```
use
```c
#include <libr/r_util.h>
```

**Comment by radare** [comment]
use pkg-config and you'll have no problems to include anything, you have to add the libr directory in the include path, this is not suposed to be included like this, glib

**Comment by ivanstepanovftw** [comment]
Is there anything in plans with CMake?

**Comment by ivanstepanovftw** [comment]
OK, who uses CMake and wanted to use radare API:
```cmake
find_package(PkgConfig)
pkg_check_modules(R2 REQUIRED
        r_anal
        r_asm
        r_bin
        r_bp
        r_config
        r_cons
        r_core
        r_crypto
        r_debug
        r_egg
        r_flag
        r_fs
        r_hash
        r_io
        r_lang
        r_magic
        r_parse
        r_reg
        r_search
        r_socket
        r_syscall
        r_util
        )

target_include_directories(... ${R2_INCLUDE_DIRS})
target_link_libraries(... ${R2_LIBRARIES})
```
Thank you!

**Comment by TheNewJavaman** [comment]
For other people who have this issue:

The list above may not be the same as your installation. Use this to generate an updated list of r2 modules:

```shell
pkg-config --list-all | grep r_ | cut -d' ' -f1
```
