### ISSUE TITLE
Display variables value in the disasm view

### ISSUE THREAD

**Issue by radare** [radare/radare2#13672]
also the new behaviour that enables asm.var.summary if the lines is short its a problem for this, we should be able to have an asm.summaryr=2 or -1 to make that behaviour consistent up to the user

<img width="753" alt="Screenshot 2019-04-09 at 01 50 38" src="https://user-images.githubusercontent.com/917142/55764004-f0d3f780-5a69-11e9-89fe-7b14d31ed33d.png">

**Comment by radare** [comment]
maybe as an alternative visual stack pirnt format

**Comment by Vane11ope** [comment]
hang on, what's the problem here btw? i see no problem so far with automatic manipulation of asm.var.summary yet?

**Comment by radare** [comment]
the asm.var.ssummary show the args/vars types and names, but not their values

**Comment by Vane11ope** [comment]
ah right ok thanks :)
