### ISSUE TITLE
Kill PICK and RPICK esil operations

### ISSUE THREAD

**Issue by condret** [radare/radare2#13689]
They are not needed and make analysis unnecessary hard

**Comment by XVilka** [comment]
@condret one more thing - please remove the commands you kill from the [ESIL chapter](https://github.com/radare/radare2book/blob/master/disassembling/esil.md) of the [Radare2 book](https://github.com/radare/radare2book).

**Comment by XVilka** [comment]
Or at least create an issues in that repo, so that we are keeping track what is actually implemented.

**Comment by radare** [comment]
its done i think

**Comment by radare** [comment]
we can open an issue in the r2book to kill rpick, but i think its better to re-read the whole book and rewrite everything we see. so much changes

**Comment by radare** [comment]
was rpick handled in esil.rs?

**Comment by condret** [comment]
ok, will look at the book
