### ISSUE TITLE
Improvements in panels

### ISSUE THREAD

**Issue by radare** [radare/radare2#13697]
* [ ] Get keys and panels ideas from https://github.com/JeremyBlackthorne/Ghidra-Keybindings
* [ ] Default view should contain 3 frames and look good at 80x25
* [x] nN do thee same, i expect to make N create a new frame splitting horizontal the current one
* [x] support cursor in hexdump modes
* [ ] _ key should do ~... on current frame contents.. or at leesat find a way to have current and this actions
* [x] HL should be scrolling faster like JK does already but horizontally inside frames
* [x] Symbols and Functions frames does not scroll
* [x] Handle tab key in 'w' mode to select next/prev frame
* [x] Toggle caching of frame contents
* [x] pP doesnt work in zoom mode
* [x] Use [X] instead of [x] to match the key to close the frame
* [x] ; key should query to enter a comment. like it does in visual
* [x] Comments panel does not scroll
* [ ] I miss a notes panel, maybe using the project panels? (Pn, Pn - (uses cfg.editor))
* [x] Add an entry in the menubar to show the entropy with p== instead of p= (entropy fire)
* [x] When pressing u or U do not sleep 1s with an error message that cant undo/redo
* [x] When press 'X' for a whihle (just 2 times) and there are only 2 panels it cannot delete more frames and new ones are wrongly placed in layout (corrupted state)
* [x] Add View->Summary to render the output of pdsf
* [x] Press 'i' to insert hexpairs, string or assembly depending on view frame (or user specified by a 2nd key after i)
* [x] tab should rotate between frames only (not the menubar, we have the 'm' key to reach that)
* [x] pressing enter when the menubar is selected, but no menu opened executes an action unexpectedly (imho the menu should be always opened when the menubar is selected) (see issue above)
As a side note i think it will be cool to have a way to define custom menus, maybe the plugins or scripts can add their own menu in there, or just placed as a submenu of "Plugins" or "Other"
* [x] Pressing 'C' changes colors, but scr.color doesnt changes at all. should the same code as visual.c
* [x] pressing 'c' should toggle the cursor mode (not c q c q c q)
* [x] pressing 'w' should toggle window mode (not w q w q w q)
* [x] Focus first frame (or last frame selected) after pressing enter in the menubar action
* [x] Add support for tabs (see how it's done in visual.c (press 't')
* [x] Handle ':' key in cursor and window modes too
* [ ] Also sometimes i get into this broken state:

<img width="1680" alt="Screenshot 2019-04-11 at 05 36 05" src="https://user-images.githubusercontent.com/917142/55929153-bad67500-5c1b-11e9-8aa1-7d1123c21d10.png">

**Comment by Vane11ope** [comment]
by the way you can already insert hexpairs in some of panels such as disassembly, hex dump, stack, and register if there are not more by c->i. you can't elaborate the detail of the edit by second key just yet tho.

**Comment by Vane11ope** [comment]
and also, that ansi_crop bug, I don't know if i can fix that soon. I researched a lot but still i don't know. I hate color codes.

**Comment by Vane11ope** [comment]
omg X key does not even behave right in so many cases let me fix all

**Comment by radare** [comment]
i think all the points are fixed now :D good job!

**Comment by radare** [comment]
just improve the default layouts probably to make it look good on 80x24
