### ISSUE TITLE
Search range isn't working properly for /c and /ce

### ISSUE THREAD

**Issue by qwuau06** [radare/radare2#13730]
# Search range isn't working properly for /c and /ce

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ArchLinux x86-64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 32bit ARM
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21680 @ linux-x86-64 git.3.4.1-92-g6051c55b2 commit: 6051c55b2648f6395f7e2769461b78c2957a88bb build: 2019-04-12__13:27:58

### Expected behavior
Searching range are bound by search.from and search.to
### Actual behavior
Only search.from works properly. It always search until the end of the current function.
This happens when searching for esil /ce and asm code /c, but /a works fine.
### Steps to reproduce the behavior 
Asciinema link: https://asciinema.org/a/DjJefUdzMKor5JKce5MtOUdF0
both /c and /ce exceeds searching range.
/a works within range.

**Comment by radare** [comment]
reproducer to be added to the r2r testsuite using the mac-ls binary
```
r2 -qc 'e search.from=0x100004421 ;e search.to=0x1000044ed; e search.in=raw;/ce rax,=' /bin/ls
```
can you add a test in the radare2-regressions repo once the PR gets merged?

**Comment by qwuau06** [comment]
Sure. i'll do that.

**Comment by radare** [comment]
merged . fixed in https://github.com/radare/radare2/pull/13739
