### ISSUE TITLE
SPECIAL_SYM TLDR

### ISSUE THREAD

**Issue by radare** [radare/radare2#13760]
Use 4 letter for this thing in `is`

![IMAGE 2019-04-15 12:44:19](https://user-images.githubusercontent.com/917142/56126861-3027aa00-5f7c-11e9-8383-821068b41893.jpg)

**Comment by ret2libc** [comment]
I think anything too short would be not understandable by users.

What about `SPEC_SYM`?

**Comment by radare** [comment]
then just uses SPEC, all the other keywords are 4 letter, we should stick to something visually consistent or i'll cry again

**Comment by ret2libc** [comment]
they are not all 4. There is also `NOTYPE`. But ok for `SPEC`.

**Comment by radare** [comment]
then SPECIAL or SPCL. because SPEC looks more like specifications

**Comment by ret2libc** [comment]
`SPCL`. Done! :D

**Comment by radare** [comment]
then NOTYPE into NTYP? looks really messed up, more like stocks than a real word

**Comment by ret2libc** [comment]
Mh... NOTYPE is already ok. It is correctly aligned.

**Comment by radare** [comment]
@ret2libc can you fix this issue? im fine with NOTYPE too
