### ISSUE TITLE
aaa (aaft) - Stack isn't initialized

### ISSUE THREAD

**Issue by GustavoLCR** [radare/radare2#13776]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | WSL Debian x64 (buster)
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21907 @ linux-x86-64 git.3.4.1-142-ge4c9b1053 commit: e4c9b10533dbe945c2f7412975401a853d90b5ef build: 2019-04-15__21:43:39

### Expected behavior
No errors

### Actual behavior
Multiple 
```
Try running aei and aeim commands before aft for default stack initialization
Stack isn't initialized.
```
`aei` and `aeim` seems to have no effect

### Steps to reproduce the behavior 
`$ r2 ls`
`aaa`

### Additional Logs, screenshots, source-code,  configuration dump, ...

[ls.zip](https://github.com/radare/radare2/files/3082561/ls.zip)

**Comment by radare** [comment]
aei and aeim work as expected. just pushed a pr that solves that issue

**Comment by radare** [comment]
waiting for your solution

btw got another bin that reproduces the issue.

[NoREpls.zip](https://github.com/radare/radare2/files/3099159/NoREpls.zip)
