### ISSUE TITLE
Add an option to use the popup autocompletion instead of the current one in RCons

### ISSUE THREAD

**Issue by radare** [radare/radare2#13795]
Like it's done in vg

<img width="344" alt="Screenshot 2019-04-17 at 12 30 24" src="https://user-images.githubusercontent.com/917142/56281305-98a59100-610c-11e9-85f2-2a8ffc846e43.png">

**Comment by radare** [comment]
And use the theme colors

**Comment by XVilka** [comment]
Related: https://github.com/radare/radare2/issues/8476

**Comment by XVilka** [comment]
@deepakchethan @radare can be closed now I guess?

**Comment by radare** [comment]
yes
