### ISSUE TITLE
Incorrect usage of byte order/endianess

### ISSUE THREAD

**Issue by mrnuke** [radare/radare2#138]
I came across this code in libr/util/num.c

	R_API ut16 r_num_ntohs (ut16 foo) {
	#if LIL_ENDIAN
		ut8 *p = (ut8*)&foo;
		foo = p[1] | p[0] << 8;
	#endif
		return foo;
	}

When the code cares about byte order, it is most certainly wrong. A lot of bugs will stem from this in the future. int16 is simple, but let's look at int32. The proper way to read a BE uint32_t on a LE machine is:

	((b[0] << 24) | (b[1] << 16) | (b[2] << 8) | (b[3] << 0));

The proper way to read it on a BE machine is:

	((b[0] << 24) | (b[1] << 16) | (b[2] << 8) | (b[3] << 0));

And the proper way to read it on a mixed-endian machine is:

	((b[0] << 24) | (b[1] << 16) | (b[2] << 8) | (b[3] << 0));

They are all the same. Host byte order does _not_ matter. For more details see:
http://commandcenter.blogspot.com/2012/04/byte-order-fallacy.html

**Comment by Maijin** [comment]
thanks @zamaudio
