### ISSUE TITLE
Allow setting flag->realname from commands

### ISSUE THREAD

**Issue by Siguza** [radare/radare2#13816]
**Is your feature request related to a problem? Please describe.**  
I'm trying to resymbolicate large C++ code bases, and the only way I know of importing symbols to r2, short of writing a custom plugin, is via flags. Now flags filter our special characters in their "normal" name, but have a "realname" to preserve those. Only sadly, it seems you cannot set this realname from the command line or from scripts, and hence this:

    OSOrderedSet::initWithCapacity(unsignedint,int(*)(OSMetaClassBaseconst*,OSMetaClassBaseconst*,void*),void*)

turns into this:

    sym.OSOrderedSet::initWithCapacity_unsignedint_int____OSMetaClassBaseconst__OSMetaClassBaseconst__void___void

**Describe the solution you'd like**  
I'd like an additional flag command, with which the `realname` field of a flag can somehow be set from the command line and scripts.

**Comment by radare** [comment]
I would say fN or fnn command for this. Can you send a PR?

**Comment by Siguza** [comment]
Closing this as #13824 was merged.
