### ISSUE TITLE
Use aap in aaa

### ISSUE THREAD

**Issue by radare** [radare/radare2#13825]
Include aap in aaaa

Check this bin
[NoREpls.zip](https://github.com/radare/radare2/files/3099163/NoREpls.zip)

**Comment by Maijin** [comment]
I'll try to perform aap in aaa after everything to see what's the impact in r2r again

**Comment by deepakchethan** [comment]
Already done on #13543 right

**Comment by Maijin** [comment]
Actually we discussed adding it even in normal binary but we need to test again on r2r.

Also, @deepakchethan your solution doesn't work when the binary is opened with `-n` could you check to add that?

**Comment by deepakchethan** [comment]
> Actually we discussed adding it even in normal binary but we need to test again on r2r.
> 
> Also, @deepakchethan your solution doesn't work when the binary is opened with `-n` could you check to add that?

I will look into it @Maijin

**Comment by radare** [comment]
ping?

**Comment by Maijin** [comment]
Don't close it, it's not done. I'll look at that when I have time

**Comment by radare** [comment]
@Maijin will you fix this before sunday? i touhgh aap was already called in aaa. so whats misssing?

**Comment by Maijin** [comment]
It's called in `aaaa` not in `aaa`

**Comment by radare** [comment]
lgtm

**Comment by radare** [comment]
so? @Maijin

**Comment by Maijin** [comment]
I think @deepakchethan said he will look into it
