### ISSUE TITLE
LEA assembler issues

### ISSUE THREAD

**Issue by radare** [radare/radare2#13835]
* [ ] lea rdi, [rip + 0x1011] -> should be 488d3d11100000 -> but we get 488db811100000 -> which is lea rdi, [rax + 0x1011]
* [ ] $ rasm2 -b64 -d `rasm2 'lea rax, [rip + 0xff9]'` => lea rcx, [rax + 0xff9]

**Comment by nongiach** [comment]
I just experienced this issue,
glad that you are already working on it.
Keep it up, great work !!!
Thx
