### ISSUE TITLE
Regression - analyze command fails to find any functions in latest trunk (7ff265257...)  (for at least mips+mips.cs)

### ISSUE THREAD

**Issue by pastcompute** [radare/radare2#1384]
Hi,

just pulled the latest trunk and after `git clean -xfd` and subsequent rebuild discovered that the `aa` command seems to be no longer working - i.e. `afl` returns no output.  I reverted to my `HEAD@{1}` and clean and rebuilt everything worked again, so the regression occurred somewhere between 2014-09-03 (commit e161a915d...) and now (7ff265257...) 

Problem occurs with both `-a mips` and `-a mips.cs`

I can see that `aa` has changed slightly to be an alias for another command, but the main help for `aa` still states `analyze all (fcns + bbs)` - is there a better way to get the same behaviour as what `aa` used to do, or is something now broken?

**Comment by radare** [comment]
thanks so we can close this issue right?
