### ISSUE TITLE
No function at 0xf7. Define it here

### ISSUE THREAD

**Issue by Itra7** [radare/radare2#13840]
When I open radare in debug mode `r2 -AAAd cedece16` and when hit a breakpoint on main it gives me **No function at 0xf2... Define it here(Y/n)?**. When I click Y it jump somewhere, where i don't want, but when click n it gives me FFFF FFFF FFFF...

![Screenshot from 2019-04-21 11-11-54](https://user-images.githubusercontent.com/37014351/56467993-7078a380-6426-11e9-8931-de95b5e8b135.png)

**Comment by Maijin** [comment]
Please follow the bug report template and provide with the information required such as the version number, Operating system, type of binary etc. https://github.com/radare/radare2/issues/new?template=bug_report.md

**Comment by radare** [comment]
Probably because doing -AAAA is experimental and not recomended and even less inside the debugger

**Comment by Itra7** [comment]
OS: Ubuntu x64 18.10
File Format: ELF

in file ~/.radare2rc
eco pink
dor aslr=no //  https://reverseengineering.stackexchange.com/questions/21143/when-reopening-file-lose-all-information-in-radare2

**Comment by Itra7** [comment]
![Screenshot from 2019-04-21 12-59-52](https://user-images.githubusercontent.com/37014351/56469112-83df3b00-6435-11e9-9d78-1d981592dc39.png)
![Screenshot from 2019-04-21 13-00-11](https://user-images.githubusercontent.com/37014351/56469113-83df3b00-6435-11e9-94ef-dc40305e10f5.png)
![Screenshot from 2019-04-21 13-00-15](https://user-images.githubusercontent.com/37014351/56469114-83df3b00-6435-11e9-824e-50b5f5e1ca3a.png)
![Screenshot from 2019-04-21 13-00-18](https://user-images.githubusercontent.com/37014351/56469115-83df3b00-6435-11e9-9c0d-0644934dfc27.png)

**Comment by radare** [comment]
ood AAA is completely wrong

also dont expect static analysis info to work in the debugger wprogram ebcause nothing is rebased. there aare many other issues related to the same thing.
also you executed 'dc' which bascially runs the program and dies, this is why you cant read anything anywhere, im sorry to say that..but the process is dead

**Comment by Itra7** [comment]
@radare No I'm not executed 'dc' just break point 'db main' and click '<F7> step into' and program jump elsewhere

**Comment by Maijin** [comment]
Still missing the version of radare2: r2 -v full output, **not truncated**

**Comment by Itra7** [comment]
@Maijin 

$ r2 -v
radare2 2.8.0 0 @ linux-x86-64 git.2.8.0
commit: HEAD build: 2018-08-08__20:37:49

**Comment by radare** [comment]
o m g

2.8 is like 2500 away from master

please, try again on git master, we dont fix ancient bugs

**Comment by XVilka** [comment]
Well, you can put it in formaldehyde, and preserve it for the future
radare2 museum.

**Comment by Itra7** [comment]
I also think that :)

**Comment by Maijin** [comment]
Next time please follow the bug report template they're here for a reason... We loose time trying to debug problems on ancient versions...
