### ISSUE TITLE
Run aaft after aa/aaa/aaaa

### ISSUE THREAD

**Issue by radare** [radare/radare2#13854]
Though it was already like this :________

![IMAGE 2019-04-21 19:53:33](https://user-images.githubusercontent.com/917142/56473702-2536b300-646f-11e9-8bca-b5eb5a4f8d37.jpg)

**Comment by radare** [comment]
@oxcabe @Maijin @sivaramaaa pls fix this, its just 1 line and write the test i used in the screenshot

**Comment by sivaramaaa** [comment]
This is fixed , just have to write a test for it , then we close this issue , i will send a PR now :)

**Comment by radare** [comment]
Cool!

**Comment by radare** [comment]
@sivaramaaa and the pr have happened or not?
