### ISSUE TITLE
radare2 can't find out data/code ref to strings

### ISSUE THREAD

**Issue by riusksk** [radare/radare2#13905]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | windows x64
| File format of the file you reverse (mandatory)      | macho
| Architecture/bits of the file (mandatory)            | arm64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21238 @ windows-x86-64 git.3.5.0-git commit: 1c279c6081bc1877fabd533a8314eb527e32c66c build: Wed 04/10/2019__10:52:39.32

### Expected behavior

find out data/code ref to strings, for example in IDA:
![image](https://user-images.githubusercontent.com/3008098/56799113-ca280600-684a-11e9-934b-d877b810a02a.png)

### Actual behavior
it can't found out string ref addr after enable emu.str=true:
```
[0x100055a2d]> fs strings;f~+bindToPort:error:
0x100055a2d 18 str.bindToPort:error:
[0x100055a2d]> axtj @@ str.bindToPort:error:
[]
[0x100055a2d]>pdf @0x10004f1b8
.....
│           0x10004f29c      880000d0       adrp x8, 0x100061000       ; (pstr 0x1000554bf) "closeSockets"
│           0x10004f2a0      08010691       add x8, x8, 0x180          ; (pstr 0x100055a2d) "bindToPort:error:"
│           0x10004f2a4      a9835df8       ldur x9, [var_28h_2]
│           0x10004f2a8      a9031df8       stur x9, [type]            ; 0x30 ; '0' ; 48
│           0x10004f2ac      010140f9       ldr x1, [x8]               ; char *selector ; (pstr 0x100055a2d) "bindToPort:error:" ; str.bindToPort:error:
│           0x10004f2b0      e20300aa       mov x2, x0
│           0x10004f2b4      cab78252       movz w10, 0x15be
│           0x10004f2b8      a3c300d1       sub x3, x29, 0x30
│           0x10004f2bc      e01300f9       str x0, [sp + var_20h_2]
│           0x10004f2c0      e00302aa       mov x0, x2                 ; void *instance
│           0x10004f2c4      e2030aaa       mov x2, x10
│           0x10004f2c8      97030094       bl sym.imp.objc_msgSend    ; void *objc_msgSend(void *instance, char *selector)
│                                                                      ; void *objc_msgSend(-1, "bindToPort:error:")
```

### Steps to reproduce the behavior 
you can use the follow attached file to test:
[TestSocket.zip](https://github.com/radare/radare2/files/3120719/TestSocket.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by radare** [comment]
@Maijin tahts another bug in aaaa, its solved by running /re $$ or in fact justs doing aae it works fine, . i dont understsand why aae is not being executed in aaa, when it is MUCH better than aav, and aav is there.. juts causing some noise.

<img width="1108" alt="Screenshot 2019-04-27 at 11 11 03" src="https://user-images.githubusercontent.com/917142/56847588-33f0f000-68dd-11e9-830a-a2d83a032d30.png">

i send a pr adding aae in aaaa in here https://github.com/radare/radare2/pull/13911

**Comment by radare** [comment]
i dont see which analysis commands did you executed, by i assume you did aaa

**Comment by riusksk** [comment]
yes, I use 'aaa'

**Comment by radare** [comment]
aae was enough, thats why i never use aaa, and i always recommend people to try to understand what each command do. but thats clearly something that should be included in aaa, and i dont know the reason it was removed. 

i'll wait for feedback from maijin here, but the PR is green and ive merged it. so it will be good to write a test with this binary to ensure aaa runs aae

**Comment by Maijin** [comment]
aae is in aaa already https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L8070-L8071

**Comment by radare** [comment]
this is not aae, its aae $SS @ $S

**Comment by Maijin** [comment]
and why not changing to that this statement then instead of having it twice?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/13914

**Comment by Maijin** [comment]
`aae` is in aaa now, closing here :) Let us know if you still experience issue, we can always re-open.
