### ISSUE TITLE
Panels

### ISSUE THREAD

**Issue by radare** [radare/radare2#13904]
* [x] honor scr.nkey (nN keys in visual go next/prev nkey thing (flag, funuction ..) - i know it conflicts with current new panel keys
* [x] in zoomed mode we cant 'g'oto or 'n/N' . maybe follow nkey only in zoomed mode?
* [x] Add decompiler selection submenu.

To do the last thing we need:

* have the ability to list all the decompilers installed
* select one by setting the cmd.pdc eval variable

For example to select
* r2dec: `e cmd.pdc=pdd`
* radeco: `e cmd.pdc=pde`

in case the decompiler is not installed we can maybe give the option to run r2pm -i ... directly from r2

**Comment by radare** [comment]
Imho we should have subcommands to pdc to handle those:

* pdc. -> list all registered decompilers (how to register them :?)
* pdc.r2dec -> instead of pdd? that looks ugly, we can maybe handle both.. but we still need a way to register them

maybe the simplest option would be to just handle anything in `pdc.` and make the decompiler plugins implement that command. by running them we can check if the command exist or not. for listing,... well, hardcoding the list of them shouldnt be a problem

problem is to have all the decompilers behhave the same:

* r2snowman adds CL lines and requires asm.dwarf to work
* r2dec uses comments to import the decompilation output

**Comment by radare** [comment]
ping @Vane11ope

**Comment by radare** [comment]
```
[0x1000011e8]> e cmd.pdc =?
r2dec
pdc
```

**Comment by Vane11ope** [comment]
i don't know any other decompiler available except  for r2dec

**Comment by radare** [comment]
just some i have installed, but there are more

[0x00000000]> e cmd.pdc=?
r2dec
pdc
!*r2retdec
.!r2snow
pdd

**Comment by radare** [comment]
This is solved now
