### ISSUE TITLE
pdj 100 breaks pd 1

### ISSUE THREAD

**Issue by MapleLeaf-X** [radare/radare2#13907]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Win7 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21238 @ windows-x86-64 git.3.5.0-git commit: 1c279c6081bc1877fabd533a8314eb527e32c66c build: Wed 04/10/2019__10:52:39.32

### Expected behavior
![img](https://user-images.githubusercontent.com/28764234/56828450-dc0ca780-6850-11e9-9ad0-e6732a95c7ee.PNG)

### Actual behavior
![bug](https://user-images.githubusercontent.com/28764234/56828512-fe062a00-6850-11e9-8895-06b006cefbc7.PNG)

### Steps to reproduce the behavior 
- Load any x86/x64 binary (I've used rabin2.exe)
- Execute `pdj 100`
- Exceute `pd 1`

**Comment by radare** [comment]
can you submit a test doing this:

pd 1
pdj 100 > /dev/null
pd 1

and comparing the output?

btw its fixed now, but a better fix may come soon or late
thanks!

**Comment by MapleLeaf-X** [comment]
I'll happily test it if I'll be able to get a copy of the latest compiled radare. Its just that currently I don't have access to machine I could compile on myself so I'll need someone to provide me the binaries for windows to test it.

**Comment by radare** [comment]
Travis and appveyour just build every commit for all the platforms.
