### ISSUE TITLE
Segfault in pd

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#13931]
[TVMLKit.tar.gz](https://github.com/radare/radare2/files/3127986/TVMLKit.tar.gz)
`r2 -c "aa; pd 1 @ 0x000e0dc3" TVMLKit`

**Comment by radare** [comment]
that will  only crash in asan, so not sure if its worth a test and we can just test 1  instruction

the bytes are:


0f2805b6010c00

opcode: movaps xmm0, xmmword [rip + 0xc01b6]
