### ISSUE TITLE
How to uninstall radare2 on macOS?

### ISSUE THREAD

**Issue by qrx** [radare/radare2#13948]
There doesn't seem to be any information on how to uninstall Radare2 on MacOS.

I installed using the package from rada.re.

How to remove it?

**Comment by afjoseph** [comment]
Try this:
- List packages with `$ pkgutil --pkgs`
- See if radare2 is installed
- Run `pkgutil --pkg-info <R2-PACKAGE>`, replacing R2-PACKAGE with the radare2 package name (I can't really remember it)
- Remove the installed package from the location mentioned in `location` property
    - See helpful note below
- Afterwards, just forget the package `pkgutil --forget <R2-PACKAGE>`
    - I think you have to use `sudo` here. Not sure


P.S: I stole this one-liner from [SO](https://stackoverflow.com/a/27546100) to remove all the file in a package using Unix magic:
```
$ pkgutil --only-files --files the-package-name.pkg | tr '\n' '\0' | xargs -n 1 -0 sudo rm -i
```

**Comment by rukmaldias** [comment]
found this from fossies.org and it worked for me

#!/bin/sh
PKG=org.radare.radare2
cd /

pkgutil --files ${PKG} > /dev/null || exit 1

# delete files
FILES="$(pkgutil --only-files --files ${PKG})"
for a in ${FILES} ; do
if [ -f "${a}" ]; then
 rm "$a"
 # | xargs rm -i
fi
done

```
# delete empty directories
FILES="$(pkgutil --only-dirs --files ${PKG})"
for a in ${FILES} ; do
if [ -d "${a}" ]; then
  rmdir "$a"
fi
done
pkgutil --forget ${PKG}
```

**Comment by radare** [comment]
Read and update doc/macos.md if thats not clear enough
