### ISSUE TITLE
Implement cursor mode in panels for function/symbol/string list

### ISSUE THREAD

**Issue by radare** [radare/radare2#13967]
to select one and seek the disasm/hexdump to there

**Comment by radare** [comment]
moving to 3.6 no need to push for this feature, even if its really desireable :) if u can make it before sunday its fine, otherwise i prefer to focus on bugfixing

**Comment by radare** [comment]
only missing is strings, workss for symbols, imports, functions...

**Comment by Vane11ope** [comment]
super easy, hang on

**Comment by Vane11ope** [comment]
it's actually working for strings. open strings via almighty menu by push " then choose strings and give it a try

**Comment by radare** [comment]
I tried it from the menu and that was not working. With the “ works

**Comment by radare** [comment]
we can close this i think
