### ISSUE TITLE
Null pointer dereference in r_bin_demangle_swift()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#13985]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.2 x64
| File format of the file you reverse (mandatory)      | Mach-O
| Architecture/bits of the file (mandatory)            |  x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21653 @ linux-x86-64 git.3.4.1-341-g14b49280e commit: 14b49280ee78147e54787d4e442ca9bc5edec0f3 build: 2019-05-06__15:23:36

### Expected behavior

Disassembly of file or error message.

### Actual behavior

SIGSEGV in ASAN build.

### Steps to reproduce the behavior 
- Download binary from https://github.com/radare/radare2-regressions/pull/1819
- Fire r2 with command: `r2 -A r2_nullptr_r_bin_demangle_swift`

### Additional Logs, screenshots, source-code,  configuration dump, ...

```
==15528==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f7b76ec55a1 bp 0x7fffe46d0210 sp 0x7fffe46cf968 T0)
==15528==The signal is caused by a READ memory access.
==15528==Hint: address points to the zero page.
    #0 0x7f7b76ec55a0  /build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/multiarch/strlen-avx2.S:59
    #1 0x55edee0e5716 in __interceptor_strcat (/usr/local/bin/radare2+0x72716)
    #2 0x7f7b7ae574ec in r_bin_demangle_swift radare2/libr/bin/mangling/swift-sd.c
    #3 0x7f7b7aaab458 in r_bin_demangle radare2/libr/bin/demangle.c:135:30
    #4 0x7f7b7ac8ee5b in symbols radare2/libr/..//libr/bin/p/bin_mach0.c:263:15
    #5 0x7f7b7aac8a91 in r_bin_object_set_items radare2/libr/bin/obj.c:356:16
    #6 0x7f7b7aac78f7 in r_bin_object_new radare2/libr/bin/obj.c:239:2
    #7 0x7f7b7aabd6a1 in r_bin_file_new_from_bytes radare2/libr/bin/bfile.c:467:18
    #8 0x7f7b7aa97ebf in r_bin_open_io radare2/libr/bin/bin.c:420:13
    #9 0x7f7b7bb2776b in r_core_file_do_load_for_io_plugin radare2/libr/core/cfile.c:409:7
    #10 0x7f7b7bb2776b in r_core_bin_load radare2/libr/core/cfile.c:563
    #11 0x7f7b7759a5cc in r_main_radare2 radare2/libr/main/radare2.c:1125:15
    #12 0x7f7b76d58b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #13 0x55edee090219 in _start (/usr/local/bin/radare2+0x1d219)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-OTsEL5/glibc-2.27/string/../sysdeps/x86_64/multiarch/strlen-avx2.S:59 
==15528==ABORTING
```

**Comment by radare** [comment]
Fixed in 569e4354b11b2eeac8a21ca52160c46e3032a3bf
