### ISSUE TITLE
Implement * for ta and maybe move commands

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#14019]
* `ta` just creates anal hints, so it would probably better fit under `ah`, for example as `ahO`
* Then, `ah*` should also emit the respective commands.
* `taa` should probably be moved to `aa`

**Comment by radare** [comment]
Related to https://github.com/radare/radare2/issues/13969

**Comment by radare** [comment]
too risky to do before r2con imho

**Comment by XVilka** [comment]
Agree, will break some examples. Moving after

**Comment by oxcabe** [comment]
I started working on this yesterday. Should I pick another one?

**Comment by XVilka** [comment]
No, feel free to continue. It's just should be the part of 3.9.0 release, not the 3.8.0

**Comment by radare** [comment]
agree on  those moves. but with different names:

taa ->  aat  (current aat should be renamed to aafr.. but in fact aaft seems similar)
ta -> aht (current aht  can be renamed to ahT)

and finally ta will  die? we should probaly up

**Comment by radare** [comment]
@oxcabe @thestr4ng3r @XVilka ^

forgot to push my proposal because the bttery was off while writing it at 4am  xD
