### ISSUE TITLE
Dont use ansi on eprintf outside unix systems

### ISSUE THREAD

**Issue by radare** [radare/radare2#14046]
though that was fixed

![Screenshot 2019-05-13 at 11 34 35](https://user-images.githubusercontent.com/917142/57611412-18d7de80-7573-11e9-80e3-3816feb7d116.png)

**Comment by radare** [comment]
i think this is fixed now cc @GustavoLCR @kazarmy

**Comment by GustavoLCR** [comment]
no, this still happens with `e scr.ansicon=0`
