### ISSUE TITLE
doo/ood fails to reopen for debugging

### ISSUE THREAD

**Issue by MapleLeaf-X** [radare/radare2#14064]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Win7 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 4 @ windows-x86-64 git.3.6.0-git commit: f76bb81d1cba9ab001535365d12f4d2635618560 build: Tue 05/14/2019__ 5:40:25.82

### Expected behavior
doo/ood should reload for debugging.

### Actual behavior
doo/ood fails to reload for debugging and requires to rerun r2 to debug again.

### Steps to reproduce the behavior 
- load any pe in r2. (r2 file.exe)
- run with doo/ood.
- do dk 9
- run with doo/ood again.

**Comment by GustavoLCR** [comment]
This was fixed with #14086
