### ISSUE TITLE
Add libr/main/r2pipe.c

### ISSUE THREAD

**Issue by radare** [radare/radare2#14070]
The idea of this r2pipe command will be to contain the following things:

* https://github.com/radare/radare2-r2pipe/tree/master/c
* https://github.com/radare/radare2-r2pipe/blob/master/shell/r2cmd.c

To allow to use shellscript (or any other lang by using the r2pipe command).

NOTE: We can maybe extend r2agent for this, but the idea is to have a small binary with no (or few dependencies) to make spawn as fast as possible.

**Comment by XVilka** [comment]
Quite reasonable and should be in the main repo instead.

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/14336
