### ISSUE TITLE
"dte" output grab

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#14082]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | kali rolling 4.6.0-kali1-amd64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | i386, x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21872 @ linux-x86-64 git.2.9.0-2263-g569e4354b
commit: 569e4354b11b2eeac8a21ca52160c46e3032a3bf build: 2019-05-13__13:40:40

### Expected behavior
dte~mem.write=0x177ff8    - find specified string via internal grep
dte | grep mem.write=0x177ff4    - find specified strring via external command
dte > out.txt                              - save output via pipe for next searching

### Actual behavior
dte~mem.write=0x177ff8    - all output pass away
dte | grep mem.write=0x177ff4    - all output pass away
dte > out.txt                              - nothing

### Steps to reproduce the behavior 
aei;aeip;aeim;aets+;aes;aes
dte~addr
dte|grep addr
dte > /tmp/out.txt

**Comment by radare** [comment]
It's easier to fix the bug than to report it.

Thanks for filling the issue, but it would be great if you could try to fix it first the next time.
