### ISSUE TITLE
Incorrect make file configuration for sdb

### ISSUE THREAD

**Issue by jorgeventura** [radare/radare2#14093]
I am trying to compile the last version for mingw32 (w32) and the command for configuration is:

./configure --with-compiler=i686-w64-mingw32-gcc --with-ostype=mingw32 --build=x86_64-linux-gnu --host=i686-w64-mingw32 --target=i686-w64-mingw32

Most of the time the scripts are getting the correct compiler i686-w64-mingw32 but for sdb it's not using the crosscompile parameters and starts using cc. There is a workaround exporting CC=i686-w64-mingw32 but at the end I have some problems with unresolved references that I will report later in case that persists. 

I suspect that shlr/sdb/config.mk should include some other mk files.

make[2]: Entering directory '/home/ventura/radare2-minggw32/radare2/shlr/sdb/src'
**cc** -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o cdb.o cdb.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o buffer.o buffer.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o cdb_make.o cdb_make.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o ls.o ls.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o sdbht.o sdbht.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o ht_uu.o ht_uu.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o sdb.o sdb.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o num.o num.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o base64.o base64.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o match.o match.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o json.o json.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o ns.o ns.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o lock.o lock.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o util.o util.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o disk.o disk.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o query.o query.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o array.o array.c
cc -c  -std=gnu99 -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L  -Wall -Wsign-compare -g -Wall -O0 -MMD -fPIC -g  -o fmt.o fmt.c

**Comment by radare** [comment]
Mingw builds have been deprecated more than one year sgo. We only support msvc in windows because mingw is very broken and we cant relay on broken compilers.

**Comment by jorgeventura** [comment]
Ok. I am installing MSVC on Windows7/32.

Thank you for the fast replay,
Ventura

**Comment by radare** [comment]
Now we have a new contributor for windows that maybe he will be able to improve the state of r2 in windowsland. So maybe mingw will be supported again at some point but it will require fixes in their side and not workarounds and hacks in our side.

Where did u find thise instructions?
