### ISSUE TITLE
[GDB protocol] r2 doesn't receive singlestep event

### ISSUE THREAD

**Issue by Wenzel** [radare/radare2#14090]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 29, x86, 64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21740 @ linux-x86-64 git.3.4.1-415-g1e0c5f676 commit: 1e0c5f6761149fd8d39b15bb9fc5579e48719a2e build: 2019-05-12__19:48:31

I'm implementing a GDB server, and developing a hypervisor-level debugger based on Xen.
When I attach to an existing process in my VM, radare2 works,
but when I attach to a new process that i'm creating, it doesn't.

### Expected behavior

radare2 should receive my singlestep event

### Actual behavior

radare2 keeps waiting

### Steps to reproduce the behavior 

- attach to a new process with [`pyvmidbg`](https://github.com/Wenzel/pyvmidbg)

### Additional Logs, screenshots, source-code,  configuration dump, ...

I recorded a **demo** of the problem:
https://drive.google.com/open?id=1SuSZlU5BhJH4r0Hci0NrlEk0iUkDgpeH

First i'm attaching to an existing process, everything is fine, when i do `ds` i get my singlestep event.

Then i'm attaching to a new process that I create afterwards.
for some reason, radare2 performs a **lot** of memory read query, I don't understand why.
and the singlestep doesn't work, i'm sending the response `$T05#b9`, but nothing happens.

Finally you can observe a difference in the GDB protocol between the 2 cases.
In both cases it starts by a `qSupported` packet, but in the first one, the second packet is a `QStartNoAckMode`, and in the second it's a `vCont?`.
This I can't explain either.

Thanks !

**Comment by Wenzel** [comment]
cc @SrimantaBarua, i have been told on r2 dev Telegram channel that you were familiar with the GDB implementation.
Can you shed some lights ?

**Comment by SrimantaBarua** [comment]
Hi, could you upload a pcap file for the demo you recorded?

**Comment by SrimantaBarua** [comment]
@Wenzel it's likely that some state is initialized when r2 connects with the gdb protocol, but not de-initialized when disconnecting.

**Comment by Wenzel** [comment]
Hi, thanks for the feedback.

I uploaded in this folder the pcap you asked:
https://drive.google.com/drive/folders/19zewadCGsgArn2uRtKksL5ijD2EHbeqi?usp=sharing

Also you will a new video demonstrating how I did the capture.
The funny thing is that in the first part of the video, at my first attempt at reproducing the bug, radare2 actually worked, and i could singlestep through my code.

However, at my second attempt, it didn't.

I hope this helps !

**Comment by SrimantaBarua** [comment]
From the pcap, your `Packetsize=1000;multiprocess...` response comes >2.5 seconds after r2 sends a `qSupported...` packet. In fact, before your `Packetsize` response, it looks like r2's waiting for a response has already timed out and it has already sent a `qC` packet.

Code starts from around [here](https://github.com/radare/radare2/blob/master/shlr/gdb/src/gdbclient/core.c#L134).

I don't think indefinitely waiting for replies is a good idea, in case some gdbserver implementation doesn't support a particular packet. Do you have any ideas?

**Comment by SrimantaBarua** [comment]
Maybe the delay in the responses is variable? That might explain why debugging seems to work sometimes, if waiting for the response does not time out.

**Comment by Wenzel** [comment]
> From the pcap, your Packetsize=1000;multiprocess... response comes >2.5 seconds after r2 sends a qSupported... packet. In fact, before your Packetsize response, it looks like r2's waiting for a response has already timed out and it has already sent a qC packet.

The reason is because while radare2 is connecting, i'm manually starting my cmd.exe process in the virtual machine.

I need to be at the entrypoint before i can return to gdb and send the first response.

the gdb client can handle that and will just wait for like 10 sec for the `Packetsize=1000` response, or resend `qSupported` multiple times otherwise.

I think we should do the same in radare2.

**Comment by SrimantaBarua** [comment]
Could you try #14104 ? This fix is necessary, but might need other fixes too.

**Comment by Wenzel** [comment]
@SrimantaBarua I confirm that this fix is working and solving my issue.
thank you so much !

**Comment by XVilka** [comment]
So it is fixed in the master. Thanks for the report!
