### ISSUE TITLE
Interactive ASCII graph is broken

### ISSUE THREAD

**Issue by BlaCoiso** [radare/radare2#14101]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows/x86/64
| File format of the file you reverse (mandatory)      | any
| Architecture/bits of the file (mandatory)            | any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22137 @ windows-x86-64 git.3.5.1-33-g6ed68c125 commit: 6ed68c1252562fa183c9fd0b904ba3e70d0f5cd0 build: 18/05/2019__13:55:22,22
### Expected behavior
interactive ASCII graph looks fine (screenshot from `agf` command):
![image](https://user-images.githubusercontent.com/13855359/57970569-9720f000-797a-11e9-8791-8a1dcaf5223d.png)
### Actual behavior
some lines and colors in the graph are messed up (screenshot from `agfv` command):
![image](https://user-images.githubusercontent.com/13855359/57970578-c5063480-797a-11e9-83a2-7c9611592513.png)
### Steps to reproduce the behavior 
Open the interactive ASCII graph

**Comment by radare** [comment]
Windows specific bug i guess.

Is this a regression? Can you determine when this bug was introduced by trying previous builds? Can you try with different color themes and scr.color=1 or 0?

**Comment by BlaCoiso** [comment]
Part of the bug only happens with scr.utf8=true, noticeable after 3fba693b91173a65d5abc66aebdb45f93449ce08 when utf8 got enabled by default

**Comment by Maijin** [comment]
We recommend https://conemu.github.io//https://cmder.net/ on windows to benefit from all the features of radare2 including the colors is that what you're using or?

**Comment by BlaCoiso** [comment]
This fix broke it even more
![image](https://user-images.githubusercontent.com/13855359/58507997-e640ff00-818a-11e9-9e0b-67eaac6b37f5.png)
![image](https://user-images.githubusercontent.com/13855359/58508035-feb11980-818a-11e9-82e0-29aa424aa919.png)

**Comment by GustavoLCR** [comment]
@BlaCoiso can you try with `e scr.ansicon = 0`

**Comment by BlaCoiso** [comment]
With scr.ansicon = 0 everything looks fine
![image](https://user-images.githubusercontent.com/13855359/58508614-5a2fd700-818c-11e9-917a-cdf388d58d56.png)
![image](https://user-images.githubusercontent.com/13855359/58508623-5ef48b00-818c-11e9-8f81-ba31b825cf77.png)

**Comment by GustavoLCR** [comment]
yep, your terminal isn't compatible with ansicon. Which Windows are you using? It works fine with Windows 10 1809

**Comment by GustavoLCR** [comment]
According to aba69dde4f41d6458447ec50c1320ea832691187 ansicon should only be enabled with Windows 10 Creators up. Is this a bug or do you have a script that sets it to 1?

**Comment by BlaCoiso** [comment]
I'm using Windows 10 version 1803, build 17134.765
Maybe ansicon should be disabled by default on windows (apparently that was the behavior on previous versions)
![image](https://user-images.githubusercontent.com/13855359/58509106-aaf3ff80-818d-11e9-9df2-de7cab6f9bc4.png)

**Comment by GustavoLCR** [comment]
cc @kazarmy

**Comment by BlaCoiso** [comment]
Apparently this is being caused by using an old SDK version that doesn't define ENABLE_VIRTUAL_TERMINAL_PROCESSING; manually defining it makes ansicon work
![image](https://user-images.githubusercontent.com/13855359/58511028-e4c70500-8191-11e9-95b7-aafb29d3f095.png)
![image](https://user-images.githubusercontent.com/13855359/58511075-02946a00-8192-11e9-94bd-083ea19a4661.png)

**Comment by GustavoLCR** [comment]
Which version of VS are you using to build radare? IIRC its only supported
on 2015 up. It is working on 2017 at least

Em ter, 28 de mai de 2019 17:46, BlaCoiso <notifications@github.com>
escreveu:
