### ISSUE TITLE
Calling izz closes the io fd and breaks subsequent calls

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#14115]
To reproduce:
```
r2 -n /bin/ls
> izz
> izz
```

**Comment by radare** [comment]
cant repro. works fine here

what shosuld i expect to happen

**Comment by thestr4ng3r** [comment]
![Bildschirmfoto vom 2019-05-20 20-37-43](https://user-images.githubusercontent.com/1460997/58044063-22e37980-7b3f-11e9-8bb6-a5c5354e2dc7.png)
No output in the second call. Seems to even crash on Windows.

**Comment by radare** [comment]
Maybe related to -n because it works fine when doing r2 /bin/ls for me. Maybe worth add some tests and paste the asan output here

**Comment by thestr4ng3r** [comment]
Not just maybe, it is related to -n.

**Comment by thestr4ng3r** [comment]
As mentioned on Telegram, `bin_raw_strings()` in cbin.c creates a new RBuffer with `r_buf_new_with_io()` and then frees it, which closes the fd. Asan says nothing here.

**Comment by radare** [comment]
thats another regresssion nitroduced in the rbuf refactoring from @ret2libc

**Comment by a1ext** [comment]
It seems like 3.3 version is affected as well

**Comment by a1ext** [comment]
I tried `izzj` instead of `izz`, after the second one it crashes 100% times on Windows

**Comment by ret2libc** [comment]
> thats another regresssion nitroduced in the rbuf refactoring from @ret2libc 

I don't think it was introduced recently, as @a1ext says. But I think we can fix it by changing a bit the RBuffer API. I can work on this.

**Comment by radare** [comment]
+1
