### ISSUE TITLE
Segfault due to Signed/Unsigned confusion

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#14142]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22118 @ linux-x86-64 git.3.5.1-76-g3e3d97b
commit: 3e3d97b1987cfceee755b70ae5549c8f6c739889 build: 2019-05-23__12:00:17

-----
Ahoy! Found a signed/unsigned confusion (`ut64 -> int -> size_t`) in the flow begins in `bin_elf.inf:343`.

https://github.com/radare/radare2/blob/3941218500afc1f987d5b72e0acd7472ce74e1bc/libr/bin/p/bin_elf.inc#L339-L343

As you can see, there is a call to `r_buf_read_at` with `sec->size` as length.
The thing is, that `sec->size` is `ut64` and `r_buf_read_at` function signature expects an int

```
R_API int r_buf_read_at(RBuffer *b, ut64 addr, ut8 *buf, int len);
```

In turn, `r_buf_read_at` is calling to `r_buf_read` with the length (which is now a negative integer). and `r_buf_read` expects `size_t`.

```
R_API int r_buf_read(RBuffer *b, ut8 *buf, size_t len);
```

So we basically have `ut64 -> int -> size_t` conversation which causes a `SIGSEGV` later when trying to do a `memset()` in `r_buf_read`.

Call flow as can be seen by executing the attached binary sample:

                    ut64 sec->size      value is: 2583691272
                    ut8 *buf = calloc (sec->size, 1);
                    r_buf_read_at (bf->buf, sec->paddr, buf, sec->size);

                                           V
                    int r_buf_read_at(RBuffer *b, ut64 addr, ut8 *buf, int len)
                    len             value is: -1711276024
                    r_buf_read (b, buf, len);

                                           V
                    
                    int r_buf_read(RBuffer *b, ut8 *buf, size_t len) 
                    len                 value is: 18446744071998275592
                    memeset (buf, 0, len)

                                           V

                                       SEGFAULT

### Expected behavior
radare2 should be able to open the file and run smoothly

### Actual behavior

radare2 crashes with Segfault

### Steps to reproduce the behavior 

```
$ r2 d42063865b63b9b2420ef4816531efc2f81c5fa69ab5bda90f1df9eb3b033a53
Segmentation fault (core dumped)
```

### Suggested solution

A possible solution is to make sure that `r_buf_read_at` is recieving `size_t` in `len` instead of using `int`. This will later make sure that when calling `r_buf_read` (which expects size_t) everything will work safely.

```
R_API int r_buf_read_at(RBuffer *b, ut64 addr, ut8 *buf, size_t len);
```

### Attached File:
[d42063865b63b9b2420ef4816531efc2f81c5fa69ab5bda90f1df9eb3b033a53.zip](https://github.com/radare/radare2/files/3211570/d42063865b63b9b2420ef4816531efc2f81c5fa69ab5bda90f1df9eb3b033a53.zip)

**Comment by ret2libc** [comment]
I agree with fixing RBuffer API to be more consistent with the sizes of the lengths and indeed I'm already doing it in PR #14141 because there were some crashes. However... The bug is usually somewhere else, in the binary parser that doesn't properly check the sizes. For example, in your test case it seems `process_constructors()` in bin_elf.inc could be more properly rewritten by using `r_buf_read_le32` instead of reading the *whole section* in a buffer (and i suspect the section has wrong info)

**Comment by lowlyw** [comment]
totally agree, offsets should be signed from `r_buf`

**Comment by lowlyw** [comment]
this no longer crashes. closing
