### ISSUE TITLE
icqq/iqqc/iqcq is not working, whilee rabin2 -qqc works

### ISSUE THREAD

**Issue by radare** [radare/radare2#14177]

**Comment by rfc2119** [comment]
`icqq` was implemented and working

what is `iqcq` and `iqqc` ? these look to me like `iq`

**Comment by radare** [comment]
iqcq and iqqc sounds to me like invalid commands or aliasses of the same if we consider supporting mixedup letters

**Comment by radare** [comment]
i think we can close this
