### ISSUE TITLE
pdJ is broken for Cf

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#14215]
![Bildschirmfoto vom 2019-06-03 18-10-21](https://user-images.githubusercontent.com/1460997/58816976-ea599a80-862a-11e9-9016-04cc065eb5b6.png)

**Comment by radare** [comment]
that's even worst `r2 -qc 'af;Cf 2 w;pdJ 1~{}' /bin/ls`

**Comment by radare** [comment]
all yours. this pdJ loop is creepy and ive spent too much time trying to fix it. this is just used by Cutter right?

**Comment by thestr4ng3r** [comment]
Yes, at the moment this is the only use I am aware of.

**Comment by radare** [comment]
can you fix this @thestr4ng3r ?

**Comment by thestr4ng3r** [comment]
Yes, should be done before the release.
