### ISSUE TITLE
zo <tab> completion segfaults

### ISSUE THREAD

**Issue by vifino** [radare/radare2#14234]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Gentoo amd64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 1 @ linux-x86-64 git.3.6.0-git
commit: d2f6640c5b3d223282f92b0b2b2cbe2db530d1e8 build: 2019-06-06__10:10:21

### Expected behavior
`zo <tab>` completes filenames. 
### Actual behavior
You get a segfault. It sucks.

### Steps to reproduce the behavior 
```
$ r2 -
[0x00000000]> zo <tab>
double free or corruption (out)
zsh: abort      r2 -
```

**Comment by vifino** [comment]
Note: I'll probably fix this later today, once I've returned home.

**Comment by radare** [comment]
👍

**Comment by lowlyw** [comment]
doesn't repro fo rme on `cc1b7035ad79c1565bb52212afe779feba36b432`

**Comment by alex-bender** [comment]
yeah, I can't repro it on `bb6f18b79a4aa6a29950792b8fb8b06aaf40d09c`

**Comment by alex-bender** [comment]
https://github.com/radare/radare2/commit/21c37a965fcc2496902562caf32d29adfb7bd43b
fixed here

**Comment by vifino** [comment]
It's indeed fixed.
