### ISSUE TITLE
Upper going reflines don't use unicode and mess the colors

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14258]
(tested on "defragger" color scheme)
![image](https://user-images.githubusercontent.com/203261/59156409-50339f80-8acd-11e9-88de-022295a3790a.png)

**Comment by deepakchethan** [comment]
Up going reflines does use utf8. 

<img width="572" alt="Screen Shot 2019-06-10 at 1 37 23 PM" src="https://user-images.githubusercontent.com/20895544/59181409-f1316180-8b84-11e9-8981-b5305d2fa287.png">

I think I might have to fix the lines where "; CODE XREF ...." are present. Will change and make a pr
