### ISSUE TITLE
Dark text color with default theme (recent regression)

### ISSUE THREAD

**Issue by astuder** [radare/radare2#14254]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian x86 64
| File format of the file you reverse (mandatory)      | bin
| Architecture/bits of the file (mandatory)            | 8051
| r2 -v full output, **not truncated** (mandatory)     | rradare2 3.6.0-git 21830 @ linux-x86-64 git.1.5.0-6974-g6fce40ea0 commit: 6fce40ea04ac1c07937cba58b4fdadf3750df66b build: 2019-06-08__18:59:39

scr.color=3
eco default

### Expected behavior

The colors of the default theme are suddenly very dark / low contrast. They were much brighter in older builds. My point of reference is May 26 2019:

![r2 PR14056](https://user-images.githubusercontent.com/1166488/59154140-38eaa880-8a20-11e9-820f-43654c0d1219.PNG)

### Actual behavior

This is how it looks after pulling the latest version from git

![r2 HEAD](https://user-images.githubusercontent.com/1166488/59154141-3f792000-8a20-11e9-9737-2267f29af534.PNG)

**Comment by radare** [comment]
That’s because we are living dark times and everything is so depressive
