### ISSUE TITLE
Implement ob=

### ISSUE THREAD

**Issue by radare** [radare/radare2#14268]
Like o= or om= or iS=

**Comment by XVilka** [comment]
@deepakchethan please also document it in the book: https://github.com/radare/radare2book/blob/master/basic_commands/mapping_files.md

**Comment by deepakchethan** [comment]
> @deepakchethan please also document it in the book: https://github.com/radare/radare2book/blob/master/basic_commands/mapping_files.md

Will add @XVilka

**Comment by Maijin** [comment]
And the self-documentation in `ob?`

**Comment by deepakchethan** [comment]
> And the self-documentation in `ob?`

Done, made a PR just now. I think this can be closed now.
