### ISSUE TITLE
Add icqj 

### ISSUE THREAD

**Issue by radare** [radare/radare2#14276]
To get all the classnames in a json array

**Comment by radare** [comment]
And icqq

**Comment by Hamled** [comment]
I'd like to work on this issue for the milestone.

**Comment by radare** [comment]
All yours! Thanks!!

**Comment by radare** [comment]
ping

**Comment by Hamled** [comment]
I got carried away with Google CTF this weekend. I'll be working on this today, but if it doesn't look like I will have things ready to go by EOD I'll update this issue.

I know it's down to the wire, so if this is something critical for 3.6.0 milestone I'm happy to let someone else take it on.

**Comment by radare** [comment]
just moved to 3.7
