### ISSUE TITLE
radare2 fails to detect relocated functions even with debug symbols

### ISSUE THREAD

**Issue by ITAYC0HEN** [radare/radare2#14278]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | PE & COFF
| Architecture/bits of the file (mandatory)            | x64.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22334 @ linux-x86-64 git.3.5.1-210-g759ebd5
commit: 759ebd5bfd2f8572d6866fffa7e26b7c739329f4 build: 2019-06-10__18:43:56

Radare2 doesn't detect may function and fails to show the name of those which it does detect

![image](https://user-images.githubusercontent.com/20182642/59209142-4c7a4880-8bb3-11e9-9ad5-1f03b96d3021.png)

### Expected behavior
Radare2 should show all the function in the binary, with their respective names.

Screenshot from IDA:

![image](https://user-images.githubusercontent.com/20182642/59209237-7cc1e700-8bb3-11e9-8a1e-9326374df824.png)

### Actual behavior
Radare shows only 3 functions, with not accurate names

### Steps to reproduce the behavior 
1. Open the attached binary
2. Analyze using `aaa`
3. run `afl` to list the functions
4. observe that almost no functions detected

Binary:

[tif_tile.zip](https://github.com/radare/radare2/files/3401461/tif_tile.zip)

**Comment by XVilka** [comment]
Please prepare the regression test

**Comment by radare** [comment]
Thats a bug in the bin parser for this file format. Totally unrelated to analysis

**Comment by radare** [comment]
Iirc this was coff

**Comment by XVilka** [comment]
@radare we don't have a separate COFF label, and format is kinda rare, no need to make it, so PE is the closest thing to the COFF (and in fact it IS COFF).

**Comment by ITAYC0HEN** [comment]
It's applied to PE ad well

**Comment by GustavoLCR** [comment]
Can you share the binary?
