### ISSUE TITLE
Make icc command available from rabin2

### ISSUE THREAD

**Issue by radare** [radare/radare2#14349]
to get a C-style output of the classes information

**Comment by alex-bender** [comment]
@radare there is already -cc option, so should that functionality be under that option?
```
$ rabin2 -h | grep cc
 -cc             list classes in header format
```

**Comment by alex-bender** [comment]
@radare and what function should be used for that?
in `cmd_info.c:cmd_info()` for `ic` case
https://github.com/radare/radare2/blob/master/libr/core/cmd_info.c#L910
comment taht `// XXX this is dupe of cbin.c:bin_classes()`
in `cbin.c:bin_classes()` comment that `support for classes is broken and needs more love`
https://github.com/radare/radare2/blob/master/libr/core/cbin.c#L2787

So what function to use for dump class in header format?

**Comment by radare** [comment]
Oh right! Missed that. Closing

**Comment by alex-bender** [comment]
@radare It's probably to fast, because -cc is not implemented, it's only presented in help message:
```$¢ r2 ~/sandbox/cpp_class 
 -- Prove you are a robot to continue ...
[0x00000a80]> icc
@interface std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char>> :  
{
}
@end
@interface std::basic_ostream<char,std::char_traits<char>>&std::operator<<<char,std::char_traits<char>,std :  
{
}
@end
@interface std::basic_ostream<char,std::char_traits<char>>&std::operator<<<std :  
{
}
@end
@interface std::ios_base::Init :  
{
}
@end
@interface Geeks :  
{
}
@end
[0x00000a80]> q
$¢ rabin2 -cc ~/sandbox/cpp_class 

```

**Comment by radare** [comment]
uhm. rabin2 -cc works perfectly fine for me, at least with an objc bin, so closing

**Comment by radare** [comment]
not sure why its not working in your side. also this icc output is designed to work on objc only, so for c++ and dalvik/java we should use java/c++ syntax instead. but this is not related to this issue

**Comment by alex-bender** [comment]
@radare yeah, that's probably because of the bin I'm using. Thanks
