### ISSUE TITLE
Consider to move bookmarks on the left in visual and panels mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14355]
Like in Vim plugins:

![image](https://user-images.githubusercontent.com/203261/59748289-63a0f080-92ad-11e9-98b1-438a326bc917.png)

See old bug here https://github.com/radare/radare2/issues/329

**Comment by XVilka** [comment]
Would be a nice eye candy before the trainings/conference.

**Comment by radare** [comment]
Which bookmarks? The jmp/lea/.. hints? Theres a config var for this

**Comment by XVilka** [comment]
Please check the screenshot. They are now only at the right of the disasm. I suggest we move them to the left.

**Comment by radare** [comment]
false, e asm.hint.pos=0 shows them at left. maybe you want pos=-1 which is not yet implemented to make those hint at the very begining of the line, if thatas the case, im happy about having this option

**Comment by radare** [comment]
almost finished this thing. will send pr soon

**Comment by XVilka** [comment]
Yes, I meant the leftmost, which is not implemented.

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/14359

**Comment by radare** [comment]
<img width="909" alt="Screenshot 2019-06-19 at 13 52 57" src="https://user-images.githubusercontent.com/917142/59763285-8de8b300-9299-11e9-84e5-b014dd8d8f86.png">

**Comment by XVilka** [comment]
Awesome. Though there is some duplication at the end.

**Comment by radare** [comment]
yeah.. but i would prefer to merge it now because ihave another pr making more changes in disasm.c and we can fix this duplicated hint for comments/flags lines later. if anyone have time to look at it do it. im very busy right now
