### ISSUE TITLE
`agf` renders graphs problematically

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14354]
After `r2 /bin/ls; aaa; s main; agf` it shows this
![image](https://user-images.githubusercontent.com/203261/59739183-65ab8500-9296-11e9-96b4-d363487e1853.png)

**Comment by radare** [comment]
Enlarge your terminal, pipe to a file or use the interactive mode

This is not a bug

**Comment by radare** [comment]
whats the problem?
