### ISSUE TITLE
Embed r2pm shell into radare2

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14372]
Like in [Julia](https://docs.julialang.org/en/v1/stdlib/Pkg/index.html) language, to look something like:
R2pm should have its own REPL mode, which can be entered from the radare2 shell by pressing ]. To get back to the radare2 shell press backspace or ^C.
It will then change the command prompt:
```
pkg>
```

**Comment by radare** [comment]
as long as we have the r2 command in r2, i would advocate to add all the other r*2 commands availiable via libr_main. so now that we all agree in rewriting r2pm in C instead of Go, we can just call it from there

**Comment by XVilka** [comment]
Closed in favor of https://github.com/radareorg/r2pm/issues/36
