### ISSUE TITLE
Cannot demangle msvc symbol inside radare2

### ISSUE THREAD

**Issue by GustavoLCR** [radare/radare2#14380]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | N.A
| Architecture/bits of the file (mandatory)            | N.A
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22556 @ windows-x86-64 git.3.5.1-313-gae00b18d0 commit: ae00b18d0b8e553d52020128731b39ac6d181134 build: 20/06/2019__14:54:44,28

### Expected behavior
Symbol gets demangled

### Actual behavior
Help message shown

### Steps to reproduce the behavior 
`"iD msvc ?xyz@?$abc@V?$def@H@@PAX@@YAXXZ"`

### Additional Logs, screenshots, source-code,  configuration dump, ...
https://github.com/radare/radare2/blob/ed73f542a758cdcfeb6e9f54fc2d2c0f875ab026/libr/core/cmd_info.c#L386-L391

**Comment by radare** [comment]
is this working with rabin2 -D ?

**Comment by GustavoLCR** [comment]
> is this working with rabin2 -D ?

yes

**Comment by radare** [comment]
Then should be easy to fix

**Comment by radare** [comment]
Tired of waiting for this 1 line fix
