### ISSUE TITLE
'S - IO section manipulation information' not appears

### ISSUE THREAD

**Issue by RazviAlex** [radare/radare2#14391]
Hi everyone,

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04.2 LTS x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            |  "type": "DYN (Shared object file)", x86/32,  etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 22130 @ linux-x86-64 git.3.5.1-294-g3fe39f0c3 commit: 3fe39f0c38b66efa64ef3673e2ba3e6fc3830bf9 build: 2019-06-19__19:13:43

### Expected behavior

When I want to see the available option of my radare with '?' i expected to see this option too:

 **S[?]   IO section manipulation information**

And use it later, like this 'S=' and see the segments of the file for example:

![image](https://user-images.githubusercontent.com/51793648/59943114-ba4f2b80-9461-11e9-8642-11ea963414bf.png)
(image from a YouTube video - LinuxDays 2017 - Disassembling with radare2 - Tomáš Antecký)

### Actual behavior

But it not appears the S option, when I try to see all the available options of my radare it just appears the following:

![image](https://user-images.githubusercontent.com/51793648/59943176-d6eb6380-9461-11e9-9e0f-20cac48114bb.png)

And if I try to use the S option 'S?' it shows me the following error:

![image](https://user-images.githubusercontent.com/51793648/59943215-f3879b80-9461-11e9-9d4e-837edb9b57aa.png)

- This is one of the file that I try, but it's not the only one, try also PE files and the same behavior :(

[CrackMe4.zip](https://github.com/radare/radare2/files/3315642/CrackMe4.zip)

Anyone know why the S option it not appears? Or is there antoher option that make a similar action? 

Thank you,

**Comment by GustavoLCR** [comment]
It was moved under `i`, check `i?`

**Comment by radare** [comment]
This was removed almost 3 years ago and documented and anounced everywhere. What S was doing is now in iS and om commands. And no, those commands dont modify the sections at all. That was a misleading confusion that make us remove this command

**Comment by RazviAlex** [comment]
I just realized.. it's on `iSS`
thanks again,

**Comment by radare** [comment]
Thats for segments
