### ISSUE TITLE
Broken function lines

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14407]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 30 x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.6.0-git 23615 @ linux-x86-64 git.3.5.1-361-gd3459ff7e
commit: d3459ff7e5da75af17b9fbb885e981c7206c1f20 build: 2019-06-24__10:54:52

### Expected behavior
Do not break the line after `0x00005125      e91ffeffff     jmp 0x4f49`
### Actual behavior
It breaks the line

### Steps to reproduce the behavior 
```
r2 /bin/ls
aaa
s main
Vp
```
Then scroll down a bit until you see `0x00005125      e91ffeffff     jmp 0x4f49` line.

### Additional Logs, screenshots, source-code,  configuration dump, ...

![image](https://user-images.githubusercontent.com/203261/59989010-d32d2c00-966f-11e9-9f05-ea2c0eb150c9.png)

Attaching `/bin/ls` here: [fedora_ls_fncreflines.zip](https://github.com/radare/radare2/files/3319062/fedora_ls_fncreflines.zip)

**Comment by radare** [comment]
Its the second time u report this false positive. This “broken” line means that this is not part of the function. Check the control flow and you’ll see its dead code necer reachable

**Comment by XVilka** [comment]
I have a bad memory these days, ETOOOLD probably, sorry.
