### ISSUE TITLE
10dw in visual only creates 1 dword

### ISSUE THREAD

**Issue by radare** [radare/radare2#14415]
should create 10 because of the repeater pattern keys. which work with hjkl for moving already

**Comment by radare** [comment]
Sometimes presssing 'J' in disasm just moves the cursor doesnt select any range

**Comment by deepakchethan** [comment]
This is done, can be closed now.

**Comment by radare** [comment]
Can we have a test?

**Comment by deepakchethan** [comment]
Okay, when in cursor more in visual, it creates 10 DWs, in normal mode it only creates one.

**Comment by deepakchethan** [comment]
// do we need hotkeys for data references? not only calls?
	// '0' is handled to seek at the beginning of the function
	// unless the cursor is set, then, the 0 is captured here
I found this comment in the codebase, it is an expected behaviour
