### ISSUE TITLE
3.6.0 release missing .pkg file

### ISSUE THREAD

**Issue by ArbitraryRW** [radare/radare2#14413]
The Radare page https://rada.re/r/ exposes a download to http://radare.mikelloc.com/get/3.6.0/radare2-3.6.0.pkg, this file does not exist and results in a `404`. 

I can see with the most recent release, [3.6.0](https://github.com/radare/radare2/releases/tag/3.6.0), is missing a `.pkg` flavour in http://radare.mikelloc.com/release/3.6.0. This is available in 3.5.0 [here](http://radare.mikelloc.com/release/3.5.0), hence why it works on the new beta site [here](http://beta.rada.re/en/latest/).

**Comment by radare** [comment]
Should be fixed now
