### ISSUE TITLE
Selecting a range of bytes and then pressing 'dw' only makes 1 dword

### ISSUE THREAD

**Issue by radare** [radare/radare2#14416]
should cover the whole range

**Comment by deepakchethan** [comment]
It is making quite a few dwords:


Selection:

<img width="578" alt="Screen Shot 2019-06-25 at 11 23 55 AM" src="https://user-images.githubusercontent.com/20895544/60072655-cfff7200-973b-11e9-8730-0f0b78c90836.png">

In disassembly mode:

<img width="804" alt="Screen Shot 2019-06-25 at 11 23 44 AM" src="https://user-images.githubusercontent.com/20895544/60072673-dd1c6100-973b-11e9-8399-45c98305abd8.png">

Is there any other way I can reproduce what you are saying?

**Comment by radare** [comment]
wtf i cant repro now... so it works as expected, but i can still see that JK are broken to select bytes in disasm. can you take a look at it?

**Comment by deepakchethan** [comment]
Do you mean when changing visual modes with P ?

**Comment by radare** [comment]
no, just in the visual disasm view, pressing 'c' to get into cursor and then pressing 'J' to select bytes down. this is not working, moving aruond with 'jk' works, but JK does not

**Comment by deepakchethan** [comment]
Working on it right now
