### ISSUE TITLE
tab key in Vpp (debug visual) must switch between stack and disasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#1443]

**Comment by radare** [comment]
discuss plz

**Comment by jvoisin** [comment]
Why not `space`, like in the webui?

**Comment by radare** [comment]
Because stack is not a graph. And i dont see why or how someone would jump from code to stack. And why stack matters more than heap to limit that switch to only 2 views

**Comment by Maijin** [comment]
Link to https://github.com/radare/radare2/issues/7017

**Comment by Maijin** [comment]
`&` for this.

**Comment by Maijin** [comment]
Already done.
