### ISSUE TITLE
Search import library

### ISSUE THREAD

**Issue by RazviAlex** [radare/radare2#14463]
Is there an option to see the extern library that are import into the binary? 
I mean something like this which is possible with IDA Pro:

![image](https://user-images.githubusercontent.com/51793648/60455018-a52e8580-9c35-11e9-80fd-7636063471e5.png)

I try different ways on Radare with `afl `on the `sym.imp*` or try `ii` but nothing what I'm looking for, it's not match what IDAPro show and what Radare show with `afl` or `ii`.

Appreciate any help, thank you!

**Comment by Maijin** [comment]
Can you provide the binary? Because `ii` returns same output as ida for the binaries I have for import and `iE` for exports.

**Comment by RazviAlex** [comment]
The binary it's from my school, I'm not pretty sure if I could share it :(

But I was searching different combination of commands with radare and realized that if started the binary with the debbug option `-d `and then look for the imports it show me the same imports like IDA Pro:

![image](https://user-images.githubusercontent.com/51793648/60458055-e165e400-9c3d-11e9-9454-be93908209e2.png)

But if I open the binary without `-d` option, in a normal way (added image) it show different imports

![image](https://user-images.githubusercontent.com/51793648/60458025-cf844100-9c3d-11e9-9131-7b11e8ede716.png)

Because what I'm looking for it was the "urlmon.dll_URLDownloadToFileW"

hmmm.. why is this happening? 

And apart from this, is there an option like in the function to have look or search inside a library? (what I mean is, with function you can select one of it with `s main` and then put `pd~call` to search all the calls in that function for example)

Thanks!

**Comment by radare** [comment]
Thats wrong in differwnt ways:

- Flags after filenames are ignored by r2 
- you cant debug windows binaries in linux without a vm or emulator

**Comment by RazviAlex** [comment]
true, I forgot that.. thanks @radare 
But just do a static analysis on a windows binarie it's ok right? It might show all the library/function like IDA PRO?

**Comment by Maijin** [comment]
Greetings @RazviAlex,

Yes for static analysis no problem you can do it on any platform on any binaries.

You don't need to analyze on radare2 to get the library functions, this is available with the command in `ii` import, `il` library and `iE` for exports.

If you're looking for call to a function you can analyze with `aaa` then use `axt @ sym.imp.KERNEL32.dll_Sleep` etc.

Those elements after the `@` are called flags and can be found under f. I strongly suggest you read the radare2book as those basic commands/notions are explained there already.

**Comment by radare** [comment]
Yep
