### ISSUE TITLE
isq. not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#14478]
and not tests so far

**Comment by ricardoapl** [comment]
I would like to take a look at this one, yet I can't find any documentation regarding the command.

What is **isq.** suposed to do?

My assumption was that it showed **s**ymbol **i**nformation for the current position in **q**uiet mode, but there's already a slightly different command for that: **is.q**

**Comment by radare** [comment]
isq. Should do the same is.q

**Comment by ricardoapl** [comment]
Got it!

I'm holding the PR for now as I haven't implemented any tests yet - that should take me a little bit longer

How to proceed? Should I implement the tests in radare2-regressions, make PR there and after its been merged make the PR here?

**Comment by ricardoapl** [comment]
Just to remind you that this should have been fixed with https://github.com/radare/radare2/pull/14498 and you may want to close it.

If not, I can take another look.
