### ISSUE TITLE
Honor `e scr.utf8.curvy=true` in fire and horizontal bar graphs

### ISSUE THREAD

**Issue by radare** [radare/radare2#14471]
Using those curvy chars!
<img width="1250" alt="Screenshot 2019-07-02 at 23 26 07" src="https://user-images.githubusercontent.com/917142/60547784-d9cb3b80-9d20-11e9-816b-7594770f470d.png">

**Comment by XVilka** [comment]
Duplicate of https://github.com/radare/radare2/issues/14351, https://github.com/radare/radare2/issues/14352, and https://github.com/radare/radare2/issues/14353

**Comment by XVilka** [comment]
I think it is obsolete with the new block-based representation merged.
