### ISSUE TITLE
aflj taking lot of time. I can't find the reason.

### ISSUE THREAD

**Issue by abhyuday07** [radare/radare2#14494]
afl works fine and quite fast. I don't know what is the issue with aflj which takes a lot of time ( more than hours atleast).

**Comment by thestr4ng3r** [comment]
This is what callgrind has to say:

afl:
![Bildschirmfoto vom 2019-07-06 16-22-40](https://user-images.githubusercontent.com/1460997/60757396-4d639600-a00a-11e9-92c9-d33dc43cee6a.png)

aflj:
![Bildschirmfoto vom 2019-07-06 16-24-22](https://user-images.githubusercontent.com/1460997/60757407-86036f80-a00a-11e9-880f-2c1b273a10ff.png)
