### ISSUE TITLE
"ic?~" returns as if searching the output of "i?"

### ISSUE THREAD

**Issue by ricardoapl** [radare/radare2#14509]
Using the internal grep (**~**) with the output of **i?** (help of **i** command) behaves as one would expect. However, if we do the same with the help output of some sub command of **i**, e.g. **ic?**, it looks as if the search for a match is done with the help output of **i**

Below is the help output of **ic** (that is, issuing **ic?** in r2 prompt)

![r2issue-1](https://user-images.githubusercontent.com/48807108/60769984-10f96e00-a0ce-11e9-8b47-e1bb4b5c3c93.png)

### Expected behavior

`ic?~List` should return

![r2issue-0](https://user-images.githubusercontent.com/48807108/60770087-2d49da80-a0cf-11e9-8fa4-ef15c5943ce2.png)

If only searching for the word Header, i.e. `ic?~Header`, only the last of the above two lines should be shown

### Actual behavior
![r2issue-2](https://user-images.githubusercontent.com/48807108/60769998-32f2f080-a0ce-11e9-8945-5a6665ded5e0.png)

which is the same as

![r2issue-3](https://user-images.githubusercontent.com/48807108/60770004-48681a80-a0ce-11e9-873d-0cf84419b892.png)

### Notes
This is actually happening with any sub command starting with **i** (ic, ik, etc.)

It also seems that a few of the tests in radare2-regressions are not taking this expected behavior into account

**Comment by radare** [comment]
I would add this issue tot he other issues related to icq iccq etc. The fix is just one line. Do you want to contribute with that line?

**Comment by ricardoapl** [comment]
When you talk about icq and iccq are you referring to #14177?

Anyway, I'll take a look at this one!

**Comment by radare** [comment]
Yes
