### ISSUE TITLE
Move all autocompletion and dietline configuration into one place

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14516]
Currently the configuration is scattered all over different places.
I suggest to create a separate key for dietline, something like `dline.*` or `input.*`. Because `scr.*` is not exactly a best fit for the input configuration. Opinion?

/cc @radare

**Comment by radare** [comment]
Imho should be under scr. Or input. Dline is kind of specific to the implementstion and we dont want to have such things

**Comment by XVilka** [comment]
Agree on `input.*`.

**Comment by radare** [comment]
The thing is.. how many input config vars we have because if its 1 or 2. Having them in scr. Is better

**Comment by XVilka** [comment]
OK, closing then.
