### ISSUE TITLE
Implement a JSON indentor that is human friendly

### ISSUE THREAD

**Issue by radare** [radare/radare2#14533]
This is... not adding all those "{, and other shitty chars that make it hard to read by humans

from
```
{"foo":123,"bar",[1,2,3]}
```

to
```
foo: 123
bar: 1, 2, 3
```

**Comment by radare** [comment]
this way we can use json internally to print the standard output of r2 commands (i vs ij)

**Comment by XVilka** [comment]
See also https://github.com/busyloop/vj as an example

**Comment by radare** [comment]
No need to chk anything i already did this
