### ISSUE TITLE
Add command to get "item" in given offset

### ISSUE THREAD

**Issue by radare** [radare/radare2#14530]
So, the idea is to be able to use that item to iterate to the next and previous item. Those items can be: instructions, structures, comments, xrefs and many other things, which right now are only accessible with separate commands.

* instruction / data / struct
* next / previous item
* comments
* xrefs
* ...

**Comment by jtbennett-fe** [comment]
In IDA Pro, these "items" are called "heads" and you can search for the previous or next head from a given address with https://www.hex-rays.com/products/ida/support/idadoc/265.shtml and https://www.hex-rays.com/products/ida/support/idadoc/264.shtml, respectively. These APIs return the virtual address of the head.

**Comment by radare** [comment]
@jtbennett-fe see https://github.com/radare/radare2/pull/14536 its an early implementation, but it may work for you. it may .. in fact be useful to refactor and fix some bugs in disasm.c.

more comments and ideas are welcome!
