### ISSUE TITLE
New column in panels

### ISSUE THREAD

**Issue by radare** [radare/radare2#14545]
Right now theres no way to create a new column in panels mode, we can split vertically and horizontally, but will be good to have a way to add a new panel at right or left with height=screen.height.

In addition, it will be interesting to rotate the panels and change the current selected panel at the same time by swapping them, this way we will be able to place any panel contents in the position of another panel easily.

**Comment by Vane11ope** [comment]
have you tried the menu? you go to the view menu then select any view from it then the new panel of it will be newly added to the side like you mention.

and there's "p" that rotates panel positions

**Comment by radare** [comment]
nope, it is on the left of the current panel, but not in a new column

**Comment by Vane11ope** [comment]
and also from " widget, you can use v or h that's to newly the panel vertically horizontally respectively.

**Comment by radare** [comment]
good. didnt knew that but still dont solves the issue

im here:

<img width="586" alt="Screenshot 2019-07-11 at 18 35 42" src="https://user-images.githubusercontent.com/917142/61068634-c9931a80-a40a-11e9-85b6-443d86b5c3c7.png">

and then i press "v to split vertically into a new panel

<img width="595" alt="Screenshot 2019-07-11 at 18 36 08" src="https://user-images.githubusercontent.com/917142/61068680-dc0d5400-a40a-11e9-8501-cfe8c9070147.png">

as you can see the new column is contained inside the current frame. i want to have a full height column

**Comment by Vane11ope** [comment]
of course that's to split the panel like that. try it in vim

**Comment by radare** [comment]
Its fixed. and now u can do that even without the keyboard. just pressing the corner of the screen
