### ISSUE TITLE
Allow to change the current panel with any custom command with '"'

### ISSUE THREAD

**Issue by radare** [radare/radare2#14544]
Right now it shows a list of possible views. but none of fthem is to use a custom command

**Comment by Vane11ope** [comment]
Create Menu in " would do this job

**Comment by radare** [comment]
the 'e' key do thhat, but maybe good to have the option to edit the current panel from ".

btw i also noticed, that it will be good to reduce the amount of questions for the user to answer:

* panel name (imho the title should be the name of the command by default)
* command to run (the only question that makes sense)
* cache? (i would make it cache by default, just let the user type & after if he wants to toggle)

**Comment by Vane11ope** [comment]
bout those points i all agree hang on PR is coming

**Comment by Vane11ope** [comment]
Done with #14551
