### ISSUE TITLE
Renamed function doesnt show in autocompletion list

### ISSUE THREAD

**Issue by radare** [radare/radare2#14543]
to reproduce :
```
r2 /bin/ls
aa
s main
afn patata
s pa<tab>  # not working
s patata # works
```

**Comment by deepakchethan** [comment]
After afn, if we do af and analyze the function the autocompletion works. Should it work without analyzing also ?

**Comment by radare** [comment]
Problem is flags vs fcnnames. S uses both, but tab only flags afaik
