### ISSUE TITLE
Window management in panels

### ISSUE THREAD

**Issue by radare** [radare/radare2#14558]
I expect to move the current selected panels to the left when i press 'H' here:
<img width="1680" alt="Screenshot 2019-07-13 at 02 22 18" src="https://user-images.githubusercontent.com/917142/61164400-0d724680-a515-11e9-8285-988388871b02.png">

current behaviour: nothing happens.

expected behaviour:

<img width="1680" alt="Screenshot 2019-07-13 at 02 21 16" src="https://user-images.githubusercontent.com/917142/61164377-e6b41000-a514-11e9-8485-7482508cb22a.png">

**Comment by Vane11ope** [comment]
H is for moving to left by a page you know that.

**Comment by Vane11ope** [comment]
but i know what you want there so let me see

**Comment by radare** [comment]
Im in w mode. That should scroll a page

**Comment by Vane11ope** [comment]
no. H is for resize panel horizontally.

**Comment by Vane11ope** [comment]
Fix #14566

**Comment by radare** [comment]
Oooh you are right
