### ISSUE TITLE
agf is slow

### ISSUE THREAD

**Issue by radare** [radare/radare2#14553]
And that's because of the edges

<img width="673" alt="Screenshot 2019-07-12 at 12 02 53" src="https://user-images.githubusercontent.com/917142/61120320-03146600-a49d-11e9-98e2-d8dc9da1ccd4.png">

**Comment by radare** [comment]
<img width="246" alt="Screenshot 2019-07-12 at 12 05 03" src="https://user-images.githubusercontent.com/917142/61120428-4b338880-a49d-11e9-89ca-64e9e7871fef.png">

**Comment by radare** [comment]
this means that 94% of the time required to render a graph is spent in the edges...

**Comment by ret2libc** [comment]
It is not really edges' fault but it's the canvas api that is slow. In particular, most of the time is spent in the `__stampAttribute()` function in canvas.c:

```C
		for (i = c->attrslen; i > 0 && loc < c->attrs[i - 1].loc; i--) {
			c->attrs[i] = c->attrs[i - 1];
		}
```

This piece of the function shifts the existing elements and it may take a lot of time.

**Comment by radare** [comment]
with your pr it looks much better, seems like the most expensive function here is the utf8length code

its funny that the horizontal lines are more expensive than the vertical ones.
<img width="758" alt="Screenshot 2019-07-13 at 02 33 24" src="https://user-images.githubusercontent.com/917142/61164552-98077580-a516-11e9-9b23-627b42590923.png">


<img width="800" alt="Screenshot 2019-07-13 at 02 31 35" src="https://user-images.githubusercontent.com/917142/61164527-570f6100-a516-11e9-9ead-809a61ae1b18.png">

so the difff time is about 11.53s vs 1.83s !!
