### ISSUE TITLE
anti-r2-trick

### ISSUE THREAD

**Issue by condret** [radare/radare2#1455]
you can stop r2 function-analysis if you put a huge number of nops into your code.
http://runas-racer.com/foo/anti_r2_trick

```
$ r2 anti_r2_trick
> s main
> af
> s 0x4014b0
> pd
```

you'll notice that this is not the end of the function

**Comment by radare** [comment]
can you write a test case for this and verify if this is still happening?

**Comment by radare** [comment]
404

**Comment by radare** [comment]
closing until further feedback
