### ISSUE TITLE
rasm wrong instruction disassembling

### ISSUE THREAD

**Issue by drmint80** [radare/radare2#14569]
`81 3E 38 43 55 AA 5A 5A
`
I checked these opcodes in sandphile
```
81 is CMP opcode 
3E is DS segment register override prefix
43 38 is offset
55 AA 5A 5A is operand

```
According to sandpile I should get such result:

`cmp [0x4338], 0x55AA5A5A
`
and final interpreted instruction:

`cmp [0x4338], 0x55AA5A5A
`
But when I checked with rasm, I got wrong result like that:

```
rasm2 -a x86 -b 32 -d "81 3E 38 43 55 AA 5A 5A"
cmp dword [esi], 0xaa554338
pop edx
pop edx
```

**Comment by radare** [comment]
This issue belongs to capstone, r2 is not a disassembler library

**Comment by radare** [comment]
you can use the x86 bea, olly, udis and zyan plugins, as well as testing capstone5 (./configure --with-capstone5 in r2) to compare and report wherever is needed
