### ISSUE TITLE
Implement head and tail programs inside r2

### ISSUE THREAD

**Issue by radare** [radare/radare2#14597]
`> head /etc/services`

(also handle -n)

**Comment by XVilka** [comment]
Also add them in https://github.com/radare/radare2book/blob/master/scripting/intro.md

**Comment by radare** [comment]
We shoukd add uids associated to specific tasks. This way we will have a proper multiuser unix system inside r2

**Comment by XVilka** [comment]
Thanks @deepakchethan ! Don't forget to document them, please.
