### ISSUE TITLE
Vi-mode indicator

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14611]
To show the state of the dietline - insert mode or a command mode. Should be shown in the vi-mode only. What do you think? Will be it useful enough?

**Comment by xx55x** [comment]
This would definitely be useful in my opinion. I may be biased I always have the mode visible in readline. I’d say it would be a great feature though.

**Comment by deepakchethan** [comment]
It would definitely be useful, but where would we make the indicator appear ?

**Comment by XVilka** [comment]
The rightmost position of the prompt maybe? @radare what do you think?

**Comment by radare** [comment]
Or different color? We can do a poll or suggest what other impl do. I never use this vi mode.. in fact after being in r2 i have started to take interest in using it

**Comment by deepakchethan** [comment]
ping @radare @XVilka decided anything?

**Comment by XVilka** [comment]
I suggest the following:
- [ ] Add the option `scr.prompt.mode=true`
- [ ] Show the different color of the prompt depending if it is a normal or insert mode. Maybe make the normal mode of the complement color of the insert prompt mode one?

**Comment by deepakchethan** [comment]
Sounds good, will make a pr

**Comment by XVilka** [comment]
@deepakchethan can you please send a PR to radare2book with a few lines about this option and how to detect when it's normal mode, and when it's insert one? Maybe with a screenshot?
