### ISSUE TITLE
Do not add refline on the second line of comment after the end of the block

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14627]
### Work environment

radare2 3.7.0-git 23937 @ linux-x86-64 git.3.6.0-206-g187e51704
commit: 187e51704f486db45802d03dcbd87af399831b51 build: 2019-07-23__13:01:45

### Expected behavior
Do not show `|` character after the end of the block

### Actual behavior
Note, there is a second line of comment after `mov dword [var_ch], 0x40`, and refline ('|' character) is shown

### Additional Logs, screenshots, source-code,  configuration dump, ...

![image](https://user-images.githubusercontent.com/203261/61692173-ba439380-ad5f-11e9-8a55-ebb349d6a19f.png)

**Comment by radare** [comment]
Thats becuase of multiline comments. Nothing to do with blocks

**Comment by XVilka** [comment]
Obviously, but I wasn't sure how to write it. Anyway, image shows
everything.
