### ISSUE TITLE
Do not show reflines from non-code areas 

### ISSUE THREAD

**Issue by GustavoLCR** [radare/radare2#14622]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian
| File format of the file you reverse (mandatory)      | coff
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22738 @ linux-x86-64 git.3.3.0-1374-ge2dd97aa0 commit: e2dd97aa098b016aabaff26216d02161d3acb2c8 build: 2019-07-22__19:40:14

### Expected behavior
Reflines are not shown if origin is not considered code (e.g. .string, .data)
### Actual behavior
![image](https://user-images.githubusercontent.com/23562137/61671116-9b3ff580-acbc-11e9-87e6-a761e61d781a.png)

### Steps to reproduce the behavior 
- Open the file
- `s str.Unknown`
- Look around with `jk`

### Additional Logs, screenshots, source-code,  configuration dump, ...

[tif_dir.zip](https://github.com/radare/radare2/files/3419445/tif_dir.zip)

**Comment by radare** [comment]
I would just check if map contains x bit set
