### ISSUE TITLE
Shortening Dalvik/Java method names

### ISSUE THREAD

**Issue by radare** [radare/radare2#14655]
Dex code will be more readable if we can shorten the names of the methods. and not just by using the afii/aii imports things. but also by removing the arugments expected to be processed by the function. dex code is usually generated by compilers so it must be verified and not call methods that have different argument types. decompilers and type analysis can still take this info from the signature. But we need a way to make the demangled output shorter some how..

here's an example.

```
- sym.imp.Landroid_content_Intent.method.getComponent__Landroid_content_ComponentName
+ intent.getComponent
```

another example:

```
- sym.imp.Ljava-util_ArrayList.method_size_I
+ ArrayList.size
```

this "issue" applies to any dex file, no need to submit a new one

**Comment by kazarmy** [comment]
To disambiguate e.g. between:

[java.io.PrintWriter#print(int)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/PrintWriter.html#print(int))
[java.io.PrintWriter#print(long)](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/io/PrintWriter.html#print(long))
mypackage.PrintWriter#print(int)
?

I suggest always adding a hash of the package + parameter list, e.g.:
```
PrintWriter.print_7d73768
PrintWriter.print_b6b1baa
```
(hashes are for illustration only)

instead of just adding ordinals:
```
PrintWriter.print
PrintWriter.print_2
```
since hashes won't change if method processing order changes.

**Comment by kazarmy** [comment]
A hash of the whole signature would probably work fine too.

**Comment by radare** [comment]
This is just for visualization. If we truncate the name without context (imports) there will be information loss and a suffix with numbers and such will be useless for the users because that will give 0 info.

Imho the pkgname unless messing with obfuscated code (1-2 letter classnames) can be removed and by context the code should be readable. The arguments and types of the call may fail too the same issue. We may infer the types from that but the user doesnt needs to know the whole signature most of the time because otherwise it will fail at runtime

**Comment by radare** [comment]
A hash gives 0 info to the user. And r2 should know the real info of the call behind the scenes so refs and such may be valid. As i said my idea for this is just to ease readability

**Comment by kazarmy** [comment]
Yes but if the user does:
```
s PrintWriter.print
```
which print method does the user go to?

**Comment by radare** [comment]
The user cant s ... to anything demangled at all right now so i dont see any issue. And the user can always use hint keys to navigate this already

**Comment by kazarmy** [comment]
I see ... i was afraid that you were going to say "nowhere" :sweat_smile:
