### ISSUE TITLE
simavr: Run aeim to get dbg->anal->esil initialized

### ISSUE THREAD

**Issue by rodarima** [radare/radare2#14669]
When debugging an AVR program running with simavr:
```
% simavr -m atmega328p -g blink.elf
Loaded 160 .text at address 0x0
Loaded 0 .data
avr_gdb_init listening on port 1234

% r2 -a avr -d gdb://127.0.0.1:1234 -e dbg.exe.path=blink.elf
= attach 0 1
= attach 0 0
= attach 0 0
Invalid range to find strings 0xf4 .. 0xf4
= attach 0 0
 -- Mind that the 'g' in radare is silent
[0x00000000]> 
```
The following message appears when changing the PC:
```
[0x00000000]> ds
Run aeim to get dbg->anal->esil initialized
[0x00000068]>
```
I used `e dbg.verbose=0` to disable the message, as the debugged program seems to work properly. It seems is coming from [here](https://github.com/radare/radare2/blob/master/libr/debug/trace.c#L68).

### Work environment

Radare2 version from Arch Linux community repository:
```
% r2 -v
radare2 3.6.0 0 @ linux-x86-64 git.3.6.0
commit: unknown build: 2019-07-01__21:50:36
```
with [simavr 1.6](https://github.com/buserror/simavr/releases/tag/v1.6)

The binary [blink.elf.zip](https://github.com/radare/radare2/files/3438192/blink.elf.zip) is just a blinking led in a loop.

**Comment by radare** [comment]
This is a useless warning that u can ignore and its removed in git already

**Comment by radare** [comment]
Pls dont report issues of nongit code
