### ISSUE TITLE
"f=" improvement

### ISSUE THREAD

**Issue by s0i37** [radare/radare2#14672]
Hello.
The "fs somespace" allows to select a flag space.
But "f=" will print ascii representation for whole flags from every flag space. I suggest to consider selected flag spaces for "f=" result.

**Comment by radare** [comment]
👍

**Comment by deepakchethan** [comment]
Current implementation is like:
Usage: f= [glob] to grep for matching flag names

@pancake @XVilka Are you sure you want to change this behaviour?

**Comment by radare** [comment]
Keep that behaviour but it should honor the flagspace

**Comment by s0i37** [comment]
btw, `f= glob` doesn't work for me.
```
/x something
f= search
```
nothing returns

**Comment by radare** [comment]
Thats expected there are no flags with “search” created in the name

**Comment by s0i37** [comment]
No, in my case "search" or another flagspace has flags inside.

**Comment by radare** [comment]
Then use fs to select it

**Comment by s0i37** [comment]
I don't understand.
You mean
```
/x 5555
fs search
f= search
```
Right?

**Comment by radare** [comment]
No. Just dont pass the search arg to f=

**Comment by radare** [comment]
But i lnow f= ignores fs. And thats what must be fixed
