### ISSUE TITLE
Opening object files results in error

### ISSUE THREAD

**Issue by Hi-Angel** [radare/radare2#14699]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux/x86_64/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22401 @ linux-x86-64 git.3.6.0-275-g094dbf331b<br>commit: 094dbf331b31edf0d7dc4aea03d4e75b0adfd209 build: 2019-07-30__08:23:40

### Expected behavior
No errors

### Actual behavior

    $ r2 ./a.o
    Invalid range to find strings 0x63 .. 0x63
    Warning: run r2 with -e io.cache=true to fix relocations in disassembly

### Steps to reproduce the behavior

    $ cat test.cpp
    int main() {}
    $ g++ test.cpp -c -o a.o -g3 -O0
    $ r2 ./a.o
    Invalid range to find strings 0x63 .. 0x63
    Warning: run r2 with -e io.cache=true to fix relocations in disassembly
    -- Move the comments to the right changing their margin with asm.cmt.margin
    [0x08000058]>

The `a.o` file attached:
[a.o.gz](https://github.com/radare/radare2/files/3446249/a.o.gz)

### Additional Logs, screenshots, source-code,  configuration dump, ...

    gcc version 8.3.0

This is reproducible both with radare2 `3.6.0` and the current git.
Also: running `pdf main` results in `p: Cannot find function at 0x08000058`

**Comment by Hi-Angel** [comment]
> Also: running `pdf main` results in p: `Cannot find function at 0x08000058`

Actually, it's a separate bug, is it…? I'm playing around, and it seems radare2 knows where the function resides, so it should be able to find it with disregard to the error this report is about.

**Comment by radare** [comment]
Because there sre no strings?

**Comment by Hi-Angel** [comment]
> Because there sre no strings?

I'm not sure what you mean, but executing `strings a.o | grep main` gives me a match.

**Comment by radare** [comment]
Main is not a string. Its a symbol

**Comment by Hi-Angel** [comment]
Okay… Then, if radare sees the symbol, its name, and information about it, why shouldn't it be able to print disassembly for `pdf main`? FWIW, `objdump -d` has no problem with it.

**Comment by radare** [comment]
I was refering yo yhe 0x68 warning

**Comment by Hi-Angel** [comment]
Oh, sorry, I see. But, where this range come from: `Invalid range to find strings 0x63 .. 0x63`? Does that mean the object file has malformed header?

**Comment by radare** [comment]
it means the strings section size is 0, so we should probably just hide this warning

**Comment by radare** [comment]
just tested your bin and everything works as expected. i have fixed the warning too. pdf wont work i fyou dont analyze first with 'af' for example (or aa)

**Comment by Hi-Angel** [comment]
> pdf wont work i fyou dont analyze first with 'af' for example (or aa)

I tried using `aaa` and `aaaa`, which I guess includes ones you mentioned, to no avail.

Here's a session with latest radare as of writing these words:

```haskell
$ r2 ./a.o
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
 -- give | and > a try piping and redirection
[0x08000058]> af
[0x08000058]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x08000058]> pdf main
This block size is too big (52428800<134217816). Did you mean 'pd @ 0x08000058' instead?
[0x08000058]>
```

**Comment by radare** [comment]
you missed the @ between pdf and main

**Comment by Hi-Angel** [comment]
Oh, amazing, thanks!
