### ISSUE TITLE
Broken `p=` and missing utf8 in `p==` output if `scr.utf8=true` 

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14696]
`p=` output is broken if `scr.utf8=true` is set with Konsole terminal emulator
Also `p==` output doesn't use the vertical Unicode line, so the lines would have been continuous.

![image](https://user-images.githubusercontent.com/203261/62100263-97ffc780-b2c3-11e9-92d7-86fb46b3bc5f.png)

**Comment by radare** [comment]
Buy a mac

**Comment by radare** [comment]
Or choose a better utf8 char

**Comment by deepakchethan** [comment]
I will use the same characters from disarm and make a pr

**Comment by radare** [comment]
Thanks

**Comment by radare** [comment]
this one is important

**Comment by radare** [comment]
ping @deepakchethan

**Comment by radare** [comment]
p== is fine imho, the problem is with p=

![Screenshot 2019-08-01 at 01 34 24](https://user-images.githubusercontent.com/917142/62255206-80782a00-b3fc-11e9-8a27-78ec8e40f9ab.png)

**Comment by radare** [comment]
ok if i use curvy then i get your issues

**Comment by radare** [comment]
even on Therm
