### ISSUE TITLE
Opening and accessing many files does not work correctly

### ISSUE THREAD

**Issue by deeso** [radare/radare2#1471]
Currently, radare does not allow the user to access _many_ files that are opened at the same time.  The files are listed but they don't seem to be accessible.  The `ob`command is used to access specific binary objects located under an RBinFile (e.g. RBinObject), but there is not an command to access a specific RCoreFile. 

Example of opening many binary files:

```
cd dumps/
r2 *
```

```
[0x00000000]> o
- 6 0x08048000-0x0804b000.bin @ 0x0 ; r
- 8 0x09d7a000-0x09d81000.bin @ 0x0 ; r
- 10 0x09d88000-0x09dde000.bin @ 0x0 ; r
- 12 0x6f200000-0x6f400000.bin @ 0x0 ; r
- 14 0x8e800000-0x8ea00000.bin @ 0x0 ; r
- 16 0x92800000-0x92877000.bin @ 0x0 ; r
- 18 0x92878000-0x9287a000.bin @ 0x0 ; r
- 20 0x9287c000-0x92882000.bin @ 0x0 ; r
- 22 0x92884000-0x92889000.bin @ 0x0 ; r
- 24 0x9288d000-0x928ab000.bin @ 0x0 ; r
- 26 0x928af000-0x928b2000.bin @ 0x0 ; r
- 28 0x928db000-0x928dc000.bin @ 0x0 ; r
- 30 0x928e2000-0x928e4000.bin @ 0x0 ; r
- 32 0x928e7000-0x928e8000.bin @ 0x0 ; r
- 34 0x928ec000-0x928ef000.bin @ 0x0 ; r
[0x00000000]> px 0xf
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  f830 6000 008e 65c1 a031 6000 008e 65    .0`...e..1`...e 
[0x00000000]> ob 20
[0x00000000]> px 0xf
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  f830 6000 008e 65c1 a031 6000 008e 65    .0`...e..1`...e 
```

It looks like the RCoreFile is not synchronized in the RCore environment, so the bytes are not correctly printed.  This may be an issue with RIO.

**Comment by ret2libc** [comment]
I have many files loaded and some of them overlap (the situation is: i have a packed binary, i decoded some functions and now i want to load them at their original address, but unpacked). I can see the functions but if i do 'aap' i see no function identified, even if they are there and with standard preludes.
Same if i do '/x 5589e5'.

I think it's related to overlapping files and related to this.

**Comment by radare** [comment]
Cc @condret and his librio replacement

**Comment by radare** [comment]
Are those files overlapped by maps or sections?

**Comment by ret2libc** [comment]
I think by sections. The output of 'o' is:
```
- 6 ./topack @ 0x0 ; r size=6160
- 8 ./0x08048655.bin @ 0x8048655 ; rw size=69
- 10 ./0x0804869a.bin @ 0x804869a ; rw size=68
- 12 ./0x080486de.bin @ 0x80486de ; rw size=92
- 14 ./0x0804873a.bin @ 0x804873a ; rw size=217
- 16 ./0x08048813.bin @ 0x8048813 ; rw size=209
- 18 ./0x080488e4.bin @ 0x80488e4 ; rw size=39
- 20 ./0x0804890b.bin @ 0x804890b ; rw size=158
- 22 ./0x080489a9.bin @ 0x80489a9 ; rw size=153
- 24 ./0x08048a42.bin @ 0x8048a42 ; rw size=99
- 26 ./0x08048aa5.bin @ 0x8048aa5 ; rw size=333
```
but the main file, topack, has the text section that overlaps with some of the other mapped files.
```
[0x08048655]> iS~text
idx=12 vaddr=0x080484a0 paddr=0x000004a0 sz=2034 vsz=2034 perm=-r-x name=.text
```

**Comment by radare** [comment]
I command will only show the info of the last file opened unless you select another one. In lldb its always showing the info of all the bins, i was planning to support this with an itetator.

As long as all bins are mapped in the same region. Io will priorize the last one over the previous ones. So its totally ok that you cant find over all files using a linear search.

There's a search.in=io.maps option that should help in that case. But i would suggest you to disable iova in that case.

**Comment by radare** [comment]
Any update on this?

**Comment by Maijin** [comment]
ping
