### ISSUE TITLE
Merge those 3 menus into 1

### ISSUE THREAD

**Issue by radare** [radare/radare2#14711]
Fun, about and help

<img width="403" alt="Screenshot 2019-07-31 at 05 16 59" src="https://user-images.githubusercontent.com/917142/62181132-8285ae80-b352-11e9-8210-2cd00f20a9b6.png">

i would prefefr to have user defined commands in there rather than a lot off top level menu entries

**Comment by XVilka** [comment]
What about loading them from the file instead?

**Comment by radare** [comment]
Related to the hierarchical hud issue i filled yesterday
