### ISSUE TITLE
Segfault on panels menu

### ISSUE THREAD

**Issue by GustavoLCR** [radare/radare2#14732]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 23236 @ linux-x86-64 git.3.6.0-308-gdb1d3ea45 commit: 7592fa52a9a0018602a4bce8cf64dcf4ee2718b3 build: 2019-07-31__18:38:41

### Expected behavior
No segfault
### Actual behavior
![image](https://user-images.githubusercontent.com/23562137/62255532-f4520c80-b3d3-11e9-8fb8-29098e7a931b.png)

### Steps to reproduce the behavior
- `e scr.utf8=1`
- Enter panels mode `V!`
- Click on menu item
- Click on the line that separates the menu from the panels (the corner is more reliable)
- Try a few times if doesn't happen on the first time

![image](https://user-images.githubusercontent.com/23562137/62255129-4b56e200-b3d2-11e9-9506-e3b2dc9d1300.png)

![image](https://user-images.githubusercontent.com/23562137/62255299-ec459d00-b3d2-11e9-8779-fda368fc5cd7.png)

**Comment by radare** [comment]
cant repro
