### ISSUE TITLE
Build fails when using `--with-syscapstone` configure option

### ISSUE THREAD

**Issue by bacher09** [radare/radare2#14751]
### Work environment

If build was configured with `--with-syscapstone` option it will fail, because build system will try to link against bundled *capstone* which wasn't compiled.
It affects both latest master and latest release (3.7.0).

### Build log

[build.log](https://github.com/radare/radare2/files/3463936/build.log)

### Simple fix for master

```patch
--- ./radare2/shlr/capstone.mk    2019-08-03 17:55:05.884798639 +0300
+++ fix/radare2/shlr/capstone.mk  2019-08-01 06:08:36.000000000 +0300
@@ -1,5 +1 @@
+ifeq ($(USE_CAPSTONE),1)
+LINK+=${CAPSTONE_LDFLAGS}
+else
 LINK+=$(SHLR)/capstone/libcapstone.a
+endif

```
For 3.7.0 this [change](https://github.com/radare/radare2/commit/8b37ac49b609cc69b27a6b3b76fa9d8d819bae83) also should be ported.

**Comment by radare** [comment]
Just send a pr

**Comment by bacher09** [comment]
Done #14753.
