### ISSUE TITLE
Search not working on block-device

### ISSUE THREAD

**Issue by fandauchytil** [radare/radare2#14755]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | QEMU-KVM ; Debian GNU/Linux 9.9 (stretch); 4.9.168-1+deb9u4 (2019-07-19) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0 22586 @ linux-x86-64 git.3.7.0 commit: cb2648cbbde3cd63cb1b2a9b1d4269c97bd653b8 build: 2019-08-03__15:16:58

### Expected behavior

Working 'search' on block-device.

### Actual behavior

'Search' on block-device does not work at all. It either matches nothing or it matches "everything".

### Steps to reproduce the behavior

```
# blockdev --getsize64 /dev/vdb1
1063256064
# r2 /dev/vdb1
```

1. No "r2" virtual seek (= I'm allways on virtual offset 0):

```
[0x00000000]>  b
0x100
[0x00000000]> px
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  0000 0000 0000 0000 0000 0000 0000 0000  ................
...
0x000000f0  0000 0000 0000 0000 0000 0000 0000 0000  ................
[0x00000000]> px 32 @ 16k
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00004000  0101 0000 0000 0000 0000 0001 0000 0024  ...............$
0x00004010  0000 0020 0000 0007 7665 7273 696f 6e00  ... ....version.
[0x00000000]> / version
Searching 7 bytes in [0x0-0x3f600000]
hits: 0
[0x00000000]> /x 7665
Searching 2 bytes in [0x0-0x3f600000]
hits: 0
[0x00000000]> / \x76
Searching 1 byte in [0x0-0x3f600000]
hits: 0
[0x00000000]> /!x 00
Searching 1 byte in [0x0-0x3f600000]
hits: 0
[0x00000000]> o
 3 * r-x 0x3f600000 /dev/vdb1
[0x00000000]> om
 1 fd: 3 +0x00000000 0x00000000 - 0x3f5fffff r-x 
```

2. "r2" virtual seek. Search starts returning false-positive "hits" if there is at least one match inside that block I'm currently in:

```
[0x00000000]> s 4m
[0x00400000]> px 32
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00400000  0000 0077 2101 0001 0061 80ab b22a f502  ...w!....a...*..
0x00400010  0b00 0a02 001a 0a0f 0005 0200 042c 0003  .............,..
[0x00400000]> /x 0000007721010001006180abb22af502
Searching 16 bytes in [0x0-0x3f600000]
hits: 4153344
Do you want to print 4153344 lines? (y/N) n
```

(That pattern above is present only twice on that device. Verified by different hexeditors.)

Actually that search was extremly fast. I had speed limit 1 MiB/s on that block-device (qemu bps), but r2 finished that search after 23 seconds. It shoud take about  17 minutes ... so here is `strace` of it:

```
write(2</dev/pts/11>, "\r[  ]  0x01093f00 < 0x3f600000  hits = 0   \r[# ]", 48) = 48
lseek(7</dev/vdb1>, 17383168, SEEK_SET) = 17383168
lseek(7</dev/vdb1>, 0, SEEK_CUR) = 17383168
lseek(7</dev/vdb1>, 0, SEEK_SET) = 0      # <---
read(7</dev/vdb1>, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 256) = 256
lseek(7</dev/vdb1>, 17383424, SEEK_SET) = 17383424
lseek(7</dev/vdb1>, 0, SEEK_CUR) = 17383424
lseek(7</dev/vdb1>, 0, SEEK_SET) = 0     # <---
read(7</dev/vdb1>, "\0\0...
```

That second lseek() is *the* problem. r2 allways reads the same block over and over again. (This behavior is simillar for those false-positive matches, but with that second seek is 4 MiB => exact number of "r2 virtual seek offset".)

```
lseek(7</dev/vdb1>, 31744, SEEK_SET) = 31744
lseek(7</dev/vdb1>, 0, SEEK_CUR) = 31744
lseek(7</dev/vdb1>, 4194304, SEEK_SET) = 4194304   # <---
read(7</dev/vdb1>, "\0\0\0w!\1\0\1\0a\200\253\26...
lseek(7</dev/vdb1>, 32000, SEEK_SET) = 32000
lseek(7</dev/vdb1>, 0, SEEK_CUR) = 32000
lseek(7</dev/vdb1>, 4194304, SEEK_SET) = 4194304   # <---
read(7</dev/vdb1>, "\0\0\0w!\1\0\1\0a\200\253\26...
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

- No ~/.radare2rc.
- No plugins.
- It was tested on clean build and environment.

**Comment by radare** [comment]
See e search.in= and from/to to specify boundaries. I think i~size is 0. Is the om map created properly?

**Comment by fandauchytil** [comment]
Before I created this issue, I tried both: 1. default search from/to: 
```
[0x00000000]> e search.from 
0xffffffffffffffff
[0x00000000]> e search.to
0xffffffffffffffff
```
and 2. set them to excact values:
```
e search.from=0
e search.to=0x3f5fffff
```
Both had the same results.

'i' is showing correct size:
```
[0x00000000]> i ~size
size     0x3f600000
```
I think that 'om' mapping is correct:
```
[0x00000000]> om
 1 fd: 3 +0x00000000 0x00000000 - 0x3f5fffff r-x 
```
In my previous testing I didn't set 'search.in', I thought that 'io.maps' is what I need. Now I tried 'raw' and it had the same result:
```
[0x00000000]> e search.from=0
[0x00000000]> e search.to=0x3f5fffff
[0x00000000]> e search.in=raw
[0x00000000]> /!x 00
Searching 1 byte in [0x0-0x3f5fffff]
hits: 0
[0x00000000]> px 16 @ 16k
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00004000  0101 0000 0000 0000 0000 0001 0000 0024  ...............$
```

I'm puzzled by that double lseek(2). First lseek(2) is correct seek inside a block-dev, but before read(2) is issued, there is second lseek(2) to the possition of r2 virtual seek, so that read(2) reads incorrect data (see "Steps to reproduce the behavior").

What am I missing?

**Comment by fandauchytil** [comment]
I found out that if file is opened in read-write mode, search starts working as expected:

```
# r2 -n /dev/loop1

[0x00000000]> Ps ro
[0x00000000]> / 01
Searching 2 bytes in [0x0-0x3f600000]
hits: 0
[0x00000000]> oo+
[0x00000000]> Ps rw
[0x00000000]> / 01
Searching 2 bytes in [0x0-0x3f600000]
hits: 6
...
```

Saved project files show that only differece are in mapping mode (`r-x` -> `rwx`) and in incremented `search.kwidx`.

**Comment by radare** [comment]
i can confirm this issue, enotime to fix today, but we need to solve this hopefully before r2con. can you give it a try?

**Comment by fandauchytil** [comment]
I think I found it (it is probably the problem, but it is maybe going deeper).

`r2 -n` and `r2 -n -w` have different code paths. Here are call trees (indent == level; # == comments):

```
# r2 -n /dev/vdb1 -c '/!x 00'

  r_io_def_mmap_lseek     # [libr/io/p/io_default.c]
    r_io_def_mmap_seek
      # mmo->rawio == 1   # <RIOMMapFileObj *mmo>
      lseek               # [glibc lseek]
    # <-- no settings of 'io->off' !!!
    # return lseek (mmo->fd, offset, whence);
```
```
# r2 -n -w /dev/vdb1 -c '/!x 00'

  r_io_def_mmap_seek
    # mmo->rawio == 0   # <RIOMMapFileObj *mmo>
    r_buf_seek          # io->off = r_buf_seek (mmo->buf, offset, whence);
      buf_seek
        b->methods->seek  # -> buf_bytes_seek()
          # case R_BUF_SET: priv->offset = addr; return priv->offset;
  # io->off = r_buf_seek (mmo->buf, offset, whence);
  # return io->off;
```

The first tree (read-only mode) shows 2 things:
1.  `mmo->rawio` is true (1), so libc `lseek()` is called right away.
2. `io->off` is not set.

The second tree shows vice versa:
1.  `mmo->rawio` is false (0) => different call-path is chosen.
2. `io->off` is set to the right offset.

Patch for setting up `io->off` is easy (I will try to create pull request), but I don't understand that `mmo->rawio` (especially if I don't see it in `r2` the settings).
