### ISSUE TITLE
Add option to save r2 projects to an arbitrary directory

### ISSUE THREAD

**Issue by jhand2** [radare/radare2#14818]
(Please let me know if this feature is already available and I just failed to find it)

**Is your feature request related to a problem? Please describe.**
I don't want to save all projects (Ps) in the same directory. Usually I want the project file to be saved in the same directory as the binary I'm working on. I do this so I can save state in a git repo and keep working on a different computer.

**Describe the solution you'd like**
I want to be able to save the project file with an absolute or relative path. Something like `Ps ~/some/path/project.r2`. Then to reload the project with `r2 -p ~/some/path/project.r2 <my_binary>` or `Po ~/some/path/project.r2 <my_binary>`.

**Describe alternatives you've considered**
I could keep my r2 projects all in one git repo and sync that across machines. But I would prefer to keep my files together for the same project.

**Comment by radare** [comment]
e dir.project

**Comment by jhand2** [comment]
I was looking for a one-off solution rather than setting it globally for all projects. But I don't think it would make the process any simpler, so this is good. Thanks

**Comment by radare** [comment]
Use r2 -e if u want to handle this in a oneliner
