### ISSUE TITLE
Radare2 crashes on certain input

### ISSUE THREAD

**Issue by marc-groundctl** [radare/radare2#14821]
# This template is meant for bug reports, if you have a feature request, please be as descriptive as possible and delete the template

Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template below*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch x86_64
| File format of the file you reverse (mandatory)      | N/A
 Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.1 22602 @ linux-x86-64 git.3.7.1-10-ge0532b817
| | commit: e0532b817fbb3726a11c911a9cb9ef04270e4d73 build: 2019-08-16__17:26:06

### Expected behavior

r2 does not crash

### Actual behavior

r2 crashes

### Steps to reproduce the behavior 
```
$ cat r2_crash.xxd
00000000: 2274 6420 656e 756d 2066 207b 2065 203d  "td enum f { e =
00000010: 2031 2c09                                 1,.
$ xxd -r r2_crash.xxd | r2 -
Segmentation fault (core dumped) 
$
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

This does not happen if the enum member does not end in the letter e.  It also does not happen if there is no space before the equals sign.

**Comment by radare** [comment]
Another tcc parser issue

**Comment by radare** [comment]
Imho pre r2con should be 3.8
