### ISSUE TITLE
r2 =  breaks the terminal configuration

### ISSUE THREAD

**Issue by radare** [radare/radare2#14834]
Reproducer:

<img width="719" alt="Screenshot 2019-08-18 at 19 21 39" src="https://user-images.githubusercontent.com/917142/63228014-69537d80-c1ed-11e9-8e38-3e6b473451ce.png">

**Comment by deepakchethan** [comment]
@radare  am I missing something ? 

<img width="513" alt="Screen Shot 2019-08-19 at 9 50 45 PM" src="https://user-images.githubusercontent.com/20895544/63281982-76df3500-c2cb-11e9-98aa-52ea6a2c4124.png">

**Comment by radare** [comment]
Type something after this and you’ll see that the terminal is now unconfigured
