### ISSUE TITLE
Support uppercase 0X instead of just 0x

### ISSUE THREAD

**Issue by radare** [radare/radare2#14840]
basically to make r2 more butterfly friendly

**Comment by radare** [comment]
proof
```
$ rax2 0X312
0x0
```

**Comment by bca0** [comment]
I think this is a worthy improvement. I have fooled myself many times by typing `0X` instead of `0x`. 

I would like to fix it if no one is working on the ticket.

**Comment by radare** [comment]
I implemented this after opening the issue but forgot to close
