### ISSUE TITLE
`Vv` + `g` (seek offset) doesn't work properly

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14856]
`r2 /bin/ls` then `aaa`, then go into `Vv` mode. It shows us `entry0` function. If we call the `seek to offset` command (`g` key), and type `main`, it doesn't jump to main and shows it. Note, that `main` is not in the visible part of the functions list. If we seek into any function that is visible in the functions list window, e.g. `sym.imp.strrchr`, it will show `>` character before it, but will not show the function body in the corresponding window.

**Comment by deepakchethan** [comment]
This is because, the seek is changed with g and not the current selected function. I will change this behaviour now.
