### ISSUE TITLE
graph-graph navigation not seeking

### ISSUE THREAD

**Issue by radare** [radare/radare2#14859]
1. analyze the program

![Screenshot 2019-08-20 at 13 38 26](https://user-images.githubusercontent.com/917142/63344052-cb2bf880-c34f-11e9-9bf6-1a1fb18f65b5.png)

2. enter visual graph 
![Screenshot 2019-08-20 at 13 38 12](https://user-images.githubusercontent.com/917142/63344034-c36c5400-c34f-11e9-91db-d9fe36155f0b.png)

3. press '>' to see callgraph

![Screenshot 2019-08-20 at 13 38 00](https://user-images.githubusercontent.com/917142/63344021-bc454600-c34f-11e9-8596-66764db9060b.png)

4. press 'tab' to select next  node (then press 'G', space, enter, or anything to seek there')

*  nothing happens *

**Comment by deepakchethan** [comment]
After going through the code. My observations:
* enter: it is not linked to any action
* space: It is for exiting from call-graph mode
* G: It is for printing the debug traces graph

So I'll just map the enter key to change the seek to current graph node address

**Comment by radare** [comment]
👍

**Comment by deepakchethan** [comment]
Turns out the seek is changed with tab itself, if you use ':s' command, you can see the seek is being changed. So assigning any keys would be pointless.
