### ISSUE TITLE
Visual mode/panel layout not saved

### ISSUE THREAD

**Issue by Keramo** [radare/radare2#14869]
radare2 3.7.1 22484 @ linux-x86-64 git.3.7.1-49-g7f9b8bdab
commit: 7f9b8bdab345b433da4e124c0c07bbb26f0dee9d build: 2019-08-21__21:31:15

Panel layouts are no longer saved in visual mode (V!). Arranging views and tried to save but no .r2panels was created (entry is also not displayed under "load layouts"). Tried the same with version 3.7.0 in another virtual machine and all works fine.

**Comment by radare** [comment]
It was working fine with my patch but it was only supporting one layout

**Comment by Keramo** [comment]
Thanks for your response. The .r2panels file in ~/.local/share/radare2/ was missing after deleting the saved layouts under r2. I created it manually/empty and it worked to save and load layouts. It seems that saving a layout does not create the file on its own.

**Comment by radare** [comment]
Dont close it. The issue is there

**Comment by Vane11ope** [comment]
ok i will deal with this tonight

**Comment by radare** [comment]
this one is imporatnt? what's the current state of this after your last pr?

**Comment by Keramo** [comment]
For me, with the latest pr, all works fine. Thanks!
(radare2 3.7.1 22610 @ linux-x86-64 git.3.7.1-159-gb61a37e14
commit: b61a37e143cfb49eedc2030302b12a9686943d77 build: 2019-09-01__20:04:35)

Think, i can close the issue now.
