### ISSUE TITLE
Exiting from panels does not properly reset terminal.

### ISSUE THREAD

**Issue by roboman2444** [radare/radare2#14861]
Most notable missing cursor.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64, bash, urxvt
| File format of the file you reverse (mandatory)      | NA
| Architecture/bits of the file (mandatory)            | NA
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.1 22592 @ linux-x86-64 git.3.7.1-35-gea4ee051d commit: ea4ee051d086dfc5e8f91aaa8357666f36df0c69 build: 2019-08-20__10:33:57

### Expected behavior

Properly resets terminal state using escape characters when quitting from panels mode.

### Actual behavior

Does not reset. Cursor is missing and must use reset to fix.

### Steps to reproduce the behavior 

[https://asciinema.org/a/0OIJbGoNwYCY3xJbeNnQo6oDB](https://asciinema.org/a/0OIJbGoNwYCY3xJbeNnQo6oDB)

Enter panels mode
Quit panels mode using q

**Comment by radare** [comment]
This is panels. Visual mode works fine

**Comment by radare** [comment]
I fixed this in an unrelated pr. Will try to make it green
