### ISSUE TITLE
HJKL in visual mode cannot be undo seek with `u`

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#14887]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.1 22829 @ darwin-x86-64 git.3.7.1-66-g039de1ba5 commit: 039de1ba52ec8d50a5e02c3b576cd9bf201a363e build: 2019-08-24__10:57:14

### Expected behavior

`J` followed by `u` seek back to previous location

### Actual behavior

`J` followed by `u` doesn't seek back to previous location

### Steps to reproduce the behavior 
- Open a binary
- `V`
- `J`
- `u`

**Comment by radare** [comment]
same happens with jk, undo seek only happens when you follow hints or do 's' to seek

**Comment by radare** [comment]
if we keep track of all the page scrolls then the seek history can become huge. cutter dont do that either

**Comment by Maijin** [comment]
Actually you're right
