### ISSUE TITLE
V?! V?c don't work

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#14889]
# Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.1 22829 @ darwin-x86-64 git.3.7.1-66-g039de1ba5 commit: 039de1ba52ec8d50a5e02c3b576cd9bf201a363e build: 2019-08-24__10:57:14

### Expected behavior

`V?` `!` open panel mode
`V?` `c` cursor

### Actual behavior

`V?` `!` don't do anything
`V?` `c` don't do anything

### Steps to reproduce the behavior 
- Open a binary
- V?
- c or !

**Comment by radare** [comment]
the structured visual help needs more love. can you improve it a bit before r2con? i think that will help many people. also i think that we should make '_' in V? run the hud over "?*~..." basically to get a filtered interactive shell over the list of all the available commands.

**Comment by radare** [comment]
Please @Maijin can you help on improving the visual help?

**Comment by radare** [comment]
tiiiiired of waiting for this 2 line fix
