### ISSUE TITLE
Visual mode in Mingw32 and Cygwin consoles (mintty and ConEmu)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1488]
1. Scrolling using PgUp/PgDwn and arrow keys doesn't work

2. When you enter visual mode, its working area not automatically resized to the console size, while cli mode is expanded ok, and if you do something in cli, so it can fill the screen, then enter visual mode - you will see visual mode actually working in the small area and garbage around (including chars shown first in cli mode).

3. Scrolling is **very** slow.

**Comment by XVilka** [comment]
![r2-win-visual](https://cloud.githubusercontent.com/assets/203261/5704257/d6e31d22-9a80-11e4-9b2c-c6fd5537fff2.png)

**Comment by radare** [comment]
Should be fixed in Git. at least for w32. because wine fails and reports always 80x25

**Comment by XVilka** [comment]
Note for myself: wine has bug on autodetection of terminal size - just run
```wine radare2.exe rabin2.exe```

And here are the tips how to implement: http://stackoverflow.com/questions/6812224/getting-terminal-size-in-c-for-windows and http://stackoverflow.com/questions/1022957/getting-terminal-width-in-c

**Comment by radare** [comment]
That issue is because wine doesnt reports unix terminal size to the windows application, at least.. using the standard w32 api. i already implemented this code and it is not working on unix. maybe it works on cmd.exe, can you confirm?

**Comment by XVilka** [comment]
windows console fixed in 45a1eb5ca0ad2def2428b545a5825eab6140e72e and 2b493cdbc617247993afbc790971ea3c18e960fc

Only the rest part is wine console.

**Comment by XVilka** [comment]
here is the graph mode
![r2-win-graph](https://cloud.githubusercontent.com/assets/203261/5705827/194e44dc-9a8d-11e4-9a36-f20b33fb78cc.png)

**Comment by crowell** [comment]
looks fixed!

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://djalesh.tachov.cz/consecutive.php?prfhr>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://greenwichtentjobs.com/silent.php?5>

 

lukas-runas@gmx.de
