### ISSUE TITLE
Mouse wheel results in ';' injected in panels

### ISSUE THREAD

**Issue by radare** [radare/radare2#14896]
1. enter panels mode
2. wheel the mouse for a while
3. press 'J'

<img width="839" alt="Screenshot 2019-08-25 at 17 33 19" src="https://user-images.githubusercontent.com/917142/63652261-711ba080-c75e-11e9-8816-e303cc317867.png">

**Comment by deepakchethan** [comment]
I can reproduct it in visual as well, 
1. click '/' to highlight
2. Wheel the mouse
