### ISSUE TITLE
radiff2 dot generates invalid output

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14900]
Seems it doesn't filter the colors from the dot output, or not convert them into the dot format
```
radiff2 -g main -m d /bin/false /bin/true | xdot -
```
Then xdot returns an error.

**Comment by deepakchethan** [comment]
Yep, able to reproduce, working on it now.

**Comment by XVilka** [comment]
@deepakchethan it wasn't properly fixed yet. While xdot doesn't return an error, the output is still rubbish:
![image](https://user-images.githubusercontent.com/203261/63741992-ea83d200-c8c9-11e9-88b2-6a334c58afa3.png)

**Comment by deepakchethan** [comment]
I think this is because I recently enabled color for the ascii graphs, its a one line fix. Will do it, I'm sorry about it :)
