### ISSUE TITLE
Can't rename variables or functions in command mode

### ISSUE THREAD

**Issue by atomheartother** [radare/radare2#14907]
I understand that this is extremely basic and I assume this is me messing this up somehow but I've been unable to find any information on this anywhere, the error message `Cant find var by name` isn't even indexed on google outside of the radare2 source code.

### Work environment

In short, this is a fresh install of radare2 on Arch with all packages up to date.

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux / x86_64 
| File format of the file you reverse (mandatory)      | Every format i've tried (PE and ELF)
| Architecture/bits of the file (mandatory)            | PE32, ELF 64bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0 0 @ linux-x86-64 git.3.7.0 commit: unknown build: 2019-08-07__22:03:12

### Expected behavior
After analysis, typing `afvn` on an existing variable or `afn` on an existing function should rename it.

### Actual behavior
Despite being able to autocomplete variables and functions when i tab into the `afvn` and `afn` commands, `radare2` is unable to find them when i launch the command. 

In a function called main, the variables are found:
```sh
[0x0040091b]> afv
var int32_t var_118h @ rbp-0x118
var int32_t var_110h @ rbp-0x110
var int32_t var_104h @ rbp-0x104
var int32_t var_100h @ rbp-0x100
var int32_t var_1h @ rbp-0x1
arg int argc @ rdi
arg char ** argv @ rsi
arg char ** envp @ rdx
```
Autocomplete works:
```sh
[0x0040091b]> afvn var_1
var_104h   var_110h   var_118h   var_100h   var_1h     
```

But the commands don't:
```sh
[0x0040091b]> afvn var_118h test
Cant find var by name
[0x0040091b]> afn main test
Cannot find function at 0x00000000
[0x0040091b]> afn 0x0040091b test
Cannot find function at 0x00000000
```

### Steps to reproduce the behavior 
- Open any binary in `r2` ([example file](https://github.com/radare/radare2/files/3545957/test.zip))
- `aaaa` to analyze
- Go to a function with a variable (`s sym.alignToFour` in the example file)
- Try to rename it. The bug occurs. (`afvn var_4h test` for the example file)

### Notes
- Visual mode renaming works just fine, this only occurs when i use commands

**Comment by radare** [comment]
see the help message. the arguments are swapped

**Comment by atomheartother** [comment]
Huh, that is it, did the order of arguments change recently? Anyway thanks :)

**Comment by SakiiR** [comment]
I had the same issue lol

cheers @atomheartother

**Comment by rahulterani** [comment]
First check the syntax by: 
:> afv? 

Currect syntax to rename argument/local variable is: 
:> afvn (new_variable) (old_variable)
