### ISSUE TITLE
Bars and fire dont follow color scheme

### ISSUE THREAD

**Issue by radare** [radare/radare2#14911]
though that was fixed already

![Screenshot 2019-08-27 at 15 57 17](https://user-images.githubusercontent.com/917142/63777414-5c1c4a00-c8e3-11e9-8407-5c2be663dad8.png)

**Comment by radare** [comment]
![Screenshot 2019-08-27 at 16 00 21](https://user-images.githubusercontent.com/917142/63777693-d2b94780-c8e3-11e9-9924-b4fc63029aaa.png)

**Comment by deepakchethan** [comment]
We might have to add new colors in palette to support this. Is that okay or should I reuse some other vars?

**Comment by radare** [comment]
Reuse some others for now. Most color schemes use similar colors or highlight levels for similar instructions. Just pick some that make sense and we can evaluate adding some more later and update all the themes

**Comment by radare** [comment]
this one is important
