### ISSUE TITLE
Mouse wheel not working in hud

### ISSUE THREAD

**Issue by radare** [radare/radare2#14914]
i think thats a regression

**Comment by deepakchethan** [comment]
I think this is because I disabled the mouse in the dietline becasue It was inserting semi colons everywhere in Visual mode we can an if condition in hud mode to avoid this and handle the mouse.
Is this approach okay @radare ?

**Comment by radare** [comment]
sgtm if it works and not glitches

**Comment by deepakchethan** [comment]
Workin on this now

**Comment by deepakchethan** [comment]
> i think thats a regression

No its not, mouse was never working in hud

**Comment by radare** [comment]
right, but itts still not working
