### ISSUE TITLE
Visual split mode is broken.

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#14926]
```
r2 /bin/ls
[0x000000]> aaa
[0x000000]> s main
[0x000000]> V\
```
And then try to scroll back and forth with arrow keys, then PageUp/PageDown. It makes the mess in the topmost split.

**Comment by radare** [comment]
wat. screenshot or reproducer i cant get anything wrong here

**Comment by XVilka** [comment]
@radare  yes, it seems fixed, probably along with other interface things. Closing.
