### ISSUE TITLE
Incorrect logic in "wo2" command

### ISSUE THREAD

**Issue by bagginslin** [radare/radare2#14937]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Void Linux, x86_64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.1 22592 @ linux-x86-64 git.3.7.1-142-g430a76a29 commit: 430a76a29e81b5d7ac1794268bd822ff34a119b4 build: 2019-08-31__10:20:34

### Expected behavior
`wo2` correctly swaps the first and second byte in each 16-bit word, resulting in `0201 0403 0605 0807`.

### Actual behavior
The output is `0402 0601 0803 0705`. (spaces added to increase readability).

### Steps to reproduce the behavior 
Doesn't need to be opened with a file
> b 8
> wx 0102030405060708
> wo2
> p8

### Additional Logs, screenshots, source-code,  configuration dump, ...
This seems to be caused by incorrect logic in https://github.com/radare/radare2/blob/430a76a29e81b5d7ac1794268bd822ff34a119b4/libr/core/cio.c#L249-L257
Please correct me if my understanding of endianness or the purpose of `wo2` is incorrect and this is actually the desired behaviour. Otherwise I'd be happy to put together a PR.

**Comment by radare** [comment]
it honors cfg.bigendian,  but i agree the current behaviour is confusing.

maybe this issue was introduced in here a3d9bf170e05d7fd6ece051f92caa9d9837dcff0

can you review/confirm?

**Comment by radare** [comment]
actually wtf
```
$ r2 -
[0x00000000]> wx 10203040
[0x00000000]> p8 4
10203040
[0x00000000]> wo2
[0x00000000]> p8 4
40200010
[0x00000000]> p8 8
4020001000300000
[0x00000000]> wx 10203040
[0x00000000]> wo4
[0x00000000]> p8 8
4030201000003000
[0x00000000]>
```
