### ISSUE TITLE
IO fails if opening a file when debugging

### ISSUE THREAD

**Issue by radare** [radare/radare2#1497]
```
$ r2 -d ls
> o /etc/services
(cannot read registers for pid 6)
(etc, etc, ..)
```

it's required to do `o 11006;dpa=11006;dp=11006` to bring it back. Its a bit confusing that we have `dp, dpa and dp=` to do the same.

There's no way to unraise a fd. What about `o -1`? or maybe o-0 ?

**Comment by condret** [comment]
tetris
