### ISSUE TITLE
Cannot find 'x' format on ihj (Inconsistent use of named/specified formats in RBinField.format)

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#15006]
To reproduce, open any elf binary and call `ihj`:
![Bildschirmfoto vom 2019-09-10 13-36-13](https://user-images.githubusercontent.com/1460997/64610629-f7c3b500-d3cf-11e9-99f5-53f912b91fa7.png)

This happens because here the command is created assuming `field->format` is the name of a format like it is `mach0_section` in another case, but for ELF it's just `x`:
https://github.com/radare/radare2/blob/07be18193e7d86bd6ba9a7d1a820b8a705f4e7e0/libr/core/cbin.c#L2800

**Comment by thestr4ng3r** [comment]
Actually I even get these errors with a mach0 binary:
[libr2ghidra_cutter.dylib.gz](https://github.com/radare/radare2/files/3601338/libr2ghidra_cutter.dylib.gz)
![Bildschirmfoto vom 2019-09-11 16-40-56](https://user-images.githubusercontent.com/1460997/64707318-1e0e5100-d4b3-11e9-935a-f3cac537dfde.png)

**Comment by radare** [comment]
pfo macho before that ihj

**Comment by radare** [comment]
yeah, proposals to link rbin with pfo are welcome
