### ISSUE TITLE
uzz binaries

### ISSUE THREAD

**Issue by lazymate** [radare/radare2#15008]
fuzz binaries

**Comment by lazymate** [comment]
ENOENT: no such file or directory, scandir './bins/fuzzed'
make[2]: *** [Makefile:30: js-tests] Error 1
make[2]: Leaving directory '/opt/radare2/radare2-regressions'
make[1]: *** [Makefile:19: all] Error 2
make[1]: Leaving directory '/opt/radare2/radare2-regressions'
make: *** [Makefile:382: tests] Error 2

**Comment by radare** [comment]
which kind of report is this and what are you trying to tell us?

**Comment by lazymate** [comment]
sorry am just a lerner tried to install radar2 on parrot os , this  was the error while making test  mentioned above , trying to make it work correctly , nothing serious if u don't wish to help , 
regards,

**Comment by radare** [comment]
I wish to help but i dont understand anything in here

**Comment by lazymate** [comment]
ill paste all stuff again , many thanks for replying

**Comment by XVilka** [comment]
Since nobody can understand what's going on, closing this one.
