### ISSUE TITLE
-P produces a worthless return value

### ISSUE THREAD

**Issue by l29ah** [radare/radare2#15002]
### Work environment

Gentoo/AMD64
raw
n/a
radare2 3.8.0 0 @ linux-x86-64 git.3.8.0
commit: HEAD build: 2019-09-05__07:05:31

### Expected behavior
`0` in case of a success, anything else in case of a failure.

### Actual behavior
Random stuff, `1` in case of the provided test case.

### Steps to reproduce the behavior 
```
#!/bin/sh
echo test > test
cat << EOF > patch
0x0 55
0x1 55
EOF
./binr/radare2/radare2 -q -w -P patch test
echo $?
```

**Comment by l29ah** [comment]
It's still `1` at 25fd8c6baf917d9befb14a9f026c22389d12a0c0.

**Comment by radare** [comment]
Uhm. It was working fine in my tests maybe i missed something, can you add some tests and improve my commit with your usecase?

**Comment by l29ah** [comment]
The test is up there in the original report. The result is identical.

**Comment by radare** [comment]
when i talk about tests i talk about the radare2-regressions testsuite. but well. ill take a look later today, busy irl now

**Comment by radare** [comment]
your script works ffine for me, i get 0 in return, what is the problem you are seeing?

**Comment by l29ah** [comment]
I get `1` yet correct `UUst` in the target file; updated to 43c61fccbdd0ac6ac2af40dd2106ea97f7db4607, same thing.

**Comment by radare** [comment]
How are you updating? Because running it like u do will use the system installed r2 libs, not the one you built

**Comment by l29ah** [comment]
Oh, after installing it system-wide it works, thank you!
