### ISSUE TITLE
MIPS Emulator increment T0 on BEQZ instruction

### ISSUE THREAD

**Issue by plrosat** [radare/radare2#15026]
5.0.0-27-generic #28~18.04.1-Ubuntu SMP Thu Aug 22 03:00:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I have the following code:

0x9d003e08      18002011       beqz t1, 0x9d003e6c
0x9d003e0c      04000825       addiu t0, t0, 4

At 0x9d003e08 (beqz t1, 0x9d003e6c), to is incremented and than again on the next line. Resulting in false emulation

I start the emulator like this:

r2 -m 0x9D000000 -a mips -A cdc_com_port_single.X.production2.bin
s 0x9fc00000
dr pc=0x9fc00000
pd 41
aecu 0x9fc000a0
aes
aes
aes
...

[cdc_com_port_single.X.production2.bin.gz](https://github.com/radare/radare2/files/3605965/cdc_com_port_single.X.production2.bin.gz)

**Comment by radare** [comment]
-A is not necessary at all

**Comment by radare** [comment]
t0 is incremented because mips executes one instruction after each branch because of the delay execution slot. i wrote a better testcase:

```
$ r2 -m 0x9D000000 -a mips -i test.r2 cdc_com_port_single.X.production2.bin
$ cat test.r2
s 0x9fc00000
ar pc=0x9fc00000
aecu 0x9fc000a0
aes
aes
aes
aes
dr=
aes
dr=
pd--4 @r:PC
aes
dr=
pd--4@r:PC
$
```

**Comment by plrosat** [comment]
ok thanks for the info, but if you execute next line it increment t0 again,...

**Comment by radare** [comment]
We can probably skip executing the next instruction if the conditional jump doesn't branches

**Comment by plrosat** [comment]
so at 0x9d003e08 (beqz t1, 0x9d003e6c) it increment t0 because branch wont be taken and then at next instruction (addiu t0,t0, 4) it increment t0 again

**Comment by radare** [comment]
Thats why im saying what i said in the previous message. Do u wanna try to fix?

**Comment by plrosat** [comment]
oh sorry, my first language is not english, I thought we miss understood... Well if you point me where to look at I might have a look, but I am sure you guys are better at lol

**Comment by radare** [comment]
I never played lol, but ill fix it later tonight probably

**Comment by radare** [comment]
can you please add the test in the r2r repo?
