### ISSUE TITLE
Odd behavior from iterator and segfault

### ISSUE THREAD

**Issue by securisec** [radare/radare2#15034]
## System
OS: Osx 10.14.6
R2 version: 

```
radare2 3.8.0 22840 @ darwin-x86-64 git.3.8.0-65-g25fd8c6ba
commit: 25fd8c6baf917d9befb14a9f026c22389d12a0c0 build: 2019-09-13__15:25:04
```

## Binary

```
/bin/ls
```

## Steps

```
s main
aaa
ecHi @@=`pdf~call[0]`
```

## .radare2rc

```
eco ayu
e scr.pager = less -R
e cfg.newtab = 1
e scr.color=3
e scr.utf8=1
e asm.lines.fcn = 1
e anal.strings =1
```

## Expected behavior
Get all the offsets from the from all `call`s. It seems some of the configs are fighting back against the output of `~pdf[0]` in this case. Also, `@@=` if failing to highlight based on `ecHi`

# asciinema
https://asciinema.org/a/pYXB9TkqfxxV4UXK1N6iOGfxG

**Comment by radare** [comment]
Pdf is not a good command to use for grepping columns, better use pif or pir, the behaviour is expected to fail
