### ISSUE TITLE
Potential copypaste bugs

### ISSUE THREAD

**Issue by pelijah** [radare/radare2#15043]
### The 'then' statement is equivalent to the 'else' statement:
https://github.com/radare/radare2/blob/16810089eec094c29c5073ecff43f85ebd4db809/libr/bin/format/mach0/mach0.c#L3832
https://github.com/radare/radare2/blob/16810089eec094c29c5073ecff43f85ebd4db809/libr/core/canal.c#L789
https://github.com/radare/radare2/blob/16810089eec094c29c5073ecff43f85ebd4db809/libr/core/agraph.c#L416
https://github.com/radare/radare2/blob/16810089eec094c29c5073ecff43f85ebd4db809/libr/core/agraph.c#L422
https://github.com/radare/radare2/blob/16810089eec094c29c5073ecff43f85ebd4db809/libr/core/cmd_print.c#L887

**Comment by radare** [comment]
lol. can you just send a PR?

**Comment by radare** [comment]
nvm i just fixed it myself, enotime to wait

**Comment by pelijah** [comment]
I just don't know what this code is supposed to do.
