### ISSUE TITLE
[ppc] TODOs

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#1509]
see below
- capstone disassembles relative jumps wrongly (delta jumps need absolute addressing) 
- gnu and capstone analysis plugins are wrong, `li` is identified as `swi`. 
- no syscalls 
- no esil 
- ap unsupported asm.bits ((Steps: get ppc from http://seclists.org/oss-sec/2014/q4/291
  run af,pdf/iz works fine!,run ap))

maybe a good RSoc Task ? :)

**Comment by wargio** [comment]
Can you share the bin and tell me which at which address there's a faulty disassembled instruction?

**Comment by Maijin** [comment]
Let's close this for now and reopen a META - PPC at some points.
