### ISSUE TITLE
afc vs afC

### ISSUE THREAD

**Issue by radare** [radare/radare2#1514]
I think that we should swap them because calling conventions are more commonly used than cycle analysis /cc @condret

**Comment by radare** [comment]
ping @condret

**Comment by condret** [comment]
in fact i don't use afc, because i don't need it. i only use aC for interrupt-prediction. do it if you think it makes r2 more comfortable

**Comment by radare** [comment]
aC will be renamed to `ac` after ac gets renamed to aac.

alvaro is working on that. will send a pr today

**Comment by radare** [comment]
As long as `ac` is back for cyclomatic, (no longer aC) it makes sense to keep having `afc`.
