### ISSUE TITLE
r2 shell ^W on substrings?

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#1544]
morrn,

I often delete parts of the shellinput with ^W. In r2 shell it seem ^W == ^U, which can be annoying.
It would be nice, if ^W under cursor only deletes the left side until next space, instead of whole
argument. 

http://asciinema.org/a/13138

Greetings
--zlul

**Comment by radare** [comment]
Is this still happening?

**Comment by zonkzonk** [comment]
this does not happen on my host machine, will test in vm later.

**Comment by radare** [comment]
premature closing with optimism(R)

**Comment by zonkzonk** [comment]
behaviour still in vm. just do 3 args in the command line then go in the middle and hit ^W 
Then, right arg is gone.
