### ISSUE TITLE
af*/afj should be deprecated and use to afi*/afij

### ISSUE THREAD

**Issue by radare** [radare/radare2#1545]
What should `af*` and `afj` do?
Should we kill them?

**Comment by radare** [comment]
discuss this change plz

**Comment by condret** [comment]
why do you want to kill af* ?

**Comment by radare** [comment]
because it conflicts with `afl*` . the `af*` should do like `afl*`, but
only for 1 function.

**Comment by XVilka** [comment]
Good idea, it was frustrating sometimes to describe the differences between afl* and af*

**Comment by jvoisin** [comment]
I agree.
