### ISSUE TITLE
asm.decode must be deprecated

### ISSUE THREAD

**Issue by radare** [radare/radare2#1547]
asm.decode was some kind of pseudo decompilation based on the information in RAnalOp.var. those vars has been removed because it caused too much overhead in the analysis. Also, the benefit is few, so the current approach would be using ESIL, or just use that information to make proper decompilation.

Imho i would remove asm.decode, but maybe someone else wants to keep it

**Comment by Maijin** [comment]
What is statut on that ? asm.decode doesn't work anymore so the eval variable should be removed no ?

**Comment by radare** [comment]
asm.decode is working only if asm.filter is disabled, this is a regression because asm.decode must prevail.

i have fixed this in git.

imho asm.decode is useful to debug RAnalOp values, because it constructs a textual representation of a specific instruction from this data, but if you look at the current output you’ll see that this is clearly incomplete and buggy. Maybe we should go for only supporting esil, or make a smarter decoded representation.

**Comment by radare** [comment]
Ithink we shouldnt deprecate this at all. just fix to avoid those nulls, it is useful to find bugs in the analysis and we can slowly improve that struct.

**Comment by radare** [comment]
Closing this issue, so now that there are no (null)'s we have room for improvement in this area to enhace RAnalOp, instead of just killing it
