### ISSUE TITLE
Graphs-related issues

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1566]
The visual graph mode is awesome, but it would be even better with:
- [ ] Ability to have a cursor in this mode
  - [ ] Ability to follow calls
  - [ ] Ability to _escape_ calls
- [ ] Show only the current block, and the _true_ and _false_ one.
- [x] Colours :3
- [x] Add an _overview_ mode, _à la_ IDA, that only show branches and blocks, with no listing in them.
- [x] UTF-8 support

**Comment by trufae** [comment]
there are dupped issues with other issues here. we should merge all the graph related tasks in a single one

**Comment by rlaemmert** [comment]
How about adding n/N for jump to next and previous highlighted item?

**Comment by radare** [comment]
lgtm ! @ret2libc ?

**Comment by ret2libc** [comment]
@rlaemmert do you mean like in vim when you highlight something and then you press n/N? If so, I think that's something missing to the highlight engine in general, not specific to the graph, because the "goto searched term" feature is not implemented even in normal visual mode I think. Right, @radare ?

But I would definitely love to have such a feature :)

**Comment by rlaemmert** [comment]
Yea thats exactly what i mean with that. This feature would be totally awesome.

**Comment by radare** [comment]
you mean highlighted stuff with /? there's n/N in visual mode to go next/prev flag/function/...

**Comment by rlaemmert** [comment]
hm that doesnt seem to work as expected

I use /mov to highlight all mov instructions, after that if i press n or N
and then the screen seem to jump weird arround. Maybe a bug?

**Comment by rlaemmert** [comment]
https://asciinema.org/a/dod6ugqn0d99frhy2cxioumj2

**Comment by trufae** [comment]
i didnt said that n/N does anything with the highlight at all

**Comment by rlaemmert** [comment]
oh my fault, didnt read carefully enough.
you mean n/N is already used for something different in visual mode
