### ISSUE TITLE
Fix remaining warnings and use -Werror in radare2

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1570]
It seems that we're getting toward having no more warnings. It would be great to put the infamous `-Werror` flag into our buildscript before the release.

Currently, most of the remaining warnings are in GNU code.

**Comment by jvoisin** [comment]
I think that we can close this issue, since:

1. `-Werror` can break the build on some exotic platform.
2. Jerkins/Travis will yell if someone adds a warning.
3. I'll use `git blame` to yell if someone adds a warning.

**Comment by XVilka** [comment]
Still plenty of them http://ci.rada.re/job/radare2-clang/1009/warningsResult/

**Comment by jvoisin** [comment]
Fortunately, no one compile with `-Wextra -pedantic -nazi` :watch:
