### ISSUE TITLE
sys/install.sh fails if build path contains spaces

### ISSUE THREAD

**Issue by radare** [radare/radare2#159]

**Comment by mohe2015** [comment]
```bash
<path with spaces>/radare2$ ./sys/install.sh 
WARNING: Updating from remote repository
Already up to date.

export USE_R2_CAPSTONE=

./sys/build.sh: 95: ./sys/build.sh: ./configure: not found
```
I think it doesn't work any more.

**Comment by radare** [comment]
Can u fix it?

**Comment by radare** [comment]
cricricri. will try to fix it today or tomorrow when i have some time

**Comment by Maijin** [comment]
@radare 
![image](https://user-images.githubusercontent.com/1408600/43287069-2d1a85c0-9124-11e8-9fd8-d1c4b747ea34.png)

**Comment by radare** [comment]
Someone using builddir with spaces doesnt deserves to use r2

**Comment by Maijin** [comment]
So closing or what? You opened this ^_^

**Comment by radare** [comment]
Use meson. Fixing the makefiles to make this work is a pain. Will eventually be fixed but its a lot of work. And meson may work
