### ISSUE TITLE
pf: impossible to get an element (see examples) and access a specific element in array

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#1636]
### Impossible to get an element (see examples)

r2 -nn pefile
`pf.pe_nt_image_headers32.signature` should only display the field `signature` but display the whole `pf.pe_nt_image_headers32`

Same `pf.pe_nt_image_headers32.(pe_image_optional_header32)optionalHeader.(pe_image_data_directory)dataDirectory`
or better
`pf.pe_nt_image_headers32.optionalHeader.dataDirectory`

Should display the dataDirectory but display an error:
`Unknown field '(pe_image_optional_header32)optionalHeader.(pe_image_data_directory)dataDirectory`

### Access a specific element in array

* `(pe_image_optional_header32)optionalHeader.(pe_image_data_directory)dataDirectory[0].virtualAddress` Should display the virtualAddress of the first element in the` dataDirectory`

**Comment by XVilka** [comment]
@Maijin this works for me

**Comment by Maijin** [comment]
Yup

**Comment by Maijin** [comment]
But not with pfj

**Comment by Maijin** [comment]
Also when I do ...dataDirectory[0].virtualAddress I would love to get the value not an array



     [0x00000000]> pf.pe_nt_image_headers32.optionalHeader.dataDirectory[2].virtualAddress
                                optionalHeader : 
              struct<pe_image_optional_header32>
                                      dataDirectory : 
    [
                    struct<pe_image_data_directory>
                virtualAddress : 0x00000088 = 0x30c8cce4
    ]

To be able to do something like px pf.pe_nt_image_headers32.optionalHeader.dataDirectory[2].size @ pf.pe_nt_image_headers32.optionalHeader.dataDirectory[2].virtualAddress

**Comment by Hyask** [comment]
So you mean that when you ask for a specific field, pf prints only the value, not the whole line with the name, the offset, etc...

**Comment by Maijin** [comment]
don't know if `pf` itself is the best but definitely needs something like this to be able for example to dump a dataDirectory :+1:

**Comment by Maijin** [comment]
Any update on this ?

**Comment by Hyask** [comment]
I just have my exams this week and the next one, so I won't have time, but when July will come, I'll think about fixing some pf issues! :)

**Comment by Hyask** [comment]
Does that work since https://github.com/radare/radare2/pull/2989 ?

**Comment by Maijin** [comment]
* `pf.pe_nt_image_headers32.optionalHeader.dataDirectory[2].virtualAddress` Still display Array not value
* `px pf.pe_nt_image_headers32.optionalHeader.dataDirectory[2].size @ pf.pe_nt_image_headers32.optionalHeader.dataDirectory[2].virtualAddress` Nope
* pf.pe_dos_header.e_res2[0] display : `e_res : 0x0000001c = [ 0x0000 ]` which is wrong

**Comment by Maijin** [comment]
Remaining issues are been addressed in another issues

**Comment by radare** [comment]
Awesome @hyask! Nice fixes
