### ISSUE TITLE
Merge ranal2 into rasm2 -A

### ISSUE THREAD

**Issue by radare** [radare/radare2#1658]
Discuss.

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/1659

this is already in `aoj`

**Comment by Maijin** [comment]
Well status on that ? @radare What about killing it [radare2-extras] now we have r2pipe for scripting with the r2 binary itself imho is sufficient. As already said, a better way to build only the necessary stuff within r2 will help.

**Comment by radare** [comment]
didnt worked on this at all yet. imho ranal2 should be removed, because the libr_asm will be merged into libr_anal, so it makes sense to kill ranal2, which is not used at all right now by anybody afaik

**Comment by Maijin** [comment]
fair enough
