### ISSUE TITLE
Add JSON output to rasm2

### ISSUE THREAD

**Issue by radare** [radare/radare2#1659]

**Comment by radare** [comment]
ranal2 is not installed so delayed to 1.0 for discussion if needed or not, we can do `aoj` in r2

**Comment by radare** [comment]
Ranal2 has been killed, and now the functionality is implemented in  `rasm2 -A`

**Comment by radare** [comment]
Example: `rasm2 -jA 90`

**Comment by Maijin** [comment]
For 0.10.2 !
