### ISSUE TITLE
add analysis to detect 16 vs 32 bit ARM within single binary

### ISSUE THREAD

**Issue by nopculture** [radare/radare2#166]
- recursive descent/following branches? 
- basic heuristic?

skier_ sez git mv anal_arm.c fisting.c                                    [16:56]

**Comment by Maijin** [comment]
@alvarofe

**Comment by alvarofe** [comment]
We can close this since this is 3 years old and i think r2 can detect this pretty well and when needed the code is tweaked to improve it

**Comment by radare** [comment]
🎉🎉🎉
