### ISSUE TITLE
I/O errors when connecting to ARM gdbserver

### ISSUE THREAD

**Issue by msftsecurityteam** [radare/radare2#1700]
Hi, I am running gdbserver built with gdb 7.5, and when trying to connect to a remote gdbserver on an ARM machine I get the following:

ptrace: Input/output error.
input_interrupt, count = 1 c = 36 ('$')
ptrace: Input/output error.
input_interrupt, count = 1 c = 36 ('$')
ptrace: Input/output error.
input_interrupt, count = 1 c = 36 ('$')
ptrace: Input/output error.
input_interrupt, count = 1 c = 36 ('$')
input_interrupt, count = 1 c = 43 ('+')
input_interrupt, count = 1 c = 36 ('$')
input_interrupt, count = 1 c = 103 ('g')
input_interrupt, count = 1 c = 35 ('#')
input_interrupt, count = 1 c = 54 ('6')
input_interrupt, count = 1 c = 55 ('7')
input_interrupt, count = 1 c = 36 ('$')
input_interrupt, count = 1 c = 103 ('g')
input_interrupt, count = 1 c = 35 ('#')
input_interrupt, count = 1 c = 54 ('6')
input_interrupt, count = 1 c = 55 ('7')
input_interrupt, count = 1 c = 36 ('$')
input_interrupt, count = 1 c = 118 ('v')
input_interrupt, count = 1 c = 67 ('C')
and this repeats on the gdbserver side.

Radare2 side shows:

[0x4041fd6c]> dcs
Running child until next syscall
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers

**Comment by XVilka** [comment]
Getting similar on qemu-arm:
```
r_reg_get_value: Bit size 96 not supported
r_reg_get_value: Bit size 96 not supported
r_reg_get_value: Bit size 96 not supported
r_reg_get_value: Bit size 96 not supported
r_reg_get_value: Bit size 96 not supported

r_reg_get_value: 32bit oob read 172
r_reg_get_value: 32bit oob read 172
[0x40014000]> q
Do you want to quit? (Y/n)
Do you want to kill the process? (Y/n)
Backend does not implements kill()
┌─[ xvilka@xxlaptop ] [20:04:56 ] ~/radare/hacklu/hacklu-demos/demo4_arm_boot 
└>./connect_r2.sh 
r_debug_select: 6 6
XWJSTEP TOFALSE
pid = 21467472 tid = 1
r_debug_select: 21467472 1
r_reg_get_value: 32bit oob read 172
r_reg_get_value: 32bit oob read 172
r_reg_get_value: 32bit oob read 172
r_reg_get_value: 32bit oob read 172
[0x40014000]> 
```

**Comment by crowell** [comment]
i see this on arm host, arm guest

![poop](http://i.imgur.com/9nM6cnD.png)

**Comment by crowell** [comment]
amd64 debugger, arm debuggee

```
minishwoods ~ » radare2 -a arm -b 32 -d -D gdb -e io.va=true gdb://10.0.0.23:5555
r_debug_select: 6 6
XWJSTEP TOFALSE
pid = 15535616 tid = 1
r_debug_select: 15535616 1
r_debug_gdb_reg_read: small buffer 176 vs 200
r_debug_gdb_reg_read: small buffer 176 vs 200
 -- If you want to open the file in read-write mode, invoke r2 with '-w'
r_debug_gdb_reg_read: small buffer 176 vs 200
[0xb6fcfd60]> dc
r_debug_gdb_reg_read: small buffer 176 vs 200
r_debug_gdb_reg_read: small buffer 176 vs 200
r_debug_gdb_reg_read: small buffer 176 vs 200
r_debug_gdb_reg_read: small buffer 176 vs 200
r_debug_gdb_reg_read: small buffer 176 vs 200
r_debug_gdb_reg_read: small buffer 176 vs 200
[0xb6fcfd60]> 
```

**Comment by radare** [comment]
We already know that gdb backend is not working in all platforms, anyone is going to look at it, should I? This must be ready for the release

**Comment by radare** [comment]
Anyone wants to take care of this issue?

The complains about the reg profile is because the total size of the regs differs from the one taken from the backend. See drp for more info.

**Comment by XVilka** [comment]
```
0x160000000]> drp
=pc     pc
=sp     sp
=a0     r0
=a1     r1
=a2     r2
=a3     r3
gpr     x0      .64     0       0
gpr     x1      .64     8       0
gpr     x2      .64     16      0
gpr     x3      .64     24      0
gpr     x4      .64     32      0
gpr     x5      .64     40      0
gpr     x6      .64     48      0
gpr     x7      .64     56      0
gpr     x8      .64     64      0
gpr     x9      .64     72      0
gpr     x10     .64     80      0
gpr     x11     .64     88      0
gpr     x12     .64     96      0
gpr     x13     .64     104     0
gpr     x14     .64     112     0
gpr     x15     .64     120     0
gpr     x16     .64     128     0
gpr     x17     .64     136     0
gpr     x18     .64     144     0
gpr     x19     .64     152     0
gpr     x20     .64     160     0
gpr     x21     .64     168     0
gpr     x22     .64     176     0
gpr     x23     .64     184     0
gpr     x24     .64     192     0
gpr     x25     .64     200     0
gpr     x26     .64     208     0
gpr     x27     .64     216     0
gpr     x28     .64     224     0
gpr     x29     .64     232     0
gpr     x30     .64     240     0
gpr     sp      .64     248     0
gpr     pc      .64     256     0
gpr     cpsr    .32     264     0

r_debug_gdb_reg_read: small buffer 268 vs 328
[0x160000000]> 
```
From real Android device

**Comment by radare** [comment]
yes the arm debugger no longer works for any platform right now, neither ios, android, native linux or gdb remote. Looks like all this stuff got broken after the w32 rewrite, im aware of this, and im looking for spare time to fix it.

**Comment by radare** [comment]
it is working now?

**Comment by 1n598** [comment]
Not working for me.

radare2 1.1.0-git 13146 @ darwin-x86-64 git.1.0.2-202-gdb0f4da
commit: db0f4da4ff07a57709ea3648d7880ade9e30e56c build: 2016-12-05

**Comment by radare** [comment]
Cant reproduce  :? tried with arm32 and arm64 on qemu and real hardware

$ r2 -a arm -b 32 -d gdb://host:port

the same goes for arm64 if -b 64 is used

**Comment by XVilka** [comment]
This is an old bug, situation can be different nowadays. Close it if you
can't reproduce.
