### ISSUE TITLE
parsing cmd with semicolon in quotes treated wrong

### ISSUE THREAD

**Issue by crowell** [radare/radare2#1745]
Currently doing something like 

```
/R/ "pop;pop;pop" 
```

will run rop search for `"pop`

and then will run `pop;pop"` 

the quoting for commands with semicolons in it should just be able to be on the argument, not on the entire command.

**Comment by radare** [comment]
You have to quote the whole command like this:
```
"/R/ pop;pop;pop"
```

**Comment by radare** [comment]
This requires rewriting the parser, which can bring back some regressions, so i'm moving it for 1.0

**Comment by Maijin** [comment]
@crowell Is the "/R/ pop;pop;pop" ok ? Because there are already tests for "/R/..." maybe that issue can be closed
