### ISSUE TITLE
Show file size in rabin2 -I ?

### ISSUE THREAD

**Issue by radare** [radare/radare2#1754]

**Comment by anastmag** [comment]
Is it needed to print file size with "-l" argument ?

**Comment by radare** [comment]
Not needed, but maybe it will be interesting to have it in there, this issue is just to discuss about that option and as an easy issue for newcomers, this should be just one line patch with a printf.

**Comment by radare** [comment]
btw, -I is uppercase `i` . aka info

**Comment by anastmag** [comment]
Oh.. i misunderstood then... I was wondering why filesize is necessary with linked libraries :). Let me give it a try as a newcomer if you don't mind...

**Comment by radare** [comment]
Yeah im aware of the typographic confusion of -l and -I :( maybe we
shouldnt use uppercase `i` .. and find a different flag for retrieving
information.

**Comment by radare** [comment]
So?
