### ISSUE TITLE
Enhace/Fix issues in the GDB backend (ARM on RPI)

### ISSUE THREAD

**Issue by radare** [radare/radare2#1773]
Those are some of the issues I have found debugging a remote gdbserver on RPI with r2:

```
[0xb6fd8e80]> pd 20
r_reg_get_value: Bit size 96 not supported
r_debug_gdb_reg_read: small buffer 176 vs 200

[0xb6fd8e80]> e asm.bits=64
r_reg_get_value: null or oob arena for current regset
r_reg_get_value: null or oob arena for current regset
```

Also, the IO is _VERY_SLOW_ (disassembling 2 instructions takes 7 seconds:

```
[0xb6fd8e80]> ?t pd 2
7.647732

[0xb6fd8e80]> ?t pd 10
11.352022
```

This slowdown is probably because of the lack of memoization or caching. The speed for plain reads with p8 is quite better:

```
[0xb6fd8e80]> ?t p8 1024
1.153852
r_debug_gdb_reg_read: small buffer 72 vs 200
[0xb6fd8e80]> ?t p8 32
0.000016
r_debug_gdb_reg_read: small buffer 72 vs 200
[0xb6fd8e80]> ?t p8 4096
2.907238
r_debug_gdb_reg_read: small buffer 72 vs 200
[0xb6fd8e80]>
```

Setting values to registers doesn't works:

```
[0xb6fd8e80]> dr r2=33
Error registername <r13> not found in profile
0x7fe7aad00972 ->0x00000021
[0xb6fd8e80]> dr?r2
r_debug_gdb_reg_read: small buffer 72 vs 200
0x00000021
```

buf if you show ALL the regs:

```
[0xb6fd8e80]> dr=
r_debug_gdb_reg_read: small buffer 72 vs 200
  lr 0x00000000      pc 0x00000000      r0 0x00000000      r1 0x00000000
  r2 0x00000000      r3 0x00000000      r4 0x00000000      r5 0x00000000
  r6 0x00000000      r7 0x00000000      r8 0x00000000      r9 0x00000000
 r10 0x00000000     r11 0x00000000     r12 0x00000000     r13 0x00000000
 r14 0x00000000     r15 0x00000000     r16 0x00000000     r17 0x00000000
r_debug_gdb_reg_read: small buffer 72 vs 200
[0xb6fd8e80]>
```

Reading and writing memory seems to work fine, (reading speed must be improved)

**Comment by pleonex** [comment]
Hi, I am trying to migrate from *IDA Pro* to *radare2* for Nintendo DS debugging (ARMv5/ARM9 processor). I am using [DeSmuME](http://sourceforge.net/projects/desmume/) emulator that supports GDB remote debugging and after increasing its buffer size I made it to work but found these issues.

Looking into the [emulator sources](http://sourceforge.net/p/desmume/code/HEAD/tree/trunk/desmume/src/gdbstub/gdbstub.cpp#l934) I figure out why it's giving `r_reg_get_value: Bit size 96 not supported` warning. In source [*value.c*](https://github.com/radare/radare2/blob/acd2ab9cb5925fef8405a3f6de2a85a05089811c/libr/reg/value.c#L111) it converts the bytes into a register value, it seems that in *arm* platforms, there are [8 registers]() for *float* numbers with 96 bits length.

I will continue looking into other warnings and performance issues (each stepIn in visual mode takes 13 seconds).

**Comment by radare** [comment]
debugging is slow in some platforms (windows, gdb remote, ..) because those targets takes so much time to read memory and registers and list maps.

this is a known issue that must be addressed before next release. because the frontend is performing too much unnecessary calls to those resources.. so its fine for local linux and osx, but the rest are really slow. This can be easily catched by using callgrind and then visualizing the results with kcachegrind, or by placing some printfs (or breakpoints) in the io and debug plugins.

its good to know that stepping works :P

**Comment by radare** [comment]
@pleonex feel free to join the irc for further discussions

**Comment by XVilka** [comment]
@radare @SrimantaBarua probably not reproducable anymore?

**Comment by SrimantaBarua** [comment]
qemu-system-arm works, as per my tests. I don't have an rpi to test on :/

The speed has probably been improved by no-ack mode, reg caching, and increasing packet size. It will increase more by mem caching, which is slightly more complicated.

So I think this can be closed. @radare , comments?

**Comment by radare** [comment]
i would like to test it before closing. thanks!

**Comment by radare** [comment]
Confirmed with gdbserver running on Termux on ARM64. Good work!
