### ISSUE TITLE
new webui prints out tons of newlines when switching between text and graph

### ISSUE THREAD

**Issue by crowell** [radare/radare2#1780]
cc @pwntester

go to webui, hit space, be amazed.

**Comment by radare** [comment]
Fixed

**Comment by obilodeau** [comment]
> go to webui, hit space, be amazed.

I know it's IDA's default keybinding to switch between graph and asm but it still took me a while to find.. The lack of {window,right-click} menus makes the keybindings harder to find.

Nice work on the new webui by the way!

**Comment by radare** [comment]
Iirc its also accessible via context menu
