### ISSUE TITLE
Add pseudo for arch hitachi sh

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#1793]
Add asm.pseudo for arhitecture hitachi sh

**Comment by jvoisin** [comment]
Shouldn't be hard to implement `asm.pseudo`:
- [here]( http://info.sonicretro.org/images/8/84/SH-1_SH-2_CPU_Core_Architecture.pdf ) is the specification.
- Check 8ff6a92f65331cf8ad74cd0f44a60c258b137a06 to see how to implement a new `asm.pseudo`.
- Looking at the ARM `asm.pseudo` implementation may be useful.

**Comment by Maijin** [comment]
@dukebarman can you provide a legitimate and shareable hitachi sh binary?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/7966
