### ISSUE TITLE
[TRACKER] PIE support

### ISSUE THREAD

**Issue by crowell** [radare/radare2#1813]
- [ ] main detection ( issue #1799 )
- [x] hitting breakpoints ( issue #1800 )

any others?

**Comment by crowell** [comment]
reopenning because main detection is broken http://ctf.haxpo.nl/files/candypop

**Comment by radare** [comment]
its still broken?

**Comment by crowell** [comment]
still broken

**Comment by crowell** [comment]
it is odd though, because the value of `rdi` is properly detected when `__libc_start_main` is called.

**Comment by radare** [comment]
should be fine now

**Comment by crowell** [comment]
:+1:
