### ISSUE TITLE
ihex:// not working on this sample

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#1843]
ihex:// not working on this sample http://rghost.net/59708019

**Comment by fenugrec** [comment]
Original problem file available @ ftp://downloads.netgear.com/pub/netgear/files/GS108E_V1.00.09.zip
Issue fixed in https://github.com/radare/radare2/commit/752435bf1b7b8143799a897f532f254a67718087

**Comment by Maijin** [comment]
It works ! 
Maybe we should create a test :+1:
