### ISSUE TITLE
ROP Search bugs

### ISSUE THREAD

**Issue by radare** [radare/radare2#1858]
This bug aims to collect all the missing points needed to make ROP usable again.

* /R uses strcmp, while it shuold be strstr
* /R rax,ret doesnt works
* There are tons of dupped results

The comma separator takes more sense as long as its strstr and not exact match. We can handle ',' as token separator asuming that there will be no assembly instruction with "," in it. It will always be ", "

I'll do more tests later and update the issue

**Comment by crowell** [comment]
closing, this is fixed.
