### ISSUE TITLE
Static objects still try to link against shared objects

### ISSUE THREAD

**Issue by zneak** [radare/radare2#1860]
I'm trying to build radare2 as a set of static libraries on Mac OS X, so I built with `--with-nonpic` to get a bunch of `.a`s. However, when I link an executable against those and try to run it, the dynamic linker complains that it can't find the `.dyld` files that I specifically don't want to link against.

I ran `nm` on the executable and found that all of these symbols are marked undefined, even though I linked against all the `.a` files that I could find in the radare2 tree:

* Pe32_r_bin_pe_free
* Pe32_r_bin_pe_get_arch
* Pe32_r_bin_pe_get_bits
* Pe32_r_bin_pe_get_class
* Pe32_r_bin_pe_get_entrypoint
* Pe32_r_bin_pe_get_exports
* Pe32_r_bin_pe_get_image_base
* Pe32_r_bin_pe_get_imports
* Pe32_r_bin_pe_get_libs
* Pe32_r_bin_pe_get_machine
* Pe32_r_bin_pe_get_main_vaddr
* Pe32_r_bin_pe_get_os
* Pe32_r_bin_pe_get_sections
* Pe32_r_bin_pe_get_subsystem
* Pe32_r_bin_pe_is_big_endian
* Pe32_r_bin_pe_is_dll
* Pe32_r_bin_pe_is_stripped_debug
* Pe32_r_bin_pe_is_stripped_line_nums
* Pe32_r_bin_pe_is_stripped_local_syms
* Pe32_r_bin_pe_is_stripped_relocs
* Pe32_r_bin_pe_new_buf
* gdbr_connect
* gdbr_init
* gdbr_read_memory
* gdbr_write_memory
* proc_pidpath
* r_bin_java_build_obj_key
* r_bin_java_free
* r_bin_java_get_classes
* r_bin_java_get_entrypoint
* r_bin_java_get_entrypoints
* r_bin_java_get_imports
* r_bin_java_get_lib_names
* r_bin_java_get_sections
* r_bin_java_get_strings
* r_bin_java_get_symbols
* r_bin_java_get_version
* r_bin_java_new_buf
* sdb_bool_set
* sdb_fmt
* sdb_free
* sdb_get
* sdb_itoa
* sdb_new
* sdb_new0
* sdb_ns
* sdb_ns_set
* sdb_num_set
* sdb_set
* sdb_unset
* zip_add
* zip_close
* zip_fclose
* zip_fopen_index
* zip_fread
* zip_get_num_files
* zip_name_locate
* zip_open
* zip_replace
* zip_source_buffer
* zip_source_free
* zip_stat_index
* zip_stat_init

There could be more missing, these are just the ones that are somehow related to what I'm doing right now (I just call `r_io_open`, `r_bin_load_io` and the related `new` functions).

Is there a better way to make a self-contained executable that uses radare?

**Comment by Maijin** [comment]
ping ?

**Comment by zneak** [comment]
I gave up on the project.
