### ISSUE TITLE
Handle negative offsets in all `p` subcommands

### ISSUE THREAD

**Issue by radare** [radare/radare2#1876]
px -10 == px 10 @ $$-10

Not only in pd and pD

**Comment by davidpolverari** [comment]
Isn't this behavior already implemented?

**Comment by radare** [comment]
Probably not for all commands. Worth testing

**Comment by davidpolverari** [comment]
Ok. Because I tested with px and pd, and it worked. I will test with other 'p' commands. Thanks!

**Comment by Maijin** [comment]
When @radare say tested, it means create a test in radare2-regressions. Like this one https://github.com/radare/radare2-regressions/blob/master/t/cmd_print#L161

**Comment by Maijin** [comment]
tested on most p
