### ISSUE TITLE
Add function parameter names to function calls (from documentation)

### ISSUE THREAD

**Issue by newlog** [radare/radare2#1883]
Hi there!

This might be a huge work... But, bah... I'm gonna say it. It would be great if calls to Windows API functions would be commented with the name of their arguments.
For example, if there's a call to URLDownloadFile(), list its arguments as in http://msdn.microsoft.com/en-us/library/ie/ms775123(v=vs.85).aspx.

    HRESULT URLDownloadToFile(
      LPUNKNOWN pCaller,
      LPCTSTR szURL,
      LPCTSTR szFileName,
      _Reserved_  DWORD dwReserved,
      LPBINDSTATUSCALLBACK lpfnCB
    );

Thank you for your awesome work! Feel free to ask me anything if I don't explain enough the issue.

**Comment by Maijin** [comment]
@radare "try "r2 -caeim -e asm.emu=1 -e asm.emuwrite=1 bins/pe/standard.exe" now need"

So now it just need an example of database and then, we'll be able to map all the parameters/vars :D

**Comment by Maijin** [comment]
@newlog This is working now we need to enrich the database :+1: :+1: :+1:

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://kaorutada.co.uk/money.php?s67iy>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hey,
You won't believe what I've just read, this is so amazing, read more at  <http://kanurdizu.born-global.com/lnmseu>

Pardon my monkey thumbs, lukas-runas@gmx.de
