### ISSUE TITLE
Rename/Comment function arguments and local variables

### ISSUE THREAD

**Issue by newlog** [radare/radare2#1885]
Hello again,

It would be great if when disassembling, function arguments and local variables would be renamed (or at least commented) to identify if the function is working with a parameter or with a local variable.

For example, rename offsets from esp/ebp as parameters or local vars with a name - varC or paramB, where 0xC and 0xB are offsets from esp/ebp - (not only related to windows).  A la IDA Pro.

This would increase the usability of using the disassembler.

Thanks for your hard work!

**Comment by radare** [comment]
The recursivity in the analysis can be configured with anal.depth. You may also want to look at 'ac'. And if you want to analyze that function just use af @ 0x401040 or if you want to use a2f prefix it with a dot: .a2f@0x401040

**Comment by cvuchener** [comment]
Hi, this work with ebp but I have assembly code using offsets from esp for local variables. Is it possible to rename variable with offset from esp instead of ebp?

**Comment by Maijin** [comment]
@cvuchener https://github.com/radare/radare2/issues/3735

**Comment by cvuchener** [comment]
Thanks. I guess that means a "no, not yet".

**Comment by Maijin** [comment]
No but you can contribute and subscribe to the issue to show interest

**Comment by Maijin** [comment]
This has been done by @oddcoder ! 👍
