### ISSUE TITLE
Function resolving when searching for calls

### ISSUE THREAD

**Issue by newlog** [radare/radare2#1886]
Hi!

It would be great that when searching, for example, for calls with /c call, the destination address would be resolved as it's resolved in the disassembly view. 

For example, we would get an output like the following:
```
f hit_0 @ 0x100052f1   # 6: call dword [0x10016010]
f hit_1 @ 0x100052fe   # 6: call dword [0x10016008]
f hit_2 @ 0x1000532a   # 2: call ebx
f hit_3 @ 0x10005341   # 3: call dword [eax-0x1]
f hit_4 @ 0x10005343   # 2: call edi
```

In the disassembly view, the call to 0x10016010 would be resolved and the function name would be shown. But it's not when searching.

Edit: Here's an asciinema showing the problem and a workaround:
https://asciinema.org/a/2o4bpkbq1zfypjx62iqklo2ux

The binary used is the Lab06-02.exe from Practical Malware Analysis. It can be downloaded from https://practicalmalwareanalysis.com/labs/

Thanks for your great work!

**Comment by newlog** [comment]
This has not been fixed/enhanced yet.

However, if in visual mode you click "_" you can get a list with ""everything"", including also all the calls. This won't show things like "call ebx", but the main point of this issue is to show the function names of all the calls, and that's, basically, accomplished by pressing "_" and looking for "fcn" or similar.

**Comment by newlog** [comment]
Added asciinema showing problem and workaround, and added binary source.

**Comment by Maijin** [comment]
To recap it's just resolution enhancement in /c:
```
0x1000011a1   # 5: call 0x1000043ff
```

should be:

```
0x1000011a1   # 5: call sym.func.1000043ff
```

For example.

It's similar issue as #5698

**Comment by radare** [comment]
you mean honor asm.relsub in /c ?
