### ISSUE TITLE
Problems listing xrefs for relocated functions

### ISSUE THREAD

**Issue by newlog** [radare/radare2#1888]
Hello,

I've found that there are some problems listing cross references to relocated functions in a DLL (Lab05-01.dll from Practical Malware Analysis book, that it's in the r2 regression tests project).

There are two problems:
1) The 'x' command in Visual Mode does not work:
The normal step would be to analyze the binary with "aa", seek the function address by "s 0x100163CC", then change to Visual Mode with "V" and [Enter] and finally typing "x" would show all references to that functions. 
In this case, this doesn't work. No xrefs are listed. Maybe because relocation issues or because "aa" doesn't analyze all binary.

![disass](http://imgur.com/NO5rIjF.png)

In the image, I'm in the right address but although I click 'x' the xrefs aren't listed.

2) Instead of using the last approach I would use the /a command to search for calls to that address and I get the following:
```
[01:56:18] newlog@multiverse:radare2 (master)$ r2 -A ~/Downloads/Telegram\ Desktop/Lab05-01.dll 
 -- Default scripting languages are NodeJS and Python.
[0x1001516d]> /a call [0x100163CC]
# 6 [0x10001000-0x100994a8]
hits: 7
0x100011af hit0_0 ff15cc630110
0x100012df hit0_1 ff15cc630110
0x100014a0 hit0_2 ff15cc630110
0x100015d0 hit0_3 ff15cc630110
0x10001757 hit0_4 ff15cc630110
0x10002430 hit0_5 ff15cc630110
0x100031c5 hit0_6 ff15cc630110
[0x1001516d]> 
```

The problem is that there are 7 hits, but with IDA Pro there are 9:
![IDA Pro xrefs](http://i.imgur.com/HBYaInr.png)

**Comment by Maijin** [comment]
@radare fixed ?

**Comment by radare** [comment]
Ask @newlog

**Comment by Maijin** [comment]
Much more detection now
```
C 0x100011af call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x10001247 call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x100012df call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x100014a0 call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x10001538 call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x100015d0 call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x10001757 call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x10002430 call dword [sym.imp.WS2_32.dll_gethostbyname]
C 0x100031c5 call dword [sym.imp.WS2_32.dll_gethostbyname]
d 0x100031c5 call dword [sym.imp.WS2_32.dll_gethostbyname]
d 0x10002430 call dword [sym.imp.WS2_32.dll_gethostbyname]
d 0x1830 call dword [sym.imp.WS2_32.dll_gethostbyname]
d 0xb57 call dword [sym.imp.WS2_32.dll_gethostbyname]
```

**Comment by Maijin** [comment]
Please reopen if necessary because this seems fixed.
