### ISSUE TITLE
Commenting strings and function references in Visual Mode

### ISSUE THREAD

**Issue by newlog** [radare/radare2#1890]
Hello,

Right now, in Visual Mode, r2 lists the strings referenced as addresses in the disassembly as comments. 

There are many times in which a string is not directly referenced but there is a double derefence, for example: 
```
[addr1] -- push <addr2>
(...)
[addr2] -- <addr3>
(...)
[addr3] -- "here we have the string"
```

In those cases, the "here we have the string" is not listed as a comment in the Visual Mode.
You can see an example of this happening in the Lab05-01.dll from the Practical Malware Analysis book (you can find it in the r2-regressions project).
![string](http://i.imgur.com/LUGomp3.png)
![string](http://i.imgur.com/8jwUvpk.png)

It would be great, but maybe it should be listed in another issue, but when there's a `call <reg>`, a comment with the resolved function could be shown. I know that this might be much more complicated, because some kind of emulation might be needed. I'm just pointing it...

**Comment by newlog** [comment]
All the string issues have been fixed! Sweeeet! Thanks, guys!

**Comment by radare** [comment]
<3
