### ISSUE TITLE
Handle sym.imp for PE (constant relocations)

### ISSUE THREAD

**Issue by radare** [radare/radare2#1896]
PE bins have also a plt-like jump table which makes use of the relocs, this table is constant and can be precalculated without doing analysis, also, all call refs point to there.. so to get proper xrefs we need that.

Maybe we will want to rename that sym.imp prefix to be plt. or somthing like that. but this way we get in sync with ELF

**Comment by XVilka** [comment]
any update on this?

**Comment by Maijin** [comment]
?

**Comment by Maijin** [comment]
ADded a test here https://github.com/radare/radare2-regressions/commit/8ab8a95841713e9646f450cea9fbb272e6874caa

**Comment by Maijin** [comment]
Test added for the dword addition that should end this issue (BROKEN=1 currently)  https://github.com/radare/radare2-regressions/commit/8ab8a95841713e9646f450cea9fbb272e6874caa

**Comment by Maijin** [comment]
Fixed
