### ISSUE TITLE
main not detected in ARM

### ISSUE THREAD

**Issue by crowell** [radare/radare2#1919]
main detection on arm is pretty bokken
even if there is a sym.main
https://asciinema.org/a/15069

**Comment by radare** [comment]
the function address and size have nothing to do with main detection. those are totally unrelated problems. can you confirm the real problem? can you share that bin?

**Comment by crowell** [comment]
http://raxcity.com/r2.b64 

for example

many more have the same issue.

**Comment by radare** [comment]
main is not sym.main, 'main' autodetection doesnt depends on symbol information. you have symn.main if you want to go to the program's main. 'main' is detected with signature checks in the entrypoint. will do that later. its 3 line patch or something
