### ISSUE TITLE
Writes are not cached nor written when io.cache=true

### ISSUE THREAD

**Issue by GuzTech** [radare/radare2#1923]
I've been trying to follow along the shellscript example on the radare website. I took the C code, compiled it, and opened it with Radare2. At the step where you undo the self-modifying code (wos 0x35@0xADDRESS:0x27) the changes do not seem to be written to cache when io.cache=true.

I've tried this with io.cache=false and I get an error:

`r_io_write: cannot write on fd 6`

which makes sense. If I set it to true and use the wos command, the code does not change. Even using wic to commit changes and wci does not seem to help.

However, if I open the file with -w on the command line, then everything works as expected. This modifies the file of course.

This was tested with be275471d73157c305c283f031c76e24815f85bd

Asciinema: https://asciinema.org/a/15089

**Comment by radare** [comment]
cc @condret

**Comment by ret2libc** [comment]
Shall we close this since more than 3 years have passed? In case the bug is still there somebody will reopen the issue.
