### ISSUE TITLE
Empty command must seek last blocksize if size parameter is used

### ISSUE THREAD

**Issue by radare** [radare/radare2#1926]
For example:

```
pD 10
<enter>
<enter>
<enter>
```

or:

```
px 32
<enter>
<enter>
<enter>
```

**Comment by radare** [comment]
By default empty commands will seek to the next block. but this can be confusing if we are passing numeric rguments to specify the size of the print command.

**Comment by radare** [comment]
@crowell do you wanna fix this?

**Comment by radare** [comment]
or maybe @alvarofe ?

**Comment by alvarofe** [comment]
I'll take it ;)

**Comment by jvoisin** [comment]
@alvarofe ping?

**Comment by alvarofe** [comment]
I've been fixing issues related with fuzzing and so,  I hope this week fix this issue ;)
