### ISSUE TITLE
Extract RBin class information from Symbol demangling

### ISSUE THREAD

**Issue by radare** [radare/radare2#1930]

**Comment by radare** [comment]
wat

**Comment by radare** [comment]
@inisider

**Comment by radare** [comment]
This was a task for @inisider and i already implemented it (partially), and it requires tests cases and proper verification for all file formats

**Comment by inisider** [comment]
I will add tests then, but when I tried it last time it did not work :(

**Comment by radare** [comment]
ping

**Comment by inisider** [comment]
I will look at it on next week! Maybe earlier.

**Comment by radare** [comment]
This was done in 7b94a79dcdfa0242388827e847833a46f0a9e877
