### ISSUE TITLE
Misleading cg command description

### ISSUE THREAD

**Issue by newlog** [radare/radare2#1936]
The cg command has the following description:
```
Byte-per-byte code graph diff
```

What this command does is to compare functions from one binary and another and correlate them (match-ratio, unmatched, matched, new) without showing the actual differences among them. It's impossible to infer what this command does only by its description. 

The same command in radiff2 has this description:
```
graphdiff code (columns: off-A, match-ratio, off-B)
```

Which is a bit more accurate given that gives the description of the output.

Changing its description might improve usability :)

A sample of the output follows:
```
fcn.00401df2  0x401df2 |   MATCH  (1.000000) | 0x401f9d  fcn.00401f9d
fcn.00401210  0x401210 |     NEW  (0.518797)
fcn.00401271  0x401271 |   MATCH  (0.142857) | 0x4012b5  fcn.004012b5
fcn.004013ca  0x4013ca | UNMATCH  (0.063830) | 0x401460  fcn.00401460

```

**Comment by radare** [comment]
feel free to send a pullreq with a better description :)

thanks

**Comment by newlog** [comment]
great!
any suggestion, please? Don't know if there's any kind of "rules" with these small descriptions!

It would be a good exercise to pr without breaking things :D

**Comment by radare** [comment]
Your already proposed string looks good

**Comment by radare** [comment]
this was already fixed in git a while ago
