### ISSUE TITLE
Disassembly highlight in code blocks in generated graphviz file

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#194]
If use `ag` command from radare2, it generates graphviz file without syntax highlight for disassembly inside code blocks.

Reported by ret2libs from #radare irc channel.

**Comment by jvoisin** [comment]
It's already implemented in web interfaces.

**Comment by radare** [comment]
The web doesnt uses dot format. But im not sure how stabdard/portable that feature is.. So maybe it will be better to stick with monochrome graphviz nodes.
