### ISSUE TITLE
webui function variable renaming bug

### ISSUE THREAD

**Issue by NickStephens** [radare/radare2#1941]
There's a bug when renaming function variables in the webui to smallish names. For example renaming a variable to 'a' causes bad html to be produced. This is caused by the the function html_for_instruction in /shlr/www/enyo/js/disasm.js

To reproduce:

download the test file 
https://github.com/ctfs/write-ups/blob/master/31c3-ctf-2014/pwn/cfy/cfy

run 'r2 -c=h' on the test file

navigate to localhost:9090/p/ in browser

go to sym.main function

rename the variable local_8 in sym.main to the letter 'a'

**Comment by pwntester** [comment]
fixed but not commited yet

**Comment by radare** [comment]
the fix has been commited some days ago. thanks
