### ISSUE TITLE
Default fortunes may be NSFW/NSFC

### ISSUE THREAD

**Issue by voltagex** [radare/radare2#1961]
We've run across a problem with radare2 where the default fortunes may violate our code of conduct at LCA2015* (e.g. displaying r2 at the front of a room in a tutorial)

Would it be possible to split the fortunes into safe/unsafe or default them to off?

*https://linux.conf.au/cor/code_of_conduct

**Comment by radare** [comment]
Sure, there have been some discussion about it, and i'm ok with it, having an option to enable offensive fortunes can be cool instead of removing them.

**Comment by radare** [comment]
Just to be clear, me, or the project doesnt support such offensive or exclusive fortunes, they are just to make fun and joy, nobody should take them seriously. But it's clear that we have 3 kind of fortunes that maybe we should split in different files:

* usage/tips
* fun/word games
* offensive

**Comment by voltagex** [comment]
Fully agree, thanks for the response!

**Comment by crowell** [comment]
@voltagex please take a look at #1966 and let me know if you disagree with any of the locations of the fortunes.

Keep in mind the new default will be `fun` and `tips`

**Comment by radare** [comment]
I'm closing this bug after reviewing your commit which splits the fortunes by categories. It looks safe for all publics now :)
