### ISSUE TITLE
Refactor the "pseudo" mechanism

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1968]
Currently, a lot of code is duplicated in `libr/parse/p/parse_*_pseudo.c` files.
It would be great to unify/simplify this, to make it easy to add new architectures.

**Comment by jvoisin** [comment]
Partly done in cfe74d9aacdec3e89269158631a6a9545b2ca926
The unification of the `replace` function seems to be a bit more tricky.

**Comment by radare** [comment]
what's missing?

**Comment by radare** [comment]
@jvoisin any chance you can finish and close this issue?

**Comment by jvoisin** [comment]
Unlikely :/

**Comment by radare** [comment]
moving to 1.2 as long as its low prio

**Comment by radare** [comment]
Closing this as long as everything must be refactored, feel free to reopen or send a pullreq refactoring more things :)

cc @Maijin @jvoisin
