### ISSUE TITLE
Please gentoo downstream

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1978]
Our gentoo downstream has [several complains]( https://bugs.gentoo.org/show_bug.cgi?id=391751 ) about radare2. It would be cool to fix them to make their life easier.

**Comment by trufae** [comment]
Should be fixed now

**Comment by XVilka** [comment]
Fixed in https://github.com/radare/radare2/commit/fb970bebb91999db15159f90dc2aa1b94b2a0853
