### ISSUE TITLE
Too much web interfaces

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1979]
Currently, there are 3 web interfaces:
- enyo
- pwntester
- tilling

I think that we can at least kill enyo, since pwntester's one is far better.
What about tilling then? In my opinion, it should be killed to.

**Comment by crowell** [comment]
I think enyo should be killed.

**Comment by radare** [comment]
try to use the /p or /t in your phone

**Comment by jvoisin** [comment]
There is an app for that.

**Comment by jvoisin** [comment]
@pwntester : Do you want to make your webui **responsive**?

**Comment by pwntester** [comment]
I think enyo should be kept for mobile and /p for desktop. Ive never used /t though. Im not a web developer and dont know how much time would it take me to make /p completly responsive and if this effort is worthy, I just dont envision myself using r2 on a phone :)

So I would say to keep enyo and /p and make as many components as possible common to both layouts to reduce mantainability. Another option is to engage a web developer through (G|R)SoC

**Comment by radare** [comment]
Now enyo is used on ios/android and /p is the default for desktops. Also, a loading panel with a webui selector is on the way. Having 3 webuis is not an issue
