### ISSUE TITLE
WebUI can't do "real time" collaboration

### ISSUE THREAD

**Issue by crowell** [radare/radare2#1981]
Currently the webui can be used for collaborative reversing. However when one user adds a comment, renames, etc. the other users will not receive the update until the page is refreshed or something on the page is modified.

Ideally the core would tell connected clients to reload or send some sort of update.

**Comment by radare** [comment]
The T command is suposed to be used to send notification messages to all clients to make them refresh a panel or so, none of the webuis use it yet
