### ISSUE TITLE
clock_gettime problem when building on Kali Linux

### ISSUE THREAD

**Issue by 1n598** [radare/radare2#1983]
I am getting a linker error when building radare2 on kali linux. I am currently trying to fix it without breaking something else

OUTPUT:

gcc -c  -fPIC  -g  -o json.o json.c
gcc -c  -fPIC  -g  -o ns.o ns.c
gcc -c  -fPIC  -g  -o lock.o lock.c
gcc -c  -fPIC  -g  -o util.o util.c
gcc -c  -fPIC  -g  -o disk.o disk.c
gcc -c  -fPIC  -g  -o query.o query.c
gcc -c  -fPIC  -g  -o array.o array.c
gcc -c  -fPIC  -g  -o fmt.o fmt.c
rm -f libsdb.a
ar q libsdb.a cdb.o buffer.o cdb_make.o ls.o ht.o sdb.o num.o base64.o json.o ns.o lock.o util.o disk.o query.o array.o fmt.o
ar: creating libsdb.a
ranlib libsdb.a
gcc -c  -fPIC  -g  -o main.o main.c
gcc -g -o sdb main.o cdb.o buffer.o cdb_make.o ls.o ht.o sdb.o num.o base64.o json.o ns.o lock.o util.o disk.o query.o array.o fmt.o
util.o: In function `sdb_now':
/opt/radare2/shlr/sdb/src/util.c:166: undefined reference to `clock_gettime'
util.o: In function `sdb_unow':
/opt/radare2/shlr/sdb/src/util.c:184: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
make[3]: *** [sdb] Error 1
make[3]: Leaving directory `/opt/radare2/shlr/sdb/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/opt/radare2/shlr/sdb'
make[1]: *** [sdb/sdb] Error 2
make[1]: Leaving directory `/opt/radare2/shlr'
make: *** [all] Error 2

**Comment by radare** [comment]
wtf, which kernel and glibc versions are shipped with kali?

**Comment by 1n598** [comment]
Kernel:3.14-kali1-amd64
glibc: ldd (Debian EGLIBC 2.13-38+deb7u3) 2.13

**Comment by radare** [comment]
Looks like in this version its distributed in a separate library (librt)

the way to fix would be to add -lrt in LDFLAGS, or just force to use the old gettimeofday(). but this is a syscall.. i dont get why such stuff should be in a separate library. Maybe other distros are affected

**Comment by 1n598** [comment]
tried to add -lrt to ldflags but i must be putting it somewhere wrong because it still doesnt work. I was thinking of disabling that whole bunch of code, but im too lazy to check the impact.

**Comment by radare** [comment]
Its just changing one define in shlr/sdb/utils.c The ldflags is only for sdb.

If its very problematic i will disable it by default.

**Comment by 1n598** [comment]
guys i think i might fixed it: 
added LDFLAGS+= -lrt to global.mk after compiler line.
add LDFLAGS+= -lrt in the config.mk in the shlr/sdb directory. It is hacky, but somehow it worked.

**Comment by radare** [comment]
I have disabled this feature because it's not yet used in r2 and it's also working, the monotonic clock only adds a clock skew protection to the expire time of keys in Sdb.
