### ISSUE TITLE
List projects with P command

### ISSUE THREAD

**Issue by radare** [radare/radare2#1984]
As long as projects are saved in ~/.config/radare2/projects (see P?)

only non sandboxed instances may be able to do this

**Comment by pwntester** [comment]
add Pj as well

**Comment by pwntester** [comment]
Im using "!ls $HOME/.config/radare2/projects" for now, but this wont probably work on windows as pointed by @crowell.

Also Po doesnt seem to work

**Comment by radare** [comment]
I have added the Plj command as requested

**Comment by radare** [comment]
Done
