### ISSUE TITLE
Implement search / in r_cons_less()

### ISSUE THREAD

**Issue by radare** [radare/radare2#1989]

**Comment by jjdredd** [comment]
ok, I've implemented it but it's a little buggy for now :)
I will push to my fork as soon as I figure it out.

**Comment by radare** [comment]
Invert searched word colors (RCons_INVERT), see how V/ works.

Also, use 'n' and 'p' keys to search for next and prev results

**Comment by jjdredd** [comment]
ok, no problem with 'n' and 'p' keys, but I didn't understand the RCons_INVERT thing.

**Comment by radare** [comment]
http://radare.tv/a/13

**Comment by jjdredd** [comment]
yeah I know about that feature, just thought that by "RCons_INVERT" you meant some macro/function
that could implement that feature

**Comment by radare** [comment]
```
R_API void r_cons_invert(int set, int color) {
        r_cons_strcat (R_CONS_INVERT (set, color));
}
....

                if (invert)
                        r_cons_invert (R_TRUE, R_TRUE);

```
