### ISSUE TITLE
[zzuf] afna FPE

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#1995]
morn,

```
Core was generated by `r2 -qc afna;afo sym.main ./a.out.bak'.
Program terminated with signal 8, Arithmetic exception.
#0  0xb751238e in r_bin_dwarf_parse_std_opcode (a=0x84bcc98, 
    obuf=0x853e584 "\360\023\231\266", len=472, hdr=0xbfd5b818, 
    regs=0xbfd5b7d8, opcode=8 '\b', f=0x0, mode=2) at dwarf.c:581
581			op_advance = adj_opcode / hdr->line_range;

(gdb) bt
#0  0xb751238e in r_bin_dwarf_parse_std_opcode (a=0x84bcc98, 
    obuf=0x853e584 "\360\023\231\266", len=472, hdr=0xbfd5b818, 
    regs=0xbfd5b7d8, opcode=8 '\b', f=0x0, mode=2) at dwarf.c:581
#1  0xb75126a5 in r_bin_dwarf_parse_opcodes (a=0x84bcc98, obuf=0x853e55c "", 
    len=472, hdr=0xbfd5b818, regs=0xbfd5b7d8, f=0x0, mode=2) at dwarf.c:645
#2  0xb751285e in r_bin_dwarf_parse_line_raw2 (a=0x84bcc98, 
    obuf=0x853e328 "<", len=512, mode=2) at dwarf.c:687
#3  0xb7514d0e in r_bin_dwarf_parse_line (a=0x84bcc98, mode=2) at dwarf.c:1512
#4  0xb7661957 in bin_dwarf (core=0x804e4c0, mode=2) at bin.c:437
#5  0xb76663b0 in r_core_bin_info (core=0x804e4c0, action=4095, mode=2, va=1, 
    filter=0x0, loadaddr=0, chksum=0x0) at bin.c:1482
#6  0xb76602ac in r_core_bin_set_env (r=0x804e4c0, binfile=0x84f5710)
    at bin.c:94
#7  0xb76666f0 in r_core_bin_set_arch_bits (r=0x804e4c0, 
    name=0x84f9ff0 "./a.out.bak", arch=0x8512d04 "x86", bits=64) at bin.c:1528
#8  0xb764ce24 in r_core_file_do_load_for_io_plugin (r=0x804e4c0, baseaddr=0, 
    loadaddr=0) at file.c:357
#9  0xb764d0f3 in r_core_bin_load (r=0x804e4c0, 
    filenameuri=0x84f3560 "./a.out.bak", baddr=0) at file.c:472
#10 0x0804bc23 in main (argc=4, argv=0xbfd5c154, envp=0xbfd5c168)
    at radare2.c:532

``` 

fuzzed_fle:
http://sprunge.us/EaOD

radare2 0.9.9-git @ linux-little-x86-32 git.0.9.8-549-g12e8ae6
commit: 12e8ae61fb35e61d831db59215098925970245e7 build: 2015-01-26

Greetings
--zlul

**Comment by zonkzonk** [comment]
valgrind r2 fu.883
==24147== Memcheck, a memory error detector
==24147== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==24147== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==24147== Command: r2 fu.883
==24147== 
Warning: index out of strtab range
Warning: index out of strtab range
==24147== Conditional jump or move depends on uninitialised value(s)
==24147==    at 0x4028C5D: strncpy (mc_replace_strmem.c:463)
==24147==    by 0x419271E: symbols (bin_elf.c:266)
==24147==    by 0x4173996: r_bin_object_set_items (bin.c:382)
==24147==    by 0x41753D9: r_bin_object_new (bin.c:872)
==24147==    by 0x4175A70: r_bin_file_new_from_bytes (bin.c:983)
==24147==    by 0x41746BC: r_bin_load_io_at_offset_as_sz (bin.c:584)
==24147==    by 0x4174785: r_bin_load_io_at_offset_as (bin.c:599)
==24147==    by 0x417412E: r_bin_load_io (bin.c:498)
==24147==    by 0x409FCE7: r_core_file_do_load_for_io_plugin (file.c:340)
==24147==    by 0x40A00F2: r_core_bin_load (file.c:472)
==24147==    by 0x804BC22: main (radare2.c:532)
==24147== 
Warning: index out of strtab range
Warning: index out of strtab range
==24147== 
==24147== Process terminating with default action of signal 8 (SIGFPE)
==24147==  Integer divide by zero at address 0x62F5CCD1
==24147==    at 0x417A387: r_bin_dwarf_parse_std_opcode (dwarf.c:581)
==24147==    by 0x417A6A4: r_bin_dwarf_parse_opcodes (dwarf.c:645)
==24147==    by 0x417A85D: r_bin_dwarf_parse_line_raw2 (dwarf.c:687)
==24147==    by 0x417CD0D: r_bin_dwarf_parse_line (dwarf.c:1512)
==24147==    by 0x40B4956: bin_dwarf (bin.c:437)
==24147==    by 0x40B93AF: r_core_bin_info (bin.c:1482)
==24147==    by 0x40B32AB: r_core_bin_set_env (bin.c:94)
==24147==    by 0x409FD17: r_core_file_do_load_for_io_plugin (file.c:345)
==24147==    by 0x40A00F2: r_core_bin_load (file.c:472)
==24147==    by 0x804BC22: main (radare2.c:532)
==24147== 
==24147== HEAP SUMMARY:
==24147==     in use at exit: 1,103,346 bytes in 2,896 blocks
==24147==   total heap usage: 4,509 allocs, 1,613 frees, 1,656,007 bytes allocated
==24147== 
==24147== LEAK SUMMARY:
==24147==    definitely lost: 13,037 bytes in 13 blocks
==24147==    indirectly lost: 13,288 bytes in 89 blocks
==24147==      possibly lost: 31,084 bytes in 60 blocks
==24147==    still reachable: 1,045,937 bytes in 2,734 blocks
==24147==         suppressed: 0 bytes in 0 blocks
==24147== Rerun with --leak-check=full to see details of leaked memory
==24147== 
==24147== For counts of detected and suppressed errors, rerun with: -v
==24147== Use --track-origins=yes to see where uninitialised values come from
==24147== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 713 from 12)
Floating point exception

**Comment by zonkzonk** [comment]
@pancake

proposed "first" patch:

```
git diff
diff --git a/libr/bin/dwarf.c b/libr/bin/dwarf.c
index af49525..5592501 100644
--- a/libr/bin/dwarf.c
+++ b/libr/bin/dwarf.c
@@ -578,7 +578,9 @@ static const ut8* r_bin_dwarf_parse_std_opcode(
                break;
        case DW_LNS_const_add_pc:
                adj_opcode = 255 - hdr->opcode_base;
+        if ((hdr->line_range)>0) { 
                op_advance = adj_opcode / hdr->line_range;
+        }
                regs->address += op_advance;
                if (f) {
                        fprintf(f, "Advance PC by constant %"PFMT64d" to 0x%"PFMT64x"\n",
```

**Comment by crowell** [comment]
@zonkzonk the promblem here is that op_advance will not be defined here.
