### ISSUE TITLE
so -1 doesnt works

### ISSUE THREAD

**Issue by radare** [radare/radare2#2005]
should seek to the previous instruction

**Comment by Tyilo** [comment]
Doesn't seem to work for me:
```
> s 0x100002ab3
> pd 2
|          0x100002ab3    488d1586b80. lea rdx, qword [rip + 0x1b886]  ; [0x10001e340:8]=0
|          0x100002aba    31ff         xor edi, edi
> so -1
> pd 3
|          0x100002aac    b80100480f   mov eax, 0xf480001
|          0x100002ab1    45c8488d15   enter -0x72b8, 0x15
|          0x100002ab6    86b8010031ff xchg byte [rax - 0xceffff], bh
```

The expected output would be:
```
> so -1
> pd 3
|          0x100002aaf    480f45c8     cmovne rcx, rax
|          0x100002ab3    488d1586b80. lea rdx, qword [rip + 0x1b886]  ; [0x10001e340:8]=0
|          0x100002aba    31ff         xor edi, edi
```

Same binary as in #2002

**Comment by radare** [comment]
it is not always possible to guess the correct size of the previous
iinstruction, because on intel there are variable instruction lengths so
there are many previous instructions.

**Comment by crowell** [comment]
@radare `pd -1` works from there.
`s -1` should do the same thing.

**Comment by Tyilo** [comment]
But when the function has been analyzed, wouldn't it be possible to guess where the previous instruction is based on the disassembly starting from the beginning of the function?

**Comment by Tyilo** [comment]
@crowell It doesn't for me:
```
> pd -1
           0x100002ab0    0f45c8       cmovne ecx, eax
 ```
 
 It should go back one more byte.
 Here's how Hopper disassembles it:
 ![](http://i.imgur.com/3VEkYec.png)

**Comment by radare** [comment]
we can get the function address or the basic block one as base address
to find in prevopsz() instead of the fixed delta of 32 that we use now.

**Comment by Tyilo** [comment]
Visual mode also gets it right:
![](http://i.imgur.com/1ETdfMM.png)
