### ISSUE TITLE
v850 disassembler bug

### ISSUE THREAD

**Issue by radare** [radare/radare2#2006]
in arch/v850/v850_disas.h (see dupped 0x28)
```
        V850_SLDH       = 0x20,
        V850_SSTH       = 0x24,
        V850_SLDW       = 0x28,
        V850_SSTW       = 0x28,
        V850_BCOND      = 0x2C,
        V850_BCOND2     = 0x2D,
```

which produces wrong assignment in this array:
```
        [V850_SLDW]     = "sldw",
        [V850_SSTW]     = "sstw",
```

**Comment by XVilka** [comment]
afair it was in the datasheet. So just comment 1st line. @montekki

**Comment by radare** [comment]
This looks like a bug because no two different instructions can be decoded equally
