### ISSUE TITLE
Incorrect assembly in rasm2

### ISSUE THREAD

**Issue by aaronpuchert** [radare/radare2#2014]
The output of the following command

    > rasm2 -ax86 -b32 "add [esp+4], 8"
    83440408

won't work, the correct bytecode is `8344240408`. The reason is that `esp` is encoded as `100` in the R/M part of the ModR/M byte, i.e. the bits 2:0 of the second byte. But `100` in the R/M field triggers addressing via a SIB byte. Hence `[esp+4]` can be encoded there, with I=`100`, S=`00`, i.e. without index and B=`100`, i.e. `esp`. The next byte is the address offset `0x04`, then comes the immediate `0x08`.

**Comment by crowell** [comment]
this is an *ambiguous* instruction, as it doesn't tell you the size of what [esp+4] is pointing to.

really it should be

`add DWORD PTR [esp + 4], 8`

but I do see this is a bug here

```sh
minishwoods ~ » rasm2 -d "83 44 24 04 08" 
add dword [esp + 4], 8
```

```sh 
minishwoods ~ » rasm2 -a x86 -b 32 "add dword [esp + 4], 8"       
83440408
```

**Comment by radare** [comment]
The dword keyword if omited should handle the default reg size, which is in this case 32bits, aka dword

**Comment by aaronpuchert** [comment]
You're right, it is ambiguous. Didn't even notice, because that part was apparently interpreted correctly.

**Comment by aaronpuchert** [comment]
I couldn't read through the entire file, but the right `if` statement seems to be there. See [assembl.c, Line 1217](https://github.com/radare/radare2/blob/master/libr/asm/arch/x86/ollyasm/assembl.c#L1217):

```cpp
if (op->base<0 && op->index<0) {
    // ...
else if (op->index<0 && op->base!=GREG_ESP) {
    // ....
else { // SIB byte necessary
    hassib=1;
    // ....
}
```

**Comment by radare** [comment]
if you want to use the olly assembler type: rasm2 -a x86.olly, otherwise
it will be using the x86_nz one

**Comment by aaronpuchert** [comment]
Oh, I see. Well, the olly assembler produces a correct, yet not optimal opcode:

    > rasm2 -a x86.olly -b 32 "add dword [esp + 4], 8"
    8184240400000008000000

So I should rather take a look at [asm_x86_nz.c](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c)?

**Comment by radare** [comment]
Yes, it should be implemented in x86.nz which is the default assembler
and the only one that supports 64bits.

At some point it will be good to split all this code into a separate
library like capstone for assembling, but atm this is not yet done. so i
prefer keeping our own assembler and adding instructions as soon as
someone needs them.

Feel free to take a look and submit a patch, it shouldnt be hard, the
code is quite straight forward.

thanks!

**Comment by aaronpuchert** [comment]
Then the problem is [here](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c#L275) (and in [some](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c#L281) [other](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c#L336) [places](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c#L342)). It seems it would take some time to solve this satisfactorily.

**Comment by radare** [comment]
Are working on a patch, or should I take care of that issue?

**Comment by aaronpuchert** [comment]
Here is the thing: I could easily add some code to get that case right, but then somebody would stumble into the same issue with another instruction. It is not really necessary to write different code for each mnemonic, as it is now, because operations are all encoded in the same way. (roughly)
I'm working on a solution that would solve this and many similar issues. I'll post something today or tomorrow and then we'll see if it is worth developing further.

**Comment by aaronpuchert** [comment]
[This](https://gist.github.com/aaronpuchert/8d7be8c4c97eb23742f8) is what I've come up with. I ended up changing so much that a new assembler module seemed reasonable. Why? Assembling an instruction consists of parsing it, finding the right opcode, and encoding the arguments. In the existing `x86_nz` assembler, there is a parser and encoder for each mnemonic. I decided to split these stages and take advantage of the opcode grammar. This reduces the redundancy dramatically.

The algorithm has three stages:

* The first is to parse the instruction: they consist of a mnemonic and several operands. Prefixes are not implemented yet, but that can easily be done.
* The second stage has a large table, where every opcode is listed with its mnemonic and allowed operations. The mnemonic `add` might for example be encoded via many opcodes, depending on whether the operands are bytes or double words, and whether one of the operands comes from memory or is an immediate. Since our parser tells us what types the operands have, we can easily go through the table and find an opcode that fits.
* The third stage is writing the arguments. This is actually a bit messy, because there are many variants of indirect addressing. I hope I handled all of them.

Some things are still missing:
* Many opcodes. If the code has a chance of being accepted, I would add as much to the table as I can.
* 64-bit. As far as I understand, this only requires the REX prefix every now and then and should be easy to add without changing much elsewhere.
* Fancy algebraic expressions in indirect addressing, such as `[2*(eax+4)+ecx]`.
* Calculation of jump distances.

Tell me how you like it. Anyhow, it's just a sketch as of now. It can be compiled as a standalone application with `-DDEBUG`. Some examples:

```
> ./test "add byte ptr [ebp+4], al"
004504
> ./test "add al, [esp+4]"
02442404
> ./test "fsin"
D9FE
> ./test "add al, [eax+2*ecx+4]"
02444804
```

**Comment by radare** [comment]
The aproach looks better , but i dont plan to merge it unless we can ensure the rewrite doesnt regress. About 64 bit its not always prefixing the instruction with a bytr. Sometimes its a different consttuction. Thats why i did it in the lazy way, because i found several exceptions.

We have some asm/dis tests but i guess its not covering all cases yet. You can have a look at it. We can also merge your assembler as an independent one. And have it as an altrrnative to x86.nz until it can replace it

**Comment by aaronpuchert** [comment]
Yes, I totally agree. It's probably better to keep the x86_nz assembler as the standard for some time, until the new one is reliable enough. And about exceptions: *3DNow!* instructions are also encoded in a much different way, but I think that is manageable. If anyone uses them today, that is.

**Comment by radare** [comment]
Very basic instructions like "mov eax, 0" are still not supported. also, im not sure the state of the 64bit instructions. I think we can ignore 3dnow, mmx and fpu instructions for now.

the x86.nz should be fixed to close this issue imho, even if done in the ugly way for just that specific case.

**Comment by radare** [comment]
@crowell ?

**Comment by Northern-Lights** [comment]
The issue seems to persist:
```
system$ rasm2 -b 32 "xor word ptr [ebp+eax*2+0x1ac], 0x55"
31ff55
system$ rasm2 -b 32 "xor word ptr [ebp+eax*2-0x1ac], 0x55"
31ff55
system$ rasm2 -b 32 "xor word ptr [ebp+eax*2], 0x55"
31ff55
system$ rasm2 -b 32 "xor word ptr [ebp+eax], 0x55"
31ff55
system$ rasm2 -b 32 "xor word ptr [ebp], 0x55"
31ff55
system$ rasm2 -b 32 "xor word ptr [], 0x55"
31ff55
system$ rasm2 -b 32 "xor word ptr, 0x55"
31ff55
system$ rasm2 -b 32 "xor word, 0x55"
31ff55
system$ rasm2 -b 32 "xor , 0x55"
31ff55
system$ rasm2 -b 32 ", 0x55"
Cannot assemble '0x55' at line 3
system$ rasm2 -b 32 -d "31ff55"
xor edi, edi
push ebp
```

**Comment by radare** [comment]
Use -a x86.olly or x86.nasm, but dont close this issue because those expressions should be handled by the default x86.nz

**Comment by aaronpuchert** [comment]
@Northern-Lights: See my [comment above](https://github.com/radare/radare2/issues/2014#issuecomment-72501009). I started writing an assembler in `libr/asm/p/asm_x86_tab.c` that should be able to assemble your instructions correctly. Unfortunately I didn't have the time to add 64-bit support, so it can't replace the existing assembler. Other issues are tracked in #2095.
