### ISSUE TITLE
[zzuf] pd -999 remaining bugs

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2019]
morrn,

from commit I noticed that pd -999 might not be fully fixed.
here is a list of some 40 files, that should trigger SIGSEGV on 32 bit.

![pd-999-fuzzedfiles](https://cloud.githubusercontent.com/assets/5694980/5987862/c5573cf6-a943-11e4-8200-300dce5f22ac.png)  (tgz)

r2 -v
radare2 0.9.9-git @ linux-little-x86-32 git.0.9.8-603-g7392437
commit: 739243749146ada66e76cafe06061746058d0c55 build: 2015-01-31

Greetings
--zlul

**Comment by crowell** [comment]
@zonkzonk I'm rewriting it now.
expect an update soon.

**Comment by radare** [comment]
The crash is fixed. but the command is just returning trash. i'm waiting for @crowell to finish the fix, otherwise if that takes too long i'll rewrite it before the release.

**Comment by crowell** [comment]
finished rewriting.
