### ISSUE TITLE
Build script error fatal

### ISSUE THREAD

**Issue by PheonixOS** [radare/radare2#2028]
Firstly, got radare2 to build after fixing a makefile script:
LDFLAGS=-L ${LIBR}/socket -lr_socket
must be
LDFLAGS=-L${LIBR}/socket -lr_socket
note the space removal, and this is a macosx build, radare2-0.9.8/shlr/gdb/Makefile.
Secondly, some warnings, but omitted for now, leading to third:
ran "make tests", some "OK", some "XX", some "BR", but had to force stop
the test on "5  feat_yank: yank-segfault4".
I am guessing a memory leak in code, symptoms: no memory, computer very slow to respond.

Question: Since hangs on test, I assume unusable. Is this a correct assumption? And, would build
warnings be of use to "you"?
Thanx

**Comment by radare** [comment]
Thanks, i have applied your patch, it shouldnt be problematic.. but its ok to push that if it fixes any issue :? and yes. i'm aware the testsuite needs to get some attention again. Because I did some changes in pd output and how analysis work, so some tests may fail.. but none of them should segfault. Btw, you are using 0.9.8? can you please use r2 from git? i plan to release 0.9.9 this month.

Thanks!

**Comment by radare** [comment]
$ t/feat_yank 
[OK]  1  feat_yank: yank-segfault                 
[OK]  2  feat_yank: yank-and-paste                
[OK]  3  feat_yank: yank-segfault2                
[OK]  4  feat_yank: yank-segfault3                
[OK]  5  feat_yank: yank-segfault4                
[OK]  6  feat_yank: yank-doublefree

**Comment by PheonixOS** [comment]
On 2 Feb 2015, at 1:21 PM, radare wrote:

> Thanks, i have applied your patch, it shouldnt be problematic.. but its ok to push that if it fixes any issue :? and yes. i'm aware the testsuite needs to get some attention again. Because I did some changes in pd output and how analysis work, so some tests may fail.. but none of them should segfault. Btw, you are using 0.9.8? can you please use r2 from git? i plan to release 0.9.9 this month.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub.
> 
Downloaded from git "clone" instead of downloading .zip, fixed up -L:

new version 0.9.9, non-fatal -L problem (not sure which file, but here's printout):
....
LD libr_parse.dylib
CC parse_z80_pseudo.c
ld: -L must be immediately followed by a directory path (no space)
collect2: ld returned 1 exit status
make[5]: *** [parse_mreplace.dylib] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [plugins] Error 2
DIR asm
DIR debug
...

make tests definitely a memory leak, hangs on:
[  ]  5  feat_yank: yank-segfault4

watched free space go to about 7MB, VM increases til I ctrl-Z script


radare2 0.9.9-git @ darwin-little-x86-64 git.0.9.8-625-g31a5572
commit: 31a557289d88c743e2f230a9f2a16a76403a37c6 build: 2015-02-02

Thanks=
