### ISSUE TITLE
/R/  /usr/bin/cdrecord 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2031]
morrn,

no fuzzed file today, just running r2 through /usr/bin

```
,r2 -c "/R/ pop" /usr/bin/cdrecord 
Segmentation fault
Core was generated by `r2 -c /R/ pop /usr/bin/cdrecord'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7a5ff872c3 in r_asm_disassemble (a=0x1f34d30, op=0x7fff0be3b280, 
    buf=0x7f7a5ce77fde <error: Cannot access memory at address 0x7f7a5ce77fde>, len=4566570) at asm.c:314
314             sprintf (op->buf_asm,".byte 0x%02x %d", buf[0], len);
(gdb) bt
#0  0x00007f7a5ff872c3 in r_asm_disassemble (a=0x1f34d30, op=0x7fff0be3b280, 
    buf=0x7f7a5ce77fde <error: Cannot access memory at address 0x7f7a5ce77fde>, len=4566570) at asm.c:314
#1  0x00007f7a62755cda in r_core_search_rop (core=0x607980 <r>, from=4194304, to=8760824, opt=0, grep=0x1f8ba64 "pop", regexp=1) at cmd_search.c:897
#2  0x00007f7a6275763a in cmd_search (data=0x607980 <r>, input=0x1f8ba61 "R/ pop") at cmd_search.c:1366
#3  0x00007f7a6277e17f in r_cmd_call (cmd=0x1f5fbe0, input=0x1f8ba60 "/R/ pop") at cmd_api.c:179
#4  0x00007f7a6275d1ce in r_core_cmd_subst_i (core=0x607980 <r>, cmd=0x1f8ba60 "/R/ pop", colon=0x0) at cmd.c:1437
#5  0x00007f7a6275b8e9 in r_core_cmd_subst (core=0x607980 <r>, cmd=0x1f8ba60 "/R/ pop") at cmd.c:981
#6  0x00007f7a6275db7d in r_core_cmd (core=0x607980 <r>, cstr=0x7fff0be3ee21 "/R/ pop", log=0) at cmd.c:1624
#7  0x00007f7a6275e11e in r_core_cmd0 (user=0x607980 <r>, cmd=0x7fff0be3ee21 "/R/ pop") at cmd.c:1747
#8  0x0000000000404cf4 in main (argc=4, argv=0x7fff0be3cc28, envp=0x7fff0be3cc50) at radare2.c:696
(gdb) 
```

r2 -v
radare2 0.9.9-git @ linux-little-x86-64 git.0.9.8-625-g31a5572
commit: 31a557289d88c743e2f230a9f2a16a76403a37c6 build: 2015-02-02

cdrecord -version
Cdrecord-yelling-line-to-tell-frontends-to-use-it-like-version 2.01.01a03-dvd 
Wodim 1.1.11

Greetings
--zlul

**Comment by trufae** [comment]
Try with asm.arch=x86.udis. i get some valgrind warnings about the capstone decoder

**Comment by zonkzonk** [comment]
http://sprunge.us/CaLO

same with 95d97044986eeb44264840df1731a76c5a971227 and udis :/

**Comment by jjdredd** [comment]
confirmed on a 32 bit build, c78b0968d601999e7204082f2c044275b91606a7 for @zonkzonk 's file

0xb741ac3b in r_asm_disassemble (a=0x80c3e50, op=0xbfffd984, 
    buf=0xb69f7fd6 <error: Cannot access memory at address 0xb69f7fd6>, 
    len=4566570) at asm.c:314
314		sprintf (op->buf_asm,".byte 0x%02x %d", buf[0], len);
(gdb) bt
#0  0xb741ac3b in r_asm_disassemble (a=0x80c3e50, op=0xbfffd984, 
    buf=0xb69f7fd6 <error: Cannot access memory at address 0xb69f7fd6>, 
    len=4566570) at asm.c:314
#1  0xb7f37f0d in r_core_search_rop (core=0x804f300 <r>, from=4194304, 
    to=8760824, opt=0, grep=0x810afac "pop", regexp=1) at cmd_search.c:897
#2  0xb7f39a98 in cmd_search (data=0x804f300 <r>, input=0x810afa9 "R/ pop")
    at cmd_search.c:1366
#3  0xb7f6493d in r_cmd_call (cmd=0x80e8238, input=0x810afa8 "/R/ pop")
    at cmd_api.c:179
#4  0xb7f3ff8b in r_core_cmd_subst_i (core=0x804f300 <r>, 
    cmd=0x810afa8 "/R/ pop", colon=0x0) at cmd.c:1437
#5  0xb7f3e441 in r_core_cmd_subst (core=0x804f300 <r>, 
    cmd=0x810afa8 "/R/ pop") at cmd.c:981
#6  0xb7f40a4f in r_core_cmd (core=0x804f300 <r>, cstr=0xbffff11d "/R/ pop", 
    log=0) at cmd.c:1624
#7  0xb7f40feb in r_core_cmd0 (user=0x804f300 <r>, cmd=0xbffff11d "/R/ pop")
    at cmd.c:1747
#8  0x0804c3db in main (argc=4, argv=0xbfffef14, envp=0xbfffef28)
    at radare2.c:696

**Comment by radare** [comment]
its an obvious bug, udis fix pushed, working on the cs one

**Comment by trufae** [comment]
The cs bug doesnt seems to be easy to fix. Cant reproduce in specific test. Maybe asan can help us here, but all the code path seems fine and it shouldnt be accessing uninit data... Mainly because udis access the same bytes and its not uninitialized :? I'll have to check this more deeply

**Comment by zonkzonk** [comment]
I can catch segfault by limiting len in r_asm_disassemble, but this is no good solution. Did you had some time to analyse it ? ( I was running this bug with -b64 on a 32 bit debian system.)
