### ISSUE TITLE
Add SEH parser

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2036]
This is for the Windows 64 https://github.com/tandasat/scripts_for_RE/blob/master/parse_x64_SEH.py

**Comment by XVilka** [comment]
For 32bit SEH see this http://blog.davidegrayson.com/2016/02/windows-32-bit-structured-exception.html

**Comment by Maijin** [comment]
Closing all the infos are in the META.

**Comment by XVilka** [comment]
@Maijin Which one? We have multiple related to Windows.

**Comment by XVilka** [comment]
Nvm, found - it's this one https://github.com/radare/radare2/issues/921
