### ISSUE TITLE
Dotted lines for conditional jumps

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#204]
1. Should help to recognize ifs/switches
2. Should help to differ them from unconditional jumps
3. Different color on debug mode when jump is taken/not taken

**Comment by Maijin** [comment]
Probably related in a way to https://github.com/radare/radare2/issues/1963

**Comment by radare** [comment]
this can be easily implemented now after 96dbf57b300b860433d7e4104c52fdb80baeddc1

**Comment by Maijin** [comment]
I tried fixing https://github.com/radare/radare2/issues/204 but I didn't find any blocks that handle the conditional/non-conditional jump defined here https://github.com/radare/radare2/blob/master/libr/anal/reflines.c#L287 or https://github.com/radare/radare2/blob/master/libr/anal/reflines.c#L270 at least not on a simple /bin/ls.

Basically i tried to add two else if here https://github.com/radare/radare2/blob/master/libr/anal/reflines.c#L441 so it has 4 cases.

**Comment by Maijin** [comment]
Related https://github.com/radare/radare2/issues/333

**Comment by MaskRay** [comment]
We need 
```
U+2504 | ┄ | e2 94 84 | BOX DRAWINGS LIGHT TRIPLE DASH HO­RI­ZON­TAL | FORMS LIGHT TRIPLE DASH HORIZONTAL
-- | -- | -- | -- | --
U+2506 | ┆ | e2 94 86 | BOX DRAWINGS LIGHT TRIPLE DASH VER­TI­CAL | FORMS LIGHT TRIPLE DASH VERTICAL


```

besides 
```
#define RUNE_LINE_VERT "│"
#define RUNE_LINE_CROSS "┼" /* ├ */
#define RUNE_LINE_HORIZ "─"
#define RUNE_LINE_UP "↑"
#define RUNE_CORNER_BR "┘"
#define RUNE_CORNER_BL "└"
#define RUNE_CORNER_TL "┌"
#define RUNE_CORNER_TR "┐"
#define RUNE_ARROW_RIGHT ">"
#define RUNE_ARROW_LEFT "<"
```

**Comment by Maijin** [comment]
go for it
