### ISSUE TITLE
Review/fix x86-cs-esil

### ISSUE THREAD

**Issue by condret** [radare/radare2#2045]
it is mostly correct, but some esil-expressions are wrong and a few of them do not meet the specification of the esil-vm, especially when it comes to the carry-flag.

`%c,cf,=` is not a correct esil-expression, but `%c63,cf,=` is correct.

we need to review them all i think

**Comment by radare** [comment]
yep. all esil stuff should be reviewed. it works for simple cases and
its ok for such usage, but if we want full emulation or at least more
complete there are several expressions that may fail. Not only on x86

I think brainfuck is the only fully working now :P

**Comment by condret** [comment]
except from daa, stop and halt gameboy is esil-complete. But gameboy requires more work on io.

**Comment by Maijin** [comment]
useless issue.
