### ISSUE TITLE
Wrong terminal size autodetection on some terminals

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2057]
reported by @jjdredd 

On both lxterminal (libvte-based) and pure tty ("Ctrl-Alt-F3") wrong terminal size autodetection - skips first 2 lines.
Also difference increasing as lxterminal window size is increasing too.
I've asked to compare with https://stackoverflow.com/questions/1022957/getting-terminal-width-in-c
and libr/cons/cons.c r_cons_new() results.
Waiting for more information from @jjdredd

**Comment by jjdredd** [comment]
I need a reminder.
xvilka__: Judge_Dredd: and pls add temp debug output in libr/cons/cons.c - r_cons_new() before the return
xvilka__: Judge_Dredd: i don't care about absolute numbers - tell me them compared with eprintfs() output in the r_cons_new()

**Comment by XVilka** [comment]
@jjdredd probably bumping lxterminal could help too https://bugs.gentoo.org/show_bug.cgi?id=531128

**Comment by radare** [comment]
A similar problem was happening on Prompt for iOS. Ive tried with latest beta and seems that it is fixed now. This is great news. So i would vote for a buggy terminal rather than bug in r2 woth incorrect terminal size. There are some scr. Vars to correct this by hand

**Comment by XVilka** [comment]
@radare - yes, because lxterminal in gentoo is 0.1.11 which is require outdated version of vte lib - 0.28.
So bumping it to a newer version, depending from >=0.34 lib probably can help (I hope so).

**Comment by jjdredd** [comment]
Ok, the issue was very simple. The lines that are too long are continued on the next row of the terminal, so the print out actually took more lines than printed (row number detection is OK). So this todo needs to be fulfilled: 
https://github.com/radare/radare2/blob/master/libr/cons/less.c#L12
and I'm not sure how to do this without breaking highlighting.

**Comment by radare** [comment]
but this happens even without colors, lines should be chopped to width =
r_cons_size(). using r_str_ansilen() // or something like this //

**Comment by jjdredd** [comment]
I'll look in util/str.c and try to propose an improvement.

**Comment by XVilka** [comment]
This is is a terminal bug. If you still want to write a patch to workaround it - feel free to send a PR.
