### ISSUE TITLE
Properly handle 'V*' commands

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2059]
Goal is properly handle all 'V' inner commands.
E.g. if you type 'V?' in the cli, it shows you help screen, then type 'q' - it shows visual mode, instead of returning in cli. Same for 'VVn' - it doesn't show minigraph directly - it goes into the 'V' mode instead.

**Comment by Maijin** [comment]
Could be really useful for testing too

**Comment by radare** [comment]
i did some enhancements here, pls rechk

**Comment by Maijin** [comment]
Still tests can't work because of this.

**Comment by radare** [comment]
I think we need to add a new method in RCons to push data into the readchar buffer and pull them if any before reading from user. And remove all the hacky workarounds. This may allow us to add some youterm-like support for scripting r2 at stdin level. maybe having some special syntax for sleeps and such

**Comment by radare** [comment]
Done :D
