### ISSUE TITLE
radiff2 -j : JSON output for diffing data or code

### ISSUE THREAD

**Issue by radare** [radare/radare2#2061]

**Comment by kairenken** [comment]
Hi,
I would like to try my luck on this issue.

**Comment by kairenken** [comment]
Would this be a good output format for JSON-based radiff2?

```shell
$ radiff2 bgrep bgrep.2
0x000008e2 31ed5e89e1 => 9066890408 0x000008e2
0x00000937 74 => 90 0x00000937
$ radiff2 -r bgrep bgrep.2
wx 9066890408 @ 0x000008e2
wx 90 @ 0x00000937
$ radiff2 -j bgrep bgrep.2
{offset:0x000008e2 , from:31ed5e89e1 , to:9066890408}
{offset:0x00000937 , from:74 , to:90}
```

**Comment by radare** [comment]
The from/to must be an hexpair string, or maybe for json we want to use an array of numbers in decimal. Which seems more native.

Also from/to seems more related to offsets. Use "data" for that array. Also your json representation misses the point that offset in fileA can be different in file B.

Also bear in mind that json != js. All keys must be quoted, hexadecimal numbers are not valid, etc use | json_pp to verify that.

I would say something like:

[{"offset":[100,200],"data":[
  [1,2,3],[2,3,4]],...

But maybe we can think better constructions.

**Comment by kairenken** [comment]
Thank you for your comments and suggestions. I've improved the json output the way you've proposed. 
See the example shell session:

````shell
$ radiff2 -j bgrep bgrep.2 
[{"offset":[2274, 2274], "data":[[49,237,94,137,4],[144,102,137,4,8]]},
{"offset":[2359, 2359], "data":[[0],[144]]}]
$ radiff2 -j bgrep bgrep.2 | json_pp
[
   {
      "data" : [
         [
            49,
            237,
            94,
            137,
            4
         ],
         [
            144,
            102,
            137,
            4,
            8
         ]
      ],
      "offset" : [
         2274,
         2274
      ]
   },
   {
      "data" : [
         [
            0
         ],
         [
            144
         ]
      ],
      "offset" : [
         2359,
         2359
      ]
   }
]
$ radiff2 bgrep bgrep.2
0x000008e2 31ed5e89e1 => 9066890408 0x000008e2
0x00000937 74 => 90 0x00000937
````

**Comment by radare** [comment]
maybe we should group that the data of each entry like this:

[
  [ { “offset”: 123, “data": [1,2,3] }, {“offset”: 321, “data”: [3,2,1]} ],
 …

also i find it redundant to have to specify the offset on every row, and we are asuming each array of 2 contains first the first file and 2nd the other one.

if both offsets are the same maybe we can just reudce that information.. did you tried with radiff2 -dj ? that supports delta diffing, that will produce different offsets in there.

Maybe @nighterman or @pwntester can enlighten us a bit with their json skillz

thanks!

**Comment by kairenken** [comment]
delta diffing seems to work. I see different offsets with -dj. 
The assumption about the ordering of files is also taken when using -r:

````shell
$ radiff2 -r bgrep bgrep.2
wx 9066890408 @ 0x000008e2
wx 90 @ 0x00000937
````

But if we declare this assumption wrong do we have to insert the filenames?

**Comment by radare** [comment]
Yep, we can add an object describing the targets like this:

Filename
Size
Path?
Hash?
...
