### ISSUE TITLE
io.cache changes not visible

### ISSUE THREAD

**Issue by wodz** [radare/radare2#2064]
r2 -a mips -b 32 -e io.va=true -e io.cache=true MBRCFXXX.BIN.r2
[0x00000000]>  S 0 0xb4040000 32768 32768 iram rwx
[0x00000000]> 0xb4040014
[0xb4040014]> px 4
0xb4040014  0000 0000                                ....            
[0xb4040014]> wx 0xaa55aa55
[0xb4040014]> px 4
0xb4040014  0000 0000                                ....            
[0xb4040014]> wc
idx=0 addr=0x00000014 size=4 00000000 -> 55aa55aa (not written)

**Comment by jjdredd** [comment]
looks similar to #1923

**Comment by condret** [comment]
can u try this with ````e io.vio = true```` ?

**Comment by wodz** [comment]
r2 -a mips -b 32 -e io.va=true -e io.cache=true -e io.vio=true MBRCFXXX.BIN.r2
no change in behaviour
