### ISSUE TITLE
DEVELOPERS.md mailing list

### ISSUE THREAD

**Issue by r0nk** [radare/radare2#2068]
The DEVELOPERS.md file says that the project has a mailing list, However it doesn't say where this mailing list is, or how to sign up for it.

**Comment by condret** [comment]
echo "your_mail_adresse" > /dev/null

the mailing list is dead, nobody really used it

**Comment by radare** [comment]
fixed in 1deb6eddde73f4a3c50ca2758c06d6273b982513
