### ISSUE TITLE
Broken filetype detection

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2076]
It seems that 31e08131d156c9e53c6a8bde8920874c732444bb is breaking some `cmd_info` tests:
```
 va       true
 root     elf
 class    ELF32
-lang     c
+lang     dlang
 arch     x86
 bits     32
 machine  Intel 80386
```

**Comment by radare** [comment]
The filetype is correct. Whats wrong is asuming that it is D instead of C
