### ISSUE TITLE
'do' is broken (only for ptrace?)

### ISSUE THREAD

**Issue by condret** [radare/radare2#2084]
it's broken in a way, that after doing ````do```` every read results in 0xff

**Comment by radare** [comment]
cant reproduce. works even with aslr here

**Comment by condret** [comment]
http://radare.tv/a/18

**Comment by radare** [comment]
Looks like The executable hasnt been loaded yet.. See dm output

**Comment by condret** [comment]
@radare yes, thats right, we're still somewhere in libr

**Comment by radare** [comment]
Thats a racist condition. Depending on how fast ur computer can spawn new processes the debugger will stop before or after that.. We can probably enforce a specific event or breakpoint to start with to avoid this..

**Comment by condret** [comment]
there is a bug in glibc, maybe we can use that

**Comment by radare** [comment]
Which bug?

**Comment by condret** [comment]
forget that bug, it's pointless here
