### ISSUE TITLE
segfault in the hud

### ISSUE THREAD

**Issue by condret** [radare/radare2#2092]
````?ik```` in the hud + mousewheel can cause segfaults

**Comment by radare** [comment]
Paste backtrace or valgrind log

**Comment by condret** [comment]
no segfault with valgrind :(

**Comment by condret** [comment]
==3380== Memcheck, a memory error detector
==3380== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==3380== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==3380== Command: r2 Projekte/sandbox/anti-debug
==3380== Parent PID: 2181
==3380== 
==3380== Invalid read of size 8
==3380==    at 0x88B386E: r_list_purge (list.c:58)
==3380==    by 0x88B38E0: r_list_free (list.c:71)
==3380==    by 0x50D2FDF: r_core_visual_mounts (vmenus.c:636)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380==  Address 0xacc8cb0 is 0 bytes inside a block of size 24 free'd
==3380==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3380==    by 0x88B38EC: r_list_free (list.c:72)
==3380==    by 0x50D3115: r_core_visual_mounts (vmenus.c:655)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380== 
==3380== Invalid write of size 8
==3380==    at 0x88B38A9: r_list_purge (list.c:64)
==3380==    by 0x88B38E0: r_list_free (list.c:71)
==3380==    by 0x50D2FDF: r_core_visual_mounts (vmenus.c:636)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380==  Address 0xacc8cb8 is 8 bytes inside a block of size 24 free'd
==3380==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3380==    by 0x88B38EC: r_list_free (list.c:72)
==3380==    by 0x50D3115: r_core_visual_mounts (vmenus.c:655)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380== 
==3380== Invalid read of size 8
==3380==    at 0x88B38B5: r_list_purge (list.c:64)
==3380==    by 0x88B38E0: r_list_free (list.c:71)
==3380==    by 0x50D2FDF: r_core_visual_mounts (vmenus.c:636)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380==  Address 0xacc8cb8 is 8 bytes inside a block of size 24 free'd
==3380==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3380==    by 0x88B38EC: r_list_free (list.c:72)
==3380==    by 0x50D3115: r_core_visual_mounts (vmenus.c:655)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380== 
==3380== Invalid write of size 8
==3380==    at 0x88B38BD: r_list_purge (list.c:64)
==3380==    by 0x88B38E0: r_list_free (list.c:71)
==3380==    by 0x50D2FDF: r_core_visual_mounts (vmenus.c:636)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380==  Address 0xacc8cb0 is 0 bytes inside a block of size 24 free'd
==3380==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3380==    by 0x88B38EC: r_list_free (list.c:72)
==3380==    by 0x50D3115: r_core_visual_mounts (vmenus.c:655)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380== 
==3380== Invalid free() / delete / delete[] / realloc()
==3380==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3380==    by 0x88B38EC: r_list_free (list.c:72)
==3380==    by 0x50D2FDF: r_core_visual_mounts (vmenus.c:636)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380==  Address 0xacc8cb0 is 0 bytes inside a block of size 24 free'd
==3380==    at 0x4C2B200: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3380==    by 0x88B38EC: r_list_free (list.c:72)
==3380==    by 0x50D3115: r_core_visual_mounts (vmenus.c:655)
==3380==    by 0x50B147F: r_core_visual_cmd (visual.c:823)
==3380==    by 0x50B4449: r_core_visual (visual.c:1623)
==3380==    by 0x50A294E: cmd_visual (cmd.c:673)
==3380==    by 0x50C652B: r_cmd_call (cmd_api.c:179)
==3380==    by 0x50A5079: r_core_cmd_subst_i (cmd.c:1437)
==3380==    by 0x50A3794: r_core_cmd_subst (cmd.c:981)
==3380==    by 0x50A5A63: r_core_cmd (cmd.c:1628)
==3380==    by 0x506BB33: r_core_prompt_exec (core.c:1015)
==3380==    by 0x404F78: main (radare2.c:742)
==3380== 
==3380== 
==3380== HEAP SUMMARY:
==3380==     in use at exit: 112,084 bytes in 757 blocks
==3380==   total heap usage: 20,926 allocs, 20,172 frees, 14,457,732 bytes allocated
==3380== 
==3380== LEAK SUMMARY:
==3380==    definitely lost: 53,644 bytes in 366 blocks
==3380==    indirectly lost: 29,685 bytes in 291 blocks
==3380==      possibly lost: 480 bytes in 12 blocks
==3380==    still reachable: 28,275 bytes in 88 blocks
==3380==         suppressed: 0 bytes in 0 blocks
==3380== Rerun with --leak-check=full to see details of leaked memory
==3380== 
==3380== For counts of detected and suppressed errors, rerun with: -v
==3380== ERROR SUMMARY: 15 errors from 5 contexts (suppressed: 0 from 0)
