### ISSUE TITLE
Issues in x86.tab assembler

### ISSUE THREAD

**Issue by aaronpuchert** [radare/radare2#2095]
This is to keep track of what needs to be done in the [x86.tab assembler](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_tab.c).
- [ ] choose shortest/best encoding
- [ ] read and process prefixes
- [ ] error handling (As of now, the assembler just fails silently in most cases)
- [ ] 16-bit support
- [ ] 64-bit support
- [ ] FPU opcodes
- [ ] operations from SSE2 and newer extensions

**Comment by radare** [comment]
I would priorize 64bit support

**Comment by radare** [comment]
What about 16bit?

**Comment by aaronpuchert** [comment]
The order of items is not meant to imply any priorities. Maybe I will implement 16-bit support first, since it is by far easier.
- [ ] 16-bit support

**Comment by radare** [comment]
ping

**Comment by aaronpuchert** [comment]
I'm currently low on free time, but I'll continue as soon as I can. Meanwhile, it would be nice if others add as many tests as possible. I might (unintentionally) only add those I'm thinking about anyway.

**Comment by Maijin** [comment]
@Svenito

**Comment by Maijin** [comment]
I think now this should be added in x86.nz whenever it's really needed since there is also keystone.

**Comment by aaronpuchert** [comment]
I wrote this assembler because the x86.nz assembler had a lot of code duplication and was hard to maintain. I'm sorry that I didn't have the time to fix the issues, but apparently the x86.nz assembler has been refactored now (996e767e0de7cac01649d66eff70664f06c93959) and looks much better.
Consequently, it made sense to remove the x86.tab assembler (6c549b424a98545df876003140c7bbcc5b9a1b48).

**Comment by radare** [comment]
your work is still living in the radare2-extras, unlogic was happy to merge your stuff into the x86.nz and everything is passing fine, so in theory the goods of nz and tab should be living now in nz. So we can keep working on nz to improve it. but i wanted to keep tab for historical reasons :)

thanks!

**Comment by aaronpuchert** [comment]
I just had a look at it, and some parts look familiar. Nice work by @Svenito. This seems easy to build on for future extensions.

**Comment by Maijin** [comment]
Now remains to move ollydbg and maybe the rest of x86 assembler in r2pm so there is only .nz remaining in master see/discuss: #660

**Comment by Svenito** [comment]
Thanks @aaronpuchert. Tab has some nice features that I felt would make nz easier to maintain and expand. So also thanks for writing it and giving some inspiration.
