### ISSUE TITLE
Add command to write base64

### ISSUE THREAD

**Issue by radare** [radare/radare2#2096]
Add two more `w` subcommands to write in base64 encoded or decoded

```
> w6d AA==
### same as wx 00

> w6e 00
### same as w AA==
```

**Comment by radare** [comment]
This way those commands are in sync with `p6`

**Comment by Tyilo** [comment]
Close?

**Comment by radare** [comment]
it's here https://github.com/radare/radare2/commit/62985a7f87c744d3bbacfc3f08d7f208c3df9914

**Comment by Tyilo** [comment]
So shouldn't this issue be closed? Anything more that needs to implemented?
