### ISSUE TITLE
Use sdb to store local vars and other RAnal information

### ISSUE THREAD

**Issue by radare** [radare/radare2#210]
As long as variables and function signatures depend on cparse in order to properly understand data types. We need to convert from current storage (RList) to use Sdb.

The keys will be something like this:

```
[+]frame.${addr}=${varname}
frame.${addr}.${varname}=$type,$size,$offset
```

Contents of var key are similar to struct definition, so, in fact, a stack frame is just a struct linked to a specific function offset. We can create structs named something like `struct frame.$fcnaddr { void* ret; ... };`

It's important to use 'addr' as unique id. name can change

**Comment by oddcoder** [comment]
@pancake isn't that one resolved ?

**Comment by radare** [comment]
Yep. Thanks
