### ISSUE TITLE
Embedding r2 webui into IPython notebook (or in reverse order)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2100]
Would unleash the power of both for the reverse engineering.
- [ ] inspired by https://github.com/james91b/ida_ipython
- [ ] allow to keep/mix notes/disassembly/calculations/images
- [ ] python mathematics for the help for RE

[IPython Notebook](http://ipython.org/notebook.html)
![screenchot](http://ipython.org/_static/sloangrant/9_home_fperez_prof_grants_1207-sloan-ipython_proposal_fig_ipython-notebook-specgram.png)

**Comment by XVilka** [comment]
Or even go further - implement something like SageCloud - https://cloud.sagemath.com/ which is allow to edit documents/notebooks collaboratively, like in Google Docs.

**Comment by XVilka** [comment]
Related http://blog.jupyter.org/2016/07/14/jupyter-lab-alpha/

**Comment by Maijin** [comment]
This is done. https://github.com/radare/radare2-r2pipe/blob/master/python/ipython.py

**Comment by XVilka** [comment]
No, I spoke about webui. it's very far from done.

On Dec 16, 2016 2:36 AM, "Maijin" <notifications@github.com> wrote:

This is done. https://github.com/radare/radare2-r2pipe/blob/master/
python/ipython.py

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/radare/radare2/issues/2100#issuecomment-267464813>, or mute
the thread

**Comment by Maijin** [comment]
ah yes true

**Comment by radare** [comment]
Then why dont open this issue in the webui repo?
