### ISSUE TITLE
Graph-related issues

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2106]
- [ ] Draggable background, like in IDA. It would be nice to be able to move the graph around by dragging the background.
- [x] z-index issues with minimap. The graph can be over the minimap.
- [ ] Real-time minimap dragging. Currently, the graph moves after the minimap has been dragged.

**Comment by radare** [comment]
Last point was disabled for performance . It was terrible slow

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/2311
