### ISSUE TITLE
Unable to open file when debugging on Windows

### ISSUE THREAD

**Issue by Cwningen** [radare/radare2#2117]
I am trying to run a windows program with radare2 but I get "r_io_open_nomap: Unable to open file" errors in two different cases, not sure if they are related.

Trying to start the program without arguments:

    $ radare2 -Ad cryptex.exe
    PID=6016
    TID=7348
    ---> attach to 6016
    (w32_first_thread): Format message failed with 0x57
    w32thread: Oops
    pid = 2684980 tid = 2684980
    r_debug_select: 2684980 2684980
    r_io_open_nomap: Unable to open file: \Device\HarddiskVolume3\reversing\cryptex\cryptex.exe
    Asuming filepath \Device\HarddiskVolume3\reversing\cryptex\cryptex.exe
    r_io_open_nomap: Unable to open file: \Device\HarddiskVolume3\reversing\cryptex\cryptex.exe
    Asuming filepath \Device\HarddiskVolume3\reversing\cryptex\cryptex.exe
    pid = 6016 tid = 7348
    r_debug_select: 6016 7348
    Try: '=!pid'
    Function too big at 0x77417347
    ...

With an argument

    $ radare2 -Ad cryptex.exe l
    CreateProcess: Le fichier spÚcifiÚ est introuvable.
    
    r_io_open_nomap: Unable to open file: dbg://./cryptex.exe l
    Cannot open 'dbg://./cryptex.exe l' for writing.

I have no problem with static analysis.

The binary is from the Chapter 6 of [this book](http://www.wiley.com/go/eeilam) (download link on the page).

I am using Windows 7 64bits with radare2-w32-0.9.9-git from the nightly builds (20-Feb-2015 04:35).

**Comment by condret** [comment]
can u try with ````-d```` instead of ````-Ad```` ?

**Comment by condret** [comment]
can you start it with rarun2?

**Comment by radare** [comment]
I think its because of the ./ path which is not valid on w32, but didnt verified

**Comment by Cwningen** [comment]
If you mean just starting the program with rarun2, it works.
If you mean debugging through rarun2, it doesn't.

    $ radare2 -d rarun2 program=cryptex.exe
    CreateProcess: Le fichier spÚcifiÚ est introuvable.
    
    r_io_open_nomap: Unable to open file: dbg://rarun2 program=cryptex.exe
    Cannot open 'dbg://rarun2 program=cryptex.exe' for writing.

rarun2 is in the PATH, but I tried that too:

    $ radare2 -d C:\radare2-w32-0.9.9-git\rarun2.exe program=cryptex.exe
    CreateProcess: La syntaxe du nom de fichier, de rÚpertoire ou de volume est incorrecte.
    
    r_io_open_nomap: Unable to open file: dbg://./C:\radare2-w32-0.9.9-git\rarun2.exe program=cryptex.exe
    Cannot open 'dbg://./C:\radare2-w32-0.9.9-git\rarun2.exe program=cryptex.exe' for writing.

There is definitely a "./" that shouldn't be there.
Are the arguments supposed to be in the dbg:// path?

**Comment by Cwningen** [comment]
By the way, if you look into paths, I have also a bug with spaces.

    $ pwd
    C:\reversing\Chapter 6
    $ radare2 -d cryptex.exe
    PID=6728
    TID=1248
    ---> attach to 6728
    (w32_first_thread): Format message failed with 0x57
    w32thread: Oops
    pid = 2684980 tid = 2684980
    r_debug_select: 2684980 2684980
    r_io_open_nomap: Unable to open file: \Device\HarddiskVolume3\reversing\Chapter
    Asuming filepath \Device\HarddiskVolume3\reversing\Chapter
    r_io_open_nomap: Unable to open file: \Device\HarddiskVolume3\reversing\Chapter
    Asuming filepath \Device\HarddiskVolume3\reversing\Chapter
    pid = 6728 tid = 1248
    r_debug_select: 6728 1248
    Try: '=!pid'

But it is already reported in #1814.

**Comment by Cwningen** [comment]
In binr/radare2/radare2.c there is this section:
```C
/* implicit ./ to make unix behave like windows */
if (*f=='.' && f[1]=='/') {
	ptr = strdup (argv[optind]);
} else if (*f!='/' && *f!='.' && r_file_exists (argv[optind])) {
	ptr = r_str_prefix (strdup (argv[optind]), "./");
} else	ptr = r_file_path (argv[optind]);
```
From the comment I guess it should be platform specific, but event for unix I see some problems.
 - The second "if" exclude files beginning with a dot.
 - If a file exists both in the current directory and the PATH, the current directory one is used. I think it is incoherent with what shells do.

I think the logic should be changed for something like:
```
if (the argument is a path (contains a '/')) {
    use the argument unchanged
}
else {
    if (the file exists in the PATH) {
        use the file in PATH
    }
    else {
        prepend './'
    }
}
```
Maybe you won't agree with the PATH part, but the path test based on the '/' presence is, I think, both simpler and the correct way to do it.

A few line below the loop
```C
if (optind <argc)
	file = r_str_concat (file, " ");
while (optind < argc) {
	file = r_str_concat (file, argv[optind]);
	optind++;
	if (optind<argc)
		file = r_str_concat (file, " ");
}
```
could be simplified in
```C
while (optind < argc) {
	file = r_str_concat (file, " ");
	file = r_str_concat (file, argv[optind]);
	optind++;
}
```
IMO, it is more readable.

That won't solve most of my problems, I'll try to read more.

**Comment by radare** [comment]
Feel free to send a pullreq for review. Code cleanup, simplification or refactoring are also valid patches for r2 :)

Yeah that ./ part was added because some wusers complained about not being able to debug a program by its name (because it was in the same directory and didnt prefixed it with ./). So i added this line for relative paths.

Which is wrong for windows :) so that must be changed.

**Comment by Cwningen** [comment]
On the \Device\HarddiskVolume* filename, it fails because "open" is unable to open this kind of path. It comes from GetProcessImageFilename in r_sys_pid_to_path.
>The GetProcessImageFileName function returns the path in device form, rather than drive letters. For example, the file name C:\Windows\System32\Ctype.nls would look as follows in device form:
>
>\Device\Harddisk0\Partition1\Windows\System32\Ctype.nls
>
>To retrieve the module name of the current process, use the GetModuleFileName function with a NULL module handle. This is more efficient than calling the GetProcessImageFileName function with a handle to the current process.
>
>To retrieve the name of the main executable module for a remote process in win32 path format, use the QueryFullProcessImageName function.

[GetProcessImageFilename](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683217.aspx) is compatible with XP and later whereas [QueryFullProcessImageName](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684919.aspx) is Vista and later.

There is an interesting comment on GetProcessImageFilename page:
>For the best results use the following table to convert paths.
>
>Windows 2000 = GetModuleFileName()
>Windows XP x32 = GetProcessImageFileName()
>Windows XP x64 = GetProcessImageFileName()
>Windows Vista = QueryFullProcessImageName()
>Windows 7 = QueryFullProcessImageName()
>
>
>Note: If you are not aware the API GetProcessImageFileName() returns a kernel DOS device path. You can use the following API to map the device paths to a Win32 format.
>
>GetLogicalDriveStrings
>QueryDosDevice 

I guess the path format from GetProcessImageFileName has changed with Vista.

Since GetProcessImageFileName is dynamically loaded, a simple solution might be to try first to load QueryFullProcessImageName and only if it fails use GetProcessImageFileName. That way we could avoid using different compilation for different Windows versions.

I'll try with QueryFullProcessImageName, but I'll wait for your advice before writing a serious patch. And I don't have a computer with WinXP to test regressions.

**Comment by Cwningen** [comment]
I confirm that using QueryFullProcessImageName solve the no argument case for me.
My quick and dirty patch looks like that: http://pastebin.com/PQkcZS0Z
It is not compatible with WinXP.

**Comment by radare** [comment]
Thats a bit anoying. Im dont know much about windows, so, what would you recommend to make this patch work for wxp too? Checking for the output of the function? Checking for the windows version? Is wine doing the same?

Thanks!

**Comment by Cwningen** [comment]
I am not a windows expert either, but as I said, I would try to load QueryFullProcessImageName, and if GetProcAddress fails use GetProcessImageFileName as a fallback.
Checking in [GetProcAddress documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683212.aspx), microsoft advice to do something of this sort.
>If the function might not exist in the DLL module—for example, if the function is available only on Windows Vista but the application might be running on Windows XP—specify the function by name rather than by ordinal value and design your application to handle the case when the function is not available, as shown in the following code fragment.

My solution would be:
```C
	DWORD WINAPI (*QueryFullProcessImageNameA) (HANDLE, DWORD, LPTSTR, PDWORD);
	DWORD WINAPI (*GetProcessImageFileNameA) (HANDLE, LPTSTR, DWORD);
	HANDLE kernel32 = LoadLibrary ("Kernel32.dll");
	if (!kernel32) {
		eprintf ("Error getting the handle to Kernel32.dll\n");
		return NULL;
	}
	QueryFullProcessImageNameA = GetProcAddress (kernel32, "QueryFullProcessImageNameA");
	if (!GetProcessImageFileNameA) {
		// QueryFullProcessImageName does not exist before Vista, fallback to GetProcessImageFileName
		HANDLE psapi = LoadLibrary ("Psapi.dll");
		if (!psapi) {
			eprintf ("Error getting the handle to Psapi.dll\n");
			return NULL;
		}
		GetProcessImageFileNameA = GetProcAddress (psapi, "GetProcessImageFileNameA");
		if (!GetProcessImageFileNameA) {
			eprintf ("Error getting the address of GetProcessImageFileNameA\n");
			return NULL;
		}
	}
	HANDLE handle = NULL;
	TCHAR filename[MAX_PATH];
	DWORD maxlength = MAX_PATH;
	handle = OpenProcess (PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, pid);
	if (handle != NULL) {
		if (QueryFullProcessImageNameA) {
			if (QueryFullProcessImageNameA (handle, 0, filename, &maxlength) == 0) {
				eprintf("Error calling QueryFullProcessImageNameA\n");
				CloseHandle (handle);
				return NULL;
			}
		} else {
			if (GetProcessImageFileNameA (handle, filename, maxlength) == 0) {
				eprintf("Error calling GetProcessImageFileNameA\n");
				CloseHandle (handle);
				return NULL;
			}
		}
		CloseHandle (handle);
		return strdup (filename);
	}
	return NULL;
```
I have no idea about wine, it would only go wrong if QueryFullProcessImageName exists but with a different behavior.

**Comment by radare** [comment]
Looks like a good solution. Can you send a pullrequest? Thanks!

**Comment by Cwningen** [comment]
About the argument case, on Windows they are not parsed (in libr/io/p/io_debug.c fork_and_ptraceme).
```C
        /* TODO: with args */
        if (!CreateProcess (cmd, NULL,
                        NULL, NULL, FALSE,
                        CREATE_NEW_CONSOLE | DEBUG_ONLY_THIS_PROCESS,
                        NULL, NULL, &si, &pi)) {
                r_sys_perror ("CreateProcess");
                return -1;
        }
```

I will wait for the needed argument parsing improvement that I started to discuss in #1814 before working on that.
