### ISSUE TITLE
entry0 in flagspace strings

### ISSUE THREAD

**Issue by condret** [radare/radare2#2118]
i've noticed that entry0 on x86 (32) is set in flagspace strings. I guess it should be in functions

**Comment by radare** [comment]
You guessed right, or in symbols maybe

**Comment by crowell** [comment]
probably functions. It is not a symbol in the binary, and this would be
confusing if it is listed as a symbol.

On Fri, Feb 20, 2015 at 5:03 PM, radare <notifications@github.com> wrote:

> You guessed right, or in symbols maybe
>
>
>
> > On 20 Feb 2015, at 22:57, condret <notifications@github.com> wrote:
> >
> > i've noticed that entry0 on x86 (32) is set in flagspace strings. I
> guess it should be in functions
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2118#issuecomment-75327653>.
>



-- 
Jeff Crowell
https://github.com/crowell
