### ISSUE TITLE
Implement analysis + esil for z80-cr

### ISSUE THREAD

**Issue by radare** [radare/radare2#2119]
@condret or @jvoisin ?

**Comment by condret** [comment]
we can use the old z80-analysis its lgpl

**Comment by jvoisin** [comment]
Sure. But first, *someone* need to take a look at the testsuite, because it's currently angry :<

**Comment by condret** [comment]
@jvoisin : let's finish the analysis here, and then generate a new testsuite based on the disassembler and the analysis. Just what i did for gb

**Comment by kolen** [comment]
I'm working on esil, going to use table-based approach, like in ``z80_cr`` assembler plugin. Making [separate tool](https://github.com/kolen/z80-esil) to make tables for .h file. Z80 is quite quirky, especially flag register behavior (just like all other CPUs, maybe, but for example 6502 looks much simplier). Using [this](http://www.myquest.nl/z80undocumented/) as reference.


> we can use the old z80-analysis its lgpl

Is old z-80-analysis [libr/anal/p/anal_z80.c](https://github.com/radare/radare2/blob/master/libr/anal/p/anal_z80.c) or something else?

**Comment by radare** [comment]
Cc @condret

**Comment by Maijin** [comment]
@Svenito ^
