### ISSUE TITLE
Easy external access for both ESIL and opcodes (binary data).

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2128]
For really good decompilation process analysis code should have easy access for both high-level IR (ESIL), to capture the algorithm, and for the low-level assembly/binary code (after relocations applied) to catch the compiler tricks, uncover the real algorithm behind the optimizer. So some API for future decompilation should be designed for easy access of both sides.

**Comment by crowell** [comment]
This will be helpful for SSA task /cc @sushant94

**Comment by sushant94** [comment]
Sounds good. I can start working on it after discussion as I'm relatively free.

**Comment by crowell** [comment]
let's set up a pad to discuss how this feature should work before jumping into it ;-)

**Comment by XVilka** [comment]
https://pad.nopcode.org/p/rsoc-task-ssa

**Comment by XVilka** [comment]
Here is suggestion from condret, that there should be api for easy access to:
 - [ ] r_bin
 - [ ] r_io
 - [ ] r_asm
 - [ ] r_anal
 - [ ] r_reg
So decompiler will be able to easily access to the any level of the executable to catch the required data.
Since there can be various decompiler plugins we need to define a mechanism to provide external API for that.

**Comment by radare** [comment]
what? define easy access.

after 1.0 i want to fully review ALL the apis, module-by-module.
breaking the apis, using much more sdb and

defining external apis means, stabilization, this requires maintainance,
backward compat and all that crap that we can't provide before 1.0, and
really. i would only "stabilize" a small subset of each module.

also, you can write a decompiler using r2pipe without depending on any
api at all.

**Comment by XVilka** [comment]
@radare well, a big parts of decompiler will be in C, as you can see from the ESIL RSoC tasks,

**Comment by radare** [comment]
Yup. At least the core functionality as i did for pdc. Imho there's a long road until we can think in stable apis for the decompiler. And imho 90% of the commands to manipulate the decompilation are already commands from r2 with anal/bin/flags apis behind. So i dont think we really want decompiler specific apis at this point.

**Comment by XVilka** [comment]
@radare we do not think about a stable api, but about a suitable api for unified access to the IO levels, disassembly and a ESIL output. This is more a discussional bug.

**Comment by radare** [comment]
Maybe we can use the r*bind structures to export simple generic interfaces in other modules. But i want those structs as simple as possible.

**Comment by XVilka** [comment]
I'll remove the 'GSoC' label, since it will require a long work and mostly some refactoring.

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://greenmunnar.com/council.php?bh0c>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://kentuckyfuturestars.com/obligation.php?ih>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hello,

I was just wondering about your opinion on that stuff, please take a look and tell me what you think <http://kyslekefo.swimswap.info/lnopp>

Sent from a prehistoric stone tablet, lukas-runas@gmx.de

**Comment by condret** [comment]
Hi,

I just wantet to tell you how much I  appreciate all you're doing  for me, and I'd like to share with you something really important,  please read  it here <http://example.gityours.com/lnzofid>

Looking forward, lukas-runas@gmx.de

**Comment by radare** [comment]
How can we ban condret?

**Comment by XVilka** [comment]
I think this can be closed?
