### ISSUE TITLE
pf help is not really helpful

### ISSUE THREAD

**Issue by radare** [radare/radare2#2136]
the output is loo long, too wide, and it misses some of the new features like nesting structs, and such

**Comment by radare** [comment]
cc @hyask

**Comment by radare** [comment]
ping

**Comment by Hyask** [comment]
pong!
I'm sorry, I forgot that, even if it's really easy and fast... :/

**Comment by radare** [comment]
We opened a pad with @maijin to cleanup this thing

**Comment by Maijin** [comment]
Here is the pad https://pad.nopcode.org/p/kGvJFjDz8T

**Comment by radare** [comment]
FIxed
