### ISSUE TITLE
pf byte arrays are not readable

### ISSUE THREAD

**Issue by radare** [radare/radare2#2137]
```
pf [8]b

0x00001c10 = [ 49 ; 0x31 ; '1', 15 ; 0x0f ; '.', 0 ; 0x00 ; '.', 0 ; 0x00 ; '.', 66 ; 0x42 ; 'B', 15 ; 0x0f ; '.', 0 ; 0x00 ; '.', 0 ; 0x00 ; '.' ]
```

maybe we shuold specify the way we want to display the contents of the array:

* as bytes (hexa)
* as signed bytes (decimal)
* as chars (string?)

all of them? or maybe just in hexpairs format if its byte:

* [ 414243 ] ; "ABC"

**Comment by Hyask** [comment]
good idea
I'll just make b to display bytes, c to display chars, and maybe C to display decimal value

What do other think of that?

**Comment by radare** [comment]
Looks good to me!

**Comment by jvoisin** [comment]
And `s` for strings :)

**Comment by radare** [comment]
Wat.. Pointers to strings you mean?

**Comment by jvoisin** [comment]
Why pointers ?
I though that you could put strings (like "hello world\x00") in a `pf-structure`; can't you?

**Comment by radare** [comment]
Uhm... This is more like a sequence or chain than an array.. Arrays use to have all elements of the same size for quick index access. Not sure if we should find a different syntax for it..

**Comment by XVilka** [comment]
@radare @Hyask any updates on this?

**Comment by Hyask** [comment]
I think this is done, that was the purpose of d86254d
