### ISSUE TITLE
no symbols in the debugger

### ISSUE THREAD

**Issue by condret** [radare/radare2#2139]
````r2 -d /bin/ls```` and ````dcu entry0```` does not work here. can someone reproduce this?
395863f04fe works

**Comment by crowell** [comment]
works for me on 23cddbb06c73304fa679ac839a64ea70b1e15dd0

**Comment by XVilka** [comment]
@condret just share your file.

**Comment by condret** [comment]
damn, cannot reproduce anymore.

**Comment by radare** [comment]
Shouldnt waitpid() be enough in this case? We are attaching, not waiting for events from more than one process
