### ISSUE TITLE
Obey colourscheme in diff graphs

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2141]
Currently, radare2 doesn't obey colourscheme in diff graphs, making them ugly.

This issue is easy to fix

* make radiff2 load the radare2rc
* grab the colors and use them

the whole patch should be about 10 lines of C

**Comment by Maijin** [comment]
ping @jvoisin

**Comment by jvoisin** [comment]
This isn't fixed in `radiff2`:

```nasm
jvoisin@mim 13:17 ~ radiff2 =true =false -g main
digraph code {
	graph [bgcolor=white fontsize=8 fontname="Courier"];
	node [color=gray, style=filled shape=box];
	edge [arrowhead="vee"];
	"0x00401330" -> "0x00401338" [color="green"];
	"0x00401330" -> "0x00401335" [color="red"];
 "0x00401330" [color="red", label="  ;-- section..text:\l/ (fcn) main 202\l| 0x00401330      cmp edi, 2\l| 0x00401333      je 0x401338\l", URL="main/0x00401330"]
 "0x00401335" [color="red", label="| 0x00401335      xor eax, eax\l| 0x00401337      ret\l", URL="main/0x00401335"]
	"0x00401338" -> "0x004013c6" [color="green"];
	"0x00401338" -> "0x0040138b" [color="red"];
 "0x00401338" [color="red", label="| 0x00401338      push rbx\l| 0x00401339      mov rdi, qword [rsi]\l| 0x0040133c      mov rbx, rsi\l| 0x0040133f      call 0x401890\l| 0x00401344      mov esi, 0x40404d\l| 0x00401349      mov edi, 6\l| 0x0040134e      call sym.imp.setlocale\l| 0x00401353      mov esi, str._usr_share_locale\l| 0x00401358      mov edi, 0x4040c8\l| 0x0040135d      call sym.imp.bindtextdomain\l| 0x00401362      mov edi, 0x4040c8\l| 0x00401367      call sym.imp.textdomain\l| 0x0040136c      mov edi, 0x4017e0\l| 0x00401371      call 0x404000\l| 0x00401376      mov rbx, qword [rbx + 8]\l| 0x0040137a      mov esi, str.__help\l| 0x0040137f      mov rdi, rbx\l| 0x00401382      call sym.imp.strcmp\l| 0x00401387      test eax, eax\l| 0x00401389      je 0x4013c6\l", URL="main/0x00401338"]
	"0x0040138b" -> "0x004013c2" [color="green"];
	"0x0040138b" -> "0x0040139c" [color="red"];
 "0x0040138b" [color="red", label="| 0x0040138b      mov esi, str.__version\l| 0x00401390      mov rdi, rbx\l| 0x00401393      call sym.imp.strcmp\l| 0x00401398      test eax, eax\l| 0x0040139a      jne 0x4013c2\l", URL="main/0x0040138b"]
	"0x0040139c" -> "0x004013c2" [color="blue"];
 "0x0040139c" [color="red", label="| 0x0040139c      mov rcx, qword [rip + 0x204e0d]\l| 0x004013a3      mov rdi, qword [rip + 0x204e7e]\l| 0x004013aa      xor r9d, r9d\l| 0x004013ad      mov r8d, str.Jim_Meyering\l| 0x004013b3      mov edx, str.GNU_coreutils\l| 0x004013b8      mov esi, str.true\l| 0x004013bd      call 0x403630\l", URL="main/0x0040139c"]
 "0x004013c2" [color="red", label="| 0x004013c2      xor eax, eax\l| 0x004013c4      pop rbx\l| 0x004013c5      ret\l", URL="main/0x004013c2"]
 "0x004013c6" [color="red", label="| 0x004013c6      xor edi, edi\l| 0x004013c8      call 0x4014d0\l| 0x004013cd      nop dword [rax]\l| ;-- entry0:\l| 0x004013d0      xor ebp, ebp\l| 0x004013d2      mov r9, rdx\l| 0x004013d5      pop rsi\l| 0x004013d6      mov rdx, rsp\l| 0x004013d9      and rsp, 0xfffffffffffffff0\l| 0x004013dd      push rax\l| 0x004013de      push rsp\l| 0x004013df      mov r8, 0x403ff0\l| 0x004013e6      mov rcx, 0x403f80\l| 0x004013ed      mov rdi, main\l| 0x004013f4      call sym.imp.__libc_start_main\l\\ 0x004013f9      hlt\l", URL="main/0x004013c6"]
}
```

**Comment by radare** [comment]
how do you expect to load a colorscheme in radiff2 if there’s no prompt and it doesnt loads radare2rc?

**Comment by jvoisin** [comment]
What about loading the `.radare2rc` then?

**Comment by radare** [comment]
there aer several more loading scripts to take care of.. but yep. that can be an option

**Comment by radare** [comment]
care to send a pr adding 1 line of C?

**Comment by jvoisin** [comment]
I don't get how your two comments could possibly go together :D

**Comment by radare** [comment]
:D but its scary to run a script when we just want a colorscheme

**Comment by radare** [comment]
we can probably run the script, but only the lines that start with “e scr.” and ignore the rest

**Comment by radare** [comment]
we should enable gml for radiff2 too

**Comment by radare** [comment]
this issue is easy to fix

* make radiff2 load the radare2rc
* grab the colors and use them

the whole patch should be about 10 lines of C

**Comment by radare** [comment]
cc @lonetech

**Comment by radare** [comment]
this was the issue iwas refering to

**Comment by radare** [comment]
diff graphs are currently broken. we must find the commit that broke it

**Comment by radare** [comment]
we need tests for radiff

**Comment by XVilka** [comment]
Who is checking graphs right now? @lowlyw @xarkes ?

**Comment by lonetech** [comment]
Sorry, I have not been working on this, or much of anything. I'm out with some fairly serious burnout. I do have one comment: The reason the diff graphs don't even try to follow the colour scheme is that that scheme is not only undocumented but incompatible with what the graph diff does. The output of the graph diff is by colouring basic blocks by match degrees. (It doesn't do a very good job comparing, as there's no handling of offset adjustments etc, but it is what it is.)

**Comment by radare** [comment]
we should focus on diffing again after we get all that bin/anal refactoring ready

**Comment by radare** [comment]
ping @xarkes

**Comment by xarkes** [comment]
No time sorry.

**Comment by XVilka** [comment]
@cyanpencil you may want also to check this. Related also to https://github.com/radare/radare2/issues/8115

**Comment by radare** [comment]
ping @lowlyw

**Comment by radare** [comment]
see a2a7b911de535f437fc4434fcd7639db163909cf

**Comment by radare** [comment]
im afraid this wont be fixed for tonight and if it has been opened for 3 years we can wait for r2con to close it, should be quick and easy

**Comment by deepakchethan** [comment]
Is the diffing functional now ?

**Comment by XVilka** [comment]
@deepakchethan yes, just run `radiff2 -g main /bin/true /bin/false`

See more at https://radare.gitbooks.io/radare2book/content/tools/radiff2/binary_diffing.html

Idea also is to show the diffs in the split with standard ASCII/Unicode graphs - see https://github.com/radare/radare2/issues/7332

**Comment by deepakchethan** [comment]
Done at https://github.com/radare/radare2/pull/14831, can be closed now

**Comment by deepakchethan** [comment]
Done at https://github.com/radare/radare2/pull/14831, can be closed now

**Comment by Maijin** [comment]
Thanks for your work @deepakchethan !
