### ISSUE TITLE
%s in the esil-vm

### ISSUE THREAD

**Issue by condret** [radare/radare2#2144]
do we want a %s in the esil-vm for signature-flag -> ````%s,sf,=```` . This should be easy to implement, since every eq-operation requires a dst with a fixed size, that we can save as a var to generate a bit-mask for %s.
currently ````test eax, eax```` is
````eax,eax,&,0,==,%z,zf,=,%p,pf,=,31,eax,eax,&,31,1,<<,&,>>,sf,=,0,cf,=,0,of,=```` , with %s it would be ````eax,eax,&,0,==,%z,zf,=,%p,pf,=,%s,sf,=,0,cf,=,0,of,=````

**Comment by condret** [comment]
pls test it

**Comment by radare** [comment]
Signature? You mean sign?

**Comment by condret** [comment]
yes, thats what i mean
