### ISSUE TITLE
problem with line limit and comments

### ISSUE THREAD

**Issue by shibumi** [radare/radare2#2147]
Hello,
there is a problem with the line limit of the terminal and radare2.
When I want to write a very large comment I will write over the same line. For example:

![lastimg](https://cloud.githubusercontent.com/assets/3833685/6405867/35f8d6aa-be29-11e4-96cd-bd0bde9715b7.png)

I write over the same line and only one char with beginning < ..

**Comment by radare** [comment]
Which terminal are you using? (Program name and TERM env var)

**Comment by shibumi** [comment]
name: rxvt-unicolor 
$TERM = rxvt-unicode-256color
