### ISSUE TITLE
Remove http.public

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2152]
As we provided http.bind we don't really need http.public anymore:

 -[  ] Add http.bind and http.port into the documentation
 -[  ] Remove http.public at all

**Comment by radare** [comment]
Is this some kind of poll?

**Comment by XVilka** [comment]
Kind of. But we need to update documentation anyway, whatever we choose.

**Comment by zonkzonk** [comment]
I had something like this, but the other case also breaks. (That is http.public=false + someip)

```
+       if (r_config_get_i (core->config, "http.public") && strstr(host,"localhost")) {
+                 eprintf("Cannot set localhost in http.public");
+               return 1;
+        }
```

+1 for removal

**Comment by zonkzonk** [comment]
@jjdredd  @crowell any opinions ?

**Comment by crowell** [comment]
what is this question even? can you ping me on irc to discuss it?

**Comment by radare** [comment]
yep. the question is that if we should remove http.public now that we have http.bind

**Comment by radare** [comment]
Ive been thinking a while on this, and i  agree about the removal, but it will probably break some documentation and it is nicer to type: 
```
r2 -e http.public=true ...
```
than
```
r2 -e http.bind=0.0.0.0 ..
```

**Comment by crowell** [comment]
so much of the existing documentation/blog posts are out of date, that the
small change probably wont be much of an issue.

On Sun, Mar 15, 2015 at 10:28 PM, radare <notifications@github.com> wrote:

> Ive been thinking a while on this, and i agree about the removal, but it
> will probably break some documentation and it is nicer to type:
>
> r2 -e http.public=true ...
>
> than
>
> r2 -e http.bind=0.0.0.0 ..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2152#issuecomment-81353820>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by condret** [comment]
i think, keeping it alive would be inconsistent.

**Comment by radare** [comment]
i think we can use some aliases to make it more human friendly:

e http.bind=local
e http.bind=public

local = alias for 127.0.0.1
public = alias for 0.0.0.0

with this change im ok with it :) anyone?

**Comment by crowell** [comment]
sgtm

**Comment by radare** [comment]
Solved!
