### ISSUE TITLE
waffle.io graph in the readme is broken

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2164]
@XVilka should we just remove it entirely?

**Comment by radare** [comment]
Wat

**Comment by crowell** [comment]
this thing https://camo.githubusercontent.com/7fdd5d0678dc59d6b8985703b71c97b7a6826222/68747470733a2f2f6772617068732e776166666c652e696f2f7261646172652f726164617265322f7468726f7567687075742e737667

**Comment by crowell** [comment]
this thing https://waffle.io/radare/radare2/metrics

**Comment by crowell** [comment]
closed by 82a4a07d92e9f02bd1177b91eef88a23906d865b
