### ISSUE TITLE
rabin2 with json output prints a non-json line

### ISSUE THREAD

**Issue by Cwningen** [radare/radare2#2168]
Using `rabin2 -gj a.out`, I get a `a.out.fat/a.out.x86_64.0 created (21367)` line in my json output, so I need to filter it out before using a command line json parser like `jq`.

**Comment by Cwningen** [comment]
It does not happen with other options than g. Removing the v option solves this.
So a workaroung is using `rabin2 -SMResizj a.out` instead `rabin2 -gj a.out`.

**Comment by radare** [comment]
Can you point out whats the json lint issue? Grepping in core/bin.c should be easy to find the bug

**Comment by Cwningen** [comment]
The string come from rabin2.c (line 175 in my repo that I pulled today), in extract_binobj function.

Also, rabin2's help claim that "-g [is the] same as -SMRevsiz (show all info)" but -SMRevsiz just prints the version because of the -v option.
Actually it is nearly equivalent to -SMResizlIHCdZ, with the only difference of the "created" line, with or without JSON output.

**Comment by radare** [comment]
This line must be jsonified

**Comment by radare** [comment]
Fixed in git, thanks
