### ISSUE TITLE
Problem to install on Mac OS X

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#2170]
I was installing radare2 on Mac OS X and I was getting this error.

![captura de pantalla 2015-03-09 a las 20 38 53](https://cloud.githubusercontent.com/assets/3474042/6562847/8706f9de-c69c-11e4-87dd-5a04aa378a6f.png)

I commented the line with `case X86_INS_FFREEP` and then I could install it.

I don't know if anyone out there was getting the same error or was only me. At least I hope to be helpful for the team. kudos

**Comment by radare** [comment]
Are you using the latest capstone release or the one shipped with r2? Because iirc this is only available on git

**Comment by alvarofe** [comment]
It seems that I am using capstone release without want it. In the config-user.mk I have the following

```
CAPSTONE_CFLAGS=-I/usr/local/Cellar/capstone/3.0.1/include/capstone
CAPSTONE_LDFLAGS=-L/usr/local/Cellar/capstone/3.0.1/lib -lcapstone
```

I installed capstone with brew and radare is taking it from there instead of use its own. How can I force to radare to use the one shipped with it?

**Comment by radare** [comment]
See b8dc7480fdef77758af16aadeb1a7c6b3e67ff96 . but we should fix that to support older capstone versions

**Comment by radare** [comment]
See b8dc7480fdef77758af16aadeb1a7c6b3e67ff96 . but we should fix that to support older capstone versions

**Comment by radare** [comment]
you dont need to do that CAPSTONE_CFLAGS ... just use export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by alvarofe** [comment]
The CAPSTONE_CFLAGS are written by radare2. When I type `sh sys/install.sh` it generates the config-user.mk. Inside this file there is the following.

```
USE_CAPSTONE=1
 ifeq ($(USE_CAPSTONE),1)
 CAPSTONE_CFLAGS=-I/usr/local/Cellar/capstone/3.0.1/include/capstone
 CAPSTONE_LDFLAGS=-L/usr/local/Cellar/capstone/3.0.1/lib -lcapstone
 else
 CAPSTONE_CFLAGS=
 CAPSTONE_LDFLAGS=
```

Then when the project is building the output is.

```
...

Final report:
 - PREFIX = /usr
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - USE_CAPSTONE = 1
 - VERSION = 0.9.9-git
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - DEBUGGER = 1
 - CC = gcc
 - USERCC = gcc
 - USEROSTYPE = darwin
 - LIL_ENDIAN = 1
 - LIBVERSION = 0.9.9-git

...
```

All these is generated from configure file that checks if I have installed capstone.

```bash
392 printf 'checking pkg-config flags for capstone... '
393 tmp=`pkg-config --cflags capstone 2>/dev/null`
394 if [ '!' $? = 0 ]; then echo no ; HAVE_PKGCFG_CAPSTONE=0;
395 else
396 CAPSTONE_CFLAGS=$tmp;
397 tmp=`pkg-config --libs capstone 2>/dev/null`
398 if [ $? = 0 ]; then
399 echo yes; HAVE_PKGCFG_CAPSTONE=1;
400 CAPSTONE_LDFLAGS=$tmp; fi; fi
401 if [ 11 = "$WITH_CAPSTONE$HAVE_PKGCFG_CAPSTONE" ]; then
402
403 USE_CAPSTONE="1"
404 else
405 USE_CAPSTONE="0"; fi
```

Even using `export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig` I am getting the same error. The only solution by now is commenting that line to ignore the `case X86_INS_FFREEP`. The problem of doing that is I do not know the implications that it generates.

**Comment by radare** [comment]
See the commit. you have to define the USE_R2_CAPSTONE env var before
running sys/install.sh

the fail you have having must be fixed in the code. can you send a patch
for it?

**Comment by alvarofe** [comment]
The patch would be the following unless you want a pull request or via email

```
diff --git a/libr/anal/p/anal_x86_cs.c b/libr/anal/p/anal_x86_cs.c
index 46b44b1..1be5871 100644
--- a/libr/anal/p/anal_x86_cs.c
+++ b/libr/anal/p/anal_x86_cs.c
@@ -216,7 +216,7 @@ static int analop(RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len) {
 		case X86_INS_FPREM:
 		case X86_INS_FPREM1:
 		case X86_INS_FPTAN:
-		case X86_INS_FFREEP:
+		/*case X86_INS_FFREEP:*/
 		case X86_INS_FRNDINT:
 		case X86_INS_FRSTOR:
 		case X86_INS_FNSAVE:
```

**Comment by radare** [comment]
This patch is wrong. You must check which version of capstone supports that instruction and add an #ifdef #if .. I think i have already suggested a patch few comments above

**Comment by alvarofe** [comment]
I didn't add #ifdef because in capstone the symbol `X86_INS_FFREEP` is not defined and I didn't know how to write it correctly. In the file `include/x86.h` inside capstone directory only is defined `X86_INS_FFREE`. I have been looking through all capstone versions and I couldn't find `X86_INS_FFREEP`. 

I just read that  FFREEP is not well documented and `FFREEP performs FFREE ST(i) and pop stack`. Maybe that is the reason which capstone is not defining that symbol.

```
diff --git a/libr/anal/p/anal_x86_cs.c b/libr/anal/p/anal_x86_cs.c
index 46b44b1..9a5ea0f 100644
--- a/libr/anal/p/anal_x86_cs.c
+++ b/libr/anal/p/anal_x86_cs.c
@@ -216,7 +216,9 @@ static int analop(RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len) {
                case X86_INS_FPREM:
                case X86_INS_FPREM1:
                case X86_INS_FPTAN:
-               case X86_INS_FFREEP:
+#if CS_API_MAJOR < 2
+    case X86_INS_FFREEP:
+#endif
                case X86_INS_FRNDINT:
                case X86_INS_FRSTOR:
                case X86_INS_FNSAVE:
```

**Comment by radare** [comment]
Iirc the patch would be >2 or >3. This instruction is available for capstone in git. Didnt checked if last release from today contains that instruction. I have already asked the author for the way to solve those conflicts

**Comment by alvarofe** [comment]
I made `git clone https://github.com/aquynh/capstone` and looked for different tags then using ACK I couldn't find that instruction nor in the last release 3.0.2. I wrote < 2 just in case it would be valid for some old version and I was not able to see it.

The `case X86_INS_FFREEP` was introduce in the commit [`7bda81d`](https://github.com/radare/radare2/commit/7bda81d6d004dab6e41fc77d6122c506ede887fd)

**Comment by aquynh** [comment]
This undocumented instruction is only available in the `next` branch of Capstone (together with around 50 new instructions, compared to version *3.0.2*). 

Apparently radare is now using the `next` branch of Capstone, so be sure to install the right code.

Thanks.

**Comment by alvarofe** [comment]
Thanks @aquynh I didn't know about that next branch. It's true that @radare was commenting in the code to review all the file when capstone 4 was released.

For those that are using the stable release or the latest in this case 3.0.2 instead of `next` branch the patch would be this.
```
diff --git a/libr/anal/p/anal_x86_cs.c b/libr/anal/p/anal_x86_cs.c
index 46b44b1..86ab41b 100644
--- a/libr/anal/p/anal_x86_cs.c
+++ b/libr/anal/p/anal_x86_cs.c
@@ -216,7 +216,9 @@ static int analop(RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len) {
                case X86_INS_FPREM:
                case X86_INS_FPREM1:
                case X86_INS_FPTAN:
-               case X86_INS_FFREEP:
+#if CS_API_MAJOR > 3
+    case X86_INS_FFREEP:
+#endif
                case X86_INS_FRNDINT:
                case X86_INS_FRSTOR:
                case X86_INS_FNSAVE:
```

Although I think that it would be better from the beginning install radare2 using its own capstone. So instead of use `export USE_R2_CAPSTONE=1`. Do it by default and those that want use more stable version say it explicitly since many as me install everything with `brew` and maybe is not synced with radare2. But this is my humble opinion.


Thanks for the quick replies and to be patient @radare

**Comment by radare** [comment]
Fixed in master
