### ISSUE TITLE
$ in esil

### ISSUE THREAD

**Issue by condret** [radare/radare2#2181]
we need to rename the `$-cb` in esil, it should handle interrupts, so don't call it `esil_syscall`. Futher we need another sdb-instance in the esil-struct, to store our own interruptvectors

**Comment by radare** [comment]
Why u dont like esil_syscall ? I wanted to let this stuff be defined in a separate callback in the anal plug because that is arch/os specific.

I would prefer not to force the use of sdb here, also, i dont get what do you mean with $-cb

**Comment by condret** [comment]
int 0x80 is an interrerupt in the first place, not a syscall. and thats how the esilstring in x86_cs looks like. ````128,$```` so i think we should call it interrupt and not syscall

**Comment by radare** [comment]
Well.. Its just renaming syscall as interrupt. Right?

**Comment by condret** [comment]
yes

**Comment by radare** [comment]
go for it
