### ISSUE TITLE
r2: symbol lookup error: r2: undefined symbol: r_sys_set_environ

### ISSUE THREAD

**Issue by msftsecurityteam** [radare/radare2#2182]
Hi, I can't seem to get r2 to work on 32 bit systems. 

I tried the following commands:

$ sudo make purge
$ git clean -xdf
$ ./configure
$ make 
$ sudo make install
$ r2
r2: symbol lookup error: r2: undefined symbol: r_sys_set_environ
$

**Comment by msftsecurityteam** [comment]
I had a conflicting package installed from my package manager.  Uninstalledand it works fine.  Closing issue now

**Comment by radare** [comment]
This is because we are not enforcing rpath by default. Debian does, so if u install r2 in usr/local it will try to find the libraries first in /usr

**Comment by mossberg** [comment]
For anyone in the future that runs into this problem, I was able to use `apt-get remove radare2` and also `dpkg --purge` -ing any output from `dpkg -l | grep radare` to fix this. (help from @crowell)

**Comment by mmkhitaryan** [comment]
Also `sudo apt remove "*radare*" ` is ok
