### ISSUE TITLE
List local/args in proper order

### ISSUE THREAD

**Issue by radare** [radare/radare2#2188]
Alphabetically sort them.

First list args, and then locals

Probably needs to implement `sdb_array_sort()` in [sdb]( https://github.com/radare/sdb ).

**Comment by alvarofe** [comment]
What does mean this issue?

The local/args that the issue refers are those that belong to a function as the example below and saved in the database alphabetically? If that is, I will try to close the issue. It was only to be sure ;)

```
[0x00002430]> pdf@sym._ssl2_read
╒ (fcn) sym._ssl2_read 1072
│           ; var int local_10_4   @ rbp-0x54
│           ; var int local_12     @ rbp-0x60
│           ; var int local_6      @ rbp-0x30
│           ; var int local_10     @ rbp-0x50
│           ; var int local_0      @ rbp-0x0
```

**Comment by radare** [comment]
yep that is. arguments should be listed first and symbols later, and both should be sorted by delta.

**Comment by alvarofe** [comment]
I'll keep you updated @radare
