### ISSUE TITLE
Add `pf` support to local vars/args

### ISSUE THREAD

**Issue by radare** [radare/radare2#2189]
This can be configured with `avt` to define the variable type. The type name must be resolved from the `t` command, which can registered structs from .h files or we can use `pf.` aliases.

The `t` comand only supports global vars/structs .so this issue aims to exend the support to local/in-function variables.

**Comment by Hyask** [comment]
Could you give a concrete example to show how it should work?

**Comment by jvoisin** [comment]
Sure:

![concrete]( http://texturezine.com/wp-content/uploads/2012/11/IMG_9194.jpg )

This is an example of concret.

**Comment by radare** [comment]
same for return values

**Comment by XVilka** [comment]
@oddcoder see this one. Looks like it is already done, or am I wrong?

**Comment by oddcoder** [comment]
it is done with different command 
local arg and var has its own set of commands
