### ISSUE TITLE
Add ESIL 2 REIL translation support

### ISSUE THREAD

**Issue by radare** [radare/radare2#2190]
The only benefit of reil is that there are other people using it and there are tools available. Converting esil to reil is quite easy, but we should define the way for others to interact with our reil output.

See https://github.com/Cr4sh/openreil

**Comment by radare** [comment]
Note that REIL have signed SMUL, SDIV and SMOD. We should probably extend esil with those operations. This needs some discussion.

**Comment by XVilka** [comment]
Fixed, with minor issues.
