### ISSUE TITLE
r_buf_cpy() with sparse buffers returns 0 (should be len)

### ISSUE THREAD

**Issue by fenugrec** [radare/radare2#2200]
Please see commit https://github.com/fenugrec/radare2/commit/20f6c06906d18e6bd5b7bd6c5b0b409774ec463a for a fix. It also adds some error checking, and fixes a possible segfault

**Comment by radare** [comment]
https://github.com/radare/radare2/pull/2201 <-- is this what you wanted to do?

**Comment by fenugrec** [comment]
Fixed in https://github.com/radare/radare2/commit/752435bf1b7b8143799a897f532f254a67718087

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://izlift.com.tr/newly.php?q>

 

lukas-runas@gmx.de
