### ISSUE TITLE
Rename `ac` to `aac` ?

### ISSUE THREAD

**Issue by radare** [radare/radare2#2203]
Maybe it takes more sense to contain `analyze calls` under `analyze all calls`

Please discsus and point affected code

**Comment by jvoisin** [comment]
The `a` (and `aa`) commands needs to be a bit cleaned up in my opinion.

What about putting *bulk* analysis command under `aa` and *targeted* ones under `a`?

**Comment by radare** [comment]
yep. this makes sense, so ac -> aac change is ok for all you?

**Comment by condret** [comment]
its ok, it does not hurt me

**Comment by radare** [comment]
solved.
