### ISSUE TITLE
add nice(2) support to rarun2

### ISSUE THREAD

**Issue by radare** [radare/radare2#2207]
Define process priority (single syscall on unix, some w32 apis for windows)

**Comment by Jambato** [comment]
Looking at [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686277%28v=vs.85%29.aspx). Is it okay for a potential niceness field in RRunProfile to contain either priority for UNIX and Windows?

**Comment by radare** [comment]
Yes
