### ISSUE TITLE
pi-x and pij-x not working properly

### ISSUE THREAD

**Issue by radare** [radare/radare2#2223]
Try `r2 -c 'pij -1' -` or see http://pastie.org/10045419

/via @Maijin

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/47dd3ba0cee47694380c5c3e0f6a72249a49e521/t/cmd_pi#L64

**Comment by Maijin** [comment]
@radare error message changed a bit:
    error reading at 0xfffffffffffffeff
    []

**Comment by radare** [comment]
Yeah this crap as well as the other are there because its using mdisasm() which is not the way to go. The whole code needs to be rewritten . I just pushed a working version based on the latest code. Which more or less works. But its definitvely needed to be fixed

**Comment by radare** [comment]
@crowell ?

**Comment by Maijin** [comment]
@radare error message again changed:

    []

**Comment by radare** [comment]
@crowell ?

**Comment by radare** [comment]
Cant reproduce

**Comment by Maijin** [comment]
Still reproducible

**Comment by Maijin** [comment]
Ok now it's not error but still not working see the current test:

https://travis-ci.org/radare/radare2/jobs/64087315#L376-L390

**Comment by radare** [comment]
you see it you fix it

**Comment by radare** [comment]
ping @crowell

**Comment by radare** [comment]
This is important for the webui.

**Comment by radare** [comment]
can someone confirm, re-test, check this with master?

**Comment by Maijin** [comment]
Not fixed

![image](https://cloud.githubusercontent.com/assets/1408600/19774605/fb335926-9c6d-11e6-8777-ea1058837836.png)


Otherwise I would have closed it

**Comment by radare** [comment]
well, pi -3 is also broken anyway :P

**Comment by radare** [comment]
so imho this is dupe of https://github.com/radare/radare2/issues/2400

**Comment by m1ghtym0** [comment]
Should be closed by ba3ed8f7f6fc9aee04cc0d9f0872f1666f8803fb

**Comment by Maijin** [comment]
You fixed the test?

**Comment by m1ghtym0** [comment]
@Maijin yes: f0a208463845012210884111e98a14398f979a62

**Comment by Maijin** [comment]
Close issues then ;)

**Comment by m1ghtym0** [comment]
Can't close myself;-)

**Comment by Maijin** [comment]
ah ok, well next time in commit, use "Fix #XXXX" so when it gets merged it is closed automatically.

**Comment by m1ghtym0** [comment]
Yes, was a duplicate issue and while I mentioned the other one, I forgot this one:D

**Comment by Maijin** [comment]
Check the other issues I mentionned you and tell if we can close #2402 #2401
