### ISSUE TITLE
radare2 + openreil (Reverse Engineering Intermediate Language)

### ISSUE THREAD

**Issue by ret5et** [radare/radare2#2225]
subj
[openRIEL](https://github.com/Cr4sh/openreil)
```
Open source library that implements translator and tools for REIL (Reverse Engineering Intermediate Language) 
```

**Comment by radare** [comment]
it's already planned and it's part of the RSoC/GSoC of this year. in fact there's already a task to do esil->reil translation, which should be a one-night thing. and there's already an issue for that (not openreil-specific, but generalistic reil).
