### ISSUE TITLE
feature-request: dsuo

### ISSUE THREAD

**Issue by condret** [radare/radare2#2227]
dsuo: debugger step until optype
example: `dsuo ucall`
example: `dsuo ucall|ujmp`

**Comment by radare** [comment]
also dsu? help and most of other esil related commands help message are
confusing, unexistent or wrong.

**Comment by MaskRay** [comment]
I think this is fixed.
`dsui`

**Comment by Maijin** [comment]
@MaskRay nop dsui is for a specific instruction != optype see /A for example
