### ISSUE TITLE
frequent ERR_CONTENT_LENGTH_MISMATCH in chrome

### ISSUE THREAD

**Issue by allanlw** [radare/radare2#2232]
With a fresh install of radare2 (from revision f4e3f593d4893e2b96c8d41d9e54c7b11fa4bac0), I am frequently encountering ERR_CONTENT_LENGTH_MISMATCH when loading files from `/p/lib/js/` in Chrome. In firefox I have a similar problem, and can only get the /p/ frontend to load by refreshing a few times (and even then various files have javascript errors). I believe this is an issue with the http server built into radare.

**Comment by radare** [comment]
Any specific file from there? Maybe its related to the way newlines are encoded? Can you verify which size is expected and which one is shown?

Thanks

**Comment by radare** [comment]
cant reproduce

**Comment by Maijin** [comment]
No file, No asciinema, no debug log provided for reproducing. -> Closing
