### ISSUE TITLE
Some commands only work when passed as -c

### ISSUE THREAD

**Issue by allanlw** [radare/radare2#2233]
I've been playing around with the radare web interface, and have found that the `H` command (which seems to start the web interface) is not available from inside the REPL. Perhaps this is a documentation issue, or the `r2 -h` entry for `-c` should not say `execute radare command`.

Example session:

	allan@allanwirth:~/deskpins$ r2 DeskPins.exe
	 -- Execute a command on the visual prompt with cmd.vprompt
	[0x00425b40]> H
	|ERROR| Invalid command 'H' (0x48)
	^D
	allan@allanwirth:~/deskpins$ r2 -c=H DeskPins.exe
	Starting http server...
	open http://localhost:9090/
	r2 -C http://localhost:9090/cmd/
	Couldnt get a file descriptor referring to the console
	Could not get a file descriptor referring to the console
	^C -- Use +,-,*,/ to change the size of the block
	^D
	allan@allanwirth:~/deskpins$

**Comment by radare** [comment]
The command to start the web interface is `=H`.

the `-c` command takes the argument `=H`, the equal sign is not a separator.
