### ISSUE TITLE
aa0 broken by a commit

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2235]
Radare2-Regressions-format-elf shows a regression coming from e1edc18a688a47c02b0a346b4cab276778e46430 @alvarofe
http://ci.rada.re/view/File%20Formats/job/radare2-regressions-formats-elf/2142/console

[XX]  5  helloworld-gcc-elf: flags spaces after analysis

**Comment by radare** [comment]
It would be helpful to see the fail log in the jenkins output when a test is not passing.

**Comment by Maijin** [comment]
http://pastie.org/10049457

**Comment by radare** [comment]
aa0 was deprecated a while ago, not @alvarofe's fault. i just fixed the test. thanks for noticing

**Comment by Maijin** [comment]
oki

**Comment by alvarofe** [comment]
Sorry for the drawback, but before to make the PR  I ran the test script and I was getting the same output as with the master branch so I assumed that I didn't broke nothing.
