### ISSUE TITLE
Add so- command

### ISSUE THREAD

**Issue by hteso** [radare/radare2#2238]
Would be useful to have a new command "so-" to seek backwards N number of opcodes. Same as "so" command, but backwards.

**Comment by XVilka** [comment]
Just adding '-N' syntax support for the 'so', like it is done for 'px' or 'pd' e.g.

**Comment by hteso** [comment]
Yep, that would work too and keep the same "style" as with the other commands.

**Comment by crowell** [comment]
Don't we have something that does this? I remember implementing it

**Comment by hteso** [comment]
Actually I just checked and `so -1` seems to work :)

I would just change the `s?` command to reflect on the help.

**Comment by hteso** [comment]
After double checking, either the `so -N` or the `pd N` commands don't work properly.

If I do `so -100` and then `pd 100` I should get all the disassembly right until the point I was before the `so -100` (let's say entry0), but I'm afraid on my tests that doesn't work.

**Comment by radare** [comment]
Backward disasm is not an exact science

**Comment by radare** [comment]
Also, we need to add help for `so?`

**Comment by crowell** [comment]
@hteso on variable width instructions, it's not going to be perfect. (x86, amd64, etc.)
if you're on an arch with fixed width instructions, like MIPS, this should work as you're describing.

**Comment by radare** [comment]
To seek between functions. Which was your innitial question in priv, use sn and sp in conjuntion to e scr.nkey

**Comment by crowell** [comment]
this should be closed, the functionality exists already.
