### ISSUE TITLE
e asm.describe for sparc

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#2240]
asm describe for sparc is not yet done. Is this a good RSoc task?

**Comment by jvoisin** [comment]
Likely too easy in my opinion.

**Comment by XVilka** [comment]
I'd say it is RWoC at max (Radare Week of Code).

**Comment by radare** [comment]
Sparc support on capstone is pretty weak compared to gnu. Sparc needs some love... And we will need some hardware to play with.

**Comment by crowell** [comment]
ultrasparc are pretty cheap ;-)
http://www.ebay.com/itm/Sun-Microsystems-Sunfire-V240-Server-2-x-Sun-Ultrasparc-IIIi-3-40-Ghz-w-8-GB-RAM-/131459523783?pt=LH_DefaultDomain_0&hash=item1e9b9924c7

On Tue, Mar 24, 2015 at 6:32 PM, radare <notifications@github.com> wrote:

> Sparc support on capstone is pretty weak compared to gnu. Sparc needs some
> love... And we will need some hardware to play with.
>
>
>
> > On 24 Mar 2015, at 23:06, Anton Kochkov <notifications@github.com>
> wrote:
> >
> > I'd say it is RWoC at max (Radare Week of Code).
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2240#issuecomment-85719986>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by Maijin** [comment]
Done https://github.com/radare/radare2/commit/eb56f6d424d8e64bcaa19b5406b573dd916e05d4
