### ISSUE TITLE
Command to Print/Dump ASCII graph (like in VVV)

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2251]
Possibility to print the ascii graph,  for example to create text graph with ascii file in it :full_moon_with_face:

**Comment by ret2libc** [comment]
Please check if 'agf'('afg') done in e20b36095b131e8e30f3a161a0039848b33f8a11 are what you want.

**Comment by Maijin** [comment]
@ret2libc awesome, now it just need an auto-layout to avoid having the graph branch overlapping and that'll be perfect :dancers:  Thanks :+1: 

See that @jvoisin
