### ISSUE TITLE
cmd_pd_bytes: pD -10 @ 10 RegressionS

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2253]
[XX]  1  cmd_pd_bytes: pD -10 @ 10                   

Command:  /usr/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_pd_bytes-rad.KAFT82   malloc://512 > /tmp/r2-regressions//cmd_pd_bytes-out.amytHE 2> /tmp/r2-regressions//cmd_pd_bytes-err.oS4lrW
File: malloc://512
Script: e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pD -10 @ 0xa

Diff: --- /tmp/r2-regressions//cmd_pd_bytes-exp.zKIK5Z	2015-03-27 16:11:09.522361275 +0100
+++ /tmp/r2-regressions//cmd_pd_bytes-out.amytHE	2015-03-27 16:11:09.522361275 +0100
@@ -1,3 +0,0 @@
-           0x00000000    b801000000   mov eax, 1
-           0x00000005    4839ca       cmp rdx, rcx
-           0x00000008    7f00         jg 0xa

[XX]  2  cmd_pd_bytes: pD -10 @ 0                    

Command:  /usr/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_pd_bytes-rad.HDpGhp   malloc://512 > /tmp/r2-regressions//cmd_pd_bytes-out.AoqTDK 2> /tmp/r2-regressions//cmd_pd_bytes-err.VOZIGZ
File: malloc://512
Script: e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pD -10 @ 10

Diff: --- /tmp/r2-regressions//cmd_pd_bytes-exp.bLiIgm	2015-03-27 16:11:09.546361276 +0100
+++ /tmp/r2-regressions//cmd_pd_bytes-out.AoqTDK	2015-03-27 16:11:09.546361276 +0100
@@ -1,3 +0,0 @@
-           0x00000000    b801000000   mov eax, 1
-           0x00000005    4839ca       cmp rdx, rcx
-           0x00000008    7f00         jg 0xa

**Comment by crowell** [comment]
blame the pancake
