### ISSUE TITLE
pd -x is always broken

### ISSUE THREAD

**Issue by radare** [radare/radare2#2254]
latest fixes introduced way more severe bugs. 

r2 -c 'pd -10' /bin/ls   # infinite loop

bug again

"wx b8010000004839ca7f00 ; pD -10 @ 0xa" regression

**Comment by Maijin** [comment]
Duplicate https://github.com/radare/radare2/issues/2253

**Comment by radare** [comment]
this issue if fixed now, but pd -x shows sometimes undefined instructions, it must be reworked, but at least its working, closing for now
