### ISSUE TITLE
Cannot assemle arm code. capstone can just do disassemle but not assemble.

### ISSUE THREAD

**Issue by rexdf** [radare/radare2#2257]
```bash
$rasm2 -a arm "mov pc, lr"
Cannot assemble 'mov pc, lr' at line 3

$rasm2.exe -a arm -d "0ef0a0e1"
mov pc, lr
```

**Comment by radare** [comment]
We have our own arm assembler. And it is able to assemble a 'mov pc,lr' are you using r2 from git?

**Comment by rexdf** [comment]
@AntonDevil 

```bash
make[1]: Leaving directory `/home/user/radare2/shlr/zip'
make -C libr/util
make[1]: Entering directory `/home/user/radare2/libr/util'
gcc -c  -MD    -g -Wall -DMINGW32=1 -I/home/user/radare2/libr/../shlr/zip/include -I/ho/home/user/radare2/libr/include -DGIT_TAP=\"0.9.8-1089-gade2945\" -o mem.o mem.c
mem.c:3:20: fatal error: r_util.h: No such file or directory
 #include <r_util.h>
                    ^
compilation terminated.
/home/user/radare2/libr/../global.mk:46: recipe for target `mem.o' failed
make[1]: *** [mem.o] Error 1
make[1]: Leaving directory `/home/user/radare2/libr/util'
Makefile:28: recipe for target `all' failed
make: *** [all] Error 2
```


Why is it -I/ho/home/user/radare2/libr/include?

**Comment by AntonDevil** [comment]
@rexdf
Faced similar problem on mingw. Mb your make.exe abspath function working incorrect, check it and change make.exe if so. This problem is not related to me btw :-)

**Comment by radare** [comment]
I dont even understand why are u building as mingw with vanila gcc, the include path seems wrongly generated by sed or something. How are you building this?

**Comment by radare** [comment]
So its totally unrelated issue to the assembler. Are you builing natively on windows here? If so, feel free to fill a separate issue

**Comment by rexdf** [comment]
Thx, It works. I upgrade make-3.8 to make-4.1 by building from make-4.1 source code.

**Comment by rexdf** [comment]
[radare2-w32-0.9.9-git.zip](http://www.radare.org/get/pkg/radare2-w32-0.9.9-git.zip) cannot do assemble arm code. 
That is why I build it from source code.

And there is some difference from `rasm2 -L`

```bash
radare2-w32-0.9.9-git.zip
_dA_  16 32      arc         GPL3    Argonaut RISC Core
_dAe  16 32 64   arm         BSD     Capstone ARM disassembler
adA_  16 32 64   arm.gnu     GPL3    Acorn RISC Machine CPU
_d__  16 32      arm.winedbg LGPL2   WineDBG's ARM disassembler
```

    $rasm2 -a arm.gnu "mov pc, lr"
    Cannot assemble 'mov pc, lr' at line 3
    invalid

But,building from git has no `arm.gnu` choice and it says adAe to Capstone ARM disassembler.

That is why my title writes before.

**Comment by radare** [comment]
$ rasm2 -L| grep arm
adAe  16 32 64   arm         BSD     Capstone ARM disassembler
_dA_  16 32 64   arm.gnu     GPL3    Acorn RISC Machine CPU
_d__  16 32      arm.winedbg LGPL2   WineDBG's ARM disassembler

$ rasm2 -a arm.gnu -b32 "mov pc, lr"
0ef0a0e1

$ rasm2 -a arm -b32 "mov pc, lr"
0ef0a0e1

when yo are using a plugin that doesnt provides assembling, r2 guesses the arch and finds another one that does it, in that case the capstone one, but this doesnt means that it is able to assemble with casptone, the assembling is done with our own arm assembler code.

**Comment by rexdf** [comment]
On My windows platform. The one from official site download windows version
```bash
$ rasm2 -L| grep arm
_dAe  16 32 64   arm         BSD     Capstone ARM disassembler
adA_  16 32 64   arm.gnu     GPL3    Acorn RISC Machine CPU
_d__  16 32      arm.winedbg LGPL2   WineDBG's ARM disassembler
$ rasm2 -a arm -b32 "mov pc, lr"
Cannot assemble 'mov pc, lr' at line 3
invalid
$rasm2 -a arm.gnu -b32 "mov pc, lr"
Cannot assemble 'mov pc, lr' at line 3
invalid
```

I've just successed in building one with cygwin after all kind of failing about `undefined reference to `WinMain@16''`.
And this need to hacking some code about `_aligned_malloc` to `malloc`. Because it is for mingw.
It works just as you describe now.

**Comment by radare** [comment]
use git or download it from the nightly builds. the stable release is behind this commit.
