### ISSUE TITLE
implement `et` to show type of config vars.

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2276]
`<xvilka___> crowell: something like 'et asm.nbytes' => 'Int'?`

**Comment by radare** [comment]
We can show this in e?? too, but et is fine for me

**Comment by Maijin** [comment]
@crowell 

Already existing: 
* `e asm.arch=?`
* `e? asm.arch`
* `e??`

Maybe adding this info of type in the first notation `e asm.arch=?` would avoid another notation again.

**Comment by radare** [comment]
Type != Value

**Comment by Maijin** [comment]
@radare yes but why not something like
e asm.arch=?
     (STRING-VALUE)
    _dA_  _8         8051        PD      8051 Intel CPU
    _dA_  _16_32     arc         GPL3    Argonaut RISC Core
e search.count=?
     (INT)

Dunno but make more sense than creating a 4th way to display this info that could be stored in `=?`

**Comment by Maijin** [comment]
Or in `e?` :stuck_out_tongue_closed_eyes:

**Comment by jjdredd** [comment]
I support @Maijin

**Comment by Maijin** [comment]
@jjdredd for which one :candy:

**Comment by radare** [comment]
The type of the value is defined by rconfig. Its implicit in the api when defining new keys.

**Comment by jjdredd** [comment]
@Maijin  https://github.com/radare/radare2/issues/2276#issuecomment-89755676

**Comment by crowell** [comment]
@jjdredd @Maijin sgtm, I'll do it that way. :+1:

**Comment by XVilka** [comment]
@crowell any news about that? So we can ask @zonkzonk to fuzz this stuff

**Comment by crowell** [comment]
this fell off my radar for a while, thanks for the ping

**Comment by Maijin** [comment]
@crowell  reping

**Comment by crowell** [comment]
I thought I did this a long time ago, maybe never pushed it... Thanks for
the ping

**Comment by jvoisin** [comment]
@crowell reping :D

**Comment by radare** [comment]
Anyone? This is pretty easy thing to do

**Comment by radare** [comment]
Also, milestone for 0.10.1

**Comment by radare** [comment]
```
[0x100001174]> et asm.slow
bool
[0x100001174]> et asm.bits
int
[0x100001174]> et asm.arch
str
[0x100001174]>
```

about to commit in 3..2. ...

**Comment by radare** [comment]
Done
