### ISSUE TITLE
ESIL command to convert a expression into a number

### ISSUE THREAD

**Issue by radare** [radare/radare2#2280]
we need a shorter way to do `eax,0,+`

**Comment by condret** [comment]
why?

**Comment by radare** [comment]
this is useful to backup/restore reg values before entering a loop, needed for REP

because ESI/EDI are not updated after the copy loop for example.

maybe we can fix that adding a DUP command for esil. what do you think?

**Comment by condret** [comment]
looks like a customop for me

**Comment by radare** [comment]
Yup, the question is, do we need it/want it enough?

**Comment by condret** [comment]
done
