### ISSUE TITLE
Implement temporary asm.arch in @a:

### ISSUE THREAD

**Issue by radare** [radare/radare2#2281]
This may be useful to simplify the pad, pd, ..

```
pd 10 @a:arm,16
pad 909090 90 9032 09 23 23 @a:mips,32
pd 20 @a:sparc @0xA3400
...
```

**Comment by jjdredd** [comment]
this is already done (but imho not documented). do you want to change the format of input for these commands?

https://github.com/radare/radare2/blob/master/libr/core/cmd_print.c#L122
https://github.com/radare/radare2/blob/master/libr/core/cmd_print.c#L212

**Comment by radare** [comment]
yes. i have never been happy about that because it was limiting the hexpair string input, forcing you to not paste any single space between the hex pairs..

**Comment by radare** [comment]
i bet there'r some tests.. or there should be some for all those syntaxes

**Comment by radare** [comment]
what about for 0.9.9? anyone? discuss

**Comment by radare** [comment]
Should be fixed now
