### ISSUE TITLE
[X86][SSE] wrong value in xmmX registers

### ISSUE THREAD

**Issue by n0way0ut** [radare/radare2#2284]
[0x7f7fe8d19210]> db 0x00401396
[0x7f7fe8d19210]> dc
username:
12345678
serial number:
4444
hit breakpoint at: 401396
r_debug_select: 20071 1
[0x00401396]> dr? xmm1
---- x86-64 ----
 cwd = 0x1a28  ; control   swd = 0xa78b  ; status
ftw = 0x7f68              fop = 0x0000
rip = 0x00007f68a86a6921  rdp = 0x0000000002455c50
size = 0x00000200
xmm0 = 00000000 00000000 a88df6e0 00007f68   st0 =1.88e-316 (0x0000000002455c50) | 0.000 (02455c50)  | 0.000 (00000000)
xmm1 = 0230d6a0 00000000 000000d8 00000000   st1 =1.88e-316 (0x0000000002456ee0) | 0.000 (02456ee0)  | 0.000 (00000000)
[0x00401396]> ?v 4444
0x115c
[0x00401396]> pd 5 @ 0x00401390
       ,=< 0x00401390    7a24         jp 0x4013b6
       |   0x00401392    660f2ec1     ucomisd xmm0, xmm1
      ,   ;-- rip:
      ,==< 0x00401396 b  751e         jne 0x4013b6
          |  0x00401398    beea154000   mov esi, str.s_n_OK_             ; "s/n OK!" @ 0x4015ea

I expect 4444 in xmm1.
the binary is this http://crackmes.de/users/adamziaja/crackme1/

**Comment by condret** [comment]
````dr xmm1h```` or ````dr xmm1l```` ?

**Comment by n0way0ut** [comment]
this is the gdb output:
$3 = {
  v4_float = {0, 5,54248047, 0, 0}, 
  v2_double = {4444, 0}, 
  v16_int8 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x5c, 0xb1, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
  v8_int16 = {0x0, 0x0, 0x5c00, 0x40b1, 0x0, 0x0, 0x0, 0x0}, 
  v4_int32 = {0x0, 0x40b15c00, 0x0, 0x0}, 
  v2_int64 = {0x40b15c0000000000, 0x0}, 
  uint128 = 0x000000000000000040b15c0000000000
}

this from r2:
xmm0h = 0x00000000
xmm0l = 0x00000000
xmm1h = 0x00000000
xmm1l = 0x00000000

**Comment by n0way0ut** [comment]
did you change something?
with the today pull I see:

xmm0h = 0x41879b1c00000000
xmm0l = 0xff000000
xmm1h = 0x40b15c0000000000
xmm1l = 0x00000000

not yet the right value maybe:
4444 -> 0x115c

**Comment by radare** [comment]
This is correct output. 
```
(ut64)0x40b15c0000000000 = (double)4444
```
I have added the double casting support to the `?` command try this:

```
[0x00000000]> ? 0x40b15c0000000000~[9]
4444.000000
```

**Comment by radare** [comment]
We need to find a simpler way to interact with rax2 conversions in r2, in order to integrate this conversion from other commands in an easy way. I'm open to suggestions, but i'm not with the idea of making `dr` display all the regs in all the possible encoding formats all the time, that's probably useful when you dont know the type, but there should be a simpler way to interact with it.

**Comment by n0way0ut** [comment]
yes, showing more possible encoding and format should be nice. ie. not only hex value, but even double, int, etc.. like "p $xmmX" in gdb
