### ISSUE TITLE
Reflect changes/detection to local variables and arguments when in graph mode (VV).

### ISSUE THREAD

**Issue by kroemeke** [radare/radare2#2285]
Hi there,

radare2 0.9.9-git 7391 @ linux-little-x86-64 git.0.9.8-1041-g917729b

When local argument / variable is renamed using afan/afvn , the change 
is reflected in Visual mode and cli, but when running a graph it refers 
the original "raw" values like 'rbp - 4' or 'rbp - 8' . It would be nice 
to have support to show it in the same format.

```
│          ;-- sym.main:
│          0x004004b6    55           push rbp
│          0x004004b7    4889e5       mov rbp, rsp
│          0x004004ba    c745fc7b000. mov dword [rbp-x], 0x7b         ; [0x7b:4]=0x400  ; '{'
│          0x004004c1    c745f805000. mov dword [rbp-y], 5
```
but in graph mode : 
```
=----------------------------=
|-[ 0x004004b6 ]-            |
| push rbp                   |
| mov rbp, rsp               |
| mov dword [rbp - 4], 0x7b  |
| mov dword [rbp - 8], 5     |
=----------------------------=
v
|
|
|
```

regards,
Marek

**Comment by radare** [comment]
graph disassembly doesnt filters expressions, local vars, symbol names, comments and instruction colors are not yet displayed in the graph view. It’s easy to add, but it may result in some visual glitches, this is why its disabled right now.

thanks for noticing, will keep this issue to track that feature.

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/3661

**Comment by ret2libc** [comment]
@XVilka i think we can actually close this, because now the output of the graph is taken from 'pd', not from 'pi' anymore.

**Comment by Maijin** [comment]
Yep two problems different and this one is fixed
