### ISSUE TITLE
A dedicated command to print bits and a dedicated command to write bits

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2292]
It is possible to prints bits using `pb` or `pB` but in fact it is displaying only bytes per bytes (you need to specify a byte len)
It could be great to have a dedicated command to print bits and a dedicated command to write bits.

**Comment by radare** [comment]
In swapped order?

**Comment by Maijin** [comment]
"w 1 ; p# 4" (# to be defined) should display something like 0011 by default no?

**Comment by radare** [comment]
what about moving the current `pb` into `pxb`, and making pb work like you propose?

**Comment by Maijin** [comment]
why not :+1:

**Comment by radare** [comment]
Btw, do you know about pB?

**Comment by Maijin** [comment]
@radare Yes but pB like pb is only working bytes per bytes not bit per bit :)

**Comment by radare** [comment]
So lets sumarize:

pb -> pxb : hexdump in bits
pB : pB show N*8 bits
pb : how N bits skipping M bits

pb should get two arguments, one to specify the number of bits to show and the second optional to skip N bits from the beginning.

**Comment by Maijin** [comment]
Great \o/

**Comment by Maijin** [comment]
@radare the issue was also mentionning a dedicated command for writing bits/bits but we'll see later :+1:

**Comment by radare** [comment]
Lets discuss this in a separate issue https://github.com/radare/radare2/issues/2307
