### ISSUE TITLE
pd $v / pd $s ENOMEM

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2296]
using pd $v renders system instable for me.

```
zlul@debian:~/radare2$ r2 -d /bin/ls
Process with PID 16385 started...
PID = 16385
pid = 16385 tid = 16385
r_debug_select: 16385 16385
Using BADDR 0x8048000
Asuming filepath /bin/ls
bits 32
pid = 16385 tid = 16385
[0xb7774840]> pd $s
disassemble error at offset 0
... hang ...
^Z
zlul@debian:~/radare2$ strace -vp pid
mmap2(NULL, 2097152, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap2(NULL, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = -1 ENOMEM (Cannot allocate memory)
[..]
```

will test later on 64bit

**Comment by radare** [comment]
the same issue can be reproduced with pd -1

you can add this issue to the rest of issues related to the crappy current implementation of negative pd. there are 2 or 3 issues related to the same problem already.

after a month of complaining about it, maybe its time for me to take a look at the code and fix it. .. again

**Comment by zonkzonk** [comment]
ok closing as dup.
