### ISSUE TITLE
px -x is broken too

### ISSUE THREAD

**Issue by radare** [radare/radare2#2297]
that's what px -x should do
`px -10 == px 10 @ $$-10`

**Comment by condret** [comment]
wat

**Comment by radare** [comment]
that's what px -x should do
`px -10 == px 10 @ $$-10`

**Comment by radare** [comment]
Same for all other similar print commands (p8, pr, ...)

**Comment by condret** [comment]
muähhh, that code is a mess, i don't get where to start

**Comment by radare** [comment]
Im aware of this. And thats probably the main reason why this got broken. 

I know this code became a mess and probabky because the syntax of r2 evolved during the time instead of having a strict design from the beginning. And im aware that im the only one who knows/understands all those syntax tricks.. But as long as there are no tests for this, we should fix it, write tests and then some day later refactor it.

If you are scared i can fix it quickly probably. I just wanted a reminder because i was surprised this was not working anymore.

**Comment by Maijin** [comment]
@radare tests like these https://github.com/radare/radare2-regressions/commit/ed7a90c805dbe5ac2bec570e1c4b22281279a0dd ?

**Comment by radare** [comment]
Yep :)
