### ISSUE TITLE
radiff2 Memory Usage

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#2300]
radiff2 uses too much memory on even moderate sized files. It asks for GBs worth until it crashes. It seems like there should be a better way...

**Comment by zonkzonk** [comment]
can you tell us which architecture ?

**Comment by ninjahacker** [comment]
Yes, sorry. It is 32-bit ARM, but the files are off of Android. I hadn't considered maybe that also will make a difference. I'm new to github. Is there a way to attach files to an Issue tracker issue?

**Comment by radare** [comment]
can you provide a test case or tell us which flags are you using, so we can improve that?

**Comment by radare** [comment]
you can upload the files to any imageupload service (changing the extension of the file), or base64/uuencode and pastebin, or just use dropbox or your own server.

**Comment by ninjahacker** [comment]
Thanks! I wasn't sure. 
https://www.dropbox.com/s/2gqbqddjncgw6zp/libart.so?dl=0
You can just make two identical copies of that file and use either -s or -C, and it will use a significant amount of memory. My computer will automatically kill it with -s, and the -C freezes up the computer. I'm using Linux with the latest stable release. I haven't tried the what's in git currently.

**Comment by zonkzonk** [comment]
morn, can't reproduce on X86 32bit debian. Will test with 64bit.

**Comment by radare** [comment]
There are about 2000 commits since last release, i would recommend you to always try the code in git before reporting an issue.

There are some bindiff related issues, so im not saying this is fixed. Im currently afk, but will review asap

**Comment by radare** [comment]
I's normal that it takes lot of memory, it works for me, maybe debian defines some hard memory ulimits.
