### ISSUE TITLE
Timestamp extracted are local time dependant causing CI to fail

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2302]
https://travis-ci.org/radare/radare2/jobs/57022075

    [  ]  22  cmd_pf: PE test                       [XX]
    Command:  /usr/local/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_pf-rad.hKx53G  -nn ../bins/pe/ch22.exe > /tmp/r2-regressions//cmd_pf-out.3G3Tqd 2> /tmp/r2-regressions//cmd_pf-err.P7oXS8
    File: ../bins/pe/ch22.exe
    Script: e asm.bits=32
    s 0x80
    pf.pe_nt_image_headers32
    Diff: --- /tmp/r2-regressions//cmd_pf-exp.Hq6hPy	2015-04-03 11:43:36.618076289 +0000
    +++ /tmp/r2-regressions//cmd_pf-out.3G3Tqd	2015-04-03 11:43:36.647075025 +0000
    @@ -3,7 +3,7 @@
               struct<pe_image_file_header>
                                       machine : 0x00000084 =  machine (enum) = 0x14c ; IMAGE_FILE_MACHINE_I386
                              numberOfSections : 0x00000086 = 0x0004
    -                            timeDateStamp : 0x00000088 = Thu Sep 11 20:21:46 2014
    +                            timeDateStamp : 0x00000088 = Thu Sep 11 18:21:46 2014
                          pointerToSymbolTable : 0x0000008c = 0x00000000
                               numberOfSymbols : 0x00000090 = 0x00000000
                          sizeOfOptionalHeader : 0x00000094 = 0x00e0
    

    [  ]  6  cmd_pf: timestamp                     [XX]
    Command:  /usr/local/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_pf-rad.oqOePe   malloc://1024 > /tmp/r2-regressions//cmd_pf-out.oyuGVc 2> /tmp/r2-regressions//cmd_pf-err.BmI5G2
    File: malloc://1024
    Script: wx 321ED92D90DF5254
    pf tt troll plop
    Diff: --- /tmp/r2-regressions//cmd_pf-exp.x8z3vB	2015-04-03 11:43:36.224093476 +0000
    +++ /tmp/r2-regressions//cmd_pf-out.oyuGVc	2015-04-03 11:43:36.238092864 +0000
    @@ -1,2 +1,2 @@
    -troll : 0x00000000 = Tue May 17 21:42:42 1994
    - plop : 0x00000004 = Fri Oct 31 02:02:08 2014
    +troll : 0x00000000 = Tue May 17 19:42:42 1994
    + plop : 0x00000004 = Fri Oct 31 01:02:08 2014

**Comment by Maijin** [comment]
This is the output of exiftool for the first binary with exiftool
Time Stamp                      : 2014:09:11 20:21:46+02:00

**Comment by radare** [comment]
Exitfool!

Theres an issue to support timezones. It should be easy/quick to do. If u
feel brave ;)

**Comment by XVilka** [comment]
Related to https://github.com/radare/radare2/issues/921

**Comment by Maijin** [comment]
@XVilka not only ;)

**Comment by radare** [comment]
Hint : http://stackoverflow.com/questions/13804095/get-the-time-zone-gmt-offset-in-c

**Comment by Maijin** [comment]
I've added BROKEN=1 on the tests to allow TravisCI to run

**Comment by condret** [comment]
cool bug

**Comment by radare** [comment]
We should have our time formatter, system one always fuckups with the
timezone and most of the apis are not portable. It shouldnt be hard to copy
that code from any bsd.

**Comment by Hyask** [comment]
Is this fixed?

**Comment by Maijin** [comment]
@Hyask yes

**Comment by Hyask** [comment]
nice! :)
