### ISSUE TITLE
pdj segfault

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2310]
To reproduce:
    r2 /bin/ls
    http://localhost:9090/cmd/pdj%20100@0x4048bf0W45pz4p

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff3d8465d in __GI__IO_default_xsputn (f=0x7fffffffae40, data=<optimized out>, n=9) at genops.c:475
    475	genops.c: No such file or directory.
    (gdb) bt
    #0  0x00007ffff3d8465d in __GI__IO_default_xsputn (f=0x7fffffffae40, data=<optimized out>, n=9) at genops.c:475
    #1  0x00007ffff3d538cf in _IO_vfprintf_internal (s=s@entry=0x7fffffffae40, format=<optimized out>, format@entry=0x7ffff7bc1b87 "\"offset\":%lld", ap=ap@entry=0x7fffffffafc0) at vfprintf.c:1641
    #2  0x00007ffff3d801c9 in _IO_vsnprintf (string=0x7fff9e56eff3 "\"offset\":1137"<error: Cannot access memory at address 0x7fff9e56f000>, maxlen=<optimized out>, format=0x7ffff7bc1b87 "\"offset\":%lld", args=0x7fffffffafc0)
        at vsnprintf.c:119
    #3  0x00007ffff7485f7e in r_cons_printf (format=0x7ffff7bc1b87 "\"offset\":%lld") at cons.c:528
    #4  0x00007ffff7b95af2 in r_core_print_disasm_json (core=0x607640 <r>, addr=67406832, buf=0x7fffffffb5b0 '\377' <repeats 200 times>..., nb_bytes=256, nb_opcodes=100) at disasm.c:2528
    #5  0x00007ffff7b3c877 in cmd_pdj (core=0x607640 <r>, arg=0xa1c563 " 100") at cmd_print.c:77
    #6  0x00007ffff7b44204 in cmd_print (data=0x607640 <r>, input=0xa1c561 "dj 100") at cmd_print.c:1934
    #7  0x00007ffff7b7a409 in r_cmd_call (cmd=0x6aadd0, input=0xa1c560 "pdj 100") at cmd_api.c:182
    #8  0x00007ffff7b55dcb in r_core_cmd_subst_i (core=0x607640 <r>, cmd=0xa1c560 "pdj 100", colon=0x0) at cmd.c:1470
    #9  0x00007ffff7b541dd in r_core_cmd_subst (core=0x607640 <r>, cmd=0xa1c560 "pdj 100") at cmd.c:1018
    #10 0x00007ffff7b570b0 in r_core_cmd_str_pipe (core=0x607640 <r>, cmd=0xc2ddf5 "pdj 100@0x4048bf0W45pz4p") at cmd.c:1824
    #11 0x00007ffff7b76ca7 in r_core_rtr_http_run (core=0x607640 <r>, launch=72, path=0x6d45a0 "p") at rtr.c:597
    #12 0x00007ffff7b776b2 in r_core_rtr_http (core=0x607640 <r>, launch=72, path=0x669013 "/graph/") at rtr.c:748
    #13 0x00007ffff7b5150c in cmd_rap (data=0x607640 <r>, input=0x669012 " /graph/") at cmd.c:186
    #14 0x00007ffff7b7a409 in r_cmd_call (cmd=0x6aadd0, input=0x669010 "=H /graph/") at cmd_api.c:182
    #15 0x00007ffff7b55e70 in r_core_cmd_subst_i (core=0x607640 <r>, cmd=0x669010 "=H /graph/", colon=0x0) at cmd.c:1483
    #16 0x00007ffff7b541dd in r_core_cmd_subst (core=0x607640 <r>, cmd=0x669010 "=H /graph/") at cmd.c:1018
    #17 0x00007ffff7b56981 in r_core_cmd (core=0x607640 <r>, cstr=0x7ffff7bab309 "=H /graph/", log=0) at cmd.c:1674
    #18 0x00007ffff7b56fc3 in r_core_cmd0 (user=0x607640 <r>, cmd=0x7ffff7bab309 "=H /graph/") at cmd.c:1805
    #19 0x00007ffff7b3254e in cmd_anal_graph (core=0x607640 <r>, input=0x6d8ef2 "v") at cmd_anal.c:2166
    #20 0x00007ffff7b3311d in cmd_anal (data=0x607640 <r>, input=0x6d8ef1 "gv") at cmd_anal.c:2415
    #21 0x00007ffff7b7a409 in r_cmd_call (cmd=0x6aadd0, input=0x6d8ef0 "agv") at cmd_api.c:182
    #22 0x00007ffff7b55e70 in r_core_cmd_subst_i (core=0x607640 <r>, cmd=0x6d8ef0 "agv", colon=0x0) at cmd.c:1483
    #23 0x00007ffff7b541dd in r_core_cmd_subst (core=0x607640 <r>, cmd=0x6d8ef0 "agv") at cmd.c:1018
    #24 0x00007ffff7b56981 in r_core_cmd (core=0x607640 <r>, cstr=0x6d8c50 "agv", log=1) at cmd.c:1674
    #25 0x00007ffff7b13512 in r_core_prompt_exec (r=0x607640 <r>) at core.c:1076
    #26 0x0000000000405413 in main (argc=2, argv=0x7fffffffe2e8, envp=0x7fffffffe300) at radare2.c:771

**Comment by zonkzonk** [comment]
looks like #2158, there is also pdj problem.

**Comment by Maijin** [comment]
@zonkzonk it even crash when clicking on "open a file" in webUI

**Comment by zonkzonk** [comment]
yes, same thing

**Comment by Maijin** [comment]
@zonkzonk ok so I should probably close this issue ?

**Comment by zonkzonk** [comment]
@Maijin relax and let open, if fixed we can mark it as dup
