### ISSUE TITLE
Bug when highlighting colored visual panel

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2312]
Bug when highlighting colored visual panel:

http://radare.tv/a/37

**Comment by radare** [comment]
regexing with ansi is hard :P

**Comment by jjdredd** [comment]
there's a similar bug in less regex search. IMHO there's no solution for this if you're trying to search in a colorized (read 'mangled') string because it naturally differs from the original and you'll inevitably get wrong hits, especially in the case of a regex search!

**Comment by jjdredd** [comment]
If there are suggestions, I can try to implement them, but frankly idk how can this be fixed.

**Comment by jjdredd** [comment]
The first idea is to preserve the original (not colorized or highlighted) string, and store all the color/highlight info in a seperate array with indexes to the original string, colorize/highlight everything at once later. This would require a major rewrite though.

**Comment by radare** [comment]
@jjdredd status update?

**Comment by jjdredd** [comment]
searching must be done in the raw (not-colorized) string obviously. We can store it seperately or
de-colorize a colorized string we have right before searching. This way we'll get hit offsets in the raw string, so to highlight a colorized string we'll have to walk it from the beginning, skipping ascii control sequences to insert a new sequence at the right offset (as I understand). This will be O(n)
per hit (n being length of the string) worst case. This will slow down highlighting very much imho, and this doesn't look like an elegant solution, so I'm not rushing with this.

**Comment by jjdredd** [comment]
can this be closed now too?
