### ISSUE TITLE
Visual mode highlight does not support backspace.

### ISSUE THREAD

**Issue by paraxor** [radare/radare2#2313]
The highlight command (`/`) responds to delete (ascii 0x7F) but not backspace/`\b` (ascii 0x7). Most modern terminals translate the 'Backspace' key to delete. Some older terminals translate it to backspace. For compatibility reasons, both are usually supported. Perhaps we could make highlight use dietline.

**Comment by radare** [comment]
what? do you want backspace to be considered a valid char in the input instead of removing the last char?

**Comment by paraxor** [comment]
Preferably it would remove the last character. Currently, backspace is just echoed back. For example:

    highlight: acd^H^Hbcd

**Comment by radare** [comment]
Not for me. I tried on several terminals and operating systems. Can you provide more details of your setup?

**Comment by paraxor** [comment]
Apparently the function uses `fgets`, leaving any processing up to the terminal. The problem occurs with line disciplines that process delete but not backspace (most modern line disciplines behave in this manner). Also, it would be nice if highlight processed arrow keys and such. Using some sort of readline implementation for highlight would fix this.

**Comment by radare** [comment]
nope its not, its already using dietline

**Comment by radare** [comment]
can you provide arch/os/r2version?

**Comment by paraxor** [comment]
Version is:

    radare2 0.9.9-git 7535 @ linux-little-x86-64 git.0.9.8-1186-g560e983
    commit: 560e983d6a9a328aa26662a90b7b1b317edc5db8 build: 2015-04-07

**Comment by dequis** [comment]
Also, would help to mention the name of terminal which behaves like this.

**Comment by radare** [comment]
Iirc i already fixed this
