### ISSUE TITLE
Highlight does not work correctly in disassembly view.

### ISSUE THREAD

**Issue by paraxor** [radare/radare2#2314]
The visual mode highlight command (`/`) does not highlight the second/hex column of disassembly view correctly. For example, searching for `00` will highlight both `00`s in the second column of this line:

    0x00000231    0000         add byte [eax], al

But searching for `0000` will not highlight anything in that column.

See http://radare.tv/a/39 (provided by @Maijin) for a demonstration.

**Comment by radare** [comment]
This is because we apply ansi per blocks and not per char, when highlighing we dont track all ansi escape changes, so when applying the highlight ansi replacement the latest set is not restored and results in partial color loss.The conscanvas have a similar issue without highlighting

**Comment by radare** [comment]
@jjdredd can you check this issue?

**Comment by jjdredd** [comment]
I will be working on this today.

**Comment by jjdredd** [comment]
The color loss should be fixed now. As for the lack of highlighting on the second (hex) column, it's essentially the same problem as in  #2312.

**Comment by radare** [comment]
`V/37`
![screen shot 2015-05-26 at 10 28 43](https://cloud.githubusercontent.com/assets/917142/7812723/6064cac6-03b5-11e5-8679-47463bf5b2bb.png)

**Comment by jjdredd** [comment]
can this be closed now?
