### ISSUE TITLE
Individual register printing is broken

### ISSUE THREAD

**Issue by paraxor** [radare/radare2#2315]
`dr?<register>` seems to print a bunch of registers instead of the one I specified.

    $ r2 -v
    radare2 0.9.9-git 7512 @ linux-little-x86-64 git.0.9.8-1163-g679a1d2
    commit: 679a1d25315b9a8302dfa046d69021094f06c716 build: 2015-04-05

    $ r2 -d /bin/ls
    ...
    [0x7f396006bd80]> dr?rip
    ---- x86-64 ----
     cwd = 0x037f  ; control   swd = 0x0000  ; status
    ftw = 0x0000              fop = 0x0000
    rip = 0x0000000000000000  rdp = 0x0000000000000000
    mxcsr = 0x00001f80        mxcr_mask = 0x0000ffff
    size = 0x00000200
    xmm0 = 00000000 00000000 00000000 00000000   st0 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm1 = 00000000 00000000 00000000 00000000   st1 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm2 = 00000000 00000000 00000000 00000000   st2 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm3 = 00000000 00000000 00000000 00000000   st3 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm4 = 00000000 00000000 00000000 00000000   st4 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm5 = 00000000 00000000 00000000 00000000   st5 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm6 = 00000000 00000000 00000000 00000000   st6 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm7 = 00000000 00000000 00000000 00000000   st7 =0 (0x0000000000000000) | 0.000 (00000000)  | 0.000 (00000000) 
    xmm8 = 00000000 00000000 00000000 00000000   
    xmm9 = 00000000 00000000 00000000 00000000   
    xmm10 = 00000000 00000000 00000000 00000000   
    xmm11 = 00000000 00000000 00000000 00000000   
    xmm12 = 00000000 00000000 00000000 00000000   
    xmm13 = 00000000 00000000 00000000 00000000   
    xmm14 = 00000000 00000000 00000000 00000000   
    xmm15 = 00000000 00000000 00000000 00000000   
    0x00000000

**Comment by jvoisin** [comment]
What about using `~` instead of `?` btw?

**Comment by condret** [comment]
what about ````dr rip````

**Comment by radare** [comment]
Yep. Dr <reg> should be the way imho, do you want to discuss this in here?

**Comment by jvoisin** [comment]
`dr <reg>` looks good to me :)

**Comment by radare** [comment]
Now dr <foo> is to show all regs of specific type:

Dr gpr, dr fpu, etc

**Comment by jvoisin** [comment]
So what is the correct syntax to show only on register?

**Comment by radare** [comment]
dr?regname

**Comment by jvoisin** [comment]
Why not `dr~regname` instead? It would be more consistent, since `~` is usually used to *grep*, while `?` is to get help.

**Comment by radare** [comment]
You can do that, but it doesnt hurts to have a direct command to do that instead of messing with the rcons buffer to just get a number.

**Comment by jvoisin** [comment]
I really don't like `?` :/

What about:
- `drt <regtype>`
- `dr <regname`

**Comment by radare** [comment]
Yes, i was about to say this. I already had this change in mind, but i
didnt thought more on this. Will do that when i get back to the laptop in
few mins

**Comment by crowell** [comment]
I'm confused, what would `drt` be?

On Mon, Apr 6, 2015 at 3:59 PM, jvoisin <notifications@github.com> wrote:
> I really don't like ? :/
>
> What about:
>
> drt <regtype>
> dr <regname
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Jeff Crowell
https://github.com/crowell

**Comment by jvoisin** [comment]
To show the registers *type*.
