### ISSUE TITLE
Compressed Linux Kernel Support

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#2316]
radare2 currently treats a compressed Linux kernel as binary. This is particularly an issue in embedded ARM where the kernel that is being loaded onto the filesystem has no header such as ELF/MZ. There is a standard head.S that gets assembled to the same thing every time. This can effectively be used to identify that the user has loaded a Linux kernel. See below for a typical ARM zImage:

0x00000000  0000 a0e1 0000 a0e1 0000 a0e1 0000 a0e1  ................ <- typical
0x00000010  0000 a0e1 0000 a0e1 0000 a0e1 0000 a0e1  ................ <- typical
0x00000020  0300 00ea 1828 6f01 0000 0000 4834 3400  .....(o.....H44. <- 0x18286f01 MAGIC value for ARM kernel
0x00000030  0102 0304 0090 0fe1 b00d 00eb 0170 a0e1  .............p..    <- endianness flag at 0x30

Anyway, identifying is the first step, but then a lot could be done once it is identified. Setting up the environment to be asm.arch=arm and disassembling from 0 gives accurate disassembly. Endianness can be read off. Kernel start can be found. Those kinds of things. Once the ARM case is done, it could actually be expanded to other architectures in a similar way, but these may not be as common.

I'd be willing to give implementing this a shot, but it sounded like I should open a ticket as well from the chatroom conversation.

**Comment by XVilka** [comment]
Related but footing is completely different https://github.com/radare/radare2/issues/1251

**Comment by radare** [comment]
The kernel is compressed. an rbin plugin can be used to uncompress it in memory or in disk and then just provide all those missing bits of information. its easy to do, but without the time, documentation, examples it is hard for me :P this is not going to happen for 0.9.9, feel free to provide example files and documentation for it, and if you feel brave to write the rbin plugin, which is quite simple to do.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/wiki/Implementing-a-new-format
