### ISSUE TITLE
sdb in r_io

### ISSUE THREAD

**Issue by condret** [radare/radare2#2317]
i think we should replace that RList io->files with a sdb-instance, fd could be the key and a pointer to RIODesc could be the value. this could boost performance on multiple files. pls discuss, this is rio, this is dangerzone

**Comment by radare** [comment]
Yes, im with doing sdb in io, bin, flags, config, core, ... so ok for me, but we should take care of regressions and performance (and maintainance) when doing sdb we need a clear design, otherwise it can result in hard to maintain code.

**Comment by jvoisin** [comment]
![archer danger zone]( https://s3.amazonaws.com/FratMusic-Site-Images/assets/cover/1416530385-18fz1zxxbtovqjpg.jpg )

**Comment by condret** [comment]
like in siol

**Comment by radare** [comment]
hahahh. no
