### ISSUE TITLE
ELF Segfault

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#2321]
r2 segfaults on an ELF file:
http://pastebin.com/MWPMXv9d

**Comment by crowell** [comment]
cannot repro

```
♥♥♥♥♥♥♥♡♡♡ minishwoods /tmp » md5sum elf.elf 
3d4e0ebde11507397615a988028fb31d  elf.elf
♥♥♥♥♥♥♥♡♡♡ minishwoods /tmp » r2 ./elf.elf 
Warning: read (phdr)
Warning: Cannot initialize program headers
Warning: read (shdr) at 0x1014
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
 -- Wow, my cat knows radare2 hotkeys better than me!
[0x30303030]> aa
Cannot find function 'entry0' at 0x30303030
^D
♥♥♥♥♥♥♥♡♡♡ minishwoods /tmp »    
```

**Comment by ninjahacker** [comment]
Yes, it may be a matter of luck whether you actually segfault. The strings table will try to access unmmap'd memory on my system, but it could be ok on yours, depending on the layout of the program in memory. This is clearly a messed up file though!

**Comment by ninjahacker** [comment]
Oh, also after base64 -d, I get an md5sum of: 0a28c80b1f224c0a9fad6658d22b8752
