### ISSUE TITLE
program dies in esil

### ISSUE THREAD

**Issue by condret** [radare/radare2#2326]
What should happen when a program tries to die in ESIL (return from entry0 or call to exit)?
 Do we need an esil-op for this? (I could do this)

**Comment by radare** [comment]
We should have a callback for this. Its an event that will collect the return value of the program. We should be able to mark functions as *noreturn* this can be determined with esil emulation. But i would like to be able to :

- trace interrupts/syscalls like strace does
- determine functions with exit point (assert, exit, ...)

The second cna be done without esil, so lets discuss

**Comment by jvoisin** [comment]
`exit` should be implemented as a syscall.
I think that we might need an op to tell ESIL VM that it's over; this should simplify a bit the analysis.

**Comment by radare** [comment]
you can stop the execution
