### ISSUE TITLE
"^[[A", "^[[B", "^[[C" or "^[[D" on first line in V

### ISSUE THREAD

**Issue by vifino** [radare/radare2#2333]
Hey.
While maneuvering around with the arrow keys, one of "^[[A", "^[[B", "^[[C" or "^[[D" appear before the first line, shifting it around and flicker.
The 0.9.8 release did not have that problem.

Environment:
- Arch Linux
- zsh 5.0.7 (x86_64-unknown-linux-gnu)
- tmux 1.9_a
- Terminology Version: 0.8.99
- Linux 3.19.2-pf

Greetings,
vifino

**Comment by vifino** [comment]
Fixed now

**Comment by radare** [comment]
Yeah forgot to close the issue when i fixed it. Thanks for confirming the
fix :)
