### ISSUE TITLE
ragg2 man example doesn't work

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2340]
ragg2 man example doesn't work

    $ cat hi.r
       /* hello world in r_egg */
       write@syscall(4);
       exit@syscall(1);

       main@global(128) {
         .var0 = "hi!\n";
         write(1,.var0, 4);
         exit(0);
       }
       $ ragg2 -O -F hi.r
       $ ./hi
       hi!

```
*** Error in `ragg2': double free or corruption (out): 0x00007fff962a1e30 ***
```

[BT]( http://pastie.org/10081244 )
[Valgrind]( http://pastie.org/10082227 )

**Comment by Maijin** [comment]
I'll add test for those examples when fixed :hamster:

**Comment by qsantos** [comment]
This commit does fix the freeing of the stack in ragg2, but the example still does not work: the generated binary uses the stack to store a string and, for some reason, `sys_write()` does not like it. A simplified version of the non-working code:

```asm
global main
main:
    push dword 0xa216968 ; "hi!\n"
    mov rbx, 1 ; stdout
    mov rcx, rsp 
    mov rdx, 4 ; length
    mov rax, 4 ; write
    int 0x80

    xor rbx, rbx ; EXIT_SUCCESS
    mov rax, 1 ; exit
    int 0x80
```

And this is a C program showing that directly calling `sys_write()` with a pointer to the stack is not appreciated:

```c
void print(const char* str)
{
    asm(
        "mov $4, %%rdx\n"
        "mov %0, %%rcx\n"
        "mov $1, %%rbx\n"
        "mov $4, %%rax\n"
        "int $0x80\n"
        :
        : "r" (str)
    );
}
int main()
{
    unsigned int x = 0xa216968; // "hi!\n"
    const char* y = "HI!\n";
    print((const char*) &x);
    print(y);
    return 0;
}
```

```
$ gcc test_write.c
$ ./a.out
HI!
$
```

**Comment by Maijin** [comment]
Then it's not entirely fixed

**Comment by qsantos** [comment]
The title of my commit may have been misleading. It should have said "partially resolves #2340".

**Comment by Maijin** [comment]
@qsantos no worries ;)

**Comment by qsantos** [comment]
Since we cannot presume information about the heap and the stack apparently will not do, there remains the `.text` section. The following code use the call/pop trick to locate the address of the string.

```asm
DB "hi!", 10

global main
main:

    ; retrieve address of string
    ; address of string = address of main - 4
    ;                   = address of call - 4
    ;                   = address of ret  - 9
    call next
next:
    pop rcx ; here, rcx = rip
    sub rcx, 9

    mov rbx, 1 ; stdout
    mov rdx, 4 ; length
    mov rax, 4 ; write
    int 0x80

    xor rbx, rbx ; EXIT_SUCCESS
    mov rax, 1 ; exit
    int 0x80
```

Obviously, this does not let us modify the string during execution so I doubt this is an acceptable solution.

**Comment by qsantos** [comment]
The explanation is actually simple: the syscall numbers are different on [Linux 32 bits](http://docs.cs.up.ac.za/programming/asm/derick_tut/syscalls.html) and [Linux 64 bits](https://filippo.io/linux-syscall-table/)). The example from `man` should therefore be correct to the following on amd64:

```c
write@syscall(1);
exit@syscall(60);

main@global(128) {
    .var0 = "hi!\n";
    write(1,.var0, 4); 
    exit(0);
}
```
