### ISSUE TITLE
Implement `aor` command to show REIL of an instruction

### ISSUE THREAD

**Issue by radare** [radare/radare2#2345]
`aoe` shuold display the esil . Currently it shows a TODO message which must be removed and replaced for this functionality. Help message must be updated

**Comment by sushant94** [comment]
So, if I understand this right, `aoe` should display the ESIL of the instruction and `aor` should display its corresponding REIL. Am I right?

**Comment by crowell** [comment]
@sushant94 correct

**Comment by radare** [comment]
Yep

**Comment by radare** [comment]
And remove the current aeCr, which should be accessible via aer

**Comment by sushant94** [comment]
What's the status of this? Do we still need this? As I see, `aoe` still currently says TODO.

**Comment by radare** [comment]
Yes, this needs to be done. Its just calling analop to get the esil expression and pass it to the reil translator and print that.
The command must accept a numeric argument to specify how many instructions you want to get in reil
