### ISSUE TITLE
Discuss moving `aeCr` to `aer`

### ISSUE THREAD

**Issue by radare** [radare/radare2#2346]
Do we really want to handle the esil registers separately from the anal ones?

*discuss*

**Comment by jvoisin** [comment]
I think so, since this might be confusing.

**Comment by sushant94** [comment]
@condret suggested that it should be aeCr as we plan on implementing translations to other ILs in the future. So it could be something like - Anal ESIL Convert <IL>

**Comment by radare** [comment]
The uppercase C and the length of the command concerns me a bit. Maybe we should discuss a bit more. Any other suggestion?

**Comment by jvoisin** [comment]
I like the `aecr` syntax:
- having a *category* (`c`) to convert to IL is better than throwing this directly into the `ae` one
- this will reduce the help length for `ae`, making it more clear

Four letters is not that long for a command that won't be used that often; I mean, it's only one letter more that the beloved `pdf`

**Comment by condret** [comment]
i would prefere esil to have it's own regs

**Comment by sushant94** [comment]
So, what have we decided on this? :P

**Comment by jvoisin** [comment]
It seems that we reached a consensus: 
- `aecr`
- separate reg

Except if someone disagree; @radare ?

**Comment by radare** [comment]
I vote for 'aetr' where T is for 'to'

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
:+1:  for the `aetr`

**Comment by sushant94** [comment]
Cool. So `aetr` is is then. I'll make a patch soon :)

**Comment by radare** [comment]
Perfecf! Will merge asap. Ill do some more fuzzing today, but i think we
are ready to release :)
