### ISSUE TITLE
Add visual esil mode - `VE`

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2348]
For the ESIL (and probably SSA later, keep that in mind) nice view, similar to the visual debug view.

**Comment by radare** [comment]
This is VO. Do you want something else?

**Comment by XVilka** [comment]
@radare Yes, I mean for emulation purposes, and probably two columns - one for disasm and one - for esil.

**Comment by radare** [comment]
this should be an option under asm.xxx so it will do normal disasm, but throw the esil or reil after the instruction. Is this what you mean?

**Comment by XVilka** [comment]
yes, I thought more like executing ESIL VM operation-by-operation, representing actual state of ESIL VM, not the state of main CPU.

**Comment by radare** [comment]
you can do this with `dh esil`
