### ISSUE TITLE
dr in visual mode doesn't work

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2352]
dr in visual mode doesn't work

afn is still working

**Comment by radare** [comment]
Wat. Can u be more descriptive?

**Comment by Maijin** [comment]
@radare Go in Visual mode, position on function, type "d", then "r". The console freeze

**Comment by Maijin** [comment]
Oh, highlight (/) in Visual mode also stucks when used.

**Comment by deffi420** [comment]
I can reproduce the bug. 'dr' in visual mode shows the "new function name:" prompt  but does not accept any input (the only way to exit is to kill the process).

**Comment by radare** [comment]
The input is accepted. Just not echoed to the terminal. Its a one line fix
in rcons. Will do as soon as i can reach my laptop

**Comment by Maijin** [comment]
@radare It's not only echoed, you can't even type "enter" to get the value accepted

**Comment by deffi420** [comment]
Yup, '/' is also broken. Seek to offset 'o' is still working though.

**Comment by deffi420** [comment]
The bug was introduced by this commit:

commit 37476d6eef1805df552e3823676b1980e390e977
Author: pancake <pancake@nopcode.org>
Date:   Thu Apr 9 16:43:20 2015 +0200

    Do not drop raw cons after getchr to avoid visual flickering

**Comment by radare** [comment]
No need to regress this. It was quite obvious. I already know the problem
and the fix. But im busy irl now. Will do before dinner probably :p if u
want to spend time regressing you can test the laddr bug or many other ones
which are not that obvious

**Comment by deffi420** [comment]
I sent a pull request. Uncommenting the line

408     //r_cons_set_raw (0);

solved the issue. I'm not sure if this is the best fix or causes problems somewhere else...

**Comment by radare** [comment]
This is wrong. Can you guys wait until i can get my hands on the laptop?

**Comment by Maijin** [comment]
Fixed :+1:
