### ISSUE TITLE
Wrong handling of the Chinese comments in Visual mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2359]
just do:

```
cp /bin/true 逆向工程
r2 逆向工程
> CCu 逆向工程
> Vp
```

It shows this
![r2-hanyu](http://xvilka.me/r2-hanyu.png)

You can loop through visual modes with 'p' to get additional glitches

**Comment by XVilka** [comment]
Also in Cygwin r2 can't open files with the Chinese names:
```
xvilka@WS-705 ~/radare
$ r2 逆向工程.exe
xvilka@WS-705 ~/radare
$ r2 逆向工程.exe
xvilka@WS-705 ~/radare
$
```

**Comment by radare** [comment]
http://s2.quickmeme.com/img/34/34c5a5d89699a28f2486c23c5b381486b62553f3eba9ebaccf36df6306494e00.jpg

**Comment by radare** [comment]
Cant reproduce anymore
