### ISSUE TITLE
Add uleb128 support to `pf`

### ISSUE THREAD

**Issue by radare** [radare/radare2#2360]
Very useful for parsing dwarf or dex

**Comment by radare** [comment]
@hyask ?

**Comment by Hyask** [comment]
I implemented the functionality this morning, and a testcase, but the JSON doesn't work yet, as for arrays of ulebs, that's why I didn't commited...
I haven't much time, but I'll try to complete it asap

**Comment by radare** [comment]
Awesome! That will be a cool addition! Thanks

**Comment by radare** [comment]
thanks!
