### ISSUE TITLE
Move `main` of r2 inside libr_core

### ISSUE THREAD

**Issue by radare** [radare/radare2#2367]
Do the same with rabin2, rasm2, ...

This way we allow the programmer to call the main of each main from his program. Useful for embedding and avoid forks.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/13281

**Comment by radare** [comment]
lets make it happen, not going to delay this change more

**Comment by radare** [comment]
Done in 82416b021239286833c2336dddcb3ac6d1dab165
