### ISSUE TITLE
Infrastructure changes - improving code quality

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2373]
- [ ] Deploying proper code-review system (`gerrit`?)
- [ ] Writing Coverity modelling file for better analysis http://scan.coverity.com/models
- [ ] Improve CI (move to the `buildbot`?)
- [ ] Use automatic formatting tool for C files and headers (`clang-format`?)
- [x] Use `shellcheck` for .sh scripts (errors are fixed but warnings should be fixed too) http://ci.rada.re/view/Quality/job/radare2-shellcheck/ && http://ci.rada.re/view/Quality/job/radare2-shellcheck/14/warnings17Result/NORMAL/

**Comment by crowell** [comment]
for code-review, the options that I know of are [gerrithub](http://gerrithub.io) or [barkeep](http://getbarkeep.org/)

**Comment by crowell** [comment]
after watching the video, barkeep looks bad.

**Comment by jjdredd** [comment]
code review: github doesn't cut it?

**Comment by crowell** [comment]
github code review kind of sucks

On Mon, Apr 13, 2015 at 2:13 PM, Judge_Dredd <notifications@github.com>
wrote:

> code review: github doesn't cut it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2373#issuecomment-92449048>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by jvoisin** [comment]
I'm using [astyle]( http://astyle.sourceforge.net/ ) for other projects, and it's **way** better than uncrustify.

**Comment by crowell** [comment]
clang-format > astyle

**Comment by radare** [comment]
We already have a clang-format configfile commited. Still not perfect, so thats why im not enforcing. Also newer llvm versions come with better clangformat options.. So in case of being used it will depend on a modern llvm

**Comment by Maijin** [comment]
shellcheck added to all scripts + make quality to run it

**Comment by Maijin** [comment]
@radare 
Shellcheck errors are fixed and a shellcheck test is ready and will not pass if someone add an error + we have detailed online of warnings: 
* http://ci.rada.re/view/Quality/job/radare2-shellcheck/14/warnings17Result/NORMAL/

**Comment by XVilka** [comment]
Added ability to run the testsuite under the valgrind http://ci.rada.re/view/Quality/job/valgrind-radare2-regressions/ 
Not yet visible from Web, I'll fix that soon.

**Comment by Maijin** [comment]
See https://github.com/radare/radare2/issues/3251
