### ISSUE TITLE
detect version of libc on static-compiled binaries

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2374]

**Comment by radare** [comment]
Use flirt or zignatures. This is not an easy task if u want to cover all the possible cases. Checking for strings can be usrful buy this feature should not come in core. Move it to extras or so

**Comment by crowell** [comment]
right, I think it would be nice to provide a database/string matching in
r2-extras

On Mon, Apr 13, 2015 at 3:03 PM, radare <notifications@github.com> wrote:

> Use flirt or zignatures. This is not an easy task if u want to cover all
> the possible cases. Checking for strings can be usrful buy this feature
> should not come in core. Move it to extras or so
>
>
>
> > On 13 Apr 2015, at 20:28, Jeffrey Crowell <notifications@github.com>
> wrote:
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2374#issuecomment-92462280>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
Please move this issue to r2-extras. It can even be a full project completely separated from r2
