### ISSUE TITLE
Analysis acting weird on this malware

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2375]
See the [radare.tv](http://radare.tv/a/48), the sample is [here]( http://rghost.net/private/6DYWSWPq9/a6f6b58dd91580f3d18cfe5378298bdb ), password "infected".

**Comment by radare** [comment]
skipping: b73b4a11f725137a4e1aa19236a5b61671d0880edc8ba1c4d7dd22031e55a922  need PK compat. v5.1 (can do v4.6)

**Comment by radare** [comment]
also, use 7z with password or so, firefox-nightly doesnt allows me to download this file because of being identified as malware

**Comment by radare** [comment]
lol, nevermind, its already 7z with pass. why the hell comes with .zip

**Comment by radare** [comment]
Probably related to https://github.com/radare/radare2/issues/2361 because i can see imports inside the text section

**Comment by radare** [comment]
The analysis is not an infinite loop. so maybe just move this for 1.0 . ill try to fix #2361 regression, and maybe this will fix this issue too.
