### ISSUE TITLE
entry0 in libs

### ISSUE THREAD

**Issue by condret** [radare/radare2#2378]
i'm really sure that there is not entry0 in libs, but r2 finds one.

**Comment by radare** [comment]
you are wrong, libraries are also executable in ELF, in fact a library can have a constructor and a destructor. and the most promiment example is the /lib/ld-linux.so

also you can use readelf -e | grep Entry to verify what i’m describing here.

**Comment by jjdredd** [comment]
http://www.tldp.org/HOWTO/Program-Library-HOWTO/miscellaneous.html

**Comment by condret** [comment]
oups, sry
