### ISSUE TITLE
Add support of loading IDC databases modified with Hex-Rays

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2380]
Just go to the Hex-Rays decompiler and rename any function, then store database and export it into the IDC, then try doc/idc2r.py script.
- [ ] Add support of converting labels
- [ ] Add support of converting enums

**Comment by radare** [comment]
You can tell radare to execute a file and remove it everytime the prompt is shown with cmd.prompt, then just make ida hook the function rename and comments to append them in this file as radare commands.

**Comment by XVilka** [comment]
@radare I'm already on it (not yet finished commit), extending doc/idc2r.py

**Comment by Maijin** [comment]
https://github.com/radare/radare2ida
