### ISSUE TITLE
Add support of building radare2 using clang-cl

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2384]
Like it [was done](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Building_Firefox_on_Windows_with_clang-cl) for Firefox.

This can be used as a [ready compiler](http://sourceforge.net/projects/clangonwin/files/MsvcBuild/3.7/)

**Comment by radare** [comment]
ping anyone?

**Comment by radare** [comment]
PING

**Comment by Maijin** [comment]
Clearly low prio

**Comment by Maijin** [comment]
Added in META
