### ISSUE TITLE
Integrating ESIL analysis into the output of `pdc` command

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2386]
Use `pdc` for simple decompilation, but its just unfinished right now. You can verify this by comparing the output of `pdr` and `pdc`. Also, the output of pdc can be heavily enhanced and using [esil]( https://github.com/radare/radare2/wiki/ESIL ) may help to get proper pseudo decompilation.

**Comment by radare** [comment]
this is already tracked in another issue
