### ISSUE TITLE
Store the flags and flagspace in the sdb using base64

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2389]
To easily store/load them and to support any weird name you want to use.

**Comment by radare** [comment]
SDB no longer have non-ascii restrictions. so this is not an issue now. only \0 is an invalid char. the restriction is more about the shell itself. to allow always the user to retype a flag, if it supports non-ascii chars it will be difficult by some users if they reload the project or so.

also flags should have a realname field which may contain those free-of-restrictions strings. already used by the demangler.
