### ISSUE TITLE
dcs doesn't respect syscall args defined

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2397]
dcs doesn't work correctly, I mean in the "linux-x86-64" file There is `brk=0x80,12,1,` (1 argument) and this is what I get:

    --> 0x7f70192461ac syscall 12 brk (0xffffffffffffffda 0x400040 0xffffffffffffffff)
It displays 3 args

**Comment by Maijin** [comment]
Nop doesn't work here : linux x86-64
Same issue

**Comment by condret** [comment]
maijin can you try 'as' for that

**Comment by Maijin** [comment]
@condret as seems to work as expected (but still not dcs):

    [0x7f743544a18c]> as 12
    12 = brk (0x00400040)

**Comment by radare** [comment]
should be working fine now

**Comment by Maijin** [comment]
@radare It works but doesn't respect parameter settings for example `open("/lib/x86_64-linux-gnu/libselinux.so.1", O_RDONLY|O_CLOEXEC) = 3` in dcs is `-->sn 0x7f6d39f1c4d7 syscall 2 open (0x7f6d3a1108fc 0x80000 0x7f6d3a1271c8)` and the config is `open=0x80,2,3,zxx`

+  https://github.com/radare/radare2/issues/2404

**Comment by radare** [comment]
Thats why i wanted skia to add support for registers in pf... But i can reimplement it inside rdebug to show that from yhere instead of natively with pf

**Comment by Maijin** [comment]
@radare Then let's wait for https://github.com/radare/radare2/issues/1025 to be closed :+1:

**Comment by radare** [comment]
Cool. So this should go for 1.0

**Comment by Maijin** [comment]
Rely on #1515
