### ISSUE TITLE
`pB -x` is broken

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2402]

**Comment by radare** [comment]
Not sure how useful would be to show backward bits... It may result in a very confusing command

**Comment by crowell** [comment]
yeah, for a lot of these backwards things, do we really need them?

On Sat, Apr 18, 2015 at 3:11 PM, radare <notifications@github.com> wrote:

> Not sure how useful would be to show backward bits... It may result in a
> very confusing command
>
>
>
>
> > On 18 Apr 2015, at 15:49, jvoisin <notifications@github.com> wrote:
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2402#issuecomment-94192503>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by jvoisin** [comment]
Backward disassembly is useful, hexdump a bit less yes :/

**Comment by Maijin** [comment]
@radare I remember you said that pd -x was equivalent to something like `pd @@ -` something, I don't remember. This is how I've created the tests for the other command. Why not just create like an alias to this command like it's done with aa ?

**Comment by radare** [comment]
px -10

Must be the same as

px 10 @ $$-10

**Comment by radare** [comment]
I think negative offsets in hexdump and disasm take sense. But not for bitfields or other cases.

**Comment by Maijin** [comment]
Yes that was it

**Comment by jvoisin** [comment]
So it can be implemented as `px 10 @ $$-10`, nothing tricky.

**Comment by radare** [comment]
yep. thats how it was done before someone(R) broke it.

**Comment by jvoisin** [comment]
This is why @maijin has been singing the `run the testsuite before pushing` song :snowman:

**Comment by radare** [comment]
i feel way more important to be able to write bits than being able to read them backwards ;D moving this thing to 1.0

**Comment by Maijin** [comment]
@m1ghtym0 if done close it

**Comment by radare** [comment]
it is not fixed see:
```
$ r2 -
 -- Welcome to IDA 10.0.
[0x00000000]> wx 0102030405060708
[0x00000000]> s 4
[0x00000004]> pB 1
00000101
[0x00000004]> pB -1
00000101
[0x00000004]> pB -2
0000010100000110
[0x00000004]> pB 2
0000010100000110
```

**Comment by alvarofe** [comment]
fixed
