### ISSUE TITLE
Saving breakpoints when saving a project.

### ISSUE THREAD

**Issue by lyuts** [radare/radare2#2409]
Fairly new to radare and can't seem to find a way to persist breakpoints between debugging sessions.
Played with project save/open but breakpoints are ignored. Is there a way that i'm missing to get the desired effect?
 Thank you.

**Comment by radare** [comment]
You can just do the following:

```
db* > bps
```

and then restart again and load them again:
```
. bps
```

**Comment by jvoisin** [comment]
Sure, but it would be cooler to have this by default :)

**Comment by radare** [comment]
This can be easily added to project save/restore if you find it necessary.

**Comment by lyuts** [comment]
Didn't know you could do that. Thank you. I think many people would still prefer them to be saved automatically so that you don't accidentally lose all your breakpoints which might take some effort to reset. I've created a pull request for this change. Hopefully didn't miss anything there.
https://github.com/radare/radare2/pull/2444

Another thought that I had is that we can actually check if radare is running in debugging mode (i.e. with -d flag) and save breakpoints only if it is. Not sure if inconsistent behaviour is good (i guess it is ok if it is communicated well to the user.

**Comment by jvoisin** [comment]
It's ok, issuing `db*` in non-debugger mode will return nothing.

**Comment by radare** [comment]
Breakpoints should work with esil emulation. So db must be working even without -d

**Comment by Maijin** [comment]
This has been fixed.

**Comment by radare** [comment]
do we have tests for this?

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t/cmd_project#L160

**Comment by Maijin** [comment]
I though the PR had been merged but it didn't so it's not fixed.

**Comment by radare** [comment]
which pr?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/2444
