### ISSUE TITLE
setting a bp on a PIE binary

### ISSUE THREAD

**Issue by n0way0ut** [radare/radare2#2415]
should be nice to support this http://reverseengineering.stackexchange.com/questions/8724/set-a-breakpoint-on-gdb-entry-point-for-pie-binaries-without-disabling-aslr 

seems that gdb supports it..

**Comment by radare** [comment]
This is done for loading the symbols at a base address. We should dump those breakpoint with the base information so it can be restored later.

Something like

f baddr =0x820300
db 0x4867+baddr

**Comment by radare** [comment]
if you do -e dbg.bep=entry0 the debugger will load in there, honoring the aslr, same for symbols, etc. the only missing point is when you quit, backup bps, and reload the process, you have to redo the breakpoints by hand

**Comment by ret2libc** [comment]
@radare @n0way0ut can you test this now?

**Comment by radare** [comment]
we should support named breakpoints, this is, breakpoints that depend on a flag instead of an offset.

**Comment by jduck** [comment]
Related to #3105 and #2903

**Comment by alvarofe** [comment]
this was fixed in 6b827c1563ed8d4021c4dcb21814b32927d7b88f and 564803d5c21545a11941f3059fdbad65109044ed
