### ISSUE TITLE
List exports only command - `iE`

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2416]
Currently radare2 has `ii` and `is` commands to list just imports and all symbols respectively. It would be awesome to list also only exports. May be `iE` since `ie` already printing entrypoint, or rename `ie` to list exports and use `iE` to show entrypoint.

**Comment by radare** [comment]
Exports are also symbols. We can just filter the ones with the public attributte set

**Comment by XVilka** [comment]
@radare so what about using `iE` for entrypoint instead and using `ie` for the export listing?

**Comment by radare** [comment]
I think people is more used to -e for entrypoint...

**Comment by Maijin** [comment]
iE would be perfectly fine :)

**Comment by radare** [comment]
You can get this with rabin2 -s | grep bind=GLOBAL

**Comment by jvoisin** [comment]
`iE1 would be cool

**Comment by ret2libc** [comment]
+1 for ```iE```.

**Comment by XVilka** [comment]
There is 'visibility' field in the RBinSymbol structure https://github.com/radare/radare2/blob/master/libr/include/r_bin.h#L308 But if you check the bin plugins for PE or ELF, for example, you wont be able to find its usage. So I guess reusing this flag could be a proper suggestion.

**Comment by radare** [comment]
Internet explorer?

**Comment by radare** [comment]
What about adding another flag to select the visbility of the symbols you want to get listed.. iE seems simpler to be, but i would prefer to use only lowercase flags.. but i like to dream

**Comment by Maijin** [comment]
User will prefer to use import/export keyword or shortcut like iE, ii.

**Comment by ret2libc** [comment]
I agree with @Maijin. iE, ii, etc. are much easier and immediate to use imho.

**Comment by radare** [comment]
current rabin2 -E does this:
```
 -E              show loading offset (useful for non-ASLR libraries)
```

so maybe we should probably drop that option or move it before implementing iE
