### ISSUE TITLE
Recognize Blackfin

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#2419]
I'm not asking to add the Blackfin architecture, but we should be able to recognize it from the ELF header.

Example:
https://www.dropbox.com/s/4hn8rikhzss6ey3/hellobf?dl=0

```
$ readelf -h hellobf 
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Analog Devices Blackfin
  Version:                           0x1
  Entry point address:               0x830c
  Start of program headers:          52 (bytes into file)
  Start of section headers:          4532 (bytes into file)
  Flags:                             0x5000202, FDPIC
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         9
  Size of section headers:           40 (bytes)
  Number of section headers:         30
  Section header string table index: 27
$
```

```
$ r2 hellobf
[0x0000830c]> i~machine
machine  <unknown>: 0x6a
machine  <unknown>: 0x6a
[0x0000830c]> 
```

In general, recognizing new machines could be added based on ELF header information. This could exist before a disassembler for the machine even does. Or would that cause issues?

**Comment by radare** [comment]
The bin plugin tells which asm plugin to use. This arch doesnt needs to be supported by the disassembler/analyzer, so thats fine. But would be nice to have support for it. Maybe in extras

**Comment by jvoisin** [comment]
Wouldn't it be possible to simply display the correct value in the `machine` field?

**Comment by Maijin** [comment]
Already in my updated version of the pf elf enum https://github.com/Maijin/r2-pf-templates/blob/master/elf_enums

**Comment by radare** [comment]
Sure. Thats what i was trying to say with my sleepenglish. Will commit when i arrive at home

**Comment by radare** [comment]
Fixed in git. i'll add the disassembler plugin soon. it's just few mins and copypasta, but im a bit busy now, so i'll push it later at afternun/nite

**Comment by XVilka** [comment]
@radare is that disasm LGPLv3 compatible? or you're going to push it to the 'extra'?

**Comment by radare** [comment]
it’s from binutils.it’s about 5KLOC of GPL code

it must go into the extras repo imho

**Comment by radare** [comment]
Added blackfin disassembler plugin in https://github.com/radare/radare2-extras/commit/ad5a00ccce902cd0c0bbb069371dfb43e4b2c00b

enjoy ;)

**Comment by ninjahacker** [comment]
That's fantastic! Thanks!

**Comment by radare** [comment]
There's no analysis plugin yet, so the colors and jump lines will not
work, also, looks like the syntax is uppercase which breaks the way
diassemblers work in r2, this must be changed, but as long as it's
distributed in -extras it's not a critical issue. Feel free to suggest
improvements or send patches for blackfin.

**Comment by ninjahacker** [comment]
Yeah, I wouldn't mind working on it. I've got some example files I can use to help. I tried installing the extras, but it won't display the disassembly (./configure, make asm, make install-asm). Is there some extra step I need to do to get the main core r2 to find it?

**Comment by radare** [comment]
Its "make asm-install". 

You can also copy the .so into your ~/.config/radare2/plugins too

Use R_DEBUG=1 environ to make the plugin loading more verbose in r2 if you have problems trying to load it.

**Comment by ninjahacker** [comment]
Yeah, sorry. I was doing the right make asm-install, just typing it into here from memory wrong. The plugins dir works though, so I'm set. Thanks again!

**Comment by radare** [comment]
Cool!
