### ISSUE TITLE
add nstimestamp (osx) timestamps for rax2 and print time

### ISSUE THREAD

**Issue by radare** [radare/radare2#242]

**Comment by Maijin** [comment]
Link to "nstimestamp" doc ? Implementation ?

rax2 already have timestamp supports:

```
  -t    tstamp -> str     ;  rax2 -t 1234567890
```

**Comment by radare** [comment]
Wat

**Comment by Maijin** [comment]
? This is your issue ? But it's empty and there is no info on this nstimestamp online.

**Comment by radare** [comment]
https://www.epochconverter.com/mac
