### ISSUE TITLE
Feature request: Add a memory reference type to ESIL

### ISSUE THREAD

**Issue by dkreuter** [radare/radare2#2420]
I propose a new ESIL type and corresponding instructions. What used what used to be

```
a, b, +=[2]
```

shall become

```
a, b, ref[2], +=
```

It would simplify generation, analysis and interpretation. Two open questions:
- The names for the instructions turning addresses into lvalues. Suggestions: "ref[2]", "*(ut16*)", …
- The on-stack representation of the value. Suggestions: "[2]0xffff", "*(ut16_)0xffff", "\_2:0xffff" …
  Maybe prefix normal numbers with some bytes so they can be turned into memory references by changing the prefix.

Pinging for feedback/approval: @radare @condret @crowell @jpenalbae

**Comment by crowell** [comment]
think this breaks the stack operation of +=. it would require 3 pops in it, instead of the normal 2.

this will require a lot of refactoring I think.

**Comment by dkreuter** [comment]
@crowell += would still only pop 2 elements
ref[2] pops 'b', evaluates it (let's say b is '10'), then pushes "*10"
+= would then pop two elements: "*10" and "a"

**Comment by radare** [comment]
Not before the release. This will break all current implementations. Nighterman also proposed another breaking change and i want to release before the end of this week.

Imho the proposal looks good in the sense that it will reduce the number of commands needed to emulate code. But we have to be careful with this because it will need updates for reil, emulation, all archs backends, etc..

Also im not sure if this will make analysis harder because right now is easy to see if an instruction is writing to memory without having to emulate it.

Lets discuss

**Comment by dkreuter** [comment]
>Also I'm not sure if this will make analysis harder because right now is easy to see if an instruction is writing to memory without having to emulate it.

Even if you don't know the values on the stack, you can see which values are consumed by which ESIL instructions. Checking if a ref[2] is used in a reading or writing context can be decided in linear time. (Assuming the ESIL stack is cleared between instructions of the emulated CPU)

There could be ambiguity if there's a ternary ESIL operation that has a register as true-expression and a memory reference as false-expression. It shouldn't matter for analysis though, since it can const fold the deciding expression until it knows which of the two to pick.

The change would involve modifying 'r_anal_esil_get_parm' to handle the case of a memory reference and a new function 'r_anal_esil_set_parm' that acts like 'r_anal_esil_reg_write' for the register case.

**Comment by condret** [comment]
i like the concept of explicit reads and writes. So i would prefere you do this in a plugin as custom-stuff for testing and later we can decide if this decision would break anything. I also plan to add some kind of history for registers in esil, that provides information how a value got computed (until the reg gets set with a constant value). I'm not sure if this really would work with your proposal

**Comment by XVilka** [comment]
@sushant94 I think you can join this discussion too.

**Comment by condret** [comment]
i thought some time about this. I think we can realize this later. For now i would like to "release" esil-specs current esil as esil-v1, and later we could add this in the specs for esil-v2 (which should be backward-compatible)

**Comment by XVilka** [comment]
@condret: there is a big possibility that ESIL syntax will be heavily changed this summer. So I'm not sure about complete backward compatibility - that could slow down development a lot.

**Comment by condret** [comment]
but changing all the stuff that is allready done will block us for a while. pls don't remove the callback-system and the customops.

**Comment by XVilka** [comment]
no one want to remove the ability to do the customops and system-callbacks. But syntax can be changed during this summer.

**Comment by radare** [comment]
cc @sushant94 @killabytenow @skuater

**Comment by radare** [comment]
As discussed with @sushant94 it is ok to close
