### ISSUE TITLE
Unable to attach radare2 to a process

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2422]
```
[0x00000000]> dpa 22862
p/debug_native.c:439 ptrace (PT_ATTACH): No such process
pid = 22862 tid = 22862
r_debug_select: 22862 22862
[0x00000000]> !ps aux | grep 22862
jvoisin  22862  0.0  0.0   2040   512 pts/15   t+   23:03   0:00 ./ezhp
root     23322  0.0  0.0   4444   848 pts/23   S+   23:12   0:00 sh -c grep 22862
root     23324  0.0  0.0  16664  2108 pts/23   S+   23:12   0:00 grep 22862
[0x00000000]> !id
uid=0(root) gid=0(root) groups=0(root),126(pkcs11)
[0x00000000]> dp~22862
Selected: 22862 22862
 * 22862 s (current)
```

But I can't see any opcode with `pd`.

**Comment by crowell** [comment]
hm... you should be able to attach with just r2 -d <pid>

can you do that?

**Comment by jvoisin** [comment]
It's working o/
From now, you shall be called *crowell the saviour*.

**Comment by XVilka** [comment]
@jvoisin can we close it?

**Comment by Maijin** [comment]
@XVilka working with `r2 -d` but not working with dpa

**Comment by radare** [comment]
Dpa is only suposed to work on childrens of the target process, otherwise you need the machinery under io.

**Comment by Maijin** [comment]
@radare so what's the equivalent to `attach pid` in gdb ???

**Comment by radare** [comment]
o dbg://pid ?

We can make dpa work like that if u liek

**Comment by Maijin** [comment]
The self documentation just says
    dpa <pid>           Attach and select pid
    dpf                 Attach to pid like file fd // HACK

So that would be nice :+1:

**Comment by jvoisin** [comment]
I agree with @maijin, it would be great.

**Comment by qsantos** [comment]
Also, no pid is mentioned in either the man page or the `-h` message of `r2`. The behavior for `r2 -d pid` should be documented. I am sending a pull request for the latter.

**Comment by radare** [comment]
The self:// is for rarun2 r2preload, i though that -d pid was documented already..

**Comment by radare** [comment]
you can also use `o debug://pid`

**Comment by radare** [comment]
Closing this thing
