### ISSUE TITLE
Impossible to switch back to the text view from the graph

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2428]
When switching to graph view (pressing space) in the @pwntester webui, sometimes the graph isn't rendered, and it's impossible to switch back to text view. refreshing the page is a workaround.

**Comment by radare** [comment]
Just add a button in top-left of the disassembly panel to toggle between those two modes will solve the issue. Imho this option ahould be removed from the context menu

**Comment by pwntester** [comment]
ok, I will add that button.

**Comment by radare** [comment]
@pwntester ping?

**Comment by pwntester** [comment]
sorry, I havent found the time yet. Its on my todo list, problably today

**Comment by pwntester** [comment]
https://github.com/radare/radare2/pull/2467

**Comment by jvoisin** [comment]
If it's fixed, we can close this issue.
