### ISSUE TITLE
rabin2 -I ptrace://<pid>

### ISSUE THREAD

**Issue by condret** [radare/radare2#2431]
it worked once, i loved that feature, but now it's bokken :((

**Comment by XVilka** [comment]
would be awesome to fix that before the release

**Comment by radare** [comment]
This was never suposed to work, if it did was because of magic, gimme a commit where this was working because i can imagine tons of reasons starting by aslr that can make this thing not work at all

**Comment by condret** [comment]
uhm aslr should not affect on that. at least rabin2 -I dbg:///bin/ls works

**Comment by radare** [comment]
aslr has been fixed again. linux changed the order it was relocating bins in memory. .can you recheck?
