### ISSUE TITLE
 error: 'ADDR_NO_RANDOMIZE' undeclared

### ISSUE THREAD

**Issue by davidgfnet** [radare/radare2#2433]
Seems that my RH5 machine does not define this macro. Is it something radare2 should be aware of? I don't really understand why, seems like a broken kernel to me :(
Thanks!

**Comment by jvoisin** [comment]
[Yup]( http://permalink.gmane.org/gmane.linux.utilities.util-linux-ng/1462 ), seems to be kernel-related.

**Comment by radare** [comment]
thanks
