### ISSUE TITLE
NAN / INFINITY not declared

### ISSUE THREAD

**Issue by davidgfnet** [radare/radare2#2434]
Hello,

For some reason NAN and INFINITY seem not to be defined in my RH5 machine. Using C99 it just works, no idea why. I was getting:

```
class.c:1300:9: error: 'INFINITY' undeclared (first use in this function)
```

But it's just a matter of adding `-std=c99` in the Makefile (at `shlr/java`).

Hope it helps!

**Comment by radare** [comment]
Both INFINITY and NAN are defined in the c99 standard and are non-portable defines . i wrote some helper macros in r2 include to fix this. im closing the issue, but please confirm that its fixed.

thanks
