### ISSUE TITLE
AddressSanitizer anal/fcn.c

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2450]
```
=================================================================
==29970==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fff10974350 at pc 0x7f1aa7e0b8cf bp 0x7fff1096ff10 sp 0x7fff1096ff00
READ of size 1 at 0x7fff10974350 thread T0
    #0 0x7f1aa7e0b8ce in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:277
    #1 0x7f1aa7e0deda in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:514
    #2 0x7f1aa7e0deda in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:514
    #3 0x7f1aa7e0deda in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:514
    #4 0x7f1aa7e0deda in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:514
    #5 0x7f1aa7e0deda in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:514
    #6 0x7f1aa7e0deda in fcn_recurse /home/revskills/dev/radare2/libr/anal/fcn.c:514
    #7 0x7f1aa7e0e914 in r_anal_fcn /home/revskills/dev/radare2/libr/anal/fcn.c:584
    #8 0x7f1aa98e2e6c in r_core_anal_fcn /home/revskills/dev/radare2/libr/core/anal.c:815
    #9 0x7f1aa98e440b in r_core_anal_fcn /home/revskills/dev/radare2/libr/core/anal.c:997
    #10 0x7f1aa98e440b in r_core_anal_fcn /home/revskills/dev/radare2/libr/core/anal.c:997
    #11 0x7f1aa98e3ce0 in r_core_anal_fcn /home/revskills/dev/radare2/libr/core/anal.c:934
    #12 0x7f1aa98e440b in r_core_anal_fcn /home/revskills/dev/radare2/libr/core/anal.c:997
    #13 0x7f1aa98315b2 in cmd_anal_fcn /home/revskills/dev/radare2/libr/core/cmd_anal.c:938
    #14 0x7f1aa983d52a in cmd_anal /home/revskills/dev/radare2/libr/core/cmd_anal.c:2422
    #15 0x7f1aa98d8b9b in r_cmd_call /home/revskills/dev/radare2/libr/core/cmd_api.c:182
    #16 0x7f1aa9889cde in r_core_cmd_subst_i /home/revskills/dev/radare2/libr/core/cmd.c:1542
    #17 0x7f1aa988522f in r_core_cmd_subst /home/revskills/dev/radare2/libr/core/cmd.c:1039
    #18 0x7f1aa988baec in r_core_cmd /home/revskills/dev/radare2/libr/core/cmd.c:1760
    #19 0x7f1aa988c605 in r_core_cmd0 /home/revskills/dev/radare2/libr/core/cmd.c:1891
    #20 0x7f1aa98ea19b in r_core_anal_all /home/revskills/dev/radare2/libr/core/anal.c:1603
    #21 0x7f1aa983d790 in cmd_anal /home/revskills/dev/radare2/libr/core/cmd_anal.c:2464
    #22 0x7f1aa98d8b9b in r_cmd_call /home/revskills/dev/radare2/libr/core/cmd_api.c:182
    #23 0x7f1aa9889cde in r_core_cmd_subst_i /home/revskills/dev/radare2/libr/core/cmd.c:1542
    #24 0x7f1aa988522f in r_core_cmd_subst /home/revskills/dev/radare2/libr/core/cmd.c:1039
    #25 0x7f1aa988baec in r_core_cmd /home/revskills/dev/radare2/libr/core/cmd.c:1760
    #26 0x7f1aa988c605 in r_core_cmd0 /home/revskills/dev/radare2/libr/core/cmd.c:1891
    #27 0x407091 in main /home/revskills/dev/radare2/binr/radare2/radare2.c:707
    #28 0x7f1aa4a01ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #0 0x4030f8 in _start ??:?

0x7fff10974350 is located 138532700606443 bytes insideASAN:SIGSEGV
==29970==AddressSanitizer
```

file gz: 
> H4sICJyWPlUCA2VuY29kZWRfZGIubWRlAO1da3Ac1ZU+t/v2Yx56jm38SMJsBBgc
2zuWbHBYApI1UiKQLMcyToqYSC1NSx5lNKPtmZElXp5QlRBIbcFukkpIkZD8SRXF
j8TZYncLqDwJ7NaSJQV/kuxmqaJcW7Ab7xYp9lEJSe+5/ZjplkZjE2Ak2efr6e5z
T9/Hube777nndN8eYABjJSOfMaxM8mazlEwfAoEn8vLkRORHt7722IzVexM8cs+j
D9mf+eq+nyw9eS719MvPf23qF+eee3Twdw88ffizv/v1dbenH/nts5+8+t8Sf/PA
xLEv3nntX55++cypNxL9L3z7TM9+Y+kTf/XEXbuU1+96mO34yu87R2/+Yu7GiavG
v/R/P7v/is/MPHv5zvSL//mCec7Wnhv85uKW+LnX9gCBQCAQ3mVoDGi5hBfGXlVx
CAAS3Kn9j+peE4eXXSMSAMPVtul2IRAIBALhncIP7DWExI73CyGeQQXf4Qk01gEx
DEiu6gfAYQHzhgZ+FLHnfgUi/CxPiDBnQQ6GISoFOJ04hgBZBlaLo2MJOg9yoqCD
rgQ5nciJqAFOt8iHa65wbpztWFZcD3A6BRGPgBzmRKOe2FV5IjFQwpxYHNRwqlgL
aMs4rShUmNMGkWWcdoiGOdJQRj9iWGa+NJThh405kx9bmjejaaNk9lsmbh3y1vkM
bpXRU3nTUgZzxkxRR7YxaRRNrb+Qz5tTpdhgwTKzM3mRR/zoXGkoP10YO1mwSjEv
MFzIz0jDC+rwwhGrMK8PL4wUMuWcqQ0vDCyWLIOJAR3DAV3dn6iaqAu2+KpxRDSs
XUxEY25cMUJ0x4i8eiEEeaL6cb/6QvIIcGxoRRUFSriVcW0BHbd4uqEdWsVpwIZv
g7g4gmsrRHEbwxXPEW41lYalBAJho+JNe23h6/+Xce3x9b9QyK5SdvrxOO7jjfR+
JKj3Xe0sBTW4GAmwkN4XOeujk7Ooy4Yy8thQWu7rH4kPDuVPmlYWdV3ObKx7pLhQ
FeAp4WV6ppoxqQYCgUAgEOrC1/831Sw2GNNQX2tV/S+jruXx2uGV+l9aZvcziITs
fo4jgmhQ/7scHrTXBSeuBO11obzRJKzZ6wlFeAt85R7pK5Ws7GRZmMpWBk1lYVLu
c7bd0YHFecssFrOFPBcWtGOkuiZv1rZztp237Ttse9a2S0hocWFZeoOdZYMJ1uGX
VysOFEygxsn0JBAIBMKG1/+tUkD/66CgZS1UsVh11HSR+OpZRIPjAceDzlnY1ud1
/AF82XMALsYDLJxPVAl79G3h/pWXcbTlHv3W4h1HzZxRQuVfPJmdV2asyWxJm5oq
5MpzeS3r7vXiHa5iR6Lf4XSKZNOmZeanzIx7LMRyYzV2S0TjwluNrcobRovFhXsb
hNO7UbR43HW4SHUc7LWnMwFeXWeIX9E69VvWUjScIRAIhEsHjLU4+zbn/b8/V3+t
zCiv8Nv5z+Ux+Z+kIekZdhN7Eg5QQ61/tJMQBAKBcIHgJARjBefVNob6ny4IAoFA
IBAuFfuf9D+BQCAQCE2HtLbFc/ZtpZ4I7bj0gviJqQA6hioASce/y52H0e0ipK+5
/H8sTj8oNpmJUxPGxML0AgY6mcubscoFJxx3wwUrszjnxmhzOeXpuYlTs9b8Qna2
6PAln1+0yqccTovLWZgszxZdTqvHuXsBkwtGu8tAAbzcHZnY6QJGmZh0WUqNFRAj
toL7ccGO1tiW8anpSbdcXuOWFqfLs24Wao27ojaaOCY5xzKGYMguY2GxUJgo3z07
P2MJru5yFxemy5npmdn56YzgRuiOJhAIBLL/CQQCgUAg1Ie+1vZ/Qa1jwktcb0/2
VoDViIur2U+7O7RincEPGq6nXWcMmv3gzHtAGx4cZwea7kgojv0PzteQ0HavuJG5
IGTHUq+4kVVBKI4ZjcRmxy5HYmvVbvctfcl3OciOB+EhVx6Z7ggCgUAgNMX+3+HM
LGtp8P4/tdL5sC4GR+vhPFXoWlhP6KUmIKxHJNeHGOthAoC+pkJw9iFFviD7/8KI
DWb/Jy7z7P/EVs/+T1zuE0mf+BOfeL/nGkh0+cQVPnGlT1zleQ0SO33iap+4xid2
eQ6FxAc8Yjv4BPMJyfM1bJd9gvuE4hOq54ZIgE/EfaLTc0wkmE+0eB6KhOQTrT7R
5vksErJPtPtEh+fFSGzzie0+scPzayTe4xPv9Yn3eZ6OBPcJxScSPrHJc4IkdM8J
klB9QvOJzT6xxfOPJCI+EfWJGPWmBAKB8Efpf13j1AwEAoFAIFxy+l+hZiAQCAQC
gfQ/gUAgEAgE0v8EAoFAIBAuKjD2K1m8vd4B/6A9qH1Ua9VeVB9Wb1d3qC8pX1Zu
U96nvMq/wxd5L49w+nsYAuEiRYfqzt5ok+H7H//Nn1njZ3v9vTg8tlQ8auZktrOK
Ky+PYYfQoTRMNlLIlHNmUWZXV3GVm443Lm7Kys6X6qWTG6Y7as4XrLrppIbpBgvW
HKa6qoor3FRbwXlZtY2tSCU6zRFslWoNd1exy027+ULTdstsTxUfcBNjwgpGa4tV
xv77dSeRvxfi3lo0rbQ5nc2bmToFw4q0N+gP3Fht2vLcnGEtDeWnCzK7DaBX3+Re
AQcPHgzk0+ucWq8CdWSojLiXRPXfw4qS3F1FqnqSz5PDR8umlTUx7YpayOdN29c/
gAmvqWJn9UyfJ6H772f1CsUY7aLppFXTpidlNoCtxr1W6+npCdwQvY7cbe6FVi+L
ZS22t4rdVeEbpE4bJWPSKIr22lXF1dUrpkHKY8ZkTiRbfv8yvARES++G17VXtJe0
Z7QntG9pX9Y+py1ps9ontFfVsiqpDyoVpUX5A/8vfhef47+V/0P+F/mn8vfkW+Qb
5D3yk9Lj0iPSNdJ2KSa9ye5nd7BPsRPsNfgl/CM8/W76LkTfY9ttILFYhLWJP8Bz
gzwUlMNH2T/f94Xkp0cfP/jy8e2Xdc3e0nHbx/79xy/99I1qeLW99fzC2VO5M9b5
4jn7QkggVwI5LJ8clk9uvnxyWD4pLJ8Ulk9qvnxSWL6t3nlfFmyiQH6RXpOIHv4N
XyCtGmyaQLUiZVcC5ig55gsE4aDomcKXY1uTTygLS8CaL4FQDptqp0ypF1SbeQZ5
WALefAlE93+suUVKzS9SaPbWtSgSAnejI4F3r7qavhqUnRFLKPgHqPbF/p0i126c
wFHXgd/qp3Xf5w9mFQxKoSBjA9rw8b7hCMDfu8tT2lPPicVooP83vrmz+vd/V/u6
78oP9dZyo/n/HipkSK8n9DYaPZP+J/0f1A9N1v+b1oH+v+WWNOx0ui0FjmVLOVOF
vnLpZMHSoL8wN2/klzQYMfLGjGn9qddKAtuARYWzYK44bkxNmcXi+LxVEC6FKB7A
4TZMnazm/O4W8R4n5xboc+IcN61itpBX4FA5m8tcGciuxclOgdR1ew/0xMVjf+Dw
dy3isjveLyKYzFUg4mI4rINYqv86vwX3W2o6Jur3IBF+lkuP7bZFbqzGYfs54BmW
qhz1sd1cdDfysjjc+/6Clw+HmAJKMA5ATPUq4MVBjgZaOA4/bMyZ/NjSvKl5DdB5
1JzPZaccR4vfJoM5Y6aouh43Ltx9ukghvGDCCeJ839C2d9v2Y7a937ZZlVaw5pdB
8DuNNsLpQDmoQ/mMubgPB1Ne+yggeZQGfIsfnxQRYQ1A9v/G1//wjj8LCKYNPQtY
kZb8/6v4/7vFyPqd8/8Xi0KVb643SAgPCWC1IQEEhgSb6w0Jtq02FmDsee4eCn3/
z3v+X+8jPxdH31j7/k/l3f+EDn0Mh0AgzxShhq3rQYjkJS8EZ79RN79Fz+FFof+9
v7dzlH3ltG3/HuC9a/AtPRoaEAiEhrhwD0DtrTA0aL9P9v+GsP/X8v0/3/8/ELjc
Dgt3fsDO34btuW253x/ABmV8vG98nPzbBAL5/8n/HxCo4fv/4uQ09f3/VXW+eP9f
pvf/L139z9irzlMByfH/U59JIBAIBMKlAMb+VhUjLQ3+QrtHK2gT2jn1X9UX1Lfy
tz8bsd7N+P+fCv05Dz10IBAITXN5qeE5zGp4DrPa/DnMangOsxKWTwnLpzRdPoa9
vZj/xyAOYjZBtpM7Cn37OByHQ9AH43AEjsIo3AwD0A/H8NBTWKXnjU8KRWGLeRUR
XM/y2iiAoVKQYDvbBSfgw3AnpJylG9f9mMcg7PE4qRDVv4IXXPbDtXA3dEEP7MVQ
F3wQ1364Hks4AhYUYAa3BszhYjqlmg6VhTwUHb4JSUgjVXK4JvJPwAhSU07qIq7T
eCwJY3ASY1kYI4Mx3Bbw9z24dGP5aRjGpQu5WUxZxvg5THkI90UnxyTWsYB5JDHN
PC45hyvKziJfSBTEm+C3036MP4hLP9auz2mJAxj6IC57YB+G92EZe5w4oh3ddupz
YqZQskHcivU6p50Oeu2UathO9VpgFPfTDt/Ekq9zYo1hKf24iFxHse6HMNd6afuQ
I9IVcUl6MogcJ2EWuVNOnGFMN+lIYcFSqCWSK66YA1hPUe+3c8Xsv6CWeKeumDS2
wWh134M1SAWumHrp3ZhJ58o+8BZaSwy9JByhcYmBivuoZNv+zBSx7V3aN8bAfpuo
N7afXnLnwDCmS/C2SyBsfCyC/36lwjSw4RtXuC5llbsvocv8+KG+/32lHRT+sWx+
37U/vMcje7q10+0g8xFj6q+/K4h03+jX722HDr7iJfeHz7SDJC66lJv3sgtPFdrI
1vGOsG3/VghCB3+CtJ7Be8oSD3rElLf2MxUG7mOK1C5JeigC85vUj8hwrwSZs5xD
BypFXxbwhUmXFOxFoFeKqk9I0Q9JUU2qsE262ilFpE73xnsgLt18gxTdgneplsRa
3QjsUBoq4l5vga/CJukhkHed+PCdqVQl1X1gILVvD+jXp2TejzdyhHWmsAO79u6u
/XtT2HN19V9/4oiFXZZlzM2ZJ7CvmjOz+aKBnVQybZTMLPZOJ0ayU1YBu5XpUnLs
pGFtNTMnKjd8mvUcSE3sTQ8Pd93XBvFkb8/eA8nRSVZOVoazk5ZhLTH2K83V/69p
4LVRg/l/AjT/j+b/ETaCMQT0/J/m/9H7fzT/z5v/B0MDwNru/TxA4l55mi+1SzHG
ntXcF1Ve1LyBFel/0v8E0v+k/0n/k/7fcPpfd6WUoPZZOufDPkKB7XDDXV1dlyXa
YhrTb/p/FzrxFwDwAAA=

**Comment by revskills** [comment]
r2 -v
radare2 0.9.9-git 7743 @ darwin-little-x86-64 git.0.9.8-1393-g8bd3aba
commit: 8bd3aba9112bc3035804695a502849c1f55c7d45 build: 2015-04-27
r2 -A testcase

**Comment by radare** [comment]
cant reproduce with latest git, anyone else can try?
