### ISSUE TITLE
AddressSanitizer libr/util/str.c

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2452]
=================================================================
==13415==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61300000c909 at pc 0x7f19e56c4a41 bp 0x7fff03cc8360 sp 0x7fff03cc8350
READ of size 1 at 0x61300000c909 thread T0
    #0 0x7f19e56c4a40 in r_str_nlen /home/revskills/dev/radare2/libr/util/str.c:975
    #1 0x7f19e8f70a93 in r_bin_dwarf_parse_lnp_header /home/revskills/dev/radare2/libr/bin/dwarf.c:254
    #2 0x7f19e8f73bc6 in r_bin_dwarf_parse_line_raw2 /home/revskills/dev/radare2/libr/bin/dwarf.c:690
    #3 0x7f19e8f7983f in r_bin_dwarf_parse_line /home/revskills/dev/radare2/libr/bin/dwarf.c:1537
    #4 0x7f19e9d8240c in bin_dwarf /home/revskills/dev/radare2/libr/core/bin.c:462
    #5 0x7f19e9d8c1ec in r_core_bin_info /home/revskills/dev/radare2/libr/core/bin.c:1617
    #6 0x7f19e9d7e8bb in r_core_bin_set_env /home/revskills/dev/radare2/libr/core/bin.c:94
    #7 0x7f19e9d520ca in r_core_file_do_load_for_io_plugin /home/revskills/dev/radare2/libr/core/file.c:349
    #8 0x7f19e9d529ae in r_core_bin_load /home/revskills/dev/radare2/libr/core/file.c:476
    #9 0x4061fd in main /home/revskills/dev/radare2/binr/radare2/radare2.c:573
    #10 0x7f19e4ec3ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)
    #11 0x4030f8 (/home/revskills/dev/radare2/binr/radare2/radare2+0x4030f8)

0x61300000c909 is located 104658015245732 bytes insideASAN:SIGSEGV
==13415==AddressSanitizer

file from radare2-regressions: crash1 e820ac1f0957242cae7e802c6103e597 
radare2 0.9.9-git 7719 @ linux-little-x86-64 git.0.9.8-1369-gb0c520b
commit: b0c520b856a73959b15ff9c5538462bb76084b0b build: 2015-04-22

**Comment by radare** [comment]
reproduced. working on a fix
