### ISSUE TITLE
OSX packaging

### ISSUE THREAD

**Issue by radare** [radare/radare2#2461]
- [ ] Create launcher + icon in Applications
- [ ] Make uninstaller accessible with clicks
- [ ] Handle context menu to open with
- [ ] Install optional r2pipe bindings (nodejs, python, ruby, ...)
  - run pip, npm, gem, ...
- [ ] Check/Notify for updates

**Comment by XVilka** [comment]
@radare @Maijin  can you please check if some of those were already fixed?

**Comment by radare** [comment]
Nope not done but this probably makes more sense just in cutter. Let the cmdline be cmdline

**Comment by Maijin** [comment]
I never use icon for command line application, i find that useless tbh makes more sense for cutter yes. But the right click context why not?

**Comment by radare** [comment]
The right click thing depends on the terminal you use in your mac. -e is not possible so you have to do applescripts to make that shit to happen. Imho its overengineering. Lets just close this and let cutter handle this

**Comment by Maijin** [comment]
done
