### ISSUE TITLE
Customize JZ/JNZ instead of JE/JNE on x86

### ISSUE THREAD

**Issue by radare** [radare/radare2#2462]
http://capstone-engine.org/mnemonic.html

i think this should be the default... at least, for the ones who started doing low level stuff in the DOS era, jz looks better than je.

**Comment by jvoisin** [comment]
I prefer `jz/jnz`.

**Comment by jjdredd** [comment]
does it matter?

**Comment by wapiflapi** [comment]
Having the capstone default has the advantage of being consistent with other tools that use capstone.
The correct fix in my opinion lies upstream: A user configuration file for capstone produced disassembly.

**Comment by radare** [comment]
Let's discuss https://docs.google.com/a/nopcode.org/forms/d/1GOaavS-K0r1ga3tAFYkeSOT1RUTnjOXBTHGfWQmi1x8/viewform

**Comment by jpenalbae** [comment]
Maybe we could add an evaluable var to enable or disable mnemonics....

**Comment by radare** [comment]
yep, this can be an option as the one from asm.syntax=att/intel

and in fact.. this can be also replaced with the anal hints on every specific offset

**Comment by condret** [comment]
i prefere je/jne

**Comment by skuater** [comment]
i Preffer jz/jnz (msdos debug.exe good times) but in x64 the correct way to show its JE/JNE. 
Then dont matter the votes the correct way must be JE/JNE

**Comment by XVilka** [comment]
:+1: for JE/JNE

**Comment by jpenalbae** [comment]
Here is the summary of JE/JZ and JNE/JNZ instructions

```
| Opcode  | Instruction| Op/En| 64-Bit Mode| Compat/Leg Mode| Description    
| 74 cb   | JE rel8    | D    | Valid      | Valid          | Jump short if equal (ZF=1).    
| 0F 84 cw| JE rel16   | D    | N.S.       | Valid          | Jump near if equal (ZF=1). Not supported    
| 0F 84 cd| JE rel32   | D    | Valid      | Valid          | Jump near if equal (ZF=1).                  
| 74 cb   | JZ rel8    | D    | Valid      | Valid          | Jump short if zero (ZF ← 1).    
| 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported    
| 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1).                  
| 0F 84 cw| JZ rel16   | D    | N.S.       | Valid          | Jump near if 0 (ZF=1). Not supported    
| 0F 84 cd| JZ rel32   | D    | Valid      | Valid          | Jump near if 0 (ZF=1). JZ FARLABEL;
| 75 cb   | JNE rel8   | D    | Valid      | Valid          | Jump short if not equal (ZF=0).        
| 0F 85 cw| JNE rel16  | D    | N.S.       | Valid          | Jump near if not equal (ZF=0). Not supported
| 0F 85 cd| JNE rel32  | D    | Valid      | Valid          | Jump near if not equal (ZF=0).                  
| 75 cb   | JNZ rel8   | D    | Valid      | Valid          | Jump short if not zero (ZF=0).                  
| 0F 85 cw| JNZ rel16  | D    | N.S.       | Valid          | Jump near if not zero (ZF=0). Not supported 
| 0F 85 cd| JNZ rel32  | D    | Valid      | Valid          | Jump near if not zero (ZF=0).   
```

**Comment by condret** [comment]
i prefere je/jne because it is more semantic to have a compare-instruction folled by a jump_if_equal-instruction

**Comment by mrexodia** [comment]
@condret Or in case of `test eax, eax` a `JZ` is more logical. or in this case:
```asm
@loop:
; some useful loop
dec ecx ; decrease bytes left
jnz @loop ; jump while ecx is not zero
```

In this case JNE doesn't make any sense, since there is no comparison.

**Comment by radare** [comment]
I just add a hack to override je/jne with jz/jnz at asm.syntax=jz level. This option is only available under capstone-x86 plugin and it's just a workaround until capstone decides the proper way to do that.

**Comment by mrexodia** [comment]
You can already do it in a supported way? Just change the mnemonic...

**Comment by radare** [comment]
Yes, but its unnecesarily complicated and i didnt like the way this api was designed, so i expect it to disappear because there's no other use case for it.

Also, with anal hints you can change just hint a single instruction to do this postprocessing. So r2 allows to make the disasm more readable by hinting those jumps by hand or with automatic analysis in the future.

Anyway if this api seems to get some acceptance or more uses the plugin code can be changed easily. So i will do the same for the udis plugin.

**Comment by radare** [comment]
Meh, done with e asm.syntax=jz, also supports anal hinting
