### ISSUE TITLE
Add an api for RBin to override all internal binary information using Sdb

### ISSUE THREAD

**Issue by radare** [radare/radare2#2468]
As long as rbin gets sdbized it will be possible to override some keys from the binary this is, patching number of sections, offset, etc without altering the file.

**Comment by condret** [comment]
Uhm, I otten feel like the info provided by rbin is dupped in rio, or somewhere else, and the info in rbin does not really affect r2, after everything got loaded. Where is the winning point here?

**Comment by radare** [comment]
already discussed in other issues. closing
