### ISSUE TITLE
Add DES into libr/crypto

### ISSUE THREAD

**Issue by radare** [radare/radare2#2470]
https://github.com/ARMmbed/mbedtls/blob/development/library/des.c

**Comment by crowell** [comment]
In /hash/? Why?

**Comment by radare** [comment]
because libr_hash contains all crypto and checksuming algorithms of r2.
it abstracts the apis for AES, etc..

**Comment by ninjahacker** [comment]
I don't think so... 
libr/hash has hashing algorithms. 
libr/crypto has the cipher algorithms (only AES right now)

**Comment by radare** [comment]
Agree :)

**Comment by radare** [comment]
anyone wants to grab this task?

**Comment by Maijin** [comment]
@P4N74 is on it

**Comment by radare** [comment]
ok, will move back to 0.10.3 if done before the release :)
thx

**Comment by P4N74** [comment]
@Maijin, @radare I have fixed the key scheduling part and update the repo https://github.com/P4N74/radare2/tree/des . Currently I am busy with some other work so I am not able to look into the code and get the fix.

**Comment by radare** [comment]
can you send a PR with this branch please?

**Comment by radare** [comment]
https://github.com/P4N74/radare2/commits/des

**Comment by P4N74** [comment]
but it has some more issues iirc. The entire thing is still not working correctly. I might need to look at the endianess issue (if that's the problem). Should I send that irrespective of those error?

**Comment by radare** [comment]
ok then moving to 0.10.5, but if you open a PR we can review it, otherwise it will stay there forever and ocassionaly die. like all the other code that is not merged into master
