### ISSUE TITLE
nullEP.exe Entrypoint

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2471]
* nullEP.exe               PE with null EntryPoint (MZ is executed as dec ebp, pop edx)
* https://github.com/radare/radare2-regressions/blob/master/bins/pe/nullEP.exe
* Source: https://github.com/corkami/pocs/blob/master/PE/nullEP.asm

Right now R2 "creates" the entrypoint at 0x00400000

IdaPro prompt-asked: "Entry point 0x400000 is not loaded into the database. Do you want to load the missing data?" 
    
    If you press YES: then it creates the entrypoint at 0x00400000 named __ImageBase
    if you say NO, it doesn't creates the Entrypoint

**Comment by radare** [comment]
I think the main problem here is with yhe sections created by it. We need more tests for this binary to verify the correct entrypoint offset and contents in it.

**Comment by Maijin** [comment]
@radare https://github.com/radare/radare2-regressions/blob/master/t.formats/pe/nullEP 
* There is already a wrong test for entrypoint but needs to know if
** We keep 0x00400000 by default
** We display no EP by default

* I can add a secondary test which test if first instruction is `dec ebp`

**Comment by Maijin** [comment]
@alvarofe

**Comment by alvarofe** [comment]
This seems fixed also with my PR

**Comment by Maijin** [comment]
it was fixed prior the PR, the question is maybe a warning should be displayed to indicate the nullEP since `ie` display:

```
[Entrypoints]
vaddr=0x00400000 paddr=0x00000000 baddr=0x00400000 laddr=0x00000000 type=program

1 entrypoints
```

**Comment by Maijin** [comment]
That's fixed and tested !
