### ISSUE TITLE
Add support for sequence of instructions and help in /c

### ISSUE THREAD

**Issue by radare** [radare/radare2#2473]
```
> "/c jmp;nop;mov"
```

must search for a jmp followed by a nop and then another mov.
this syntax must support a way to specify that a kind of instruction (or group) can be repeated N times. I would suggest supporting plain sequencial instruction search and later extend it with higher level logic.

**Comment by crowell** [comment]
/c should support regular expression as well

**Comment by jjdredd** [comment]
isn't the first feature already done with comma delimiter atm?

**Comment by radare** [comment]
Test it or gtfo :)

**Comment by jjdredd** [comment]
ahaha, yes, output is quite messy:
```
:> /c push,mov
0x00002492   # 10: push 0x68000000mov eax, 0xe9000000
0x00002892   # 10: push 0x68000001mov eax, 0xe9000002
0x000029f0   # 3: push ebpmov ebp, esp
0x00002c34   # 6: push dword [esi + edx + 0xf]mov bh, 0x84
0x00002c36   # 9: push ssmovzx eax, word [esp + 0xce]
0x00003018   # 5: pushalmov dword [esp + 0x38], edx
0x000030d5   # 3: push dsmov edx, dword [esi]
0x000030d7   # 4: push ssmov eax, dword [edx + 0x14]
```

**Comment by radare** [comment]
Yeah seems to work. Would be nice to have a /c* with a nicer output to be consumed by r2.

I tried with ; because other commands like wa changed to use ; as a separator, maybe we should support both in /c or just change it to be only ;

**Comment by jvoisin** [comment]
I think that we should use `;` only since you may want to search for `mov eax, ecx`.
Also, it would be cool to put a `;` between the opcodes in the result ;)

**Comment by radare** [comment]
And handle * as a way to tell N random instructions, also we can handle *3 to sprcify at least 3 instructions between two:

/c mov eax;*3;int

And add search.maxops as a way to limit the number of instructions between two known ones

**Comment by jvoisin** [comment]
Regexps would be cooler:

```
/c (mov eax,*){3};int
```

**Comment by radare** [comment]
Making it as a standalone regex compiler with jit and hooking apis for extending the syntax and reuse it from other search loops would be even nicer :-)

**Comment by jvoisin** [comment]
59a64235d53e176549fff875cd53b33e89f42a02 improved a bit the results display, and replace the separator character with `;` instead of `,`.

**Comment by jvoisin** [comment]
I just added help in ae02d25b6804b75c7e093ffd3501589e282f8dd0

**Comment by b-ramsey** [comment]
Is there any progress on this, at the moment I have to search multiple times for varying distances between two known instructions. Unless I have missed that this has been implemented without me knowing, if so what is the syntax for this.

**Comment by Maijin** [comment]
It's in /c?
