### ISSUE TITLE
Make RMagic functionality available from rafind2

### ISSUE THREAD

**Issue by radare** [radare/radare2#2474]
As a way to replace `file`. Just as an alias for `r2 -nqcpm $FILE 2> /dev/null`

Discuss: Which flag take?

**Comment by jvoisin** [comment]
`-f` of course :)

**Comment by radare** [comment]
-f and -F are already taken unless we move it :p

We can also do that in rafind2, as a carver.

**Comment by Maijin** [comment]
+1 for rabin2

**Comment by radare** [comment]
Also, we want rafind2 to do /m too. Search.align is also important to be accessed from rafind2.
