### ISSUE TITLE
rax2 doesn't convert binary

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#2479]
I can't convert binary data to int or hex value

![rax2_convert](https://cloud.githubusercontent.com/assets/1186777/7441083/5f44d832-f0e8-11e4-8a4a-6df4af571c8f.png)

**Comment by radare** [comment]
You are doing it wrong. Read the documentation

**Comment by radare** [comment]
Well, mainly it does, but its wrapped to 64bits, not bignum

**Comment by Maijin** [comment]
@radare https://github.com/radare/radare2-regressions/blob/master/t.tools/rax2/rax2#L203-L208

**Comment by radare** [comment]
Long != Bignum

**Comment by Maijin** [comment]
Ah I didn't look at the screenshots, was thinking the same issue :p

**Comment by Maijin** [comment]
@kriw See also this ^

**Comment by Maijin** [comment]
btw @kriw are you on the telegram or the IRC ?

**Comment by kriw** [comment]
No, is it better to use the telegram or the IRC?

**Comment by Maijin** [comment]
telegram so you get the screenshots and the stickers

**Comment by kriw** [comment]
Is it needed to implement(or use library of) bignum so that we can calculate `bignum`+`bignum` ?

**Comment by Maijin** [comment]
Bignum is already here see https://github.com/radare/radare2/blob/master/libr/util/big.c
