### ISSUE TITLE
Wrong analysis of 16-bit relative call

### ISSUE THREAD

**Issue by Nodepad** [radare/radare2#2482]
Radare2 analyse 16-bit relative call wrong.
```
rasm2 -a x86 -b 16 -D 'e8fdff' 
0x00000000   3                   e8fdff  call 0x10000
```
But it should be call 0x0. This is issue of capstone because udis analyse it right.
```
rasm2 -a x86.udis -b 16 -D 'e8fdff'
0x00000000   3                   e8fdff  call 0x0
```

**Comment by radare** [comment]
This is a disassemble bug, not analysis one. And its related to capstone, not r2. Can you open an issue for capstone?

And reference it here? Will be good to have more 16bit x86 tests in our testsuite. Cc @maijin

Thanks!

**Comment by Nodepad** [comment]
Capstone related issue: https://github.com/aquynh/capstone/issues/352

**Comment by aquynh** [comment]
this is related to this issue https://github.com/aquynh/capstone/issues/111

at that time, i put in a fix & we have this at https://github.com/aquynh/capstone/blob/next/arch/X86/X86IntelInstPrinter.c#L632

```
			if (MI->csh->mode == CS_MODE_16 && imm > 0x100000)
				imm -= 0x10000;
```

now with this issue coming up, it seems i got the last fix wrong: that `0x100000` on the first line should be `0x10000` instead?

**Comment by Nodepad** [comment]
1. I guess issue is in loading immediate operand, it's loaded like unsigned instead of signed. I think function `MCOperand_getImm ` returns unsigned value: 0xfffd instead of -3 for my example above.
https://github.com/aquynh/capstone/blob/next/arch/X86/X86IntelInstPrinter.c#L627
```
int64_t imm = MCOperand_getImm(Op) + MI->flat_insn->size + MI->address;
```
2 .  About issue https://github.com/aquynh/capstone/issues/111
Why do you think that relative offsets should overlap in 16-bit mode? For example you can address same code with `f000:ffaa` or `fff0:00aa`. In second case there won't be overlapping. I guess this issue isn't the issue and it shouldn't be fixed

**Comment by radare** [comment]
Please comment this in the capstone issue, not the r2 one

**Comment by radare** [comment]
Updated to the latest -next, and its not fixed

**Comment by radare** [comment]
Fixed
