### ISSUE TITLE
r2  ~.. 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2484]
morn,

playing around with '~..'. Using twice crashes r2. (eg.~.., ^C, ~..)

http://radare.tv/a/58

Thanks to Sebastian, for providing the machine!

Cheers
zlul

```
r2 -v
radare2 0.9.9-git 7786 @ linux-little-x86-64 git.0.9.8-1433-g59a6423
commit: 59a64235d53e176549fff875cd53b33e89f42a02 build: 2015-05-03
 r2[13524]: segfault at 8 ip 00007f309e08e20a sp 00007ffc65d3a6f8
 error 4 in libc-2.21.so[7f309e00e000+199000]
```

**Comment by jjdredd** [comment]
sounds like my fault :P

**Comment by zonkzonk** [comment]
Throwing a TB117 at you. :P

**Comment by jjdredd** [comment]
looks like strlen() give undefined behavior if passes NULL

**Comment by zonkzonk** [comment]
@jjdredd  looks fixed :D

**Comment by jjdredd** [comment]
some tests failed, I'll make another fix
