### ISSUE TITLE
Visual mode add key to continue until cursor

### ISSUE THREAD

**Issue by radare** [radare/radare2#249]

**Comment by Maijin** [comment]
FYI: Shortcut in idapro is F4 for that feature

**Comment by radare** [comment]
Press c, move cursor, then f9

Its already done. There was another way before without using f keys, but it was confusing for some people

**Comment by Maijin** [comment]
@radare Wait no it's not working :p

http://radare.tv/a/34

**Comment by radare** [comment]
Which keys do you propose then?

**Comment by Maijin** [comment]
F4

**Comment by asutoshpalai** [comment]
Don't know if it's intentional or a bug, but while in cursor mode if we step using `s`, the behaviour is that of "continue until cursor".

Note: it doesn't happen if we use `f7` for stepping.

**Comment by radare** [comment]
It is on purpose. If it feels unnatural we can discuss to change this
