### ISSUE TITLE
Abillity  to break at fork.

### ISSUE THREAD

**Issue by omfgroflbbq** [radare/radare2#2494]
As far as I know currently radare2 isn't able to debug processes that fork.
There is the "dcf" command which runs "dcs vfork" but it doesn't seem to break when a fork is occuring.

Using gdb it's possible to execute "catch fork", and it would break when a fork occurs.

Steps to reproduce using the tiny_bash* binary:

1) [user@box]$ r2 -d ./tiny_bash 1234
2) [0x00400eab]> dcf
3) [user@box]$ nc localhost 1234

Output:
[+] Running 'dcs vfork' behind the scenes...
Running child until syscalls:58 57 
--> sn 0x7ff0540b828d syscall 13 rt_sigaction (0x11 0x7ffec756d4f0 0x0)
--> sn 0x7ff05416a1c7 syscall 41 socketcall (0x2 0x1)
--> sn 0x7ff05416a16a syscall 54 setsockopt (0x6 0x1 0x2 0x7ffec756d658 0x4)
--> sn 0x7ff054169d37 syscall 49 bind (0x6 0x7ffec756d710 0x10)
--> sn 0x7ff054169e57 syscall 50 listen (0x6 0x80)
--> sn 0x7ff054169ce0 syscall 43 accept (0x6 0x7ffec756d720 0x7ffec756d654)
--> sn 0x7ff05415bf84 syscall 5 fstat (0x1 0x7ffec756ce70)
--> sn 0x7ff05416514a syscall 9 mmap (0x0 0x1000 0x3 0x22 0xffffffff 0x0)
--> sn 0x7ff05415c620 syscall 1 write (0x1 0x7ff054649000 0x23)
Accepted connection from 127.0.0.1
--> sn 0x7ff05413a7e4 syscall 56 clone (0x1200011 0x0 0x0 0x7ff0546399d0)
--> sn 0x7ff05415cbe0 syscall 3 close (0x7)
--> sn 0x7ff054169ce0 syscall 43 accept (0x6 0x7ffec756d720 0x7ffec756d654)

The tiny_bash binary can be found at: https://github.com/ctfs/write-ups-2015/blob/master/volgactf-quals-2015/pwn/bash/tiny_bash

**Comment by jjdredd** [comment]
imho r2 has the ability to break anywhere, anytime

**Comment by radare** [comment]
@jjdredd this probably never worked well, or was poorly tested. the way to do that is with `r2 -e dbg.forks=true`, dont close the issue as long as `dcf` must be fixed, but this is not going to happen before the release. @skuater and me we are working behind the scenes redesigning the debugger and making some lists of things to address. And this is on the list. but as i said many times i didnt focused on the debugger yet in r2.

Thanks for reporting
