### ISSUE TITLE
dxgkrnl.sys confuses radare2

### ISSUE THREAD

**Issue by jrmuizel** [radare/radare2#2499]
Steps to reproduce:
wget http://people.mozilla.org/~jmuizelaar/dxgkrnl.sys
rabin2 -PP dxgkrnl.sys 
radare2 dxgkrnl.sys
> .!rabin2 -rP dxgkrnl.pdb
> s 0x00065090
> pd 5
           ;-- pdb._SubmitPresentHistoryToken_DXGCONTEXT__QEAAJPEBU_D3DKMT_PRESENTHISTORYTOKEN__PEAVCOREDEVICEACCESS__PEAVCWin32kLocks__HPEAT_LARGE_INTEGER___Z:
           0x00065090    0000         add byte [rax], al
           0x00065092    00418b       add byte [rcx - 0x75], al
           0x00065095    cdff         int 0xff
              read (0x0,0x0,0x0) ; section_end..reloc
           0x00065097    156c27fcff   adc eax, 0xfffc276c
           0x0006509c    8b0e         mov ecx, dword [rsi]

The bytes being disassembled here don't match llvm-objdump

**Comment by crowell** [comment]
what does llvm-objdump give?

On Tue, May 5, 2015 at 4:57 PM, Jeff Muizelaar <notifications@github.com>
wrote:

> Steps to reproduce:
> wget http://people.mozilla.org/~jmuizelaar/dxgkrnl.sys
> rabin2 -PP dxgkrnl.sys
> radare2 dxgkrnl.sys
>
> .!rabin2 -rP dxgkrnl.pdb
> s 0x00065090
> pd 5
> ;--
> pdb._SubmitPresentHistoryToken_DXGCONTEXT__QEAAJPEBU_D3DKMT_PRESENTHISTORYTOKEN__PEAVCOREDEVICEACCESS__PEAVCWin32kLocks__HPEAT_LARGE_INTEGER___Z:
> 0x00065090 0000 add byte [rax], al
> 0x00065092 00418b add byte [rcx - 0x75], al
> 0x00065095 cdff int 0xff
> read (0x0,0x0,0x0) ; section_end..reloc
> 0x00065097 156c27fcff adc eax, 0xfffc276c
> 0x0006509c 8b0e mov ecx, dword [rsi]
>
> The bytes being disassembled here don't match llvm-objdump
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2499>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by jrmuizel** [comment]
llvm-objdump gives:
   
   65090:       48 89 5c 24 10                                  movq    %rbx, 16(%rsp)
   65095:       48 89 6c 24 18                                  movq    %rbp, 24(%rsp)
   6509a:       48 89 74 24 20                                  movq    %rsi, 32(%rsp)
   6509f:       57                                              pushq   %rdi
   650a0:       41 54                                           pushq   %r12
   650a2:       41 55                                           pushq   %r13
   650a4:       41 56                                           pushq   %r14
   650a6:       41 57                                           pushq   %r15
   650a8:       48 81 ec f0 00 00 00                            subq    $240, %rsp

**Comment by radare** [comment]
@skuater can you have a look at this issue?

**Comment by skuater** [comment]
Sure.

**Comment by jrmuizel** [comment]
It looks like the difference comes from the ImageBase field of dxgkrnl.sys. ImageBase is 0x10000 and it seems like this confuses radare about what's where because some places add ImageBase and some don't.

**Comment by skuater** [comment]
@ jrmuizel hi, can you paste me ur llvm-objdump command line.

Im looking the code at address u pointed and don its a dissasembled adress this address land inside a opcode correct addresses are, 65080,65082,6508d,65093 but 65090 still invalid.

The pdb file point to this address but dont have sense, are u sure its the correct version of .pdb file?

This its the dissasembled code at correct adrress.
0000000000065082
0000000000065082                 mov     [rsp+108h+arg_50], 0DB6h
000000000006508D                 mov     r13d, 2
0000000000065093                 mov     ecx, r13d
0000000000065096                 call    cs:WdLogNewEntry5
000000000006509C                 mov     ecx, [rsi]
000000000006509E                 xor     edx, edx
00000000000650A0                 mov     [rax+20h], rcx
00000000000650A4                 mov     ecx, [rsi+4]
00000000000650A7                 mov     r11, rax
00000000000650AA                 mov     [rax+28h], rcx

**Comment by skuater** [comment]
pdb file is correct. checked

**Comment by skuater** [comment]
Confirmed rebase problem the pdb parser dont apply the 0x10000 imagebase all the flags are incorrects.
