### ISSUE TITLE
AddressSanitizer p/bin_xbe.c

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2501]
==20314==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffdb11bba70 at pc 0x7fbe57e0cc2c bp 0x7ffdb11bb920 sp 0x7ffdb11bb0c8
READ of size 263 at 0x7ffdb11bba70 thread T0
    #0 0x7fbe57e0cc2b in strdup (/lib64/libasan.so.1+0x34c2b)
    #1 0x7fbe56d2d9dc in info /home/revskills/dev/radare2/libr/..//libr/bin/p/bin_xbe.c:276
    #2 0x7fbe56c60a8a in r_bin_object_set_items /home/revskills/dev/radare2/libr/bin/bin.c:421
    #3 0x7fbe56c642c1 in r_bin_object_new /home/revskills/dev/radare2/libr/bin/bin.c:944
    #4 0x7fbe56c64f6e in r_bin_file_new_from_bytes /home/revskills/dev/radare2/libr/bin/bin.c:1055
    #5 0x7fbe56c628e0 in r_bin_load_io_at_offset_as_sz /home/revskills/dev/radare2/libr/bin/bin.c:644
    #6 0x7fbe56c629db in r_bin_load_io_at_offset_as /home/revskills/dev/radare2/libr/bin/bin.c:666
    #7 0x7fbe56c61e0e in r_bin_load_io /home/revskills/dev/radare2/libr/bin/bin.c:546
    #8 0x7fbe57a50c5a in r_core_file_do_load_for_io_plugin /home/revskills/dev/radare2/libr/core/file.c:344
    #9 0x7fbe57a51593 in r_core_bin_load /home/revskills/dev/radare2/libr/core/file.c:476
    #10 0x406188 in main /home/revskills/dev/radare2/binr/radare2/radare2.c:573
    #11 0x7fbe52bc7fdf in __libc_start_main (/lib64/libc.so.6+0x1ffdf)
    #12 0x4030d8 (/home/revskills/dev/radare2/binr/radare2/radare2+0x4030d8)

0x7ffdb11bba70 is located 119832471187254 bytes insideASAN:SIGSEGV
==20314==AddressSanitizer:

file: http://revskills.cz/r2/0fda269757fb09e36daca69c26f54fdb
radare2 0.9.9-git 7812 @ linux-little-x86-64 git.0.9.8-1404-g5b984e8
commit: 5b984e8a71ca59e424d62140cc1d707da5f057b6 build: 2015-05-06

**Comment by radare** [comment]
can't reproduce
