### ISSUE TITLE
AddressSanitizer format/mach0/mach0.c:1082 *

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2504]
Note this is a _write_ :

==20352==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62600000eb88 at pc 0x7fe6ff2c13dd bp 0x7ffef55c2910 sp 0x7ffef55c2900
WRITE of size 8 at 0x62600000eb88 thread T0
    #0 0x7fe6ff2c13dc in get_relocs_64 /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:1082
    #1 0x7fe6ff2b48a2 in relocs /home/revskills/dev/radare2/libr/..//libr/bin/p/bin_mach0.c:215
    #2 0x7fe6ff231c07 in r_bin_object_set_items /home/revskills/dev/radare2/libr/bin/bin.c:424
    #3 0x7fe6ff2352c1 in r_bin_object_new /home/revskills/dev/radare2/libr/bin/bin.c:944
    #4 0x7fe6ff235f6e in r_bin_file_new_from_bytes /home/revskills/dev/radare2/libr/bin/bin.c:1055
    #5 0x7fe6ff2338e0 in r_bin_load_io_at_offset_as_sz /home/revskills/dev/radare2/libr/bin/bin.c:644
    #6 0x7fe6ff2339db in r_bin_load_io_at_offset_as /home/revskills/dev/radare2/libr/bin/bin.c:666
    #7 0x7fe6ff232e0e in r_bin_load_io /home/revskills/dev/radare2/libr/bin/bin.c:546
    #8 0x7fe700021c5a in r_core_file_do_load_for_io_plugin /home/revskills/dev/radare2/libr/core/file.c:344
    #9 0x7fe700022593 in r_core_bin_load /home/revskills/dev/radare2/libr/core/file.c:476
    #10 0x406188 in main /home/revskills/dev/radare2/binr/radare2/radare2.c:573
    #11 0x7fe6fb198fdf in __libc_start_main (/lib64/libc.so.6+0x1ffdf)
    #12 0x4030d8 (/home/revskills/dev/radare2/binr/radare2/radare2+0x4030d8)

0x62600000eb88 is located 87269352792142 bytes insideASAN:SIGSEGV
==20352==AddressSanitizer

file: http://revskills.cz/r2/95b8e3ae758db3f129b776200ae9d357
radare2 0.9.9-git 7812 @ linux-little-x86-64 git.0.9.8-1404-g5b984e8
commit: 5b984e8a71ca59e424d62140cc1d707da5f057b6 build: 2015-05-06

**Comment by alvarofe** [comment]
This commit is prior to this https://github.com/radare/radare2/commit/3b04c5442b4e62d82571258cad8dd30558baa57c but anyway I will try with your files ;) Thanks again

**Comment by alvarofe** [comment]
I can't reproduce this

**Comment by dequis** [comment]
Mostly-duplicate of #2465, already fixed by 3b04c54
