### ISSUE TITLE
AddressSanitizer SEGV format/mach0/mach0.c:1067

### ISSUE THREAD

**Issue by revskills** [radare/radare2#2512]
ASAN:SIGSEGV
=================================================================
==23291==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000f8 (pc 0x7fd2714456f3 sp 0x7ffe4c2f1060 bp 0x7ffe4c2f1180 T0)
    #0 0x7fd2714456f2 in get_relocs /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:1067
    #1 0x7fd2714391be in relocs /home/revskills/dev/radare2/libr/..//libr/bin/p/bin_mach0.c:215
    #2 0x7fd2713c7c07 in r_bin_object_set_items /home/revskills/dev/radare2/libr/bin/bin.c:424
    #3 0x7fd2713cb2c1 in r_bin_object_new /home/revskills/dev/radare2/libr/bin/bin.c:944
    #4 0x7fd2713cbf6e in r_bin_file_new_from_bytes /home/revskills/dev/radare2/libr/bin/bin.c:1055
    #5 0x7fd2713c98e0 in r_bin_load_io_at_offset_as_sz /home/revskills/dev/radare2/libr/bin/bin.c:644
    #6 0x7fd2713c99db in r_bin_load_io_at_offset_as /home/revskills/dev/radare2/libr/bin/bin.c:666
    #7 0x7fd2713c8e0e in r_bin_load_io /home/revskills/dev/radare2/libr/bin/bin.c:546
    #8 0x7fd2721b7c5a in r_core_file_do_load_for_io_plugin /home/revskills/dev/radare2/libr/core/file.c:344
    #9 0x7fd2721b8593 in r_core_bin_load /home/revskills/dev/radare2/libr/core/file.c:476
    #10 0x406188 in main /home/revskills/dev/radare2/binr/radare2/radare2.c:573
    #11 0x7fd26d32efdf in __libc_start_main (/lib64/libc.so.6+0x1ffdf)
    #12 0x4030d8 (/home/revskills/dev/radare2/binr/radare2/radare2+0x4030d8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/revskills/dev/radare2/libr/..//libr/bin/p/../format/mach0/mach0.c:1067 get_relocs
==23291==ABORTING

file: http://revskills.cz/r2/fad9a3cdee6800a100146ff0a3e8c55f
radare2 0.9.9-git 7812 @ linux-little-x86-64 git.0.9.8-1404-g5b984e8
commit: 5b984e8a71ca59e424d62140cc1d707da5f057b6 build: 2015-05-06

**Comment by alvarofe** [comment]
I can't reproduce this

**Comment by dequis** [comment]
Mostly-duplicate of #2465, already fixed by 3b04c54
