### ISSUE TITLE
Cheat Search

### ISSUE THREAD

**Issue by radare** [radare/radare2#2513]
Define a common interface in r2 to ease this procedure. For example:

* Search for a value in a specific range (using /v on search.in=dbg.maps)
* Check which of those hits contain a new value
* Reduce this way with multiple accumulated search to find the exact position of the struct we are looking for

**Comment by jvoisin** [comment]
We should borrow ideas and syntax from [gameconqueror]( https://github.com/scanmem/scanmem/blob/master/gui/README )

**Comment by radare** [comment]
This feature is already implemented in the mame debugger

**Comment by radare** [comment]
Dup of https://github.com/radare/radare2/issues/3086
