### ISSUE TITLE
PE_(r_bin_pe_init_hdr) uses deprecated 'struct timezone', breaks clang/pedantic builds

### ISSUE THREAD

**Issue by dequis** [radare/radare2#2516]
The clang and pedantic builds in jenkins define `-D_XOPEN_SOURCE=700`, and `struct timezone` doesn't exist there, and this is why they fail.

`PE_(r_bin_pe_init_hdr)` in `libr/bin/format/pe/pe.c`:

``` c
    // adding compile time to the SDB
    {
        struct timezone tz;
        struct timeval tv;
        int gmtoff;
        char *timestr;
        time_t ts = (time_t)bin->nt_headers->file_header.TimeDateStamp;
        sdb_num_set (bin->kv, "image_file_header.TimeDateStamp",
            bin->nt_headers->file_header.TimeDateStamp, 0);
        gettimeofday (&tv, &tz);
        gmtoff = (int)(tz.tz_minuteswest*60); // in seconds
        ts += gmtoff;
        timestr = r_str_chop (strdup (ctime (&ts)));
       // gmt offset for pe date is t->tm_gmtoff
        sdb_set_owned (bin->kv,
            "image_file_header.TimeDateStamp_string",
            timestr, 0);
    }
```

Cutting only the relevant part:

``` c
        gettimeofday (&tv, &tz);
        gmtoff = (int)(tz.tz_minuteswest*60); // in seconds
        ts += gmtoff;
```

So it's using `gettimeofday()` (an obsolete function, but still part of posix) to get the current timezone of the system it's running on, and store it in `struct timezone` (a deprecated struct that isn't part of posix anymore)

This was added in 3b4773d6

**Comment by radare** [comment]
What should we use instead? Whats the correct apis to use?

**Comment by dequis** [comment]
Dunno. I was hoping this thing would be unnecessary

Googling a bit gets me [this stackoverflow question][1] which suggests using a BSD/GNU extension in the first answer, and `extern long timezone` in the second. Not sure how standard the latter is, but apparently it doesn't account for DST.

[1]: http://stackoverflow.com/questions/13804095/get-the-time-zone-gmt-offset-in-c

**Comment by radare** [comment]
I think the best solution for this problem consists in implementing our own unixtime APIs, ignoring system configuration and allowing to convert from ut64 to char* formatted date.

**Comment by dequis** [comment]
Not sure about going all the way reinventing the APIs, but the same commit that introduced this issue (3b4773d602e3467f8d535d08000b7e3297c9d3ca) also introduced the time.zone setting, saved in `core->print->datezone` as a number of hours. Using that instead seems simpler.

**Comment by radare** [comment]
yep, but not fully correct, a timezone is not just an hour shifting
