### ISSUE TITLE
Expose baddr information to r2 in a flag or in bin.baddr

### ISSUE THREAD

**Issue by radare** [radare/radare2#2523]
useful to do stuff like this:
```
f baddr=0x8048000
fs symbols
.f*baddr
```

**Comment by radare** [comment]
This is how it works right now. but only for the debugger

**Comment by ret2libc** [comment]
Please check if it's ok now. bin.baddr is considered when doing reloading of bin and it should be always set to the effective value of the base address.

**Comment by radare** [comment]
Yep this was the expected behaviour. As far as i have tested its fine now
