### ISSUE TITLE
Escape quotes when saving comments to project

### ISSUE THREAD

**Issue by qsantos** [radare/radare2#2531]
A comment like `open("/proc/self/maps")` will result in `"CCu open("/proc/self/maps")" @ …` in the project file. Quotes should therefore be escaped in comments, or not used in the project file (why are most lines between quotes?).

**Comment by radare** [comment]
Because in r2 quotes work in a whole. You quote the whole command instead of the string. So this text will be properly saved and restored

**Comment by qsantos** [comment]
I noticed this bug because my comment got truncated to `open(`. I guess the best thing to do would be to make sure to {,un}escape the comments. My question was triggered by the fact that it feels odd to see so many quoted commands in a configuration file.

**Comment by radare** [comment]
Ideally all the project information should be stored in Sdb, so there will be a native sync to disk without having to serialize the information by hand. But i still find useful to be able to export the information of every command in a textual form

**Comment by radare** [comment]
should be fixed because we save comments in base64 now

**Comment by radare** [comment]
(please confirm and add test if possible)
