### ISSUE TITLE
rabin2 -rP win32k.pdb crashes

### ISSUE THREAD

**Issue by jrmuizel** [radare/radare2#2532]
I get:
WARNING: bin_strings buffer is too big (0x004bac00)
parse_sval()::oops
parse_sval()::oops
parse_sval()::oops
parse_sval()::oops
parse_sval()::oops
parse_sval()::oops
get_sval_name::oops
get_sval_val::oops
get_sval_name::oops
Segmentation fault (core dumped)

with https://people.mozilla.org/~jmuizelaar/p/win32k.pdb

**Comment by jrmuizel** [comment]
This patch fixes the problem:
http://people.mozilla.org/~jmuizelaar/pdb-parse.patch

**Comment by Maijin** [comment]
@jrmuizel what about a pull request ?

**Comment by XVilka** [comment]
@Maijin crafted the PR, based on the publicly available metadata https://github.com/radare/radare2/pull/2539
