### ISSUE TITLE
Java Commands output on stderr

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2538]
See test created here doesn't pass cause of this problem https://github.com/radare/radare2-regressions/commit/c87d478429a4ac16d7a598645d8a2460cc6a78f8
But also java commands in general output on stderr.

`eprintf` should be replaced by `r_cons_printf`

**Comment by radare** [comment]
IGNORE_ERR

**Comment by Maijin** [comment]
@radare yes that could be used but as far as I know those ouput are not errors

**Comment by radare** [comment]
Fixed
