### ISSUE TITLE
PDB parser improvement - dump also functions with arguments

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2540]
For example show

```
HRESULT __stdcall RegisterApplicationRecoveryCallback(APPLICATION_RECOVERY_CALLBACK pRecoveyCallback, PVOID pvParameter, DWORD dwPingInterval, DWORD dwFlags)
```

instead of just `RegisterApplicationRecoveryCallback`

**Comment by inisider** [comment]
This is possible to do with help of msvc demangler that has been  already implemented.
It will be good if someone start to test it and push bugs ;)

**Comment by XVilka** [comment]
See also this implementation of PDB parser https://github.com/google/syzygy/tree/master/syzygy/pdb

**Comment by XVilka** [comment]
And this documentation as well
