### ISSUE TITLE
[WINDOWS] Auto update radare2.exe (like Google Chrome)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2542]
So users will be always notified about a new version

Something based on https://github.com/vslavik/winsparkle could be a solution.

**Comment by jvoisin** [comment]
![sparkles]( http://image.blingee.com/images19/content/output/000/000/000/7cd/808451525_1313859.gif )

**Comment by XVilka** [comment]
@jvoisin Here is it how it works:
https://github.com/vslavik/winsparkle/wiki/User-Experience

**Comment by radare** [comment]
http://sparkle-project.org/ for osx

**Comment by revskills** [comment]
-https://github.com/oneget/oneget
-Windows Store?
-winsparkle

**Comment by crowell** [comment]
windows store is not a good solution as it is only for win8+, most(?)
windows users are on win7 still i think.

On Sun, May 10, 2015 at 4:42 PM, revskills <notifications@github.com> wrote:

> -https://github.com/oneget/oneget
> -Windows Store?
> -winsparkle
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2542#issuecomment-100697725>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
Please move this issue to the correct repo

**Comment by radare** [comment]
Moved to https://github.com/radare/radare2-win-installer/issues/3
