### ISSUE TITLE
rasm2 - incorrect instructions for MSP430

### ISSUE THREAD

**Issue by movEAX** [radare/radare2#2547]
`rasm2 -a msp430 -d ...`

| bytes  | returns                | expected                 |
|--------|------------------------|--------------------------|
|1b53    | `inc #1`               |  `inc r11`               |
|3441    |`pop @r1+`              | `pop r4`                 |
|3b41    |`pop @r1+`              | `pop r11`                |
|0b63    | `adc #0, r11`          | `adc r11`                |
|4b63    | `adc.b #0, r11`        |`adc.b r11`               |
|0ba3    | `dadc #0 `             |`dadc r11`                |
|4ba3    | `dadc.b #0`            |`dadc.b r11`              |
|1b83    | `dec #1`               |`dec r11`                 |
|5b83    | `dec.b #1`             |`dec.b r11`               |
|0b73    | `sbc #0`               |`sbc r11`                 |
|4b73    | `sbc.b #0`             |`sbc.b r11`               |
|12d3    | `bis #1, r2`           |`setc`                    |
|22d3    |`setn`                  |`setz`                    |

**Comment by radare** [comment]
Can you send a pullreq for the testsuite?

**Comment by movEAX** [comment]
https://github.com/radare/radare2-regressions/pull/182

**Comment by XVilka** [comment]
so, can this be closed now?

**Comment by movEAX** [comment]
But bug not fixed yet. Why issue should be closed?

**Comment by radare** [comment]
It should be fixed, not closed :)

**Comment by m403** [comment]
Sorry for the mess, the last ref. issue is the correct one.
