### ISSUE TITLE
Invalid read in r_bin_dwarf_parse_lnp_header when doing rabin2 -d of rabin2 itself

### ISSUE THREAD

**Issue by dequis** [radare/radare2#2555]
Did this `valgrind -v rabin2 -d /usr/bin/rabin2`. Got this:

```
==26501== 1 errors in context 1 of 1:
==26501== Invalid read of size 1
==26501==    at 0x5CF3CA2: vfprintf (in /usr/lib/libc-2.21.so)
==26501==    by 0x5CFA096: fprintf (in /usr/lib/libc-2.21.so)
==26501==    by 0x538D7F1: r_bin_dwarf_parse_lnp_header (dwarf.c:261)
==26501==    by 0x538EDBF: r_bin_dwarf_parse_line_raw2 (dwarf.c:695)
==26501==    by 0x5391751: r_bin_dwarf_parse_line (dwarf.c:1517)
==26501==    by 0x4EC0B53: bin_dwarf (bin.c:465)
==26501==    by 0x4EC51B9: r_core_bin_info (bin.c:1631)
==26501==    by 0x404B7D: main (rabin2.c:792)
==26501==  Address 0x9cdbc68 is 0 bytes after a block of size 3,288 alloc'd
==26501==    at 0x4C2C080: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==26501==    by 0x53916DB: r_bin_dwarf_parse_line (dwarf.c:1509)
==26501==    by 0x4EC0B53: bin_dwarf (bin.c:465)
==26501==    by 0x4EC51B9: r_core_bin_info (bin.c:1631)
==26501==    by 0x404B7D: main (rabin2.c:792)
```

Line numbers correspond to 96a44f8ebf2c3f8e19f37ad89d1b0b50015b71e0

The relevant part of the output looks like this:

```
DWARF LINE HEADER
  total_length: -468843518
  version: 512
  header_length: : 6688516
  mininstlen: 2
  is_stmt: 4
  line_base: 16
  line_range: 130
  opcode_base: 0
INCLUDEDIR (�)
INCLUDEDIR (t
INCLUDEDIR (
INCLUDEDIR (�)
INCLUDEDIR (f)
INCLUDEDIR t)
INCLUDEDIR (C)
INCLUDEDIR (    �)
```

The INCLUDEDIR lines are the ones that have invalid reads. The real issue is when it starts reading the line header at some location where it shouldn't, but I have no idea about any of this dwarf code does, so uh, better leave it to someone else.

Also, ASAN doesn't catch this because it doesn't instrument fprintf.

If you happen to need the binary i used for whatever reason, http://dequis.org/rabin2 - it also happens with the r2 binary and other programs i've built with debug symbols here.

**Comment by radare** [comment]
where’s the fix? :D

**Comment by dequis** [comment]
uhhh..

>but I have no idea about any of this dwarf code does, so uh, better leave it to someone else.

I'm submitting this bug as a result of looking for a few hours and giving up.

**Comment by radare** [comment]
Ok will fix tonight. Thabks for reporting. Will add test as soon as fixed

**Comment by dequis** [comment]
But that doesn't fix the fact that the header contents are gibberish.

```
DWARF LINE HEADER
  total_length: -468843518
  version: 512
  header_length: : 6688516
  mininstlen: 2
  is_stmt: 4
  line_base: 16
  line_range: 130
  opcode_base: 0
```

**Comment by radare** [comment]
it fixes the issue which says “invaild read in ..”, now there are no invalid reads acording to asan or valgrind, but the parsing problem is another problem that should be addressed with more time, fixing the crash is the first step.

i would ping the author @montekki before going deeper in the issue. Because this can be produced by a regression. which should be addressed by checking which commit broke that (first try with older versions of that parser).
