### ISSUE TITLE
arm registers not available in thumb mode

### ISSUE THREAD

**Issue by slorquet** [radare/radare2#2557]
I have an stm32f4 target hooked to openocd, the setup is functional since I can debug my app with arm-none-eabi-gdb the usual way.

I attempt to control the target using radare 2, using this command line:

/home/joe/sys/bin/radare2 -a arm.gnu -b 16 -D gdb gdb://localhost:3333

This is the output:

```
joe@nuc:~/radare2$ /home/joe/sys/bin/radare2 -a arm.gnu -b 16 -D gdb gdb://localhost:3333
r_debug_select: 3 3
XWJSTEP TOFALSE
Not supported register profile
pid = 13952560 tid = 0
r_debug_select: 13952560 0
r_reg_get_value: null or oob arena for current regset
etc etc etc
```

Not supported register profile.

Is anything planned to fix this?

thanks!

edit: I have the latest code from today...

edit2: reading the memoy works:

```
  [0x00000000]> px
  - offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
  0x00000000  0010 0020 4503 0008 a103 0008 a103 0008  ... E...........
  0x00000010  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000020  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000030  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000040  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000050  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000060  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000070  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000080  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x00000090  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x000000a0  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x000000b0  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x000000c0  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x000000d0  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x000000e0  a103 0008 a103 0008 a103 0008 a103 0008  ................
  0x000000f0  a103 0008 a103 0008 a103 0008 a103 0008  ................
```

**Comment by slorquet** [comment]
Hmm, I think this patch would not hurt:

~~~
diff --git a/libr/debug/p/debug_gdb.c b/libr/debug/p/debug_gdb.c
index b9bc79f..2d607ac 100644
--- a/libr/debug/p/debug_gdb.c
+++ b/libr/debug/p/debug_gdb.c
@@ -145,7 +145,7 @@ eprintf ("XWJSTEP TOFALSE\n");
                                // TODO
                                break;
                        case R_SYS_ARCH_ARM:
-                               if ( dbg->anal->bits == 32 ) {
+                               if ( dbg->anal->bits == 16 || dbg->anal->bits == 32 ) {
                                        gdbr_set_architecture(&g->desc, ARM_32);
                                } else if (dbg->anal->bits == 64) {
                                        gdbr_set_architecture(&g->desc, ARM_64);
~~~

**Comment by radare** [comment]
the gdb-arm backend is not working and has never tested so far. it should be easy to fix. if i have some spare time i can have a look at it.

cc @defragger

**Comment by slorquet** [comment]
We crossed, I have a small patch in the correct direction, I think.

**Comment by slorquet** [comment]
I am starting to understand, by instrumenting the code with printfs:

~~~
joe@nuc:~/radare2$ /home/joe/sys/bin/radare2 -a arm.gnu -b 16 -D gdb gdb://localhost:3333
r_debug_gdb_reg_profile: dbg->anal->bits=64, dbg->bits=8, val16=2 val32=4
r_debug_gdb_reg_profile: dbg->anal->bits=16, dbg->bits=8, val16=2 val32=4
r_debug_select: 3 3
r_debug_gdb_reg_profile: dbg->anal->bits=16, dbg->bits=8, val16=2 val32=4
XWJSTEP TOFALSE
~~~

Is there any reason why r_debug_gdb_reg_profile uses dbg->anal->bits for the x86 target, but not for the arm target?

**Comment by radare** [comment]
printf is the best multiplatform debugger out there. All for you then :) so it's failing at the first check? it should be using it in all cases, but maybe its used it before being initialized by -b

**Comment by slorquet** [comment]
crosspost again, see my previous message, I have a seemingly better patch, but the dr commands does not show anything now.

**Comment by radare** [comment]
dr shows nothing probably because there's no such thing as thumb register profile, because its shared with arm. you can "workaround" this by using "dr 32". in fact you can change the register profile at any time, so it should not be a problem if it fails at first try

**Comment by radare** [comment]
There was a proposal to keep a single shared struct exposing arch+bits used by asm, anal, debug, ... but im afraid this can break something if not properly tested.

**Comment by slorquet** [comment]
~~~
[0x00000000]> dr 32
0x00000000
[0x00000000]> dr all
0x00000000
[0x00000000]> drl
lr
pc
r0
r1
r2
r3
r4
r5
r6
r7
r8
r9
r10
r11
r12
r13
r14
r15
f0
f1
f2
f3
f4
f5
f6
f7
fps
cpsr
~~~

interesting... so register value retrieval and display seems to be broken, since the official reg names are known...

**Comment by slorquet** [comment]
Moar:
~~~
[0x00000000]> drb
0x00000000  0x00000000 0x00000000 0x00000000 0x00000000  ................
0x00000010  0x00000000 0x00000000 0x00000000 0x00000000  ................
0x00000020  0x00000000 0x00000000 0x00000000 0x00000000  ................
0x00000030  0x00000000 0x00000000 0x00000000 0x00000000  ................
0x00000040  0x00000000                                ....
[0x00000000]> drp
=pc     r15
=sp     r14
=a0     r0
=a1     r1
=a2     r2
=a3     r3
gpr     lr      .32     56      0
gpr     pc      .32     60      0
gpr     r0      .32     0       0
gpr     r1      .32     4       0
gpr     r2      .32     8       0
gpr     r3      .32     12      0
gpr     r4      .32     16      0
gpr     r5      .32     20      0
gpr     r6      .32     24      0
gpr     r7      .32     28      0
gpr     r8      .32     32      0
gpr     r9      .32     36      0
gpr     r10     .32     40      0
gpr     r11     .32     44      0
gpr     r12     .32     48      0
gpr     r13     .32     52      0
gpr     r14     .32     56      0
gpr     r15     .32     60      0
gpr     f0      .96     64      0
gpr     f1      .96     76      0
gpr     f2      .96     88      0
gpr     f3      .96     100     0
gpr     f4      .96     112     0
gpr     f5      .96     124     0
gpr     f6      .96     136     0
gpr     f7      .96     148     0
gpr     fps     .96     160     0
gpr     cpsr    .32     172     0
~~~

**Comment by radare** [comment]
bear in mind that thumb and arm debugger works fine on linux-arm and ios-arm, so the bug is gdb-specific

**Comment by slorquet** [comment]
Hello,

no, the fix is not OK.

dbg->bits == R_SYS_BITS_64 is not the correct test. This variable is not even tested for x86

With this commit I still get a bunch of 
r_reg_get_value: null or oob arena for current regset
r_reg_get_value: null or oob arena for current regset
r_reg_get_value: null or oob arena for current regset

and the reg names containx x%d instead of the correct register names.

With this fix the register names are correct.
-              if (dbg->bits == R_SYS_BITS_64) {
+              if (dbg->anal->bits == 64) {


But they are still NOT retrieved (all zeros)

**Comment by radare** [comment]
agree. the correct test is (dbg->bits & R_SYS_BITS_64)

**Comment by radare** [comment]
can you submit a PR with this? after changing this the oob arena message is no longer appearing?

**Comment by slorquet** [comment]
let me try that.

**Comment by radare** [comment]
otherwise i'll be doing blind fixes :P thanks!

**Comment by slorquet** [comment]
Doesnt work. A printf reveals that the R_SYS_BITS_64 is set, thats why I dont get ARM regs but the x%d regs.

Are you sure that this R_SYS_BITS_64 is related to my ARM cortex TARGET and not my x86_64 PC host?

Thats why I wanted to test dbg->anal->bits and not dbg->bits.

**Comment by radare** [comment]
You should specify -b32 the gdb backend cant magically guess the remote target because the gdb protocol is crap

**Comment by slorquet** [comment]
How do you say it's Thumb-2 ?

I'm still using the command line in the original post:
/home/joe/sys/bin/radare2 -a arm.gnu -b 16 -D gdb gdb://localhost:3333

why no -b16 ?

**Comment by slorquet** [comment]
hardware setup is equivalent to an stm32f4discovery board with openocd, not an iphone or android that may support full ARM opcodes.

**Comment by XVilka** [comment]
@slorquet @radare it is possible to determine the bitness automatically, but not before the release, since it could require more changes for the whole gdb parser.

**Comment by slorquet** [comment]
by grepping the code, I see that R_SYS_BITS_16 exists but nothing uses it at runtime.

**Comment by radare** [comment]
there’s no binary conflict between thumb and thumb2, this is why capstone and other disassmblers just doesnt allow to specify that because thumb2 is an extension for variable length instructions in THUMB code

-a arm -b 16 should be fine, “arm” is capstone. “arm.gnu” is the gnu disassembler from binutils.ar

**Comment by radare** [comment]
you can specify the cpu type with -e asm.cpu

```
[0x00000000]> e asm.cpu=?
v8
cortex-m
```

but this depends on the disassembler plugin.

**Comment by radare** [comment]
it is possible to determine thumb and non-thumb mode by checking the cpsr register, because arm and thumb share the same register profile. but iirc you cant identify the target arch and bits, you have to specify that by hand. same with gdb

**Comment by radare** [comment]
> On 18 Nov 2015, at 18:12, slorquet <notifications@github.com> wrote:
> 
> by grepping the code, I see that R_SYS_BITS_16 exists but nothing uses it at runtime.
> 
> 

because its the same reprofile as arm, there’s no difference, is just a mode switch, reg values and everything is kept between thumb and arm mode changes.

**Comment by radare** [comment]
Thumb2 is not conflicting

**Comment by radare** [comment]
@slorquet ping

**Comment by paulfertser** [comment]
Hello,
Just tried a similar setup, r2 -b 16 -a arm -D gdb gdb://localhost:3333, few comments so far:
1. Documentation is lacking in that it's totally not obvious that to force thumb mode it's necessary to use -b16; and as it's already said, PSR register is available and its flag can tell whether the current address will be decoded as thumb or arm by target; also gdb serial protocol supports providing the debugger with XML description of the target, so -a arm shouldn't be needed (in ideal world, at least that works with gdb-multiarch)
2. OpenOCD doesn't support vCont packet yet so to single-step I needed to
```
diff --git a/shlr/gdb/src/core.c b/shlr/gdb/src/core.c
index 435a492..7d4308d 100644
--- a/shlr/gdb/src/core.c
+++ b/shlr/gdb/src/core.c
@@ -698,7 +698,7 @@ int send_vcont(libgdbr_t* g, const char* command, int thread_id) {
        int ret;
        if (!g) return -1;
        if (thread_id < 0) {
-               ret = snprintf (tmp, sizeof (tmp) - 1, "%s;%s", CMD_C, command);
+               ret = snprintf (tmp, sizeof (tmp) - 1, "%s", command);
        } else {
                ret = snprintf (tmp, sizeof (tmp) - 1, "%s;%s:%x", CMD_C, command, thread_id);
        }
```
3. It's unclear how to stop the target once it's running
4. libr_io.so didn't get rebuilt after applying the patch, somehow the make dependency is lacking;
5. continue command leads to segfault in #1  0xb75caad3 in cmd_debug_continue (core=0xb773b400 <r>, input=0xb7a1cbc1 "c") at cmd_debug.c:2956 because core->dbg->h is non-NULL but core->dbg->h->threads is NULL.

If you prefer, I can file individual tickets per every issue mentioned.

**Comment by radare** [comment]
> On 31 Dec 2016, at 13:24, Paul Fertser <notifications@github.com> wrote:
> 
> Hello,
> Just tried a similar setup, r2 -b 16 -a arm -D gdb gdb://localhost:3333, few comments so far:
> 
> Documentation is lacking in that it's totally not obvious that to force thumb mode it's necessary to use -b16; and as it's already said, PSR register is available and its flag can tell whether the current address will be decoded as thumb or arm by target; also gdb serial protocol supports providing the debugger with XML description of the target, so -a arm shouldn't be needed (in ideal world, at least that works with gdb-multiarch)
yes there was an issue about doing this. but forcing thumb mode when the psr bit is set is incorrect because it will produce invalid disasm when trying to disassm non-thumb code. This was one though i had a while ago.. in fact there’s an issue for this already. and imho it only makes sense to do it when seek == pc

> OpenOCD doesn't support vCont packet yet so to single-step I needed to

can you send a pr? maybe @defragger can see if this breaks x86 somehow, please send a PR to discuss this gdb change
> diff --git a/shlr/gdb/src/core.c b/shlr/gdb/src/core.c
> index 435a492..7d4308d 100644
> --- a/shlr/gdb/src/core.c
> +++ b/shlr/gdb/src/core.c
> @@ -698,7 +698,7 @@ int send_vcont(libgdbr_t* g, const char* command, int thread_id) {
>         int ret;
>         if (!g) return -1;
>         if (thread_id < 0) {
> -               ret = snprintf (tmp, sizeof (tmp) - 1, "%s;%s", CMD_C, command);
> +               ret = snprintf (tmp, sizeof (tmp) - 1, "%s", command);
>         } else {
>                 ret = snprintf (tmp, sizeof (tmp) - 1, "%s;%s:%x", CMD_C, command, thread_id);
>         }
> It's unclear how to stop the target once it's running

sending a signal with dk?
> libr_io.so didn't get rebuilt after applying the patch, somehow the make dependency is lacking;

I use `sys/rebuild.sh gdb`.. its better than overcomplicating all the makefiles, this script shows other similar issues 

> continue command leads to segfault in #1 <https://github.com/radare/radare2/pull/1> 0xb75caad3 in cmd_debug_continue (core=0xb773b400 , input=0xb7a1cbc1 "c") at cmd_debug.c:2956 because core->dbg->h is non-NULL but core->dbg->h->threads is NULL.

should be fixed in master, no need to open an issue for that next time just send a pr :)

> If you prefer, I can file individual tickets per every issue mentioned.
> 
> 
no need to open more issues i think

thanks!

**Comment by paulfertser** [comment]
r_io_plugin_gdb doesn't implement kill(), so sending signal to stop a running target is not possible.

Compared to the usual GDB debugging I'm also lacking a sensible way to send qRcmd command ("monitor" in gdb) to be able to send OpenOCD commands directly. =!pkt isn't suitable because qRcmd needs hex-encoded contents.

It's also kind of strange PSR is not shown in "?0;f tmp;s.. @ pc" visual mode for Thumb.

**Comment by radare** [comment]
this is up to the r_debug_gdb plugin, not the io one. you can implement this in the io if you like too via system

> On 31 Dec 2016, at 18:40, Paul Fertser <notifications@github.com> wrote:
> 
> r_io_plugin_gdb doesn't implement kill(), so sending signal to stop a running target is not possible.
> 
> Compared to the usual GDB debugging I'm also lacking a sensible way to send qRcmd command ("monitor" in gdb) to be able to send OpenOCD commands directly. =!pkt isn't suitable because qRcmd needs hex-encoded contents.
> 
> It's also kind of strange PSR is not shown in "?0;f tmp;s.. @ pc" visual mode for Thumb.
> 
thats because of the reg profile missing the bit definition of the psr

**Comment by paulfertser** [comment]
I meant to say that "dk" doesn't let me send any signal via GDB Serial protocol and that I'm not able to stop a running target anyhow.

**Comment by radare** [comment]
i see, the gdb debug plugin doesnt implements the kill callback

**Comment by radare** [comment]
can you send a PR for that?

**Comment by radare** [comment]
i think we should split that into different issues and close this one @Maijin

**Comment by alvarofe** [comment]
We have an issue for arm regprofile, maybe create one related with gdb backend and close this?

**Comment by XVilka** [comment]
Since it came up in the twitter - @SrimantaBarua this may be a slight interest of you.

**Comment by SrimantaBarua** [comment]
Among the issues mentioned here -
1. The gdb remote protocol doesn't have kill_with_signal, as far as I can see. But the generic kill signal has been implemented. To send specific signals, one could probably use continue_with_signal.
2. vCont/step issue is probably sorted.
3. qRcmd will be implemented in io_gdb (related to [#6431](https://github.com/radare/radare2/issues/6431))

**Comment by radare** [comment]
Continue with signal will stop inside the signal handler? If so go for it

**Comment by XVilka** [comment]
What with this issue? Was it solved?
