### ISSUE TITLE
Unexpected results after running 'aa'

### ISSUE THREAD

**Issue by vvvverre** [radare/radare2#2565]
Hi all,

I seem to be having some misunderstanding about how 'aa' is supposed to behave. On one system I get the following behaviour: I open up a binary (ELF, x86-64) and run 'aa', after this I run 'pdf @ main'. r2 then returns an error saying it can not find a function at \<address\>, which is the correct address for main. Then if I run 'af @ main' followed by 'pdf @ main', I get the disassembly for main, as expected. Why do I not get this output after running 'aa'? The system that has this problem runs Arch Linux, with radare 2 version 0.9.8. Strangely enough, on another system, which runs Kali Linux with radare 2 version 0.9, I do get the expected output right after running 'aa'. 

Is this behaviour controlled by an option I can set somewhere? Did the expected behaviour change between versions?

Below is the sample output for one binary, but I have seen this behaviour with all binaries I tried on this system.

>[0x004009c0]> aa
>[0x004009c0]> pdf @ main
>Cannot find function at 0x00400d73
>[0x004009c0]> af @ main
>[0x004009c0]> pdf @ main
>|          ; DATA XREF from 0x004009dd (entry0)
>/ (fcn) main 312
><snip>

Many thanks in advance

**Comment by Maijin** [comment]
@vvvverre please try with the latest git version

**Comment by vvvverre** [comment]
Thanks, just tried with the latest. It now works :+1: Didn't realise how far off it was... Since version 0.9 does work and 0.9.8 does not, this seems to be suprising? Was this a regression that has been fixed since?

**Comment by Maijin** [comment]
@vvvverre probably

**Comment by radare** [comment]
I think it was since quite faster right after the release of 0.9.8, that release have other known bugs. I always recommend using git.
