### ISSUE TITLE
rabin -rP prints debug message on stdout, breaking imports

### ISSUE THREAD

**Issue by roblabla** [radare/radare2#2566]
Still with the same [pdb file](http://static.cmc.im/GameLogic.pdb), running `.!rabin2 -rP GameLogic.pdb` from inside r2 breaks :

```
[0x10065205]> .!rabin2 -rP GameLogic.pdb
<string>:1: error: identifier expected
This is not an enum
This is not an enum
This is not an enum
This is not an enum
Slurping file 'std::pair<IQuest * const,PlayerQuestState> > ? (std::pair<IQuest)value_type'
cannot open file
[About a gazillion lines later]
==> Reading from stdin until 'lambda_4d4ac1743178d84df07ae592d8702431>,0> E (long)<unnamed-enum-_EEN_INDIRECT>'
>
```

I'm fairly sure this is due to `rabin2` printing some debug messages to STDOUT, which radare2 tries to interpret. Messages like [`there is no support for type "class" in PF structs`](https://github.com/radare/radare2/blob/515b2e77bc486c996b0011018277261cd2da5116/libr/bin/pdb/pdb.c#L754), or [`warning: strange for nesttype`](https://github.com/inisider/radare2/blob/cff0a236b70ecb713bef1748eef5d0c1a0aee3e8/libr/bin/pdb/tpi.c#L1426) show up quite often, and I suspect they are at the root of the issue. Would it be possible to print them to STDERR, for instance ?

**Comment by radare** [comment]
Yes, those warnings should be printed to stderr with `eprintf`. see last commit in master

**Comment by roblabla** [comment]
New version still breaks with similar errors. Here are some lines from the output of `rabin2 -rP` that cause the `<string>:1:error: identifier expected` message :

```
"td enum std::float_round_style { ound_indeterminate=FFFFFFFF,round_toward_zero=00000000,round_to_nearest=00000001,round_toward_infinity=00000002,round_toward_neg_infinity=00000003 };"`
"td enum std::float_denorm_style { enorm_indeterminate=FFFFFFFF,denorm_absent=00000000,denorm_present=00000001 };"
"td enum std::_Tree_val<std::_Tree_simple_types<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >::_Redbl { _Red=00000000,_Black=00000001 };"
```

As for the `Slurping file 'std::pair<IQuest * const,PlayerQuestState> > ? (std::pair<IQuest)value_type'` messages, they are caused by lines similar to :

```
pf std::_Allocator_base<std::pair<IQuest * const,PlayerQuestState> > ? (std::pair<IQuest)value_type
```

I'll take a wild guess and this is due to the namespacing and templates ?

**Comment by radare** [comment]
I didnt added support for those constructions, just moved the warnings to stderr. Implementing these types will require reversing the pdb parser and redo it. Because iirc theres no doc or opensource impl of this.

Inisider (the author of the pdb parser) will work on that.

**Comment by radare** [comment]
update: inisider still working on that

**Comment by xarkes** [comment]
The pdb file is not uploaded anymore

**Comment by roblabla** [comment]
Here's a new link : http://dl.roblab.la/GameLogic.pdb

I think that's the same file.

**Comment by Maijin** [comment]
use github upload next time. drag and drop zip here so it never gets deleted from those garbage hosting services

**Comment by roblabla** [comment]
The garbage hosting service is my personal box. I didn't know github had a hosting service for issues ! Here's a link.

[GameLogic.pdb.zip](https://github.com/radare/radare2/files/1252390/GameLogic.pdb.zip)

**Comment by radare** [comment]
==18282== Argument 'size' of function realloc has a fishy (possibly negative) value: -2126230351
==18282==    at 0x10009F71A: realloc (vg_replace_malloc.c:788)
==18282==    by 0x100341BAD: copy_string (microsoft_demangle.c:128)
==18282==    by 0x100344D98: parse_microsoft_mangled_name (microsoft_demangle.c:1391)
==18282==    by 0x100343FD8: microsoft_demangle (microsoft_demangle.c:1433)
==18282==    by 0x10029094A: r_bin_demangle_msvc (demangle.c:114)
==18282==    by 0x100355B28: print_gvars (pdb.c:1116)
==18282==    by 0x1001914CB: bin_pdb (cbin.c:1033)
==18282==    by 0x10018E6DD: r_core_bin_info (cbin.c:3042)
==18282==    by 0x100003B06: main (in /usr/local/bin/rabin2)
