### ISSUE TITLE
add 'drx' description to 'db' help?

### ISSUE THREAD

**Issue by jjdredd** [radare/radare2#2567]
one would expect that everyting regarding breakpoints is under db, why not print at least a mention of
drx in the help for db?

**Comment by radare** [comment]
because someone forgot it? feel free to send a pr with one line of text

**Comment by jjdredd** [comment]
because we can have new users

**Comment by radare** [comment]
the commit adding help on that command is shorter and faster to do than discussing all this pointless stuff in github
