### ISSUE TITLE
Stop searching for gadget on first match

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2574]
When I'm searching for `pop eax; ret`, most of the time I'll take the first occurrence; I don't need to be shown that there are 143.432.543.445 hits. It would be great to be able to tell this to r2, so it could break on first hit.

**Comment by crowell** [comment]
@jvoisin uh... in the current state, this isn't such a great idea, as we search in all sections (including NX sections) by default.

**Comment by jvoisin** [comment]
Why are we doing this again?

**Comment by radare** [comment]
e search.count=1

**Comment by jvoisin** [comment]
It doesn't work with `/R` :/

**Comment by crowell** [comment]
@jvoisin we're doing this because pancake has dictated it!

**Comment by crowell** [comment]
I've added the search.count support in c41e4dda114f9e66e1ea8eb63445af3dedfb2627 closing

**Comment by alvarofe** [comment]
@crowell is breaking travis https://travis-ci.org/radare/radare2/jobs/62710289

**Comment by crowell** [comment]
@alvarofe fixed.
