### ISSUE TITLE
[WINDOWS] radare2.exe on Cygwin doesn't have support for native debug

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2577]
Run radare2 in Cygwin 32 on Windows 7 x64
(compiled from the sources)

```
./radare2.exe -d somefile.exe
```

`-d` doesn't work while `d` do the job.
![](https://puu.sh/hNxNa/01c8701c61.png)

**Comment by radare** [comment]
Can cygwin-gdb debug windows programs? if so it is using the w32 api, not the ptrace one that should be wrapped by cygwin

**Comment by XVilka** [comment]
Just checked - same error
```
$ ./radare2.exe -d rarun2.exe
Cannot open 'dbg://rarun2.exe' for writing.
```

**Comment by XVilka** [comment]
Related - https://github.com/radare/radare2/issues/2578

**Comment by radare** [comment]
Lets focus on this strange hybrid target for 1.0

**Comment by XVilka** [comment]
Closing since removing Cygwin support https://github.com/radare/radare2/issues/9973
