### ISSUE TITLE
[WINDOWS] radare2 on cygwin doesn autoresolve 'esi' in 'x @esi' command

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2578]
Run radare2 in Cygwin 32 on Windows 7 x64
(compiled from the sources)

./radare2.exe -d somefile.exe

Then try to run `x @ esi` and it will not recognize it:
![here be dragonz](http://puu.sh/hNwa4/2ef46d48fc.png)

**Comment by radare** [comment]
What do `? esi` shows?

is the flag already set? it is shown in the `drp` reg profile?

**Comment by XVilka** [comment]
looks like related to the previous bug (because there is no proper code for native debug for Cygwin in debug_native.c

**Comment by XVilka** [comment]
Closing as duplicate of https://github.com/radare/radare2/issues/2577 since the reason of the problem - is missing support of the native debugger in cygwin.

**Comment by radare** [comment]
Just modify the profile to add esi too. Also, cygwin debugger sounds wtf to me
