### ISSUE TITLE
axf returns empty result

### ISSUE THREAD

**Issue by n0way0ut** [radare/radare2#2582]
[0x00400522]> aa
[0x00400522]> pdf@main
/ (fcn) sym.main 56
|          ; arg int arg_2_4      @ rbp+0x14
|          ; var int local_0_4    @ rbp-0x4
|          ; DATA XREF from 0x0040041d (entry0)
|          ;-- main:
|          ;-- sym.main:
|          0x00400522    55             push rbp
|          0x00400523    4889e5         mov rbp, rsp
|          0x00400526    4883ec10       sub rsp, 0x10
|          0x0040052a    c745fc140000.  mov dword [rbp-local_0_4], 0x14  ; [0x14:4]=1
|          0x00400531    be0c000000     mov esi, 0xc
|          0x00400536    bf0b000000     mov edi, 0xb
|          0x0040053b    e8ccffffff     call sym.foo
|             sym.foo()
|          0x00400540    8345fc01       add dword [rbp-local_0_4], 1
|          0x00400544    8b45fc         mov eax, dword [rbp-local_0_4]
|          0x00400547    89c6           mov esi, eax
|          0x00400549    bf0c064000     mov edi, 0x40060c
|          0x0040054e    b800000000     mov eax, 0
|          0x00400553    e888feffff     call sym.imp.printf
|             sym.imp.printf()
|          0x00400558    c9             leave
\          0x00400559    c3             ret
[0x00400522]> axt sym.foo
C 0x40053b call sym.foo
[0x00400522]> axf 0x0040053b
C 0x40053b call sym.foo
[0x00400522]> axf 0x00400536
d 0x400536 mov edi, 0xb
[0x00400522]> axf 0x00400513
[0x00400522]> pdf@sym.foo
/ (fcn) sym.foo 22
|          ; CALL XREF from 0x0040053b (sym.main)
|          ;-- sym.foo:
|          0x0040050c    55             push rbp
|          0x0040050d    4889e5         mov rbp, rsp
|          0x00400510    897dec         mov dword [rbp-local_2_4], edi
|          0x00400513    8975e8         mov dword [rbp-local_3], esi
|          0x00400516    c745fc040000.  mov dword [rbp-local_0_4], 4
|          0x0040051d    8b45fc         mov eax, dword [rbp-local_0_4]
|          0x00400520    5d             pop rbp
\          0x00400521    c3             ret
[0x00400522]> axf 0x00400513
[0x00400522]>

**Comment by radare** [comment]
there are no xrefs for local variables, those are called local accesses and are not accessible with axf. you probably only want to use axt/axf to follow execution branches and calls, or absolute memory offsets for data peeks. But stack follows different rules.
