### ISSUE TITLE
[WINDOWS] Support of loading windows .DMP (kernel dumps and process dumps) files

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2598]
https://msdn.microsoft.com/en-us/library/windows/hardware/ff551867%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/ff560246%28v=vs.85%29.aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/ff538042%28v=vs.85%29.aspx
http://blogs.technet.com/b/askperf/archive/2008/01/08/understanding-crash-dump-files.aspx
https://code.google.com/p/volatility/wiki/CrashAddressSpace

**Comment by XVilka** [comment]
Related https://reviews.llvm.org/rL280356

**Comment by radare** [comment]
isnt this r2pm -i mdmp ?

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
No, it's different format.

**Comment by XVilka** [comment]
Was done by @AlexKornitzer
