### ISSUE TITLE
rax2 < /bin/ls > ls.hex Invalid write of size 4

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2603]
Valgrind output http://paste.ubuntu.com/11266910/

**Comment by alvarofe** [comment]
Which command did you use @Maijin ?

**Comment by Maijin** [comment]
@alvarofe 

valgrind rax2 < /bin/ls > ls.hex

**Comment by alvarofe** [comment]
Good job Álvaro it was written in the title jeje thanks @Maijin
