### ISSUE TITLE
gpg cast5 data

### ISSUE THREAD

**Issue by C-H-A-I-R** [radare/radare2#2616]
not sure if folks care, but could radare2 implement search for gpg cast5 data?
it seems that signature is 8c0d04030302 for files. (encrypted with gpg -c)

greetings 
chair

**Comment by Maijin** [comment]
That could also fit in https://github.com/Yara-Rules/rules

**Comment by C-H-A-I-R** [comment]
@all do you agree to put this in yara?  @radare @jvoisin @jjdredd @crowell

**Comment by radare** [comment]
or magic. but yep
