### ISSUE TITLE
afn cannot find flag doesn't save in Project

### ISSUE THREAD

**Issue by protoload** [radare/radare2#2618]
`r2 -p ezhp2 -Ad ezhp`

`  ││   0x08048a80    e80ffdffff     calll fcn.08048794`

`[0xf7786080]> afn add_note fcn.08048794`
`Cannot find flag (fcn.08048794)`

`pdf @ main`
`
0x08048a80    e80ffdffff     calll add_note
`

`Ps `

Now reopening the project shows 
`││   0x08048a80    e80ffdffff     calll fcn.08048794 `
instead of the name I gave it

**Comment by radare** [comment]
It's fixed now in git master. thanks for reporting!
