### ISSUE TITLE
rasm2 Segfault

### ISSUE THREAD

**Issue by daniel-rome** [radare/radare2#2627]
Converting some arm (thumb) instructions I have noticed that rasm2 returns a segfault.

Below you can find an example:

$ rasm2 -v                                                                                                           
rasm2 0.9.9-git 7977 @ linux-little-x86-64 git.0.9.8-1625-g313a4f7
commit: 313a4f7fcafb64ee5d3da3cca597d9301b23e1d5 build: 2015-05-26

$ rasm2 -a arm -b 16 "ldr r3 [r1]"
Segmentation fault

In order to debug the crash I annex the gdb output:

$ gdb -q rasm2
Reading symbols from rasm2...done.
(gdb) r -a arm -b 16 "ldr r3 [r1]"
Starting program: /usr/bin/rasm2 -a arm -b 16 "ldr r3 [r1]"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
29      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
=> 0x00007ffff650c46a <__strcmp_sse2_unaligned+26>:     f3 0f 6f 0f     movdqu xmm1,XMMWORD PTR [rdi]
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:29
#1  0x00007ffff7591314 in thumb_assemble (ao=0x7fffffffce50, str=0x7fffffffcfe0 "ldr r3 [r1]") at p/../arch/arm/armass.c:449
#2  0x00007ffff759308b in armass_assemble (str=0x624fe0 "ldr r3 [r1]", off=0, thumb=1) at p/../arch/arm/armass.c:842
#3  0x00007ffff758fbf8 in assemble (a=0x604010, op=0x7fffffffd160, buf=0x624fe0 "ldr r3 [r1]") at p/asm_arm_cs.c:79
#4  0x00007ffff760e8b3 in r_asm_assemble (a=0x604010, op=0x7fffffffd160, buf=0x7fffffffd470 "ldr r3 [r1]") at asm.c:363
#5  0x00007ffff760fc1d in r_asm_massemble (a=0x604010, buf=0x7fffffffe4ae "ldr r3 [r1]") at asm.c:641
#6  0x0000000000401f30 in rasm_asm (buf=0x7fffffffe4ae "ldr r3 [r1]", offset=0, len=0, bits=16, bin=0) at rasm2.c:171
#7  0x0000000000402e0d in main (argc=6, argv=0x7fffffffe148) at rasm2.c:429

**Comment by Maijin** [comment]
@daniel-rome please use git version. The version you use is 1625 commits from master which is about  792 changed files  with 21,067 additions and 4,633 deletions.

**Comment by daniel-rome** [comment]
I have updated my r2 version this afternoon (sys/install.sh), what is wrong?

**Comment by XVilka** [comment]
@daniel-rome do you have any other installations? system-wide may be? looks like you have an old libraries somewhere.

**Comment by daniel-rome** [comment]
It is possible.. Do you recommend me some way to clear the old libraries/installation?

**Comment by XVilka** [comment]
@daniel-rome check the places like /usr/local/lib and /usr/lib, remove all radare2 related, also libr*.so stuff (just be sure it is a radare2 libs, not the other ones).

**Comment by radare** [comment]
The official procedure is:

./configure --prefix=/usr/local
make purge
sys/install.sh

**Comment by daniel-rome** [comment]
I have done the official procedure, but it returns the same segfault.

$ rasm2 -v
rasm2 0.9.9-git 7977 @ linux-little-x86-64 git.0.9.8-1625-g313a4f7
commit: 313a4f7fcafb64ee5d3da3cca597d9301b23e1d5 build: 2015-05-27

**Comment by XVilka** [comment]
@daniel-rome then pls check 'unofficial' one, it works for me every time.

**Comment by XVilka** [comment]
@daniel-rome forget it, I confirm the bug. Your installation is probably OK.

**Comment by radare** [comment]
This is a stupid null deref. fix in git in few mins

**Comment by daniel-rome** [comment]
I was driving me crazy!!!

Thanks! :)
