### ISSUE TITLE
Allow to run a command on all threads?

### ISSUE THREAD

**Issue by radare** [radare/radare2#2638]
would be cool to have a way to run a command on all running threads of a target process. We need syntax sugar for this. I'm thinking in something like this:

```
> dbt= @@:dp
> dr @@:dp
```
The @@:dp modifier should run the previous command for every thread after selecting it. Can we think on other non-offset iterators here?

**Comment by jvoisin** [comment]
What about forks?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/6756b88b0fd40589fa516de1d4a3d558ec461838 fixed ?

**Comment by radare** [comment]
Yeah :D
