### ISSUE TITLE
s/ free(): invalid next size (fast): 0x0926d0e0 ***

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2640]
morn,

```
zlul@debian:~$ r2 /bin/ls
 -- What has been executed cannot be unexecuted
[0x0804c1b4]> s/ `/dev/urandom`
*** glibc detected *** r2: free(): invalid next size (fast): 0x0926d0e0 ***
======= Backtrace: =========
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6feb1)[0xb6662eb1]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x71718)[0xb6664718]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(cfree+0x6d)[0xb666785d]
/usr/lib/libr_search.so(r_search_keyword_new_hexmask+0xbf)[0xb75e053e]
/usr/lib/libr_core.so(+0x59333)[0xb766b333]
/usr/lib/libr_core.so(r_cmd_call+0x120)[0xb7694f58]
/usr/lib/libr_core.so(+0x5e7b6)[0xb76707b6]
/usr/lib/libr_core.so(+0x5ce64)[0xb766ee64]
/usr/lib/libr_core.so(r_core_cmd+0x25b)[0xb767122a]
/usr/lib/libr_core.so(r_core_cmd_str+0x38)[0xb76719ed]
/usr/lib/libr_core.so(+0x5dc7e)[0xb766fc7e]
/usr/lib/libr_core.so(+0x5ce64)[0xb766ee64]
/usr/lib/libr_core.so(r_core_cmd+0x25b)[0xb767122a]
/usr/lib/libr_core.so(r_core_prompt_exec+0x32)[0xb763257e]
r2(main+0x2375)[0x804cd40]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xb6609e46]
r2[0x804a381]
======= Memory map: ========
08048000-0804f000 r-xp 00000000 08:01 22287332   /usr/bin/radare2
0804f000-08050000 rw-p 00006000 08:01 22287332   /usr/bin/radare2
08050000-080b1000 rw-p 00000000 00:00 0 
08f30000-0928c000 rw-p 00000000 00:00 0          [heap]
b6400000-b6421000 rw-p 00000000 00:00 0 
b6421000-b6500000 ---p 00000000 00:00 0 
b653c000-b6558000 r-xp 00000000 08:01 26214404   /lib/i386-linux-gnu/libgcc_s.so.1
b6558000-b6559000 rw-p 0001b000 08:01 26214404   /lib/i386-linux-gnu/libgcc_s.so.1
b656c000-b656d000 rw-p 00000000 00:00 0 
b656d000-b6572000 r--s 00000000 08:01 4795       /usr/lib/radare2/0.9.9-git/syscall/linux-x86-32.sdb
b6572000-b658e000 r--s 00000000 08:01 23330907   /bin/ls
b658e000-b658f000 r-xp 00000000 08:01 4692       /usr/lib/radare2/0.9.9-git/asm_x86_as.so
b658f000-b6590000 rw-p 00000000 08:01 4692       /usr/lib/radare2/0.9.9-git/asm_x86_as.so
b6590000-b6591000 r-xp 00000000 08:01 4687       /usr/lib/radare2/0.9.9-git/asm_x86_nasm.so
b6591000-b6592000 rw-p 00000000 08:01 4687       /usr/lib/radare2/0.9.9-git/asm_x86_nasm.so
b6592000-b6594000 r-xp 00000000 08:01 4684       /usr/lib/radare2/0.9.9-git/asm_snes.so
b6594000-b6595000 rw-p 00002000 08:01 4684       /usr/lib/radare2/0.9.9-git/asm_snes.so
b6595000-b6598000 r-xp 00000000 08:01 4666       /usr/lib/radare2/0.9.9-git/asm_6502.so
b6598000-b6599000 rw-p 00002000 08:01 4666       /usr/lib/radare2/0.9.9-git/asm_6502.so
b6599000-b659e000 r--s 00000000 08:01 4795       /usr/lib/radare2/0.9.9-git/syscall/linux-x86-32.sdb
b659e000-b65a0000 rw-p 00000000 00:00 0 
b65a0000-b65a2000 r-xp 00000000 08:01 26345522   /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
b65a2000-b65a3000 r--p 00001000 08:01 26345522   /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
b65a3000-b65a4000 rw-p 00002000 08:01 26345522   /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
b65a4000-b65b9000 r-xp 00000000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
b65b9000-b65ba000 r--p 00014000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
b65ba000-b65bb000 rw-p 00015000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
b65bb000-b65bd000 rw-p 00000000 00:00 0 
b65bd000-b65e1000 r-xp 00000000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
b65e1000-b65e2000 r--p 00023000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
b65e2000-b65e3000 rw-p 00024000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
b65e3000-b65e4000 rw-p 00000000 00:00 0 
b65e4000-b65ed000 r-xp 00000000 08:01 22286706   /usr/lib/libr_socket.so.0.9.9-git
b65ed000-b65ee000 rw-p 00008000 08:01 22286706   /usr/lib/libr_socket.so.0.9.9-git
b65ee000-b65f2000 r-xp 00000000 08:01 22284589   /usr/lib/libr_lang.so.0.9.9-git
b65f2000-b65f3000 rw-p 00003000 08:01 22284589   /usr/lib/libr_lang.so.0.9.9-git
b65f3000-b6751000 r-xp 00000000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
b6751000-b6753000 r--p 0015e000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
b6753000-b6754000 rw-p 00160000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
b6754000-b6757000 rw-p 00000000 00:00 0 
b6757000-b675a000 r-xp 00000000 08:01 22283799   /usr/lib/libr_crypto.so.0.9.9-git
b675a000-b675e000 rw-p 00002000 08:01 22283799   /usr/lib/libr_crypto.so.0.9.9-git
b675e000-b676a000 r-xp 00000000 08:01 22284569   /usr/lib/libr_egg.so.0.9.9-git
b676a000-b676b000 rw-p 0000c000 08:01 22284569   /usr/lib/libr_egg.so.0.9.9-git
b676b000-b676d000 rw-p 00000000 00:00 0 
b676d000-b67b5000 r-xp 00000000 08:01 22286710   /usr/lib/libr_util.so.0.9.9-git
b67b5000-b67b6000 rw-p 00048000 08:01 22286710   /usr/lib/libr_util.so.0.9.9-git
b67b6000-b67bf000 rw-p 00000000 00:00 0 
b67bf000-b67c4000 r-xp 00000000 08:01 22284576   /usr/lib/libr_flags.so.0.9.9-git
b67c4000-b67c5000 rw-p 00004000 08:01 22284576   /usr/lib/libr_flags.so.0.9.9-git
b67c5000-b67d7000 r-xp 00000000 08:01 22284592   /usr/lib/libr_magic.so.0.9.9-git
b67d7000-b67d8000 rw-p 00011000 08:01 22284592   /usr/lib/libr_magic.so.0.9.9-git
b67d8000-b67e2000 r-xp 00000000 08:01 22284582   /usr/lib/libr_hash.so.0.9.9-git
b67e2000-b67e3000 rw-p 0000a000 08:01 22284582   /usr/lib/libr_hash.so.0.9.9-git
b67e3000-b67fe000 r-xp 00000000 08:01 22284554   /usr/lib/libr_db.so.0.9.9-git
b67fe000-b6800000 rw-p 0001a000 08:01 22284554   /usr/lib/libr_db.so.0.9.9-git
b6800000-b6819000 rw-p 00000000 00:00 0 
b6819000-b681b000 r-xp 00000000 08:01 22286708   /usr/lib/libr_syscall.so.0.9.9-git
b681b000-b681c000 rw-p 00002000 08:01 22286708   /usr/lib/libr_syscall.so.0.9.9-git
b681c000-b681d000 rw-p 00000000 00:00 0 
b681d000-b6b9f000 r-xp 00000000 08:01 22283775   /usr/lib/libr_asm.so.0.9.9-git
b6b9f000-b6e90000 rw-p 00382000 08:01 22283775   /usr/lib/libr_asm.so.0.9.9-git
b6e90000-b6ea5000 rw-p 00000000 00:00 0 
b6ea5000-b6ed6000 r-xp 00000000 08:01 22284580   /usr/lib/libr_fs.so.0.9.9-git
b6ed6000-b6ed8000 rw-p 00030000 08:01 22284580   /usr/lib/libr_fs.so.0.9.9-git
b6ed8000-b6ede000 rw-p 00000000 00:00 0 
b6ede000-b6f1f000 r-xp 00000000 08:01 22284585   /usr/lib/libr_io.so.0.9.9-git
b6f1f000-b6f27000 rw-p 00040000 08:01 22284585   /usr/lib/libr_io.so.0.9.9-git
b6f27000-b6f2d000 rw-p 00000000 00:00 0 
b6f2d000-b6f31000 r-xp 00000000 08:01 22283783   /usr/lib/libr_bp.so.0.9.9-git
b6f31000-b6f32000 rw-p 00003000 08:01 22283783   /usr/lib/libr_bp.so.0.9.9-git
b6f32000-b6f37000 r-xp 00000000 08:01 22285348   /usr/lib/libr_reg.so.0.9.9-git
b6f37000-b6f38000 rw-p 00005000 08:01 22285348   /usr/lib/libr_reg.so.0.9.9-git
b6f38000-b6f3b000 r-xp 00000000 08:01 22284562   /usr/lib/libr_diff.so.0.9.9-gitAborted

 gdb -q r2 core
Core was generated by `r2 /bin/ls'.
Program terminated with signal 6, Aborted.
#0  0xb7786424 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7786424 in __kernel_vsyscall ()
#1  0xb669e661 in *__GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0xb66a1a92 in *__GI_abort () at abort.c:92
#3  0xb66d9dc5 in __libc_message (do_abort=2, fmt=0xb67b4b50 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
#4  0xb66e3eb1 in malloc_printerr (action=<optimized out>, str=0x6 <Address 0x6 out of bounds>, ptr=0x9c45d80) at malloc.c:6312
#5  0xb66e5718 in _int_free (av=<optimized out>, p=<optimized out>) at malloc.c:4824
#6  0xb66e885d in *__GI___libc_free (mem=0x9c45d80) at malloc.c:3738
#7  0xb7661549 in r_search_keyword_new_hexmask (kwstr=0x9c76c7b "v/urandom", data=0x0) at keyword.c:148
#8  0xb76ec333 in cmd_search (data=0x804f740, input=0x9c76c79 "dev/urandom") at cmd_search.c:1825
#9  0xb7715f58 in r_cmd_call (cmd=0x98e3438, input=0x9c76c78 "/dev/urandom") at cmd_api.c:182
#10 0xb76f17b6 in r_core_cmd_subst_i (core=0x804f740, cmd=0x9c76c78 "/dev/urandom", colon=0x0) at cmd.c:1583
#11 0xb76efe64 in r_core_cmd_subst (core=0x804f740, cmd=0x9c76c78 "/dev/urandom") at cmd.c:1080
#12 0xb76f222a in r_core_cmd (core=0x804f740, cstr=0x9c76c64 "/dev/urandom", log=0) at cmd.c:1801
#13 0xb76f29ed in r_core_cmd_str (core=0x804f740, cmd=0x9c76c64 "/dev/urandom") at cmd.c:1982
#14 0xb76f0c7e in r_core_cmd_subst_i (core=0x804f740, cmd=0x9c76c60 "s/ ", colon=0x0) at cmd.c:1376
#15 0xb76efe64 in r_core_cmd_subst (core=0x804f740, cmd=0x9c76c60 "s/ ") at cmd.c:1080
#16 0xb76f222a in r_core_cmd (core=0x804f740, cstr=0x9c76c30 " s/ `/dev/urandom`", log=1) at cmd.c:1801
#17 0xb76b357e in r_core_prompt_exec (r=0x804f740) at core.c:1076
#18 0x0804cd40 in main (argc=2, argv=0xbfda17b4, envp=0xbfda17c0) at radare2.c:777
(gdb) x/i $pc
=> 0xb7786424 <__kernel_vsyscall+16>:	pop    %ebp
```

r2 -v
radare2 0.9.9-git 7993 @ linux-little-x86-32 git.0.9.8-1637-g7194525
commit: 7194525554cc1bc2a2b34c9ad197299cbc31c481 build: 2015-05-28

I might bring a chair to bsides :)

Greetings
zlul

**Comment by crowell** [comment]
cannot repro, can you give a test case that doesn't rely on a random value?

also is this on a 32 bits machine?

On Thu, May 28, 2015 at 11:29 AM, zonkzonk <notifications@github.com> wrote:

> morn,
>
> zlul@debian:~$ r2 /bin/ls
>  -- What has been executed cannot be unexecuted
> [0x0804c1b4]> s/ `/dev/urandom`
> *** glibc detected *** r2: free(): invalid next size (fast): 0x0926d0e0 ***
> ======= Backtrace: =========
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6feb1)[0xb6662eb1]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x71718)[0xb6664718]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(cfree+0x6d)[0xb666785d]
> /usr/lib/libr_search.so(r_search_keyword_new_hexmask+0xbf)[0xb75e053e]
> /usr/lib/libr_core.so(+0x59333)[0xb766b333]
> /usr/lib/libr_core.so(r_cmd_call+0x120)[0xb7694f58]
> /usr/lib/libr_core.so(+0x5e7b6)[0xb76707b6]
> /usr/lib/libr_core.so(+0x5ce64)[0xb766ee64]
> /usr/lib/libr_core.so(r_core_cmd+0x25b)[0xb767122a]
> /usr/lib/libr_core.so(r_core_cmd_str+0x38)[0xb76719ed]
> /usr/lib/libr_core.so(+0x5dc7e)[0xb766fc7e]
> /usr/lib/libr_core.so(+0x5ce64)[0xb766ee64]
> /usr/lib/libr_core.so(r_core_cmd+0x25b)[0xb767122a]
> /usr/lib/libr_core.so(r_core_prompt_exec+0x32)[0xb763257e]
> r2(main+0x2375)[0x804cd40]
> /lib/i386-linux-gnu/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xb6609e46]
> r2[0x804a381]
> ======= Memory map: ========
> 08048000-0804f000 r-xp 00000000 08:01 22287332   /usr/bin/radare2
> 0804f000-08050000 rw-p 00006000 08:01 22287332   /usr/bin/radare2
> 08050000-080b1000 rw-p 00000000 00:00 0
> 08f30000-0928c000 rw-p 00000000 00:00 0          [heap]
> b6400000-b6421000 rw-p 00000000 00:00 0
> b6421000-b6500000 ---p 00000000 00:00 0
> b653c000-b6558000 r-xp 00000000 08:01 26214404   /lib/i386-linux-gnu/libgcc_s.so.1
> b6558000-b6559000 rw-p 0001b000 08:01 26214404   /lib/i386-linux-gnu/libgcc_s.so.1
> b656c000-b656d000 rw-p 00000000 00:00 0
> b656d000-b6572000 r--s 00000000 08:01 4795       /usr/lib/radare2/0.9.9-git/syscall/linux-x86-32.sdb
> b6572000-b658e000 r--s 00000000 08:01 23330907   /bin/ls
> b658e000-b658f000 r-xp 00000000 08:01 4692       /usr/lib/radare2/0.9.9-git/asm_x86_as.so
> b658f000-b6590000 rw-p 00000000 08:01 4692       /usr/lib/radare2/0.9.9-git/asm_x86_as.so
> b6590000-b6591000 r-xp 00000000 08:01 4687       /usr/lib/radare2/0.9.9-git/asm_x86_nasm.so
> b6591000-b6592000 rw-p 00000000 08:01 4687       /usr/lib/radare2/0.9.9-git/asm_x86_nasm.so
> b6592000-b6594000 r-xp 00000000 08:01 4684       /usr/lib/radare2/0.9.9-git/asm_snes.so
> b6594000-b6595000 rw-p 00002000 08:01 4684       /usr/lib/radare2/0.9.9-git/asm_snes.so
> b6595000-b6598000 r-xp 00000000 08:01 4666       /usr/lib/radare2/0.9.9-git/asm_6502.so
> b6598000-b6599000 rw-p 00002000 08:01 4666       /usr/lib/radare2/0.9.9-git/asm_6502.so
> b6599000-b659e000 r--s 00000000 08:01 4795       /usr/lib/radare2/0.9.9-git/syscall/linux-x86-32.sdb
> b659e000-b65a0000 rw-p 00000000 00:00 0
> b65a0000-b65a2000 r-xp 00000000 08:01 26345522   /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> b65a2000-b65a3000 r--p 00001000 08:01 26345522   /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> b65a3000-b65a4000 rw-p 00002000 08:01 26345522   /lib/i386-linux-gnu/i686/cmov/libdl-2.13.so
> b65a4000-b65b9000 r-xp 00000000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> b65b9000-b65ba000 r--p 00014000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> b65ba000-b65bb000 rw-p 00015000 08:01 26345500   /lib/i386-linux-gnu/i686/cmov/libpthread-2.13.so
> b65bb000-b65bd000 rw-p 00000000 00:00 0
> b65bd000-b65e1000 r-xp 00000000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> b65e1000-b65e2000 r--p 00023000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> b65e2000-b65e3000 rw-p 00024000 08:01 26345523   /lib/i386-linux-gnu/i686/cmov/libm-2.13.so
> b65e3000-b65e4000 rw-p 00000000 00:00 0
> b65e4000-b65ed000 r-xp 00000000 08:01 22286706   /usr/lib/libr_socket.so.0.9.9-git
> b65ed000-b65ee000 rw-p 00008000 08:01 22286706   /usr/lib/libr_socket.so.0.9.9-git
> b65ee000-b65f2000 r-xp 00000000 08:01 22284589   /usr/lib/libr_lang.so.0.9.9-git
> b65f2000-b65f3000 rw-p 00003000 08:01 22284589   /usr/lib/libr_lang.so.0.9.9-git
> b65f3000-b6751000 r-xp 00000000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> b6751000-b6753000 r--p 0015e000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> b6753000-b6754000 rw-p 00160000 08:01 26345517   /lib/i386-linux-gnu/i686/cmov/libc-2.13.so
> b6754000-b6757000 rw-p 00000000 00:00 0
> b6757000-b675a000 r-xp 00000000 08:01 22283799   /usr/lib/libr_crypto.so.0.9.9-git
> b675a000-b675e000 rw-p 00002000 08:01 22283799   /usr/lib/libr_crypto.so.0.9.9-git
> b675e000-b676a000 r-xp 00000000 08:01 22284569   /usr/lib/libr_egg.so.0.9.9-git
> b676a000-b676b000 rw-p 0000c000 08:01 22284569   /usr/lib/libr_egg.so.0.9.9-git
> b676b000-b676d000 rw-p 00000000 00:00 0
> b676d000-b67b5000 r-xp 00000000 08:01 22286710   /usr/lib/libr_util.so.0.9.9-git
> b67b5000-b67b6000 rw-p 00048000 08:01 22286710   /usr/lib/libr_util.so.0.9.9-git
> b67b6000-b67bf000 rw-p 00000000 00:00 0
> b67bf000-b67c4000 r-xp 00000000 08:01 22284576   /usr/lib/libr_flags.so.0.9.9-git
> b67c4000-b67c5000 rw-p 00004000 08:01 22284576   /usr/lib/libr_flags.so.0.9.9-git
> b67c5000-b67d7000 r-xp 00000000 08:01 22284592   /usr/lib/libr_magic.so.0.9.9-git
> b67d7000-b67d8000 rw-p 00011000 08:01 22284592   /usr/lib/libr_magic.so.0.9.9-git
> b67d8000-b67e2000 r-xp 00000000 08:01 22284582   /usr/lib/libr_hash.so.0.9.9-git
> b67e2000-b67e3000 rw-p 0000a000 08:01 22284582   /usr/lib/libr_hash.so.0.9.9-git
> b67e3000-b67fe000 r-xp 00000000 08:01 22284554   /usr/lib/libr_db.so.0.9.9-git
> b67fe000-b6800000 rw-p 0001a000 08:01 22284554   /usr/lib/libr_db.so.0.9.9-git
> b6800000-b6819000 rw-p 00000000 00:00 0
> b6819000-b681b000 r-xp 00000000 08:01 22286708   /usr/lib/libr_syscall.so.0.9.9-git
> b681b000-b681c000 rw-p 00002000 08:01 22286708   /usr/lib/libr_syscall.so.0.9.9-git
> b681c000-b681d000 rw-p 00000000 00:00 0
> b681d000-b6b9f000 r-xp 00000000 08:01 22283775   /usr/lib/libr_asm.so.0.9.9-git
> b6b9f000-b6e90000 rw-p 00382000 08:01 22283775   /usr/lib/libr_asm.so.0.9.9-git
> b6e90000-b6ea5000 rw-p 00000000 00:00 0
> b6ea5000-b6ed6000 r-xp 00000000 08:01 22284580   /usr/lib/libr_fs.so.0.9.9-git
> b6ed6000-b6ed8000 rw-p 00030000 08:01 22284580   /usr/lib/libr_fs.so.0.9.9-git
> b6ed8000-b6ede000 rw-p 00000000 00:00 0
> b6ede000-b6f1f000 r-xp 00000000 08:01 22284585   /usr/lib/libr_io.so.0.9.9-git
> b6f1f000-b6f27000 rw-p 00040000 08:01 22284585   /usr/lib/libr_io.so.0.9.9-git
> b6f27000-b6f2d000 rw-p 00000000 00:00 0
> b6f2d000-b6f31000 r-xp 00000000 08:01 22283783   /usr/lib/libr_bp.so.0.9.9-git
> b6f31000-b6f32000 rw-p 00003000 08:01 22283783   /usr/lib/libr_bp.so.0.9.9-git
> b6f32000-b6f37000 r-xp 00000000 08:01 22285348   /usr/lib/libr_reg.so.0.9.9-git
> b6f37000-b6f38000 rw-p 00005000 08:01 22285348   /usr/lib/libr_reg.so.0.9.9-git
> b6f38000-b6f3b000 r-xp 00000000 08:01 22284562   /usr/lib/libr_diff.so.0.9.9-gitAborted
>
>  gdb -q r2 core
> Core was generated by `r2 /bin/ls'.
> Program terminated with signal 6, Aborted.
> #0  0xb7786424 in __kernel_vsyscall ()
> (gdb) bt
> #0  0xb7786424 in __kernel_vsyscall ()
> #1  0xb669e661 in *__GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
> #2  0xb66a1a92 in *__GI_abort () at abort.c:92
> #3  0xb66d9dc5 in __libc_message (do_abort=2, fmt=0xb67b4b50 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
> #4  0xb66e3eb1 in malloc_printerr (action=<optimized out>, str=0x6 <Address 0x6 out of bounds>, ptr=0x9c45d80) at malloc.c:6312
> #5  0xb66e5718 in _int_free (av=<optimized out>, p=<optimized out>) at malloc.c:4824
> #6  0xb66e885d in *__GI___libc_free (mem=0x9c45d80) at malloc.c:3738
> #7  0xb7661549 in r_search_keyword_new_hexmask (kwstr=0x9c76c7b "v/urandom", data=0x0) at keyword.c:148
> #8  0xb76ec333 in cmd_search (data=0x804f740, input=0x9c76c79 "dev/urandom") at cmd_search.c:1825
> #9  0xb7715f58 in r_cmd_call (cmd=0x98e3438, input=0x9c76c78 "/dev/urandom") at cmd_api.c:182
> #10 0xb76f17b6 in r_core_cmd_subst_i (core=0x804f740, cmd=0x9c76c78 "/dev/urandom", colon=0x0) at cmd.c:1583
> #11 0xb76efe64 in r_core_cmd_subst (core=0x804f740, cmd=0x9c76c78 "/dev/urandom") at cmd.c:1080
> #12 0xb76f222a in r_core_cmd (core=0x804f740, cstr=0x9c76c64 "/dev/urandom", log=0) at cmd.c:1801
> #13 0xb76f29ed in r_core_cmd_str (core=0x804f740, cmd=0x9c76c64 "/dev/urandom") at cmd.c:1982
> #14 0xb76f0c7e in r_core_cmd_subst_i (core=0x804f740, cmd=0x9c76c60 "s/ ", colon=0x0) at cmd.c:1376
> #15 0xb76efe64 in r_core_cmd_subst (core=0x804f740, cmd=0x9c76c60 "s/ ") at cmd.c:1080
> #16 0xb76f222a in r_core_cmd (core=0x804f740, cstr=0x9c76c30 " s/ `/dev/urandom`", log=1) at cmd.c:1801
> #17 0xb76b357e in r_core_prompt_exec (r=0x804f740) at core.c:1076
> #18 0x0804cd40 in main (argc=2, argv=0xbfda17b4, envp=0xbfda17c0) at radare2.c:777
> (gdb) x/i $pc
> => 0xb7786424 <__kernel_vsyscall+16>:   pop    %ebp
>
> I might bring a chair to bsides :)
>
> Greetings
> zlul
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2640>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by zonkzonk** [comment]
this is 32bit Debian 7, will test on other machine

**Comment by zonkzonk** [comment]
does NOT crash on 64bit arch current

**Comment by radare** [comment]
Use asan, it crashes on all systems, 

```[0x00000000]> s/ `/dev/urandom`
=================================================================
==15018==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000014c4c at pc 0x7f962312d852 bp 0x7fff95ad7270 sp 0x7fff95ad7260
WRITE of size 1 at 0x602000014c4c thread T0
    #0 0x7f962312d851 in r_hex_str2bin /home/pancake/prg/radare2/libr/util/hex.c:204
    #1 0x7f962312de38 in r_hex_str2binmask /home/pancake/prg/radare2/libr/util/hex.c:222
    #2 0x7f9626594f3a in r_search_keyword_new_hexmask /home/pancake/prg/radare2/libr/search/keyword.c:141
    #3 0x7f9626b4a19d in cmd_search /home/pancake/prg/radare2/libr/core/cmd_search.c:1825
    #4 0x7f9626ba580a in r_cmd_call /home/pancake/prg/radare2/libr/core/cmd_api.c:182
    #5 0x7f9626b56f8d in r_core_cmd_subst_i /home/pancake/prg/radare2/libr/core/cmd.c:1583
    #6 0x7f9626b52548 in r_core_cmd_subst /home/pancake/prg/radare2/libr/core/cmd.c:1080
    #7 0x7f9626b58d5b in r_core_cmd /home/pancake/prg/radare2/libr/core/cmd.c:1801
    #8 0x7f9626b59c68 in r_core_cmd_str /home/pancake/prg/radare2/libr/core/cmd.c:1982
    #9 0x7f9626b54cf2 in r_core_cmd_subst_i /home/pancake/prg/radare2/libr/core/cmd.c:1376
    #10 0x7f9626b52548 in r_core_cmd_subst /home/pancake/prg/radare2/libr/core/cmd.c:1080
    #11 0x7f9626b58d5b in r_core_cmd /home/pancake/prg/radare2/libr/core/cmd.c:1801
    #12 0x7f9626ac6855 in r_core_prompt_exec /home/pancake/prg/radare2/libr/core/core.c:1076
    #13 0x4076f0 in main /home/pancake/prg/radare2/binr/radare2/radare2.c:777
    #14 0x7f96229457ff in __libc_start_main /builddir/glibc-2.21/csu/libc-start.c:289
    #15 0x4030f8 in _start (/home/pancake/prg/radare2/binr/radare2/radare2+0x4030f8)

ASAN:SIGSEGV
==15018==AddressSanitizer: while reporting a bug found another one.Ignoring.


```

but appending /dev/urandom is somewhat dangerous and unpredictible... use sandbox inside a vm at least.. a spurious rm -rf / can be shown in urandom...

**Comment by zonkzonk** [comment]
@crowell @pancake
actually, using /dev/arandom crashed too, so it was no value of /dev/urandom :)
