### ISSUE TITLE
fix search highlight bug in cons/less.c similar to one fixed in visual highlight

### ISSUE THREAD

**Issue by jjdredd** [radare/radare2#2643]
just a reminder for me. Hope to fix this shortly.

**Comment by jjdredd** [comment]
also, see https://pad.nopcode.org/p/r2099

**Comment by radare** [comment]
ping @jjdredd

**Comment by jjdredd** [comment]
yeah, starting tonight

**Comment by radare** [comment]
ping?

**Comment by jjdredd** [comment]
Well, the bug mantioned in the title is fixed, but there are a couple of related issues:
- [ ] Modify less.c for an arbitrary number of matches using list?
- [ ] fix possible color loss in visual highlight and cons/less
- [ ] Highlight isn't removed when exiting Visual mode? (need testing!)

**Comment by radare** [comment]
is this fixed?

**Comment by jjdredd** [comment]
well, there are two minor bugs left, I'm not sure how to fix them yet. I guess this is enough for 0.9.9

**Comment by radare** [comment]
ok, milestone shifted

**Comment by radare** [comment]
ping?

**Comment by jjdredd** [comment]
2 seems simple at first, 3 idk how to fix, 4 needs recheck and possibly a fix (idk how hard will it be)
It's highly unlikely that I'll be able to contribute something this week, maybe two.

**Comment by radare** [comment]
Ok. I was just looking for some feedback. No hurry, this is totally low prio

**Comment by radare** [comment]
@jjdredd "fix shortly" - 2015

**Comment by radare** [comment]
Closing, reopen if you are in the mood some day
