### ISSUE TITLE
Comments and renamed variables are not saved in project.

### ISSUE THREAD

**Issue by NuclearHorseStudios** [radare/radare2#2648]
**Expected**:  

Renamed variables (`afvn`, `afan`) and comments (CC) to persist upon reload after saving a project.  

**Actual**:

After loading project (`Po`), renamed variables and comments no longer exist.  

Commands to reproduce, output, config, etc available here:

https://gist.github.com/NuclearHorseStudios/032003f6f4c2781347b2

radare2 0.9.9-git 7982 @ linux-little-x86-64 git.0.9.8-1630-g37d1dce
commit: 37d1dce099647e4d0f3e05e57b74ce3fb27b5669 build: 2015-05-28

**Comment by radare** [comment]
please confirm. we should have some tests to verify this

**Comment by radare** [comment]
^ @Maijin

**Comment by Maijin** [comment]
@radare https://github.com/radare/radare2-regressions/blob/master/t/cmd_project#L126

**Comment by radare** [comment]
Works for me

**Comment by Maijin** [comment]
Variables clearly doesn't => https://github.com/radare/radare2/issues/3855
