### ISSUE TITLE
and instruction missing flags setting (x86)

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2652]
```
           0x0061c1f9    2540000000     and eax, 0x40                                                            
```

```
           0x0061c1f9    2540000000     64,eax,&=                                                                
```

from the developers guide "The OF and CF flags are cleared; the SF, ZF, and PF flags are set according to the result. The state of the AF flag is undefined. "

http://x86.renejeschke.de/html/file_module_x86_id_12.html

**Comment by radare** [comment]
The patch is way smaller than this text :p several other instructions in esil/x86 doesnt update flags.

**Comment by crowell** [comment]
Someone reported it on irc. I thought it would be a nice one for him to fix
