### ISSUE TITLE
oc enables color :)

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2655]
morn,

http://radare.tv/a/67

Greetings
--zlul

**Comment by jvoisin** [comment]
This is expected, since it's like a *restart* of radare2, not sure if it's a bug.

**Comment by radare** [comment]
V! Disables color :) and this is a bug

**Comment by radare** [comment]
Not sure if we want to inherit the parent config when creating a new core... imho no, but im keeping this issue as open waiting for comments

**Comment by Maijin** [comment]
It's fixed here
