### ISSUE TITLE
Import data from JSON

### ISSUE THREAD

**Issue by radare** [radare/radare2#2662]
As long as many commands support json as output, it will be good to be able to import that information, in the same way, the `*` output mode works.

```
f* > flags.r2
. flags.r2
```

will be:

```
fj > flags.json
.j flags.json
```

**Comment by radare** [comment]
Importing json shouldnt be restricted to flags. we may probably need to change some jsons to start with a key specifying the kind of data stored in the document.

**Comment by jpenalbae** [comment]
which other cmds besides "f" support importing like that?

**Comment by radare** [comment]
Right now, there's no single command to import from json. the snippet is just an example for flags, but it may be useful for bin info, comments, functions, etc.

**Comment by radare** [comment]
im not sure this would be a good idea or not. im more about no right now...

**Comment by Maijin** [comment]
Duplicate with https://github.com/radare/radare2/issues/3222

**Comment by Maijin** [comment]
That has been done

**Comment by Maijin** [comment]
partially at least, the rest is tracked in #3222 already
