### ISSUE TITLE
debuggin with rarun2 fails, without doesnt

### ISSUE THREAD

**Issue by q6r** [radare/radare2#2663]
https://asciinema.org/a/akbly84exf5es6dhs5iotk17a

rarun2 causes a problem with debugging. without rarun2 it works fine. -D gdb didn't work at all for me for both cases with rarun2 and without rarun2.

**Comment by radare** [comment]
rarun2 is used for spawning using the native debugger backend. you can't use it together with gdb because is gdb who spawns the process in that case. so setting up that variables does nothing.
