### ISSUE TITLE
SIGSEGV on bogus libc.so

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#2668]
morrn,

running r2 against this file 
![libc-bogus 7z](https://cloud.githubusercontent.com/assets/5694980/7922874/70f9a628-08af-11e5-858e-08c6cbbfd623.png 
crashes:

```
[ 1536.630187] r2[6928]: segfault at 4 ip b77b7a72 sp bfad5614 error 4 in ld-2.13.so[b77ad000+1c000]
```

can folks reproduce? Debian7 32bit

Greetings
--zlul

**Comment by Maijin** [comment]
Can't reproduce

**Comment by jvoisin** [comment]
Can't reproduce, even with ASAN.

**Comment by XVilka** [comment]
Wrong one.

**Comment by zonkzonk** [comment]
so actually the problem happened in the linker. sorry. Wasn't radares fault.
