### ISSUE TITLE
rax2 -F is broken

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#2670]
What about removing the `rax2 -F` feature, since:
- It's broken (check the [tests](https://github.com/radare/radare2-regressions/blob/master/t.tools/rax2/rax2#L153-L158))
- I can't think about a single useful usercase, and even if I could, I could simply use `sed` instead
- It would remove yet-another-handcrafted-parser from r2 ;)

**Comment by Maijin** [comment]
@radare ping ?

**Comment by radare** [comment]
Theres nothing to parse here. -F uses  libc scanf/sprintf. I did it because it was necessary for a ctf. So yes its useful. Also for debugging fpu.

the functionality is just 1 or 2 lines to get the ptr and call scanf. So the bug should be really stupid. Or the test case is wrong.
