### ISSUE TITLE
iOS build broken

### ISSUE THREAD

**Issue by radare** [radare/radare2#2678]

**Comment by radare** [comment]
Fixed. Wondering how the hell it was able to build for any other platform before my patches :D

**Comment by jvoisin** [comment]
Yup, the build system is a bit convoluted :/

**Comment by radare** [comment]
no, only if you dont know how to write makefiles, the build system is
quite clean, it can be better, but its pretty simple and modularized.
the problem is that there were some hardcoded paths in the latest h8300,
v850... plugins which were wrongly done, see the commit
c0b1e5fad317b775a5c08e4cfeb547d055758b35
