### ISSUE TITLE
Fix search when hit is between two blocks

### ISSUE THREAD

**Issue by radare** [radare/radare2#2689]
https://github.com/radare/radare2-regressions/pull/191

**Comment by jjdredd** [comment]
I assumed this could happen by reading code, imo it's hard to catch a bug like this. It could be fixed by moving the block read 'window' by len(block) - len(needle), instead of len(block).

**Comment by radare** [comment]
Found one issue... but still not fixed completely. looks like search keywords are wrongly generated in the sense that they all contain a binary mask, even if this is fffffff which is useless and slowdowns the search.

**Comment by radare** [comment]
Fixed :) search keywords was always created with a binary mask. and binary masks search need full block hits in order to work because of the sub-hits. This can be improved, but it's actually working.

f182a726dfb77209c91586c4d4423ce200ee3ed3
