### ISSUE TITLE
Honor asm.midflags in `pi` and `pid`

### ISSUE THREAD

**Issue by radare** [radare/radare2#2690]
Fix t/disasm/midflags test

**Comment by jvoisin** [comment]
Nah, I don't think so. Why would `pi` and `pid` care about flags?

**Comment by radare** [comment]
They do show the flags unless asm.flags is disabled... So it would be consistent to honor that option too

**Comment by radare** [comment]
required for https://github.com/radare/radare2/issues/7249

**Comment by radare** [comment]
Fixed in master
