### ISSUE TITLE
Show colors in pi/pid or just keep that output black&white?

### ISSUE THREAD

**Issue by radare** [radare/radare2#2692]

**Comment by jvoisin** [comment]
Show colours, and honor `scr.color`.

**Comment by jpenalbae** [comment]
I'm with @jvoisin :+1:

**Comment by jjdredd** [comment]
for me `pi` is already colorized

**Comment by radare** [comment]
Only the arguments. Not the instruction itself.

One of the purposes of pi is to be fast and easy to parse. Thats why its not in the same loop as pd. But having only arguments colorized takes no sense.

When scripting most people already disable colors by default, so this shouldnt be a problem. Anyone for a pullreq?

**Comment by radare** [comment]
Done, colors everyfuckingwhere now
