### ISSUE TITLE
Enhance the graph layout

### ISSUE THREAD

**Issue by radare** [radare/radare2#2699]
* Do not overlap nodes
* Do not overlap edges
* Avoid crossing edges

**Comment by ret2libc** [comment]
This is partially fix with b3589b4a0cd85c94637451f39c3a78be16a595cb.
The only thing that remains to be done is:
* Do not overlap edges

**Comment by ret2libc** [comment]
Edges layout improved in 31dfeda157b93b5725179478dbe909fbd2a49f85

**Comment by radare** [comment]
Done!
