### ISSUE TITLE
Output Graph structure to graphviz dot format

### ISSUE THREAD

**Issue by radare** [radare/radare2#2701]
we can already dump function graphs and callgraphs to dot format, but not using the graph API used for ascii art rendering. The graph API should be exposed to bindings and r2 commandline, so anyone can create a graph with its contents and render it.. this way we can also do code graphdiffing in ascii art. and enable python/js to use that

**Comment by XVilka** [comment]
@ret2libc probably this could interest you.

**Comment by Maijin** [comment]
See META - GRAPH
