### ISSUE TITLE
Windows save project not working

### ISSUE THREAD

**Issue by jstewart1172** [radare/radare2#2716]
When saving a project on Windows it will create the blank file but not the .d folder with the xref as it does on Linux.  When trying to open a project it complains about not being able to find the project.

**Comment by radare** [comment]
Can you try changing the 'e dir.projects=...' Variable to see if its able to save the sdb instances in other paths? Is the directory containing spaces or special characters? I would like to reproduce this issue on linux.

Projects will relay more on sdb on future releases. This will be addressed for 1.0.

Thanks for reporting

**Comment by jstewart1172** [comment]
No spaces or special characters in path and I have tried saving in different locations.  I tried Radare2 on a Linux VM and it had no issue saving, But I really need it to work on Windows

**Comment by jstewart1172** [comment]
This is the error when I try to open the project
Invalid project name: 'C:\Users\user\Desktop/bomb'
Even after I changed the directory the last \ is still wrong and still no .d folder

**Comment by radare** [comment]
Please, build the last stuff from git, i did some changes related to this issue that will hopefully fix this (didnt tested)

**Comment by jstewart1172** [comment]
I rebuilt the latest version just now.  The path has the correct slashes now, but it still doesn't create the .d folder and when I try to open the project it says invalid project name or missing file.  I also tried changing the e dir.projects to my desktop path and it still isn't working..

**Comment by radare** [comment]
Ok. will try to reproduce on wine tonight if i have some time

**Comment by radare** [comment]
Please confirm :)

**Comment by jstewart1172** [comment]
[0x00401000]> Ps bomb
bomb
[0x00401000]> Po bomb
Invalid project name 'C:\Users\[User]\.config\radare2\projects\bomb'
Cannot retrieve information for project 'C:\Users\[User]\.config\radare2\projects\bomb'
[0x00401000]>

It creates the .d folder now.  Am I doing something wrong?

**Comment by radare** [comment]
Project saving works. Lets go fix the project opening :)

**Comment by crowell** [comment]
let's reopen this until saving *and* loading works :hushed:

**Comment by radare** [comment]
Po fixed

**Comment by radare** [comment]
Should be fine now

**Comment by jstewart1172** [comment]
Everything is great now, thanks!
