### ISSUE TITLE
wa doesn't generate correct assembly

### ISSUE THREAD

**Issue by grandemk** [radare/radare2#2731]
![screen2](https://cloud.githubusercontent.com/assets/5851912/8034413/abb7048a-0de7-11e5-9da1-4662c9301b61.jpg)

**Comment by grandemk** [comment]
![screen2](https://cloud.githubusercontent.com/assets/5851912/8035314/c7297312-0def-11e5-98e1-b973e9a0ea05.jpg)

**Comment by radare** [comment]
I dont see which instruction are you trying to assemble. Not all disassembled insteuctions can be disassembled. So please be more specific and paste the 'wa' line you are using

**Comment by grandemk** [comment]
For first picture:
"wa jge 0x40051e;mov eax,0;leave;ret"
for second picture:
wa jle 0x40051e

**Comment by radare** [comment]
sorry, my crappy internet didndt allowed me to watch the images and i was like wtf

**Comment by radare** [comment]
First of all you are assembling 32bit instructions (mov eax,..) on 64bit code. use 'rax' please :) second i cant reproduce. Which version of r2 are you using?

**Comment by radare** [comment]
You can also try with othwr assemblers like x86.new x86.olly or x86.as, the default one is .nz

**Comment by grandemk** [comment]
I am using the latest git version. I am rewritting the same assembly that was displayed to me, so mov eax, 0 should work right? It is also an 64bit opcode (or is there an other way to specify rax[0:31] ?)

I tried with x86.olly and I got the correct result :)

**Comment by crowell** [comment]
@grandemk `xor rax, rax`

**Comment by radare** [comment]
ok, i think the problem here is that you didnt reanalized the function after patching it, so, jusing `pdf` just tries to disassemble a wrong number of bytes because the basic blocks layout have changed, making it fail. Use the following commands to reanalize it:

```
s begin_of_function
af-
af
```

**Comment by grandemk** [comment]
@crowell ? that would set rax to 0, not rax[0:31] = 0

**Comment by grandemk** [comment]
@radare Thank you ! I had tried aa but af- solved it :)

**Comment by radare** [comment]
Wat

**Comment by grandemk** [comment]
@radare  ? I thought aa reanalized everything, but you need to tell radare2 to drop the analyse it already did (with af-) that's what I was missing

**Comment by radare** [comment]
aa will not reanalize if the function is already analized. i only told
r2 to drop the analysis of the function you patched, not the whole
thing. also, aa doesnt analyzes everything. only what is reachable by
symbols and related calls, see aaa or aac and all the anal. vars for
more details
