### ISSUE TITLE
Error saving project in Windows system with radare2

### ISSUE THREAD

**Issue by jholgui** [radare/radare2#2733]
Process:

![image](https://cloud.githubusercontent.com/assets/2709307/8055095/68c9e05a-0e9d-11e5-941a-9e8bb586aea2.png)

![image](https://cloud.githubusercontent.com/assets/2709307/8055736/09a5bb26-0ea2-11e5-8e9b-eac5d156744d.png)

![image](https://cloud.githubusercontent.com/assets/2709307/8055672/894b61e2-0ea1-11e5-9496-dbd5eeb708ed.png)

Radare2 does not save the information well. In Linux, r2 doesn't fail.

**Comment by radare** [comment]
Dupped of https://github.com/radare/radare2/issues/2716

**Comment by radare** [comment]
Please, build the last stuff from git, i did some changes related to this issue that will hopefully fix this (didnt tested)

**Comment by radare** [comment]
Po is working now too
