### ISSUE TITLE
Support all analysis info required for Diaphora and create a script to extract

### ISSUE THREAD

**Issue by radare** [radare/radare2#2742]
What is required:
- [x] Name of the function
- [x] Number of nodes & edges of the function
- [x] In and out-degree of the function
- [x] Size in bytes
- [x] Number of assembly instructions
- [x] The mnemonics (not the instruction)
- [x] The names referenced (strings and other constants)
- [x] The function's prototype
- [x] The comment of the function if any
- [x] The pseudo-code (decompiled code) of the function if any
- [x] The assembly dump and the relative virtual address.

* [ ] Script easy to use to extract those information

**Comment by joxeankoret** [comment]
What is required: name of the function, number of nodes & edges of the function, the in and out-degree of the function, the size in bytes, the number of assembly instructions, the mnemonics (not the instruction), the names referenced (strings and other constants), the function's prototype, the comment of the function if any, the pseudo-code (decompiled code) of the function if any, the assembly dump and the relative virtual address. All the other fields are calculated by Diaphora.

**Comment by joxeankoret** [comment]
Oh! And some structure or whatever representing the control flow graph of each function.

**Comment by radare** [comment]
Can you specify the type of each field? array of strings, graph, etc? Except the the decompilation, r2 can provide the all this information. and the decompilation can be extracted by using the retdec plugin or pdc/radeco in the future if needed. Also, mark which of those fields are optional

**Comment by radare** [comment]
ref https://github.com/joxeankoret/diaphora/blob/master/diaphora.py#L1020

**Comment by radare** [comment]
Waiting for @joxeankoret to provide an interface class to fill it with r2pipe magic

**Comment by jvoisin** [comment]
Any updates about this?
Shall we defer it to 1.0, or write the interface ourselves ?

**Comment by radare** [comment]
I guess we should do everything. But its ok for 1.0

**Comment by XVilka** [comment]
@sushant94 @oddcoder would be useful also for 'radare2 <-> radeco' interaction.

**Comment by radare** [comment]
see ?O to get the list of all the instructions

**Comment by radare** [comment]
inout degree is the number of xrefs and the number of refs? i think you can already have all the info you want from current r2. just need to chat a bit with you to confirm that

**Comment by joxeankoret** [comment]
One of the problems I'm facing: I have no idea how to, simply, get the number of edges in a function. That's it, for a function graph G = (V,E), where V = {A, B, C} and E = {(A,B), (A,C)}, I just want to know that there 2 edges. What command should I use for that? The help of the appropriate command (I think) afi is none.

**Comment by radare** [comment]
https://twitter.com/trufae/status/793504061152690178

**Comment by lowlyw** [comment]
When you say V and E do you mean for the BBS in a function, or its in and
out connectivity to other functions? afi can give this info

**Comment by joxeankoret** [comment]
With "V" I mean "vertex" (nodes, basic blocks) and with "E" I mean "Edges" (connections between basic blocks). Anyway, that part is already implemented, thanks to pancake.

**Comment by Maijin** [comment]
All those requirements are fullfilled, what is remaining for this to happen @joxeankoret

**Comment by joxeankoret** [comment]
GUI support, mainly.

**Comment by radare** [comment]
Buy a mac

**Comment by radare** [comment]
No srsly. Cant you just make a command line interface? Visual mode should be enough for most of that or at least a batch mode

**Comment by joxeankoret** [comment]
The Visual mode is cool, but non practical for diffing, I guess. Command line diffing? For example, I had a project where many functions had hundreds and even thousands of basic blocks. How am I supposed to analyse it with a command line version? No, you need a graph view with an overview or something similar.

That said, one Diaphora's side project is to create an independent GUI tool.

**Comment by radare** [comment]
is you create proper primitives the gui will be a separate part totally independent from the diffing engine and the backend source. so it doesnt matters if its a gui or a cli or a cui.

i understand a proper gui is needed for managing this kind of things for big projects, but that’s not a reason for blocking access to this, mainly because you cant test graphical apps.. well you can but its silly and having stuff done without tests is dangerous

**Comment by Maijin** [comment]
+ 1 for having the info available from CLI so we can test.

**Comment by joxeankoret** [comment]
Writing an exporter should be rather easy. I will start with this part.

**Comment by XVilka** [comment]
Can this be closed? Since it's completely done.

**Comment by XVilka** [comment]
@radare so what do you think? everything on radare2 side is ready/

**Comment by radare** [comment]
Yes i think we can close this issue and open another one to write the script that exposes all that info instead. Tired of waiting, this stupid python script is taking more than 2 years to be implemented.
