### ISSUE TITLE
Refactor RFlagSpaces to use RSpaces

### ISSUE THREAD

**Issue by radare** [radare/radare2#2761]
Remove libr/flags/spaces.c
Use libr/util/spaces.c
See libr/anal/meta.c and anal.c as an usage example

**Comment by condret** [comment]
I'm not sure if a double-linked list is the best idea for this

**Comment by radare** [comment]
r_spaces.h is not used anywhere, imho we should kill it

**Comment by Maijin** [comment]
It's used actually https://github.com/radare/radare2/blob/master/libr/anal/anal.c#L58

**Comment by radare** [comment]
And now in zignatures too . Cc @jroimartin

**Comment by jroimartin** [comment]
Yes. I'm using it for zignature spaces in my local branch. Also, I removed hardcoded commands present inside and updated CS accordingly.

**Comment by radare** [comment]
will merge together with your brnach, but not in 1.3. thanks!

**Comment by radare** [comment]
any update?

**Comment by jroimartin** [comment]
My plan is start working on it next week.

**Comment by radare** [comment]
Ok for 1.4 or not?

**Comment by jroimartin** [comment]
Yep, should be ready for 1.4.

**Comment by radare** [comment]
etoolate

**Comment by radare** [comment]
Ping? Werent u back? I though that refactor was almost ready.. just push your pr

**Comment by jroimartin** [comment]
ENOTIME, will do asap

**Comment by MaskRay** [comment]
An interval tree (the augmented binary search tree variant) is a best fit here https://github.com/radare/radare2/pull/8381
An attempt to refactor RAnal::fcns https://github.com/radare/radare2/pull/8387

prev/next flag can be answered in O(log n) time
intersection queries can be answered in O(log n + m) time

**Comment by ret2libc** [comment]
This is now fixed. RFlagSpaces are now implemented just with util/RSpaces. Rspaces uses rbtree as well.
