### ISSUE TITLE
Add `aar` command to analyze references

### ISSUE THREAD

**Issue by radare** [radare/radare2#2763]
something like `/r @@ sym.imp.*` but more optimal. to analyze the whole text section for instructions referencing an address inside the code or data segments. (find references to strings and functions in mov, lea, push instructions). This technique will not work on arm because addresses are constructed in code in order to retrieve a dword which can be spotted with /v4.

**Comment by radare** [comment]
Bonus points:
* [ ] add /r? help message

**Comment by ret2libc** [comment]
Is this fixed?

**Comment by radare** [comment]
Yep :)
