### ISSUE TITLE
Fail to save the settings in the cygwin while quitting

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2768]
Failing to create a directory:

```
[0x100401000]> q
r_sys_rmkdir: fail '/cygdrive/d' of '/cygdrive/d/Work/.config/radare2'
```

**Comment by radare** [comment]
can you try again?

**Comment by XVilka** [comment]
@radare bug is still here

**Comment by radare** [comment]
Can u try to run mkdir -p to create this and identify if the problem is in r2 mkdirp code or this path is just impossible to create in cygwinland?

**Comment by XVilka** [comment]
@radare `mkdir -p` worked flawlessly.

**Comment by radare** [comment]
Please confirm if this is fixed now

**Comment by radare** [comment]
let's consider this fixed
