### ISSUE TITLE
Rethink/Clarify pd/pi/pD/pI/pid/pdi/pdj/pij/pDj/....

### ISSUE THREAD

**Issue by radare** [radare/radare2#2770]
We need to avoid duppes. some commands just show the same output now that everybody wants all config vars to be obeyed by the disassembler loops. (color, pseudo, esil, decode..) so this clearly needs to be discussed and clarified to simplify those commands.

Probably the most important needs are the following
- disassemble N bytes or N instructions
- show output in JSON, or colorful/commentful
- fast plain/parseable disassembler without analysis or so. (disable color, ...)
- ...

**Comment by sushant94** [comment]
Yes. We need to work on this. I noticed several commands were giving *similar* output. Though this may not be a problem for experienced users, resolving this would certainly be useful for people wanting to use r2pipe.

**Comment by jvoisin** [comment]
Do we want to have less `pd` commands and configure everything with vars, like colours/offsets/bytes/... ?

**Comment by radare** [comment]
The benefit of having different commands is that you can get the output you want in a single command. which is important for the webui, r2pipe and so on.. also the benefits of having different configurable outputs makes more sense, but actually its implemented in different loops for performance reasons. because the big disasm loop is too huge to run fast. also, having pi for simplest instruction disassembling allows to benchmark different disassembler engines.

**Comment by ret2libc** [comment]
pxw/W/h/H/q/Q at the moment print words/halfwords/quadwords that it can find in N bytes.
I think they should be changed to print N words/halfwords/quadwords.

If scripts have bytes, they can easily convert number of bytes to number of words/hwords/qwords. In this way we can keep a reasonable number of commands.

**Comment by radare** [comment]
what about using gdb syntax to split in blocks/instructions/... this is:

px 10 -> show 10 bytes
px/w 10 -> show 10 words in bytes
pxw/w 10 -> show 10 words
..

we can define our own syntax for that /2 /4 ... or maybe just use : token

**Comment by ret2libc** [comment]
it seems good to me, but maybe making word the default for pxw, quadword the default for pxq, and halfword the default for pxh would be good, also making those commands easy to write

**Comment by radare** [comment]
that's pretty clear right know i think :)
