### ISSUE TITLE
run osx travis

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2777]
travis can do osx, let's do it!

**Comment by radare** [comment]
omg really? :D

**Comment by Maijin** [comment]
Yes but it'll double the time of running

**Comment by radare** [comment]
Would t be running in paralel?

**Comment by crowell** [comment]
@Maijin we already run clang on jenkins, no? it will be nice to have some osx stuff running

**Comment by radare** [comment]
What about an llvm bitcode build running all tests with lli?

**Comment by Maijin** [comment]
@crowell yes but we could also use only travis :p

**Comment by Maijin** [comment]
@XVilka for Clang and Mac OSX, it cannot be done without caching otherwise it will take age :p

**Comment by Maijin** [comment]
#3251

**Comment by Maijin** [comment]
done
