### ISSUE TITLE
Add havecode field in `i` list

### ISSUE THREAD

**Issue by radare** [radare/radare2#2780]
Only true if info->arch is != NULL

**Comment by radare** [comment]
Maybe also confirm the bin contains sections with executable bit set?

**Comment by alvarofe** [comment]
is this necessary? when loading a not binary file the info that is showed is only from core not from bin because of this https://github.com/radare/radare2/blob/master/libr/core/cmd_info.c#L167 so indirectly we are doing it

```
mac:tmp alvaro_fe$ r2 wifi-rR0rli.log
 -- vm is like a small cow in ascii
[0x00000000]> i
file     wifi-rR0rli.log
fd       7
size     0x60
blksz    0x0
mode     -r--
block    0x100
format   any
```

```
[0x100001174]> i
type     Executable file
file     /bin/ls
fd       7
size     0x9670
blksz    0x0
mode     -r--
block    0x100
format   mach064
pic      true
canary   true
nx       false
crypto   false
va       true
havecode true
intrp    /usr/lib/dyld
bintype  mach0
class    MACH064
lang     c
arch     x86
bits     64
machine  x86 64 all
os       osx
minopsz  1
maxopsz  16
pcalign  0
subsys   darwin
endian   little
stripped false
static   false
linenum  false
lsyms    false
relocs   false
binsz    38512
```

**Comment by radare** [comment]
Not really. You can have an elf that doenst contain code at all. And there are fileformats supported in r2 that are not binaries

**Comment by radare** [comment]
@alvarofe i think that we can asume that a binary have code when there's an entrypoint or a section with the executable bit set. What do you think?

**Comment by XVilka** [comment]
IMHO, it wouldn't harm by adding this field.

**Comment by alvarofe** [comment]
sorry i missed this. We can assume that
