### ISSUE TITLE
Add 'author' and 'version' field in plugins

### ISSUE THREAD

**Issue by radare** [radare/radare2#2781]
This is an ABI change. But it is important because this way we can avoid loading plugins compiled against a different version of r2. Authorship is also important because is tied to the license.

* [x] io
* [x] bin
* [x] asm
* [ ] anal
* [ ] debug
* [ ] core
- ...

**Comment by XVilka** [comment]
@radare what about a multiple authors?

**Comment by radare** [comment]
mindblown

**Comment by jvoisin** [comment]
Just use comma.

**Comment by radare** [comment]
I did the version thing. Author stuff should be done in the same struct probably. This way we dont have to change all plugins. And we can probably move some fields from module to libstruct to make it more generic

**Comment by radare** [comment]
What about moving this discussion to 1.0?

**Comment by jvoisin** [comment]
It is that hard/long to add an `author` field to a struct?
Am I missing something?

**Comment by radare** [comment]
What if theres more than one author? Do we want a string or an int to store the version? If a string we need a version comparator function. .. Blablabla

**Comment by Maijin** [comment]
.author = "nick1, nick2, nick3"
.version = "0.1.0"

Can't this *gnuism* be ported in r2ism ? https://sourceware.org/git/?p=glibc.git;a=blob;f=string/strverscmp.c;h=96d4227cd50090f3a7c45e7241d817d34e42f5ce;hb=cbc06bc486635347ee0da51d04a82eedf51602d5#l42 ?

See also http://stackoverflow.com/questions/15057010/comparing-version-numbers-in-c for other implementation to be ripped.

**Comment by radare** [comment]
There was an issue for that already

**Comment by Maijin** [comment]
For what...

**Comment by radare** [comment]
for dis https://github.com/radare/radare2/issues/2781 <https://github.com/radare/radare2/issues/2781>

**Comment by trufae** [comment]
:D

**Comment by Maijin** [comment]
This is the issue I just commented -_-

**Comment by radare** [comment]
lgtm

**Comment by radare** [comment]
Done for r_io in 30aebdc52150f61058e0842133e0e41eb79781d0

**Comment by radare** [comment]
@Maijin wanna do some more?

**Comment by radare** [comment]
Done for rbin in ef463f983eedadd56a96f6b184829dc5b93d075b

**Comment by radare** [comment]
Asm done in d6756e235cf13d98b6d8106bdbf6ed0fa65c91dc

**Comment by radare** [comment]
I have updated the *Plugin structs. well most of them, we now need to update all the plugins and enhance the way to visualize them. debug, core and anal are done in 5057cb6fb61dbea8339c2d0f16b08294f7dd94a6
