### ISSUE TITLE
Handle Zero Length Hashes

### ISSUE THREAD

**Issue by radare** [radare/radare2#2784]
```
$ printf '' | md5sum
d41d8cd98f00b204e9800998ecf8427e
$ printf '' | sha1sum
da39a3ee5e6b4b0d3255bfef95601890afd80709
```

rahash2 just considers null strings, empty buffers and zero length files as non-hashable.

**Comment by radare** [comment]
Done

**Comment by radare** [comment]
Do we have tests for this?

**Comment by Maijin** [comment]
@radare https://github.com/radare/radare2-regressions/commit/a13c6b0ec52ec2cb8bfe048e26419e7e3807359c Already broken?

**Comment by radare** [comment]
those tests are poorly written, see comment

**Comment by Maijin** [comment]
Yes, I'm changing that right away

**Comment by Maijin** [comment]
There are tests but they're broken now https://github.com/radare/radare2-regressions/blob/d0f6fd1688e5145ce2cfa9723fda1ba8c8c04d86/t.tools/rahash2/rahash2#L298-L310

**Comment by radare** [comment]
Should be fixed now
