### ISSUE TITLE
Search hashes

### ISSUE THREAD

**Issue by radare** [radare/radare2#2785]
By giving a length, find a sequence of bytes that match a specific hash using a given checksum algorithm. Ideally we should be supporting arbitrary length and start addresses, so the command will iterate over all possible lengths trying to find a region of the file that matches the hash

**Comment by jjdredd** [comment]
> . Ideally we should be supporting arbitrary length and start addresses, so the command will iterate
> over all possible lengths trying to find a region of the file that matches the hash

won't it be like O(N^2) ?

**Comment by radare** [comment]
Yep. That can be a loooong search. But providing some boundaries and cpu time it can be useful

**Comment by jvoisin** [comment]
What is the point of this?

**Comment by radare** [comment]
Use to reverse engineer unknown file formats. PD: i need it, but i didnt had time for it yet. Thats just a reminder for now

**Comment by radare** [comment]
Done in git :)
