### ISSUE TITLE
Remove unused functions

### ISSUE THREAD

**Issue by radare** [radare/radare2#279]
The r2 api is quite big right now and this makes the linker take so much time looking for symbols .. that's not really noticeable on current hardware, but we should remove unused functions (write a script to list all exports not imported). and try to make the api smaller by looking at usage patterns.

**Comment by Maijin** [comment]
What about closing this one ?

**Comment by radare** [comment]
My plan was to start cleaning up the apis after 1.0, and r2 to graph the whole codebase to find which functions are not used or only used once to catch them.

Dont close it. We will have some fun time refactoring after 1.0

**Comment by radare** [comment]
Unless anyone is gonna do some research on this refactoring. im moving it for 1.1.0

**Comment by radare** [comment]
i think that greeping for `rabin2 -s foo.dylib | grep GLOBAL |grep -v =r_` is enough to find many things that should be cleaned up

**Comment by radare** [comment]
beh, i think we can close this for now, removing unused functions is part of our continuous refactoring

**Comment by Maijin** [comment]
thanks closing this one 👍
