### ISSUE TITLE
ESIL 2.0 improvements

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2790]
- [ ] Standartize the usage of decimal/hex numbers
- [ ] Improve esil by adding support to more (commonly used) opcodes. eg: imul.
- [x] https://github.com/radare/radare2/issues/3374

**Comment by radare** [comment]
i vote for octal :P

hex values are usually more readable, but for small numbers they are a
pain, and as long as they are writen and reviewed by humans i think both
forms take sense in esil, and its just checking 2 bytes in order to
determine its base..

**Comment by sushant94** [comment]
I vote hex for everything. And then have an option to change between bases maybe?

**Comment by radare** [comment]
This will make it unnecesarily complex

**Comment by sushant94** [comment]
Another task:
 * [ ]  Improve esil by adding support to more (commonly used) opcodes. eg: imul.
