### ISSUE TITLE
renaming vars from visual mode renames functions

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2805]
the variable isn't renamed, but the function is...

**Comment by radare** [comment]
do you have a test case or at least an ascii enema?

**Comment by crowell** [comment]
https://asciinema.org/a/1ziuky1cw5ehq74ylcvc0fyeg

**Comment by radare** [comment]
i have never used that menu and last commit for this line was 2 years
ago, so it makes sense that it is not working at all :P

**Comment by Maijin** [comment]
@oddcoder ^

**Comment by Maijin** [comment]
Fixed, to rename function use `dr` to rename flag or var/local use `dn`
