### ISSUE TITLE
Use h instead of # to avoid problems with comments

### ISSUE THREAD

**Issue by radare** [radare/radare2#2813]
Discuss

```
> #md5
> h md5
```

hashbang

```
> #!pipe
> h!pipe
```

This will make /h more meaningful because /# is not possible. But for the hashing it seems ugly. also not sure if we should use 'h' with or without space for hashing.

**Comment by crowell** [comment]
uh... this isn't immediately even useful to me.

what is `/#` going to be?

**Comment by radare** [comment]
See the search hashes issue

**Comment by radare** [comment]
Reference https://github.com/radare/radare2/issues/2785

**Comment by crowell** [comment]
`/#` sounds like a terrible feature imo

**Comment by radare** [comment]
Feature or syntax? Because imho its very useful or maybe im the only one here that have been doing data reversing.. Will implemwnt it tonight. As well as fixing several bugs on the ios debugger that ive been delaying for a while.

**Comment by jvoisin** [comment]
I like `> h md5`, but I don't get the usage of the pipe thing, care to clarify?

**Comment by radare** [comment]
The pipe thing is the hashbang for r2pipe and rlang plugins to launch scripts interpretted by a different engine

**Comment by jvoisin** [comment]
I don't think that it's cool to share `h` for hashing *and* hashbang, is it?
If you think that it's ok, then I'm all for switching from `#` to `h`.

**Comment by radare** [comment]
i think #! is good as well as “# “ for comments. the only thing is that hmd5 looks uglier than #md5, so imho i like the current approach more, but i think that using # for more than comments or hashbangs is a bad idea.

**Comment by radare** [comment]
It's already done with ph
