### ISSUE TITLE
Self referenced basic blocks in ascii-art graph wrongly rendered

### ISSUE THREAD

**Issue by radare** [radare/radare2#2814]
Test case:
```
r2 -cwx' 4c8b014883c1084d85c075f4ffe0;af;' -
```

![screen shot 2015-06-21 at 12 04 28](https://cloud.githubusercontent.com/assets/917142/8271252/c2ecbc96-180d-11e5-9e51-f3431d49fb19.png)

**Comment by radare** [comment]
cc @ret2libc

**Comment by ret2libc** [comment]
Regression from when? It seems to work the same way in 5efc92520d9e43e22cd60802e9c70b39cc22ed81

**Comment by radare** [comment]
is this fixed?

**Comment by ret2libc** [comment]
I think it's kinda fixed. To test:
```
agn title1 body1
age title1 title1
agg
```

**Comment by radare** [comment]
A test case with those commands will be good. Can @maijin or you send a pr?

**Comment by radare** [comment]
you guys are too slow..

**Comment by radare** [comment]
just did it myself, after being bored of waiting
