### ISSUE TITLE
add the possibility to rebind key in ascii-graph view

### ISSUE THREAD

**Issue by ampotos** [radare/radare2#2838]
I use radare on azerty keyboard and I can't use ascii-graph properly because the binding to move the canvas is only made for qwerty (I quit accidentally the view instead of move the canvas to the left quite often).
It would be nice to add the possibility to change the binding on ascii-graph view to make it's use easier.

**Comment by Maijin** [comment]
Azerty ^\o/^

**Comment by jvoisin** [comment]
Do we want to simply add new configurations variables?

**Comment by radare** [comment]
what about using SDFG :D its like left-hand HJKL and its portable across
all major keyboard layouts

dunno if those keys are already taken..

**Comment by ret2libc** [comment]
+1 for adding configuration variables
(can you add graph label?)

**Comment by XVilka** [comment]
I'd suggest even refactoring to store the all keybindings in the SDB, and selecting the 'profile' via the config variable.

**Comment by crowell** [comment]
@radare please no! this should be configurable. sdfg is a terrible compromise ;)

**Comment by radare** [comment]
Damn humans :p

A fully cofigurable keymap looks interesting approach. But we should have some sane defaults.

Another option would be to use HJKL for canvas movement and hjkl for node movement. And just use a different key to toggle between 1 char or 4 char deltas. This looks better and simpler to me and will free the wasd and WASD keys.

Which key do u want for toggling the speed?

**Comment by radare** [comment]
I did this change, let me know how does it feel

**Comment by radare** [comment]
For simplicity i would prefer not to allow to configure all the keys, otherwise it every user will have different setups which will make it unusable for other users.
