### ISSUE TITLE
af - analyze just a single function

### ISSUE THREAD

**Issue by radare** [radare/radare2#2839]
without going into the calls or anal.hasnext. maybe under a different command

**Comment by radare** [comment]
Sometimes when doing `Vdf` in the debugger takes so much time because of this.

**Comment by ret2libc** [comment]
does af go into calls? it seems to me it doesn't analyze called functions

**Comment by radare** [comment]
Yes

**Comment by ret2libc** [comment]
So it doesn't work very well. Sometimes it analyzes calls, many other times it doesn't

**Comment by radare** [comment]
Example?

**Comment by ret2libc** [comment]
https://asciinema.org/a/4ckyu11r8hcb6vhwb8r0m0r3p
as you can see when i do pdf~call there are still a lot of call to not defined functions

**Comment by ret2libc** [comment]
also, if af already analyzes calls, what's the difference between af and aac?

**Comment by radare** [comment]
af follow calls. aac find calls. its completely different

**Comment by radare** [comment]
there’s no bug on that. you cant statically find main from entry0 if the addresses are calculated lik ethis because it requires code emulation. whcih is not performed by af. i already explained this in irc.

**Comment by ret2libc** [comment]
i wasn't referring to the main.
Example:
* take this: https://github.com/ctfs/write-ups-2015/raw/master/defcon-qualifier-ctf-2015/pwnable/wibbly-wobbly-timey-wimey/wwtw_c3722e23150e1d5abbc1c248d99d718d
* s 0x2d0d
* af
* pdf ~ call

you'll still see some calls like 'call 0xaa0', where instead you should find 'call fcn.00000aa0'. And there's more than one.

**Comment by radare** [comment]
nice catch, i’ve never found that bug. will investigate when i have some time, but feel free to go fix it if you are in the mood.

**Comment by radare** [comment]
Maybe this should go into a different task

**Comment by ret2libc** [comment]
Isn't it already done in aF?

**Comment by radare** [comment]
Yes
