### ISSUE TITLE
cmd.hit can be used to dos radare2

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2841]
!e search.in=raw
!e search.from = 0
!e cmd.hit=px 1 or even worse !e cmd.hit=/ ff
!/ ff

**Comment by radare** [comment]
We can disable cmd.hit when sandbox mode is enabled. what do you think?

because handling recursive calls like this is not easy

**Comment by Maijin** [comment]
I think that's the best if we want to avoid this possibility ? At least from now ?

**Comment by radare** [comment]
nested searchs are forbidden. i would restrict the search in sandbox mode to be to-from <= filesize

**Comment by radare** [comment]
Also, blocksize should be restricted too
