### ISSUE TITLE
Project save swaps variable name and type

### ISSUE THREAD

**Issue by bluec0re** [radare/radare2#2844]
When a project is saved, it mixes local and argument variable names and types:

Saved:

> [...]
**afa 8 *int arg_2* @ 0x80487d5**
**afv 0 *int local_0* @ 0x80487d5**
**afv 12 *int local_3* @ 0x80487d5**
af+ 0x08048821 93 sym.create_struct s n
afb+ 0x08048821 0x08048821 0000 0xffffffffffffffff 0xffffffffffffffff n n
**afv 12 *int local_3* @ 0x8048821**
[...]

Should  be:

>[...]
**afa 8 *arg_2 int* @ 0x80487d5**
**afv 0 *local_0 int* @ 0x80487d5**
**afv 12 *local_3 int* @ 0x80487d5**
af+ 0x08048821 93 sym.create_struct s n
afb+ 0x08048821 0x08048821 0000 0xffffffffffffffff 0xffffffffffffffff n n
**afv 12 *local_3 int* @ 0x8048821**
[...]

Loading and resaving fixes it until next save (swap of swap).

Version:
>radare2 0.9.9 9999999 @ linux-little-x86-64 git.0.9.9
commit: HEAD build: 2015-06-05
0.9.9  r2
0.9.9  r_anal
0.9.9  r_lib
0.9.9  r_egg
0.9.9  r_asm
0.9.9  r_bin
0.9.9  r_cons
0.9.9  r_flags
0.9.9  r_core
0.9.9  r_crypto
0.9.9  r_db
0.9.9  r_bp
0.9.9  r_debug
0.9.9  r_hash
0.9.9  r_fs
0.9.9  r_io
0.9.9  r_magic
0.9.9  r_parse
0.9.9  r_reg
0.9.9  r_sign
0.9.9  r_search
0.9.9  r_syscall
0.9.9  r_util

**Comment by bluec0re** [comment]
Still exists in
>radare2 0.10.0-git 8250 @ linux-little-x86-64 git.0.9.9-148-gd5f2661
commit: d5f2661cbe1a32bc26490bd7a1864ef45907aaea build: 2015-06-26

**Comment by radare** [comment]
Pls confirm after my commit

**Comment by bluec0re** [comment]
Is fixed. Thanks :)
