### ISSUE TITLE
mov rdi, section..text instead of main

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2876]
when `__libc_start_main` is the called, `section..text` is put into rdi, this should be

`mov rdi, main` instead

```
[0x004048c5]> pdf@entry0
╒ (fcn) entry0 42
│          ;-- entry0:
│          0x004048c5    31ed           xor ebp, ebp
│          0x004048c7    4989d1         mov r9, rdx
│          0x004048ca    5e             pop rsi
│          0x004048cb    4889e2         mov rdx, rsp
│          0x004048ce    4883e4f0       and rsp, 0xfffffffffffffff0
│          0x004048d2    50             push rax
│          0x004048d3    54             push rsp
│          0x004048d4    49c7c0502541.  mov r8, fcn.00412550           ; fcn.00412550
│          0x004048db    48c7c1e02441.  mov rcx, fcn.004124e0
│          0x004048e2    48c7c7a02840.  mov rdi, section..text         ; "AWAVAUATUS..H..H...." @ 0x4028a0
│          0x004048e9    e802dcffff     call sym.imp.__libc_start_main ;sym.imp.__libc_start_main(unk, unk)
╘          0x004048ee    f4             hlt
[0x004048c5]>
```

**Comment by radare** [comment]
If an address is flagged twice which one to choose? This has been a question from the very first times in r2land

**Comment by jvoisin** [comment]
Functions are more important than sections in my opinion.

**Comment by crowell** [comment]
+1 @jvoisin

**Comment by crowell** [comment]
also `AWAVAUATUS` is a great string.

**Comment by radare** [comment]
Main is not a function. Yet

**Comment by jvoisin** [comment]
Functions-related flags are more important than sections-related ones then :dancer:

**Comment by ret2libc** [comment]
+1 @jvoisin

**Comment by radare** [comment]
Flags doesnt have any reference to functions, imports, sections or anything like that. Boom

**Comment by radare** [comment]
maybe we can use the flagspace for this.. a rewrite of rflags on top of sdb will be helpful for performance reasons and simplifcation of code.

**Comment by radare** [comment]
can we have a test case for this issue?

**Comment by Maijin** [comment]
http://rghost.net/private/8BLkKYjyt/db4bf522462bbee2c937c04a4e57e924

```
r2 -A -qc "s 0x0040488d ; pi 1" /bin/ls
mov rdi, section..text
```

Where it should be
```
r2 -A -qc "s 0x0040488d ; pi 1" /bin/ls
mov rdi, main
```

**Comment by Maijin** [comment]
ping ?
