### ISSUE TITLE
Can't find function 'entry0' !

### ISSUE THREAD

**Issue by ghost** [radare/radare2#2885]
Hello 
I try to disassemble a virus in PE format  ( know as safedrive) with radare2. it's compressed with FSG v2.0 (detailed on http://www.openrce.org/reference_library/packer_database_view/23)
But don't know why it can't find it's entry point ?
```
r2 sample/SafeDrv.exe 
Warning: Invalid import directory size: 0x84 is now 0x81
 -- Ilo ni li pona li pali e lipu. mi wile e ni: sina kama jo e musi
[0x00400154]> aa
Cannot find function 'entry0' at 0x00400154
```
I tried with the following code
```python
import pefile
pe =  pefile.PE("sample/SafeDrv.exe")
print pe.OPTIONAL_HEADER.AddressOfEntryPoint
```
which gives
```
340
```
but 
```
[0x00400154]> pdf @ 340
Cannot find function at 0x00000154
```

**Comment by jvoisin** [comment]
Can you please share the binary?

**Comment by Maijin** [comment]
@user597 Ensure you are using the latest github version of radare2.

**Comment by radare** [comment]
af @ 340
ie

**Comment by user597** [comment]
@jvoisin
it's compressed, but be carefull ! 
http://filebin.ca/27WIxxX9KzLx
@Maijin 
I need to update it 
```
radare2 0.9.9-git 7975 @ linux-little-x86-64 git.0.9.8-1623-g465f35b
commit: 465f35b2b28c28dafa81e6feb0311db8764fe9cc build: 2015-05-26
```
@radare 
```
[0x00400154]> af @ 340
Function too big at 0x304c530
```

**Comment by jvoisin** [comment]
With latest r2:
```
jvoisin@kaa 1:06 /tmp r2 SafeDrv.exe 
Warning: Invalid import directory size: 0x84 is now 0x81
 -- Control the height of the terminal on serial consoles with e scr.height
[0x00400154]> aa
Cannot find function 'entry0' at 0x00400154
[0x00400154]> pdf
Cannot find function at 0x00400154
[0x00400154]> ie
[Entrypoints]
vaddr=0x00400154 paddr=0x00000154 baddr=0x00400000 laddr=0x00000000

1 entrypoints

[0x00400154]> af @ 0x00400154
[0x00400154]> pdf
Cannot find function at 0x00400154
[0x00400154]> 
```

**Comment by radare** [comment]
Yeah the issue here is that the section information is not loaded properly.you can workaounr this by definig the text section by hand. i'll look into this to make a generic solution and compare it with the real windows loader. Where the entry point and text section is defined by other tools and which instructions are found in there?

You can define the text section like this:

```
> S 0 0x400000 $s $s text r-x
```

**Comment by jvoisin** [comment]
@radare Feel free to write a blogpost about sections manipulations; a lot of people are asking questions about this ;)

**Comment by Maijin** [comment]
Added a test case https://github.com/radare/radare2-regressions/blob/master/t.formats/pe/base_FSG + a binary that use this packing method

**Comment by Maijin** [comment]
That's fixed and tested
