### ISSUE TITLE
Improve OS X syscalls database

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2898]
https://github.com/radare/radare2/blob/master/libr/syscall/d/ios-x86-32 file line count is smaller than this http://dyjakan.sigsegv.pl/osx-bsd-syscalls/

**Comment by crowell** [comment]
the file you linked is ios, not osx. do they share the same syscalls?

On Wed, Jul 8, 2015 at 10:41 AM, Anton Kochkov <notifications@github.com>
wrote:

> https://github.com/radare/radare2/blob/master/libr/syscall/d/ios-x86-32
> file line count is smaller than this
> http://dyjakan.sigsegv.pl/osx-bsd-syscalls/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2898>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by XVilka** [comment]
yes, skimmed through them. Some match. Could be another file though, we should ask @radare

**Comment by radare** [comment]
yep, syscalls are different for each arch-os-bits triplet.
