### ISSUE TITLE
libr/core/disasm.c - r_core_print_disasm()

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#29]
r_core_print_disasm() is a 499 line long function with >50 local variables. I am sure this can be refactored and cleaned.

Reply 1:  This is in TODO since radare1 0.1.. we always made fun about how dirty this code is, but we never did nothing as long as it's not a priority and it will take lot of time to refactorize it in an extensible way. We are open to patches and proposals ;)

**Comment by jvoisin** [comment]
It's now 250 lines long, but has several `TODO` and way too much `#ifdef`, but it shouldn't be hard to refactor/split.

**Comment by radare** [comment]
That refactor is totally low prio for me. It would be nice, but all TODO, XXX in comments should be fixed or discussed

**Comment by radare** [comment]
we have already refactored a lot of things in disasm.c and ew will refactor even more in the future ,there's no need to keep an issue for that
