### ISSUE TITLE
Enhace sys/asan.sh build flags

### ISSUE THREAD

**Issue by radare** [radare/radare2#2900]
https://fuzzing-project.org/tutorial-cflags.html

**Comment by revskills** [comment]
What about a custom build (look at my NS slides):
AddressSanitizer: -fsanitize=address
LeakSanitizer: -fsanitize=leak
MemorySanitizer: -fsanitize=memory 
UBSan: -fsanitize=undefined
*SyzyASan: Windows specific (dunno if AddressSanitizer for Windows was renamed as Syzy)

**Comment by radare** [comment]
Yeah we can handle $1 for this. Do you want to send a pr for this?

**Comment by revskills** [comment]
$2, I'm not idiot

**Comment by radare** [comment]
yeah-sure.jpg

**Comment by radare** [comment]
Bored of waiting. There are some more interesting asan flags:

http://clang.llvm.org/docs/UsersManual.html#controlling-code-generation
