### ISSUE TITLE
PE plugin not returning any information with rabin2

### ISSUE THREAD

**Issue by boomboompsh** [radare/radare2#2920]
When examining a portable executable with rabin2, (specifically the Canon PIXMA MX432 firmware update utility), The utility fails to find any sections, strings, or anything else in the binary. I used gdb to examine a run with the -zzz option and it seemed that it failed on the arch->buf->buf check. Running with -S it fails because the RBinObject o is zero. Does the PE plugin not work in general, or is this something just on my machine? Objdump will find the information, so I know that it is in the binary.

**Comment by radare** [comment]
Are you running r2 from git? Can you reproduce the same problem with any other exe that can be distributed?

**Comment by boomboompsh** [comment]
I am running from git, rabin2 -v output:
rabin2 0.10.0-git 8401 @ linux-little-x86-64 git.0.9.9-302-gf90f947
commit: f90f947d078119b7ce0cb4edc1b43984662b9f5b build: 2015-07-09
I just checked with the Notepad++Portable.exe binary, and it worked properly, so it seems it is just an issue with the particular binary. Very strange that the other binary works with objdump but not with rabin2.

**Comment by boomboompsh** [comment]
link to download offending binary:
http://www.usa.canon.com/cusa/consumer/products/printers_multifunction/office_all_in_one_inkjet_printers/pixma_mx432#DriversAndSoftware
The firmware section has a self-extracting archive that contains the binary in question.

**Comment by Maijin** [comment]
@boomboompsh  If it's Printer_update.exe, it works here:

http://radare.tv/a/77

**Comment by Maijin** [comment]
Also you can see more PE infos that is not displayed in a dedicated command using `ik ***`. Like vs_version_info/... Which contains the version informations on binaries

**Comment by radare** [comment]
Can u paste pebear screenshot or just check if any other tool works with it?
