### ISSUE TITLE
Key to remove bytes in Visual mode

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2924]
like the

```
r?
```

**Comment by radare** [comment]
Shrinking the file? This can be done with the r command.. But as long as this is only usef in text editors i didnt added a shortkey for that.. I would suggest using x like in vim.

Also this can be only done with files. Not block devices or processes in memory. So its not an universal operation.

**Comment by radare** [comment]
What is the use case?

**Comment by Maijin** [comment]
@XVilka ping
