### ISSUE TITLE
x86_64 esil doesn't clear upper 32 bits, in at least mov instructions

### ISSUE THREAD

**Issue by dkreuter** [radare/radare2#2925]
$ r2 -b 64 -
    [0x00000000]> wa mov eax, 4
    Written 5 bytes (mov eax, 4) = wx b804000000
    [0x00000000]> e asm.esil=true
    [0x00000000]> pd 1
               0x00000000    b804000000     4,eax,=
    [0x00000000]> 

should be

    [0x00000000]> pd 1
               0x00000000    b804000000     4,rax,=
    [0x00000000]>

**Comment by radare** [comment]
We should set rax in that case

**Comment by radare** [comment]
wasnt this already fixed?

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t.esil/x86-64#L46-L54 Now is tested :p

**Comment by radare** [comment]
What about emulating it and check the register value? :p

**Comment by radare** [comment]
This is already done in git
