### ISSUE TITLE
Add proper attribution to randomart.c

### ISSUE THREAD

**Issue by neuschaefer** [radare/radare2#2927]
A quick search shows that the code seems to be originally from OpenSSH. I think this should be mentioned in a comment.

**Comment by radare** [comment]
Yes the code comes from there and iirc i kept a ref i. The header everytime i rip code from someone else. In facct the code is the same. And i kept the original comments in there. It was not even originary from openssh. Im just keeping the original reference and documwntation.

https://github.com/radare/radare2/blob/master/libr/util/randomart.c
