### ISSUE TITLE
Better opcode analysis information (ao)

### ISSUE THREAD

**Issue by radare** [radare/radare2#293]
`ao` doesn't works as expected. some stuff must be changed:

* [x] family : must be a string, not an integer
* [x] esil : support more opcodes and archs (at least mips,arm,x86)
* [x] `ao*` : must output in 'ah' format (anal hints)
* [ ] stack : reported value is wrong (2 instead of 8? wtf)
* [x] default size should be 1 instead of blocksize
* [x] `aoj` : should output in json format

**Comment by jvoisin** [comment]
Can you give an example of `ah` output? It doesn't spit anything here.

**Comment by radare** [comment]
```
[0x00000000]> ahb 16
[0x00000000]> ah
 0x00000000 - 0x00000000 bits=16
```
But looks like `aho` was broken after the disasm refactoring, and other commands like `ah?off` are not yet implemented. I would like to pay some attention to them, but i dont have much time lately to play with it.

**Comment by jvoisin** [comment]
Can we move this to 1.0?

**Comment by radare** [comment]
i would like to have this feature ready for the release. I think its very useful and handy. and important anotating code, maybe not make it perfect for 0.9.9... but at least make the basic stuff work like `aho` and such

**Comment by radare** [comment]
What do ` stack : reported value is wrong (2 instead of 8? wtf)` mean?

**Comment by radare** [comment]
Maybe @alvarofe can make `ah` happy again :)

**Comment by alvarofe** [comment]
Do I have to fix `aho` or `ao*` ? I assume `ao*`

**Comment by radare** [comment]
Yep fix them all. start by fixing `ah` and all his subcommands. that should reflect the results in `pd`.. I guess there's some kind of discussion in here, because anal hints are suposed to hijack the real opcode analysis, so, when you are analyzing an instruction we want to let the user the power to specify some hints on that instruction to change the arch,bits,esil,opcode,etc ..

**Comment by radare** [comment]
@alvarofe wanna checkout this easy task?

**Comment by radare** [comment]
otherwise i'll do it tonight :) it's a quick thing

**Comment by Maijin** [comment]
@alvarofe this fix seems to only fix "ao* : must output in 'ah' format (anal hints)" not "stack : reported value is wrong (2 instead of 8? wtf)"

**Comment by alvarofe** [comment]
yes, that's right. I didn't know what to write in the commit :s sorry for that. The other issue I don't even know what means. If someone could enlighten me I might give it a try

**Comment by Maijin** [comment]
@radare ^

**Comment by radare** [comment]
Ok. I can do it for my own. Maybe the description was not good enough. Sorry

Also i found that we should have analop.imm too. Not just ptr, refptr... After release we should redefine this struct to make it more powerful, to aviid depending on esil when aop is enough

**Comment by radare** [comment]
any test case for that last checkbox to close the issue?

**Comment by Maijin** [comment]
@radare I've added a aoj test but the stack output is constantly changin in aoj whereas in ao it's "null" which seems to be correct:

https://github.com/radare/radare2-regressions/commit/7707de01ecb13d05c03c98d6b5ce7cc73c779635

**Comment by radare** [comment]
i guess this is ok with x86.udis, can you confirm that this is only
happening in capstone?

**Comment by Maijin** [comment]
Same with udis, problem is only in `aoj`, stack display fine in `ao`
