### ISSUE TITLE
Add an AppVeyor badge to README.md

### ISSUE THREAD

**Issue by neuschaefer** [radare/radare2#2930]

**Comment by neuschaefer** [comment]
... Or maybe not. @XVilka ?

**Comment by crowell** [comment]
appveyor is constantly failing for reasons which seem to be beyond our control. better to wait until it is more stable i think.

**Comment by radare** [comment]
its beyond our control because we never checked the build log. i fileed an issue and submitted a theorical fix for the issue.

**Comment by jvoisin** [comment]
Done in 17a891cae0e4aa5fabd7a873734ebca80ad40fe5
