### ISSUE TITLE
arcompact analysis is broken

### ISSUE THREAD

**Issue by radare** [radare/radare2#294]
The arcompact analysis is broken. The best option is imho rewrite the gnu-dis code into a smallest function to get only the required information for analysis without all the cpp mayhem.

- instruction length can be 2, 4, 6 or 8
- branch analysis is broken

The testcase r2-regressions/t/asm/arcompact performs some tests, we should extend it to check more instructions and corner cases.

**Comment by Maijin** [comment]
@XVilka can u confirm the fix :?

**Comment by Maijin** [comment]
ping(2)
