### ISSUE TITLE
json contains ints displayed as hex

### ISSUE THREAD

**Issue by crowell** [radare/radare2#2941]
this is invalid json

JSON does not support hex literals (0x..) so numbers must be formatted as %llu instead of %PFMT64 or whatever.

**Comment by radare** [comment]
Which json?. I bet the patch is shorter than the issue

**Comment by crowell** [comment]
I'm fixing them as i find them, made this issue just as a reminder.

**Comment by radare** [comment]
Ok cool :)

**Comment by radare** [comment]
Can you tell which jsons are invalid?

**Comment by crowell** [comment]
i think they're all fixed by now, just never closed the bug.

On Sun, Oct 4, 2015 at 1:50 PM, radare <notifications@github.com> wrote:

> Can you tell which jsons are invalid?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2941#issuecomment-145369423>.
>



-- 
Jeff Crowell
https://github.com/crowell
