### ISSUE TITLE
Doesn't work bash completion

### ISSUE THREAD

**Issue by werber** [radare/radare2#2947]
Doesn't work bash completion with ! command as follow: 
`!ls /path`

**Comment by jvoisin** [comment]
Why would it?
`!` will execute the given command in `system`, nothing more.

**Comment by werber** [comment]
I thought if I can pass bash commands through "!" that it must be autocomplete like in bash, but if it shouldn't be, so... I'll close issue.

**Comment by radare** [comment]
you can run !bash to get a full featured bash shell without quitting r2
