### ISSUE TITLE
Problem with aar

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2959]
I've tried aar/arrj/aar\*. On /bin/ls after aaa, I get display on "aarj/aar*" but not with aar.
See this quick asciinema: 
* http://radare.tv/a/76

**Comment by radare** [comment]
Aar doesnt finds functions. It finds references and register them under the ax command

**Comment by deffi420** [comment]
Yup, radare got it right. `aar` is basically the same as `.aar*` so it is not supposed to print anything. After `aar`, you can list the references with `ax` or query them using `axt` and `axf`.

**Comment by Maijin** [comment]
Oh ok :+1: got it

**Comment by Maijin** [comment]
@radare @deffi420 so then aaa should do aar by default no?

**Comment by radare** [comment]
Yeah. Looks legit. I verified on different bins and it seems to be good. Feel free to send a pr with that change, if not i'll commit this in a while.

**Comment by radare** [comment]
Done. btw, this issue is related, feel free to add your comments in there: https://github.com/radare/radare2/issues/2958

**Comment by Maijin** [comment]
Great \o/
