### ISSUE TITLE
Segfault when disassembling a MIPS executable with asm.pseudo=true

### ISSUE THREAD

**Issue by karolba** [radare/radare2#2963]
r2 segfaults when it tries to disassemble a MIPS executable and when asm.pseudo is set to true.

    $ r2 -e asm.pseudo=true -c pd ./busybox
    Warning: Cannot initialize dynamic section
    [1]    25522 segmentation fault (core dumped)  r2 -e asm.pseudo=true -c pd ./busybox

Link to used MIPS busybox: <http://www.busybox.net/downloads/binaries/1.21.1/busybox-mips>

This happens on all MIPS executables, even on simple ones like GNU hello.

**Comment by crowell** [comment]
this is a simple fix due to `lui` having `<<16` in it. fixing now

**Comment by karolba** [comment]
Thank you!
