### ISSUE TITLE
seek to .section_name

### ISSUE THREAD

**Issue by C-H-A-I-R** [radare/radare2#2968]
morn,

can we have feature **seek to .section_name** ? Running s .comment, seeks to 0x00.
As workaround one can  specify the address.

**Comment by radare** [comment]
All sections are prefixed by 'section' thats to avoid naming conflicts between sections, symbols, strings...

**Comment by C-H-A-I-R** [comment]
ok, cool. Doing  s section..<section_name> with two dots works.
However. it seems that S. is screwed  
I get phdr0 displayed, instead of .data, which might be still right?

**Comment by radare** [comment]
Thats because .phdr header covers all sections linearly. So we maybe we should show all sections covered by current seek, instead of the first one as we do now

**Comment by radare** [comment]
Its two dots because the section name is .text instead of text. Other fileformats doesnt prefix them with dots

**Comment by C-H-A-I-R** [comment]
another feature request: can we have like a prompt for the current section? eg instead of displaying pc, using
section_name on the right side?

```
[0x00400220]> s section
section..init                     section_end..init                 section_end..text                 
section..fini                     section_end..fini                 section..rodata                   section_end..rodata               
section..data                     section_end..data                 section..eh_frame                 section_end..eh_frame             
section..jcr                      section_end..jcr                  section..got                      section_end..got                  
section..ctors                    section_end..ctors                section..dtors                    section_end..dtors                
section..bss                      section_end..bss                  section..comment                  section_end..comment              
section..note.openbsd.ident       section_end..note.openbsd.ident   section..shstrtab                 section_end..shstrtab             
section.phdr0                     section_end.phdr0                 section.phdr1                     section_end.phdr1                 
section.phdr2                     section_end.phdr2                 section.phdr3                     section_end.phdr3                 
section.phdr4                     section_end.phdr4                 section.ehdr                      section_end.ehdr                  
[0x00400220]> s section..ctors 
[ctors]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00737e70  ffff ffff ffff ffff b017                 ..........      
[0x00737e70]> 
```

?

**Comment by radare** [comment]
You want current section name to be shown in the prompt? Looks good to me, we can add this under the scr.section option (which doesnt exists yet). Lets mark this task as easy. Any volunteer? :)

**Comment by ret2libc** [comment]
It would be cool to have also symbols and functions in the prompt.. Like:

[fcn.0x8xxxxxx] and
[sym.foo+17]
Il 03/ago/2015 09:42, "radare" <notifications@github.com> ha scritto:

> You want current section name to be shown in the prompt? Looks good to me,
> we can add this under the scr.section option (which doesnt exists yet).
> Lets mark this task as easy. Any volunteer? :)
>
>
>

**Comment by radare** [comment]
Maybe we want to add a promot. Eval prefix? We already change that offset with the segoff thing for x86-16. What do you think? Scr groups all visual stuff from cursor, visual, prompt, terminal...

**Comment by radare** [comment]
A bit confusing but yep. Could be an option. Do we want to display also the offset? Main reason not to do that is to avoid cons glitches and usability problems when having long prompts. We can maybe think in using multiline prompts like some bash/zsh users do. But i never liked it and will be probably unsupported on windows

**Comment by ret2libc** [comment]
Why should it cause cons glitches?

I don't like the idea of multiline prompts btw.

**Comment by radare** [comment]
Because prompt is always displayed, but user input is processed to always fit in screen. We dont curtently chop prompt when bigger than screen width. And also it can result in 75 column prompt and just 5 chars left for user input which is quite unusable

**Comment by ret2libc** [comment]
If you print a 75 column prompt it's your mess imo :S Btw, the chopping thing is just an engineering problem, not a design one

**Comment by radare** [comment]
Flag names, aka symbol, sections... Can be very long :) and thats not what the user wants when seeking to a specific offset

**Comment by ret2libc** [comment]
@C-H-A-I-R please test if ```scr.promptflag``` and ```scr.promptsect``` are what you're looking for.
