### ISSUE TITLE
add commands 'agn-','age-' to remove nodes/edges from core->graph

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#2974]
fix test in r2-regressions/t/cmd_graph

**Comment by radare** [comment]
I think that we shuold rename agn/age into aGn/aGe.. and make `aG` to be a different function than the one that `ag` does right now. `ag` graphs the info from the function, but age shows the one created with agn and age. This way we can split the logic of ag and aG in differents commands.

**Comment by ret2libc** [comment]
Do you mean that ```ag``` commands should display the graph of a function and ```aG``` should display the ```core->graph``` ??

**Comment by radare** [comment]
Yes.. Or maybe we want afg to do that and leep ag for the handmade graph

**Comment by ret2libc** [comment]
So, for the moment I would keep them as they are. In the future, I agree we should split them: a list of commands that work on functions and a list of commands that work on core->graph. Or maybe (to avoid having too many commands) just use some special symbols or something to differentiate the two cases, like:

```
agn fcn.name_fun title1 body1 # works on fn.name_fun
age fcn.name_fun title1 title1

agn title1 body1 # works on core->graph
```

**Comment by radare** [comment]
Good, this way we can load a graph from a function inside this pointer, and modify it with commands. We should add other commands to group nodes and change colors etc.

We will need a command to clear the graph (i think we already have one)

**Comment by ret2libc** [comment]
```ag-``` is what you want, I think. Yeah they should be quite easy to do.

**Comment by radare** [comment]
Done in a pr
