### ISSUE TITLE
Unsupported relocs for this arch

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#2991]
hello,

I get this error, when analysing 
![foo](https://cloud.githubusercontent.com/assets/6604362/8838040/ffa881e0-30c9-11e5-81db-75c403bc55e0.png)

```
r2 foo
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
Unsupported relocs for this arch
 -- This is an unacceptable milion year dungeon.
[0x00101200]> aa
Function too big at 0x204320
Function too big at 0x2047a0
```

I can provide objdump output, if needed.

Greetings
VP

**Comment by radare** [comment]
can you provide the binary?

**Comment by VisualPrankDude** [comment]
see updated issue

**Comment by radare** [comment]
Ok, so no ELF-relocs are support for SPARC yet. the warning is correct. let's keep this issue until done. can this bin be uploaded to the regressions suite?

**Comment by VisualPrankDude** [comment]
@Maijin can you do that? Or shall I open extra issue in regression suite?

**Comment by VisualPrankDude** [comment]
Thanks! :)
