### ISSUE TITLE
px pfv.**** @ pfv.**** doesn't work

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2994]
`px pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[2].size @ pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[2].virtualAddress` :

Invalid address (pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[2].virtualAddress)

`[15:17:39] <Skia> I think it's linked to the @ cmd`

**Comment by XVilka** [comment]
@Maijin please push the corresponding test in the regression tests repository.

**Comment by Maijin** [comment]
@XVilka better do when fixed no?

**Comment by radare** [comment]
use backtick quotes after the @ if you want to use the output of that command. pfv... is not a flag. you are doing it wrong

**Comment by radare** [comment]
we can add a @ subcommand to handle pfv address values to avoid the quoting. but this doesnt fixes the problem of using it wrongly

**Comment by radare** [comment]
See ?@? help, we can add a @p:... and @@p: for the foreach iterator when the pf value is an array. not sure how this thing should work with strings

**Comment by radare** [comment]
ALso, fix the test because the test is wrong

**Comment by Maijin** [comment]
pr `pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[4].size @ pe_nt_image_headers32` @ `pfv.pe_nt_image_headers32.optionalHeader.dataDirectory[4].virtualAddress @ pe_nt_image_headers32`+8 > certif
