### ISSUE TITLE
agf doesn't print the entire graph

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3003]
edges are not considered when graph sizes are calculated

![Screenshots](http://i.imgur.com/rjjF7lF.png)

**Comment by radare** [comment]
Because of the terminal size?

**Comment by ret2libc** [comment]
I haven't investigated yet, but I'm quite sure it's because to print the graph we calculate its size (so that we can set the canvas size) but we just consider nodes. Edges sometimes can go beyond these limits
