### ISSUE TITLE
edges start outside the nodes sometimes in the minigraph

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3010]
https://github.com/radare/radare2/blob/master/libr/core/graph.c#L1760 this is used to reorder true/false branches when they can cross, but when the nodes are too small, like in the minigraph, the edges can start in a wrong place.
![wrong](https://cloud.githubusercontent.com/assets/562321/8895508/b1601f40-33dd-11e5-8aa9-9fcef2c25e19.png)

**Comment by radare** [comment]
Fixed now, but can be better
