### ISSUE TITLE
ESIL incorrectly computes parity flag.

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#3011]
x86 processors calculate parity flag only for the least significant byte.
(source: https://en.wikibooks.org/wiki/X86_Assembly/X86_Architecture#EFLAGS_Register)

However, esil currently calculates for all 64 bits. (%p)
(See [libr/anal/esil.c:184](https://github.com/radare/radare2/blob/master/libr/anal/esil.c#L184-L193))

**Comment by radare** [comment]
cc @condret
