### ISSUE TITLE
bug in uleb128 decoding in pf command

### ISSUE THREAD

**Issue by qjerome** [radare/radare2#3013]
It seems there is a small bug with the pf command when we specify a format to decode uleb128 encoded data.

Example:
binary data : "\x96\x01\x05"
radare commands:
      pf.test uu
      pf.test
radare output:
0xoffsetuleb1 = 150
0xoffsetuleb2 = 150

The correct output should be 150 and 5.

I noticed that if I add others uleb128 format I still get the value of the first uleb128 decoded (150 in this case), so probably you forgot to increment a pointer somewhere.

**Comment by radare** [comment]
Cc @hyask

**Comment by XVilka** [comment]
Pls add the test in the radare2-regressions
