### ISSUE TITLE
Enable stack by default in visual mode (e cmd.stack = px)

### ISSUE THREAD

**Issue by techvoltage** [radare/radare2#3018]
In the GUI the stack is not visible by default. Please enable it so that newcomers to radare find the Visual mode helpful.

**Comment by ret2libc** [comment]
I think you can easily get it with
```
Vpp
```

**Comment by XVilka** [comment]
Was very easy to fix, huh?

**Comment by condret** [comment]
Hi,
Look what they have for you, I guess it's worth reading, more info here <http://loliwifu.sandsonsinc.com/lnxkz>

Typos courtesy of my iPhone, lukas-runas@gmx.de
