### ISSUE TITLE
0.9.9 tarball make error

### ISSUE THREAD

**Issue by sparkhom** [radare/radare2#3019]
Hi there,

The release tarball for 0.9.9 (located at http://www.radare.org/get/radare2-0.9.9.tar.xz) has a bug in shlr/Makefile:

```
if [ ! -d capstone ]; then \
		git clone https://www.github.com/aquynh/capstone.git ; \
	fi
cd capstone ; \
		git reset --hard @^^^ ; \
		git checkout next ; \
		git reset --hard 3808eec03330341a09f8017c5370dbf6a4fa1c13 || \
	( if [ -d .git ]; then \
		git pull ; git reset --hard 3808eec03330341a09f8017c5370dbf6a4fa1c13 ; \
	else true ; fi)
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
if [ -n "21b9b25e9dae4af0ef309d4089a54e53b8f5b479" ]; then \
		cd capstone ; \
		git config user.name || ( \
		git config user.name "radare-travis" ; \
		git config user.email radare-travis@foo.com ) ; \
		EDITOR=cat git revert 21b9b25e9dae4af0ef309d4089a54e53b8f5b479 ; \
	fi
Serguey Parkhomovsky
fatal: Not a git repository (or any of the parent directories): .git
make[1]: *** [capstone-sync] Error 128
make: *** [all] Error 2
```

This errors out because the shlr/capstone directory already exists in the release tarball, but is not a git repository. A possible fix is to remove the capstone directory so that it is cloned from git on make.

Thanks,
Serguey

**Comment by radare** [comment]
Unm nope. The fix should be to support this. Mainly because our testsuite only works with a specific version of capstone. Most releases comes with bugs and is better to use that. But using the system one should be fine for 90% of ppl.

Thanks for noticing
