### ISSUE TITLE
remove R_ANAL_BB_HAS_OPS from r_anal

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3022]
this macro should allow to enable RAnalOp inside RAnalBlock.
The commit that introduced this macro is 686e23c9d825c7d48fc326683bb3db401bb65657 and it's from 2011. Btw, it was broken since then, because in one place there was a typo and it was R_ANAL_BB_HA_OPS instead of R_ANAL_BB_HAS_OPS.

Shall we remove it?
@radare

**Comment by radare** [comment]
I think this was introduced for the bindiff engine. I dont have a handy blame shell here, but if its unused and by meaning looks useless and deprecated its ok to rm

**Comment by Maijin** [comment]
https://github.com/radare/radare2/search?utf8=%E2%9C%93&q=R_ANAL_BB_HAS_OPS ?
