### ISSUE TITLE
AddressSanitizer: odr-violation ebc/ebc_disas.c:1024:8

### ISSUE THREAD

**Issue by revskills** [radare/radare2#3031]
Howto reproduce:
Add next options to the afl build script 'AFL_USE_ASAN=1'

```sh
r2 -v

==21210==ERROR: AddressSanitizer: odr-violation (0x7f28e26eb080):
  [1] size=464 'decodes' /ns/slides/radare2-afl/libr/..//libr/anal/p/../../asm/arch/ebc/ebc_disas.c:1024:8
  [2] size=464 'decodes' /ns/slides/radare2-afl/libr/..//libr/anal/p/../../asm/arch/ebc/ebc_disas.c:1024:8
These globals were registered at these points:
  [1]:
    #0 0x43f6e5  (/ns/slides/radare2-afl/binr/radare2/radare2+0x43f6e5)
    #1 0x7f28dfe136ee  (/usr/lib/libr_asm.so+0x60a6ee)
    #2 0x7f28e46115b9  (/lib64/ld-linux-x86-64.so.2+0x105b9)
    #3 0x7f28e46116ca  (/lib64/ld-linux-x86-64.so.2+0x106ca)
    #4 0x7f28e4601d09  (/lib64/ld-linux-x86-64.so.2+0xd09)

  [2]:
    #0 0x43f6e5  (/ns/slides/radare2-afl/binr/radare2/radare2+0x43f6e5)
    #1 0x7f28e1cab50e  (/usr/lib/libr_anal.so+0x31950e)
    #2 0x7f28e46115b9  (/lib64/ld-linux-x86-64.so.2+0x105b9)
    #3 0x7f28e46116ca  (/lib64/ld-linux-x86-64.so.2+0x106ca)
    #4 0x7f28e4601d09  (/lib64/ld-linux-x86-64.so.2+0xd09)
```

**Comment by radare** [comment]
Env var added to afl.sh

**Comment by radare** [comment]
Can you provide rasm2 oneliner to reproduce the crash?

**Comment by revskills** [comment]
:-( why have you added that env var for /sys/afl.sh. It seems that breaks all functionality until it is odr-violation, leaks are resolved. IMHO It should be done for -m32

**Comment by radare** [comment]
Should i drop that envvar then?

**Comment by radare** [comment]
pls confirm

**Comment by revskills** [comment]
this should be fixed too:

=================================================================
==20471==ERROR: AddressSanitizer: odr-violation (0x7fdc537212c0):
  [1] size=8192 'ins_hash' /ns/radare2/libr/..//libr/anal/p/../..//asm/arch/tms320/c55x_plus/hashvector.c:96:18
  [2] size=8192 'ins_hash' /ns/radare2/libr/..//libr/anal/p/../..//asm/arch/tms320/c55x_plus/hashvector.c:96:18
These globals were registered at these points:
  [1]:
    #0 0x43f6e5  (/ns/radare2/binr/radare2/radare2+0x43f6e5)
    #1 0x7fdc50ef759e  (/usr/lib/libr_asm.so+0x71359e)
    #2 0x7fdc556125b9  (/lib64/ld-linux-x86-64.so.2+0x105b9)
    #3 0x7fdc556126ca  (/lib64/ld-linux-x86-64.so.2+0x106ca)
    #4 0x7fdc55602d09  (/lib64/ld-linux-x86-64.so.2+0xd09)

  [2]:
    #0 0x43f6e5  (/ns/radare2/binr/radare2/radare2+0x43f6e5)
    #1 0x7fdc52d748de  (/usr/lib/libr_anal.so+0x4038de)
    #2 0x7fdc556125b9  (/lib64/ld-linux-x86-64.so.2+0x105b9)
    #3 0x7fdc556126ca  (/lib64/ld-linux-x86-64.so.2+0x106ca)
    #4 0x7fdc55602d09  (/lib64/ld-linux-x86-64.so.2+0xd09)

==20471==HINT: if you don't care about these warnings you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'ins_hash' at /ns/radare2/libr/..//libr/anal/p/../..//asm/arch/tms320/c55x_plus/hashvector.c:96:18
