### ISSUE TITLE
rasm2 doesn't produce correct output on darwin

### ISSUE THREAD

**Issue by Leandros** [radare/radare2#3041]
`rasm2` correctly disassembles the hex into an instruction.

```
$ rasm2 -a x86 -b 64 -d 8B55FC
mov edx, dword [rbp - 4]
```

however, it doesn't correctly assemble the same instruction into hex.
```
$ rasm2 -a x86 -b 64 'mov edx, dword [rbp - 4]'
8b5500fc
```

Using the built-in (horribly old) `as` produces the correct output, though.

```
$ cat as.asm # the very same instruction
.section __TEXT,__text
movl    -4(%rbp), %edx

$ as as.asm -o as.o

$ gobjdump -d as.o
as.o:     file format mach-o-x86-64

Disassembly of section .text:

0000000000000000 <.text>:
   0:	8b 55 fc             	mov    -0x4(%rbp),%edx
```

Am I missing something, or is the output from `rasm2` wrong?

**Comment by radare** [comment]
Remove the unnecessary dword , try other assemblers. Rasm2 -L. Operating systems have nothing to do here. There's even gas, nasm, olly x86 assembler plugins
