### ISSUE TITLE
Missing basic blocks

### ISSUE THREAD

**Issue by 0xabe-io** [radare/radare2#3044]
Hi,

I try to get all the basic blocks from a binary, but it seems that the analysis is missing some.

I compiled radare2 from git (commit: 1db221ede005d5d1ada2af2297f52c1fc79bb6a7)
I have capstone version 3.0.3 (from the Debian testing repositories)

For example if I analyze `/bin/ls` from Debian testing (coreutils 8.23):

```
[0x004028a0] afb @0x004028a0
0x004028a0 0x0040295b 00:0000 187 j 0x004031de f 0x0040295b
0x0040295b 0x00402960 00:0000 5 j 0x0040298f f 0x00402960
0x00402960 0x00402965 00:0000 5 j 0x0040296a f 0x00402965
0x00402965 0x0040296a 00:0000 5 j 0x0040296a
0x0040296a 0x0040297c 00:0000 18 j 0x004037a8 f 0x0040297c
0x0040297c 0x0040298f 00:0000 19 j 0x004029a5
0x0040298f 0x004029a5 00:0000 22 j 0x004029a5
0x004029a5 0x00402a30 00:0000 139 j 0x00402a5f f 0x00402a30
0x00402a30 0x00402a4f 00:0000 31 j 0x0040374a f 0x00402a4f
0x00402a4f 0x00402a5f 00:0000 16 j 0x00402a5f
0x00402a5f 0x00402a86 00:0000 39 j 0x00402a91 f 0x00402a86
0x00402a86 0x00402a91 00:0000 11 j 0x0040377c f 0x00402a91
0x00402a91 0x00402aac 00:0000 27 j 0x00402abd f 0x00402aac
0x00402aac 0x00402ab6 00:0000 10 j 0x00402abd f 0x00402ab6
0x00402ab6 0x00402abd 00:0000 7 j 0x00402abd
0x00402abd 0x00402ada 00:0000 29 j 0x00402b02 f 0x00402ada
0x00402ada 0x00402af6 00:0000 28 j 0x004040dd f 0x00402af6
0x00402af6 0x00402b02 00:0000 12 j 0x00402b02
0x00402b02 0x00402b3a 00:0000 56 j 0x004031f9 f 0x00402b3a
0x00402b3a 0x00402b4a 00:0000 16 j 0x004031d4 f 0x00402b4a
0x00402b4a 0x00402b51 00:0000 7
0x004031d4 0x004031de 00:0000 10 j 0x004031de
0x004031de 0x004031f9 00:0000 27 j 0x004029a5
0x004031f9 0x0040320a 00:0000 17 j 0x00403b03 f 0x0040320a
0x0040320a 0x00403220 00:0000 22 j 0x004037b7 f 0x00403220
0x00403220 0x00403246 00:0000 38 j 0x00404484 f 0x00403246
0x00403246 0x00403251 00:0000 11 j 0x00403286 f 0x00403251
0x0040374a 0x0040377c 00:0000 50 j 0x00402a5f
0x0040377c 0x00403792 00:0000 22 j 0x004037c9 f 0x00403792
0x00403792 0x0040379c 00:0000 10 j 0x004037c9 f 0x0040379c
0x0040379c 0x004037a8 00:0000 12 j 0x00402a91
0x004037a8 0x004037b7 00:0000 15 j 0x004029a5
0x004037b7 0x004037c9 00:0000 18 j 0x00403220
0x004037c9 0x004037fb 00:0000 50 j 0x00402a91
0x00403b03 0x00403b32 00:0000 47 j 0x004045c7 f 0x00403b32
0x00403b32 0x00403b4c 00:0000 26 j 0x00403b4c
0x00403b4c 0x00403b55 00:0000 9 j 0x0040320a f 0x00403b55
0x00403b55 0x00403b6f 00:0000 26 j 0x0040320a
0x004040dd 0x0040410f 00:0000 50 j 0x00402b02
0x00404484 0x0040449f 00:0000 27 j 0x00403246
0x004045c7 0x004045da 00:0000 19 j 0x00403b32 f 0x004045da
0x004045da 0x004045df 00:0000 5 j 0x00403b4c
```

we can see that there are some gaps between basic blocks, for example:
```
0x00403246 0x00403251 00:0000 11 j 0x00403286 f 0x00403251
0x0040374a 0x0040377c 00:0000 50 j 0x00402a5f
```

If I try to print the basic block at the destination of the jumps, it tells me that it can't find the function:
```
[0x004028a0]> pdb @0x00403286
Cannot find function at 0x00403286
[0x004028a0]> pdb @0x00403251
Cannot find function at 0x00403251
```

But if I print the function the code is there:
```
[0x004028a0]> pdf @0x00403251
Do you want to print 1971 lines? (y/N)
[snip]
|           ; JMP XREF from 0x0040449a (section..text)
| --------> 0x00403246    8b05e09f2100   mov eax, dword [rip + 0x219fe0] ; [0x61d22c:4]=-1
| |  |      0x0040324c    83f801         cmp eax, 1                    ; "ELF..." @ 0x1
| ========< 0x0040324f    7635           jbe 0x403286                 
| |  |      0x00403251    83e802         sub eax, 2
| |  |      0x00403254    4c8db8125241.  lea r15, qword [rax + str._____] ; 0x415212 ; str._____ ; "*=>@|" @ 0x415212
| |  |      0x0040325b    0fb680125241.  movzx eax, byte [rax + str._____] ; [0x415212:1]=42 LEA str._____ ; "*=>@|" @ 0x415212
| |  |      0x00403262    84c0           test al, al
| ========< 0x00403264    7420           je 0x403286                  
|           ; JMP XREF from 0x00403284 (section..text)
| --------> 0x00403266    488b3d7b9f21.  mov rdi, qword [rip + 0x219f7b] ; [0x61d1e8:8]=-1
| |  |      0x0040326d    4983c701       add r15, 1
| |  |      0x00403271    0fbef0         movsx esi, al
| |  |      0x00403274    ba01000000     mov edx, 1
| |  |      0x00403279    e8c2b70000     call 0x40ea40
| |  |        ^- 0x0040ea40() ; fcn.0040e830+528
| |  |      0x0040327e    410fb607       movzx eax, byte [r15]
| |  |      0x00403282    84c0           test al, al
| ========< 0x00403284    75e0           jne 0x403266                 
|           ; JMP XREF from 0x0040324f (section..text)
|           ; JMP XREF from 0x00403264 (section..text)
| --------> 0x00403286    31ff           xor edi, edi
| |  |      0x00403288    e853b70000     call 0x40e9e0                  ; fcn.0040e830+0x1b0
| |  |        ^- fcn.0040e830()
| |  |      0x0040328d    ba01000000     mov edx, 1
[snip]
```

The same behavior can be reproduced if I compile the tagged 0.9.9 version, as well as on an up-to-date Archlinux with radare2 commit: 421d3c3dd11c68d368c6e8da17f7ddc654a23184 (from the blackarch repo)

Am I doing something wrong or the analysis is missing them? 

Thanks

**Comment by radare** [comment]
Try with git please. Also there are some anal. Options you can tune to get better analysis results. 

From what i see you are looking for the basic blocks of a function, not the whole binary. The code coverage for full analysis can be enhaced by using other analysis commands.

Those days we are working a bit on the analysis engine, in order to identify and fix those issues.

There's also the command a2f command which is a rewritten analysis loop. The only missing part is the jump tables which are considered an end of function. This will be adressed soon too.

Can you provide the binary so we can test it?

**Comment by ret2libc** [comment]
The analysis in r2 at the moment has some limitations that prevents r2 from discovering some "deep" basic blocks.

**Comment by 0xabe-io** [comment]
Thanks for your responses.

Yes I compiled from git (commit: 1db221ede005d5d1ada2af2297f52c1fc79bb6a7)

Here is the `ls` binary: https://tinyurl.com/nfd4nzh
sha256: ce14856cf5fce0b4401fac00d50e1ce82b641be19a2566121045c9bcd30b4664

(I was wrong in my previous message: this is `ls` version 8.23 from binutils 2.25-11 in the debian testing repo)

**Comment by 0xabe-io** [comment]
I think I found a way to get all the basic blocks:
I iterate over all the functions reported by `afl`. For each function, I take its list of basic block with `afb`. If I find gaps between basic blocks, I analyze them with `a2f`.

With that each calls or jumps found in the text leads to basic block that has been found.

I have a question about `a2f`:
As I am using r2pipe to communicate between a python script and r2, I can't get all the output of `a2f` because the first part until the lines that look like an output of `afl*` are written to stderr (r2pipe python doesn't support stderr yet). Is this something normal or just temporary during the work on the analysis engine?

**Comment by radare** [comment]
The stuff that is printed to stderr is just debugging info or error messages. In the cAse of a2f, its just a wip implementation. We can probably add an option to r2pipe to close the stderr filedescriptor of the r2 spawn.
