### ISSUE TITLE
Commands priority for external plugins first

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3046]
To be able add commands before the builtin ones.
E.g. (actual example)
```
[0x000000]> yara
```
(with loaded yara plugin)
return usage for 'y' command.

**Comment by Darkkey** [comment]
Same problem. core_yara3.dylib is loaded (according to strace -f), but cannot use it.

**Comment by Darkkey** [comment]
[0x100001058]> ?:
anal: The reworked analysis from scratch thing
java: Suite of java commands, java help for more info
yara3: YARA V3 integration
[0x100001058]> yara3

^ yara3 is working, the documentation should be fixed, not code.

**Comment by XVilka** [comment]
Screw that, my bad. Not actually a bug. Though, my suggestion to drop the yara2 support, and use yara3 be default.

**Comment by radare** [comment]
The command is yara3, not yara

**Comment by XVilka** [comment]
@radare figured already - thats why I closed the bug.
