### ISSUE TITLE
Split the assembler plugins from the disassembler

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3049]
Nowadays, after growing quarterly list of the supporting architectures, it is hard to find what libr/asm/p/asm_*.c file is disassembler plugin, and what is an assembler one. I'm suggesting to split them into the libr/asm  and libr/dasm. Or some other way.

**Comment by radare** [comment]
Nope that would make it even more hard to maintain. We want to mergw libs, not split them. What is the problem to find which is the assembler and which the disassembler? Just check the callbacks

**Comment by XVilka** [comment]
@radare at least change the naming scheme or put it in the another directory. Right now you need to open each file to understand if it is assembler or disassembler plugin. Should be understandable from the file name or path, imho.

**Comment by radare** [comment]
I use grep

**Comment by XVilka** [comment]
Still not the right way to go, don't you think?

**Comment by radare** [comment]
I think it's fine the way we go right now. Maybe in the future we can just cook an "assembler" library, that just does like capstone, but for assembling, and just use it as an external to drop all this logic to a different code module. but at plugin level, adding another kind of plugin just for assembling seems to me like too much unnecessary refactoring atm.

Also, maybe it will be good to select a different assembler than the disassembler, but this is done in purpose to enforce good defaults

**Comment by XVilka** [comment]
@radare I'm not talking about refactoring - just, at least place assembler plugins in the another directory in radare2 sources? For example in `libr/asm/a` from `libr/asm/p`
It will require a very little of the refactoring and nearly zero effort. What do you think about that approach?

**Comment by radare** [comment]
p is for plugin, using a will be even more confusing, in theory ALL archs should support assemble and disassemble, so its just a matter of time, and i dont think we should do that split at source level, a simple grep is enough to find what you need.

**Comment by XVilka** [comment]
@radare at least name then properly then? asm_x86_nz.c and disasm_x86_cs.c?

**Comment by Maijin** [comment]
ping @radare

**Comment by radare** [comment]
This is already done
