### ISSUE TITLE
glibc 2.22 printf is a macro

### ISSUE THREAD

**Issue by shua** [radare/radare2#3052]
In the latest test edition of glibc printf is defined as a preprocessor macro.

This is a problem for any structure like RPrint which has a member function called printf, and any call to p->printf(...) gets changed by the preprocessor to p->__printf_chk(...) and yields an compiler error.

RPrint defined in libr/include/r_print.h

**Comment by jjdredd** [comment]
sweet

**Comment by shua** [comment]
thanks ~~Obama~~ GNU

    grep PrintfCallback -r libr |grep .h 

will give you a couple more structs that have a printf function pointer member.

**Comment by jjdredd** [comment]
portability ftw

**Comment by shua** [comment]
Other structs with printf function pointer defined manually (instead of with RPrintCallback type)
RPrint r_print.h
RIO r_io.h

**Comment by radare** [comment]
What about Printf instead? To keep it short?

**Comment by radare** [comment]
Or ->cb_printf

**Comment by ret2libc** [comment]
I actually prefer cb_printf than Printf

**Comment by radare** [comment]
@shua if you can reproduce the build issue, please send a pullreq replacing those callbacks to `cb_printf`

**Comment by shua** [comment]
what about just print, or pfmt?

**Comment by radare** [comment]
or prntf :D

**Comment by jvoisin** [comment]
or `p`

**Comment by jjdredd** [comment]
```
ppp()
```
pancake-powered print

**Comment by shua** [comment]
or cb_prnt_fmt_not_glbc

**Comment by shua** [comment]
also used is printfmt https://github.com/radare/radare2/blob/master/libr/util/print.c#L223
you want me to change that to cb_printf too for consistency?

**Comment by radare** [comment]
Merged
