### ISSUE TITLE
physical size of phdr RBinSections in ELF parsing set to virtual size

### ISSUE THREAD

**Issue by yetmorecode** [radare/radare2#3057]
When an ELF binary is opened the ELF parser also adds RBinSections for each ELF segment found through programm headers (phdr* sections).

When those sections are initialized, ``section.size`` as well as ``section.vsize`` is set to to size of the segment in memory (while the size in the file itself can differ).

I am not sure if this is done for a reason. Otherwise the following patch sets ``section.size`` to the actual physical size of the segment in the file.

```
diff --git a/libr/bin/p/bin_elf.c b/libr/bin/p/bin_elf.c
index f8034de..6fee91c 100644
--- a/libr/bin/p/bin_elf.c
+++ b/libr/bin/p/bin_elf.c
@@ -162,6 +162,7 @@ static RList* sections(RBinFile *arch) {
                        ut64 paddr = phdr[i].p_offset;
                        ut64 vaddr = phdr[i].p_vaddr;
                        int memsz = (int)phdr[i].p_memsz;
+                       int filesz = (int)phdr[i].p_filesz;
                        int perms = phdr[i].p_flags;
                        ut64 align = phdr[i].p_align;
                        if (!align) align = 0x1000;
@@ -170,7 +171,7 @@ static RList* sections(RBinFile *arch) {
                        if (!(ptr = R_NEW0 (RBinSection)))
                                return ret;
                        sprintf (ptr->name, "phdr%d", n);
-                       ptr->size = memsz;
+                       ptr->size = filesz;
                        ptr->vsize = memsz;
                        ptr->paddr = paddr;
                        ptr->vaddr = vaddr;

```

**Comment by yetmorecode** [comment]
One issue arising from this is when the RBinSection is e.g. scanned for strings by the r_bin subsystem, it uses the virtual size to scan the contents of the ELF segment and finds strings in adjacent segments as it overestimates the real size in file used by r_bin.

**Comment by radare** [comment]
Can you send a pr so we can let travis, jenkins and appveyour check it automatically and review it in github?

Thanks

**Comment by radare** [comment]
Is this fixing the issue of searching for strings in va mode?
