### ISSUE TITLE
assembler mov byte ptr

### ISSUE THREAD

**Issue by lllaaa** [radare/radare2#3068]
rasm2 has something wrong with **mov byte ptr & mov word ptr**.

root@liang:~/secure_test# rasm2 -b 32 -a x86 "**mov byte ptr [eax], 0x99**;popad;push 0x456;ret"
**ff99000000**616856040000c3
root@liang:~/secure_test# rasm2 -a x86 -b 32 -D ff99000000616856040000c3        
0x00000000   6             ff9900000061  **lcall [ecx + 0x61000000]**
0x00000006   5               6856040000  push 0x456
0x0000000b   1                       c3  ret
root@liang:~/secure_test# rasm2 -b 32 -a x86 "**mov word ptr [eax], 0x99**;popad;push 0x456;ret"
**ff99000000**616856040000c3
root@liang:~/secure_test# rasm2 -a x86 -b 32 -D ff99000000616856040000c3
0x00000000   6             ff9900000061  **lcall [ecx + 0x61000000]**
0x00000006   5               6856040000  push 0x456
0x0000000b   1                       c3  ret

root@liang:~/secure_test# rasm2 -a x86 -b 32 -D **c60099**616856040000c3
0x00000000   3                   c60099  **mov byte [eax], 0x99**
0x00000003   1                       61  popal
0x00000004   5               6856040000  push 0x456
0x00000009   1                       c3  ret

**Comment by radare** [comment]
if you need them “now”, use the x86.olly plugin instead of ‘x86’. its way more complete x86-32 assembler than the default one which is the x86.nz <http://x86.nz/> that targets 32 and 64 bit.

**Comment by radare** [comment]
Fixed in git. thanks
