### ISSUE TITLE
Wrong search zignatures calls

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3076]
1) Open AVR-file ( ReadAnalogVoltage.cpp.bin - https://yadi.sk/d/o3qrK0I2iQNfU)
2) Make signature:
```
    zb strcpy fb01dc0101900d920020e1f70895
```
3) Search signature
```
    .z/ 0x000 0x01de
```
4)
```
    aa
    pd 35 @ sign.sign.b.strcpy (Why sign.sign? We think it's bug)
    s @ sign.sign.b.strcpy <-- work
```
5) Magic
```
    [0x00000f4a]> aa
    [0x00000f4a]> axt
    [0x00000f4a]>
```
But we have 2 calls on this address (с 0x128 и 0x152)

**Comment by radare** [comment]
Can you write test cases for zignatures and avr?

**Comment by radare** [comment]
Uhm, do you mean that the signature is found more than once, and the last flag is overlaping the first?

**Comment by dukebarman** [comment]
After last updates name was changed:
```
zb sys.b.strcpy fb01dc0101900d920020e1f70895
```
And I can't find:
```
[0x00000000]> pd 35 @ sys.b.strcpy
Invalid address (sys.b.strcpy)
```

**Comment by radare** [comment]
The signature search matches are flagged with the sign prefix. Now its using the sys namespace . So the flagname is sign.sys.b.strcpy

**Comment by dukebarman** [comment]
I tried:
```
$ r2 -a avr ReadAnalogVoltage.cpp.bin 
 -- Mess with the best, Die like the rest
[0x00000000]> zb strcpy fb01dc0101900d920020e1f70895
[0x00000000]> z*
zp-
zb sys.b.strcpy fb01dc0101900d920020e1f70895
[0x00000000]> .z/ 0x000 0x01de
Ranges are: 0x00000000 0x000001de
[0x00000000]> pd 35 @ sys.b.strcpy
Invalid address (sys.b.strcpy)
[0x00000000]> pd 35 @ sign.sys.b.strcpy
Invalid address (sign.sys.b.strcpy)
```

And with key "Tab" I can't autocomplete this name. But if change range to 0x0f90:
```
[0x00000000]> s @ sign.sys.b.strcpy 
0xf4a
```

P.S. axt isn't work yet

**Comment by radare** [comment]
s @ .. is weird… what about using "? sign.sys.b.strcpy" ?

the hit seems to be found outside the boundary range you have specified. can you paste the output of z/ instead of supressing it with the prefix dot? you can also autocompelte flag names with the ’s <tab>’ command. use the ‘z’ command to see how many zignatures are loaded. the flagname should be sign.sys.b.strcpy, not sys.b.strcpy. this is just the name for the signature, not the flag name resulting from the search.

**Comment by radare** [comment]
its strange because for my tests. the boundaries zignature search are working as expected:

```
[0x100001058]> zb penis e8f53300
[0x100001058]> z/ $$ $$+10
Ranges are: 0x100001058 0x100001062
fs sign
[0x100001058]> z/ $$ $$+1024
Ranges are: 0x100001058 0x100001458
fs sign 1 matching function signatures
f sign.sys.b.penis @ 0x100001114
[0x100001058]>
```

**Comment by radare** [comment]
Signatures doesnt do any refence or code analysis. Axt is not suposed to qork after this

Didnt moticed u changed the offset where the signature is found so everything looks good to me.

Also, i have fixed several issues in the amalysis. Run aac to get those axt things working.

Other analysis commands would work better too. In addition, can you try if the function size is properly analyzed now?

**Comment by dukebarman** [comment]
Right?

```
[0x00000000]> zb strcpy fb01dc0101900d920020e1f70895
[0x00000000]> .z/ 0x000 0x0f90
Ranges are: 0x00000000 0x00000f90
[0x00000000]> aa
[0x00000000]> axt sign.sys.b.strcpy 
C 0x152 call sign.sys.b.strcpy
C 0x128 call sign.sys.b.strcpy
```

I think it works :)

**Comment by radare** [comment]
ow yeah ;)

**Comment by Maijin** [comment]
@dukebarman can you add a test in r2r?
