### ISSUE TITLE
Incorrect end of function for signature (AVR)

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3077]
1)
```
r2 -a avr test.bin
```
2)
```
zb strtok 62d19d014e815f81042e052a69f4e0916401f0916501309719f4e0e0f0e027c040916401509165015a934a93d901d3df4e0f5f1fda01ec91e03041f4e0e0e0936401e0936501e0e0f0e011c05a934a93d9010ddf8f01309729f0d8010f5f1f4fe0e0ec930093640110936501fa0132d128960895
```
3)
```
.z/ 0x0 0xd04
```
4) aa
5) strtok start from 0xa0a to 0xa7c
6) But:
```
               0x000003d6    77d4           rcall 0xcc6                    ;0x00000cc6() ; sign.sign.b.strtok
               0x000003d8    f3d3           rcall 0xbc0                    ;0x00000bc0() ; sign.sign.b.strtok
```
0xcc6 >> 0xa7c
   
P.S. May correct
```
s @sign.sign.b.strtok
aff
aa
```

**Comment by radare** [comment]
zignatures do not specify function size, only the begining of it. they are used to set flags,not analyze. maybe af @@ sign.* can help on this. it would be good if you could provide a test case for the regressions suite for better understanding this case, also, we need tests for the zignatures and iirc there’s nothing to confirm that the AVR analysis works at all :)

**Comment by radare** [comment]
as i said, this is a bug in the avr code analysis loop. can you provide that test.bin so i can try whats wrong?

**Comment by dukebarman** [comment]
Sure, https://dl.dropboxusercontent.com/u/10688770/test.bin

**Comment by dukebarman** [comment]
Retried this file in last version of radare2

![test bin_fault](https://cloud.githubusercontent.com/assets/1186777/10485545/de74eff4-729b-11e5-9679-092ea14fe2e7.png)

**Comment by radare** [comment]
aa will look for symbols, are you doing it wrong. there are no symbols in this bin

why the hell you get a crash in aa? can you show backtrace?, you should run af @ sign.sys.b.strotk

aff is nothing

adn then type afi @ sign.sys.b.strtok.

**Comment by alvarofe** [comment]
maybe it was related with the segfault in dex. Try pull

**Comment by dukebarman** [comment]
@alvarofe you're right. I don't see segfault anymore.

**Comment by dukebarman** [comment]
Earlier:
```
0x000003d6    77d4           rcall 0xcc6                    ;0x00000cc6() ; sign.sign.b.strtok
0x000003d8    f3d3           rcall 0xbc0                    ;0x00000bc0() ; sign.sign.b.strtok
```
Now:
```
0x000003d6    77d4           rcall 0xcc6                   ; 0x00000cc6() ; sign.sys.b.strok+700
0x000003d8    f3d3           rcall 0xbc0                   ; 0x00000bc0() ; sign.sys.b.strok+438
```

Is it correct? Our sign is finished on sign.sys.b.strok+90

**Comment by radare** [comment]
The signatures doesnt spexify function size. A function should not stop on a call. Can u paste the output of pdf?

**Comment by dukebarman** [comment]
```
[0x00000000]> pdf @ sign.sys.b.strok 
Cannot find function at 0x00000a0a
```

Sorry, not correct. I mean sign.sys.b.strok+114 And +114=ret

**Comment by radare** [comment]
You have to run af @sign.... Before calling pdf

**Comment by dukebarman** [comment]
Seems ok

![pdf_sign](https://cloud.githubusercontent.com/assets/1186777/10494939/327f62fe-72ca-11e5-8b7e-58a39d1c6941.png)

**Comment by radare** [comment]
Then im closing it
