### ISSUE TITLE
Double name in signatures for AVR

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3078]
When we create binary signatures in AVR files, radare2 adds double title - sign.sign

Examples:
- sign.sign.b.strcpy (https://github.com/radare/radare2/issues/3076)
- sign.sign.b.strtok (https://github.com/radare/radare2/issues/3077)

**Comment by radare** [comment]
can you explain all the steps you followed to create those signatures, import them and search them? we need test cases for the zignature search engine.

thanks
