### ISSUE TITLE
Add string filter support

### ISSUE THREAD

**Issue by radare** [radare/radare2#3090]
When listing or searching for strings we should be able to apply specific filters.

* Avoid duplicated strings
* Avoid strings with binary stuff in it (ascii only)
* Avoid strings starting by spaces or underline, etc
* Only grep for URLs, or emails, or phone numbers, ...

Those filters should be implemented in C

**Comment by Manouchehri** [comment]
@simsong's [bulk_extractor](https://github.com/simsong/bulk_extractor) might be a good source for the last point. [The manual](http://digitalcorpora.org/downloads/bulk_extractor/BEProgrammersManual.pdf) has some descriptions on using `be13_api`.

**Comment by radare** [comment]
Some work has been done in 1dba5a687d62c2190e1e9ea10ad478f787f64d24

**Comment by radare** [comment]
Except the 'uniq' functionality, it's done
