### ISSUE TITLE
Incorrect addresses in elf for avr (incorrect loading of the ELF compiled by arduino)

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3091]
Incorrect addresses in jumps for elf-avr (compiled by arduino) and broken Interrupt descriptor table

Compare same files: elf (wrong one) after compiling and binary (right one) after translation:
```
avr-objcopy -I ihex -O binary ReadAnalogVoltage.cpp.elf ReadAnalogVoltage.cpp.bin
```
![compare_elf_bin](https://cloud.githubusercontent.com/assets/1186777/9263787/240bdeba-4231-11e5-8ae8-bdef9e24fbd4.png)

For checking may use:
```
avr-objdump -D -b binary -m avr <file>
```

Files:
https://yadi.sk/d/o3qrK0I2iQNfU
https://yadi.sk/d/mu6P4Z3yiSUp5

**Comment by radare** [comment]
cant download

**Comment by radare** [comment]
unset the flags that are realigning the code

**Comment by radare** [comment]
Or just set `e asm.midflags=false`

**Comment by dukebarman** [comment]
Ok, will try.

Other link for download - https://dl.dropboxusercontent.com/u/10688770/ReadAnalogVoltage.zip

**Comment by dukebarman** [comment]
```e asm.midflags=false``` didn't help :(

**Comment by dukebarman** [comment]
In elf file you can see that addresses doesn't start from 0x0

**Comment by radare** [comment]
map this file in a different address. with -m 0x7800 for example. or just add an extra Section with the 'S' command to reflect this virtual mapping.

**Comment by XVilka** [comment]
@dukebarman @radare As far I know, it is impossible to understand that automatically (except using some heruistics). So I propose you to just add those in some shell file for the demo, which will run the r2 with those addresses for the raw binary.

**Comment by dukebarman** [comment]
jmps/addresses was repaired. But interrupt vector table isn't :(

**Comment by radare** [comment]
@ret2libc ?

**Comment by ret2libc** [comment]
@dukebarman i think you didn't do ```e asm.midflags=false```. On my system if i set mid flags to false I can see a list of jmp.

**Comment by dukebarman** [comment]
@ret2libc o, Thanks! Now it's work.

**Comment by condret** [comment]
Hey, I've read a really useful article recently, you may like it too, please read it <http://duslonkalta.grupogrezzo.com/lniokcov>

Very truly yours, lukas-runas@gmx.de
