### ISSUE TITLE
metadata for ROP-search

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3092]
For easy search may be add option - show gadgets with comments (function)

For example:
```
e rop.comments=true 
```

**Comment by jvoisin** [comment]
What kind of comments are you expecting?

**Comment by dukebarman** [comment]
User comments:
```
CC comment
```
It's comfortably for raw avr:

**Comment by jvoisin** [comment]
Useless in my opinion; when you search for gadget, you don't care about comments.

**Comment by crowell** [comment]
@dukebarman what type of metadata would be important, maybe like `asm.describe` type?

**Comment by radare** [comment]
i think comments can be useful,because this way you can add your notes to the gadgets, useful for filtering them and marking them.

**Comment by radare** [comment]
Maybe always on? Do we want a show or hide those comments by default?

**Comment by crowell** [comment]
@radare on by default is kind of a bad experience imo.
what are you envisioning for comments "this one pops something from the stack"...

**Comment by dukebarman** [comment]
@radare it is not necessary in the ordinary case so hide better.

**Comment by radare** [comment]
Nope. User comments, adding notes like "this gadget is good", "blablabla", "etc.."

Anyway i find useful to add notes anywhere.. But i cant find anything more useful than just using it as "tags" for good/bad.. Which could probably be done in another way with bitfields or so

**Comment by Darkkey** [comment]
Another reason for comments is platform-specific, e.g. in AVR there are many types of MCUs. They have different ports/etc. I'm using binding to automatically create comments like this:
out 0x36, r0 ; PORTD
and want to see this comments in the results of /R/ search.

**Comment by crowell** [comment]
ok, you've convinced me it's reasonable. how about `rop.comments` defaulting to off?

**Comment by XVilka** [comment]
@crowell any update on this?
