### ISSUE TITLE
rabin2 -B is broken again

### ISSUE THREAD

**Issue by radare** [radare/radare2#3094]
run `t.tools/rabin2/rabin2` or just `rabin2 -B 0x43000000` -e /bin/ls and check the vaddr

This is related to 039858fd86e5a4a500312017512a53dfa0c28b86

**Comment by radare** [comment]
@ret2libc note that the tests you added also need other tests that confirm that the contents in the given addresses are valid. We must verify addresses and data.

**Comment by ret2libc** [comment]
should be fixed now

**Comment by radare** [comment]
Awesome! That refactor was really necessary!
