### ISSUE TITLE
Debugging in OSX is broken

### ISSUE THREAD

**Issue by radare** [radare/radare2#3095]
This is because rbin is not loading the file properly and it's asuming 32bit for the debugger instead of 64, so it is not able to read registers or anything.

This is related to : 2ff37b8de09b4e5995b8a7c424aa6fe04658dd59

**Comment by ret2libc** [comment]
What is the purpose of that commit? What is supposed to fix? Can you provide an example to see the difference between before and after the commit?

**Comment by radare** [comment]
Speicfing fd=-1 will force it to open the file from disk instead o using the current one loaded in memory of the debugger which will probably fail. The thing is.. Why it was working for me and now it doesnt? :D
