### ISSUE TITLE
Android installer removes downloaded/unpacked data after unsuccesful  root request

### ISSUE THREAD

**Issue by mittorn** [radare/radare2#3097]
Dowload size is too large and it's better to keep downloaded data, not remove it

**Comment by mittorn** [comment]
After downloading it says "somthing went wrong" and refusing to launch

**Comment by radare** [comment]
I can add an option for that. But if it fails to install is better to remove it.

In addition. We should download from https, otherwise it can be really dangerous to update on untrusted networks.

I am aware of that issue, but i have no time to code more stuff :p its in my todo o:)

**Comment by radare** [comment]
This issue is not related to radare. Can you close this and open it in the radare2-installer repo? Thanks!

**Comment by mittorn** [comment]
Sorry, i have not seen installer repo from phone. Thank you.
