### ISSUE TITLE
Debugging is broken

### ISSUE THREAD

**Issue by shitsecurity** [radare/radare2#3098]
Possible duplicate of radare/radare2#3095

```
$ r2 -d /bin/ls
[0xcf956c80]> f
0x00400000 110592 map._usr_bin_ls.r_x
0x0061b000 8192 map._usr_bin_ls.rw_
0x0061d000 4096 map.unk0.rw_
0x7f2acf956000 135168 map._usr_lib64_ld_2.21.so.r_x
0x7f2acfb76000 8192 map._usr_lib64_ld_2.21.so.rw_
0x7f2acfb78000 4096 map.unk1.rw_
0x7ffff5489000 139264 map._stack_.rw_
0x7ffff54dd000 8192 map._vvar_.r__
0x7ffff54df000 8192 map._vdso_.r_x
0xffffffffff600000 4096 map._vsyscall_.r_x
0xcf956c80 1 eip
0x0000003b 1 oeax
0x00000000 1 eax
0x00000000 1 ebx
0x00000000 1 ecx
0x00000000 1 edx
0xf54a9090 1 esp
0x00000000 1 ebp
0x00000000 1 esi
0x00000000 1 edi
0x00000200 1 eflags
[0xcf956c80]> b 10
[0xcf956c80]> pd
           ;-- eip:
           0xcf956c80    ff             invalid
           0xcf956c81    ff             invalid
```

Env: Fedora 22 x86_64 and Debian 8 x86_64, latest r2 from git.

Static disasm works fine.

**Comment by radare** [comment]
Yep. Looks like the same issue as the one in osx. As a workaround just pass -b64 to r2 or type 'e asm.bits=64'

**Comment by shitsecurity** [comment]
Workaround confirmed. Feel free to close this issue whenever you feel is appropriate (say after master gets a fix?). Thanks.

**Comment by JPro173** [comment]
Hi, I'm also getting "ff  invalid" for every function. 'e asm.bits=64' and -b64 are not helping
Fedora 24 x86_64, latest r2 from git.

**Comment by radare** [comment]
Seems related to aslr. Can u confirm if that works without aslr?

**Comment by JPro173** [comment]
binary compiled without ASLR

**Comment by JPro173** [comment]
Hi, is there any ideas how to fix it?
