### ISSUE TITLE
Incorrect addresses in arduino bootloader

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3103]
Bug or feature? How can I change addresses on const value? For example, it this case for standard Arduino bootloader 0x7800 (incorrect jumps).

```
$ r2 -a avr ATmegaBOOT_168_atmega328.bin 
[0x00000000]> aa
[0x00000000]> pd 100
```

![atmegaboot_168_atmega328](https://cloud.githubusercontent.com/assets/1186777/9295190/0cbd4c2a-4476-11e5-9e81-85b167f322a9.png)

Files for test https://dl.dropboxusercontent.com/u/10688770/ATmegaBOOT_168_atmega328.zip

**Comment by radare** [comment]
What do you want to see in there?

**Comment by dukebarman** [comment]
First command ```jmp 0x7868``` must point on ```0x00000068    1124           clr r1```

**Comment by Darkkey** [comment]
First address should be 0x7800 (in IDA, e.g. you could declare a segment with such offset(.

**Comment by radare** [comment]
Use `r2 -m 0x7800 -a avr ATmegaBOOT_168_atmega328.bin`. Do you think we can assume `0c94343c` as the magic value for this kind of files? this will require an extra rbin plugin

**Comment by Darkkey** [comment]
Unfortunately not, jump address depends on aligning of bootloader (and could change depending on fuses and MCU flash size).

**Comment by radare** [comment]
Can we detect this firmware using a footer maybe? or a speicifc string somewhere with few analysis steps, like following that jump and checking some code in the destination , etc? otherwise i would close this issue beacuse its something the user should do by hand.

**Comment by dukebarman** [comment]
Thanks for help
