### ISSUE TITLE
Add symbol-breakpoints. using bpi->name

### ISSUE THREAD

**Issue by radare** [radare/radare2#3105]
The address of those should be recalculated everytime the debugger stops or a library is loaded. Slowdown tracing

**Comment by radare** [comment]
As long as r2 is not reloading symbols from libs or such, this should be delegated to some futuristic code injection that uses dlsym() to get the proper pointers.

**Comment by jduck** [comment]
Seems related to #3105

**Comment by jduck** [comment]
Is this a duplicate of #1999 too?

**Comment by radare** [comment]
cc @leberus

**Comment by leberus** [comment]
I don't get what should be done here.
Could you explain it a bit?

Thanks

**Comment by radare** [comment]
We want named breakpoints. this is not resolving an address at bpSet time, breakpoints should keep the name given and resolve the address everytime the process is continued.

This will allow us to save/restore breakpoints between different sessions for example. or .. if the process redefines a symbol or dlopens a lib..

**Comment by radare** [comment]
cc @skuater

**Comment by radare** [comment]
Implemented in f5f090b70970c0bf4e22abc3ad0ce7ab1db8b2f4
