### ISSUE TITLE
Incorrect search rop-gadgets in AVR arch

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3112]
/R/ should search for gadgeds with an even offset, rather then odd one, because of instruction length in the AVR (2/4 bytes aligned for some data/instructions).

May be add cfg variable(option in /R?) or make this automatically in AVR arch for even search?

**Comment by radare** [comment]
there’s search.align that in theory all search commands should obey.

can you confirm /R/ is ignoring it or not?

**Comment by dukebarman** [comment]
search.align don't help :(

**Comment by XVilka** [comment]
@dukebarman pls make a test case
