### ISSUE TITLE
Cannot mapping elf avr-file

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3114]
I try to use ```-m 0x0``` and ```-m 0x1``` options but addresses don't change. r2 show this warning:

```
# r2 -a avr -m 0x0 ReadAnalogVoltage.cpp.elf
Warning: Cannot initialize dynamic section
```

Files: https://dl.dropboxusercontent.com/u/10688770/ReadAnalogVoltage.zip

**Comment by radare** [comment]
the -m flag have nothing to do with the warning you get here. that warning comes from the ELF parser, which totally ignores any base address. because its just parsing structures.
