### ISSUE TITLE
Arrays of structures support in 't*' commands

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3115]
To be able to define arrays and arrays of structures.
E.g. `example.h`
```c
struct qwe {
    int a;
    char b;
};
typedef struct qwe p[5];
```
Open with `to example.h` and then list all types with simple `t`. While `qwe` type appeared here - `p` isn't.

**Comment by XVilka** [comment]
Since it is always boring to describe all arrays on the types stage, idea is to add new command, something like `tla` - link type to the address, but not a single element, an array of them.

**Comment by radare** [comment]
You can bind a pf expression that defines this type. This can be done, but not with tla. We can just make a shortcut. TLA looks good

**Comment by radare** [comment]
What about using type[count] syntax?

**Comment by XVilka** [comment]
yes, this syntax is nice.

**Comment by XVilka** [comment]
And clearly important for the https://github.com/radare/radare2/issues/3535

**Comment by radare** [comment]
Isnt enough to place a number before the struct?

**Comment by XVilka** [comment]
@radare what you mean? Didn't got your idea.

**Comment by radare** [comment]
Uhm maybe i didnt understood the problem. Can you write a test case marked as broken?

**Comment by XVilka** [comment]
@oddcoder and this one

**Comment by XVilka** [comment]
Related issue https://github.com/radare/radare2/issues/4763

**Comment by Maijin** [comment]
Fixed !
