### ISSUE TITLE
Review licenses used and kill GPL as much as possible

### ISSUE THREAD

**Issue by radare** [radare/radare2#312]
Here's a list of licenses used in 0.9. We need an updated list

http://ftp-master.metadata.debian.org/changelogs//main/r/radare2/radare2_0.9-3_copyright

**Comment by jvoisin** [comment]
```
$ git grep -E ' GPL.* (pancake|condret)'
binr/old.rarc2/rarc2.c:/* GPLv3 -- Copyright 2009-2010 -- pancake /at/ nopcode.org */
libr/asm/p/asm_msil.c:/* radare - GPL3 - Copyright 2011-2014 - capi_x, pancake */
libr/bin/format/nin/nin.h:/* radare - GPL3 - 2013 condret@runas-racer.com */
libr/syscall/fastcall.h:/* radare 2010-2013 GPL -- pancake */
```
@radare @condret

**Comment by radare** [comment]
We should do something with the msil support. Because is currently not supported and the disassembler is poor and probably outdated.

What about moving this to extras and think in using mono as backend for disassembler, debugger and io? I think @skuater have some ideas for debugging .net

**Comment by radare** [comment]
include files shouldnt contain license information. and im gonna change that asm_msil.c thing to lgpl or move it to extras. the rarc2 code is not compiled by default, and should be removed or moved to extras.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/7fcb8e081d10fb83bafa6201d7f6141dc7674f92
