### ISSUE TITLE
Support of the autoloading needed PDBs for the imported dlls

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3128]
Autoload automatically all needed PDBs for the imported dlls.

**Comment by XVilka** [comment]
That could be taking the raw functions data from the object files, searching those pieces in the raw image, then marking them with the flags and loading code from the DWARF as a comments. Could be useful for the debugging.

**Comment by Maijin** [comment]
@XVilka to ask Peter.

**Comment by XVilka** [comment]
So the only way to do that - support this recursive loading only in:
 - native debug mode, when r2 runs on Windows system and using GUIDs from loaded DLLs and autoload/download them, if needed
 - WinDbg connection mode, when r2 connected to remote/local WinDbg and requests loaded DLLs then reads their GUIDs, like in the previous case.

P.S. May be to think also about ability to manually specify needed PDBs somehow? We need to evaluate that possibility. But the 1st case is the most important/common one.

**Comment by XVilka** [comment]
@xarkes FYI.

**Comment by radare** [comment]
ping?

**Comment by Maijin** [comment]
ok so for the first one it's almost done, just need to add running `.idpd*` by default when running -d on windows @xarkes

**Comment by xarkes** [comment]
Well it depends. I could run .idp* <filename.dll> but that would mean reopening the already opened DLL. It works but less efficient than seeking the mapped DLL and reading required information from here

**Comment by Maijin** [comment]
That's an issue for the 2- not for the 1-

**Comment by XVilka** [comment]
@Maijin no, he is right, it makes sense to read from already loaded files, if they are loaded, if they are not - then fallback to opening the file.

**Comment by Maijin** [comment]
But this is for 2, not for 1

**Comment by Maijin** [comment]
Ah my bad yes, it's for both.

**Comment by Maijin** [comment]
Why not doing this without optimisation first, then we can optimize. 

Wanting perfect stuff from the start is real issue 👎  that's why we still don't have any C output for radeco :(
