### ISSUE TITLE
size matters for r_bin

### ISSUE THREAD

**Issue by condret** [radare/radare2#3131]
i created a new bin-plugin for gamecube images, but r_bin seems to have a problem with 1,4 GB files: http://radare.tv/a/90 is it r_bins fault or mine?, how do i fix dat?

**Comment by condret** [comment]
here is the source of the plugin https://github.com/condret/radare2/blob/bin_gc/libr/bin/p/bin_ningc.c

**Comment by radare** [comment]
Rbin doesnt loads into rbuf huge files for obvious reasons (hard disks doesnt fit in ram and cant be mmaped). So maybe we should change that behaviour, because modern game dumps use to be bigger.

**Comment by condret** [comment]
maybe we can define a size of needed stuff in the bin-plugins, so that plugins for huge files can say "i definitly need the first 128 bytes"

**Comment by radare** [comment]
The problem of this is that the value must be computed somehow. Because some headers point to higher addresses to complete the parsing. So this is not a fixed value or fully valid solution.

Maybe we should allow to use riobind  from rbin to pull more bytes if needed. I should check the src in detail to think in a better soluion

What do you think?

**Comment by condret** [comment]
i think we should build wrappers for r_io in r_bin to keep stuff more maintainable. so plugins access the wrappers and not the bindings directly. If there is a change needed on how the bindings get accessed we can do that much easier

**Comment by radare** [comment]
Rbin plugins already have access to riobind

**Comment by condret** [comment]
wrappers are better

**Comment by radare** [comment]
Well thats part of the api review. Let me know when you are ready to merge siol. We can look together

**Comment by radare** [comment]
we use RBuffer everywhere now
