### ISSUE TITLE
ARM64 - tbz/tbnz opcodes not handled properly

### ISSUE THREAD

**Issue by mickey031** [radare/radare2#3134]
Hi, I just faced an issue regarding tbz/tbnz opcodes when analysing ARM64 software. Indeed, these opcodes are not detected as branching instructions. Here is my fix :
```
+++ b/libr/anal/p/anal_arm_cs.c
@@ -537,6 +537,12 @@ static void anop64 (RAnalOp *op, cs_insn *insn) {
                op->jump = IMM64(1);
                op->fail = addr+op->size;
                break;
+       case ARM64_INS_TBZ:
+       case ARM64_INS_TBNZ:
+               op->type = R_ANAL_OP_TYPE_CJMP;
+               op->jump = IMM64(2);
+               op->fail = addr+op->size;
+        break;
        case ARM64_INS_BR:
```

**Comment by Maijin** [comment]
@mickey031 what about a pull request instead ?

**Comment by radare** [comment]
Next time please send a pullreq :) you can also edit the code in the github website and it will automatically fork, commit and pullreq for free.

**Comment by radare** [comment]
thanks!
