### ISSUE TITLE
Add api and command to fake regprofile size

### ISSUE THREAD

**Issue by radare** [radare/radare2#3138]
This can be useful when experimenting with new gdb targets

**Comment by XVilka** [comment]
Probably even more - put the regprofiles in the text files, so you wont need recompile r2 all the time?

**Comment by radare** [comment]
You can load the regprofilea from disk. There are commands for this. No need to recompile to change this. I prefer to put those regprofiles embedded in the bin because they should come with zero deps. Filesystem is hard :)

**Comment by radare** [comment]
done in master `drps`
