### ISSUE TITLE
dr 16, dr 32 as well as dr mmx, ... are broken

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3144]
dr 16, dr 32 as well as dr mmx, dr ... are broken:

```
[0x7f57937b4cd0]> dr 16
0x00000000
[0x7f57937b4cd0]> dr 32
0x00000000
[0x7f57937b4cd0]> dr 80
0x00000000
[0x7f57937b4cd0]> dr all
0x00000000
[0x7f57937b4cd0]> dr gpr
0x00000000
[0x7f57937b4cd0]> dr mmx
0x00000000
```
Plateform: x86-64 linux Ubuntu on Linux x64 binary

**Comment by radare** [comment]
Help message is wrongf. This functionality is under drt command. Dr expects a regname as argument. Can you send a pr fixing the help?

Thanks

**Comment by Maijin** [comment]
@radare 
Doesn't fix those:

"drt", " 80", "Show 80 bit registers (long double)",
"drt", " all", "Show all registers",

**Comment by radare** [comment]
Are u sure your profile have 80bit registers in it?

**Comment by radare** [comment]
Try drt -1

**Comment by Maijin** [comment]
```
[0x7f57937b4cd0]> drt -1
ebx = 0x00000000
eax = 0x00000000
ecx = 0x00000000
edx = 0x00000000
esi = 0x00000000
edi = 0x00000000
eflags = 0x00000200
```

**Comment by radare** [comment]
Looks like a nope and another thing to fix/improve

**Comment by Maijin** [comment]
Result of drp : http://pastie.org/private/qsvyozxgkoob5v2rapfedg

**Comment by radare** [comment]
There's no 80bit regs in there. So?

**Comment by Maijin** [comment]
No, but "drt all" still doesn't work

**Comment by radare** [comment]
Should be fine now, didnt tested with fpu and mmx because those families needs proper testing on all platforms.
