### ISSUE TITLE
navigating disassembly with up arrow key is broken

### ISSUE THREAD

**Issue by mrpink17** [radare/radare2#3148]
pressing up arrow key in visual mode quickly starts to disassemble offsets 4 bytes before than current, instead of the size of previous instruction

**Comment by ret2libc** [comment]
Btw, I've noticed a long time ago that also 'J' and 'K' are broken in some ways. When you do 'J' and then 'K' you don't go back to the same point.

**Comment by radare** [comment]
Backward disassembly is not an exact science. On intel for example there are many subinstructions for a long instruction so nobody is able tondetermine which is the previous instruction in all the situations. There have been many changes on this topic and current one works quite fine. Can you provide a test case to demonstrate that issue? A specific bin on a specific offset, or a sequence of bytes at least.

Also, for the JK thingg if u want to move back and forth and stay at the same place use block seeking with <> Keys

**Comment by mrpink17** [comment]
I'm tyring it on linux amd64 radare2 executable main() function.

**Comment by radare** [comment]
can you post it in http://radare.tv?

**Comment by mrpink17** [comment]
https://asciinema.org/a/6lk2hqnyi6gxfrwh8oqdso5gc

**Comment by Maijin** [comment]
@mrpink17 btw, you can use `aaa` to get autonaming (instead of `aa`)

**Comment by radare** [comment]
Maybe we can add a scroll field for comments, so scrolling down a line when in a comment will just skip N comments instead of instructions, but this will make page scrolling a bit more difficult/slow

**Comment by radare** [comment]
i think this is fixed now
