### ISSUE TITLE
Things broken in OSX 10.9 debugger

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3151]
- [x] Shows same stack for all threads ('dbt' cmd)
 - [x] Doesn't show the module name in the output of 'dm' (check also 'dmm')
 - [ ] Doesn't load all imports for the debugged process (check the 'f' output)

**Comment by radare** [comment]
Theres already an issue for the dbt of all the threads. And its in my todo for this week maybe.

The imports are taken from rabin. So this is totally unrelated to the debugger. If theres an issue with a specific mach0 please provide the bin and a testcase

About yhe module names. Its working on ios and mac 10.10 and 10.11. Didnt knew the apis changed ... So it should work as expected

**Comment by radare** [comment]
Added `dmm` command to list modules. it works on linux and osx for now. it would be good if @skuater can take a look for windows support.

**Comment by radare** [comment]
You can import the imports by doing `.!rabin2 -rsi /path/to/bin`

**Comment by radare** [comment]
The symbol thing should work fine now, also, its known that r2 doesnt loads ALL symbols from all binaries
