### ISSUE TITLE
New fields in RIOSection/RBinSection

### ISSUE THREAD

**Issue by radare** [radare/radare2#3165]
We need some more information in the sections (discussed with @ret2libc and @inisider )

iOS binaries have a `protected` field in the sections that mark them as they are encrypted or protected by the system), but as far as i know it is not used at all, so not sure if we want that `protected field` in there.

The main field we need is one to tell RIO how to handle that section. this is:

* is loaded by the linker (io must take care of it)
* is a program header (not a section), loaded by r_io
* is a section (specifies arch/os/bits/perms/..)
* is allocated (like .bss)

We can assign a single letter for each of those types, and show it in the 'S' output.

**Comment by condret** [comment]
hm, why pushing RIOSections?

**Comment by ret2libc** [comment]
I chose to use swrx field to store the flags that we needed. In particular i'm referring to R_IO_MAP to indicate that an RIOSection is really mapped.

**Comment by radare** [comment]
Yeah, so we can close this thing for now :) and we can add new flags when we need them
