### ISSUE TITLE
Enhancement : derference pointers when required

### ISSUE THREAD

**Issue by q6r** [radare/radare2#3174]
For example an entry0 for an aarch64 binary shows :

```
[0x0040042c]> pd 4
| 0x0040042c   ldr x0, 0x400440
| 0x00400430   ldr x3, 0x400448
| 0x00400434   ldr x4, 0x400450
| 0x00400438   bl sym.imp.__libc_start_main
```

instead of addresses it would be nice if they're resolved to the functions they point to for example x0,=main, x3,=__libc_csu_init,..._finit this is actually how IDA does it.

```
.text:000000000040042C                 LDR             X0, =main
.text:0000000000400430                 LDR             X3, =__libc_csu_init
.text:0000000000400434                 LDR             X4, =__libc_csu_fini
.text:0000000000400438                 BL              $x_1
```

This makes reading the disassembly much easier. This applies to all archs as far as I remember not just aarch64. I'm not sure how can this be done correctly and accurately in r2.

**Comment by radare** [comment]
this should be already working, can you share the binary?

**Comment by q6r** [comment]
binary http://0x80.org/aarch64_flags0
also check 0x80.org/arm_32_flags0 in this one we have

```
entry0
....
| 0x000102e0   ldr ip, [pc, 0x10]                                      ; [0x102f8:4]=0x10494 sym.__libc_csu_fini
...
| 0x000102e8   ldr r0, [pc, 0xc]                                       ; [0x102fc:4]=0x10408 sym.main
| 0x000102ec   ldr r3, [pc, 0xc]                                       ; [0x10300:4]=0x10434 sym.__libc_csu_init
| 0x000102f0   bl sym.imp.__libc_start_main                            ;sym.imp.__libc_start_main()
| 0x000102f4   bl sym.imp.abort                                        ;sym.imp.abort()
```

IDA also resolve [pc, 0xc] to where it actually points. IDA shows :
```
...
.text:000102E0                 LDR     R12, =__libc_csu_fini
...
.text:000102E8                 LDR     R0, =main
.text:000102EC                 LDR     R3, =__libc_csu_init
.text:000102F0                 BL      __libc_start_main
.text:000102F4                 BL      abort
```

**Comment by radare** [comment]
That's clearly not the same as you mentioned at first.

The flags are showed after the analysis at right in a comment. So it's already detected and used. I know that can be better. if the argument gets replaced by the final pointer resolution, but thats not going to happen in short.

**Comment by Maijin** [comment]
this is fixed \o/
