### ISSUE TITLE
phdr have a wrong vsz

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3177]
```
[33] . 0x000018c8 ---- va=0x00000000 sz=0x06d8 vsz=0x06d8 .symtab
[34] . 0x00001fa0 ---- va=0x00000000 sz=0x023a vsz=0x023a .strtab
[35] * 0x00000000 mr-x va=0x00400000 sz=0x06dc vsz=0x200000 phdr0
[36] . 0x000006e0 mrw- va=0x006006e0 sz=0x0230 vsz=0x200000 phdr1
[37] * 0x00000000 -rwx va=0x00000000 sz=0x21da vsz=0x21da ehdr
```

vsz of phdr0 and phdr1 is 0x200000 while with readelf i get other results (phdr0 vsz=0x6dc, phdr1 vsz=0x238). I expect to have vsz equals to what i get in readelf.

The mapping with RIOSection should be aligned, but with page boundary or so (that probably depends on the architecture more than on the format)

So we may add a msize field to RBinSection, so that we can display the right vsz, but  still mapping things correctly.

**Comment by ret2libc** [comment]
Considering the loader usually maps pages, even if phdr1 starts at 0x000006e0, the whole page [0x0000-0x1000[ will be mapped in the process memory. So, should we also have a ```maddr``` field in RBinSection to indicate what is the address that IO should consider when mapping a RBinSection?

**Comment by radare** [comment]
We must align virtual size up to 4KB (0x1000) by default, and allow the user to override that value. i would use 4K by default, or just write a helper that returns the default pagesize for the arch/bits/os triplet. also, bear in mind that sometimes the kernel uses one pagesize and userland another.

use `io.pagesize` to specify this by the user.

**Comment by ret2libc** [comment]
In order for this to be done correctly/cleanly we'll have to change the output of 'S'. At the moment it prints a mix of rIO and rBIN. rIO doesn't really care about the vsz in the header, but it only cares about the aligned addresses. So if a section has vaddr=0x8048123 and vsz=0x300, rIO will only care to map from 0x8048000 to 0x8049000.

For this reason, IMO ```S``` should display only the rBin info, and the mappings of the RIOSection can be displayed in ```om``` or in a new command ```os```

**Comment by radare** [comment]
The info from rbij should be under the i command. iS

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
is this still happening? do we have a test?

**Comment by ret2libc** [comment]
Looks good now! ;) I don't think we have a test though

**Comment by alvarofe** [comment]
we have t.formats/elf/sections. This was fixed a long time ago iirc by me parsing phdr https://github.com/radare/radare2/issues/838
