### ISSUE TITLE
Command `java prototypes j` causes segmentation fault.

### ISSUE THREAD

**Issue by movEAX** [radare/radare2#3192]
radare2 0.10.0-git 8843 @ linux-little-x86-64 git.0.9.9-740-g71c4245
commit: 71c4245df7571803a58a6e8a944988a871df833a build: 2015-08-29

Java class (loaded as image): ![jdwpexeccmd.class](https://cloud.githubusercontent.com/assets/717481/9563791/626a0038-4e98-11e5-89d2-e72e3c61f863.png)

Coredump (loaded as image):  ![dump.lz4](https://cloud.githubusercontent.com/assets/717481/9563807/2fb70900-4e99-11e5-815f-7297ef18a4dd.png)

```
           PID: 18695 (r2)
           UID: 1001 (me)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Сб 2015-08-29 21:43:12 MSK (13min ago)
  Command Line: r2 /usr/share/nmap/nselib/data/jdwp-class/JDWPExecCmd.class
    Executable: /usr/local/bin/radare2
 Control Group: /user.slice/user-1001.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1001.slice
       Session: c1
     Owner UID: 1001 (me)
       Boot ID: 4800b24292c14dd7802c6c29f4a669a5
    Machine ID: 414707c7012d48e7a8f937c729b597a4
      Hostname: host
      Coredump: /var/lib/systemd/coredump/core.r2.1001.4800b24292c14dd7802c6c29f4a669a5.18695.1440873792000000.lz4
       Message: Process 18695 (r2) of user 1001 dumped core.
```

**Comment by radare** [comment]
Can you submit a test case for the regressions repo? Mark it as BROKEN, will be fixed soon. Thanks

**Comment by radare** [comment]
thanks for reporting!

**Comment by radare** [comment]
i added another test to verify this doesnt breaks in the future. feel free to submit more test cases in t.anal/java
