### ISSUE TITLE
Set cmd.hit=px 32 by default

### ISSUE THREAD

**Issue by radare** [radare/radare2#3195]
I think r2 by default should have a useful, but also handy and simple configuration. Maybe we shuold suggest users to do this or add it in the fortunes as useful stuff to do.

**Comment by Maijin** [comment]
Like #3216 is suggesting, maybe by default command are allowing to fill the `cmd.hit=` with a dedicated value `cmd.hit=default`, which will be for example `ps` for the `/z`. But if  `cmd.hit!=default` then the value of `cmd.hit` is used instead ?

**Comment by radare** [comment]
uhm, nope, i dont think its consistent to have a var to define a command or another string.

**Comment by Maijin** [comment]
* `cmd.hit=`: Is empty so, nothing executed
* `cmd.hit=default`: use the command prefered value for the search command used
* `cmd.hit=px 32`, `cmd.hit=ps 32` : User defined value => replace the prefered value

**Comment by radare** [comment]
what about `e search.dumphit`? also, im not sure which should be the default value

**Comment by Maijin** [comment]
In the code of /z:

```
if cmd.hit=default:
   cmd.hit=ps
```

In the code of /x
```
if cmd.hit=default:
   cmd.hit=px 32
```

**Comment by XVilka** [comment]
I think it is better to split those, so it would be easy to redefine `px 32` for `/x` and `ps` for `/z` from the config.

**Comment by Maijin** [comment]
Or instead of a single command, passing cmd;cmd,cmd2;cmd2

**Comment by radare** [comment]
this needs more discussion imho

**Comment by radare** [comment]
nope

**Comment by radare** [comment]
i think its fine the way it's now no need to make more complex its usage
