### ISSUE TITLE
[META] Jump tables analysis

### ISSUE THREAD

**Issue by radare** [radare/radare2#3201]
```nasm
|  |||| `-> 0x10000119a    8d48cf         lea ecx, [rax - 0x31]
|  ||||     0x10000119d    83f947         cmp ecx, 0x47                ; 'G'
|  ||`====< 0x1000011a0    77cc           ja 0x10000116e               ;[2]
|  || |     0x1000011a2    b801000000     mov eax, 1
|  || |     0x1000011a7    488d157e0700.  lea rdx, [rip + 0x77e]       ; 0x10000192c
|  || |     0x1000011ae    48630c8a       movsxd rcx, dword [rdx + rcx*4]
|  || |     0x1000011b2    4801d1         add rcx, rdx
|  || |     0x1000011b5    ffe1           jmp rcx
```

```C
if (rcx<=0x47) {
  jumpbase = 0x1000192c
  rcx = jumpbase + ut32 [jumpbase + rcx*4]
  rcx();
}
```

```nasm
:> pxW 4*0x47 @ 0x10000192c
jump table here
```

note that jump tables use relative addressing for storing the destination pointers, so aar will not help on this kind of analysis. it requires a bit of esil, we need examples from other compilers and arch. feel free to contribute to the thread

**Comment by Maijin** [comment]
See this existing issue https://github.com/radare/radare2/issues/176

**Comment by radare** [comment]
@Maijin there's no UJMP in there, neither a pointer table

**Comment by radare** [comment]
Analysis for ARM64: (LLVM), switch table of 18 elements starting from 1 to 19:

<img width="491" alt="screen shot 2015-09-01 at 00 38 17" src="https://cloud.githubusercontent.com/assets/917142/9592279/f007d5d2-5041-11e5-9206-c429acef06b6.png">

```
            0x100007d44    82000094       bl sym.imp.atoi              ;[1] ;0x100007f4c() ; sym.imp.atoi
            0x100007d48    08040071       subs w8, w0, 1
            0x100007d4c    e10308aa       mov x1, x8
            0x100007d50    08490071       subs w8, w8, 0x12
            0x100007d54    a1831ef8       stur x1, [x29, -0x18]
            0x100007d58    a8431eb8       stur w8, [x29, -0x1c]
```
this is taking the number from `x1 = atoi () - 1` and `w8 = x1-18`. those are then saved in the stack (which can be optimized out with -O2.

Then we have the second part of the code that computes the destination address to jump
```
        ,=< 0x100007d5c    a80c0054       b.hi 0x100007ef0             ;[2]
        |   0x100007d60    08000090       adrp x8, 0x100007000
        |   0x100007d64    08013c91       add x8, x8, 0xf00
        |   0x100007d68    a9835ef8       ldur x9, [x29, -0x18]
        |   0x100007d6c    0a79a9b8       ldrsw x10, [x8, x9, lsl 2]
        |   0x100007d70    4801088b       add x8, x10, x8
        |   0x100007d74    00011fd6       br x8
```
That `b.hi` skips the jump table in case the value is out of range. We should be able to determine those boundaries when analyzing the jump tables. so we can translate the above code into:
```
x8 = 0x100007000 + 0xf00
x9 = local_var0x18 // aka x1 = atoi ()-1
x10 = int [x8 + (x9 << 2)]
br (x10 + x8)
```

This is. the pointers for that switch table are stored in 0x100007f00:
```
[0x100007d24]> pxd 20*4 @ 0x100007000+0xf00
- offset -     0  1   2  3   4  5   6  7   8  9   A  B   C  D   E  F  0123456789ABCDEF
0x100007f00           -392          -372          -352          -332  x...............
0x100007f10           -312          -292          -272          -252  ................
0x100007f20           -232          -212          -192          -172  ....,...@...T...
0x100007f30           -152          -132          -112           -92  h...|...........
0x100007f40            -72           -52           -32    -721215457  ............. ..
```

So, the branches for this jump table will be the following:

```
0x100007f00 - 392 = 0x100007d78
0x100007f00 - 372 = 0x100007d8c
...
```

**Comment by radare** [comment]
On Thumb:

<img width="439" alt="screen shot 2015-09-01 at 14 51 05" src="https://cloud.githubusercontent.com/assets/917142/9604699/66130770-50b9-11e5-9952-2e1a7614df54.png">

The TBB instruction will resolve a byte table of N elements and jump in

```
[0x0000bec6]> pd 1
|          0x0000bec6    dfe801f0       tbb [pc, r1]
[0x0000bec6]> pf 12b @ $$+4
0x0000beca [0] {
   0x0000beca = 0x06
}
0x0000becb [1] {
   0x0000becb = 0x0f
}
0x0000becc [2] {
   0x0000becc = 0x18
}
0x0000becd [3] {
   0x0000becd = 0x21
}
...
```

so we can just determine the destination of that branch by the following formula:

* jmp $$ + 4 + ( [delta] * 2 )

So, it will multiply by 2 the byte in the nth position of the table found right after the TBB or TBH instruction and add to the address of the next instruction.

See http://stackoverflow.com/questions/7033847/confused-over-a-section-of-arm-disassembly fmi

**Comment by jvoisin** [comment]
This issue is related to [this one]( https://github.com/radare/radare2/issues/176 )

**Comment by radare** [comment]
Please @dmtch feed this thread with your analysis, so we can organize some ideas to get proper jump table analysis. thanks!

**Comment by dmtch** [comment]
I inspected several samples of x86/64 executables from different compilers (msvc, gcc, delphi, borland c++, fpc). There are two common cases of jumptables-branching code:
1. direct jump like "jmp [tbl + ind * sz]"
2. indirect jumps:
2.1. absolute addresses: "mov r1, tbl [ind * sz] ; jmp r1"
2.2. relative addresses: "lea r1, tbl ; *** ; mov r2, [r1 + ind * sz] ; add r2, r1 ; jmp r2"
May be you know more cases related to these architectures?

**Comment by dmtch** [comment]
>  2.1. absolute addresses: "mov r1, tbl [ind * sz] ; jmp r1"

Also there is one thing like this:
mov r1, some_func
...
call r1
Does radare recognise this call?

**Comment by radare** [comment]
also https://github.com/radare/radare2/issues/3223 related

**Comment by bdemick** [comment]
Is there anyone working this?  I'm just starting to wrap my head around radare2 (longtime IDA user) and it's one thing that jumped out at me as an enhancement that would really help bring it closer to IDA's graph view.  As you can see, the x64 binary bomb has a jump table that gets missed on the graph view in the path: 
<img width="822" alt="screen shot 2016-05-02 at 11 23 30 pm" src="https://cloud.githubusercontent.com/assets/3675695/14985493/ae96ca32-1115-11e6-850a-f962d235cd0d.png">
And the jump table is an absolute address vs. a relative one:
`ff24c520244000 jmp qword [rax*8 + 0x402420]`
Would love to help, but I'm just digging down into the radare2 source for the first time, so I'm just getting my bearings.

**Comment by Maijin** [comment]
have u try to activate one of the :
```
       anal.jmpabove: Jump above function pointer
         anal.jmpref: Create references for unconditional jumps
         anal.jmptbl: Analyze jump tables in switch statements
```
option?

**Comment by bdemick** [comment]
I did, but it made no difference in the disassembly or graph view, unfortunately.

**Comment by radare** [comment]
you have to rerun the analysis after setting those vars. but there are no tests for them, so i expect brokeneess or not all cases supported. feel free to go deep and fix/enhance that if you are in the mood :)

**Comment by bdemick** [comment]
Running aa after setting the variables didn't change anything.  Will play around with it some more, and do some source diving if I have time.

**Comment by radare** [comment]
Dont do aa for testing. Just seek to the function with a jump table and type af

**Comment by bdemick** [comment]
No help there.  With jmpref, jmpabove and jmptable set to true, no changes to the function.  I'm used to the IDA switch idiom dialog, or setting it up via script, but have yet to find what I'm looking for in the radare options.

I did attempt to manually set basic blocks and add xrefs from the jump instruction to each basic block ref'd, which works, but this is doesn't scale well and given that other tools handle this case easily I'd love to see this piece working without having to script my way around it.

**Comment by radare** [comment]
of course. this must implemented, there are many ways to do switch tables, so i guess we are just not catching this one

**Comment by radare** [comment]
nobody is working on that right now, but there have been some stuff done where maijin points out.

**Comment by bdemick** [comment]
Any pointers to where this analysis is implemented?  It's a big codebase and my time is limited, but if I get pointed in the right direction I might be able to help enhance it a bit.

**Comment by Maijin** [comment]
well good start would be to look at what those eval variable are actually doing to enhance them !

**Comment by Maijin** [comment]
@radare added a command for displaying them in graph too recently that needs more work

**Comment by XVilka** [comment]
We need probably a set of tests for those, before improving/implementing.

**Comment by XVilka** [comment]
For anyone who wants to dig into jump tables analysis code - most of the code is located in `libr/anal/fcn.c` and some of it is in `libr/core/cmd_print.c`. Just search for `opt.jmptbl`.

**Comment by XVilka** [comment]
Hmm, maybe time to make a list, what does work and what still not? With file examples? Because it is very hard to track like this.

**Comment by io12** [comment]
The [binary bomb](https://github.com/petroav/CMU-assembly-challenge/raw/master/binary) that @bdemick posted about above still doesn't work. (`sym.phase_3`)

**Comment by io12** [comment]
Am I missing something, or should

`if (len < 1 || tmp_aop.type != R_ANAL_OP_TYPE_CMP) {`

be changed to

`if (len < 1 || !(tmp_aop.type & R_ANAL_OP_TYPE_CMP)) {`

(libr/anal/fcn.c:722)

Changing this seems to enable default branch detection on the binary bomb.

**Comment by radare** [comment]
What about sending a pullreq instead?

**Comment by io12** [comment]
Okay I sent a pullreq https://github.com/radare/radare2/pull/10686

**Comment by radare** [comment]
can someone have a look at this pr? im kinda busy with other things now, but the change looks legit, the regressions must be reviewed

**Comment by d4em0n** [comment]
Switch case on arm32 not working.
![image](https://user-images.githubusercontent.com/29397847/43871484-15b7da76-9ba7-11e8-9a5e-d86c78144bd9.png)
![image](https://user-images.githubusercontent.com/29397847/43871503-2915c24a-9ba7-11e8-812a-eba7cfca4793.png)

**Comment by Maijin** [comment]
@d4em0n can you provide the binary please, drag and drop zip with binary here.

**Comment by d4em0n** [comment]
[ctfzone_mobilebank.zip](https://github.com/radare/radare2/files/2273456/ctfzone_mobilebank.zip)

**Comment by yfuchs-c2a** [comment]
indirect jump table (arm 32) is also not working if the table is iterated in a loop. (no loop unroll optimization)
only the first pointer is analyzed (probably the loop is not emulated).
and i can only see that with the axg command.
![selection_003](https://user-images.githubusercontent.com/37180015/44091920-afe87e0a-9fd7-11e8-9f5d-40493659382d.png)
[callback.zip](https://github.com/radare/radare2/files/2286893/callback.zip)

if the loop is optimized then the anal works.

**Comment by radare** [comment]
I think we can safely close this issue as long as anal.jmptbl is enabled by default and we are improving the support for more jump tables over time.

**Comment by radare** [comment]
Will be good to verify all the comments here and see if they work now and if we have tests for them.

**Comment by XVilka** [comment]
But if they are not verified, issue can't really be closed, no?

**Comment by XVilka** [comment]
I think we need a separate tests category for jump tables - there are going to be a lot different tests with time.

**Comment by radare** [comment]
Well this issue is just a collection of test cases that must go into r2r. I dont consider the issue itself a bug or something to fix because we have no tests and its a feature enabled so we get complains from users from time to time. So its even less a problem to worry.

**Comment by Maijin** [comment]
None of these provide files, can't test without files :/
