### ISSUE TITLE
Cygwin, r_sys_rmkdir() fails on quit.

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3202]
```
[0x100401000]> q
r_sys_rmkdir: fail '/cygdrive/d' of '/cygdrive/d/Work/.config/radare2'
```

**Comment by radare** [comment]
Can you cook a single .c file testing this case?

**Comment by XVilka** [comment]
Still here

**Comment by XVilka** [comment]
@radare I can, but pls wait a few days.

**Comment by radare** [comment]
But did u reproduced?

**Comment by XVilka** [comment]
Yes, ofc I reproduced this bug after your patch.

**Comment by radare** [comment]
Then is better to revert. Can u add printfs in this function to see ehats trying to mkdir?

**Comment by XVilka** [comment]
@radare it was a pair of two issues - using WinAPI instead of the unix API and "Permission denied". Lol. Fixed the first one, still thinking how to solve the permissions stuff.

**Comment by radare** [comment]
👍

**Comment by XVilka** [comment]
Closing since removing Cygwin support https://github.com/radare/radare2/issues/9973
