### ISSUE TITLE
Do not filter ':' symbol for assembler plugins.

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3207]
Referenced here:
https://github.com/radare/radare2/blob/master/libr/asm/asm.c#L565

Required for commands like "MOV ZH:ZL, 0x0" for the AVR.

**Comment by radare** [comment]
we can add config options to the parser and tune them depending on the selected arch

**Comment by XVilka** [comment]
I'm not sure about config options but I'll make PR you;ll see

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/a40719649be6868282e966b2fbb0344277f90e57

**Comment by radare** [comment]
ok :) fair enough
