### ISSUE TITLE
^R in dietline doesnt supports repeated search

### ISSUE THREAD

**Issue by radare** [radare/radare2#3209]
http://superuser.com/questions/610980/readline-reverse-search-history-c-r-repeatedly-finds-next-cmd-how-to-go-back-to

(add support for inputrc?)

**Comment by XVilka** [comment]
@deepakchethan can you please add it in your todo? Very useful feature for working with CLI

**Comment by XVilka** [comment]
@radare - can you clarify? Do you want the `Ctrl-s` for forward search? Or something different?

**Comment by radare** [comment]
I never use it. Only do ^r

**Comment by XVilka** [comment]
Ok, then it is not that useful. Closing.
