### ISSUE TITLE
unit tests for r_* utilities

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3221]
rregex, string, etc. should have unit tests.

**Comment by jvoisin** [comment]
How do you want to write them? Using something like [lcov]( https://coverage.otr.im/libotr-4.0.0/src/index.html)?

**Comment by Maijin** [comment]
@jvoisin We could use https://coveralls.io/ or https://codecov.io/ once this problem is fixed https://github.com/radare/radare2/issues/3189

**Comment by Maijin** [comment]
Added in r2r issues
