### ISSUE TITLE
Better support for signed byte/half tables

### ISSUE THREAD

**Issue by radare** [radare/radare2#3223]
Some arches use a switch table of signed bytes or shorts, We need commands to print that in the correct form. This is, extending `pf` to handle them or write another `px` subcommand.

Proposals:

* pxc . print signed char
* pxC . " per line
* pxB . like pxb, but one per line (same as pxH, pxW and pxQ)
* pxs . print short dump (signed 16 bit words in base 10)
* ^-current pxs is for `sparse hexdump` we need a new house for it.
* pxS . same as above but one per line

we also need commands for signed 32bit words in `px` and `pf`

**Comment by jpenalbae** [comment]
Maybe including them under pxd?

pxdb - byte decimal
pxdh - half word decimal
pxdw - word decimal
pxdq - quad word decimal

If the size letter is a capital letter, then output one value per line.

Also for signed output, an extra `s` could be added to the cmd `pxdbs`, `pxdhs` and so on...

**Comment by radare** [comment]
Yeah! That looks saner.

**Comment by radare** [comment]
See related issue @jpenalbae .. i did pxd1 , pxd2 ... but maybe it will be good to have aliased chars like bhwq

**Comment by radare** [comment]
What about signed? pxd1s ?

**Comment by radare** [comment]
Duplicate for https://github.com/radare/radare2/issues/4144
