### ISSUE TITLE
Inject library in target process

### ISSUE THREAD

**Issue by radare** [radare/radare2#3224]
Like LD_LIBRARY_PATH, but at runtime, this is common injection technique on Windows. The library constructor must be called

**Comment by jjdredd** [comment]
> The library constructor must be called

Isn't it called by the loader automatically?

**Comment by radare** [comment]
Not sure if in all platforms works the same when calling dlopen

**Comment by radare** [comment]
we can use frida for this, maybe move to extras and r2pm?

**Comment by killabytenow** [comment]
My experience says that .init section/_init func/so constructor are called always. The difficult part is to avoid get them called xD

**Comment by radare** [comment]
This can be done with r2frida, we can consider this an offtopic for r2 because it can be done by hand already by a plugin or using external tools like r2frida.
