### ISSUE TITLE
Can't demangle all syms with rabin2

### ISSUE THREAD

**Issue by radare** [radare/radare2#3227]
rabin2 cant demangle symbols with -D, but this flag expects the symbol name as argument. i think we should find a better approach and use another flag or just reuse this one in a better way

**Comment by radare** [comment]
Test case is: `rabin2 -s mangledbin`

**Comment by XVilka** [comment]
https://github.com/radare/radare2/issues/3979 - `RABIN2_DEMANGLE=1 rabin2 -E mo/lib/libt`

**Comment by radare** [comment]
its fixed now i think
