### ISSUE TITLE
r2 demangling ELF64 cxx not working?

### ISSUE THREAD

**Issue by itsbriany** [radare/radare2#3232]
Hi, I would like to demangle the symbols during disassembly (preferably without using rabin2 to demangle each individual symbol and compare it with the mangled symbol showing up in the r2 disassembly).

Is this a bug, or am I not configuring r2 properly?
I am running Ubuntu14.04 x86_64 LTS and the binary I am disassembling is an ELF64 cxx binary.

```bash
 itsbriany  ~  Playground  crackmes  r2 a.out 
 -- Stop debugging me!
[0x004009f0]> e bin.demangle = true
[0x004009f0]> e asm.demangle = true
[0x004009f0]> is~main
vaddr=0x00400bce paddr=0x00000bce ord=040 fwd=NONE sz=21 bind=LOCAL type=FUNC name=_GLOBAL__sub_I_main
vaddr=0x00400ae6 paddr=0x00000ae6 ord=081 fwd=NONE sz=171 bind=GLOBAL type=FUNC name=main
vaddr=0x00400930 paddr=0x00000930 ord=004 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.__libc_start_main
[0x004009f0]> s 0x00400ae6
[0x00400ae6]> pd  10
           ;-- main:
           ;-- main:
           0x00400ae6    55             push rbp
           0x00400ae7    4889e5         mov rbp, rsp
           0x00400aea    53             push rbx
           0x00400aeb    4883ec38       sub rsp, 0x38
           0x00400aef    897dcc         mov dword [rbp - 0x34], edi
           0x00400af2    488975c0       mov qword [rbp - 0x40], rsi
           0x00400af6    488d45df       lea rax, [rbp - 0x21]
           0x00400afa    4889c7         mov rdi, rax
           0x00400afd    e8befeffff     call sym.imp._ZNSaIcEC1Ev      ;0x004009c0() ; sym.imp._ZNSaIcEC1Ev
           0x00400b02    488d55df       lea rdx, [rbp - 0x21]
```

As we can see, the symbol **sym.imp._ZNSaIcEC1Ev** still appears to be mangled in the disassembly.

**Comment by jjdredd** [comment]
looks like a bug

**Comment by jjdredd** [comment]
seems to be ok on cff606d99f9ea90c08126aa85b9d55b397e98cd4 linux 32 bit

**Comment by Maijin** [comment]
Can you try using radare2rc config file in ~/.config/radare2/radare2rc 
containing ? 
```e bin.demangle = true
```

**Comment by itsbriany** [comment]
Thanks! That solves my problem, however, I am still confused on why I need to apply 
```bash
e bin.demangle = true
```
on startup.

Another thing: Now that my **~/.config/radare2/radare2rc** is properly configured with the previous command, during runtime, when I set 

```bash
e bin.demangle = false
```

the symbols are still demangled. Is this normal behaviour?

**Comment by XVilka** [comment]
there is also an `asm.demangle` option

**Comment by radare** [comment]
Demangling is not yet by default because it has not been fuzzed yet and theres no support for  changing this at runtime (yet) will be done soon, also, there are plans to support utf8 symbol names like swift does, for c++ r2 uses the gnu demangler which is gpl and this can cause some distro/legal complains.

**Comment by radare** [comment]
In rbin we should store multiple identifiers for every symbol:

Raw name
Demangled name
Flag name

We should be able to enable demangling by default without much complications i guess. We can test this in a branch for letting travis test

**Comment by itsbriany** [comment]
Thanks for the help again, it was a bit confusing for me initially because I thought that setting configurations during runtime would solve my issues. Looks like I will be setting configurations from my *radare2rc* from now on!
