### ISSUE TITLE
r_bin_dwarf_parse_spec_opcode Error

### ISSUE THREAD

**Issue by unixfreaxjp** [radare/radare2#3237]
As per requested in:
https://twitter.com/MalwareMustDie/status/640492903056347136
https://twitter.com/radareorg/status/640533681388552192
https://twitter.com/Maijin212/status/640534671089082368

I submitted the error in r_bin_dwarf_parse_spec_opcode, as per snipped:

```
$ r2 Srarm-depack
Warning: Cannot initialize dynamic section
Error r_bin_dwarf_parse_spec_opcode: hdr->line_range is 0
Error r_bin_dwarf_parse_spec_opcode: hdr->line_range is 0
Error r_bin_dwarf_parse_spec_opcode: hdr->line_range is 0
Error r_bin_dwarf_parse_spec_opcode: hdr->line_range is 0
Error r_bin_dwarf_parse_spec_opcode: hdr->line_range is 0
 -- Invert the block bytes using the 'I' key in visual mode
[0x000097a8]> iI
pic      false
canary   false
nx       true
crypto   false
va       true
bintype  elf
class    ELF32
lang     cxx
arch     arm
bits     32
machine  ARM
os       linux
subsys   linux
endian   little
stripped false
static   true
linenum  true
lsyms    true
relocs   true
rpath    NONE
binsz    1001465
```

The sample is wget-able from below URL, it's in 7zip archive w/password "infected" without quotes.
0day.jp/sec/ff0a (the link will be self deleted after 48h)

thank you for the good development & supporting open source!

rgds / malwaremustdie / @unixfreaxjp

**Comment by unixfreaxjp** [comment]
This is the part where the above error occurred. Couldn't find init.c with lack of searched assembly source in .S causing this I guess.. 

---- snip -----
 94874 radare2  NAMI  "init.c"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f143f0,0xbfbfe004)
 94874 radare2  NAMI  "init.c"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f143f8,0xbfbfe004)
 94874 radare2  NAMI  "init.c"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14400,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14408,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14410,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14418,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14420,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14428,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14430,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x29f14438,0xbfbfe004)
 94874 radare2  NAMI  "crti.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e2814a0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281820,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281840,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281860,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281880,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e2818a0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e2818c0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e2818e0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281900,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281920,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281940,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281960,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281990,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281980,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e2819c0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e2819e0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281a00,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281a20,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281a40,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281a60,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281a80,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"
 94874 radare2  RET   stat -1 errno 2 No such file or directory
 94874 radare2  CALL  stat(0x2e281aa0,0xbfbfe004)
 94874 radare2  NAMI  "lib1funcs.S"

 94874 radare2  CALL  write(0x2,0x28262c00,0x3a)
 94874 radare2  GIO   fd 2 wrote 58 bytes
       "Error r_bin_dwarf_parse_spec_opcode: hdr->line_range is 0
       "
 94874 radare2  RET   write 58/0x3a
---- end snip ------

There are also a lot of errno parts but doesn'T causing crash but I guess some minor functions will be gone. The error may causes with the new engine libraries.

rgds / malwaremustdie / @unixfreaxjp

**Comment by unixfreaxjp** [comment]
Additional.. this happened in most of upx/depacked elf.. I just reproduced this with some more ELF packed in upx, depack it and the same error occur. I did not test this in linux or windows, those aren't not my work platform.

rgds / malwaremustdie / @unixfreaxjp

**Comment by radare** [comment]
Fixed in fa9028f19d40cac70da3527bfc5f8a1a645a085d

**Comment by radare** [comment]
Thanks for reporting! that warning message was not really necessary. This happens when there's dwarf info, but not addr2line info. you can verify this with the addr2line gnu tool. Also, r2 dwarf parser is based on dwarf3 specs. we are not supporting latest specs yet. but as long we are not a source debugger this is not really a huge issue :)

**Comment by unixfreaxjp** [comment]
Thank's so much for the fix. Confirmed. 
We upgraded the fixed git version.
