### ISSUE TITLE
add support for CGC executables

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3247]
example from DEFCON 2015 quals https://github.com/ctfs/write-ups-2015/tree/master/defcon-qualifier-ctf-2015/pwnable/cybergrandsandbox

It would be cool to directly support this format.
The current workaround to analyse them is to replace the CGC string in the header with ELF, because the two formats are almost the same.

**Comment by XVilka** [comment]
https://github.com/CyberGrandChallenge/libcgcef/blob/master/cgc_executable_format.md

**Comment by ret2libc** [comment]
Is it better to duplicate the ELF files or just handle CGC executables as a particular case of ELF?

**Comment by XVilka** [comment]
@ret2libc - 2nd.

**Comment by radare** [comment]
Who uses this?

**Comment by jvoisin** [comment]
People from Defcon likely ;)
