### ISSUE TITLE
Rename `aed` into `ae-`

### ISSUE THREAD

**Issue by radare** [radare/radare2#3250]
to deinitialize the esil vm

**Comment by radare** [comment]
And also rename `aei` into `ae+`

**Comment by radare** [comment]
Please comment your feelings on this change @condret @skuater @jpenalbae

**Comment by jpenalbae** [comment]
I would use `aesl` for emulating N instructions without following calls/jumps/rets...

And use `aei` and `aei-` just to keep consistency with `aeim` and `aeim-`

**Comment by radare** [comment]
lgtm!
