### ISSUE TITLE
Invalid range (from >= to) 

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3254]
It seems that the "Invalid range (from >= to) warnings" is much more present than before. Also I noticed these valgrind issues : don't know if it's related

Valgrind report: http://pastie.org/10405588 (I've used radare2-regressions/bins/mach0/hello-osx-x86_64, but also appeared with /bin/ls ...)

**Comment by sushant94** [comment]
I noticed this too. This has also caused a regression in radeco and causes the tests there to fail.
