### ISSUE TITLE
Emulate N instructions without following calls/jumps/rets/..

### ISSUE THREAD

**Issue by radare** [radare/radare2#3257]
Maybe with `aei` after https://github.com/radare/radare2/issues/3250 ?

**Comment by radare** [comment]
or just... `aesl`  - for 'stepping linearly'

**Comment by radare** [comment]
AGE ESIL SEX LOCATION

**Comment by jjdredd** [comment]
24/esp,ebp,=/M/Russia

**Comment by condret** [comment]
why should we want to do that?

**Comment by radare** [comment]
This is what i do in asm.emu
