### ISSUE TITLE
e asm.cmtright doesn't align symbol names when set

### ISSUE THREAD

**Issue by shiftre** [radare/radare2#326]
r2 sometimes splits the line when a long line is listed, setting the `asm.cmtright` option to true
tries to solve that however the alignment doens't re-align the full symbol name
to the same line

```
 0x0040000d    ff150001e1c8 call dword [0xc8e10100] [2]                                                                                                                             
        |      0xffffffffc9210113(unk) ; str.GetDC      
```

should be 

```
 0x0040000d    ff150001e1c8 call dword [0xc8e10100] [2]           0xffffffffc9210113(unk)str.GetDC    0xffffffffc9210113(unk) ; str.GetDC      
```

**Comment by Maijin** [comment]
@shiftre statut ? Can you provide a test binary if not already resolved ?

**Comment by radare** [comment]
Symbol name != comment

**Comment by shiftre** [comment]
Hrhr

The issue hasn't been resolved, I opened it long ago,

You can test it on any terminal, I was using iTerm2 in tmux, are you saying
you can't reproduce it ?
