### ISSUE TITLE
List of non-return functions

### ISSUE THREAD

**Issue by radare** [radare/radare2#3266]
We want r2 to know which functions will never return. This can't be determined statically, so we have to provide a list of them to the analyzer in order to chop functions when a call to them is performed.

```
call sys.imp.exit
blx sym.imp.__stack_chk_fail
...
```

**Comment by condret** [comment]
that can only be an assumption. what happens if i create my own lib with a function exit that actually does something completly different and returns something

**Comment by radare** [comment]
Thats up to the user. We can guess some end points by using esil emulation but we end up depending on the archos specific constants for syscalls and symbols imported

**Comment by condret** [comment]
hm'kay

**Comment by ret2libc** [comment]
* err
* verr
* errc
* verrc
* errx
* verrx

**Comment by Maijin** [comment]
* sym.imp.msvcrt.dll_atexit

**Comment by radare** [comment]
The current list is quite complete now, and it improves over the time. ok to close
