### ISSUE TITLE
Implement 'afv' and integrate with cparse

### ISSUE THREAD

**Issue by radare** [radare/radare2#327]
After the refactoring we are doing in RAnal that command stopped working. We need a way to use C syntax to define function signatures and local variables.

Those commands should perform low level actions to a c string that must compile with cparse. Cparse does not yet parses function signatures, and it needs to record also the local variables.

Also, this command was used to modify the output of 'pd' by changing '[ebp-32]' into '[counter]'. if we set 'afv ebp-32 = int counter;' (or something like this);

This needs more discussion.

**Comment by XVilka** [comment]
This is what @oddcoder has done. Closing.
