### ISSUE TITLE
Add ret0/ret1/ret-1 gadgets in `wao`

### ISSUE THREAD

**Issue by radare** [radare/radare2#3271]

**Comment by radare** [comment]
```
THUMB-LE RET 0     01207047   movs r0, 0; bx lr
THUMB-LE RET 1     01207047   movs r0, 1; bx lr
...
```

**Comment by jvoisin** [comment]
Done in c01eb89036a6b77f7c2265e57f30d2fba12d12a4

**Comment by radare** [comment]
I dislile having more than two returns (not hanlded by an error case) per function. Having returns true instead of break after every rcorecmd looks ugly to me.

Also. Those rcorecmd() is very bad idea because you should be using the api or just a wrapper of it. The primitive is simple enough.

I was using rcons to have one step more of debugging printfs before executing the change.

Please fix those two things :*

**Comment by radare** [comment]
Omg.

All comments are wrong!! Please remove them, or update them to be in sync with the code.

Wtf is retn? U are using mov r0,1 for wvery single case!!

I would prefer to have a pullreq to review all this stuff properly without getting merged. Its not a core feature, but there are several things that are wrong or can be better.

Also, a proper refactor should not use strcmp

**Comment by jvoisin** [comment]
What do you want me to use instead of strcmp?
As for your first comment, `cmd_write.c` should be refactored. Shall I put functions directly in `cmd_write.c`, or in a new file?

**Comment by radare** [comment]
Ypu can probably hardcode all those patches into an array of structs and iterate instead of spaguett.

Using the core io api instead of the core.cmd() is prefered.

Atm keep everything inside cmd_write
