### ISSUE TITLE
Analysis commands that doesn't obey ^C

### ISSUE THREAD

**Issue by radare** [radare/radare2#3273]
- [x] `aae`
```
r2 -caae /bin/ls
^C
```
 - [x] `aaa` https://github.com/radare/radare2/issues/3316
 - [x] `aac`
 - [x] `aap` https://github.com/radare/radare2/issues/3269

**Comment by Maijin** [comment]
aac seems to obey to ^C

**Comment by radare** [comment]
Thanks @alvarofe

**Comment by Maijin** [comment]
Nop, it' still not working try aaa^C on this http://rghost.net/private/7TLhfnvdy/887a052f214118d4d3ff84a967e2d9eb
