### ISSUE TITLE
Debugger option to stop on exception

### ISSUE THREAD

**Issue by radare** [radare/radare2#3275]
Add "hidden" breakpoints to:
- __cxa_throw
- objc_exception_throw
- exit
- abort
- ...

On hit they a special message should appear and stop the execution. we should also update the stop_reason acordingly.

Add a config var to enable/disable this behaviour.

**Comment by radare** [comment]
Those functions match with the no-return function database

**Comment by radare** [comment]
related to https://github.com/radare/radare2/issues/3266

**Comment by radare** [comment]
Add `dbne` and `dbnd` command maybe? to enable disable the breakpoints on all the functions reported by `an` command.

this also requires to load all the default symbols into `an` at startup depending in asm.os

**Comment by radare** [comment]
cc @leberus

**Comment by radare** [comment]
i think that we should just add a command to put a breakpoint on all the noreturn functions. or at least provide a documenetd an easy way to do that

**Comment by radare** [comment]
the list of noreturn functions can be listedn with the `tn` command

**Comment by leberus** [comment]
I'll take a look on monday ;)

**Comment by leberus** [comment]
Hi, I have a question regarding this:

Why the functions listed with `tn` are not matching the functions listen with `afl`:

```
[0x7facba62c190]> tn
- __libc_start_main
- _Exit
- __stack_chk_fail
- _exit
- exit
- __uClibc_main
- abort
- err
- __libc_init
```

```
[0x7facba62c190]> afl
0x00400370    3 26           sym._init
0x004003b0    2 16   -> 48   loc.imp.__gmon_start__
0x004003c0    1 41           entry0
0x004003f0    4 50   -> 41   sym.deregister_tm_clones
0x00400430    3 53           sym.register_tm_clones
0x00400470    3 28           sym.__do_global_dtors_aux
0x00400490    4 38   -> 35   sym.frame_dummy
0x004004b6    1 11           sym.main
0x004004d0    4 101          sym.__libc_csu_init
0x00400540    1 2            sym.__libc_csu_fini
0x00400544    1 9            sym._fini
[0x7facba62c190]>
```

Is there a "quick" way in r2 (some api) to get the address owned by functions listed with `tn`?

Thanks

**Comment by radare** [comment]
you can chk the code in the analysis loops that uses this list of names to check if the destination of a jmp/call is a no-return destination to see how its done. the bp functionality should use the same behaviour

**Comment by radare** [comment]
because r2 uses flags, not symbol names, to refer to an address. this is.. you can hook the import, the symbol (but there can be more than one symbol with the same name), the flag can also refer the source (if it was found via zignatures), etc.

**Comment by leberus** [comment]
Ok, i'll take a look to all together. Thanks for the explanation ;)

**Comment by radare** [comment]
I think this will require SEH support for windows and othr c++ ecosystems. Maybe @skuater can light a bit this thread

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/2036

**Comment by radare** [comment]
@leberus any update on that? moving for 1.3 or do you have something to PR and test?

**Comment by leberus** [comment]
Yep, move it to 1.3, didnt have time so far but i'll work on it during this
week

El dia 25/01/2017 01:13, "radare" <notifications@github.com> va escriure:

**Comment by leberus** [comment]
Hi @radare , is there a way to get the functions list on debug mode without triggering "aa". Because then would be as easy as do:

tiny example
```
const char *functions[] =
                        {
                                "sym._init",
                                "sym.imp.__libc_start_main",
                                "sym.imp.exit",
                        };

for (i = 0; i < sizeof (functions) / sizeof(char *); i++) {
                        addr = r_num_math (core->num, functions[i]);
                        bool ret = r_anal_noreturn_at (core->anal, addr);
                        if (ret) {
                                   r_debug_bp_add (core->dbg, addr, hwbp, NULL, 0);
                       }
}
```

**Comment by radare** [comment]
you want symbols, not functions, no need to analyze anything to get flags or symbols

**Comment by leberus** [comment]
ok, thanks ;)

**Comment by leberus** [comment]
I have it working, tomorrow I do PR

El dia 08/02/2017 17:03, "radare" <notifications@github.com> va escriure:

> you want symbols, not functions, no need to analyze anything to get flags
> or symbols
>

**Comment by radare** [comment]
Kewl

**Comment by radare** [comment]
Done in 8dd5a3846179009578317e55f1021d140efdd2f1
