### ISSUE TITLE
rotation-mask

### ISSUE THREAD

**Issue by condret** [radare/radare2#3278]
we should be able to show the rotation-mask for ppc rlwinm-instructions

**Comment by radare** [comment]
In the disaasemnly? Esil? Comment? can you provide some more info?

**Comment by condret** [comment]
in the disassembly, the dolphin-guys needed some help, an i couldn't help them with rasm2

**Comment by radare** [comment]
Is this a bug in capstone? Maybe it should be filled there. Can you specify the input? What the gnu plugin does?

**Comment by radare** [comment]
hello?

**Comment by condret** [comment]
our output is correct, but it could provide more information

**Comment by XVilka** [comment]
@wargio maybe you want to check this one?

**Comment by wargio** [comment]
i already generate masks in esil! they can see them there, if needed. `pdd` does translate those in proper output too.
I have tests on the rotation masks that i've applied in order to get the correct result.
i mostly followed the IBM refs

**Comment by wargio** [comment]
```
$ r2 -a ppc -e cfg.bigendian=true -
[0x00000000]> wx 5460DD745469C428546397BE5463EEFE
[0x00000000]> af
[0x00000000]> pdf
/ (fcn) fcn.00000000 20
|   fcn.00000000 ();
|           0x00000000      5460dd74       rlwinm r0, r3, 0x1b, 0x15, 0x1a
|           0x00000004      5469c428       rlwinm r9, r3, 0x18, 0x10, 0x14
|           0x00000008      546397be       rlwinm r3, r3, 0x12, 0x1e, 0x1f
|           0x0000000c      5463eefe       rlwinm r3, r3, 0x1d, 0x1b, 0x1f
\           0x00000010      00000000       invalid
```

**Comment by wargio** [comment]
@condret > https://github.com/radare/radare2/pull/11315

**Comment by wargio** [comment]
@radare can you close this?
