### ISSUE TITLE
Refinement of debug mode/output

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#328]
Current debug view is not really best. Lets see to a few examples of good debugging UIs.

voltron
=====
![voltron screenshot](http://ho.ax/posts/2013/06/example.png)

peda
====
![PEDA screenshot](http://ropshell.com/peda/gdb-peda-context.png)

lldb
===
Looks sucky, inserted here just for contrast
![lldb screenshot](http://cocoafactory.com/images/lldb.png)

gdbinit from osxreverser
=================
![gdbinit osxreverser](http://reverse.put.as/wp-content/uploads/2013/11/gdb2.png)

So:
1. We need to improve debug mode ui output
2. Add colourization support in it

**Comment by Maijin** [comment]
Now most of these layout can be reproduced with the V! command so this can be closed, now issues created are more on adding feature than having a panel like interface which is V!
