### ISSUE TITLE
radare2 breaks shell

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#3280]
Putting r2 to background (ctrl+z) when in visual mode breaks the terminal

Steps to reproduce:
- Enter visual mode in r2
- ctrl+z
- try scrolling with mouse

**Comment by Maijin** [comment]
That works here (Terminator, linux x86_64 ubuntu 15.04 )

**Comment by radare** [comment]
confirmed in osx with iterm. should be easy to fix, 1m
