### ISSUE TITLE
Increment pc before evaluating the esil thing

### ISSUE THREAD

**Issue by radare** [radare/radare2#3285]
* The idea is to increment the `pc` register with the instruction size.
* Then use `$$` as a register that points to the current offset where the instruction is.
* And use `TRAP` as a keyword for the current functionality in `$$`.

**Comment by jpenalbae** [comment]
It might work as a workaround...

I still think that we should increase the global pc before evaluating the esil chain, instead of using any hacks. We are just doing it wrong so why trying to use hacks instead of doing it right?

**Comment by radare** [comment]
Which hack do u see in my explanation? I think we are talking about the same thing. I can try a patch and you can review it.

**Comment by jpenalbae** [comment]
Sorry, my bad. Thought that the TRAP was required in order to access the proper `pc` value, but propose to use it to access the value returned by the current behavior.

That sounds fine to me.

**Comment by radare** [comment]
Maybe we can change the % internal reg prefix for $, to make this more consistent, so we will have $o instead of %o. and $$ is also a virtual register that points to the current instruction.

**Comment by radare** [comment]
In fact %% was already returning current instruction address  :D so we should use $ instead of % because $ is not a binop

**Comment by radare** [comment]
Also, % char can be problematic on format strings, so better stick to $

**Comment by radare** [comment]
All those changes mentioned in the issue are done in the last commit in git. But `pc` register is not yet incremented. We should update the documentation

**Comment by XVilka** [comment]
@sushant94 what do you think?

**Comment by radare** [comment]
All this stuff requires to update radeco's esil parser

**Comment by sushant94** [comment]
Sounds alright to me. Tell me when all this has landed and I'll make the changes on radeco's end appropriately. Even better if someone opens a bug on radeco for this so that I don't forget.

**Comment by radare** [comment]
See last commits in libr/anal/esil.c

Basically $$ is now TRAP
$$ is now current address
Internal reg prefix is $ instead of %

And we are discussing about preincrementing the program counter befote evaluating the esil line

**Comment by condret** [comment]
we should do the preincrementing thing, because this is how cpu's work, at least the datasheets say so

**Comment by radare** [comment]
+1

Can you guys do a pr?

**Comment by jpenalbae** [comment]
I will send a PR later including the per-increment and fixes for any issues this could cause on instructions such as call, etc.. for x86_cs.c

**Comment by jpenalbae** [comment]
After doing some tests and checking all the opcodes using `pc` inside `anal_x86_cs.c` looks like esil for x86 works fine with PR d910a778b595f97c1f6d0c8c533055e6b2c495d3

Can anyone please also check other architectures?

**Comment by radare** [comment]
Duck yeah
