### ISSUE TITLE
Move current z80 plugin to extras

### ISSUE THREAD

**Issue by radare** [radare/radare2#3287]
We have z80.cr plugin which is LGPL instead of NC-GPL, and its cleaner.

**Comment by jvoisin** [comment]
What about removing the current z80 plugin instead? Its code is ~~awful~~ suboptimal, its license is non LGPL, and comments are in German.

**Comment by radare** [comment]
Why remove if it works and can be moved to extras? There are tons of tests written for it.. We should put some tests for extras at some point.

Im aware of the gpl thing and the code quality. But i dont like to see code die if its ok.

**Comment by radare** [comment]
@condret are u ok with this?

**Comment by jvoisin** [comment]
I think that he said ok to remove the current (and awful) z80 one on IRC

**Comment by radare** [comment]
Ok. Will purge today

**Comment by Maijin** [comment]
Related z80-cr issues:

https://github.com/radare/radare2/issues/2119
https://github.com/radare/radare2/issues/2075

**Comment by radare** [comment]
Regressions should be updated too

**Comment by Maijin** [comment]
Regressions are already z80 and not z80-cr

**Comment by radare** [comment]
Z80 is the plug that must be killed. So all those tests will presumabily fail

**Comment by Maijin** [comment]
Ok

**Comment by Maijin** [comment]
I remember @condret said he will generate the test for z80.cr just like he did for z80

**Comment by radare** [comment]
ok, so let’s wait for condret to do this

**Comment by radare** [comment]
move it to 1.0, we should do a major plugin re-organization after the release. to make the core smaller and handier

**Comment by Maijin** [comment]
@radare r2pm for the win :D

**Comment by radare** [comment]
@condret can you post some tests for the z80.cr transition? so we can safely move the old plugin to extras?

**Comment by crowell** [comment]
This issue was moved to radare/radare2-pm#3
