### ISSUE TITLE
Visual class/methods browser

### ISSUE THREAD

**Issue by radare** [radare/radare2#3290]
* Which key should we use? to enter the vmenu from visual?
* vmenus.c should be refactored to simplify/reuse all that menu+list thing

**Comment by XVilka** [comment]
Btw, I like more the way vmenus are looking, not curses-like panel. Probably should be a parameter, or so.

**Comment by radare** [comment]
Im Not going to use the visualpanels thing for this. Vmenus are more handy

**Comment by XVilka** [comment]
@radare good news!

**Comment by radare** [comment]
Use `B` key in Visual as discussed with @ret2libc in order to browse the entire rbin info (like VF does for flags)

**Comment by radare** [comment]
Done in git, it can be better, but it works
