### ISSUE TITLE
-B baseAddress not working when using -a6502

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3294]
tested r2 from git HEAD as of today, and from `brew`. 
In both cases I couldn't force the base address of the binary.

I tried this:

`$ r2 -a6502 -B2048 ~/game/game.prg`

And it loads the binary at 0x0000 instead of 0x0800.

**Comment by radare** [comment]
I guess, as long it is a raw binary you want to map it with the -m flag. No rbin plugin handles unknown formats

**Comment by ricardoquesada** [comment]
@radare thanks. I couldn't find the `-m flag` argument in `r2`.
How can I specify it ? Thanks!
