### ISSUE TITLE
Missing opcodes when disassembling 6502 with asm.pseudo=true

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3295]
```
           0x0000080d    20db09         jsr 0x09db
           0x00000810    207909         jsr 0x0979
           0x00000813    4c0070         goto 0x7000
           0x00000816    40
           0x00000817    a200           ldx #0x00
           0x00000819    9d0004         sta 0x0400,x
           0x0000081c    9d0005         sta 0x0500,x
           0x0000081f    9d0006         sta 0x0600,x
           0x00000822    9de806         sta 0x06e8,x
           0x00000825    e8
           0x00000826    d0f1           bne 0xf1
           0x00000828    60
           0x00000829    a200           ldx #0x00
           0x0000082b    9d00d8         sta 0xd800,x
           0x0000082e    9d00d9         sta 0xd900,x
           0x00000831    9d00da         sta 0xda00,x
           0x00000834    9de8da         sta 0xdae8,x
           0x00000837    e8
           0x00000838    d0f1           bne 0xf1
           0x0000083a    60
           0x0000083b    a900           lda #0x00
           0x0000083d    8d03dc         sta 0xdc03
           0x00000840    a9ff           lda #0xff
           0x00000842    8d02dc         sta 0xdc02
           0x00000845    a900           lda #0x00
           0x00000847    8d00dc         sta 0xdc00
           0x0000084a    ad01dc         lda 0xdc01
           0x0000084d    c9ff           if (#0xff ==
           0x0000084f    f021           beq 0x21
           0x00000851    a8
```

`$40`, `$e8`, `$a8`, `$60`, etc... are all valid 6502 opcodes.
Also `goto` is used instead of `jmp`... and `if (#==)` instead of `cmp`... I don't know if this was done on purpose or a bug.
I can add them myself and send you a Pull Request if you tell me which file should I edit. Thanks.

**Comment by condret** [comment]
this is weird, i cannot repoduce this:
```` $rasm2 -a 6502 -d 40e860a8````
`rti`
`inx`
`rts`
`tay`

**Comment by ricardoquesada** [comment]
thanks. I found the culprit. I had: `e asm.pseudo = true` in my `~/.radare2rc`
I removed it and everything is working ok.

I think this is still a bug... it shouldn't happen when `asm.pseudo=true`, but I can live with it.

**Comment by condret** [comment]
@ricardoquesada i think this happens because we don't have an analysis-plugin for 6502. I didn't create one because on some instructions i don't know what they do, but i did the disassembler. if you want you can create one. (or i create a basic one and you add the missing parts)

**Comment by radare** [comment]
Theres not even a pseudo parser for 6502. So the result of that thing enabled will be wrong

**Comment by condret** [comment]
i thought that asm.pseudo uses analysis inforamtion too

**Comment by radare** [comment]
Nope. Its just based on the parsing of the disassembly string.

**Comment by condret** [comment]
like my first version of ramulate

**Comment by ricardoquesada** [comment]
@condret If you create a basic one, I can continue that work.

One thing that I would like to add is support for the illegal instructions for the 6502:
http://unusedino.de/ec64/technical/aay/c64/ibmain.htm

Does radare support illegal instructions for other architectures? should I handle them in an special way... eg: print then in uppercase instead of lowercase ? or is there a flag to enable printing illegal opcodes, and I should read that flag ?
thanks.

**Comment by condret** [comment]
we support undocumented instructions for z80-cr, i'm not sure about 6502

**Comment by condret** [comment]
@ricardoquesada have you seen ma commit?

**Comment by Maijin** [comment]
Example of a "pseudo parser" support [commit](https://github.com/radare/radare2/commit/64636e9505f9ca8b408958d3c01ac8e3ce254a9b)

**Comment by ricardoquesada** [comment]
@condret @Maijin  yes. thanks. I'll work on this on the weekend. I'm on IRC now. My nick is "riq_"

**Comment by condret** [comment]
@Maijin bad example

**Comment by Maijin** [comment]
If you can show a better example dat would be nice to add in the wiki ;)

**Comment by Maijin** [comment]
Link corrected @condret ;)

**Comment by radare** [comment]
I think this is fixed or wip, so we can close this already
