### ISSUE TITLE
"sudo make install" fails after having run "sudo make install-symlink"

### ISSUE THREAD

**Issue by felixheld** [radare/radare2#3297]
/usr/bin/install fails with "‘*.h’ and ‘/usr/local/include/libr/*.h’ are the same file"

**Comment by radare** [comment]
As expected. You should make uninstall or make purge first

**Comment by radare** [comment]
would you expect rm -rf /usr/include/libr when doing make install?

**Comment by felixheld** [comment]
rather not. i'd just expect that the symlinks get replaced with the real files
