### ISSUE TITLE
avr-assembler and disassembler do not support xch-instruction

### ISSUE THREAD

**Issue by condret** [radare/radare2#3307]

**Comment by Darkkey** [comment]
Will check on weekends.

**Comment by juhakivekas** [comment]
This is supported in newer versions of vavrdisasm, but integration requires some refactoring. Updating the whole disassembly module from vavrdisasm is good, but a single line hotfix should be possible too.

**Comment by radare** [comment]
Oh! I though it was a dead project.

**Comment by Darkkey** [comment]
@pancake, I will pull request a fix on this Sunday.

**Comment by XVilka** [comment]
Closed in 32a4b9e6b77117f175ffc553c9c4b00ce4a1d0db
