### ISSUE TITLE
rarun2 input doesn't work as expected

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3308]
cat.r2
```
program=/bin/cat
input=AAAA
```
or also "AAAA\n", or 'AAAA' or 'AAAA\n'.

The input is not replayed by cat and cat doesn't reply to any other string.

**Comment by radare** [comment]
input expects a filename, not a string

**Comment by ret2libc** [comment]
```
input       set string to be passed to the program via stdin
stdin       select file to read data from stdin
```
Seems like stdin expects a file name, input a string.
Anyway, also using a filename doesn't work. Indeed the name of the file it's just printed, it isn't read.

**Comment by radare** [comment]
Works perfectly for me if i pass a filename

**Comment by ret2libc** [comment]
@radare can you share your test profile file?

my output:
```
 /tmp  cat input.txt
Hello
World
 /tmp  cat test.r2
program=/bin/cat
input=input.txt
 /tmp  rarun2 test.r2
input.txt
```

**Comment by radare** [comment]
try with input=@input.txt <mailto:input=@input.txt>. dunno wth it was using a custom fucntion to parse the value of that field. also, its closing the pipe right after the write.

**Comment by ret2libc** [comment]
I think it's still not working. Btw, IMO input should accept a string, not a file, otherwise what is the difference between stdin and input?

**Comment by radare** [comment]
input accepts a file, a string, hexpair, etc,

rarun2 input=/etc/services program=/bin/cat

**Comment by ret2libc** [comment]
Thanks ;)
