### ISSUE TITLE
base64 encoder is broken

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3311]
```sh
$ ./test_base64 
error, b64encode(hello) != aGVsbG8A
Tests run: 2
```

```sh
$ echo -n "hello" | base64
aGVsbG8=
```

**Comment by radare** [comment]
Works fine from r2. i guess your test case is wrongly written. can you paste the source of test_base64.c ?

```
> w hello
> p6e 5
aGVsbG8=
```

**Comment by crowell** [comment]
fixed in https://github.com/radare/radare2/commit/278e4a022856327a68bdc65ef32310688dddca3b

**Comment by crowell** [comment]
the code for testing is here

```c
char* test_r_base64_encode(void) {
  char* hello = (char*) r_base64_encode_dyn("hello", 0);
  sprintf(buf, "error, b64encode(hello) != %s", hello);
  mu_assert(buf, strcmp(hello, "aGVsbG8=") == 0);
  return NULL;
}
```

**Comment by radare** [comment]
Is this problem also happening in sdb?

**Comment by radare** [comment]
The prinf doesnt matches the function called.

Also. The length parameter should be -1 if you want to automatically strlen, otherwise it will encode 0 bytes.

Is the char* cast needed? It should not.

Use snprintf if you dont like overflows

Why it is always returning null? Should the test return bool?

**Comment by radare** [comment]
Note that sdb also have its own implementation, which is more tested. Did you tried with asan/valgrind?

**Comment by crowell** [comment]
@radare based on the code for base64, any value <1 call strlen, but the problem was with strlen, there was still adding 1 to encode the null byte.

the test returns null, because it returns a pointer to the error string, just returning zero gives some compiler warnings.

about the printf/sprintf you have me there, but it is for a simple test and i was lazy.
