### ISSUE TITLE
endianess issue in the arc analyzer plugin

### ISSUE THREAD

**Issue by felixheld** [radare/radare2#3313]
https://github.com/radare/radare2/blob/master/libr/anal/p/anal_arc.c#L28 only works as expected on little endian systems (b is in arc byte-order and constant is in host byte-order)

**Comment by condret** [comment]
have you tested?

**Comment by felixheld** [comment]
i don't have a big endian system to test, but the first parameter of memcmp is in the target endianness and the second one in the host endianness

**Comment by radare** [comment]
i dont see why this should be endian-sensitive. the buffer is already compared with another buffer, the value of the buffer passed is already endianized before being called.

You can use a qemu for mips or powerpc to test this ( http://stackoverflow.com/questions/3337896/imitate-emulate-a-big-endian-behavior-in-c )

Can you write a test case that fails and marked as BROKEN=1 for this issue?

**Comment by felixheld** [comment]
ok, i'll do that

**Comment by Maijin** [comment]
@felixheld since you seems to like endianess related issue maybe you could give a look at the oldest issue in r2: https://github.com/radare/radare2/issues/138 and give more info/proof/fix about it?

**Comment by felixheld** [comment]
just noticed that the second argument is a byte-array of hex values and not a hex constant, so this was a false alarm. will still set up a powerpc qemu to check and maybe have a look into that other issue and through the tree
