### ISSUE TITLE
mingw64: link with -static-libgcc

### ISSUE THREAD

**Issue by yetmorecode** [radare/radare2#3318]
radare2.exe build with Mingw64 has a dynamic dependency to libgcc, which is not present on windows if mingw64 is not installed (e.g. on production system).

Idk why I keep running into these mingw64 oddities. I had better luck some weeks ago ;)

I build on debian with mingw-w64 package (mingw64 3.2.0-2) and:

```
./configure --with-compiler=x86_64-w64-mingw32-gcc --with-ostype=windows --host=x86_64-unknown-windows
make && make w64dist
```

Thats the build with the missing dependency:
![mingw](https://cloud.githubusercontent.com/assets/11893375/9962727/88538e10-5e27-11e5-8c7c-f8d74d0df8b5.png)

I then added to the bottom of config-user.mk:

```
LDFLAGS+= -static-libgcc
```

And it fixed the issue for me.

![mingw2](https://cloud.githubusercontent.com/assets/11893375/9962781/da4dbcf4-5e27-11e5-9f4a-7cd9000b61b0.png)

However I have no experience with the build system in general, so maybe someone with more experience can find the right place to add this.

**Comment by radare** [comment]
just use sys/mingw32.sh

**Comment by yetmorecode** [comment]
Alright, that helped. Both sys/mingw32.sh and mingw64.sh link statically against it. Thanks.
