### ISSUE TITLE
radare2 gets confused by simple 64 bit addresses for x86-64?  0x1800002cc != 0xffffffff800002cc

### ISSUE THREAD

**Issue by beebob23c** [radare/radare2#3320]
"
C:\Users\beebob\Documents\radare2-w32-0.9.9>radare2 F:\SMMstuff\SmmDisp.bin
 -- Here be dragons.
[0x1800002cc]> aa
Cannot find function 'entry0' at 0xffffffff800002cc
"
SmmDisp.bin is a 64 bit PE extracted from a BIOS with UEFITool. It analyzes fine in IDA. Radare2 is clearly getting confused and treating 0x1800002cc, the entry point according to the PE headers, as 0xffffffff800002cc (an improperly sign-extended value?) It doesn't seem to behave the same way for notepad though.

Is there some easy fix to work around this?

**Comment by crowell** [comment]
Can you provide the binary?

**Comment by beebob23c** [comment]
sure, here it is
https://drive.google.com/file/d/0B8Gd17H1LFXjcDRrc1NMdUdTbW8/view?usp=sharing

I should also say that I'm using the latest (0.9.9) windows precompiled binary download

**Comment by Maijin** [comment]
Cannot reproduce on the last version github + linux x86_64

**Comment by crowell** [comment]
```
[0x1800002cc]> ie
[Entrypoints]
vaddr=0x1800002cc paddr=0x000002cc baddr=0x180000000 laddr=0x00000000
```
works well here, Linux amd64.

Can you test with a version from git on windows?

**Comment by Maijin** [comment]
http://bin.rada.re/radare2.exe for a git version windows installer

**Comment by beebob23c** [comment]
um...Maijin, some reason that radare2.exe that you're linking to is prompting for admin privs when the normal installed one from radare.org isn't?

Crowell, "ie" isn't a valid test, "aa" is, since aa is what I reported wasn't working. ie works fine for me.

[0x1800002cc]> ie
[Entrypoints]
vaddr=0x1800002cc paddr=0x000002cc baddr=0x180000000 laddr=0x00000000

1 entrypoints

**Comment by yetmorecode** [comment]
Tested with mingw32 and 64 builds. Cant reproduce as well.

```
w:\workspace\radare2\source>file radare2-w32-0.10.0-git\radare2.exe
radare2-w32-0.10.0-git\radare2.exe: PE32 executable (console) Intel 80386, for M
S Windows

w:\workspace\radare2\source>radare2-w32-0.10.0-git\radare2.exe D:\TMP\SmmDisp.bi
n
[0x1800002cc]> ie
[Entrypoints]
vaddr=0x1800002cc paddr=0x000002cc baddr=0x180000000 laddr=0x00000000

1 entrypoints

[0x1800002cc]> aa
[0x1800002cc]> q

w:\workspace\radare2\source>
w:\workspace\radare2\source>file radare2-w64-0.10.0-git\radare2.exe
radare2-w64-0.10.0-git\radare2.exe: PE32+ executable (console) x86-64, for MS Wi
ndows

w:\workspace\radare2\source>radare2-w64-0.10.0-git\radare2.exe D:\TMP\SmmDisp.bi
n
[0x1800002cc]> ie
[Entrypoints]
vaddr=0x1800002cc paddr=0x000002cc baddr=0x180000000 laddr=0x00000000

1 entrypoints

[0x1800002cc]> aa
[0x1800002cc]> f
...
0x1800002cc 1444 entry0
...
[0x1800002cc]> q
```

**Comment by Maijin** [comment]
@yetmorecode It's an installer, It's installing you radare2 as a software that you can easily update/uninstall with another installer + PATH variable for right click : open in r2, debugt with r2

**Comment by radare** [comment]
There are automated per-commit builds for windows. I would suggest you to always use r2 from git.
