### ISSUE TITLE
can we remove r_io_plugin_add and r_io_add?

### ISSUE THREAD

**Issue by condret** [radare/radare2#3321]
@radare @XVilka @jvoisin if you take a look at https://github.com/radare/radare2/blob/master/libr/io/plugin.c#L17 you'll see that this code just adds an empty list_head to io->io_list, right? i would like to remove that. r_io_add is a macro for r_io_plugin_add . Both are never used afaik. Is that ok for u?

**Comment by ret2libc** [comment]
seems like it is used in https://github.com/radare/radare2/blob/master/libr/io/plugin.c#L45

**Comment by condret** [comment]
we can remove it from there

**Comment by radare** [comment]
Wtf indent

**Comment by ret2libc** [comment]
So maybe we can make it static

**Comment by radare** [comment]
Remove??? How do you plan to add plugins?

**Comment by condret** [comment]
with a perlscript

**Comment by condret** [comment]
i rewrote some stuff from libr/io/pluginc.c on the siol-branch, i'm happy with this now
