### ISSUE TITLE
Install.sh: issue with signing on OSX

### ISSUE THREAD

**Issue by Anrock** [radare/radare2#3325]
I don't know if it's expected, but it makes impossible to install signed version on osx.
So, i checkout radare, i do ```sys/build.sh```, then ```make -C binr/radare2 osxsign && make -C binr/radare2 osx-sign-libs``` and everything appears signed. I launch ```sys/install.sh``` and it rebuilds everything and installs unsigned binaries.
It would be nice if install.sh would also sign everything before installing automatically.

**Comment by radare** [comment]
Did u followed the instructions from doc/osx to create the certificate? This cant be automated

**Comment by Anrock** [comment]
I did, of course, that's how i got signed binaries. Problem is i can't install them, because install.sh rebuilds binaries, producing unsigned ones and tries to install them.
I've just dirty hacked `binr/Makefile` to make it call `osx-sign` and `osx-sign-libs` if `uname` is `Darwin` so calling `sys/install.sh` now installs signed binaries. 
I'm pretty sure it's possible to create additional script/target/whatever, that checks if prerequsites of sign is met and do signing, or otherwise spit out some instructions to user.

**Comment by radare** [comment]
The osxsign target should be called from sys:/install.sh in case the env var to define the name of the cert is set. (CERTID iirc). Maybe we can find a better name for it and suggest with an echo+sleep when building with this script on darwin.

Can you send a pr? I'll review and merge as soon as i get my hands in the laptop.

Thx
