### ISSUE TITLE
Autodetect BIOS/UEFI file formats better, overlapping with a particular NES image

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3328]
It could be nice to force the usage of an r_bin plugin inside the r2 when a r_bin detection is wrong see: 
http://rghost.net/private/7myncwlFc/d278644ef5dd00915c9bd94da87d5cce

Edited*

**Comment by radare** [comment]
What about fixing that rbin check instead?

**Comment by Maijin** [comment]
@radare yes it will be fixed by @XVilka but it could happen another time

**Comment by radare** [comment]
See r2 -h:
```
 -F [binplug] force to use that rbin plugin
```

**Comment by Maijin** [comment]
oh ok so it's possible when opening the radare2 :)
