### ISSUE TITLE
Does not respect "search.from/to" on binaries, therefore can't search relocated binaries

### ISSUE THREAD

**Issue by beebob23c** [radare/radare2#3329]
C:\Program Files (x86)\Radare2>radare2 -v
radare2 0.10.0-git 9070 @ windows-little-x86-32 git.jenkins-radare2-win-installer-986
commit: 0d4f09507137b01bebc082d2b6756f2916f6a001 build: 15-09-18

I open a binary memory dump, and search for a string, I see the following:

```
[0x00000000]> / ASDF
Searching 4 bytes from 0x00000000 to 0x000631b0: 41 53 44 46
# 3 [0x0-0x631b0]
hits: 4
0x0000a210 hit0_0 "ASDF"
0x0005764b hit0_1 "ASDF"
0x00063010 hit0_2 "ASDF"
0x00063110 hit0_3 "ASDF"
[0x00000000]> omr 0x1000
[0x00000000]> / ASDF
Searching 4 bytes from 0x00000000 to 0x000631b0: 41 53 44 46
# 3 [0x0-0x631b0]
hits: 2
0x0000b210 hit1_0 "ASDF"
0x0005864b hit1_1 "ASDF"
[0x00000000]> omr 0x70000
[0x00000000]> / ASDF
Searching 4 bytes from 0x00000000 to 0x000631b0: 41 53 44 46
# 3 [0x0-0x631b0]
hits: 0
```

Basically it's always only searching from 0 to the binary end, even if I set search values:
```
[0x00000000]> e search.from = 0x70000
[0x00000000]> e search.to = 0xF0000
[0x00000000]> / ASDF
Searching 4 bytes from 0x00000000 to 0x000631b0: 41 53 44 46
# 3 [0x0-0x631b0]
hits: 0
```

after discussing on IRC, NighterMan pointed at this code as being the likely culprit:
https://github.com/radare/radare2/blob/master/libr/core/cmd_search.c#L1644

It would be nice if that were changed to still respect "e search.from = FOO" type values even for binary files (but I don't want to try and fix it, because I don't know what else could break)

**Comment by beebob23c** [comment]
I would also just note that it doesn't work to try and trick radare2 and make a new section at some high address to accomplish the same thing as rebasing (idk if this is a separate bug or the expected behavior)

[0x00000000]> o
- 3 my.bin @ 0x0 ; r size=405936
[0x00000000]> S 0 0xDB000000 405936 405936 mysect rwx
[0x00000000]> S
[00] * 0x00000000 -rwx va=0xdb000000 sz=0x631b0 vsz=0x631b0 mysect
[0x00000000]> pxw 0x10
0x00000000  0xec7f4fa1 0x42fcb217 0x0c02f7a7 0xbad50543  .O.....B....C...
[0x00000000]> s 0xDB000000
[0xdb000000]> pxw 0x10
0xdb000000  0xffffffff 0xffffffff 0xffffffff 0xffffffff  ................

(the "0xec7f4fa1" is the correct output, but which I would have expected to see at 0xDB000000 after I defined the section above)

**Comment by radare** [comment]
E io.va=true?

**Comment by beebob23c** [comment]
OK, setting "e io.va = true" did make virtual addresses behave as expected, so that would be a workaround
