### ISSUE TITLE
Different colors for local (in-function) jump arrows and global (from function) jump

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#333]
Separate colors of local reflines (for jumps in one function frame) and global reflines (for jumps outside current function)

**Comment by crowell** [comment]
Is this done in the new /p ui?

**Comment by pwntester** [comment]
in disasm view, conditional jumps have a yellow line associated to them while non conditional ones have a blue one. It doesnt affect the graph though

**Comment by jvoisin** [comment]
I think that r2 doesn't have global arrows any more, does it?

**Comment by radare** [comment]
by global arrows you mean e asm.linescall=true ?

**Comment by jvoisin** [comment]
Yes.
But to be honest, a different shade for up/down and a different colour for (un)conditional would be super-cool :)

**Comment by radare** [comment]
imho its ok the way it is now, overengineering more the lines will make it slower with not much benefit, because all jmps use to be in the same function, and call lines are not enabled by default
