### ISSUE TITLE
disasm not clear in visual mode

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3331]
```
[0x1000011df]> pd 3
                   0x1000011df    ff5548         call qword [rbp + 0x48]
╒ (fcn) entry0 3540
│                  ; var int local_0_1    @ rbp-0x1
│                  ; var int local_5      @ rbp-0x28
│                  ; var int local_6      @ rbp-0x30
│                  ; var int local_7      @ rbp-0x38
│                  ;-- main:
│                  0x1000011e0    55             push rbp
│                  0x1000011e1    4889e5         mov rbp, rsp
[0x1000011df]>
```

In my opinion the instruction at 0x1000011df should consider only one byte (ff), because the other two are already part of 'push rbp'(55) and 'mov rbp, rsp'(48). A visible issue with the current approach, is that when I do, 'j' in visual mode, it goes to 0x1000011e2 and not on the next visible instruction, which should be 0x1000011e0

**Comment by radare** [comment]
Ff5548 is also a valid instruction

**Comment by ret2libc** [comment]
Yes but it is using some bytes that are also used in the next two instructions. So you can't actually have both "call qword [rbp + 0x48]" and "push rbp". If we show the call, we shouldn't show the push and viceversa. It's quite confusing.

**Comment by radare** [comment]
Because of asm.midflags

**Comment by ret2libc** [comment]
Yes, I know. What I'm saying is that even when mid flags is true, we shouldn't show multiple instructions that use the same bytes. How do I know that they can't be both executed? Should I look every time at the bytes that they are using? Do I need to carefully check for every instruction that the instruction address + instruction size is equal to the next instruction address?
What I think is much more simple and easy to understand is:

```
[0x1000011df]> pd 3
                   0x1000011df    ff             invalid
╒ (fcn) entry0 3540
│                  ; var int local_0_1    @ rbp-0x1
│                  ; var int local_5      @ rbp-0x28
│                  ; var int local_6      @ rbp-0x30
│                  ; var int local_7      @ rbp-0x38
│                  ;-- main:
│                  0x1000011e0    55             push rbp
│                  0x1000011e1    4889e5         mov rbp, rsp
[0x1000011df]>
```

Or, if mid flags is False:
```
[0x1000011df]> pd 3
                   0x1000011df    ff5548         call qword [rbp + 0x48]
╒ (fcn) entry0 3540
│                  ; var int local_0_1    @ rbp-0x1
│                  ; var int local_5      @ rbp-0x28
│                  ; var int local_6      @ rbp-0x30
│                  ; var int local_7      @ rbp-0x38
│                  ;-- main:
│                  0x1000011e2    89e5         mov ebp, esp
[0x1000011df]>
```

What do you think?

**Comment by radare** [comment]
What u say is contrary to midflags. It makes no sense

**Comment by ret2libc** [comment]
It makes sense. The current approach makes you think some instructions will be executed, when instead they won't. You can see it in https://asciinema.org/a/650f6q9ligqhg6begnn03uubm

**Comment by ret2libc** [comment]
Possible solution: add a mark (like '~') near the ```call qword [rbp + 0x48]``` instruction

**Comment by radare** [comment]
put that mark in the place where breakpoints ‘b’ and current cursor position ‘*’ is placed (right before the instruction)

**Comment by radare** [comment]
can you send a pullreq for testing?

**Comment by ret2libc** [comment]
I will, sure!

**Comment by jvoisin** [comment]
@ret2libc Any updates about this?

**Comment by ret2libc** [comment]
haven't looked at it yet :( sorry
