### ISSUE TITLE
esil: inconsistencies with Carry $c7

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3346]
anal_gb.c, with the SLA op, it seems to be using $c7 to check carry.
The SLA op a simple shift left op: http://www.z80.info/z80syntx.htm#SLA

code: https://github.com/radare/radare2/blob/c79b31ef3ba506bc3521408a1545bc06eed0f6f8/libr/anal/p/anal_gb.c#L608

But according to `esil_internal_carry_check()` and `genmask()`:

esil_internal_carry_check: https://github.com/radare/radare2/blob/dfebd35de884df9c8609b65c959e8bdde82e3e6c/libr/anal/esil.c#L259
genmask: https://github.com/radare/radare2/blob/dfebd35de884df9c8609b65c959e8bdde82e3e6c/libr/anal/esil.c#L15

It should use `$c8` and not `$c7`. I tested on 6502, and `$c8` is the correct way to test for carry on 8-bit registers... I wasn't able to test it on anal_gb since it doesn't have regression tests, but it looks like all the operations that are testing for `$c7` should fail.

**Comment by condret** [comment]
it's a bug, $c7 is correct
