### ISSUE TITLE
Do not assume default bits from the host system

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3348]
e.g. run something 32bit ARM with the qemu embedded gdbserver and connect to it by the radare2:
`
r2 -a arm -D gdb gdb://localhost:1234
`
then, if you check the bits with `iI` command, you'll find that it is 64bits, only due to the reason of the 64bit host system (of radare2) and if you list available registers with `drl` you will find a bunch of the `x[N]` ARM64 registers.

**Comment by radare** [comment]
you must specify -b 32 if you want to debug arm

**Comment by XVilka** [comment]
@radare yes, I know, this request is about autodetection of the remote target architecture automatically.

**Comment by crowell** [comment]
gdb has `set architecture auto`, who wants to read the ugly GNU source to discover how it works.

/me not it!

**Comment by XVilka** [comment]
@crowell I know now how it works, but better not to break so fragile support of GDB before the release.

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
I think this may fit into WONTFIX cathegory
