### ISSUE TITLE
/R doesn't respect search.from & search.to

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3353]
/R doesn't seem to respect search.from & search.to

**Comment by radare** [comment]
Can you submit a test case for this?

**Comment by radare** [comment]
@crowell ?

**Comment by crowell** [comment]
uh, it should respect it, i have it go through `r_core_get_boundaries`, can you add a test, and if it fails, i'll look more into it.

apologies for being very mia lately

**Comment by radare** [comment]
looks like search.{from|to} is ignored unless `search.in=range`. So this is not really a bug with /R, but maybe a usability problem.

**Comment by Maijin** [comment]
search.in: Specify search boundaries (raw, block, file, section)
`range` is not in the help

**Comment by crowell** [comment]
added to helptext

a0ddd7d17d3c41742f8fd3e2f2e19b4e38015f25

**Comment by radare** [comment]
As we discussed in tg, range is not a valid value, but it works because its catching the default case of the switch and that code handles this

**Comment by Maijin** [comment]
as @radare suggested, the best would be to suggest the user to type `e search.in =?` in the help instead of "raw, block, file, section, range"
