### ISSUE TITLE
Ability to run DLLs or another kind of shared libraries

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3355]
To create a special 'master' process from radare2 and "run" that DLL to inspect via the debugger.
Like this done in OllyDbg or similar programs. For all supported systems.

For the reference https://github.com/edix/LoadDll

**Comment by radare** [comment]
we can add this feature within rarun2
. in fact, on linux, libs can be also executed

**Comment by Maijin** [comment]
It's on 921
