### ISSUE TITLE
Use a real sorting algorithm for linked-lists

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3356]
Currently, in `list.c`, the `r_list_sort` function is using a *Bubble-Sort*, which is super-inefficient.

**Comment by crowell** [comment]
s/real sort/merge sort

qsort doesn't work on linked lists well because it requires random access.

**Comment by radare** [comment]
qsort is used in sdb-numeric arrays because it can

**Comment by condret** [comment]
@crowell : i think i can do qsort for lists

**Comment by crowell** [comment]
@condret you can do it, but it wont be good. qsort relies on random access for speed. or you could just ignore me :-1:

**Comment by condret** [comment]
@crowell : what about this: allocate memory for r_list_lenght pointers, and then transfere stuff to that memory, and there you have your random access

**Comment by crowell** [comment]
@condret yes that sounds ultra efficient... iterate over the list copy to a buffer, sort, then recopy to a list

**Comment by condret** [comment]
for huge masses of data it is

**Comment by crowell** [comment]
i'll do this

**Comment by condret** [comment]
ok

**Comment by crowell** [comment]
adding a test first because i actually broke this

**Comment by radare** [comment]
You are reinventimg rarray or rslist.

**Comment by alvarofe** [comment]
What about to have various algorithm and depending of the length choose the most appropriate. I don't know much about the performance of each algorithm and which would be the right choice for each situation.
```
if (len < 100) r_list_sort_with_bubble(..)
else if (len > 100 && len < 100000) r_list_sort_with_merge(..)
...
```

**Comment by radare** [comment]
How many times do u sort a huge array to care about this? It looks to me like a premature optimization.

**Comment by jvoisin** [comment]
Haha, sorry for opening this bug :D 
Can we close it now?

**Comment by crowell** [comment]
ok, at least we got a unit test out of it ;)

On Thu, Sep 24, 2015 at 11:09 AM, jvoisin <notifications@github.com> wrote:

> Haha, sorry for opening this bug :D
> Can we close it now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3356#issuecomment-142957495>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
Yep :p
