### ISSUE TITLE
windows debugger: add support to break on debug events

### ISSUE THREAD

**Issue by yetmorecode** [radare/radare2#3361]
When using the windows native debugging backend, it is currently not possible to break on all received debug events, like "break on new thread", "break on load dll", "break on unload dll" and a couple more.

Especially the "break on load dll" is very handy, as it is commonly used to patch dlls before the application interacts with it. One well known example is to break when kernel32.dll is loaded and patching IsDebuggerPresent with nops (google "unpacking yoda's protector" for an live example). 

There are 9 different debug event types: https://msdn.microsoft.com/en-us/library/windows/desktop/ms679308(v=vs.85).aspx

Here is what olly offers: http://www.aldeid.com/w/images/0/07/Ollydbg-debugging-options-system-breakpoint.png

I would gladly volunteer to work this out, if the feature is approved at all. Maybe it would be easiest to just setup some new config values and use them in the native debugger backend?

Opinions?

**Comment by Maijin** [comment]
It would be super useful for malware analysis so definitely :+1:

**Comment by yetmorecode** [comment]
So what should it be like from a user perspective? Do we need some "d" command or something  simple like "e dbg.windows.break_on_dll_load=true"?

**Comment by radare** [comment]
I was discussing this with @skuater. I think the plan would be to use dbg.libs and find a way to make it work on linux and osx.

The events are actually handled on windows , so it should be easy to add.

**Comment by yetmorecode** [comment]
Is dbg.libs meant to be an boolean?

r_debug_plugin->wait already should return reasons for waiting (R_DEBUG_REASON_NEW_LIB,
R_DEBUG_REASON_EXIT_LIB in that case). 

So it should be possible to handle this right in r_debug_wait() here: https://github.com/radare/radare2/blob/master/libr/debug/debug.c#L341

**Comment by radare** [comment]
I have commited a change that sets `dbg->reason.type = ret; `. so the check could be added on any other place inside core after calling r_debug_wait(). wanna send a pullreq? Yes, the dbg.libs is suposed to be a variable that when set to true, it will stop the debugger when a new library is loaded. if not it will just print a message like its doing now.

This feature is windows specific, and currently i have no handy windows to try. But maybe @skuater can check it out too.

I wonder which should be the way to do this in linux/osx. hooking dlopen?

**Comment by radare** [comment]
@skuater ping

**Comment by radare** [comment]
Implemented in https://github.com/radare/radare2/commit/c72caa67acc4b90fef527eb75cce23ab38d2356c needs more testing and support for non-w32 platforms, but i guess that commit is enough to close this issue
