### ISSUE TITLE
Rolling Release Binaries/Packages - Travis CI

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2#3366]
Lately I've been finding it quite hard to keep up with r2, since I have a pretty slow machine and it takes awhile to build.

There's a few solutions:

 1. Use Travis as the primary source for Ubuntu/Debian releases, and possibly other distros if their build tools can be compiled/ran as a user/fakeroot. (Best option.)
 2. Have people share their exist builds/build servers. (Raise your hand if this is you!)
 3. ~~I can macgyver @travis-ci's new @Docker (non-root) containers to use @rpodgorny's [unionfs-fuse](https://github.com/rpodgorny/unionfs-fuse) and then "change" into a fakeroot system with [PRoot (ptrace)](https://github.com/proot-me/PRoot). (This would allow using `apt-get` with no root and proot'ing into an entirely different distro.) I've done this before and it works (with my quick tests anyway), but it does waste a lot of bandwidth/stogage space for @travis-ci.~~ (Not needed here.)

I'm going to implement option 1 to build an Arch package (which may or may not go well), or option 2 if I end up breaking too many things.

Aside from Arch, what are the popular distros to aim for?

**Comment by crowell** [comment]
@Manouchehri are you using ccache? this may help your compile times.

**Comment by Maijin** [comment]
@Manouchehri https://github.com/radare/radare2/issues/3251 duplicate ?

**Comment by Manouchehri** [comment]
Not quite a duplicate, but very close and related.

From what I understand, the Travis CI script is currently throwing away the
binaries after each build. I want to distribute (or cache, but I think
there's no public facing URL for cached files) the binaries to somewhere
that other people can download.

**Comment by Manouchehri** [comment]
"The caching tars up all the directories listed in the configuration and
uploads them to S3, using a secure and protected URL, ensuring security and
privacy of the uploaded archives."

http://docs.travis-ci.com/user/caching/#How-does-the-caching-work%3F

Basically, the goal is to either publish the secure URL, or push them
somewhere else that is public.

**Comment by Manouchehri** [comment]
https://twitter.com/DaveManouchehri/status/647355470961901568

Waiting for a reply at the moment.

**Comment by Maijin** [comment]
@Manouchehri Speed improvement is much more important imho than this cause it's impacting a lot the dev

**Comment by Manouchehri** [comment]
Indeed, this is purely an end-user thing. I don't expect it to be too
difficult, I'll submit a PR once I hear back from the Travis CI team.

**Comment by Maijin** [comment]
@Manouchehri deb file would probably also makes sense see the already existing scripts => https://github.com/radare/radare2/tree/master/sys/ for already existing script

**Comment by Manouchehri** [comment]
So the Travis CI team got back to me and said that the cache is not publicly accessible. At the moment I can't think of any service that would allow us to host large binaries for free, so I'm going to close this ticket.

I would suggest using Docker instead, as #3439 has been solved.

**Comment by XVilka** [comment]
@Manouchehri we have the hosting for large binaries btw. And docker installed on it.

**Comment by Manouchehri** [comment]
Would you be willing to let/trust Travis CI push to it though?

**Comment by XVilka** [comment]
Yup, it is only for CI purposes, nothing important on it. So, why not?

**Comment by Manouchehri** [comment]
Cool, I'll try experimenting a bit with my own box first and submit a PR when I get things working.

**Comment by Maijin** [comment]
TravisCI already uses docker + is much efficient than docker hub clearly :p

**Comment by radare** [comment]
Fix it with hardware

**Comment by Manouchehri** [comment]
Noticed that this has already been implemented with Docker in #3439.
