### ISSUE TITLE
Add esil.verbose set to true by default

### ISSUE THREAD

**Issue by radare** [radare/radare2#3367]
We should make `aae` throw nothing to stdout on any bin.

**Comment by condret** [comment]
why true by default?

**Comment by radare** [comment]
Because the user expects those fancy error messages like 'cannot write' or 'esil stack is empty' in order to understand why something is not working. Maybe we can switch to false when esil is properly supported on more archs. Try aae with arm bins

**Comment by condret** [comment]
ah, you mean that stuff. well i think that some of those messages are misplaced. "cannot write" should be in the r_io i think

**Comment by radare** [comment]
But those errors should not appear when running aae for example

**Comment by Maijin** [comment]
`e esil.debug =false`

**Comment by Maijin** [comment]
* https://github.com/radare/radare2/blob/master/libr/anal/esil.c#L8
* https://github.com/radare/radare2/blob/master/libr/anal/esil.c#L18
* https://github.com/radare/radare2/blob/master/libr/anal/esil.c#L2591

And value can be set using 
```
(int)r_config_get_i (core->config, "esil.debug");
```

But core isn't in esil.c :/

**Comment by radare** [comment]
i think we can close this issue

**Comment by Maijin** [comment]
Noooo

**Comment by radare** [comment]
why not

**Comment by Maijin** [comment]
Because it is not fixed...

**Comment by radare** [comment]
i have in theory fixed this. pls confirm :3

**Comment by Maijin** [comment]
Setted to 0, 1 or 2 I still see stuff like:
```
0x00401216 esil_mod: Division by zero!
0x004012fe esil_mod: Division by zero!
0x004017ca esil_mod: Division by zero!
0x004017e9 esil_mod: Division by zero!
0x00430891 esil_mod: Division by zero!
0x004308ad esil_mod: Division by zero!
0x0044580d esil_mod: Division by zero!
0x0044ab23 esil_mod: Division by zero!
0x0045ae64 esil_mod: Division by zero!
0x00473863 esil_mod: Division by zero!
```

**Comment by radare** [comment]
then just git pull

**Comment by Maijin** [comment]
yep now looks like it is fixed 👍
