### ISSUE TITLE
Default color palette

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3368]
- [x] for Windows with 8 colors - bit better than ugly current
 - [ ] the rest

**Comment by radare** [comment]
the rest?

**Comment by radare** [comment]
@XVilka can you provide a screenshot of windows Vpp (visual debugger) and output of `ec` ? to see which colors we have and write the proper palette.
thx

**Comment by radare** [comment]
i have added a new colorscheme named "basic", it looks quite good on windows.

**Comment by radare** [comment]
meh, no feedback no issue

**Comment by XVilka** [comment]
@radare it was good enough -> thus no feedback.

**Comment by radare** [comment]
There are some visual glitches with utf8 and graph mode in windows because of some tiny bugs in rcons. Not sure if we will be in time to fix it before the release
