### ISSUE TITLE
`rabin2 -g` hang

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3369]
`rabin2 -g` hangs on [this]( http://rghost.net/8CrlTWZlr ) file.

**Comment by radare** [comment]
How are u running? Which is the expected behaviour? Did you tried with strace -f? The program runs fine without rarun2?

**Comment by jvoisin** [comment]
Err, I should sleep more those days. It's rabin2, not rarun2…

**Comment by jvoisin** [comment]
And also [this]( http://rghost.net/6zDZRfjCG ) one.

**Comment by radare** [comment]
Thanks! i have added a test too

**Comment by jvoisin** [comment]
And [this]( http://rghost.net/7CQFsyqVB ) one too, if it hasn't been fixed yet.

**Comment by jvoisin** [comment]
And another [hang]( http://rghost.net/8P8QdVv2h )

**Comment by jvoisin** [comment]
And [this]( http://rghost.net/8Zv9x2Cj2 ) one is weird:
```
$ rabin2 -g fuzz2/crashes/id:000000,sig:11,src:002062,op:havoc,rep:4
Invalid Lnames record (bad size)
Error in r_bin_object_new: load_bytes failed for omf plugin
Invalid Lnames record (bad size)
Error in r_bin_object_new: load_bytes failed for omf plugin
Invalid Lnames record (bad size)
Error in r_bin_object_new: load_bytes failed for omf plugin
Invalid Lnames record (bad size)
Error in r_bin_object_new: load_bytes failed for omf plugin
r_bin: Cannot open file
zsh: exit 1     rabin2 -g fuzz2/crashes/id:000000,sig:11,src:002062,op:havoc,rep:4
```

**Comment by radare** [comment]
Fixed!

**Comment by radare** [comment]
i also added the bin to r2r
