### ISSUE TITLE
register "telescoping"

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3372]
peda has nice telescoping 

![peda](https://camo.githubusercontent.com/1144a3db95ecd1972b5f8846a7e776a2b9096652/687474703a2f2f692e696d6775722e636f6d2f50314246356d702e706e67)

we should do this in some `dr` mode

**Comment by Maijin** [comment]
Duplicate https://github.com/radare/radare2/issues/1000

**Comment by crowell** [comment]
er, not really a duplicate, but ok...

memory / register telescoping is more of a needed feature than belongs as a simple part of a list

**Comment by Maijin** [comment]
@crowell it was part of this list already + this one https://github.com/radare/radare2/issues/328

**Comment by jvoisin** [comment]
Since this feature is amazing, I don't mind having it in two issues.

**Comment by Maijin** [comment]
even more :+1:

**Comment by radare** [comment]
Telescoping a a very bad name for this. Also. This is already done

**Comment by radare** [comment]
Is also done for memory

**Comment by radare** [comment]
I would close both and point you to the command to do this

**Comment by radare** [comment]
Even more TOO OLD

**Comment by jvoisin** [comment]
Why isn't this enabled by default in visual mode?

**Comment by crowell** [comment]
@radare care to share the command that does this then?

**Comment by Maijin** [comment]
`drr` => Undocumented, should also be added in Visual mode :open_mouth:

**Comment by Maijin** [comment]
See https://github.com/radare/radare2/issues/3375
