### ISSUE TITLE
esil: limitation when calculating Carry

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3374]
This is how addition works on 6502

A = A + Memory + Carry

eg:
```asm
sec         ; Set Carry = 1
lda #$f0    ;  A = 0xf0
adc #$10    ;  A = A + 0x10 + Carry (which is 1)

;  The result is:
A = 0x01    ; because 0xf0 + 0x10 + 0x01 == 0x01
C = 1       ; because the result of the addition was >= 0x100
```

This is the esil code and works Ok for almost all cases
```
C,0x10,+,a,+=,$c7,C,=
```

The case where it doesn't work is this one:
```asm
sec          ; Set Carry = 1
lda #$00     ;  A = 0x00
adc #$ff     ;  A = A + 0xff + Carry (which is 1)

; The result should be:
A=0           ; 0 + 0xff + 1
C=1           ; due to the carry

; But result using the previous esil code is:
A=0           ; is this ok.
C=0           ; this is NOT ok. It should be 1.
```

I took a look at how `esil_internal_carry_check` works, and it compares if `current_value&mask < old_value&mask`, which seems to be Ok, but it doesn't cover the above mentioned case.
Using a mask of 255 (`$c7`) is the correct way to do it. I cannot do it with a mask of 511 (`$c8`), otherwise it will break other stuff.

A similar case occurs with SBC (substract with carry). Its logic is:
`A = A - M - !C`.
This code will break it: `A = 0 - 0xff - 1`
But in this case I can use one extra bit for borrow. Using `$b9` instead of `$b8` works Ok. Looks kind of hackish using `$b9`, but I can live with it.

I don't know how to workaround this limitation at the moment. If you know, please let me know.

A possible solution would be add an extra internal test... perhaps a `$tbitmask` that returns `anal->cur` value.

With that I could test `C` like this:
`$t8,0x100,>=,C,=`

__UPDATE:__ I think the Z80 addition/subtraction code works pretty similar to 6502. I took a look at its [esil implementation](https://github.com/radare/radare2/blob/33d5cf0cc0df384c186c3ac4faab8bed57fc7947/libr/anal/p/anal_gb.c#L366) and from what I saw it fails also on the above mentioned tests

__UPDATE 2__: `bit` opcode

`bit $ffff`
The `bit` opcode works like [this](http://homepage.ntlworld.com/cyborgsystems/CS_Main/6502/6502.htm#BIT)

```asm
 ; A: Accumulator
 ; M Memory (passed as an argument)
 ; t: temp variable
  t = A & M
  flag.N = t.7         ; flag.N is bit 7 as well
  flag.V = t.6          ; flag.V is bit 6 as well
  flag.Z = (t==0) ? 1:0 
```

What is unusual, is that it "copies" bit 6 and 7 from the result of the operation to the `flags` variable. I haven't seen an opcode like this before, and it is an opcode rarely used on the 6502. In fact, people sometimes use it as an alternative to `nop`. But that doesn't mean that it shouldn't be implemented correctly.

I think I might be able to implement it with `DUP`... although I'm not sure yet.
Having an internal variable that returns the value of a certain bit from `anal->cur` would be great for this particular case.

**Comment by condret** [comment]
it once worked, when we had the array of bitmasks

**Comment by condret** [comment]
hm, u can use the DUP-operation here

**Comment by ricardoquesada** [comment]
@condret thanks! I think that fixes it.

I updated my bug report with `bit` opcode information.

**Comment by condret** [comment]
@ricardoquesada the problem with new internal-vars is, that they make the code-generation/decompilation for radeco harder, which is why i would like not to add new vars

**Comment by condret** [comment]
```` A,M,&,0x80,&,!,!,N,=,A,M,&,0x40,&,!,!,V,=,A,M,&,0xff,&,!,Z,= ````

**Comment by condret** [comment]
isn't A a 8-bit register? why do they bitcheck it with 16-bit values?

**Comment by ricardoquesada** [comment]
@condret Thanks. Good tip with the double `!`. I started implementing it using `<<`, `>>` but `!,!,` is better.

Ok. No need to add the `$t` test internal flag.
Yes, `A` is an 8 bit register. It is bit-checked with 8-bit values only. `M` (memory) is not a 16-bit value... using the esil format, it is something like this: `m,[1],a,&`
