### ISSUE TITLE
Enhace drr and pxr

### ISSUE THREAD

**Issue by radare** [radare/radare2#3375]
See https://twitter.com/radareorg/status/647896752901738496

* [x] drr is not documented in `dr?`
* [x] section/map name is not shown
* [x] we can probably show the dword contained in the target address
* [x] Show string that points to

**Comment by Maijin** [comment]
Should be added to the Visual mode debugger

**Comment by radare** [comment]
You can personalize what you see in visual mode. by default i prefer not to take all the space the output of pxr and drr is too vertical/big. it will make 80x24 terminals totally unusable. but can be handy for the V! panels thing

**Comment by jvoisin** [comment]
What about making the visual mode responsive then?
The telescoping thing is super-useful and appreciated in peda; and at workshops, a lot of people where asking for this.

**Comment by radare** [comment]
I've tried out this, but it results in very slow performance, because that analysis requires too many memory reads:
```
[0x7fff5fc01000]> e scr.null =1
[0x7fff5fc01000]> ?t pxr@rsp
3.385858
[0x7fff5fc01000]> ?t px@rsp
0.000213
[0x7fff5fc01000]> ?t drr
1.319105
[0x7fff5fc01000]> ?t dr=
0.000063
[0x7fff5fc01000]>
```

**Comment by radare** [comment]
Some enhacements have been done in master. i have updated the checklist

**Comment by Maijin** [comment]
To be added in V! :)

**Comment by radare** [comment]
If u set dbg.slow=true u get this in visual

**Comment by alvarofe** [comment]
Do you want to show always the string or only when the direction falls in a string section?

https://asciinema.org/a/4okm1fxalykgi9ruy2ci50jhr

**Comment by radare** [comment]
Only if yhe contents of the destination or the poijter stored in the destination contains a string

**Comment by radare** [comment]
Fixed!

**Comment by Maijin** [comment]
Still missing V! support

**Comment by radare** [comment]
V! Was not lsited in the issue. Open amother one or just submit a pr. Its just 2 lines of c
