### ISSUE TITLE
Please, don't analize anything

### ISSUE THREAD

**Issue by wilhelmmatilainen** [radare/radare2#3378]
http://www.urbandictionary.com/define.php?term=Analize

The correct word is analyze, not analize.
This is somewhat disturbing.

https://github.com/radare/radare2/search?utf8=%E2%9C%93&q=analize

**Comment by jjdredd** [comment]
pff, if it bothers you so much - send a pr.

**Comment by wilhelmmatilainen** [comment]
https://github.com/radare/radare2/pull/3379

**Comment by condret** [comment]
@wilhelmmatilainen what if i tell you that we use anal-plugins? :D i think, maybe this was an intended joke
