### ISSUE TITLE
af+ visual mode ascii graph segfault

### ISSUE THREAD

**Issue by shitsecurity** [radare/radare2#3381]
Fedora x86_64 w/ r2 fa238ae3c0ef246f23389b3c6d97f65725814b27

```
aa
f ftp.logic@0x402673
s ftp.logic
af+ ftp.logic 0x6bb ftp.main
VppV
j # segfault on movement in visual mode ascii graph
```

The [binary](http://rghost.net/private/62Nwsj6GK/8b65a6944377c251aed81df9d6399d32) is from csaw ctf.

Coredump available upon request.

**Comment by ret2libc** [comment]
It should be fixed now, please confirm. And thanks for reporting the issue!

**Comment by shitsecurity** [comment]
Fix confirmed! It'd be pretty sweet if af+ could recognize basic blocks based on jmp/call (without ret) control flow.

**Comment by radare** [comment]
af+ is suposed to be used for manual dump/restore of function definitions.

Use af or a2f. If something is wrong must be fixed in the analysis.

Thanks

**Comment by Maijin** [comment]
@shitsecurity you can always look for existing issue and create one related to this other problem
