### ISSUE TITLE
Cleanup the RIOSection API

### ISSUE THREAD

**Issue by radare** [radare/radare2#3382]
```
R_API RIOSection *r_io_section_get_i(RIO *io, int idx);
R_API RIOSection *r_io_section_getv(RIO *io, ut64 vaddr);
R_API RIOSection *r_io_section_mget(RIO *io, ut64 maddr);
R_API RIOSection *r_io_section_vget(RIO *io, ut64 addr);
R_API RIOSection *r_io_section_pget(RIO *io, ut64 addr);
R_API RIOSection *r_io_section_get(RIO *io, ut64 offset);
R_API ut64 r_io_section_get_offset(RIO *io, ut64 offset);
R_API ut64 r_io_section_get_vaddr(RIO *io, ut64 offset);
```

and there are more like this... the move to SIOL should include that cleanup

**Comment by radare** [comment]
i would suggest to use a single function `r_io_section_get (RIO *io, int type, ut64 addr);` where type specifies if its `va, pa, ma` or `index`

**Comment by ret2libc** [comment]
imo it's ok to have a single function ```r_io_section_get``` except for the index, because idx has a very different meaning compared to an address. So I would keep at least the ```r_io_section_get_idx```

**Comment by radare** [comment]
Ok

**Comment by condret** [comment]
@pancake: do you think it is fixed now?

**Comment by radare** [comment]
@defragger had some complains
