### ISSUE TITLE
`iaj` does not produce intended output

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#3386]
* `iaj` produces an invalid json
```json
              ... snip...
     {
            "name": "socket",
            "plt": 4198688
        }
    ]{
        "core": {
            "type": "EXEC (Executable file)",
            "file": "/Users/sushant/projects/CTF/CSAW2015/ftp_0319deb1c1c033af28613c57da686aa7",
            "fd": 6,
            "size": 18928,
            "mode": "-r--",
            "obsz": 0,
            "block": 256,
            "format": "elf64"
        },
```

* Secondly, I don't think `iaj` is working as intended. `iaj` calls ([line178](https://github.com/radare/radare2/blob/master/libr/core/cmd_info.c#L178)):
```C
case R_CORE_BIN_JSON: cmd_info (core, "ijIiecsSmz"); break;
```
However, the `j` in the string ends up matching to the following [case](https://github.com/radare/radare2/blob/master/libr/core/cmd_info.c#L439):
```C
		case 'j':
			mode = R_CORE_BIN_JSON;
			if (is_array > 1) {
				r_cons_printf (",");
			}
			cmd_info_bin (core, va, mode);
			goto done;
```
Which just prints out the bin_info and then jumps to done, therefore not producing outputs for "liecsSmz" (assuming that this was the intended behavior).

**Comment by radare** [comment]
I think that `ia` breaks a bit of the logic behind `i`. and this is why all those bugs come up. the reason why the json is invalid is because it misses a command between one block and another. so i would probably vote for removing this or rewriting the option to be just a self-call with all the specific flags.

**Comment by radare** [comment]
@jvoisin @alvarofe wanna chk this?

**Comment by radare** [comment]
Bear in mind that changint the output of `ij` to acomodate `iaj` can break the webui

**Comment by radare** [comment]
@alvarofe wanna try?
