### ISSUE TITLE
rasm2 oneliner labels doesnt work on nasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#3395]
try this:

```
$ cat test.s
label:
call label
$ rasm2 -f test.s
```

and now this:
```
$ rasm2 'label:;call label'
```

this works fine,, but it fails when using a non-native assembler plugin like `-a x86.nasm`

**Comment by mrmacete** [comment]
This apparently is not working even on multiliners, it seems the if at line 587 of libr/asm/asm.c is simply inverted.

**Comment by radare** [comment]
Can you send a pr for testing and write sone tests for the regressions?

**Comment by mrmacete** [comment]
Sure!

**Comment by mrmacete** [comment]
since this regression is actually arch-independent, should i create a new foder under t.asm ?

**Comment by radare** [comment]
yes, looks fine to me

**Comment by mrmacete** [comment]
added a PR for both radare2 and radare2-regressions

**Comment by mrmacete** [comment]
when labels has common prefix and different lengths, replacement breaks the code. it may be an issue of  how equs are replaced, i guess they should be replaced in order of length (longer first). just made a PR in regressions to catch this with a broken test.

**Comment by radare** [comment]
Nice catch!

**Comment by Maijin** [comment]
ping ?

**Comment by radare** [comment]
I doubt nasm fixed anything. The idea of this bug was to workaround that issue in our side

**Comment by Svenito** [comment]
Running this on the latest git release I get:

    $ rasm2 -a x86.nasm  'label:;call label'
    e8fbffffff

and

    $ cat test.s
    label:
    call label

    $ rasm2 -a x86.nasm -f test.s
    e8fbffffff

The rest in r2r is `t.asm/label/singleline` (https://github.com/radare/radare2-regressions/blob/3af33bb99f0653c2f6becee6eab75f8d6082ebc0/t.asm/labels/singleline) which also seems to pass. Assuming that `nasm` is the default assembler, otherwise I can add `e asm.assembler=nasm` to the test

**Comment by Maijin** [comment]
Thanks !

**Comment by radare** [comment]
that works because label evaluates to 0 and therefor it works. so this is not fixed at all

**Comment by Svenito** [comment]
OK. I'll keep on it then

**Comment by radare** [comment]
feel free to add tests :3

**Comment by Svenito** [comment]
Will do

**Comment by Maijin** [comment]
<unlogic> https://github.com/radare/radare2/issues/3395 for this, any suggestions as to how to test this?

**Comment by radare** [comment]
just rasm2 -a x86.nasm  'nop;label:;call label'

**Comment by Svenito** [comment]
I'm still getting the same result when using multiline or single line for those instructions

**Comment by Maijin** [comment]
@radare

**Comment by radare** [comment]
Oh so it works then?

**Comment by Svenito** [comment]
I'm inclined to say yes, as I'm unable to get different output from multilinear or single line input as described. I can add tests if you like though

**Comment by Maijin** [comment]
@Svenito yes please

**Comment by radare** [comment]
So close this
