### ISSUE TITLE
Stepping with F8 outside program main() generates error "r_debug_reg: error reading registers"

### ISSUE THREAD

**Issue by mrpink17** [radare/radare2#3406]
Stepping with F8 outside program main() generates error "r_debug_reg: error reading registers" in a loop. Console outputs that string in a infinite loop. CTRL + C does not work and the only way to recover is closing the console

![r2](https://cloud.githubusercontent.com/assets/13852200/10262239/76ff7464-69bf-11e5-9a3b-6ffab0e67b48.png)

**Comment by radare** [comment]
i cant reproduce this thing. which ARCH/OS/DISTRO are you using? Is this with latest code in git? i have tried linux and osx and step over never gets a hang for me.

**Comment by mrpink17** [comment]
OS:
Linux i5k 3.2.0-0.bpo.4-rt-amd64 #1 SMP PREEMPT RT Debian 3.2.68-1+deb7u3~bpo60+1 x86_64 GNU/Linux

RADARE2:
./radare2 -V
0.9.9-1059-g9b7d06a  r2
0.10.0-git  r_anal
0.10.0-git  r_lib
0.10.0-git  r_egg
0.10.0-git  r_asm
0.10.0-git  r_bin
0.10.0-git  r_cons
0.10.0-git  r_flags
0.10.0-git  r_core
0.10.0-git  r_crypto
0.10.0-git  r_db
0.10.0-git  r_bp
0.10.0-git  r_debug
0.10.0-git  r_hash
0.10.0-git  r_fs
0.10.0-git  r_io
0.10.0-git  r_magic
0.10.0-git  r_parse
0.10.0-git  r_reg
0.10.0-git  r_sign
0.10.0-git  r_search
0.10.0-git  r_syscall
0.10.0-git  r_util
WARNING: r2 library versions mismatch!

This is compiled from latest git:
commit bb26dbc82b89441e531312c99843f9da83d6cfc4
Author: pancake <pancake@nopcode.org> 2015-10-03 14:48:20
Committer: pancake <pancake@nopcode.org> 2015-10-03 14:48:20

I didn't notice that warning before, but radare2 file modification date is today. May that be important?

**Comment by mrpink17** [comment]
The warning seems to come from r_version.h which in my system is:
#ifndef R_VERSION_H
#define R_VERSION_H 1
#define R2_VERSION_COMMIT 9180
#define R2_GITTAP "0.9.9-1072-gbb26dbc"
#define R2_GITTIP "bb26dbc82b89441e531312c99843f9da83d6cfc4"
#define R2_BIRTH "2015-10-03"

R2_BIRTH seems updated but R2_GITTAP is not...

**Comment by mrpink17** [comment]
I'm getting many segmentation faults (since today, after compiling latest git). How can i fix that library mismatch?

**Comment by radare** [comment]
Are you building with sys/install.sh? Looks like there are slme libraries from different versions. See the last warninng

**Comment by radare** [comment]
Use sys/install.sh .always

**Comment by mrpink17** [comment]
Well, i was updating with git pull and compiling inside eclipse using makefile directly...
Running sys/install.sh again did not remove the warning.
I'm trying cloning from scratch and running sys/install.sh

**Comment by radare** [comment]
Do you have r2 installed in more than one place? /usr, /usr/local, ... ? Purge them all

**Comment by mrpink17** [comment]
this is the version output after a fresh compile:
0.9.9-1077-g38de57f  r2
0.10.0-git  r_anal
0.10.0-git  r_lib
0.10.0-git  r_egg
0.10.0-git  r_asm
0.10.0-git  r_bin
0.10.0-git  r_cons
0.10.0-git  r_flags
0.10.0-git  r_core
0.10.0-git  r_crypto
0.10.0-git  r_db
0.10.0-git  r_bp
0.10.0-git  r_debug
0.10.0-git  r_hash
0.10.0-git  r_fs
0.10.0-git  r_io
0.10.0-git  r_magic
0.10.0-git  r_parse
0.10.0-git  r_reg
0.10.0-git  r_sign
0.10.0-git  r_search
0.10.0-git  r_syscall
0.10.0-git  r_util
WARNING: r2 library versions mismatch!

Indeed r_version.h in the source tree contains the same version which causes the warning:
#define R2_GITTAP "0.9.9-1077-g38de57f"
So i think the warning is not real

I don't think I have other radare2 executables on my system now:
mrpink@i5k:~$ sudo find / -name radare2
[sudo] password for mrpink: 
/home/mrpink/.config/radare2
/home/mrpink/Git/radare2
/home/mrpink/Git/radare2/sys/cydia/radare2
/home/mrpink/Git/radare2/sys/debian/radare2
/home/mrpink/Git/radare2/binr/r2pm/d/radare2
/home/mrpink/Git/radare2/binr/radare2
/home/mrpink/Git/radare2/binr/radare2/radare2
/home/mrpink/Git/radare2/prefix/bin/radare2
/usr/local/bin/radare2
/usr/local/share/doc/radare2
/usr/local/share/radare2
/usr/local/lib/radare2

mrpink@i5k:~/Git/radare2$ which r2
/usr/local/bin/r2

Anyway you were right, the segfaults occurred after running install.sh with wrong prefix and I didn't clean properly.

With this clean install the issue with "r_debug_reg: error reading registers" is still present unfortunately.

**Comment by mrpink17** [comment]
GIT_TAP comes from makefile, defined as: git describe --tags
On my system is:
0.9.9-1077-g38de57f

**Comment by radare** [comment]
This is very old. Current git is 0.10-...

**Comment by mrpink17** [comment]
just tried:
git clone https://github.com/radare/radare2.git
cd radare2
git describe --tags
**0.9.9-1078-g8f8bb3f**

so everyone who clones will have the warning? am i missing something?

**Comment by mrpink17** [comment]
The same error happens when receiving signal 11:
![image](https://cloud.githubusercontent.com/assets/13852200/10279145/5af20b88-6b63-11e5-8adf-fad98e1b726d.png)

Maybe a bug in signal handling?
May you confirm if my assumption on "git describe --tags" is correct or not? (if the library mismatch warning is caused by the wrong git describe then this issue is real and not related to the warning, and there is another issue with wrong GIT_TAP)

**Comment by jjdredd** [comment]
you have an installation error. make a clean install.

**Comment by mrpink17** [comment]
Well, i tried a fresh install on virtual machine. This is output of uname -a in the VM
Linux archvm 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux

-----------
ISSUE 1 (warning library mismatch): still present. Trimmed output of r2 -V is:
0.9.9-1082-g1b3f471  r2
0.10.0-git  r_anal
-----------
ISSUE 2 (console infinite loop as in the screenshots above): still present.
-----------

Please let me know if I can provide other information in order to understand what happens.

**Comment by mrpink17** [comment]
Sorry for wrong formatting... hope it is clear anyway

**Comment by Maijin** [comment]
Dup of #5487 fixed
