### ISSUE TITLE
Windows generated binaries are broken

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3408]
Installation is correct, but the binary shipped with the installer doesn't seem to do anything

**Comment by Maijin** [comment]
Ok it's http://bin.rada.re/radare2-w32-0.10.0-git.zip which are not correct ! ping @XVilka

**Comment by XVilka** [comment]
Lets try to setup it on AppVeyor? :)

**Comment by radare** [comment]
yup!

**Comment by XVilka** [comment]
AppVeyor is cooking installer successfully now, we need to setup autodeployment via the FTP, since SSH doesn't work.

**Comment by radare** [comment]
Ftp??!? Really? Cant we use http post?

**Comment by radare** [comment]
not anymore. the windows build seems to be fine again. mingw have a bug that just generates crap if you try to make it position-independent

**Comment by Maijin** [comment]
So now, @XVilka is only need appveyor to post the binaries :)

**Comment by Maijin** [comment]
You can find installer in the release section now: https://github.com/radare/radare2/releases/tag/radare2-windows-nightly

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
ive tested the last builds and its working good

**Comment by XVilka** [comment]
@radare it doesn't fixed in the AppVeyor https://ci.appveyor.com/project/radare/radare2-shvdd/build/0.10.0.2278
It is not your fault, but all sed, uname, etc executable failing even on the configure stage.
Which binaries you were testing?

**Comment by radare** [comment]
Appveyour build system is fuckedup. Can you send a mail to they to see whats going on?

**Comment by radare** [comment]
ping @XVilka any update?

**Comment by XVilka** [comment]
@radare waiting for an answer. I'll open a support request in the forum too, today, bit later.

**Comment by radare** [comment]
Ktxby

**Comment by radare** [comment]
ive moved this to 1.0 because i dont plan to use appveyour builds for the release. this is not blocking, because this is just an appveyour bug. mingw32 and native builds on windows work as expected

**Comment by XVilka** [comment]
@radare Yep, they've answered, but it didn't helped. So it will take time to mitigate this stuff.

**Comment by radare** [comment]
Still?

**Comment by Maijin** [comment]
still on going

**Comment by radare** [comment]
status?

**Comment by Maijin** [comment]
"On going" from @XVilka

**Comment by radare** [comment]
isnt everything working now?

**Comment by radare** [comment]
status?

**Comment by XVilka** [comment]
Still not performs static linking. "--static-libgcc" not yet helped as it should have: https://github.com/radare/radare2/blob/master/sys/mingw32.bat#L7

**Comment by radare** [comment]
shouldnt this be in the LDFLAGS?

you can also just copy the missing .dll in the final build

**Comment by radare** [comment]
is ‘gcc’ really the name of the compiler you are using?

**Comment by XVilka** [comment]
yes, it's gcc

**Comment by radare** [comment]
what now

**Comment by radare** [comment]
Looks like its just an issue in jenkins. let move this to 0.10.2

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
i think i have waiting enough months for feedback on this. closing the issue. open a new one if its broken or have any kind of issue

**Comment by XVilka** [comment]
No feedback is needed, it just not worked - Jenkins generating good binaries, AppVeyor - is not. While it's ultimate goal to make AppVeyor builds OK, it's still possible to use Jenkins builds for Windows.

**Comment by Maijin** [comment]
So find a solution, because is really bad for user

**Comment by Maijin** [comment]
let the jenkins generate binaries until appveyor do and distribute the installer :P

**Comment by radare** [comment]
dont let appveyour block this thing more time. also it would be better to not distribute binaries compiled by machines not owned by us. But as long as windows is a secure operating system we shuoldnt care much about this.
