### ISSUE TITLE
Esil for AVR

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3426]
Feature: Add esil for avr

**Comment by radare** [comment]
+1

**Comment by XVilka** [comment]
:+1: too

**Comment by condret** [comment]
dependency #3307

**Comment by condret** [comment]
depends on reg-profile

**Comment by radare** [comment]
reg profile has been added.

**Comment by radare** [comment]
Basics are working, @condret is pushing some goodies everyday.
