### ISSUE TITLE
marks not saved

### ISSUE THREAD

**Issue by q6r** [radare/radare2#3429]
Marks are not saved in project.

**Comment by radare** [comment]
what is a mark?

**Comment by q6r** [comment]
In `Vpp` we can do `m1` to set mark #1 at current address and `'1` to go to that address... mN/'N. Those are not saved in the project. These are helpful if they're saved so when returning to a project one can navigate to interesting points faster.

**Comment by radare** [comment]
Ok :) nice catch.

**Comment by radare** [comment]
This was suposed to be temporal, and as long theres no r2 command to get/set them this is not serialized into the project file. But it makes sense to add a command for it and allow to dump/restore.

**Comment by radare** [comment]
i just did it :)
