### ISSUE TITLE
Sega Genesis roms support request

### ISSUE THREAD

**Issue by DrMefistO** [radare/radare2#3431]
There are SNES, Gameboy roms already, so, it would be great to add support also for Sega Genesis / Mega Drive roms.

**Comment by radare** [comment]
Can you paste the structs of the file formats for those rom images? (Just for reference and lazyness) The cpus are already supported.

**Comment by DrMefistO** [comment]
There is documentation here: http://www.romhacking.net/download/documents/643/

**Comment by DrMefistO** [comment]
Also, C structure: https://github.com/DrMefistO/smd_ida_tools/blob/master/smd_loader/smd_loader.h

**Comment by Maijin** [comment]
I have begin to work on that

**Comment by radare** [comment]
I found that this structure seems to be at 0xc0

so im not sure how those structs are going to match in there. waiting for your pullreq :) i was a huge game gear fan. and i have hardware for debugging and running that stuff on real console, so it can be a nice target for r2

thanks!

**Comment by DrMefistO** [comment]
Ok, I'll try to implement such plugin. Or, you could look at here: https://github.com/DrMefistO/smd_ida_tools/blob/master/smd_loader/smd_loader.cpp There is a stub (make_segments() subroutine) for adding SMD sections and etc. there.

**Comment by Maijin** [comment]
@DrMefistO for the NES plugin, I've used an ida loader as a reference then switched to the doc, it's easy when such loader exist because it's mostly copy/pasting the code logic.

**Comment by DrMefistO** [comment]
@Maijin, so, should I wait for your finished work, or should I start it on my own?

**Comment by radare** [comment]
we need etherpad.github.com <http://etherpad.github.com/>

**Comment by DrMefistO** [comment]
@radare, what is etherpad.github.com?

**Comment by radare** [comment]
something that doesn’t exists, but it would allow us to do proper realtime pair-programming over the interwebs

**Comment by Maijin** [comment]
@DrMefistO you should come on #radare @ freenode (IRC) at some point :) webchat.freenode.net if you don't have IRC client

**Comment by radare** [comment]
there’s also a telegram group. ping me @pancake if you prefer tg for an invite

**Comment by radare** [comment]
I would suggest to make this plugin in radare2-extras, and package it in r2pm like this:

```
$ r2pm -i gamegear
```

we can put it rbin, but i think it would be good to start moving all non-common plugins into -extras, because r2pm is quite handy right now.

**Comment by Maijin** [comment]
:+1:

**Comment by radare** [comment]
ping

**Comment by DrMefistO** [comment]
When it will be ready, I'll write here.

**Comment by radare** [comment]
no pressure, just looking for an update. let me know if you need any help.

**Comment by radare** [comment]
Sorry, i was tired of waiting. this took me just 10m to get it working and 1h to complete the support. It can be enhaced, but here's the initial implementation for you to play with. https://github.com/radare/radare2/commit/97233ecbae0c8076f37d064ee62d1a5d920b64f6

**Comment by radare** [comment]
Related http://gamehacking.org/vb/threads/489-My-Genesis-Hacking-Info%28-Chemists%29
