### ISSUE TITLE
Cheatsheet for Visual Panels

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3441]
Need cheatsheet or help for using Visual Panels

**Comment by Maijin** [comment]
@dukebarman probably better in the radare2book issues than here

**Comment by radare** [comment]
Probably handy in V!?

**Comment by Maijin** [comment]
I don't even think @dukebarman was knowing V! before you speak about it

**Comment by radare** [comment]
Then whats the visual panels for him?

**Comment by dukebarman** [comment]
I created this issue because some people try this new mode and not all know vim bindings so ask keys. I think better add guide section in radare2book and a small cheatsheet in V!?

P.S. I know that is V! :) And mean it

**Comment by Maijin** [comment]
jk of course :p Yes both of them may be useful

**Comment by radare** [comment]
Uhm? this info is already available in V!?
