### ISSUE TITLE
PE hangs

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3444]
I've started to play again with *afl*, I'll add issues as soon as I find them, likely during the next 48h.

[this]( http://rghost.net/7hxQ4WCZj ) files hangs with `r2 -A id:000000,src:000011,op:havoc,rep:64`

**Comment by radare** [comment]
cant reproduce

**Comment by jvoisin** [comment]
It doesn't hang, but it takes a really long time to be processed, and spit some errors
```
r2 -A fuzz4/hangs/id:000000,src:000011,op:havoc,rep:64 
Error: read (resource directory)
Cannot find function 'entry0' at 0x0002ba00
Cannot determine xref search boundaries
 -- Control the signal handlers of the child process with the 'dk' command
[0x0002ba00]> 
```

**Comment by jvoisin** [comment]
And [this one]( http://rghost.net/8SDP29hCD ) is hanging, **for real**

**Comment by radare** [comment]
pls confirm

**Comment by crowell** [comment]
cannot repro

On Mon, Oct 12, 2015 at 1:51 PM, radare <notifications@github.com> wrote:

> pls confirm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3444#issuecomment-147474178>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by jvoisin** [comment]
The second one is fixed, yup.

**Comment by radare** [comment]
what about the first? can you run it in gdb and ^C during the load and paste some backtraces? valgrind (callgrind) may help too

**Comment by radare** [comment]
Provide bt for the first plz
