### ISSUE TITLE
kill .esil_intr

### ISSUE THREAD

**Issue by condret** [radare/radare2#3451]
in order to enable replacing single interrupt-handlers, that cb must die, because it handles all interrupts. We already have esil->interrupts (sdb-instance), what should store all interrupt-handlers and is going to enable loading userdefined interrupt-handlers for single interrupts. This cannot be done when we have .esil_intr . Default interrupt-handlers get setup in .esil_init . Having .esil_intr is some kind of missconception to my mind.

**Comment by radare** [comment]
This is used in the baleful plugin, its suposed to be used as a lowlevel hook to implement them in the sane plugin. I know it dups functionality, but i was expecting some discussion before doinf the change. Because having an sdb router seems overkill when we just want a hook in c. Theres also a way to do interrupt hooks in r2cmd which is the 3rd method to do the same.

Its there for simplicity

**Comment by condret** [comment]
hm well, i guess i missed that change. Can we remove it, when the define-interrupt-handlers-from-user-land works?

**Comment by radare** [comment]
if we remove this we will break baleful at least. so, its not in my plans to remove it. right now there are 3 ways to hook interrupts.

* in C using filling this function pointer
* e cmd.esil.intr=#!pipe myint.js
* sdb pointers (requires to have one for each interrupt number).

also, bear in mind that syscalls are not interrupts, and the C hook you want to remove allows you to intercept ALL interrupts, the sdb router will only catch 1

**Comment by condret** [comment]
yes, interrupts are not syscalls, this is why the interrupthandler should trigger the syscall-handler

**Comment by radare** [comment]
Nop

**Comment by condret** [comment]
why not?

**Comment by condret** [comment]
i mean i think we can keep the pipe-functionallity alive without .esil_intr

**Comment by condret** [comment]
what about killing https://github.com/radare/radare2/blob/master/libr/anal/p/anal_x86_cs.c#L1301 ?

**Comment by radare** [comment]
It is harming you in any way? Its just a verbose print when this thing happens. So what

**Comment by condret** [comment]
https://github.com/radare/radare2/blob/master/libr/anal/esil.c#L123 it blocks the interrupts stored in the sdb-instance

**Comment by radare** [comment]
we should just return false or remove it. a logger should not return true.

feel free to push that change.

**Comment by XVilka** [comment]
What with this one?

**Comment by radare** [comment]
I would not kill it
