### ISSUE TITLE
wrong branch instructions for AVR

### ISSUE THREAD

**Issue by radare** [radare/radare2#3452]
```
        |   0x0000052e    a9f0           breq 0x55a
        |   0x00000546    e1f7           brne 0x540
            0x0000062a    08f4           brcc 0x62e
```

**Comment by radare** [comment]
push is also wrongly analyzed
```
            0x00000b0e    5f93           push r21
``

**Comment by Darkkey** [comment]
@radare What's wrong with push?
Push opcode is:
1001 001d dddd 1111

935f == 1001 0011 0101 1111, ddddd == 10101 == 21

For branch instructions: they are reference-like instructions (from PC - 63 to PC + 64), opcode format is 1111 00kk kkkk k001, where:
e.g. for brew:
PC <- PC + k + 1
PC <- PC + 1, if condition is false 
Also, not that AVR word is 2 bytes. So for full analyze, could you provide the exact binary with incorrect disasm?

**Comment by radare** [comment]
@Darkkey push is properly disassembled, but wrongly analyzed, it is identified as an Unknown instruction, so colorized in red.

Also, there's no ESIL for AVR yet. the arch looks pretty simple, so that should be quick to add. are you in the mood for that?

**Comment by Darkkey** [comment]
@radare Ah, sorry, it's all about sleepless night and all-day work :(

May be, but not in the next few weeks :( too much work -- need to prepare slides and solder 45 boards for radare avr workshop :)

**Comment by condret** [comment]
@radare i did some love to avr_anal, but i'm not done yet, i'm waiting for the xch-patch to continue

**Comment by radare** [comment]
@condret the patch is there, i have also pushed some tests and more enhacements in the anal, hopefully i didnt overlap too much of your changes.

**Comment by radare** [comment]
@Darkkey i have pushed some tests and fixes in the avr analysis. also added a reg profile, so everything starts to make sense now. 
@condret this xch patch is merged, so you can go on with the esil thing.
