### ISSUE TITLE
Support dbg.libs/dbg.unlibs on linux/osx

### ISSUE THREAD

**Issue by radare** [radare/radare2#3462]
If those vars are set, a hidden breakpoint to dlopen/dlclose should be set

**Comment by radare** [comment]
Internal breakpoints are set and working, the "feature" works, but it's not working as well as in Windows yet (no automatic continuation or libname detection) yet. So let's move the task for 1.0

**Comment by radare** [comment]
cc @leberus

**Comment by radare** [comment]
cc @skuater

**Comment by radare** [comment]
cc @leberus

**Comment by leberus** [comment]
I'll take a look ;)

**Comment by leberus** [comment]
hey @radare, you sure this feature is "working"?
I've written a small program that does a dlopen and dlclose, and then I've enabled "dbg.libs" in my .radare2rc.

Debugging it with gdb shows that actually breakpoints are not being set (at least on linux), the problem is :


 ```
    if (*r_config_get (r->config, "dbg.libs")) {
                r_core_cmd0 (r, ".dmm*");
#if __linux__
                setbpint (r, "dbg.libs", "imp.dlopen");
                setbpint (r, "dbg.libs", "sym._dl_map_object_from_fd");
```

then, setbpint is called:
```

static bool setbpint(RCore *r, const char *mode, const char *sym) {
        RBreakpointItem *bp;
        RFlagItem *fi = r_flag_get (r->flags, sym);
        if (!fi) return false;
```

But it looks like `r_flag_get` is not able to find any of these symbols:

```
sym._dl_map_object_from_fd
sym._dl_open
```

`dmi` shows:

```
vaddr=0x7fb2c4b99530 paddr=0x00000530 ord=004 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.dlopen
vaddr=0x7fb2c4b99540 paddr=0x00000540 ord=005 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.dlclose
```

Am I missing something?

**Comment by leberus** [comment]
Nevermind, the problem is that the right symbol is "sym.imp.dlopen". I've checked this out for all calls to r_flag_set.
I tried to change the setbpint call to look for sym.imp.dlopen and it worked.

**Comment by radare** [comment]
no it is not working on linux, only on windows

**Comment by radare** [comment]
pr?

**Comment by leberus** [comment]
I'll do the PR today, i'm on it right now

**Comment by radare** [comment]
pls @leberus confirm that its done

**Comment by radare** [comment]
ping @leberus

**Comment by radare** [comment]
reopen if not fixed, i think it is

**Comment by leberus** [comment]
it's done. Sure it could be done better but so far it works.
I'm sorry, but I'm moving to another city and i'm quite busy, so this is why i didn't reply the other pings.
I hope to get back soon :)

**Comment by radare** [comment]
Thanks for replying :) good luck with the relocation!
