### ISSUE TITLE
Problem finding PE  functions in release mode

### ISSUE THREAD

**Issue by hegusung** [radare/radare2#3468]
Hi,
I tried to disassemble my own PE binary with radare2 but when i list the functions with my PE binary compiled in release mode, only 2 functions appear : (after doing aa and afl)

a function called entry0
a function called section..text

Everything works fine with my Debug mode binary.

**Comment by radare** [comment]
How are you analyzing the binary? are you talking about symbols or functiks? Dis you run the aac command? Or maybe aap? I guess this is a 32bit W32 executable, can u provide a sample? Which functions are not found? Try enabling anal.hasnext if u are using af. Join the irc, maybe someone can give u some hints on how the analysis works in realtime

**Comment by hegusung** [comment]
ok thanks ! aac works. I will join the IRC for further questions.

**Comment by Maijin** [comment]
@hegusung use "aaa" not "aa"

**Comment by Maijin** [comment]
@hegusung  Or even simpler use r2 -A
