### ISSUE TITLE
Need command for matched zygnatures

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3471]
It would be awesome to be able to see what subset of signatures actually was found

**Comment by XVilka** [comment]
@dukebarman please, show an example how do you see it

**Comment by dukebarman** [comment]
Maybe like in 
```
z*                   display all zignatures
```
But only founded or add column/flag in z* for each founded sign

**Comment by radare** [comment]
We can show this in the `z` command

**Comment by radare** [comment]
should be done now :)

**Comment by dukebarman** [comment]
We need not only number :) Need list of founded signs

**Comment by dukebarman** [comment]
I'd suggest new "zlm" command, to show the full list of the matched zignatures

**Comment by radare** [comment]
They are stored in flags. Use the flagspace associated

**Comment by dukebarman** [comment]
Right?
```
fs sign
f
```

**Comment by Maijin** [comment]
@dukebarman `f` to display list of flagspace to choose from. You can also use `VF`

**Comment by dukebarman** [comment]
```
f                   list flags (will only list flags from selected flagspaces)
```
:))))

For VF thanks!

**Comment by Maijin** [comment]
corrected is fs sorry
