### ISSUE TITLE
seek undo/redo: don't stack consecutive dups

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3474]
How to check it:
```
s $$
s $$
s $$
s $$
s $$
s*
```
Expected output: only one entry in the seek history.

**Comment by ret2libc** [comment]
The reason for this change is that in visual and graph mode, when i press ```u``` it can happen that I have to press it many times because the same address may be stacked many times and you don't really know if there's something wrong with the visual/graph mode or it's ok.

**Comment by condret** [comment]
pls do it on the siol-branch

**Comment by radare** [comment]
Ok for but the change should be simple so it can be done in both

**Comment by condret** [comment]
merge-conflict, here we go :(

**Comment by radare** [comment]
can we close this?

**Comment by ret2libc** [comment]
Did anybody fix it?
Il 21/ott/2015 22:58, "radare" <notifications@github.com> ha scritto:

**Comment by crowell** [comment]
reopening

```
[0x004048c5]> s*
f undo_5 @ 0x4048c5
f undo_4 @ 0x4048c5
f undo_3 @ 0x4048c5
f undo_2 @ 0x4048c5
f undo_1 @ 0x4048c5
f undo_0 @ 0x4048c5
```

**Comment by radare** [comment]
Add a test case or gtfo

**Comment by radare** [comment]
@ret2libc @crowell ping
