### ISSUE TITLE
Killing the bindings?

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3480]
Since the recommended way to use r2 from foreign languages is to use `r2pipe`, shall we kill the (borken) bindings?

**Comment by XVilka** [comment]
1. Nope, bokken still use it
2. Nodejs bindings are broken for a long time - could be killed, etc.
3. In general - move the rest (officially unsupported) into the r2-bindings-extra
4. Focus on 3-4 most important languages and write tests them + add in the TravisCI

**Comment by jvoisin** [comment]
It wouldn't be that hard to port bokken to r2pipe anyway.

What would be the point of keeping the bindings?

**Comment by XVilka** [comment]
Bindings are useful, especially for things like that https://github.com/radare/radare2/issues/2100
But supporting _all_ languages - that's certainly overkill, yep. I'd leave only Python and JS as 'official' languages - thats my suggestion.

**Comment by XVilka** [comment]
Speaking of nodejs - here is the bug https://github.com/radare/radare2-bindings/issues/88

**Comment by dukebarman** [comment]
So not kill nodejs plz :)

**Comment by condret** [comment]
we should kill python (i'm not talking about the bindings)

**Comment by Maijin** [comment]
@dukebarman did you try the r2pipe in node?

**Comment by dukebarman** [comment]
@Maijin yeap. But it's not all for planned my tasks :(

**Comment by jvoisin** [comment]
But no one is maintaining nor using them :/
And I'm tired of endlessly redirecting people to r2pipe because they are broken.

**Comment by Maijin** [comment]
@dukebarman :/ I mean, why would you ever use bindings, it is very complex to use and install + highly prone to break because no maintenance, it's only generated

**Comment by dukebarman** [comment]
@Maijin r2pipe doesn't work in Windows :'(

**Comment by Maijin** [comment]
@dukebarman It would be much more easier to make the r2pipe working on windows than the bindings if that's your only problem

**Comment by XVilka** [comment]
@Maijin let both bindings blossom, not to mold.

**Comment by radare** [comment]
The bindings are working and maintained, in the sense that they compile and run the tests. Also bokken depends on them to work.

My plan is to focus on native bindings after 1.0, at the same time we do some API cleanup and refactoring. The node-ffi is probably one of the most anoying parts. But we should recommend everyone to use r2pipe.

**Comment by radare** [comment]
nodejs bindings should be fixed. but i dont think @eddyb can find some time anytime soon for it. its low-prio for me, but it would be great to get it ready for es6 and latest node-ffi

**Comment by radare** [comment]
Nope
