### ISSUE TITLE
ESIL support for the "it" Thumb instruction

### ISSUE THREAD

**Issue by radare** [radare/radare2#3486]
Some bytes: 08bf b8bf 18bf ...

Some doc: http://community.arm.com/groups/processors/blog/2010/09/30/condition-codes-3-conditional-execution-in-thumb-2

**Comment by condret** [comment]
looks like a conditional jump to me

**Comment by radare** [comment]
It is

**Comment by radare** [comment]
@condret do want?

**Comment by radare** [comment]
Currently the esil expression is wrong:

```
[0x00000000]> ao
address: 0x0
opcode: it eq
prefix: 0
id: 412
bytes: 08bf
refptr: 0
size: 2
type: cjmp
esil: zf,?{,
jump: 0x00000002
fail: 0x00000006
stack: null
cond: eq
family: cpu
```
