### ISSUE TITLE
pn command regression

### ISSUE THREAD

**Issue by futex** [radare/radare2#3494]
I'm little sad that the useful command `pn` have been removed, i was using it when I was running radare2. This habit has been disturbed, so please bring back `pn` !

**Comment by Maijin** [comment]
+1

**Comment by XVilka** [comment]
@futex that's because everyone thinking that such an utility should be a part of the coreutils, in addition to the `/bin/true`, `/bin/false` and `/bin/yes`

**Comment by jjdredd** [comment]
@XVilka since reimplementing standard utils/libs is an old tradition of r2, why not include pn in r2 also?

**Comment by condret** [comment]
u can create a core-plugin for this

**Comment by Kiwhacks** [comment]
+1

**Comment by jvoisin** [comment]
+1

**Comment by condret** [comment]
pn always impressed a lots of ppl on conferences

**Comment by CoolOppo** [comment]
What did `pn` do?
