### ISSUE TITLE
Broken Docker Build

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2#3495]
I noticed my build hadn't been updated in a few days, turns out the build is broken. Looks like it's related to the bindings.

https://hub.docker.com/r/radare/radare2/builds/bh5cxcrwpg3ym5qysw52ion/

**Comment by radare** [comment]
```
r_bin_wrap.cxx:6077:57: error: too many arguments to function 'void r_io_section_list_visual(RIO*, long long unsigned int, long long unsigned int, int)'
```

**Comment by crowell** [comment]
what compiler and such does this dockerhub use?

i dont have this problem on my machine.

On Sun, Oct 18, 2015 at 11:13 AM, radare <notifications@github.com> wrote:

> r_bin_wrap.cxx:6077:57: error: too many arguments to function 'void r_io_section_list_visual(RIO*, long long unsigned int, long long unsigned int, int)'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3495#issuecomment-149024136>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by Manouchehri** [comment]
https://hub.docker.com/r/phusion/baseimage/

Ubuntu 14.04 LTS, standard gcc 4.6.

```
apt-get install -y software-properties-common python-all-dev wget
Reading package lists...

Building dependency tree...
Reading state information...

The following extra packages will be installed:
  binutils cpp cpp-4.6 gcc gcc-4.6 gir1.2-glib-2.0 libc-dev-bin libc6-dev
  libdbus-glib-1-2 libexpat1-dev libgirepository-1.0-1 libgmp10 libgomp1
  libmpc2 libmpfr4 libquadmath0 libssl-dev libssl-doc linux-libc-dev manpages
  manpages-dev python-all python-dbus python-dbus-dev python-dev python-gi
  python2.7-dev zlib1g-dev
Suggested packages:
  binutils-doc cpp-doc gcc-4.6-locales gcc-multilib make autoconf automake1.9
  libtool flex bison gdb gcc-doc gcc-4.6-multilib libmudflap0-4.6-dev
  gcc-4.6-doc libgcc1-dbg libgomp1-dbg libquadmath0-dbg libmudflap0-dbg
  binutils-gold glibc-doc man-browser python-dbus-doc python-dbus-dbg
  python-gi-cairo
The following NEW packages will be installed:
  binutils cpp cpp-4.6 gcc gcc-4.6 gir1.2-glib-2.0 libc-dev-bin libc6-dev
  libdbus-glib-1-2 libexpat1-dev libgirepository-1.0-1 libgmp10 libgomp1
  libmpc2 libmpfr4 libquadmath0 libssl-dev libssl-doc linux-libc-dev manpages
  manpages-dev python-all python-all-dev python-dbus python-dbus-dev
  python-dev python-gi python2.7-dev software-properties-common wget
  zlib1g-dev
0 upgraded, 31 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by radare** [comment]
For some reason the radare2-bindings-python build of our CI disasspeared and i didnt realized this brokeness. Here's the patch, maybe next time you can send a PR :)

thanks!

https://github.com/radare/radare2-bindings/commit/0b9928616eaee8ec4937dc5b2b164235413d9800

**Comment by radare** [comment]
@XVilka plz setup the radare2-bindings-python CI task again
