### ISSUE TITLE
Cannot find /usr/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3497]
When opening some PE executable I got this message
```
Cannot find /usr/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
Cannot find /usr/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
Cannot find /usr/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
Cannot find /usr/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
```

I use ./sys/install.sh

**Comment by radare** [comment]
Same issue as in the w32 ordinal
Thing. This is because make install or symtall fails somehow. Check the path plz

**Comment by jvoisin** [comment]
What PE? Can you share them?

**Comment by Maijin** [comment]
most of PE got this issue

**Comment by radare** [comment]
make symstall is ok, make install is wrong. fixing in 3.. 2..

**Comment by radare** [comment]
pls confirm
