### ISSUE TITLE
a2f is not documented

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3498]
```
>a2?
>Usage: a2f
```

**Comment by radare** [comment]
Documentation is unnessary when you have the source.

**Comment by jvoisin** [comment]
Lemme documented this hidden command.

**Comment by radare** [comment]
this command is available in a plugin, not sure if you want it to be documented in core...

**Comment by radare** [comment]
also, a2f was suposed to be a rewritten of af using esil and sdb, for ease maintainability, it works. but nobody checked out yet. so im still waiting for someone to review the anal loop

**Comment by jvoisin** [comment]
I wrote two short lines to explain what it does, nothing fancy :)

**Comment by radare** [comment]
From my latest tests af is way better than a2f.. More complete.

U can enable it by setting anal.a2f=true

This will make af call a2f
