### ISSUE TITLE
radiff2 -g should output in ascii art too

### ISSUE THREAD

**Issue by radare** [radare/radare2#3508]
we need another flag to specify which kind of output we want: graphviz or asciiart. and maybe sdb-k/v, csv, etc..

**Comment by radare** [comment]
we should implement this in R_API int r_core_anal_graph(RCore *core, ut64 addr, int opts) {

**Comment by radare** [comment]
Would be cool to have an interactive asciiart graphdiff from `radiff2 -g` too

**Comment by XVilka** [comment]
Duplicate of https://github.com/radare/radare2/issues/7332
