### ISSUE TITLE
masm syntax is broken

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3516]
masm syntax is broken

"e asm.syntax=masm" doesn't work anymore

**Comment by radare** [comment]
This is capstone-x86 specific. Can ypu write a test for this? As long as capstone doesnt tests anything, we should take care of that...

**Comment by Maijin** [comment]
Will create a test from https://github.com/radare/radare2/commit/e774d332b792a0f3cffeb220071c44d9a13c36b6

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/8256fdb6c0f6b1a4a343d4e4da9afca50d25154c
