### ISSUE TITLE
handling of | character within ""  is broken

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3520]
see t/cmd_rop

```
[BR]  6  cmd_rop: search rop gadgets with a regex of the form (a|b)

Command:  /usr/bin/radare2 -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_rop-rad.KrAZSD  -n ../bins/elf/x86-helloworld-phdr > /tmp/r2-regressions//cmd_rop-out.7LnMk5 2> /tmp/r2-regressions//cmd_rop-err.gAta8s
File: ../bins/elf/x86-helloworld-phdr
Script: "/R/ (ecx|eax)"

Diff: --- /tmp/r2-regressions//cmd_rop-exp.ew3NYF       2015-10-20 07:39:19.947129667 -0400
+++ /tmp/r2-regressions//cmd_rop-out.7LnMk5     2015-10-20 07:39:19.947129667 -0400
@@ -1,23 +0,0 @@
-  0x000000b4               cd80  int 0x80
-  0x080480b6     b801000000  mov eax, 1
-  0x080480bb     b900000000  mov ecx, 0
-  0x080480c0           cd80  int 0x80
-  0x080480c2             c3  ret
-
-  0x080480b5 80b801000000b9  cmp byte [eax + 1], 0xb9
-  0x080480bc           0000  add byte [eax], al
-  0x080480be           0000  add byte [eax], al
-  0x080480c0           cd80  int 0x80
-  0x080480c2             c3  ret
-
-  0x080480b7           0100  add dword [eax], eax
-  0x080480b9           0000  add byte [eax], al
-  0x080480bb     b900000000  mov ecx, 0
-  0x080480c0           cd80  int 0x80
-  0x080480c2             c3  ret
-
-  0x080480b8           0000  add byte [eax], al
-  0x080480ba   00b900000000  add byte [ecx], bh
-  0x080480c0           cd80  int 0x80
-  0x080480c2             c3  ret
```

this used to work.

**Comment by crowell** [comment]
has rregex been changed lately?

something looks f'd

```
(gdb) p tok
$4 = 0x7fa980689640 "(ecx|eax)"
(gdb) next
(gdb) p rx
$5 = (RRegex *) 0x7fa980689890
(gdb) p tok
$6 = 0x7fa980689640 "(ecx|eax)"
(gdb) list
946                     if (!rx_list) rx_list = r_list_newf (free);
947                     gregexp = strdup (grep);
948                     tok = strtok (gregexp, ";");
949                     while (tok) {
950                             rx = r_regex_new (tok, "");
951                             r_list_append (rx_list, rx);
952                             tok = strtok (NULL, ";");
953                     }
954             }
955
(gdb)   
```
it should be working

**Comment by radare** [comment]
Yes. I updated rregex to fix a segfault. Git log libr/magic for more info. If theres a regression on that pls add more tests

**Comment by crowell** [comment]
there *is* a test, this is how i discovered it failing...

On Thu, Oct 22, 2015 at 9:23 AM, radare <notifications@github.com> wrote:

> Yes. I updated rregex to fix a segfault. Git log libr/magic for more info.
> If theres a regression on that pls add more tests
>
>
>
> > On 20 Oct 2015, at 13:49, Jeffrey Crowell <notifications@github.com>
> wrote:
> >
> > has rregex been changed lately?
> >
> > something looks f'd
> >
> > (gdb) p tok
> > $4 = 0x7fa980689640 "(ecx|eax)"
> > (gdb) next
> > (gdb) p rx
> > $5 = (RRegex *) 0x7fa980689890
> > (gdb) p tok
> > $6 = 0x7fa980689640 "(ecx|eax)"
> > (gdb) list
> > 946 if (!rx_list) rx_list = r_list_newf (free);
> > 947 gregexp = strdup (grep);
> > 948 tok = strtok (gregexp, ";");
> > 949 while (tok) {
> > 950 rx = r_regex_new (tok, "");
> > 951 r_list_append (rx_list, rx);
> > 952 tok = strtok (NULL, ";");
> > 953 }
> > 954 }
> > 955
> > (gdb)
> > it should be working
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/3520#issuecomment-150222353>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
marked as broken? when did it break? which test?

**Comment by crowell** [comment]
https://github.com/radare/radare2-regressions/blob/master/t/cmd_rop#L97

Idk when it is broken but this used to work

**Comment by Maijin** [comment]
See this one @EasyHard

**Comment by Maijin** [comment]
This is fixed
