### ISSUE TITLE
Wrong number colorization with 'e asm.emu=true' 

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3526]
```
│                0x0040012c    bd000e0000     mov ebp, 0xe00           ; 3584; ebp=0xe00 -> 0xffffff00
```
It colorize 3584 like the `[1]` follow up key, and those 0xe00, 0xffffff00  - are not colored at all.
Probably also it will be nice to make the numbers looks different from the follow-ups keys.

**Comment by radare** [comment]
Because those numbers are in a comment. And comments are comments . Not colorized magical animals
