### ISSUE TITLE
Show the line of the source code in DWARF

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3553]
That was working - see the testsuite.

**Comment by radare** [comment]
It is broken now? Is asm.dwarf set?

**Comment by XVilka** [comment]
yes. yes.

**Comment by radare** [comment]
Do you know where this was broken? Or when it was working?

**Comment by XVilka** [comment]
I'll dig after the workshop.

**Comment by radare** [comment]
the git log of this test is as weird as it has been always makred as broken.

the source:line comments are added, but it’s just unable to find the file in the filesystem. should be easy to fix then. also, maybe its a good time to add a config to specify path to source

**Comment by XVilka** [comment]
@radare then this variable should be a list of the directories, since it is useful to support iterative search in the whole list.

**Comment by radare** [comment]
Added a workaround with dir.source eval var

**Comment by radare** [comment]
We need to rethink the current dbgsrc implementation. let's move this for 1.0

**Comment by radare** [comment]
This is fixed now
