### ISSUE TITLE
VF_ should be V_

### ISSUE THREAD

**Issue by radare** [radare/radare2#3557]
the question is ... where should the current V_ live?

**Comment by radare** [comment]
@ret2libc feedback on this?

**Comment by ret2libc** [comment]
```V?_``` ?? I don't really use V_, but I see it more as an help for new users ( so some sort of "help" ```?```), more than an usual way to do things

**Comment by Maijin** [comment]
Maybe something like "V??" for the hud, since it's just an 'advanced' kind of helper

**Comment by radare** [comment]
i dont see the reason to hide another level of help in V? because the help is already r_cons_less'd

**Comment by radare** [comment]
The question is... do new users use the hud at all? :D

**Comment by radare** [comment]
Oh you mean that V?? for the hud... and V_ for the current VF_? doesnt seems a bad approach
