### ISSUE TITLE
ec is broken

### ISSUE THREAD

**Issue by condret** [radare/radare2#3566]
it does not parse background color anymore

**Comment by radare** [comment]
How are you testing this issue? `ec math red blue` works for me.

the current code seems ok:
```
R_API int r_hex_to_byte(ut8 *val, ut8 c) {
        if ('0' <= c && c <= '9')      *val = (ut8)(*val) * 16 + (c-'0');
        else if (c >= 'A' && c <= 'F') *val = (ut8)(*val) * 16 + (c-'A'+10);
        else if (c >= 'a' && c <= 'f') *val = (ut8)(*val) * 16 + (c-'a'+10);
        else return 1;
        return 0;
}
```

confusing, but correct.. so im not sure about your fix

**Comment by condret** [comment]
try that ````ec offset rgb:000000 rgb:ffffff````

**Comment by condret** [comment]
ok, i changed that 8-bit leftshift to 4-bit. Is it better now?

**Comment by radare** [comment]
no, read the code of the function. that shift is done inside the
function itself. you dont need two variables to achieve the same
