### ISSUE TITLE
support different syscall-tables

### ISSUE THREAD

**Issue by condret** [radare/radare2#3568]
as u can see in https://school.fluxfingers.net/challenges/24 it is possible to run 32-bit syscalls in 64-bit mode. It would be nice to have an extension for the as-command, where u can specify the bitness.

**Comment by radare** [comment]
All syscall tables are loaded at runtime, it depends on asm.bits, asm.os and asm.arch. there's an sdb for each combo

**Comment by radare** [comment]
just use `as 4 @b:32`

**Comment by condret** [comment]
````as 4 @b:32```` sets asm.bits to 32 and does not set it back

**Comment by radare** [comment]
oops. this is a regression. it was suposed to be temporal. i'll write a
test case now

**Comment by condret** [comment]
and it is noisy

**Comment by radare** [comment]
It is fixed now
