### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by radare** [radare/radare2#3578]
https://github.com/clyfish/gcnasm/blob/master/test/basic_test.isa

**Comment by radare** [comment]
The idea for this issue is to create assembler and disassembler plugins for various gpus

**Comment by condret** [comment]
http://developer.amd.com/wordpress/media/2012/10/R700-Family_Instruction_Set_Architecture.pdf

**Comment by neuschaefer** [comment]
Referencing #1463: The VideoCore IV is a GPU.
