### ISSUE TITLE
when using "r2 -mAddress" search will break with search.to==search.from

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3598]
When mapping a file to a certain address, `search.from` will be equal to `search.to`... and the value will be the length of the mapped file.

Steps to reproduce it:

```
$ ls -l file.bin
-rw-r--r--  1 riq  staff  3887 Sep 12 20:40 file.bin    ; Length is 3887 bytes

$ r2 -a6502 -m4096 file.bin
[0x00001000]> /x ffff
WARNING from == to?
Searching 2 bytes...
#6 [0xf2f-0xf2f]                                                      ; 0xf2f == 3887
hits: 0
```

If I don't use the `-m` option, it works ok.
I tried changing `e search.to` and `e search.from` but it didn't work.

**Comment by radare** [comment]
Whats in search.in variable? Thats the only one that matters here

**Comment by ricardoquesada** [comment]
```
[0x00000f82]> e search.
search.align = 0
search.chunk = 0
search.contiguous = true
search.count = 0
search.distance = 0
search.esilcombo = 8
search.flags = true
search.from = 0xffffffffffffffff
search.in = file
search.kwidx = 0
search.maxhits = 0
search.prefix = hit
search.show = true
search.to = 0xffffffffffffffff
```

I tried changing `search.to` and `search.from` variables but nothing happened.
I changed `search.in` to use `range` but nothing happened.

**Comment by radare** [comment]
Use search.in=map or io.map... =? Will list them

**Comment by ricardoquesada** [comment]
Thanks.
`search.in=io.maps` seems to work with `/x`
But if I use `/c` it doesn't work.
eg:
```
[0x00000f82]> e search.in=io.maps
[0x00000f82]> /x 010101010102
WARNING from == to?
Searching 6 bytes...
# 6 [0xf82-0x1eb1]
hits: 0
[0x00000f82]> /c nop
WARNING from == to?
[0x00000f82]>
```

**Comment by Maijin** [comment]
@jroimartin

**Comment by aholtzma** [comment]
Shouldn't search.in get set to io.maps automatically when '-m' is used?

**Comment by radare** [comment]
Sounds good to me, but the other default method should work as expected
