### ISSUE TITLE
wrong address after restoring a 6502 mapped file

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3599]
Just open a mapped 6502 file and save the project:
eg:
```
$ r2 -a6502 -m3970 pvm2-indiecito.sid
[0x00000f82]> Ps myproject
```

Then try to restore:
```
$ r2 -
[0x00000000]> Po sidtracker
Close current session? (Y/n)
```

The file, that was original mapped at 3970, will be mapped at 0x0 instead after restoring the project.

**Comment by radare** [comment]
Yeah. Projects are not saving the map address. Will look into it before release.

Thanks

**Comment by radare** [comment]
Can you add a testcase?

**Comment by ricardoquesada** [comment]
sure. I'll add one tomorrow.

**Comment by radare** [comment]
Yesterday is not tomorrow ;D i just fixed this thing. please add a test case, see the projects tests for it.

thanks for pointing out this!

**Comment by ricardoquesada** [comment]
@radare thanks. sorry, I didn't get it. In which folder are the project tests ? In `radare2-regressions/files/projects/test` ?

**Comment by radare** [comment]
Use r2 -p projectname to reload the project

**Comment by radare** [comment]
Grep for Po/Ps im all tests to find other project tests as sample

**Comment by ricardoquesada** [comment]
@radare done:
https://github.com/radare/radare2-regressions/pull/254
