### ISSUE TITLE
Infinite printing bug

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3605]
```
e anal.a2f=true
e anal.afterjmp=true
e anal.bbsplit=true
e anal.calls=false
e anal.eobjmp=true
e anal.esil=false
e anal.hasnext=true
e anal.limits=false
e anal.noncode=true
e anal.recont=false
e anal.nopskip=true
e anal.split=false
e anal.trace=false
e asm.bits=16
e asm.arch=mcs96
wx 0000000000
aaa
```

```
e anal.a2f=true
e anal.afterjmp=false
e anal.bbsplit=true
e anal.calls=false
e anal.eobjmp=true
e anal.esil=true
e anal.hasnext=false
e anal.limits=false
e anal.noncode=true
e anal.recont=false
e anal.nopskip=false
e anal.split=true
e anal.trace=true
e asm.bits=16
e asm.arch=m68k
wx 0000000000
aaa
```

Anothers infinite print bug, found when doing #3450

**Comment by radare** [comment]
Thats because m68k and the other anal plugs are wrong. There are some issues to report to capstone, but i have some local workarounds until its ready

**Comment by radare** [comment]
im working on this

**Comment by Maijin** [comment]
More with riscv http://pastie.org/private/p68mv2vw2o3nqofeudqzzg

**Comment by radare** [comment]
Please add this test case for ALL archs. This happens when invalid instructions are not handled by the anal plugin, so the analysis is unable to find the end

**Comment by Maijin** [comment]
* DCPU16 http://pastie.org/private/vspiiaa23hxkhrntrlmkfa 
e asm.bits=16
e asm.arch=dcpu16
e anal.a2f=true
e anal.afterjmp=true
e anal.bbsplit=true
e anal.calls=false
e anal.eobjmp=false
e anal.esil=true
e anal.hasnext=true
e anal.limits=true
e anal.noncode=true
e anal.recont=true
e anal.nopskip=false
e anal.split=true
e anal.trace=true
aaa

**Comment by Maijin** [comment]
@radare Also I cannot use w6d on the base64 string, otherwise I could create directly a r2script that you just have to run to reproduce

**Comment by radare** [comment]
Why not? Why not just wx? Thats fine. Its also fine if you send a fix :p

**Comment by Maijin** [comment]
@radare because wx would be huge

**Comment by radare** [comment]
then split it up into several lines 

wx …
s+128
wx …
s+128
…
s 0

**Comment by radare** [comment]
any other infinite analysis here?

**Comment by radare** [comment]
@Maijin ping
