### ISSUE TITLE
Run sys/user.sh in sys/install.sh if running on elcapitan

### ISSUE THREAD

**Issue by radare** [radare/radare2#3609]

**Comment by radare** [comment]
Anyone has comments on this? do we want users to install stuff system-wide?

**Comment by bydo** [comment]
/usr/local is still writeable in 10.11, SIP whitelists it.

**Comment by radare** [comment]
We should probably install r2 in /usr/local in osx. As long as its an expected path for pkgconfig and dyld.. Thanks for the tip. Will do some tests later on this

**Comment by radare** [comment]
Thanks! I have changed sys/install.sh for osx after some testing. Its now installer in /usr/local
