### ISSUE TITLE
Parsing function arguments also in registers too

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3615]
To use not only the stack for passing arguments inside the function.

**Comment by XVilka** [comment]
TOTHINK: Select some kind of ABI "profiles"? Based on the operating system or the file format.

**Comment by radare** [comment]
See ranalcctype enum... This was already defined but not finished. And cna be finished pretty quickly. I just didnt priorized it

**Comment by radare** [comment]
This can be also done with pf and debug/arg.c

**Comment by oddcoder** [comment]
done manually 
for automation on radeco side
