### ISSUE TITLE
Find and destroy esil bugs

### ISSUE THREAD

**Issue by radare** [radare/radare2#3621]
Using this magic line
```
r2 -e asm.emu=1 -qc'pD $SS@$S' /bin/ls
```

from https://github.com/radare/radare2/issues/3233

32bit only
* [x] PUSHAW
* [x] PUSHAL
```
bytes: 60
opcode: pushal
esil: 4,esp,-=,(null),esp,=[4]
must be:

Opcode	Instruction	Clocks	Description	Example
60	pusha	18	Push AX, CX, DX, BX, original SP, BP, SI, and DI	pusha
60	pushal	18	Push EAX, ECX, EDX, EBX, original ESP, EBP, ESI, and EDI	pushal
```
* [ ] POPAL
```
bytes: 61
opcode: popal
esil: esp,[4],(null),=,4,esp,+=

Opcode	Instruction	Clocks	Description	Example
61	popa	24	Pop DI, SI, BP, SP, BX, DX, CX, and AX	popa
61	popal	24	Pop EDI, ESI, EBP, ESP, EDX, ECX, and EAX	popal
```
* [ ] POPAW
```
bytes: 6661
opcode: popaw
esil: esp,[4],(null),=,4,esp,+=

(same as popa?)
```

* [x] pushf
* [ ] pushfd
* [ ] pushfq

```
[0x10007ecc8]> ao
address: 0x10007ecc8
opcode: xchg dword [rdi], ecx
prefix: 0
bytes: 870f
refptr: 0
size: 2
type: mov
esil: rdi,[4],rcx,^,rcx,=,rcx,rdi,[4],^,rdi,[4],=,rdi,[4],rcx,^,rcx,=,
stack: null
cond: 0
family: cpu
[0x10007ecc8]> "ae rdi,[4],rcx,^,rcx,=,rcx,rdi,[4],^,rdi,[4],=,rdi,[4],rcx,^,rcx,=,"
0x10007ecc8 esil_eq: invalid parameters
```

----

`r2 -caae /bin/ls`

* [x] esil_mod: Division by zero!
* [x] esil_addeq: invalid parameters
* [ ] esil_add: invalid parameters
* [ ] esil_muleq: empty stack
* [ ] esil_xor:
* [ ] ....

**Comment by Maijin** [comment]
Just linking with #3233

**Comment by XVilka** [comment]
![dead bug](http://ih1.redbubble.net/image.10787525.4248/fc,550x550,black.jpg)

**Comment by radare** [comment]
esil_mod: Division by zero!
esil_addeq: invalid parameters
esil_add: invalid parameters
esil_muleq: empty stack

**Comment by radare** [comment]
```
[0x100086c26]> ao
address: 0x100086c26
opcode: inc byte [rbx + rax]
prefix: 0
bytes: fe0403
val: 0x00000001
refptr: 0
size: 3
type: add
esil: rbx,rax,+,++=,$o,of,=,$s,sf,=,$z,zf,=,$p,pf,=
stack: null
cond: 0
family: cpu
[0x100086c26]> "ae rbx,rax,+,++=,$o,of,=,$s,sf,=,$z,zf,=,$p,pf,="
0x100086c26 esil_inceq: invalid parameters
```

**Comment by radare** [comment]
same with all the simd instructions that place (null)) instead of regname in the esil expression

**Comment by zamaudio** [comment]
I think I fixed POPA{LW} here: #4788

**Comment by rlaemmert** [comment]
pushf[dq] 
popf[dq]
pusha[d]
popa[d] 
should now work correctly

**Comment by radare** [comment]
can you add some tests for this?

thanks!

**Comment by rlaemmert** [comment]
sure just the flag pushs are not in regressions, pusha and popa is already done

**Comment by Maijin** [comment]
So just remains those

 esil_mod: Division by zero!
 esil_addeq: invalid parameters
 esil_add: invalid parameters
 esil_muleq: empty stack
 esil_xor:
 .... 

Right ?

**Comment by radare** [comment]
can you share more details on those? which instructions are producing this?

**Comment by Maijin** [comment]
Maijin M, [11.05.16 15:45]
ok, I'm closing the issue for now

Maijin M, [11.05.16 15:45]
and if encounter again, I'll create another one with details
