### ISSUE TITLE
can't search for pattern 01010102. Page issue?

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3622]
I'm trying to search for the pattern 0x01, 0x01, 0x01, 0x02 in this file:
https://www.dropbox.com/s/mt7mlde7yh9i180/pvm2-indiecito.sid?dl=1

I know the bytes are there. I simple hexudmp, o even with radare you can see them:
```
$ hexdump pvm2-indiecito.sid
...
00011f0 f0 a6 0e 33 20 ff 01 01 01 01 01 01 01 01 01 01
0001200 01 02 02 02 02 02 02 02 03 03 03 03 03 04 04 04
```
So, I would expect to find that pattern using `/x 01010102` in radare.

So I did:
```
$ r2 pvm2-indiecito.sid
[0x00000000]> /x 01010102
Searching 4 bytes...
# 6 [0x0-0x126d]
hits: 0
```

and it couldn't find it. However if I search of `0102`, instead of `01010102`, it finds it.
```
$ r2 pvm2-indiecito.sid
[0x00000000]> /x 0102
Searching 2 bytes...
# 6 [0x0-0x126d]
hits: 3
0x00000a2e hit0_0 0102
0x00000a3b hit0_1 0102
0x00001200 hit0_2 0102
```

and if I search of `01020202`  it also finds it:
```
[0x00000000]> /x 01020202
Searching 4 bytes...
# 6 [0x0-0x126d]
hits: 1
0x00001200 hit1_0 01020202
```
Perhaps it has to do that that it is on a different page (the pattern 0102 starts at 0x1200) so the alignment could affect, but my current `search.align` is 0.
These are all my search settings:
```
[0x00000000]> e search.
search.align = 0
search.chunk = 0
search.contiguous = true
search.count = 0
search.distance = 0
search.esilcombo = 8
search.flags = true
search.from = 0xffffffffffffffff
search.in = file
search.kwidx = 2
search.maxhits = 0
search.prefix = hit
search.show = true
search.to = 0xffffffffffffffff
```

__UPDATE__:
I also tried with a space between the bytes, but it didn't work:
```
[0x00000000]> /x 01 01 01 02
Searching 4 bytes...
# 6 [0x0-0x126d]
hits: 0
[0x00000000]>
```

**Comment by radare** [comment]
Try with different block sizes using the b command. I'll look into this when i have time.

Thanks for reporting

**Comment by ricardoquesada** [comment]
Thanks. Changing the block size haven't solved the issue.
I tried with a block size of 64k.
```
[0x00000000]> b 65536
[0x00000000]> b
0x10000
[0x00000000]> /x 01010102
Searching 4 bytes...
# 6 [0x0-0x126d]
hits: 0
```

**Comment by XVilka** [comment]
@ricardoquesada please add the test for this in https://github.com/radare/radare2-regressions/tree/master/t/search

**Comment by Maijin** [comment]
Or here https://github.com/radare/radare2-regressions/blob/master/t/cmd_search

**Comment by radare** [comment]
Please, stop this burocracy crap.. Writing 4 lines of test doesn't deserves the amount of time needed to comment here and wait for him to do it. Is good to teach newcomers how to contribute properly, but please, don't fall into the burocracy trap.

I just pushed the test in `t/search/sidbug`. I dont have time to check it now, but maybe i'll have a look later today or tomorrow. Thanks for reporting

**Comment by ricardoquesada** [comment]
it's working ok now. thanks for fixing it.
