### ISSUE TITLE
ob command is confusing and some commands doesnt work

### ISSUE THREAD

**Issue by radare** [radare/radare2#3628]
The `ob` command needs to be fixed and simplified. the current output is:
```
[0x100001058]> ob
binfile fd=7 /bin/ls id=1226 1 0x8750
 binobj 1079 x86-64 0x0000 0x8750
binfile fd=9 /bin/sleep id=3145 1 0x36c0
 binobj  659 x86-64 0x0000 0x36c0
```

To reproduce a bug on this try:
```
$ r2 /bin/ls
> o /bin/sleep
> ob 7
> i~file
```
this affects 'i' .. and the title in visual which displays the wrong file selected

**Comment by XVilka** [comment]
Well, it needs tests then. But what output you have in mind?
