### ISSUE TITLE
Better Tests for ESIL

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#3639]
The idea is to have better tests for x86 and x86_64 esil by comparing the ESIL register and memory states vs. a run of the same binary inside gdb. This will help us catch bugs that maybe difficult to find manually. Also, can reduce the amount of time spent in writing tests as the output is compared against a run rather than static, hardcoded values.

**Comment by radare** [comment]
this issue should be in the r2r repo, not here

**Comment by XVilka** [comment]
@sushant94 kind of related, since the gdb replay can be used instead of running gdb every time https://github.com/radare/radare2/issues/3574
