### ISSUE TITLE
unable to disassemble win PE exe on ARM host 

### ISSUE THREAD

**Issue by hemantmits** [radare/radare2#3653]
Hi,

I am trying to disassemble a win PE, build using i686-w64-mingw32-gcc on my rpi 2 box.
Its a simple "hello world" c program.

but in disassemble I am seeing lots of "unaligned" and "invalid" codes. e.g.

            0x004014e0    83ec0c         sub esp, 0xc
            0x004014e3    83ec0c         unaligned
            0x004014e4    05d8534000     add eax, 0x4053d8
            0x004014e9    05d8534000     unaligned
            0x004014ea    05d8534000     unaligned
            0x004014eb    05d8534000     unaligned
            0x004014ec    00e8           add al, ch
            0x004014ee    00e8           unaligned
            0x004014ef    00e8           unaligned
            0x004014f0    0000           add byte [eax], al
            0x004014f2    0000           unaligned
            0x004014f3    0000           unaligned
            0x004014f4    0ce9           or al, 0xe9
            0x004014f6    0ce9           unaligned
            0x004014f7    0ce9           unaligned
            0x004014f8    ff             invalid
            0x004014f9    ff             unaligned
            0x004014fa    ff             unaligned
            0x004014fb    ff             unaligned
            0x004014fc    90             nop
            0x004014fd    90             unaligned
            0x004014fe    90             unaligned
            0x004014ff    90             unaligned

But same exe disassembles fine x86 linux box.
Any idea how to fix this?

**Comment by radare** [comment]
I think `e asm.pcalign=0` will fix the issue. x86 doesnt have the alignment issue. i'll push a workaround tonight

**Comment by hemantmits** [comment]
Thanks alot for quick response.  `e asm.pcalign=0`  solved my issue.

**Comment by radare** [comment]
The fix should be ready now :) thanks for pointing out!

**Comment by radare** [comment]
please confirm. i have also pushed 4 test cases to avoid this thing to happen again

**Comment by hemantmits** [comment]
I did a build with latest code and its working fine.
Thanks alot that was quick :+1:  :)
