### ISSUE TITLE
Add Windows Types 

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3654]
For better function arguments we need to handle windows types.
Probably to be shipped in a separated sdb file

**Comment by radare** [comment]
They are all defines to basic c types

**Comment by XVilka** [comment]
@radare I think he means to ship pre-parsed types sdb for windows.

**Comment by Maijin** [comment]
Maybe something like http://paste.ubuntu.com/13086562/

**Comment by radare** [comment]
Yep. Precompiled headers :)

**Comment by Maijin** [comment]
"windows-types" in https://github.com/radare/radare2/tree/master/libr/anal/d ?

**Comment by jvoisin** [comment]
It would be cool to have those, yup.
