### ISSUE TITLE
graph comments

### ISSUE THREAD

**Issue by radare** [radare/radare2#3661]
i find useless and noisy to have comments in the graph view. the thing is that now, there's no way to drop them without quiting the graph mode. way to reproduce:

```
af
VV
:e asm.comments
(comments are gone, but node sizes are not resized)
```

**Comment by ret2libc** [comment]
You have ';' to switch comments

**Comment by ret2libc** [comment]
Btw, I think comments are really fundamental when you do RE and if you don't display comments you don't even have the shortcuts to move between functions and nodes.
We may probably want to have shorter comments by cutting them or moving them on multiple lines. 

Personally, I would go for having a var asm.multicomments=n to split comments on multiple lines if they exceed n chars. What do you think?

**Comment by ret2libc** [comment]
But that's for sure a bug. It was introduced with 35b180a484def84b12f10b664380b72385b8ee13.

**Comment by radare** [comment]
The jmphint comments are displayed even without asm.comments.. Or they should at least, because they are not comments.

Comments are provided by the user via anal/meta. And the nodes should be resized in case the content changes

**Comment by radare** [comment]
We should redesign comments for next release. Just focus on this for now. We will need to support different colors for commwnts, different locations (right or top), folded comments, flag comments.. And more. Its a huge topic and i dont wanna mess with it before the release.

**Comment by radare** [comment]
also, the ';' key redraws the graph which is ok, but it shouldnt change the scroll position. thats how it was working before

**Comment by radare** [comment]
@ret2libc ping
