### ISSUE TITLE
Cannot use long string in w6d ?

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3663]
Maybe it's a known bug but I can't use a long string when using w6d
Could be nice for creating r2 script to reproduce issue found during fuzzing or other bug such as https://github.com/radare/radare2/issues/3605

**Comment by radare** [comment]
Define long strings. R2 prompt is not infinite

**Comment by Maijin** [comment]
http://pastie.org/private/vspiiaa23hxkhrntrlmkfa

**Comment by Maijin** [comment]
wx …
s+128
s 0
To be used instead

**Comment by radare** [comment]
in r1 there was an slurp mode, but it was removed in r2 to avoid confussion. this thing was working like this:

w<<EOF
….
EOF

we can discuss to enable again this mode, but it was problematic for batch and r2pipe

**Comment by radare** [comment]
What about disussing the << instead of closingv
