### ISSUE TITLE
flirt signature loader is broken?

### ISSUE THREAD

**Issue by dmtch** [radare/radare2#3665]
Hi.
I try to use signatures like this:
[0x0040c194]> zF vc32rtf.sig
inflate error: -5 buffer error
Decompressing failed.
We encountered an error while parsing the file. Sorry.
Loading: Microsoft VisualC 2-11/net runtime
[0x0040c194]> z
Loaded 0 signatures
  0 byte signatures
  0 head signatures
  0 func signatures
I did it wrong or it's some bug in radare?

**Comment by XVilka** [comment]
@dmtch we need that file to test.

**Comment by radare** [comment]
there are some tests for flirt. But probably not enough, so it will be good if you could provide some more .flirt and bin files for testing.

thanks

**Comment by dmtch** [comment]
http://rghost.net/8x9S5Q82V
signatures from ida free

**Comment by radare** [comment]
Some files report to be using newer compression methods:
```
[0x00000000]> zFd ./c4vcl.sig
Sorry we do not support the signatures version 5 compression.
We encountered an error while parsing the file. Sorry.
Loading: CBuilder 4 and Delphi 4 VCL

**Comment by dmtch** [comment]
Are there samples of compressed *.sig files? I will fix this bug in inflate implementation.

**Comment by radare** [comment]
i dont think is a bug in the inflate implementation because we are using vanila zlib, which is fine. The problem here is that IDA changed the format of their latest signature files. And this will require some reversing to make them work here.

I'm moving this issue for 1.0, feel free to investigate on the issue, but it will be good if JF, the author of the current flirt implementation can check it out too.

**Comment by dmtch** [comment]
See, it's mistake:
zip.c: 49
	do {
		* * *
		err = inflate (&stream, Z_FINISH);
		* * *
	} while (err != Z_STREAM_END);
We call inflate() with parameter flush == Z_FINISH repeatedly until compressed data ends. zlib author wrote:
   So the only thing the flush parameter actually does is:
   when flush is set to Z_FINISH, inflate() cannot return Z_OK.  Instead it
   will return Z_BUF_ERROR if it has not reached the end of the stream.

**Comment by radare** [comment]
Can you send a pullreq that fixes this issue? Is this change fixing the problem?

Thx

**Comment by radare** [comment]
Nevermind :) i just merged and tested your PR.

Thanks!

**Comment by lambofsenpai** [comment]
It looks like this issue was resolved, however, on the most recent r2 release on Mac OS, some IDA signatures work, but I'm still getting this error when trying to scan others (for example bcb5rt.sig from the latest IDA Freeware version, or any of the mips signatures in IDA Pro).

```
[0x00000000]> zfs **.sig
Sorry we do not support the signatures version 5 compression.
We encountered an error while parsing the file ./pc/bcb5rt.sig. Sorry.
```

**Comment by radare** [comment]
i dont have or use IDA at all, if you can provide a sample maybe we can help, but if that file cant be distributed you sohuld check it out and try to fix it yourself. otherwise i would recommend you to use the r2 zignatures which are quite superior to ida ones because they support more attributes and methods.

**Comment by williballenthin** [comment]
Here is a .sig file (and corresponding .pat file) that contains around 108k FLIRT signatures generated with pcf/sigmake from IDA 7.4 against VC2015/2017/2019 x32/x64 C runtimes and common open source libraries. They are *not* derived from Hex-Rays signatures and are licensed Apache 2.0 with copyright to FireEye. They should exercise most FLIRT code paths for the latest signature format, including functions larger than u16::MAX.


[1.sig.gz](https://github.com/radareorg/radare2/files/6131554/1.sig.gz)

[1.pat.gz](https://github.com/radareorg/radare2/files/6131553/1.pat.gz)
