### ISSUE TITLE
Support and test Linux ARM64 debugger

### ISSUE THREAD

**Issue by radare** [radare/radare2#3672]

**Comment by XVilka** [comment]
Related issues are https://github.com/radare/radare2/issues/1773 and https://github.com/radare/radare2/issues/1700 (though last one should be fixed, can't reproduce anymore with qemu, please can someone retest it on the real hardware?).

**Comment by radare** [comment]
@XVilka nope. this issue is to track the native debugger, not the remote one

**Comment by radare** [comment]
linux-arm64 debugger should be working now. i have updated android builds for testing

**Comment by radare** [comment]
Looks like current register profile is wrong. (wrong size) in theory it's 34 qwords (x0-x32 + pc + sp + cpsr)

**Comment by radare** [comment]
Finally working !
