### ISSUE TITLE
Embedding the text files

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3681]
To be able to open/read/edit/remove/add the links to the local text files (or store them somewhere), and add shortcut to open them (in split? or I don't know) and read/edit. (like in vim)

Should looks something like:
```
0x000045348  mov eax, 4 ; Here is 4, magical number [all_about_4.txt]
```

**Comment by radare** [comment]
We need some discussion on this topic:

* use a specific syntax in comments?
* use anal hints to specify this?
* add extra field in comments
* which keys to use in visual mode? same for graph and panels

**Comment by XVilka** [comment]
Yes, I suggest using [filename.txt] or [filename.md] or [filename.url]. Anal hints? No, I don't think so, I think it should be somewhere in the `CC` command set. Extra field? Nope, just embed it in the comment. We can even underline such reference in the comment. Not sure about keys, any ideas?

**Comment by radare** [comment]
What about using the ',' key.or maybe just pressing ';' in viusal mode and then another key? im not sure how should we handle this from the commandline... instead of visual, because a comment can contain more than one file reference and also it can have a very long filepath which is unreadable in visual mode

**Comment by XVilka** [comment]
What about displaying only the filename, instead of the full path?

**Comment by XVilka** [comment]
And using ';' twice, I think is ok.

**Comment by radare** [comment]
; opens a prompt, so it shuold be ;;<enter> which doesnt seems too much handy. so maybe just ‘,’ and then select the file

**Comment by XVilka** [comment]
Sounds reasonable

**Comment by XVilka** [comment]
Closing now, please reopen if you think there is more to improve or discuss,

**Comment by radare** [comment]
Yeah looks quite good for now :) the code can he improved
