### ISSUE TITLE
Ability to do xor of char in ? and rax2

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3682]
Ability to do xor of char in `?` and `rax2`

Something like
```
? 0x42^B
0 0x0 00 0 0000:0000 0 00000000 0.0 0.000000f 0.000000
```

**Comment by radare** [comment]
Use wox, is not on chars or chairs, but in bytes. Aka unsigned chair

**Comment by radare** [comment]
In that case that would would be 'B' otherwise u cannot determine if its a number a char or wat

**Comment by Maijin** [comment]
I use wox already, but I don't want to write stuff but some user told that it could be nice to do that also in "? ..." to quickly try stuff. 'B' would be fine as well

**Comment by radare** [comment]
we can just teach r_num to handle single quoted chars as numbers too
