### ISSUE TITLE
r2 "pd" incorrectly disassembles some instructions [ARM, Thumb]

### ISSUE THREAD

**Issue by lizardo** [radare/radare2#3684]
Using latest r2 from git (master ad74a6e) on [example.elf.b64.txt](https://github.com/radare/radare2/files/32236/example.elf.b64.txt) (ARM Thumb ELF executable for a Cortex-M0 based microcontroller), some instructions are disassembled incorrectly.

For instance, this sequence is incorrect:
```
$ r2 example.elf
[0x00000b00]> pd 3 @ 0x356
            0x00000356    00f033f9       bl sym.app_uart_get
            ;-- $d_62:
            0x00000358    33f90028       invalid
            0x0000035c    fad1           bne 0x354
```

If the "absolute" address (.text section offset + instruction offset) is given instead, disassembly is correct (but binary analysis is lost):

```
$ r2 example.elf
[0x00000b00]> pd 3 @ 0x8356
            0x00008356    00f033f9       bl 0x85c0
            0x0000835a    0028           cmp r0, 0
            0x0000835c    fad1           bne 0x8354
```

Similarly, disabling binary analysis (using -n option) also gives correct disassembly output:

```
$ r2 -n -e asm.arch=arm -e asm.bits=16 example.elf
[0000:0000]> pd 3 @ 0x8356
            0000:8356    00f033f9       bl 0x85c0
            0000:835a    0028           cmp r0, 0
            0000:835c    fad1           bne 0x8354
```

**Comment by lizardo** [comment]
Using the following commands also generate correct disassembly (and even somewhat working rabin2 analysis!):

```
rabin2 -rSIeMzisRp example.elf > /tmp/rabin2.r2
r2 -i /tmp/rabin2.r2 example.elf
[0x00008b01]> af @ sym.main
[0x00008b01]> pdf @ sym.main
...
|    ||||   0x00008356    00f033f9       bl sym.app_uart_get
|    ||||   0x0000835a    0028           cmp r0, 0
|    `====< 0x0000835c    fad1           bne 0x8354   
...
```

Curiously, using "r2 -t example.elf" (which would be similar to the above) still generates incorrect disassembly.

**Comment by radare** [comment]
This is probably an io bug, bear in mind that physical mapping of the binary is not what the process will see when loaded in memory, so you should be seeking to the virtual address to get the correct disassembly for absolute addresses referenced in the code.

You can use the short r2 -a arm -b 16 instead of the long -e version.

Ill look into this when i have some time. Thanks

**Comment by radare** [comment]
this happens when the base address of the program is lower than the filesize. so it overlaps the fake physical memory with the virtual map producing those issues. @condret can you confirm this works fine with siol?

**Comment by radare** [comment]
nevermind. didnt saw the flag. just unset asm.midflags, thats because of the loc flags. you can fix this just doing ‘f-loc*'

**Comment by radare** [comment]
maybe we shuoldnt set flags for the local symbols.. or we should set midflags to false by default..

**Comment by lizardo** [comment]
I can confirm setting asm.midflags to false fixed the issue for me. How do I find out why some flag was created?

**Comment by radare** [comment]
This flag comes from the LOC elf symbols . See libr/format/elf.c

**Comment by radare** [comment]
I just found that NOTYPE symbols are not listed in -r mode, but created when loading r2, that was inconsistent, so i just did a separate function to perform this check and make this more consistent. Thanks for pointing this out :) it should be fine now

**Comment by radare** [comment]
Added tests https://github.com/radare/radare2-regressions/commit/017172fa915d4e677ee8860a70cd954ba5f31c93
