### ISSUE TITLE
Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3693]
* http://pastie.org/private/gldrar4n4jaatu6is8bjaa
* http://rghost.net/private/6lKvL7fJy/bcc2ce00488ecf976babd0ec18a030c2

**Comment by radare** [comment]
paste the output after this patch

$ git diff .
diff --git a/libr/anal/p/anal_x86_cs.c b/libr/anal/p/anal_x86_cs.c
index 2d8445a..862941e 100644
--- a/libr/anal/p/anal_x86_cs.c
+++ b/libr/anal/p/anal_x86_cs.c
@@ -234,6 +234,7 @@ static int analop(RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len) {
                        &size, (uint64_t*)&naddr, insn);
        }
 #else
+eprintf ("%d\n", len);
        n = cs_disasm (handle, (const ut8*)buf, len, addr, 1, &insn);
 #endif
        struct Getarg gop = {

**Comment by Maijin** [comment]
http://rghost.net/private/7LSwcCHwl/64e420e851040db65342a4add16ebc65

**Comment by radare** [comment]
32 was enough as a reply. i can confirm the issue with valgrind. not with asan, and having 32bytes of buffer shouldnt be a problem in r2. i have verfiied the thing with even rasm2:
```
[pancake@koega ~]$ valgrind rasm2 -a x86 -b32 -d 67ffc5
```

so i wrote a simple C program that just uses the capstone library, and the same valgrind messages are spitted. So this is not an r2 bug.

**Comment by radare** [comment]
@aquynh ping

**Comment by Maijin** [comment]
Fixed.
