### ISSUE TITLE
/R doesnt colorizes opcodes in disasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#3695]

**Comment by crowell** [comment]
i hate to pass the blame, but looks like an IO error, I'm goign to look more at this tonight.

**Comment by crowell** [comment]
```
(gdb) p map->from
$4 = 8388864
(gdb) p map->to
$5 = 8388884
```

something's seriously fricked

**Comment by radare** [comment]
i doubt this mainly because the color of the instruction is in the bytes…

**Comment by crowell** [comment]
Er, this was meant to be the avr bug

**Comment by radare** [comment]
no. this is a generic bug in /R
