### ISSUE TITLE
Building on OSX errors

### ISSUE THREAD

**Issue by gaming-hacker** [radare/radare2#3696]
i'm builind with xcode 7.2b3 on OS X 10.11.1
just pulled the latest
d
CC libr2.c
clang: warning: argument unused during compilation: '-pie'

clang: warning: argument unused during compilation: '-pie'
../../libr/core/libr_core.dylib: no identity found

Makefile:37: recipe for target 'osx-sign' failed
make[1]: *** [osx-sign] Error 1

any help of fixing this?

**Comment by radare** [comment]
git clean -xdf
sys/install.sh

osx-sign fail is an ignored error, if you want to codesign your r2 build just setup the environment var described in sys/install.sh output

**Comment by gaming-hacker** [comment]
ok let me look,  there was also this error
user.sh: line 42: symstall: command not found
Oops
..

i've looked there's no such command on OS X

**Comment by radare** [comment]
i cant reproduce this. if you look at the line the only reason for this issue to happen is to have "MAKE" set to "". im on yosemite, but i'll try on elcapitan

**Comment by gaming-hacker** [comment]
ok, i got it to install with sh user.sh, somehow make picked up -j4 from my env??

**Comment by radare** [comment]
the -j4 comes from MAKEJOBS, so it was you having some special env vars?
