### ISSUE TITLE
Failed to get correct segment vaddr for mach-o file.

### ISSUE THREAD

**Issue by jingtaozf** [radare/radare2#3697]
In file radare2/libr/bin/bin.c, function r_bin_get_vaddr, the following code exist:

```c
		if (!strcmp (bin->cur->o->info->arch, "arm") && (vaddr & 1)) {
			vaddr = (vaddr >> 1) << 1;
		}
```
But it's not true, for example, I have one mach-o file, which segment __objc_classname's vaddr is 0x0100c09687 and its align is one byte.

The above code will raise issue to such file.

**Comment by radare** [comment]
Can you provide a test file and a regressions script? I think this code was just a hack to get it working for thumb sections, but needs proper implementation to cover all cases.

@ret2libc can you check out this issue too?

Thanks

**Comment by jingtaozf** [comment]
```sh
r2 radare2-regressions/bins/mach0/TestApp.ios
> S
...
[03] . 0x0000a4e1 mr-x va=0x0000a4e0 sz=0x109f vsz=0x109f 3.__objc_methname
...
```
but the va should be 0x0000a4e1

**Comment by radare** [comment]
Oh! that can be the reason why some asm.emu strings are chopped by 1 char in many iOS apps. is this the same issue?

**Comment by jingtaozf** [comment]
It should be:)

**Comment by radare** [comment]
confirmed :) it’s the same issue, and dropping this code fixes the emulation output. i’m gonna investigate a bit to get a proper fix. thanks for pointing out this

**Comment by radare** [comment]
its not the ideal solution, but it should be fine now :)

**Comment by jingtaozf** [comment]
Thanks.:)
