### ISSUE TITLE
Never ever force-push to master again

### ISSUE THREAD

**Issue by TheJJ** [radare/radare2#3703]
I just noticed that there was a force push for one commit: old: b2f81a7 new: 6c48783
Please, horrible conflicts will arise when rewriting history.

The difference between these is:
```patch
@@ -1,4 +1,4 @@
-commit b2f81a7dc5a8f42d57602b66b804907bbd5a6ae2
+commit 6c487835f32ab95b2c6efc897d28fefc35d17a73
 Author: pancake <pancake@nopcode.org>
 Date:   Tue Oct 20 16:37:41 2015 +0200
 
@@ -42,7 +42,7 @@
            </div>
          </header>
 diff --git a/shlr/www/m/index.js b/shlr/www/m/index.js
-index 3ac53ad..5e4c19f 100644
+index 3ac53ad..62899e1 100644
 --- a/shlr/www/m/index.js
 +++ b/shlr/www/m/index.js
 @@ -1129,6 +1129,11 @@ function ready() {
@@ -52,7 +52,7 @@
 +	/* left sub-menu */
 +	onClick('menu_project_save', saveProject);
 +	onClick('menu_project_delete', deleteProject);
-+	onClick('menu_project_close', deleteClose);
++	onClick('menu_project_close', closeProject);
 +
  	/* right menu */
  	onClick('menu_seek', seek);

```

I have great trust in radare and it's future, so please don't mess up the repo again with a force push.

**Comment by radare** [comment]
i don't see anything wrong with this file in master, close != delete, and that's fine in the current master. this commit is very old. you should pull twice a day at least. and that's true, push -f is bad and i'm flagelating myself for this right now. But sometimes i'm not the one who fuckedup master with some wrong code and i prefer to push -f with clean code than keeping reverts and such.

There are other good development practices we are not following (yet), and we are all trying to be more puritans in those aspects. Thanks for the advice

**Comment by TheJJ** [comment]
Thanks for your consideration :)

Of course the change you did was valid, i'm just saying the force push should be avoided.
Keep up the awesome work (the TUM ctf team relies on you :grin:)!

**Comment by radare** [comment]
💪🏻
