### ISSUE TITLE
Flash assembly and disassembly support 

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3705]
Porting and extending something like a flasm could be a start http://www.nowrap.de/flasm

**Comment by Maijin** [comment]
See also: 
* https://hex-rays.com/contests/2009/SWF/ReadMe.txt => https://hex-rays.com/contests/2009/SWF/swf.zip

**Comment by xarkes** [comment]
I'm working on it.

**Comment by radare** [comment]
awesome! put it in radare2-extras and make a pkg for r2pm

**Comment by XVilka** [comment]
Done in https://github.com/radare/radare2-extras/tree/master/libr/asm/arch/swf and https://github.com/radare/radare2-extras/blob/master/libr/asm/p/asm_swf.c

Though it's quite basic and missing analysis support - this one could be closed.

**Comment by Maijin** [comment]
https://github.com/radare/radare2-extras/issues/51
