### ISSUE TITLE
Wrong generation of OpCodes

### ISSUE THREAD

**Issue by rebrec** [radare/radare2#3718]
Example better than a comment i guess :
$ rasm2 "test al,al"
85c0
$ rasm2 -d 85c0
test eax, eax

$ rasm2 -d 84c0
test al, al

(if i am missing something please forgive me (first issue ever...)

**Comment by jjdredd** [comment]
iirc not all the (dis)assembler plugins are working correctly

**Comment by radare** [comment]
-a x86.olly and -b32 as a workaround for those cases. But it is planned to extend the default assembler to handle more instructions

**Comment by rebrec** [comment]
Thanks for the workaround
