### ISSUE TITLE
Debugging 32 bits on xnu bad cpu type

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#3724]
I have not tested on others platform but when debugging 32 bits mach0 files the cpu_type that is expecting posix_spawnp is wrong because of 
```
		cpu = CPU_TYPE_I386;
		if (bits == 64) cpu |= CPU_ARCH_ABI64;

```

bits is always 64 and this value is get from core->assembler->bits in `r_core_file_open`. The way to go I think should be load the binary first and get its bits.

**Comment by radare** [comment]
Even if you -b32?

**Comment by radare** [comment]
This was working before. Probably a regression introduced by @ret2libc

**Comment by alvarofe** [comment]
Yes, it fails even though you use -b 32
