### ISSUE TITLE
[Question] PS-X executable support

### ISSUE THREAD

**Issue by Dax89** [radare/radare2#3727]
Hi,

I want to port the work that I have done some time ago in my PSX disassembler to Radare2, so other people can benefit of it.

So, I have created a r_bin plugin which parses PS-X Executable format, I have added sections and entry points, currently I'm able to get a basic MIPS listing.

Now, I want to rename some functions, because part of them are SysCalls and other ones are COP2 processor calls.

**1. PSX Syscalls** (Documentation: http://problemkaputt.de/psx-spx.htm#biosfunctionsummary)
This function rappresents a printf (t2=0x00a0, t1=0x003f, listing comes from radare2): 

```
╒ (fcn) fcn.80121c20 12
│       TEXT           ; XREFS: CALL 0x80120a3c  CALL 0x80120a70  CALL 0x801232e0  
│       TEXT           ; XREFS: CALL 0x80125f28  CALL 0x80125f54  CALL 0x8012a8a8  
│       TEXT           ; XREFS: CALL 0x8012b2e4  CALL 0x8012b618  CALL 0x8012b74c  
│       TEXT           ; XREFS: CALL 0x8012b9d4  CALL 0x8012bbe4  CALL 0x8012bc3c  
│       TEXT           ; XREFS: CALL 0x8012be40  CALL 0x8012c274  CALL 0x8012c538  
│       TEXT           ; XREFS: CALL 0x8012d4a8  CALL 0x8012d5e4  CALL 0x8012dbf0  
│       TEXT           ; XREFS: CALL 0x8012dc18  CALL 0x8012e758  CALL 0x8012f870  
│       TEXT           ; XREFS: CALL 0x8012fb44  CALL 0x8012fbd8  
│       TEXT           0x80121c20    a0000a24       addiu t2, zero, 0xa0
│       TEXT           0x80121c24    08004001       jr t2
╘       TEXT           0x80121c28    3f000924       addiu t1, zero, 0x3f
```

**2. COP2 Calls (PSX's GTE)**
COP2 calls are even easier to find (listing comes from radare2):

```
        TEXT           0x80019040    00000000       nop
        TEXT           0x80019044    0600144a       c2 0x140006  # This is a COP2 call!
        TEXT           0x80019048    00c00448       mfc2 a0, $24
```

If you look in my sources: https://github.com/PREF-Framework/PrefSDK/blob/master/disassemblers/psxexe/gte/functions.lua

You'll find that function ID 6 corresponds to **NCLIP**, so when I find a c2/cop2 call, Radare should replace the function id with its name.

There is some way to rename Syscall functions and COP2 calls automatically?

**PS:** If I use the Capstone based disassembler COP2 instructions are marked as 'invalid'

**Comment by Maijin** [comment]
@Dax89 For Capstone specific problems, feel free to open an issue on there thread https://github.com/aquynh/capstone/issues ;)

**Comment by Dax89** [comment]
I have made some research and it seems to be a known issue: https://github.com/aquynh/capstone/issues/156 :)

**Comment by Maijin** [comment]
@Dax89 Wouldn't hurt to ping them :+1:

**Comment by radare** [comment]
Try with mips.gnu disassembler and report those issues to capstone

**Comment by Dax89** [comment]
Yes, in fact I have posted the disassembler listing using mips.gnu :)

And, about the main issue (function renaming), is it possible to do it? I need a custom r_anal plugin?

**Comment by radare** [comment]
Can you submit this rbin plugin in a pullreq so i can review and suggest the enhancements?

At first instance, i would implement those post-analysis function renamings, syscall findings, etc in r2pipe scripts which can be written in any language and can be run by hand at any time.

if those functions follow any pattern you can just write some signature files for it and run them too.

I guess that you want some kind of automated way to run those scripts or post-analysis from the rbin plugin, right?

**Comment by radare** [comment]
Maybe we can add some kind of bin-specific scripts that will run after loading a specific filetype, like vim does.

**Comment by Dax89** [comment]
PR Sent: https://github.com/radare/radare2/pull/3734

**Comment by Maijin** [comment]
@dax89 see capstone issue answer

**Comment by Dax89** [comment]
I have made progress!

With Zignatures is possible to detect BIOS calls and even syscalls, I have uploaded the zignature file here: https://dl.dropboxusercontent.com/u/40206233/psxbios.z

I'm able to load it in radare and see its content:

```
[0x8012f484]> z
Loaded 256 signatures
  256 byte signatures
  0 head signatures
  0 func signatures

[0x8012f484]> z*~printf
zb psxbios.b.printf a0000a24080040013f000924
```

This is the printf:
```
[0x80121c20]> pdf
╒ (fcn) fcn.80121c20 12
│           ; XREFS: CALL 0x8012a8a8  CALL 0x8012e758  CALL 0x80125f28  
│           ; XREFS: CALL 0x80125f54  CALL 0x801232e0  CALL 0x8012dbf0  
│           ; XREFS: CALL 0x8012dc18  CALL 0x8012d5e4  CALL 0x8012d4a8  
│           ; XREFS: CALL 0x8012c274  CALL 0x8012c538  CALL 0x8012b74c  
│           ; XREFS: CALL 0x8012b9d4  CALL 0x8012be40  CALL 0x8012bc3c  
│           ; XREFS: CALL 0x8012bbe4  CALL 0x8012b618  CALL 0x8012b2e4  
│           ; XREFS: CALL 0x8012f870  CALL 0x8012fbd8  CALL 0x8012fb44  
│           ; XREFS: CALL 0x80120a70  CALL 0x80120a3c  
│           0x80121c20      a0000a24       li t2, 160
│           0x80121c24      08004001       jr t2
╘           0x80121c28      3f000924       li t1, 63
```

The problem is that when I want to apply those Zignatures radare says:

```
[0x80121c20]> iS
[Sections]
idx=00 vaddr=0x80010000 paddr=0x00000800 sz=1572864 vsz=1572864 perm=m---x name=TEXT

1 sections

[0x80121c20]> .z/0x80010000 0x80010000+1572864
Cannot alloc -2145845248 bytes
```

I'm doing something wrong?

**Comment by radare** [comment]
Looks like its using ut32 and swapping the sign of the size/offset somehow. Where can i find that file to tedt that signature file? I guess it will be reproducible with any other binary. Will check later today.

**Comment by Dax89** [comment]
I have uploaded the PS1 executable that I used for testing here: https://dl.dropboxusercontent.com/u/40206233/HITPSX.EXE

The segment addressing is more or less the same for other executables too.
If you need more samples I can provide it.

Thanks btw!

**Comment by radare** [comment]
Can i put this bin in the r2r repo or its under some kind of copyright restriction?

**Comment by Dax89** [comment]
The binary is available from here: http://hitmen.c02.at/html/psx_releases.html (more precisely: http://hitmen.c02.at/files/releases/psx/hit-mother.zip)

It's just an Intro developed in 1998 and the creators ares not affiliated by Sony.
I have checked the readme files, there is no copyright restriction.

**Comment by Dax89** [comment]
I have checked the source code for ' .z/ ' command, I was using it in the wrong way, in fact running it with a whitespace:

```
[0x80121c20]> .z/ 0x80010000 0x80010000+1572864
```

instead of:

```
[0x80121c20]> .z/0x80010000 0x80010000+1572864
```

it works.

**Comment by radare** [comment]
looks like an usability bug. can you send a PR fixing this? and add a test for that spacing issue?


thanks!

**Comment by Dax89** [comment]
Sure, I will look at that!

**Comment by Maijin** [comment]
@Dax89 for the syscall, did you take a look at this: https://twitter.com/radareorg/status/659679149385244673 ?

**Comment by Dax89** [comment]
@Maijin: yes! But it doesn't seem what I'm looking for.

Instead with Zignatures I have the behavior that I expect: functions are renamed with their real syscall name so I can find it in my listing easily :)
