### ISSUE TITLE
Automatic line break for long comments

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3731]
Instead of printing it in the one line, add the ability to break it into the multiple lines, may be depending from the terminal/split size.

**Comment by ret2libc** [comment]
This is also important for ascii art graph, because otherwise many times you have very big nodes.

**Comment by radare** [comment]
partially fixed with asm.cmtright

**Comment by radare** [comment]
pls @ret2libc @XVilka provide tests cases, screenshots or examples to see whats missing

**Comment by radare** [comment]
HELLO

**Comment by radare** [comment]
this stupid patch is also taking so much time to do it, moving forward and waiting for someone to do the 3 lines patch

**Comment by radare** [comment]
cc @kazarmy

**Comment by kazarmy** [comment]
@XVilka Was the original issue specific to Visual mode?

**Comment by XVilka** [comment]
@kazarmy yes
