### ISSUE TITLE
Flag name validation

### ISSUE THREAD

**Issue by dmtch** [radare/radare2#3738]
Hi.
There is flirt signatures db with names like "@__security_check_cookie@4". r_name_check() return error when char "@" was caught. Do you think, is safe to add '@' as valid char here?

**Comment by radare** [comment]
no, @ is an invalid char because it conflicts with r2 cmdline

**Comment by radare** [comment]
in rbin, every symbol have a realname, demangled name and flagname. this should be probalby handled for this cases too.

**Comment by dmtch** [comment]
Thanks.

**Comment by jjdredd** [comment]
maybe there should be a way to escape some chars for r2 cmdline

**Comment by radare** [comment]
There's . The quote. But escaping xhars everywhere will be a mess.
