### ISSUE TITLE
Vdi doesn't always work

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3746]
Step to reproduce:
```
e asm.arch=x86
e asm.bits=64
wx 4883f80e # cmp rax, 0xe
Vp
Vdi 10
```

The instruction keeps using hexadecimal.

**Comment by ret2libc** [comment]
Another instruction: 
```
48c1f803 # sar rax, 3
```

**Comment by radare** [comment]
only works if the number is hexadecimal. its easy to fix, this was reported yesterday by travisgoodspeed on twitter. do you want to fix it? or write a test case instead of a snippet in github?

**Comment by radare** [comment]
aka tired of waiting (R)

**Comment by ret2libc** [comment]
Doesn't work with colours.

**Comment by radare** [comment]
It does now
