### ISSUE TITLE
asm.bytes=false and cursor

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3748]
If you hide the bytes while in Visual mode, it's not clear sometimes if you are in the middle of an instruction or not.

What about replacing the cursor from '*' to '+' when it is in the middle of an instruction?

**Comment by radare** [comment]
what about +%d with the delta inside the instruction and * if its at the begining?

**Comment by ret2libc** [comment]
The only issue I can see with this approach is that we will have to reserve 3 chars for the cursor (1 for '+'/'*' and 2 for the offset, since some instructions can have more than 10 bytes). Do you think is ok to always reserve 4 chars for marks? (possibly even more, considering that soon there will be also #3331)

**Comment by radare** [comment]
looks too much space to me, only 2-3 chars is enough imho, i dont think we need 4

**Comment by ret2libc** [comment]
yeah it's too much also for me. this is why i suggested to just use '+' alone, without specifying the offset. if you want to show it, you have to reserve 4 chars ('b' for breakpoint, '+'/'*' and 2 chars for offset)
