### ISSUE TITLE
improve metadata usage in visual mode

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3751]
When moving with 'j'/'k' in visual mode, metadata should be skipped as a whole: so if i defined a qword at address 0, by pressing j i go to the address 8. Same for 'k'. If i want to go "inside" the metadata I can use 'h' and 'l'.

**Comment by ret2libc** [comment]
See #2712

**Comment by radare** [comment]
Skipped bytes depend on opcode size or anal hint right now, data size must be honored too, but can be ptoblematic if this area is too big

**Comment by ret2libc** [comment]
In which cases data can be so big?

At the moment, as you said, this is based on opcode size, but if you have defined dword/qword/or some other metadata it's better to skip the whole metadata, instead of keep using the opcode size as it was an instruction.

**Comment by radare** [comment]
nope, becuase if you are scrolling down code and suddenly you found a jump table which is 512 byte length you want to scroll slowly across this table, not skip it. same for the data section. this is. the good approach for this would be to mix px and pd in the same view if the offset is in a non-executable section

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/4026

**Comment by radare** [comment]
Closing as dupe for https://github.com/radare/radare2/issues/2712
