### ISSUE TITLE
to have Banks support (or Sections to remap the memory)

### ISSUE THREAD

**Issue by ricardoquesada** [radare/radare2#3756]
Old machines used bank-switching to map data on a certain physical memory.
As an example:
- on the C64, on the address 0xa000  you can find either the BASIC ROM or the RAM depending on a certain flag
- the C128, has 128Kb of RAM, but only 64Kb were accesible at the same time. Bank switching was used for that.

I'm implementing VICE C64 Snapshot file format support (https://github.com/ricardoquesada/radare2/tree/vsf_format) and I can load multiple sections that should be mapped in the same physical address.

As an example, these are the sections:

```
[0x0000e5d4]> S
[00] * 0x00000084 mrwx va=0x00000000 sz=0x10000 vsz=0x10000 RAM
[01] . 0x0001209d mr-x va=0x0000a000 sz=0x2000 vsz=0x2000 BASIC
[02] . 0x0001409d mr-x va=0x0000d000 sz=0x1000 vsz=0x1000 CHARGEN
[03] . 0x0001009d mr-x va=0x0000e000 sz=0x2000 vsz=0x2000 KERNAL
```

As you can see the RAM section collides with the rest, and I can't see the info that is in BASIC, unless I map it to a different address. But if I do so, then the jumps will be misplaced. 

**What it would be great to have**:
- `banks` support in `r_bin_plugin_t`: it should behave similar to `sections`, but only one can be active.
- or allow to sections to collide and have a `switch to Section` command that will activate that section.

Perhaps there is a way to re-map a section, but I couldn't find it.

This other issue is similar: https://github.com/radare/radare2/issues/448

**Comment by radare** [comment]
Gameboy have the same requirements and i think condret solve it by changing section/maps order/priorities

**Comment by ricardoquesada** [comment]
Ok, thanks. I'll ping @condret 

Changing the order did help a little bit. If RAM is the last section then it will only "occupy" the unused space, but I couldn't find a way to see the RAM space when there are collisions.

**Comment by Maijin** [comment]
Isn't that should be in https://github.com/radare/radare2/blob/master/libr/bin/p/bin_ningb.c#L221 ? Instead of sections?

**Comment by ricardoquesada** [comment]
@Maijin Thanks. Perhaps I'm doing something wrong. I'll give it a try.

How can I switch between "memories" ? Can the "memories" overlap ? The code that you mentioned doesn't have overlapped "memories".

**Comment by condret** [comment]
@ricardoquesada the answere is that all this stuff does not work, yet, because of io.
In concept those memorie-maps may overlap, but u cannot read/write on multiple maps at the same offset. you can change what map to access, either from userland or from the postloop-cb in the anal-plugin. Btw, i suggest to extend the pc to 32 bit, so that you can map everything into 32-bit addresspace and change the upper half of the pc register in the postloop-cb for bankswitches. This way the user does not accedentially mess with the priorization of the maps

**Comment by condret** [comment]
is it fixed now
