### ISSUE TITLE
io/debugger OS X: different views depending on the current offset

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3760]
How to reproduce:
```
r2 -d r2r/bins/mach0/hello-osx-x86_64
> s 0x100000000
> px 16
> s -1
> px 16
```
In the second 'px' there are only 'ff'. Seems to happen only when debugging and only with mach0.

**Comment by alvarofe** [comment]
It seems that the same happens in linux

https://asciinema.org/a/bc2xdevudvz14mbw2j9ufef42

perhaps this is right i don't know by sure but you are seeking at baddr and maybe behind that address there shouldn't be nothing mapped but just thinking loud. I've never thought on that :S

btw i just noticed that i have to seek twice to get the output right with V (you can see it in the asciinema). Someone may confirm this?

**Comment by ret2libc** [comment]
It's right that there isn't nothing behind the base address, but if i just go one byte before, only the first byte should be "ff", not all of them.

**Comment by radare** [comment]
The solution for this would be to make the mach and ptrace io read the maps of the process and in case you do a read out of bounds, just fill with fff until the begining of the next map and then read again aligned to that address. its a know bug, just not tracked yet :) feel free to fix, its kinda easy

**Comment by radare** [comment]
The problem i see in implementing this is performance, but i'll try to do it before the release

**Comment by radare** [comment]
Please confirm
