### ISSUE TITLE
Ability to reference descriptors in' o' command by index

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3763]
'o' command lists opened files
- 755566 place:// bla
  Something like ' [0] - 755566 place:// ' bla 
  Would be nice
  To type o [0]
  Instead of typing 
  o 755566

**Comment by radare** [comment]
maybe the solution would be to define sequential file descriptors in libr/io/desc.c

**Comment by radare** [comment]
what about using the `o:<idx>` subcommand?

**Comment by XVilka** [comment]
@radare sounds good, yes

**Comment by radare** [comment]
Or maybe

```
oi    - list all opened files with index (alias for  o and add index info
oi-3 - close 3rd file
oi 3 - priorize for this index
```
