### ISSUE TITLE
ahi 2 mov eax, 'A' instead of mov eax, 'AAAA'

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3766]
ahi 2 mov eax, 'A' instead of mov eax, 'AAAA'

https://github.com/radare/radare2-regressions/blob/6913c508304e3c25c1a04a81afe02be6f5634c98/t/cmd/ahi#L164

**Comment by dzruyk** [comment]
@Maijin, I suppose we may close this issue now.

**Comment by Maijin** [comment]
yep definitely :+1:
