### ISSUE TITLE
radare2 isn't as cool as elfsh

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3769]
radare2 should be able to do elf manipulations

- [x] resize sections
- [x] add sections, done with `S off va sz vsz name mrwx  add new section (if(!vsz)vsz=sz)`
- [x] change permissions on sections

this can be done with libelf, but requires some magic to fixup other pointers when modifying sections.

**Comment by jvoisin** [comment]
It seems that you can set bits with `Sa`, but it's not super documented.

**Comment by radare** [comment]
just rtfm, r2 can do all this stuff, see rabin2 -O help

**Comment by jvoisin** [comment]
rabin2 isn't super-usable from `r2pipe` ;)

**Comment by radare** [comment]
i'm doing the section.perm change thing. will commit soon

**Comment by crowell** [comment]
this add sections thing doesn't fly, it doesn't save http://asciinema.org/a/2h4rn196gdmknl4q24o925s3w

**Comment by radare** [comment]
Yeah i noticed that the modified buffer doesnt gets written to the file. This was wroking before. And i have confirmed that the changes in the buffer are correct. So it just needs a sync somewhere

**Comment by radare** [comment]
Can u write tests?

**Comment by radare** [comment]
Using the syscmdf api ;)

**Comment by radare** [comment]
Sa is for in memory changges this doesnt modifies the bin itself. See rabin2 -O p/.data/rwx for example

**Comment by radare** [comment]
Everthing is done in git already

**Comment by Maijin** [comment]
So it needs documentation

**Comment by radare** [comment]
rabin2 -O help

**Comment by crowell** [comment]
```
termina tools/radare2 ‹master› » rabin2 -O help
Operation string:
  Dump symbols: d/s/1024
  Dump section: d/S/.text
  Resize section: r/.data/1024
  Remove RPATH: R
  Change permissions: p/.data/rwx
```

this help isn't very helpful...

**Comment by jjdredd** [comment]
It's because you've never read the source ;)
