### ISSUE TITLE
Radare2 is not as cool as Relyze

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#3777]
See its [features page](https://www.relyze.com/features.html)
- [x] Analyse and explore PE files
- [x] Quick info display
- [x] Entropy graph
- [x] Structures support
- [x] Disassembler
- [x] Interactive graphs
- [x] Functions analysis
  - [x] Call convention
  - [x] Local variables
    - [x] Local variable types
  - [x] Parameter types
  - [x] Return types
- [x] Jump tables detection and resolution
- [x] Advanced search
- [x] Data type analysis, like autodiscovering types
- [x] Create and manage custom data types
- [x] Callgraph between functions
- [x] Find paths between functions
- [x] Interactive Binary Diffing
- [x] Rebasing
- [x] Plugins support
- [x] Import/export
- [x] Scriptability
- [x] Themes

**Comment by condret** [comment]
r2 is much cooler, because it has esil

**Comment by radare** [comment]
We need some ice. For kernel land or something.

**Comment by XVilka** [comment]
Updated, we are now very close. Would be even closer in a couple releases.

**Comment by radare** [comment]
we can find path between 2 functions and between 2 basic blocks already (iirc)

**Comment by XVilka** [comment]
Everything except interactive binary diffing is done. Please update the issue if something missing now.

**Comment by XVilka** [comment]
Aaand, now it is done. Thanks everyone!
