### ISSUE TITLE
visual mode: cursor issues

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#3779]
* [x] when bytes are hidden because the instruction is too long (asm.nbytes < asmop length) and you go to the last visible byte there's a glitch
* [x] when bytes are not displayed (asm.bytes=false) and you press 'l' you can move only in the first 6 bytes of the instruction (even if the instruction is longer)
* [x] sometimes when you move backward with the cursor with 'k', it goes in the middle of another instruction, not at the start of it.

**Comment by Maijin** [comment]
awesome !
