### ISSUE TITLE
Reflines use the same color as arguments

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3785]
When the line contains the local variables or arguments and there are some reflines passing by, reflines use the color of the local variables or arguments and not the color of the reflines.

**Comment by ret2libc** [comment]
asciinema please?

**Comment by radare** [comment]
a screenshot is probably enough

**Comment by XVilka** [comment]
Here you go: ![r2-varcolor](https://cloud.githubusercontent.com/assets/203261/11453638/b581a56e-9623-11e5-84a3-6a5169bd657b.png)

**Comment by radare** [comment]
Only happens with custom colorschemes

**Comment by XVilka** [comment]
Fixed, but broken the function boundary line
![r2-varcolor2](https://cloud.githubusercontent.com/assets/203261/11607561/411ab18c-9b5c-11e5-97cc-98e9f137caae.png)

**Comment by radare** [comment]
ping @ret2libc

**Comment by radare** [comment]
tired of waiting(R)
