### ISSUE TITLE
Jumps to addresses >= 0x80000000 are followed incorrectly in visual mode

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#3793]
The visual mode in radare shows branch instructions including their target offset, and pressing "enter" at a branch instruction is intended to move to its target offset. However, I have found that under certain conditions, the shown target offset and the offset that is moved to are different (e.g. 0x8000da88 vs. 0xffffffff8000da88). In particular, this seems to happen whenever the target of a branch is larger than or equal to 0x80000000. I have briefly checked the tracker for similar issues, but haven't found anything like this.

Steps to reproduce (using a 32-bit ARM binary):
* Create a dummy ARM file with e.g. the (hex) contents A03600EA (this is a relative forward branch of 0xda88 bytes)
* Run `radare2 dummy.bin`. Set up the architecture information using `e asm.arch=arm` and `e asm.bits=32`.
* Switch to visual mode using `V`. Press enter at offset 0x00000000, and it will automatically jump to 0xda88 as expected
* Now create a new section via "S 0 0x80000000 4 stuff mrwx". This will just map the same branch instruction at 0x80000000.
* Navigate to offset 0x80000000: You will see that the branch target is shown correctly as 0x8000da88, however, upon pressing "enter", the view will instead move to offset 0xffffffff8000da88.
* Having experimented with different values than 0x80000000, it seems that the issue is triggered as soon as the *target* offset is greater or equal to 0x80000000, while it seems to work fine as soon as the target offset is smaller than that. I have not tested this thoroughly enough to be 100% sure, however.

My guess about what's going on is that the target offset is internally stored as a signed 32-bit integer, then extended to a signed 64-bit integer, and eventually casted to an unsigned 64-bit integer. The presumed bug here is that sign extension is performed on a value which shouldn't actually considered to be negative.

Tested against 4e9916942c01a01e42c6482d38f03458f410ee2b.

**Comment by radare** [comment]
Can you checkthe output of the ao command? Is this bug happening with asm.arch=arm.gnu (maybe a bug in capstone?)

Thanks

**Comment by neobrain** [comment]
```
[0x80000000]> ao
address: 0x80000000
opcode: invalid
prefix: 0
bytes: ffffffff
refptr: 0
size: 4
type: ill
type2: null
stack: null
cond: 0
family: cpu
```

`asm.arch=arm.gnu` works fine indeed!

**Comment by neobrain** [comment]
With `asm.arch=arm`:
```
[0x80000000]> ao
address: 0x80000000
opcode: b 0x8000da88
prefix: 0
bytes: a03600ea
refptr: 0
size: 4
type: jmp
type2: null
esil: 2147539592,pc,=
jump: 0xffffffff8000da88
stack: null
cond: 0
family: cpu
```

`asm.arch=arm.gnu` works fine indeed! ao output:
```
[0x80000000]> ao
address: 0x80000000
opcode: b 0x8000da88
prefix: 0
bytes: a03600ea
ptr: 0x00000000
refptr: 0
size: 4
type: jmp
type2: null
jump: 0x8000da88
stack: null
cond: 6
family: cpu
```

**Comment by radare** [comment]
So thats a bug in capstone or in the capstone plugin of r2. Can you write a test case for this and i'll investigate if its a problem in our side or not.

Thanks!

**Comment by neobrain** [comment]
I'm sorry, could you explain what specifically you consider a test case? What's missing compared to the steps to reproduce given in the report?

**Comment by radare** [comment]
a test case is a script that is commited in the radare2-regressions repository that is executed on every r2 commit in order to confirm that nothing gets broken. I need the bytes of the instruction compare the output of ao, etc...

**Comment by neobrain** [comment]
I see. Since I'm not too familiar with your regression suite, would something like the following be sufficient as part of https://github.com/radare/radare2-regressions/tree/master/t.asm/arm ?

```
NAME="${PLUGIN}: stuff"
FILE=malloc://4
CMDS='
e asm.arch=arm
e asm.bits=32
e io.va=true
wx ffffffea # bl 0x80000000
S 0 0x7ffffffc 4 stuff m
s 0x7ffffffc
ao | grep jump
'
EXPECT='jump: 0x80000000
'
run_test
```

I don't have a radare2 fork set up currently, but I suppose I could set up one for submitting a PR if need be.

**Comment by Maijin** [comment]
Never use | , use `~` for internal grep

**Comment by neobrain** [comment]
@Maijin Thanks, fixed that.

**Comment by radare** [comment]
Yeah thatd fine. Iwll adapt, test and fox tonight. Thanks!

**Comment by radare** [comment]
I have added two tests. see https://github.com/radare/radare2-regressions/commit/fd71f0770cee48aae46e5a1ed92233f25f7e369f

**Comment by neobrain** [comment]
Verified that the fix works. Thank you! :)
