### ISSUE TITLE
ASCII graph edge over node

### ISSUE THREAD

**Issue by hteso** [radare/radare2#3794]
While testing the `agf` command I found that one edge goes "though" a node.

Target binary: `/bin/true`

`true: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, stripped`

Example:

http://pastebin.com/MzDSGegW

**Comment by ret2libc** [comment]
Thanks for reporting. This is a known bug, already listed in https://github.com/radare/radare2/issues/2091 and a good solution would require some time.

**Comment by radare** [comment]
404

**Comment by Maijin** [comment]
Duplicate
