### ISSUE TITLE
pdf can't find function listed by afl

### ISSUE THREAD

**Issue by hgascon** [radare/radare2#3797]
The function *fcn.0040807e* is listed in the output of **afl** but the **pdf** command doesn't find it. 

```nasm
	$ r2 -A ./bin
	[0x004081fc]> afl | head
	0x004081fc  10  27  entry0
	0x0040f742  150  9  fcn.0040f742
	0x0040807e  382  26  fcn.0040807e
	0x004097fc  69  1  fcn.004097fc
	0x004099ec  48  3  fcn.004099ec
	0x0040a40a  397  18  fcn.0040a40a
	0x0040f6f6  38  5  fcn.0040f6f6
	0x0040f4a2  596  47  fcn.0040f4a2
	0x0040f36b  311  29  fcn.0040f36b
	0x0040f2b0  187  12  fcn.0040f2b0
	[0x004081fc]> s fcn.0040807e
	[0x0040807e]> pdf
	Cannot find function at 0x0040807e
```

The **pd** command displays some code but still doesn't show the function completely:

```nasm
	[0x0040807e]> pd@fcn.0040807e | tail
	│           0x00408138      a3c0554300     mov dword [0x4355c0], eax
	│           0x0040813d      e86e710000     call fcn.0040f2b0
	│           0x00408142      85c0           test eax, eax
	│       ┌─< 0x00408144      7d08           jge 0x40814e
	│       │   0x00408146      6a08           push 8
	│       │   0x00408148      e8ff180000     call fcn.00409a4c
	│       │   0x0040814d      59             pop ecx
	│       │   ; JMP XREF from 0x00408144 (fcn.0040807e)
	│       └─> 0x0040814e      e8e56e0000     call fcn.0040f038
	│           0x00408153      85c0           test eax, eax
	[0x0040807e]>
```

In visual mode, the function is displayed correctly and the corresponding *ret* instruction is shown at the end of the function:

		 =---------------------------------------------------=	
         |  0x4081f6                                         |
         | ; JMP XREF from 0x004081e1 (fcn.0040807e)         |
         | 0x004081f6 e846160000     call fcn.00409841 ;[t]  |
         | 0x004081fb c3             ret                     |
         =---------------------------------------------------=

**Comment by radare** [comment]
Hashtable glitch?

**Comment by hgascon** [comment]
It happens with different binaries for a small number of functions. In the binary here, for example (https://drive.google.com/file/d/0B8IlCPnvBi9TVGtOU1JEUlN4R0k  pass:infected), functions at 0x0000ec00 and 0x0000f45b are listed but disassembling with **pdf** fails. Any idea?

**Comment by Maijin** [comment]
the function located at 0x0000ec00 is detected as loc and cannot indeed be pdf but works fine in the visual graph.

For the one at 0x0000f45b it as simply disappear from the analysis result probably was false positive

**Comment by radare** [comment]
use `-e io.sectonly=true` . there's no function there because its not mapped in memory, its just the mirror of the physical file that produces that analysis issue. some references jump below the baddr and it thinks its valid code.

Maybe we should set io.sectonly=true by default

**Comment by Maijin** [comment]
Yes, that would make sense and would be definitely less confusing !

**Comment by Maijin** [comment]
I'll make a test PR to see how tests react on this

**Comment by radare** [comment]
Do we have tests for this?

**Comment by Maijin** [comment]
nop I'll add one for sure. Here are the XX tests:

- baddr: io.baddr -x86_32 entry0 data  
- ff: presection read  
- java: use java set_flags and flags_str_at to reset the access flag on class file entities
- java: af java multiple classes loaded via malloc and ib
-  emu: Windows Function EMU printf   
- emu: Windows Function EMU LoadStringA
- emu: Linux fcnsign test        
- cmd_anal_fcn: sym is not fun 
-  stref: auto string memory reference (io.va)

https://s3.amazonaws.com/archive.travis-ci.org/jobs/123024983/log.txt

**Comment by Maijin** [comment]
ok tested

**Comment by radare** [comment]
i cant find     Cannot find function at 0x0040807e listed in functions. so imho this was a bug that is already fixed in the analysis and there was no function at all there. can @hgascon confirm?

**Comment by hgascon** [comment]
I can't find it either so you may be right and there was no function there. I'll report if it happens again somewhere else.

**Comment by Maijin** [comment]
I'll reopen another issue for sect only
