### ISSUE TITLE
Past-EOF Writes to Binary Files, Incorrect Addressing Mode

### ISSUE THREAD

**Issue by travisgoodspeed** [radare/radare2#3807]
## Summary

When writing to a binary blob file, r2 writes to the absolute memory address in the file, rather than the address relative to the loading point.

## Behaviors

The expected behavior is for the write to happen relative to the loading address, so that a patch to an instruction happens in that instruction.  The observed behavior is that the write occurs well past the end of the file, at the absolute address interpreted as a relative file address.

## Example

In this example, `foo` is a raw ARM/Thumb firmware image that is loaded to 0x0800C000; it is not an ELF or PE.  The user tries to patch a branch instruction into 0x0803ee86, expecting r2 to write the new instruction at file address 0x32e86, which is (0x0803ee86-0x0800C000).  Instead, r2 writes the patch to file address 0x0803ee86, more than 128 megabytes after the previous end of the file!

```
tmg% ls -lah foo
-rw-r--r--  1 tmg  staff   971K Dec  5 15:19 foo
tmg% r2 -a arm -b 16 -m 0x0800C000 -w foo
[0x0800c000]> wa b 0x0803ee20 @ 0x0803ee86
Written 2 bytes (b 0x0803ee20) = wx cbe7
^D
tmg% ls -lah foo
-rw-r--r--  1 tmg  staff   128M Dec  5 15:21 foo
tmg% hexdump foo | tail
00f2990 05 00 0b d4 10 01 e8 03 10 23 12 40 31 62 00 09
00f29a0 15 44 1c 17 01 05 63 63 ff 05 05 05 07 05 06 05
00f29b0 30 08 0a 24 0c 05 0d 05 0e 06 0f 05 0e 63 10 03
00f29c0 09 04 00 00 ff ff ff ff ff ff ff ff ff ff ff ff
00f29d0 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
*
00f2c00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
803ee80 00 00 00 00 00 00 cb e7                        
803ee88
tmg% 
```

## Disclaimers

Before submitting, this was verified to be the behavior in the latest git tree.  No opened issues were found that matched to this issue.

**Comment by radare** [comment]
This happens only when using maps instead of sections. The map address is not properly handled by the write machinery. as a workaround you can just define a section for now.

This should be working fine in the siol branch because theres no such distinction. A testcase would be good to be added in the regressions repo, the fix should be easy but im actually afk til monday or so.

**Comment by travisgoodspeed** [comment]
Many thanks for patching this so quickly, but 61fba1e6630c78d932b557dbca87a53fb8feaaf7 doesn't seem to have fixed the bug.

```
tmg% dd if=/dev/urandom of=foo bs=1024 count=1024
1024+0 records in
1024+0 records out
1048576 bytes transferred in 0.069921 secs (14996578 bytes/sec)
tmg% ls -lah foo
-rw-r--r--  1 tmg  staff  1M Dec  7 17:22 foo
tmg% r2 -a arm -b 16 -m 0x0800C000 -w foo
[0x0800c000]> wa b 0x0803ee20 @ 0x0803ee86
Written 2 bytes (b 0x0803ee20) = wx cbe7
^D
tmg% ls -lah foo
-rw-r--r--  1 tmg  staff   128M Dec  7 17:22 foo
tmg% r2 -V | head -n 1
0.9.9-1773-g61fba1e  r2
tmg% 
```

The target address arithmetic seems to be unchanged.

```
tmg% hexdump foo | tail
00fffa0 ce c2 c2 6e ff 7a 30 92 a3 86 73 29 25 80 65 a0
00fffb0 8a 85 c3 72 31 71 d1 4e 5c 27 3b 5c a4 27 55 76
00fffc0 c4 40 08 64 e5 1e 96 14 ad 38 d0 3f 20 54 04 55
00fffd0 03 ef 6b de 2a 46 78 db d8 aa d3 c0 15 b4 ab 4a
00fffe0 0c f3 db 94 83 dd 16 b9 8a 10 e1 88 96 53 c3 e3
00ffff0 a6 d5 2a 55 92 6b 57 2a 8e d3 1f fe de c0 cc 57
0100000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
*
803ee80 00 00 00 00 00 00 cb e7                        
803ee88
tmg% 
```

**Comment by radare** [comment]
i wrote a test case and it was fixing the issue, ill look again and write more tests

**Comment by radare** [comment]
ehm.. it works fine for me. you are patching the wrong offset or something.. 
```
0x0803ee86 - 0x0800C000 = 0x32e86
```

the patch is done at this offset. you can use radiff2 to see what changed

**Comment by travisgoodspeed** [comment]
Upgrading from 61fba1e to master, I can no longer reproduce the bug.  Closing this issue and very happily dropping a bunch of my janky Python code for r2 scripts!

**Comment by radare** [comment]
awesome :)
