### ISSUE TITLE
Poor performance in visual mode during remote debugging via gdbserver

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#3808]
Radare's visual mode performs incredibly slow when viewing the disassembly of programs running in a gdbserver.

Steps to reproduce:
- Run `gdbserver localhost:12345 /usr/bin/ls`
- Run `r2 -D gdb gdb://localhost:12345`
- Switch to visual mode using `V` and toggle the disassembly using `p`. If that's not already super-slow, try scrolling in visual mode. Scrolling by a single row already takes a few seconds here, making _actual_ scrolling is unbearable.

During development of an ARM gdbstub for debugging ARM applications running in a private emulator of mine, I've noticed that radare sends off a lot of redundant memory read commands in visual mode, suggesting a lack of caching. I suspect this to be the core reason for the poor performance. For instance, enabling the disassembly view triggers this chain of memory reads (format: `m<address>,<size>`):

```
 m000000001ffab034,500
 m000000001ffab228,92
 m000000001ffab034,185
 m000000001ffab0ed,185
 m000000001ffab12c,500
 m000000001ffab320,125
 m0000000017e00004,500
 m0000000017e001f8,125
 m000000001ffab118,500
 m000000001ffab30c,125
 m000000001ffab130,500
 m000000001ffab324,125
 m00000000ffff0000,500
 m00000000ffff01f4,125
 m000000001ffab130,500
 m000000001ffab324,125
 m00000000ffff0000,500
 m00000000ffff01f4,125
 m000000001ffab130,500
 m000000001ffab324,125
 m00000000ffff0000,500
 m00000000ffff01f4,125
 m000000001ffab130,500
 m000000001ffab324,125
 m00000000ffff0000,500
 m00000000ffff01f4,125
 m000000001ffab130,500
 m000000001ffab324,125
 m00000000ffff0000,500
 m00000000ffff01f4,125
```

Clearly, only three reads should be necessary: One based at address 0x1ffab034, one based at 0x17e00004, and one based at 0xffff0000.

I've tried using the options `io.buffer.from=0x1ffab000; io.buffer.to=0x1ffabf00; io.buffer=true` and `io.cache=true`, however they didn't seem to reduce the number of redundant reads at all.

I've looked for similar issues and couldn't find any, other than possibly #1773, which seemed fairly specific though. The issue described in this report affects any sort of remote gdb debugging over network.

**Comment by jjdredd** [comment]
Overall visual mode performance is slow, even when colorization is off.

**Comment by radare** [comment]
e asm.slow=false

**Comment by neobrain** [comment]
@radare That seems to help a little by reducing the number of redundant reads by (presumably) reducing the overall number of reads. However, it still re-reads memory upon any single-line scrolling. As such, it still takes between 2 and 3 seconds for me to scroll by a single line of disassembly.

**Comment by radare** [comment]
Yep im aware. The gdb backend should cache the read mem/reg ops to avoid that. I just never use it, so thats why i didnt really priorized it. Gdb is an awful protocol

**Comment by neobrain** [comment]
> Gdb is an awful protocol

It absolutely is indeed, heh.

Would there be any interest in having a caching system for the gdb code contributed? I might be able to spend a day or two on doing so. Just curious whether the project guidelines would require me to make the caching system more generically useful beyond gdb, or whether it needs to come with unit tests, etc.

**Comment by radare** [comment]
yes, i have started to write that caching thing in the io, but it needs to be tweaked to enable it ,and some tests just fail, that's why its not enabled by default yet. i'll try to find some time for this before the release. but i cant promise much lately..

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/4038

**Comment by XVilka** [comment]
@neobrain any news about that?

**Comment by neobrain** [comment]
@xvilka Sorry, other stuff came up and I won't be able to work on this currently.

**Comment by jduck** [comment]
I propose if there is some cache implemented that it remains valid so long as the process is stopped. There are a lot of redundant things happening (looking up register values, memory contents, etc) that only need to happen once if the process is stopped. This gets a bit trickier once multiple threads are supported (or if shared memory is used) though. Further, it might be possible to use the insns/data-delta to update the memory cache without invalidating it. Certainly there are cases -- like stepping over sysenter or such -- where invalidating the cache would still be necessary.

**Comment by radare** [comment]
Yes this is half implemented in the iogdb plugin with an #if 0. Also there's a cache layer in rio. But i think it would be better to cache blocks rather than what its read because sometimes it does many little reads that makes the cache fragment and underperform.

If you wanna take a look go ahead. Its not currently an issue for me but it will be pleasant to have caches reads working

**Comment by jduck** [comment]
It's not a huge issue for me either since I am doing what I can to avoid remote-gdb. It's just too damn slow =)

**Comment by Maijin** [comment]
@SrimantaBarua status on this ?

**Comment by SrimantaBarua** [comment]
IO cache I think was added in the siol merge. @condret ? But I still see a few redundant memreads in visual mode after turning on cache.
```
getpkt ("m00007ffff7dda976,b9")
getpkt ("m00007ffff7dda976,b9")
...
getpkt ("m00007fffffffe540,b9")
getpkt ("m00007fffffffe540,b9")
getpkt ("m00007fffffffe540,b9")
getpkt ("m00007fffffffe540,40")
getpkt ("m00007fffffffe540,b9")
getpkt ("m00007fffffffe540,b9")
...
getpkt ("m00007ffff7dda976,b9")
getpkt ("m00007ffff7dda976,b9")
...
getpkt ("m00007ffff7ffd9d0,34f")
getpkt ("m00007ffff7ffd9d0,7f")
...
getpkt ("m0000000000000000,7")
getpkt ("m0000000000000000,8")
...
getpkt ("m0000000000000000,8")
getpkt ("m0000000000000000,7")
getpkt ("m0000000000000000,8")
...
getpkt ("m00007ffff7ffd9f0,8")
getpkt ("m00007ffff7ffd9f0,34f")
```
It's possible to implement this specifically for the gdb plugin, but might promote redundancy. But should I?

**Comment by Maijin** [comment]
Question is more, is it still slow 
Yes-> Don't close the issue
No -> Close this issue and keep this inquiry somewhere else

**Comment by SrimantaBarua** [comment]
Much better than before. Scrolling, stepping etc. even with `e dbg.slow=true` is quite smooth, atleast on localhost. But can be improved further.

Asciinema for debugging r2 itself -
https://asciinema.org/a/hIj9uP3sBmEFF4KTV1EORSHPC

**Comment by Maijin** [comment]
Then closing here
