### ISSUE TITLE
Flirt signatures technical details

### ISSUE THREAD

**Issue by dmtch** [radare/radare2#3816]
I want to improve functions recognition through using of flirt signatures. Sometimes r2 functions analysis is mistaken and it splits one function with inner call (probably, a seh installation). It will be nice to get somehow functions size from flirt! But signatures "module length" is often larger or smaller than functions size. Do you have any opinion how it's made in ida?

**Comment by dmtch** [comment]
Ida exactly uses signatures in this case, because without them she makes the same errors.

**Comment by radare** [comment]
as far as i know, the flirt version supported by r2 doesnt shows this information, maybe this is in the next version of it. also, function sizes are not linear, so the only way to do this would to store a graph of the function with each basic block and boundaries stored in there

**Comment by dmtch** [comment]
I did it, it was a small error when signature comparison. Signatures contains correct (as it's presented in ida) functions lengths.
https://github.com/radare/radare2/pull/3817

**Comment by radare** [comment]
Awesome! good catch, can we close this issue now?

**Comment by radare** [comment]
maybe adding some tests?

**Comment by radare** [comment]
@Maijin ping

**Comment by Maijin** [comment]
@radare ? Tests have been by @dmtch already looks like

**Comment by radare** [comment]
so we can close this thing?
