### ISSUE TITLE
afa-* & afv-* doesn't work

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3825]
afa-* & afv-* doesn't work see the testcase https://github.com/radare/radare2-regressions/blob/master/t.anal/others_anal/vars#L167

**Comment by radare** [comment]
this is important to get it fixed

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t.anal/others_anal/vars#L167

**Comment by radare** [comment]
It works. but argument is the offset. not the name

**Comment by radare** [comment]
and i have already fixed that afv-* thing yesterday

**Comment by Maijin** [comment]
yes this one is fixed :)
