### ISSUE TITLE
afa-name & afv-name doesn't work

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3827]
afa-name & afv-name doesn't work 

* https://github.com/radare/radare2-regressions/blob/master/t.anal/others_anal/vars#L77
* https://github.com/radare/radare2-regressions/blob/master/t.anal/others_anal/vars#L141

**Comment by radare** [comment]
you have to pass the offset, not the name. at least thats what the code does

**Comment by Maijin** [comment]
So it's an enhancement

**Comment by radare** [comment]
@zlowram wanna check this one too?

**Comment by zlowram** [comment]
Will take a look at this after I finish with #3866

**Comment by jjdredd** [comment]
dead links?

**Comment by Maijin** [comment]
@jjdredd fixed

**Comment by radare** [comment]
??
