### ISSUE TITLE
Bug when removing a comment in Visual mode

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3829]
See the asciinema: http://radare.tv/a/121
* for the binary http://rghost.net/private/7BkfqmT6B/c4e729badf1b540d8bf05b6146ba1755
Just aar -> s str.David_MacKenzie -> Vp -> ";" -> "lol"\n -> ";" ->  "-" -> WTF

**Comment by radare** [comment]
The bug happens when removing a comment on any address containing other meta info. In this case the .string conversion. The bug shhould be reproducible from the shell too, so a testcase is welcome ;)

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t/meta/comments#L16 tested here

**Comment by radare** [comment]
please confirm

**Comment by Maijin** [comment]
Not fixed see the test still broken https://github.com/radare/radare2-regressions/blob/master/t/meta/comments#L16

**Comment by Maijin** [comment]
-            0x004005c4     .string "Hello World" ; len=12
+            0x004005c4     .string "(null)" ; len=0
