### ISSUE TITLE
Implement LUA disassembler/analyzer plugins

### ISSUE THREAD

**Issue by radare** [radare/radare2#3836]
http://www.lua.org/source/5.3/lopcodes.h.html

**Comment by Maijin** [comment]
http://www.lua.org/source/5.3/lopcodes.h.html

**Comment by q6r** [comment]
I'm working on it

**Comment by jjdredd** [comment]
just copypaste sources from lua

**Comment by SoniEx2** [comment]
[It's Lua, not LUA.](https://www.lua.org/about.html#name)

**Comment by jjdredd** [comment]
true, but who cares
