### ISSUE TITLE
Analyzing ROMs with breaks in address space/virtual addresses.

### ISSUE THREAD

**Issue by cr1901** [radare/radare2#3837]
I have an old arcade 16kB ROM for a Z80 board that I'm trying to analyze. The first 8kB is at address 0x0, and the remaining 8kB is placed at 0xa000 in the z80 address space. Although this is a raw binary, the use of virtual addresses seems appropriate here, per the r2 manual.

I tried to create the following sections to try to get r2 to recursively analyze functions, which use addresses in to 0xa000 region, but are in fact at offset 0x2000 in the ROM image), but to no avail:

```
S 0x2000 0xa000 0x2000 0x2000 left_ROM rx
S 0x0000 0x0000 0x2000 0x2000 right_ROM rx
```

```
[0x00000100]> s 0x2000
[0x00002000]> pdf
/ (fcn) fcn.00002000 3
\           0x00002000    c3a6a1         jp 0xA1A6                      ; fcn.00
000000
[0x00002000]> af @ 0xa1a6
[0x00002000]> f
0x00000000 6 fcn.00000000
0x00002000 3 fcn.00002000
[0x00002000]> af @ 0x21a6
[0x00002000]> f
0x00000000 6 fcn.00000000
0x00002000 3 fcn.00002000
0x000021a6 15 fcn.000021a6
[0x00002000]> pdf @0x21a6
/ (fcn) fcn.000021a6 15
|           0x000021a6    3eff           ld a, 0xFF
|           0x000021a8    322140         ld (0x4021), a
|           0x000021ab    7e             ld a, (hl)
|           0x000021ac    feff           cp 0xFF
|           0x000021ae    c8             ret z
|           0x000021af    23             inc hl
|           0x000021b0    e5             push hl
|           0x000021b1    fe20           cp 0x20
\           0x000021b3    2809           jr z, 0x0B                     ; fcn.00
000000
[0x00002000]> S=
00* 0x00002000 |---------#########| 0x00004000 -r-x left_ROM  008K
01  0x00000000 |##########--------| 0x00002000 -r-x right_ROM  008K
=>  0x00002000 |------------------| 0x00002100
[0x00002000]>
```

I would've expected `af @ 0xa1a6` to correctly seek to 0x21a6 based on the virtual address mapping I gave earlier, but to no avail. My goal is to eventually output a disassembly that can be recompiled into a byte-accurate image; is it possible to get radare2 to automatically recursively analyze functions where the offset in the ROM does not match the address that the CPU "sees"?

**Comment by cr1901** [comment]
Incidentally, the code at 0x2000 in the ROM image is 
```0x00002000    c3a6a1         jp 0xA1A6```

I would've expected `af @ 0xa000` or `af @ 0x2000` to recursive analyze offset 0x21A6, but I found that this behavior doesn't exist; I have to manually recurse. Not sure if this is related or a separate problem.

**Comment by Maijin** [comment]
Just some precision about using virtual adressing:
First you have to activate virtual adressing using `r2 -e -e io.va=true blah`, and use "m" flag when defining a new section:

```
S 0x2000 0xa000 0x2000 0x2000 left_ROM mrx
S 0x0000 0x0000 0x2000 0x2000 right_ROM mrx
```

You can also then use io.sectonly: Only read from sections (if any) .

**Comment by cr1901** [comment]
Okay, that fixed part of the issue. radare2 is still not recursively analyzing functions, but I suspect that's a separate issue. More reports inbound :P.

**Comment by radare** [comment]
use `e anal.calls=true` with af and aa to do that, but you can also use `aac`

**Comment by cr1901** [comment]
I think part of the problem is in this code base, many function "calls" are in fact unconditional jumps (it's not a particularly well-designed z80 ROM, even by 1982 standards). Radare2 seems to want to stop analyzing immediately upon detection of termination of a basic block. Which... makes sense, but makes my life harder XD.

**Comment by radare** [comment]
i would need some testing on that binary, but i guess there are many vars that will help you to get better analysis for your use case. try with anal.hasnext=true for example
