### ISSUE TITLE
Manual RAM address labeling in disassembly

### ISSUE THREAD

**Issue by cr1901** [radare/radare2#3841]
In my raw binary experiment, I have found a function that does some initialization at 0xa34c in z80 address space (0x234c in ROM). From experience, I know that the address 0x4803 and 0x5003 are I/O registers:

```
[0x0000a34c]> pdf
/ (fcn) fcn.0000a34c 22
|           0x0000a34c    3e92           ld a, 0x92
|           0x0000a34e    320348         ld (0x4803), a
|           0x0000a351    3e91           ld a, 0x91
|           0x0000a353    320350         ld (0x5003), a
|           0x0000a356    3e0d           ld a, 0x0D
|           0x0000a358    320348         ld (0x4803), a
|           0x0000a35b    3eff           ld a, 0xFF
|           0x0000a35d    321a40         ld (0x401A), a
|           0x0000a360    3c             inc a
\           0x0000a361    c9             ret
```

I would prefer that all instances of 0x4803 and 0x5003 be replaced w/ user defined symbols. However, adding these flags to the symbol namespace do not appear to be honored during disassembly:

```
[0x0000a34c]> fs symbols
[0x0000a34c]> f ppi0_ctrl @ 0x4803
[0x0000a34c]> f ppi1_ctrl @ 0x5003
[0x0000a34c]> fs
0    2 * symbols
1    0 . sections
2    9 . functions
[0x0000a34c]> pdf
/ (fcn) fcn.0000a34c 22
|           0x0000a34c    3e92           ld a, 0x92
|           0x0000a34e    320348         ld (0x4803), a
|           0x0000a351    3e91           ld a, 0x91
|           0x0000a353    320350         ld (0x5003), a
|           0x0000a356    3e0d           ld a, 0x0D
|           0x0000a358    320348         ld (0x4803), a
|           0x0000a35b    3eff           ld a, 0xFF
|           0x0000a35d    321a40         ld (0x401A), a
|           0x0000a360    3c             inc a
\           0x0000a361    c9             ret
```

I would've expected 0x4803 and 0x5003 to be replaced w/ ppi0_ctrl and ppi1_ctrl strings respectively after adding the relevant symbols.

Is this perhaps an oversight/bug in that radare2 can not yet handle raw binary anaylsis without an object format? Or have I failed to execute the correct set of commands (likely the latter :P)?

**Comment by radare** [comment]
only flags with dots are replaced in the disasembly by the associated numbers. this is to avoid having disassembly like “jmp eax”, when eax=destination, which will be confusing. as long as no disassembler uses the . in the registers or parameters it is used as a restriction to avoid issues.

**Comment by cr1901** [comment]
Okay, very good. Things work :D! "." is actually problematic in some assemblers like nasm, where it's used for local labels.

The idea of this project was to create a disassembly which can be reassembled. However, I'm guessing I can write a Python script to detect labels if necessary and "sanitize" their names.

**Comment by radare** [comment]
Sounds like an interesting project. It will be great if you could make it available in r2pm, but ideally the default output should be correct enough for the available assembler

**Comment by cr1901** [comment]
May even be a blog post about it :). It's just an arcade board I've been fascinated with for a while. I assume trufae/pancake runs the radare acct? I'll idle in #radare should I have more inane q's :P.

**Comment by radare** [comment]
yep. radare and trufae/pancake it’s a single person (me)
