### ISSUE TITLE
Radare2 not honoring symbol deletion/creation on Windows after quit.

### ISSUE THREAD

**Issue by cr1901** [radare/radare2#3842]
Sorry, I suspect filing issues is the only way I'm going to get better at this XD. I am unsure what is a bug vs what I'm doing incorrectly.

I have accidentally created two flags that I want to delete in the `functions` flag namespace. When I try to delete them, radare2 will only delete them until I either quit or dump disassembly to a file (saving the project is okay).

```
[0x00001009]> fs
0    8 . symbols
1    0 . sections
2  351 . functions
3    2 . trampolines
[0x00001009]> f- fcn.0xa34c
[0x00001009]> f- int38h
[0x00001009]> fs
0    8 . symbols
1    0 . sections
2  349 . functions
3    2 . trampolines
[0x00001009]> q
Do you want to save the 'gtsers' project? (Y/n)

F:\Legacy\MAME\gtsers1>radare2 -A -p gtsers
Reloading project
[0x00001009]> fs
0    8 . symbols
1    0 . sections
2  351 . functions
3    2 . trampolines
[0x00001009]>
```

Neither saving during quit nor not passing the "-A" option makes a difference. The two deleted symbols are re-appended to the end of the list. Dumping to a file using `pD 16384 > gtsers.asm` shows that indeed the deleted symbols are still present:

```
/ (fcn) fcn.00001000 3

\ |||||||   0x00001000    c30910         jp tr.1009                     ; fcn.0x1000

  |||||||   0x00001003    c35410         jp tr.1054                     ; fcn.0x1000

  |||||||   0x00001006    c32819         jp fcn.00001928                ; fcn.0x1000

/ (fcn) tr.1009 16

| |||||||   0x00001009    cd1ba0         call fcn.0xa34c 
```

Perhaps related, any new symbols that radare2 finds during an analysis are not added to the list of flags until after I restart. While of course I could be using radare2 wrong (still :P), I can't help but wonder if this is a Windows-related bug.

I am willing to provide my project files and binary upon request.

**Comment by radare** [comment]
first check that windows version is also from git (0.10).

the symbols are loaded from the binary headers. you can remove the associated falgs, but unless you load the project it will be loaded again

**Comment by radare** [comment]
but flags does not modify the binary at all. so you are not removing/creating symbols
