### ISSUE TITLE
Enhance axt output

### ISSUE THREAD

**Issue by radare** [radare/radare2#3843]
Current list is a bit useless because only shows `call XXXX` some suggestions to evaluate:

* show comments
* show function name

proposed patch in cmd_anal.c:

```
char *comment = r_meta_get_string (core->anal, R_META_TYPE_COMMENT, ref->addr);
  if (comment) {
     r_cons_printf ("%c 0x%"PFMT64x" %s ; %s\n", ref->type, ref->addr, buf_asm, comment);
                      free (comment);
       } else {
         r_cons_printf ("%c 0x%"PFMT64x" %s \n", ref->type, ref->addr, buf_asm);
  }
```

**Comment by radare** [comment]
Also, we should add tests for that too

**Comment by Maijin** [comment]
@radare tests already exist for axt, a change will be needed in r2r and it should be ok :)

**Comment by radare** [comment]
@Maijin we should also test that the output contains the comments/fcnnames if available

**Comment by radare** [comment]
Done by @as0ler in https://github.com/radare/radare2/pull/3848
