### ISSUE TITLE
afv on Frame Pointer Optimized functions is still relative to ebp

### ISSUE THREAD

**Issue by RISCYBusiness** [radare/radare2#3844]
I try

>afv esp+0x14 AgeVar int

but it instead creates:

>; var int AgeVar @ ebp-0x14

Is this a bug?

**Comment by Maijin** [comment]
I think this is a duplicate with https://github.com/radare/radare2/issues/3735

**Comment by Maijin** [comment]
yes it's a feature request, closing here
