### ISSUE TITLE
Add command to launch interactive visual graph on current agn/age graph

### ISSUE THREAD

**Issue by radare** [radare/radare2#3846]
Should be done in a subcommand of `agg`

**Comment by radare** [comment]
Same for webui

**Comment by radare** [comment]
@ret2libc ping

**Comment by radare** [comment]
@ret2libc ping

**Comment by ret2libc** [comment]
Sorry for the delay, I'll do it in the first days of the next year

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/3914 the command is `aggi`

**Comment by radare** [comment]
Oh, it's not listed in the help message of `ag?` and there's no `agg?`.

Also, when quitting this `aggi` the cons setup is not restored, so the prompt is lost

**Comment by radare** [comment]
Also, there are some missing ` ` before the `(`

**Comment by radare** [comment]
those fixes are now pushed

**Comment by ret2libc** [comment]
thanks!
