### ISSUE TITLE
Feature-complete folded functions 

### ISSUE THREAD

**Issue by radare** [radare/radare2#3849]
- [x] wrong pdf, shows more bytes if the function is folded
- [x] Problem with the graph:

![image](https://cloud.githubusercontent.com/assets/1408600/11798344/43826710-a2ca-11e5-9fb2-cba22c71a8a5.png)
- [x] comments at function address are now shown
- [x] show _all_ comments in folded function

**Comment by radare** [comment]
@ret2libc wanna check this too? @Maijin we need tests ^^

**Comment by Maijin** [comment]
Added two tests https://github.com/radare/radare2-regressions/commit/062a3c64f046b19dbb226fe0a9064d6f706d0d3d

For the "comments at function address are now shown" I've tried: 
```
wx 6a004889e5c3
af test
afF
CCu this @ fcn.test
pd 1 @ fcn.test
```

Doesn't work

**Comment by radare** [comment]
e asm.cmtright=0

**Comment by Maijin** [comment]
Could be nice to have it next to the function as well with e asm.cmtright=1 at some point

**Comment by Maijin** [comment]
Regression on the VVz :(

**Comment by radare** [comment]
Please be less specific.

**Comment by Maijin** [comment]
The function doesn't fold in graph mode anymore

**Comment by radare** [comment]
Did it worked at some point? I never used that "feature". Who did that?

**Comment by Maijin** [comment]
iirc you :D

**Comment by radare** [comment]
this issue is fixed now that we have a command to list all comments in a function
