### ISSUE TITLE
radiff2 -s option Killed without showing results

### ISSUE THREAD

**Issue by giomismo** [radare/radare2#3861]
I'm testing "-s" flag in radiff2 but the process is always killed by something, no output just "Killed" message.
You can test it running "radiff2 -s /bin/ls /bin/ls".

**Comment by jjdredd** [comment]
on what commit? arch/platform?

**Comment by giomismo** [comment]
I have just installed r2 a few minutes ago from git, at Ubuntu 14 x64.

Performing some checks, the issue seems to happen due to memory exhaustion (2GB RAM + 16GB Swap on a Digital Ocean machine).

**Comment by zonkzonk** [comment]
@jjdredd I can confirm on ubuntu 15.10 x86_64, OOM

**Comment by giomismo** [comment]
The "-s" may should check if it has enough free RAM/Swap to perform the diffing, or maybe add another algorithm to perform a similar diffing operation.

**Comment by zonkzonk** [comment]
not sure if this helps:

https://gist.github.com/zonkzonk/096c4ae521393b53423a

there is still teh OOM problem

**Comment by VisualPrankDude** [comment]
in radiff2, why do we free(bufa) when checking for bufb?, also it's missing in the first check for bufa!

**Comment by alvarofe** [comment]
@VisualPrankDude it frees bufa to avoid a memory leak. if you can't open file2 you have to free the space reserved in `bufa = (ut8*)r_file_slurp (file, &sza);` 

bufa is checked above 

```
bufa = (ut8*)r_file_slurp (file, &sza);
	if (!bufa) {
		eprintf ("radiff2: Cannot open %s\n", r_str_get (file));
		return 1;
	}
```

I just checked and yes, it takes around 4GB of memory.

**Comment by radare** [comment]
ALso, bear in minda that -s takes a LOT of memory because it needs to compare every single pattern of one file with the deltified offset in the second. I guess your distro is debian-based which comes with really retarded defaults about memory limits and kills the process too early, so r2 cant catch that at time to show any error

**Comment by radare** [comment]
no memleaks so far acording to valgrind
```
$ valgrind radiff2 -s /bin/true /bin/false 
==4103== Memcheck, a memory error detector
==4103== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==4103== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==4103== Command: radiff2 -s /bin/true /bin/false
==4103== 
similarity: 0.97
distance: 748
==4103== 
==4103== HEAP SUMMARY:
==4103==     in use at exit: 0 bytes in 0 blocks
==4103==   total heap usage: 26,864 allocs, 26,864 frees, 2,885,463,491 bytes allocated
==4103== 
==4103== All heap blocks were freed -- no leaks are possible
==4103== 
==4103== For counts of detected and suppressed errors, rerun with: -v
==4103== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by zonkzonk** [comment]
@radare the diff was against the _same_ binary

**Comment by radare** [comment]
Please confirm

**Comment by zonkzonk** [comment]
~$  radiff2 -s /bin/true /bin/true
similarity: 1.00
distance: 0
~ $ date
Fri Jan 15 16:27:47 CET 2016

**Comment by giomismo** [comment]
Nice, now it is fixed and does not crashes some of my systems due to memory exhaustion. However, if possible and if does not requieres too much effort, I would suggest to check if it is possible to perform the diffing by checking the memory consumption of the operation against the free memory space (instead of aborting the operation if it requieres 512 MB of memory or more). 

Thank you very much for your efforts.

**Comment by radare** [comment]
The problem is that kernel kills the app when its too memconsuming and theres no way r2 can know that limit. The -s diff is really mem consuming and it can be optimized by swaping to disk, but this is something kernels already do.. So im not sure about a proper solution to this.

We can precalculate the memory required and show a warning or just avoid running if the amount is insane.
