### ISSUE TITLE
Seek Line

### ISSUE THREAD

**Issue by radare** [radare/radare2#3866]
* [ ] Add sl subcommand to deinitialize/free line cache
* [ ] Make `prl` output use the line cache information to make linenum make sense
* [ ] Show absolute or relative line numbers?
* [ ] Add tests

**Comment by zlowram** [comment]
I will implement those enhances. In fact, I've already implemented the subcommand 'slc' and help 'sl?'.

I would use absolute line numbers, as it will allow to use the absolute 'sl' command easily. It is like having relative line numbers at vim: useless to my point of view.

**Comment by radare** [comment]
Please send a pR with that `slc` and `sl?` things. Yep if there's sl info cache it makes sense to use absolute lines. Maybe we can just prefix with + the line numbers that are shown in relative just to avoid the confusion in `prl`

**Comment by radare** [comment]
@zlowram status?

**Comment by zlowram** [comment]
This last PR should close this issue :)
