### ISSUE TITLE
Install radre2 on Windows by using Cygwin.

### ISSUE THREAD

**Issue by Anon2016** [radare/radare2#3868]
Hi,
I'm trying build radare2 on Windows by using Cygwin, but during building programm I encountered with problem: 
x86_64-mingw32/bin/ld: cannot find -lr_fs.
collect2: error ld returned 1 exit status.
recipe for target 'libr_core.dll' failed.
Anybody met with this problem?

**Comment by XVilka** [comment]
What you use to build radare2?
```
./configure ; make  ; make w32dist
```

**Comment by Anon2016** [comment]
In Ubuntu:
1) git clone https://github.com/radare/radare2
2) ./configure --with-compiler=x86_64-w64-mingw32-gcc --with-ostype=windows --host=x86_64-unknown-windows --without-magic --without-ssl
After that I copy radare2 folder on Windows with Cygwin and use make. Error appeared in this step.

**Comment by XVilka** [comment]
Don't do that please
Just run configure without arguments on windows cygwin itself.

**Comment by Anon2016** [comment]
Thanks! Now it's builded!
Tell me please, how I can install blackfin's disassembler from radare2-extras? In ubuntu I can do this like: "r2pm -i blackfin", but in Windows I can't find r2pm.

**Comment by XVilka** [comment]
just run commands from this script as well: https://github.com/radare/radare2/blob/master/binr/r2pm/d/blackfin

**Comment by mohamed-omara39** [comment]
Hi I was trying to install radare2 using cygwin on windows but I get this error 

ar: creating libsdb.

OSTYPE: cygwin_nt-10.0-19045
ERROR: Unknown platform
