### ISSUE TITLE
[zzuf] f.str

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#3870]
morrn,

```
Core was generated by `r2 -qc /R/ AAAAA; aar; pds; f str.NULL; pxd 8 -d ./a.out.bak'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___libc_free (mem=0x6972617009300934) at malloc.c:2933
2933	malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_free (mem=0x6972617009300934) at malloc.c:2933
#1  0x00007f3afb50b96c in r_bin_dwarf_free_attr_value (val=0x55d0d98742c0) at dwarf.c:971
#2  0x00007f3afb50b9b2 in r_bin_dwarf_free_die (die=0x55d0d9860118) at dwarf.c:983
#3  0x00007f3afb50ba1c in r_bin_dwarf_free_comp_unit (cu=0x55d0d985ff10) at dwarf.c:993
#4  0x00007f3afb50ba85 in r_bin_dwarf_free_debug_info (inf=0x7fffc74de250) at dwarf.c:1004
#5  0x00007f3afb50d0a1 in r_bin_dwarf_parse_info_raw (s=0x55d0d9843bd0, da=0x55d0d9873e20, obuf=0x55d0d9833610 ",", len=48, debug_str=0x55d0d985fe60 "long long inT", debug_str_len=168, mode=2) at dwarf.c:1374
#6  0x00007f3afb50d612 in r_bin_dwarf_parse_info (da=0x55d0d9873e20, a=0x55d0d97e30a0, mode=2) at dwarf.c:1486
#7  0x00007f3afc0f5e81 in bin_dwarf (core=0x55d0d858e5c0 <r>, mode=2) at bin.c:544
#8  0x00007f3afc0fb096 in r_core_bin_info (core=0x55d0d858e5c0 <r>, action=20479, mode=2, va=1, filter=0x0, chksum=0x0) at bin.c:1855
#9  0x00007f3afc0f3f6b in r_core_bin_set_env (r=0x55d0d858e5c0 <r>, binfile=0x55d0d983ddd0) at bin.c:106
#10 0x00007f3afc0d49dd in r_core_file_do_load_for_debug (r=0x55d0d858e5c0 <r>, baseaddr=4194304, filenameuri=0x55d0d9840416 "./a.out.bak") at file.c:351
#11 0x00007f3afc0d507d in r_core_bin_load (r=0x55d0d858e5c0 <r>, filenameuri=0x55d0d9840416 "./a.out.bak", baddr=4194304) at file.c:462
#12 0x000055d0d838ab31 in main (argc=5, argv=0x7fffc74ded08, envp=0x7fffc74ded38) at radare2.c:579
(gdb) i r
rax            0x0	0
rbx            0x55d0d97e30a0	94355490484384
rcx            0x7f3af851ec08	139891250949128
rdx            0xfffffffffff68ca7	-619353
rsi            0xffffffff	4294967295
rdi            0x6972617009300934	7598242655145822516
rbp            0x7fffc74de150	0x7fffc74de150
rsp            0x7fffc74de0f0	0x7fffc74de0f0
r8             0x55d0d9826e20	94355490762272
r9             0x0	0
r10            0x4	4
r11            0x55d0d9874190	94355491078544
r12            0x55d0d83890d0	94355469144272
r13            0x7fffc74ded00	140736537160960
r14            0x0	0
r15            0x0	0
rip            0x7f3af81de872	0x7f3af81de872 <__GI___libc_free+34>
eflags         0x10202	[ IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

Greetings
--zlul

radare2 0.10.0-git 9996 @ linux-little-x86-64 git.0.9.9-1879-g36b6a48
commit: 36b6a48444869a249a06df72b62059a13e9f7115 build: 2015-12-22

![a out](https://cloud.githubusercontent.com/assets/5694980/11961325/1255c2cc-a8d8-11e5-961d-eb301a5660f2.png)

**Comment by radare** [comment]
i have pushed a blind fix, the bug is in the dwarf parser, probably a doublefree, but i cant reproduce,  mainly because i dont have that a.out file and maybe you can just show the ASAN or the valgrind output to understand better the problem

**Comment by zonkzonk** [comment]
running valgrind/zzuf again

**Comment by zonkzonk** [comment]
Can't reproduce in 
radare2 0.10.0-git 10011 @ linux-little-x86-64 git.0.9.9-1903-g6f5f32b
commit: 6f5f32bb17fb5233e9fbadb120672faca6656c8c build: 2015-12-29!


valgrind out:
==14010== Memcheck, a memory error detector
==14010== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==14010== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==14010== Command: r2 -qc /R/\ AAAAA;\ aar;\ pds;\ f\ str.NULL;\ pxd\ 8 -d ./a.out.bak
==14010== Parent PID: 10894
==14010== 
==14010== Conditional jump or move depends on uninitialised value(s)
==14010==    at 0x612C49D: readModRM (X86DisassemblerDecoder.c:1581)
==14010==    by 0x612B750: getIDWithAttrMask (X86DisassemblerDecoder.c:1100)
==14010==    by 0x612BC10: getID (X86DisassemblerDecoder.c:1266)
==14010==    by 0x612DCD3: decodeInstruction (X86DisassemblerDecoder.c:2346)
==14010==    by 0x611370E: X86_getInstruction (X86Disassembler.c:940)
==14010==    by 0x60179F0: cs_disasm (cs.c:600)
==14010==    by 0x5FDCD3C: analop (anal_x86_cs.c:239)
==14010==    by 0x5FF1169: r_anal_op (op.c:65)
==14010==    by 0x4EBC1D5: r_core_search_rop (cmd_search.c:1032)
==14010==    by 0x4EBEA9A: cmd_search (cmd_search.c:1744)
==14010==    by 0x4EF7F90: r_cmd_call (cmd_api.c:210)
==14010==    by 0x4EC685D: r_core_cmd_subst_i (cmd.c:1702)
==14010== 
==14010== Conditional jump or move depends on uninitialised value(s)
==14010==    at 0x612A0D5: isPrefixAtLocation (X86DisassemblerDecoder.c:442)
==14010==    by 0x612BB34: getID (X86DisassemblerDecoder.c:1244)
==14010==    by 0x612DCD3: decodeInstruction (X86DisassemblerDecoder.c:2346)
==14010==    by 0x611370E: X86_getInstruction (X86Disassembler.c:940)
==14010==    by 0x60179F0: cs_disasm (cs.c:600)
==14010==    by 0x5FDCD3C: analop (anal_x86_cs.c:239)
==14010==    by 0x5FF1169: r_anal_op (op.c:65)
==14010==    by 0x4EBC1D5: r_core_search_rop (cmd_search.c:1032)
==14010==    by 0x4EBEA9A: cmd_search (cmd_search.c:1744)
==14010==    by 0x4EF7F90: r_cmd_call (cmd_api.c:210)
==14010==    by 0x4EC685D: r_core_cmd_subst_i (cmd.c:1702)
==14010==    by 0x4EC46B3: r_core_cmd_subst (cmd.c:1164)
==14010==

**Comment by radare** [comment]
Thanks!
