### ISSUE TITLE
radare2 doesn't detect "noreturn"

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3874]
calls to exit() and friends should be classified as "noreturn" and not continue in the cfg.

example:

![image](http://imgur.com/FpPpl1W.png)

the call to sym._exit should not continue.

**Comment by Maijin** [comment]
| an[an-] [...]     manage no-return addresses/symbols/functions

The info should be stored in https://github.com/radare/radare2/tree/master/libr/anal/d imho (#3655)

**Comment by radare** [comment]
you have to register that import as a noreturn. write some more tests...

and the thing is... sym._exit?? shouldnt be sym.imp.exit?

**Comment by Maijin** [comment]
http://stackoverflow.com/questions/5422831/what-is-the-difference-between-using-exit-exit-in-a-conventional-linux-fo

**Comment by Maijin** [comment]
<img width="1471" alt="screen shot 2016-06-18 at 22 22 31" src="https://cloud.githubusercontent.com/assets/1408600/16173497/2dd907d6-35a3-11e6-946f-e61d2da0e081.png">

```
│           0x0040201d      ff1523204000   call dword [sym.imp.kernel32.dll_ExitProcess] ; sym.imp.kernel32.dll_ExitProcess
```

too

**Comment by radare** [comment]
R2 cant detect norerurn because it needs to have a predefined list of noreturn import names, which is already done. If you have those symnames just add them in a PR

**Comment by Maijin** [comment]
Added
```
        r_anal_noreturn_add (core->anal, "abort", UT64_MAX);
        r_anal_noreturn_add (core->anal, "sym.exit", UT64_MAX);
        r_anal_noreturn_add (core->anal, "sym.imp.__libc_init", UT64_MAX); /* mips */
-
+       r_anal_noreturn_add (core->anal, "sym.imp.kernel32.dll_ExitProcess", UT64_MAX);
```

Doesn't solve anything
