### ISSUE TITLE
adding comments in graph mode

### ISSUE THREAD

**Issue by Crx77** [radare/radare2#3877]
It would be great if you could add a comment directly to a specific line in one of the graph nodes, directly from graph mode.

**Comment by radare** [comment]
:CC yourcomment
Dunno if ; is handled too

**Comment by Maijin** [comment]
`;` is currently used for toggling `asm.comments` so no.

**Comment by radare** [comment]
The. I vote for , to toggle and ; to add a comment. Ok?

**Comment by Maijin** [comment]
`,` is already used for `setting a comment file`

**Comment by XVilka** [comment]
What about using `'` or `"` for toggling?

**Comment by radare** [comment]
Lgtm

**Comment by ret2libc** [comment]
The main problem here is not the key but the fact that you need a cursor inside the graph node and that isn't supported right now
