### ISSUE TITLE
Section renaming not persistent across project sessions

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#3898]
Renaming program sections using `Sr <new_name>` is not persistent across project sessions. In fact, instead of having a single section with the `new_name`, two sections will be loaded upon reloading the project (one with the old name, one with `new_name`).

Steps to reproduce:
* `radare2 -p ls_test /usr/bin/ls` (open `ls` and create an r2 project for it)
    * `s 0x00400000` (jump to offset 0x00400000)
    * `S.` (prints "LOAD0" for me)
    * `Sr stuff`
    * `S.` (prints "stuff")
    * `q` (and save the project)
* `radare2 -p ls_test` (reload the project)
    * `S.` (show current section)
    * `S` (show all sections)

Expected output: `S.` should print the new section name, and `S` should properly list the sections with `LOAD0` replaced with the new section name.

Observed output: `S.` prints the old section name, and `S` shows the "old" output and an additional section identical to the old section but with the new name.

**Comment by radare** [comment]
Section renamings are not persistent in the target binary. But i agree that they should be saved and restored from the project. Will look at it

Thanks

**Comment by neobrain** [comment]
Nice, thanks! :)
