### ISSUE TITLE
Add a way to redirect debugee's IO.

### ISSUE THREAD

**Issue by akrasuski1** [radare/radare2#3908]
I've been trying for a while to make radare2 run a binary with debugee's IO redirected. Note: `radare2 rarun2 binary stdio=whatever` is not a solution, since radare2 will disassemble rarun2 instead of my binary. I tried also hot-swapping file descriptors, as described here: http://etbe.coker.com.au/2008/02/27/redirecting-output-from-a-running-process/, but it seems gdb won't do it, since process is already being debugged by radare2. Is there any other way to do this? If not, I'd be happy to see this implemented in radare2 code.

**Comment by crowell** [comment]
Try something like this

r2 -de dbg.profile=profile.rr2 binary

Where profile.rr2 is like this

#!/usr/bin/rarun2
program=./binary
stdin=./pattern.txt
stdout=./other.txt

**Comment by akrasuski1** [comment]
Well, what I actually needed was ability to redirect stdio to a pipe or something like that - file has static contents. However, thanks to your hint I found rarun2's option to `connect`. Still, it doesn't seem to work correctly (or I'm using it wrong...). Reproducing:

In one terminal:
```
$ while true; do nc -lv 9999; done
```
In another:
```
$cat test.cpp
#include <cstdio>

int main(){
	char buff[10];
	scanf("%s",buff);
	printf("Scanned: %s\n",buff);
}
$ g++ test.cpp
$ cat prof
program=./a.out
connect=localhost:9999
```
Scenarios:
1. Now, if you type simply `r2 -d ./a.out` (no redirection), then `dc` (debug-continue), then `Ctrl-C` to temporarily stop the debugged program, then `dc` again, then type `asd`, you'll get `Scanned: asd` in radare2. Just as expected.

2. Run radare2 with redirection: `r2 -de dbg.profile=prof ./a.out`, type `dc`, `Ctrl-C`, `dc`. The first terminal (the one with netcat open), will show string, that base64-encoded is: `U2Nhbm5lZDogYAZACg==` - this translates to: ```Scanned: `x@```, with `x` being actually character with ASCII code 6, or ACK.

Why are those two scenarios behaving differently?

**Comment by radare** [comment]
When you press ^c the input function breaks the pipe and does not reads more from stdin. The other case just uses the nc -l as stdin/stdout

**Comment by akrasuski1** [comment]
Is there a way then to have ability to *temporarily* cancel input, like in first scenario, but with connecting via sockets?

**Comment by radare** [comment]
Send a signal to the process using kill

**Comment by akrasuski1** [comment]
Sending SIGINT to radare2 itself has no visible effect at all, so I assume you meant signalling the debugee. This however does not work either:

Scenario 3:
Type: `dc`, then in another terminal type: `kill -2 19116`. Radare2 will return to prompt and say something like: `Debugging pid = 19116, tid = 1 now`. If you type `dc` again though, the effect will be the same as in scenario 2, i.e. process finishes although no input was supplied.

**Comment by radare** [comment]
^C sends a SIGINT to the target process. you should not send a signal to r2 at all.

**Comment by akrasuski1** [comment]
Yeah, I just checked it for completion. Scenario 3 documents how I sent signal to target process.

**Comment by radare** [comment]
You were asking for skipping process input and that's what you get, so I guess I missed something... what do are you trying to achieve?

**Comment by akrasuski1** [comment]
*Temporarily*. I want to have behaviour as in scenario 1, which allows me to type input later, after second `dc`.

**Comment by radare** [comment]
then just provide the input from the contents of a file or a plain string in the rarun2 profile, no need to forward anything to the network or another terminal for that

**Comment by akrasuski1** [comment]
But this is not what I want. Plain string is hard-coded and has to be known before running binary, and the file solution, as far as I know, has the same problem. I want to input the string to the program while it's running.

**Comment by radare** [comment]
you can also instruct rarun2 to use a program as stdin provider. so just write a program that write the stuff you want to stdout and this will be fed to the program stdin, isnt this more deterministic than just using human console/network interaction for each run?

**Comment by akrasuski1** [comment]
This does not solve my problem - I repeat, I want to be able to somehow break the `dc` command in radare2, while still maintaining possibility to enter input later. Sample use: I want to input string that lies somewhere on stack during the read syscall, so I need to `dc`, NOW somehow break out of this blocking `dc`, then `x @ esp` to read the stack, then `dc` to type input for real. Technically this could be solved by putting a breakpoint before each syscall, but it's not always feasible - for example if the binary reads input byte at once.

**Comment by radare** [comment]
i dont think you can do this even with gdb/lldb. you should be using a runtime debugger like Frida to achieve this, because otherwise, the code you are using to read the input doesnt handles interruptions, signals or broken pipes at all.

**Comment by akrasuski1** [comment]
Well, I believe I can. Proof (using same program as before):

Terminal 1:
```
$ mkfifo f
$ cat > f
```
Terminal 2:
```
$ gdb a.out
gdb-peda$ r < f
Starting program: /home/adam/Downloads/a.out < f
^C
Program received signal SIGINT, Interrupt.
gdb-peda$ c
Continuing.
```
Now, if I type something in terminal 1, for example "test" and press Enter, terminal 2 will show:
```
Scanned: test
[Inferior 1 (process 16211) exited normally]
Warning: not running or target is remote
gdb-peda$ 
```
And this is exactly what functionality I want from radare.

**Comment by Maijin** [comment]
@radare ping?

**Comment by radare** [comment]
Im afk for a week. But this can be done with rarun2 as specified in the first comments and also at runtime with the dd command to change the filedescriptors

**Comment by radare** [comment]
Just allocate a new pty and talk to it

**Comment by Maijin** [comment]
@akrasuski1 ping

**Comment by akrasuski1** [comment]
I'll look into it when I have some time.

**Comment by Maijin** [comment]
Then reopen the issue when time comes.
