### ISSUE TITLE
Question pf and pointer

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3918]
In the pf help "|  p       pointer reference (2, 4 or 8 bytes) but how can i choose that because [4] will consider 4 pointers ?

**Comment by radare** [comment]
i think its just obeying asm.bits for that. like this:

``` pf 2p @b:32```

**Comment by Maijin** [comment]
There should have a syntax, a way to add somehow the information in a pf template because for example when you open with `pfo` some templates you expect them to work whatever is the asm.bits

**Comment by Hyask** [comment]
`pf p2xp4xp8` could be a pointer of size 2, an hex, a ptr of size 4, an hex, and a ptr of size 8?

**Comment by radare** [comment]
Do we have tests for this?

**Comment by Hyask** [comment]
Not yet, I'll do some

The patch is coming

**Comment by radare** [comment]
Embrace yourself

**Comment by radare** [comment]
this is fixed now

**Comment by Maijin** [comment]
Yep, awesome :+1:
