### ISSUE TITLE
rasm2 fails to assemble the `neg` instruction

### ISSUE THREAD

**Issue by ibabushkin** [radare/radare2#3920]
On a fully updated Arch Linux system, running
```sh
$ rasm2 -b 64 -a x86 "neg rbx"
Unknown opcode (neg)
Unknown opcode (neg)
Unknown opcode (neg)
Cannot assemble 'neg rbx' at line 3
invalid
```
returns an error.

However, 
```sh
$ rasm2 -b 64 -a x86 -d 48f7db  
neg rbx
```
works just fine.

```sh
$ rasm2 -v
rasm2 0.9.9 9999999 @ linux-little-x86-64 git.0.9.9
commit: HEAD build: 2015-06-05
```

Maybe this is an error on my side, in which case I apologize for the hassle.

**Comment by jjdredd** [comment]
you ought to try different asm plugins.

**Comment by Maijin** [comment]
commit: HEAD build: 2015-06-05 <- ? Always Use the radare2 from the git !
You can then use `rasm2 -b 64 -a x86.as "neg rbx"`

**Comment by ibabushkin** [comment]
Using the newest version from git and the command provided by @Maijin , it works now. However, the problem as described originally persists (although I know how to work around it now).

Thank you for your time.

**Comment by radare** [comment]
Its very easy to implement this opcode. Will do after eating some food

**Comment by radare** [comment]
This was already supported by x86.olly on 32bit. It will be good to add it too for the x86.tab
