### ISSUE TITLE
[Feature] Compact view of nops

### ISSUE THREAD

**Issue by pagabuc** [radare/radare2#3921]
Hello radare2!
While injecting a lot of NOP inside a binary, i thought it could be nice to compact them in a single nop when printing. So for example, instead of printing:
```
0x000000 xor eax, eax
0x000001 nop
0x000002 nop
0x000003 nop
0x000004 xor ebx, ebx
```
radare could print:
```
0x000000 xor eax, eax
0x000001 nop
0x000004 xor ebx, ebx
```
If someone can give me a hint where i can start from, i think i can implement this feature!

**Comment by pagabuc** [comment]
And of course i would like radare to do this automagically, without using 'ahs' ;-)

**Comment by radare** [comment]
it will be interesting to also do that for any other instruction, halts, traps.. but this can be problematic in different situations, the idea looks good and its damn easy to implement, just want to discuss those points:

* non-nop instructions can change the meaning of the disasm
* we should add a comment about how many instructions have been collapsed
* repeated instructions for \x00\x00 or \xff\xff can result in infinite or chopped disasm when reaching EOF or OOB

**Comment by pagabuc** [comment]
Ok, maybe we can start just with x86 nops and see how it looks?

**Comment by ret2libc** [comment]
@radare where do you think such a feature should be implemented? after 'aaa'?

**Comment by radare** [comment]
nope. just an `asm.nodup` option that should be used in disasm.c to check if cur instruction is the same as previous to loop until its idfferent and show the counter of repeated instructions. this can be done without previous analysis.

**Comment by radare** [comment]
we can also collapse them by emiting ahs commands after analysis…

**Comment by ret2libc** [comment]
yes i was thinking about using ahs command after analysis so that we don't have to reimplement anything.

**Comment by radare** [comment]
Check it out :)

**Comment by radare** [comment]
pull and try again :)
