### ISSUE TITLE
ESIL ARM CMP incorrect

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#3924]
While emulating in ESIL, ARM cmps do not update the cpsr register. I believe this is why branches afterward fail.

cmp r1, #0x10 
beq 0x1234

will not branch whether r1 is 0x10 or not. The zero flag is not set from the comparison. The beq ESIL instruction clearly asks whether zf is 0. It always is.

**Comment by radare** [comment]
Can you write a test case for this case in the radare2-regressions repo?

**Comment by radare** [comment]
I have updated the regprofiles for the dbg.linux-arm and anal.arm_cs plugins to provide better CPSR information and more bitsized registers to access them directly.

The ESIL for those instructions should be updated to use them

**Comment by radare** [comment]
for the record:
```
CPSR
====


0-4: mode bits
5: T Thumb state
6: F FIQ
7: I IRQ
8: A Imprecise Abort Disable bit
9: Endianness

31: N Negative
30: Z Zero
29: C Carry
28: V Overflow
27: Q Sticky overflow

24: Java State bit

http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0344i/ch02s14s08.html
10-15: IT if then . number of instructions that will be skipped
16-19: GE Greater or Equal

```

**Comment by radare** [comment]
Please check if this commit fixes your issue. If so, we should write some tests cases and extend the code to handle all type of conditionals.

**Comment by radare** [comment]
https://github.com/radare/radare2/commit/367e9eec4795259f181d1f7a778000e0400f9e2b

**Comment by ninjahacker** [comment]
This didn't seem to work. I don't have a chance to update regressions right now, but check it out:

https://www.dropbox.com/s/9l73r9zzz1xxrza/arm16-test.bin?dl=0

e asm.arch = arm
e asm.bits = 16
aei 
aer r1 = 0x10
aes
aes
aes

The jump did not happen, nor did cpsr get updated.

**Comment by radare** [comment]
Related to https://github.com/radare/radare2-regressions/pull/302

**Comment by radare** [comment]
isn't this issue fixed now?

**Comment by radare** [comment]
can we have a test?

**Comment by mrmacete** [comment]
I think this issue is fixed, tests are there already: https://github.com/radare/radare2-regressions/blob/master/t.esil/arm-16#L7-L88

i'm closing this
