### ISSUE TITLE
Color "wraps" when line too long.

### ISSUE THREAD

**Issue by akrasuski1** [radare/radare2#3926]
![http://i.imgur.com/QmRBuUw.png](http://i.imgur.com/QmRBuUw.png)
The line would read `stack R W` in blue, but since the terminal line is too short, the blue color "wraps" to the next line, although the register names should be white.

**Comment by radare** [comment]
Can be reproduced with `V]]]]]]]]]`, when the hexdump exceeds the terminal width. A solution would be to prefix every line that exceeds with a `Color_RESET` escape code, but this can be wrong in some cases, so the chop operation must evaluate the escape codes in the trimmed down part.

**Comment by radare** [comment]
@ret2libc any better idea on this?
