### ISSUE TITLE
Add support for 4004 CPU

### ISSUE THREAD

**Issue by radare** [radare/radare2#3933]
https://github.com/iratqq/dis4004/blob/master/dis4004.c

**Comment by radare** [comment]
http://e4004.szyc.org/

**Comment by radare** [comment]
Oh, it was already there :D maybe we can add ESIL and proper analysis
```
$ rasm2 -L | grep 4004
_d__             i4004       LGPL3   Intel 4004 microprocessor
```

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/libr/asm/p/asm_i4004.c

**Comment by radare** [comment]
Done in git :)
