### ISSUE TITLE
Paste from buffer only one symbol

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3936]
In windows version of radare2 paste only one symbol from string in clipboard. On screen I pressed shift+insert and tried to paste string "0x100003570"

![2016-01-10 01-43-54](https://cloud.githubusercontent.com/assets/1186777/12218902/385f4092-b747-11e5-81d3-c7b5e28bf1a0.png)

It was a first symbol ("0") or other("x", "1", ...)

Env:
Windows 7 x64
Radare2 from git
ConEmu

**Comment by radare** [comment]
@skuater will look at it probably a wide-char input issue

**Comment by skuater** [comment]
plz check the last version of r2 and use CTRL + V for doing  "paste" from windows clipboard.
The standalone shitf+ins of cmd.exe dont work , im thinking add support for this.  Feel free of use ^V until this is doned.

**Comment by dukebarman** [comment]
It doesn't work :'( Now insert last symbol and ctrl+V work (Last line is a check ctrl+V for simple input)

![2016-01-11 00-50-01](https://cloud.githubusercontent.com/assets/1186777/12224280/0bcf555c-b806-11e5-9025-d3f76f7d6c5f.png)

**Comment by radare** [comment]
maybe its because of how the path is constructed with / instead of backslash, can you confirm the files exist?

**Comment by radare** [comment]
The copypaste thing is fixed by @skuater

**Comment by skuater** [comment]
Ensure u are using last version of r2 from git and assign another shortut for CTRL + V into ConEmu settings. Tested and work fine under conemu and cmd.exe

**Comment by dukebarman** [comment]
In simple window of `cmd.exe` I cannot insert data. Only first byte

In `cmd.exe` or console of FAR if I set this options:

![image](https://cloud.githubusercontent.com/assets/1186777/16455375/bd275baa-3e1c-11e6-8ab4-75898ec0a316.png)

I can insert data with ctrl+v, but cannot with shift+ins or right click of mouse

**Comment by radare** [comment]
and this is a bug in r2 or in the console?

On 29 June 2016 at 16:18, Anton Kochkov <notifications@github.com> wrote:

> Reopened #3936 <https://github.com/radare/radare2/issues/3936>.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/radare/radare2/issues/3936#event-707821389>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA3-lrBP0ImD7dmAGM0k8aW_xvy_Rl30ks5qQn69gaJpZM4HBx9m>
> .
>



-- 
--pancake

**Comment by dukebarman** [comment]
It's bug in r2 from console (far or cmd)

**Comment by radare** [comment]
cc @skuater

**Comment by skuater** [comment]
no bug, all work correctly, plz configure correctly conemu to bypass the ctrl+v hook.
@dukebarman are showing conemu config gui, cmd.exe dont have the showed screen, under a default cmd.exe u only need to do a ctrl+v to paste text from clipboard.

**Comment by dukebarman** [comment]
`ctrl+v` works in cmd.exe window but `right click and choose insert` not.
