### ISSUE TITLE
Visual Editor preview assembler size

### ISSUE THREAD

**Issue by Ristovski** [radare/radare2#3937]
Having the amount of assembler preview in the **visual editor** be ***relative*** to the window size (terminal size) would be better than a fixed size. 

Sometimes switching features inside the visual editor can be confusing as you do not have enough assembly (Nor can you "scroll" the preview) to see the action of all the options.

**Comment by radare** [comment]
What is the visual editor?

**Comment by Maijin** [comment]
He meant Ve

**Comment by radare** [comment]
Ah .. well, this is just suposed to be a preview, not a fully interactive. i pushed a commit that enlarges the disasm to fill the console

**Comment by radare** [comment]
If you find another anoying things in Ve please report. About scrolling the disasm, you should scroll in the normal disasm view by pressing 'qq' and then type 'e' again to continue changing options
