### ISSUE TITLE
Bad register values when using HTTP and "?"

### ISSUE THREAD

**Issue by akrasuski1** [radare/radare2#3941]
Reading registers behaves differently when using radare2 normally, and when using HTTP interface. Using normal (terminal) interface works fine:
```
$ cat test.c
int main(){return 0;}
$ gcc test.c
$ r2 -d ./a.out
[0x7fb9b4a82cd0]> db main;dc
hit breakpoint at: 4004f6
Debugging pid = 2038, tid = 1 now
[0x004004f6]> dr rip
0x004004f6
[0x004004f6]> ? rip
4195574 0x4004f6 020002366 4M 40000:04f6 4195574 11110110 4195574.0 0.000000f 0.000000
```
This works good, because I'm using radare2 normally. But when I switch to HTTP mode, weird stuff happens:
Terminal 1:
```
$ r2 -d ./a.out
[0x7f8b3d09fcd0]> =h
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/
```
Terminal 2:
```
$ cat proof.py
import requests

requests.get("http://localhost:9090/cmd/db main;dc")
print requests.get("http://localhost:9090/cmd/dr rip").text
print requests.get("http://localhost:9090/cmd/? rip").text
$ python proof.py
0x004004f6

140236001246416 0x7f8b3d09fcd0 03770547502376320 130605.0G b3d09000:0cd0 140236001246416 11010000 140236001246416.0 0.033688f 0.000000
```
As you can see, the register values differ - `dr rip` returns other values than `? rip`.

**Comment by radare** [comment]
Use r2pipe api. Works as expected in my tests

**Comment by akrasuski1** [comment]
Well, I don't know if whatever builtin web interface uses is called r2pipe, but it has the same issue I discuss here, so it should be fixed either way.

**Comment by radare** [comment]
r2pipe is an api for python and many other languages to do what you are aiming with `requests`.

the value of `dr rip` and `? rip` is different because you have to call `.dr*` to update the flags before using the `?` to get the rip flag value

**Comment by akrasuski1** [comment]
Oh, ok, I did not  know about `.dr*`. How does it work that normally you do not have to call it? Is it some kind of automatic command?

**Comment by radare** [comment]
it’s executed because is defined in the cmd.prompt variable, which is set when setting up the debugger mode in r2.

this command is executed everytime the prompt is shown. it is not suposed to be automatic, at least for now.

**Comment by akrasuski1** [comment]
Closing it then.
