### ISSUE TITLE
Make registers sorted by function.

### ISSUE THREAD

**Issue by akrasuski1** [radare/radare2#3945]
It would be aesthetically better if registers printed via `dr` or `drr` command were sorted in alphabetical order, or at least grouped by "function" - r{a,b,c,d}x together, r{10,11,...,15} together and so on. Right now it looks more like:
```
r15 = 0x00000000
r14 = 0x00000000
r13 = 0x7ffddfde0cf0
r12 = 0x00400800
rbp = 0x7ffddfde0c10
rbx = 0x00000000
r11 = 0x00000246
r10 = 0x00000022
r9 = 0x00000000
r8 = 0xffffffff
rax = 0x000000b6
rcx = 0x7f192f092000
rdx = 0x7f192ee6e970
rsi = 0x7f192f092000
rdi = 0x00000001
orax = 0xffffffffffffffff
rip = 0x004013e1
rflags = 0x00000246
rsp = 0x7ffddfde0c00
```

**Comment by radare** [comment]
See https://github.com/radare/radare2/commit/399a1b82c9dde34169ab52390f28ccc2899b82f6

feel free to improve and port to other regprofiles. Let me know if current output looks better, also compare `dr=` output too
