### ISSUE TITLE
Add -d,-w,-b subregisters in x86-64 debugger profiles

### ISSUE THREAD

**Issue by radare** [radare/radare2#3947]
* [x] Darwin x64
* [x] Linux x64
* [x] Anal x64 CS
* [x] Anal x64 Udis https://github.com/radare/radare2/blob/master/libr/anal/p/anal_x86_udis.c
* [ ] netbsd x64
* [ ] windows x64
* [ ] kfbsd x64

```
                 "gpr   r8      .64     72      0\n"
                 "gpr   r8d     .32     72      0\n"
                 "gpr   r8w     .16     72      0\n"
                 "gpr   r8b     .8      72      0\n"

```

**Comment by Maijin** [comment]
Should orax also got this ?

**Comment by radare** [comment]
orax is only used to get the syscall number, so i dont think we need that

**Comment by radare** [comment]
@Maijin add checkboxes and mark the ones pending to be done.

**Comment by radare** [comment]
Nope not needed for orax

**Comment by Maijin** [comment]
Windows register profile syntax is slightly different https://github.com/radare/radare2/blob/master/libr/debug/p/native/reg/windows-x64.h

**Comment by radare** [comment]
👍
