### ISSUE TITLE
Rarun2's program redirection doesn't work. 

### ISSUE THREAD

**Issue by akrasuski1** [radare/radare2#3951]
`dbg.profile`'s stdin field seem to work only with files, not with programs. Consider:

```
$ cat /tmp/prof
#!/usr/bin/rarun2
program=/bin/ls
stdin=!python -c 'print "2"'
$ r2 -d /bin/ls -e dbg.profile=/tmp/prof
Attached debugger to pid = 16782, tid = 16782
Debugging pid = 16782, tid = 16782 now
p/debug_native.c:764 debug_init_maps: /proc: No such file or directory
Using BADDR 0x0
Assuming filepath /bin/ls
bits 64
p/debug_native.c:764 debug_init_maps: /proc: No such file or directory
r_debug_reg: error reading registers
Attached debugger to pid = 16782, tid = 16782
r_debug_reg: error reading registers
r_debug_reg: error reading registers
 -- Experts agree, security holes suck, and we fixed some of them!
r_debug_reg: error reading registers
[0x00000000]> 
```

There are a couple of errors. On the other hand, if I change `/tmp/prof` file to use file as input, it works fine:

```
$ cat /tmp/prof
#!/usr/bin/rarun2
program=/bin/ls
stdin=/tmp/prof
$ r2 -d /bin/ls -e dbg.profile=/tmp/prof
Process with PID 16799 started...
Attached debugger to pid = 16799, tid = 16799
Debugging pid = 16799, tid = 16799 now
Using BADDR 0x400000
Assuming filepath /bin/ls
bits 64
Attached debugger to pid = 16799, tid = 16799
 -- In Soviet Russia, radare2 have documentation.
[0x7efdaf952cd0]>
```

Note that doing this with just `rarun2` works fine in both cases - `rarun2 /tmp/prof` lists files.

**Comment by radare** [comment]
program and its arguments must be the last ones in the commandline, try
with:

```
$ r2 -e dbg.profile=/tmp/prof -d /bin/ls 
```

also, there are several shorter ways to make that stdin thing for example:

```
stdin=2
```

a bit longer:

```
stdin=!echo 2
```

i was a bit scared with that python for just an echo :P

**Comment by akrasuski1** [comment]
```
$ r2 -e dbg.profile=/tmp/prof -d /bin/ls
Attached debugger to pid = 17185, tid = 17185
Debugging pid = 17185, tid = 17185 now
p/debug_native.c:764 debug_init_maps: /proc: No such file or directory
Using BADDR 0x0
Assuming filepath /bin/ls
bits 64
p/debug_native.c:764 debug_init_maps: /proc: No such file or directory
r_debug_reg: error reading registers
Attached debugger to pid = 17185, tid = 17185
r_debug_reg: error reading registers
r_debug_reg: error reading registers
 -- Disassemble in intel syntax with 'e asm.syntax = intel'.
r_debug_reg: error reading registers
[0x00000000]> 
```
Doesn't seem to work either. Also, the short python program was just an example, normally it would be much longer of course ;)

**Comment by radare** [comment]
which version of r2 are you using? last one from git?

do `r2 -d ls` works for you? because it looks like there's not even
/proc in your system? wtf

**Comment by akrasuski1** [comment]
```
r2 -d ls
Process with PID 17224 started...
Attached debugger to pid = 17224, tid = 17224
Debugging pid = 17224, tid = 17224 now
Using BADDR 0x400000
Assuming filepath /bin/ls
bits 64
Attached debugger to pid = 17224, tid = 17224
 -- Switch between print modes using the 'p' and 'P' keys in visual mode
[0x7fbe7c576cd0]>
```
I updated r2 just yesterday, I don't believe anythin important changed since then.

**Comment by akrasuski1** [comment]
https://github.com/radare/radare2/blob/40e08dbd89618643309fd2560e9fc19f88668b7c/libr/debug/p/debug_native.c#L764

This is the place which prints the first error - it lies a bit - it's not the `/proc` that doesn't exist, but the `/proc/PID_OF_PROG/maps` - which makes me believe that pid is wrong.

**Comment by radare** [comment]
Confirmed, this is a regression on linux. im looking at it

**Comment by akrasuski1** [comment]
Fix didn't work, same problem persists.

**Comment by akrasuski1** [comment]
Could you reopen the issue?

**Comment by radare** [comment]
Can anyone reproduce?

**Comment by Maijin** [comment]
```
$ cat /tmp/prof
#!/usr/bin/rarun2
program=/bin/ls
stdin=!echo 2
$ r2 -e dbg.profile=/tmp/prof -d /bin/ls
Attached debugger to pid = 27894, tid = 27894
Debugging pid = 27894, tid = 27894 now
p/debug_native.c:764 Cannot open '/proc/27894/maps': No such file or directory
Using BADDR 0x0
Assuming filepath /bin/ls
bits 64
p/debug_native.c:764 Cannot open '/proc/27894/maps': No such file or directory
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
 -- You can debug a program from the graph view ('ag') using standard radare2 commands
r_debug_reg: error reading registers
^D
Do you want to quit? (Y/n)
Do you want to kill the process? (Y/n)
```

**Comment by radare** [comment]
Echo is not a program

**Comment by radare** [comment]
Welcome to unix

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/3951#issuecomment-171386904

I just followed your instructions....

```
$ cat /tmp/prof 
#!/usr/bin/rarun2
program=/bin/ls
stdin=2
$ r2 -e dbg.profile=/tmp/prof -d /bin/ls
[ERROR] rarun2: Cannot open: 2
Can't config the environment.
Attached debugger to pid = 32718, tid = 32718
Debugging pid = 32718, tid = 32718 now
p/debug_native.c:764 Cannot open '/proc/32718/maps': No such file or directory
Using BADDR 0x0
Assuming filepath /bin/ls
bits 64
p/debug_native.c:764 Cannot open '/proc/32718/maps': No such file or directory
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
 -- Now with more better English!
r_debug_reg: error reading registers
^D
Do you want to quit? (Y/n)
Do you want to kill the process? (Y/n)
```

Same with the first example

```
$ cat /tmp/prof
#!/usr/bin/rarun2
program=/bin/ls
stdin=!python -c 'print "2"'
$ r2 -e dbg.profile=/tmp/prof -d /bin/ls
Attached debugger to pid = 394, tid = 394
Debugging pid = 394, tid = 394 now
p/debug_native.c:764 Cannot open '/proc/394/maps': No such file or directory
Using BADDR 0x0
Assuming filepath /bin/ls
bits 64
p/debug_native.c:764 Cannot open '/proc/394/maps': No such file or directory
r_debug_reg: error reading registers
r_debug_reg: error reading registers
r_debug_reg: error reading registers
 -- No such file or directory.
r_debug_reg: error reading registers
^D
Do you want to quit? (Y/n)
Do you want to kill the process? (Y/n)

```

**Comment by Thaelz** [comment]
Happy Haloween, the dead thread is coming back! (Sorry for that..)
From what i've experienced, the /proc/pid/maps file error is a consequence of the failed stdin input command.
A workaround to get the result of a command as stdin:
`$ cat /tmp/prof`
`#!/usr/bin/rarun2`
`program=/bin/ls`
`stdin=$(python -c 'print "2"')`
Or with a python script:
`stdin=$(python sample.py)`
Then the errors related to the /proc/pid/maps should disappear (and the analysis of sections, entrypoint, etc.. will get expected results) as the stdin argument is correctly interpreted.

**Comment by radare** [comment]
$( is nothing, RTFM

**Comment by Maijin** [comment]
Following your instruction it doesn't work either.

**Comment by Maijin** [comment]
instructionS

**Comment by Diadlo** [comment]
I, think, I found the reason of error: https://github.com/radare/radare2/blob/1.1.0/libr/socket/run.c#L247
Here ends the original process (whose PID has been saved) and continue new one

**Comment by radare** [comment]
Can you send a PR?

**Comment by Diadlo** [comment]
@radare I'm trying to fix the issue, but changing sign `s/==/!=/` provide a regression.

**Comment by radare** [comment]
Can you add a test case for this?

**Comment by Diadlo** [comment]
@radare I will try

**Comment by pragyan1994** [comment]
radare2$: r2 -d ls
Child killed
ptrace: Cannot attach: Invalid argument
Possibly unsigned r2. Please see doc/macos.md
ERRNO: 22 (EINVAL)
[w] Cannot open 'dbg:///bin/ls' for writing.



having this error! How to troubleshoot

**Comment by Maijin** [comment]
Please see doc/macos.md it's written.
