### ISSUE TITLE
Add a Command to add a new entrypoint

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3952]
Command to add a new entrypoint

**Comment by radare** [comment]
I find this useful in rabin2 -O to change the entrypoint of any binary.. but in memory?

**Comment by Maijin** [comment]
The idea is to be able to do fileformat only in scripting with r2pipe, It's already possible to define section, mapping, disassembly engine, but lacks entrypoints.

**Comment by radare** [comment]
What about: `ie=0x840840`. just to change the vaddr (and indirect paddr) in the entrypoint of the loaded RBinObject (in memory)

**Comment by Maijin** [comment]
@radare Is ok to modify but I want to add another one :P. And also what happens when you have multiple entrypoint with this syntax ?

**Comment by radare** [comment]
Can you share an usage example for your needs? I dont see the point of managing entrypoints in memory when statically loading the bin

**Comment by Maijin** [comment]
"be able to manipulate format using only r2pipe ?" There is already the possibility to manipulate Sections without patching the file, , adding the possibility to add entrypoint is another way to avoid using native C to add a fileformat.

**Comment by Maijin** [comment]
I have multiple concrete other case, for example having the possibility to manipulate a VB PE binary, in which an additional header contain another entrypoint that is proper to VB, it would be really cool to define that and I don't necessary have the time to add a complete VB header in C but with pf or script it's quite quick and then using ie I can get its value afterward.

**Comment by radare** [comment]
the `i` command doesnt modifies the binary itself, so you are not modifying the binary. Adding more than one entrypoint in a fileformat that doesnt accepts more than one makes no sense. imho this should go with the sdb and `k` command.

**Comment by Maijin** [comment]
The point is not to modify the binary, just to use ie for displaying entrypoints instead of using k which is completely undocumented and will make the user to type 2 command instead of one to get the same information

**Comment by radare** [comment]
You can manipulate sections, but only io sections, not the binary ones... So maybe you are looking for other ways to do that

**Comment by Maijin** [comment]
No, again, I'm looking to manipulate the section so I can begin analysis,  I am not looking for patching the binary.

**Comment by Maijin** [comment]
```
def VB6(XXXX): 
    VB6Header_offset = XXXX * XXXX + XXXXXX - XXX
    r2.cmd("S 0x00000400 0x00401000 0x00008a00 0x00043000 .text mrwx")
    r2.cmd("S 0x00008e00 0x00444000 0x00002200 0x00003000 .rsrc mrwx")
    r2.cmd("`ie+ `pf.VBHeader.aSubMain @ " + VB6Header_offset+"`" Sub_Main`")
    return r2.cmdj("iej")
def VB5(XXXX): 
    ....
def BLABLA(XXXX):
    ....
    ....
print VB6(XXXX)
r2.cmd("Ps project")
```

**Comment by XVilka** [comment]
@radare, I think @Maijin meant to make 'entrypoint' command detached from the binary. Instead of calling the function to set entrypoint it is possible to make a special command and call it after calculations in r_bin plugins, using r_cmd() functions. So it will make it more flexible - it should allow to:
  - [ ] change entrypoint on the fly
  - [ ] allow to set the entrypoint for 'raw' binaries, so it will be possible to implement file format parser 'on the fly', using only r2 commands or calling them from r2pipe.

What do you think about that?

**Comment by Maijin** [comment]
A command for adding a new main could be nice too (see `im` command)

**Comment by Maijin** [comment]
ok, see META - Rabin2.
