### ISSUE TITLE
cfg.encoding doesn't exist anymore

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3953]
Is mentionned here : https://github.com/radare/radare2/blob/master/libr/search/strings.c#L13
and in the Fortunes.

Maybe this could be used back for https://github.com/radare/radare2/issues/3417 and https://github.com/radare/radare2/issues/414 ?

Or removed from fortunes if useless

**Comment by radare** [comment]
r2 detects utf8, utf16, widechar, cp850 and ascii, no need to specify
the encoding. imho the fortune can be removed

**Comment by radare** [comment]
we can probalby add an option to only accept some specific encodings...

**Comment by radare** [comment]
sorry, cp850 is disabled implictly in code. i guess because of some
false positives
