### ISSUE TITLE
rabin2 -O should obey -r and show r2 commands instead of binpatching

### ISSUE THREAD

**Issue by radare** [radare/radare2#3954]

**Comment by alvarofe** [comment]
you suggest here use -O to sign binaries as ldid does https://github.com/radare/radare2/issues/4069 and using radare commands output is not very feasible in that case i think.

**Comment by radare** [comment]
it is in case the binary already contains that command and we just need to update the hashes. if we need to add a new command and relocate all the segments it will need more work. but it is also possible to do it with r2 commands.

**Comment by radare** [comment]
requires some refactoring that is better to delegate to 0.10.3

**Comment by Maijin** [comment]
Added to META rabin2
