### ISSUE TITLE
DUP is broken

### ISSUE THREAD

**Issue by condret** [radare/radare2#3957]
the current way how dup is implemented in esil pushes the numeric value of a register or internal var twice on the esil-stack, which is not how it should work. Introduced here https://github.com/radare/radare2/commit/05c56ad2f20deb811c6565b59ff43a532cbfc8ee
dup is intended to push the value only once, it is needed for cases where u need the value of a register on the stack that it has at the beginning of an instruction, where you cannot use the register itself, because the register changes in the instruction

**Comment by radare** [comment]
Do we have tests for this?

**Comment by radare** [comment]
We should update the implementations:
```
$ grep -re DUP p/anal_*.c
p/anal_6502.c:			r_strbuf_setf (&op->esil, "%s,a,+=,C,DUP,$c7,C,=,a,+=,$c7,C,|=", addrbuf);
p/anal_6502.c:		else	r_strbuf_setf (&op->esil, "%s,[1],a,+=,C,DUP,$c7,C,=,a,+=,$c7,C,|=", addrbuf);
p/anal_8051.c:		/* mul */ emit("8,A,B,*,DUP,>>,DUP,!,!,OV,=,B,=,A,=,0,C,="); break;
p/anal_arm_cs.c:		r_strbuf_appendf (&op->esil, "DUP,!,SWAP,&,%s,SWAP,cpsr,&,|,cpsr,=",REG(1));
p/anal_avr.c:		else	r_strbuf_setf (&op->esil, "r%d,DUP,r%d,CF,+=,r%d,r%d,+=,$c7,CF,=,$c3,HF,=,$o,VF,=,r%d,r%d,=,$z,ZF,=,r%d,0x80,&,!,!,NF,=,VF,NF,^,SF,=,r%d,=", r, r, r, d, d, d, r);
p/anal_avr.c:		else	r_strbuf_setf (&op->esil, "r%d,DUP,r%d,CF,+=,r%d,r%d,-=,$b8,CF,=,$b3,HF,=,$o,VF,=,r%d,r%d,=,$z,ZF,=,r%d,0x80,&,!,!,NF,=,VF,NF,^,SF,=,r%d,=", r, r, r, d, d, d, r);
p/anal_avr.c:				r_strbuf_setf (&op->esil, "r%d,DUP,0,r%d,=,r%d,-=,$b3,HF,=,$b8,CF,=,CF,!,ZF,=,r%d,0x80,&,!,!,NF,=,r%d,0x80,==,$z,VF,=,NF,VF,^,SF,=", d, d, d, d);	//Hack for accessing internal vars
p/anal_gb.c:				r_strbuf_append (&op->esil, "a,+=,C,DUP,$c7,C,=,$c3,H,=,a,+=,$c7,C,|=,$c3,H,|=,a,a,=,$z,Z,=,0,N,=");
p/anal_gb.c:				r_strbuf_append (&op->esil, "a,-=,C,DUP,$b8,C,=,$b4,H,=,a,-=,$b8,C,|=,$b4,H,|=,a,a,=,$z,Z,=,1,N,=");
p/anal_mips_gnu.c:	// XXX DUPPED CAUSES FAILURE "gpr	at	.32	8	0\n"
p/anal_x86_cs.c:						esilprintf (op, "%s,!,?{,BREAK,},%s,DUP,%s,DUP,"\
p/anal_x86_cs.c:				esilprintf (op, "$z,DUP,zf,=,al,=");
```

**Comment by radare** [comment]
Please verify

**Comment by radare** [comment]
And we need tests for this

**Comment by condret** [comment]
the patch looks ok. do we really need the new DUP?

**Comment by radare** [comment]
Its used in the arm.cs now and maybe we can rewrite the esil expression but all stack based vms have this op, so it doesnt hurts imho

**Comment by condret** [comment]
should it really do what it does now? it just does not only dup the element on the stack it nums it too.

currently  ```eax,DUP``` performs equal to ```eax,NUM,eax,NUM``` , maybe it is more reasonable to let it perform like ```eax,eax,NUM```

**Comment by radare** [comment]
Yes i know i added a comment in the code to discuss this. What do u think?

**Comment by condret** [comment]
i think it should behave like ```eax,eax,NUM``` if we keep DUP alive, i currently see no reason for this, because, u can actually write ```eax,eax,NUM```, and DUP does not make it significantly shorter

**Comment by condret** [comment]
i think, that dup might be useful, in cases where u need need to set a very custom flag on a weird architectur that is not covered by internal vars. see #3975

**Comment by radare** [comment]
👍

**Comment by condret** [comment]
can we close this?

**Comment by radare** [comment]
yes!
