### ISSUE TITLE
dll sdb are case sensitive

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3962]
In one sample I got this error : 
```
Cannot find /usr/share/radare2/0.10.0-git/format/dll/ws2_32.sdb
Cannot find /usr/share/radare2/0.10.0-git/format/dll/ws2_32.sdb
Cannot find /usr/share/radare2/0.10.0-git/format/dll/ws2_32.sdb
Cannot find /usr/share/radare2/0.10.0-git/format/dll/ws2_32.sdb
```

Actually the file exist but is named `WS2_32.sdb`

**Comment by radare** [comment]
Just rename it. This is not a problem for osx or windows

**Comment by Maijin** [comment]
If I rename it, it will not work if I got an import like `WS2_32.dll_Ordinal_21`.

**Comment by Maijin** [comment]
Same problem after adding all those missing stuff

```
Cannot find /usr/share/radare2/0.10.0-git/format/dll/uxTheme
Cannot find /usr/share/radare2/0.10.0-git/format/dll/UXTheme
Cannot find /usr/share/radare2/0.10.0-git/format/dll/UxTheme 
```

**Comment by radare** [comment]
I suggested to lowercase the dllname before constructing the path

**Comment by Maijin** [comment]
it will not work in those case then:
Cannot find /usr/share/radare2/0.10.0-git/format/dll/uxTheme
Cannot find /usr/share/radare2/0.10.0-git/format/dll/UXTheme
Cannot find /usr/share/radare2/0.10.0-git/format/dll/UxTheme 
Cannot find /usr/share/radare2/0.10.0-git/format/dll/UXTHEME

What's the point ?

**Comment by radare** [comment]
It will work because all those sdb will be lowecased for sanity
