### ISSUE TITLE
to - and Sandbox

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#3963]
Hi.

r2 -c "to -" -S /bin/cat gives $EDITOR instead of "system call disabled etc."

Greetings
VP

r2 -v
dec50ae9d445de27a1ddc2e48969e04f301ca66c

**Comment by Maijin** [comment]
* https://github.com/radare/radare2/commit/ebed8e45f1368e0ea1ac7f5f92891c4c18d9ce75 fix the to when you use it with command line but doesn't fix this specific issue

**Comment by Maijin** [comment]
Same also with `r2 -c "ls" -S /bin/ls`

**Comment by Maijin** [comment]
For me this is not a bug for the usage of sandbox I would have.
ping @radare ?

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/12403093/c5dcbd6e-be31-11e5-8506-adf56052f8e4.png)

**Comment by radare** [comment]
In the stary line, everything is run before the sandbox is set. In order to configure the sandbox
