### ISSUE TITLE
Problem with compiling examples from radare2book (error in ragg2)

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3964]
Example :

```
$ cat hi.c
main() {
     write(1, "Hello0, 6);
     exit(0);
   }
$ ragg2 hi.c
WARNING: No room in the static stackframe! (0 must be 5)
e8fbffffff6a06c7852000000048656c6cc785240000006f000000c7852800000000000000488d452048894518ff75186a01e8c9ffffff4883c4186a00e8beffffff4883c408c3
```

./hi - https://dl.dropboxusercontent.com/u/10688770/hi

PS: I have updated the issue to keep only the faulty remaining issue

**Comment by zonkzonk** [comment]
@Maijin can you give the binary please ?

**Comment by dukebarman** [comment]
./hi - https://dl.dropboxusercontent.com/u/10688770/hi

**Comment by Maijin** [comment]
@dukebarman will update, but the man has got it correct for the first one:

```
       $ cat hi.r
       /* hello world in r_egg */
       write@syscall(4); //x64 write@syscall(1);
       exit@syscall(1); //x64 exit@syscall(60);

       main@global(128) {
         .var0 = "hi!\n";
         write(1,.var0, 4);
         exit(0);
       }
       $ ragg2 -O -F hi.r
       $ ./hi
       hi!
```

See that it's different in x64 ;)

**Comment by dukebarman** [comment]
Ok, It was bug in documentation :D 

It works for x64, thx.

**Comment by Maijin** [comment]
I fixed the first example in the book

**Comment by yashi21** [comment]
ragg2 is not working for any ".c" file... i.e it isn't producing any executable files for any ".c" file.
I am new to radare2, so please correct me if I am wrong.

**Comment by radare** [comment]
Ragg2 supports two languages. One of them is C, and uses gcc or clang as backend. But it requires that the functions you use are registered as syscalls in the sflib included. Otherwise it will not work.

The other language is a minimalistic compiler that generates relocatable code . This language was originally called rc and the compiler was rcc (relocatable code compiler)

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://malhistudio.com/stream.php?y9>

 

lukas-runas@gmx.de

**Comment by condret** [comment]
Hello!

 

You have a new message, please read <http://casadopenedo.com.br/vocal.php?4m87n>

 

lukas-runas@gmx.de
