### ISSUE TITLE
axt doesn't work but Vx does

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3969]
Here is a weird problem:

https://github.com/RPISEC/Malware/blob/master/Labs/Lab_01/Lab_01.zip?raw=true (first binary, password "infected")

When `r2 -A Lab_01-1.malware -> axt fcn.00401270` there is no result but there are xref available + in Visual mode using `Vx`, xref are shown.

**Comment by Maijin** [comment]
Oh and it works with `axtj`

**Comment by radare** [comment]
Can u cook some tests?

**Comment by Maijin** [comment]
I don't know what causes this, the current tests on axt are working :/

**Comment by alvarofe** [comment]
the issues comes here around line 2638 in cmd_anal.c. fcn is null. I'm trying to find a solution

```
fcn = r_anal_get_fcn_in (core->anal, ref->addr, 0);
if (!fcn)
        continue;
```
