### ISSUE TITLE
cannot build r2

### ISSUE THREAD

**Issue by condret** [radare/radare2#3974]
i get this on make:

make[1]: *** Keine Regel vorhanden, um das Ziel „/usr/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/include/stdbool.h“, 
  benötigt von „mem.o“, zu erstellen.  Schluss.

**Comment by crowell** [comment]
fresh checkout and `sys/install.sh` works for me on ubuntu 14.04, what distro are you on?

**Comment by condret** [comment]
i forgot to git clean -xdf
