### ISSUE TITLE
Output for rabin2 with a few errors for Windows

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3978]
```
C:\>..\radare2-w32-0.10.0-git\rabin2.exe -l sample64.exe
Warning: read (String szKey)
Warning: bad parsing String
Warning: bad parsing StringTable
Warning: bad parsing (VS_VERSIONINFO StringFileInfo)
Cannot find share/radare2/0.10.0-git/format/dll/WSOCK32.sdb
Cannot find share/radare2/0.10.0-git/format/dll/WSOCK32.sdb
```

**Comment by radare** [comment]
Looks like an old r2

**Comment by dukebarman** [comment]
It's a "new" version aka today release from site :)

**Comment by radare** [comment]
Ah sorry the stupid mail was comtaining wrong stuff,

The warns are ok as long as the bin is corrupted ?

The canmot find is also ok if that wsock cache is not yet generated

**Comment by Maijin** [comment]
wsock32 exist, it should be generated

**Comment by radare** [comment]
It is in the zip?

**Comment by Maijin** [comment]
nop not in http://bin.rada.re/radare2-w32-0.10.0-git.zip neither in http://bin.rada.re/radare2-w32-0.10.0.zip

**Comment by radare** [comment]
so thats an issue in the windist make target. will push fix soon and upload a new zip

**Comment by radare** [comment]
Done. please confirm

**Comment by dukebarman** [comment]
Doesn't work. Did you upload new version? (redownload from http://bin.rada.re/radare2-w32-0.10.0-git.zip)
```
C:\r2>radare2.exe -v
radare2 0.10.0-git 10203 @ windows-little-x86-32 git.0.9.9-1983-g82d1ba5
commit: 82d1ba53afcd06b29e8a1d7fa4fbc7c3ee7c1356 build: 2016-01-13
```

And may be this error in only x64 samples?

**Comment by Maijin** [comment]
#5348
