### ISSUE TITLE
rabin2 demangling consistency

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3979]
What about using some option, instead of env var for demangling all symbols?
```
RABIN2_DEMANGLE=1 rabin2 -E mo/lib/libt
```
```
rabin2 -E -D all mo/lib/lib...
Unknown lang to demangle. Use: cxx, java, objc, swift
```

**Comment by radare** [comment]
This was alreay discussed and theres an issue for this iirc. Nobody replied
