### ISSUE TITLE
Button for saving project doesn't work in Webui & OS Windows

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#3981]
Button doesn't save information (name of functions, comments) in files of *.d project folder and user lost data when radare2 was crashed

**Comment by eik00d** [comment]
When use WEB console or Button (Save Project) then file in C:\Users\<USER>\.config\radare2\projects\NAME will be empty:
----- CUT-----
# r2 rdb project file
# flags
# eval
# sections
# meta
----END CUT-----

If you will use normal console (not WEB) then save works fine.

**Comment by crowell** [comment]
which webui? /m /p ?

**Comment by dukebarman** [comment]
-c=H

**Comment by Maijin** [comment]
@dukebarman gives the url ;)

**Comment by dukebarman** [comment]
/cmd/%20Ps%20name
