### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by radare** [radare/radare2#3985]
This issue aims to coordinate the priorities for the 1.0 release:

* [ ] Merge/Connect asm-anal to avoid disassemble and analyze in a shot (~2x speedup)
* [ ] iOS debugger
* [ ] ART binaries support (oat)
* [ ] Faster dyldcache parser
* [ ] ag command must show graph of current function by default
* [ ] ag subcommand to make a huge graph with all the functions (disabled in sandbox mode?)

More to come, please comment, what would you like to have in 1.0?

**Comment by Maijin** [comment]
Proper function argument/variable detection #3655

**Comment by XVilka** [comment]
Sdbtization too https://github.com/radare/radare2/labels/sdbtization

**Comment by Maijin** [comment]
+1 on sdbtization. Will solve many problem !

Also another point, to be able to install radare2 empty and install everyplugin manually with r2pm so @condret can only install stuff for consoles, i can only install radare2 PE, ELF, x86, ARM, so on and so forth...

**Comment by XVilka** [comment]
- [ ] May be also new IO layer as well - siol.
 - [ ] And faster debug engine for remote connections - not to load it byte by byte when scrolling, but by a chunks
 - [ ] Fix and merge windows minidump support (from 'radare2-extras')
 - [ ] (note for myself) Finish and merge windows kernel dump support
 - [ ] Support of the Linux coredump file loading
 - [ ] Recording debug session in SDB

**Comment by dukebarman** [comment]
- [] Comfortable GUI (may be on QT)
- [] Finish series "Radare2 is not as cool as Peda / Relyze / Mona / x64dbg / ..."

**Comment by dukebarman** [comment]
- [ ] Plugin for Frida https://github.com/radare/radare2-extras/issues/6

**Comment by radare** [comment]
There are different plugins.cfg profiles for you to choose. Or just edit it to put all the static plugins as shared and copy the plugins u want.

For embeddeds is better to make a static build and just include the plugins u need

**Comment by radare** [comment]
A gui is out of the scope of this repository and is not a simple/specific task

**Comment by Maijin** [comment]
I kno but Imho it should be possible to do it with r2pm also the plugins.cfg stuff should be documented in the book will add that info.

**Comment by Maijin** [comment]
* [ ] Reliable x86 assembler
* [ ] Reliable arm assembler

**Comment by radare** [comment]
Start writing tests if u want that :)

**Comment by Maijin** [comment]
Also, https://github.com/radare/radare2/issues/2423 duplicate

**Comment by condret** [comment]
if we want things a bit more modular, we need a way to describe dependencies for plugins

**Comment by timofonic** [comment]
- Clean the issue tracker in a sane way, not deleting them like some moronic FOSS projects do. For example: Prepare a road map to solve them and reduce it to less than 50 :D 

Over 600 issues? WTF! Are you ADHD like me? :P

**Comment by Maijin** [comment]
So all of this and more is supposed to be finished for r2con http://rada.re/con/ 🤔

**Comment by radare** [comment]
this issue looks like crap and should be closed or reordered cc @Maijin

**Comment by Maijin** [comment]
I agree on closing definitely useless with milestones
