### ISSUE TITLE
code question libr/bin/p/bin_pe.c

### ISSUE THREAD

**Issue by JohnDoe1234123** [radare/radare2#3986]
Hello radare world :)

following a commit about vb_6 dec50ae9d445de27a1ddc2e48969e04f301ca66c, I have two questions:

question about malloc error check

while this is a MACRO from libr/bin/format/pe/pe.h
with

```
91 #define GUIDSTR_LEN 34
```

getting +1, there is no malloc error check. But later
there is null termination.

However, in an atomic operation where malloc fails, junk
would be copied into ret->guid, possibly leading to a
problem in snprintf?

```
 if (PE_(r_bin_pe_get_debug_data)(arch->o->bin_obj, &di)) {
                ret->guid = malloc (GUIDSTR_LEN+1);
                strncpy (ret->guid, di.guidstr, GUIDSTR_LEN);
                ret->guid[GUIDSTR_LEN] = 0;
```

Shouldn't ret->lang in RBinInfo not be freed later on?

```
339         if (is_vb6 (arch)) {
340                 ret->lang = "vb";
```

(libr/bin/p/bin_pe.c)

Thanks!

**Comment by radare** [comment]
Please send a pr for proper review

**Comment by JohnDoe1234123** [comment]
ok: https://github.com/radare/radare2/pull/3989

what about second question?

**Comment by JohnDoe1234123** [comment]
libr/bin/p/bin_pe.c
@@ -375,11 +375,13 @@ static RBinInfo* info(RBinFile *arch) {
 
 	if (PE_(r_bin_pe_get_debug_data)(arch->o->bin_obj, &di)) {
 		ret->guid = malloc (GUIDSTR_LEN+1);
-		if (!ret->guid) { exit;}
+		if (!ret->guid) 
+		     exit;
 		strncpy (ret->guid, di.guidstr, GUIDSTR_LEN);
 		ret->guid[GUIDSTR_LEN] = 0;
 		ret->debug_file_name = malloc (DBG_FILE_NAME_LEN+1);
-		if (!ret->debug_file_name) { exit;}
+		if (!ret->debug_file_name)
+		     exit;
 		strncpy (ret->debug_file_name, di.file_name, DBG_FILE_NAME_LEN);
 		ret->debug_file_name[DBG_FILE_NAME_LEN] = 0;
 	}

**Comment by JohnDoe1234123** [comment]
@crowell Thanks for the pointer. I have problems creating the pr.
