### ISSUE TITLE
Wrong code generated by assembler

### ISSUE THREAD

**Issue by haco20292** [radare/radare2#3990]
```
$ rasm2 -d -b 64 `rasm2 -a x86.as -b 64 'mov rax, 0x9c251da8'`
movabs rax, 0x9c251da8 <= Right.
$ rasm2 -d -b 64 `rasm2 -a x86 -b 64 'mov rax, 0x9c251da8'`
mov rax, -0x63dae258 <= Wrong.
```
-0x63dae258 == 0xffffffff9c251da8.

Is there an option variable about assembler used by radare2? I have tried to set asm.arch=x86.as but it doesn't work.

**Comment by radare** [comment]
Use udis. Negative hex values are a known issue in capstone. Are u using system or git version on capstone?

**Comment by haco20292** [comment]
I am using radare2 from git repository on Ubuntu. I spotted USE_CAPSTONE=0 when I configured radare2 and make git-cloned capstone. Is there an option to specify default assembler for wa command in radare2?

**Comment by crowell** [comment]
Capstone isn't an assembler it can only disassemble

**Comment by haco20292** [comment]
So there are two problems:
1. "wa mov rax, 0x90251da8" generates "mov rax, 0xffffffff90251da8" when arch=x86 in rasm2 and r2.
2. How to specify default disassembler in r2?

**Comment by haco20292** [comment]
I found another bug: Assembler doesn't recognize register r8, r9.
```
$ rasm2 -a x86 -b 64 "push rax; push r8; push r9;"
Invalid register name (r8)
Invalid register name (r9)
Invalid register name (r8)
Invalid register name (r9)
Invalid register name (r8)
Cannot assemble 'push r8' at line 8
invalid
```

**Comment by Maijin** [comment]
works with x86.as

**Comment by haco20292** [comment]
I think it's necessary to have an option variable to specify default assembler for wa command in radare2. Some assembler & disassembler plugins are not mature.

**Comment by radare** [comment]
i have added r8-r15 support for push/pop in x86.nz <http://x86.nz/> plugin

**Comment by radare** [comment]
Can you please write tests and fill different issues for each assembler problem?

**Comment by radare** [comment]
you change the assembler/disassembler plugin right now there's no way to specify a different assembler for a disassembler plugin, both callbacks come together in the same plugin, so you can just switch to one plugin and then switch back.

Anyway, before the release i have plans to fix this and other stuff related to asm/anal

**Comment by haco20292** [comment]
OK!

**Comment by Maijin** [comment]
This has been fixed see `e asm.assembler`
