### ISSUE TITLE
Question on ascii-graph

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#3991]
So I've been trying to get ascii-graph to work over ssh.  The setup is putty and Ubuntu 14.04 with radare2 installed.  I start with:
~~~
r2 -A bleh.exe
s main
VV @ main
~~~
The results is a black screen with a cursor.  The font/color setup is the default with putty.  Any help would be wonderful...thank you.

**Comment by Maijin** [comment]
What's the version of radare2 installed ? `r2 -v`

**Comment by DigiAngel** [comment]
Ack...it looks kind of old 8-|
~~~
radare2 0.9.6 @ linux-little-x86-64 git.0.9.6
commit: 1: build: 2014-04-10
~~~

Tahnk you.

**Comment by DigiAngel** [comment]
Ya new version works a treat:
~~~
radare2 0.10.0 10150 @ linux-little-x86-64 git.0.10.0
commit: 9c39df6806b09306ebb102b1c41de8367ac1a7c9 build: 2016-01-21
~~~
Thanks much.
