### ISSUE TITLE
? doesn't print help but seems to run the command

### ISSUE THREAD

**Issue by kerokeroloid** [radare/radare2#3992]
```
[0x00000000]> !date; aaa?; !date
Thu Jan 21 20:56:34 CET 2016
Thu Jan 21 20:56:41 CET 2016
```

I'm expecting to see some help instantly, but maybe I don't understand the syntax here. `aa?` seems to work fine. I think I saw this behavior with some other command, but that also printed some help (I assume because it was available). I don't remember what command it was.

**Comment by radare** [comment]
There's no help for aaa

**Comment by kerokeroloid** [comment]
But is it supposed to run the command too?

**Comment by radare** [comment]
Yes. Because theres no switch statment to handle any parameter in there so it runs the command. I know its not suposed to do that. But its the exact behaviour as the one described by the code :-)

**Comment by radare** [comment]
Fixed
