### ISSUE TITLE
Retrieve name from functions in native library on Android

### ISSUE THREAD

**Issue by dummys** [radare/radare2#3995]
Hello,

```
radare2 version: radare2 0.9.9 9999999 @ linux-little-x86-64 git.0.9.9
commit: HEAD build: 2015-06-05
```

On this crackme: https://play.google.com/store/apps/details?id=net.defendio.cme.natus
lib.so: http://rghost.net/7LrdgtNT5
There is a native library for arm/intel x86/x64.
With ida, the function are named correctly but not with radare2.

```
[0x00000490]> aaa
[0x00000490]> afl
0x00000490  12  2  entry0
0x00000470  6  1  sym.imp.__cxa_finalize
0x00000476  10  2  fcn.00000476
0x00000450  12  1  section..plt
0x00000460  6  1  sym.imp.__cxa_atexit
0x00000466  10  1  fcn.00000466
0x00000480  6  1  sym.imp.__android_log_print
0x00000486  10  1  fcn.00000486
0x0000049c  13  3  fcn.0000049c
0x000004b0  22  1  fcn.000004b0
0x000004d4  241  9  fcn.000004d4
0x00000930  1193  1  fcn.00000930
0x000008c0  1305  1  fcn.000008c0
0x000008b0  1321  1  fcn.000008b0
```
And with ida the name of fcn.000004d4 is: Java_net_defendio_cme_antus_CheckCodeActivity_Auth

**Comment by Maijin** [comment]
What's the version of your radare2 : `r2 -v`

**Comment by Maijin** [comment]
Update using github. `commit: HEAD build: 2015-06-05` => Uninstall your version then:

`git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`

**Comment by dummys** [comment]
yes it's working. Thanks
