### ISSUE TITLE
Add opcodes description

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4014]
* [x] 6502
* [x] 8051
* [x] arc
* [x] arm.as
* [x] arm
* [x] arm.gnu
* [x] arm.winedbg
* [x] avr
* [x] bf
* [ ] cr16
* [ ] cris
* [ ] csr
* [x] dalvik
* [ ] dcpu16
* [ ] ebc
* [x] gb
* [ ] h8300
* [ ] hppa
* [x] i4004
* [x] i8080
* [x] java
* [x] lh5801 waiting on #4012 
* [x] lm32
* [x] m68k
* [x] m68k.cs
* [x] malbolge
* [ ] mcs96
* [x] mips
* [x] mips.gnu
* [x] msp430
* [ ] nios2
* [x] ppc
* [x] ppc.gnu
* [ ] rar
* [x] riscv
* [x] sh
* [x] snes
* [x] sparc
* [x] sparc.gnu
* [ ] spc700
* [x] sysz
* [x] tms320
* [x] v810
* [ ] v850
* [ ] vax
* [x] ws
* [x] x86.as
* [x] x86
* [x] x86.nasm
* [x] x86.nz
* [x] x86.olly
* [x] x86.tab
* [x] x86.udis
* [ ] xcore
* [x] z80
* [x] z80.cr
* [x] propeller

**Comment by Maijin** [comment]
Looking for pdfs/documents for the remaining architecture

**Comment by radare** [comment]
@bigendiansmalls can you help with the `sysz` one?

**Comment by bigendiansmalls** [comment]
absolutely. ill look at it today.

**Comment by neuschaefer** [comment]
I'll do RISC-V.

**Comment by evanrichter** [comment]
I found [documentation ](http://nagasm.org/ASL/Propeller/printedPDF/QuickReference-v15.pdf)for propeller but I have no experience with it. should I try anyway?

**Comment by radare** [comment]
Why not? :)

**Comment by evanrichter** [comment]
I made a pull request, but I don't know how to reference this issue...

**Comment by Maijin** [comment]
Major one are here now thanks all guys :) Closing the issue for now.
