### ISSUE TITLE
ROP: Find gadgets from all offsets

### ISSUE THREAD

**Issue by abpolym** [radare/radare2#4020]
If this is a duplicate or already exists, please excuse or redirect me.

Currently, the ROP search command doesn't find gadgets that are "hidden at different offsets" - meaning that if you shift one byte or more, you actually can find the correct opcodes for the gadget as seen here:

![](https://transfer.sh/Oeq95/shift.png)

`ff` from the `__libc_start_main` call together with `f4` from the `hlt` instruction create a `push esp`, which can't be found by the usual `\R` command.

Proof:

![](https://transfer.sh/NKvYm/ropsearch.png)

PS: The binary I am analyzing is from UIUCTF 2015, challenge "unoriginal", see [here](https://github.com/ctfs/write-ups-2015/tree/master/uiuctf-2015/pwn/unoriginal)

**Comment by crowell** [comment]
/R won't find that because it's not followed by a stop gadget ofc

Close #4020

**Comment by radare** [comment]
You are probably looking for /c

**Comment by YASME-Tim** [comment]
@radare Ok so with `/c` I get some results:

![](https://transfer.sh/4tyM0/c.png)

However, it would be preferred to have the results showing in `/R`, too.

I don't understand your solution @crowell - I tried something like `"/R/ jmp.*esp$"` for example, but I only get false positives. Can you tell me what exactly do you mean?

**Comment by crowell** [comment]
ah, so the issue here is `rop.len` default is 5, try it again with `e rop.len = 10`

**Comment by YASME-Tim** [comment]
@crowell Hmm almost. I get one out of two possible `push esp` - but not the correct one, even with a higher max rop length:

![](https://transfer.sh/WMT6U/push.png )

**Comment by crowell** [comment]
grrr, frustrating. i'll take a look at this tonight.

On Mon, Jan 25, 2016 at 4:26 PM, polym <notifications@github.com> wrote:

> @crowell <https://github.com/crowell> Hmm almost. I get one out of two
> possible push esp - but not the correct one, even with a higher max rop
> length:
>
>
> <https://camo.githubusercontent.com/9d6be249ad78cc9463ee46c54202370863fc9c57/68747470733a2f2f7472616e736665722e73682f574d5436552f707573682e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4020#issuecomment-174670183>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by YASME-Tim** [comment]
@crowell Thanks man, you're awesome :)

**Comment by YASME-Tim** [comment]
@crowell Can you tell me which files I should have a look at, if I decide to try to solve it by myself? Thanks!

**Comment by Maijin** [comment]
Most ropgadget stuff is located in this file https://github.com/radare/radare2/blob/master/libr/core/cmd_search.c#L638

**Comment by Maijin** [comment]
Ping?

**Comment by EasyHard** [comment]
Hi @Maijin  @crowell I am trying to looking into this as my GSoC micro task and found some clues.

Just a heads up ^_^.

**Comment by EasyHard** [comment]
Hi @abpolym @crowell @Maijin 
The problem is that the `hlt` instruction is treated as an end gadget. And currently `r_core_search_rop` does not search any addresses that are smaller than the previous end gadgets. So it will blocks the chance to disassemble `fff4` as `push esp`.

I will submit a PR for this.

**Comment by radare** [comment]
👍
