### ISSUE TITLE
Fix disasm in the middle of hexdumps in pd issue

### ISSUE THREAD

**Issue by radare** [radare/radare2#4026]
```
Cd 100
s 4
pd 2
```

**Comment by ret2libc** [comment]
Please explain what's the wrong output and what's the expected output...

**Comment by radare** [comment]
The Cd in the pd is only handled at the begining, if you try to disasm a dword +1 it will show code instead of the 3 bytes pending.

The same happens for large hex blocks and such

**Comment by ret2libc** [comment]
I have to delay this to the next release, unless someone else wants to do it before.

**Comment by radare** [comment]
Dupe of https://github.com/radare/radare2/issues/2712
