### ISSUE TITLE
Add @@!x or @@:x as an alias for @@=`x`

### ISSUE THREAD

**Issue by radare** [radare/radare2#4027]
Pls discuss. the idea is that many commands output lists and `@@=`x`` is useful for those cases but its too much stuff to type and sometimes the backtick quote cannot be easily typed in some keyboards and it can be problematic because of the r_cons buffering. so a simpler syntax can be useful.

**Comment by jvoisin** [comment]
`@@:x` looks cool

**Comment by joelabr** [comment]
I also prefer `@@:x` over `@@!x` since the latter looks like it has something to do with changing the block size. (I'm thinking of `@ addr[!blocksize]`)
