### ISSUE TITLE
regression, rar disassembly support doesn't work correctly

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4040]
Just tried to open: 
- https://github.com/radare/radare2/blob/master/shlr/rar/helloworld.rar

Got: 

```
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
Cannot set bits 64 to 'rar'
Cannot set bits 32 to 'rar'
 -- Use 'zoom.byte=printable' in zoom mode ('z' in Visual mode) to find strings
[0x0000009a]> pd 10
    entry0:
    section_end.header:
    section.rarvm:
                 invalid                                               ; [1] va=0x0000009a pa=0x0000009a sz=779 vsz=779 rwx=m-r-x rarvm
                 invalid
                 invalid
                 invalid
                 invalid
                 invalid
                 invalid
                 invalid
                 invalid
                 invalid
[0x0000009a]> 
```

**Comment by Maijin** [comment]
There are test, but they should be moved from this repo to the r2r

**Comment by radare** [comment]
asm.rar is a 1bit arch, yep its weird, thats not handled by current asm checks

**Comment by gtors** [comment]
Disassembling of rarvm is turned off (see [asm_rar.c](https://github.com/radare/radare2/blob/master/libr/asm/p/asm_rar.c#L12)):

```
static int disassemble(RAsm *a, RAsmOp *op, const ut8 *buf, int len) {
	// TODO: support bitsize opcodes
	// rarvm_disassemble (&b, str);
	return 0;
}
```

**Comment by crowell** [comment]
and it's been turned off since 2012...
https://github.com/radare/radare2/commit/51b7147df6ce0beed567f09af103fc7e213397a5

On Thu, Apr 28, 2016 at 10:58 AM, Andrey Torsunov <notifications@github.com>
wrote:

> Disassembling of rarvm is turned off (see asm_rar.c
> <https://github.com/radare/radare2/blob/master/libr/asm/p/asm_rar.c#L12>):
>
> static int disassemble(RAsm *a, RAsmOp *op, const ut8 *buf, int len) {
>     // TODO: support bitsize opcodes
>     // rarvm_disassemble (&b, str);
>     return 0;
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4040#issuecomment-215453458>
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by Maijin** [comment]
Should be moved in r2e no?

**Comment by radare** [comment]
Yep makes sense

**Comment by radare** [comment]
There was no r2e at the time. Also, the idea to keep it in master was to have a way to test and support archs with instruction sizes smaller than a byte

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/65776308c9ea4e24716584fdce3c90d0520139cd
