### ISSUE TITLE
lm32 missed opcodes

### ISSUE THREAD

**Issue by l4l** [radare/radare2#4047]
Corresponding to [doc](https://sourceware.org/cgen/gen-doc/lm32-insn.html) there are missed mnemomincs in the code:

- addgotoff
- bret
- eret
- lbgotoff
- lbgprel
- lbugotoff
- lbugprel
- lhgotoff
- lhgprel
- lhugotoff
- lhugprel
- lwgotoff
- lwgotrel
- lwgprel
- mva
- mvui
- sbgotoff
- sbgprel
- shgotoff
- shgprel
- swgotoff
- swgprel
- user

**Comment by Maijin** [comment]
ping @felixheld :)

**Comment by felixheld** [comment]
those instructions are only in the online instruction reference from gcc, but not in LatticeMico32ProcessorReferenceManual35pdf.pdf, which i used for writing the disassembler support. The "missing" instructions are aliases. i should add them when i push the assembler support. not sure about the disassembler.

**Comment by l4l** [comment]
Ok, things are much clearer now
