### ISSUE TITLE
example request: assemble

### ISSUE THREAD

**Issue by iddq** [radare/radare2#4053]
example request: assemble

**Comment by radare** [comment]
Wat

**Comment by Maijin** [comment]
???

**Comment by iddq** [comment]
sorry, can you please make some example for assemble?
There is some example for usage but no for assemble.
https://github.com/radare/radare2/wiki/Usage-Examples

**Comment by Maijin** [comment]
Stop using the wiki, it's outdated.

**Comment by radare** [comment]
The same without -d. The wiki should be merged into the book or something

**Comment by radare** [comment]
Imho its ok to rm the wiki. Nobody uses them

**Comment by Maijin** [comment]
The dev part is used, the rest no.

**Comment by Maijin** [comment]
page deleted
