### ISSUE TITLE
cbs to plugin

### ISSUE THREAD

**Issue by condret** [radare/radare2#4063]
ok, i'm a bit busy, so it would be nice if someone else can do this:

`io->cbs` is a relic from the original `libsiol`, which needs to be replaced by `io->plugin`, otherwise it won't access our plugins. It's an easy taks, it only may take a few minutes.
And pls look out for typos and fix them, the earlier they get fixed, the less bugs they produce.
push to the siolbranch, not master

**Comment by condret** [comment]
see https://github.com/radare/radare2/blob/siol/libr/io/io.c

**Comment by XVilka** [comment]
Good function ```R_API RIODesc *r_io_open_nomap (RIO *io, char *uri, int flags, int mode)```: https://github.com/radare/radare2/blob/siol/libr/io/io.c#L23

Bad function ```R_API int r_io_close (RIO *io, int fd)```: https://github.com/radare/radare2/blob/siol/libr/io/io.c#L75

**Comment by slawniczak** [comment]
#4071

**Comment by condret** [comment]
thank you
