### ISSUE TITLE
"(null) = (null)" with asm.decode on ARM

### ISSUE THREAD

**Issue by neuschaefer** [radare/radare2#4064]
```
$ r2 -v
radare2 0.10.0 10236 @ linux-little-x86-64 git.0.10.0-85-g4bbcad5
commit: 4bbcad586459c53bb14a4566bdd5fd08a3e514da build: 2016-02-04
$ r2 -
 -- Find hexpairs with '/x a0 cc 33'
[0x00000000]> e asm.arch=arm
[0x00000000]> e asm.bits=32
[0x00000000]> e asm.filter=true
[0x00000000]> wx 000000eb1eff2fe10000a0e11eff2fe1
[0x00000000]> aa
[0x00000000]> pd 4
/ (fcn) fcn.00000000 8
|           0x00000000      000000eb       bl 8                         ; fcn.00000008
\           0x00000004      1eff2fe1       bx lr
/ (fcn) fcn.00000008 8
|           ; CALL XREF from 0x00000000 (fcn.00000008)
|           0x00000008      0000a0e1       mov r0, r0
\           0x0000000c      1eff2fe1       bx lr
```

`asm.decode` replaces the function names, but breaks the `mov r0, r0` (`nop`) instruction.
```
[0x00000000]> e asm.decode=true
[0x00000000]> pd 4
/ (fcn) fcn.00000000 8
|           0x00000000      000000eb       fcn.00000008()
\           0x00000004      1eff2fe1       ret
/ (fcn) fcn.00000008 8
|           ; CALL XREF from 0x00000000 (fcn.00000008)
|           0x00000008      0000a0e1       (null) = (null)
\           0x0000000c      1eff2fe1       ret
[0x00000000]> 
```

**Comment by neuschaefer** [comment]
The replacement does work if the address is >= 0x100, so it seems to be intended. Sorry for the noise.

**Comment by radare** [comment]
Yes. It is suposed to fix some false positives

**Comment by neuschaefer** [comment]
The other (small) problem is the `(null) = (null)`. Should I open a new issue for that or rename this issue?

**Comment by radare** [comment]
Yeah this looks like a bug. We can reuse this issue. Any shorter way to reproduce?

**Comment by neuschaefer** [comment]
Yes, only the mov instruction matters. Oneliner:
```
r2 -q -a arm -b 32 -e asm.decode=true -c 'wx 0000a0e1; pd 1' -
```

**Comment by radare** [comment]
imho asm.decode should be deprecated, because now we have esil and asm.pseudo and the RAnalOp doesnt fills all the info needed. anyway. what do you think?

**Comment by XVilka** [comment]
+1 for deprecation

**Comment by radare** [comment]
asm.decode was suposed to be an asm.pseudo powered by the RAnalOp information. but as long as this turns to use a lot of memory and slowed down the analysis i just dropped half of it. and it was mainly done for x86, so thats what we get for arm :P (nulls)

**Comment by radare** [comment]
@condret @ret2libc @alvarofe what do you think about this? if we decide to fully remove it we can reduce the size of RANalOp and therefor the memory needed to analyze

**Comment by neuschaefer** [comment]
I don't need asm.decode, I'm fine with deprecation.

**Comment by Maijin** [comment]
Thus asm.decode issue is duplicate of https://github.com/radare/radare2/issues/1547

**Comment by radare** [comment]
Ha! Nice catch :) so lets the deprecation machinery start
