### ISSUE TITLE
ahi for syscall numbers

### ISSUE THREAD

**Issue by radare** [radare/radare2#4068]

**Comment by unixfreaxjp** [comment]
some missing syscall tables maybe :

[0x08048054]> aaa
[0x08048054]> e asm.emu=true
[0x08048054]> e asm.emuwrite=true
[0x08048054]> aeim
[0x08048054]>
[0x08048054]> pd
syscall 102 not implemented yet
syscall 102 not implemented yet
syscall 125 not implemented yet
```asm
/ (fcn) entry0 71
|           0x08048054      31db           xor ebx, ebx               ; ebx=0x0 ; zf=0x1 -> 0x1464c00; pf=0x1 -> 0x1464c00; sf=0x0 ; cf=0x0 ; of=0x0
|           0x08048056      f7e3           mul ebx                    ; ebx=0x0
|           0x08048058      53             push ebx                   ; esp=0x177ffc
```
and this is the suggested ones, snapshot:
![](https://lh3.googleusercontent.com/-xC_37dAYLGE/VrHnM7Sw-NI/AAAAAAAAUVY/vqDI7jNJ6wA/h120/1001.png)

**Comment by Maijin** [comment]
Not working on OSX reverted

**Comment by unixfreaxjp** [comment]
Because OSX is not freebsd :-P

**Comment by radare** [comment]
Will fail also on windows. Mainly because linux linker doesnt verifies too much and does lazy resolving of symbols.

**Comment by radare** [comment]
At 3rd try 👍
