### ISSUE TITLE
arm assembler doesn't know .word directive

### ISSUE THREAD

**Issue by rofl0r** [radare/radare2#4070]
gcc 4.7.3 compiles this code (with -O1)
```
typedef void (*func)(void*);
unsigned char foo(void* a, unsigned char b) {
        func f = (func)0x8050c5ac;
        f(a);
        return 1;
}
```
to
```
08 40 2D E9  08 30 9F E5  33 FF 2F E1  01 00 A0 E3  08 80 BD E8  AC C5 50 80
```
```
00000000 <foo>:
   0:   e92d4008        push    {r3, lr}
   4:   e59f3008        ldr     r3, [pc, #8]    ; 14 <foo+0x14>
   8:   e12fff33        blx     r3
   c:   e3a00001        mov     r0, #1
  10:   e8bd8008        pop     {r3, pc}
  14:   8050c5ac        .word   0x8050c5ac
```
however the radare2 assembler doesn't know the .word directive, making it impossible to disassemble or reassemble equivalent code.

**Comment by radare** [comment]
Use .hex directive

**Comment by radare** [comment]
Or .byte

**Comment by radare** [comment]
I disnt added .word because its endian-confusing, but it can be added in 3 lines in libr/asm/asm.c

**Comment by rofl0r** [comment]
yeah, it seems with .hex the endianness is switched
i.e.  it outputs 8050c5ac rather than acc55080

**Comment by rofl0r** [comment]
also while disassembling some real-world arm code i saw a number of "invalid"s, and i suppose those were .word directives used in a similar manner than the .text-hardcoded func address, but those happened not to produce a valid asm statement. imo in such a case rasm2 should emit a .word directive rather than "invalid" so the asm it spits out can be re-assembled.

**Comment by radare** [comment]
R2 with .hex doesnt swaps endian. Its objdump who confuses everyone :p

**Comment by radare** [comment]
Theres an eval var for this:

e asm.invhex=true

You can also use Vd to define other types and structures

**Comment by rofl0r** [comment]
well usually it swaps, i.e. does the right thing, just not with .hex
so that appears a little inconsistent

**Comment by radare** [comment]
Will be ok with .dword . Hex is just linear write of bytes. Not affected by endian

**Comment by radare** [comment]
It swaps if you do 0x because numbers are tied to endianness, but data is not
