### ISSUE TITLE
rabin2 -x on latest iOS dyldcaches doesn't work

### ISSUE THREAD

**Issue by radare** [radare/radare2#4072]
```
format/mach0/dyldcache.c:44 oob thing: Invalid argument
```

**Comment by radare** [comment]
anyone working on this?

**Comment by alvarofe** [comment]
dunno if @lionaneesh is looking at this. If not i could take it to see what is happening. is there dyldcache binary in r2r?

**Comment by alvarofe** [comment]
I think that i fixed the issue with the format though there is room for improvement regarding memory and time consuming

**Comment by radare** [comment]
awesome! looking forward your PR

**Comment by radare** [comment]
This is fixed by @alvarofe
