### ISSUE TITLE
"pfv" does not show the value

### ISSUE THREAD

**Issue by michalmalik** [radare/radare2#4075]
I am trying to get the value of ```elf_header.entry```, for example. 

```asm
[0x00000000]> pf.elf_header
               ident : 0x00000000 = .ELF...
                type : 0x00000010 =  type (enum) = 0x2 ; ET_EXEC
             machine : 0x00000012 =  machine (enum) = 0x3e ; EM_AMD64
             version : 0x00000014 = 0x00000001
               entry : 0x00000018 = (qword) 0x00000000004048c5
               phoff : 0x00000020 = (qword) 0x0000000000000040
               shoff : 0x00000028 = (qword) 0x000000000001c748
               flags : 0x00000030 = 0x00000000
              ehsize : 0x00000034 = 0x0040
           phentsize : 0x00000036 = 0x0038
               phnum : 0x00000038 = 0x0009
           shentsize : 0x0000003a = 0x0040
               shnum : 0x0000003c = 0x001b
            shstrndx : 0x0000003e = 0x001a
[0x00000000]> pfv.elf_header.type
 type (enum) = 0x2 ; ET_EXEC
[0x00000000]> pfv.elf_header.entry
[0x00000000]>
```

I would expect it to work like this:
```asm
[0x00000000]> .pf*.elf_header
[0x00000000]> pf q @ entry
0x00000018 = (qword) 0x00000000004048c5
[0x00000000]>
```

Although, I think it would be nicer to just output either ``` (qword) 0x00000000004048c5``` or ``` 0x00000000004048c5``` if only one value (```pf q```) is wanted.

I am using the git version of radare2.

**Comment by radare** [comment]
Cc @hyask

**Comment by Hyask** [comment]
`pfv` is made for scripting, and thus displays only the value, without even a '\n' at the end, and that's why it's overwritten by (I suspect), the r2 shell.
Try typing ```echo `pfv.elf_header.entry` ```, it should work.

Why don't you want the offset in `pf q` ? I think it can be useful even with only one value, although we already know the address, as a reminder...

**Comment by michalmalik** [comment]
```
echo `pfv.elf_header.entry`
```
 works like a charm. Perfect. This changes everything -  I thought e.g. ```pfv q @ 0``` did nothing because I did not know about the missing ```echo```, thus I thought about using ```pf q @ 0~=[2]``` to get the value. Which in retrospect seems unecessarily complicated, haha. 

Thank you again and sorry for noob questions - there might be more, although I try my best at reading radare2 cheatsheets and usages.

**Comment by Hyask** [comment]
No problem, have fun using r2! :)

**Comment by radare** [comment]
This issue happened to other commands when output is json and such, when @ret2libc changed this logic in rcons. The solution would be to add a newline at the end. The prompt shouldnt hide that info

**Comment by Hyask** [comment]
If we add a new line, then it can not be used in scripts anymore, since we would get "my_value\n"

**Comment by radare** [comment]
Which scripts ? Because r2pipe and r2 scripting chop the tailing newlines always

**Comment by Hyask** [comment]
Oh, I didn't know! Even the too long one-liners of @Maijin will work? It didn't when I implemented `pfv`

**Comment by Maijin** [comment]
No worries for the script, it's long time ago now should work

**Comment by radare** [comment]
Well that changed over the time :p because we had some extra newlines, so we are going the other way around

**Comment by Hyask** [comment]
Okay, then I'll see to patch `pfv` in the next few hours :)

**Comment by Hyask** [comment]
Okay, I've tried to patch, but it seems that the \n is replaced by a whitespace, so it make the scripting with backticks fails... :/
Any solution, @radare ?

**Comment by radare** [comment]
why it breaks this? the reason why this replacemnt happens is because r2 prompt is oneliner, so if you can do stuff like this: ` pdf @@='afl'` -- where ' is an imaginary backtick
