### ISSUE TITLE
a cute ascii graph maybe?

### ISSUE THREAD

**Issue by unixfreaxjp** [radare/radare2#4079]
If this is not too many to ask, gents. will look cute on startup.
This is only an example.. 
![](https://lh3.googleusercontent.com/-rL0bLIDgh3k/VrQ0jpXkJdI/AAAAAAAAUXQ/TUn_Cv3NpP8/s700/LuvR2.png)

```asm

                   .___                     
____________     __| _/____ _______   ____  
\_  __ \__  \   / __ |\__  \\_  __ \_/ __ \ 
 |  | \// __ \_/ /_/ | / __ \|  | \/\  ___/ 
 |__|  (____  /\____ |(____  /__|    \___  >
            \/      \/     \/            \/ 
```

**Comment by crowell** [comment]
You can put something like this in your radare2rc

**Comment by unixfreaxjp** [comment]
oh, okay. closed.
