### ISSUE TITLE
r_anal_get_fcn_in should walk bb ranges

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#4080]
At the moment it just consider an address to be in a function iff
```
fcn->addr <= X < fcn->addr + fcn->size
```
This is not the case when the function is not contiguous.

**Comment by radare** [comment]
This change can slowdown a lot the process. So maybe it will be good to store an ut64 array of covered ranges or deltas, merging contiguous basic blcoks and avoid following pointers, etc

**Comment by ret2libc** [comment]
Maybe we can use something like this. https://en.wikipedia.org/wiki/Range_tree. 
I already implemented some time ago the RTree structure (https://github.com/radare/radare2/blob/master/libr/util/tree.c), so it shouldn't be too hard to extend or "subclass" it to implement the range tree
