### ISSUE TITLE
ARM analysis doesn't track mode

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#4091]
I know there are some similar issues, but nothing seems to capture this exactly. Full analysis should try to do some sort of tracking of what is 32-bit and what is 16-bit. Binaries that do a lot of switching don't get very good results since it only analyzes based on the original asm.bits setting. I was looking at something today that did a lot of switching and the manual setting of asm.bits every couple of lines of assembly was quite painful. We should be able to mark a region of code as being 16 or 32 bit based on xrefs and how the branch is called.

**Comment by radare** [comment]
It does, but not in all situations. Can you provide a test case for this?

**Comment by ninjahacker** [comment]
I see. I can definitely give one (that was mentioned), but I can probably pull together at least a couple.

**Comment by ninjahacker** [comment]
https://www.dropbox.com/s/bohoeesxync7zyw/recovery?dl=0

The first jump from entry doesn't change modes like it should.

**Comment by Maijin** [comment]
@ninjahacker is this fixed ?

**Comment by Maijin** [comment]
@ninjahacker please add tests like you did for blx. ping(2)

**Comment by alvarofe** [comment]
Anal hints already does that and is how arm/thumb is handled now not based on asm.bits. It would be great to have more test cause arm/thumb is quite delicate

**Comment by Maijin** [comment]
ok but closing here then.
