### ISSUE TITLE
be able to follow references to symbols that aren't call/jmp

### ISSUE THREAD

**Issue by crowell** [radare/radare2#4093]
it would be useful to be able to press enter on something like a `mov eax, SYMBOL` or `push SYMBOL` and seek to `SYMBOL`

**Comment by shiftre** [comment]
I have the exact scenario and crowell and maijin either offered ":s " or ":o ",
I'm not going to shoot myself in the head, please add this feature to follow symbols.

**Comment by Maijin** [comment]
Using the cursor also maybe ?

**Comment by radare** [comment]
the way to get that "symbol" can be done in different ways.

* analop : incomplete in some situations
* esil : emulate the instruction and catch mem references and immediates computed
* parsing disasm : like r_parse does

**Comment by Maijin** [comment]
In fact all of this can be fixed via a proper fix on `X` in Visual Mode.
