### ISSUE TITLE
wrong metadata definition/parse

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#4095]
Input `/bin/ls` from elCapitan

<img width="561" alt="captura de pantalla 2016-02-10 a las 13 45 23" src="https://cloud.githubusercontent.com/assets/3474042/12947607/dc9691d8-cffc-11e5-8261-b7524fb7f812.png">

using the cursor in visual mode i define a qword with `dW`

<img width="607" alt="captura de pantalla 2016-02-10 a las 13 45 39" src="https://cloud.githubusercontent.com/assets/3474042/12947626/f34971f2-cffc-11e5-81a3-a25dca2e3c1a.png">

but that `1` gets lost and it should be `0x0000000100004608`

**Comment by radare** [comment]
Thanks! nice catch
