### ISSUE TITLE
Support repetitions in Vd

### ISSUE THREAD

**Issue by radare** [radare/radare2#4096]
Syntax would be like this:

Vd8W -> define 8 qwords starting in cursor or current seek
Vd32w -> define 32 dwords...

**Comment by alvarofe** [comment]
I would suggest `Vdw32, VdW8`, since when you are in visual mode a menu is presented to you to choose between different options, among those `w` and `W`

So after choose `w` or `W` we just ask the user how many times he wants to repeat the cmd.

**Comment by radare** [comment]
Vd32w is more vim-friendly and consistent with the rest, so the current behaviour will not change and the current use will not be broken
