### ISSUE TITLE
do not hardcode preludes

### ISSUE THREAD

**Issue by radare** [radare/radare2#4113]
Support in `ap` and `aap`

**Comment by Maijin** [comment]
So where this should be defined ? External SDB ?

**Comment by radare** [comment]
maybe in plugins, directly in C, we also need to identify forward preludes and backward preludes. this is because forward searching will find the first instruction matching some bytes, but in arm64 for example, the function prelude is defined by N same instructions. so it requires some more logic than just checking a fixes amount of bytes.

**Comment by radare** [comment]
related to zignaturez

**Comment by Maijin** [comment]
```
# Signatures
zn prelude
zb prelude_ppc_A 7c0802a6
zb prelude_arm_16_A f0b5
zb prelude_arm_32_A 00482de9
zb prelude_arm_64_A f657bda9
zb prelude_arm_64_B fd7bbfa9
zb prelude_arm_64_C fc6fbea9
zb prelude_arm_64_D 27bd00
zb prelude_x86_32_A 8bff558bec
zb prelude_x86_32_B 5589e5
zb prelude_x86_32_C 558bec
zb prelude_x86_64_A 554889e5
zb prelude_x86_64_B 55488bec
zn-
```

**Comment by Maijin** [comment]
See 6947
