### ISSUE TITLE
Remove sigsetjmp from Xtensa disasm

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4114]
It does not build on Windows correctly.

**Comment by stanciuadrian** [comment]
Use setjmp when sigsetjmp is not available. Just sync with GNU opcodes.

**Comment by stanciuadrian** [comment]
Did you start working on it? 
I have already fixed it in my fork and can do a pull request.

**Comment by radare** [comment]
Nope i was just asking. Send the pr :) thanks

**Comment by stanciuadrian** [comment]
Rechecked this issue and it seems I also need to modify `configure.acr` to define `HAVE_SIGSETJMP` if the `sigjmp_buf`/`sigsetjmp()`/`siglongjmp()` are available. In `binutils` they do this by compiling a short C program and checking if the compilation fails:
```#include <setjmp.h>
main()
{
	sigjmp_buf env; 
	while (!sigsetjmp (env, 1)) siglongjmp (env, 1);
}```
Does `acr` support this mechanism?

**Comment by radare** [comment]
Yes it does. But i prefer to avoid that thing. Setjmp is as bad as goto. It should be removed if possible
