### ISSUE TITLE
MSP430 Invalid Instruction Width / Alignment

### ISSUE THREAD

**Issue by travisgoodspeed** [radare/radare2#4125]
Howdy y'all,

The MSP430 architecture always fetches half-word aligned instructions, and all valid instructions begin at even addresses.  Unfortunately, R2's MSP430 decoder treats invalid instructions as being just one byte long, breaking alignment and causing future, valid instructions to be unnecessary mistaken for invalid instructions.

For example, this sequence from the MSP430F2618's mask ROM consists of some data words followed by the instruction `ff3f`, an unconditional jump-to-self.  Because of the broken alignment, R2 presumes than an `and r15, r12` instruction exists at 0x0c03, even though that address is odd.

```
tmg% rax2 -s 06 0c 1e 0c ff 3f b2 40 40 a5 >foo
tmg% r2 -a msp430 -m 0x0c00 foo
[0x00000c00]> pdx 5
            0x00000c00      06             invalid
            0x00000c01      0c             invalid
            0x00000c02      1e             invalid
            0x00000c03      0cff           and r15, r12
            0x00000c05      3fb2           bit #8, r15
[0x00000c00]> 
```

A proper disassembly would look something like this:
```
tmg% r2 -a msp430 -m 0x0c00 foo
[0x00000c00]> pdx 5
            0x00000c00      060c         invalid
            0x00000c02      1e0c         invalid
        └─> 0x00000c04      ff3f         jmp $-0x0000
[0x00000c00]> 
```

The length of 1 seems to be presumed whenever `msp430_decode_command()` returns -1 for an invalid instruction.  I'm unsure whether the appropriate fix is to have it return a two-byte instruction called "invalid" or to specify the alignment elsewhere in the processor module.

**Comment by Maijin** [comment]
Hi there o/ Can you check if @prazzb fix fixes your issue ?

**Comment by travisgoodspeed** [comment]
Yup, this fixes it right up.  Thanks, @prazzb!
