### ISSUE TITLE
Add ability to compare hash in rehash2 and change return value

### ISSUE THREAD

**Issue by radare** [radare/radare2#4126]
```
rahash2 -a md5 -c 0f8b42328d7d9e430208e733e6151675 /bin/ls
```

This will calculate the checksum of /bin/ls and compare it with the given hash with -c.

the return code will be 0 if they are the same, and 1 if not.

**Comment by stanciuadrian** [comment]
I started working on this.

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
This was implemented here https://github.com/radare/radare2/pull/4135
