### ISSUE TITLE
Radare2 is not as cool as PEStudio

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#4128]
See its [features](https://www.winitor.com/) page

Add command for print Indicators like in PEStudio (i.e display version information that are already parsed). For example:

![image](https://cloud.githubusercontent.com/assets/1186777/13176670/fc0fe4d6-d724-11e5-81f3-d2be71bd5741.png)

- Filter and flag potential malware and antidebug functions from imports (GetWindowThreadProccesId, ...)

All this indicators, functions and signatures of packers are in xml files for this soft. You can download PEstudio from [official site](https://www.winitor.com/) or only [xml files](https://yadi.sk/d/eSzS6zYsp7iNV)

**Comment by Maijin** [comment]
Is indeed very interesting to print all the information from a binary elf/pe/mach0 but is definitely not r2 job to determine if malicious or not, this could be done by an external plugin + quid licence of the xml files, I highly doubt this can be shared ?

**Comment by radare** [comment]
yeah, this should be done with r2pipe or something, maybe a separate tool on top of r2

**Comment by Maijin** [comment]
Closing this as it is somehow part a duplicate for #921 and part another tool to be built on top of r2 and not an issue for r2 repository.
