### ISSUE TITLE
Follow stack and registers, do patterns detection.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#4137]
Am I missing something very important about r2?

1) Please do something with the simple tricks to prevent disassembly. Simple example is a "push" + "ret" combination. Is it so difficult?

2) I would like to see a simple stack and registers analyze to have comments on the registers and stack ("push", "ESP")  change operations, as well as the "call" that are changed in the "call".
Such call:
` 0x00401251      e884110000     call fcn.004023da           ;[4]    `
would change to:
` 0x00401251      e884110000     call fcn.004023da           ;[4]; args: ecx(0x00401218 "0x406c3c", 0x0040121a "0x406c44"), edx(0x0040120e "0x10")`

There could also be comments on the instructions pointing to the next function that is modifying their values.

3) I would prefer that there would be a simple way to add code "assembly" signatures to r2 that are recognized by analysts using the tool. Lets say someone is analyzing an executable and finds some interesting trick in the code or identifies the code part to do some staff. Please add a simple possibility for this analyst to give a feedback to community and "automatically" submit a "simple" signature to recognize such pattern with his comments.
Maybe some simple command that would send the analyzed instructions with comments for signature generation. Or there should be a pattern matching signature file. Lets discuss it in comments.

Please consider my suggestions. I really find r2 a great tool and want to contribute where I can.

Sincerely,
Tolik

**Comment by radare** [comment]
e asm.emu=true

**Comment by MariasStory** [comment]
Sorry to take so much time to follow on this feature request.
From all the tests I have done so far it seems that the "e asm.emu=true" option is a work in progress. At the moment though it is mostly confusing than helpful.

Please correct me if I am wrong.

I'll take a closer look on the code when I'll have a bit more time.
Maybe you could give some hints how to improve the features in the code?

What are the plans in this direction?

Greetings,
Tolik

**Comment by radare** [comment]
asm.emu is not work in progress. it works as it should, you will need to initialize the stack if you want to follow push/pop data movements otherwise you’ll get tons of fffffff.

the esil emulation works quite fine already, but there’s always room for improvment. what suggestions do you have on this field?

**Comment by MariasStory** [comment]
So, I would like to comeback to the point. Let's compare the simple function call.
r2:
![image](https://cloud.githubusercontent.com/assets/6576335/14141936/b4638a0c-f682-11e5-9bf0-1c5a9edb0daf.png)
Ida free (old):
![image](https://cloud.githubusercontent.com/assets/6576335/14141944/c2b57584-f682-11e5-97ee-c4784207855c.png)
r2 (e asm.emu=true):
![image](https://cloud.githubusercontent.com/assets/6576335/14141951/d1984e78-f682-11e5-91fc-c232d7639257.png)

Can't we recognize the parameters?
Maybe I am missing some important point there?

**Comment by XVilka** [comment]
This is why we have this GSoC taks this summer: http://radare.org/gsoc/2016/ideas.html#title_3

**Comment by Maijin** [comment]
Yep duplicates of #3655 please subscribe to this one to show support !

**Comment by radare** [comment]
if you dont initialize the stack you will never see the values that are pushed in there. run aeim

**Comment by radare** [comment]
The push;ret thing works with emulation. and i can add a simple hack to handle push+ret as jmp but this will be wrong if there are jumps right into the ret, as well as this construction can be computed in several ways, not just push+ret. So i would recommend you to write a script to patch this using anal hints for example to fit in your problem

**Comment by radare** [comment]
the push + call pattern is only done by microsoft compiler. i do no windows reversing, so i've never find this necessary for me. but in order to handle function parameters detection and handle proper function signatures there's a GSoC, which will hopefully be read after the summer.

**Comment by radare** [comment]
use the 'z' command to create the signatures you need. if i understood you correctly this is already done in there

**Comment by radare** [comment]
Also, try to not fill issues discussing over 9000 topics, or some of them will be forgotten/ignored
