### ISSUE TITLE
write string "@executable_path" error

### ISSUE THREAD

**Issue by juneJuly** [radare/radare2#4142]
when write string "@executable_path/XXXXX" 
return error with "Invalid address (executable_path/XXXXX)"

so, how to write a string with "@"

**Comment by juneJuly** [comment]
my current solution is "write \x40"

**Comment by radare** [comment]
you can also quote the entire command like this:

`"w @executable_path/XXXX"`

**Comment by juneJuly** [comment]
@radare 
in fact i did,  and return error with "Invalid address (executable_path/XXXXX)"

**Comment by radare** [comment]
if you get this error is because you didnt quoted the command. try again with exact line i pasted there

**Comment by juneJuly** [comment]
@radare 
thx for help.
but still not work for me, i got another solution, it's just enough.
