### ISSUE TITLE
Print signed values

### ISSUE THREAD

**Issue by radare** [radare/radare2#4144]
We need a way to show byte, word, dword, qword signed values from immediate or memory. not sure if will be better if we just  an hexdump-like view but using (st32) before printing it

* [x] Honor cfg.bigendian
* [x] Add more tests
* [x] Add pxd[X] to specify the size of the decimal words
* [ ] Add documentation for all this stuff
* [ ] Support signed sized values in pf

**Comment by radare** [comment]
some work on this here 0f211141124f75b1547f85ebf3c6e3bf74c8c7b7

**Comment by radare** [comment]
* [ ] Honor cfg.bigendian
* [ ] Add more tests
* [ ] add pxd[X] to specify the size of the decimal words

**Comment by radare** [comment]
added pxd[124] in 35af84c9786612a4b74ec9d92e25fa1dd897a6ef so current functionality is done. just need some more tests and documentation. cc @Maijin

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/3223

**Comment by radare** [comment]
Basic support for this thing is done, let's move this for 0.10.2 to finish the final details

**Comment by Maijin** [comment]
So what about the issue with the offset "ruller" ?

```
[0x00000000]> pxd1 16 ; pxd2 16 ; pxd4 16
0x00000000    65   65   65   66   65   65   67   65   65   68   65   65   69   65   65   70  AAABAACAADAAEAAF
0x00000000    16705   16961   16705   16707   17473   16705   16709   17985  AAABAACAADAAEAAF
- offset -    0  1   2  3   4  5   6  7   8  9   A  B   C  D   E  F  0123456789ABCDEF
0x00000000     1111572801    1094926657    1094796353    1178681669  AAABAACAADAAEAAF
```

**Comment by radare** [comment]
Dunno whats a ruller

**Comment by Maijin** [comment]
Really

```
- offset -    0  1   2  3   4  5   6  7   8  9   A  B   C  D   E  F  0123456789ABCDEF
```

**Comment by radare** [comment]
i call it header, and reading the mail from the phone it looked like crap

**Comment by Maijin** [comment]
So, what about the header

**Comment by radare** [comment]
btw, how many differences do i have to find in this picture?. there's one missing fruit in the bottom-right corner

**Comment by radare** [comment]
ah! the buterfly in the cloud , right on top of the mouse head!

**Comment by radare** [comment]
and the flower in front of the ladybug

**Comment by Maijin** [comment]
xD ok, but what about the header, removed or not removed.

**Comment by radare** [comment]
you are not really helpful in finding the real problem, there's a LADYBUG, A FUCKING LADYBUG

**Comment by Maijin** [comment]
Grass on the left is missing and beard/hair of the lion is different

**Comment by XVilka** [comment]
I've found LADYBUG too:
![](http://nick.mtvnimages.com/nick/properties/miraculous/season-1/characters/miraculous-ladybug-about-web.jpg?quality=0.75)

**Comment by radare** [comment]
this thing you mean? https://github.com/radare/radare2/commit/b56d1c01bf2f58fcd2d5cb54067b73973f21e511

**Comment by radare** [comment]
can you write tests for this? the current print_hexdump_header thing is quite complex and im afraid of having regressions when cleaning it up

**Comment by radare** [comment]
ping @Maijin

**Comment by Maijin** [comment]
test have already been pushed ;)

**Comment by Maijin** [comment]
See this issue @balzarot

**Comment by balzarot** [comment]
@maijin are you talking about the ladybug or the ruler? 
I guess you want me to add a ruler for afM, is that right?

And btw, why is this issue still open? 
pxd1,2,4 all have a ruler. 

And what's up with pdx8 ... it prints little penises (and the rulers is off-sync) ?! :)

    [0x00401340]> pxd8
    - offset -   0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
    0x00401340      8===D     8===D     8===D     8===D  ...St.1......H.>
    0x00401350      8===D     8===D     8===D     8===D  H........5?@....
   0x00401360      8===D     8===D     8===D     8===D  .........?@...?@

**Comment by radare** [comment]
Congratulations!!

You are the first to find the new easteregg!

**Comment by Maijin** [comment]
@balzarot the ruler thing is fixed now. just see the still open

* [ ]  Add documentation for all this stuff
* [ ] Support signed sized values in pf
* [ ] Honor cfg.bigendian

**Comment by radare** [comment]
endianness support in fbdbd09b262bf118df5f0d4dee93343d4a346c0f
pxd8 implemented in b5e57379cde163954d25d3336c533267bff05579

**Comment by Maijin** [comment]
@P4N74 maybe?

**Comment by P4N74** [comment]
@Maijin for `Support signed sized values in pf`, signed values are already supported. Format chars `i` and `f`. I was not able to find the unsigned values support. Also I am looking into pf for adding a anon struct declaration (can be used for nested struct)

**Comment by Maijin** [comment]
@radare then we can close?

**Comment by radare** [comment]
nope. pf doesnt supports char, short signed and long int signed values, only floating and 32bit

**Comment by P4N74** [comment]
@radare pf supports char and unsigned char. format: `c` and `b`

**Comment by radare** [comment]
then st16 and st64 are missing

**Comment by radare** [comment]
and maybe cleaner documentation

**Comment by P4N74** [comment]
not only that, st16, st64, ut64, ut32 and double (64 bit)
nested anon pf is now supported :) (i will push it after fixing some more stuff in pf)

**Comment by radare** [comment]
kewl! dont forget to add some tests

**Comment by Maijin** [comment]
@P4N74 just add documentation in pf?? and that should do the trick
