### ISSUE TITLE
arm64 zr and sp equivalence

### ISSUE THREAD

**Issue by mrmacete** [radare/radare2#4151]
just noticed that `sp` and `zr` registers just share the same memory.
Is this correct? i guess is for what is written here:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/ch04s01.html

> There is also a restricted group of instructions where one or more of the arguments are encoded such that number 31 represents the Stack Pointer (SP).

but isn't it already handled in capstone?

in order to do correct math we need wzr, xzr, zr to be zeroes... the straightforward way would be to decouple sp and zr, but what will this break? 

does someone have a proper test case for this? (or some code which can be coverted to a test case?)

**Comment by radare** [comment]
From my understanding some instructions handle the 31th register (aka SP) as the zero register. so imho this is a bug in capstone, well, a feature enhancement :P 

we can change the register profile to handle zr in a separate region.. also there's no way to tell r_reg that a specific register is wired to ground. This is also happening in MIPS. and i think it's something we should handle. 
 
https://www.element14.com/community/servlet/JiveServlet/previewBody/41836-102-1-229511/ARM.Reference_Manual.pdf

**Comment by mrmacete** [comment]
ok, i can start writing some broken test in regressions, and then file a pull request for separating them in reg profile. is it ok?

**Comment by radare** [comment]
sure :)

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/4156
