### ISSUE TITLE
Arm thumb incorrect base of PC-rel load

### ISSUE THREAD

**Issue by aeickho** [radare/radare2#4158]
The following testcase contains two PC-relative loads, both loading constant zeros from [PC+0], in the first case, radare2 incorrectly interprets the address, indicating a load of -1 from the word following the correct address.

With:
radare2 0.10.0 10303 @ linux-little-x86-64 git.0.10.0-139-g79c09b4
commit: 79c09b43560e3b7a1827ee97a027c1de27196293 build: 2016-02-15

![f2](https://cloud.githubusercontent.com/assets/986535/13269198/cff4715e-da86-11e5-8ec7-13a3484d1704.png)

# Output of radare2
[0x00000034]> pd 10
    ;-- main:
            0x00000034  ~   dff80000       ldr.w r0, [pc, 0]           ; [0x3c:4]=-1 ; '<'
    ;-- section_end..ARM.attributes:
            0x00000038  ~   0000           movs r0, r0
            0x0000003a      0000           movs r0, r0
            0x0000003c      ffffffff       invalid
            0x00000040      0000           movs r0, r0
    ;-- $t_1:
            0x00000042      0048           ldr r0, [pc, 0]             ; [0x44:4]=0 LEA loc._d_1 ; loc._d_1
    ;-- $d_1:
            0x00000044      0000           movs r0, r0
            0x00000046      0000           movs r0, r0
            0x00000048      ffffffff       invalid
    ;-- $t_2:
            0x0000004c      7047           bx lr

# Output of arm-none-eabi-objdump (GNU objdump (2.25-5+5+b1) 2.25)
00000000 <main>:
   0:   f8df 0000       ldr.w   r0, [pc]        ; 4 <main+0x4>
   4:   00000000        .word   0x00000000
   8:   ffffffff        .word   0xffffffff
   c:   0000            .short  0x0000
   e:   4800            ldr     r0, [pc, #0]    ; (10 <main+0x10>)
  10:   00000000        .word   0x00000000
  14:   ffffffff        .word   0xffffffff
  18:   4770            bx      lr
  1a:   bf00            nop

# assembly soure 
```

        .syntax unified
        .cpu cortex-m4
        .eabi_attribute 27, 3
        .eabi_attribute 28, 1
        .fpu fpv4-sp-d16
        .eabi_attribute 20, 1
        .eabi_attribute 21, 1
        .eabi_attribute 23, 3
        .eabi_attribute 24, 1
        .eabi_attribute 25, 1
        .eabi_attribute 26, 1
        .eabi_attribute 30, 2
        .eabi_attribute 34, 1
        .eabi_attribute 18, 2
        .thumb
        .file   "nullprog.c"
        .section        .text.startup,"ax",%progbits
        .align  2
        .global main
        .thumb
        .thumb_func
        .type   main, %function
 main:
        @ args = 0, pretend = 0, frame = 0
        @ frame_needed = 0, uses_anonymous_args = 0
        @ link register save eliminated.
        ldr.w   r0, [pc, #0] @wide load-instruction, 4-byte aligned
        .word 0
        .word -1
        .short 0
        ldr     r0, [pc, #0] @narrow load-instruction, 2-byte aligned
        .word 0
        .word -1
        bx      lr
        .size   main, .-main
        .ident  "GCC: (4.8.4-1+11-1) 4.8.4 20141219 (release)"

```
## Assembled with
arm-none-eabi-gcc -mlittle-endian -mthumb -mcpu=cortex-m4 -mthumb-interwork -mfloat-abi=hard -mfpu=fpv4-sp-d16 -fshort-wchar -c nullprog.s -O2

tnx to @sklamt and uwe

**Comment by radare** [comment]
this is probably because of the flags in the middle of instructions. try with `e asm.midflags=0`

**Comment by radare** [comment]
also, a testcase is welcome

**Comment by aeickho** [comment]
![f2](https://cloud.githubusercontent.com/assets/986535/13319669/98ff23d6-dbc3-11e5-8b1a-2a5e61197570.png)

**Comment by radare** [comment]
Sorry i misunderstood the issue. this thing should be fine now. this is a regression that happened after changing the meaning of `pc` in the analysis context.

**Comment by radare** [comment]
i have added a test case for this

**Comment by aeickho** [comment]
radare2 0.10.0-git 10417 @ linux-little-x86-64 git.0.10.0-253-g99c200b
commit: 99c200b9c3ae3a6a4c7c08198a6c97ceadf30e4c build: 2016-02-25

sorry, maybe we have a big  misunderstanding but with your patch "my" problem is not be solved

this is an real code snipped:  
_the r2 "address comment" in .. 0x0800d8e0, ..  0x0800d8f6, 0x0800d90c  is not calculated correctly
the output from objdump is correct _

![f2](https://cloud.githubusercontent.com/assets/986535/13326332/b4d4d476-dbe5-11e5-8040-0875d0c8ac08.png)

**Comment by radare** [comment]
Uhm.. So pc is not preincremwnted in this instruction? We should -8 instead  of -4 then...

**Comment by radare** [comment]
Try again, i added 3 more tests and tested on real hardware with thumb code, i should test the unaligned loads because i guess the arm mmu is being strict on that.

I have changed the analop info and the esil expression.

In esil, the pc is preincremented like in real cpus, so theres no need to increment the value of pc

**Comment by aeickho** [comment]
tnx
![f2](https://cloud.githubusercontent.com/assets/986535/13356839/bb674f4a-dca7-11e5-966b-91ee9f62727b.png)

**Comment by radare** [comment]
👍
