### ISSUE TITLE
Can't debug r2 if sys/user.sh

### ISSUE THREAD

**Issue by radare** [radare/radare2#4168]
This is because `r2` is a shellscript baked by env.sh, so you need to run `env.sh gdb --args r2 ..` or maybe we can just add another script named `gdb-r2` and `lldb-r2`, but the proper way would be to just handle an env var or also wrap gdb and lldb to catch those cases

**Comment by ret2libc** [comment]
fixed with 2f306d01a3291e31a021668474c0a7ac204234fc
