### ISSUE TITLE
Reverse cmd in rap

### ISSUE THREAD

**Issue by radare** [radare/radare2#4173]
We need a way for rap servers to run commands in r2 host. something like this:
```
r2 <----> rap://target
> CMD(x)
< CMD(y)
> CMD|REPLY(res-y)
< CMD|REPLY(res-x)
```

**Comment by radare** [comment]
This will be useful when writing debug backends using rap://, so the io plugin can run r2 commands to change register values and stuff like that. we should slowly redesign this to support remote debuggers in a better way

**Comment by jarusified** [comment]
I am interested in solving this? This is my idea right now, Basically When the host is Listening for Incoming Connections, I Should use (select() or new thread) for reading from stdin and pass that to existing functions right?? (tell me if this is the right path?)

**Comment by XVilka** [comment]
@jarusified radare2 already has it's own API to talk via the network - see libr/include/r_socket.h for API and libr/socket/*.c for implementation.

**Comment by jarusified** [comment]
@XVilka  will use that. But is the overall understanding of the issue correct?

**Comment by XVilka** [comment]
@jarusified there yes, just add the answering part.

**Comment by radare** [comment]
you can test this by doing:
```
$ r2 rap://:9999
```

and then:

```
$ r2 rap://localhost:9999//bin/ls
```

the idea behind this issue is to review/cleanup/document the rap protocol
and add support for the server side to issue commands in the host one. This
will be easier to test/implement if done in python or nodejs, there are
already implementations of that protocol for them.

This is important because it will allow non-r2 rap servers to tell r2 which
commands to run to set flags, change register state, emulate step, etc.
Only the command packet makes sense to be bidirectional imho.

On 16 March 2016 at 16:00, Anton Kochkov <notifications@github.com> wrote:

> @jarusified <https://github.com/jarusified> there yes, just add the
> answering part.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4173#issuecomment-197370400>
>



-- 
--pancake

**Comment by jarusified** [comment]
initial fix : https://github.com/radare/radare2-bindings/pull/107

**Comment by radare** [comment]
It's good to have this fix in python, but the proper fix should be in core, are you planning to do it too?

**Comment by jarusified** [comment]
yes, i am planning to the same.

**Comment by radare** [comment]
cool!

**Comment by radare** [comment]
ping. any update on this?

**Comment by radare** [comment]
PING

**Comment by radare** [comment]
ping @jarusified

**Comment by radare** [comment]
Done in master
