### ISSUE TITLE
xref doesn't work on arm32

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4184]
On IDA pro:

<img width="578" alt="screen shot 2016-02-27 at 15 39 41" src="https://cloud.githubusercontent.com/assets/1408600/13373462/fa385450-dd68-11e5-85e0-79913064be39.png">

On radare2 after a r2 -A

<img width="1022" alt="screen shot 2016-02-27 at 15 39 55" src="https://cloud.githubusercontent.com/assets/1408600/13373465/fc864ef6-dd68-11e5-8611-0885c73b6afe.png">

Here is the binary:

![chall9](https://cloud.githubusercontent.com/assets/1408600/13373481/6150fc28-dd69-11e5-970b-7f9a2e8804f0.jpg)

**Comment by radare** [comment]
use aae like normal people does when analyzing code that construct data references by several chained instructions and taking delta pointers from memory. Feel free to add it into the aaa command. i will never use that, but aae is quite stable now.

also, ida is retarded and shows two references, when its in fact only one chained with another one. so r2 does right here.

**Comment by Maijin** [comment]
Well obvious for you, not for the rest of the people :p

**Comment by Maijin** [comment]
I'm adding it to aaa

**Comment by radare** [comment]
people sucks

**Comment by redfast00** [comment]
aae just spits out a bunch of "0xaddress invalid interrupt/syscall 0xaddress"

**Comment by radare** [comment]
it also creates references internally, the output is because its trying to run data as code because it makes a linear emulation of the code. we should scr.null=true before running aae in aaa to avoid scaring users

**Comment by redfast00** [comment]
So, I am looking for any refs to the string "73vjackakblablabla". I think it's used as a salt in a hash. So I set asm.emu to true, ran aae, and then ran pd~73vjackakblablabla . Still doesn't output a thing.

**Comment by Maijin** [comment]
for xref you need to use axt

**Comment by radare** [comment]
you dont need to set asm.emu to true to run aae.

its only needed for the pd~str thing.

if this is not shown can be for different reasons:

* this string is referenced by a pointer table, so the linear emulation and data references are not found
* the string is taken after an offset. so you can find the closest reference before that string
* the reference is non aligned and you should grep for a portion of that string
* the reference is constructed by a reference from a delta table

Please, try to find that reference in IDA or Hopper and if it’s found paste here where the reference comes from and i’ll evaluate the best way to analyze that case.

Another way to find that reference is by using hardware breakpoints and running the program on real hardware.

**Comment by redfast00** [comment]
https://drive.google.com/file/d/0B4Wy3AomuX2qY3Zzc0FhS0d4NXc/view?usp=sharing . I am almost sure the string is aligned. The actual string is "73vjaclg3287tdskj".

**Comment by radare** [comment]
tried with hopper demo and it cant find the xrefs either. if someone have ida
will be good to have some feedback o nthis

> On Feb 27 2016, at 4:28 pm, redfast00 &lt;notifications@github.com&gt;
wrote:  

>

> <https://drive.google.com/file/d/0B4Wy3AomuX2qY3Zzc0FhS0d4NXc/view?usp=shari
ng> . I am almost sure the string is aligned. The actual string is
"73vjaclg3287tdskj".

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/radare/
radare2/issues/4184#issuecomment-189665310).![](https://github.com/notificatio
ns/beacon/AA3-lhqF6nt4UpSHEq46c0RlRyjck4chks5pobgzgaJpZM4HkgJh.gif)
