### ISSUE TITLE
Scroll below address 0 in visual mode shouldnt be possible

### ISSUE THREAD

**Issue by radare** [radare/radare2#4190]
This is a regression introduced recently. Way to reproduce:

```
r2 -
V
kkkkkk
```

same behaviour in cursor mode

**Comment by codido** [comment]
Seems this was fixed for regular visual mode but not for cursor mode:

```
r2 -
Vpc
kk
```

**Comment by Maijin** [comment]
@codido please open another issue.

**Comment by radare** [comment]
Its ok no need to open more issues. The fix is simple. But im afk, if anybody manages to fix this before the moon raises at gmt+1 send a pr. Its just one line, the challenge is to find it :p
