### ISSUE TITLE
Add aae in aaa

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4191]
In order to get xrefs in ARM32 binaries https://github.com/radare/radare2/issues/4184 

* [x] Add a warning message at the end of aaa something like "Use aaaa for more experimental analysis engine"
* [ ] Create r2 -AA for aaaa

**Comment by EliaGeretto** [comment]
I'm looking into this one. Suggestions are welcome.

**Comment by Maijin** [comment]
Well the issue #4184 is quite well documented, you can check the binary I provided and see if you can manage to get the xref after the aaa [once you have added aae in it]
Here is where the aaa is https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3548

**Comment by Maijin** [comment]
@EliaGeretto Don't forget that as well https://github.com/radare/radare2/commit/6b6fca7b656dd5af57b8f3a746ec25daab580e94

**Comment by Maijin** [comment]
Don't forget also to add https://github.com/radare/radare2/commit/fbb1b1e80ff343c14f095a340ef53b977ebfc943

**Comment by EliaGeretto** [comment]
Ok, I was able to insert aae into aaa and to get the missing xrefs with aaa. Now aaa is also printing the same errors reported in #4184. Should I set scr.null to true before executing aae in aaa for every arch or only for arm and mips? Could you be more specific about the conditions?

**Comment by Maijin** [comment]
@EliaGeretto `if (arm || mips && textsection < 1MB)` <- Condition to execute aae. just remove the display of it by enabling scr,null before and disabling after.

**Comment by radare** [comment]
Done in aaaa

**Comment by radare** [comment]
i think scrnull is better not to touch it, because current warnings are important.

**Comment by EliaGeretto** [comment]
OK, so this issue is closed? I'll just delete everything?

**Comment by Maijin** [comment]
I would say instead of aaaa replace with `if (arm || mips && textsection < 1MB)`

**Comment by EliaGeretto** [comment]
Just to be clear, now "aaaa" executes "aae" and "aat", the last one two times. Where would you place that condition given that it was decided to keep the warnings? If you want "aaa" to execute "aae" isn't it better to simply eliminate the new if?

**Comment by radare** [comment]
I think is better to keep aaaa and not put hidden restrictions that change the behaviour qhich makes r2 less predictible

**Comment by Maijin** [comment]
I don't agree with that, I would remove aaaa and put the condition instead.

**Comment by radare** [comment]
Users will be confused by why some bins run some analysis and others dont. As well as the user will have no choice to choose what to do

**Comment by Maijin** [comment]
Well, people are confuse anyway  https://github.com/radare/radare2/issues/4184

**Comment by radare** [comment]
we can confuse them even more by adding some meaningless sentences and sleep(random()) in there too. good idea

**Comment by Maijin** [comment]
Or just a simple message about the conditions and say to the user that since it's experimental feature he has to run it manually but can run everything with aaaa

**Comment by Maijin** [comment]
Until a better way of having aaa doing really everything is found

**Comment by ret2libc** [comment]
We could keep using aaa and add yet another var (enabled by default) to enable/disable the new aae feature. I believe too that adding another aaaaaaa command is not good

**Comment by Maijin** [comment]
@ret2libc @radare To make everyone happy, what about this for some time until a good fix is done on all those commands: 
If section is < 1MB
`[x] Text Section < 1 MB detected, running extended analysis automatically`
`[x] Emulate code to find computed references (aaa)`
`[x] Finding function by preludes (aap)`
`[x] Analyze consecutive function  (aat)`
`[x] Text Section > 1 MB detected, extended analysis disabled to avoid you can launched`
If section is > 1MB
`[x] Text Section is > 1MB, extra analysis not run to avoid infinite time you can run it manually using aaaa`

**Comment by radare** [comment]
aae is unusable on big binaries mainly because it takes lot of time to emulate all the code, but this is something that must be up to the user, because even if the bin is big maybe he wants to do that. also, we should detect static linked stuff and reduce the size of code to be analized. maybe fill another issue for that

**Comment by Maijin** [comment]
That's why
`[x] Text Section is > 1MB, extra analysis not run to avoid infinite time you can run it manually using aaaa`

**Comment by Maijin** [comment]
@EliaGeretto So after discussion on Telegram:

* [ ] Add a warning message at the end of aaa something like "Use aaaa for more experimental analysis engine"
* [ ] Create r2 -AA for aaaa
