### ISSUE TITLE
Graph edges breaking in OSX 10.11

### ISSUE THREAD

**Issue by egyp7** [radare/radare2#4200]
I'm report for this bug wich presented in last version of radare2. Broken graph edges marked with red lines(and red circle) in next screenshot:
http://i.imgur.com/BBfxz1Q.jpg

OSX 10.11, default Terminal application.

**Comment by XVilka** [comment]
Related to https://github.com/radare/radare2/issues/3794 and https://github.com/radare/radare2/issues/2091

**Comment by Maijin** [comment]
Please register/comment on the existing issue
