### ISSUE TITLE
Process Animation in debug mode radare2

### ISSUE THREAD

**Issue by YHVHvx** [radare/radare2#4201]
I'm interesting also for animate into/over opportunities in radare2 for process animation like Olly Debugger(Ctrl+F7/F8). This is really cool and interesting future(mainly for productivity) for dynamical application analysis wich must be presented in next release radare2!

**Comment by Maijin** [comment]
This is already done in Visual mode

**Comment by Maijin** [comment]
I'm closing unless you get more specific
