### ISSUE TITLE
Broken menu in Debug Interface on OSX 10.11

### ISSUE THREAD

**Issue by egyp7** [radare/radare2#4202]
I'm tried use new undocumented interface in radare2 for application debugging, but i get some troubles with menu action in OSX 10.11 iTerm 2. For use this radare2 mode, i'm switch debug mode with <SHIFT> + F1 keys combination and goto menu with <M> key. But when i try access into menu options menu is closed and console is fuckuped. At next screen i'd try show it without action:
http://i.imgur.com/teUgIhs.jpg

i hope it will be fixed at next release :)

**Comment by radare** [comment]
It is not broken, use right-left arrows to select panel and up/down to select option, if you run V! you and then press 'j' the menu will drop down. You can also use tab and shift-tab to select next/previous panel. the 's' for stepping works as expected. whats the issue you are having?

**Comment by radare** [comment]
i'm closing this as long as i don't see a real issue here
