### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Th4nat0s** [radare/radare2#4203]
Hello got this this morning on the make

make[3]: Entering directory '/home/user/code/radare2/libr/bin'
gcc -c  -MD   -fPIC -g -Wall -D__UNIX__=1 -DCORELIB -Iformat -Imangling -I/home/user/code/radare2/libr/../shlr/zip/include -I/home/user/code/radare2/libr/include -o bin.o bin.c 
In file included from bin.c:12:0:
../config.h:143:7: error: ‘r_bin_xtr_plugin_dyldcache’ undeclared here (not in a function)
      &r_bin_xtr_plugin_dyldcache, \
       ^
bin.c:37:52: note: in expansion of macro ‘R_BIN_XTR_STATIC_PLUGINS’
 static RBinXtrPlugin *bin_xtr_static_plugins[] = { R_BIN_XTR_STATIC_PLUGINS };
                                                    ^
/home/user/code/radare2/libr/../global.mk:43: recipe for target 'bin.o' failed
make[3]: *** [bin.o] Error 1
make[3]: Leaving directory '/home/user/code/radare2/libr/bin'
Makefile:82: recipe for target 'bin' failed
make[2]: *** [bin] Error 2
make[2]: Leaving directory '/home/user/code/radare2/libr'
Makefile:28: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/user/code/radare2/libr'
Makefile:47: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by radare** [comment]
Are u using sys/install.sh?

**Comment by Th4nat0s** [comment]
Houps.. of course not.. but it was working until now with a make... I
will try the script.

**Comment by radare** [comment]
The script makes a clean build every time. Sometimes the .d files keep referencing unused files which causes this error if not cleaned properly

**Comment by radare** [comment]
Also sys/install.sh installs in /usr or /usr/local in osx using symlinks. So you dont have to reinstall if u are doing changes in the code

**Comment by Th4nat0s** [comment]
It's on a linux ubuntu 15 and a make clean was issued before.  I will
try the script thursday.

Thank's

**Comment by radare** [comment]
Ah then i guess its because you didnt remove plugins.cfg before configure-plugins

**Comment by Th4nat0s** [comment]
sys/install.sh works flawlessy :) !
