### ISSUE TITLE
Implement modifications of fastcall-style function arguments

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4204]
When arguments stored in registers, they should have working commands 'afA*' exactly like 'afa*'.

**Comment by oddcoder** [comment]
could you please add extra information !!

**Comment by radare** [comment]
This task is about implementing the `afA` command. As long as fastcall depends on the ABI we can assume that we only need the number of arguments and the types of each. for example:

```
s sym.imp_syscall_write
afA 0 fd int
afA 1 str char*
afA 2 len int
afA 3 oops int
afA-3   # remove last arg
```

When disassembling a function, the disassembler loop must grab this information, if there's any fastcall argument defined it will use the rsyscall api to get the corresponding register and show it in the comments on the top of the function.

Also, as a bonus point, it will be good to enhance the help message of the `afv?` and `afa?` commands.
