### ISSUE TITLE
pf. command cannot displaying format file ? :|

### ISSUE THREAD

**Issue by febriyantonugroho** [radare/radare2#4211]
why file format does not appear on the screen? 

![screenshot from 2016-02-26 19_55_08](https://cloud.githubusercontent.com/assets/11923154/13493208/544f05b0-e16f-11e5-9e23-0e8952b158f4.png)

**Comment by Maijin** [comment]
What version of r2 are you using. Please paste r2 -v

**Comment by radare** [comment]
Looks like the 4 year old shipped in ubuntu

**Comment by febriyantonugroho** [comment]
my r2 version is 0.9.6

**Comment by Maijin** [comment]
Please read the guidelines https://github.com/radare/radare2/blob/master/CONTRIBUTING.md before reporting issues, this is fixed in the git version please use that. 

git clone https://github.com/radare/radare2/ && cd radar && ./sys/install.sh

**Comment by febriyantonugroho** [comment]
thank you :))
