### ISSUE TITLE
r2pm installing radeco states cargo error

### ISSUE THREAD

**Issue by ril3y** [radare/radare2#4223]
Hey guys I am not sure this is an actual issue but when installing radeco from r2pm it complains that cargo is not found.

~/Desktop $ r2pm -i radeco
Processing radeco ...
Already up-to-date.
Install Done For radeco
**_/usr/local/bin/r2pm: 9: /usr/local/bin/r2pm: cargo: not found
/usr/local/bin/r2pm: 10: /usr/local/bin/r2pm: cargo: not found_**

FYI. I am running the git version on linux mint.  This is the last commit. 797a675b456bbc00ff870a086bb9b99a5adf03a3

**Comment by radare** [comment]
You need to install rust :P i have pushed a fix for this
