### ISSUE TITLE
Should we consider the allocation of CVEs?

### ISSUE THREAD

**Issue by revskills** [radare/radare2#4238]
I love this project, but as a user **concerned about security** I want to know the status of patches and potential vulnerabilities that may affect radare2* (internal code, external components or just c&p code). I understand that this adds new tasks, but unlike any other reversing framework or tool is a way to **motivate the user to update** not only because bugfixes, new arch, whatever. Likewise this **helps linux distributions to push updates**.

**Thoughs?**

Eg: libmagic, regex library, etc that we are not fixing at all

**Comment by revskills** [comment]
Regarding #4234

**Comment by radare** [comment]
Yes, I think that this will be very interesting, because, as long as we are using some third-party libraries we shuold inform the users and be aware of backporting those fixes from capstone, grub, magic, etc...

**Comment by Maijin** [comment]
ok closing this then.
