### ISSUE TITLE
afl output must be sorted by offset

### ISSUE THREAD

**Issue by radare** [radare/radare2#4248]

**Comment by EliaGeretto** [comment]
I'm willing to complete this one. I was thinking about retrieving a copy of the function list and ordering it before this iteration: https://github.com/radare/radare2/blob/master/libr/core/anal.c#L1235 Where should I put the comparator? In the same file?

**Comment by radare** [comment]
Use r_list_sort and pass the callback that compares the offsets. Yes

**Comment by chinmaydd** [comment]
@EliaGeretto I am sorry but I was working on this already, I hope you don't mind. #4252 aims at solving this issue.

**Comment by radare** [comment]
This is done. It can be optimized by not sorting on every listing, but it's ok for now
