### ISSUE TITLE
pd and pdj stops at two different addresses

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#4263]
```
$ r2 ./r2r/main
> pd 300 # look at the last adress, it is 0x00400760
> pdj 300 # look at the last address, it is 4195488 == 0x4004a0
```
Those two addresses should be the same.

**Comment by radare** [comment]
do blocksize affects this result? who is right? can we have tests?

**Comment by ret2libc** [comment]
pd is right... pdj just prints only 20 lines more or less.

I will do tests soon.
