### ISSUE TITLE
Enable demangle by default

### ISSUE THREAD

**Issue by radare** [radare/radare2#4266]

**Comment by radare** [comment]
Add a way to disable it from `$ r2`

**Comment by Maijin** [comment]
+1 on this one `e bin.demangle = true` by default ? And if user want to disable then he have to use `e bin.demangle = false` in the config file or command prompt until it is properly fixed.

**Comment by Maijin** [comment]
Also, until the possibility to enable/disable without relaunching is fixed, why not just adding in e? bin.demangling something like "to disable, add e bin.demangling=false in cmdline or config file".

**Comment by XVilka** [comment]
`r2 -M /bin/idaq` to disable demangle. And :+1: for enabling it by default. And not only bin.demangle but also asm.demangle too.

**Comment by radare** [comment]
Ok for -M and put it by default. Can anyone send a pr? Let travis tell us what we break
