### ISSUE TITLE
Change rc filenames

### ISSUE THREAD

**Issue by radare** [radare/radare2#4268]
`~/.config/radare2/radare2rc` is redundant. what about `~/.config/radare2/rc`  and `rc.d` ?

**Comment by radare** [comment]
The reason behind keeping radare2rc was to be consistent with ~/.radare2rc and ~/.config/radare2/radare2rc but it is not even the same filename because of the dot... what do you think?

**Comment by ret2libc** [comment]
radare2rc looks good to me actually.

**Comment by oddcoder** [comment]
same here it is the convention gdbrc bashrc zshrc vimrc so radare2rc looks great.

**Comment by crowell** [comment]
yeah, i like radare2rc as well. I maintain my config in ~/.radare2rc and not in the ~/.config dir

**Comment by radare** [comment]
my plan was only to change the name when the script is in ~/.config/radare2/rc, add support for rc.d in there and keep handling ~/.radare2rc

**Comment by radare** [comment]
Moving to 0.10.4, this is really low prio as long as everyone is happy with current rc names, only need to discuss about the rc.d thing and maybe file-format-arch-specific scripts like vim does

**Comment by VisualPrankDude** [comment]
radare2rc looks good to me. I don't think, "rc" is a good name, because it could be confused with /etc/init.d/rc
also, let me tell, I hate collecting radare2rc from ~/.config.
  grrr !1

**Comment by radare** [comment]
ok, let's keep it like it is now, closing for now as long as most ppl agree that current naming is good enough
