### ISSUE TITLE
Optimize r_list_sort() by using more r_list_add_sorted 

### ISSUE THREAD

**Issue by radare** [radare/radare2#4274]
and check if any of the elements in the list has been added unsortedly

**Comment by Maijin** [comment]
Was that part of the recent commit @radare @alvarofe ?

**Comment by radare** [comment]
i think we can close this, alvaro already added merge sort and list_append_sorted() exists too. so its quite complete the whole thing... waiting for @alvarofe comments to close it

**Comment by alvarofe** [comment]
I would close it. r_list_sort with merge_sort is quite fast, maybe i would improve list_append_sorted using merge algorithm instead of going through the whole list.
