### ISSUE TITLE
Compression algorithm for rahash2 -E and a dedicated r2 command

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4280]
Like #4254, really interesting for malware analysis the compression algorithm : 
- [ ] Define/Create rehash2 command maybe same as crypto algorithm
- [ ] Define/Create radare2 command
- [ ] zip
- [ ] lzma
- [ ] lznt1
- [ ] aPlib
- [ ] lzmat
- [ ] gzip

**Comment by futex** [comment]
Nice to have it!

**Comment by radare** [comment]
there’s already support for zip, and therefor gzip. but there’s no command to do that from the shell.

we need to think which command to use here

**Comment by Maijin** [comment]
from the r2 cli + from a command like rahash2

**Comment by PankajKataria** [comment]
sounds cool I'd like to work on it.

**Comment by radare** [comment]
anyone?

**Comment by Maijin** [comment]
I think @P4N74 is looking at it

**Comment by radare** [comment]
@futex wanna do that? at least adding zlib/gzip is easy because its already shipped with r2

**Comment by futex** [comment]
I will take a look

**Comment by radare** [comment]
Cool 👍

**Comment by Maijin** [comment]
See hxxps://github.com/radare/radare2/issues/6946
