### ISSUE TITLE
radare2 cant debug i386-app on OSX?

### ISSUE THREAD

**Issue by hachzz** [radare/radare2#4282]
i have an issue posted [reverseengineering.stackexchange.com](http://reverseengineering.stackexchange.com/questions/12183/radare2-cant-debug-i386-app-on-osx)
pls help, thank you!

**Comment by radare** [comment]
i dont see any post about this in there. but lets start with the common questions:

- are you using last version from git?
- default dbuegger is not based on XNU, instead of ptrace, there’s an USE_XNU_PTRACE var to go back to the previous engine
- did you tried r2 -b 32 -d /path/to/bin ?

@alvaro_fe maybe can help on this

what is the error you have?

**Comment by hachzz** [comment]
my post here:
http://reverseengineering.stackexchange.com/questions/12183/radare2-cant-debug-i386-app-on-osx

i tried with r2 -b 32 -d /path/to/bin, still fail... :(

**Comment by radare** [comment]
the error message is quite clear:

* run r2 as root

or

* create a codesign certificate and sign r2 and all their shared libs with it

see doc/osx for more information

**Comment by hachzz** [comment]
after run these commands:
$ make -C binr/radare2 osxsign
$ make -C binr/radare2 osx-sign-libs

but nothin better, still have errors, here my log

> dc:~ hungpv$ cd hoc/rc/radare2/
dc:radare2 hungpv$ sudo make -C binr/radare2 osxsign
rm -f radare2
gcc radare2.c  -MD   -fPIC -g -Wall -D__UNIX__=1 -I/Users/hungpv/hoc/rc/radare2/libr/../shlr/zip/include -pie -I/Users/hungpv/hoc/rc/radare2/libr/..//libr/include -I/Users/hungpv/hoc/rc/radare2/libr/../shlr/zip/include      -L/Users/hungpv/hoc/rc/radare2/libr/core -L/Users/hungpv/hoc/rc/radare2/libr/parse -L/Users/hungpv/hoc/rc/radare2/libr/search -L/Users/hungpv/hoc/rc/radare2/libr/cons -L/Users/hungpv/hoc/rc/radare2/libr/config -L/Users/hungpv/hoc/rc/radare2/libr/bin -L/Users/hungpv/hoc/rc/radare2/libr/debug -L/Users/hungpv/hoc/rc/radare2/libr/anal -L/Users/hungpv/hoc/rc/radare2/libr/reg -L/Users/hungpv/hoc/rc/radare2/libr/bp -L/Users/hungpv/hoc/rc/radare2/libr/io -L/Users/hungpv/hoc/rc/radare2/libr/fs -L/Users/hungpv/hoc/rc/radare2/libr/lang -L/Users/hungpv/hoc/rc/radare2/libr/asm -L/Users/hungpv/hoc/rc/radare2/libr/syscall -L/Users/hungpv/hoc/rc/radare2/libr/db -L/Users/hungpv/hoc/rc/radare2/libr/hash -L/Users/hungpv/hoc/rc/radare2/libr/magic -L/Users/hungpv/hoc/rc/radare2/libr/socket -L/Users/hungpv/hoc/rc/radare2/libr/flags -L/Users/hungpv/hoc/rc/radare2/libr/util -L/Users/hungpv/hoc/rc/radare2/libr/egg -L/Users/hungpv/hoc/rc/radare2/libr/crypto -lr_core -lr_parse -lr_search -lr_cons -lr_config -lr_bin -lr_debug -lr_anal -lr_reg -lr_bp -lr_io -lr_fs -lr_lang -lr_asm -lr_syscall -lr_db -lr_hash -lr_magic -lr_socket -lr_flags -lr_util -lr_egg -lr_crypto -fPIC /Users/hungpv/hoc/rc/radare2/libr/../shlr/zip/librz.a /Users/hungpv/hoc/rc/radare2/libr/../shlr/zip/librz.a ../../shlr/gdb/lib/libgdbr.a ../../shlr/java/libr_java.a -o radare2 \
		-sectcreate __TEXT __info_plist Info.plist \
		-framework Security -framework CoreFoundation
clang: warning: argument unused during compilation: '-pie'
#xcrun --sdk macosx10.10 codesign -f -s org.radare.radare2 radare2
codesign -dvvv --deep -f -s org.radare.radare2 -i org.radare.radare2 radare2
radare2: signed bundle with Mach-O thin (x86_64) [org.radare.radare2]
#sudo chown root:_developer radare2
#sudo chmod g+s radare2
dc:radare2 hungpv$ sudo make -C binr/radare2 osx-sign-libs
for LIB in ../../libr/core/libr_*.dylib ../../libr/parse/libr_*.dylib ../../libr/search/libr_*.dylib ../../libr/cons/libr_*.dylib ../../libr/config/libr_*.dylib ../../libr/bin/libr_*.dylib ../../libr/debug/libr_*.dylib ../../libr/anal/libr_*.dylib ../../libr/reg/libr_*.dylib ../../libr/bp/libr_*.dylib ../../libr/io/libr_*.dylib ../../libr/fs/libr_*.dylib ../../libr/lang/libr_*.dylib ../../libr/asm/libr_*.dylib ../../libr/syscall/libr_*.dylib ../../libr/db/libr_*.dylib ../../libr/hash/libr_*.dylib ../../libr/magic/libr_*.dylib ../../libr/socket/libr_*.dylib ../../libr/flags/libr_*.dylib ../../libr/util/libr_*.dylib ../../libr/egg/libr_*.dylib ../../libr/crypto/libr_*.dylib ; do \
		echo Signing $LIB ; \
		codesign -f -s org.radare.radare2 $LIB ; \
	done
Signing ../../libr/core/libr_core.dylib
../../libr/core/libr_core.dylib: replacing existing signature
Signing ../../libr/parse/libr_parse.dylib
../../libr/parse/libr_parse.dylib: replacing existing signature
Signing ../../libr/search/libr_search.dylib
../../libr/search/libr_search.dylib: replacing existing signature
Signing ../../libr/cons/libr_cons.dylib
../../libr/cons/libr_cons.dylib: replacing existing signature
Signing ../../libr/config/libr_config.dylib
../../libr/config/libr_config.dylib: replacing existing signature
Signing ../../libr/bin/libr_bin.dylib
../../libr/bin/libr_bin.dylib: replacing existing signature
Signing ../../libr/debug/libr_debug.dylib
../../libr/debug/libr_debug.dylib: replacing existing signature
Signing ../../libr/anal/libr_anal.dylib
../../libr/anal/libr_anal.dylib: replacing existing signature
Signing ../../libr/reg/libr_reg.dylib
../../libr/reg/libr_reg.dylib: replacing existing signature
Signing ../../libr/bp/libr_bp.dylib
../../libr/bp/libr_bp.dylib: replacing existing signature
Signing ../../libr/io/libr_io.dylib
../../libr/io/libr_io.dylib: replacing existing signature
Signing ../../libr/fs/libr_fs.dylib
../../libr/fs/libr_fs.dylib: replacing existing signature
Signing ../../libr/lang/libr_lang.dylib
../../libr/lang/libr_lang.dylib: replacing existing signature
Signing ../../libr/asm/libr_asm.dylib
../../libr/asm/libr_asm.dylib: replacing existing signature
Signing ../../libr/syscall/libr_syscall.dylib
../../libr/syscall/libr_syscall.dylib: replacing existing signature
Signing ../../libr/db/libr_db.dylib
../../libr/db/libr_db.dylib: replacing existing signature
Signing ../../libr/hash/libr_hash.dylib
../../libr/hash/libr_hash.dylib: replacing existing signature
Signing ../../libr/magic/libr_magic.dylib
../../libr/magic/libr_magic.dylib: replacing existing signature
Signing ../../libr/socket/libr_socket.dylib
../../libr/socket/libr_socket.dylib: replacing existing signature
Signing ../../libr/flags/libr_flags.dylib
../../libr/flags/libr_flags.dylib: replacing existing signature
Signing ../../libr/util/libr_util.dylib
../../libr/util/libr_util.dylib: replacing existing signature
Signing ../../libr/egg/libr_egg.dylib
../../libr/egg/libr_egg.dylib: replacing existing signature
Signing ../../libr/crypto/libr_crypto.dylib
../../libr/crypto/libr_crypto.dylib: replacing existing signature
dc:radare2 hungpv$

dc:MacOS hungpv$ sudo r2 -a x86 -b 32 -d Challenge\ #1
posix_spawnp: unknown error 2
p/io_debug.c:271 posix_spawnp: No such file or directory
You probably need to run as root or sign the binary.
 Read doc/ios.md || doc/osx.md
 make -C binr/radare2 ios-sign || osx-sign
Cannot open 'dbg://./Challenge\#1' for writing.
dc:MacOS hungpv$

???

**Comment by radare** [comment]
If Challenge#1 is not in the path you will have to prefix it with ./ like in any unix system.

Also, i would recommend you to rename the bin to not contain silly characters like the hash or space.

Also u dont have to build r2 as root, only at run.

See the error medsages you get they are quite clear imho

**Comment by hachzz** [comment]
ok, after rename "Challenge 1" to "c1", its run well, but have some lines:

> dc:MacOS hungpv$ r2 -a x86 -b 32 -d c1
attach 769 769
bin.baddr 0x00001000
asm.bits 32
**r_debug_reg: error reading registers**
 -- If you're not satisfied by our product, we'll be happy to refund you.
[0x8fe01000]>

is it effect to program? (its bad?)

**Comment by radare** [comment]
so it works as expected.

you can enter in visual mode with V<enter>

press ‘p’ twice to go tot he debugger view and then ’s’ to step. all this stuff should work.

if you want to debug the program you should type `dcu entry0` to continue execution until the entrypoint.

**Comment by hachzz** [comment]
okay, thank you.
your support is best.

**Comment by alvarofe** [comment]
closing as it seems everything is fine. If you find any issue regarding debugging on OS X just create another issue. Bear in mind that multithread is not supported yet but for one thread of execution everything should work smoothly.

regards
