### ISSUE TITLE
r2 displays (lots of) '.gnu.version' entries at startup

### ISSUE THREAD

**Issue by cym13** [radare/radare2#4283]
Maybe it is intended behaviour but it quickly becomes *very* bloated as some binaries have many thousands of entries.

    $ r2 -v
    radare2 0.10.2-git 10544 @ linux-little-x86-64 git.0.10.1-91-g9edd7bc
    commit: 9edd7bc3f30d24a98911ca5fa3bc2a1f7cee03c0 build: 2016-03-09

    $ r2 /usr/bin/yes
    Version symbols section '.gnu.version' contains 61 entries:
     Addr: 0x00400b40  Offset: 0x00000b40  Link: 5 (.dynsym)
      000:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      004:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      008:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      00c:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      010:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      014:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      018:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      01c:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      020:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      024:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      028:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      02c:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      030:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      034:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      038:   0 (*local*)       0 (*local*)       0 (*local*)       0 (*local*)    
      03c:   0 (*local*)
     -- Error: cannot yank negative sleep
    [0x00401840]> ^D

**Comment by alvarofe** [comment]
That's been introduced recently because of the version info code, they are just eprintf for debug purpose i will add a macro to avoid those annoying messages

**Comment by alvarofe** [comment]
it should be fixed now but nothing to be worry about
