### ISSUE TITLE
RCrypto: segfault on running "-E blowfish"

### ISSUE THREAD

**Issue by therealkbhat** [radare/radare2#4287]
Command `$ rahash2 -S "abc" -E blowfish -s "testing"` results in a segmentation fault.

Relevant code is [here](https://github.com/radare/radare2/blob/master/libr/crypto/p/crypto_blowfish.c).
Suspicions are on invalid assumptions regarding the key, but there may be other issues.

**Comment by zonkzonk** [comment]
So SetHashString takes two arguments? 

E_NOT_CRYPTOGUY

**Comment by crowell** [comment]
`r_crypto_final (cry, NULL, 0);`
`return (cry && cry->h && cry->h->final)?
        cry->h->final (cry, buf, len): 0;`
`return update (cry, buf, len);`
`blowfish_crypt (&st, buf, obuf, len);`
nice, buf is null
`left = (inbuf[0] << 24 | inbuf[1] << 16 | inbuf[2] << 8 | inbuf[3]);`
segfault.

**Comment by alvarofe** [comment]
yes, in `blowfish_crypt` keylen is 3 but it assumes outbuf of size 8 so is a oob write. Can you fix it @therealkbhat ?

**Comment by therealkbhat** [comment]
@alvarofe yes, I'll fix this soon.

**Comment by radare** [comment]
any update on this?

**Comment by therealkbhat** [comment]
@radare Sorry, I was occupied over the weekend.

I'm having trouble debugging this. My code assumes both key and plaintext string are in hex.

Even with `$ rahash2 -E blowfish -S "aaaaaaaa" -s "aaaaaaaa"`, it produces one block (8 bytes) of ciphertext. However, it calls `blowfish_crypt` on the "next" block, which doesn't exist, and it segfaults.

Also, @crowell , I don't see the null. :/

**Comment by radare** [comment]
anyway, tired of waiting I pushed the one-line fix.

**Comment by radare** [comment]
23af75fd16f526f668383906d6325c5638abcd2e

**Comment by XVilka** [comment]
Still require proper fix, @therealkbhat

**Comment by radare** [comment]
Define proper fix. Probably needs proper testing, nothing more, or maybe im missing something. the null deref was pretty clear. and it misses an error message maybe, but not much more imho.

Also, im aware decryption doesnt works because the function is not referenced anywhere, but this is unrelated to this issue

**Comment by Maijin** [comment]
I have unchecked the blowfish support in main issue then #4254
