### ISSUE TITLE
Add `aftp` command to analyze type propagation in function

### ISSUE THREAD

**Issue by radare** [radare/radare2#4291]
* Tracks local vars defined in current function
* Finds when they are passed in CALLs
* Output r2 commands to register those `afa` (function arguments types) in the calls
* ...

I think that this kind of analysis can be done by using ESIL, so taking `aae` code as reference..or maybe just extending `aae` to do that tracking is important.

**Comment by oddcoder** [comment]
shall we close this ?

**Comment by radare** [comment]
yeah why not :D
