### ISSUE TITLE
MIPS find string references with two-part loads.

### ISSUE THREAD

**Issue by hummypkg** [radare/radare2#4293]
I'm disassembling a MIPSel application and can't easily cross reference strings because they are generally referenced using two-part register loads such as:

    a100043c       lui a0, 0xa1
    bc768424       addiu a0, a0, 0x76bc

Here's the string:

    [0x008e19fc]> sf strings
    [0x008e19fc]> f~a176bc
    0x00a176bc 18 str.cont_count_ignore

No xrefs

    [0x008e19fc]> axt str.cont_count_ignore

In IDA, the disassembly is shown as:

    la      $a0, aCont_count_ign  # "cont_count_ignore"

I'm starting to use radare2 instead of IDA more and more but Is there any way of automatically resolving and showing the string references like this?

**Comment by Maijin** [comment]
1. Ensure you are using radare2 from github. Please paste your radare2 -v
2. Try with aaaa prior txt

**Comment by radare** [comment]
Use aae. EmulaTing code is the inly way to compute those references statically

**Comment by hummypkg** [comment]
deb# (164) radare2 -v
    radare2 0.10.2-git 10550 @ linux-little-x86-64 git.0.10.1-97-g04a5eb3
    commit: 04a5eb3fb45724a18806b003a3b64695a8b64d3c build: 2016-03-11

Thanks, that definitely improves things and I now have some references in place but most of them are still missing. The one I first posted still doesn't have it.

    | ||||||    0x008e19ec      21200002       a0 = 2
    | ||||||    0x008e19f0      a100043c       a0 = 0xa1 << 16
    | ||||||    0x008e19f4      a200053c       a1 = 0xa2 << 16
    | ||||||    0x008e19f8      01000224       v0 = zero + 1
    | ||||||    0x008e19fc      bc768424       a0 += 0x76bc
    | ||||||    0x008e1a00      c8cca524       a1 -= 0x3338
    | ||||||    ; DATA XREF from 0x0016084c (fcn.008e19ac)
    | ||||||    0x008e1a04      f400a2a3       byte [sp + 0xf4] = v0
    | ||||||    ; DATA XREF from 0x00160772 (fcn.008e19ac)
    | ||||||    0x008e1a08      1a00a0a3       byte [sp + 0x1a] = zero
    | ||||||    ; DATA XREF from 0x00160773 (fcn.008e19ac)
    | ||||||    0x008e1a0c      1b00a0a3       byte [sp + 0x1b] = zero

and one that's working with aae:

    / (fcn) fcn.0069e858 216
    |           ; CALL XREF from 0x004d78d0 (fcn.0069e858)
    |           0x0069e858      a300033c       v1 = 0xa3 << 16
    |           0x0069e85c      20c36224       v0 = v1 - 0x3ce0
    |           ; DATA XREF from 0x00a2c320 (fcn.0069e858)
    |           0x0069e860      20c3648c       a0 = halfword [v1 - 0x3ce0] ; esilref: '/mnt/hd2/fred'
    |           ; DATA XREF from 0x00a2c32c (fcn.0069e858)
    |           0x0069e864      0c00468c       a2 = halfword [v0 + 0xc]    ; esilref: '/mnt/hd2/wilma'
    |           ; DATA XREF from 0x00a2c324 (fcn.0069e858)
    |           0x0069e868      0400458c       a1 = halfword [v0 + 4]      ; esilref: '/mnt/hd2/barney'
    |           ; DATA XREF from 0x00a2c328 (fcn.0069e858)
    |           0x0069e86c      0800438c       v1 = halfword [v0 + 8]      ; esilref: '/mnt/hd2/betty'
    |           0x0069e870      80ffbd27       sp -= 0x80
    |           ; DATA XREF from 0x000fd2a0 (fcn.0069e858)

**Comment by radare** [comment]
Can you verify if the ESIL representation for the instructions in the
reference that is not working are correct? if you go into visual mode and
press 'p' to see the disasm you can press 'O' (uppercase 'o') to see the esil
expressions.

> On Mar 11 2016, at 5:38 pm, hummypkg &lt;notifications@github.com&gt; wrote:  

>  
>  
>     deb# (164) radare2 -v

>     radare2 0.10.2-git 10550 @ linux-little-x86-64 git.0.10.1-97-g04a5eb3

>     commit: 04a5eb3fb45724a18806b003a3b64695a8b64d3c build: 2016-03-11

>  
>

> Thanks, that definitely improves things and I now have some references in
place but most of them are still missing. The one I first posted still doesn't
have it.

>  
>  
>     | ||||||    0x008e19ec      21200002       a0 = 2

>     | ||||||    0x008e19f0      a100043c       a0 = 0xa1 << 16

>     | ||||||    0x008e19f4      a200053c       a1 = 0xa2 << 16

>     | ||||||    0x008e19f8      01000224       v0 = zero + 1

>     | ||||||    0x008e19fc      bc768424       a0 += 0x76bc

>     | ||||||    0x008e1a00      c8cca524       a1 -= 0x3338

>     | ||||||    ; DATA XREF from 0x0016084c (fcn.008e19ac)

>     | ||||||    0x008e1a04      f400a2a3       byte [sp + 0xf4] = v0

>     | ||||||    ; DATA XREF from 0x00160772 (fcn.008e19ac)

>     | ||||||    0x008e1a08      1a00a0a3       byte [sp + 0x1a] = zero

>     | ||||||    ; DATA XREF from 0x00160773 (fcn.008e19ac)

>     | ||||||    0x008e1a0c      1b00a0a3       byte [sp + 0x1b] = zero

>  
>

> and one that's working with aae:

>  
>  
>     / (fcn) fcn.0069e858 216

>     |           ; CALL XREF from 0x004d78d0 (fcn.0069e858)

>     |           0x0069e858      a300033c       v1 = 0xa3 << 16

>     |           0x0069e85c      20c36224       v0 = v1 - 0x3ce0

>     |           ; DATA XREF from 0x00a2c320 (fcn.0069e858)

>     |           0x0069e860      20c3648c       a0 = halfword [v1 - 0x3ce0] ;
esilref: '/mnt/hd2/fred'

>     |           ; DATA XREF from 0x00a2c32c (fcn.0069e858)

>     |           0x0069e864      0c00468c       a2 = halfword [v0 + 0xc]    ;
esilref: '/mnt/hd2/wilma'

>     |           ; DATA XREF from 0x00a2c324 (fcn.0069e858)

>     |           0x0069e868      0400458c       a1 = halfword [v0 + 4]      ;
esilref: '/mnt/hd2/barney'

>     |           ; DATA XREF from 0x00a2c328 (fcn.0069e858)

>     |           0x0069e86c      0800438c       v1 = halfword [v0 + 8]      ;
esilref: '/mnt/hd2/betty'

>     |           0x0069e870      80ffbd27       sp -= 0x80

>     |           ; DATA XREF from 0x000fd2a0 (fcn.0069e858)

>  
>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/radare/
radare2/issues/4293#issuecomment-195443199).![](https://github.com/notificatio
ns/beacon/AA3-lgKLQOGUbbYBPPt7xZJCh-VJQKI4ks5psZqZgaJpZM4Huy8O.gif)

**Comment by hummypkg** [comment]
The negative addiu looks wrong in ESIL but a0 looks right to me:

    | ||||||    0x008e19f0      a100043c       lui a0, 0xa1
    | ||||||    0x008e19f4      a200053c       lui a1, 0xa2
    | ||||||    0x008e19f8      01000224       addiu v0, zero, 1
    | ||||||    0x008e19fc      bc768424       addiu a0, a0, 0x76bc
    | ||||||    0x008e1a00      c8cca524       addiu a1, a1, -0x3338

    | ||||||    0x008e19f0      a100043c       0xa10000,a0,=
    | ||||||    0x008e19f4      a200053c       0xa20000,a1,=
    | ||||||    0x008e19f8      01000224       1,zero,+,v0,=
    | ||||||    0x008e19fc      bc768424       30396,a0,+,a0,=
    | ||||||    0x008e1a00      c8cca524       18446744073709538504,a1,+,a1,=

**Comment by radare** [comment]
git pull and check if this is working/correct now :)

**Comment by hummypkg** [comment]
Subtraction looks good now but still no ESIL reference to the string at 0xa076bc

    | ||||||    0x008e19f0      a100043c       0xa10000,a0,=
    | ||||||    0x008e19f4      a200053c       0xa20000,a1,=
    | ||||||    0x008e19f8      01000224       1,zero,+,v0,=
    | ||||||    0x008e19fc      bc768424       30396,a0,+,a0,=
    | ||||||    0x008e1a00      c8cca524       13112,a1,-,a1,=

**Comment by radare** [comment]
I guess that you runned aae to try to find this ref, right? Or at least with asm.emu=true

Can you tell me how is this reference computed or which would be the correct address instead of the wrongly computed one? (I dont have much time for looking at this task right now)

Let me know if you find other esil issues in mips.

Thanks!

**Comment by hummypkg** [comment]
Yes, I used aae.
It isn't a wrong reference, just that the reference doesn't seem to be detected.
Thanks for the help so far, I will see if I can fix the problem myself and submit a patch.

**Comment by hummypkg** [comment]
FWIW, this seems to be the same issue as https://github.com/radare/radare2/issues/949#issuecomment-43643179 - trying to automatically create xrefs for these strings.

**Comment by hummypkg** [comment]
Here's a hack-ish patch. I doubt this is the best way to do it but it's working for me and means I don't have to go back to IDA for this project!

[mipsref.diff.txt](https://github.com/radare/radare2/files/172866/mipsref.diff.txt)

It is resolving most of the string references in my project. Ideally it would only look at ADD operations where 'arg1 && !(arg1 & 0xffff)' but the ESIL analyser doesn't see the wider context. I thought of checking the register before and after (via extra PUSH, POP, == instructions) but sometimes the instructions look like a1 = v0 + 0x1234..
I can also force some xrefs by forcing a peek (DUP,[],POP) but they aren't as useful.

I hope that something like this can make it into radare2 at some point, thanks.

Test program:

    int main() {
            char buf[50], *p;
    
            strcpy(buf, "some text");
            p = "more text";
            printf("%s%s\n", buf, p);
    }

With the patch, string references are created and can be seen as comments on the right:

                ;-- main:
    / (fcn) sym.main 112
    |           ; JMP XREF from 0x00400648 (sym.main)
    |           0x004005c0      a8ffbd27       addiu sp, sp, -0x58
    |           0x004005c4      5400bfaf       sw ra, 0x54(sp)
    |           0x004005c8      5000beaf       sw fp, 0x50(sp)
    |           0x004005cc      21f0a003       move fp, sp
    |           0x004005d0      1c00c227       addiu v0, fp, 0x1c
    |           0x004005d4      21204000       move a0, v0
    |           0x004005d8      4000023c       lui v0, 0x40
    |           0x004005dc      d0064524       addiu a1, v0, 0x6d0         ; str.some_text
    |           0x004005e0      0a000624       addiu a2, zero, 0xa
    |           0x004005e4      3001100c       jal sym.imp.memcpy
    |           0x004005e8      00000000       nop
    |           0x004005ec      4000023c       lui v0, 0x40
    |           0x004005f0      dc064224       addiu v0, v0, 0x6dc         ; str.more_text
    |           0x004005f4      1800c2af       sw v0, 0x18(fp)
    |           0x004005f8      1c00c327       addiu v1, fp, 0x1c
    |           0x004005fc      4000023c       lui v0, 0x40
    |           0x00400600      e8064424       addiu a0, v0, 0x6e8         ; str._s_s_n
    |           0x00400604      21286000       move a1, v1
    |           0x00400608      1800c68f       lw a2, 0x18(fp)
    |           0x0040060c      2c01100c       jal sym.imp.printf
    |           0x00400610      00000000       nop
    |           0x00400614      21100000       move v0, zero
    |           0x00400618      21e8c003       move sp, fp
    |           0x0040061c      5400bf8f       lw ra, 0x54(sp)
    |           0x00400620      5000be8f       lw fp, 0x50(sp)
    |           0x00400624      5800bd27       addiu sp, sp, 0x58
    |           0x00400628      0800e003       jr ra
    \           0x0040062c      00000000       nop

and:

    [0x004005c0]> axt str.some_text
    data 0x4005dc addiu a1, v0, 0x6d0 in sym.main; str.some_text

**Comment by radare** [comment]
Aaah that makes sense, an ADD instruction is not suposed to reference an address in other architectures. let me adapt your patch and try if that can be generic for other architectures.
thanks!

**Comment by radare** [comment]
I did some more enhancements for the MIPS analyzer, also, call reg references are now properly handled if gp is set correctly, because delayed branches were not catched properly before.

**Comment by radare** [comment]
i have recently added `anal.strings` for aae and aar. so you can basically load the bin with bin.strings=false, and then check how many strings the analysis was able to find.

After all those changes, i see that not all refs are still catched, but we are improving :) feel free to submit more tests for mips analysis, this is necessary to avoid breaking stuff
