### ISSUE TITLE
Raw search in ELF files fails

### ISSUE THREAD

**Issue by codido** [radare/radare2#4294]
Raw search seems to be broken:

```
(gcc -x c - << EOF
void foo() {}
int main() { return 0; }
EOF
r2 -e search.in=raw -qc '/ foo' a.out)
```
...searches in the range of 0x00400400 to 0xffffffffffffffff.

Modifying search.from & search.to don't seem to control the search appropriately.

**Comment by Maijin** [comment]
Use oon or r2 -n to open raw then search on the entire binary, not only mapped sections. Alternatively drop all sections and disable io.va
