### ISSUE TITLE
afna is sometimes confusing

### ISSUE THREAD

**Issue by radare** [radare/radare2#4306]
We should find better way to name functions, because aaa is sometimes producing confusing disassemblies

**Comment by Maijin** [comment]
Enhancing #3800 would also allow better detection

**Comment by rlaemmert** [comment]
i think the best would be fcn.<addr>(arg1,arg2,arg3) or something similar. the first called library function as label is not that useful, because most of the time the first library function is something for initializing the real stuff

**Comment by Maijin** [comment]
I think you confuse display and flag name. fcn.(arg1,arg2,arg3) will looks like even bigger mess since argument will just be undefined. fcn.0x0000(0x000,0x000,0x0000) that is looking more useful...
"because most of the time the first library function is something for initializing the real stuff" <- This behaviour works somehow well on lot of PE binaries at least and is far better than fcn.0x000

**Comment by radare** [comment]
wtf

**Comment by XVilka** [comment]
@radare can you show the example of confusing name?

**Comment by rlaemmert** [comment]
"This behaviour works somehow well on lot of PE binaries at least and is far better than fcn.0x000"
Not in the binaries i have seen so far. In the last one for example i had functions that always start with VirtualAlloc. Or this one:                                                                                                                      
0x0041526f      e89cf1ffff     call sub.USER32.dll_GetDC_410 ;[5]   
This function is the _WinMain in idapro.

**Comment by radare** [comment]
I think WinMain should be identified like a bin symbol from the PE plugin, like it is done for ELF. this way the afna will not fail here. if you can share a bin for htat, or just implement the `binsym` callback in the PE plugin for the R_BIN_SYM_MAIN.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/832

**Comment by radare** [comment]
We should disable afna by default. And add anal.autoname for this purpose

**Comment by radare** [comment]
I have added the `anal.autoname` variable set to false by default. we can enable it in the future when we make it better.

**Comment by Maijin** [comment]
`afta` may help to reduce false detection, question is how to proceed to submit and fix those false detection ?

**Comment by Maijin** [comment]
Very common are:

```
* sub.__stack_chk_guard_XX_XXX
* sub.__stderrp_XX_XXX
* sub.__stdinp_XX_XXX
* sub.__stdoutp_XX_XXX
* sub._DefaultRuneLocale_XX_XXX
```

**Comment by radare** [comment]
we can add some blacklist of symbols or names to not use by afna

**Comment by Maijin** [comment]
ok this false positive are now handled

**Comment by radare** [comment]
Lets consider this fixed for now

**Comment by Maijin** [comment]
ok, I think the deal will be probably later to enhance all those stuff https://github.com/radare/radare2/blob/master/libr/core/anal.c#L299 for example, detecting "str.usage" should rename the block or function as fcn.usage and so on
