### ISSUE TITLE
Support to change asm.bits via ESIL

### ISSUE THREAD

**Issue by radare** [radare/radare2#4311]
This is necessary to emulate the `blx` and `bx` instructions that switch between arm and thumb

**Comment by radare** [comment]
cc @condret any suggestion for this?

**Comment by XVilka** [comment]
add a special status register?

**Comment by radare** [comment]
Yeah sounds good to me. But maybe we want a toggler for 16/32 instead of a var?

**Comment by ninjahacker** [comment]
Related: #4091 #3924 
Also, there are some regressions that need to be brought up to passing (based on those issues).
I was hoping to some day get to do this, but I don't know much about ESIL. Through emulation, are we going to mark each opcode as 16 vs. 32 vs. 64 bit? Then when we seek to an offset, it is known how to disassemble?

**Comment by radare** [comment]
This is already supported theres a glibal asm.bits value taken from rbin, but this value can change depending on fcn->bits or section->bits. Also theres ahb to change the anal hint bits. To change the bits for N instructions.

What we need is a way to represent in esil which instructions change the cpu mode like bx or so.

**Comment by radare** [comment]
@condret ping
