### ISSUE TITLE
How to disassemble system_call?

### ISSUE THREAD

**Issue by ithurricane** [radare/radare2#4312]
I love this project, and want to disassemble system_call,
I want to to do a job like:
gdb /usr/src/linux-2.6.32.9/vmlinux /proc/kcore
and disassemble system_call.

How to disassemble system_call in radare2?

**Comment by radare** [comment]
Theresno support for cores in r2 yet. To disassemble just use 's sym.system_call and then pd to disassemble

**Comment by radare** [comment]
this is not an issue, just a support request and its already been explained. use irc or telegram if youw ant more interactive support
