### ISSUE TITLE
Use afr instead of af in r2 -A

### ISSUE THREAD

**Issue by radare** [radare/radare2#4314]

**Comment by oddcoder** [comment]
what is the question ?

**Comment by Maijin** [comment]
Should we switch af to afr in r2 -A that's the question.

**Comment by oddcoder** [comment]
I would say yes AFAIK recursive analysis is much more accurate than linear search.

**Comment by radare** [comment]
we can also enable anal.calls=true and disable it right after the -A analysis. can you guys send a PR to see what travis thinks about this?

**Comment by radare** [comment]
see https://github.com/radare/radare2-regressions/issues/336

**Comment by Maijin** [comment]
? https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3668

**Comment by radare** [comment]
Oh , so it is done already ^^:D
