### ISSUE TITLE
can not use regex sequence in rop search

### ISSUE THREAD

**Issue by EasyHard** [radare/radare2#4319]
I notice that `"/R push esi;push ebx"` could find a correct gadget but `"/R/ push esi;push ebx"` can find nothing. For example,

```
➜  radare2 git:(regex-seq) ✗ binr/radare2/radare2 ../radare2-regressions/bins/elf/x86-helloworld-gcc                                                      git:(regex-seq|✚1…
 -- We are bleeding edge here. Can't you feel the razors?
[0x08048300]> "/R/ push esi;push ebx"
[0x08048300]> "/R push esi;push ebx"
  0x08048421                 57  push edi
  0x08048422               31ff  xor edi, edi
  0x08048424                 56  push esi
  0x08048425                 53  push ebx
  0x08048426         e805ffffff  call 0x8048330

[0x08048300]> 

```

**Comment by radare** [comment]
Can you send a test for the radare2-regressions repository?

@crowell this looks like a regression

**Comment by Maijin** [comment]
Duplicate already reported https://github.com/radare/radare2/issues/1745

**Comment by Maijin** [comment]
Already reported see https://github.com/radare/radare2/issues/3520

**Comment by crowell** [comment]
@maijin that's a different issue with | this is a general one

**Comment by EasyHard** [comment]
Hi, I made a PR of this. I will create a test ASAP.

**Comment by EasyHard** [comment]
Accidentally create a PR in my fork. O_o

**Comment by radare** [comment]
This was fixed already
