### ISSUE TITLE
search limits -1 on sliced mach0 goes beyond the selected slice

### ISSUE THREAD

**Issue by mrmacete** [radare/radare2#4333]
On an iOS mach0 binary with armv7 and arm64 slices, when `search.from` and `search.to` are both set to -1, it seems that the search is performed on the whole binary and not only on the selected slice (using -b 64 in my case) resulting in exponentially slower search times.

I'm not sure if this is a bug or an intended behaviour, although this was unexpected for me. My working workaround is to always set the search.from and search.to to proper values != -1, but in my case it's simple because i'm just using `/c` so the limits can be set to match the `__text` section here. I can imagine more complex use cases in which setting that values explicitly could be more uncomfortable.

**Comment by radare** [comment]
It depends on search.in and if the binary is loaded into sections you will not be able to search on the whole file at all

**Comment by mrmacete** [comment]
wow, just didn't know about search.in :( i'll try it

**Comment by radare** [comment]
Use "e search.in=?" To see all the values u can use here

**Comment by mrmacete** [comment]
great!
