### ISSUE TITLE
Implement imq and imj

### ISSUE THREAD

**Issue by radare** [radare/radare2#4342]

**Comment by radare** [comment]
(and add tests)

**Comment by radare** [comment]
@Maijin do we have tests for im?

**Comment by Maijin** [comment]
one yes https://github.com/radare/radare2-regressions/commit/8e2bca49b793c02da9a0f3337e7e5e139aebe596

**Comment by Maijin** [comment]
what do you suggest for imq display ?

**Comment by radare** [comment]
Just the addresses, newline separated

**Comment by P4N74** [comment]
submitted patch for this: https://github.com/radare/radare2/pull/4550

**Comment by radare** [comment]
fixed in master!
