### ISSUE TITLE
x86: Wrong ESIL for ljmp

### ISSUE THREAD

**Issue by neuschaefer** [radare/radare2#4344]
I have a 32-bit program that does a `ljmp 8:0x34040`, which AFAIK sets `cs` to `8` and `eip` to `0x34040`. The opcode is `ea404003000800`.
The generated esil, however, is `0x8,eip,=`.

```
$ r2 -V
0.10.1-132-gda9616f  r2    
0.10.1-164-gdc33b03  r_*
```

**Comment by radare** [comment]
This is a very easy thing to fix. Can you submit a test case for the r2r repo? Do you wanna try to fix it?

Thanks

**Comment by neuschaefer** [comment]
Yes, I'll try now

**Comment by neuschaefer** [comment]
It appears to not be that easy. I don't really understand `shlr/udis86/itab.c`.

I can send the r2r patch, but I'm not sure how to test this, and what to test. Segment registers are apparently not tracked in ESIL, at the moment.

**Comment by radare** [comment]
We dont use udis86 by default. The patch should be for capstone first

**Comment by radare** [comment]
And u dont need to read disassembler internals

**Comment by mrmacete** [comment]
well what i see is:

```
ea4040030008.  0x8,cs,=,0x34040,eip,=
```
which looks good to me. Is there a specific case in which it doesn't work? Is the original binary around?

**Comment by neuschaefer** [comment]
No, I don't have the binary anymore.
The bug seems to be fixed, thanks!
