### ISSUE TITLE
Output of t is wrong

### ISSUE THREAD

**Issue by radare** [radare/radare2#4351]
The current output of the `t` command is the same as `tk`. this is not correct. mainly because t should have a better/simpler output, and tk is used to access the database in raw. The output for `t` should be the key for the keys with value "type".. or the last part of the keys starting with `type.`

**Comment by oddcoder** [comment]
something like this ?
```
unsigned int
unsigned char
unsigned short
int
long
void *
char
char *
const char*
uint8_t
uint16_t
uint32_t
uint64_t
```

**Comment by oddcoder** [comment]
ok and what about struct types ?

**Comment by radare** [comment]
Maybe do this in ts?

**Comment by oddcoder** [comment]
what should ts be exactly doing ?
