### ISSUE TITLE
Better `te`

### ISSUE THREAD

**Issue by radare** [radare/radare2#4354]
Some random issues for te

* [ ] Using `te` without anything else lists all the enums defined, but this is not explained in t?
* [ ] There's no te? help
* [x] output for `te Foo.COW` should be 1, not the entire k=v string.

```
[0x00000000]> "td enum Foo {COW=1,BAR=2};"
[0x00000000]> te
Foo
[0x00000000]> te?
Foo.COW=0x1
Foo.BAR=0x2
[0x00000000]> te
Foo
[0x00000000]> te?
Foo.COW=0x1
Foo.BAR=0x2
[0x00000000]> te Foo
Foo.COW=0x1
Foo.BAR=0x2
[0x00000000]> te Foo.COW
Foo.COW=0x1
[0x00000000]>
```

**Comment by radare** [comment]
The output of `tb Foo.COW` matches what `te Foo.COW` should do. (imho).. what do you think?

**Comment by oddcoder** [comment]
| tb <enum> <value>  Show matching enum bitfield for given number
| te <enum> <value>  Show name for given enum number
the correct way of using te is
```
"td enum Foo {COW=1,BAR=2};"
te FOO 1
```
output: COW
while
```
tb FOO COW
```
output: 1
no need to change it I think

**Comment by radare** [comment]
Ok close it

**Comment by Maijin** [comment]
Letting open for t? and te?
