### ISSUE TITLE
tf should be like te, but for functions

### ISSUE THREAD

**Issue by radare** [radare/radare2#4355]
In `t` we can store the following things:

* types (int, char, ..)
* structs
* enums
* function signatures
* bitfields  (tb)

We should clarify this and make them accessible using a single root command instead of multiple root ones. for example:

`t` -> list types
`ts` -> list structs
`te`-> enums
`tf` -> functions
`tb` -> bitfields

This is what i would probably expect without checking the help message.

The current use of tf and tl are a bit confusing imho

**Comment by oddcoder** [comment]
ok :D :D always writing specs is very helpfull !!  but if it was done before coding step :last_quarter_moon_with_face:

**Comment by radare** [comment]
Even if you design something for months you will notice the design is flawed when you write the code or use the functionality. I prefer to write pocs and have working or usable stuff that can be improved than tons of docs and drafts for something that will never exist because it will be too poorly interesting to do
