### ISSUE TITLE
tl is incomplete

### ISSUE THREAD

**Issue by radare** [radare/radare2#4356]
Some issues with tl

* [x] tl- doesnt exist, so you cant remove a link
* [x] link is probably a bad name for this operation
* [x] cannot redefine type (tl int;tl char;pd 1)
* [x] current tf functionality should be in tl
* [x] no `tl*` is implemented

**Comment by oddcoder** [comment]
what is the purpose of `tl*`

**Comment by Maijin** [comment]
fix by @oddcoder in https://github.com/radare/radare2/pull/4417
