### ISSUE TITLE
Verify/fix that all type definitions and links are stored and restored in projects

### ISSUE THREAD

**Issue by radare** [radare/radare2#4357]

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/1a3e09d1e8894c98ac265da8c741b3bd7ae49aaa ; Now need some tests

**Comment by Maijin** [comment]
Closing for now https://github.com/radare/radare2-regressions/blob/77c64a2ea9e7302ed0b377bf28ca8a0d8fc86351/t/cmd_project#L145
