### ISSUE TITLE
Types in disasm doesnt consume bytes

### ISSUE THREAD

**Issue by radare** [radare/radare2#4359]
See that there are some issues here:
```
$ r2 -
 -- One does not simply write documentation.
[0x00000000]> wx 33
[0x00000000]> tl int
[0x00000000]> pd 1
struct int {
0x00000000 = 51
}
            0x00000000      3300           xor eax, dword [rax]
[0x00000000]>
```
* [ ] struct int wtf
* [ ] links of offset=type should also sepcify a name
* [ ] those names doesnt need to be unique
* [ ] the offset of the next instruction should be `$$ + sizeof(typeIn($$))`

**Comment by Maijin** [comment]
The last issue is related to all metadata like Cd and so on.

**Comment by radare** [comment]
this one is important

**Comment by Maijin** [comment]
@oddcoder

**Comment by radare** [comment]
See how dF works

**Comment by radare** [comment]
no time for today

**Comment by radare** [comment]
ping @oddcoder

**Comment by oddcoder** [comment]
I am working on it now

**Comment by radare** [comment]
ping @oddcoder

**Comment by radare** [comment]
ping

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/5288
