### ISSUE TITLE
Add support for unions in t

### ISSUE THREAD

**Issue by radare** [radare/radare2#4360]

**Comment by XVilka** [comment]
Especially to show them and switch on the fly

**Comment by radare** [comment]
Switch?

**Comment by XVilka** [comment]
@radare for example see:
```c
struct {
    int a;
    union {
       struct {
         int d;
         int f;
       } c;
       struct {
         float z;
         float x;
       } y;
    } b;
} qwe;
```
So we need to switch between printing `struct c` with int types and `struct y` with float inside the union b. Idea is not to print all of them, but ability to select only one and hide others. Something like this.

**Comment by radare** [comment]
you mean conditional structures depending on some types like 010 does?

**Comment by XVilka** [comment]
No, conditional structures are awesome and will be nice addition too, but I meant unions. To switch between possible values somehow. Have no idea how to do that yet.

**Comment by radare** [comment]
about conditional structures, maybe we can just abuse cpp for this. reloading the same struct multiple times with different defines set depending on the value of a specific field. that will ease the implementation but slowldown the runtime because will require to parse it more times.

**Comment by oddcoder** [comment]
at the current time 
unions are not parsed correctly
```
[0x00000000]> t-*
[0x00000000]> "td union x{int a; float b;}"
[0x00000000]> tk
x=struct
struct.x=a,b
struct.x.a=int,0,0
struct.x.b=float,0,0
```

**Comment by radare** [comment]
Should be easy to fix tcc to change struct for union in this case

**Comment by radare** [comment]
Are u on this?

**Comment by oddcoder** [comment]
I am not sure ! most probably I wont get into tcc

**Comment by radare** [comment]
Fear is the worst enemy ;) be brave and solutions will appear quickly.

**Comment by radare** [comment]
please confirm and write tests, because i dont see the output of t

**Comment by radare** [comment]
't' should list all the types and now is not showing any type at all. also tu is not implemented

**Comment by radare** [comment]
but it is parsed and stored properly now
