### ISSUE TITLE
Show value for type for some specific bytes

### ISSUE THREAD

**Issue by radare** [radare/radare2#4361]
(from xvilka)
Add one more pls - 'ability to apply type to the sequence of bytes directly from command line'

`ts struct qwe 474333456`

(pancake)
it is useful to be able to show the values for a specific type (struct, union ..) with some specific data.
this can be already done with `pf ... @x:....` .. the pf expression can be extracted from the struct type, and the hexpairs will go after the @x: .. maybe we need a specific command to avoid having to use @x: and so on

**Comment by Maijin** [comment]
#6091

**Comment by XVilka** [comment]
@sivaramaaa we have "tp" command now, can be extended to accept sequence of types too.
