### ISSUE TITLE
Add `aex` command to emulate hexpairs

### ISSUE THREAD

**Issue by radare** [radare/radare2#4362]
This command must work like this:
```
$ r2 -a x86 -
> aex 40
```
This is `inc eax` for x86

**Comment by Darredevil** [comment]
@radare @XVilka I would like to tackle this but I need more information

**Comment by XVilka** [comment]
Thx, commited in https://github.com/radare/radare2/commit/b362e2d2fb77149a374618d75baa29fb77be0e0c

**Comment by radare** [comment]
Aex != doo ????

**Comment by radare** [comment]
What info do you need?

**Comment by XVilka** [comment]
@radare already explained, now we can wait for PR :)

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/pull/347
