### ISSUE TITLE
Add ae subcommand to emulate N instructions starting at X offset

### ISSUE THREAD

**Issue by radare** [radare/radare2#4363]
Without having to change the program counter by hand like we can do now:

```
> ar PC=offset # change program counter register
> aes 10 # emulate 10 instructions
```

**Comment by sivaramaaa** [comment]
Hey hi  ,
Do u mean like this  ``` aexn x,n ``` where x is an offset relative to current esil - PC 
if so  first they have to intialize the pc somewhere they want and from there we can emulate from given offset , to N instr , but i think even this happens in 2 command  .
