### ISSUE TITLE
Alias in 'd' commands for 'ood'

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4365]
May be 'doo'? Since reopening debugger with arguments - very common need and most people search it in the 'd' commands namespace

**Comment by radare** [comment]
Yep lgtm

**Comment by Darredevil** [comment]
@XVilka @radare PR ready for merge

**Comment by Maijin** [comment]
@Darredevil small tips, if you add Fix like "Fix #4365" in your commit message, it will automatically close the issue. good to know for next time ;)

**Comment by Darredevil** [comment]
@Maijin Got it, thx :D
