### ISSUE TITLE
Implement ldid -e

### ISSUE THREAD

**Issue by radare** [radare/radare2#4368]
To show embedded iOS binary entitlements

**Comment by kuckuck** [comment]
Working on it, should this be in rabin2?

**Comment by radare** [comment]
yes rabin2 -O ldid path/to/bin

On 26 March 2016 at 19:31, Nicholas Kuckuck <notifications@github.com>
wrote:

> Working on it, should this be in rabin2?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4368#issuecomment-201909403>
>



-- 
--pancake

**Comment by radare** [comment]
@alvarofe did you shared your code with @kuckuck ?

**Comment by radare** [comment]
any update on this?

**Comment by kuckuck** [comment]
Sorry I haven't had much time to work on this as I'm starting a new term in school, but I should be able to submit a pr sometime this week.

**Comment by radare** [comment]
Awesome! 👍

**Comment by radare** [comment]
moving to 0.10.3 i think we should do this with `rabin2 -O e/v` and then we can add others like `rabin2 -O e/s/entitlements.xml` .. using the bin_write callbacks

**Comment by kuckuck** [comment]
Where might I find parsed Mach-O entitlements? I've been looking at the code but I'm not seeing it.

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
reping @alvarofe @kuckuck

**Comment by alvarofe** [comment]
done in local i have to integrate with rabin -O and create a new command `iC` to display the info.
