### ISSUE TITLE
Add support to add comments to variables

### ISSUE THREAD

**Issue by radare** [radare/radare2#4373]

**Comment by oddcoder** [comment]
@Maijin can you please add little explanation ?

**Comment by Maijin** [comment]
```
╒ (fcn) entry0 2340
│           ; var int local_0h @ rbp-0x0
```

->

```
╒ (fcn) entry0 2340
│           ; var int local_0h @ rbp-0x0 ; MYCOMMENT
```

**Comment by Maijin** [comment]
in idapro: `AppendLvarComment(4205152, 40, "FLOSS stackstring: ?@@@AAAA?@@@", True)`

**Comment by radare** [comment]
Maybe In Cv or Ca as an alias for afvC and such. Looks good to me

Yesterday i missed a way to run a command at a speicfic offset without using flags. Like in hints or comments. What do you think?

**Comment by oddcoder** [comment]
looks good to me
