### ISSUE TITLE
Invalid install location for OS X 10.11+

### ISSUE THREAD

**Issue by natewalck** [radare/radare2#4375]
The OS X installer package is broken on 10.11+ when SIP is enabled. 

It is installing files to ```/usr/bin``` which is a SIP protected location. It should instead install to ```/usr/local/bin``` or another non-SIP protected location.

**Comment by radare** [comment]
Nope this was fixed days before elcapitan was released. Whih version are u using? Are u running the sys/install.sh?

**Comment by alvarofe** [comment]
he refers to .pkg. I've just checked and it fails. Just use r2 from git and `./sys/install.sh`

**Comment by radare** [comment]
fixed in master, will be ready in the next release

**Comment by natewalck** [comment]
Yep this was for the .pkg. Thanks for the quick fix!
