### ISSUE TITLE
rabin2 -x /etc/services no error

### ISSUE THREAD

**Issue by radare** [radare/radare2#4377]
it does nothing and it shows nothing

**Comment by Maijin** [comment]
@lionaneesh see this ^

**Comment by lionaneesh** [comment]
It passes the bin object to each of the RbinXtr plugin's check() method and each one of them return 0 (because none of the plugins support its extraction). Then it exits. Should we show an error message?

**Comment by lionaneesh** [comment]
I think we can close this bug now?
