### ISSUE TITLE
lulz issue: drt 128 :)

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#4379]
```
[> drt 128
eax = 0x00000000
ebx = 0x00000000
ecx = 0x00000000
edx = 0x00000000
r8d = 0x00000000
r9d = 0x00000000
r10d = 0x00000000
r11d = 0x00000000
r12d = 0x00000000
r13d = 0x00000000
r14d = 0x00000000
r15d = 0x00000000
esi = 0x00000000
edi = 0x00000000
esp = 0xf02b3380
ebp = 0x00000000
eflags = 0x000002c0

```

**Comment by radare** [comment]
When passimg a bitsize that is not handled by any reg just shows them all

**Comment by VisualPrankDude** [comment]
hm, not so beautiful, but not a problem.

**Comment by radare** [comment]
Must be fixed imho dont close it

**Comment by Svenito** [comment]
It actually falls back to 32 for unknown sizes. Is expected behaviour then to not show anything?

Only sizes that aren't valid (where (size & 121) != 0) show nothing.

**Comment by radare** [comment]
its fixed in master
