### ISSUE TITLE
Sort output of radiff2 -C

### ISSUE THREAD

**Issue by radare** [radare/radare2#4384]
order by:

* alphabetically by function name
* offset
* similarity
* type (NEW, MATCH, UNMATCH)
* function size

in:

* forward
* backward

**Comment by jkrshnmenon** [comment]
I'll start working on this

**Comment by radare** [comment]
all yours 👍

**Comment by radare** [comment]
ping @jkrshnmenon

**Comment by radare** [comment]
looking forward your PR :)

**Comment by jkrshnmenon** [comment]
Created a PR. Looking forward to your comment

**Comment by radare** [comment]
merged thanks
