### ISSUE TITLE
dyldcache file format support broken

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4392]
It takes 100% cpu and extracts no files at all.
The fileformat has changed and the current api changes broke the plugin

**Comment by radare** [comment]
it was supporting only 32bit dyldcaches, now they are 64bit (because of arm64).

**Comment by alvarofe** [comment]
This can be useful  http://newosxbook.com/tools/joker.html the source code is available

**Comment by radare** [comment]
assigned to @lionaneesh

**Comment by radare** [comment]
This is fixed now by @alvarofe

**Comment by radare** [comment]
we need tests for this, but there are no distributable dyldcache's out there.. so we will need to cook our one. moving this to https://github.com/radare/radare2-regressions/issues/360
