### ISSUE TITLE
update the swift demangler

### ISSUE THREAD

**Issue by radare** [radare/radare2#4394]
now that swift is opensource we should port the c++ version to C

i dont think the mangling is gonna change much from 2.2 to 3.x

**Comment by alvarofe** [comment]
https://mikeash.com/pyblog/friday-qa-2014-08-15-swift-name-mangling.html

**Comment by radare** [comment]
I have already updated the swift demangler. so i think we can close this issue for now.

There are still many things to be implemented in the current implementation, but at least its able to demangle most common signature constructions.

There are other issues to track the rest of stuff required to get better swift demangling
