### ISSUE TITLE
iz string length

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#4397]
morrn,

is it possible to specify string length in iz(z) like in strings -n ?

Greetings
--zlul

**Comment by Maijin** [comment]
bin.minstr: Minimum string length for r_bin
bin.maxstr: Maximum string length for r_bin

**Comment by Maijin** [comment]
and in rabin2:  -N [min:max]    force min:max number of chars per string (see -z and -zz)

**Comment by zonkzonk** [comment]
@maijin doesn't work

**Comment by Maijin** [comment]
what doesn't work

**Comment by zonkzonk** [comment]
forgot to set maxstr
