### ISSUE TITLE
Find more string references for MIPS and remove some false positives.

### ISSUE THREAD

**Issue by hummypkg** [radare/radare2#4403]
Thanks for making the changes in #4293 
Here's another patch that improves this, allowing it to find strings referenced through subtraction and removing some references that aren't relevant by checking the register name (works for me, there may be a better way of doing this...)

[mipsrel2.diff.txt](https://github.com/radare/radare2/files/185936/mipsrel2.diff.txt)

Without the patch:

    [0x00413aa0]> pd 1 @ 0x008e19fc;pd 1 @ 0x008e396c;pd 1 @ 0x0090a65c
       0x008e19fc      bc768424       a0 += 0x76bc                ; str.cont_count_ignore
       0x008e396c      fce7c426       a0 = s6 - 0x1804
       0x0090a65c      88d8c624       a2 -= 0x2778

and with:

    [0x00413aa0]> pd 1 @ 0x008e19fc;pd 1 @ 0x008e396c;pd 1 @ 0x0090a65c
       0x008e19fc      bc768424       a0 += 0x76bc                ; str.cont_count_ignore
       0x008e396c      fce7c426       a0 = s6 - 0x1804            ; str.fmt
       0x0090a65c      88d8c624       a2 -= 0x2778                ; str.HDD_Temp

**Comment by XVilka** [comment]
Please, provide also the test for radare2-regressions. Thank you!

**Comment by hummypkg** [comment]
New test file is at: http://hpkg.tv/misc/mips-busybox
and test script (t.anal/mips/mips-ref2)

    for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

    PLUGIN=mips

    NAME="mips hello ref anal subtract"
    BROKEN=
    ARGS="-e bin.strings=false -e anal.strings=true"
    FILE=../../bins/elf/busybox-mips
    CMDS="
    aae @entry0
    pd 1 @ 0x00406228

    "
    EXPECT='            0x00406228      fcc38424       addiu a0, a0, -0x3c04       ; str.busybox
    '

    run_test

**Comment by Maijin** [comment]
Well, a pull request is better in this case

**Comment by hummypkg** [comment]
I've created a pull request against radare2-regressions for the new test, #345

**Comment by hummypkg** [comment]
Closing since change has now been merged.
