### ISSUE TITLE
Incorrect JSON output at command ij

### ISSUE THREAD

**Issue by hteso** [radare/radare2#4404]
The command `ij`, at least with PE files, returns an incorrect JSON:

`"{"core":{"type":"EXEC (Executable file)","file":"/Users/hteso/Pocs/pocs/pe-w32-x86","fd":36,"size":23464,"mode":"-r--","obsz":0,"block":256,"format":"pe"},"bin":{"pic":false,"canary":false,"nx":false,"crypto":false,"va":true,"intrp":"","bintype":"pe","class":"PE32","lang":"","arch":"x86","bits":32,"machine":"i386","os":"windows","minopsz":1,"maxopsz":16,"pcalign":0,"subsys":"Windows CUI","endian":"little","stripped":false,"static":false,"linenum":true,"lsyms":false,"relocs":true,"rpath":"","binsz":"23464","compiled":"Thu Jul  3 22:09:54 2008","guid":"","dbg_file":"""hdr_cksum":"0x00012571""cmp_cksum":"0x00012571""crc32":"0x00012571","crc32c":"0x00012571",}}`

After `dbg_file` some fields have the `,` missing

**Comment by Maijin** [comment]
@lionaneesh See this

**Comment by radare** [comment]
See what? I already fixed this

**Comment by Maijin** [comment]
@radare I posted it prior you fixed it :P
