### ISSUE TITLE
New command needed for the /m web-ui

### ISSUE THREAD

**Issue by iriahi** [radare/radare2#4410]
I'm trying to display information shown at the bottom this [screenshot](https://imgur.com/UjdF6Dq).
As discussed with @radare, it would be great if a command exposed all the information needed.

**Comment by radare** [comment]
What info do we want to show here? i will probably implement this in the `aai` command (analyze-all-info).

**Comment by Maijin** [comment]
Or reuse content of p-h

**Comment by radare** [comment]
The bug is fixed, but there's still room for improvement. feel free to suggest changes and additions to the new `aai` command.
