### ISSUE TITLE
Mismatched r13 in esil emulation

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4420]
Binary: Ubuntu 14.04 /bin/ls
Instruction: mov r13d, edi
ESIL: rdi,r13d,=
Offset: 0x411733

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| r13     | 0x7fffffffe050 -> 0x1                 | 0x7fffffffe050 -> 0x7fff00000001      |

**Comment by sushant94** [comment]
__More__
Binary: Ubuntu 14.04 /bin/ls
Instruction: mov r13d, 4
ESIL: 4,r13d,=
Offset: 0x410a34

| REGISTER| GDB                                   | ESIL                                  |
|-----------------|------------------------------------|----------------------------------|
| r13     | 0x7fffffffdc80 -> 0x4                 | 0x7fffffffdc80 -> 0x7fff00000004      |

**Comment by Maijin** [comment]
@condret
