### ISSUE TITLE
Incorrect value of rax after xor eax,eax

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4422]
Binary: Ubuntu 14.04 /bin/ls
Instruction: xor eax, eax
ESIL: rax,eax,^=,$z,zf,=,$p,pf,=,$s,sf,=,0,cf,=,0,of,=
Offset: 0x4026c4

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rax     | 0xb623949448d72f00L -> 0x0            | -0x49dc6b6bb728d100 -> -0x49dc6b6c00000000 |

**Comment by sushant94** [comment]
__Similar__

Binary: Ubuntu 14.04 /bin/ls
Instruction: xor edx, edx
ESIL: rdx,edx,^=,$z,zf,=,$p,pf,=,$s,sf,=,0,cf,=,0,of,=
Offset: 0x40350a

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rdx     | 0x7ffff77a4258 -> 0x0                 | 0x7ffff77a4258 -> 0x7fff00000000      |
|---------|---------------------------------------|---------------------------------------|

**Comment by radare** [comment]
So xor edx is in fact rdx?

**Comment by sushant94** [comment]
No, I think according to x86 implementation, whenever 32 bit registers are
used, the higher order bits must be zeroed out. But, this is not the case
when 16/8 bit versions of the resister is used.

**Comment by zamaudio** [comment]
i thought rXx was just a superset of eXx with 32 extra bits on top...

**Comment by zamaudio** [comment]
so in terms of implementation, couldn't you make the lower 32 bits of rXx point to the same memory as eXx ?

**Comment by radare** [comment]
Should be already doing this. Can you share a test scriptto reproduce?

**Comment by zamaudio** [comment]
Fix provided in #4801

**Comment by radare** [comment]
Srsly?

**Comment by Maijin** [comment]
Yeah is not fixed :/

**Comment by zamaudio** [comment]
Because my fix #4801 was the wrong approach to fixing the bugs.  It still isnt fixed.

**Comment by condret** [comment]
so maybe we should make the esil here like this:
````eax,eax,^=,$z,zf,=,$p,pf,=,$s,sf,=,0,cf,=,0,of,=,0xffffffff,rax,&=````
