### ISSUE TITLE
xor r8d, r8d does not reset higher order bits

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4423]
Binary: Ubuntu 14.04 /bin/ls
Instruction: xor r8d, r8d
ESIL: r8d,r8d,^=,$z,zf,=,$p,pf,=,$s,sf,=,0,cf,=,0,of,=
Offset: 0x4034c2

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| r8      | 0x7fffffffdab0 -> 0x0                 | 0x7fffffffdab0 -> 0x7fff00000000      |

**Comment by crowell** [comment]
This is surprising. R8D refers to the lower dword of r8

**Comment by FelixBer** [comment]
This is one of the gotchas with x86_64: operations on 32 bit regs generally zero-extend to their 64 bit length.

Same for example:
mov rax, -1
mov eax, 0
//now rax == 0

**Comment by zamaudio** [comment]
Fix provided in #4801 for XOR and AND

**Comment by Maijin** [comment]
@condret

**Comment by condret** [comment]
should be fixed now
