### ISSUE TITLE
Incorrect ESIL AND

### ISSUE THREAD

**Issue by sushant94** [radare/radare2#4432]
Binary: Ubuntu 14.04 /bin/ls
Instruction: and edx, 0x200
ESIL: 512,edx,&=,0,of,=,0,cf,=,$z,zf,=,$s,sf,=,$o,pf,=
Offset: 0x40c3a7

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rdx     | 0xffffffffffffffffL -> 0x200          | -0x1 -> -0xfffffe00                   |

**Comment by sushant94** [comment]
Possibly related to #4423. Again, the higher order bits do not seem to have been reset.
Will close once I confirm.

**Comment by zamaudio** [comment]
Fix provided in #4801

**Comment by condret** [comment]
AAAAH! Don't do this! Internal vars don't work like this ````512,edx,&=,0,of,=,0,cf,=,$z,zf,=,$s,sf,=,$o,pf,=```` always handle them first, before you do any constant flag settings. It should be like this ````512,edx,&=,$z,zf,=,$s,sf,=,$o,pf,=,0,of,=,0,cf,=````
