### ISSUE TITLE
e asm.reloff = true doesn't display flag+offset

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4435]
e asm.reloff = true doesn't display flag+offset

like main+0x3, main+0xa...

**Comment by radare** [comment]
asm.refloff is suposed to show the offset in relative, aka in disasm :

```      0x00005df0      31ed           xor ebp,
ebp

                  +0x2      4989d1         mov r9,
rdx

                  +0x5      5e             pop
rsi

                  +0x6      4889e2         mov rdx,
rsp

                  +0x9      4883e4f0       and rsp,
0xfffffffffffffff0

                  +0xd      50             push
rax

                  +0xe      54             push
rsp

                  +0xf      4c8d05aaf300.  lea r8, [rip + 0xf3aa]      ;
0x151b0

                 +0x16      488d0d33f300.  lea rcx, [rip + 0xf333]     ;
0x15140

                 +0x1d      488d3d6cdeff.  lea rdi, [rip - 0x2194]     ;
0x3c80 ; section..text ; "AWAVAUATI..US..H...." @
0x3c80

                 +0x24      e8a7daffff     call sym.imp.__libc_start_main
;[1]

                 +0x29      f4
hlt

```

soi you are expecting this var to do something else

On 27 March 2016 at 13:35, Maijin <notifications@github.com> wrote:

> e asm.reloff = true doesn't display flag+offset
>
> like main+0x3, main+0xa...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4435>
>



-- 
--pancake

**Comment by Maijin** [comment]
ok so another eval variable then ? or maybe int like e asm.reloff = 1 for the current and e asm.reloff = 2 to have it relative from the flag like gdb is doing or even like in visual mode.

**Comment by radare** [comment]
marked as question so other ppl can discuss this

**Comment by Maijin** [comment]
fixed by asm.symbols :)
