### ISSUE TITLE
Segfault when radare takes .class file as parameter

### ISSUE THREAD

**Issue by alexandrasandulescu** [radare/radare2#4444]
$ radare2 Main.class
$ dmesg | tail
radare2[7030]: segfault at 2c ip 00007f66ede29149 sp 00007ffdcdc0a730 error 4 in libr_bin.so.0.9.6[7f66edde7000+59000]
$ file Main.class
Main.class: compiled Java class data, version 51.0
$uname -a
Linux mortimer 3.19.0-56-generic #62-Ubuntu SMP Thu Mar 10 22:40:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by crowell** [comment]
can you share the offending .class file?

**Comment by alexandrasandulescu** [comment]
@crowell , yes. The interesting fact is that I installed radare2 from sources and the issue did not appear again.  So the Ubuntu version has this issue.
$  radare2 -version
radare2 0.9.6 @ linux-little-x86-64 git.0.9.6
commit: 1: build: 2014-04-10
[java-class.zip](https://github.com/radare/radare2/files/191948/java-class.zip)

**Comment by crowell** [comment]
closing. the ubuntu version is super out of date.
