### ISSUE TITLE
Api in ref.c is just a superset of xrefs.c

### ISSUE THREAD

**Issue by radare** [radare/radare2#4448]
But it just makes things a bit confusing.

**Comment by MaskRay** [comment]
which one should be kept

**Comment by Maijin** [comment]
ping @radare

**Comment by radare** [comment]
I want to have the dict replacing sdb for xrefs before reviewing that. I have already though on that issue a bit and this will go after that. I have some other optimizations for dict to come introduce

**Comment by Maijin** [comment]
Link #9061

**Comment by radare** [comment]
isnt this fixed in your pr @rlaemmert ?

**Comment by ret2libc** [comment]
This should have been resolved with https://github.com/radare/radare2/commit/b703dfbf17c0cff54181627fb40da92de3a52b79
