### ISSUE TITLE
"aga" command empty graph

### ISSUE THREAD

**Issue by hteso** [radare/radare2#4450]
For very simple functions, with no basic blocks, the command `aga` returns an empty graph:

```
digraph code {
	graph [bgcolor=white];
	node [color=lightgray, style=filled shape=box fontname="Courier" fontsize="8"];
}
```

It would be better if it returns a graph with one single node with the function address.

**Comment by radare** [comment]
the aga command just draws edges. the nodes are implicit to the edges
