### ISSUE TITLE
Change aga output format

### ISSUE THREAD

**Issue by hteso** [radare/radare2#4451]
It would be nice to change the design of the graph generated by the `aga` command. An example of the actual one and the proposal follows:

- Actual design:

```
digraph code {
    graph [bgcolor=white];
    node [color=lightgray, style=filled shape=box fontname="Courier" fontsize="8"];
    "0x08048d60_0x08048d60" -> "0x08048d60_0x08048d7c" [color="green"];
    "0x08048d60_0x08048d60" -> "0x08048d60_0x08048d70" [color="red"];
    "0x08048d60_0x08048d7c" -> "0x08048d60_0x08048e36" [color="green"];
    "0x08048d60_0x08048d7c" -> "0x08048d60_0x08048de3" [color="red"];
    "0x08048d60_0x08048de3" -> "0x08048d60_0x08048d70" [color="green"];
    "0x08048d60_0x08048de3" -> "0x08048d60_0x08048dfb" [color="red"];
    "0x08048d60_0x08048dfb" -> "0x08048d60_0x08048d70" [color="blue"];
}

``` 

- New design:
 
```
digraph code {
        graph [bgcolor=invis, splines=polyline];
        node [style="filled" fillcolor="white" shape=box fontname="Courier" fontsize="8" color="#2A83FF" fontcolor="#2A83FF"];
        edge [arrowhead="vee"];
        "0x08048d60" -> "0x08048d7c" [color="#88FF88"];
        "0x08048d60" -> "0x08048d70" [color="#FF6666"];
        "0x08048d7c" -> "0x08048e36" [color="#88FF88"];
        "0x08048d7c" -> "0x08048de3" [color="#FF6666"];
        "0x08048de3" -> "0x08048d70" [color="#88FF88"];
        "0x08048de3" -> "0x08048dfb" [color="#FF6666"];
        "0x08048dfb" -> "0x08048d70" [color="#2A83FF"];
}
```

**Comment by radare** [comment]
The reason for those basic blocks names is that a basic block can be shared between two functions. so graphs dont get mixed when disassebling more than one function because the address is "fcnaddr_bbaddr"

**Comment by radare** [comment]
all the color stuff can be "fixed" with a regexp in your side... but i agree that we should probably honor the color palete loaded in r2 rather than hardcoding "red" or "green" ... or maybe just add new `graph.` config vars

**Comment by radare** [comment]
i dont plan to do this change for 0.10.2, it may break some stuff in the future and i prefer proper discussion and testing. you can fix all those issues in your side with regexpes if you need.

**Comment by radare** [comment]
I can also add a config var disabled by default to show the output in the way you expect too.. but it will be a temporary fix

**Comment by ret2libc** [comment]
I don't have a strong opinion on that. I agree that using the right palette would be cool, but probably not so urgent. Maybe someone else want to fix that :)

**Comment by radare** [comment]
in fact ec graph. works as expected with aga

**Comment by radare** [comment]
I have added graph.gv.{edge|node|graph} variables to change the style you want. that kind of arrow is now the default. and the color of the lines can be configured using `ec graph.true rgb:00ff00` and the same for `false` and `trufae` (blue lines)
