### ISSUE TITLE
"Show xrefs to current function" refers to the wrong instruction in visual mode with cursor enabled

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#4453]
The "show xrefs" feature (`x`) in visual mode of the command line interface is unintuitive when the cursor is enabled. It seems that the feature always shows xrefs to the instruction at the top of the current window scroll position. Instead, I would expect xrefs to the instruction at the cursor position to be shown.

Steps to reproduce:
* Run `radare2 /usr/bin/ls`
* Enter `aaa` to perform full analysis starting from the program entrypoint
* Enter `V` to enter visual mode
* Hit `p` to move to the disassembly view
* Scroll the view to some function call or branch instruction, hit `enter` to follow the branch. Note how pressing `x` should now properly show you the xrefs to that function, and in particular the offset of the call instruction you jumped from.
* Hit `c` to enable the cursor. Move it down by one instruction (without scrolling the whole disassembly view). Try to see the xrefs by pressing `x`, and notice that the xrefs will either not be shown at all or different ones will be shown than one would expect.

**Comment by radare** [comment]
You can just say that cursor is ignored for Vx

**Comment by radare** [comment]
The fix was shorter than the description of the bug

**Comment by neobrain** [comment]
Heh, thanks!
