### ISSUE TITLE
null in pf*x

### ISSUE THREAD

**Issue by radare** [radare/radare2#4466]
```
[0x00000014]> pf*x
f (null)=0x00000014
```

**Comment by radare** [comment]
question is. if there's no name given to a specific field for a pf string, which flag name should we use? something generic? something random? nothing?

**Comment by radare** [comment]
@Hyask ?

**Comment by Hyask** [comment]
Tell the user to use the syntax specifying a name?

**Comment by radare** [comment]
What if the user gets offended because its against his religion?

**Comment by radare** [comment]
I think the best option here would be to add some generic flag names for this.

`pf.0` , `pf.1`, ...

**Comment by Hyask** [comment]
Nice! :)
