### ISSUE TITLE
call-refs & data-refs not saved (or loaded) in projects

### ISSUE THREAD

**Issue by radare** [radare/radare2#4480]
```
r2 -nqc "Pd jeje" -
r2 -p jeje -AA /bin/ls
r2 -p jeje -cVp
```

now scroll up by pressing 'k' and be amazed by how fucked up is something.

now type `afi`, and see how the call-refs and data-refs are gone.

**Comment by Maijin** [comment]
Tracked here https://github.com/radare/radare2/issues/6945
