### ISSUE TITLE
radiff2 -C not working

### ISSUE THREAD

**Issue by NaveenBoggarapu** [radare/radare2#4482]
In radiff2 -C option was working till a461bbc5364f907e49903a6630ba787eb4f9ee45.

It used to report in the following way, but it is not working now

```
naveen@naveen:~/Analysis1$ radiff2 -C test1 test1_sim
                   entry0  42 0x400400 |   MATCH  (1.000000) | 0x400400   42 entry0
sym.imp.__libc_start_main  32 0x4003e0 |   MATCH  (1.000000) | 0x4003e0   32 sym.imp.__libc_start_main
                 sym.main  38 0x4004ed | UNMATCH  (0.973684) | 0x4004ed   38 sym.main
 sym.deregister_tm_clones  48 0x400430 |   MATCH  (1.000000) | 0x400430   48 sym.deregister_tm_clones
   sym.register_tm_clones  64 0x400460 |   MATCH  (1.000000) | 0x400460   64 sym.register_tm_clones
sym.__do_global_dtors_aux  28 0x4004a0 |   MATCH  (1.000000) | 0x4004a0   28 sym.__do_global_dtors_aux
          sym.frame_dummy  42 0x4004c0 |   MATCH  (1.000000) | 0x4004c0   42 sym.frame_dummy
      sym.__libc_csu_fini   2 0x400590 |   MATCH  (1.000000) | 0x400590    2 sym.__libc_csu_fini
                sym._fini   9 0x400594 |   MATCH  (1.000000) | 0x400594    9 sym._fini
      sym.__libc_csu_init 101 0x400520 |   MATCH  (1.000000) | 0x400520  101 sym.__libc_csu_init
                sym._init  26 0x4003a8 |   MATCH  (1.000000) | 0x4003a8   26 sym._init
   loc.imp.__gmon_start__  48 0x4003f0 |   MATCH  (1.000000) | 0x4003f0   48 loc.imp.__gmon_start__
```

In commit f4618c0bbd2208359faca7ac361f275dc24e0bce there are few changes made causing this.

The change mainly came from libr/core/gdiff.c (function: r_core_gdiff). 

**There is no analysis done in r_core_gdiff**, quick fix is to add `r_core_anal_all (cores[i]);` in the for loop.

Similar result is available by using -AAC option, but it also prints out other unwanted information

**Comment by NaveenBoggarapu** [comment]
I have fixed and checked it.

It is working fine.

**Comment by radare** [comment]
So we can close this thing

**Comment by radare** [comment]
this patch is not included in master, and it was not included in your PRs.

**Comment by radare** [comment]
What about `radiff2 -AC a b` ? by default radiff2 is not performing any analysis, only for the public symbols and entrypoint. the -A was implicit before and it was causing problems in some binaries

**Comment by NaveenBoggarapu** [comment]
I have realized that the fix is done in a wrong place, I am still working on it.

`radiff2 -AC a b` gives the output but along with other unwanted information.

**Comment by radare** [comment]
Which unwanted info?

We should run basic analysis on all syms. Is this the issue withiut -A?

**Comment by NaveenBoggarapu** [comment]
Following is the output when ran using `-AC`

```
naveen@naveen:~/Analysis1$ radiff2 -AC test1 test1_sim
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
                   entry0  42 0x400400 |   MATCH  (1.000000) | 0x400400   42 entry0
sym.imp.__libc_start_main  32 0x4003e0 |   MATCH  (1.000000) | 0x4003e0   32 sym.imp.__libc_start_main
                 sym.main  38 0x4004ed | UNMATCH  (0.973684) | 0x4004ed   38 sym.main
 sym.deregister_tm_clones  41 0x400430 |   MATCH  (1.000000) | 0x400430   41 sym.deregister_tm_clones
   sym.register_tm_clones  57 0x400460 |   MATCH  (1.000000) | 0x400460   57 sym.register_tm_clones
sym.__do_global_dtors_aux  28 0x4004a0 |   MATCH  (1.000000) | 0x4004a0   28 sym.__do_global_dtors_aux
          sym.frame_dummy  42 0x4004c0 |   MATCH  (1.000000) | 0x4004c0   42 sym.frame_dummy
      sym.__libc_csu_fini   2 0x400590 |   MATCH  (1.000000) | 0x400590    2 sym.__libc_csu_fini
                sym._fini   9 0x400594 |   MATCH  (1.000000) | 0x400594    9 sym._fini
      sym.__libc_csu_init 101 0x400520 |   MATCH  (1.000000) | 0x400520  101 sym.__libc_csu_init
                sym._init  26 0x4003a8 |   MATCH  (1.000000) | 0x4003a8   26 sym._init
   loc.imp.__gmon_start__  48 0x4003f0 |   MATCH  (1.000000) | 0x4003f0   48 loc.imp.__gmon_start__
```

The debug messages before the actual output is the unwanted messages, I was referring to.

`-A` has no issue, it is just that it prints all the debug messages along with the output.

just an increment of `anal_all` and disabling debug messages option will do. But since, I am new to the project. I am going through the code and in the process of understanding the internals.

**Comment by radare** [comment]
Those messages are in stderr, so you can redirext them if they are anoying to you.

Without -A which is the problem? That it only takes symbols and doesnt analyzes further?

**Comment by NaveenBoggarapu** [comment]
Yes, the problem is it only takes symbols and doesn't analyzes further.

**Comment by radare** [comment]
that’s the expected behaviour, otherwise with some binaries the analysis “further” can take A LOT of time. thats why i added -A and -AA. So i guess we can close the issue
