### ISSUE TITLE
issue with address calculation for ARM with -d (debug) flag

### ISSUE THREAD

**Issue by Jegeva** [radare/radare2#4487]
binary is in issue 4484

calcualted adresses are wrong in an arm target with debug flag

without -d :

[15:47:34][531] jg@N0cte:~/hack/iotad/STM32L100C-Discovery/iotad_victim_board$ r2 -AA -a arm main.elf
Warning: Cannot initialize dynamic strings
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[0x0800071c esil_trap: missing parameters in stack
[x] Emulate code to find computed references (aae)
[>] Scanning -r-x 0x800013c - 0x8003a78 skip
[>] Scanning mrwx 0x8000000 - 0x8003a84 done
[>] Scanning -rwx 0x8000000 - 0x8044150 skip
Analyzed 1 functions based on preludes
[x] Finding function by preludes (aap)
[x] Analyze consecutive function (aat)
[x] Constructing a function name for fcn.\* and sym.func.\* functions (aan)
 -- Trace register changes while debugging with 'e trace.cmtregs=true'
**_[0x080035f4]>**_

with -d : (gdbserver is openocd on a stm31 dev board)

[15:49:20][532] jg@N0cte:~/hack/iotad/STM32L100C-Discovery/iotad_victim_board$ r2 -AA -a arm -D GDB -d main.elf gdb://localhost:3333
Process with PID 17726 started...
attach 17726 17726
bin.baddr 0x55b7ea2fe000
Assuming filepath ./main.elf
Warning: Cannot initialize dynamic strings
asm.bits 16
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[Oops invalid rangen calls (aac)
[x] Analyze function calls (aac)
[x] Emulate code to find computed references (aae)
[>] Scanning -r-x 0x7f9e0eb83000 - 0x7f9e0eba5000 done
Analyzed 0 functions based on preludes
[x] Finding function by preludes (aap)
[Cannot find section boundaries in here
[x] Analyze consecutive function (aat)
[x] Constructing a function name for fcn.\* and sym.func.\* functions (aan)
 -- Move the comments to the right changing their margin with asm.cmtmargin
**_[0x7f9e0eb83c90]>**_

**Comment by radare** [comment]
thats because the base address of the target binary is not properly recognized via gdb
you can override this value if you know it before hand. can you tell which line did you used to connect to the gdbserver?

**Comment by Jegeva** [comment]
r2 -AA -a arm -D GDB -d main.elf gdb://localhost:3333

if i use gdb like
$gdb-multiarch ./main.elf
(gdb) target extended localhost:3333
gdb works fine

**Comment by radare** [comment]
This is wrong way to talk to gdb

**Comment by Jegeva** [comment]
then there is a problem with slide 70 of the hack.lu preso.
http://2015.hack.lu/archive/2015/radare2-workshop-slides.pdf

what is the correct way then ?

**Comment by Maijin** [comment]
Are you realising that the project is moving fast ? Workshop is from October 22, 2015 which like SUPER OLD...

**Comment by radare** [comment]
Thia thing never changed... Several things:

- The gdb plugin is in lowercase.
- The gdb plugign doesnt accept filenames
- the io plugin for gdb must match the debug one, otherwise it makes no sense what u read and what you debug.

The short way is:

r2 -d gdb://ip:port

The long way:

r2 -D gdb gdb://ip:port

To load the file, symbols, flags, etc. u mist do this from memory, and if u have a local copy of the bin just use .!rabin2... With the base address in -B to relocate them properly

**Comment by radare** [comment]
Also more things wrong in ur line:

-AA is useless here because most analysis depend on symbolinfo which is not loaded yet

- no -b flag passed to spexify bits. So u are probably disassembling arm64 . Use -a arm -b 32 at load time

**Comment by radare** [comment]
And slide 70 is wrong . This thing never worked like this.

**Comment by Maijin** [comment]
@XVilka ^

**Comment by XVilka** [comment]
Yes, I know, it's a mistake / typo.

**Comment by Jegeva** [comment]
even if it's a typo it would make sense for this case (ie remote debugging an arm board with an openocd gdb server, having the elf) maybe automating the rabin2 part with a command line option could be nice... can this become a feature request ?

**Comment by radare** [comment]
Yes. And im open to suggestions, but i dont know a way to get filenames from gdb protocol. And not sure about base address. But yep its desirable for sure :)

**Comment by radare** [comment]
can you please verify that this issue is still happening? a lot have changed in r2 for arm and debugger since 2016, it is probably fixed already.
