### ISSUE TITLE
Add function str2reg/reg2str like in IDA

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#4492]
In IDAapi we have function str2reg:
```str2reg('esi') -> 6```

It will be cool if it will be work in radare2. And IDA hasn't got a function for this operation:
```reg2str(6) -> 'esi'```

But sometimes we need it

**Comment by Maijin** [comment]
```
Convert a register name to a register number.

The register number is the register index in the processor_t::regNames array Most processor modules do not need to implement this callback It is useful only if processor_t::regNames[reg] does not provide the correct register names

Parameters
regname	(const char *)
Returns
register number + 2
```

**Comment by Maijin** [comment]
What's the usecase for this btw

**Comment by dukebarman** [comment]
Now it's need for unicorn plugin in IDA but may will be useful for radare2

**Comment by radare** [comment]
Just grab the regprofiles, solit by newlines and get the nth line that matches the reg. Why do you need this? Imho its bad api design, like most ida apis.

**Comment by radare** [comment]
Wat? And why and how do u need this in r2?

**Comment by XVilka** [comment]
Am I wrong, or r2 was already supporting unicorn at some point?

**Comment by Maijin** [comment]
Is already supporting unicorn without this stuff, this issue seems useless.

**Comment by dukebarman** [comment]
No problem. It was a offer feature.
