### ISSUE TITLE
pf.aaa [10]D ; pf.aaa => Size not yet implemented

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4494]
pf.aaa [10]D ; pf.aaa => Size not yet implemented

**Comment by radare** [comment]
Cc @hyask

**Comment by Hyask** [comment]
I'll do that when I'll find the time to! :)

**Comment by XVilka** [comment]
ping

**Comment by Hyask** [comment]
Yup, I'm sorry, but with my studies, I won't have any time before this summer... :/

**Comment by radare** [comment]
cc @oddcoder 

ping @Hyask

**Comment by Maijin** [comment]
Oops it's done.
