### ISSUE TITLE
Recursive asm.emu

### ISSUE THREAD

**Issue by radare** [radare/radare2#4497]
asm.emu is now lineal to `pd`. this is "ok" for most use cases, but it's a problem when a function is more complex and reuses values computed in different paths. This issue aims to extend `pdr` to evaluate and save/restore the state of the esil vm on every basic block. so the next blocks can inherit the state.

**Comment by mrmacete** [comment]
i have a wip solution for this, will open a PR in few hours

**Comment by radare** [comment]
Awesome!! 💥
