### ISSUE TITLE
rasm2 arm

### ISSUE THREAD

**Issue by McLovi9** [radare/radare2#4502]
Not sure if its a bug since I'm new to rasm2, anyway I tried to assemble ARM code for patching but it fails, does anyone know what the problem with this command line ?

```
> rasm2 -a arm -o 0xFB0001CC "blx 0xfb0005d1"

This branch does not accept off as arg
This branch does not accept off as arg
This branch does not accept off as arg
Cannot assemble 'blx 0xfb0005d1' at line 3 invalid
```

**Comment by radare** [comment]
you are missing the -b to specify thumb, arm32 or aarch64. but yes. this is a bug because blx on arm32 expects an address instead of a register. which is what i guess what you are trying to do

**Comment by McLovi9** [comment]
wow, that was quick! Thanks

**Comment by Maijin** [comment]
@McLovi9 ;)

**Comment by radare** [comment]
See the commit and feel free to send patches to support more instructions when you need them

**Comment by McLovi9** [comment]
question how to gen blx instr in thumb mode ?

e.g. arm thumb code from dissasembler
```
0xF400048A FF F7 54 EE    BLX    0xF4000134
```
I tried
```
rasm2 -b16 -a arm -o 0xFB00048A "blx 0xfb000134"
branch out of range or not even
branch out of range or not even
branch out of range or not even
Cannot assemble 'blx 0xfb000134' at line 3
invalid
```

**Comment by radare** [comment]
you can try with the gas assembler, there’s a plugin in r2 for that. or just dump some dev/random and disassemble it with r2 and grep for blx

```
prop:~ pancake$ dd if=/dev/random of=random
^C37092+0 records in
37092+0 records out
18991104 bytes transferred in 1.483207 secs (12804082 bytes/sec)
prop:~ pancake$ r2 -a arm -b16 random
 -- Please register your copy of r2 today! Only £29.90!
[0x00000000]> pd 100~blx
[0x00000000]> pd 1000~blx
   ||||     0x00000286      f7f1c6ed       blx 0x1f7e14
  |||| ||   0x000003fa      63f686ee       blx 0xffe64108
  |||| ||   0x0000045e      07f6eee0       blx 0xffa0763c
```

do you want to send a PR implemneting the BLX <IMM> thumb instruction for the armass?

**Comment by radare** [comment]
(i did it for arm32), you can easily read that code as a sample for your PR if you want to contribute

**Comment by McLovi9** [comment]
Thanks, unfortunately I'm occupied with other issues so I wont be able to contribute at least no in the upcoming week.

**Comment by radare** [comment]
@Maijin can you add some tests? https://github.com/radare/radare2-regressions/issues/359

**Comment by McLovi9** [comment]
I just tested blx thumb and it's not always working e.g.

0xF400048A FF F7 54 EE    BLX    0xF4000134
```
~$ rasm2 -b 16 -a arm -o 0xFB00048A "blx 0xFB000134"
Invalid destination for blx
Invalid destination for blx
Invalid destination for blx
Cannot assemble 'blx 0xFB000134' at line 3 invalid
```

**Comment by radare** [comment]
Can you add a test in the r2r repo?

Do you wanna try to fix it?

**Comment by McLovi9** [comment]
I'd prefer someone else to fix it.

How do you add a test ? Append to radare2-regressions/t.asm/arm/thumb something like this ?
```
NAME="${PLUGIN}: arm-thumb-mclass"
CMDS='rasm2 -b16 -a arm -o 0xFB00048A "blx 0xfb000134"'
EXPECT='fff754ee'
```

**Comment by Maijin** [comment]
What about looking in the repo... https://github.com/radare/radare2-regressions/blob/master/t.asm/arm/arm
