### ISSUE TITLE
Cursor not repositioned to branch site in Vu

### ISSUE THREAD

**Issue by neobrain** [radare/radare2#4504]
When following a branch and returning to the call site using `u` in visual mode, the cursor is not repositioned to the branching instruction (radare2 instead scrolls the view to cover the branching instruction, and the cursor gets moved to the top of the view), hence making navigation in cursor mode fairly confusing.

Asciinema showing the issue: https://asciinema.org/a/7n3t66o6oxmnyuu0jrg9jfvvi

**Comment by radare** [comment]
We have a seek history but this doesnt stores the cursor history. Which looks like q nice feature request to me.

**Comment by radare** [comment]
We should also store selection ranges. moving to 0.10.3

**Comment by radare** [comment]
maybe @rlaemmert can take a look at this too

**Comment by rlaemmert** [comment]
So you would like to add every move you make with your cursor to another history?
maybe we should pimp the whole history thing? I would also like some functions only history, that would also be useful for the graph i think. Anyway sounds like a cool feature.

**Comment by ret2libc** [comment]
I think we don't need every cursor move, just store the position of the cursor when we jump elsewhere, for example when you follow a branch or change offset with `o` and so on.

**Comment by radare** [comment]
Agree, but we should save cursor position and offset

**Comment by ret2libc** [comment]
@rlaemmert are you on this or do you want to do this?

**Comment by rlaemmert** [comment]
not yet, had not much time to think about it actually

**Comment by rlaemmert** [comment]
any ideas where to save the cursor postion? undo.c seems to be the wrong place for that?

**Comment by ret2libc** [comment]
@rlaemmert good question.. cursor is in RPrint at the moment, so maybe it would make sense to put the functionalities there or also directly in `core/visual.c` or in a new file `core/visual_undo.c`.

**Comment by radare** [comment]
We can push the cursor info when pushing the new undo offset, so the cursor can be saved there. No need to keep two histories in parallel

**Comment by rlaemmert** [comment]
i think we can close this?

**Comment by ret2libc** [comment]
I think so :) Thanks!
