### ISSUE TITLE
RCore not being used by most r*2 tools?

### ISSUE THREAD

**Issue by Lukas-Dresel** [radare/radare2#4506]
When i run `grep -R RCore binr/` i only see usages in 
`preload/libr2.c`, `radare2/radare2.c`, `radiff2/radiff2.c` and `rabin2/rabin2.c`.

Isn't the core and all its unifying functionality supposed to be used by every tool?

This leads me to assume that issue #4495 could also be present in all the other tools, not only rasm2. Is this a relic or intended?

**Comment by radare** [comment]
Nope. Not all of them use rcore

**Comment by Lukas-Dresel** [comment]
Can i then assume that at least every tool that loads plugins uses the core?

**Comment by radare** [comment]
nope
