### ISSUE TITLE
libr/util/lib.c doesn't fit into /util

### ISSUE THREAD

**Issue by Lukas-Dresel** [radare/radare2#4513]
I stumbled across this, because a TODO in `libr/core/libs.c` says that the default paths should be in r_lib. But as far as i can find the implementations of r_lib are found in `libr/util/` which doesn't seem a very appropriate location to store default plugin paths. Is this intended? Especially because this file contains all the structures necessary for the plugins, so having it in the `libr/util` tree seems weird to me.

**Comment by Lukas-Dresel** [comment]
Can we move it either to the core or in a seperate plugins folder? Or even split it up into actual utilities as in `libr/util/lib.c` for architecture-dependent library loading and `libr/plugins/plugins.c` or something for the actual plugin related functionality. Essentially splitting up what it references as high-level and low-level API into different places.

**Comment by radare** [comment]
yep. makes sense to centralize this somewhere outside r_core, but i would like to know which path is missing there

**Comment by Lukas-Dresel** [comment]
what do you mean which path is missing there?

**Comment by radare** [comment]
why not just put that plugins.c into util/? creating new modules is a heavy operation for the linker and so on. for just few helper functions i would prefer to have them in r_util.

**Comment by radare** [comment]
it was already in r_lib, but i find it unnecessary to have this functionality splitted and i merged it into util/

**Comment by radare** [comment]
Closing for now, i dont see an issue to have this in there
