### ISSUE TITLE
Feature Request - get symbols and base adress from a local binary while debugging on a remote gdb server 

### ISSUE THREAD

**Issue by Jegeva** [radare/radare2#4522]
gdb allows you to do that by:

$gdb ./binary
(gdb) target host:port
(gdb) ...

apparently you can do that by invoking rabin2 inside radare after invoking r2 -d gdb://
-base adress should be obtainable from the binary (at elast elfs) as well as the syms.
-r2 could -a the local executable also

it could go like:

r2 -A -a assembly -b asm_size -E /path/to/executable -D dbg_backend -d gdb://host:port

(-E is not taken atm is r2 -help, -E would stand for Executable)

**Comment by radare** [comment]
if you use -d gdb:// you dont need to use -D because it's implicit. so the final line would be:

`r2 -A -a arm -b 16 -E /path/to/bin -d gdb://host:port`

The thing is.. from this line, arch+bits can be grabbed from the gdb server, but we dont support those commands yet (not all gdbservers report this info) and the -E seems a bit ugly since we can probably handle that in the same uri like this:

`r2 -A -a arm -b 16 -d gdb://host:port/localfile`

**Comment by XVilka** [comment]
this could be done by calling 'rabin2' for dumping dwarf/pdb info.

**Comment by XVilka** [comment]
But automating this is indeed would be awesome.

**Comment by radare** [comment]
yep, that's why this issue is for. discussing and finding better ways to automate this process :)

**Comment by Jegeva** [comment]
gdb://host:port/localfile is ***much more elegant*** but i think there is some caveats to it :

-to give absolute path would be ugly (f.e. gdb://host:port//bin/ls) dunno how you parse the uri but // is still legal i think
-this would prevent future extention where the bin could be at a uri fetched by r2 (marginally useful but still)

**Comment by jduck** [comment]
I prefer the -E method. There might already be another supported option thought I'm not sure. What if the user opens the binary with r2 and then uses some form of "doo" to then open a gdb:// session? Does that work? Will analysis be preserved?

**Comment by radare** [comment]
analysis is saved in projects. but maybe it sohuld be preserved across sessions too

**Comment by radare** [comment]
works fine with oa and ob. but it's just a manual process

**Comment by XVilka** [comment]
This one is closed, but might gave some ideas for @SrimantaBarua
