### ISSUE TITLE
[r2pip2]returned object of `isj` command

### ISSUE THREAD

**Issue by benquike** [radare/radare2#4524]
I want to use "is" command to get the list of symbols in the file.

If I use `is` command, I can get a list of symbols in which type information is included:
[0x00000040]> is
      [Symbols]
      vaddr=0x00000040 paddr=0x00000040 ord=011 fwd=NONE sz=11 bind=GLOBAL type=FUNC name=int_cmp
      vaddr=0x00000050 paddr=0x00000050 ord=012 fwd=NONE sz=13 bind=GLOBAL type=FUNC name=float_cmp
      vaddr=0x00000060 paddr=0x00000060 ord=013 fwd=NONE sz=176 bind=GLOBAL type=FUNC name=mysort
      vaddr=0x00000040 paddr=0x00000040 ord=015 fwd=NONE sz=366 bind=GLOBAL type=FUNC name=main
      vaddr=0x00000040 paddr=0x00000040 ord=014 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.memcpy
      vaddr=0x00000040 paddr=0x00000040 ord=016 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.__printf_chk
      vaddr=0x00000040 paddr=0x00000040 ord=017 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.putchar
      vaddr=0x00000040 paddr=0x00000040 ord=018 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.__stack_chk_fail

But if I switch to `isj` command, the type information is lost:

    [{"name":"int_cmp","demname":"","flagname":"sym.int_cmp","size":11,"vaddr":64,"paddr":64},    {"name":"float_cmp","demname":"","flagname":"sym.float_cmp","size":13,"vaddr":80,"paddr":80},{"name":"mysort","demname":"","flagname":"sym.mysort","size":176,"vaddr":96,"paddr":96},{"name":"main","demname":"","flagname":"sym.main","size":366,"vaddr":64,"paddr":64},{"name":"imp.memcpy","demname":"","flagname":"loc.imp.memcpy","size":16,"vaddr":64,"paddr":64},{"name":"imp.__printf_chk","demname":"","flagname":"loc.imp.__printf_chk","size":16,"vaddr":64,"paddr":64},{"name":"imp.putchar","demname":"","flagname":"loc.imp.putchar","size":16,"vaddr":64,"paddr":64},{"name":"imp.__stack_chk_fail","demname":"","flagname":"loc.imp.__stack_chk_fail","size":16,"vaddr":64,"paddr":64}]

I want to use `isj` because I do not want to parse the returned string myself.

Is is possible to add the type information if `isj` command is used ?

**Comment by radare** [comment]
Of course, and this can be achieved with just 1 line of code in libr/core/bin.c do you wanna try to send a pr?

**Comment by jpenalbae** [comment]
@benquike you should take a look to pullreq #4527 it was a real easy fix as @radare stated....

**Comment by benquike** [comment]
Confirmed, thanks
