### ISSUE TITLE
the starting VA address of object files

### ISSUE THREAD

**Issue by benquike** [radare/radare2#4525]
I found that if the binary is an object file (not an executable), the starting position will be set to 0x40 and the starting addresses of all the functions in the object file will be added by 0x40.

Is there anyway to override this behavior?

**Comment by radare** [comment]
Use -B

**Comment by Maijin** [comment]
man r2 ; r2 -hh

**Comment by benquike** [comment]
@Maijin I am opening binaries using r2pipe, is there any way to pass this option to r2 if I use r2pipe.open()?

**Comment by radare** [comment]
pydoc r2pipe 

all this stuff is documented. the 2nd argument of open() is an array of flags that will be passed to r2 on spawn

**Comment by benquike** [comment]
Help on class open in module r2pipe:

class open
 |  Class representing an r2pipe connection with a running radare2 instance
 |  
 |  Methods defined here:
 |  
 |  __init__(self, filename='', writeable=False, bininfo=True, debug=False)
 |      Open a new r2 pipe
 |      The 'filename' can be one of the following:
 |      
 |      * absolute or relative path to file
 |      * http://<host>:<port>/cmd to connect to an r2 webserver
 |      * tcp://<host>:<port> to connect to an r2 tcp server
 |      * #!pipe when launching it from r2 via RLang.pipe
 |      
 |      Args:
 |              filename (str): path to filename or uri
 |              writeable (bool): if True opens the file in read-write
 |              bininfo (bool): if True loads the info from the binary
 |              debug (bool): if True opens in debugger (r2 -d)
 |      Returns:
 |              Returns an object with methods to interact with r2 via commands

**Comment by benquike** [comment]
I updated the r2 to the latest version in the repository, and found that the default base address became 0x08000040 

is there any specific reason that you choose to set the base address to some value even if the entry point address is not available in the binary?

**Comment by benquike** [comment]
I guess we can change the base address to 0 by using e bin.baddr=0 after starting r2 as a work around.

But the interface(`r2pipe.open`) should be redesigned to make it possible to specify any option to r2 when we use r2pipe to start it

**Comment by benquike** [comment]
No, I guess I was wrong.
I found that if the binary file is an object file (bit executable), there is some discrepancy between the values of symbols defined in the ELF file and the values we can get from r2.

There is the evidence:

Symbol values I got from readelf

    9: 00000000   333 FUNC    GLOBAL DEFAULT    1 mysort
    10: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND memcpy
    11: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __stack_chk_fail
    12: 0000014d    31 FUNC    GLOBAL DEFAULT    1 int_cmp
    13: 0000016c    35 FUNC    GLOBAL DEFAULT    1 float_cmp
    14: 0000018f   368 FUNC    GLOBAL DEFAULT    1 main

here is the value I got from r2:
vaddr=0x08000034 paddr=0x00000034 ord=009 fwd=NONE sz=333 bind=GLOBAL type=FUNC name=mysort
vaddr=0x08000181 paddr=0x00000181 ord=012 fwd=NONE sz=31 bind=GLOBAL type=FUNC name=int_cmp
vaddr=0x080001a0 paddr=0x000001a0 ord=013 fwd=NONE sz=35 bind=GLOBAL type=FUNC name=float_cmp
vaddr=0x080001c3 paddr=0x000001c3 ord=014 fwd=NONE sz=368 bind=GLOBAL type=FUNC name=main


My Question is, when the binary is an object file,  how is the value of  those symbols analysed in r2?

**Comment by radare** [comment]
The info is the same. Readelf doesnt provides vaddr because its an object file and only provides the paddr ones which are the same as r2.

Also aftwr yesterday commit from alvaro, the kernel modules and object files are loaded at that base by default just to avoid the problem of not being able to read the physical mapping when the vaddr overlaps.

You can override the baddr using -B on launch if you want a different address

**Comment by benquike** [comment]
@radare 

OK, I will confirm that.

But using r2pipe interface, we can not specify `-B` option, right? 
(I have checked the pydoc of r2pipe)

Are you planing to redesign the r2pipe interface?

**Comment by radare** [comment]
U can do this i already explained in a prev comment:

r2 = r2pipe.open(file,['-B' 0x8000])

**Comment by benquike** [comment]
@radare I have one more thing to confirm with you. 

 Even if I specify the base address using `-B`,  the starting address seems not correct. The evidence is as follows.

This is the command that I used to open an object file (using `-B 0`):

```
r2 -B 0 binaries-for-test/x86/c-func-test/indirect_call_test_1-gcc-m32-O3.o
```
However, from the commands below, we can see that the starting address is still `0x40`, not 0

```
[0x00000040]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x00000040]> is
[Symbols]
vaddr=0x00000040 paddr=0x00000040 ord=011 fwd=NONE sz=19 bind=GLOBAL type=FUNC name=int_cmp
vaddr=0x00000060 paddr=0x00000060 ord=012 fwd=NONE sz=24 bind=GLOBAL type=FUNC name=float_cmp
vaddr=0x00000080 paddr=0x00000080 ord=013 fwd=NONE sz=150 bind=GLOBAL type=FUNC name=mysort
vaddr=0x00000120 paddr=0x00000120 ord=015 fwd=NONE sz=337 bind=GLOBAL type=FUNC name=main
vaddr=0x00000000 paddr=0x00000000 ord=014 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.memcpy
vaddr=0x00000000 paddr=0x00000000 ord=016 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.__printf_chk
vaddr=0x00000000 paddr=0x00000000 ord=017 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.putchar
vaddr=0x00000000 paddr=0x00000000 ord=018 fwd=NONE sz=16 bind=GLOBAL type=NOTYPE name=imp.__stack_chk_fail
```
