### ISSUE TITLE
Implement `pdc` diffing in radiff2

### ISSUE THREAD

**Issue by radare** [radare/radare2#4528]
Similar to diaphora does:
![](http://www.alex-ionescu.com/wp-content/uploads/diaphora1.png)

We should have colorful disassembly and pseudo-decompilation diffing in radiff2 and r2 shell

**Comment by radare** [comment]
@jroimartin ? :D

**Comment by jroimartin** [comment]
I'll give it a look :)

**Comment by radare** [comment]
Should be relatively easy to implement now that we have -u and -U

**Comment by Maijin** [comment]
:O
