### ISSUE TITLE
issues with "agj" command

### ISSUE THREAD

**Issue by benquike** [radare/radare2#4541]
I am using r2pipe to get the basic blocks of a function. The command I am using is `agj`.
But I found that there is no fields indicating the relationship(`from` or `to`) with other blocks.
The following 4 fields are contained in each basic block, and none of them can be used.
[u'jump', u'ops', u'size', u'offset']

It could have been contained somewhere else, if it is could you please tell me where it is.

If it is not contained in the output, is it possible to add that in the output?

Thanks

**Comment by radare** [comment]
this information is there.  `jump` and `fail` are the info you are looking for

**Comment by benquike** [comment]
Thanks
