### ISSUE TITLE
argument number analysis result error

### ISSUE THREAD

**Issue by benquike** [radare/radare2#4542]
I have a C function implemented as follows:

```
int wrapper_1_args(int (*fc)(int), int a) {
  int ret = fc(a);
  return ret;
}
```

This the generated assembly code.
|  0x8000047                        |
| (fcn) sym.wrapper_1_args 28       |
| ; arg int arg_8h       @ ebp+0x8  |
| ; var int local_ch     @ ebp-0xc  |
| push ebp                          |
| mov ebp, esp                      |
| sub esp, 0x18                     |
| sub esp, 0xc                      |
| push dword [ebp + 0xc]            |
| mov eax, dword [ebp+arg_8h]       |
| call eax                          |
| add esp, 0x10                     |
| mov dword [ebp - local_ch], eax   |
| mov eax, dword [ebp - local_ch]   |
| leave                             |
| ret                               |

When I use "agj" command to get the analysed data of the function, it shows that the number of arguments is 1 

[{"name":"sym.wrapper_1_args","offset":134217799,"ninstr":12,**"nargs":1**,"locals":1,"size":28,"stack":48,"type":4,"blocks":
..........
[{"offset":134217799,"size":28,"ops":mily":"cpu","type":"ret","type_num":5,"type2_num":0}]}]}]

**Comment by radare** [comment]
Maybe @oddcoder want to look at this issue because its related to his gsoc task.

**Comment by oddcoder** [comment]
could you add the binary being used ?

**Comment by benquike** [comment]
It contains indirect function call. 

the source file and compiled object file are both included in the tarball which you can download from here

http://expirebox.com/download/d74479014cbbbd1622340e1994237f53.html

**Comment by benquike** [comment]
@oddcoder 

We are also doing research in function arity analysis, and we have some implementation.

**Comment by oddcoder** [comment]
ready to collaborate.. 
this is part of my GSOC  task... and I didn't start yet

**Comment by benquike** [comment]
@oddcoder how to collaborate with you?

**Comment by oddcoder** [comment]
@benquike  I dont know but maybe testing writing test cases  in r2r will be good start and

**Comment by Maijin** [comment]
yes please, add some test that would be useful 👍

**Comment by benquike** [comment]
OK, I will have a look

**Comment by benquike** [comment]
@radare @Maijin I have a question.

Does Radare2 support binary rewriting?
E.g: can we insert some instruction in a function?

**Comment by crowell** [comment]
yes, you have to open it with -w in order to modify the file.
then you can modify the file (see w? or VA for patching)

On Wed, Apr 13, 2016 at 6:48 PM, Hui Peng <notifications@github.com> wrote:

> @radare <https://github.com/radare> @Maijin <https://github.com/Maijin> I
> have a question.
>
> Does Radare2 support binary rewriting?
> E.g: can we insert some instruction in a function?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4542#issuecomment-209680174>
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by oddcoder** [comment]
yup r2 is designed to be hex editor in the first place
check the `w` command and its subcommands
`| w [str]              Multiple write operations`

**Comment by benquike** [comment]
@oddcoder @crowell 
yeah, using -w, we can overwrite code, but can we insert some code at some address so that the existing code there will be moved backward automatically?

**Comment by radare** [comment]
No. Code relocation is not as easy as displacing it few bytes below. You can resize the binary with r and insert with w. But u will have to fully analyze the program and shift all pointers to further sections, taking care of  computed pointers . Change section headers to reallocate all sections with rabin2 -O S/r, and then maybe it will work what you want to do....

**Comment by benquike** [comment]
@radare I got it. thanks!

**Comment by oddcoder** [comment]
@benquike can you please reupload the file again it just expierd :\
and btw r2 now have afCa that can be used to analyse function arguments please check or upload the file once more so I can recheck

**Comment by radare** [comment]
Upload the bins as images in gh instead of using crappy upload services

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
PING

**Comment by Maijin** [comment]
@benquike ????

**Comment by radare** [comment]
ping

**Comment by Maijin** [comment]
Already pinged 4 times, closing @radare  ?

**Comment by radare** [comment]
ETOOMANYPINGS
