### ISSUE TITLE
Script to draft new release notes

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4592]
- [x] extract commits message
 - [x] stats how many lines we added/removed
 - [x] stats about new contributors
 - [ ] comparison with previous releases
 - [x] search commit messages with 'category' keywords and split those into corrensponding subsections
 - [x] generate list of bugs (strip lines like 'Fix #...') and coverities, with links to them
 - [x] output markdown

may be even generating some nifty graphics?

add what you think would be helpful

**Comment by radare** [comment]
Make chlog is related

**Comment by radare** [comment]
work in progress in `sys/release-notes.js`

**Comment by XVilka** [comment]
And second script to publish it automatically
 - [ ] in github releases
 - [ ] in radare.today blog
 - [ ] change radare.org links
 - [ ] pin message in the telegram channel
 - [ ] update IRC topic
 - [ ] did I forgot something?

**Comment by Maijin** [comment]
see https://github.com/vaab/gitchangelog

**Comment by radare** [comment]
After my last commits this script is almost complete. Let's move the issue for the next release so we can improve it over time and keep track of this. More ideas are welcome.

**Comment by XVilka** [comment]
Would be nice to also check in this script status of:
  - [ ] Travis CI builds
  - [ ] Appveyor builds
  - [ ] Jenkins builds (mostly Android + mingw32 + supplimentary utils)
  - [ ] Job checking the correctness of r2pm buids

**Comment by XVilka** [comment]
- [ ] Script to parse Travis CI log and extract count + names of tests broken and fixed, and adding the output (expected and actual output) formatted as markdown.

**Comment by radare** [comment]
see sys/xx.sh

**Comment by XVilka** [comment]
Yep, it could be improved, to parse the fetched log.

**Comment by radare** [comment]
All yours

**Comment by radare** [comment]
any update on this? @XVilka

**Comment by radare** [comment]
imho current script is quite good. im closing this issue for now, just send pr if you think we need anything else
