### ISSUE TITLE
Decryption option in rahash2

### ISSUE THREAD

**Issue by P4N74** [radare/radare2#4595]
Currently there is only encryption support available for algorithms like `aes`, `blowfish` and others for which the decryption algorithm is available in the source code but it is not accessible from `rahash2` tool. So for algorithm where `enc(enc(text)) != text`, there is no support to decrypt it. So for implementing that, what options should be used in `rahash2` since `-d` and `-D` are preoccupied.

**Comment by Maijin** [comment]
It would definitely make sense to use -D because the command that is supposed to decrypt within r2 is woD. Merging -d with -E and then use -D for all algo not just base64 sounds the way to go, what do you think @radare ?

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
The b64 encode/decode commands in r2 should be in sync with those flags too

**Comment by P4N74** [comment]
I am working on it.

**Comment by P4N74** [comment]
I am working on it.

**Comment by radare** [comment]
Why close it?

**Comment by Maijin** [comment]
It is duplicate with #4254 kind of it's ok, if it's not done I'll add those detail there ;)
