### ISSUE TITLE
Add hotkeys to jump to data/code pointers

### ISSUE THREAD

**Issue by radare** [radare/radare2#4603]
`Cd 4`

<img width="1084" alt="screen shot 2016-04-10 at 23 08 10" src="https://cloud.githubusercontent.com/assets/917142/14413106/326fafd8-ff71-11e5-9e9e-26c23a1094e7.png">

**Comment by Maijin** [comment]
This should be added in VX ping @xarkes

**Comment by Maijin** [comment]
dup with https://github.com/radare/radare2/issues/4140

**Comment by Maijin** [comment]
This already work see ASCIINEMA here ->https://asciinema.org/a/57pgha3u9q0zbcd2vchbzglwh ! 

Only remain https://github.com/radare/radare2/issues/6653

**Comment by Maijin** [comment]
After @xarkes fix 👍
