### ISSUE TITLE
Incorrect encryption output of RC2 algorithm in rahash2

### ISSUE THREAD

**Issue by P4N74** [radare/radare2#4611]
Doing command: `rahash2 -S key -E rc2 -s "helloworld123456" | rax2 -S` gives output as:
`9515284e2b99f0ba1e1ab3f3fe64ee28`.

This does not match with any of the output in the respective modes:

| Mode      | Output                                                 |
|------------|------------------------------------------------|
| CBC       |  3f916eaf34a4ddc66c8a6167539d9966  |
| CFB       | 7b4df761c0579a55cba0657c7fd5b2ef     |
| CTR       | 7b3e8c95b7cd216caa6d3b4209be3345  |
| ECB       | a9c85c7650456d8f5f369704ad1e339f    |
| NCFB     | 7b3e8c95b7cd216c186b8bcb79f4768a   |
| OFB       | 7b4f88a50417a30758b021f460d63a7c   |
| NOFB     | 7b3e8c95b7cd216c175f1c163e7cfacc    |

Since no mode is specified in the code and no answer match with any of the above, there is a high chance that the rc2 algorithm is not correct.

**Comment by P4N74** [comment]
I am working on it.

**Comment by Maijin** [comment]
Fixed
