### ISSUE TITLE
can't seek to localflags

### ISSUE THREAD

**Issue by crowell** [radare/radare2#4615]
```
[0x00404890]> f.lol @ main+10
[0x00404890]> s main.lol
[0x00000000]> f. @ main
0x004028ca lol   [main + 10]
[0x00000000]> 
```

**Comment by balzarot** [comment]
Thanks Crowell. This works, but I noticed a strange alternating behavior.
Here is an example:

[0x004028cc]> s main
[0x004028c0]> f.foo @ 0x004028c4
[0x004028c0]> f.
0x004028c4 foo   [main + 4]
[0x004028c0]> s main+.foo
[0x004028c4]> s main+.foo
[0x004028c0]> s main+.foo
[0x004028c4]>

**Comment by radare** [comment]
Can u add a test case and mark it as broken?

**Comment by balzarot** [comment]
I tried on /bin/ls but I get the same behavior on any binary.
You can reproduce it by simply running these commands:
> aaa
> f.foo @ main+4
> s main+.foo
> s main+.foo
> s main+.foo
Let me know if you want me to attach a hello_word elf but as I said you should be able to obtain the same effect on any binary. 
Sorry for the stupid question, but where/how do I mark it as broken?

**Comment by crowell** [comment]
see https://github.com/radare/radare2-regressions/blob/master/t.anal/avr/functions for an example for a broken test.

**Comment by crowell** [comment]
test added https://github.com/radare/radare2-regressions/commit/0f42092fdfc1391966c2d7c4cef411866e593d1f

**Comment by crowell** [comment]
```diff
diff --git a/libr/core/cmd_seek.c b/libr/core/cmd_seek.c
index 13fd1bf..2031d66 100644
--- a/libr/core/cmd_seek.c
+++ b/libr/core/cmd_seek.c
@@ -139,6 +139,13 @@ static int cmd_seek(void *data, const char *input) {
                } else eprintf ("|Usage| 'sr PC' seek to program counter register\n");
        }
        if (*input) {
+               char* ptr;
+               if ((ptr = strstr(input, "+.")) != NULL) {
+                       char* dup = strdup(input);
+                       dup[ptr - input] = '\x00';
+                       r_core_cmdf (core, "s %s", dup);
+                       free (dup);
+               }
                const char *inputnum = strchr (input, ' ');
                int sign = 1;
                {

```diff

ultra ghetto fix, I can do something a bit better after the weekend.

**Comment by radare** [comment]
Thats hurts to me. Better wait for the weekend and use api instrad of cmd

**Comment by crowell** [comment]
the pushed impl uses core->offset instead of cmd. i think there is probably a better way to do this still. revert if you want and we can discuss the "real" way to do it, or keep it and I'll do something after the weekend.

**Comment by radare** [comment]
Theres a place inside rnum that stores the current computed value

**Comment by radare** [comment]
Its warm and comfy
