### ISSUE TITLE
should afl show "realsize" instead of "size"?

### ISSUE THREAD

**Issue by crowell** [radare/radare2#4621]
https://gist.github.com/crowell/ab4c1856eeba9c32633e44fef1ea5b94

for example. size is listed as 8, but the function is much larger.

example binary is here https://gist.github.com/702f6228b4b45a5cd48dad65cd2fa447

**Comment by ret2libc** [comment]
I agree. I think there's no sense in having two different "sizes". A function has *one* size, not two :/

**Comment by radare** [comment]
I think we should consider function size (sum(bbs)) and function boundaries (lastbb-firstbb) we can keep using the fcn->size and add a function to update it by itersting over the bbs

**Comment by ret2libc** [comment]
Or just use a getter `r_fcn_get_size` every time you need the size of a function, without accessing directly the size field. This way we can easily change how fcn->size is calculated without affecting other code.

**Comment by radare** [comment]
this will slowdown the thing, caching the size seems useful to me
we must update that size everytime a basic block is modified or added/removed.. or just set it to -1 to only update it when requested and needed

**Comment by ret2libc** [comment]
I think we can use anyway `r_fcn_get_size` that just returns fcn->size even if it is calculated every time. The compiler should be able to optimize it, but at least we will have only one place to touch in case we need to update how the size is calculated, i think.

**Comment by crowell** [comment]
i agree with @ret2libc that a getter is more flexible.

**Comment by radare** [comment]
Fixed in dad8b434c47479becd3e3f901fe81e34c9f5dd7a

**Comment by radare** [comment]
Why do u reopen? Afl and afll are showing realsize already

**Comment by ret2libc** [comment]
It was also about writing a getter for the size of a function. You can look at #4904 .

**Comment by radare** [comment]
Then the title of the issue was wrong

**Comment by radare** [comment]
i think both are important. because sometimes the data is mixed witht he code and max-min will be != sum(bbs). this will make p8f fail for example, because it will not copy the bytes of the function itself.

**Comment by ret2libc** [comment]
This is true, but I would probably change names. Something like:
* `r_anal_fcn_size` for the size of the function, that is sum(bbs)
* `r_anal_fcn_firstaddr` for the minimum address in a function
* `r_anal_fcn_lastaddr` for the maximum address in a function
* `r_anal_fcn_addr` for the entry address of a function
* `r_anal_fcn_range` for max-min, that is `r_anal_fcn_lastaddr` - `r_anal_fcn_firstaddr`

What do you think?

**Comment by ret2libc** [comment]
@crowell getter added. "realsize" doesn't replace "size" though in `afl` :(

Both of them are displayed at the moment... and unfortunately a lot of code depends on this wrong size.
We can close this for the moment and refer to https://github.com/radare/radare2/issues/4868 for other things.
