### ISSUE TITLE
converting numeric immediates (and offsets) into structures offsets/global offsets

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4622]
To convert code like `mov eax, [edi + 0x18]` into something like `mov eax, [edi + SomeStruc.SomeField]`
Here are some problems that need to be solved
- [ ] command to specify such a "hint" for a particular address
- [ ] ability to choose between 2 different structures, where number represent same offset, but different fields
- [ ] ability to autorecognize those numbers if there is only one possible substitution

**Comment by XVilka** [comment]
@oddcoder @radare do you have any ideas how to implement this with less effort?

**Comment by oddcoder** [comment]
I found a work around to avoid using this (I don't remember what I did but
I never needed it) however it will be still good addition to have similar
feature

**Comment by XVilka** [comment]
What also is useful - to suggest structure sizes. For example it's common pattern
```c
memset (some_struc, 0, 0xef8);
```
Where 0xef8 is structure size. Adding a mechanism to guess if it's some structure size can be helpful for recognizing some types where it's not possible otherwise.

**Comment by XVilka** [comment]
This was partially done with `ta` command. @sivaramaaa you can check this one too.
