### ISSUE TITLE
loaded modules path not displayed correctly

### ISSUE THREAD

**Issue by dauphin327** [radare/radare2#4623]
Hi,

It seems like there's a bug with the commands "dm" and "dmm". After I attach the debugger to the process and type those commands I get those outputs, but they are cut off:

sys   4K 0xf5813000 - 0xf5814000 s -rw- /root/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libuuid.so.1.3.0 /root/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libuuid.so.1.3.0
sys 1020K 0xf5814000 - 0xf5913000 s -r-x /root/.local/share/Steam/steamapps/common/Counter-Strike /root/.local/share/Steam/steamapps/common/Counter-Strike
sys  20K 0xf5913000 - 0xf5918000 s -rw- /root/.local/share/Steam/steamapps/common/Counter-Strike /root/.local/share/Steam/steamapps/common/Counter-Strike

The full line should be ending with "Counter-Strike Global Offensive/client_client.so"

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
can you check the /proc/pid/maps if any of the rows exceeds 1024 chars?

**Comment by radare** [comment]
maybe are those filenames also chopped in the /proc?

**Comment by dauphin327** [comment]
Hi,
Sorry for the late reply, upgraded to the latest radare2 from git instead of the one from gentoo repo.

/proc/pid/maps example:
f063f000-f1397000 r-xp 00000000 fd:00 27790159                           /root/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so
f1397000-f13ca000 rw-p 00d57000 fd:00 27790159                           /root/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/bin/engine_client.so

radare2 dm/dmm:
sys   4K 0xf7725000 - 0xf7726000 s -r-- /root/.local/share/Steam/steamapps/common/Counter-Strike /root/.local/share/Steam/steamapps/common/Counter-Strike
sys   4K 0xf7726000 - 0xf7727000 s -rw- /root/.local/share/Steam/steamapps/common/Counter-Strike /root/.local/share/Steam/steamapps/common/Counter-Strike
sys  96K 0xf7727000 - 0xf773f000 s -rw- unk69 unk69
sys 204K 0xf773f000 - 0xf7772000 s -r-x /root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so /root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
sys   4K 0xf7772000 - 0xf7773000 s -r-- /root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so /root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so
sys   4K 0xf7773000 - 0xf7774000 s -rw- /root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so /root/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so


Still having issues with spaces in path.

Thanks.

**Comment by dauphin327** [comment]
hidden ~ # r2 -v
radare2 0.10.2 10963 @ linux-little-x86-64 git.0.10.2-20-gcdfddf9
commit: cdfddf921ca14104e5699776c05b3eb9538a1b57 build: 2016-04-13

**Comment by radare** [comment]
Which issues?

**Comment by dauphin327** [comment]
"steamapps/common/Counter-Strike" still doesn't show full module path

**Comment by crowell** [comment]
yes, this si due to the handling of the /proc/pid/maps in debug_native.c

I'll write up a simple test and a fix for this tonight.
