### ISSUE TITLE
installation question!

### ISSUE THREAD

**Issue by hdarwin** [radare/radare2#4624]
```
root@ubuntu:~/source/radare2# sys/install.sh
```
I installed radare2 using above command but rootless user can't use radare2
```
hdarwin@ubuntu:~$ r2 --version
The program 'r2' is currently not installed. You can install it by typing:
sudo apt-get install radare2
```
Is there a script to install at /bin or /usr/bin?

**Comment by Maijin** [comment]
what about `./sys/user.sh` ?

**Comment by XVilka** [comment]
'.configure ; make ; sudo make install' should work too

**Comment by radare** [comment]
you can even use r2 without installing it:

* build statically and copy the binary where you want

or

* build and use env.sh to setup PATH and LD_LIBRARY_PATH

**Comment by hdarwin** [comment]
@XVilka thank you! it works

**Comment by Maijin** [comment]
@hdarwin have you tried sys/user.sh

**Comment by hdarwin** [comment]
@Maijin nope that script is not fit my intention.
```
If you want to install radare2 in the home directory without using root privileges and sudo, simply run
$ sys/user.sh
```
