### ISSUE TITLE
AG command returning only the first function on linux

### ISSUE THREAD

**Issue by davidt99** [radare/radare2#4627]
I'm analyzing a file with the command "aa;aac;aac".
After that, I need to get the function graph, so I'm running the "ag" command.
I'm getting only the first function, the other functions are omitted.
I'm having this issue only on linux - when radare2 is deployed on windows, I'm able to get the full graph.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by davidt99** [comment]
Hi,
I'm using the radare2 from git, clone it today few times.

**Comment by radare** [comment]
Only returns the function where you are. Theres a subcommand to show them all

**Comment by davidt99** [comment]
I figured it must be that, but I looked for it in book, in the cheat sheet and in the command ag? and could't find any reference (beside moving with seek command each function).
What was bothering me is that in windows it worked just fine.
Would you mind to post the subcommand?

**Comment by radare** [comment]
This behaviour changed 1 year ago. I guess documentation was not updated. Thats the problem of reading documentation :pp

**Comment by davidt99** [comment]
What is subcommand?

**Comment by davidt99** [comment]
?

**Comment by radare** [comment]
Oh i think this functionality got lost after @ret2libc refactoring. Should be easy to add just need some discussion because ag subcommands look quite crappy right now

**Comment by Maijin** [comment]
See META - Graph
