### ISSUE TITLE
m68k.cs branches on >0x7fffffff are wrongly computed

### ISSUE THREAD

**Issue by radare** [radare/radare2#4631]
```
        ┌─< 0x800114ee      6706           beq.b 0x800114f6            ;[1]
> ao
jump: 0xffffffff800113f6
fail: 0x800114f0
```

works fine with asm.arch=m68k

**Comment by radare** [comment]
probably a bug in capstone. it has been workarounded in adc9922c6aceacc0cffa89bc45a20250a5e43e1f

**Comment by radare** [comment]
Moved to 0.10.4 because its been workarounded for now

**Comment by radare** [comment]
maybe @poliva can do some tests here

**Comment by radare** [comment]
ping @poliva

**Comment by radare** [comment]
@Svenito can you have a look at this?

**Comment by Svenito** [comment]
:+1:

**Comment by Svenito** [comment]
```
$ r2 -v
radare2 0.99.9-git 12824 @ linux-x86-64 git.0.10.6-317-g90fcf76
commit: 90fcf7662359acaa6dfdf64d6dac46b350f874ce build: 2016-11-03

$ r2 -a m68k -m 0x80000000 -
[0x80000000]> wx 6707
[0x80000000]> pi 1
beq.b 0x80000009
[0x80000000]> ao
Oops at 0x80000000 (67 07 00 ...)
```

This is what I am getting when trying to test this issue

**Comment by radare** [comment]
this ao bug has been fixed here 3d1141ff7edcecaa5d6f864732848bcfaaad3441

not sure if its introducing another regression...

**Comment by Svenito** [comment]
Looks like some different issues now:

```
jump: 0x00000000
fail: 0x00000000
```

**Comment by radare** [comment]
ping @Svenito

**Comment by Svenito** [comment]
`ao` works fine if  you run`rpm -i m68k` before hand. `pi 1` will work fine without the installed plugin.
