### ISSUE TITLE
Do not call rabin2 in 'izz' commands

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4638]
For example we do zip:// or ihex:// protocol to open the file using r2:
```
r2 -a arm ihex://file
[0x0000000] izz
```
`izz` here calls rabin2 in libr/bin/bin.c, and use the name of the descriptor, but since rabin2 can't open such io protocols, it returns wrong result.

**Comment by XVilka** [comment]
see example here: http://xvilka.me/r2izz.log

**Comment by XVilka** [comment]
Sorry, invalid one

**Comment by XVilka** [comment]
It was because "core->bin->minstrlen" is 0 and "core->bin->maxstrlen" is 4, which is obviously wrong

**Comment by XVilka** [comment]
should be different by default

**Comment by radare** [comment]
Who sets that?
