### ISSUE TITLE
Infinite looping of r_debug_reg_sync function.

### ISSUE THREAD

**Issue by P4N74** [radare/radare2#4655]
the following commands gives: `r_debug_reg: error reading registers.`
```
r2 -d /tmp/level08

db sym.main
dc
V
```

now going to debugger panel in visual mode, and stepping over the function `<F8>` until `call  sym.imp._exit` is executed, this results in infinite loop outputting `r_debug_reg: error reading registers.`
[File](https://drive.google.com/open?id=0B2QD_FoGXK08LUdXRUI1TjNfRHM)

**Comment by radare** [comment]
can you attach a debugger to r2 and see where's looping and paste the backtrace? a simpler reproducer would be nice
