### ISSUE TITLE
r2 0.10.2 on fresh install of ubuntu mate on raspberry pi 3

### ISSUE THREAD

**Issue by diouziou** [radare/radare2#4659]
Hi

the problem encountered here: [issue 4612](https://github.com/radare/radare2/issues/4612) is the same on ubuntu mate (SIGILL when trying to insert a breakpoint then run `dc` in `r2 -d` of simple hello world program).
This time, gdb completely fails (it segfaults)...

Note that there is one more problem: the disassembly is wrong because the system is identified as a 16 bits system (command `i` gives: `bits 16`  although it identifies `class ELF32`) (and the same occurs in gdb)

all the best

**Comment by crowell** [comment]
the 16 bits is probably due to arm vs thumb.

**Comment by diouziou** [comment]
i close this issue, as i did for issue 4612
