### ISSUE TITLE
Add write+seek commands

### ISSUE THREAD

**Issue by radare** [radare/radare2#4665]
This is useful to create scripts from dumpers like this:

```
wx 102029384849458484
s+16
wx 188238923893289312
s+16
..
```

maybe with `wxs` ?

**Comment by ret2libc** [comment]
I think it's not useful to create "yet another command" that it's not necessary for the user. A script can easily do `wx` followed by `s+` without any problem, IMO.

**Comment by monosource** [comment]
`(foo val sz, wx $0, s+$1)`
`.(foo 102029384849458484 16)`
Works perfectly fine. I think macros are well suited for these kinds of tasks; no need for "combined" commands; better to keep it simple by having write primitives and seek primitives separate.

**Comment by Maijin** [comment]
Related to #5089 ?

**Comment by radare** [comment]
Having to specify the length of what you are wrtiting seems silly to me. Maybe we should just reuse the return value of the write commands. So it can be macrofied or scripted easily without adding new commands

**Comment by radare** [comment]
Nope that issue is toyally unrelated

**Comment by Maijin** [comment]
well a P* command could just drop a wxs + usual project dump and that's it u got ur "Copy binary inside projects to make them self-distributable" no?

**Comment by radare** [comment]
wat. nope, that would be slow, we just need to copy the binary inside the project, not replicate the 200MB executable into text commands
