### ISSUE TITLE
Swift binary

### ISSUE THREAD

**Issue by l4l** [radare/radare2#4666]
Swift binary from RuCTF'16 was spam at r2 launching(even without -A/-AA flags)
Messages are like: 
```
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_Tv4main8specialsGSaGSaSb__''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TMaGVs18EnumeratedSequenceGSaSb__''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TWlGSaGSaSb__urGSax_s8Sequences''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TMLGSPVs4Int8_''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TMLGVs18EnumeratedIteratorGVs16IndexingIteratorGSaSb___''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TMLGVs16IndexingIteratorGSaGSaSb___''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TMaGVs16IndexingIteratorVSS13CharacterView_''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TMLGSaTSfSfSf__''
r_sys_cmd_str_full: failed command 'xcrun swift-demangle -compact -simplified '_TFSag9subscriptFSix''
```
Binary is [here](https://github.com/radare/radare2/files/226002/DiscoBall.txt)

**Comment by XVilka** [comment]
have you had xcrun installed?

**Comment by l4l** [comment]
No, so that's the problem?
Anyway that's quite wierd to get a flood like that

**Comment by XVilka** [comment]
Swift demangling using external swift utility, so it requires it to be installed.

**Comment by XVilka** [comment]
You can disable demangling using "bin.demangle=false" and "asm.demangle=false"

**Comment by l4l** [comment]
That's work fine, thanks

**Comment by radare** [comment]
that error should only appear if you have xcrun installed but you dont
have the swift demangler. are you using a very old version of OSX maybe?

**Comment by radare** [comment]
dont close this until its properly fixed

**Comment by radare** [comment]
ideally we should demangle swift without an external program.

can we put this bin in r2r?

**Comment by l4l** [comment]
I do not use OS X at all. I tried to analyze it from linux and can't able to launch it(some wierd stuff with icu lib)
At the contest it was launched at fedora with loading some dynamic libraries with LD_LIBRARY_PATH

**Comment by radare** [comment]
do you have any “xcrun” in your PATH? this is not suposed to be in linux

**Comment by l4l** [comment]
As I said no
I download image of workstation and will check there

**Comment by l4l** [comment]
Nope, the contest system also have no `xcrun`. I guess `libFoundation.so libswiftCore.so  libswiftGlibc.so  libswiftSwiftOnoneSupport.so` instead of it

**Comment by radare** [comment]
Meanwhile use `-e bin.demangle=false`
