### ISSUE TITLE
Problem with winedbg debugging in linux

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#4667]
Try to debug windows binary with winedbg but have got a errors:

Create "gdb-socket":
```
~/CTF $ winedbg --gdb --no-start crackme0x02.exe 
0023:0024: create process 'Z:\home\dukebarman\CTF\crackme0x02.exe'/0x110780 @0x401260 (11776<537>)
0023:0024: create thread I @0x401260
target remote localhost:48403
```

Try to debug:
```
radare2 $ r2 -a x86 gdb://localhost:48403
read_packet: read failed
read_packet: read failed
attach 7 7
Assuming filepath gdb://localhost:48403
attach -1860284624 -1860284624
r_debug_reg: error reading registers
r_debug_reg: error reading registers
 -- Find wide-char strings with the '/w <string>' command
r_debug_reg: error reading registers
[0x00000000]> dr=
r_debug_reg: error reading registers
r_debug_reg: error reading registers
```

I think problem in negative id of process: `attach -1860284624 -1860284624`

r2 from git:
```
$ r2 -v
radare2 0.10.2 10993 @ linux-little-x86-64 git.0.10.2-49-g7c3c865
commit: 7c3c865ef806efd5ad73ecdb9f331a884827059d build: 2016-04-19
```

**Comment by radare** [comment]
use -b32 too. i guess you are on a 64bit linux debugging a 32bit windows executable
…

**Comment by dukebarman** [comment]
I tried add `-b32` and `-b 32`:
```
r2 -a x86 -b 32 gdb://localhost:55193
```
But see same errors

**Comment by radare** [comment]
Without the -d you will not get the debugger to work

**Comment by dukebarman** [comment]
oops, sry. It works.

**Comment by dukebarman** [comment]
New error:
![2016-04-20_01-39-09](https://cloud.githubusercontent.com/assets/1186777/14657967/7002e6d8-0699-11e6-81ba-98a2ab731a33.png)

When I pass function (this function wait a input) with key `F8` in debugger r2 sent errors and didn't respond (only command "kill process" helped.

**Comment by dukebarman** [comment]
When I killed r2 process and clicked by mouse in this terminal, saw a strange symbols in console:
![image](https://cloud.githubusercontent.com/assets/1186777/14672219/2335bce8-06ff-11e6-8b99-22a6efed76ed.png)

**Comment by radare** [comment]
isnt this fixed already? can you try again?

**Comment by dukebarman** [comment]
Nope :(

**Comment by XVilka** [comment]
Closing in favor of https://github.com/radare/radare2/issues/955
@rlaemmert since you're back - can you please check this one?
