### ISSUE TITLE
Loading symbols/debugging information via gdb://protocol

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#4668]
Need feature: When I debug windows binary with winedbg/gdb I don't see list of functions and strings after `aaa` command:

```
[0x7b45f70c] iz

[0x7b45f70c] afl
0x7b45f700 14 1 fcn.7b45f700
0x7b460730 24 1 eip
```

**Comment by radare** [comment]
analysis doesnt finds strings unless you enable anal.strings=true and use aae.

also, the list of fucnctions is correct because the binary header is not parsed at all unless you specify the file you are using from disk, because in memory it cant be parsed correctly most of the times

**Comment by XVilka** [comment]
I suggested to load the symbols using rabin2 in current session, but I think it need to be solved somehow to be done automatically
