### ISSUE TITLE
Radare detects Resources of the PE as Code

### ISSUE THREAD

**Issue by AriEi4** [radare/radare2#4674]
Hi, 
In some files, r2 detect the resources of the PE file as code and try to disassemble it.

Here is an example - CardGames.dll (Windows dll)
Here's a link to this dll from Windows7x86 Machine: http://www.filedropper.com/cardgames
IDA detects the file as PE without code (and without functions), but r2 detects 3343 functions after 'aa;aac',

If you check the file in ResourceHacker/PExplore or any other tool - you will see all the resources, without code or import\export functions at all.

Any ideas?

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by AriEi4** [comment]
I'm using the git version

**Comment by Maijin** [comment]
This is related to havecode

**Comment by Maijin** [comment]
@AriEi4 use `px` for showing hexadecimal

**Comment by Maijin** [comment]
if there is no code why did you run aa and aac????

**Comment by Maijin** [comment]
also, in the current case, ida is really bad didn't even tell you what entry point is found in the binary just throwing you FFFFFFF awful...

**Comment by AriEi4** [comment]
At that point i didn't know if there is a code or not.. I thought that if there is no code in the file - I would get 0 functions

**Comment by AriEi4** [comment]
@Maijin What do you mean this is related to havecode?

**Comment by radare** [comment]
havecode is a bit in the bininfo struct that shows if the file opeend contains code or not. this is not going to help too much in here because the current support for iscode/data is not pretty complete and will get better around 0.10.3 and 0.10.4 releases.

we should probably avoid disassembling sections that have no executable bit.

**Comment by alvarofe** [comment]
I am gonna look at this but the havecode just check if it has some section with `x` bit enable or some entry point and print havecode true or false. I don't see that the issue comes for this

```
mac:r2 alvaro_fe$ git grep havecode
libr/core/bin.c:        bool havecode;
libr/core/bin.c:        havecode = is_executable (obj) | (obj->entries != NULL);
libr/core/bin.c:                pair_bool ("havecode", havecode, mode, false);
```

**Comment by alvarofe** [comment]
@AriEi4 may you share the dll again? just paste here with .png extension. Thx

**Comment by AriEi4** [comment]
@alvarofe here is a new link:
http://www.filedropper.com/cardgames

**Comment by Maijin** [comment]
What now ?

**Comment by radare** [comment]
related to the fat-pe task imho

**Comment by Maijin** [comment]
Please share the bin and next time put it in a zip that you drag and drop on github to avoid shitty online service.
