### ISSUE TITLE
Wrong name in "XREF" ?

### ISSUE THREAD

**Issue by balzarot** [radare/radare2#4675]
The name between parenthesis that follows a "XREF" address is now the name of the current function. Shouldn't be instead the name where the address is located?

Example. I have **main** that calls **bar**.
Here is what I see in r2:

    [0x004004ed]> pdf @ sym.bar
    / (fcn) sym.bar 23
    |           ; var int local_4h @ rbp-0x4
    |           ; CALL XREF from 0x00400527 (sym.bar)
    |           0x004004fc      55             push rbp
    |           0x004004fd      4889e5         mov rbp, rsp
    |           0x00400500      4883ec08       sub rsp, 8
    |           0x00400504      897dfc         mov dword [rbp - local_4h], edi
    |           0x00400507      8b45fc         mov eax, dword [rbp - local_4h]
    |           0x0040050a      89c7           mov edi, eax
    |           0x0040050c      e8dcffffff     call sym.foo
    |           0x00400511      c9             leave
    \           0x00400512      c3             ret

    [0x004004ed]> pdf @ 0x00400527
                ;-- main:
    / (fcn) sym.main 27
    |           ; var int local_4h @ rbp-0x4
    |           ; var int local_10h @ rbp-0x10
    |           ; DATA XREF from 0x0040041d (sym.main)
    |           0x00400513      55             push rbp
    |           0x00400514      4889e5         mov rbp, rsp
    |           0x00400517      4883ec10       sub rsp, 0x10
    |           0x0040051b      897dfc         mov dword [rbp - local_4h], edi
    |           0x0040051e      488975f0       mov qword [rbp - local_10h], rsi
    |           0x00400522      8b45fc         mov eax, dword [rbp - local_4h]
    |           0x00400525      89c7           mov edi, eax
    |           0x00400527      e8d0ffffff     call sym.bar
    |           0x0040052c      c9             leave
    \           0x0040052d      c3             ret

As you can see in the header of **bar**, radare says: 
 
     ; CALL XREF from 0x00400527 (sym.bar)

I think it should be instead:
 
     ; CALL XREF from 0x00400527 (sym.main)

Same thing applies to the DATA XREF in main.

**Comment by radare** [comment]
Yep thats a typo. Can you send a pr fixing this?

**Comment by balzarot** [comment]
Yeah sure, I'll do it right after I am done with the other pr. 
One little question though. I have another little bug fix for a different command. Is it ok to send a single pr for the two (unrelated) fixes, or you guys prefer to keep them separate?

**Comment by radare** [comment]
Its ok :)

**Comment by radare** [comment]
tired of waiting :P its fixed in master now

**Comment by radare** [comment]
can you please add a test?
