### ISSUE TITLE
sigsegv in elf parser (store_versioninfo_gnu_verneed)

### ISSUE THREAD

**Issue by n0way0ut** [radare/radare2#4686]
I am just fuzzing r2 with AFL and found this:

Starting program: /usr/bin/r2 crash_bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
|Usage: di Debugger target information
| di   Show debugger target information
| dij  Same as above, but in JSON format

Program received signal SIGSEGV, Segmentation fault.
[----------------------------------registers-----------------------------------]
RAX: 0x55555588a9c0 --> 0x0 
RBX: 0xffffffff80000020 
RCX: 0x0 
RDX: 0x55555588d740 --> 0x0 
RSI: 0xffffffff 
RDI: 0x55555588a9e8 --> 0x0 
RBP: 0x555555887870 --> 0x0 
RSP: 0x7fffffffd3d0 --> 0x7fffffffd4c0 --> 0x0 
RIP: 0x7ffff6c75958 (<elf_init+13160>:	movzx  edx,WORD PTR [r14])
R8 : 0x55555588d700 --> 0x0 
R9 : 0x7ffff31e5cc8 --> 0x7ffff31e5cb8 --> 0x7ffff31e5ca8 --> 0x7ffff31e5c98 --> 0x7ffff31e5c88 --> 0x7ffff31e5c78 --> 0x55555588a600 --> 0x0 
R10: 0x7ffff31e5c58 --> 0x55555588d770 --> 0x0 
R11: 0x55555588d6f0 --> 0x0 
R12: 0x55555588a9c0 --> 0x0 
R13: 0x0 
R14: 0x5554d58842f0 
R15: 0x5555558587c0 --> 0x10102464c457f
EFLAGS: 0x10206 (carry PARITY adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff6c75947 <elf_init+13143>:	mov    rcx,QWORD PTR [rsp+0x8]
   0x7ffff6c7594c <elf_init+13148>:	mov    rdx,QWORD PTR [rsp]
   0x7ffff6c75950 <elf_init+13152>:	lea    rsp,[rsp+0x98]
=> 0x7ffff6c75958 <elf_init+13160>:	movzx  edx,WORD PTR [r14]
   0x7ffff6c7595c <elf_init+13164>:	lea    rsi,[rip+0x18a311]        # 0x7ffff6dffc74
   0x7ffff6c75963 <elf_init+13171>:	xor    ecx,ecx
   0x7ffff6c75965 <elf_init+13173>:	mov    rdi,rax
   0x7ffff6c75968 <elf_init+13176>:	call   0x7ffff6b8f260 <sdb_num_set@plt>
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffd3d0 --> 0x7fffffffd4c0 --> 0x0 
0008| 0x7fffffffd3d8 --> 0x55555588a9c0 --> 0x0 
0016| 0x7fffffffd3e0 --> 0x555555884330 --> 0x0 
0024| 0x7fffffffd3e8 --> 0x5555558842d0 --> 0x100010001 
0032| 0x7fffffffd3f0 --> 0x8 
0040| 0x7fffffffd3f8 --> 0x5555558740c0 --> 0x6ffffffe0000006b 
0048| 0x7fffffffd400 --> 0x55555587b250 --> 0x0 
0056| 0x7fffffffd408 --> 0x555555878430 --> 0x0 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
store_versioninfo_gnu_verneed (sz=<optimized out>, shdr=0x5555558740c0, bin=0x5555558587c0)
    at /home//tools/reversing/radare2/libr/..//libr/bin/p/../format/elf/elf.c:673
673			sdb_num_set (sdb_version, "vn_version", entry->vn_version, 0);

I attached the binary that crashes r2 with .jpg extension :)

![crash_bin](https://cloud.githubusercontent.com/assets/5345101/14755547/6921737e-08e3-11e6-998c-a8ddd566ab1c.jpg)

**Comment by radare** [comment]
thanks! i’ll add a test case now :)
