### ISSUE TITLE
load_omf_lnames problem

### ISSUE THREAD

**Issue by q6r** [radare/radare2#4689]
https://github.com/radare/radare2/blob/master/libr/bin/format/omf/omf.c#L117

```
		if (!(names[ct_name] = R_NEWS0 (char, buf[3 + tmp_size] + 1))) {
			free_lname (ret);
			return false;
		}
```

char overflow when `buf[3+tmp_size]` is `0xff` .. so `0xff+1 == 0` it calloc's `0`, so this `if` is passed.. then comes

https://github.com/radare/radare2/blob/master/libr/bin/format/omf/omf.c#L122

```
		memcpy (names[ct_name], buf + 3 + tmp_size + 1,
			buf[3 + tmp_size]);
```
which will copy `(size_t)0xff` bytes into the smaller names[ct_name], and 'segfault'

**Comment by radare** [comment]
Do you have a test case for the regressions suite? Do you plan to send the pullreq with the patch? Thanks!

**Comment by q6r** [comment]
This is an omf that triggers the bug
![lname_ov](https://cloud.githubusercontent.com/assets/1616882/14765532/77b63634-09d5-11e6-8855-c123d58a7901.gif)
