### ISSUE TITLE
r2 failed to analyze file, IDA succeeds (Can't find entry0)

### ISSUE THREAD

**Issue by AriEi4** [radare/radare2#4693]
Here is the sample:
http://www.filedropper.com/virusshare1a09395a845bd64bb23b185445614651
WARNING - Malware.

If you try to do 'aa' you get the error - Cannot find function 'entry0' at 0x004679ec
The address is the correct address - the EntryPoint of the file, but despite that r2 failed to analyze the file.
After that, each of the functions command returns empty results ('afl' for example)

IDA succeeds to analyze the file perfectly.

Thanks.

**Comment by Maijin** [comment]
Section is marked as non-executable. if it is passed executable it works. 
Does the section CODE really non-executable in this case IDA is doing magic by changing it.
Or does the section is executable in this case this is a bug.
This should be checked with PEFILE.

**Comment by Maijin** [comment]
So no, ida just analyse even if non-executable

**Comment by AriEi4** [comment]
Great, I didn't notice the non-executable flag. It make sense. Thanks!
