### ISSUE TITLE
Xrefs not loaded from sdbs in non-default locations

### ISSUE THREAD

**Issue by fabsx00** [radare/radare2#4697]
When saving a project file with `Ps $absolute_path` to a location outside of the default projects directory (`~/.config/radare/projects`), quiting radare, and then loading the project file using `Po $absolute_path`, it seems cross references are not loaded from the corresponding sdb file. `ax` then returns no cross references.

**Comment by radare** [comment]
Are you using r2 from git? This was fixed already two weeks ago

**Comment by fabsx00** [comment]
Yes, I'm using r2 from git.

**Comment by Maijin** [comment]
paste output of r2 -v

**Comment by fabsx00** [comment]
17:40:25-fabs~/git/radare2 (master)$ r2 -v
radare2 0.10.0-git 11041 @ linux-little-x86-64 git.0.10.2-94-g8cd8ac3
commit: 8cd8ac3b0ed6c7c630dd4f2c7b728e9343b2fdee build: 2016-04-24

17:40:27-fabs~/git/radare2 (master)$ r2 -A /bin/ls
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
 -- Initial frame selected; you cannot go up.
[0x004048c5]> Ps /tmp/foo
/tmp/foo
[0x004048c5]> q
Do you want to save the '/tmp/foo' project? (Y/n)
17:40:50-fabs~/git/radare2 (master)$ 
17:40:51-fabs~/git/radare2 (master)$ r2 /bin/ls
 -- Almost 5am, maybe you should go to bed.
[0x004048c5]> Po /tmp/foo
Close current session? (Y/n)
[0x004048c5]> ax
[0x004048c5]>

**Comment by radare** [comment]
This is 0.10.0... About half a year old

**Comment by fabsx00** [comment]
But the commit it references is from yesterday. Are you sure the version info is correct? I pulled today, right before building and it's the master branch.

**Comment by fabsx00** [comment]
I cloned again and rebuilt. The version is now displayed correctly, but the problem remains:
20:16:40-fabs~/git/radare2 (master)$ r2 -v
radare2 0.10.2 11036 @ linux-little-x86-64 git.0.10.2-94-g8cd8ac3
commit: 8cd8ac3b0ed6c7c630dd4f2c7b728e9343b2fdee build: 2016-04-24
20:16:42-fabs~/git/radare2 (master)$ rm /tmp/foo
20:16:52-fabs~/git/radare2 (master)$ r2 -A /bin/ls
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
 -- THE CAKE IS A PIE
[0x004048c5]> Ps /tmp/foo
/tmp/foo
[0x004048c5]> q
Do you want to save the '/tmp/foo' project? (Y/n)
20:17:02-fabs~/git/radare2 (master)$ 
20:17:02-fabs~/git/radare2 (master)$ r2 /bin/ls
 -- See you in shell
[0x004048c5]> Po /tmp/foo
Close current session? (Y/n)
[0x004048c5]> ax
[0x004048c5]>
