### ISSUE TITLE
r2 "Cannot find 'XXX'" before printing the function Dissasm

### ISSUE THREAD

**Issue by AriEi4** [radare/radare2#4698]
Hi, 
In some files, for some functions r2 prints 'Cannot find '1.-2147483648'' before printing the Disassembly of the function.

Sample - http://www.filedropper.com/showdownload.php/sample5exe

After 'aaa', if I try to execute 'pdf @ 0x4030b0' (0x4030b0 is one of the functions and r2 detects it) i get those prints:
![image](https://cloud.githubusercontent.com/assets/18167024/14768172/06d3ee5c-0a43-11e6-9c3f-c4ec5d2f90d6.png)

Thanks for the help!

**Comment by radare** [comment]
404

**Comment by AriEi4** [comment]
Try this:
http://www.filedropper.com/sample5exe

**Comment by radare** [comment]
fixed in 73b639e2af99f9d1a6a8be64b3d7243f40513094

@oddcoder please take a look at this issue. it’s closed, because i removed the comment, but this happens because the var analysis is not working 100% well yet.

**Comment by oddcoder** [comment]
Checking it  right now but please take care that var analysis I wrote is only triggered by the command afCa only..

**Comment by XVilka** [comment]
TOFIX: fill analop for this address

**Comment by AriEi4** [comment]
@oddcoder @radare  where analop at 0x004031f8 should be stored?

**Comment by oddcoder** [comment]
RAnalop are stored as array of offsets from the begineing of the basic blocks RAnalBlock
each RAnalFunction has linked list of all accesible RAnalBlocks

**Comment by AriEi4** [comment]
So.. what do we do with it?

**Comment by radare** [comment]
The line was already commented because its a debug printf, so it shouldnt annoy you. But i was just pointing this to @oddcoder because its related to his task

**Comment by AriEi4** [comment]
The print problem was fixed but there is still no analysis results to this function.. should I open another issue for the missing result?

**Comment by oddcoder** [comment]
hi there 
before pdf @ 0x4030b0
try afCa @0x4030b0
would help abit
