### ISSUE TITLE
p= and p=p output are (I think) wrong 

### ISSUE THREAD

**Issue by balzarot** [radare/radare2#4701]
... or I do not understand what it is supposed to do.
Example:

```
>r2 /bin/true
[0x004013e2]> p=p
... 
0x004018e2 05 0003 ||
...
0x00405fe2 4c 0047 |############|
...
```

Now , my understanding is that the block at 0x004018e2 contains 3 printable characters and the one 
at 0x00405fe2 0x47. Problem is, if I look at those blocks:

```
[0x004013e2]> px @ 0x004018e2
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x004018e2  0248 8b44 2408 4889 4208 488b 4424 1048  .H.D$.H.B.H.D$.H
0x004018f2  8942 1048 8b44 2418 4889 4218 488b 4424  .B.H.D$.H.B.H.D$
0x00401902  2048 8942 2048 8b44 2428 4889 4228 488b   H.B H.D$(H.B(H. 
0x00401912  4424 3048 8942 3048 89d0 4883 c448 c3e8  D$0H.B0H..H..H..
0x00401922  4af7 ffff 662e 0f1f 8400 0000 0000 4155  J...f.........AU
0x00401932  ba05 0000 0041 5441 89f4 4889 fe55 4889  .....ATA..H..UH.  
0x00401942  fd31 ff53 4883 ec08 e8a1 f7ff ff48 39e8  .1.SH........H9.
```

   ...

```
[0x004013e2]> px @ 0x00405fe2
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00405fe2  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00405ff2  ffff ffff ffff ffff ffff ffff ffff ffff ................
ff   all the way
```

I see that on any file, but if you want I can upload my /bin/true

**Comment by ret2libc** [comment]
It seems like the addresses are wrong. The command is calculating the # of printable chars from address 0 up to the total size of the file (https://github.com/radare/radare2/blob/master/libr/core/cmd_print.c#L1753). Probably there should be also some sort of header as a first line explaining the meaning of the fields...

**Comment by balzarot** [comment]
I see. But it wouldn't be more useful if the user could run the command at different offsets?
I mean, it could be interesting to plot the graph for the data on the heap while debugging for instance.

**Comment by radare** [comment]
sure it is :)

maybe with config vars to a command to specify the map/section/range to show

**Comment by ret2libc** [comment]
Yeah probably it would be better.

**Comment by balzarot** [comment]
I think the zoom (**pz**) and plot (**p=**) commands should be more consistent.
Some examples:

- [ ] **pz** honors the block size, but uses it in a very weird way (it consider it as the number of blocks instead of a size.. which is quite confusing)
- [ ] **pz** uses conf variables to define the boundaries. The same could be used for **p==**
- [ ] **pz** and **p=** do not support the same functions. They both have entropy and printable chars.
But **p=** also has number of bytes, while **pz** has strings (and more).
- [ ]  **pz** prints a heatmap but also a hexview on its side (I do not understand its use)
- [ ] If the terminal supports 256 colors **pz** could really take advantage of it
(something like this: https://github.com/Evizero/UnicodePlots.jl/blob/master/doc/img/density.png ) 
- [ ] with utf8, the barchar could be more pretty (e.g., https://github.com/Evizero/UnicodePlots.jl/blob/master/doc/img/barplot.png ) 

**pz** prints heatmaps, and **p=** bar charts.  There is a feature request to also add 2d plots in braille.
It would be nice if all these representations were somehow grouped together.
For instance, I could print the entropy of each block as a list (to easily grep high entropy blocks), or plot it in bars, or in a 2d graph, or in a heatmap. Same for the number of flags, characters, null-chars, invalid instructions, etc.

**Comment by Maijin** [comment]
" If the terminal supports 256 colors pz could really take advantage of it (something like this: https://github.com/Evizero/UnicodePlots.jl/blob/master/doc/img/density.png )
" 
check scr.truecolor=true

**Comment by radare** [comment]
agree, both commands are a bit forgotten and can be heavily enhaced by adding colors and more ways to represent the data.

+1 for all those proposals

**Comment by deepakchethan** [comment]
I am confused regarding what is the issue here. Is the output wrong or the headers are to be added or something else, can you please tell me @XVilka sir?

**Comment by deepakchethan** [comment]
ping?

**Comment by radare** [comment]
I think this was a presiol issue
