### ISSUE TITLE
cons/hud: match only exact substrings (ignoring case)

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#4704]
At the moment any letter of the pattern is highlighted in the HUD.
Example:
```
> re
0x100004Ec9    stR.REadttR
0x100004Edc    stR.REadExtattR
```

Notice how the E in the addresses are highlighted (even if it's not "re") and also the R at the end of the strings are highlighted. It should look like this:
```
> re
0x100004ec9    str.REadttr
0x100004edc    str.REadextattr
```
In this case only the "re" patterns are highlighted.

Also, the case should be ignored and we should highlight the pattern even if present in different case.

* [ ] highlight only exact substrings
* [ ] highlight even if the case doesn't match, because the search ignores the case

**Comment by balzarot** [comment]
Fixed by commit 86760900b1da9dc6530e99f7ffaf48fe5c8c20fb 
Please close

**Comment by radare** [comment]
Thanks!

**Comment by ret2libc** [comment]
Awesome!! Thanks
