### ISSUE TITLE
Simplify results of analyze.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#4706]
Hi,
Can we simplify results of analyze in order to get the known parts out of the way?

Check the "Important function!", all the rest should be the same for this compiler. This could be done by using a signature (hashes) db or another method to identify and mark known functions and concentrate only on modified, unknown.

1) I compiled:
`#include <stdio.h>
#include <stdlib.h>
int main()
{
	printf("Hello World\n");
	return(0);
}`
with gcc and Mingw.

2) For GCC. strip test, r2 test, aaaa:

> [0x0040052d]> afl
**0x004003e0  26    3     sub.__gmon_start___248_3e0
0x00400410  16    2     sym.imp.puts
0x00400420  16    2     sym.imp.__libc_start_main
0x00400430  16    2     loc.imp.__gmon_start__
0x00400440  42    1     entry0
0x00400470  41    4     fcn.00400470
0x004004e9  19    1     fcn.004004e9**
0x0040052d  21    1     main ---------------------------|  Important function!

Main function is identified and is the only important:
> [0x00400440]> pdf @main
/ (fcn) main 21
|           ; UNKNOWN XREF from 0x00400460 (entry0)
|           ; DATA XREF from 0x0040045d (entry0)
|           0x0040052d      55             push rbp
|           0x0040052e      4889e5         mov rbp, rsp
|           0x00400531      bfd4054000     **mov edi, str.Hello_World    ; "Hello World"** @ 0x4005d4
|           0x00400536      e8d5feffff     **call sym.imp.puts**
|           0x0040053b      b800000000     mov eax, 0
|           0x00400540      5d             pop rbp
\           0x00400541      c3             ret

2) For Mingw. r2 test.exe, aaaa:

> [0x004013aa]> afl
**0x00401000  12    1     sub.msvcrt.dll_atexit_0
0x00401020  231   5     sub.msvcrt.dll__iob_20
0x00401110  32    1     sub.msvcrt.dll___set_app_type_110
0x00401130  32    1     entry0
0x00401150  308   25    fcn.00401150
0x00401290  76    6     fcn.00401290
0x004012e0  5     1     fcn.004012e0
0x004012f0  40    3     fcn.004012f0
0x00401320  117   11    fcn.00401320
0x004013a0  10    1     fcn.004013a0**
0x004013aa  41    1     fcn.004013aa -----------------------|  Important function!
**0x004013e0  278   24    fcn.004013e0
0x00401500  7     1     fcn.00401500
0x00401510  42    3     fcn.00401510
0x00401540  6     1     sub.msvcrt.dll___getmainargs_540
0x00401548  6     1     sub.msvcrt.dll__setmode_548
0x00401550  6     1     sub.msvcrt.dll___p__fmode_550
0x00401558  6     1     sub.msvcrt.dll_signal_558
0x00401560  6     1     sub.msvcrt.dll___p__environ_560
0x00401568  6     1     sub.msvcrt.dll__cexit_568
0x00401570  6     1     sub.msvcrt.dll_puts_570
0x00401578  6     1     sub.KERNEL32.dll_SetUnhandledExceptionFilter_578
0x00401580  6     1     sub.KERNEL32.dll_ExitProcess_580
0x00401588  6     1     sub.KERNEL32.dll_GetModuleHandleA_588
0x00401590  6     1     sub.KERNEL32.dll_GetProcAddress_590**

> [0x004013aa]> pdf fcn.004013aa
/ (fcn) fcn.004013aa 41
|           ; var int local_4h @ ebp-0x4
|           0x004013aa      55             push ebp
|           0x004013ab      89e5           mov ebp, esp
|           0x004013ad      51             push ecx
|           0x004013ae      83ec04         sub esp, 4
|           0x004013b1      e86affffff     call fcn.00401320
|           0x004013b6      83ec0c         sub esp, 0xc
|           0x004013b9      6824304000     **push str.Hello_World ; str.Hello_World ; "Hello World"** @ 0x403024
|           0x004013be      e8ad010000     **call sub.msvcrt.dll_puts_570**
|           0x004013c3      83c410         add esp, 0x10
|           0x004013c6      b800000000     mov eax, 0
|           0x004013cb      8b4dfc         mov ecx, dword [ebp - local_4h]
|           0x004013ce      c9             leave
|           0x004013cf      8d61fc         lea esp, [ecx - 4]
\           0x004013d2      c3             ret

Am I missing something?

Thanks,
Tolik

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
the same bug again and again

**Comment by MariasStory** [comment]
Thanks for fast reply. r2 team is the best!

I hope that I use the git version:

> :~$ r2 -v
radare2 0.10.2 11065 @ linux-little-x86-64 git.0.10.2-99-g13db3fc
commit: 13db3fc20a9b9d6c56fb6803d77c3507d03d0364 build: 2016-04-25

From my point of view it is not a bug per say. Maybe a feature request.

Just want to help where I can and  cut the corners where possible. :-)

**Comment by radare** [comment]
there are some more bugs already opened to track this issue that is caused because of the `aa` subcommands and the lack of ability to decide which is the best way to name a function.

**Comment by radare** [comment]
having tests will benefit the overall situation to find the best method to autoname functions
