### ISSUE TITLE
Command injection vulnerability for swift-demangle

### ISSUE THREAD

**Issue by radare** [radare/radare2#4710]
```
r_sys_cmd_str_full: failed command '/usr/bin/xcrun swift-demangle -compact '_TMSS''
```

note the single quote

**Comment by XVilka** [comment]
you can make an alias in r2 environment for xcrun

**Comment by XVilka** [comment]
and inject everything you want

**Comment by radare** [comment]
its now disabled by default

**Comment by radare** [comment]
Yes, but the user controls the environment, not the bins that are loaded in r2
