### ISSUE TITLE
Add option for fill ESIL VM stack with data

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#4722]
Add option in aeim command for fill ESIL VM stack with debruijn pattern like in ragg2 -P. It's need for search vulns in program.

Example:

```
> aeimp # or other name
> px @ mem.0x100000_0xf0000 
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  4141 4142 4141 4341 4144 4141 4541 4146  AAABAACAADAAEAAF
0x00000010  4141 4741 4148 4141 4941 414a 4141 4b41  AAGAAHAAIAAJAAKA
0x00000020  414c 4141 4d41 414e 4141 4f41 4150 4141  ALAAMAANAAOAAPAA
...
```

**Comment by radare** [comment]
Maybe a config var undee the esil. Prefix? And choose between zeros, patterns, sequence...

**Comment by dukebarman** [comment]
This variant is a good too.

**Comment by radare** [comment]
Moving to 0.10.4 as long as its something that can be done in another way by hand. it's an easy thing to implement (focus on release)

**Comment by radare** [comment]
which kind of data u want to fill in the stack?

**Comment by dukebarman** [comment]
I wrote example above - `debruijn pattern like in ragg2 -P`. Or may add ability direct output any command to filling memory, like `aeim | ragg -P 10`

**Comment by radare** [comment]
wopD seems to fail for > 232K sizes. so its not gonna work for the 1MB default stack. other uses can be to dump/restore the contents of the stack, and be able to specify a file in aeim to just load the file in memory with its contents instead of having to aeim+wx and such
