### ISSUE TITLE
Incorrect (?) "registers read" for ESIL `=` operations

### ISSUE THREAD

**Issue by fabsx00** [radare/radare2#4726]
For an ESIL instruction of the form `src,dst,=`, "aear" reports both `src` and `dst`, meaning that both registers are reported to be read. I am wondering whether reporting `dst` is intentional or a bug.

Looking at the code, the handler `myregread` in `libr/core/cmd_anal.c` is called for the destination register because `esil_eq` in `libr/anal/esil.c` calls `r_anal_esil_reg_read` to determine the old value of the register and store it in `esil->old`.

**Comment by radare** [comment]
yep. ideally we shouldnt grab those as “read” registers. so under this situation we shouldnt call the read callback.

**Comment by fabsx00** [comment]
Ok. One possible patch would be to define a wrapper `r_anal_esil_reg_read_nocallback` that removes the hooks, calls `r_anal_esil_reg_read` and restores the hooks again. Something like this:

```C
R_API int r_anal_esil_reg_read_nocallback(RAnalEsil *esil, const char *regname, ut64 *num, int *size) {
	void *old_hook_reg_read = (void *) esil->cb.hook_reg_read;	
	esil->cb.hook_reg_read = NULL;		
	r_anal_esil_reg_read (esil, regname, num, size);
	esil->cb.hook_reg_read = old_hook_reg_read;	
}
```
This can then be called in `esil_eq` when reading the value of the destination register. What do you think?

**Comment by radare** [comment]
yep, looks good. maybe @condret can suggest another idea here?

**Comment by fabsx00** [comment]
I've added a commit to patch this for eq and all other functions that call `r_anal_esil_reg_read` only to retrieve the old value. @condret please let me know if you think this solution is ok or you would like me to implement a better one.

**Comment by fabsx00** [comment]
Hm, sorry about that, I'm just realizing that for or_eq, and_eq and the like, the existing code is correct as the destination register is indeed read. I'll fix this.

**Comment by condret** [comment]
sry, i was busy with real life. I hope to provide you a satisfying answere: esil->old and esil->cur is needed for computation of the cpu-flags, which is why we need to store old and new value of destination, so that we can compare them

**Comment by Maijin** [comment]
Digging up the old threads :P
