### ISSUE TITLE
Merging recursive traversal disassembler results and linear one - auto analysis of jump-in-the-middle fails

### ISSUE THREAD

**Issue by balzarot** [radare/radare2#4734]
radare uses a recursive traversal disassembler. However, I am playing with a simple binary I use to show my students the differences between the recursive and linear approaches and I get some weird output.
The program just contains a little forward jump to skip over two data bytes. 
`objdump` gets de-synchronized by this little trick and prints garbage, while IDA correctly disassembles the program without problems:

    .text:40052D main            proc near               ; DATA XREF: _start+1Do
    .text:40052D var_20          = qword ptr -20h
    .text:40052D var_14          = dword ptr -14h
    .text:40052D var_4           = dword ptr -4
    .text:40052D                 push    rbp
    .text:40052E                 mov     rbp, rsp
    .text:400531                 sub     rsp, 20h
    .text:400535                 mov     [rbp+var_14], edi
    .text:400538                 mov     [rbp+var_20], rsi
    .text:40053C                 mov     [rbp+var_4], 2
    .text:400543                 jmp     short loc_400547
    .text:400543 ; ---------------------------------------------------------------------------
    .text:400545                 db 11h, 47h
    .text:400547 ; ---------------------------------------------------------------------------
    .text:400547 loc_400547:                             ; CODE XREF: main+16j
    .text:400547                 xor     eax, eax
    .text:400549                 mov     eax, [rbp+var_4]
    .text:40054C                 mov     esi, eax
    .text:40054E                 mov     edi, offset format ; "%d\n"
    .text:400553                 mov     eax, 0
    .text:400558                 call    _printf
    .text:40055D                 leave
    .text:40055E                 retn
    .text:40055E main            endp

Despite the fact that it uses a recursive approach and that I have played with different options, I cannot get radare to correctly disassemble this code.
This is what I get:

     [...]> aaaa
     [...]> pdr @ main
    ╒ (fcn) sym.main 24
    │           ; var int local_4h @ rbp-0x4
    │           ; var int local_14h @ rbp-0x14
    │           ; var int local_20h @ rbp-0x20
    │           ; UNKNOWN XREF from 0x00400460 (entry0)
    │           ; DATA XREF from 0x0040045d (entry0)
    │           0x0040052d      push rbp
    │           0x0040052e      mov rbp, rsp
    │           0x00400531      sub rsp, 0x20
    │           0x00400535      mov dword [rbp - local_14h], edi
    │           0x00400538      mov qword [rbp - local_20h], rsi
    │           0x0040053c      mov dword [rbp - local_4h], 2
    ╘       ┌─< 0x00400543      jmp loc.00400547
    
In visual mode I get this:  
  
                0x0040052d      push rbp
    │           0x0040052e      mov rbp, rsp
    │           0x00400531      sub rsp, 0x20
    │           0x00400535      mov dword [rbp - local_14h], edi
    │           0x00400538      mov qword [rbp - local_20h], rsi
    │           0x0040053c      mov dword [rbp - local_4h], 2
    ╘       ┌─< 0x00400543      jmp loc.00400547                    ;[1]
            │   ; DATA XREF from 0x00600e51 (unk)
            │   0x00400545  ~   adc dword [rdi + 0x31], eax
    │           0x00400548      ror byte [rbx - 0x397603bb], 0xbf
    │           0x0040054f      in al, 5
    │           0x00400551      add byte [rax], dil
    │           0x00400558      call sym.imp.printf                 ;[2]
    │           0x0040055d      leave
    ╘           0x0040055e      ret

Is it normal? Am I missing something here, maybe some options for the analysis?
(you can find the binary I use as example here: http://s3.eurecom.fr/~balzarot/download/test )

**Comment by crowell** [comment]
looks like analysis failed here. it should be size 50, right?

`af+ 0x0040052d 50 main` to make the function, but pdr is failing now, this is a bug.

**Comment by crowell** [comment]
with some hand-rolled analysis it can be printed (the second bb isn't properly added to the function, ugh...)
the following commands should work for your demo purposes until the anal is fixed.
```
[0x00400440]> s main
[0x0040052d]> af
[0x0040052d]> pdf
            ;-- main:
╒ (fcn) sym.main 24
│           ; var int local_4h @ rbp-0x4
│           ; var int local_14h @ rbp-0x14
│           ; var int local_20h @ rbp-0x20
│           0x0040052d      55             push rbp
│           0x0040052e      4889e5         mov rbp, rsp
│           0x00400531      4883ec20       sub rsp, 0x20
│           0x00400535      897dec         mov dword [rbp - local_14h], edi
│           0x00400538      488975e0       mov qword [rbp - local_20h], rsi
│           0x0040053c      c745fc020000.  mov dword [rbp - local_4h], 2
╘       ┌─< 0x00400543      eb02           jmp loc.00400547
[0x0040052d]> afb+ main 0x00400547 23
[0x0040052d]> pdr
            ;-- main:
╒ (fcn) sym.main 24
│           ; var int local_4h @ rbp-0x4
│           ; var int local_14h @ rbp-0x14
│           ; var int local_20h @ rbp-0x20
│           0x0040052d      55             push rbp
│           0x0040052e      4889e5         mov rbp, rsp
│           0x00400531      4883ec20       sub rsp, 0x20
│           0x00400535      897dec         mov dword [rbp - local_14h], edi
│           0x00400538      488975e0       mov qword [rbp - local_20h], rsi
│           0x0040053c      c745fc020000.  mov dword [rbp - local_4h], 2
╘       ┌─< 0x00400543      eb02           jmp loc.00400547
--
├ loc.00400547 24
│           ; var int local_4h @ rbp-0x4
│           ; JMP XREF from 0x00400543 (sym.main)
│           0x00400547      31c0           xor eax, eax
│           0x00400549      8b45fc         mov eax, dword [rbp - local_4h]
│           0x0040054c      89c6           mov esi, eax
│           0x0040054e      bfe4054000     mov edi, 0x4005e4
│           0x00400553      b800000000     mov eax, 0
│           0x00400558      e8b3feffff     call sym.imp.printf
│           0x0040055d      c9             leave
--
[0x0040052d]>
```

**Comment by crowell** [comment]
@balzarot also, i was offbyone on my afb+, that 23 should be a 24 :smile:

**Comment by balzarot** [comment]
Thanks @crowell for the workaround. I plan to show radare in class in 10 days, so it was not super-urgent. Just wanted to understand if it was a bug or my poor use of the tool :)

**Comment by radare** [comment]
Is this happening in 0.10.2 too or its just a bug in the git?

**Comment by crowell** [comment]
was broken in 0.10.2

```
minishwoods tools/radare2 ‹644c0c4*› » r2 -v
radare2 0.10.2 11086 @ linux-little-x86-64 git.0.10.2
commit: 644c0c4930190c7ef45b491643e381e8f4795263 build: 2016-04-28
minishwoods tools/radare2 ‹644c0c4*› » r2 ./test       
Error: provided size must be size > 0
 -- SSAbotage from ISIL
[0x00400440]> af@main
[0x00400440]> pdr@main
            ;-- main:
╒ (fcn) sym.main 24
│           ; var int local_4h @ rbp-0x4
│           ; var int local_14h @ rbp-0x14
│           ; var int local_20h @ rbp-0x20
│           0x0040052d      55             push rbp
│           0x0040052e      4889e5         mov rbp, rsp
│           0x00400531      4883ec20       sub rsp, 0x20
│           0x00400535      897dec         mov dword [rbp - local_14h], edi
│           0x00400538      488975e0       mov qword [rbp - local_20h], rsi
│           0x0040053c      c745fc020000.  mov dword [rbp - local_4h], 2
╘       ┌─< 0x00400543      eb02           jmp loc.00400547
--
[0x00400440]> 
```

**Comment by radare** [comment]
can you provide the binary or the bytes that construct this function?

**Comment by balzarot** [comment]
There is a link to the binary at the bottom of my first message.

**Comment by crowell** [comment]
ah, i see (probably) the bug here. 

```
[0x00400440]> af @ main
[0x00400440]> afl
0x00400410  16    2     sym.imp.printf
0x0040052d  24    1     sym.main
0x00400547  24    1     loc.00400547
```
loc.00400547 is being treated as a function instead of just a label.

**Comment by balzarot** [comment]
Yes, good catch. Indeed radare detects the basic block as an independent function.

**Comment by radare** [comment]
i think the fix for this is just to check not just if the destination address is inside a basic block, but if that address is in ANY of the instructions of the basic block or in the middle of two. and then producing a new basic block without splitting it which will produce invalid disassembly.

We shuold run another pass after this to mark as data all dead code, but dead code should not be listed in the function graph

**Comment by jduck** [comment]
I suspect this isn't necessarily constructive, but @endeav0r once made a disassembler that does something very cool in this case. He follows both paths (both the jump and the alternative timeline created by it) and the recursive descent. This produces two distinct basic blocks and a control flow divergence. Very cool idea IMHO. See https://github.com/endeav0r/rdis

**Comment by VPaulV** [comment]
After fix:
```[0x00400440]> pdf @main
            ;-- main:
/ (fcn) sym.main 48
|           ; var int local_20h @ rbp-0x20
|           ; var int local_14h @ rbp-0x14
|           ; var int local_4h @ rbp-0x4
|           ; DATA XREF from 0x0040045d (entry0)
|           0x0040052d      55             push rbp
|           0x0040052e      4889e5         mov rbp, rsp
|           0x00400531      4883ec20       sub rsp, 0x20
|           0x00400535      897dec         mov dword [rbp - local_14h], edi
|           0x00400538      488975e0       mov qword [rbp - local_20h], rsi
|           0x0040053c      c745fc020000.  mov dword [rbp - local_4h], 2
\       ,=< 0x00400543      eb02           jmp loc.00400547
|- loc.00400547 24
|           ; var int local_4h @ rbp-0x4
|           ; JMP XREF from 0x00400543 (sym.main)
|           0x00400547      31c0           xor eax, eax
|           0x00400549      8b45fc         mov eax, dword [rbp - local_4h]
|           0x0040054c      89c6           mov esi, eax
|           0x0040054e      bfe4054000     mov edi, 0x4005e4
|           0x00400553      b800000000     mov eax, 0
|           0x00400558      e8b3feffff     call sym.imp.printf
|           0x0040055d      c9             leave
\           0x0040055e      c3             ret
[0x00400440]> 
```
