### ISSUE TITLE
Feature: Lazy loading of a project

### ISSUE THREAD

**Issue by ishitatsuyuki** [radare/radare2#4736]
Currently I'm analyzing a large binary (~20 megabytes).

Radare2 processes very slow: barely 20 minutes on analyzing, and also 10 min on loading and saving. This is the result on an latest processor: `Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz`.

I'm wondering if we can do load (and probably save) on demand, as it's burning my computer every time resuming the session.

A little details: it's an ARM Android binary.

**Comment by radare** [comment]
We didnt started to optimize the analysis yet. Theres a lot of ways to do that. And u can append an ampersand at the end of any command to make it run in a background thread .. With al the racy goblins in there..

**Comment by radare** [comment]
See r2 -t too

**Comment by radare** [comment]
Anyway i dont recommend doing full anaysis because its pointless but all users seems to be infected by the idaism approach

**Comment by XVilka** [comment]
We need sample binary anyway, to test from time to time. Or you can help us by profiling, what function/command repeats more or takes longer.

**Comment by Maijin** [comment]
The issue is more on the improvement of Project rather than Analysis

**Comment by radare** [comment]
ideally using sdb loading huge projects should be done in miliseconds, because it will just imply mapping the database in memory. but this is not gonna be done anytime soon i guess.. i dont have much time for this lately

**Comment by radare** [comment]
This can be done by using r_threads in libr/core/project.c {save/load}. should be easy to do it racy

**Comment by radare** [comment]
Fixed in 9c57ff07a63356fd7bd2020c0f6c64bc9700b18e
