### ISSUE TITLE
Question about relocation 

### ISSUE THREAD

**Issue by MatteoBertolino92** [radare/radare2#4737]
Let me say that I am a beginner. I am trying to solve a crackme example. The purpose was finding the correct password. I disassembled the main, and I read:
` 0x080484c7    c7042440a00. mov dword [esp], sym.pass.1964` 
So I did: `px @ sym.pass.1964`, but I see an empty memory area (address 0x0804a040). 
I brute-forced the memory and I discovered the string that I searched at: 0x08049040 and not 0x0804a040 as supposed. What is the problem? I thinked about randomization and I disabled ASLR, but nothing changes. I read some other topics but I didn't find an explanation. 
Thank you for your suggestions.

**Comment by oddcoder** [comment]
would you mind sharing the bin file ?

**Comment by MatteoBertolino92** [comment]
Sure. I took the binary test in the section Setting Up of this web site:
https://samsymons.com/blog/reverse-engineering-with-radare2-part-1/
In the first line (To kick things off, I’ll walk through the first few challenges for lecture two.) 
The challenge is the number: crackme0x00b. 
Thanks

**Comment by oddcoder** [comment]
well I followed that sequence
```
r2 crackme0x00b
aaa
afCa @ main
pdf @main
```
the first line analyzes all the functions
line 2 set the arguments/variables name
line 3 prints disassembly at main
```
|   0x080484af      8d54241c       lea edx, [esp + 0x1c]       ; 0x1c
|   0x080484b3      89542404       mov dword [esp + 4], edx
|   0x080484b7      890424         mov dword [esp], eax
|   0x080484ba      e811ffffff     call sym.imp.__isoc99_scanf
|   0x080484bf      8d44241c       lea eax, [esp + 0x1c]       ; 0x1c
|   0x080484c3      89442404       mov dword [esp + 4], eax
|   0x080484c7      c7042440a004.  mov dword [esp], obj.pass.1964 ; [0x804a040:4]=119 LEA obj.pass.1964 ; "w" @ 0x804a040
|   0x080484ce      e8bdfeffff     call sym.imp.wcscmp
```
so whats being scanned is tested against some wide char string stored at obj.pass.1964
so most probably `ps` wont work I dont know if r2 have support to print wide char or not but you can always hex dump at obj.pass.1964
```
px @obj.pass.1964
0x0804a040  7700 0000 3000 0000 7700 0000 6700 0000  w...0...w...g...
0x0804a050  7200 0000 6500 0000 6100 0000 7400 0000  r...e...a...t...
0x0804a060  0000 0000                                                        ....
```
so the key is w0wgreat
I dont think their is anything here related to ASLR imho.
those zeros are because wc here takes 4 bytes per character

**Comment by crowell** [comment]
@oddcoder you can also use psw to print widechar strings

On Fri, Apr 29, 2016 at 12:10 PM, Ahmed Mohamed Abd El-MAwgood <
notifications@github.com> wrote:

> well I followed that sequence
>
> r2 crackme0x00b
> aaa
> afCa @ main
> pdf @main
>
> the first line analyzes all the functions
> line 2 set the arguments/variables name
> line 3 prints disassembly at main
>
> |   0x080484af      8d54241c       lea edx, [esp + 0x1c]       ; 0x1c
> |   0x080484b3      89542404       mov dword [esp + 4], edx
> |   0x080484b7      890424         mov dword [esp], eax
> |   0x080484ba      e811ffffff     call sym.imp.__isoc99_scanf
> |   0x080484bf      8d44241c       lea eax, [esp + 0x1c]       ; 0x1c
> |   0x080484c3      89442404       mov dword [esp + 4], eax
> |   0x080484c7      c7042440a004.  mov dword [esp], obj.pass.1964 ; [0x804a040:4]=119 LEA obj.pass.1964 ; "w" @ 0x804a040
> |   0x080484ce      e8bdfeffff     call sym.imp.wcscmp
>
> so whats being scanned is tested against some wide char string stored at
> obj.pass.1964
> so most probably ps wont work I dont know if r2 have support to print
> wide char or not but you can always hex dump at obj.pass.1964
>
> px @obj.pass.1964
> 0x0804a040  7700 0000 3000 0000 7700 0000 6700 0000  w...0...w...g...
> 0x0804a050  7200 0000 6500 0000 6100 0000 7400 0000  r...e...a...t...
> 0x0804a060  0000 0000                                                        ....
>
> so the key is w0wgreat
> I dont think their is anything here related to ASLR imho.
> those zeros are because wc here takes 4 bytes per character
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4737#issuecomment-215783678>
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by MatteoBertolino92** [comment]
Thanks for the answers. Unfortunately the behaviour of my machine is different. 
`[0x080483e0]> pdf @ main
/ (fcn) sym.main 101
|           0x08048494    55           push ebp
|           0x08048495    89e5         mov ebp, esp
|           0x08048497    83e4f0       and esp, 0xfffffff0
|           0x0804849a    83c480       add esp, 0xffffff80
|           ; CODE (CALL) XREF from 0x080484f7 (fcn.08048493)
|- loc.0804849d 196
|           0x0804849d    b8d0850408   mov eax, str.Enterpassword
|           0x080484a2    890424       mov [esp], eax
|           ; CODE (CALL) XREF from 0x08048386 (fcn.08048386)
|           ; CODE (CALL) XREF from 0x08048380 (fcn.0804837c)
|           ; CODE (CALL) XREF from 0x080483d6 (fcn.080483d6)
|           ; CODE (CALL) XREF from 0x08048396 (fcn.08048396)
|           ; CODE (CALL) XREF from 0x080483a6 (fcn.080483a6)
|           ; CODE (CALL) XREF from 0x080483b6 (fcn.080483b6)
|           ; CODE (CALL) XREF from 0x080483c6 (fcn.080483c6)
|           0x080484a5    e8d6feffff   call 0x108048380 ; (sym.imp.printf)
|              sym.imp.printf(unk)
|           0x080484aa    b8e1850408   mov eax, str.ls
|           0x080484af    8d54241c     lea edx, [esp+0x1c]
|           0x080484b3    89542404     mov [esp+0x4], edx
|           0x080484b7    890424       mov [esp], eax
|           ; CODE (CALL) XREF from 0x080483d0 (fcn.080483c6)
|           0x080484ba    e811ffffff   call 0x1080483d0 ; (sym.imp.__isoc99_scanf)
|              sym.imp.__isoc99_scanf()
|           0x080484bf    8d44241c     lea eax, [esp+0x1c]
|           0x080484c3    89442404     mov [esp+0x4], eax
|           0x080484c7    c7042440a00. mov dword [esp], sym.pass.1964
|           ; CODE (CALL) XREF from 0x08048390 (fcn.08048386)
|           0x080484ce    e8bdfeffff   call 0x108048390 ; (sym.imp.wcscmp)
|              sym.imp.wcscmp()
|           0x080484d3    85c0         test eax, eax
 ,=< 0x080484d5    7514         jnz 0x80484eb
|       |   0x080484d7    c70424e5850. mov dword [esp], str.Congrats
|       |   0x080484de    e8bdfeffff   call 0x1080483a0 ; (sym.imp.puts)
|       |      sym.imp.puts()
|       |   0x080484e3    90           nop
|       |   0x080484e4    b800000000   mov eax, 0x0
|       |   0x080484e9    c9           leave
|       |   0x080484ea    c3           ret
|       `-> 0x080484eb    c70424ef850. mov dword [esp], str.Wrong
|           ; CODE (CALL) XREF from 0x080483a0 (fcn.08048396)
|           0x080484f2    e8a9feffff   call 0x1080483a0 ; (sym.imp.puts)
|              sym.imp.puts()
|           ; CODE (CALL) XREF from 0x0804849d (fcn.08048493)
\           0x080484f7    eba4         jmp 0x10804849d ; (loc.0804849d)
`

After that:
`[0x080483e0]> px @sym.pass.1964
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x0804a040  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a050  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a080  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a090  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a0a0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a0b0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a0c0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a0d0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a0e0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a0f0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a100  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a110  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a120  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x0804a130  ffff ffff ffff ffff ffff ffff ffff ffff  ................`

And, obviously:
`[0x080483e0]> psw @sym.pass.1964
\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff
`

**Comment by oddcoder** [comment]
what is output of  `r2 -v` ?

**Comment by MatteoBertolino92** [comment]
This one
radare2 0.9.6 @ linux-little-x86-64 git.0.9.6
commit: Not build: 2014-03-23

**Comment by oddcoder** [comment]
tooo old 
please use r2 from github

**Comment by MatteoBertolino92** [comment]
Ops, I noticed! I rely on the string "your version is already the newest version" after an apt-get.
I'll try, Thank you for the answers

**Comment by oddcoder** [comment]
first uninstall the old one 
then
```
git clone git@github.com:radare/radare2.git
cd radare2
sudo sys/install.sh

```
and it should work well 
always update the git repo once every fewdays 
git pull a day keeps seg faults away

**Comment by MatteoBertolino92** [comment]
All works, thank you guys.
I tricked by the phrase "already up to date" ! 
I'll close the discussion, thank you again.
