### ISSUE TITLE
cmd.bp executes twice on breakpoint hit

### ISSUE THREAD

**Issue by Qwokka** [radare/radare2#4739]
After assigning a command to be executed at each breakpoint hit using "cmd.bp", the command executes twice at each breakpoint. This seems to be because both _r_core_debug_breakpoint_hit_ in _libr/core/core.c_ and _checkbpcallback_ in _libr/core/cmd_debug.c_ execute the command.

**libr/core/core.c**
```c
static void r_core_debug_breakpoint_hit(RCore *core, RBreakpointItem *bpi) {
        const char *cmdbp;
        int oecho = core->cons->echo; // should be configurable by user?
        core->cons->echo = 1; // should be configurable by user?
        cmdbp = r_config_get (core->config, "cmd.bp");
        if (cmdbp && *cmdbp)
                r_core_cmd0 (core, cmdbp);
        r_core_cmd0 (core, bpi->data);
        core->cons->echo = oecho;
}
```

**libr/core/cmd_debug.c**
```c
static int checkbpcallback(RCore *core) {
        ut64 pc = r_debug_reg_get (core->dbg, "PC");
        RBreakpointItem *bpi = r_bp_get_at (core->dbg->bp, pc);
        if (bpi) {
                const char *cmdbp = r_config_get (core->config, "cmd.bp");
                if (bpi->data)
                        r_core_cmd (core, bpi->data, 0);
                if (cmdbp && *cmdbp)
                        r_core_cmd (core, cmdbp, 0);
                return true;
        }
        return false;
}
```

Commenting out the lines relating to cmd.bp in either function fixes the problem for me, but I'm not sure in which function the command should be executed.

**Comment by radare** [comment]
Imho the checkbp shouldnt be calling the cmd.bp. Can u check if any of the callers is not calling corebphit after the check? And send a pullreq?

Thanks

**Comment by radare** [comment]
Also a testcase is welcome
