### ISSUE TITLE
Top level program overview.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#4741]
I really like the visual representation of a function "VV". There is a next "V" XREF representation. I would really like to have a top level overview of a program. Let's say a tree that starts from the entry and interconnects all functions.

Is there a way to do it?

**Comment by radare** [comment]
Thats what agc does but most of the time the graph is so huge that showing it in ascii is really complex. Thats why current VVV shows only one level of call refs

**Comment by Maijin** [comment]
Try `p` several time in `VV` or the `VVV` and you will get what you need

**Comment by radare** [comment]
no, this is not done

**Comment by Maijin** [comment]
? Then give what is expected because for me this is this:

<img width="924" alt="screen shot 2016-05-03 at 16 17 42" src="https://cloud.githubusercontent.com/assets/1408600/14986064/9a140eaa-114a-11e6-82b6-eb9144e6a59e.png">

**Comment by radare** [comment]
this is pds, not agc

**Comment by Maijin** [comment]
yes, didn't read correctly ur initial message my bad, but though this was what @MariasStory wanted :P

**Comment by MariasStory** [comment]
Thanks Maijin, but I am speaking about something similar to agc.

The problem is that it is quite a tricky plot and it is hard to find a way around.
Maybe, it could be useful to have a fast way to view the function that you are working within the connection graph with another functions.
In some cases the *.dot plot is tricky and even does not plot.

Can we think of plotting such connections in the same way as the function plot is done?

**Comment by radare** [comment]
Yes thats what i plan to do when i have 5m of spare time

**Comment by radare** [comment]
It is now done in master :)

see https://twitter.com/radareorg/status/727621386244661250
