### ISSUE TITLE
Support for loading PS3 binaries

### ISSUE THREAD

**Issue by radare** [radare/radare2#4748]
Add tests and fix support to load all those .elf files:

https://ci.appveyor.com/project/rpcs3/rpcs3/branch/master/artifacts

**Comment by leberus** [comment]
Hi, what's exactly the problem loading these files? I could get the symbols and sections (and compared to readelf seems to be correct). I'm pretty sure i'm missing something

**Comment by radare** [comment]
the disasm doesnt seems correct. probably because how the linker works.. but dunno...

**Comment by radare** [comment]
I think we can close this issue and open it again if someone complains.
