### ISSUE TITLE
MIPS binaries overly difficult to use

### ISSUE THREAD

**Issue by kyleglowacki** [radare/radare2#4749]
I am using today's r2 build (version below)
$ r2 -v
radare2 0.10.2 9999999 @ linux-little-x86-64 git.0.10.2
commit: HEAD build: 2016-05-02

I have a binary file from a MIPS device that I've scp'd over to my ubuntu box (where r2) is installed.   When I load it in r2, I get messages that it can't load the sections :
$ r2 busy
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings

Depending on the exact binary I load, sometimes it also includes :
Warning: Cannot initialize dynamic section

I notice this whether I use the webui or commandline interface.   If I search for a string that I know is in the binary, I can find its memory address and use the hex dump to view it (and other nearby strings).   So, I know they are being loaded and exist in the binary, but r2 just can't seem to locate them.

Without being able to locate strings, functions, etc, it makes r2 very difficult to use.

**Comment by radare** [comment]
please test r2 from git before reporting a bug.

this warning is normal, it means that the binary is stripped, etc..

to search stuff in va mode you should check the search.in var, etc

dont report more than one issue in the same bug

**Comment by kyleglowacki** [comment]
This is a product improvement request.   You can claim its normal and how it works but then when you compare to opening the same binary in IDA, well, IDA blows radare out of the water.  It opens it fine, finds the symbols, strings, etc and parses things out. 

Point is, there are automated things which can be done.   The symbols are in the file.   function names, strings, etc.   I can see them all in a hex dump and other programs can make use of them... maybe radare should step up to the plate and handle them.

**Comment by radare** [comment]
r2 find strings, handle refs, and load symbols fine in MIPS binaries, but i cant help more if you dont use the version from git or share any binary to test what you are complaining

**Comment by kyleglowacki** [comment]
I thought I had the git version, but I guess not.   If I clone, it still doesn't support this functionality. 

$r2 -v
radare2 0.10.3-git 11109 @ linux-little-x86-64 git.0.10.2-167-ge805d70
commit: e805d701db7564fc8d3fe6c97f62cf042af72d84 build: 2016-05-02

$ r2 busy
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings

**Comment by alvarofe** [comment]
Can you share the bin? otherwise is difficult to test, fix and so on. Thx

**Comment by kyleglowacki** [comment]
I can... do I attach it here or how do I get it to the developer?

**Comment by alvarofe** [comment]
attach here

**Comment by kyleglowacki** [comment]
Here is an example from the host. 
[chat.zip](https://github.com/radare/radare2/files/246973/chat.zip)

It clearly has strings (search for "file") and it has function names (search for fprintf), but when loaded, it complains : 
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings

**Comment by radare** [comment]
Those strings you mention are not strings, those are in the import table and they are not strings because they should be in a different section but as long as the bin is sstripped the section info is not there

**Comment by radare** [comment]
binaries can contain strings, those warnings just say the string table from the ELF section cant be initialized because the headers are gone because its sstriped

**Comment by alvarofe** [comment]
should be fixed now. I screw up the parser getting wrong number of entries from the dynamic section.
