### ISSUE TITLE
Fails to Detect All Functions

### ISSUE THREAD

**Issue by jayint3z3r** [radare/radare2#4750]
Here's the file I am working with: http://puu.sh/oDA6E/75a93859d9.bin

radare2 is having a problem detecting all of the functions. This is a huge issue and also leads to other problems such as recognizing functions located in the FLIRT signature files.

The issue with the FLIRT that it is not matching up the functions properly is because some function signatures rely on an offset from another function. 

An example with the file above would be at 0x10006A59 which is marked at __NLG_Notify in IDA but is not marked in radare2. This is because the __NLG_Notify signature relies on an offset from _global_unwind2 as seen here: 
```
556A006A0068........FF7508E8........5D5F5E5B8BE55DC3:
              0. 2D 1EFC 00BF 0000:__global_unwind2 (l)0020:__unwind_handler 0042:__local_unwind2 009C:__abnormal_termination (0020: 20)
              1. 2D 1EFC 00EE 0000:__global_unwind2 (l)0018:_gu_return (l)0020:__unwind_handler (l)0041:_uh_return 0042:__local_unwind2 (l)005F:_lu_top 009A:__NLG_Return2 (l)009C:_lu_done 00AA:__abnormal_termination (l)00CC:_at_done 00CD:__NLG_Notify1 00D6:__NLG_Notify (l)00E0:__NLG_Go 00E9:__NLG_Dispatch (0020: 2E)
              2. 1C 8AB4 0137 0000:__global_unwind2 (l)0018:_gu_return (l)0020:__unwind_handler (l)0064:_uh_return 0065:__local_unwind2 (l)008E:_lu_top (l)00AA:_continue_ (l)00D5:_lu_continue (l)00D7:_lu_done 00E9:__abnormal_termination (l)010B:_at_done 010C:__NLG_Notify1 0115:__NLG_Notify (l)0120:__NLG_Go 012C:__NLG_Dispatch2 0134:__NLG_Call 0136:__NLG_Return2
```

So, it appears that radare2 is not having a problem with the FLIRT files besides the referenced functions and the other issues are caused by the fact that radare2 fails to find all of the functions. An example in this file would be that it does not find 0x10006944 (_global_unwind2) and although it finds the __NLG_Notify function at 0x10006A59, it is unable to mark it because of not finding _global_unwind2.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
this code hasnt been touched in at least a year, i doubt git fixes anything here

maybe it will beg ood to contact who wrote flirt support to verify this. ormaybe the ida format is now different

**Comment by jayint3z3r** [comment]
@Maijin r2 -v gives me 0.10.1

@radare Look at the file I gave you and go to 0x10006944. It does not recognize the function via radare. 

The FLIRT is just one of the things affected by radare not finding all the functions after analysis due to how FLIRT works. I verified the FLAIR code, ported it over to Python, and it works correct.

After the pattern is found, some of the other signatures are found by an offset from the original function.
Example: __NLG_Notify is found at __global_unwind2 + 0x115

I was just mentioning FLIRT so you know that the FLIRT code is not the reason it is not recognizing these functions.

The real problem is that it's not finding all of the functions in numerous samples I have tested with. (tried "aa", "aaa", "aaaa", and then listed using "afl"

**Comment by Maijin** [comment]
So is definitely not last version, follow the uninstall and install from git !

**Comment by jayint3z3r** [comment]
@XVilka this is not just a zignatures problem. The zignatures problem is caused by the fact that radare2 is not finding all of the functions

**Comment by Maijin** [comment]
Did u update your r2 ?

**Comment by alvarofe** [comment]
if you `aap` (analyze function by preludes) it does detect the function

**Comment by alvarofe** [comment]
```
[0x10001247]> aap
[>] Scanning mr-x 0x10001000 - 0x10007400 done
Analyzed 85 functions based on preludes
```

**Comment by jayint3z3r** [comment]
@Maijin yes

@alvarofe Does not find 0x10006964 even with aap. The function is not referenced via a call and the prelude bytes do not match up.
`
static int check_preludes(ut8 *buf, ut16 bufsz) {
	if (bufsz < 10) return false;
	if (!memcmp(buf, (const ut8 *)"\x55\x89\xe5", 3))
		return true;
	else if (!memcmp(buf, (const ut8 *)"\x55\x8b\xec", 3))
		return true;
	else if (!memcmp(buf, (const ut8 *)"\x8b\xff", 2))
		return true;
	else if (!memcmp(buf, (const ut8 *)"\x55\x48\x89\xe5", 4))
		return true;
	else if (!memcmp(buf, (const ut8 *)"\x55\x48\x8b\xec", 4))
		return true;
	return false;
}
`
 It is referenced as shown in the photo here: http://puu.sh/oGVSU/b1992ca44e.png

**Comment by radare** [comment]
This is a data reference

**Comment by VPaulV** [comment]
In order to get results similar to the IDA results enable anal.hasnext
```
 r2 virus.bin 
[0x10001247]> e anal.hasnext = true
[0x10001247]> aac
[0x10001247]> afl~?
222
[0x10001247]> pdf @0x10006964
/ (fcn) fcn.10006964 69
|           ; DATA XREF from 0x100069b4 (fcn.100069a9)
|           ; DATA XREF from 0x10006a36 (fcn.10006a2d)
|           0x10006964      8b4c2404       mov ecx, dword [esp + 4]    ; [0x4:4]=3
|           0x10006968      f74104060000.  test dword [ecx + 4], 6     ; [0x6:4]=0x40000
|           0x1000696f      b801000000     mov eax, 1
|       ,=< 0x10006974      7432           je 0x100069a8
|       |   0x10006976      8b442414       mov eax, dword [esp + 0x14] ; [0x14:4]=0
|       |   0x1000697a      8b48fc         mov ecx, dword [eax - 4]
|       |   0x1000697d      33c8           xor ecx, eax
|       |   0x1000697f      e801e9ffff     call fcn.10005285
|       |   0x10006984      55             push ebp
|       |   0x10006985      8b6810         mov ebp, dword [eax + 0x10] ; [0x10:4]=184
|       |   0x10006988      8b5028         mov edx, dword [eax + 0x28] ; [0x28:4]=0 ; '('
|       |   0x1000698b      52             push edx
|       |   0x1000698c      8b5024         mov edx, dword [eax + 0x24] ; [0x24:4]=0 ; '$'
|       |   0x1000698f      52             push edx
|       |   0x10006990      e814000000     call fcn.100069a9
|       |   0x10006995      83c408         add esp, 8
|       |   0x10006998      5d             pop ebp
|       |   0x10006999      8b442408       mov eax, dword [esp + 8]    ; [0x8:4]=4
|       |   0x1000699d      8b542410       mov edx, dword [esp + 0x10] ; [0x10:4]=184
|       |   0x100069a1      8902           mov dword [edx], eax
|       |   0x100069a3      b803000000     mov eax, 3
\       `-> 0x100069a8      c3             ret
```
