### ISSUE TITLE
Write hexpairs from file

### ISSUE THREAD

**Issue by radare** [radare/radare2#4751]
iirc there was a command to do this, but icant find it now.. so maybe is gone or maybe in a non-logical place. it should be in `wxf` or `wfx`. this stuff should be more consistent to load/save blobs from r2 to disk in the following formats:

* binary
* base64
* hexpairs
* gzip

**Comment by Maijin** [comment]
```
| wf -|file          write contents of file at current offset
| wF -|file          write contents of hexpairs file here
```

**Comment by radare** [comment]
ok, imho it makes more sense to be wxf instead of wF, what do you think?

any other proposal for the other write subcommands?

**Comment by Maijin** [comment]
To be linked with #4280 maybe @P4N74 could work on this too

**Comment by radare** [comment]
Related to https://github.com/radare/radare2/issues/4835

**Comment by Maijin** [comment]
ok for the wxf instead of wF !

**Comment by Svenito** [comment]
Tests added radare/radare2-regressions#397

**Comment by radare** [comment]
we shuold also update the autocompletion tables to make wxf appear in <tab>

**Comment by Svenito** [comment]
Will add it

**Comment by XVilka** [comment]
Related then https://github.com/radare/radare2/issues/3033
