### ISSUE TITLE
Initial byte of unmapped area

### ISSUE THREAD

**Issue by haco20292** [radare/radare2#4752]
Hi, is there an option which can specify initial byte of unmapped  memory space? It can be used to simplify diffing between binary and corresponding memory image when doing malware analysis because there is some unused gap between sections and windows seems filled these gaps with 0x00. Thank you.

**Comment by radare** [comment]
are you refering to malloc:// ?

**Comment by radare** [comment]
you can fill a region with the wo subcommands

**Comment by haco20292** [comment]
I am referring 0xff at every address after I start r2 with '--' as argument. There are many gaps between sections because of alignment, these regions are still  filled with 0xff. I have tried to malloc a region before opening pe file but this method needs knowledge of load address, size of memory image of pe file. Is there a simple way to do this?

**Comment by radare** [comment]
Ah! I understand now. Theres no option for that but should be easy. Will do soon

**Comment by radare** [comment]
Fixed in master. Use e io.0xff=0

**Comment by haco20292** [comment]
Thank you!
