### ISSUE TITLE
Autodetect thumb, arm code

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#4755]
http://reverseengineering.stackexchange.com/questions/6080/how-to-detect-thumb-mode-in-arm-disassembly

I'm reading ABI ELF ARM because in the case of the library this doesn't work

**Comment by radare** [comment]
i wrote some more tests for this, will you take a look at this before 0.10.4 release?

**Comment by alvarofe** [comment]
Added in master in https://github.com/radare/radare2/commit/0bc983027f6052044b4c3d9fe143229df0f18aab and added test in r2r
