### ISSUE TITLE
Confusing tracing support

### ISSUE THREAD

**Issue by radare** [radare/radare2#4765]
Right now the tracing is implemented in debug and anal. `dt` and `at`. The `dbg.trace` option only traces instructions. but if we want to trace calls. the only way we have is using `dtc`.

it will be good to add `dbg.trace.calls` eval var set to true to store this information.

Otherwise the dtg command will not work.

**Comment by radare** [comment]
@leberus wanna chk this?

**Comment by leberus** [comment]
i'll take a look ;)

**Comment by XVilka** [comment]
Related to @RKX1209 's work too.

**Comment by radare** [comment]
ping @leberus @RKX1209

**Comment by XVilka** [comment]
@radare so this one can be closed?

**Comment by radare** [comment]
yep
