### ISSUE TITLE
Do not trace library code

### ISSUE THREAD

**Issue by radare** [radare/radare2#4766]
when using `dtc` we should not emulate library code.

**Comment by radare** [comment]
cc @skuater

**Comment by ret2libc** [comment]
@radare I think there was already an option to do something like this... 
```
dbg.shallow_trace (While tracing, avoid following calls outside specified range)
```

**Comment by radare** [comment]
wtf who added that option it breaks the eval var naming conventions. and it makes no sense, we should rename this to something more meaningful. proposals?

**Comment by ret2libc** [comment]
:P I did, a long time ago, after talking with you about this.

**Comment by radare** [comment]
😭

**Comment by ret2libc** [comment]
@radare What to do about this? There's already an option to do that, maybe you can rename it to follow the standard naming convention. I don't have a good name for it :(

**Comment by radare** [comment]
this is already done for the traptracing iirc

i would move this to 0.10.5 because there’s not time for properlty testing this change

**Comment by radare** [comment]
this crap is taking too much time to be done

**Comment by radare** [comment]
TIRED OF WAITING
