### ISSUE TITLE
Add keys in visual graph to toggle between sub-graphs

### ISSUE THREAD

**Issue by radare** [radare/radare2#4769]
A graph represetntation via agn/age can contain multiple sub-graphs. this is. a group of nodes that are united by edges. when graphing the whole program callgraph we will find several isolated blocks, and it will make it more visual to be able to go next/prev sub-graph

**Comment by ret2libc** [comment]
I think this change can make the code really messy at the moment and also the visual representation would get hard to understand with so many graphs.. This would require to have a node that can be  a normal node or a RAGraph object. Considering the layout is far from being perfect, I would consider this with lower priority compared to fix the graph layout

**Comment by radare** [comment]
we can reopen in the case we need this at some point
