### ISSUE TITLE
mips.gnu analysis is broken after the BIG endian patch

### ISSUE THREAD

**Issue by radare** [radare/radare2#4775]

**Comment by XVilka** [comment]
@zamaudio that's all yours.

**Comment by zamaudio** [comment]
I'm working on it

**Comment by zamaudio** [comment]
Test for this is already provided for mips.gnu, it is marked as broken.  I am nearly there... The problem is that the branch delay gets confused when the jump is to the next address.  How should this be handled? op->delay should be set to 0 if the jump/ret is to the next instruction?

**Comment by radare** [comment]
is this handled properly in capstone?

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
PING

**Comment by radare** [comment]
:______________

**Comment by radare** [comment]
can you check this issue @daniel-rome ? you have access to be-mips machines

**Comment by daniel-rome** [comment]
Ok! let me some days, I am a bit busy ;)

**Comment by radare** [comment]
can you do this for 0.10.6 release?

**Comment by radare** [comment]
verified by @daniel-rome it was already fixed by me in 90fb18dcfc
