### ISSUE TITLE
Remove CHECK_ENDIAN rule from the configure script

### ISSUE THREAD

**Issue by radare** [radare/radare2#4777]
This requires reviewing all code in order to confirm that there's no pending LIL_ENDIAN ifdefs or so.

**Comment by radare** [comment]
cc @zamaudio

**Comment by zamaudio** [comment]
Uh oh, I found some stuff like SHA2 that uses host byte order...

**Comment by radare** [comment]
add tests!!!!!

**Comment by zamaudio** [comment]
See #4786

**Comment by zamaudio** [comment]
This issue should be closed

**Comment by radare** [comment]
If you commit like this : "Fix #xxx message" github will automatically close the issue and associate it with your commit

**Comment by zamaudio** [comment]
ok thanks
