### ISSUE TITLE
should afCa be added to aa

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#4782]
afCa autorename and declare vars/args

**Comment by radare** [comment]
Maybe in af but only if anal.vars is set

**Comment by Maijin** [comment]
@oddcoder Some stuff are buggy there, see the logs https://travis-ci.org/radare/radare2/builds/128861810
```
-|           0x08048435      2b450c         sub eax, dword [ebp + arg_ch]
+|           0x08048435      2b450c         sub eax, dword [ebp + 0xc]
```
