### ISSUE TITLE
Prelude Function Detection (aap)

### ISSUE THREAD

**Issue by jayint3z3r** [radare/radare2#4783]
Case File: http://puu.sh/oDA6E/75a93859d9.bin

In a lot of cases I have found that the prelude detection when finding functions can often produce wrong results. After running aap:
`0x10002652  2     1     fcn.100a2652
0x10002654  30    3     fcn.10002654
`
The function sizes get thrown off and we are getting the same function detected twice. It actually begins with 0x10002652.

`.text:10002652 8B FF                                   mov     edi, edi
.text:10002654 55                                      push    ebp
.text:10002655 8B EC                                   mov     ebp, esp`

This is because it matches the `"\x55\x8b\xec"` pattern but the mov edi, edi is very common at the start of a function. Maybe another prelude should be `"\x8B\xFF\x55\x8b\xec"`

**Comment by radare** [comment]
thats why it has been removed from `aa` and its only suposed to be run by the user by hand

aap is experimental, and right now it produces lot of false positives and breaks the analysis in several situations. also the aap should be pluggable and properly configurable, which right now is hardcoding all the preludes inline.

preludes should consist in a more complex representations, not just a sequence of bytes, also a sequence of instruction types, a speific offset alignment, some constraints (not being in the middle of an already analyzed function, ..) and so on.. if you want to help on defining all those rules it wiill be helpful to properly implement aap

**Comment by radare** [comment]
Meanwhile you can just send a PR including the signature you propose

**Comment by Maijin** [comment]
That's the reason btw https://blogs.msdn.microsoft.com/oldnewthing/20110921-00/?p=9583/

**Comment by VPaulV** [comment]
Sorry for this "commit spam", did it by mistake
