### ISSUE TITLE
r2script ability to pause

### ISSUE THREAD

**Issue by xn0px90** [radare/radare2#4787]
Having the ability to create pauses on r2scripts.
As the r2scripts runs it pauses for example the ability to create tutorials with r2script and asciinema.

**Comment by radare** [comment]
!sleep 1

**Comment by radare** [comment]
There are ? Subcommands for prompting the user in different ways too

**Comment by Maijin** [comment]
Check `???`

**Comment by XVilka** [comment]
@radare my idea is to implement something like "demo mode" - when all commands echoing on the screen, then pause (to read them), then output, then pause (to read output). And ability to run it using just option of r2, for example? something like `r2 -E script.r2`, where `-E` means `entertain`.

**Comment by radare** [comment]
Every key or every command?

-i doesnt permits visual mode

So maybe we can add an scr.demo that when is set to true it will permit visual mode and will show all keys pressed and all commands in console.. Except maybe the ?e echo and such

The thing is that this logic can be implemented with another propgram in an unix way. But it will be not really portable.

A command in r2 to launch those will be nice too.. But im thinking that it will be nice to have a tutor mode that permits interaction in visual mode too.

**Comment by xn0px90** [comment]
Demo mode sounds awesome ! 
How would you present shortcuts used to drill in Visual mode for example.
> dcu entry0
> V
|df|
|TAB>|
|<TAB|

Just wondering ...

**Comment by radare** [comment]
What about making some kind of rcons scripting? We just want to script the console input and output by showing some messages at some points and doing sleeps and pressanykey. All this stuff is already in rcons and i can draft a quick dsl for it to emulate readchar and such

What do you think?

**Comment by Maijin** [comment]
ping(1) @xn0px90

**Comment by radare** [comment]
I added a config var to set a sleep time between lines. This is fancy for recordings
