### ISSUE TITLE
"syntax error: error in error handling"

### ISSUE THREAD

**Issue by apjanke** [radare/radare2#4793]
I've installed `radare2` 0.10.2 on OS X 10.9.5 using Mac Homebrew's [formula for it](https://github.com/Homebrew/homebrew-core/blob/97b4be0a171f425aef50502c39c26fbce76bd640/Formula/radare2.rb).

When I start it up, I get a couple syntax error messages, but then it seems to start up all right.

```
$ radare2 -
syntax error: error in error handling
syntax error: error in error handling
 -- Use rarun2 to launch your programs with a predefined environment.
[0x00000000]>
```

Are these errors significant? Does anybody know where they're coming from and how to get rid of them?

This was [originally reported to Homebrew](https://github.com/Homebrew/legacy-homebrew/issues/50633) by another radare2 OS X user.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
he is clearly not using r2 from @Maijin ... 

those messages are not in r2 sourcecode, so its probably a bug in the brew package or maybe in your system installation that you have multiple versions of r2 installed at the same time or outdated plugins.

try with r2 -vv

**Comment by apjanke** [comment]
That gives me version information.

```
$ r2 -vv
radare2 0.10.2 9999999 @ darwin-little-x86-64 git.0.10.2
commit: HEAD build: 2016-04-14
$ r2 -V
0.10.2  r2
0.10.2  r_anal
0.10.2  r_lib
0.10.2  r_egg
0.10.2  r_asm
0.10.2  r_bin
0.10.2  r_cons
0.10.2  r_flags
0.10.2  r_core
0.10.2  r_crypto
0.10.2  r_db
0.10.2  r_bp
0.10.2  r_debug
0.10.2  r_hash
0.10.2  r_fs
0.10.2  r_io
0.10.2  r_magic
0.10.2  r_parse
0.10.2  r_reg
0.10.2  r_sign
0.10.2  r_search
0.10.2  r_syscall
0.10.2  r_util
```

I'm pretty sure I only have the one `r2` installed. If I uninstall it, running `r2` gives me a "command not found" error.

**Comment by XVilka** [comment]
@apjanke `HEAD build: 2016-04-14` - is already too old, there are a lot of changes since this date, could you please confirm this bug with the latest available version from git?

**Comment by XVilka** [comment]
@apjanke ah, forgot to mention why this is important - new release 0.10.3 is pretty soon and it would amazing if we'll fix this bug before. Thank you for reporting this!

**Comment by apjanke** [comment]
Sure. I'm up for figuring this out, if you can help me with the debugging process (I'm not a regular `radare2` user).

I tried to install `radare2` from the current HEAD of master on GitHub (using `brew install --HEAD radare2, which grabs the latest commit from `radare2.git`, `radare2-bindings.git`, and `radare2-extras.git`). But the build is failing for me, on both OS X 10.9 and 10.11.

Error on 10.9, single-job build:
```
clang -dynamiclib -o libr_asm.dylib -Wl,-install_name,/usr/local/Cellar/radare2/HEAD/lib/libr_asm.dylib p/asm_6502.o p/asm_8051.o p/../arch/8051/8051.o p/asm_arc.o p/../arch/arc/gnu/arc-dis.o p/../arch/arc/gnu/arc-ext.o p/../arch/arc/gnu/arc-opc.o p/../arch/arc/gnu/arcompact-dis.o p/asm_arm_as.o p/asm_arm_cs.o p/../arch/arm/armass.o p/../arch/arm/armass64.o p/asm_arm_gnu.o p/../arch/arm/gnu/arm-dis.o p/../arch/arm/gnu/floatformat.o p/../arch/arm/aarch64/aarch64-dis.o p/../arch/arm/aarch64/aarch64-dis-2.o p/../arch/arm/aarch64/aarch64-opc.o p/../arch/arm/aarch64/aarch64-opc-2.o p/asm_arm_winedbg.o p/../arch/arm/winedbg/be_arm.o p/asm_avr.o p/asm_bf.o p/asm_cr16.o /private/tmp/radare2-20160508-40684-sum7bx/libr/asm/arch/cr16/cr16_disas.o p/asm_cris_gnu.o p/../arch/cris/gnu/cris-dis.o p/../arch/cris/gnu/cris-opc.o p/asm_csr.o p/asm_dalvik.o p/asm_dcpu16.o p/asm_ebc.o /private/tmp/radare2-20160508-40684-sum7bx/libr/asm/arch/ebc/ebc_disas.o p/asm_gb.o p/asm_h8300.o /private/tmp/radare2-20160508-40684-sum7bx/libr/asm/arch/h8300/h8300_disas.o p/asm_hppa_gnu.o p/../arch/hppa/gnu/hppa-dis.o p/asm_i4004.o p/asm_i8080.o p/asm_java.o p/asm_lanai_gnu.o p/../arch/lanai/gnu/lanai-dis.o p/../arch/lanai/gnu/lanai-opc.o p/asm_lh5801.o p/asm_lm32.o p/asm_m68k.o p/../arch/m68k/m68k_disasm/m68k_disasm.o p/asm_m68k_cs.o p/asm_malbolge.o p/asm_mcs96.o p/asm_mips_cs.o p/asm_mips_gnu.o p/../arch/mips/gnu/mips-dis.o p/../arch/mips/gnu/mips16-opc.o p/../arch/mips/gnu/mips-opc.o p/../arch/mips/mipsasm.o p/asm_msp430.o /private/tmp/radare2-20160508-40684-sum7bx/libr/asm/arch/msp430/msp430_disas.o p/asm_nios2.o p/../arch/nios/gnu/nios2-dis.o p/../arch/nios/gnu/nios2-opc.o p/asm_pic18c.o p/asm_ppc_cs.o p/asm_ppc_gnu.o p/../arch/ppc/gnu/ppc-dis.o p/../arch/ppc/gnu/ppc-opc.o p/asm_rar.o p/asm_riscv.o p/asm_sh.o p/../arch/sh/gnu/sh-dis.o p/asm_snes.o p/asm_sparc_cs.o p/asm_sparc_gnu.o p/../arch/sparc/gnu/sparc-dis.o p/../arch/sparc/gnu/sparc-opc.o p/asm_spc700.o p/asm_sysz.o p/asm_tms320.o p/../arch/tms320/tms320_dasm.o p/../arch/tms320/c55x_plus/c55plus.o p/../arch/tms320/c55x_plus/c55plus_decode.o p/../arch/tms320/c55x_plus/decode_funcs.o p/../arch/tms320/c55x_plus/hashtable.o p/../arch/tms320/c55x_plus/ins.o p/../arch/tms320/c55x_plus/utils.o p/asm_tricore.o p/../arch/tricore/gnu/tricore-dis.o p/../arch/tricore/gnu/tricore-opc.o p/../arch/tricore/gnu/cpu-tricore.o p/asm_v810.o p/../arch/v810/v810_disas.o p/asm_v850.o /private/tmp/radare2-20160508-40684-sum7bx/libr/asm/arch/v850/v850_disas.o p/asm_vax.o p/../arch/vax/vax-dis.o p/asm_ws.o p/asm_x86_as.o p/asm_x86_cs.o p/asm_x86_nasm.o p/asm_x86_nz.o p/asm_x86_olly.o p/../arch/x86/ollyasm/disasm.o p/../arch/x86/ollyasm/asmserv.o p/../arch/x86/ollyasm/assembl.o p/asm_x86_tab.o p/asm_x86_udis.o p/asm_xcore_cs.o p/asm_xtensa.o p/../arch/xtensa/gnu/xtensa-dis.o p/../arch/xtensa/gnu/xtensa-isa.o p/../arch/xtensa/gnu/xtensa-modules.o p/../arch/xtensa/gnu/elf32-xtensa.o p/asm_z80.o p/asm_z80_cr.o asm.o code.o          ../../shlr/udis86/decode.o ../../shlr/udis86/itab.o ../../shlr/udis86/syn-att.o ../../shlr/udis86/syn-intel.o ../../shlr/udis86/syn.o ../../shlr/udis86/udis86.o   -L/private/tmp/radare2-20160508-40684-sum7bx/libr/util -L/private/tmp/radare2-20160508-40684-sum7bx/libr/parse -L/private/tmp/radare2-20160508-40684-sum7bx/libr/db -L/private/tmp/radare2-20160508-40684-sum7bx/libr/syscall -L/private/tmp/radare2-20160508-40684-sum7bx/libr/lang -lr_util -lr_parse -lr_db -lr_syscall -lr_lang   -fPIC /private/tmp/radare2-20160508-40684-sum7bx/libr/../shlr/java/libr_java.a    /private/tmp/radare2-20160508-40684-sum7bx/libr/../shlr/capstone/libcapstone.a
ld: library not found for -lr_parse
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libr_asm.dylib] Error 1
make[2]: *** [asm] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

Build logs from 10.9/Xcode 6.2: https://gist.github.com/e9ffa725e5f5a7227f5ba2c04dc3dc00
Build logs from 10.11/Xcode 7.3: https://gist.github.com/b6c80d355d3d4f403343dc500a221737

I also build it manually from source from GitHub on 10.9, using the following steps, and got a similar-looking build error.

```
git clone https://github.com/radare/radare2.git
cd radare2
./configure --prefix=/tmp/test-radare2 --with-openssl
make CS_PATCHES=0
```

This sounds like an intermediate or internally-provided `radare2` library that isn't making it on to the path in this build sequence? Maybe we can fix this build error up first and then figure out the "`syntax error: error in error handling`" stuff.

**Comment by radare** [comment]
Why are you building without capstone patches? 

Why you are not using sys/install.sh?

**Comment by apjanke** [comment]
> Why are you building without capstone patches?

Honestly, I'm not sure. It's that way in the Homebrew formula, so I was following along. Based on [this PR](https://github.com/Homebrew/legacy-homebrew/pull/48914), it looks like `CS_PATCHES` might be necessary to get it to build under sandboxing that restricts file writes to the target prefix.

I get the same failure when I do a plain `make` without the `CS_PATCHES=0`.

> Why you are not using sys/install.sh?

I couldn't tell whether/how it supports `prefix` relocation, and I'm more comfortable using vanilla-looking `make` and autotools stuff. It also looks like it uses `sudo`, and I'd rather not run `sudo` if I can avoid it. (And it was late last night so I didn't have the energy to read through sys/install.sh. I can do so today if it's significant.)

Is it likely to build differently using sys/install.sh?

**Comment by radare** [comment]
Openssl is not necessary. It is not used at all right now. If you drop the capstone patches why not depend on system capstone? Thats what good packagers do to avoid dupped CVEs and such.

Sys/install is the script that simplifies the build process to
Avoid complains from users who doesnt know how to configure+make, yes, they exist.

R2 uses acr, which is an autoconf replacement which is totally comptible from the user point of view. But with heavy performance, maintainance and size benefits compred to the gnu version.

Dropping the cs ptches because they modift the src tree theres no sense because capstone itself is downloaded right before unless you are using a release tarball.

The reason why sys/install uses sudo is because users are dumb and im tired of responding simple build issues. The buuld is done as user and the installation is done as root. 

If you have a build issue then there shoukdnt be an installation possible, in fact that error is not in my code. So my guess is that your r2 is running with older libs already installed in system or using externa libs that produce this error at startup.

**Comment by apjanke** [comment]
> Openssl is not necessary. It is not used at all right now. If you drop the capstone patches why not depend on system capstone?

Good question. I'll look in to this and the CS patch dropping.

At this point, I think that message is coming from somewhere inside `lua` or the Lua UI code. (Most of the Google hits for similar errors are Lua-related.) And we're using an older version of Lua. I'll poke around there and see if I can get this running against the latest Lua.

Going to close this out since, yeah, looks like it might just be an issue with building against older libs/runtimes. Will re-open if this turns out to be something specific to the `r2` code.

Thanks!

**Comment by orome** [comment]
I'm seeing this with Homebrew `radare2`:

```
~ $ r2 -vv
radare2 1.1.0 9999999 @ darwin-x86-64 git.1.1.0
commit: HEAD build: 2017-01-30
```

Can I continue using Homebrew's version? I notice that the Homebrew installed an older `lua`: `lua@5.1`.

**Comment by radare** [comment]
It is fixed now?

**Comment by orome** [comment]
@radare — Did something change?

**Comment by radare** [comment]
Lua is not required by r2. Its just if you want to write scripts for it. Most people choose python or javascript . It is always recommended to install from git. If that's an issue in brew it should be reported there

**Comment by nucleare2** [comment]
I'm getting this too but now.

```
$ r2 -vv
radare2 1.6.0 0 @ darwin-x86-64 git.1.6.0
commit: HEAD build: 2017-09-15__13:23:54

#with:
$ r2 -V
1.6.0  r2
1.6.0  r_anal
1.6.0  r_lib
1.6.0  r_egg
1.6.0  r_asm
1.6.0  r_bin
1.6.0  r_cons
1.6.0  r_flag
1.6.0  r_core
1.6.0  r_crypto
1.6.0  r_bp
1.6.0  r_debug
1.6.0  r_hash
1.6.0  r_fs
1.6.0  r_io
1.6.0  r_magic
1.6.0  r_parse
1.6.0  r_reg
1.6.0  r_sign
1.6.0  r_search
1.6.0  r_syscall
1.6.0  r_util
```

On straight homebrew `brew install radare2`.

**Comment by maratmkhitaryan** [comment]
r_anal  anal Lol :)

**Comment by maratmkhitaryan** [comment]
I too error:
syntax error: error in error handling
syntax error: error in error handling
syntax error: error in error handling

r2 g++ Desktop/lol.cpp

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
Please reopen an issue if necessary.

**Comment by radare** [comment]
related https://github.com/radare/radare2/issues/9111
