### ISSUE TITLE
Nice syntax for breakpoints on "module_base + offset" instead of "db @ `dm~library.so:0[2]`+ 0x50"

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4796]
Since module bases can change per process execution, but offsets stay the same, support for breaking on a module_base + offset would be very helpful.

I picture something like "db (~stagefright.so) + 0x31337"...

The module base address should be resolved, offset added, and breakpoint inserted.

**Comment by alvarofe** [comment]
try ```db@`dm~stagefright.so:0[2]`+ 0x31337``` i don't know if that would we work. I think is the second column that gives you the address

**Comment by unixfreaxjp** [comment]
on d1530d5..6c7d91c openbsd x32
```asm
[804000:8168]> pd 5 @ `db~ld-2:0[2]`+0x10
            4000:8178      689480         push 0x8094
            4000:817b      0408           add al, 8
            4000:817d      51             push cx
            4000:817e      56             push si
            4000:817f      684199         push 0x9941
[804000:8168]>
```

**Comment by XVilka** [comment]
I think this bug suggests shorter way to describe this - may be some shortcut or embedded macro?

**Comment by jduck** [comment]
the `db~fright.so:0[2]` is workable but definitely not pretty. I think we can close this one as THERE IS A WAY!!!

**Comment by XVilka** [comment]
I've renamed issue so it's now feature request for syntax enhacement.

**Comment by unixfreaxjp** [comment]
> THERE IS A WAY!!!

huzzah!

**Comment by jduck** [comment]
Woot!
