### ISSUE TITLE
Error reading registers on Windows 7 64-Bit

### ISSUE THREAD

**Issue by dirkbike** [radare/radare2#4802]
The issue appears when running the latest binary release for Windows (radare2-w32-0.10.2-git) in a Windows Command Prompt.  It is repeatable regardless of the program being debugged, and whether or not the Command Prompt is opened as Administrator.  Here's an example:

C:\radare2-w32-0.10.2-git>radare2.exe -d program.exe
Spawned new process with pid 1692, tid = 5836
Attaching io to pid 1692
bin.baddr 0x00400000
Assuming filepath C:\radare2-w32-0.10.2-git\program.exe
asm.bits 32
attach 1692 1692
GetThreadContext: 6
r_debug_reg: error reading registers
GetThreadContext: 6
r_debug_reg: error reading registers
 -- Press 'c' in visual mode to toggle the cursor mode
GetThreadContext: 6
r_debug_reg: error reading registers
[0x00000000]>

**Comment by radare** [comment]
Should be fixed now, please confirm

**Comment by dirkbike** [comment]
So, I ran into a couple issues when trying to do a w32 compile from git.  My build environment is Ubuntu 16.04 x64 with i686-w64-mingw32-gcc.


1) When exporting CC=i686-w64-mingw32-gcc, there comes a point when the build scripts revert back to plain gcc.  Here's the first time this happens:

>>>>>>>>>>>>>>>>
NATIVE BUILD SDB
>>>>>>>>>>>>>>>>

  CC      arch/AArch64/AArch64BaseInfo.o
  CC      arch/AArch64/AArch64Disassembler.o
CC cdb.c
make[3]: gcc: Command not found
Makefile:71: recipe for target 'cdb.o' failed
make[3]: *** [cdb.o] Error 127
Makefile:90: recipe for target 'sdb/sdb.exe' failed
make[2]: *** [sdb/sdb.exe] Error 2
  CC      arch/AArch64/AArch64InstPrinter.o
  CC      arch/AArch64/AArch64Mapping.o


2) If I get around that by linking gcc to i686-w64-mingw32-gcc I get up to here:

CC io_bfdbg.c
CC crypto_aes.c
SDB dos-x86-16
../../..//libr/../shlr/sdb//sdb: 1: ../../..//libr/../shlr/sdb//sdb: MZ▒▒▒▒@▒▒▒: not found
../../..//libr/../shlr/sdb//sdb: 4: ../../..//libr/../shlr/sdb//sdb: Syntax error: Unterminated quoted string
Makefile:43: recipe for target 'dos-x86-16.sdb' failed
make[5]: *** [dos-x86-16.sdb] Error 2
Makefile:35: recipe for target 'all' failed
make[4]: *** [all] Error 2
Makefile:17: recipe for target 'do' failed
make[3]: *** [do] Error 2
make[3]: *** Waiting for unfinished jobs....

**Comment by radare** [comment]
Use sys/mingw32.sh

**Comment by dirkbike** [comment]
Yes, that is the script I ran.  Let me know if there is a known working build setup and I'll just use that.

**Comment by dirkbike** [comment]
mingw32.sh passes --with-compiler to the configure script, but that only sets USERCC.  Adding the line CC=$USERCC in the configure script before the compiler check resolves the problem, but I'm not sure if that's how the configure script is supposed to behave.

**Comment by dirkbike** [comment]
Also, the copy command shown below from the Makefile doesn't expand {elf,pe} like it does when run from a shell.  So I had to split it into two separate commands.

@cp -f libr/bin/d/{elf,pe}* "${WINDIST}/share/radare2/${VERSION}/format"

**Comment by dirkbike** [comment]
The build was successful and the error with the registers is fixed!  Thanks for help.  Any thoughts on updating the configure script and Makefile?
