### ISSUE TITLE
Load libraries after loading main binary

### ISSUE THREAD

**Issue by radare** [radare/radare2#4816]
Maybe add `bin.libs` variable that will find `rabin2 -l` libraries in $LIBPATH and load them into the current r2 session (fixing all PLT and such)

**Comment by jduck** [comment]
I don't think this is working as intended quite yet. Problems I can see with it:

1. the library path to search is hardcoded. on Linux systems there are /etc/ld.so.* files to specify system-wide default load path. I think there's also some special sauce inside binaries that can override that ($ORIGIN or such). Then there's environment variable that should be consulted too: LD_PRELOAD, LD_LIBRARY_PATH, etc.

PS. the existing hardcoded path list does not work for ubuntu linux. it uses /lib/x86_64-linux-gnu or similar for libc and other libraries. (this would be picked up by supporting ld.so.conf though)

2. the libraries that are loaded override symbols provided by the main binary. when i loaded my binary with symbols (that only links against libc) it overrode main and took me to main in libc :-/

3. although the library is loaded it does not appear to be linked and thus navigating from the binaries's main, through imports, to the actual function that would be used, does not work.

IMHO we should keep the ticket open until the feature is usable.

**Comment by jduck** [comment]
One more thing, the hardcoded size increment seems extra bad. What if the libraries are bigger than the increment? Would they start overwriting each other? Fail to load? Why not get the size and round up to the next page boundary?

**Comment by radare** [comment]
yep im aware of this, feel free to send a pr. my implementation was just an initial playground to start discussing the rest of stuff needed to have it fully working.
