### ISSUE TITLE
Deprecate file.analyze

### ISSUE THREAD

**Issue by radare** [radare/radare2#4817]

**Comment by jduck** [comment]
It doesn't seem to work anyway and seems obsoleted by -A, -AA, -AAA

**Comment by radare** [comment]
the idea of file.analyze is to analyze right after calling `o filename` .. which -A is used at load time.. but i think file.analyze will be broken when loading multiple files too..

**Comment by jduck** [comment]
In either case the gitbook should be updated to either reflect how this setting works (or remove it gets deprecated). It should also mention -A, -AA, -AAA, and putting "aaa" in the .r2rc too.

**Comment by ret2libc** [comment]
never used it.
