### ISSUE TITLE
OSX build *still* broken

### ISSUE THREAD

**Issue by zamaudio** [radare/radare2#4822]
#4810 did not fix the problem

**Comment by radare** [comment]
it builds fine in OSX, so not sure what is your problem

**Comment by radare** [comment]
not for me, it builds perfectly fine in all my macs, and also in travis. so the problem is not in the repo

**Comment by zamaudio** [comment]
https://travis-ci.org/radare/radare2/jobs/128781294#L103  <---- dude @.@  dont just look at the :ok: status in travis, look at the log!!!

**Comment by radare** [comment]
wtf isnt this suposed to be run in a clean environment every time?

**Comment by zamaudio** [comment]
its because it runs with make -k keeps going even if errors

**Comment by zamaudio** [comment]
so youre missing libr_tcc.a in the final build

**Comment by radare** [comment]
why is travis using make -k?

even if the build continues, if r2 is not built , the testsuite should fail, so it seems like there’s a previously installed version wtf

**Comment by radare** [comment]
libr_tcc.a is not suposed to be linked at the end. just by rparse
