### ISSUE TITLE
Incorrect return value of the function `r_str_unescape`

### ISSUE THREAD

**Issue by P4N74** [radare/radare2#4827]
In the function `r_str_unescape` (https://github.com/radare/radare2/blob/master/libr/util/str.c#L1122-L1163), the condition for the for loop is `buf[i]`. This can return incorrect value if the buf contains a NULL character which is not in escaped.

Handling this issue at the time of calling `r_str_unescape` won't be possible if the NULL character is in between of the buf string. In that case, it would be hard to decide if the return value is correct or not. Also in such cases, the string won't be unescaped properly.

Possible solution: change the signature of the function to `R_API int r_str_unescape(char *buf, int buflen)`.

**Comment by radare** [comment]
Well. The function is suposed to unescape strings, not buffers, your signature makes sense if handling len=-1 to strlen inside and keep the current functionality working

Can you send a PR for this?

**Comment by P4N74** [comment]
I didn't understand `your signature makes sense if handling len=-1 to strlen inside and keep the current functionality working`, esp. the part `handling len=-1 to strlen inside` Can you please explain it?

**Comment by radare** [comment]
(const ut8 *buf, int len) {
  if (len <0) {
    len = strlen ((const char *)buf);
  }
}

**Comment by P4N74** [comment]
Don't remember the main issue that led to create this issue and most probably it seems to have be worked around. If I find any issue about this again, I will look into the proper fix :)
