### ISSUE TITLE
BB of size 0

### ISSUE THREAD

**Issue by radare** [radare/radare2#4836]
wtf

way to reproduce:

```
r2 bins/mach0/FileDP
s main
af
afb
```

there are some nodes with size 0:
```
0x000028ec 0x00002988 00:0000 156 j 0x0000298c f 0x00002988
0x00002988 0x0000298c 00:0000 4 j 0x000029b0
0x0000298c 0x000029b0 00:0000 36 j 0x00002db8
0x000029b0 0x000029d8 00:0000 40 j 0x000029dc f 0x000029d8
0x000029d8 0x000029dc 00:0000 4 j 0x00002ac0
0x000029dc 0x00002a48 00:0000 108 j 0x00002aac f 0x00002a48
0x00002a48 0x00002a48 00:0000 0
0x00002aac 0x00002ac0 00:0000 20 j 0x00002d90
0x00002ac0 0x00002b28 00:0000 104 j 0x00002b50 f 0x00002b28
0x00002b28 0x00002b28 00:0000 0
0x00002b50 0x00002b74 00:0000 36 j 0x00002d80 f 0x00002b74
0x00002b74 0x00002b74 00:0000 0
0x00002d80 0x00002d90 00:0000 16 j 0x00002d90
0x00002d90 0x00002db8 00:0000 40 j 0x00002db8
0x00002db8 0x00002dd0 00:0000 24
```

**Comment by ret2libc** [comment]
Not a `graph` problem, it's clearly an analysis issue because there shouldn't be empty basic blocks. I'm gonna remove the graph tag.

**Comment by radare** [comment]
Yep i know thats not a graph issue

**Comment by radare** [comment]
Maybe we can consider that jumps up to the next instruction doesnt create new basic blocks

**Comment by jduck** [comment]
I agree that normal flow (following the false of a conditional branch) should not create a new basic block. I am not sure if this fits the strict definition of a basic block though. Regardless, it makes the most sense when thinking about control flow.

**Comment by radare** [comment]
will be nice to see if the same issue happens with a2f

**Comment by ret2libc** [comment]
@jduck why not? unless the code is obfuscated, a conditional branch always produces two basic blocks. The problem in this binary is most likely related with some bugs in ARM analysis (in particular with conditional branches)

**Comment by jduck** [comment]
sure but a basic block of zero size is useless. consider a comparison followed by 2 jumps... one for less than, one for greater than, then the normal flow is equal. what should that look like? what about in a graph visual mode?

**Comment by ret2libc** [comment]
The zero size basic block is simply caused by a bug somewhere in the analysis, there should be basic blocks larger than that in those cases.

Also when you have the case you described, you have anyway some basic blocks, maybe small, but you have them. Of course you don't have basic blocks of size 0, because it doesn't have any sense

**Comment by radare** [comment]
The same for the branches that jump to the next instruction which can be merged . I tried to hunt down that bb0 issue and didnt managed to find it because it looked like the jmp instruction was never being analyzed. Surely the anal loop needs love but fixing those bugs and writing tests will help on that.

I know we cant fix anal in one week, but lets try to fix those obvious bugs :)

**Comment by radare** [comment]
Having a bb of size zero should at least print a warning. This will help on finding the root of the issue
