### ISSUE TITLE
F8 doesn't work in visual mode, Linux

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4840]
subj

**Comment by crowell** [comment]
dso is broken or just f8 in visual mode?

**Comment by crowell** [comment]
looks like it is working to me here http://asciinema.org/a/3ne9a2ewgr631gm19x00d94yi

**Comment by radare** [comment]
i think its a problem in your terminal. please confirm

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
Can't reproduce anymore. Seems like a glitch of particular version - may be related to breakpoint changes? I don't know. Closing.
