### ISSUE TITLE
Installation on El Capitan

### ISSUE THREAD

**Issue by cclamb** [radare/radare2#4850]
Radare2 doesn't install in El Capitan without integrity protections turned off; I don't think this needs to be the case. I'm not sure why this couldn't install to /usr/local instead of /usr.

**Comment by Maijin** [comment]
What did you use to install ? Did you tried the dedicated script `./sys/install.sh` ?

**Comment by radare** [comment]
/usr/local is the place where sip allows you to install. So it does support that

**Comment by cclamb** [comment]
I tried the package installer, which installs to /usr. 

- c.
(Mispelngs courtesie of iPhone)

**Comment by cclamb** [comment]
Well, that'd be the right place, but the package installer goes to /usr, not /usr/local.

- c.
(Mispelngs courtesie of iPhone)

**Comment by radare** [comment]
It is fixed in master. 0.10.3 will be released soon and will get this done right.

Meanwhile i recommend you to install the version from git.

**Comment by cclamb** [comment]
Right on guys thanks!

On Tuesday, May 10, 2016, radare <notifications@github.com> wrote:

> It is fixed in master. 0.10.3 will be released soon and will get this done
> right.
>
> Meanwhile i recommend you to install the version from git.
>
> > On 11 May 2016, at 03:06, Chris Lamb <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Well, that'd be the right place, but the package installer goes to /usr,
> not /usr/local.
> >
> > - c.
> > (Mispelngs courtesie of iPhone)
> >
> > > On May 10, 2016, at 4:18 PM, radare <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > /usr/local is the place where sip allows you to install. So it does
> support that
> > >
> > > > On 10 May 2016, at 21:50, Chris Lamb <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > >
> > > > Radare2 doesn't install in El Capitan without integrity protections
> turned off; I don't think this needs to be the case. I'm not sure why this
> couldn't install to /usr/local instead of /usr.
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4850#issuecomment-218343165>
>


-- 
- c.
(Mspellngs courtesie of ipad)

**Comment by XVilka** [comment]
@cclamb can you confirm it was fixed for you?

**Comment by cclamb** [comment]
Do you want me to wait for the next version's installer, or check out from
git to install? I do have another mac I can use to install (i just
disabled/enabled SIP to install the latest production version).

- c.

**Comment by XVilka** [comment]
git of course

**Comment by Maijin** [comment]
go for the git please it's just 3 commands: Uninstall your current radare2 version then git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh

**Comment by radare** [comment]
Closing, as long as its already fixed in master
