### ISSUE TITLE
the sys/rebuild.sh script doesn't actually update binr/*

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4853]
This was really confusing for me when I was getting started with development.

**Comment by radare** [comment]
You dont really need to rebuild binr/* unless you are doing static binaries. do you?

**Comment by jduck** [comment]
I don't think I am doing static binaries but I've seen cases where things I changed were not reflected in the build. I've also seen some weirdness where an incremental build failed due to somehow missing definition. When in doubt, "make clean all" =)

What is the "rebuild.sh" supposed to do? IMHO it shouldn't exist if it won't be updated/supported/do what new developers would assume.

**Comment by radare** [comment]
The rebuild is suposed to rebuild some parts of r2 that are not able to detect revdeps like the stuff in shlr/*

It was done when modifying the java code but it is useful for other casss. Rebuild acceptsa word as argument that specifies what to rebuild.

**Comment by radare** [comment]
wontfix
