### ISSUE TITLE
V aliased as v ?

### ISSUE THREAD

**Issue by radare** [radare/radare2#4876]
we dont use v for anything right now, so it makes sense to have visual mode in lowercase too.. many ppl is actually used to use the uppercase one, so i would not remove it .. at least for now

**Comment by Svenito** [comment]
Agree, v would be more consistent, but keep a cross over period with V for scripts and muscle memory :)

**Comment by ret2libc** [comment]
Agree. Maybe in two/three versions we can completely remove V and just use v

**Comment by radare** [comment]
+1 change done.
