### ISSUE TITLE
dcr fails with Stepping failed! r_debug_step: failed ?

### ISSUE THREAD

**Issue by TheBigS** [radare/radare2#4881]
`$ r2 -version`
`radare2 0.10.3-git 11095 @ linux-little-x86-64 git.0.10.2-154-g9991f05`
`commit: 9991f05e8533d2b1f11e5d983c593d3800864a3f build: 2016-04-28`

I've made a video of the issue here, am I missing something?

https://asciinema.org/a/4l4k24glmrarqhtjhm5la79ap

**Comment by TheBigS** [comment]
Just updated using `sys/install.sh`, now 
`$ r2 -version`
`radare2 0.10.3-git 11209 @ linux-x86-64 git.0.10.2-266-g647b4f2`
`commit: 647b4f29b535bff0f8f231d902ea93ef1edd7715 build: 2016-05-14`

Still seeing same issue

**Comment by radare** [comment]
dcr steps into until it finds a ret instruction. This is probably not what the user will expect. So this must be moved into dcur and make dcr take the breakpoint adreess from the stack, link register, etc depending on platform

The step fails because the process is already dead

**Comment by radare** [comment]
also, the current behaviour of `dcr` is documented. See `dc?~dcr`

**Comment by jduck** [comment]
Related to #4708

**Comment by TheBigS** [comment]
Yeah looks like #4708 is what I'm looking for. 

Process isn't dead, at least it shouldn't be. If i rerun and step debug but don't step into the `sscanf` but instead do `Shift+S` to step over, the program keeps running. Its `sscanf` with the format string `%d %c %d` which is what I gave it, so it shouldn't crash there.

I'll monitor #4708 for feature updates. Thanks!

**Comment by jduck** [comment]
If you can contribute a test case for this on radare2-regressions that would be awesome =) I'll work to make the test pass =)
