### ISSUE TITLE
Multiple breakpoints command

### ISSUE THREAD

**Issue by radare** [radare/radare2#4882]
I think it will be interesting to have a way to set multiple breakpoints in one line. Stuff like:
- break on any import
- break on all symbols matching a glob
- break on all functions in a range
- ...

Propose ideas in here to design how should be implemented and used

**Comment by TobalJackson** [comment]
can we have a command of syntax like `db @@ pd 500~test[0]`

**Comment by radare** [comment]
Use backticks around the pd thing and u have it

**Comment by radare** [comment]
And use @@=

**Comment by TobalJackson** [comment]
It doesn't seem to work with 
```-> % r2 -v
radare2 1.2.1 13712 @ linux-x86-64 git.1.2.0-76-gc76baa303
commit: c76baa3036472855a2d3448946d438119b80b93c build: 2017-02-06__14:57:57
```

https://asciinema.org/a/2s3iskzkulu3gjxw7mf04o37x

**Comment by radare** [comment]
you want to do this:

```
[0x7fff5fc01000]> db $$ @@= `pid 300~call[0]`
```

**Comment by TobalJackson** [comment]
Ah, Ok.  Thank you!  Now it makes sense!
