### ISSUE TITLE
Support various Linux systems' symbol packages

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4888]
It's customary for Linux distributions to have packages that provide debug symbols. For example "libc6-dbg" in Debian-like systems. It would be amazing to support these.

They usually put the symbols in files that are prefixed with "/usr/lib/debug" from their main paths.

For bonus points, be sure that the packages match some how to avoid loading invalid symbols.

**Comment by radare** [comment]
This is how debug information is distributed on Apple systems. I think only Debian packages/builds stuff like that. And there's a bunch of people looking into support that already. Looking forward their update

**Comment by XVilka** [comment]
Same also in Gentoo with ['splitdebug'](https://wiki.gentoo.org/wiki/Debugging) option.

**Comment by radare** [comment]
cc @n4x0r

**Comment by radare** [comment]
works fine with oa and ob but requires manual step, moving to 1.x because its low prio now

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/5758

**Comment by XVilka** [comment]
Was fixed in https://github.com/radare/radare2/commit/0d78c577a3c66ff493073d321a35b3c8b6782f86
