### ISSUE TITLE
Sometimes a comment is not just a comment

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4889]
For example, see:

```
[0x08048400]> #dr PC
Error: provided size must be size > 0
```

:-/

**Comment by radare** [comment]
Comments start by '# ' see #? For help on why is this err

**Comment by jduck** [comment]
Okay! Thanks. Although this is surprising, I can swallow that it is working as intended. Maybe sprinkling some more help for the user would be good though. Something like "Error: provided size must be > 0 (see #?)"

**Comment by radare** [comment]
Im aware this is confusing so maybe we should be more strict on this and only catch the valid values. But the hashbang should be kept.. and for hashing most ppl is used to it.. So if you think inna better command for the hashing we can jump of here and just keep #! As an exception

**Comment by jduck** [comment]
Maybe 'ch' for calculate hash?

**Comment by jduck** [comment]
Also, there's nothing using "h" it seems...

**Comment by radare** [comment]
Or ph

Print Hash

**Comment by jduck** [comment]
In shell scripts, the shebang is a special case where the first line is the only line it works on.

**Comment by radare** [comment]
yep i know, but here in r2 is used to launch rlang plugins which are used by r2pipe

**Comment by jduck** [comment]
And that is necessary at any time during the input stream? I'm not familiar with rlang plugins or r2pipe. I guess I have some reading to do. Any pointers?
