### ISSUE TITLE
Ability to pass R2VERSION to acr, configure, makefiles to r2pm packages before building

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4893]
For example yara3 has https://github.com/radare/radare2-extras/tree/master/yara/yara3 it's own configure.acr and ./configure generated from it. It defines its own `VERSION 0.10.3-git`, which if different cause the problem, when r2 can't see this installed plugin. Plugins should derive somehow this parameter via r2pm.

**Comment by radare** [comment]
Done

**Comment by radare** [comment]
Note, that now all packages should be installed in the home by default. but they can also be installed in system with -gi, and uninstalled with -gu. i dont keep track where are the packages installed, so its up to the user for now. i'll try to find a clean solution to this
