### ISSUE TITLE
Update all r2pm packages to support home and system installation

### ISSUE THREAD

**Issue by radare** [radare/radare2#4898]

**Comment by radare** [comment]
broken packages:

* [ ] bcl

**Comment by radare** [comment]
Please @zlowram try to install all packages `r2pm -s` in your home (`r2pm -i`) and then in system (`r2pm -gi`), and fix if any pkg is broken, ive been testing, fixing and updating many packages today. so i will close this issue after your review.

thanks!

**Comment by radare** [comment]
@zlowram can you review all the pending packages (also the new csharp and such) which only install at home? and close this issue?

maybe having tests for the packages will help

**Comment by zlowram** [comment]
I'll do this, but can't promise to be quick :P

**Comment by crowell** [comment]
This issue was moved to radare/radare2-pm#4
