### ISSUE TITLE
step over is blocked by breakpoints

### ISSUE THREAD

**Issue by sha0coder** [radare/radare2#490]
Is not possible to step over an asm instruction which has a breakpoint.

Probably the cause is that the step over is a PRTACE_CONT and there is a bp on the starting instruction, then the cont stops.

Stepping-Into a bp WITHOUT problems:
[0x7fab28eb2fa0]> db rip
[0x7fab28eb2fa0]> ds
[0x7f5c96f8f633]> 

Stepping-Over a bp is not possible:
[0x7f5c96f8f633]> db rip
[0x7f5c96f8f633]> dso
Interrupted by a breakpoint
[0x7f5c96f8f633]> dso
Interrupted by a breakpoint
[0x7f5c96f8f633]> dso
Interrupted by a breakpoint
[0x7f5c96f8f633]>

**Comment by jjdredd** [comment]
can't reproduce. check and close. ping @sha0coder

**Comment by radare** [comment]
can someone confirm if this is still happening?

**Comment by radare** [comment]
PING. a test case is welcome

**Comment by Maijin** [comment]
old it works now adding an issue in r2r
