### ISSUE TITLE
Implement a byte-based hexdump output

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4905]
The default is 16-bit words, with 32-bit and 64-bit options available, but there is no byte version. May I suggest one of "pxc", "pxv", "pxB" ?  This would be similar to hexdump's "-C" option.

**Comment by radare** [comment]
Nope its not words. Current hexdump is byte based but groups bytes by pairs to save space. If it was word sized like hexdump or binutiles do you will be confused all time by the endian

**Comment by jduck** [comment]
Okay, I see. xxd also does byte-based with 2-byte grouping. The odd man out is "hexdump"'s default output that does seem to do 16-bit words... Meh.

**Comment by radare** [comment]
yep. we must keep our endian sanity

**Comment by radare** [comment]
Ok to close this?

**Comment by jduck** [comment]
Thanks for learnin me real good!

**Comment by radare** [comment]
👍
