### ISSUE TITLE
Breakpoints inside loops do not fire properly without swstep

### ISSUE THREAD

**Issue by jduck** [radare/radare2#4907]
Try the following script:

```
e scr.color=0
e dbg.swstep=false
db sym.called_in_loop
dc
dr PC
dc
dr PC
dc
dr PC
dk 9
```

I'll PR this and other tests to r2-regressions soon.

**Comment by jduck** [comment]
Actually it seems I broke that test with 29c2670 while I fixed "dbg.dc+ds.swstep2" / #4560 in #4890 . I have the kinks worked out on my debugger-fixes branch but there's too much going on there to merge anything ATM.

**Comment by radare** [comment]
looking forward your pr!
