### ISSUE TITLE
backtrace on BSD systems

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4910]
It requires [libexecinfo](https://github.com/freebsd/freebsd/tree/master/contrib/libexecinfo), so r2 buildsystem should check its presence.

**Comment by XVilka** [comment]
Based on https://github.com/radare/radare2/issues/4900

**Comment by radare** [comment]
R2 builds fine in fbsd for me

**Comment by radare** [comment]
can anyone testing r2 in netbsd and openbsd?

**Comment by XVilka** [comment]
@radare - yes, it should, because we disabled backtrace at all for *BSD.
But this bug is about checking `libexecinfo` dependency presence in the configure/makefile for *BSD systems, so users can enjoy backtrace on those systems too.

**Comment by radare** [comment]
Aah ok

**Comment by radare** [comment]
can we close this now?

**Comment by XVilka** [comment]
No, it's not solved yet.

**Comment by radare** [comment]
cc @younix

**Comment by radare** [comment]
we have #if (__linux__ && __GNU_LIBRARY__) || (__APPLE__ && APPLE_WITH_BACKTRACE) || defined(NETBSD_WITH_BACKTRACE) ... whats missing here? which specific bsd are you talking about? this is in libc, no need for execinfo imho

**Comment by XVilka** [comment]
libexecinfo is still required. Just try it yourself on FreeBSD for example

**Comment by XVilka** [comment]
@krytarowski @mscherer may be you can help here

**Comment by krytarowski** [comment]
Unless someone broke NetBSD, I got backtrace in the past and it worked correctly.

```
NAME
     backtrace - fill in the backtrace of the currently executing thread

LIBRARY
     Backtrace Information Library (libexecinfo, -lexecinfo)

SYNOPSIS
     #include <execinfo.h>

     size_t
     backtrace(void **addrlist, size_t len);

     char **
     backtrace_symbols(void * const *addrlist, size_t len);

     int
     backtrace_symbols_fd(void * const *addrlist, size_t len, int fd);

     char **
     backtrace_symbols_fmt(void * const *addrlist, size_t len,
         const char *fmt);

     int
     backtrace_symbols_fd_fmt(void * const *addrlist, size_t len, int fd,
         const char *fmt);
```

**Comment by krytarowski** [comment]
NetBSD requires `-lexecinfo`.

**Comment by mscherer** [comment]
I get the same output on Linux and FreeBSD when I use r2 -d /bin/ls and 'dbt', and no issue from building a fresh git checkout. FreeBSD has backtrace since FreeBSD 10.0 in the base system so I suspect that's the reason it work.

**Comment by radare** [comment]
@Cka3o4Huk do you wanna take a look at this issue?

**Comment by Cka3o4Huk** [comment]
@radare never tried this feature before. 
My first try (FreeBSD 12-CURRENT, radare 1.6.0):
![screenshot from 2017-11-24 20-03-21](https://user-images.githubusercontent.com/47472/33219329-c2f0b6a6-d152-11e7-8351-891b5f1b4db7.png)

What is expected result?

**Comment by Maijin** [comment]
That's too old please try with the latest git version of radare2
