### ISSUE TITLE
dcu entry0 seeks to 0 with esil

### ISSUE THREAD

**Issue by radare** [radare/radare2#4911]

**Comment by oddcoder** [comment]
@radare what is this issue about

**Comment by radare** [comment]
Esil emulation thing

**Comment by oddcoder** [comment]
please can you add details

**Comment by radare** [comment]
r2 /bin/ls
dcu entry0
s


The offset is 0 which is a bit wtf because it shouldnt reach that location at all because the entry cant be reached without ldso and such

**Comment by radare** [comment]
meh
