### ISSUE TITLE
Spaces in the function boundary lines in random places

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4914]
Spaces in the function boundary lines in random places:
![screenshot](http://xvilka.me/r2spaces.png)

**Comment by radare** [comment]
Not random. Those are parts not covered by the function. Thanks tot he ret2libc patch. So this is expected . Not a bug

**Comment by radare** [comment]
@ret2libc ok toclose this?

**Comment by ret2libc** [comment]
Yep
