### ISSUE TITLE
afn eip can result in wtf disasm

### ISSUE THREAD

**Issue by radare** [radare/radare2#4915]
```
[XX]  3  cmd_pd_bugs: call fcn eip

Regression: ./t/cmd_pd_bugs
Command:  /Users/ret2libc/bin/radare2 -e scr.color=0 -N -q -i /tmp/r2-regressions//cmd_pd_bugs-rad.lUxQUp   ../bins/elf/ls-alxchk > /tmp/r2-regressions//cmd_pd_bugs-out.aJaVbl 2> /tmp/r2-regressions//cmd_pd_bugs-err.h9D6jU
File: ../bins/elf/ls-alxchk
Script:
s 0x5e50
af; afn eip
pd 1 @ 0x5f16~:0
e asm.lines=0
e asm.bytes=0
e asm.comments=0

Diff: --- /tmp/r2-regressions//cmd_pd_bugs-exp.bQcHKR	2016-05-17 13:14:09.000000000 +0200
+++ /tmp/r2-regressions//cmd_pd_bugs-out.aJaVbl	2016-05-17 13:14:09.000000000 +0200
@@ -1 +1 @@
-|           0x00005f16      e835ffffff     call fcn.eip
+            0x00005f16      e835ffffff     call eip
```

**Comment by ret2libc** [comment]
I would move this to 0.10.4... what do you think?
We still need to choose if we want to allow the user to choose whatever names they want or if we want to always prefix "fcn."... 

I think prefixing "fcn." is ok, but that's my opinion.

**Comment by radare** [comment]
ive beendiscussing about this with other ppl and looks like ida does like this:

* if function name = registername -> show error

the problem is.. r2 can change from one arch to another at any time, ida cant do that, so registernames are not really good.

if we want to prefix a reg we should use the underline char instead of dot. so imho the options are:

* avoid fcnnames to be <4 chars of length
* avoid fcnnames that == registername
* prefix underline in case those conditions doesnt apply or fail

**Comment by ret2libc** [comment]
It may be good as solution, but it needs to be implemented in a good way to have only one place where these things are checked, otherwise it will be a mess.

**Comment by radare** [comment]
agree, but thats an aproximation to find a solution or at least a temporal workaround for the release. what do you think?

**Comment by ret2libc** [comment]
I think it's not worth doing it if it's just a temporary workaround for this release. We completely fix it now or we leave it as is and fix it in the best way possible for the next release IMO :)

**Comment by XVilka** [comment]
:+1: to ret2libc - temporary fix can mess the things up.

**Comment by radare** [comment]
no temporary fix can result in people confused, burned kitchens, massive destruction and unexpected behaviours.

**Comment by ret2libc** [comment]
Mmm this is not closed I think. 86213ba5556466b45c467fec65f844946e4e802e is not a proper fix, because as we already said, one can change arch later and you would have two flags with the same name

**Comment by radare** [comment]
Yes but this is the most aproximated way to fix this situation. Im also aware that regprofiles dont have all the regnames. So even walking all plugs will not be ok.

Another solution would be to make a blacklist, but i dont see any nice solution to this. Do you have a better proposal?

**Comment by ret2libc** [comment]
I think the solution you proposed some time ago is the way to go. A blacklist with all the names of registers. Like each asm plugin can implement a method to get the list of regnames and we can walk all plugins to see if the function name is in any one of these lists...
