### ISSUE TITLE
aav - undesirable results

### ISSUE THREAD

**Issue by hummypkg** [radare/radare2#4925]
I noticed that running _aaaa_ against a MIPS binary with the git version converts lots of assembly code into dwords. It looks like there are too many false positives here for it to be useful.

```
% r2 -N -a mips radare2-regressions/bins/elf/busybox-mips
[0x00404360]> pd 1 @0x00404488
            0x00404488      06504500       srlv t2, a1, v0
[0x00404360]> aav 
aav: using from to 0x400000 0x4581f0
Using vmin 0x400000 and vmax 0x458e94
[0x00404360]> pd 1 @0x00404488
            0x00404488 .dword 0x00455006
```

**Comment by radare** [comment]
Aav works pretty well for arm. Which recommendations do you have for reducing those false positives in mips?

**Comment by hummypkg** [comment]
I'll have another look at this when I can. It might just not be practical on MIPS since lots of words appear to look like references.

**Comment by radare** [comment]
Ok let me know

**Comment by hummypkg** [comment]
I don't have any good suggestions for this I'm afraid. I'm just avoiding aav for MIPS programs - aaa;aae;aat instead.

On MIPSel a lot of register instructions are represented as xxxx4300 and xxxx4400 so they look like data references to aav.

Here are some more examples (sdiff output, left is before aav and right after).

```
| 0x00432300      2b304400       a2 = (unsigned) (v0 < a0)    | | 0x00432300 .dword 0x0044302b
| 0x0043232c      2b384400       a3 = (unsigned) (v0 < a0)    | | 0x0043232c .dword 0x0044382b
| 0x00447b64      24104400       v0 &= a0                     | | 0x00447b64 .dword 0x00441024
| 0x00447b80      21104300       v0 += v1                     | | 0x00447b80 .dword 0x00431021
| 0x00433fa4      21204000       a0 = v0                      | | 0x00433fa4 .dword 0x00402021
| 0x00433fa8      21384000       a3 = v0                      | | 0x00433fa8 .dword 0x00403821
| 0x00435910      21884000       s1 = v0                      | | 0x00435910 .dword 0x00408821
| 0x0044a42c      21104300       v0 += v1                     | | 0x0044a42c .dword 0x00431021
| 0x00436764      21284000       a1 = v0                      | | 0x00436764 .dword 0x00402821
| 0x0043677c      24104300       v0 &= v1                     | | 0x0043677c .dword 0x00431024
| 0x00436788      24104300       v0 &= v1                     | | 0x00436788 .dword 0x00431024
| 0x00436790      24104300       v0 &= v1                     | | 0x00436790 .dword 0x00431024
| 0x00436794      25104400       v0 |= a0                     | | 0x00436794 .dword 0x00441025
| 0x00436b94      24104300       v0 &= v1                     | | 0x00436b94 .dword 0x00431024
| 0x004386dc      21804000       s0 = v0                      | | 0x004386dc .dword 0x00408021
| 0x00438700      21204000       a0 = v0                      | | 0x00438700 .dword 0x00402021
| 0x00438704      25104300       v0 |= v1                     | | 0x00438704 .dword 0x00431025
| 0x00438624      21804000       s0 = v0                      | | 0x00438624 .dword 0x00408021
| 0x00438648      21204000       a0 = v0                      | | 0x00438648 .dword 0x00402021
| 0x0043864c      25104300       v0 |= v1                     | | 0x0043864c .dword 0x00431025
| 0x00438fd0      0a204300       if (!v1) a0 = v0             | | 0x00438fd0 .dword 0x0043200a
```

**Comment by mrmacete** [comment]
Maybe a parameter to skip executable sections from search? In this way is still possible to find pointers to code stored in non executable sections, and avoids to misinterpret instructions

**Comment by radare** [comment]
i think esanfelix proposed a nice solution to this, which can be implemented in aav, and keep the current aav into aavv

see https://twitter.com/esanfelix/status/740877838837030912

**Comment by mrmacete** [comment]
yeah, that's cool

**Comment by hummypkg** [comment]
https://github.com/radare/radare2/commit/2ca927caea4e3dd920601493e7b360fe7b742d00
has definitely improved things (thanks for that) but it is still converting some instructions within function boundaries. Here's an example:

```
deb# (133) r2 ~/git/radare2-regressions/bins/elf/busybox-mips
 -- phrack, better than java in the browser -- jvoisin
[0x00404360]> e anal.vinfun
false
[0x00404360]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
[0x00404360]> pdf @ fcn.00421700 | grep -i dword
[0x00404360]> aav
aav: using from to 0x400000 0x4581f0
Using vmin 0x400000 and vmax 0x458e94
[0x00404360]> pdf @ fcn.00421700 | grep -i dword
      ||    0x00421764 .dword 0x00408821
  ||||||    0x00421864 .dword 0x00408821
  ||||||    0x00421890 .dword 0x00409021
  ||||||    0x004218d0 .dword 0x00408821
  ||| ||    0x004219e0 .dword 0x00408821
  ||||||    0x00421aa0 .dword 0x00409021
  ||||||    0x00421b20 .dword 0x00401821
   |||||    0x00421b54 .dword 0x00408821
   |||||    0x00421b7c .dword 0x00408821
  ||||||    0x00421bd0 .dword 0x00402021
  ||||||    0x00421bec .dword 0x00431021
  ||||||,=< 0x00421bf4 .dword 0x00400008
  |||||||   0x00421c24 .dword 0x00408821
   ||||||   0x00421d88 .dword 0x00408821
```

**Comment by radare** [comment]
those dwords are outside the boundaries of the function. use pdr if you dont wanna see them. there are dwords that are placed inside the code of the function just not reachable by any jump. can you confirm this is really code?

**Comment by hummypkg** [comment]
It's code, just apparently not reachable from that function. Here's the first hit @ 0x421764
```
/ (fcn) fcn.00421700 (32 bits) 1896
...
|     |,==< 0x00421754      08004000       goto v0
|     ||    0x00421758      00000000
      ||    ; UNKNOWN XREF from 0x00450378 (unk)
      ||    0x0042175c      fe7b100c       call sub.memset_ff8
      ||    0x00421760      10000424       a0 = zero + 0x10
      ||    0x00421764      21884000       s1 = v0
```
So it looks like it's doing what you intended, just not what I expected.

**Comment by radare** [comment]
so its then a bug in the code analyzer, or at least in the way its sequenced now. can you try with anal.hasnext=true enabled?

**Comment by hummypkg** [comment]
Same result.

**Comment by hummypkg** [comment]
That function is a big switch() statement switching on the return value of a function
https://git.busybox.net/busybox/tree/shell/ash.c?h=1_20_2&id=83785f0ebcad58157bb7d866037664ab95563f48#n10838
It's possibly too hard for the code analyser to deal with automatically.

Perhaps you could extend the new valinfun option to skip all words between the start and end addresses of functions?

**Comment by radare** [comment]
yeah makes sense. but not by default, because this is a bug in the analysis, and we should handle switch tables properly on arm too. which name do you propose?

**Comment by radare** [comment]
err mips

**Comment by hummypkg** [comment]
anal.novalinfuncrange

doesn't exactly trip off the tongue though..

**Comment by radare** [comment]
Maybe better with anal.vinfunrange

**Comment by hummypkg** [comment]
Yes that sounds better.

Is switch table support for MIPS something I should look at or is it planned for later?
It looks like there are three different analysis code paths at the moment including esil.

**Comment by radare** [comment]
added that var in master, pls check

**Comment by Maijin** [comment]
ping @hummypkg

**Comment by Maijin** [comment]
ping(2) @hummypkg

**Comment by Maijin** [comment]
Reproduced here https://github.com/radare/radare2/issues/6653 + has tests this time.
