### ISSUE TITLE
Advanced noreturn detection

### ISSUE THREAD

**Issue by radare** [radare/radare2#4929]
Analyze and find infinite loop instructions (jump to itself) and other termination instructions and syscalls to mark those functions as noreturn

**Comment by oddcoder** [comment]
fixed by https://github.com/radare/radare2/commit/6c47f5a20d08760289004f2ae15612b9a4073e0a

**Comment by oddcoder** [comment]
well not fully done*

**Comment by radare** [comment]
oh.. wats missing?

**Comment by oddcoder** [comment]
automatic detection of similar functions to this one as noreturn
```
void foo () {
        if (something) {
                //some code
                exit(0);
        }
        exit(2);
}
```
since all pathes here would lead to a no return function this function should also be identified as no return but that wont simply happen, one should add that manually

**Comment by oddcoder** [comment]
probably we will be able to that at certain point :)

**Comment by Maijin** [comment]
Fixed
