### ISSUE TITLE
r2 'aac'. False positive functions detections

### ISSUE THREAD

**Issue by VPaulV** [radare/radare2#4936]
r2 'aac' sometimes detects a big number of false positive functions. I did test on a malware sample dumped from memory. (Please find attached a zip file containing this sample. Password - infected)

r2 'aac' detects - 799 functions
IDA - 289 functions
 
I was able to find one reason. Sometimes r2 consider text/garbage as code, and there may appear some weird instructions. For example:
`0x00402aee      9a80ff4d2d08.  lcall 8:0x2d4dff80`
Further r2 'aac' parse such calls and create functions even if a location cannot be resolved.
In IDA if I load this sample as PE file the behaviour is similar. However, IDA just ignore such addresses.

It is possible to fix this issue with fast workaround. Just add in libr/core/anal.c at the start of the r_core_anal_fcn:
`if(at < r_bin_get_baddr(core->bin))  return 0;`

After workaround r2 'aac' detects 521 functions.

Also, if I load this sample in IDA as a "Binary file" with correct offset such miss detections will not appear at all. Maybe, it is possible to introduce similar mode?

[citadel_d__0x00400000.zip](https://github.com/radare/radare2/files/269349/citadel_d__0x00400000.zip)

**Comment by XVilka** [comment]
It should be an option for sure. For firmware you can often can find a calls/jumps to 'illegal' memory, but it's just another binary/ROM/whatever.
