### ISSUE TITLE
wrong opcode 'or ecx, 0FFFFFFFFh'

### ISSUE THREAD

**Issue by StPanning** [radare/radare2#4938]
Hi all,
rasm2 produces the wrong opcode here:
The same happens in visual mode/ visual Assembly (A)

    rasm2 -b32 -a x86 'or ecx, 0xffffffff'
    09f1ff

    rasm2 -a x86 -b 32 -d '09f1ff'
    ecx, esi
    .byte 0xff 1

**Comment by radare** [comment]
Use -a x86.olly.

The default assembler is handmade and we add instructiins as soon as someone misses them. ill implement this instruction properly in the current default assembler and add tests for it too.

Anyway 0ffffffh is not a valid number anyway. You are mixing octal and hexa here. Use -1 or 0xffffffff instead

**Comment by StPanning** [comment]
Thanks for the heads up




On Wed, May 18, 2016 at 9:18 AM, radare <notifications@github.com> wrote:

> Use -a x86.olly.
>
> The default assembler is handmade and we add instructiins as soon as
> someone misses them. ill implement this instruction properly in the current
> default assembler and add tests for it too.
>
> Anyway 0ffffffh is not a valid number anyway. You are mixing octal and
> hexa here. Use -1 or 0xffffffff instead
>
>
>
> > On 18 May 2016, at 09:11, StPanning <notifications@github.com> wrote:
> >
> > Hi all,
> > rasm2 produces the wrong opcode here:
> > The same happens in visual mode/ visuaal Assembly (A)
> >
> > rasm2 -b32 -a x86 'or ecx, 0xffffffff'
> > 09f1ff
> > rasm2 -a x86 -b 32 -d '09f1ff'
> > ecx, esi
> > .byte 0xff 1
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/4938#issuecomment-219945800>
>



-- 
Immer wenn man die Meinung der Mehrheit teilt, ist es Zeit, sich zu besinnen
Mark Twain
