### ISSUE TITLE
couldn't find entry0

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#4945]
this is the problem
```
[0x00400208]> pd 10 @ entry0
            ;-- entry0:
            0x00400208      ff             invalid
            0x00400209      ff             invalid
            0x0040020a      ff             invalid
            0x0040020b      ff             invalid
            0x0040020c      ff             invalid
            0x0040020d      ff             invalid
            0x0040020e      ff             invalid
            0x0040020f      ff             invalid
            0x00400210      ff             invalid
            0x00400211      ff             invalid
[0x00400208]> afl
[0x00400208]> ie
[Entrypoints]
vaddr=0x00400410 paddr=0x00000208 baddr=0x00400208 laddr=0x00000000 type=program

1 entrypoints
[0x00400208]> iI
havecode true
pic      false
canary   false
nx       false
crypto   false
va       true
bintype  pe
class    PE32
arch     x86
bits     32
machine  i386
os       windows
minopsz  1
maxopsz  16
pcalign  0
subsys   Windows GUI
endian   little
stripped true
static   false
linenum  true
lsyms    true
relocs   true
binsz    6144
compiled Sun Jan  6 16:51:31 2008
hdr.csum 0x00001f9d
cmp.csum 0x00001d9b
crc32    0x00001f9d
crc32c   0x00001d9b

[0x00400208]> 

```
on the other hand this is results of IDA (thanks to @Maijin )
![disassembly](https://cloud.githubusercontent.com/assets/10424605/15370744/eb0c280e-1d40-11e6-9aff-72d416387040.jpg)
![entry point](https://cloud.githubusercontent.com/assets/10424605/15370745/eb27e742-1d40-11e6-9198-151a57fdc209.jpg)
![sections](https://cloud.githubusercontent.com/assets/10424605/15370746/eb41e02a-1d40-11e6-9a02-975edbee9123.jpg)

[infected.zip](https://github.com/radare/radare2/files/271109/infected.zip)
password is infected note that this file is malicious

**Comment by MariasStory** [comment]
Cool!
The same for me.
Just for information, it is an old sample (PoisonIvy Remote Access Trojan): https://www.virustotal.com/en/file/39028d975d4d05af21e2338ef8f6b4805bc781798f1d42d8d9c8f6ede372c739/analysis/1412946798/

The only thing working for me is izz

Whats going on?

**Comment by radare** [comment]
@skuater

**Comment by radare** [comment]
this is a problem with the sections. you can fix this by hand like this:

S-
S 0 0x00400000 $s $s blob mrwx

then the entrypoint will show the same output as IDA.

those sections are quite fuckedup, but i guess windows is able to load and run this, so we should understand how windows loads them and emulate the situation

**Comment by alvarofe** [comment]
the issue is with `vaddr` if you seek to `paddr` you will get the actual code, so for some reason r2/io is not mapping in the correct offset.

```
            0x00000208      b800044000     mov eax, 0x400400
            0x0000020d      ffd0           call eax
            0x0000020f      6a00           push 0
            0x00000211      e800000000     call 0x216                  ;[1]
            0x00000216      ff2500024000   jmp dword [sym.imp.kernel32.dll_ExitProcess] ; sym.imp.kernel32.dll_ExitProcess
```

**Comment by radare** [comment]
r2 is not mapping any section because the section info stored in the PE header is fuckedup, but is easy to fix by just adding the default mapping which is loading the entire bin at 0x400K

**Comment by alvarofe** [comment]
@oddcoder  `r2 -m 0x400000 infected`

**Comment by oddcoder** [comment]
why would I do `-m 0x400000` and how would I figure out that number

**Comment by alvarofe** [comment]
because if you use `iS`

```
idx=00 vaddr=0x00400002 paddr=0x00000002 sz=2 vsz=0 perm=m---x name=text
```
the vaddr is `paddr + 0x400000`

**Comment by oddcoder** [comment]
shouldn't that be done automatically ?

**Comment by alvarofe** [comment]
agree, but the sections as @radare said are fucked up and the code that handle this is not able to understand it. If the binary is capable to run we should format it correctly since the info is there

**Comment by skuater** [comment]
This binary is invalid in windows, seem be part of a injection into other process or a payload modified by the malware loader before launch.

This type of files dont need be manage as pe32/64. The best solution is load as raw file and adjust the dissasembler variables to show the correct instruction sizes. "e asm.bits=32".

**Comment by Maijin** [comment]
@skuater no need to do that with ida

**Comment by alvarofe** [comment]
first attempt to handle these cases

https://github.com/radare/radare2/pull/5135

as  i get new samples i will try to adapt the code and improve it

**Comment by Maijin** [comment]
Fixed !

**Comment by radare** [comment]
Awesome. Thanks alvaro!
