### ISSUE TITLE
some ESIL Issues

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#4952]
| Error | Opcode | ESIL |
| --- | --- | --- |
| ~~0x00402378 esil_diveq: empty stack~~| ~~idiv ebx~~ | ~~ebx,rax,/=~~ |
| 0x004026ed esil_eq: invalid parameters | adc al, 4 | 0,zf,=,cf,4,+,al,+,0,cf,=,DUP,0xff,<,?{,1,cf,=,},al,=,=,0xff,al,&,!,?{,1,zf,=,} |
| 0x0040297c esil_eq: invalid parameters | adc al, bl | 0,zf,=,cf,bl,+,al,+,0,cf,=,DUP,0xff,<,?{,1,cf,=,},al,=,=,0xff,al,&,!,?{,1,zf,=,} |
| 0x004054d5 esil_eq: invalid parameters | adc dword [esp + 0x1c], edi | 0,zf,=,cf,edi,+,0x1c,esp,+,[4],+,0,cf,=,DUP,0xffffffff,<,?{,1,cf,=,},0x1c,esp,+,=[4],=,0xffffffff,0x1c,esp,+,[4],&,!,?{,1,zf,=,} |
| 0x004054f5 esil_eq: invalid parameters | adc edx, edi | 0,zf,=,cf,edi,+,edx,+,0,cf,=,DUP,0xffffffff,<,?{,1,cf,=,},edx,=,=,0xffffffff,edx,&,!,?{,1,zf,=,} |
| 0x0040af1b esil_eq: invalid parameters | adc dword [esp + 4], edx | 0,zf,=,cf,edx,+,0x4,esp,+,[4],+,0,cf,=,DUP,0xffffffff,<,?{,1,cf,=,},0x4,esp,+,=[4],=,0xffffffff,0x4,esp,+,[4],&,!,?{,1,zf,=,} |
| 0x0040af23 esil_eq: invalid parameters | adc dword [esp + 4], -1 | 0,zf,=,cf,-1,+,0x4,esp,+,[4],+,0,cf,=,DUP,0xffffffff,<,?{,1,cf,=,},0x4,esp,+,=[4],=,0xffffffff,0x4,esp,+,[4],&,!,?{,1,zf,=,} |
| 0x0040d65d esil_eq: invalid parameters | adc dword [ecx + 0x224], edx | 0,zf,=,cf,edx,+,0x224,ecx,+,[4],+,0,cf,=,DUP,0xffffffff,<,?{,1,cf,=,},0x224,ecx,+,=[4],=,0xffffffff,0x224,ecx,+,[4],&,!,?{,1,zf,=,} |
| 0x0040d81e esil_eq: invalid parameters | adc dword [ecx + 0x224], edx | 0,zf,=,cf,edx,+,0x224,ecx,+,[4],+,0,cf,=,DUP,0xffffffff,<,?{,1,cf,=,},0x224,ecx,+,=[4],=,0xffffffff,0x224,ecx,+,[4],&,!,?{,1,zf,=,} |
| ~~0x0040f4d2 esil_diveq: empty stack~~ | ~~idiv dword [esp + 0x1d]~~ | ~~0x1d,esp,+,[4],rax,/=~~ |
| ~~0x0040f9b9 esil_div: default case~~ | ~~div ecx~~ | ~~ecx,eax,%,edx,=,ecx,eax,/,eax,=~~ |

**Comment by Maijin** [comment]
It would be much faster to have this in the error instead of just the offset...

**Comment by sushant94** [comment]
All the ones due to `adc` is cause ESIL string for `adc` has an extra `=`. I have fixed that in my PR but it isn't merged yet. I need to look into the rest of these issues.

**Comment by Maijin** [comment]
More 

| Error        | Opcode           | ESIL  |
| ------------- |-------------| -----|
esil_eq: invalid src references (aae)|ljmp [rsi - 7]|0x7,rsi,-,[10],rip,=
esil_eq: invalid src|lcall [rsi - 0x4e000009]|rip,8,rsp,-=,rsp,=[],0x4e000009,rsi,-,[10],rip,=
esil_eq: invalid src|lcall [rsi - 0x61000009]|rip,8,rsp,-=,rsp,=[],0x61000009,rsi,-,[10],rip,=
esil_eq: invalid src|lcall [rsi]|rip,8,rsp,-=,rsp,=[],rsi,[10],rip,=
esil_eq: invalid src|lcall [rsi - 0x5a000009]|rip,8,rsp,-=,rsp,=[],0x5a000009,rsi,-,[10],rip,=
esil_eq: invalid src|lcall [rsi + 0x63fffff7]|rip,8,rsp,-=,rsp,=[],0x63fffff7,rsi,+,[10],rip,=
esil_mem_inceq_n: invalid parameters|inc dword [rbx + rdi*8 - 0x4690001|0x4690001,rdi,8,*,rbx,+-,++=[4],$o,of,=,$s,sf,=,$z,zf,=,$p,pf,=
esil_eq: invalid src|lcall [rsi + 0x3effffff]|rip,8,rsp,-=,rsp,=[],0x3effffff,rsi,+,[10],rip,=
esil_eq: invalid src|lcall [rsi - 0x56000009]|rip,8,rsp,-=,rsp,=[],0x56000009,rsi,-,[10],rip,=
ESIL infinite loop detected|lea r14d, [r15*4]|r15,4,*,,r14d,=

**Comment by condret** [comment]
can we pls not use the ````<```` and ````>```` in esil anymore, we have ````==```` and internal vars for compares

**Comment by Maijin** [comment]
@ml86 can you check this issue and all the related opened esil issues like https://github.com/radare/radare2/issues/4344 and so on ? https://github.com/radare/radare2/issues?q=is%3Aopen+is%3Aissue+label%3Aesil

**Comment by Maijin** [comment]
lot of them has been fixed. Closing for now..
