### ISSUE TITLE
Temporary range operator

### ISSUE THREAD

**Issue by radare** [radare/radare2#4958]
Add @.. Modifier to change anal.from and search.from... To alow to run commands that affect a range of the memory. For example:

/v 0x1234 @..0x1000 0x3000

**Comment by XVilka** [comment]
May be better to use intervals? 
```
v 0x1234 @ 0x1000..0x3000
```

**Comment by radare** [comment]
I though the same syntax but..... U can use flags instead of numbers here and .. Is a valid string that can be in flag names. So i prefered to use the space char to differentiate that and define that range like the rest of @ commands

**Comment by radare** [comment]
related https://github.com/radare/radare2/issues/1476
