### ISSUE TITLE
Line wrapping fix needed for comments on Vv mode

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#4959]
The comment lines, if long enough difficult/mess the navigation on Vv mode:

![skarmavbild 2016-05-20 kl 16 38 08](https://cloud.githubusercontent.com/assets/175587/15431389/edc85e04-1ea9-11e6-9e90-dd2cc9804d1d.png)

**Comment by Maijin** [comment]
Why not just disable `e asm.describe` ?

**Comment by brainstorm** [comment]
Because those are still very useful when annotating/renaming functions via
(m). Cutting ends with "..." is faster and more practical that toggling
describe repeatedly.
