### ISSUE TITLE
Add support for luhn searching and hashing

### ISSUE THREAD

**Issue by radare** [radare/radare2#4965]
https://en.m.wikipedia.org/wiki/Luhn_algorithm

**Comment by m1ghtym0** [comment]
I've implemented the Luhn-Algo, but i'm not sure about the integration into rahash.
It doesn't really fit into the other hashing algos, as it doesn't have a fixed size or a real "hash" output. Including it into the other static algos like crc or md5 would require a lot of special cases, not sure if this is intended?

**Comment by Maijin** [comment]
Probably those:

```
/bin/ls: 0x00000000-0x0000966f hamdist: 01
/bin/ls: 0x00000000-0x0000966f pcprint: 1b
/bin/ls: 0x00000000-0x0000966f mod255: 98
/bin/ls: 0x00000000-0x0000966f xor: a1
/bin/ls: 0x00000000-0x0000966f xorpair: 9d3c
/bin/ls: 0x00000000-0x0000966f parity: 01
```
Are much closer to what you want.
