### ISSUE TITLE
r_num_math ignoring arguments and variables

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#4971]
this can appear clearly at `tp` command
`tp person = rbp - local_20h`
was parsed as if it was 
`tp person = rbp `
it did pass the full address `rbp - local_20h` to r_num_math but r_num_math ignored the `- local_20h` for some reason

**Comment by radare** [comment]
Because rnum cant parae local vars . Theres no such local_20h flag mainly because it is bound to the function context and rnum doesnt handle this.. And im
Not sure if we want to handle this with rnum

**Comment by oddcoder** [comment]
Why not ?
like if the required flag not available it will go and search tha vars/args of the current function

**Comment by radare** [comment]
for different reasons:

* performance (looking for function boundaries takes some time)
* reliability (dependong in seek, the same operation will have differnt results)
* rbp depends on program execution.

Maybe we should have a different function to do the rnummath with local var info, being able to specify regstate, which will be useful when going up/down in the stackframe list to get the values of the local variables when debugging.

**Comment by oddcoder** [comment]
probably this is fixed by now
