### ISSUE TITLE
eval command truncating binary to 8 bits

### ISSUE THREAD

**Issue by zlowram** [radare/radare2#4975]
The eval command truncates the binary to 8 bits, which gives wrong results.

Example:

```
[0x100001174]> ? 0x1234
4660 0x1234 011064 4.6K 0000:0234 4660 00110100 4660.0 0.000000f 0.000000
```

**Comment by radare** [comment]
Wat

**Comment by radare** [comment]
Ping

**Comment by radare** [comment]
@zlowram mind to fix this?

**Comment by crowell** [comment]
looks like r_str_bits is totally bokken. it's currently being passed sizeof(ut64), which is the size in bytes, so I changed it to sizeof(ut64) * 8, and it gives total garbage.

```
[0x004049de]> ? 0x1234
4660 0x1234 011064 4.6K 0000:0234 4660 0011010000010010000000000000000000000000000000000000000000000000 4660.0 0.
000000f 0.000000
```

I've rewritten it as `r_str_bits64` which works.

I dont know what `bitz` is so I haven't totally replaced the function. `r_str_bits64` can be used for any size number up to 64 by cutting off trailing 0's.

also im not quite sure what `?f` does so i left it be.
