### ISSUE TITLE
Keep color escape codes on

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2#4976]
Mentioned this to @XVilka on IRC, right now radare2 always turns off colors when it's piped to another program. It would be nice if there was an option to keep/force colors on.

![2016-05-23-01 08 04-screenshot](https://cloud.githubusercontent.com/assets/7232674/15457943/eb9dc7ce-2082-11e6-9cb7-fcd8f9bee6f8.png)

I was hoping to use [aha](https://github.com/theZiz/aha) to be able to export the colored disassembly to HTML.

**Comment by XVilka** [comment]
Something like `e io.esc_filter` option would be nice. If `true` - it will filter escape sequences from the piping and redirecting output, if `false` - obviously not.

**Comment by radare** [comment]
Maybe with || or something like this. I remember piping colors was really problematic in the past. Maybe we can enable it back and it will work fine now.

Need to test, but probably disabled by default and slowly testing it

**Comment by radare** [comment]
just use this var. it's documented in the source
```
       if (!r_config_get_i (core->config, "scr.pipecolor")) {
                pipecolor = r_config_get_i (core->config, "scr.color");
                r_config_set_i (core->config, "scr.color", 0);
        }
```
