### ISSUE TITLE
Reflines glitch - one more time

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4977]
![r2-reflines3](https://cloud.githubusercontent.com/assets/203261/15458587/29b3a4dc-20ad-11e6-9dc8-89b580480f80.png)

**Comment by radare** [comment]
Only when no function is defined . Right ?

**Comment by XVilka** [comment]
@radare yes.

**Comment by radare** [comment]
cant reproduce. please add a test case or something

**Comment by radare** [comment]
Ping

**Comment by radare** [comment]
HELLO?

**Comment by radare** [comment]
im gonna close this unless you show a way to reproduce this

**Comment by XVilka** [comment]
I wasn't able to reproduce it anymore, sadly. Closing for now.

**Comment by radare** [comment]
not being able to reproduce a bug is not something to be sad. cheers
