### ISSUE TITLE
r2 -A -c 'pD $SS@$S' alias? (objdump -d)

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2#4978]
Right now using r2 like `objdump -d` is a bit of a unintuitive, you have to do `r2 -A -c 'pD $SS@$S'` to disassemble a binary. Might be useful to have a shortcut for doing that? 

https://reverseengineering.stackexchange.com/questions/8568/how-do-you-tell-radare-to-do-a-full-dump-of-an-x86-binary

**Comment by radare** [comment]
you dont want to do this in r2 bwcause the pd loop does much more than just disassembling but foe small bins it will work


pD $SS@$S

**Comment by Manouchehri** [comment]
Thanks, changed the title.

**Comment by Maijin** [comment]
objdump doesn't do analysis at all so -A is irrelevant.

**Comment by Manouchehri** [comment]
True, but why wouldn't I want `-A` on? (Assuming I'm using a binary basic enough that using `objdump` is a valid alternative to begin with.)

```bash
root@0ee2daf87201:~# r2 -q -AA -c 'pD $SS@$S' /bin/true | wc -l
aav: using from to 0x400000 0x405970
Using vmin 0x400000 and vmax 0x605320
aav: using from to 0x400000 0x405970
Using vmin 0x400000 and vmax 0x605320
2567
root@0ee2daf87201:~# r2 -q -A -c 'pD $SS@$S' /bin/true | wc -l
2700
root@0ee2daf87201:~# r2 -q -c 'pD $SS@$S' /bin/true | wc -l
2409
```

**Comment by radare** [comment]
i dont get what’s the point on comparing r2 output with wc. what are you trying to achieve?

**Comment by Maijin** [comment]
ping @Manouchehri

**Comment by Manouchehri** [comment]
Not sure what the question really is. I just think a `pD $SS@$S` alias would be handy.

**Comment by zonkzonk** [comment]
redirecting stderr helps for one of the problems:

,r2 -q -A -c 'pD $SS@$S' /bin/true | wc -l
3083
, r2 -q -c 'pD $SS@$S' /bin/true | wc -l
2733
, r2 -q -c 'pD $SS@$S' /bin/true 2>/dev/null| wc -l
2733
