### ISSUE TITLE
Add support for ipa:// like there's already apk://

### ISSUE THREAD

**Issue by radare** [radare/radare2#4980]
Basically it must open as zip:// and then load the executable without having to unzip or so

**Comment by radare** [comment]
iOS apps can contain multiple binaries, not just the executable, also, libraries and extra binaries for extensions (watch, ...)

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/a7bfd9b76b93252d14671d7292fc2a64e1ebdf85
