### ISSUE TITLE
'izz' can't handle unicode names properly

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4996]
If open file in radare2 with unicode name, then using command that runs rabin2 through `r_sys_cmd_strf()` it can't open this file properly.
See http://xvilka.me/逆向工程

**Comment by XVilka** [comment]
It happens on Linux, but didn't happen on OSX

**Comment by radare** [comment]
imho its your terminal’s fault

**Comment by XVilka** [comment]
@crowell confirmed this issue on his computer too.

**Comment by alvarofe** [comment]
There is a TODO on the `izz` to use api instead of calling rabin2.

**Comment by radare** [comment]
Can we close this issue?

**Comment by alvarofe** [comment]
yes was done forgot to close it. thx
