### ISSUE TITLE
Option to enable view of unicode strings

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#4997]
1. Open this file http://xvilka.me/chinese
2. Go to the `sym.print_text`
3. `pd 5`

```
[0x00400460]> s sym.print_text
[0x00400556]> pd 5
                 ;-- print_text:
                 0x00400556      55             push rbp
                 0x00400557      4889e5         mov rbp, rsp
                 0x0040055a      bf04064000     mov edi, str.____________ ; str.____________
                 0x0040055f      e8ccfeffff     call sym.imp.puts
                 0x00400564      90             nop
[0x00400556]>
```

It would be nice to be able to see the content of this string. It is `逆向工程`
Something like `e asm.unicode=true` would be nice to have.

**Comment by crowell** [comment]
dup of https://github.com/radare/radare2/issues/926 ?

**Comment by Maijin** [comment]
Nop, but dup of https://github.com/radare/radare2/issues/2032

**Comment by oddcoder** [comment]
same for arabic
[arabic.tar.gz](https://github.com/radare/radare2/files/313631/arabic.tar.gz)

**Comment by radare** [comment]
lgtm

**Comment by radare** [comment]
not prio for this release. but nice to have it at some point

**Comment by radare** [comment]
please add a test case

**Comment by radare** [comment]
moving to 9999, faith under -90000

**Comment by XVilka** [comment]
@kazarmy this may be an interest of you

**Comment by kazarmy** [comment]
This is planned but it's still somewhere in the future.

**Comment by kazarmy** [comment]
Perhaps the option should be:

```
scr.strenc = utf8, raw, asciiesc, asciidot
```

where before display:
 - `utf8`: every string is converted to utf8
 - `raw`: no conversion done
 - `asciiesc`: every string is converted to ascii with non-ascii chars escaped
 - `asciidot`: every string is converted to ascii with non-ascii chars turned into a dot

Known ascii control chars are always escaped.

**Comment by kazarmy** [comment]
Maybe naming it as `scr.strdispmode` is better to prevent confusion with `asm.strenc`.

**Comment by radare** [comment]
Scr.strdispmode looks too long for me. I will think about the best name for this but the option seems doable. Thank you!

**Comment by kazarmy** [comment]
Wow Japanese @radare is so polite! :grinning:

**Comment by XVilka** [comment]
@cyanpencil check please also this one.

**Comment by XVilka** [comment]
Implemented with `e asm.flags.real = true`, disabled by default for now.
