### ISSUE TITLE
ESIL memory write issues with endianness and MIPS

### ISSUE THREAD

**Issue by mrmacete** [radare/radare2#4998]
The problems are various, and there are differences if architecture is MIPS, here are the cases:

case 1, MIPS (or non-mips actually), little endian: **everything's ok**:
```
$ r2 -a mips -
[0x00000000]> e cfg.bigendian=false
[0x00000000]> aeim
[0x00000000]> e io.cache=true
[0x00000000]> "ae 0x69686766,0x00100000,=[4]"
[0x00000000]> pxw 4@0x100000
0x00100000  0x69686766                                fghi            
[0x00000000]> 
```

case 2, MIPS big endian: **writes always zeroes**:
```
$ r2 -a mips -
[0x00000000]> e cfg.bigendian=true
[0x00000000]> aeim
[0x00000000]> e io.cache=true
[0x00000000]> "ae 0x69686766,0x00100000,=[4]"
[0x00000000]> pxw 4@0x100000
0x00100000  0x00000000                                ....            
[0x00000000]> 
```

case 3, non-MIPS big endian: **writes in little endian**:
```
$ r2 -
 -- The door controls time and space.
[0x00000000]> e cfg.bigendian=true
[0x00000000]> aeim
[0x00000000]> e io.cache=true
[0x00000000]> "ae 0x69686766,0x00100000,=[4]"
[0x00000000]> pxw 4@0x100000
0x00100000  0x66676869                                fghi            
[0x00000000]> 
```

i just made a PR on regressions with exactly the above cases (https://github.com/radare/radare2-regressions/pull/426)

**Comment by mrmacete** [comment]
the **case 3** i think it's because the default arch is x86 which doesn't support big endian in fact, so it seems safe to say that ESIL memory writes in big endian are writing zeroes

**Comment by radare** [comment]
can you confirm if this was working fine in 0.10.2 (before the big-endian patch)?

because i have noticed several other broken things after merging it

**Comment by mrmacete** [comment]
i'm not sure at the moment

**Comment by mrmacete** [comment]
placing a couple of `eprintf` i observed the problem: in the function `esil_poke_n` defined in `esil.c` there is this code:

```c
r_write_ble64 (b, num, esil->anal->big_endian);
ret = r_anal_esil_mem_write (esil, addr, b, bytes);
```

so, let's say i'm writing `0x69686766` poking `[4]` bytes, what happens is that my number is converted into the array `[0,0,0,0,0x69,0x68,0x67,0x66]` which is the correct way to layout a 64-bit little endian number into bytes, but.

but then, passing `bytes=4` to the  `r_anal_esil_mem_write` makes only the four most significant zeroes to be written in memory.

IMHO, one possible way to solve this is, for big endian, calling the write function like this:

```
ret = r_anal_esil_mem_write (esil, addr, b+(8-bytes), bytes);
```

**Comment by mrmacete** [comment]
another solution, maybe more generic, is to make a switch on `bytes` and use specific `r_write_bleXX`

**Comment by mrmacete** [comment]
made a PR, see if it's ok: https://github.com/radare/radare2/pull/5001
if exist other places in the code affected by the same problem, the same generic write function can be used
