### ISSUE TITLE
More memory efficient implementation of Levenshtein Distance in diff.c

### ISSUE THREAD

**Issue by NikolaiHampton** [radare/radare2#4999]
[diff.patch.txt](https://github.com/radare/radare2/files/281168/diff.patch.txt)

A patch for: ./libr/util/diff.c

To make it possible to do distance diffing on larger files.
Original version required matrix of ~ sizeof(fileA) * sizeof(fileB), the smaller implementation requires only ~ sizeof(fileB)*2.

Original needed 200GB to radiff2 -s busybox versions, vs about 460K now..
 
Implemented the "Iterative with Two Matrix Rows" algorithm for from here:
[Wikipedia](https://en.wikipedia.org/wiki/Levenshtein_distance
) and [CodeProject/Sten Hjelmqvist](http://www.codeproject.com/Articles/13525/Fast-memory-efficient-Levenshtein-algorithm)
My testing shows it working accurately with text files and with a 1K random binary file. i.e. it produces the same 'distance' and 'similarity' values.
Speed wise it seems similar:

```
$ time radiff2.orig -s a/nf_conntrack_ipsec.ko b/nf_conntrack_ipsec.ko
similarity: 1.00
distance: 20

real	0m0.577s
user	0m0.444s
sys	0m0.092s

 --------------------

$time radiff2.new -s a/nf_conntrack_ipsec.ko b/nf_conntrack_ipsec.ko
similarity: 1.00
distance: 20

real	0m0.526s
user	0m0.472s
```
Thanks,
Nikolai.

**Comment by radare** [comment]
Can you send a pull request for proper review and authoring? The speedup looks awesome!

Thanks

**Comment by NikolaiHampton** [comment]
Done. #5000
