### ISSUE TITLE
Ability to remap some offset in the file to the another address

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#500]
For example, we have file, with a size of 1Mb, and we have 0x350 offset in it, which is in fact mapping to the 0x0 address. So, we are should be able to open/create that virtual mapping without actually cutting this file

**Comment by condret** [comment]
@XVilka is it fixed now?

**Comment by XVilka** [comment]
Most probably yes.

**Comment by radare** [comment]
I think so.
