### ISSUE TITLE
Add support for temporarily referencing another fd

### ISSUE THREAD

**Issue by joelabr** [radare/radare2#5002]
A feature I would like to see implemented in radare2 is the possibility to reference another fd temporarily. The main reason I would like to have this feature is to make it easier to compare parts of files within radare2.

#### Example:
We have 2 files, file1 and file2. Both are opened in radare2. The fd of file2 is 9 in this example.
```
cc 0x100 @o:9:0x200!0x30
```
In the example above I want to compare a block of 0x30 bytes from 0x100, in the currently "active" file, with a block of the same size in file 2 (fd = 9) starting from address 0x200.

I used `@ o` in the example above. That's just something I chose when I wrote this. If there is a better way than this, feel free to suggest it. Maybe it would look better if the first colon was dropped (`@o9:0x200!0x30`)?

Anyways, that's my suggestion. I would love to see this feature implemented in radare2 in the future. Feel free to discuss the suggestion here.

**Comment by radare** [comment]
ping @jroimartin
