### ISSUE TITLE
separate the assembler from the disassembler in the config.

### ISSUE THREAD

**Issue by crowell** [radare/radare2#5005]
sometimes I want to use nasm as the assembler, but still use capstone as the disassembler. In this case, I have to do `e asm.arch = x86.nasm` do my assembly, and then switch back to `e asm.arch = x86`, it would be nice to have a second variable `asm.assembler` which can be set separate from the disassembler used.

**Comment by radare** [comment]
agree on that, we should have this done for 0.10.4 as long as it will be integrated with keystone and we dont want users to have problems with that.

**Comment by radare** [comment]
This is already fixed in master. See asm.assembler var
