### ISSUE TITLE
DWARF parser crash when parsing this ELF (fix included).

### ISSUE THREAD

**Issue by khrs** [radare/radare2#5013]
Hi,

DWARF parser dump core when parsing ELF generated by:
GCC: (GNU Tools for ARM Embedded Processors) 4.6.2 20120613 (release) [ARM/embedded-4_6-branch revision 188521]. File included.

After some debug session i have found than changing **DEBUG_ABBREV_CAP** (in file r_bin_dwarf.h) from **16** to **32** solve the problem.

[stm32.elf.zip](https://github.com/radare/radare2/files/283867/stm32.elf.zip)

**Comment by radare** [comment]
please send a pull req
