### ISSUE TITLE
Make 'dbc' work with flags

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5021]
It makes sense in various contexts. An example will suffice:

`[0x7f225d36e190]> db main`
`[0x7f225d36e190]> dbc main pd 10`
`No breakpoint defined at 0x00000000`

Of course, you could use `dbi` followed by `dbic`.

Would you find this useful or am I just being picky?

**Comment by radare** [comment]
it’s fixed now :)

thanks for reporting
