### ISSUE TITLE
problem buiding python bindings from sys/python.sh

### ISSUE THREAD

**Issue by Jegeva** [radare/radare2#5024]
with a fresh ./sys/install.sh
 sys/python.sh generates error messsages 

`r_core_wrap.cxx: In function 'RDiff* new_RDiff(long long unsigned int, long long unsigned int)':
r_core_wrap.cxx:7515:34: error: too many arguments to function 'RDiff* r_diff_new()'
return r_diff_new (off_a, off_b);`
...
`r_bin_wrap.cxx: In function 'RDiff* new_RDiff(long long unsigned int, long long unsigned int)':
r_bin_wrap.cxx:6194:34: error: too many arguments to function 'RDiff* r_diff_new()'
   return r_diff_new (off_a, off_b);`
...
`r_asm_wrap.cxx: In function 'RDiff* new_RDiff(long long unsigned int, long long unsigned int)':
r_asm_wrap.cxx:5215:34: error: too many arguments to function 'RDiff* r_diff_new()'
   return r_diff_new (off_a, off_b);`

`
$egrep -n 'r_diff_new\s+\(' radare2-bindings/python/*.i
radare2-bindings/python/r_asm.i:348:            return r_diff_new (off_a, off_b);
radare2-bindings/python/r_bin.i:542:            return r_diff_new (off_a, off_b);
radare2-bindings/python/r_core.i:1087:          return r_diff_new (off_a, off_b);
`

apparently there's something wrong with the swig interfaces (valabind generated i*think*) referencing  r_diff_new instead of  r_diff_new_from : 

`
$grep  'f_new' /usr/include/libr/r_diff.h
R_API RDiff *r_diff_new();
R_API RDiff *r_diff_new_from(ut64 off_a, ut64 off_b);`

**Comment by radare** [comment]
Fixed in caf24392a200d43323788d45210d74ace4f8f940

**Comment by radare** [comment]
also this issue is for the radare2-bindings repo, not radare2 one.

next time you can send a pullreq just editing the vapi file. see https://github.com/radare/radare2-bindings/commit/caf24392a200d43323788d45210d74ace4f8f940
