### ISSUE TITLE
Support color=auto like GNU tools

### ISSUE THREAD

**Issue by jduck** [radare/radare2#5038]
From the "ls(1)" man page:

```
Using color to distinguish file types is disabled both by default and with --color=never.  With --color=auto, ls emits color codes only when standard output is connected to a terminal.  The LS_COLORS
```

I'm not proposing adding these --long-options, but simply making the right decision based on terminal. There should (of course) be a way to force colors on (perhaps just be doing e scr.color=true after detection makes its determination).

**Comment by radare** [comment]
I think r2 users expext the output in color unless they want it otherwise. For grepping and such is a bit anoying to have colors, but thats up to the user. Also, detecting terminal is not always an easy task and most of the time serial consoles work with colors too.

Whats the benefit you see in adding this additional check?

You can just -e scr.color=false to disable this, the LS_COLORS doesnt define if the cklor is enabled or not. Its used to configure the color palete.

Do you have any real use case to see the current behaviour as a problem?

**Comment by jduck** [comment]
You called the biggest one - piping output on a shell / grepping. By forcing users to manually disable the color when not on a terminal, you're making more work for them. AFAIK this is against the philosophy of the project. I definitely like and appreciate the color, especially in interactive mode. Perhaps when using "-qi" and not on a terminal, we can default to color=false ?

**Comment by jduck** [comment]
Looks like #4976 is related, but does not have this problem.

**Comment by radare** [comment]
Colors are disabled if you use |

**Comment by jduck** [comment]
Yes, but only if you use | internally inside radare2. This ticket is more concerned with things like "r2 -d -qi script.r2 ls | grep ^0x"

**Comment by radare** [comment]
Yeah makes sense. But im afraid android will be black and white then. As well as some r2pipe methods and probably windows too

**Comment by jduck** [comment]
I suppose we just need some testing to find out. Can always override color handling in those cases too. For example,

```
if (!isatty(stdin) && (!windows && !android_app))
```

Perhaps this will not work (or maybe it's not worth it), but it's worth considering for the use on a UNIX command line use case.

See also http://stackoverflow.com/questions/1312922/detect-if-stdin-is-a-terminal-or-pipe-in-c-c-qt

**Comment by radare** [comment]
see r_cons_get_size implementation maybe we should split that code into r_cons_is_tty() and use that in the r2 initialization to disable colors unless the scr.pipecolor is true

wanna send a PR for this?

**Comment by radare** [comment]
tired of waiting https://github.com/radare/radare2/pull/5067
