### ISSUE TITLE
Ability to write/patch ESIL output.

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5044]
May be something like analysis hints but for ESIL output?
(should be stored in the project too).

**Comment by radare** [comment]
then use comments. otherwise it makes no sense

**Comment by radare** [comment]
can we close this? @sushant94 @condret

**Comment by condret** [comment]
i think we need to fix a lots of stuff in esil first

**Comment by condret** [comment]
@XVilka do you want to patch the esil for a single instruction or for all occurences of that instruction?

**Comment by Maijin** [comment]
I suppose @xvilka wants something like:

`| aho foo a0,33      replace opcode string` 

But for esil right ?

**Comment by XVilka** [comment]
Something like that, yes

**Comment by condret** [comment]
so what about ahoe for this?

**Comment by Maijin** [comment]
What is `ahe` btw?

**Comment by Maijin** [comment]
`ahe` already supposed to do that: https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3434

But doesn't work.

**Comment by radare** [comment]
Fixed in 3cd649559e2fcccb8d947fcd42f75a7537faa1d3
