### ISSUE TITLE
Breakpoint will not hit unless running r2 as root when io.cache=true

### ISSUE THREAD

**Issue by andreasur** [radare/radare2#5046]
**This seems to occur when `~/.radare2rc` has `e io.cache = true`**

When trying to debug a simple program e.g `/bin/ls` via

`r2 -d /bin/ls`

After analyzing via `aaa` I try to set breakpoints in visual mode via `F2` or `b` command by navigating to any address in cursor mode `c`

When I continue the execution via `dc` the breakpoints are not hit and the program exits. This doesn't happen if run as `root` e.g

`sudo r2 -d /bin/ls`

I am running Debian clean install

`#1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29)`

Radare2 version

    radare2 0.10.3 9999999 @ linux-x86-64 git.0.10.3
    commit: HEAD build: 2016-05-28

Built using `sys/install.sh`

**Comment by radare** [comment]
Do you get any error when doing db entry0?

**Comment by andreasur** [comment]
Nope, no errors

**Comment by andreasur** [comment]
As a side note, doesn't matter whether using `.radare2rc` or setting in console `e io.cache=true` while debug has started. After setting the io.cache breakpoints no longer hit unless running root

**Comment by jduck** [comment]
I can confirm. It seems the cache is not getting flushed correctly.

**Comment by radare** [comment]
ah, thats normal, didnt read the io.cache part.. the io.cache adds a layer to not modify the debugger process memory. the only breakpoints that will work in that mode are hardware and mmu based breakpoints, not software breakpointst that are the ones you are trying to use. so thats expected behaviour imho

**Comment by khrs** [comment]
So maybe we should print some message on startup if cfg.debug=true && io.cache=true I also had this problem when starting working with radare.

**Comment by radare** [comment]
and it works as root because your ~/.radare2rc is not loaded when running as root because root home is thanksfully not the same as your user

**Comment by radare** [comment]
why do you use io.cache? if you are starting to learn/use r2 dont enable options that you dont know what are they for, and dont enable them in your rc

**Comment by radare** [comment]
The io.cache doesnt flushes unless the user specifies this explicitly using the `wci` command. and i doubt anyone will be using it in addition to the debugger. this is imho not a bug, but just a bad usage /understanding of r2

**Comment by radare** [comment]
using io.cache with the debugger is useful for emulating code without trashing your current session. it is expected behaviour

**Comment by jduck** [comment]
I tried "wci" in this scenario and I only get:

```
[0x7fec072892d0]> wci
Error writing change at 0x00400630
```

This means "swstep" (the default is true) won't work and single stepping will run the entire program.

I think a warning is reasonable and prudent here. IMHO, R2's silence in general is very unhelpful to the newbie. I do like the silence though once I know what's going on.

**Comment by radare** [comment]
r2 tries to follow the unix rule of not showing anything unless there’s an error.

i dont see a reason why someone will enable io.cache at all without knowing what it he doing.

that warning will be pointless if the user knows what is he doing

**Comment by jduck** [comment]
It deserves a warning because it's a dangerous configuration if someone is analyzing malicious code. Also, see the following:

```
> e?io.cache
io.cache: Enable cache for io changes
```

This does not explain the ramifications of enabling the feature.

Is the expectation that new users will read the entire source code to understand every nuance before using radare2?

**Comment by jduck** [comment]
Perhaps only warning if io.cache is enabled when using the debugger...

**Comment by radare** [comment]
But i use iocache when i run esil on there to simulate changes in process memory without altering. Imho thats a corner case and a bad understanding of that feature

**Comment by radare** [comment]
R2 aims to be very ortogonal. This means that a single change in one option will affect other ones. This is good for some things, but bad for others, if we have to explain al the collateral effects of evrry single command or config var we will never end
