### ISSUE TITLE
Analysis (-AA) missing xrefs

### ISSUE THREAD

**Issue by jduck** [radare/radare2#5049]
See the following excerpt:

```
radare2/regressions$ r2 -A bins/elf/x64-fork-test -qc "axt sym.imp.exit"
call 0x400765 call sym.imp.exit in sym.child_proc
```

vs.

```
radare2/regressions$ r2 -AA bins/elf/x64-fork-test -qc "axt sym.imp.exit"
aav: using from to 0x400000 0x402d46
Using vmin 0x400000 and vmax 0x601080
aav: using from to 0x400000 0x402d46
Using vmin 0x400000 and vmax 0x601080
```

The same last line is expected in both cases.

**Comment by Manouchehri** [comment]
I'm having the same issue on a different binary too. ([Download link.](https://github.com/XVilka/hacklu/blob/master/IOLI-crackme/bin-linux/crackme0x07?raw=true))

```bash
root@edfca679119d:/angr-doc/examples/CSCI-4968-MBE/challenges# r2 -A crackme0x07/crackme0x07 -qc "axt sym.imp.exit"
call 0x804853d call sym.imp.exit in sub.printf_524
call 0x80485ab call sym.imp.exit in sub.sscanf_542
call 0x804866f call sym.imp.exit in sub.strlen_5b9
```

```bash
root@edfca679119d:/angr-doc/examples/CSCI-4968-MBE/challenges# r2 -AA crackme0x07/crackme0x07 -qc "axt sym.imp.exit"
0x080484a4 ESIL infinite loop detected
  
0x080484aa ESIL infinite loop detected

0x080484c4 ESIL infinite loop detected

0x080484d7 ESIL infinite loop detected  

0x08048743 ESIL infinite loop detected

0x08048749 ESIL infinite loop detected

aav: using from to 0x8048000 0x80496e4
Using vmin 0x8048000 and vmax 0x804a030
aav: using from to 0x8048000 0x80496e4
Using vmin 0x8048000 and vmax 0x804a030
```

**Comment by Manouchehri** [comment]
@jduck Weren't you saying that even `aaa` (`-A`) misses some xrefs over `aa` too?

**Comment by jduck** [comment]
@Manouchehri Yes, I believe "aa" == "-A" and "aaa" == "-AA"

**Comment by Manouchehri** [comment]
Nope.

**Comment by Manouchehri** [comment]
@Maijin changed that in #2641.

aaa == -A
aaaa == -AA

Yeah, I agree it's somewhat confusing.

**Comment by jduck** [comment]
Okay, strange. "aa" doesn't pick it up either, but I suppose that's expected since it doesn't do "aac".

**Comment by jduck** [comment]
Actually the xrefs come in from "aar". When I re-do the steps shown in the output from -AA I still see the xref, but not when using -AA on the command line and not when using "aaaa"

**Comment by Manouchehri** [comment]
Ah, so `aaa` is working, it's just `aaaa` that's broken.

**Comment by Manouchehri** [comment]
@jduck Don't know if this is useful or not, here's what `aaaa` does. (Might want to double check to make sure the output isn't hiding things from you.) 

https://github.com/radare/radare2/blob/4de809061a75e1018810443ebec52f13e538b001/libr/core/cmd_anal.c#L4069-4080

**Comment by jduck** [comment]
Unfortunately that doesn't really shed any light since doing what it does there still doesn't reproduce the issue :-/

**Comment by Maijin** [comment]
Have you tried launching the commands display in -A or -AA separately to see which of them are causing the problem?

**Comment by radare** [comment]
i wonder why those commands output anything at all. last argument must be filename, passing commandline flags after it it is not posix getopt and shouldnt work at all

**Comment by radare** [comment]
probably related https://github.com/radare/radare2/issues/4946

**Comment by radare** [comment]
Also the file `bins/elf/x64-fork-test` doesnt exists in the r2r repo. so i cant test even by passing the args in the correct order. but this issues doesnt suprise me at all. automatic analysis is doomed to fail. Read http://radare.today/posts/analysis-by-default/ for more information.

But the reason because this is happening is because some automated analysis commands change the function information and boundaries of previous analysis and sometimes producing wrong results, because not all automated analysis work fine in all archs/compilers/bins/etc.. the way to solve this is just adding `//`  in random lines in the `aa` command, to see which autoanalisis command is making this fail.

**Comment by Manouchehri** [comment]
@radare You can use this binary as well to test it.

https://github.com/XVilka/hacklu/blob/master/IOLI-crackme/bin-linux/crackme0x07?raw=true

**Comment by Manouchehri** [comment]
Want me to add the binary to r2r?

**Comment by XVilka** [comment]
Yes, please.

**Comment by Maijin** [comment]
Wait, check if is not the same as https://github.com/radare/radare2-regressions/tree/master/bins/elf/ioli

**Comment by Maijin** [comment]
@Manouchehri ping1

**Comment by Manouchehri** [comment]
@Maijin Yep, they're the same binary.

![image](https://cloud.githubusercontent.com/assets/7232674/18137242/96be83d2-6f75-11e6-9807-9edc80936232.png)

**Comment by Maijin** [comment]
dat troll.

**Comment by Manouchehri** [comment]
You haven't even seen my best yet.

Anyway, is there anything else I should do before forgetting about this
again?

**Comment by Maijin** [comment]
Just added tests, It's fixed, thanks !
