### ISSUE TITLE
Data Referenced Functions

### ISSUE THREAD

**Issue by jayint3z3r** [radare/radare2#5053]
I have tried using the aar command and I haven't been able to detect only data referenced functions. Is there any possible way to do this in radare2?

**Comment by radare** [comment]
Yes, there are many ways to do this in r2. But it depends on the targe architecture, the filetype, the compiler and how this thing is refenced.

I would blindly recommend you to use aav or aae, but having more details on the kind of binary will help

**Comment by radare** [comment]
Are u using r2 from git?

**Comment by jayint3z3r** [comment]
Yes, with but forked with some modifications I'm playing around with. I'm going to try out the aav and aae thanks.
