### ISSUE TITLE
s addr not kept when switching to visual mode for the first time while debugging

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5059]
A concrete example:

`r2 -Ad /bin/echo`
`[0x7f9c60465190]> s 0x00401473`
`[0x00401473]> V`
`[0x7f9c60465190 512 /bin/echo]> x @ rip`

However, if I quit visual mode and seek again afterwards, it works:

`q`
`[0x7f9c60465190]> s 0x00401473`
`[0x00401473]> V`
`[0x00401473 512 /bin/echo]> x @ main+147 # 0x401473`

Is this intended because r2 keeps track of eip?

**Comment by radare** [comment]
Thats what the cmd.visual says..

**Comment by monosource** [comment]
Look at the seek offsets at the end of both cases, not the visual command. That's the bug I'm referring to. Maybe I can do an ascii cast to show it better.

**Comment by radare** [comment]
No need for asciinema. I understand the issue. Its funny because some ppl complain about visual seeking to eip and others for not seeking there :p

**Comment by monosource** [comment]
Ah, I see now. Is there a config variable to change the default behavior?

**Comment by radare** [comment]
`e dbg.follow=0` should solve your issue

**Comment by monosource** [comment]
Yes, that fixes it. Thanks.
