### ISSUE TITLE
Add dependency checks to r2pm

### ISSUE THREAD

**Issue by zlowram** [radare/radare2#5062]
Make r2pm install fail if there are unmet dependencies

**Comment by crowell** [comment]
@zlowram just to be sure you mean things like checking that unicorn-lib is installed for unicorn, and not that thigns like glib-dev is installed for unicorn-lib. (the former sounds reasonable, the latter, out of scope imo).

**Comment by zlowram** [comment]
Yup, exactly. And that when installing radeco rust is installed, etc.

**Comment by crowell** [comment]
This issue was moved to radare/radare2-pm#6
