### ISSUE TITLE
ARM swp/swpb crashes when assembling with too few operands

### ISSUE THREAD

**Issue by endrift** [radare/radare2#5083]
When assembling the `swp`/`swpb` instruction using rasm2, if too few operands are provided to the instruction, rasm2 will crash when trying to fetch the operands.

Example invocation:
```
rasm2 -a arm 'swp r0'
```

**Comment by Maijin** [comment]
Have you tried with keystone plugin ?

**Comment by Maijin** [comment]
But yes segfault

**Comment by radare** [comment]
obviously no, this is an issue with armass.c . gimme 5m to fix it
