### ISSUE TITLE
rasm2 wrong code instead of error 

### ISSUE THREAD

**Issue by McLovi9** [radare/radare2#5085]
On invalid instruction rasm2 gives wrong code:

```
$ rasm2 -a arm -b16 "b lr"
fee7 -> b PC
```

Error message would be more desirable

**Comment by Maijin** [comment]
Can you add radare2-regressions test.

**Comment by McLovi9** [comment]
When I get more time I will add the test.

I've tried keystone no surprise "KsError: Cannot find a symbol (KS_ERR_ASM_SYMBOL_MISSING)"

**Comment by McLovi9** [comment]
well, actually I cannot at add radare2-regressions test cause that's invalid instruction so EXPECT output will not exist.

**Comment by Maijin** [comment]
? And how so you cannot create test on empty output ?

**Comment by Maijin** [comment]
Why closing ? 

```
NAME='Rasm2 b lr'
CMDS="!rasm2 -a arm -b16 'b lr'"
EXPECT=''
EXPECT_ERR='ERROR BLABLA'

run_test
```

so hard right ? 🐇

**Comment by McLovi9** [comment]
not hard but definitely frustrating when you just want to report the bug and someone expect you to know everything about the regression test inner working.

Anyways, I added the test.

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/README.md#writing-test-cases
