### ISSUE TITLE
binding for python double free?

### ISSUE THREAD

**Issue by cherry-wb** [radare/radare2#5086]
Hello everyone:

Is this a double free problem?

```
%extend RAnalBlock {
	~RAnalBlock() {
		r_anal_bb_free(self);
	}
};
%extend RAnalOp {
	~RAnalOp() {
		r_anal_op_free(self);
	}
};
%extend RAnalDiff {
	~RAnalDiff() {
		r_anal_diff_free(self);
	}
};
%extend RAnalFunction {
	std::vector<RAnalBlock> get_bbs() {
		std::vector<RAnalBlock> ret;
		RList *list;
		RListIter *iter;
		RAnalBlock *item;
		list = r_anal_fcn_get_bbs (self);
		if (list)
		for (iter = list->head; iter && (item = (RAnalBlock*)iter->data); iter = iter->n)
			ret.push_back(*item);
		return ret;
	}
```

The apis generated by valabind are as above, the returned  std::vector<RAnalBlock> obj in python is  a shallow copy, so the objs  pointed by pointers in the objs are not copyed, but when destroying, the de-constructer function will try to free memory regions that it does not own.
And this will cause a problem.
How can we solve this?

**Comment by radare** [comment]
This is not an issue in r2. The issue is for r2b
