### ISSUE TITLE
Project files do not keep asm.bits nor asm.arch

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5087]
Whenever I restart a project with radare, I have to re-set `asm.bits`:

```
$ grep asm.bits ~/.config/radare2/projects/ardrone_flash_blc
"e asm.bits = 8"
$ radare2 -p ardrone_flash_blc
[0x00000000]> e asm.bits
64
```

... and `asm.arch` (at least) to continue:

```
$ grep asm.arch ~/.config/radare2/projects/ardrone_flash_blc
"e asm.arch = avr"
$ radare2 -p ardrone_flash_blc
[0x00000000]> e asm.arch
x86
```

Also, it needs to be re-analyzed (`aaa`), etc... it would be nice if `radare -p project` just left the session as it was right before closing.

**Comment by radare** [comment]
works for me

**Comment by radare** [comment]
oh, doesnt works for me :D i have reproduced it after you gave me your project file. you can use -i for now

**Comment by brainstorm** [comment]
Glad to hear you could :) Using those flags currently, not sure it affects nor is related, but here you are:

```
mba-3:tmp romanvg$ cat ~/.radarerc
e asm.describe=true
e scr.utf8=true
e asm.midflags=true
e asm.emu=true
e asm.emustr=true
e io.va=true
e cfg.fortunetype = tips
eco solarized
```

~/.radarerc points to `.config/radare2`... so it's indeed an active rc file in my env.

**Comment by radare** [comment]
thanks!
