### ISSUE TITLE
Copy binary inside projects to make them self-distributable

### ISSUE THREAD

**Issue by radare** [radare/radare2#5089]
Also, it will be good to have a way (another command or so)

**Comment by Maijin** [comment]
pancake, [29.06.16 12:56]
inside .d

pancake, [29.06.16 12:56]
its just a stupid cp

pancake, [29.06.16 12:56]
r_file_copy()

**Comment by radare** [comment]
this is easy, but im not sure if we want to happen all the time. or only when the user wants
