### ISSUE TITLE
Flag functions without analyze

### ISSUE THREAD

**Issue by saidelike** [radare/radare2#5093]
I want to add symbols to a binary which is a 42MB ELF using ida-syms2elf (https://github.com/danigargu/ida-syms2elf). The recommend way is to analyse the binary, then flag functions but it doesn't work well with big binaries.

```
 $ radare2 lina
 -- See you in shell
[0x0804ea00]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x0804ea00]> aac
Segmentation fault (core dumped)
```

Would it be possible allow flag functions without analyze? Since I only need to flag functions then export the updated binary, I don't need to analyze it completely so would be worth having a workaround if possible ofc?

When working with a small binary it works fine:

```
$ radare2 normal_stripped
 -- In Soviet Russia, radare2 have documentation.
[0x08048350]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x08048350]> aac
[0x08048350]> afn level1 0x0804844B
[0x08048350]> afn level2 0x08048468
[0x08048350]> #!pipe python /home/user/.config/radare2/r2pm/git/ida-syms2elf/syms2elf.py normal_stripped_syms2elf
Exporting symbols to ELF...
0x080482d0 - 080482d0
0x08048350 - entry0
0x08048380 - 08048380
0x08048390 - 08048390
0x0804844b - level1
0x08048468 - level2
0x08048485 - 08048485
0x080484a2 - 080484a2
0x080484bf - 080484bf
0x080484dc - 080484dc
0x080484f4 - main
ELF saved to: normal_stripped_syms2elf
```

**Comment by saidelike** [comment]
This is a duplicate for https://github.com/radare/radare2/issues/5092

**Comment by radare** [comment]
maybe the way to go here would be to do the following:

* duplicate current anal->fcns
* run analysis commands
* restore the old anal->fcns

this way, the flags will be kept, but all function information will not be saved. the thing is that not saving function information will produce some analysis artifacts because of lack of information of other functions registered while performing the analysis.

**Comment by radare** [comment]
so im not sure if this functionality makes much sense

**Comment by radare** [comment]
we can also add a specific variants with `*` suffix to dump r2 commands like `a2f` do.

**Comment by Maijin** [comment]
aac* has been added #8455.
aa* should be fixed
aar* exists
aan* should be added
aat* should be added
aae* should be added
afta* should be added

I will open a new issue with this.
