### ISSUE TITLE
pxA _R undocumented

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5094]
```
[0x0040495c]> pxA?
Usage: pxA [len]   # f.ex: pxA 4K
 mv    move,lea,li
 ->    push
 <-    pop
 io    in/out ops
 $$    int/swi/trap/new
 ..    nop
 +-*/  math ops
 |&^   bin ops
 <<>>  shift ops
 _J    jump
 cJ    conditional jump
 _C    call
 ==    cmp/test
 XX    invalid
```

This is a very minor issue. _R stands for 'ret' instructions.

**Comment by Maijin** [comment]
U can fix it without even forking the project just with github web Interface, what about doing that instead of opening an issue?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/edit/master/libr/core/cmd_print.c#L3187

**Comment by monosource** [comment]
Thanks for the tip! Will fix minor issues directly from now on.
