### ISSUE TITLE
duplicated variable names

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#5096]
I was analysing the binary "alloca" from pwnable.kr

In the main function I got:
```
╒ (fcn) sym.main 435
│                  ; var int local_ch @ ebp-0xc
│                  ; var int local_4h @ ebp-0x4
│                  ; var int local_4h @ esp+0x4
│                  ; var int local_8h @ esp+0x8
│                  ; var int local_ch @ esp+0xc
```

as you can see there are multiple variables with the same name.
@oddcoder 

Update: the binary file ![alloca](https://cloud.githubusercontent.com/assets/562321/15872933/59f9f578-2cfc-11e6-8cbe-6cb4256cb559.png)

**Comment by oddcoder** [comment]
I cant get the binary
