### ISSUE TITLE
x86.nz assembler generates wrong opcode

### ISSUE THREAD

**Issue by j123123** [radare/radare2#5097]
testcase
```
$ rasm2 -a x86.as -b 64 'mov sil, 0'
40b600
$ rasm2 -a x86.nasm -b 64 'mov sil, 0'
40b600
$ rasm2 -a x86.ks -b 64 'mov sil, 0'
40b600
$ rasm2 -a x86.nz -b 64 'mov sil, 0'
ff00000000
```

disasm:
```
$ rasm2 -a x86 -b 64 -d '40b600'
mov sil, 0x0
$ rasm2 -a x86 -b 64 -d 'ff00000000'
inc dword [rax]
add [rax], al
invalid
```

**Comment by jjdredd** [comment]
use another assembler plugin, I don't think anyone's going to patch a x86 assembler

**Comment by Maijin** [comment]
@jjdredd ???? It's reguraly patch, maybe @j123123 you could patch it. 
@j123123 You can also try other assembler see list in `rasm2 -L` for example, with keystone, `r2pm -i keystone-lib && r2pm -i keystone`
@j123123 And Please add this test case in the https://github.com/radare/radare2-regressions

**Comment by radare** [comment]
Check the commit history in the nz.c and you will see thats not right. We are fixing and enhancing it all the time.

**Comment by j123123** [comment]
@Maijin testcase https://github.com/radare/radare2-regressions/pull/450/commits/816f29cdb29ece078be2e61bd12c0223d083e8eb

**Comment by Maijin** [comment]
@Svenito
