### ISSUE TITLE
[AFL] Crash in /libr/bin/p/bin_elf.c:load_bytes()

### ISSUE THREAD

**Issue by ekse** [radare/radare2#5103]
When dealing with core files,  /libr/bin/p/bin_elf.c:load_bytes() fails to validate that the return value of r_bin_elf_grab_regstate() is not null. radare then crashes when calling r_hex_bin2strdup with a null pointer for regs.

Relevant code:
https://github.com/radare/radare2/blob/master/libr/bin/p/bin_elf.c#L53

/libr/bin/p/bin_elf.c line 55
```c
		ut8 *regs = Elf_(r_bin_elf_grab_regstate)(res, &len);
		eprintf ("LEN = %d\n", len);
		char *hexregs = r_hex_bin2strdup (regs, len);
```

Crash file: https://www.dropbox.com/s/goayrlw6ygh3are/id%3A000000%2Csig%3A11%2Csrc%3A000000%2Cop%3Aflip1%2Cpos%3A4?dl=0

**Comment by crowell** [comment]
can't repro http://asciinema.org/a/bil8sv0wguovu1x76j1stx3gf

**Comment by alvarofe** [comment]
Me neither. I get the same output

```
mac:Downloads alvaro_fe$ r2 id-000000,sig-11,src-000000,op-flip1,pos-4
Warning: Cannot initialize program headers
Warning: Cannot initialize section headers
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
Cannot find NOTE section
LEN = 0
arw
 -- Save your projects with 'Ps <project-filename>' and restore then with 'Po <project-filename>'
[0xffffffffffffffff]>
```

**Comment by radare** [comment]
Are you using r2 from git?

**Comment by ekse** [comment]
Apologies, I did a build from git but it was still using system shared libraries from a previous version. Closing.
