### ISSUE TITLE
document all of libr

### ISSUE THREAD

**Issue by crowell** [radare/radare2#5112]
functions in libr are sometimes confusing. they should all have a short description, with inputs, outputs, and common caveats as well as unit tests.

**Comment by radare** [comment]
The idea of this was to put that documentstion in the vapi files so the bindings get documented too. Also, documenting implies reviewing all the apis and renaming functions, removing the unused, etc

Documentation shoukdnt be necessary if the function name is good enough imho.

**Comment by radare** [comment]
see make vdoc

**Comment by crowell** [comment]
distantspring tools/radare2 ‹master› » make vdoc
make: *** No rule to make target 'vdoc'.  Stop.


On Mon, Jun 13, 2016 at 4:13 PM, radare <notifications@github.com> wrote:

> see make vdoc
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/radare/radare2/issues/5112#issuecomment-225694321>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAlnYIUJGyYa78VZ4nqLeyWFf4lH2tTYks5qLbnTgaJpZM4IylDU>
> .
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
in the r2b repo

**Comment by Maijin** [comment]
No need an issue for that. It's known and it can't be tracked down as libr is huge, closing.

**Comment by Maijin** [comment]
tracked down individually on github*.
