### ISSUE TITLE
axf: XRefs from address is broken

### ISSUE THREAD

**Issue by abpolym** [radare/radare2#5113]
`axf` only shows xrefs from a function if you provide the address of the call instruction. This is not the same behaviour as pressing <kbd> shift </kbd> +<kbd>x</kbd> anywhere in the caller function to find all callees.

Testcase: https://transfer.sh/dg0aa/xreftestcaste (Note: File automatically deleted in 14 days)

Reproduce:
- Go into graph mode and enter main (`V @ sym.main` or `VV @ sym.main`)
- See some calls to functions from main , e.g. `sym.encrypt`, press <kbd> shift </kbd> +<kbd>x</kbd> to confirm these xrefs from main
- Type in `axf @ sym.main` (with or without `@`?), see an empty result
- Type in `axf @ 0x00400f22` to see that listing the xrefs from the main function only works if you provide the address of the call instruction (at `0x00400f22 <=> call sym.encrypt`

**Comment by radare** [comment]
s/ctrl//

**Comment by Maijin** [comment]
He meant UPPERCASE X

**Comment by radare** [comment]
can you write a test for r2r?

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t.anal/others_anal/xref

**Comment by crowell** [comment]
![xreftestcaste](https://cloud.githubusercontent.com/assets/616288/15983116/2fd980f8-2f6b-11e6-830c-27ff720f2e32.jpg)

so it wont get deleted in 15 days

**Comment by Manouchehri** [comment]
@crowell That image URL doesn't seem to work?

**Comment by radare** [comment]
It is not an image, it is the way we share files in r2land

**Comment by Maijin** [comment]
@abpolym ping ? 

```
can you write a test for r2r?

```

**Comment by abpolym** [comment]
@Maijin Ping didn't work - no mention on my frontpage :/. Never wrote a r2r test - can you point me to an example?

**Comment by Maijin** [comment]
You're kidding ? 
<img width="793" alt="screen shot 2016-06-21 at 19 01 47" src="https://cloud.githubusercontent.com/assets/1408600/16238893/a20e1128-37e2-11e6-8b7e-47d35cb262cd.png">

**Comment by radare** [comment]
See the radare2-regressions repo. Any of the files under t* will serve as an example

**Comment by Maijin** [comment]
@abpolym ping

**Comment by radare** [comment]
Please recheck and write tests

**Comment by dequis** [comment]
```
$ r2 -A bins/elf/ioli/crackme0x03
[...]
[0x08048360]> axt sym.shift
call 0x8048491 call sym.shift in sym.test
call 0x8048483 call sym.shift in sym.test
[0x08048360]> axf sym.test
d 0x8048474 mov eax, dword [ebp + 8]
d 0x8048477 cmp eax, dword [ebp + 0xc]
d 0x804848a mov dword [esp], str.Sdvvzrug_RN______
C 0x8048491 call sym.shift
d 0x804847c mov dword [esp], str.Lqydolg_Sdvvzrug_
C 0x8048483 call sym.shift
c 0x8048488 jmp 0x8048496
```

It's an improvement over empty output, but are ebp based arguments supposed to appear in axf?

(preparing a r2r pr right now)

**Comment by dequis** [comment]
```
[0x08048360]> axf sym.test
d 0x8048474 mov eax, dword [ebp + 8]
d 0x8048477 cmp eax, dword [ebp + 0xc]
d 0x804848a mov dword [esp], str.Sdvvzrug_RN______
C 0x8048491 call sym.shift
d 0x804847c mov dword [esp], str.Lqydolg_Sdvvzrug_
C 0x8048483 call sym.shift
c 0x8048488 jmp 0x8048496

[0x08048360]> ?v sym.test
0x804846e
[0x08048360]> ax ~0x804846e
ref.code.call.0x804850c=0x804846e
xref.code.call.0x804846e=0x804850c

[0x08048360]> axt str.Sdvvzrug_RN______
data 0x804848a mov dword [esp], str.Sdvvzrug_RN______ in sym.test

[0x08048360]> axf 0x804848a
d 0x8048474 mov eax, dword [ebp + 8]
d 0x8048477 cmp eax, dword [ebp + 0xc]
d 0x804848a mov dword [esp], str.Sdvvzrug_RN______
C 0x8048491 call sym.shift
d 0x804847c mov dword [esp], str.Lqydolg_Sdvvzrug_
C 0x8048483 call sym.shift
c 0x8048488 jmp 0x8048496

[0x08048360]> ax ~0x804848a
ref.data.mem.0x804848a=0x80485fe
xref.data.mem.0x80485fe=0x804848a
ref.code.jmp.0x804847a=0x804848a
xref.code.jmp.0x804848a=0x804847a
```

**Comment by radare** [comment]
Can we consider this issue fixed now that we have axf.?

**Comment by radare** [comment]
Related to https://github.com/radare/radare2/issues/5959

**Comment by alvarofe** [comment]
I would close. We have test and it works at least someone has a complain
