### ISSUE TITLE
trimbits is broken

### ISSUE THREAD

**Issue by megabug** [radare/radare2#5119]
The newly added `trimbits` (which is used for the `?` command) is broken:
* It doesn't handle input where the most significant bit is set (i.e. `-1`). It'll attempt to `memmove` a negative length of bytes, leading to segfault
* In other cases, the `memmove` can end up reading off the end of the input string. E.g., for input `"0000..0001"` (64-bit `1`), it'll end up `memmove`ing from offset 56 with a length of 57 bytes, which is clearly wrong

**Comment by Maijin** [comment]
```
--1 0xffffffffffffffff 01777777777777777777777 17179869184.0G fffff000:0fff -1 1111111111111111111111111111111111111111111111111111111111111111 -1.0 nanf nan
+-1 0xffffffffffffffff 01777777777777777777777 17179869184.0G fffff000:0fff -1 1111111111111111111111111111111111111111111111111111111111111111 -1.0 -nanf -nan
```

On linux, so it's not fixed

**Comment by radare** [comment]
What is not fixed?

**Comment by Maijin** [comment]
The added test pass on OSX, but not on Linux

**Comment by radare** [comment]
Thats libc fault

**Comment by megabug** [comment]
What about this: https://github.com/megabug/radare2-regressions/commit/75590b04ace043bea7fcd38cd4cfd3c61542ecc7
This tests trimbits while avoiding the libc differences (giving 0 as a float, and -2 as a double)

**Comment by radare** [comment]
it is fixed now
