### ISSUE TITLE
print format does not support 64bit enums

### ISSUE THREAD

**Issue by Lukas-Dresel** [radare/radare2#5121]
However, this is required by elf 64bit parsing.

Reproduce:
r2 radare2-regressions/bins/elf/x64-simple
pfo elf64
pf [3]? (elf_shdr)h @ 0xa8

Notice how the shdr's entsize overlaps with the next sections name

**Comment by Lukas-Dresel** [comment]
I have a fix ready, just testing if anything breaks

**Comment by Maijin** [comment]
do a Pull request and tests will be launched automatically

**Comment by radare** [comment]
can we have a test case for this too?

**Comment by Lukas-Dresel** [comment]
Done in radare2-regressions, at least the one i have should cover it. Might also want to make testcases for all the different format types.

**Comment by Lukas-Dresel** [comment]
Fixed in commit 8f6c4716e0b1272eebff9cb74c289b1033a6da9b
