### ISSUE TITLE
Lost E & F columns

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#5123]
Lost E & F columns in hex views :'(

```
:> px @ ebp-0x38
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  0123456789ABCD
0xfff983a0  0080 0000 00d0 72f7 28b2 72f7 d083  ......r.(.r...
0xfff983ae  0408 0100 0000 0000 0000 c883 f9ff  ..............
```

binary's arch: x86

![photo_2016-06-11_15-45-16](https://cloud.githubusercontent.com/assets/1186777/15985112/af3a34ca-2feb-11e6-91f0-7cd35d7c0047.jpg)

If restart r2 - columns is arrived

**Comment by radare** [comment]
Change console width. Change hex.cols or use [] keys to change that width... Or you can even use scr.responsive to make that automatic
