### ISSUE TITLE
esil->anal->big_endian is never being set

### ISSUE THREAD

**Issue by Lukas-Dresel** [radare/radare2#5124]
This is a regression.
With hardware breakpoints in gdb i can confirm that in normal analysis the esil->anal->big_endian is not being set, but is being used for example in the r_anal_esil_poke_n function. 

Is the mistake that it is not being set or should it use the sdb config's cfg.bigendian value?

Also, in libr/anal/esil.c there are cases where the esil->anal->big_endian is even commented out and hardcoded with 0 (false).

**Comment by radare** [comment]
probably a mistake or a regression. can you send a pullreq fixing it? im slowly trying to move to big-endian and setting up the environment at home for fixing all the endian issues we suffer now

**Comment by Lukas-Dresel** [comment]
Sure, but this issue is more of a question of how you want it fixed. Initialized as the value of cfg.bigendian? Or just use cfg.bigendian everytime?

**Comment by radare** [comment]
Esil->anal is the same as core->anal, and this bigendian thing is set at ranal.set_big_endian. Am i missing something?

**Comment by radare** [comment]
NOTABUG
