### ISSUE TITLE
Cannot insert asm command cbz

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#5125]
I try insert asm command (`a` and `A` keys) in Visual mode (Vp) + write mode for file (oo+).

Command `b address` is normally inserted:

![2016-06-12_14-46-13](https://cloud.githubusercontent.com/assets/1186777/15990988/09bbd75c-30ad-11e6-9c2b-8ef386cb8f31.png)

Command `cbz ` isn't:

![2016-06-12_14-47-00](https://cloud.githubusercontent.com/assets/1186777/15990990/0ceca744-30ad-11e6-8f67-0ba5c489ba3c.png)

Inserting hex `65b1` works:

![2016-06-12_14-58-04](https://cloud.githubusercontent.com/assets/1186777/15991012/161f757a-30ae-11e6-80d0-b38e57289075.png)

**Comment by radare** [comment]
Probably because cbz is not supported by the default assembler. Use keystone or implement it

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/commit/8a82e5cae6ef6b734194c063d98ced1d2c65eff9 will be merged when i finish all the arm analysis fixes im working on in the arm-fixes branch

**Comment by trufae** [comment]
fixed in master

**Comment by dukebarman** [comment]
Thx. It works!
