### ISSUE TITLE
support for MEGA OLD kernels

### ISSUE THREAD

**Issue by crowell** [radare/radare2#5131]
the new coredump stuff uses a ptrace api that was added in `2.6.34` (2010). is it safe to use this `PTRACE_GETREGSET` or should we use a workaround?

**Comment by radare** [comment]
we should have a workaround for older kernels

**Comment by radare** [comment]
cc @leberus

**Comment by leberus** [comment]
Ei! No problem, I'll add a workaround once I'm back from holydays (one week or so). Thanks for spotting that ;)

**Comment by radare** [comment]
thanks

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
```
prop:debug pancake$ grep -re PTRACE_GETREGSET *
p/native/linux/linux_coredump.c:        if (ptrace (PTRACE_GETREGSET, tid, (unsigned int)NT_PRXFPREG, &transfer) < 0) {
p/native/linux/linux_coredump.c:        if (ptrace (PTRACE_GETREGSET, tid, (unsigned int)NT_X86_XSTATE, &transfer) < 0) {
p/native/linux/linux_coredump.c:        if (ptrace (PTRACE_GETREGSET, pid, (unsigned int)NT_X86_XSTATE, &local) < 0) {
p/native/linux/linux_debug.c:                   ret = ptrace (PTRACE_GETREGSET, pid, NT_PRSTATUS, &io);
```

**Comment by leberus** [comment]
I'm on it, I will come back with something soon.
Thanks.

2016-06-25 3:23 GMT+02:00 radare <notifications@github.com>:

**Comment by radare** [comment]
i fixed it already

**Comment by leberus** [comment]
I'm sorry, I had some problems and I couldn't do it

**Comment by stacknip** [comment]
My build didn't work because the macro PTRACE_GETREGSET is not defined on my machine.
My machine:
$uname -r
3.16.0-0.bpo.4-686-pae

But PTRACE_GETREGS is defined on my machine, though.
To get it to build I changed PTRACE_GETREGSET to PTRACE_GETREGS in the file
./libr/debug/p/native/linux/linux_coredump.c
on line 907.

I'm not familiar with the code, I only know that I got it to build successfully now. Maybe I broke it, I don't know.
I only wanted to let you know that something was not right. And maybe this will help someone in the future.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by stacknip** [comment]
This is how it ends when I run the command ./sys/install.sh :

...
...
CC asm_z80_cr.c
CC asm.c
CC code.c
LD libr_asm.so
CC asm_propeller.c
CC propeller_disas.c
gcc: warning: /home/robert/git/extern/radare2/libr/../shlr/capstone/libcapstone.a: linker input file unused because linking not done
gcc: warning: /home/robert/git/extern/radare2/libr/../shlr/capstone/libcapstone.a: linker input file unused because linking not done
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by stacknip** [comment]
The next logical step (to me) was to do make in the root of the project.
$ make

...
...
cd capstone && CFLAGS="-Dmips=mips -g  -MD    -fPIC -g -Wall -D__UNIX__=1 -MD" LDFLAGS="-Wl,--as-needed -Wl,--as-needed" \
                make CC="gcc" AR_EXT=a IS_CYGWIN=0 CAPSTONE_STATIC=yes CAPSTONE_SHARED=no \
                RANLIB="ranlib" AR="ar" IS_MINGW=0 libcapstone.a
make[2]: Entering directory `/home/robert/git/extern/radare2/shlr/capstone'
  CC      arch/X86/X86IntelInstPrinter.o
arch/X86/X86IntelInstPrinter.c:1075:0: fatal error: opening dependency file arch/X86/X86IntelInstPrinter.d: Permission denied
compilation terminated.
make[2]: *** [arch/X86/X86IntelInstPrinter.o] Error 1
make[2]: Leaving directory `/home/robert/git/extern/radare2/shlr/capstone'
make[1]: *** [capstone-build] Error 2
make[1]: Leaving directory `/home/robert/git/extern/radare2/shlr'
make: *** [all] Error 2


Permission denied, no problem:
$sudo make

...
...
gcc -c  -MD   -fPIC -g -Wall -D__UNIX__=1 -DCORELIB -Ip/libbfwbf/include -I/home/robert/git/extern/radare2/libr/../shlr/bochs/include/ -I/home/robert/git/extern/radare2/libr/../shlr/gdb/include/ -I/home/robert/git/extern/radare2/libr/../shlr/qnx/include/ -Ip/librapwrap/include -I/home/robert/git/extern/radare2/libr/../shlr/wind/ -DXNU_USE_PTRACE=0 -I../bin/format/elf -I/home/robert/git/extern/radare2/libr/include -o p/native/linux/linux_coredump.o p/native/linux/linux_coredump.c
p/native/linux/linux_coredump.c: In function ‘linux_get_fpx_regset’:
p/native/linux/linux_coredump.c:905:14: error: ‘PTRACE_GETREGSET’ undeclared (first use in this function)
p/native/linux/linux_coredump.c:905:14: note: each undeclared identifier is reported only once for each function it appears in
make[4]: *** [p/native/linux/linux_coredump.o] Error 1
make[4]: Leaving directory `/home/robert/git/extern/radare2/libr/debug'
make[3]: *** [foo] Error 2
make[3]: Leaving directory `/home/robert/git/extern/radare2/libr/debug'
make[2]: *** [debug] Error 2
make[2]: Leaving directory `/home/robert/git/extern/radare2/libr'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/robert/git/extern/radare2/libr'
make: *** [all] Error 2

Ok, some more info.
It says something about PTRACE_GETREGSET undeclared.
Looking at:
./libr/debug/p/native/linux/linux_coredump.c
on line 905:
	if (ptrace (PTRACE_GETREGSET, tid, (unsigned int)NT_PRXFPREG, &transfer) < 0) {

This is within a macro conditional #if __i386__
This is a predefined macro and gcc sets this macro to 1.

Changine PTRACE_GETREGSET to PTRACE_GETREGS makes a successful build possible.

**Comment by Maijin** [comment]
then make a PR, you can even do that with the Pencil on github.

**Comment by stacknip** [comment]
Ok

**Comment by leberus** [comment]
I'll take a look tomorrow

El dia 16/08/2016 22:29, "stacknip" <notifications@github.com> va escriure:
