### ISSUE TITLE
Encrypt/Sign projects

### ISSUE THREAD

**Issue by radare** [radare/radare2#5132]
In order to protect DMCA, NDAs and other uppercase words

**Comment by Manouchehri** [comment]
Maybe use GPGme?

https://www.gnupg.org/(es)/related_software/gpgme/index.html

**Comment by radare** [comment]
no.i think its better to relay on spawning gpg2 or gpg is not found. This will
be a runtime dependency rather than a compile time option.  
  
Sent from [Nylas N1](https://link.nylas.com/link/554pmnmrff6ngsy16f869qgd2
/local-196ddc4e-
cd1d/0?redirect=https%3A%2F%2Fnylas.com%2Fn1%3Fref%3Dn1&r=cmVwbHkrMDAwZGZlOTY4MzNkZDEyZTMzZDRjYjY4MTk4YjI3OTUxNzgxNDIzMzFjMzkyOGNhOTJjZjAwMDAwMDAxMTM3OGEzNmM5MmExNjljZTA5OGIzYzllQHJlcGx5LmdpdGh1Yi5jb20=),
the extensible, open source mail client.  
![](https://link.nylas.com/open/554pmnmrff6ngsy16f869qgd2/local-196ddc4e-
cd1d?r=cmVwbHkrMDAwZGZlOTY4MzNkZDEyZTMzZDRjYjY4MTk4YjI3OTUxNzgxNDIzMzFjMzkyOGNhOTJjZjAwMDAwMDAxMTM3OGEzNmM5MmExNjljZTA5OGIzYzllQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 15 2016, at 7:02 am, David Manouchehri &lt;notifications@github.com&gt;
wrote:  

> Maybe use GPGme?

>

>
[https://www.gnupg.org/(es)/related_software/gpgme/index.html](https://www.gnupg.org/\(es\)/related_software/gpgme/index.html&r=cmVwbHkrMDAwZGZlOTY4MzNkZDEyZTMzZDRjYjY4MTk4YjI3OTUxNzgxNDIzMzFjMzkyOGNhOTJjZjAwMDAwMDAxMTM3OGEzNmM5MmExNjljZTA5OGIzYzllQHJlcGx5LmdpdGh1Yi5jb20=)

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/radare/radare2/issues/5132#issuecomment-226088566&r=cmVwbHkrMDAwZGZlOTY4MzNkZDEyZTMzZDRjYjY4MTk4YjI3OTUxNzgxNDIzMzFjMzkyOGNhOTJjZjAwMDAwMDAxMTM3OGEzNmM5MmExNjljZTA5OGIzYzllQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AA3-lqdz9qCHR3I29CeO5FidAP9K1PKqks5qL4dsgaJpZM4I1DrN&r=cmVwbHkrMDAwZGZlOTY4MzNkZDEyZTMzZDRjYjY4MTk4YjI3OTUxNzgxNDIzMzFjMzkyOGNhOTJjZjAwMDAwMDAxMTM3OGEzNmM5MmExNjljZTA5OGIzYzllQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AA3-lnw5jTOFmTbK2-VWQbQJO5iY3fNQks5qL4dsgaJpZM4I1DrN.gif)

**Comment by crowell** [comment]
i dont really see what the point of this in r2 is? sharing project files? this doesn't really make sense to me.

**Comment by brainstorm** [comment]
It does to other people:

https://recon.cx/2016/talks/Sol-IDA-rity.html

Think cloud.radare and teams reversing a potentially big binary.

**Comment by XVilka** [comment]
@brainstorm for that kind of collaboration realtime is better, this could be much easier if [sdbtization](https://github.com/radare/radare2/labels/sdbtization) is completed.

**Comment by Maijin** [comment]
Tracked here https://github.com/radare/radare2/issues/6945
