### ISSUE TITLE
Support (automatic?) versioning/backups of projects

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5141]
In order to avoid situations like that in #5140... also I would suggest to remove the `"Do you want to save the 'name_of_project' project? (Y/n)"` if on-disk changes are already in sync with the active session (i.e `Ps name_of_project` issued in-session right before quitting).

**Comment by radare** [comment]
how do you know if the project is already in sync with r2 state? :P

**Comment by brainstorm** [comment]
Meh, then "just" backups/versioning ;)

**Comment by radare** [comment]
Git? :p

**Comment by brainstorm** [comment]
Yep, wrapped under the `P` command... come on, @radare, even bioinformatic pipelines have this stuff ;)

http://www.nextflow.io/blog/2014/share-nextflow-pipelines-with-github.html

Also the UNIX password manager:

https://www.passwordstore.org/

**Comment by crowell** [comment]
https://libgit2.github.com

**Comment by brainstorm** [comment]
I'm with pancake here regarding this: not using libs, but going for runtime dependencies. That is, like in #5132, use gpg/gpg2 binary instead of linking against libgit2.

Makes sense?

**Comment by Manouchehri** [comment]
Time stamping versions could be useful as well. Lots of free RFC3161 servers.

https://unmitigatedrisk.com/?p=395

**Comment by Manouchehri** [comment]
Actually, why isn't RFC3161 timestamping built into Git...?

**Comment by brainstorm** [comment]
Another "feature"/tweak I realized: It would be nice to have the project directories self-contained in a single project directory. As it is now:

```
mba-3:projects romanvg$ pwd
/Users/romanvg/.config/radare2/projects
mba-3:projects romanvg$ ls -alh
total 544
drwxr-xr-x  6 romanvg  staff   204B  6 Aug 20:05 .
drwxr-xr-x  7 romanvg  staff   238B  6 Jun 17:20 ..
-rw-r--r--  1 romanvg  staff    32K  2 Sep 17:41 ardrone_flash_blc
drwxr-xr-x  4 romanvg  staff   136B  2 Sep 17:41 ardrone_flash_blc.d
-rw-r--r--  1 romanvg  staff   232K 14 Jun 12:31 ardrone_program.elf.radare
drwxr-xr-x  3 romanvg  staff   102B 14 Jun 12:31 ardrone_program.elf.radare.d
```

If those flatfiles were already inside the `.d`'s, I could just do a `git init` and we would be totally ready to go.

@radare Any reason for keeping those separate and not all in the same project directory?

**Comment by brainstorm** [comment]
Another "feature"/tweak I realized: It would be nice to have the project directories self-contained in a single project directory. As it is now:

```
mba-3:projects romanvg$ pwd
/Users/romanvg/.config/radare2/projects
mba-3:projects romanvg$ ls -alh
total 544
drwxr-xr-x  6 romanvg  staff   204B  6 Aug 20:05 .
drwxr-xr-x  7 romanvg  staff   238B  6 Jun 17:20 ..
-rw-r--r--  1 romanvg  staff    32K  2 Sep 17:41 ardrone_flash_blc
drwxr-xr-x  4 romanvg  staff   136B  2 Sep 17:41 ardrone_flash_blc.d
-rw-r--r--  1 romanvg  staff   232K 14 Jun 12:31 ardrone_program.elf.radare
drwxr-xr-x  3 romanvg  staff   102B 14 Jun 12:31 ardrone_program.elf.radare.d
```

If those flatfiles were already inside the `.d`'s, I could just do a `git init` and we would be totally ready to go.

@radare Any reason for keeping those separate and not all in the same project directory?

**Comment by Maijin** [comment]
Duplicate message

**Comment by radare** [comment]
The reason was for backward comptibility and be able to consider a script a project.

**Comment by brainstorm** [comment]
ln -sf'ing that outside file in the `.d` directory for now then ;)
