### ISSUE TITLE
Register names should be case-insensitive

### ISSUE THREAD

**Issue by jduck** [radare/radare2#5156]
Back in 5c99eb0 we changed register alias names to use uppercase. IMHO they should be case-insensitive. It's pretty annoying to have to type them in uppercase all the time and changing case like this could also cause breakage in various parts of the code.

**Comment by radare** [comment]
The reeason behind this is that uppercase registers are aliases, not real hardware registers. If we use pc instead of PC or A0 for r0 it will conflict with the real register which can be mapped somewhere else.

**Comment by jduck** [comment]
I understand the semantics but not the desire to differentiate them =)

**Comment by radare** [comment]
imho nope
