### ISSUE TITLE
Memory leak when running 'aac' or 'aap'

### ISSUE THREAD

**Issue by axt** [radare/radare2#5165]
I've tried to run 'aac' on a 18Mb PE32 binary using the current `master` and it eat up all the memory available (24GB). The same command using 'radare-0.10.3' uses only 1GB.

Bisected it to this commit : 000c6023488f8fa4b08816dc326ac3388911c75a

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
Can you share the binary ?

**Comment by Maijin** [comment]
and/or give more details like valgrind logs ?

**Comment by axt** [comment]
Unfortunatelly I can't share the binary. I can create valgrind logs, but only on next week because I will be off for the weekend. But, I've tried to fix the problem + sent a pull-request, with some description.

**Comment by radare** [comment]
The fix you suggested looks good to me. Just waiting for travis to be green to merge.

After this patch, how much memory is required? Did you find more leaks in aac/aae/af?

Thanks!

**Comment by axt** [comment]
After the patch the memory footprint is the same as before the leak, so back to 1GB again.

There are some minor leaks (1 leak / command execution) in core, but didn't know how to fix them, since the `r_anal_var_free` method is not visible in the `core` module, by the linker.

This is the not applied diff of them:

```diff
diff --git a/libr/core/cmd_anal.c b/libr/core/cmd_anal.c
index 055a18c..84be1d2 100644
--- a/libr/core/cmd_anal.c
+++ b/libr/core/cmd_anal.c
@@ -157,7 +157,7 @@ static int var_cmd(RCore *core, const char *str) {
                                v1 = r_anal_var_get_byname (core->anal, fcn, 'v', new_name);
                        }
                        if(v1) {
-                               free (v1);
+                               r_anal_val_free (v1);
                                eprintf("variable or arg with name `%s` already exist\n", new_name);
                                break;
                        }
diff --git a/libr/core/cmd_meta.c b/libr/core/cmd_meta.c
index 78b52b0..145cd5a 100644
--- a/libr/core/cmd_meta.c
+++ b/libr/core/cmd_meta.c
@@ -624,6 +624,7 @@ void r_comment_vars (RCore *core, const char *input) {
                var = r_anal_var_get_byname (core->anal, fcn, input[0], name);
                if (var) {
                        idx = var->delta;
+                       r_anal_var_free (var);
                } else if (!strncmp (name, "0x", 2))  {
                        idx = (int) r_num_get (NULL, name);
                } else if (!strncmp (name, "-0x", 3)) {
@@ -656,6 +657,7 @@ void r_comment_vars (RCore *core, const char *input) {
                var = r_anal_var_get_byname (core->anal,fcn, input[0], name);
                if (var) {
                        idx = var->delta;
+                       r_anal_var_free (var);
                } else if (!strncmp (name, "0x", 2)) {
                        idx = (int) r_num_get (NULL, name);
                } else if (!strncmp (name, "-0x", 3)) {
@@ -685,7 +687,7 @@ void r_comment_vars (RCore *core, const char *input) {
                        r_meta_set_var_comment (core->anal, input[0], var->delta, fcn->addr, comment);
                        free (comment);
                }
-               free (var);
+               r_anal_var_free (var);
                }
                break;
        }
```

**Comment by radare** [comment]
Awesome! Cc @oddcoder , review those changes so next time we will try to be more careful about those kind of issues.

Thanks

**Comment by axt** [comment]
I've tried to find a publicly available binary which shows the problem. (Its the latest TOTALCMD.EXE)

```
$ git reset --hard 000c6023488f8fa4b08816dc326ac3388911c75a
$ git clean -f 
$ make clean all 
$ sudo make purge 
$ sudo make install
$ r2 -V
0.10.3-120-g000c602  r2
$ r2 TOTALCMD.EXE
[0x007066ec]> aac
```
```
$ ps aux |grep r2
axt       3904 0.0  0.0 763692 685972 pts/20  S+   19:19  11:59 r2 TOTALCMD.EXE```
```

```
$ git reset --hard 31c4c89e9f3bdac913762133eeb33b03abbb1d63
$ git clean -f 
$ make clean all 
$ sudo make purge 
$ sudo make install
$ r2 -V
0.10.3-119-g31c4c89  r2
$ r2 TOTALCMD.EXE
[0x007066ec]> aac
```
```
$ ps aux |grep r2
axt       14478 0.0  0.0 284584 206840 pts/20  S+   19:45  9:53 r2 TOTALCMD.EXE```
```

As you can see, the memory usage in the second case is ~200MB, while in the first case its ~680MB.
(But I have a binary, for which in the second case its around ~1GB, while the first can't finish with 24GB of ram)

(For me it seems, that the memory is leaked in `r_anal_var_get_byname` by `r_anal_var_list`, because its result is never freed. When I've patched that, the leak disappeared, but it caused other problems with variable nameing.)

Here is the sample binary:
[TOTALCMD.ZIP](https://github.com/radare/radare2/files/322435/TOTALCMD.ZIP)

**Comment by radare** [comment]
can someone confirm is this still happening after last @oddcoder merge?

**Comment by Maijin** [comment]
This binary is taking age to get aac finished oO

**Comment by axt** [comment]
It got better (~310Mb) than it was (~680Mb), but still worst than 0.10.3 (~200Mb).
```
 $ ps aux |grep r2
axt      25705 98.3  3.8 388584 310680 pts/25  S+   17:46  11:00 r2 TOTALCMD.EXE
```

I will run it on my original binary, with the 1GB->24GB+ increase, but that runs for several hours.

**Comment by Maijin** [comment]
Is it still related to arguments stuff ?

**Comment by axt** [comment]
@Maijin if your question is addressed to me, i don't understand. Can you explain, what do you mean?

**Comment by Maijin** [comment]
Yes, question is, does the issue still concern `anal_var` or related ?

**Comment by axt** [comment]
I'm not familiar with the codebase, so maybe I'm wrong, but it seems to me, that although the variables are now freed, the list support structure (which holds the next pointers) itself is stil leaked.

```diff
diff --git a/libr/anal/var.c b/libr/anal/var.c
index 4cda25c..6ee9c29 100644
--- a/libr/anal/var.c
+++ b/libr/anal/var.c
@@ -229,16 +229,19 @@ R_API bool r_anal_var_delete_byname (RAnal *a, RAnalFunction *fcn, int kind, con
 R_API RAnalVar *r_anal_var_get_byname (RAnal *anal, RAnalFunction *fcn, char kind, const char* name) {
        RList *var_list;
        RListIter *iter;
-       RAnalVar *var = NULL;
+       RAnalVar *var = NULL, *itervar;
        if (!fcn || !anal || !name) {
                return 0;
        }
        var_list = r_anal_var_list (anal, fcn, kind);
-       r_list_foreach (var_list, iter, var) {
-               if (!strcmp (name, var->name)) {
-                       break;
+       r_list_foreach (var_list, iter, itervar) {
+               if (!strcmp (name, itervar->name)) {
+                       var = itervar;
+               } else {
+                       r_anal_var_free (itervar);
                }
        }
+       free (var_list);
        if (!var || strcmp (name, var->name)) {
                return 0;
        }
```

(The analysis on the original file is at ~2.3G right now. Probably it will go higher than this. I will get back with the exact value, if it finishez (~2hours), or if it eats up all of my RAM.)

**Comment by axt** [comment]
I've interrupted `aac` after 100 mins, during this it consumed 6.8GB of RAM, so I think that prooves, that the leak still exists.
```
$ cat /proc/`pgrep r2`/status |grep -E 'VmSwap|VmRSS'
VmRSS:	 4523040 kB
VmSwap:	 2316636 kB
```

**Comment by alvarofe** [comment]
Here valgrind output 

![leak-r2](https://cloud.githubusercontent.com/assets/3474042/16210748/ef6b553e-373d-11e6-8024-b775c21d93bc.png)

**Comment by radare** [comment]
I did a tiny change in aac. Can you retry and see the memory diff?

**Comment by axt** [comment]
After 20 mins of running it consumed 4GB of memory, so the problem still exists.
```
r2 -V
0.10.3-331-gc145740  r2
```

**Comment by Maijin** [comment]
any valgrind logs or something ?

**Comment by radare** [comment]
0.10.3 is very old

**Comment by Maijin** [comment]
use r2 from git please...

**Comment by axt** [comment]
Its built from the latest git version (with clean all purge install), and if I run it with `-v`, it displays this:
```
 ./r2 -v
radare2 0.10.4-git 11725 @ linux-x86-64 git.0.10.3-331-gc145740
commit: c1457400308a98f88bed2a4b8f5b533f12dc8a77 build: 2016-06-26
```
Is that ok? Or is there a way to upgrade the `lib version` too?

**Comment by axt** [comment]
Since this code is generating that version number, and `0.10.3` is the latest tag in the repository, I assume my build of `r2` is the latest and its correct.
```
.PHONY: libr/include/r_version.h
GIT_TAP=$(shell git describe --tags --match "[0-9]*" 2>/dev/null || echo $(VERSION))
GIT_TIP=$(shell git rev-parse HEAD 2>/dev/null || echo HEAD)
GIT_NOW=$(shell date +%Y-%m-%d)
```

@Maijin: Someone has attached valgrind logs, and since the bug still occurs, they should be still reliable.

I still think, this is causing the leak in `r_anal_var_get_byname`, since it doesnt free the support structure (next pointers) of the list:
```c
free (var_list);
```

**Comment by alvarofe** [comment]
@axt try with this PR to see if it improves. Along this week i will try to reduce the memleaks but is a delicate task due to uaf

https://github.com/radare/radare2/pull/5218

**Comment by axt** [comment]
@alvarofe Thanks, i've started it! 

It tooks around 2 hours (for every single variable "operation" aac does an sdb query for all the variables of the given function), will get back to you with the results, as soon as I have them. 

Prelminary: it looks good after 10 mins of running, but lets wait for the final results.

**Comment by axt** [comment]
Confirmed! Its working. The memory consumption after 'aac' finished, is below 1GB.

**Comment by alvarofe** [comment]
This has been merged into master so we can close the issue. Thx for reporting
