### ISSUE TITLE
RHashTable doesn't handle collisons

### ISSUE THREAD

**Issue by crowell** [radare/radare2#5168]
https://github.com/radare/radare2-regressions/blob/master/unit/test_hashtable.c#L59

should inserts fail with a collision?
how should they be handled, because the key is just hash, not an actual object, handling collisions in this way doesn't seem possible?

**Comment by radare** [comment]
Usually insert will never fail by definition unless the hashtable is full or cant allocate memory. The add operation, is the one that will fail in thatcase. This is how the sdb api  and many other hashtable implementations work too. I think its a known thing and i try to check if the value exists before setting it.

But i agree that this behavious must be different to avoid confussions or common problems

**Comment by crowell** [comment]
well, the fact of the matter is that djb2 isn't a fantastic hashing function for strings.

```
printf("%p\n",r_str_hash ("cb"));
printf("%p\n",r_str_hash ("bC"));
```

provides a collision, it's super easy to find collisions. colliding keys will break sdb, and the more we rely on sdb, the worse it is.

Perhaps, key, hash, value should all be stored? This will take up more space but will allow for actual collision resolution.

**Comment by radare** [comment]
nice catch. but %p is the wrong format string to use here.


this algorithm comes from java hash string algorithm, we can switch to another one that have other collisions. but we will always find collisions

**Comment by crowell** [comment]
related: https://github.com/radare/sdb/pull/102

**Comment by radare** [comment]
will be nice to have this fixed before 0.10.4. thanks for the effort :)

**Comment by Maijin** [comment]
Can be closed ?

**Comment by alvarofe** [comment]
afaik @radare is working on this in the sdb branch, cause the collision is not longer an issue but others have arised

**Comment by radare** [comment]
Nope dont close it

**Comment by radare** [comment]
im afraid of merging this before having the update-sdb branch merged. so moving to 1.1

**Comment by radare** [comment]
Now that the sdb branch is merged this issue should be "gone" as soon as we replace the raw usage of util/ht.c to use the new one. but this may introduce new regressions.

**Comment by radare** [comment]
util/ht is still used in some places, we should use sdb's one

**Comment by alvarofe** [comment]
we have already issues for this
