### ISSUE TITLE
double free

### ISSUE THREAD

**Issue by jjdredd** [radare/radare2#5178]
$ ~/usr/bin/r2 -d /bin/ls
Process with PID 23220 started...
attach 23220 23220
bin.baddr 0x08048000
Assuming filepath /bin/ls
*** Error in `/home/ragim/usr/bin/r2': double free or corruption (fasttop): 0x81e559c0 ***
======= Backtrace: =========
/lib/libc.so.6(+0x6df41)[0xb67cef41]
/lib/libc.so.6(+0x74392)[0xb67d5392]
/lib/libc.so.6(+0x74b1d)[0xb67d5b1d]
/home/ragim/usr/lib/libr_io.so(r_io_desc_free+0xdb)[0xb6d34f96]
/home/ragim/usr/lib/libr_io.so(r_io_desc_del+0x9b)[0xb6d35098]
/home/ragim/usr/lib/libr_io.so(r_io_close+0xd0)[0xb6d302a5]
/home/ragim/usr/lib/libr_bin.so(r_bin_load_io_at_offset_as_sz+0x23d)[0xb7450305]
/home/ragim/usr/lib/libr_bin.so(r_bin_load_io_at_offset_as+0x6d)[0xb74506c7]
/home/ragim/usr/lib/libr_bin.so(r_bin_load_io+0x4d)[0xb74500c0]
/home/ragim/usr/lib/libr_bin.so(r_bin_load+0x105)[0xb744fba1]
/home/ragim/usr/lib/libr_core.so(+0x8157c)[0xb761057c]
/home/ragim/usr/lib/libr_core.so(r_core_bin_load+0x20a)[0xb7610e50]
/home/ragim/usr/bin/r2(main+0x14bf)[0x80090020]
/lib/libc.so.6(__libc_start_main+0xf5)[0xb6779645]
/home/ragim/usr/bin/r2(+0x2221)[0x8008e221]
======= Memory map: ========
8008c000-80093000 r-xp 00000000 08:01 1577621    /home/ragim/usr/bin/radare2
80093000-80094000 r--p 00006000 08:01 1577621    /home/ragim/usr/bin/radare2
80094000-80095000 rw-p 00007000 08:01 1577621    /home/ragim/usr/bin/radare2
80095000-800f6000 rw-p 00000000 00:00 0 
81dea000-81e9f000 rw-p 00000000 00:00 0          [heap]
b6698000-b66b2000 r-xp 00000000 08:01 2506120    /usr/lib/gcc/i686-pc-linux-gnu/4.9.3/libgcc_s.so.1
b66b2000-b66b3000 r--p 00019000 08:01 2506120    /usr/lib/gcc/i686-pc-linux-gnu/4.9.3/libgcc_s.so.1
b66b3000-b66b4000 rw-p 0001a000 08:01 2506120    /usr/lib/gcc/i686-pc-linux-gnu/4.9.3/libgcc_s.so.1
b66d5000-b66d7000 r-xp 00000000 08:01 4985279    /home/ragim/usr/lib/radare2/0.10.4-git/asm_propeller.so
b66d7000-b66d8000 r--p 00001000 08:01 4985279    /home/ragim/usr/lib/radare2/0.10.4-git/asm_propeller.so
b66d8000-b66d9000 rw-p 00002000 08:01 4985279    /home/ragim/usr/lib/radare2/0.10.4-git/asm_propeller.so
b66d9000-b66dd000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b66dd000-b66de000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b66de000-b66e2000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b66e2000-b66e6000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b66e6000-b66ea000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b66ea000-b66f1000 r--s 00000000 08:01 4986997    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-64.sdb
b66f1000-b66fc000 r--s 00000000 08:01 4986613    /home/ragim/usr/lib/radare2/0.10.4-git/opcodes/x86.sdb
b66fc000-b66fe000 rw-p 00000000 00:00 0 
b66fe000-b6716000 r-xp 00000000 08:01 1845832    /lib/libpthread-2.21.so
b6716000-b6717000 r--p 00017000 08:01 1845832    /lib/libpthread-2.21.so
b6717000-b6718000 rw-p 00018000 08:01 1845832    /lib/libpthread-2.21.so
b6718000-b671a000 rw-p 00000000 00:00 0 
b671a000-b675f000 r-xp 00000000 08:01 1845421    /lib/libm-2.21.so
b675f000-b6760000 r--p 00044000 08:01 1845421    /lib/libm-2.21.so
b6760000-b6761000 rw-p 00045000 08:01 1845421    /lib/libm-2.21.so
b6761000-b6903000 r-xp 00000000 08:01 1846840    /lib/libc-2.21.so
b6903000-b6906000 r--p 001a1000 08:01 1846840    /lib/libc-2.21.so
b6906000-b6908000 rw-p 001a4000 08:01 1846840    /lib/libc-2.21.so
b6908000-b690b000 rw-p 00000000 00:00 0 
b690b000-b690d000 r-xp 00000000 08:01 1846831    /lib/libutil-2.21.so
b690d000-b690e000 r--p 00001000 08:01 1846831    /lib/libutil-2.21.so
b690e000-b690f000 rw-p 00002000 08:01 1846831    /lib/libutil-2.21.so
b690f000-b697a000 r-xp 00000000 08:01 1577552    /home/ragim/usr/lib/libr_util.so.0.10.4-git
b697a000-b697b000 ---p 0006b000 08:01 1577552    /home/ragim/usr/lib/libr_util.so.0.10.4-git
b697b000-b697c000 r--p 0006b000 08:01 1577552    /home/ragim/usr/lib/libr_util.so.0.10.4-git
b697c000-b697f000 rw-p 0006c000 08:01 1577552    /home/ragim/usr/lib/libr_util.so.0.10.4-git
b697f000-b6988000 rw-p 00000000 00:00 0 
b6988000-b699a000 r-xp 00000000 08:01 1577082    /home/ragim/usr/lib/libr_crypto.so.0.10.4-git
b699a000-b699b000 ---p 00012000 08:01 1577082    /home/ragim/usr/lib/libr_crypto.so.0.10.4-git
b699b000-b699c000 r--p 00012000 08:01 1577082    /home/ragim/usr/lib/libr_crypto.so.0.10.4-git
b699c000-b699d000 rw-p 00013000 08:01 1577082    /home/ragim/usr/lib/libr_crypto.so.0.10.4-git
b699d000-b69b6000 rw-p 00000000 00:00 0 
b69b6000-b69c2000 r-xp 00000000 08:01 1577217    /home/ragim/usr/lib/libr_egg.so.0.10.4-git
b69c2000-b69c3000 ---p 0000c000 08:01 1577217    /home/ragim/usr/lib/libr_egg.so.0.10.4-git
b69c3000-b69c4000 r--p 0000c000 08:01 1577217    /home/ragim/usr/lib/libr_egg.so.0.10.4-git
b69c4000-b69c5000 rw-p 0000d000 08:01 1577217    /home/ragim/usr/lib/libr_egg.so.0.10.4-git
b69c5000-b69c6000 rw-p 00000000 00:00 0 
b69c6000-b69ca000 r-xp 00000000 08:01 1577348    /home/ragim/usr/lib/libr_flags.so.0.10.4-git
b69ca000-b69cb000 ---p 00004000 08:01 1577348    /home/ragim/usr/lib/libr_flags.so.0.10.4-git
b69cb000-b69cc000 r--p 00004000 08:01 1577348    /home/ragim/usr/lib/libr_flags.so.0.10.4-git
b69cc000-b69cd000 rw-p 00005000 08:01 1577348    /home/ragim/usr/lib/libr_flags.so.0.10.4-git
b69cd000-b69ce000 rw-p 00000000 00:00 0 
b69ce000-b69d8000 r-xp 00000000 08:01 1577513    /home/ragim/usr/lib/libr_socket.so.0.10.4-git
b69d8000-b69d9000 r--p 00009000 08:01 1577513    /home/ragim/usr/lib/libr_socket.so.0.10.4-git
b69d9000-b69da000 rw-p 0000a000 08:01 1577513    /home/ragim/usr/lib/libr_socket.so.0.10.4-git
b69da000-b69ec000 r-xp 00000000 08:01 1577430    /home/ragim/usr/lib/libr_magic.so.0.10.4-git
b69ec000-b69ed000 r--p 00011000 08:01 1577430    /home/ragim/usr/lib/libr_magic.so.0.10.4-git
b69ed000-b69ee000 rw-p 00012000 08:01 1577430    /home/ragim/usr/lib/libr_magic.so.0.10.4-git
b69ee000-b69f8000 r-xp 00000000 08:01 1577402    /home/ragim/usr/lib/libr_hash.so.0.10.4-git
b69f8000-b69f9000 r--p 00009000 08:01 1577402    /home/ragim/usr/lib/libr_hash.so.0.10.4-git
b69f9000-b69fa000 rw-p 0000a000 08:01 1577402    /home/ragim/usr/lib/libr_hash.so.0.10.4-git
b69fa000-b69fc000 r-xp 00000000 08:01 1577532    /home/ragim/usr/lib/libr_syscall.so.0.10.4-git
b69fc000-b69fd000 r--p 00001000 08:01 1577532    /home/ragim/usr/lib/libr_syscall.so.0.10.4-git
b69fd000-b69fe000 rw-p 00002000 08:01 1577532    /home/ragim/usr/lib/libr_syscall.so.0.10.4-git
b69fe000-b6b90000 r-xp 00000000 08:01 1576971    /home/ragim/usr/lib/libr_asm.so.0.10.4-git
b6b90000-b6b91000 ---p 00192000 08:01 1576971    /home/ragim/usr/lib/libr_asm.so.0.10.4-git
b6b91000-b6bdb000 r--p 00192000 08:01 1576971    /home/ragim/usr/lib/libr_asm.so.0.10.4-git
b6bdb000-b6cc0000 rw-p 001dc000 08:01 1576971    /home/ragim/usr/lib/libr_asm.so.0.10.4-git
b6cc0000-b6cd7000 rw-p 00000000 00:00 0 
b6cd7000-b6cdc000 r-xp 00000000 08:01 1577424    /home/ragim/usr/lib/libr_lang.so.0.10.4-git
b6cdc000-b6cdd000 r--p 00004000 08:01 1577424    /home/ragim/usr/lib/libr_lang.so.0.10.4-git
b6cdd000-b6cde000 rw-p 00005000 08:01 1577424    /home/ragim/usr/lib/libr_lang.so.0.10.4-git
b6cde000-b6d0f000 r-xp 00000000 08:01 1577388    /home/ragim/usr/lib/libr_fs.so.0.10.4-git
b6d0f000-b6d10000 r--p 00030000 08:01 1577388    /home/ragim/usr/lib/libr_fs.so.0.10.4-git
b6d10000-b6d11000 rw-p 00031000 08:01 1577388    /home/ragim/usr/lib/libr_fs.so.0.10.4-git
b6d11000-b6d18000 rw-p 00000000 00:00 0 
b6d18000-b6d60000 r-xp 00000000 08:01 1577404    /home/ragim/usr/lib/libr_io.so.0.10.4-git
b6d60000-b6d61000 ---p 00048000 08:01 1577404    /home/ragim/usr/lib/libr_io.so.0.10.4-git
b6d61000-b6d62000 r--p 00048000 08:01 1577404    /home/ragim/usr/lib/libr_io.so.0.10.4-git
b6d62000-b6d6d000 rw-p 00049000 08:01 1577404    /home/ragim/usr/lib/libr_io.so.0.10.4-git
b6d6d000-b6d73000 rw-p 00000000 00:00 0 
b6d73000-b6d77000 r-xp 00000000 08:01 1576985    /home/ragim/usr/lib/libr_bp.so.0.10.4-git
b6d77000-b6d78000 r--p 00003000 08:01 1576985    /home/ragim/usr/lib/libr_bp.so.0.10.4-git
b6d78000-b6d79000 rw-p 00004000 08:01 1576985    /home/ragim/usr/lib/libr_bp.so.0.10.4-git
b6d79000-b6d80000 r-xp 00000000 08:01 1577456    /home/ragim/usr/lib/libr_reg.so.0.10.4-git
b6d80000-b6d81000 r--p 00006000 08:01 1577456    /home/ragim/usr/lib/libr_reg.so.0.10.4-git
b6d81000-b6d82000 rw-p 00007000 08:01 1577456    /home/ragim/usr/lib/libr_reg.so.0.10.4-git
b6d82000-b6d83000 rw-p 00000000 00:00 0 
b6d83000-b70b2000 r-xp 00000000 08:01 1576932    /home/ragim/usr/lib/libr_anal.so.0.10.4-git
b70b2000-b70b3000 ---p 0032f000 08:01 1576932    /home/ragim/usr/lib/libr_anal.so.0.10.4-git
b70b3000-b70b9000 r--p 0032f000 08:01 1576932    /home/ragim/usr/lib/libr_anal.so.0.10.4-git
b70b9000-b7351000 rw-p 00335000 08:01 1576932    /home/ragim/usr/lib/libr_anal.so.0.10.4-git
b7351000-b7413000 rw-p 00000000 00:00 0 
b7413000-b7437000 r-xp 00000000 08:01 1577144    /home/ragim/usr/lib/libr_debug.so.0.10.4-git
b7437000-b7438000 r--p 00023000 08:01 1577144    /home/ragim/usr/lib/libr_debug.so.0.10.4-git
b7438000-b7439000 rw-p 00024000 08:01 1577144    /home/ragim/usr/lib/libr_debug.so.0.10.4-git
b7439000-b752b000 r-xp 00000000 08:01 1576976    /home/ragim/usr/lib/libr_bin.so.0.10.4-git
b752b000-b752c000 ---p 000f2000 08:01 1576976    /home/ragim/usr/lib/libr_bin.so.0.10.4-git
b752c000-b752d000 r--p 000f2000 08:01 1576976    /home/ragim/usr/lib/libr_bin.so.0.10.4-git
b752d000-b7531000 rw-p 000f3000 08:01 1576976    /home/ragim/usr/lib/libr_bin.so.0.10.4-git
b7531000-b7532000 rw-p 00000000 00:00 0 
b7532000-b7536000 r-xp 00000000 08:01 1577021    /home/ragim/usr/lib/libr_config.so.0.10.4-git
b7536000-b7537000 r--p 00003000 08:01 1577021    /home/ragim/usr/lib/libr_config.so.0.10.4-git
b7537000-b7538000 rw-p 00004000 08:01 1577021    /home/ragim/usr/lib/libr_config.so.0.10.4-git
b7538000-b754d000 r-xp 00000000 08:01 1577038    /home/ragim/usr/lib/libr_cons.so.0.10.4-git
b754d000-b754e000 r--p 00014000 08:01 1577038    /home/ragim/usr/lib/libr_cons.so.0.10.4-git
b754e000-b754f000 rw-p 00015000 08:01 1577038    /home/ragim/usr/lib/libr_cons.so.0.10.4-git
b754f000-b7552000 rw-p 00000000 00:00 0 
b7552000-b7557000 r-xp 00000000 08:01 1577495    /home/ragim/usr/lib/libr_search.so.0.10.4-git
b7557000-b7558000 r--p 00004000 08:01 1577495    /home/ragim/usr/lib/libr_search.so.0.10.4-git
b7558000-b7559000 rw-p 00005000 08:01 1577495    /home/ragim/usr/lib/libr_search.so.0.10.4-git
b7559000-b757d000 r-xp 00000000 08:01 1577450    /home/ragim/usr/lib/libr_parse.so.0.10.4-git
b757d000-b757e000 r--p 00023000 08:01 1577450    /home/ragim/usr/lib/libr_parse.so.0.10.4-git
b757e000-b757f000 rw-p 00024000 08:01 1577450    /home/ragim/usr/lib/libr_parse.so.0.10.4-git
b757f000-b758f000 rw-p 00000000 00:00 0 
b758f000-b76af000 r-xp 00000000 08:01 1577061    /home/ragim/usr/lib/libr_core.so.0.10.4-git
b76af000-b76b0000 r--p 0011f000 08:01 1577061    /home/ragim/usr/lib/libr_core.so.0.10.4-git
b76b0000-b76b8000 rw-p 00120000 08:01 1577061    /home/ragim/usr/lib/libr_core.so.0.10.4-git
b76b8000-b76b9000 rw-p 00000000 00:00 0 
b76b9000-b76bc000 r-xp 00000000 08:01 1845449    /lib/libdl-2.21.so
b76bc000-b76bd000 r--p 00002000 08:01 1845449    /lib/libdl-2.21.so
b76bd000-b76be000 rw-p 00003000 08:01 1845449    /lib/libdl-2.21.so
b76be000-b76bf000 rw-p 00000000 00:00 0 
b76bf000-b76c0000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76c0000-b76c1000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76c1000-b76c5000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b76c5000-b76c6000 r--s 00000000 08:01 4987283    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-64.sdb
b76c6000-b76d1000 r--s 00000000 08:01 4986613    /home/ragim/usr/lib/radare2/0.10.4-git/opcodes/x86.sdb
b76d1000-b76d5000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b76d5000-b76d9000 r--s 00000000 08:01 4986994    /home/ragim/usr/lib/radare2/0.10.4-git/syscall/linux-x86-32.sdb
b76d9000-b76da000 r--s 00000000 08:01 4987283    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-64.sdb
b76da000-b76db000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76db000-b76dc000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76dc000-b76dd000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76dd000-b76de000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76de000-b76df000 r--s 00000000 08:01 4987279    /home/ragim/usr/lib/radare2/0.10.4-git/fcnsign/linux-x86-32.sdb
b76df000-b76e0000 rw-p 00000000 00:00 0 
b76e0000-b76e2000 r--p 00000000 00:00 0          [vvar]
b76e2000-b76e3000 r-xp 00000000 00:00 0          [vdso]
b76e3000-b7705000 r-xp 00000000 08:01 1846869    /lib/ld-2.21.so
b7705000-b7706000 r--p 00021000 08:01 1846869    /lib/ld-2.21.so
b7706000-b7707000 rw-p 00022000 08:01 1846869    /lib/ld-2.21.so
bfe40000-bfe62000 rw-p 00000000 00:00 0          [stack]

radare2 0.10.4-git 11637 @ linux-x86-32 git.0.9.9-3526-g6d4c169
commit: 6d4c16923d0bcd34d12ab9415502d2f9c1d97adc build: 2016-06-19

on x86 and amd64

**Comment by radare** [comment]
fixed already in master

**Comment by Maijin** [comment]
Fixed
