### ISSUE TITLE
Slow scrolling in visual mode after analysis

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5180]
With no analysis, despite the large (but not obscene) binary size, visual scrolling is just fine (hold down `j`). After analysis, movement slows down quite a lot and becomes inertial. This is a big issue when working with larger binaries.

Example file: [var.zip](https://github.com/radare/radare2/files/322992/var.zip)

Is it terminal-related or radare2-related? I disabled `scr.utf8` with no improvements. Also tried in different terminals; it seems _slightly_ better with xterm, but still bad.

**Comment by radare** [comment]
you can asm.slow=false if you want. but the bottleneck is somewhere else. this is known issue and its improving over time, but it takes some time to refactor all the code to make it O(1)

**Comment by ret2libc** [comment]
I cannot reproduce this anymore. Please reopen if you still have the problem
