### ISSUE TITLE
variables are saved as arguments

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#5181]
How to reproduce:
```
$ r2 ./radare2-regressions/bins/elf/ls-linux64
[0x00005c20]> s main
[0x00003ad0]> af
[0x00003ad0]> afa
var int local_0h @ rbp-0x0
arg int arg_12h @ rbp+0x12
arg int arg_2eh @ rbp+0x2e
[0x00003ad0]> afv
[0x00003ad0]>
```

As you can see, local_0h is considered an argument and not a variable. As far as i can tell, all arguments and variables are now considered arguments :(

@oddcoder

**Comment by oddcoder** [comment]
afaik local_0h was a bug that is fixed right before you open the issue
plus one extra thing they are no longer classified as arg/var
they are classified as bp based or sp based 
all bp based arguments and vars  are stored at afa all sp based  arguments and vars are stored at afe
afv is for register based arguments only
like 

```
[0x00000000]> afv rax reg int
[0x00000000]> afv
reg int reg @ rax
[0x00000000]> 
```
I hope their is no more confusion and

**Comment by ret2libc** [comment]
I'm closing this with "notabug". Thanks @oddcoder !
