### ISSUE TITLE
`Invalid value for bits` when opening ELF

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2#5184]
```
C:\Users\Dave>C:\Users\Dave\Downloads\radare2-w32-0.10.4-git\radare2.exe C:\Users\Dave\IdeaProjects\radare2-binexport2\sample-files\fauxware
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
Invalid value for bits
[0x00400580]>
```

Binary is here: https://github.com/angr/angr-doc/blob/master/examples/fauxware/fauxware

**Comment by Manouchehri** [comment]
Using 55e0804d1d264e687a71ae88ddfe72641edafb43.
```
C:\Users\Dave>C:\Users\Dave\Downloads\radare2-w32-0.10.4-git\radare2.exe -v
radare2 0.10.4-git 11661 @ windows-x86-32 git.0.10.3-274-g55e0804
commit: 55e0804d1d264e687a71ae88ddfe72641edafb43 build: 2016-06-20
```

**Comment by alvarofe** [comment]
I don't get nothing in mac

```
mac:tmp alvaro_fe$ r2 fauxware
 -- Trace register changes while debugging with 'e trace.cmtregs=true'
[0x00400580]>
```

so it should be something with windows

**Comment by radare** [comment]
cant reproduce

**Comment by alvarofe** [comment]
that eprintf is happening in `r_debug_set_arch` and dbg->h is not null, do you have something in .radarerc maybe?

**Comment by radare** [comment]
maybe its because you have some old plugins or using libraries from different versions

**Comment by Manouchehri** [comment]
It's a brand new install, not using any plugins. All I did was unzip the release. (0.10.3 has the same issue.)

Definitely Windows related. Any ideas on how I could get more info on what's causing those messages?

**Comment by radare** [comment]
this warning is harmless and must be removed

**Comment by Manouchehri** [comment]
Thanks!
