### ISSUE TITLE
Debugger breaks on tracepoints from SIGTRAP

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5196]
Using latest commit from git, including the debugger rework. Redoing: https://monosource.github.io/2016/06/solving-bomb-phase2

```
[0x08048b7e]> db
0x08048b7e - 0x08048b7f 1 --x sw trace enabled cmd=".dr*;*(esi+ebx*4)=`dr eax`" name="" module=""
0x08048b8e - 0x08048b8f 1 --x sw break enabled cmd="pf dddddd @ esi" name="" module=""
[0x08048b7e]> dc
child stopped with signal 5
[+] SIGNAL 5 errno=0 addr=(nil) code=128 ret=0
child stopped with signal 5
[+] SIGNAL 5 errno=0 addr=(nil) code=128 ret=0
```

Tracepoints should not break execution flow.

**Comment by radare** [comment]
Addr nil??!? Wtf

**Comment by monosource** [comment]
Yeah, a simpler example:
```
$ r2 -d /bin/ls
[0x7fe1354dd190]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x7fe1354dd190]> dcu main
Continue until 0x004028a0 using 1 bpsize
child stopped with signal 5
[+] SIGNAL 5 errno=0 addr=(nil) code=128 ret=0
hit breakpoint at: 4028a0
attach 21643 1
[0x004028a0]> 
```

**Comment by monosource** [comment]
cc @jduck you moved the `eprintf` which was done only for SIGSEGV outside of the switch statement. Is there any particular reason for this?

**Comment by jduck** [comment]
I'll need to create a regression test case to cover this regression and fix it...

**Comment by radare** [comment]
the nil thing is because you used %p to display an ut64 value. always use “0x%"PFMT64x

**Comment by jduck** [comment]
I moved it outside because it's useful to print other signals too. It's only a err print and doesn't really relate to the topic of this issue. The preceding eprint (child stopped with signal 5) is also unrelated to the topic of the issue. Neither print is strictly necessary, especially in the SIGTRAP case.

**Comment by jduck** [comment]
@monosource please give the PR a try and let me know if it helps. I'll start a new topic branch to quiet the output down a bit for SIGTRAP.

**Comment by jduck** [comment]
See also https://github.com/radare/radare2/pull/5263 for quieter SIGTRAP handling.

**Comment by monosource** [comment]
@jduck Cloned your fix branch. It fixes tracepoints, but they are still verbose i.e. spit out

```
[+] SIGNAL 5 errno=0 addr=0x00000000 code=128 ret=0
```

for each pass through the tracepoint.

I also cloned the quiet tracepoint branch. It removes the above line, but it still gives register update notifications of the form:
```
fs+regs
fs-
```

Perhaps we can add a `dbg.silent` option to quietly execute "dbc" commands on tracepoints. Or vary the verbosity level.

Anyway, lgtm.

**Comment by jduck** [comment]
I'm not sure why it shows "fs+regs" and "fs-" but I suspect an r_cons bug. cc @radare 
I'm not a huge fan of the dbg.silent option. You could always ``` > /dev/null ``` any commands you didn't want to see...

**Comment by radare** [comment]
because those commands are needed to import the register values into flags
dbg.silent makes no sense. this shouldnt be debugger-specific

**Comment by monosource** [comment]
The problem with the `> /dev/null` approach is that it isn't very flexible. And also doesn't seem to work with `dbc`:

```
[0x08048b79]> "dbc 0x08048b7e .dr* > /dev/null;*(esi+ebx*4)=`dr eax` > /dev/null"
[0x08048b79]> dc
hit tracepoint at: 8048b7e
fs+regs
fs-
hit tracepoint at: 8048b7e
fs+regs
fs-
hit tracepoint at: 8048b7e
fs+regs
fs-
hit tracepoint at: 8048b7e
fs+regs
fs-
hit tracepoint at: 8048b7e
fs+regs
fs-
hit breakpoint at: 8048b8e

0xffa904a0 = 1
0xffa904a4 = 2
0xffa904a8 = 6
0xffa904ac = 24
0xffa904b0 = 120
0xffa904b4 = 720
```

And I don't want to `dc > /dev/null` either because I want the final 6 values (from another dbc) to be printed out.

@radare I agree that it shouldn't be debugger specific.

**Comment by radare** [comment]
The > thing was just an example . If u really want rcons not to pront anythingg al the time just enable scr.null
