### ISSUE TITLE
[README] Why radare2 does not use enums for functions return (enum vs int)

### ISSUE THREAD

**Issue by radare** [radare/radare2#5197]
the reason why many places in r2land functions return int instead of an enum type is because enums cant be OR'ed because the fuckup the usage within a switch statement, and also because swig cant handle that stuff. so basically the last @jduck commit broke the bindings with this issue:

```
r_core_wrap.cxx:28612:60: error: assigning to 'RRegisterType' from incompatible type 'long'
  arg2 = static_cast< long >(val2); if (arg1) (arg1)->type = arg2; resultobj = SWIG_Py_Void(); return resultobj; fail:
                                                           ^ ~~~~
r_core_wrap.cxx:32103:61: error: assigning to 'RDebugReasonType' from incompatible type 'int'
    arg2 = static_cast< int >(val2); if (arg1) (arg1)->type = arg2; resultobj = SWIG_Py_Void(); return resultobj; fail:
                                                            ^ ~~~~
3 warnings and 2 errors generated.
```

this was a known thing, but i understand the reason for using enums in some situations, hte problem is that we dnot want to loose the ability to have automatic bindings.. i have removed those fields from those structs to allow bindings compilation, but obviously lossing some features

**Comment by radare** [comment]
workarounded here https://github.com/radare/radare2/commit/e4eb7e5ee97d73d979041c18df9688fba1bfc435

**Comment by Maijin** [comment]
?

**Comment by radare** [comment]
the status is that valabind and swig are not able to catch those situations properly. mainly because swig doesnt handles this and valabind doesnt adapts the code to make it suitable for swig.

so its better to dont use enums in function signatures unless we find a good solution for this. otherwise all bindings get broken

**Comment by Maijin** [comment]
Definitely not the place for reminder, this must be placed in https://github.com/radare/radare2/blob/master/CONTRIBUTING.md
