### ISSUE TITLE
Add command to export graph layout

### ISSUE THREAD

**Issue by radare** [radare/radare2#5210]
agj is nice, but it doesnt provides the position x and y of each node. Necessary for https://github.com/radare/radare2-webui/issues/69

**Comment by radare** [comment]
@ret2libc comments on this?

**Comment by ret2libc** [comment]
What about just adding those info to `agj` command? you just need x and y.

Also, `agk` should already provide those info but it seems like it's broken. So I would prefer to either fix `agk` and use that or improve `agj` and use that. I don't think a new command is needed.

**Comment by radare** [comment]
Improving agj sounds good as all the info will be there in a shot.

Can you do this change?

**Comment by ret2libc** [comment]
I'm really sorry, but I can't in this period :(

**Comment by radare** [comment]
2 months have passed. still no time for this?

**Comment by radare** [comment]
3 months. ping

**Comment by ret2libc** [comment]
I'd prefer if someone else could do this

**Comment by Maijin** [comment]
See META
