### ISSUE TITLE
r2 crash on binary analysis with aac

### ISSUE THREAD

**Issue by cym13** [radare/radare2#5220]
What happens
============

r2 segfaults on analysis

How to reproduce
================

- Get the binary from http://pastebin.com/PrY8BeX1
  (base64, ARM binary, md5: 4df49883063edd0c22e349f960f1a3bc).
- $ r2 -q -c 'aac' binary

    Warning: Cannot initialize dynamic strings
    Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )zsh: segmentation fault (core dumped)  r2 -q -c 'aac' binary

Version
=======

radare2 0.10.4-git 11724 @ linux-x86-32 git.0.10.3-336-g97b6bdb
commit: 97b6bdbc40fb06401ff11e1d86db037560e20cb6 build: 2016-06-27

**Comment by radare** [comment]
can't reproduce, are you running this on debian, or any other distro that imposes some strict OOB rules? can you provide a backtrace or anything to show where the error is? because neither asan or valgrind shows anything wrong in the process. but it takes almost 3GB of ram to get the prompt

**Comment by alvarofe** [comment]
I can't repro either. To speed up loading just skip dwarf info running with `r2 -e bin.dbginfo=false binary` we need to improve dwarf code because it takes so much time. Thx

**Comment by cym13** [comment]
When on IRC other people were able to reproduce. I don't have 3GB ram on this computer so it maybe linked.

    (gdb) run -q -c 'aac' 15
    Starting program: /usr/bin/r2 -q -c 'aac' 15
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    Warning: Cannot initialize dynamic strings
    Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )Warning: malformed dwarf attribute capacity doesnt match length
    )
    Program received signal SIGSEGV, Segmentation fault.
    0xb70ba3b6 in vfprintf () from /usr/lib/libc.so.6
    (gdb) backtrace 
    #0  0xb70ba3b6 in vfprintf () from /usr/lib/libc.so.6
    #1  0xb70dbbff in vsnprintf () from /usr/lib/libc.so.6
    #2  0xb726aff5 in r_strbuf_appendf (sb=0xbfffe060, fmt=0xb789b462 "%s,0x%llx,%s,%c,=[4]") at strbuf.c:105
    #3  0xb76d4c41 in analop_esil (a=0x80082838, op=0xbfffdfcc, addr=33104, 
        buf=0x801cbb78 "\004\340-\345@0\237", <incomplete sequence \345>, len=3968, handle=0xb7c59a04 <handle>, 
        insn=0x801d6550, thumb=false) at /home/cym13/usr/git/radare2/libr/..//libr/anal/p/anal_arm_cs.c:764
    #4  0xb76d6d6f in analop (a=0x80082838, op=0xbfffdfcc, addr=33104, 
        buf=0x801cbb78 "\004\340-\345@0\237", <incomplete sequence \345>, len=3968)
        at /home/cym13/usr/git/radare2/libr/..//libr/anal/p/anal_arm_cs.c:1434
    #5  0xb77275c4 in r_anal_op (anal=0x80082838, op=0xbfffdfcc, addr=33104, 
        data=0x801cbb78 "\004\340-\345@0\237", <incomplete sequence \345>, len=3968) at op.c:96
    #6  0xb7ed2360 in cmd_anal_calls (core=0x80007900 <r>, input=0x800fe0a3 "") at cmd_anal.c:2920
    #7  0xb7ed6084 in cmd_anal_all (core=0x80007900 <r>, input=0x800fe0a2 "c") at cmd_anal.c:4157
    #8  0xb7ed6fcc in cmd_anal (data=0x80007900 <r>, input=0x800fe0a1 "ac") at cmd_anal.c:4476
    #9  0xb7f30e17 in r_cmd_call (cmd=0x800b00a8, input=0x800fe0a0 "aac") at cmd_api.c:210
    #10 0xb7eff2f7 in r_core_cmd_subst_i (core=0x80007900 <r>, cmd=0x800fe0a0 "aac", colon=0x0) at cmd.c:1853
    #11 0xb7efd2ca in r_core_cmd_subst (core=0x80007900 <r>, cmd=0x800fe0a0 "aac") at cmd.c:1249
    #12 0xb7f0053b in r_core_cmd (core=0x80007900 <r>, cstr=0xbffff317 "aac", log=0) at cmd.c:2260
    #13 0xb7f00adc in r_core_cmd0 (user=0x80007900 <r>, cmd=0xbffff317 "aac") at cmd.c:2397
    #14 0x80002820 in run_commands (cmds=0x80069008, files=0x80069028, quiet=true) at radare2.c:271
    #15 0x80004850 in main (argc=5, argv=0xbffff174, envp=0xbffff18c) at radare2.c:895

I'm on archlinux btw.

**Comment by radare** [comment]
can you show the register values and the instruction that crashes?

**Comment by cym13** [comment]
Here it is, I can't say I'm proficient with gdb so it may not be exactly what you're after:

    (gdb) info registers
    eax            0x0      0
    ecx            0xffffffff       -1
    edx            0x2d     45
    ebx            0xb7227000       -1222479872
    esp            0xbfffc3e0       0xbfffc3e0
    ebp            0xbfffc8c8       0xbfffc8c8
    esi            0xffffffb8       -72
    edi            0x2d     45
    eip            0xb70ba3b6       0xb70ba3b6 <vfprintf+8662>
    eflags         0x10246  [ PF ZF IF RF ]
    cs             0x73     115
    ss             0x7b     123
    ds             0x7b     123
    es             0x7b     123
    fs             0x0      0
    gs             0x33     51
    (gdb) display/i $pc
    1: x/i $pc
    => 0xb70ba3b6 <vfprintf+8662>:  repnz scas %es:(%edi),%al

**Comment by radare** [comment]
so that’s not an stack exhaustion bug. 

so iirc repnz scas is used to compute an strlen, that’s why ecx=-1.. but the 0x2d address seems to be wrong and the reason of the crash. the thing is.. which instruction is producing this? do you have capstone installed in system? because i cant see any bug in the code that is related to this backtrace. and i cant reproduce it in any of my machines

**Comment by radare** [comment]
maybe that will fail on openbsd32 or arm32?

will try to repdocuce in my rpi later

**Comment by radare** [comment]
confirmed . reproducible on ARM :) will fix later

**Comment by radare** [comment]
Fixed in master, thanks! nice catch
