### ISSUE TITLE
r_anal_fcn_is_in_offset is SO SLOW

### ISSUE THREAD

**Issue by crowell** [radare/radare2#5221]
visual mode scrolling after analysis is really slow.

![img](http://i.imgur.com/7DMFYdI.png)

cachegrind file https://gist.github.com/b28506e09e75f3133e804cc31ed45964

improving this to use some better data structures will have a huge speed increase.

**Comment by radare** [comment]
Its a known thing that ret2libc change on that was going to be painful. This is because functions are no longer a range, but a list of ranges, which makes it hard to be o(1).

If we want speed we should calloc(sizeof(void*),sizeof(textsection)); and then use each word to store a pointer to a struct containing the info for that function, metadata, etc. this is really mem consuming because if we open a 100MB binary we will be requesting 800MB of memory without really using it completely. But its a pay off for performance.

Another solution would be to use ranged hashtable elements. This is by dividing the offset by a constant and then storig a list of the sub offsets in that block. So the search will be only 2 hashtable resolutions instead of o(n)

**Comment by monosource** [comment]
Related to https://github.com/radare/radare2/issues/5180?

**Comment by radare** [comment]
probably, or at lest 70% of that slowdown comes because of this

**Comment by ret2libc** [comment]
Yes, I think it was known, unfortunately. I traded some performance for correctness, which was missing.

As a solution, I don't think we need an array of `sizeof(text section)`(considering also that you can have code also in other sections). There are some existing data structures that can be used for faster queries, like:
* [interval tree](https://en.wikipedia.org/wiki/Interval_tree) that seems to have good performance. `Interval trees have a query time of O(log n + m) and an initial creation time of O(n log n), while limiting memory consumption to O(n))` where `n` is the number of intervals(in our case the number of basic blocks in a function). This could be implemented by using `RTree`.
* [skip list](https://en.wikipedia.org/wiki/Skip_list) that seems much easier to implement, by using a set of lists of sorted elements. It will have an expected cost for a search of `(log1/p n)/p` which is `O(log n)` (where, again, n is the number of basic blocks in a function). Also, it easily support insertion/deletion of elements in the list.

Personally, I would go with the skip list solution. We could store each basic block as an element in this list, that will be sorted by the start address of the basic block. It should speed up that function a lot (at least when a function has a lot of basic blocks, that are exactly the case that matter to us)

**Comment by crowell** [comment]
tracking progress here:

https://github.com/radare/radare2/tree/skiplist

**Comment by crowell** [comment]
:+1: 
![http://i.imgur.com/MRCU1uI.png](http://i.imgur.com/MRCU1uI.png)

**Comment by crowell** [comment]
and i guess this means that `r_cons_get_cursor` needs love next. hhehe

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
any chance to get this working before the release? i think we can delay until thursday just to be sure that the release happens properly and its stable

**Comment by radare** [comment]
tired of waiting as expected not ready for 0.10.4

**Comment by radare** [comment]
skiplist only enhaces this thing a 5% so its absolutely not the fix i was expecting. imho we should use more sdb

**Comment by radare** [comment]
i dont think skiplist solves this problem at all, and breaking the bindings is a no-way unless we patch valabind to support skiplist

**Comment by radare** [comment]
any other idea to optimize this? we have grouped the basicblocks ranges and updated sdb. segmenting the functions will be the next optimization to avoid walking the whole list all the time

**Comment by resilar** [comment]
Please fix this. The issue renders `aaa` analysis of r2 completely unusable for any serious work (>= 1MB binaries).

**Comment by radare** [comment]
aaa is the less serious command in r2land

**Comment by resilar** [comment]
Actually, the scrolling in visual mode has got MUCH better since I last tested. So the optimizations that have been done so far help a lot.

**Comment by radare** [comment]
yes, we are slowly introducing more optimizations and this is not about fixing “this issue”, is about refactoring, profiling, changing parts of r2, etc, which requires lot of testing before going forward, that’s why it’s not fixed yet. but will get better over time.

**Comment by MaskRay** [comment]
https://github.com/radare/radare2/pull/8387 is the tree @ret2libc wanted to have.

An RAnalFunction is a list of basic blocks but in most cases we can take them continuous and use an RAddrInterval to represent. It is easier to implement.  I am confident to speed it a lot. shared basic blocks and organizing basic blocks into an interval tree may be a better future.

**Comment by XVilka** [comment]
Big issue, can be infinitely long, because refactoring and speed optimization can be infinitely long.

**Comment by radare** [comment]
we can close this i think

**Comment by XVilka** [comment]
So, closing it?

**Comment by radare** [comment]
Yes
