### ISSUE TITLE
Extend RHashTable to support free function

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#5239]

**Comment by crowell** [comment]
really rhashtable needs to be done away with entirely, it's not a good impl.

**Comment by alvarofe** [comment]
but meanwhile is handy to have that pointer to free memory and avoid mem leaks, though sometimes is used along with RList and the memory is shared being the cause of annoying UAF. Once your optimization of RHasTable/sbd is done we'll use that instead

**Comment by radare** [comment]
Agree

**Comment by alvarofe** [comment]
merged in master already
