### ISSUE TITLE
Grep must return a value

### ISSUE THREAD

**Issue by radare** [radare/radare2#524]
If we do something like:

```
?v `ao~call?` >/dev/null
?? ?e this is a call
```

and then we will be able to write something like this:

```
ao~call?
?? ?e this is a call
```

**Comment by XVilka** [comment]
@radare any news on this one?

**Comment by radare** [comment]
I think its not done yet. Not even tests. Its easy, but i have no time for this now. Low prio

**Comment by alvarofe** [comment]
https://asciinema.org/a/7dwo4wmkf7ahv87b4fdjw59wo i think is done

**Comment by Maijin** [comment]
@radare to confirm

**Comment by radare** [comment]
not working

**Comment by radare** [comment]
<img width="609" alt="screen shot 2016-11-02 at 23 54 57" src="https://cloud.githubusercontent.com/assets/917142/19950445/d374103a-a157-11e6-9977-797287ebeac0.png">
