### ISSUE TITLE
Overwrite generic comments on IN/OUT insns

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5248]
When annotating for specific IO memory registers in AVR as in PR https://github.com/radare/radare2/pull/5247

The "old" generic anal comment still persists, i.e:

`"ADCH: ADC Data Register High byte."; store register to I/O location`

Instead of just:

`"ADCH: ADC Data Register High byte."`

Which is cleaner/desired.

**Comment by Maijin** [comment]
well this means asm.describe to be intelligent right ? Not sure we want that.

**Comment by brainstorm** [comment]
Don't know what @radare thinks about that. I was under the impression that this was a relatively simple "if"-like change when mentioning it to him :-S

**Comment by radare** [comment]
yes it is simple change and it makes sense to me because the ioport info is describing the instruction better than the generic description provided.

**Comment by brainstorm** [comment]
@radare, can you cherrypick those commits from your `lcall` branch (https://github.com/radare/radare2/commit/cfaec8b5ec8af5d6f061edde09fd5e2d4f2aa41e) into master if this is fixed/closed?:

**Comment by oddcoder** [comment]
oh sorry I thought that was master

**Comment by radare** [comment]
Its in master already
