### ISSUE TITLE
r2pm's use of sudo is opaque

### ISSUE THREAD

**Issue by Bob131** [radare/radare2#5255]
Hey! I love the kit, and r2pm in particular, but I have to say that having software invoking sudo on my behalf is worrying; in r2pm's case, however, it's less 'worrying' and more 'absolutely terrifying'. The scripts it invokes often do things I don't want, both intentionally and unintentionally. Installing plugins really ought not to be a crapshoot.

I understand this problem probably exists in the project more broadly than r2pm itself, but nonetheless I don't think a shell script, any shell script, should take it upon themselves to elevate their privs. If someone wants something run as root, they're well capable of typing 'sudo' themselves.

It looks as though there are quite a few shell scripts scattered around that may or may not exhibit this behaviour. I'd be more than happy to fix them and submit PRs, but I want to make sure I'm not barking up the wrong tree first :)

**Comment by radare** [comment]
Installing stuff with r2pm without the -g shouldnt use sudo at all

**Comment by Bob131** [comment]
Huh. The particular issues I had in mind must be the yara makefile, now that I think about it everything else seems to have been reasonably well behaved. Sorry about that.

Regardless, I think the principle still applies. If an operation requires root privs, it should be up to the user to run it as such.

**Comment by radare** [comment]
If you run it with -g it will run with sudo. The user can always set SUDO to false if dont want to run anything as root.

**Comment by radare** [comment]
yes agree on that, it is trying to improve over time. but initially it was even worst :P

feel free to send patches for the specific packages you find that doesnt behave as expected

**Comment by Bob131** [comment]
Awesome, I'm glad you agree. I'll have a peruse around in the morn, see if there's any obvious low-hanging fruit :)

**Comment by Maijin** [comment]
@Bob131 ping(1)

**Comment by Maijin** [comment]
ping(2)

**Comment by radare** [comment]
This is fixed now with the -g thing
