### ISSUE TITLE
AVR: ioport changes inconsistent?

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5268]
This is regarding the new AVR IO register annotation/comments in an earlier commit https://github.com/radare/radare2/commit/4ebae2ee63fa3d698d114f7bdf45a04fb50e9c7b:

The `0x3f` mapping seems to go different for `in` and `out`, which shouldn't be (both should refer to `SREG`, not `TWI`, AFAIK):

![skarmavbild 2016-07-02 kl 14 44 51](https://cloud.githubusercontent.com/assets/175587/16540397/a6d54cba-4063-11e6-8819-d5a2449fd55d.png)

Unless I misunderstood the datasheet, since I defined `0x3F` as `SREG`-related, but have no clue what the parenthesis `(0x5F)` means in the Address column (perhaps different register mappings for `out` and (`in`) respectively?):

![skarmavbild 2016-07-02 kl 14 47 43](https://cloud.githubusercontent.com/assets/175587/16540405/f84ae500-4063-11e6-8fd8-a2fc57f39804.png)

Can some AVR expert shed some light into this?

**Comment by Darkkey** [comment]
The first address in datasheet is for accessing through I/O address space, the second (in parentheses) is for accessing using data address space.

SREG is 0x3F for in and for out. :) I don't know why there is a comment for IO TWBR at 0x3f. TWBR on mega8 AFAIK is at 0x00 (0x20). May be some bug in code?

All constants for different registers could be seen in def files of avra assembler (e.g. m8def.inc for mega8). However, they differ from model, to model (e.g. TWBR on atmega128 is 0x70). Thus, I think the best way here may be not to hardcode this tables in radare2 C code, but create a set of external scripts that could be run and set appropriate comment in code.

**Comment by Darkkey** [comment]
E.g. for my internal needs I use F# script that reads appropriate *.def file and then (using r2pipe) set comments for in/out and data manipulations. However it written in *VERY* awful way, so I don't want to publish it *SHAME*.

**Comment by brainstorm** [comment]
Feel free to share it privately, would love to have a look at it: brainstorm@nopcode.org ;)

**Comment by Darkkey** [comment]
@brainstorm Published
https://github.com/Darkkey/radare2-scripts

**Comment by radare** [comment]
Awesome!

**Comment by rpavlik** [comment]
FWIW, I have some even-cruder stuff: a python script that generates an r2 script for atmel XMEGA AU-series (looking primarily at XMEGA256A3BU code) IO port SFR memory mappings, just makes some flags. Very new to r2, so I'm sure I totally botched this, but it's yours to do what you wish with - I figured an expat license (aka "MIT") would be usable in case anything's interesting, but it's basically trivial stuff from the datasheets: search for 8331F–AVR to get the XMEGA AU general manual. Atmel-8362 is the A3BU manual in particular. https://gist.github.com/rpavlik/39ce21c329c99c837c2099f03c973f05

**Comment by Maijin** [comment]
Should be added in r2-extras + r2pm

**Comment by brainstorm** [comment]
@rpavlik Do you have it for more ICs? I see the pros of your approach (much lighter than requiring a F# installation from @Darkkey), but OTOH, https://github.com/Darkkey/radare2-scripts/tree/master/fsharp seems to leverage much more by parsing `avra` includes...

Ideally I would love to see that F# script ported to sth more commonplace like python and put in r2-extras + rpm as @Maijin suggested.

Alternatively, @rpavlik, do you think you can slurp those includes in your approach too? That would be awesome in terms of AVR IC coverage for radare :)

**Comment by rpavlik** [comment]
No, sorry, I literally just hacked that together this morning because I was sick of looking up the datasheet for everything that I suspected to be a SFR :stuck_out_tongue_winking_eye: I am a total noob at this intense of RE (currently trying in vain to inform r2 of the known function signatures of some functions so I don't have to reassemble arguments from registers in my head)

**Comment by brainstorm** [comment]
The original IO issue got fixed in https://github.com/radare/radare2/commit/0d3595e83ab6ff09a01fc84254e630d8e696568f ... I wish support was more comprehensive but oh, well, I'm with rpavlik, let's chip in support as needed ;)
