### ISSUE TITLE
Broken characters with pdi + certain themes

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5278]
What I mean:
https://asciinema.org/a/7axt7hdc13lo40vwl0hclbhtc

And asciinema doesn't really show it. What I'm actually seeing is not black, but:

```
0x00404990       bf00be6100  mov edi, [38;2;175;135
```

Also, visual mode and `pd` are unaffected.

**Comment by XVilka** [comment]
Please write a test

**Comment by monosource** [comment]
I wrote the following one in cmds:
```
NAME='pdi with behelit theme'
FILE=malloc://128
ARGS=
CMDS='
eco behelit
pdi 1
'
EXPECT='0x00000000             0000  add byte [rax], al
'
run_test
```

The problem is that the test passes, so I redirected the output of `pdi 1` into a file and in the file the expected value is there, not the broken one. Therefore, I suspect the issue is related to the way the information is displayed, not to the actual content of the information provided by `pdi`.

**Comment by radare** [comment]
Do this depend on terminal size?

**Comment by radare** [comment]
I guess thats a bug onhow certain rgb escape codes are parsed. Can you try to isolate the problem?

**Comment by monosource** [comment]
I'll keep looking into it. I've tried with different terminals, but none seem to render properly. Not sure how this could be isolated and how to test themes afterwards.

**Comment by Maijin** [comment]
Can't reproduce
