### ISSUE TITLE
VRRRRRR on windows execute command

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5292]
Just try to open a file then V and maintain R on windows, it will execute some info command.

**Comment by Maijin** [comment]
https://youtu.be/VUpkZPzmsfA

**Comment by radare** [comment]
cc @skuater

**Comment by skuater** [comment]
the problem become with the folder:  radare2-w32-0.10.4-git\share\radare2\0.10.4-git\cons\ 
In the release build have inside a "makefile" and r2 core try to interprete this file as color file, remove the makefile from cons folder.

**Comment by radare** [comment]
Fixed in be220ec03801b0ee414e0a1d47b7cc1c0e6240ec
