### ISSUE TITLE
rabin2 doesn't read the symbols correctly

### ISSUE THREAD

**Issue by soez** [radare/radare2#5300]
I have two diferents responses from readelf and rabin2.

```
$ rabin2 -s /usr/lib/debug/lib/arm-linux-gnueabi/libc-2.13.so | grep main_arena
vaddr=0x00008254 paddr=0x00008254 ord=2795 fwd=NONE sz=1100 bind=LOCAL type=OBJECT name=main_arena
$ readelf -s /usr/lib/debug/lib/arm-linux-gnueabi/libc-2.13.so | grep main_arena
2795: 00138254  1100 OBJECT  LOCAL  DEFAULT   31 main_arena
```

0x138254 != 0x8254

**Comment by radare** [comment]
thats only because of the base address. this lib is compiled with PIC i guess. so that’s fine because r2 doesnt assumes any default base address for those binaries because those can be mapped anywhere, not just 0x130000 like readelf assumes.

cc @alvaro_fe for confirmation

**Comment by alvarofe** [comment]
I get the same output here using greadelf in mac from binutils

```
air:Downloads alvaro$ greadelf -s libc-2.19_64bits.so |grep main_arena
  1120: 00000000003be760  2184 OBJECT  LOCAL  DEFAULT   31 main_arena
air:Downloads alvaro$ rabin2 -s libc-2.19_64bits.so |grep main_arena 
vaddr=0x003be760 paddr=0x001be760 ord=1120 fwd=NONE sz=2184 bind=LOCAL type=OBJECT name=main_arena
```

If your file differ from this one please attach here and i will look at it but i don't see nothing strange in the code maybe with 32 bits if that is the case something we are doing wrong but it should work the same way.

```
[0x00021fd0]> i~pic,type,file,arch,bits
type     DYN (Shared object file)
file     libc-2.19_64bits.so
pic      true
bintype  elf
arch     x86
bits     64
machine  AMD x86-64 architecture
```


Though i am seeing this one is arm so maybe the error is there so please share the file and i'll look at it

**Comment by soez** [comment]
This is the output for ubuntu 32 bit.

`noname@ubuntu:~$ readelf -s /usr/lib/debug/lib/i386-linux-gnu/libc-2.19.so | grep main_arena
  1329: 001ab420  1104 OBJECT  LOCAL  DEFAULT   31 main_arena
noname@ubuntu:~$ rabin2 -s /usr/lib/debug/lib/i386-linux-gnu/libc-2.19.so | grep main_arena
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
vaddr=0x00002420 paddr=0x00002420 ord=1329 fwd=NONE sz=1104 bind=LOCAL type=OBJECT name=main_arena
noname@ubuntu:~$ r2 -d /usr/lib/debug/lib/i386-linux-gnu/libc-2.19.so
Process with PID 2822 started...
attach 2822 2822
bin.baddr 0xb76f3000
Assuming filepath /usr/lib/debug/lib/i386-linux-gnu/libc-2.19.so
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
asm.bits 32
 -- Do you want to print 333.5K chars? (y/N)
[0xb76f50d0]> i~pic,file,type,arch,bits
type     DYN (Shared object file)
file     /usr/lib/debug/lib/i386-linux-gnu/libc-2.19.so
pic      true
bintype  elf
arch     x86
bits     32
`

[libc-2.19_32bits.so.zip](https://github.com/radare/radare2/files/351113/libc-2.19_32bits.so.zip)

**Comment by alvarofe** [comment]
Fixed in master
