### ISSUE TITLE
BigEndian support in the ELF parser

### ISSUE THREAD

**Issue by unixfreaxjp** [radare/radare2#5305]
## Background 

Currently radare2 ELF parser is supporting to read files saved in little-endian bytes storing system order only. So, in the the Linux system which its files is using big-endian the opcodes can not be displayed well. This will occur in the native 32bit systems Linux/MIPS (predefined cpu compiler macro: _ _ mips _ _ ) and native 32bit Linux/powerpc (predefined cpu compiler macro: _ _ powerpc _ _ ).

For example, after successful compilation in x32 Linux/powerpc (debian wheezy):
```asm
[0x10001c0c]> e asm.arch =ppc
[0x10001c0c]> e asm.arch
ppc

[0x10001c0c]> ie
[Entrypoints]
vaddr=0x10001c0c paddr=0x10001c0c baddr=0x00000000 laddr=0x00000000 type=program

1 entrypoints

[0x10001c0c]> pd 5
            ;-- entry0:
            0x10001c0c      ffffffff       fnmadd. f31, f31, f31, f31 <=== this
            0x10001c10      ffffffff       fnmadd. f31, f31, f31, f31
            0x10001c14      ffffffff       fnmadd. f31, f31, f31, f31
            0x10001c18      ffffffff       fnmadd. f31, f31, f31, f31
            0x10001c1c      ffffffff       fnmadd. f31, f31, f31, f31

[0x10001c0c]> b 100 ;x
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x10001c0c  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x10001c1c  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x10001c2c  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x10001c3c  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x10001c4c  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x10001c5c  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x10001c6c  ffff ffff                                ....
```
Or, in the system x32 Linux/MIPS:
```asm
[0x00404380]> e asm.arch=mips
[0x00404380]> e asm.arch
mips
[0x00404380]> pd 5
            ;-- entry0:
            0x00404380      ffffffff       invalid
            0x00404384      ffffffff       invalid
            0x00404388      ffffffff       invalid
            0x0040438c      ffffffff       invalid
            0x00404390      ffffffff       invalid
[0x00404380]> x!100
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00404380  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404390  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x004043a0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x004043b0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x004043c0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x004043d0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x004043e0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x004043f0  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404400  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404410  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404420  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404430  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404440  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404450  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404460  ffff ffff ffff ffff ffff ffff ffff ffff  ................
0x00404470  ffff ffff ffff ffff ffff ffff ffff ffff  ................
[0x00404380]>
```

## The development objectivity

The problem resides in the [ELF parser](https://github.com/radare/radare2/blob/182db54e57f58eb43391c5d98739638bf3567867/libr/bp/parser.c) related codes. 
The ELF parser is vital for ELF related analysis in radare2. This will need a major plastic-surgery-coding to support BigEndian.

## Current plan

According to @radare it is in  0.10.5 milestone. 
But this will also depend on machine preparation for his coding.

## Reference:
https://github.com/radare/radare2/issues/4969#issuecomment-230942943
https://github.com/radare/radare2/commit/af0a865d9f11ec80d7d7141d280f7c61622c3de1
https://github.com/radare/radare2/issues/4720#issuecomment-230424723

FYI Notification:
@XVilka @radare @crowell @zamaudio @Maijin

**Comment by zamaudio** [comment]
@unixfreaxjp ping: please recheck this i think i fixed some of these issues in 8efaec0

**Comment by unixfreaxjp** [comment]
Pong. checks started. CPU platform:  Linux/MIPS (predefined cpu compiler macro: `_ _ mips _ _` ) and native 32bit Linux/powerpc (predefined cpu compiler macro: `_ _ powerpc _ _` ).

**Comment by unixfreaxjp** [comment]
Linux/PowerPC test for radare2 v0.10.5 was completed.
RESULT: https://github.com/unixfreaxjp/dev/blob/master/r2ppc-7.md
1. Built...success
2. Big Endian parsing...success
3. Visual mode/Stepping/
4. Debug...ERROR: r_debug_reg: error reading registers
5. ESIL...ERROR: due to: Debug...ERROR: r_debug_reg: error reading registers

FYI Notification:
@XVilka @radare @crowell @zamaudio @Maijin

**Comment by radare** [comment]
We didnt touchdd the debugger at all. What was suposed to work is to statically analyze ppc elfs or x86 ones in a powerpc system. Which was not working before

**Comment by unixfreaxjp** [comment]
Big thanks so much for being able to do the static analysis on Linux/PPC!! :-) 
This is an awesome hard work. It is going to be VERY useful gentlemen!

> We didnt touchdd the debugger at all. What was suposed to work is to statically analyze
>  ppc elfs or x86 ones in a powerpc system. 
> Which was not working before

I am on preparing the MIPS test one now. 
Great work!

**Comment by Maijin** [comment]
Yep for the debugger there are separate issues.

**Comment by unixfreaxjp** [comment]
Yes, this is a very BIG leap already. Kudos r2 team.
Waiting for compiler result in MIPS now..

**Comment by unixfreaxjp** [comment]
Linux/MIPS x32 test for radare2 v0.10.5 was completed.
Built test is morelike the Linux/PPC one with only slightly different warning due to the diff platform codes compilation, so I guess I skipped the long report about that.

## Full Result
- https://github.com/unixfreaxjp/dev/blob/master/r2mips-2.md

## Summary
1. Built...success
2. Big Endian parsing...success
3. Visual mode... success
4. Debug...ERROR: r_debug_reg: function load error (expected)
5. ESIL...ERROR: due to disabling (expected)
*) so don't use this ver for debugging or vm w/ESIL, use other platform (non native for such tasks on MIPS binaries)

## Trouble shooting (this is noted for the long term further effort only, doesn't need to milestone) 
- [r_debug_reg] (https://github.com/radare/radare2/blob/1cab8b93b6140ae9a87d64c5d8d92ae66e29d8d2/libr/debug/reg.c) vs [Elf Parser]  (https://github.com/radare/radare2/blob/182db54e57f58eb43391c5d98739638bf3567867/libr/bp/parser.c)

## Notification:
@XVilka @radare @crowell @zamaudio @Maijin
