### ISSUE TITLE
Add support for AGC - Apollo-11 cpu

### ISSUE THREAD

**Issue by radare** [radare/radare2#5313]
# To be added in radare2-extras

The Lunar Apollo-11 NASA thing runs on top of an architecture named AGC. Here there are some source code to assemble:

https://github.com/chrislgarry/Apollo-11

There are also toolings for assembling and disassembling for this architecture, so it will be good to have at least support for disassemlbing in r2

https://github.com/alfonsokim/apollo-guidance-computer/blob/master/yaAGC/agc_disassembler.c

but having assembler, analyzer, emulator... would be even cooler ;)

**Comment by radare** [comment]
Read more http://www.ibiblio.org/apollo/yaYUL.html

**Comment by Maijin** [comment]
why is it on 0.10.5 👎

**Comment by radare** [comment]
Because it can be done in 20min or so, and its easy and fancy

**Comment by Maijin** [comment]
20min or so but still useless.

**Comment by Maijin** [comment]
I have added to be added in radare2-extras in the first msg.

**Comment by radare** [comment]
It is not useless for somebody who wants to learn how to write plugins for r2 and its a pretty coop target. Anyway. 20m of me are 2 weeks of you so dont complain that much for stuff that may help newcomers to learn and suggest solutions for the stuff u care

**Comment by radare** [comment]
Yep this should go in r2e

**Comment by Maijin** [comment]
https://github.com/chrislgarry/Apollo-11/issues/3

**Comment by ibabushkin** [comment]
I wanted to start contributing to radare2, so is this something viable to do? I'd work on it in such a case.

**Comment by Maijin** [comment]
@ibabushkin 

Take a look to:

https://github.com/radare/radare2/wiki/Implementing-a-new-architecture

and

https://github.com/radare/radare2-bindings/blob/master/libr/lang/p/test-py-asm.py

**Comment by radare** [comment]
Sure it is

**Comment by ibabushkin** [comment]
Alright, I'll start working on this.

**Comment by radare** [comment]
👍

**Comment by Maijin** [comment]
Closing this for now, rest of the issues should go in r2e
