### ISSUE TITLE
separate r_util.h to be several .h files, one for each "utility"

### ISSUE THREAD

**Issue by crowell** [radare/radare2#5314]
imo this makes it easier to find what you're looking for.

opinions?

**Comment by ret2libc** [comment]
I agree!

**Comment by radare** [comment]
Then use r_util_xxxxx.h or maybe just add a subdirectory.. I agree with that but didnt went for it because i though i prefered tocleanup the api and write units first

**Comment by crowell** [comment]
of course this will be a rather lengthy process. Let's move things as unit tests are done.

**Comment by crowell** [comment]
while this is done, the api functions should be documented in the header files, so that its easier to use them in the future.

**Comment by ret2libc** [comment]
i think they are put in the source files in many projects because they are closer to the code, so when you change it you should remember to update the doc too. If the doc is in the header, it may get out of sync soon.

**Comment by crowell** [comment]
Google style guide says to use header, so that's what in used to. I think
it makes sense that way because the .h is the API reference that you will
use when consuming the util

**Comment by ret2libc** [comment]
Yeah I know. Just saying.
I think there are two ways of seeing the problem. Linux, for example, puts docs in the source file.

**Comment by Maijin** [comment]
Done. Remain is:
* [ ] Look and clean the remaining mess (unused define and typedef) in r_util.h https://github.com/radare/radare2/blob/master/libr/include/r_util.h
* [ ] Transfer https://github.com/radare/radare2/tree/master/libr/util/t towards unit-test towards r2r

**Comment by crowell** [comment]
i think we can get rid of a lot of this crap leftover in r_util.h

`RSystem` for example has no consumers.

**Comment by Maijin** [comment]
@crowell done now need to move the util/t

**Comment by radare** [comment]
Yeah put it in your units

**Comment by Maijin** [comment]
yes, but it's long work.

**Comment by radare** [comment]
Dont think so

**Comment by Maijin** [comment]
well, very annoying for sure.

**Comment by radare** [comment]
Moving the files to the r2r repo would be a first step towards this and enough for now i guess

**Comment by Maijin** [comment]
Ok done. Will open an issue on r2r to convert all the /t/ stuff in proper unit test :)
