### ISSUE TITLE
Field xref not showing all references (Dalvik)

### ISSUE THREAD

**Issue by cryptax** [radare/radare2#5317]
On a (Android) Dalvik sample, I am trying to find the **cross references for a static field of a class**. Unfortunately, all the cross references are not showing properly (I know because I checked with another tool: [JEB decompiler](https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiow56aheTNAhXFExoKHUkxC80QFggeMAA&url=https%3A%2F%2Fwww.pnfsoftware.com%2F&usg=AFQjCNH14_2cFvsInCvkhlmnvSBRcI5rcw&sig2=HGBKN7mhcvWgCYqO-ld6oQ)).

This is the static constructor of the com.google.system.Const class (I have no clue what that ENABLED_STATE_SET is..). I am interested in **following the http://193.xxx string**. We see that it is assigned to the field "field+5555":

```
>pd 10 @sym.static.ENABLED_STATE_SET.Lcom_googie_system_Const_.ENABLED_STATE_SET._clinit_
/ (fcn) sym.static.ENABLED_STATE_SET.Lcom_googie_system_Const_.ENABLED_STATE_SET._clinit_ 122
|           0x000f99c8      1261           const/4 v1, 0x6
|           0x000f99ca      1200           const/4 v0, 0
|           0x000f99cc      6a00aa15       sput-boolean v0, field+5546
|           0x000f99d0      6a00ac15       sput-boolean v0, field+5548
|           0x000f99d4      6701ad15       sput v1, field+5549
|           0x000f99d8      13005802       const/16 v0, 0x258
|           0x000f99dc      6700ab15       sput v0, field+5547
|           0x000f99e0      1a001e31       const-string v0, str.http:__193.201.224.22:3000 ; str.http:__193.201.224.22:3000
|           0x000f99e4      6900b315       sput-object v0, field+5555
|           0x000f99e8      1210           const/4 v0, 0x1

```

How do I find the cross references for this field (+5555)?
I tried:

```
> axt sym.static.ENABLED_STATE_SET.Lcom_googie_system_Const_.ENABLED_STATE_SET._clinit_@field+5555
```

This tells me the field is used... in the static constructor - which is true. But it does not show any other reference. This is wrong, because as we can see below it is used to create a socket in a method inside class SockerService.

```
> pdf @ sym.EVEN_ODD.Lcom_googie_system_SocketService_._____certificate:_.getDescription
 0x000fc026      6202b315       sget-object v2, field+5555
|           0x000fc02a      5463e21a       iget-object v3, v6, field+6882
|           0x000fc02e      71207a433200   invoke-static {v2, v3}, sym.static.FLAG_STEREO_RESET.Lio_socket_client_IO_.FLAG_STEREO_RESET.socket_1
|           0x000fc034      0c02           move-result-object v2
|           0x000fc036      5b62e51a       iput-object v2, v6, field+6885
|           0x000fc03a      1a029d48       const-string v2, str.socket ; str.socket
|           0x000fc03e      1a038605       const-string v3, str.CREATE ; str.CREATE
```

By the way, the name of this method is wrong to my understanding. Why xxx certificate xxx getDescription?  The correct name is init() (smali: .method public init()V).

So anyway, **all the cross references for the field+5555 are not showing. Or probably I'm not using radare2 properly.**
You can download the sample from [http://contagiominidump.blogspot.fr/2016/07/overlay-banker-malware-locker.html](http://contagiominidump.blogspot.fr/2016/07/overlay-banker-malware-locker.html). Password is followed by the last character before the zip extension.
Sample: FF844A8BB40DA72B5C9F3A8C3CDA7C9D051921E6
_(Beware this is a malware)._

Finally, I am using:
radare2 0.10.4-git 11830 @ linux-x86-64 git.0.10.3-413-g8532e0c
commit: 8532e0c6da013f5ecba6fcfd4bea35c5d76bdb1f build: 2016-07-05

**Comment by radare** [comment]
Can you upgrade to the latest r2? Ill take a look in 2 weeks or so. If anyone have some time go ahead

**Comment by cryptax** [comment]
Hi, 

I upgraded today's version (same result concerning cross references).

radare2 0.10.5-git 11860 @ linux-x86-64 git.0.10.4-4-g46b0e3f
commit: 46b0e3f48e405cda34146cbe6c66a36183ba1e2b build: 2016-07-08

**Comment by radare** [comment]
Can you write a test case for r2r with a redistributable binary? I will try to have a look next week

**Comment by trufae** [comment]
i think this is fixed now. pls confirm
