### ISSUE TITLE
[DISCUSSION] Help menu inconsistency

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5322]
The contextual help is inconsistent.

### Capitalized vs. lowercase descriptions

```
| s                 Print current address
| s addr            Seek to address
| s-                Undo seek
```

```
| ab [hexpairs]     analyze bytes
| aa                analyze all (fcns + bbs) (aa0 to avoid sub renaming)
| ac [cycles]       analyze which op could be executed in [cycles]
```

### [num] vs. [N] vs. [n]
```
|Usage: pi[defj] [num]
```

```
| so [N]            Seek to N next opcode(s)
```

```
| wd [off] [n]       duplicate N bytes from offset at current seek (memcpy) (see y?)
```

### r_core_cmd_help vs. eprintf

```
eprintf ("Usage: ac [cycles]   # analyze instructions that fit in N cycles\n");
```

### <> vs. [] vs. nothing

```
| dbc <addr> <cmd>         Run command when breakpoint is hit
```

```
| at+ [addr] [times]  add trace for address N times
```

```
| s addr            Seek to address
```

## Proposal/Discussion

We need a specification for the help, such as:
- use `r_core_cmd_help`
- start descriptions using capital letters
- use [N] for things like number of instructions, [val] for values and [len] for string lengths
- etc.

As soon as it's decided, I'll start working on it.

**Comment by Maijin** [comment]
See #4459

**Comment by monosource** [comment]
That issue is somewhat related. It deals more with the separation between documentation and code, which I'm all for :+1: 

I was talking more about the content itself, not where it's stored and how it's fetched.

**Comment by radare** [comment]
Commands must be sorted alphabetical, and this means that lowecase goes first. And yep, rcorehelp must be used everywhere

**Comment by monosource** [comment]
Then I'll get on it this week.

Will do:
- Alphanumerical sorting
- Capitalized descriptions
- Use [] for things like [addr], [N], [len]

If there are other preferences, please state them.

**Comment by Maijin** [comment]
Can we close this now this now that you have the go @monosource ?

**Comment by monosource** [comment]
Sure. I'll come back with a PR soon (one week tops).
