### ISSUE TITLE
Integerating and autoloading flirt signatures into auto analysis

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#5331]
one case is for windows executables one might face something like this
radare output after `aa`

```
|           0x00402af3      6a10           push 0x10
|           0x00402af5      6880774100     push 0x417780
|           0x00402afa      e8c1d50000     call fcn.004100c0
```

versus ida output right after autoloading the file

```
push    10h
push    offset unk_417780
call    __SEH_prolog
```

versus radare output after loading the zignature file from here https://github.com/shoxxdj/HackingStuff/blob/master/Reverse/idademo68/sig/vcseh.sig

```
|           0x00402af3      6a10           push 0x10
|           0x00402af5      6880774100     push 0x417780
|           0x00402afa      e8c1d50000     call flirt.__SEH_prolog
```

it will be cool to have this done automatically and making these sig files shipped with r2

**Comment by radare** [comment]
We can enable this when the bin depends on no libs. When info-static is set

**Comment by Maijin** [comment]
Not after `aa` please. after `aaa` and `aaaa` yes.

**Comment by Maijin** [comment]
And we should use zignature.

**Comment by oddcoder** [comment]
actually this bin depends on some bins but this function is some kind of Visual C++ initialization

**Comment by Maijin** [comment]
The autoloading is already done, the rest is tracked under #7310 and #6947 already. Closing here
