### ISSUE TITLE
AVR: analysis ignores interrupt handlers

### ISSUE THREAD

**Issue by diggit** [radare/radare2#5334]
Analysis does not find interrupt handlers. They use `reti` instead of common `ret` instruction to return. As far as i understand, different return instruction shouldn't be a problem. (https://github.com/radare/radare2/blob/master/libr/anal/p/anal_avr.c#L316)
I don't see any other difference to common function.

Binary file attached. One of ignored interrupt handlers start on 0x30e and ends on 0x34c.

[mem_dump.zip](https://github.com/radare/radare2/files/366636/mem_dump.zip)

**Comment by diggit** [comment]
radare2 built from upstream, running on Archlinux.

**Comment by brainstorm** [comment]
I'm getting `invalid` insn around the offsets you mentioned:

![skarmavbild 2016-07-21 kl 11 26 38](https://cloud.githubusercontent.com/assets/175587/17018002/08972456-4f36-11e6-8e9d-5d00f13e3f3b.png)

Is that what you're seeing as well when opening the ihex with `r2 -a avr -b 8 dac_dump.raw`, @diggit or sth else?

**Comment by brainstorm** [comment]
Uh, sorry, that was unrelated, I'm seeing this:

![skarmavbild 2016-07-21 kl 11 36 55](https://cloud.githubusercontent.com/assets/175587/17018331/92786bde-4f37-11e6-80d6-5537c6323468.png)
![skarmavbild 2016-07-21 kl 11 37 05](https://cloud.githubusercontent.com/assets/175587/17018330/92782e58-4f37-11e6-96e4-aa4a8948a589.png)

Do you expect those to be annotated in some way in the comments? What is your current output and the expected one?

Cheers!

**Comment by brainstorm** [comment]
If you refer to ESIL flipping the interrupt bit in SREG as a result of `reti`, well, ESIL in AVR needs some work:

```
[0x00000576]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[0x00000000 esil_eq: invalid parametersences (aae)
0x00000002 esil_eq: invalid parameters
0x00000004 esil_eq: invalid parameters
0x00000006 esil_eq: invalid parameters
0x00000008 esil_eq: invalid parameters
0x0000000a esil_eq: invalid parameters
0x0000000c esil_eq: invalid parameters
0x0000000e esil_eq: invalid parameters
0x00000010 esil_eq: invalid parameters
0x00000012 esil_eq: invalid parameters
0x00000014 esil_eq: invalid parameters
0x00000016 esil_eq: invalid parameters
0x00000018 esil_eq: invalid parameters
0x0000001a esil_eq: invalid parameters
0x0000001c esil_eq: invalid parameters
0x0000001e esil_eq: invalid parameters
0x00000020 esil_eq: invalid parameters
0x00000024 esil_eq: invalid parameters
0x00000026 esil_eq: invalid parameters
0x0000002a esil_eq: invalid parameters
0x0000002c esil_eq: invalid parameters
0x00000030 esil_eq: invalid parameters
0x000000aa esil_eq: invalid parameters
0x000000d0 esil_eq: invalid parameters
0x000000d4 esil_eq: invalid parameters
0x000000d8 esil_eq: invalid parameters
0x000000ec esil_eq: invalid parameters
[x] Emulate code to find computed references (aae)
[Cannot find section boundaries in here
[x] Analyze consecutive function (aat)
[aav: Cannot find section at this address
aav: Cannot find section at this address
[x] Analyze value pointers (aav)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
```

**Comment by XVilka** [comment]
It would be awesome if you can reduce that `aac` to small regression tests.

**Comment by Maijin** [comment]
`aac` == `af @@ `pi len~call[1]`

**Comment by XVilka** [comment]
No, I meant particular opcodes or small sequences of them.

**Comment by Maijin** [comment]
Ah you mean aae then

**Comment by radare** [comment]
pls test and feedback

**Comment by Maijin** [comment]
51 [XX] tests https://s3.amazonaws.com/archive.travis-ci.org/jobs/147262837/log.txt

**Comment by radare** [comment]
should be green again. /me crosses fingers
