### ISSUE TITLE
python r2pipe Po + cmdj == bad

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#5339]
Hey,

After messing around with r2pipe and python, i've discovered the following problem.

Case 1 (works fine):
import r2pipe
r2 = r2pipe.open("/bin/ls")
r2.cmdj("ij")

Case 2 (exception):
import r2pipe
r2 = r2pipe.open("/bin/ls")
r2.cmd("Po stuff")
r2.cmdj("ij")

It appears that loading a project with "Po" from inside r2pipe changes the state where strange things get appended to the string output. In the later case, there are a bunch of invisible characters added on before the json portion, thus causing the exception.

**Comment by Owlz** [comment]
One more case...

Case 3 (also fails):
import r2pipe
r2 = r2pipe.open("/bin/ls",["-p","myproj"])
r2.cmdj('ij')

**Comment by radare** [comment]
please confirm, but its working for me now :)
