### ISSUE TITLE
ij command with debugging open

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#5340]
When debugging a program, either through "ood" or "-d", the "ij" command returns an invalid json object. Example:

'{"core":{"type":"EXEC (Executable file)","file":"/bin/ls","fd":40834,"iorw":true,"mode":"-rwx","obsz":0"referer":"dbg:///bin/ls","block":256,"format":"elf64"},"bin":{"havecode":true,"pic":false,"canary":true,"nx":true,"crypto":false,"va":true,"intrp":"/lib64/ld-linux-x86-64.so.2","bintype":"elf","class":"ELF64","lang":"c","arch":"x86","bits":64,"machine":"AMD x86-64 architecture","os":"linux","minopsz":1,"maxopsz":16,"pcalign":0,"subsys":"linux","endian":"little","stripped":false,"static":false,"linenum":true,"lsyms":true,"relocs":true,"rpath":"NONE","binsz":"5624324","compiled":"","dbg_file":"","guid":""}}'

Note that there is not a comma between "0" and "referer". Sadly, this means that cmdj and other json auto parsing will fail.

**Comment by Maijin** [comment]
Look at the fix please.

**Comment by Owlz** [comment]
Looks good to go. :)

**Comment by Maijin** [comment]
one char fix, could have been fix with the web ui of github :P.
