### ISSUE TITLE
RAP can't establish a connection

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5341]
1. Start rap server with `=:9090`
2. Try to connect radare2 with `r2 rap://localhost:9090`

It simply prints:
```
Connected to: localhost at port 9090
Cannot open 'rap://localhost:9090'
```

**Comment by radare** [comment]
because you have to specify the remote filename like this:
```
r2 rap://localhost:9090//bin/ls
```

**Comment by radare** [comment]
works for me

**Comment by radare** [comment]
ping?

**Comment by XVilka** [comment]
Yep, it works. Just a missing question - is that really needed? To specify the file?

**Comment by radare** [comment]
well.. the rap protocol doesnt really needs to specify an OPEN packet at the begining, so it should work withuot this too. in theory.. didnt tried much far from this

**Comment by m0nkeynut** [comment]
I just ran in to the same thing when I wanted to connect to the debugger but not open a file

This worked for me, connect to stdin instead `rap://localhost:9090/-`

**Comment by radare** [comment]
Looks like there are some problems with the rap protocol after the last changes, so writing is not possible, but this issue is fixed now
