### ISSUE TITLE
dbg_file in PE breaks json output

### ISSUE THREAD

**Issue by a0rtega** [radare/radare2#5342]
```
$ r2 ~/Documents/win7_shared/notepad++.exe                                                                               [14:18:12]
Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/COMCTL32.sdb
 -- bash: r3: command not found
[0x004d9f59]> ij
{"core":{"type":"EXEC (Executable file)","file":"/home/aortega/Documents/win7_shared/notepad++.exe","fd":7,"size":2055168,"mode":"-r--","obsz":0,"block":256,"format":"pe"},"bin":{"pic":true,"canary":false,"nx":true,"crypto":false,"va":true,"intrp":"","bintype":"pe","class":"PE32","lang":"","arch":"x86","bits":32,"machine":"i386","os":"windows","subsys":"Windows GUI","endian":"little","stripped":true,"static":false,"linenum":false,"lsyms":false,"relocs":false,"rpath":"","binsz":"2055168","compiled":"Mon Aug  3 21:44:30 2015","guid":"14EBA8385E1E428C87F52D13DD87BC8B1","dbg_file":"C:\sources\notepad-plus-plus\PowerEditor\bin\npp.pdb"}}

[0x004d9f59]>
```

In this output, the `dbg_file` route is interpreted as containing character escapes, which makes json parsers crash. This also affects r2pipe integration, at least in its python flavor.

Attached notepad++.exe binary for testing.
[notepad++.zip](https://github.com/radare/radare2/files/367814/notepad.zip)

**Comment by Maijin** [comment]
@a0rtega please look at the fix.

**Comment by yetmorecode** [comment]
A very similiar issue is also present for the raw filename in "ij". Like with calc.exe:

`{"core":{"type":"EXEC (Executable file)","file":"C:\Windows\System32\calc.exe", ...`

I didn't want to open a new ticket yet, but I somehow feel like it would be a good idea to escape json string literals in general (if that's somehow feasible). I can also open a new ticket for the issue above if that's preferred.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by yetmorecode** [comment]
Moin.

I tested with a fresh git build before posting. The issue is the non-escaped JSON string and external JSON parsers chocking on it, as it's non valid JSON actually.

**Comment by Maijin** [comment]
Open a new ticket, zip the binary in an archive and drag and drop it there
