### ISSUE TITLE
viewing memory of loaded module not working

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#5344]
Attempting to work with memory from a loaded module. In this case, the steps are basically:

```
r2 -AA <file>
ood
dbm <library.so> <offset> # this works fine
dc
myAddr = dmi  <library.so> <known symbol>
px @ myAddr
[0x7fa6df1443c0]> px @ 0x7fa6df1443c0
- offset -       0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x7fa6df1443c0  aa                                       .
```

I've checked against the memory map, and the memory should be there. The application is reading from the memory location, but r2 is not displaying anything. 

In this case, I was able to find the correct memory address by tracing the execution. However, the symbol address returned by the dmi command didn't match up with where I found the actual memory for this symbol in the running binary.

**Comment by radare** [comment]
Just change the blocksize with the b command

**Comment by Owlz** [comment]
Interesting. So that works. However, when doing the pv command it assumes a 32-bit pointer in a 64-bit application. Gives me 0xc8893c0 when it should be 0x0000f790c8893c0.

**Comment by Owlz** [comment]
Looks like pvz works correctly (at least giving me the full pointer). pv alone truncates it.

**Comment by radare** [comment]
Iirc pv honors asm.bits.. But cant remember without a shell if theres a pv subcommand for 64 bit values like pv8 or pV. Did you tried?

**Comment by Owlz** [comment]
Ah, ok pv8 works. For what it's worth, it's not clear from the"?" command on it that those modifiers exist (for pv at least).

**Comment by Maijin** [comment]
Then send a PR, you don't even need to clone to edit just use web edit if you're lazy ... https://github.com/radare/radare2/edit/master/libr/core/cmd_print.c

**Comment by Owlz** [comment]
kk. here it is: https://github.com/radare/radare2/pull/5360
