### ISSUE TITLE
q[y/n][y/n] options added #5326 doesn't work on linux when using ctrl+d

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5349]
Current implementation continue the execution when using ctrl+d without asking anything which can be problematic.

https://github.com/radare/radare2/commit/28acd1a83a1f3841e41754a8693d56d4d0b0d5d1

@Kodoque1

**Comment by Kodoque1** [comment]
I'll look into it.

**Comment by radare** [comment]
Please add tests

**Comment by Kodoque1** [comment]
As mentioned by @diouziou choice is encoded into ret value, hence the source of conflict. Are there any other method to pass value between cmd_quit.c and main radare2 loop?
