### ISSUE TITLE
Rename CSR disasm/anal into XAP4

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5355]
Also, like TMS320x family, XAPx is also a family - should be 'xap' arch and selectable 'xap4', 'xap5', 'xap6' 

CSR is a SoC, XAP is the actual RISC core, produced by [Campridge Consultants](https://en.wikipedia.org/wiki/Cambridge_Consultants)

See more https://en.wikipedia.org/wiki/XAP_processor

**Comment by radare** [comment]
This can be confusing to many people who is just used to refer to it as csr. But i understand thats a missconception. Maybe just exposing this in the xap description may clarify the problem. Also do we have any test for csr?

**Comment by Maijin** [comment]
Just do liken
`_dAe  8 16       6502        LGPL3   6502/NES/C64/Tamagotchi/T-1000 CPU`

and add CSR in the right column

**Comment by radare** [comment]
Thats a simple change. Can anyone send a pr for this to rename the plugin and related filenames to see if it breaks something?
