### ISSUE TITLE
troubles when quitting radare2

### ISSUE THREAD

**Issue by diouziou** [radare/radare2#5356]
i submit this issue so things don't get lost in irc logs...

quitting `r2 -d` with the `q` command or with `ctrl+d` seems to have problems due to the changes in `radare2.c`, see [https://github.com/Kodoque1/radare2/commit/28acd1a83a1f3841e41754a8693d56d4d0b0d5d1]

lines 961 to 964 do not seem to make sense, especially knowing that `ret` can be given any value by quitting the debugging session with `q ret`

there may be other problems, i don't know...

**Comment by Maijin** [comment]
Duplicate of https://github.com/radare/radare2/issues/5349 @Kodoque1

**Comment by diouziou** [comment]
sorry i did not see you had submitted an issue, so i close this one
