### ISSUE TITLE
ARM/Thumb-2 BL instruction decoded incorrectly

### ISSUE THREAD

**Issue by ynsta** [radare/radare2#5357]
Hello,

I have the following Thumb2 opcode  "f003ff0d" that should be decoded as "bl #+0x3e1a"

but I get with rasm2 -o 8001b6e -d -aarm -b16 f003ff0d
```
lsls r0, r6, 0xf
lsrs r7, r7, 0x17
```
instead of:
```
bl 0x800598c
```

Is there a way to force thumb2 mode ?

**Comment by alvarofe** [comment]
you are using -b 16 to tell thumb, are you sure that is the output? using www.onlinedisassembler.com to test i get the same as r2. However we use capstone and just writing a snippet produces the same

```
from capstone import *

CODE = b"\xf0\x03\xff\x0d" 

md = Cs(CS_ARCH_ARM, CS_MODE_THUMB)
for i in md.disasm(CODE, 0x1000):
    print("0x%x:%s\t%s\t%s" %(i.address, ''.join('{:02x}'.format(x) for x in i.bytes), i.mnemonic, i.op_str))
---
0x1000:f003     lsls    r0, r6, #0xf
0x1002:ff0d     lsrs    r7, r7, #0x17
```

**Comment by radare** [comment]
this is not an issue in r2, if so, a bug for GNU binutils and Capstone

**Comment by Maijin** [comment]
Can we close this as it is capstone only ?

**Comment by radare** [comment]
yep

**Comment by ynsta** [comment]
No, it is  a 32bits BL instruction in Thumb2 and not lsls + lsrs.

Please read ARMv7-M Architecture Reference Manual A7.7.18 (BL).

This is decoded this way

11110 0 0000000011 11 1 1 1 11100001101

BL   = 11110
S     = 0
imm10 = 0000000011
J1    = 1 so I1 = 0 
J2    = 1 so I2 = 0
imm11 = 11100001101

I1 = NOT(J1 EOR S); I2 = NOT(J2 EOR S); imm32 = SignExtend(S:I1:I2:imm10:imm11:'0', 32);
if InITBlock() && !LastInITBlock() then UNPREDICTABLE;

=> imm32 = 0b0000000000011111000011010
=> 0x3e1a

**Comment by radare** [comment]
Can you try with 'e asm.cpu=?' If it doesnt work with any of them i would suggest to open an issue at capstone
