### ISSUE TITLE
Web UI javascript files missing

### ISSUE THREAD

**Issue by seanthegeek** [radare/radare2#5359]
After installing from git, I get

File '/usr/share/radare2/0.10.5-git/www//p/lib/js/jquery-1.9.0.js' not found
[HTTP] 127.0.0.1:50092 /enyo/js/r2.js
File '/usr/share/radare2/0.10.5-git/www//enyo/js/r2.js' not found
[HTTP] 127.0.0.1:50094 /r2.svg
[HTTP] 127.0.0.1:50096 /enyo/icon.png

**Comment by radare** [comment]
The webui lives in another repo and its updated via make dist.
