### ISSUE TITLE
AVR: Duplicate IOPort UCSRA

### ISSUE THREAD

**Issue by Dreamdance61** [radare/radare2#5365]
Entry in file radare2/libr/syscall/ioports.c 
```
{ 0x0a, "UCSRA: USART Control and Status Register B."},
```
should be
```
{ 0x0a, "UCSRB: USART Control and Status Register B."},
```

**Comment by radare** [comment]
Send a pr. You can do this by just clicking the pencil icon in the github website

**Comment by Maijin** [comment]
And close your issue when resolve ;)
