### ISSUE TITLE
Warning for large .bss section

### ISSUE THREAD

**Issue by efthym** [radare/radare2#5368]
Hi,

This is just a minor issue I encountered recently.
I got a "Warning: Too big version info field XX (XXXX)" from 
radare2/libr/bin/format/elf/elf.c  line 782
while reading an elf file with a huge .bss section.
I think it is possible for a .bss section to be larger than the ELF file size itself, so the if statement in line 781 should only give the warning if the section is not .bss

Best,
Aris

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by efthym** [comment]
I got it from github at the end of June. Here's the output of r2 -v:
radare2 0.10.4-git 11754 @ linux-x86-64 git.0.10.3-359-gbfb0d62
commit: bfb0d6206e560a3e4b35db0c6db9dd1b896d850a build: 2016-06-30

I saw the warning message before opening the issue, so it is still there.

Thanks,
Aris

**Comment by Maijin** [comment]
this is too old. Last commit is 10 hours ago, please ensure you are using latest git release as stated.

**Comment by Maijin** [comment]
to update simply relaunch ./sys/install.sh, it will pull and update everything automatically.
