### ISSUE TITLE
pu: This block size is too big (52428800<1000000000). Did you mean 'pu @ -1000000000' instead?

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#5371]
morrn,

in libr/core/cmd_print.c teh format string in line 2024 seems wrong. (%d@%d)
using arbitrary big values I get funny messages like above. Switching to
unsigned does't help?

r2 -v
39907cd94ab2a4130f52e7dfc25ffed363038485

Greetings
--zlul

**Comment by radare** [comment]
offsets cant be negative, and block size can't be bigger than 4GB, the format string in there could be better. agree

**Comment by zonkzonk** [comment]
I totally forgot about PFMT macro :)
