### ISSUE TITLE
agj and overlapping function boundaries

### ISSUE THREAD

**Issue by a0x77n** [radare/radare2#5377]
Hi,

I did some analysis on the attached executable (/bin/cat) and noticed that `agj` returns the content of a different function:

```
> aaa
[output deleted]
> afl
[output deleted]
> agj @ sub.mbrtowc_f80
[{"name":"sub.__errno_location_f50, ... }]
```

A look at the function list (`afll`) reveals that `sub.mbrtowc_f80` is contained in the address bounds of `sub.__errno_location_f50`:
```
address     size  nbbs   cc   min bound range max bound   calls locals args xref frame name
=========== ==== ===== ==== =========== ===== =========== ===== ====== ==== ==== ===== ====
...
0x00405f50   78     8    7 0x00405f50    89 0x00405fa9     3    0      0    6     0 sub.__errno_location_f50
0x00405f80   18     3    3 0x00405f80    18 0x00405f92     0    0      0    2     0 sub.mbrtowc_f80
...
```

I looked at the code and found out that the content of the first function is returned that contains the provided address ( `sub.mbrtowc_f80`).

The same happens for other executables when one function is contained in another.

Here is the executable (/bin/cat) which produced the results: [sample.zip](https://github.com/radare/radare2/files/382057/sample.zip). 

Thanks for radare btw.

**Comment by Maijin** [comment]
Fixed
