### ISSUE TITLE
Show values of args and locals on every stackframe in the debugger

### ISSUE THREAD

**Issue by radare** [radare/radare2#5392]
this info should be showable at any time using the current register state (stack pointer) but also in the `dbt` output ... maybe dbtv to show the stack local/args of each stackframe.

This thing should be also showing in pf commands, when the `*` char is found in the command.

**Comment by oddcoder** [comment]
I will use `d` suffix to `afvr`, `afvs`, and `afvb` for display

**Comment by Maijin** [comment]
Wouldn't be better that `d` exposes the location and then you can choose the command i.e:
```
pd @ `afvrd local_660h`
pf.XXX @ `afvrd local_660h`
.... @ `afvrd local_660h`
```

**Comment by oddcoder** [comment]
that will involve too much typing plus no need
plus also it will need knowledge of types
```
; var my_struct_type local_20h @ rsp+0x20
```
If I would use d to just expose location i would also need way to resolve `my_struct_type`, too much steps to be done by user just to display args/locals value.
On the other hand what I intended to do is that the `d` will grab data `pf` format and also variable location then execute
```
afvbd local_20h
```
will be equivalent to 
```
pf pf_format_for_my_struct_type @ location_of_local_20h 
```

**Comment by radare** [comment]
if an afv subcommand shows that pf command via r_cons_printf, the user can just prefix the command with a dot to get the pf command executed.

**Comment by oddcoder** [comment]
yes exactly thats what I was going to do

**Comment by Maijin** [comment]
ok then
