### ISSUE TITLE
rax2 behavior of help

### ISSUE THREAD

**Issue by aijnn** [radare/radare2#5399]
### Problem 1: hello prints help

* [ ] Fix problem 1

In addition to `rax2 -h`, rax2 prints help on `rax2 h` and `rax2 ?`. But this same behavior happens when argument only starts with 'h' or '?':

```
# rax2 -h // shows help
# rax2 h // shows help
# rax2 foo // 0x0
# rax2 hello // shows help
```

Possible fixes (in /binr/rax2/rax2.c)
1. Change line 166 from `if (!flags) {`to `if (!flags && len == 1) {`, or
2. Change lines 167 and 169 from `==` to `strcmp` or similar
### Problem 2: when help is printed, other arguments are still used normally

* [ ] Fix problem 2

If one of the arguments implies help ("-h", "h", "?"), help will be printed but other arguments will still be used in normal way (not sure if this is intentional):

```
# rax2 12 13 -h 14
0xc
0xd
// Help is printed
0xe
```

Possible fixes:
1. Exit after `help ()`

### Problem 3: '-h' also prints usage, but 'h' and '?' do not
* [ ] Fix problem 3

Not sure if this inconsistency is intentional.

Possible fixes:
1. Move usage (line 157) to start of `help ()` (line 65)

_Note: I apologize if this things are intentional, feel free to close the issue in this case_

**Comment by monosource** [comment]
Yeah, this isn't consistent behavior. Also, noticed another minor quirk. `-b` and `-B-` are swapped help-wise.

**Comment by vraelvrangr** [comment]
Hello, I can fix this functionality. I will begin working on this.

**Comment by radare** [comment]
👍
