### ISSUE TITLE
Inconsistent representation of radiff2's output

### ISSUE THREAD

**Issue by submission-cgo16** [radare/radare2#5400]
Hello,

I am doing some malware analysis, and I would like to use `radiff2` to compare the function-level similarity of two binary code.

This is the radara2 I am using:

   ` radare2 0.10.5-git 11931 @ linux-x86-64 git.0.10.4-92-g2dbb3d8
   commit: 2dbb3d8fc6168f2319bb2a50864d346d0d286eb5 build: 2016-07-27
  `

The output of `radiff2` is some like this:

    `radiff2 -AC /bin/false /bin/true
    .....
    fcn.00400e00  24 0x400e00 | UNMATCH  (1.000000) | 0x400e00   24 fcn.00400e00
    ....
    `

According to the [doc](http://radare.today/posts/binary-diffing/),  1.000000 is the Percentage of matching, and I interpret 1.00000 as two functions are matched perfectly. 

However, I don't get why the corresponding output is "UNMATCH". Shouldn't it be "MATCH"??

**Comment by Maijin** [comment]
Dup of #5142 and #5388 it seems
