### ISSUE TITLE
Man page for r2agent

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5404]
* [x] Create a man page for r2agent
* [x] Delete https://github.com/radare/radare2/blob/master/binr/r2agent/README.md
* [ ] Something in the books
* [ ] Add r2agent -v to show version info

**Comment by Maijin** [comment]
@monosource want to look at this ?

**Comment by monosource** [comment]
Sure. I'll get to it soon.

**Comment by monosource** [comment]
@radare @Maijin Could you provide use cases and intended functionality for r2agent? I can only think of remote debugging/analysis and a quick way to start up the webserver.

**Comment by Maijin** [comment]
r2agent -h

**Comment by monosource** [comment]
Initiated with this PR https://github.com/radare/radare2/pull/5409 .
