### ISSUE TITLE
'pf f' command problem

### ISSUE THREAD

**Issue by reddevillg** [radare/radare2#5406]
function `r_print_format_float` in file libr/utils/p_format.c
should use `*(float*)&addr` instead of `(float)addr` ?

**Comment by Maijin** [comment]
For such micro edits, use the github web interface to edit: https://help.github.com/articles/editing-files-in-your-repository/

**Comment by reddevillg** [comment]
thanks for the tips.

**Comment by radare** [comment]
Should use a temporal intermediate variable

**Comment by radare** [comment]
Fixed in master
