### ISSUE TITLE
afr ignored calls

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#5408]
morrn

```
for x in /bin/*; do echo "== $x ==" >> ignored_call && r2 -qc "afr" $x 2>>ignored_call  ; done

== /bin/bash ==
Warning: ignore call 0x0041db90
== /bin/bunzip2 ==
Warning: ignore call 0x004012a0
== /bin/busybox ==
Warning: Cannot initialize dynamic strings
== /bin/bzcat ==
Warning: ignore call 0x004012a0
== /bin/bzcmp ==
== /bin/bzdiff ==
== /bin/bzegrep ==
== /bin/bzexe ==
== /bin/bzfgrep ==
== /bin/bzgrep ==
== /bin/bzip2 ==
Warning: ignore call 0x004012a0
== /bin/bzip2recover ==
Warning: Too big version info field 25 (1606208)
Warning: ignore call 0x00400970
== /bin/bzless ==
== /bin/bzmore ==
== /bin/cat ==
Warning: ignore call 0x004017b0
== /bin/chacl ==
Warning: ignore call 0x00400e50
== /bin/chgrp ==
Warning: ignore call 0x00401a20
== /bin/chmod ==
Warning: ignore call 0x00401780
== /bin/chown ==
Warning: ignore call 0x00401a90
== /bin/chvt ==
Warning: ignore call 0x00400890
== /bin/cp ==
Warning: ignore call 0x00403090
== /bin/cpio ==
Warning: ignore call 0x00402580
== /bin/dash ==
...
```

call to what is ignored?

Greetings
--zlul

**Comment by radare** [comment]
if (ref->addr == UT64_MAX || ref->addr < text_addr) {
                                                eprintf ("Warning: ignore call 0x%08"PFMT64x"\n", ref->addr);
                                                continue;
                                        }
i have changed the printf to show which call is this. so rerun and see if its an analysis issue or it is a fake call, maybe from data section or something like this.

**Comment by zonkzonk** [comment]
``
zlul@lulzmachine:/tmp$ cat ignored_call 
== /bin/bash ==
Warning: ignore 0x00420564 call 0x0041db90
== /bin/bunzip2 ==
Warning: ignore 0x00401eb4 call 0x004012a0
== /bin/busybox ==
Warning: Cannot initialize dynamic strings
== /bin/bzcat ==
Warning: ignore 0x00401eb4 call 0x004012a0
== /bin/bzcmp ==
== /bin/bzdiff ==
== /bin/bzegrep ==
== /bin/bzexe ==
== /bin/bzfgrep ==
== /bin/bzgrep ==
== /bin/bzip2 ==
Warning: ignore 0x00401eb4 call 0x004012a0
== /bin/bzip2recover ==
Warning: Too big version info field 25 (1606208)
Warning: ignore 0x00401524 call 0x00400970
== /bin/bzless ==
== /bin/bzmore ==
== /bin/cat ==
Warning: ignore 0x00402564 call 0x004017b0
== /bin/chacl ==
Warning: ignore 0x004016fe call 0x00400e50
== /bin/chgrp ==
Warning: ignore 0x00402144 call 0x00401a20
== /bin/chmod ==
Warning: ignore 0x00402644 call 0x00401780
== /bin/chown ==
Warning: ignore 0x00402244 call 0x00401a90
== /bin/chvt ==
Warning: ignore 0x00400a94 call 0x00400890
== /bin/cp ==
Warning: ignore 0x00403d74 call 0x00403090
== /bin/cpio ==
Warning: ignore 0x00402a34 call 0x00402580
== /bin/dash ==
Warning: ignore 0x00005054 call 0x00004a90
[..]
`` 

k, thanks, will look for sections.

**Comment by zonkzonk** [comment]
zlul@lulzmachine:/tmp$  objdump -D /bin/bash |grep 420564
  420564:       e8 27 d6 ff ff          callq  41db90 <__libc_start_main@plt>
zlul@lulzmachine:/tmp$ objdump -D /bin/bash |grep 041db90

**Comment by radare** [comment]
It points to the plt. I think that lower address valid should be the lowest executable section instead of just checking for .text like its done now. That will fix the issue because the plt is before the text..

**Comment by radare** [comment]
Should be fixed now... but recursivity is done wrong for now we are just walking 2 levels. need a rework on this, but maybe for 0.10.6, no time to mess too much things for this release i think

i will write a test, but more tests are welcome

**Comment by Maijin** [comment]
#4868

**Comment by zonkzonk** [comment]
no ignored calls:

```
$ grep -B1 Warn ignored_call 
== /bin/busybox ==
Warning: Cannot initialize dynamic strings
--
== /bin/bzip2recover ==
Warning: Too big version info field 25 (1606208)
--
== /bin/gzip ==
Warning: Too big version info field 25 (330376)
--
== /bin/nc ==
Warning: Too big version info field 25 (524792)
== /bin/nc.openbsd ==
Warning: Too big version info field 25 (524792)
== /bin/netcat ==
Warning: Too big version info field 25 (524792)
--
== /bin/ntfs-3g.secaudit ==
Warning: Too big version info field 24 (663880)
--
== /bin/ping ==
Warning: Too big version info field 25 (78792)
== /bin/ping6 ==
Warning: Too big version info field 25 (141384)
--
== /bin/ps ==
Warning: Too big version info field 25 (135016)
--
== /bin/static-sh ==
Warning: Cannot initialize dynamic strings
```

**Comment by radare** [comment]
This too big version field thing should be fixed too

**Comment by radare** [comment]
can u share any of those files that show this warning?

**Comment by zonkzonk** [comment]
morn, ofc:

**Comment by radare** [comment]
The recursive thing will require more time to do it. so just moving to 0.10.6, also i fixed that version header warning thing

**Comment by zonkzonk** [comment]
Thanks
