### ISSUE TITLE
aaa/aaaa fails do detect functions for some dumps

### ISSUE THREAD

**Issue by VPaulV** [radare/radare2#5413]
For some malware dumps r2 is not able to find any functions.
```
r2 -v
radare2 0.10.5-git 11945 @ linux-x86-64 git.0.10.4-106-g67b1e63
commit: 67b1e63ab3c70fe6240d99d0f50cef6d88fc913e build: 2016-07-28
```
```
 r2 heloag_2010-04-12_dump_0x00400000 
Warning: off > bin->size
Warning: off > bin->size
Warning: off > bin->size
Warning: off > bin->size
 -- Press any key to continue ...
[0x00401080]> aaaa
[Cannot find function 'entry0' at 0x00401080 entry0 (aa)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[0x00401189 ESIL infinite loop detectedences (aae)
...
[x] Emulate code to find computed references (aae)
[x] Analyze consecutive function (aat)
[aav: using from to 0x400000 0x41c000
Using vmin 0x401000 and vmax 0x41b400
aav: using from to 0x400000 0x41c000
Using vmin 0x401000 and vmax 0x41b400
[x] Analyze value pointers (aav)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[0x00401080]> 

[0x00401080]> afl~?
0
[0x00401080]>
```
IDA detects 68 functions for this sample.
[sample.zip (password infected)](https://github.com/radare/radare2/files/388541/sample.zip)

**Comment by VPaulV** [comment]
```
[0x00401080]> iS
[Sections]
idx=00 vaddr=0x00401000 paddr=0x00001000 sz=8192 vsz=8192 perm=m-rw- name=.text
idx=01 vaddr=0x00403000 paddr=0x00003000 sz=4096 vsz=4096 perm=m-rw- name=.rdata
idx=02 vaddr=0x00404000 paddr=0x00004000 sz=77824 vsz=77824 perm=m-rw- name=.data
idx=03 vaddr=0x00417000 paddr=0x00017000 sz=4096 vsz=4096 perm=m-rw- name=.CRT
idx=04 vaddr=0x00418000 paddr=0x00018000 sz=8192 vsz=8192 perm=m-rw- name=.aspack
idx=05 vaddr=0x0041a000 paddr=0x0001a000 sz=4096 vsz=4096 perm=m-rw- name=.adata
idx=06 vaddr=0x0041b000 paddr=0x0001b000 sz=1024 vsz=1024 perm=m-rw- name=.idata

7 sections
```

**Comment by Maijin** [comment]
Looks like no section marked as executable ? Maybe the issue?

**Comment by VPaulV** [comment]
Yes, looks like. I checked other samples and none of them has sections marked as executable.

**Comment by Maijin** [comment]
Try to change that and see

**Comment by VPaulV** [comment]
Hm, looks like it is not the reason. I found samples without sections where functions detection works as should. Should I add such example?

**Comment by Maijin** [comment]
Nop, just find out what makes this sample doesn't work is what matters.

**Comment by radare** [comment]
e anal.hasnext=true

**Comment by VPaulV** [comment]
>e anal.hasnext=true
Unfortunately, it doesn't help.

**Comment by radare** [comment]
try with `e anal.noncode=true`

**Comment by VPaulV** [comment]
A little bit better, 4 functions are detected.

**Comment by radare** [comment]
if youa re analyzing raw dumps i would just do the following:


e anal.calls=true
e anal.hasnext=true
e anal.noncode=true
s beginOfCode
afr

afl~?

but that depends on the arch.. im assuming x86 here. if its for other archs, maybe aap or aae will be helpful

aac is also pretty handy in many situations. try to avoid using aaaaaaaa stuff because its the dumb way to analyze code without understanding whats going on

**Comment by VPaulV** [comment]
afr doesn't work. But finally with those settings I was able to get affordable results. Thank you!

>  try to avoid using aaaaaaaa stuff because its the dumb way to analyze code without understanding whats going on
I use r2 for automatic analysis and cannot set individual settings for each sample, so I decided that for tests it would be enough to just run aaaaa stuf.

**Comment by radare** [comment]
👍
