### ISSUE TITLE
Linux coredump warning

### ISSUE THREAD

**Issue by l4l** [radare/radare2#5418]
Is [it](https://github.com/radare/radare2/blob/master/libr/debug/p/native/linux/linux_coredump.c#L627) a good idea to overrun a buffer ([def here](https://github.com/radare/radare2/blob/master/libr/bin/format/elf/glibc_elf.h#L89))?

```c
// definition
typedef struct
{
  unsigned char	e_ident[EI_NIDENT];	/* Magic number and other info */
  Elf64_Half	e_type;			/* Object file type */

//..

// weird overrun
	/* buffer overrun here */
	h->e_ident[EI_NIDENT] = EI_NIDENT;
	h->e_type = ET_CORE;
```

**Comment by radare** [comment]
It is never a good idea. Mind to send the fix?

 There are no tests for this functionality but it will be required to confirm that growing the buffer will be a good fix or just decreasing the index.. M
