### ISSUE TITLE
Strange -m behaviour

### ISSUE THREAD

**Issue by VPaulV** [radare/radare2#5442]
https://asciinema.org/a/a9adhb68mr998dn2z0ratndrs
[sample.zip (password - infected)](https://github.com/radare/radare2/files/399789/sample.zip)

**Comment by Maijin** [comment]
Add detail of the issue please

**Comment by VPaulV** [comment]
As you can see from the asciinema when -m is used files is mapped twice somehow. (At least it is how I understood this behaviour).

**Comment by MaskRay** [comment]
Seems to be fixed.

No longer two functions at 209c20 & 409c20
