### ISSUE TITLE
Expression multiplication floating point fail

### ISSUE THREAD

**Issue by modrobert** [radare/radare2#5449]
There seems to be a floating point bug whenever an **even** number is multiplied with **1.5** using expression in radare2, odd numbers seems to work.

[0x004402bd]> ? 2*1.5
2 0x2 02 2 0000:0002 2 00000010 2.0 2.000000f 2.000000

[0x004402bd]> ? 3*1.5
3 0x3 03 3 0000:0003 3 00000011 4.5 4.500000f 4.500000

[0x004402bd]> ? 4*1.5
4 0x4 04 4 0000:0004 4 00000100 4.0 4.000000f 4.000000

[0x004402bd]> ? 5*1.5
5 0x5 05 5 0000:0005 5 00000101 7.5 7.500000f 7.500000

**Comment by mrmacete** [comment]
cool, it seems unrelated to multiplication, it's more about float representation:

```
[0x00000000]> ? 1.5 + 1.5
2 0x2 02 2 0000:0002 2 00000010 2.0 2.000000f 2.000000
```

**Comment by radare** [comment]
just confirmed that the value is correctly computed inside calc.c, digging a bit more to find the issue

**Comment by radare** [comment]
hehe found the bug, pushing fix in 3..2..

**Comment by modrobert** [comment]
```
 .--.     .--------.
 | _|     |        |
 | O O   <  Great! |
 |  |  |  |        |
 || | /   `--------'
 |`-'|
 `---'
```

**Comment by radare** [comment]
Can u please add tests for this?

**Comment by modrobert** [comment]
OK, adding test to: radare2-regressions/t/cmd_help

**Comment by modrobert** [comment]
Just did a pull request, first time using github, hope I didn't break something. ;)
