### ISSUE TITLE
Add visual seek (o) suggestions and tab-completion

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5456]
Similar to how `s sym.<TAB>` works. I know you can do `: s sym.<TAB>` in visual mode, but `o sym.<TAB>` would be faster.

**Comment by Maijin** [comment]
Don't use that, use `VF_`

**Comment by radare** [comment]
I would go for hud mode. How does it sounds?

**Comment by monosource** [comment]
HUD mode is pretty good for navigating flagspaces. I should use it more often, thanks!

**Comment by Maijin** [comment]
@radare what about replacing `o` with HUD ?
