### ISSUE TITLE
AVR: SBRS/SBRC before RJMP breaks function analysis

### ISSUE THREAD

**Issue by Blackjak34** [radare/radare2#5471]
The SBRS/SBRC instructions skip the following instruction (PC += 2/3) if a bit in a register is set/clear. But if the instruction is before RJMP (and probably others) it is still treated as an unconditional jump, so the blocks after RJMP are not analyzed. Attached binary has a function at 0x428e with SBRS instruction at 0x4302, for example.

[binary.zip](https://github.com/radare/radare2/files/408175/binary.zip)

**Comment by Maijin** [comment]
@killabytenow sen this ?

**Comment by killabytenow** [comment]
These pair of instructions are not implemented in the old implementation neither in mine. I will take a look into the binary, but I will try prioritize the implementation of these instructions and include them in the next PR.

**Comment by killabytenow** [comment]
Working on this issue:

https://github.com/killabytenow/radare2/blob/git-pull-of-my-branch/libr/anal/p/anal_avr.c

Try to pull of this branch and try... this patches should fix your issue.

**Comment by radare** [comment]
i will pull your branch this weekend :*

**Comment by Maijin** [comment]
So fixed ?

**Comment by radare** [comment]
cc @killabytenow

**Comment by killabytenow** [comment]
it should be fixed.. don't know now :P

**Comment by killabytenow** [comment]
in theory the opcodes are implemented, now they are conditional jumps, and they should work well

but I cannot test it now

**Comment by Maijin** [comment]
@Blackjak34

**Comment by Blackjak34** [comment]
Tested with the binary in OP, looks like it works now

**Comment by killabytenow** [comment]
Nice! Thanks!
