### ISSUE TITLE
x86 linux debugger: jmp register not followed

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5472]
[jmpeax.zip](https://github.com/radare/radare2/files/409042/jmpeax.zip)

```
$ r2 -d ./jmpeax
[0xf7796d00]> dcu main
[0x0804840f]> aaa
[0x0804840f]> pdf
╒ (fcn) eip 15
│           0x0804840f      55             push ebp
│           0x08048410      89e5           mov ebp, esp
│           0x08048412      681e840408     push loc.main_leave ; loc.main_leave ; loc.main_leave
│           0x08048417      b800840408     mov eax, loc.func           ; "U..h|..........U..h....." @ 0x8048400
╘           0x0804841c      ffe0           jmp eax
[0x0804840f]> 4ds
[0x0804841c]> ds
Hello World
```

It immediately executes the function at address eax and returns from it.

EDIT: Important to note that if I do `dcu loc.func`, it reaches that point. It just doesn't step to it when stepping the instruction `jmp eax`.

**Comment by radare** [comment]
Can you write a test case for r2r?

**Comment by monosource** [comment]
Still broken.

**Comment by Maijin** [comment]
It's still being worked on by @saucec0de on #5802

**Comment by Maijin** [comment]
Add tests please

**Comment by saucec0de** [comment]
Yes, pr #5802 fixes these issues. Tests have been added in radare/radare2-regressions/commit/6bcc48dea4ac391e14e4b5ba95c51c9efee2d188 where I have crafted a binary that tests all sorts of call and jmp.

**Comment by saucec0de** [comment]
#5802 was merged. issue can be closed
