### ISSUE TITLE
Missing dlls / sdbs

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5486]
I installed the brew version first and when it gave me an error, I tried the source code instructions from the main website (i.e. git clone, sys/install.sh).

  - 0.10.5-git/format/dll/gsprop32.sdb
  - 0.10.5-git/format/dll/mfc90u.sdb
  - 0.10.5-git/format/dll/spr32d70.sdb

**Comment by radare** [comment]
i dont know if those libs come in default windows installations, if so, we should cache their imports in there, can you share the binary and those dlls? otherwise you will need to do that in your side.

**Comment by DanTheColoradan** [comment]
Ahhh. K. I will check.

**Comment by DanTheColoradan** [comment]
[gsprop32](http://www.solvusoft.com/en/files/missing-not-found-error/dll/windows/microsoft/windows-nt-workstation-4-0-nl/gsprop32-dll/) - "associated with Windows NT Workstation 4.0 NL"

[mfc90u](http://pcsupport.about.com/od/findbyerrormessage/a/mfc90u-dll-not-found-missing-error.htm) - "a file that's part of the MS Visual C++ runtime library"

[spr32d70](http://support.guptatechnologies.com/supportforum/viewtopic.php?p=1727&sid=2118a3b8778e8a996b8c34ad06dfe9ee) - looks to be from Far Point

Default windows might include gsprop32 but not mfc90u, and definitely not spr32d70. Is the right?

**Comment by DanTheColoradan** [comment]
Attached is the installer [installer](https://github.com/radare/radare2/files/415860/issue-5486-installer.zip). I'll go ahead and see if I can zip up the whole program too.

**Comment by DanTheColoradan** [comment]
Attached is just the [binary and the dlls].(https://github.com/radare/radare2/files/415895/issue-5486-dlls-bin.zip) If you would like the whole program folder, I could try and attach that too, but it's probably too big.

**Comment by Maijin** [comment]
If you want to help on this, just extract the ordinal like https://github.com/radare/radare2/tree/master/libr/bin/d/dll and do a pull request. You can even do that by using upload button on github web.

**Comment by DanTheColoradan** [comment]
Which ones would you like that for?

Also, could you give me a little more direction on how to do that? I assume [this](https://msdn.microsoft.com/en-us/library/e7tsx612.aspx) is what you are talking about, but I've never exported before and need a bit more guidance / link to a tutorial / whatever :)

**Comment by DanTheColoradan** [comment]
Looks [dumpbin](http://stackoverflow.com/questions/1548637/is-there-any-native-dll-export-functions-viewer) from visual studio might work. Let me know if I'm on the wrong track.

**Comment by Maijin** [comment]
Just use a tool like `dependency walker` or `dumpbin` to get the ordinals and add sdb.txt stuff in a PR just like the example I sent to you ;) Also just don't forget to add them in the Makefile and should be good to go.

**Comment by Maijin** [comment]
You can always try on an existing one.

**Comment by DanTheColoradan** [comment]
@Maijin winedump on OS X works well but which dlls would you like a pull request for? All of them?

**Comment by Maijin** [comment]
All the one you said were missing !

**Comment by Maijin** [comment]
👍

**Comment by DanTheColoradan** [comment]
With mfc90u.dll, I get the following:

```
=== EXPORTS ===

# module "mfc90u.dll"
# flags=0x0  ts="2009-07-12 03:17:40"  version=0.0  ord_base=256
# nFuncs=13112  nNames=0

  ORD ENTRY_VA  NAME
  100    c4b3e  
  101    c4be8  
  102    5b121  
  103    5b151  
  104    5b0cb  
  105    5b1e5  
  106    5b17e  
  107    5b105  
  108    c4b7f
...
```

I tried several different tools and all did the same. Is this right? Or is there something else I need to do?

**Comment by Maijin** [comment]
Check the existing stuff and you will see

**Comment by DanTheColoradan** [comment]
For the existing files, I don't see any that have the ordinal number but nothing for the function name ☹️ The other dlls I was able to produce ord and func names for. mfc90u.dll is the only one that gives me no names for exports.

http://hastebin.com/raw/awomobufum

**Comment by Maijin** [comment]
For existing one, I was saying those https://github.com/radare/radare2/blob/master/libr/bin/d/dll/msvbvm60.sdb.txt for example so you can see if your tool is doing your job

**Comment by DanTheColoradan** [comment]
As you can see [here](http://hastebin.com/raw/yifabiwijo) for spr32d70 and [here](http://hastebin.com/raw/uruvuliqoy) for gsprop32, I get valid results. It's only mfc90u that I get a big list of ordn but without names.

So perhaps if someone could try to export mfc90u with dumpbin natively, that would help? I don't have the HD space to install Visual Studio.

**Comment by Maijin** [comment]
Then for the one that succeed go make a PR ! 😄

**Comment by Maijin** [comment]
for mfc, try to see with other version

**Comment by Maijin** [comment]
If you can't find the ordinals, just create an empty file + Makefile should be enough to temporary discard the message while waiting for someone to complete it.

**Comment by DanTheColoradan** [comment]
K. And by another version, do you mean from a different version of Visual C++? That's my assumption and I'll give a try.

**Comment by Maijin** [comment]
* https://download.dll-files.com/a76104d8d9aba3670fd3cea603d70ada/mfc90u.zip?0XJdODXKdW
* https://download.dll-files.com/ca6ade4f7761bb15b3325356dc3b82bb/mfc90u.zip?0XJdODXKdW
etc.

**Comment by radare** [comment]
My assumption is that this thing can probably tend to infinite, so it will be good to have a dir in extras repo and an r2pm pkg to install those extra dll ordinal descriptions. To avoid having them in rcore

**Comment by Maijin** [comment]
Nop in fact I've tested on a very large amount of samples and it's becoming really rare there is like a dozen missing for 10k samples. It's for like a log something

**Comment by DanTheColoradan** [comment]
How is the size? And will r2 search the exe's (for example) directory or the current directory for sdb?

**Comment by Maijin** [comment]
1) Check if you can get ordinals
2) If yes add them if not just create blank+makefile temporary
3) close this issue

**Comment by DanTheColoradan** [comment]
k

**Comment by DanTheColoradan** [comment]
Oops. Need to do the makefile.

**Comment by DanTheColoradan** [comment]
Ok. It should be all set. Let me know if there are any issues.

**Comment by Maijin** [comment]
thanks
