### ISSUE TITLE
radare_2_phase_2_bomb_diffusion

### ISSUE THREAD

**Issue by oviche** [radare/radare2#5487]
i start working with radare2 recently .. i am trying to solve phase_2 from bomb diffusion .. when i try to jump over function ( read_six_numbers ) ... jump over failed and cause something wrong that in picture
![r22](https://cloud.githubusercontent.com/assets/20806107/17637605/01412fce-60e5-11e6-9b25-f2f1c1bc4eab.PNG)

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by oviche** [comment]
@Maijin  
that what i get after ... **r2 -v** command
radare2 0.10.5-git 11987 @ linux-x86-64 git.0.10.4-147-g95283d5
commit: 95283d5531aefa7160e720ec7af86d4a6dec8249 build: 2016-08-04

**Comment by Maijin** [comment]
Now please detail the command you used and/or record and https://asciinema.org/.

**Comment by oviche** [comment]
@Maijin
 https://asciinema.org/a/0ff8n6g3oha583aw7xq82gnxr 
the record is here .. i don't do the last jump over because the terminal go into infinite loop like in picture  and i can't stop it ..

**Comment by Maijin** [comment]
Unrelated, I strongly suggest you learn how to use rarun2 to use a different pty as stdin. See `man rarun2`.

**Comment by oviche** [comment]
@Maijin 
thanks , i will learn it

**Comment by radare** [comment]
Libreoffice impress aproves

**Comment by Maijin** [comment]
@saucec0de can you check if this is fixed ?

**Comment by radare** [comment]
Ping

**Comment by saucec0de** [comment]
sorry delay. yes, i will check if fixed...

**Comment by saucec0de** [comment]
on radare2 latest, i could not reproduce the issue. the step-over is executed correctly on my machine and no crazyness happens.  as such, i can recommend the issue too be closed.
