### ISSUE TITLE
Assembler todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5496]
- [ ] Embed bits/arch/endian in a separated structure
  - So one can change from one arch to another with a pointer
  - Cool for defining ranges of memory
- [ ] radare2
  - Import msdn doc as comments

As per #5424.

**Comment by radare** [comment]
Theres an issue aready for that in github.

And the msdn thing is totaly unrelated to this bitarch thing
