### ISSUE TITLE
Function local flags are not stored in the project file

### ISSUE THREAD

**Issue by bluec0re** [radare/radare2#5526]
The project management misses to save function local flags. They are currently lost if the session is restarted.

**Comment by oddcoder** [comment]
what flags? can you give an example?

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by bluec0re** [comment]
Seems like this fix solved the problem only partially. `f.*` seems to be context specific and is showing only the local flags of the current function. After trying around, `f.**` seems to put out all the flags.

**Comment by radare** [comment]
oh right! i missed that :) it should be fixed now in master

thanks!
