### ISSUE TITLE
Visual renaming of local variables and arguments

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5528]
Renaming vars and args takes forever using `afv[rbs]` for each and every one. It would be nice to have a quick way of doing this in visual mode and graph mode. Something like `da` or `dv`, which would work like `dr` but for local vars and args.

Even better would be to have something like the cursor to navigate over the arg/var and rename it. Would be pretty fast.

**Comment by radare** [comment]
this is already possible in different ways in visual mode but the mot common is:

move cursor to the instruction and press `d` and then `n`.


**Comment by Maijin** [comment]
Yep already possible: https://asciinema.org/a/0z4m2ldljcu7oiuyusrfbiajg .

**Comment by radare** [comment]
Well maybe he have a suggestion for better supporting this. And didnt tried with arguments

**Comment by monosource** [comment]
Thanks for the demonstration @Maijin
