### ISSUE TITLE
ESIL: Bad Trap on MIPS ADDI 

### ISSUE THREAD

**Issue by Jaguar83** [radare/radare2#5530]
ADDI on MIPS produces invalid ESIL.

issue appears to be in libr/anal/p/anal_mips_cs.c on line 250:

```
			r_strbuf_appendf (&op->esil, "0,32,%s,0xffffffff,&,%s,+,>>,>,?{,1,TRAP,}{,%s,%s,+,%s,=,}",
				ARG(2), ARG(1), ARG(2), ARG(1), ARG(0));
```

I think it should be

```
			r_strbuf_appendf (&op->esil, "0,32,%s,0xffffffff,&,%s,+,>>,>,?{,$$,1,TRAP,}{,%s,%s,+,%s,=,}",
				ARG(2), ARG(1), ARG(2), ARG(1), ARG(0));
```

**Comment by radare** [comment]
Can you send a PR? Just click the pencil icon in github page of that specific file and it will do all the things automatically

**Comment by Jaguar83** [comment]
Done. Sorry, I'm kinda new at this.
