### ISSUE TITLE
[AVR] Random strings and "unaligned" stuff

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5534]
I have no idea why strings and unaligned opcodes started appearing in my AVR reveng project. Interestingly those two seem to affect `push` and `pop` opcodes/boundaries:

![skarmavbild 2016-08-16 kl 08 33 05](https://cloud.githubusercontent.com/assets/175587/17690044/3e2d90cc-638c-11e6-8b97-56d172ab157a.png)

![skarmavbild 2016-08-16 kl 08 35 34](https://cloud.githubusercontent.com/assets/175587/17690082/884a5ffa-638c-11e6-8dda-4ebba4eaf4e3.png)

Any hints/ideas on where should I start chasing this bug?

**Comment by oddcoder** [comment]
probably it is but withen pdf itself

**Comment by brainstorm** [comment]
@oddcoder, you have my project files, can you confirm this bug?

**Comment by oddcoder** [comment]
it is the project file 
Most likely where the bug is so I would recommend redoing the analysis again or trying to fix the project file because without the project file everything seams to work
![screenshot at 2016-08-16 09-37-47](https://cloud.githubusercontent.com/assets/10424605/17691508/8e20575c-639d-11e6-93de-94b46ea5cfe6.png)

**Comment by brainstorm** [comment]
Happy ending! It was just the `Cs` strings, possibly introduced as a side-effect and artifact of the AVR-specific comments feature.

![cs](https://cloud.githubusercontent.com/assets/175587/17695869/f2d351ce-63aa-11e6-93bd-5c8c41268317.jpg)

After removing those from the project and a few other commits by @radare, it's fixed now:

![skarmavbild 2016-08-16 kl 12 10 20](https://cloud.githubusercontent.com/assets/175587/17695846/cad613d2-63aa-11e6-9dec-7eed3472c44e.png)
