### ISSUE TITLE
Cygwin-built radare2.exe adds superfluous newlines in ConEmu

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5553]
If I run radare2.exe built in Cygwin using conemu (choose Cygwin bash start) it adds an additional newline each line:
![conemu](http://xvilka.me/r2-cygwin-conemu.png)

At the same time, file built in Cygwin ran in mintty from Cygwin works perfectly, not adding any additional new lines

**Comment by radare** [comment]
you can proabbly fix this by tuning the scr.fix_columns

**Comment by XVilka** [comment]
Yes, will try. Storing this not to forget this rare scenario.

**Comment by radare** [comment]
this was a pretty common issue on some closed source terminals for iOS, so i added this var to play with this errors in order to find the problem without having to recompile all the time

**Comment by radare** [comment]
cc @skuater

**Comment by XVilka** [comment]
Closing since removing Cygwin support https://github.com/radare/radare2/issues/9973
