### ISSUE TITLE
build error with latest release 0.10.5

### ISSUE THREAD

**Issue by rofl0r** [radare/radare2#5559]
first weirdness, no error yet though:
```
make[3]: Entering directory /src/build/radare2/radare2-0.10.5/shlr/sdb'          
echo '#define SDB_VERSION "0.10.4"' > src/sdb_version.h
```
second weirdness:
even though a crosscompiler is used and `--host=x86_64-linux-musl` is passed to configure, ar and ranlib are used without cross prefix (doesnt cause build error due to luck since ar and ranlib happen to be x86_64 as well)
```
x86_64-linux-musl-gcc -L/x-prefix/x86_64/lib -isystem /x-pr....
ar q libr_z.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftree...
ar: creating libr_z.a
ranlib libr_z.a
```
then debruijn.c invokes UB:
```
debruijn.c: In function 'r_debruijn_pattern':
debruijn.c:77:4: warning: format '%lld' expects argument of type 'long long int', but argument 3 has type 'int' [-Wformat]
debruijn.c:93:3: warning: format '%lld' expects argument of type 'long long int', but argument 3 has type 'int' [-Wformat]
debruijn.c: In function 'r_debruijn_offset':
debruijn.c:105:6: warning: variable 'n' set but not used [-Wunused-but-set-variable]
```
what finally fails is:
```
cd capstone ; git reset --hard
fatal: Not a git repository (or any of the parent directories): .git
make[1]: [capstone-sync] Error 128 (ignored)
#cd capstone ; for PATCH in ../capstone-patches/* ; do patch -tp1 < $PATCH ; done
cd capstone ; for PATCH in ../capstone-patches/* ; do patch -p1 < $PATCH ; done
patching file arch/X86/X86ATTInstPrinter.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file arch/X86/X86ATTInstPrinter.c.rej
patching file arch/X86/X86IntelInstPrinter.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file arch/X86/X86IntelInstPrinter.c.rej
patching file arch/X86/X86Mapping.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file arch/X86/X86Mapping.c.rej
patching file Makefile
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
4 out of 4 hunks ignored -- saving rejects to file Makefile.rej
make[1]: *** [capstone-sync] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by radare** [comment]
which tarball are you using? the one from github or the one from the radare webpage?

**Comment by radare** [comment]
sdb is version 0.10.4, thats no issue at all, r2 needs to build and run stuff in host, so it needs two CC, see doc/crosscompile for more info there are other scripts that may help you debugging this problem like sys/android.sh or the mingw32.sh ones with the mk/ files.

thanks for the debrujn part. its fixed now in master

the capstone thing.. well it works fine in all my machines, jenkins build farm, travis and even in my phone. so i dont know what causing this

**Comment by rofl0r** [comment]
i'm using http://rada.re/get/radare2-0.10.5.tar.xz .
apparently the capstone that's shipped in-tree already has the patches applied.
maybe it works for you because configure picks up a system capstone ?

**Comment by radare** [comment]
oh right maybe its becuase its shipping the capstone with the patches, will fix the release script for the next 6 week cicle. sorry about that

**Comment by radare** [comment]
you can just grab this patch and apply it for packaging
