### ISSUE TITLE
`asm.stackptr` miscounting

### ISSUE THREAD

**Issue by laanwj** [radare/radare2#5562]
Radare's code analysis seems to wrongly think that the `mov eax, dword [ebp]` below increases the stack pointer.
```
│           0x0804b380     0      55             push ebp              ; two args
│           0x0804b381     4+     57             push edi
│           0x0804b382     8+     56             push esi
│           0x0804b383    12+     53             push ebx
│           0x0804b384    16+     81ec30400000   sub esp, 0x4030
│           0x0804b38a 16448+     8bac24484000.  mov ebp, dword [esp + 0x4048]
│           0x0804b391 16448      8b4500         mov eax, dword [ebp] # esil: ebp,[4],eax,= 
│           0x0804b394 16452+     0500001000     add eax, 0x100000
│           0x0804b399 16452      c744241c0000.  mov dword [esp + 0x1c], 0x100000
```
Another occurrence of this later:
```
│      ││   0x0804b514 16448      894500         mov dword [ebp], eax # esil: eax,ebp,=[4]
│      ││   0x0804b517 16452+     891544eb0408   mov dword [0x804eb44], edx
```
Due to this, at the end of the function it ends 8 in the plus:
```
│     │││   0x0804b529     8-     c3             ret
```
In the esil representation I see no spurious esp manipulations, however.

**Comment by radare** [comment]
this asm.stackptr thing is computed with the RAnalOp.stackop value, which is not related to the esil expression.

i have blind fixed this, so pls confirm it works now :) you can see the commit for more details c6d76d52b2f268d9e052b174f6456ea028af7ce8

**Comment by laanwj** [comment]
Can verify that this is fixed now, thanks!
```
      │││   0x0804b529     0-     c3             ret
```

**Comment by Maijin** [comment]
please add a test in https://github.com/radare/radare2-regressions
