### ISSUE TITLE
agv starts webserver wtf

### ISSUE THREAD

**Issue by radare** [radare/radare2#5564]

**Comment by Maijin** [comment]
? This has always been the case, that's how I launched the web interface since I know about it :P

**Comment by radare** [comment]
it was launchging the graph in the webui, but right now it always shows /m

**Comment by Maijin** [comment]
oh ok.

**Comment by Maijin** [comment]
Hum when I use agv It directs me on /m

**Comment by Maijin** [comment]
Ah yes, should show graph.

**Comment by radare** [comment]
also

[0x00000000]> e~web
graph.web = false

**Comment by radare** [comment]
maybe it will be easier to just generate the png and load it with the system app for displaying images... maybe via r2pm and maybe we should remove agv because it depends on external stuff that can be done in plugins or scripts and is prone to fail because its not self contained inr 2

**Comment by Maijin** [comment]
Closed in #5662
