### ISSUE TITLE
Config var scr.colorops works incorrect

### ISSUE THREAD

**Issue by Barkhat26** [radare/radare2#5565]
When scr.colorops = false, disassembly is not colorized.
scr.colorops = true
![before](https://cloud.githubusercontent.com/assets/4105655/17815387/cfafa636-663c-11e6-9d83-699acae85723.png)
scr.colorops = false
![after](https://cloud.githubusercontent.com/assets/4105655/17815398/d912cd20-663c-11e6-8172-1a1d9fad163e.png)

**Comment by radare** [comment]
So?

**Comment by Barkhat26** [comment]
So?!
> e??~scr.colorops
        scr.colorops: Colorize numbers and registers in opcodes

**Comment by radare** [comment]
It does whats expected and described. What else do you expect?

**Comment by Barkhat26** [comment]
Maybe we understand in different ways what are opcodes.
![opcodes](https://cloud.githubusercontent.com/assets/4105655/17829174/e6c3c970-66ae-11e6-941a-2bc40a928777.png)
On the screenshot scr.colorops = false

**Comment by radare** [comment]
A mnemonic is just the name of the instruction "mov", "jmp", ... The operands are the arguments, and the opcode is the whole instruction. The column you are refering can be toggled with asm.bytes, but theres no way to drop the colors for it. So, what we need here is to implement the asm.colorbytes, correct?

**Comment by Barkhat26** [comment]
Implementing the asm.colorbytes would be excellent. I'm not still understanding clearly such terms like opcode, mnemonics. And I apologize for that. But according to http://stackoverflow.com/a/17638925 

> OPCODE: It is a number interpreted by your machine(virtual or silicon) that represents the operation to perform
