### ISSUE TITLE
BetterAnal: aap hotpatching w32 preludes

### ISSUE THREAD

**Issue by radare** [radare/radare2#5569]
i have added another prelude for x86-32 to handle the functions preludes of msvc with /hotpatching. This hasnt been tested, so this issue aims to track this (we need a test and confirm that current behaviour doesnt results in 2 hits per function (with mov edi, edi and without)

```
                                r_core_search_prelude (core, from, to, // mov edi, edi;push ebp; mov ebp,esp
                                        (const ut8 *)"\x8b\xff\x55\x8b\xec", 5, NULL, 0);
                                r_core_search_prelude (core, from, to, // push ebp; mov ebp, esp
                                        (const ut8 *)"\x55\x8b\xec", 3, NULL, 0);
```

**Comment by radare** [comment]
See 5023918793c7376555f022b5d320be362a601bea

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/4783 related
