### ISSUE TITLE
Try to decrypt referenced strings.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#5589]
What about trying some decryption/decoding on referenced strings?

Base64 and so on.

**Comment by zonkzonk** [comment]
base64 is already in

**Comment by zonkzonk** [comment]
| p6[de] [len]                 base64 decode/encode

**Comment by radare** [comment]
Sounds like an interesting feature because rbin could identify b64 encoded strings as well as it does now for utf8 or widechar. The only drawback i see is a performance penalty but it can be ok if we have a isB64String()

**Comment by Maijin** [comment]
@MariasStory There are already tons of algorithm supported with woD:
```
Available Encoders/Decoders:
  base64
  base91
  punycode
Currently supported crypto algos:
  rc2
  rc4
  rc6
  aes-ecb
  aes-cbc
  ror
  rol
  rot
  blowfish
  cps2
```

You can add more #4254

**Comment by MariasStory** [comment]
Can we start with some simple decryption that can be done automatically (without keys).
Let's say, in a code I have a reference to base64/base91/punycode strings. They could have been detected (maybe behind an asm. flag) and shown in the strings and disassembly.

**Comment by Maijin** [comment]
Go for it.

**Comment by MariasStory** [comment]
So, the simple search string is:
^([A-Za-z0-9+\/]{4})*([A-Za-z0-9+\/]{4}|[A-Za-z0-9+\/]{3}=|[A-Za-z0-9+\/]{2}==)$

1. Tested it on "Z28gZm9yIGRmYXNkZmFzZGYgZmZmZmY=":
https://regex101.com/r/iI7aF2/1
2. Compiled linux c++ file.
[decodeTest_striped.zip](https://github.com/radare/radare2/files/432702/decodeTest_striped.zip)

3. `[0x00400680]> iz
vaddr=0x00400888 paddr=0x00000888 ordinal=000 sz=33 len=32 section=.rodata type=ascii string=VGhpcyBpcyBhIGNpY3JldCBzdHJpbmc=
vaddr=0x004008a9 paddr=0x000008a9 ordinal=001 sz=18 len=17 section=.rodata type=ascii string=I'm a C++ program`

4. iz~{regex} - this step did not work. I would expect that the base64 string will be found.

What am I doing wrong?

**Comment by Maijin** [comment]
`iz~{regex}` isn't r2.

See `/?`

**Comment by Maijin** [comment]
See `~??` for `~` help

**Comment by MariasStory** [comment]
OK. Trying to cheat.

> [0x00400680]> iz | grep -iP '[^a-z\:\#\<\s]([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)'
sh: 1: Syntax error: Unterminated quoted string
sh: 1: Syntax error: ")" unexpected
sh: 1: [A-Za-z0-9+/]{3}=: not found

I simplified the regex and it work in shell.

So. What is the way to implement the regex search in r2?

**Comment by Maijin** [comment]
Again, check `/?~regex`

**Comment by MariasStory** [comment]
@radare do you mean the file_looks_utf8 function? Can we use similar with regex search or the logic should be implemented in the similar way?

**Comment by Maijin** [comment]
Also, reimplementing the logic of https://github.com/fireeye/flare-floss with ESIL could also be done

**Comment by MariasStory** [comment]
Cool reference @Maijin.
According to their documentation, the floss can already be used with r2:

> To create an annotation script for radare2, use the -r or --radare switch.
> floss.exe -r myr2script malware.bin

I didn't test it jet.

**Comment by Maijin** [comment]
I know I added the support for radare2 in the project. But this isn't the same as what I proposed.

**Comment by jvoisin** [comment]
Maybe this could go into a separate `r2pipe` script into of r2.

**Comment by Maijin** [comment]
Yes for sure or even a separated project

**Comment by jvoisin** [comment]
Lets close this then.

**Comment by Maijin** [comment]
I agree.
