### ISSUE TITLE
Strings as argument in instruction.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#5603]
Can I change the arguments to strings?

Before:
![image](https://cloud.githubusercontent.com/assets/6576335/17948540/86de1faa-6a51-11e6-9c7c-42d138b3384c.png)

After:
![image](https://cloud.githubusercontent.com/assets/6576335/17948576/a47d7b3c-6a51-11e6-8313-42200cda2d1a.png)

Maybe a radare2 method of reconstructing such strings?

PS: Debugging of Windows files does not work under Linux for me.

**Comment by Maijin** [comment]
`ahi s` in command line
or 
In visual mode `Vdi 2`

**Comment by Maijin** [comment]
What does that means
```
PS: Debugging of Windows files does not work under Linux for me.
```

**Comment by Maijin** [comment]
You can also use `Cs` or `Vds`

**Comment by Maijin** [comment]
Open a separated issue for the debugging problem with more detail.
