### ISSUE TITLE
radiff2 -x binary1 binary2 should print diff in readable hex output (offset: by te s0)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#561]
To make something like:

radiff2 -x binary1 binary2
  0x345: 45 dd 00 06 5e
+0x346: ad 09 84 55 aa
-0x346: ae 10 85 55 aa
 0x347: 66 30 ef ff c0

Or something like that. Inspired by https://reverseengineering.stackexchange.com/questions/3507/is-there-any-tool-to-quantitatively-evaluate-the-difference-of-binary/3508
and **dhex** tool experience.

**Comment by XVilka** [comment]
@radare `cu` is cool, we need same for radiff2

**Comment by XVilka** [comment]
@radare `cu` command is good, just need maybe a better coloring.

**Comment by radare** [comment]
isnt unified what you are looking for? -u?

i have improved cu the last week. pls review

**Comment by XVilka** [comment]
Yes, `radiff2 -u` does the job, but it also prints the strings, not sure if this is required at all since it messes the screen output.

**Comment by radare** [comment]
Use -qu if you dont want the strings
