### ISSUE TITLE
Radiff regression: all functions showing as UNMATCH 1.0 in -C mode

### ISSUE THREAD

**Issue by zhuowei** [radare/radare2#5613]
It seems that radiff2 -C broke somewhere between 0.10.5 and latest master (bf95f88): on latest master, running `radiff2 -C -A /bin/true /bin/true`  i.e. on the same executable, will display a list of methods with similarity all at UNMATCH 1.0. Running it against /bin/true and /bin/false also results in everything in the list being marked as unmatched.

0.10.5 seems to detect matches for /bin/true and /bin/false, but will always print out 1.000000 as the unmatch score. 0.10.2 seems to work, correctly printing out how similar functions are.

I'm using Ubuntu 15.10 x86_64 and am building from git using the sys/install.sh script.

**Comment by radare** [comment]
Iirc this was broken already in 0.10.5, could you find a working version and write a test for this case?

Thanks
