### ISSUE TITLE
Feature Request:  Global back/forward

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#5622]
Topic says it...I hope at least.  One of my biggest challenges using radare2 via cli is quickly moving around.  With the added function of paging through functions using JK (thank you again for that!) I'm able to move around a lot better, however I'd love to see a global feature of stepping back through screens.  Example:  Load up a file (pony.dll for example) with r2 -AA, hit 'v', then hit 'p', I'm at entry0.  Hit 'n' a few times to jump to the next functions, now I'm at 0x10009261, and then hit X and go to DATA XREF 3, now I'm at 0x10012144.  Now at this point it would be nice to hit say....I dunno SHIFT+TAB to go back to my previous view at 0x10009261.  Yes, I can hit 'v' and then select the previous function I was at, but if I SCROLL through instead of using nN to jump to functions, if I hit 'v' again the functions view on the left side is only going to show the last function I jumped to (using 'g', or starting out at entry0), not the one I may have looked at (I hope that made sense).

In any case, not sure if something like this is doable or not.  Thank much.

**Comment by MariasStory** [comment]
Try 'u'

**Comment by radare** [comment]
u does undo seek and U redo seek

You have s- and s+ commands to undo/redo seek in the prompt

**Comment by Maijin** [comment]
Don't forget that number you see in the Visual mode:
![image](https://cloud.githubusercontent.com/assets/1408600/18023259/377cfda8-6bf7-11e6-89e7-2535cff498c9.png)
Can be reached using your keyboard. Same with the letters in graph mode:

![image](https://cloud.githubusercontent.com/assets/1408600/18023268/43d62994-6bf7-11e6-8272-926aa72d5a8d.png)

And you can use then `u/U` to undo/redo

**Comment by DigiAngel** [comment]
Yea you folks are right....I'll close this as a case of "user not knowing what they're doing".
