### ISSUE TITLE
Add pagedown/pageup in HUD

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#5643]
Topic says it :)  After hitting v, and _ I get the awesome list.  However in navigating it seems I can only use the up/down arrow keys here.  I'm requesting a pageup/pagedown function.  I realize I can filter which is great when you know what you're looking for, but it would be nice to be able to browse though to find interesting bits.  Side note, that particular screen won't allow a "?" for help.  Thanks...sorry to be a pest.

**Comment by Maijin** [comment]
You can also use your keyboard to type the name of the flags

**Comment by DigiAngel** [comment]
Thanks Maijin....I love the filter feature...very powerful!

**Comment by Maijin** [comment]
Do you need more than this?

**Comment by DigiAngel** [comment]
Eh....filtering implies (at least to me) that I know what I'm looking for.  But for just browsing down, and again, I'm doing this over ssh remotely, just holding down the down arrow key is interesting.  I guess I browse a lot more them most.

**Comment by Maijin** [comment]
So you just want pagedown/pageup support in hud

**Comment by Maijin** [comment]
You can already use "J" and "K" I will add pagedown/pageup

**Comment by DigiAngel** [comment]
Hi Maijin...hitting J or K results in filtering by JK.  This is after hitting the _ key.  Screenshot included.
![2016-09-19 16_18_14-zone-y](https://cloud.githubusercontent.com/assets/947191/18650834/b7d607ac-7e84-11e6-99c3-8afe85502b03.jpg)

Does this make sense?  Thank you.

**Comment by DigiAngel** [comment]
Commands:
~~~
r2 -AAA bleh.exe
V
_
~~~

For example if I type "reloc" I'll get the includes screenshot.
![2016-09-19 16_20_00-zone-y](https://cloud.githubusercontent.com/assets/947191/18650873/fc0f2e6c-7e84-11e6-8c42-4f7d547dd2cd.jpg)

Thanks again.

**Comment by Maijin** [comment]
yes I see

**Comment by DigiAngel** [comment]
Sweet.  Personally I think that page up/page down would be appropriate here as people may well want to filter with "J" or "K".  Thanks so much..sorry I wasn't clearer...again 8-|

**Comment by Maijin** [comment]
* https://github.com/radare/radare2/blob/master/libr/cons/hud.c#L222

**Comment by Maijin** [comment]
Nah I though u were speaking of Flagspace set which is easy to patch but this stuff is a mess. @XVilka may be more lucky on this.

**Comment by radare** [comment]
I will do that its just 1-2 lines of code

**Comment by DigiAngel** [comment]
Awesome...thank you!

**Comment by radare** [comment]
it was more than 2 lines, but simple shit to do. njoy
