### ISSUE TITLE
Infinite / extremely long loading time on big ARM binary

### ISSUE THREAD

**Issue by ishitatsuyuki** [radare/radare2#5648]
I'm experiencing extremely long loading time for an ARM binary, and it even doesn't accept Ctrl+C. When I add "-N" (no user settings), it accept the interrupt, but it still doesn't load in 10 seconds. With "-n" (no RBin), it loaded instantly.

I have tried to downgrade to 0.10.4, it worked, loading in about 1 sec.

The binary is Minecraft:PE's native library, unfortunately I can't distribute it publicly.

**Comment by VisualPrankDude** [comment]
can you run "valgrind --leak-check=full --show-reachable=yes --track-origins=yes --leak-resolution=high --trace-children=yes r2 bin" ?

**Comment by ishitatsuyuki** [comment]
@VisualPrankDude it freezes, so nothing is outputted.

From Maijin's test: `oke it hangs it spend the time here get_symbos in elf code`

**Comment by VisualPrankDude** [comment]
@ishitatsuyuki there should be still something in the logs, wait I forgot log-file=/tmp/log :)

**Comment by alvarofe** [comment]
This has been improved. Remains the thumb/arm detection where sometimes fail and is a known issue. I will close it feel free to reopen it in case is still slow for you

**Comment by radare** [comment]
😍
