### ISSUE TITLE
[AVR] afCl errors: Unknown calling convention '0x10e9af610'

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5654]
Today my project starting complaining again about afCl, @oddcoder:

```
Unknown calling convention '0x10e9af610'
See afCl for available types
Unknown calling convention '0x10e9af610'
See afCl for available types
Unknown calling convention '0x10e9af610'
See afCl for available types
Unknown calling convention '0x10e9af610'
See afCl for available types
Unknown calling convention '0x10e9af610'
See afCl for available types
Unknown calling convention '0x10e9af610'
See afCl for available types
Unknown calling convention '0x10e9af610'
(...)
```

This relates back to issue https://github.com/radare/radare2/issues/5452.

**Comment by brainstorm** [comment]
Just pulled master, recompiled, reloaded the project and I'm getting this:

```
$ r2 -p ardrone_flash_blc
avr
avr
avr
avr
avr
avr
avr
avr
avr
(...)
[0x00000026]>
```

Missing `printf` somewhere? :)

**Comment by brainstorm** [comment]
Some commit might have solved it automagically since it does not complain now... although argument detection still doesn't seem to appear/work.

**Comment by radare** [comment]
cc @oddcoder

**Comment by Maijin** [comment]
It definitely work, but you need to implement database etc.
