### ISSUE TITLE
Have two branches?

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#5656]
What about to follow the same thing as capstone does having two branches?. Sometimes we land commits in master that introduces regression that travis does not catch and only through using the tool can be seen. One example is that for an arm binary with a lot of symbols is impossible to get a disasm without spending so much time (blame on me). 

The reason is that we always say to users use r2 from git, and sometimes is not the best solution. I propose use dev branch or whatever name and merge into master once we are sure that it does not break anything or after each release.

Your thoughts?

**Comment by Maijin** [comment]
Already been discussed, who maintains it, you ?

**Comment by Maijin** [comment]
```
Sometimes we land commits in master that introduces regression that travis does not catch and only through using the tool can be seen. One example is that for an arm binary with a lot of symbols is impossible to get a disasm without spending so much time (blame on me).
``` 
I don't get how this will be resolved btw, since you will say user to use only master, nobody will test the dev

**Comment by radare** [comment]
Nope
