### ISSUE TITLE
Graph View is broken

### ISSUE THREAD

**Issue by Liblor** [radare/radare2#5662]
The graph view on the webui doesn't work. 
`[0x00000000]> agv`
leads to `/m/` which is a known bug #5564, but even after changing to `/graph/` manually, the graph isn't shown. Instead one gets to see html code, because `<`, `>` etc. get escaped.

I tried to debug it a little, but I'm not very experienced.
if `/graph/` is opened, `I.is_html` is set to `true`, thus the "filter" `r_cons_html_print` inside `r_cons_flush`is called, which escapes `<`, etc.

Just to check I commented out the `r_cons_html_print` call, the graph view renders, but there is another bug. The assembly code always starts with `\x.2\x)4\x(2`

**Comment by Maijin** [comment]
Did you analyse the binary before going in graph

**Comment by Liblor** [comment]
Yes, I did and I added a picture ;)
After commenting out `r_cons_html_print`I might not have analyzed the binary though, I have to check the `\x.2\x)4\x(2` thing again.


![r2_bug_graph](https://cloud.githubusercontent.com/assets/4940804/18142092/53928986-6fbc-11e6-882e-bbc9feea6327.png)

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
Also this is old graph, to get the graph use /p/ or use /m/ -> disassembly -> info -> graph, but this is highly WIP by @gcolajan  https://github.com/radare/radare2-webui

**Comment by Liblor** [comment]
Ah, I see. I thought that `/m/` is WIP, that's the reason I checked out `/graph/`, so I guess `/graph/` will be removed in the foreseeable future.
Thanks for clarification!

**Comment by Maijin** [comment]
Don't know if will be removed but surely be updated.

**Comment by radare** [comment]
what do you think about agv? i dont use for since ascii graphs are there.. and imho it can just confuse users. suggestion in changes or removal?

**Comment by Maijin** [comment]
+1 on removal because it's confusing and removal of graph.web: Display graph in web browser (VV) too

**Comment by XVilka** [comment]
+1 for removal.

**Comment by Liblor** [comment]
As I got confused by it: +1 for removal

**Comment by radare** [comment]
afaik agv was honoring cmd.graph and graph.web before... now looks like someone killed all that functionality and just called "=H /graph".. which is completely wrong. so i would go for bringing back the old functionality

**Comment by radare** [comment]
Related: https://github.com/radare/radare2/issues/5668

**Comment by Liblor** [comment]
Well, `agv` now launches `/graph/`, but it still doesn't render the graph, so this bug shouldn't be closed.

`<` is escaped to `&lt;` and `>` to `&gt;`, so one just gets to see html code as in the screenshot above.

**Comment by Maijin** [comment]
Update.

**Comment by radare** [comment]
nope. agv doesnt spawns the web by default unless you enable graph.web=true

**Comment by radare** [comment]
try again

**Comment by Liblor** [comment]
Sorry for not mentioning it, I set graph.web=true, and then I ran `agv`. The browser opens, but I just see html code.

**Comment by Maijin** [comment]
well then same message as the beginning:
```
Also this is old graph, to get the graph use /p/ or use /m/ -> disassembly -> info -> graph, but this is highly WIP by @gcolajan https://github.com/radare/radare2-webui
```

**Comment by Liblor** [comment]
I know about the new graph view, but it's just confusing for a radare2 beginner. He sets `graph.web=true`, and it doesn't work. I think its better to remove the old graph view, if it doesn't work, don't you think so?

**Comment by radare** [comment]
why a beginner would change default settings? the webui lives in a separate repository. im not talking about removing, but filling an issue in the radare2-webui repo to get it working again. this is a regression.

**Comment by Maijin** [comment]
https://github.com/radare/radare2-webui/issues

**Comment by Liblor** [comment]
Newbies like GUIs, they might change settings ;)
There is a new web graph ui as @Maijin said, that's why I thought it wasn't really a regression, if this one is deleted, but I see your point.
Thanks for the help and this awesome project!

**Comment by Maijin** [comment]
What @radare says is: This is not the place for writing this issue but here https://github.com/radare/radare2-webui/issues is.

**Comment by radare** [comment]
well. that’s an issue in the webui, not in r2 itself, so imho the issue here is gone for now.

the /graph/ thing was working but was pretty bad, i was expecting this to be done by the gsoc webui task but didnt get done in time

**Comment by Maijin** [comment]
https://github.com/radare/radare2-webui/issues/100 Like this
