### ISSUE TITLE
rasm2 big endian option (-e) doesn't work properly

### ISSUE THREAD

**Issue by daniel-rome** [radare/radare2#5663]
It seems that rasm2 always returns the hexpair bytes in little endian.
```
$ rasm2 -a mips -b 32 "addi a1, a1, -1"
ffffa520

$ rasm2 -a mips -b 32 -e "addi a1, a1, -1"
ffffa520
```

**Comment by radare** [comment]
Fixed. this is a regression from the latest big-endian patches. but it's working again. i wrote two tests for it.
