### ISSUE TITLE
el capitan  no debug gdb/r2

### ISSUE THREAD

**Issue by Durakill** [radare/radare2#5665]
Installed radare2 from dmg. El Capitan 10.11.6

"MikesMBP:~ $ r2 -d /Users/durakill/Desktop/example 
syntax error: error in error handling
syntax error: error in error handling
Unsupported architecture
Child killed
unknown error in debug_attach
Cannot open 'dbg:///Users/durakill/Desktop/example' for writing."

example is 32 bit Xcode c compile. Hello World, nothing fancy.

I installed Radare2 from .dmg

"radare2 0.10.5 12231 @ darwin-x86-64 git.0.10.5
commit: 940f2d311d8e011ad76ed54122d46beea4b6db90 build: 2016-08-17"
radar keychain access cert is login
GDB keychain access cert is system
Both self signed root cert.

I realise I've done something wrong. I'm a senior citizen, relearning stuff for my own amusement. gdb debugs "example" fine by itself. Just not under r2.

Any step by step help? 

Thanks.

**Comment by radare** [comment]
Use -b32 as a workaround until this regression is fixed
