### ISSUE TITLE
ELF regression on a bin

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5667]
https://twitter.com/maciekkotowicz/status/771439232531456001
![image](https://cloud.githubusercontent.com/assets/1408600/18199827/648c0388-7102-11e6-8c5a-d99593c7e678.png)

The bin is here https://t.co/WjM0uCKdUk

[4f50ce05a9f180180c6422b2a43dd82e.zip](https://github.com/radare/radare2/files/451671/4f50ce05a9f180180c6422b2a43dd82e.zip)

**Comment by psifertex** [comment]
From a very brief look at it, it looks like the binary is using the `dynstr` dynamic symbol table to include an incorrect symbol name over an import. Only relying on the import itself for the import name should fix it.

**Comment by radare** [comment]
binutils also fails

**Comment by radare** [comment]
gdb and ltrace also fails on this. so it's not "ridiculous", i have traced a bit with ld.so and qemu -strace and got a 1 line fix in r2 code. i'll push a PR to see if it creates any regression for other binaries.

Nice catch!

**Comment by radare** [comment]
I have added a testcase too
