### ISSUE TITLE
Load compressed zignatures

### ISSUE THREAD

**Issue by radare** [radare/radare2#5686]
I would delegate this task to 3rd party programs in a streamy way:
- zg foo | gzip > foo.r2.gz
- zo foo.r2.gz

The zo command should be the same as '. foo', but should support compressed streams, and load faster, because it doesnt have the logic of rcorecmd() only parsing the lines that start with 'z'

**Comment by radare** [comment]
I have implemented the 'zo' command, but is not yet supporting compressed ones. the performance compared to '.', for loading a 24MB signatures script is 5.3s vs 4s

**Comment by zlowram** [comment]
Did you push that?

**Comment by radare** [comment]
i did zo, but doesnt supports compressed signatures, which is low prio and unnecessary for now

**Comment by Maijin** [comment]
See 6947
