### ISSUE TITLE
Zignatures with zero bytes

### ISSUE THREAD

**Issue by radare** [radare/radare2#5688]
we shouldnt assume that 0 is a mask, this informtaion must be stored in a different buffer

**Comment by jroimartin** [comment]
@radare can you add more details? If it's about the logic behind zg/zG I already fixed it. Can you check?

https://github.com/radare/radare2/commit/bc527a9aff42aebc09827575e1499eda90e73a57#diff-6b068084a00273e3079ac60537a8dc00R124

**Comment by radare** [comment]
That may affect zB and zb too. The problem is that theres nothing to forbid you to register zignatures where the mask is empty. So it will never match any byte.

**Comment by radare** [comment]
Didnt chkd after your changes

**Comment by radare** [comment]
@jroimartin ok for 1.3 or moving to 1.4?

**Comment by jroimartin** [comment]
It will be fixed as part of the zign refactoring. Move it to 1.4 just in case.
