### ISSUE TITLE
Honor search.in for z/

### ISSUE THREAD

**Issue by radare** [radare/radare2#5691]
```
[0x100001174]> z/
No section identified, please provide range.
```

z/ is confusing becuase /z is not doing the same

**Comment by radare** [comment]
Also honor search.align to speedup

**Comment by Maijin** [comment]
Duplicates of https://github.com/radare/radare2/issues/2570

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/18810659/777e4054-829c-11e6-95bf-6644d8e7f175.png)

**Comment by radare** [comment]
The align matters because signatures .. Well functions always start on aligned addresses
