### ISSUE TITLE
axt doesn't follow e asm.relsub

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5698]
`axt` doesn't follow `e asm.relsub`

![image](https://cloud.githubusercontent.com/assets/1408600/18253349/4b9536ee-7394-11e6-94a7-1c0debe64ab5.png)

![image](https://cloud.githubusercontent.com/assets/1408600/18253347/499d7694-7394-11e6-9e3b-8b03bad4be20.png)

`axt` and `axtj` still displays : 

```
data 0x200154a7 call qword [rip + 0x7bbb] in sub.ADVAPI32.dll_LookupAccountNameA_354
data 0x200153b6 call qword [rip + 0x7cac] in sub.ADVAPI32.dll_LookupAccountNameA_354
call 0x200082d7 call qword [rip + 0x1534b] in sub.ntdll.dll_RtlZeroMemory_24c
data 0x200082d7 call qword [rip + 0x1534b] in sub.ntdll.dll_RtlZeroMemory_24c
```

CC @pinkflawd

**Comment by Maijin** [comment]
Also found a bug in finding xref when creating this bug
https://github.com/radare/radare2-regressions/commit/dbe9df59d17eed49e9862e749f8e0ddc477af13a

**Comment by Maijin** [comment]
@alvarofe another dll anal issue here ^

**Comment by radare** [comment]
this is simple to do.. buuuuuut the problem is that those references can change at any time if memory changes because the contents of the address are not static like the instruction is. so it is not a reliable reference

**Comment by radare** [comment]
maybe we should consider adding a new type of reference for this

**Comment by pinkflawd** [comment]
in static analysis memory won't change, no?

**Comment by radare** [comment]
Yep it can because in static analysis you can emulate or even be modified by relocs

**Comment by radare** [comment]
I think that we should be able to specify that the src or dest of a ref is not a fixed address but the result of emulating an instruction. Just by pointing to the address of it and setting a bit for that.

**Comment by pinkflawd** [comment]
Guess me promising I wont emulate nothing if you implement this now is no help? :P

**Comment by radare** [comment]
you wont emulate anything, it will be done by r2 in a transparent way

**Comment by Maijin** [comment]
Dll bug is fixed but not relsub issue

**Comment by Maijin** [comment]
Not yet :P this time it broke older axt tests :P

**Comment by Maijin** [comment]
Fixed and tested !
