### ISSUE TITLE
asm.leahints are displayed in the middle of the disassembly

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5703]
Regression asm.leahints are displayed in the middle of the disassembly : 

![image](https://cloud.githubusercontent.com/assets/1408600/18257601/c405fd52-73c6-11e6-9953-f4bc7113be7a.png)

**Comment by radare** [comment]
we can set leahints to false by default for now

**Comment by VPaulV** [comment]
It is here https://github.com/radare/radare2/blob/master/libr/core/disasm.c#L1854

I am not sure if this print should be there at all... Maybe just comment it out?

Here is also one more potential place for regression - https://github.com/radare/radare2/blob/master/libr/core/disasm.c#L1829

**Comment by radare** [comment]
cc @kazarmy
