### ISSUE TITLE
Visual view of the $ variables

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5715]
To view the values easily, like it was done for config variables, but for '$' ones

**Comment by radare** [comment]
You cant change the value of those vars because they are computer from other sources. I would not do that

**Comment by XVilka** [comment]
@radare I wasn't talking about changing, just a view.

**Comment by radare** [comment]
Isnt :$?~.. Enough? Where do u want to have them? By pressing $ inside Ve?
