### ISSUE TITLE
Context-dependent colors for comments

### ISSUE THREAD

**Issue by brainstorm** [radare/radare2#5716]
As mentioned in the radarecon 2016's Radare A to Z session: Let's say that I have a command, rpipe tool or similar that annotates (comments) specific instructions, say `in` and `out` instructions, i.e:

![skarmavbild 2016-09-08 kl 13 57 45](https://cloud.githubusercontent.com/assets/175587/18348551/4473e268-75cc-11e6-9ce1-47f4e1889720.png)

I would like those `in`/`out` comments to have different colors than the rest of "generic" comments.

How can one do that?

**Comment by radare** [comment]
We can add another color category in the cons.pal to handle different kinds of colors. Other comments can also be interesting to have

**Comment by brainstorm** [comment]
@radare I was thinking on something like:

https://github.com/brainstorm/radare2/commit/d38cd02

What other comments/categories where you thinking about?

**Comment by radare** [comment]
i dont see any pullreq

**Comment by Maijin** [comment]
@brainstorm ping(1)

**Comment by Maijin** [comment]
Please PR this so we can close the issue if no more additional category is suggested by @radare .

**Comment by radare** [comment]
Maybe related to https://github.com/radare/radare2/issues/6828

**Comment by brainstorm** [comment]
Closing, unnecessary since it would just clutter the interface with too many colors. It's good as-is, imho.
