### ISSUE TITLE
dko 11 c Doesn't work

### ISSUE THREAD

**Issue by atrodo** [radare/radare2#5717]
If I create a custom SIGSEGV handler in my code, r2 debugger will not allow me to step into that handler.  This use to work, but after bisecting, I found that the big rewrite in 722c6282 (Major rework to the native debugger (esp on Linux) (#5185)) changed this behavior. I haven't traced how everything works, but it appears that line 955 in libr/debug/debug.c now no longer lets `dko 11 c` operate:

`if (reason == R_DEBUG_REASON_SIGNAL && dbg->reason.signum != -1)`

From my shallow digging, it appears that this line was there before 722c6282, but before the SIGSEGV was being being returned as R_DEBUG_REASON_SIGNAL, so the code that checks the values from dko was executed. Now it appears that the SIGSEGV is making the reason be R_DEBUG_REASON_SEGFAULT, which looks correct but preventing any custom SEGV handlers from running. I assume this behavior will happen with SIGTRAP and SIGABRT as well, so I'm wondering if the `reason == R_DEBUG_REASON_SIGNAL` part of the condition is necessary or if `dbg->reason.signum != -1` is sufficient for this condition to work? I don't know the code well enough to know the implications of that change, but reducing it to just that condition does allow `dko 11 c` to work as expected.

Well, it almost works like before. If my custom handler can't handle the SIGSEGV, it uninstalls itself and lets the SIGSEGV retrigger. Before r2 would then act like `dko 11` (stop), but now the child process dies and I can no longer inspect it. That's more of a side note because it can be easily worked around in my work flow, where as `dko 11 c` not working prevents me from debugging after a SIGSEGV my code can recover from.

```
radare2 0.10.6-git 12318 @ linux-x86-32 git.0.10.5-186-g7ea11a3
commit: 7ea11a38c512c68a11fc2edd455e8348156b9cdf build: 2016-09-08
```

**Comment by radare** [comment]
Can you send a pullreq with this change? Both reasons should be handled in the same way imho

**Comment by Maijin** [comment]
@atrodo ping1
