### ISSUE TITLE
r2pipe is broken

### ISSUE THREAD

**Issue by VPaulV** [radare/radare2#5721]
After the commit 7cf0e1b63361e14a92512f6a940e18283acd2afe r2pipe holds forever when r2cmd is called.

```C
#include <r_socket.h>

static void r2cmd(R2Pipe *r2, const char *cmd) {
	char *msg = r2p_cmd (r2, cmd);
	if (msg) {
		printf ("%s\n", msg);
		free (msg);
	}
}

int main() {
	//R2Pipe *r2 = r2p_open ("/bin/ls");
	R2Pipe *r2 = r2p_open ("r2 -q0 /bin/ls");
	if (r2) {
		r2cmd (r2, "?e Hello World");
		r2cmd (r2, "x");
		r2cmd (r2, "?e Hello World");
		r2cmd (r2, "pd 20");
		r2p_close (r2);
		return 0;
	}
	return 1;
}
```
---------------
Also it is not possible to use r2p_open with -c. Is it a bug?

**Comment by Maijin** [comment]
That issue should have been sent on radare2-bindings (next time :) )

**Comment by VPaulV** [comment]
Oh right, my bad sorry. Should I reopen it?

**Comment by Maijin** [comment]
it's ok

**Comment by radare** [comment]
Can you add a unit test for this with an alarm? I know this change was about to break something but i wast sure what exactly. The change was necessary to make python/node io plugins work. So i will revert the change and update the python and node sides rather than the core.

**Comment by Maijin** [comment]
@VPaulV ping

**Comment by VPaulV** [comment]
Hey, sorry I am pretty busy now, will do it when will have more free time

**Comment by Maijin** [comment]
>_<

**Comment by VPaulV** [comment]
Heh, sorry, moving from one living place to another sometimes is pretty time demanding process

**Comment by radare** [comment]
I will do that i know what to change i just needed a proof of that brokenness. A test would be great to have

**Comment by VPaulV** [comment]
ok, will add it on weekends, but is there a way to set a time-out for test?

**Comment by Maijin** [comment]
yes

**Comment by radare** [comment]
not for now, but it can be easily implemented

**Comment by Maijin** [comment]
TIMEOUT=1 is here

**Comment by radare** [comment]
ah i though you mean timeout in the r2pipe.c api

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/tests.sh#L216 just need to be completed for r2 tests probably
