### ISSUE TITLE
izz doesn't work in raw binaries

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5724]
The file: [ex.zip](https://github.com/radare/radare2/files/465313/ex.zip)

## izz:

![image](https://cloud.githubusercontent.com/assets/1408600/18409197/2effcf88-7742-11e6-97ae-ea413ce0eea8.png)

## Rabin2:

![Rabin2](https://cloud.githubusercontent.com/assets/1408600/18409192/161e6812-7742-11e6-980a-51076509e85d.png)

**Comment by radare** [comment]
Thats because iz and izz depends on having headers in the bin

**Comment by Maijin** [comment]
@alvarofe thanks for the fix, this is going to reduce a lot of problems during workshops and irc/telegram !
