### ISSUE TITLE
Install radare2-bindings-python

### ISSUE THREAD

**Issue by constdec** [radare/radare2#5730]
After make and sudo make install on python folder I get this error.

Makefile:164: recipe for target 'install-python' failed
make[1]: *** [install-python] Error 1

**Comment by XVilka** [comment]
1. Please provide the full log
2. Try to use r2pipe instead.

**Comment by constdec** [comment]
make
Build r_core -L/usr/local/lib -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flags -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic -lr_crypto
valabind-cc python r_core -NRadare -NSDB --swig -x --vapidir=../vapi ../vapi/r_core -I/usr/local/include/libr -L/usr/local/lib -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flags -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic -lr_crypto
valabind --swig -I /usr/local/include/libr -x -N SDB -N Radare -x --vapidir ../vapi -o r_core.i -m r_core ../vapi/r_core --swig
NOTICE Symbol defined VALABIND_SWIG
NOTICE Adding dependency package glib-2.0
NOTICE Adding dependency package gobject-2.0
NOTICE Adding dependency package ../vapi/r_core
NOTICE Adding dependency package r_cmd
NOTICE Adding dependency package r_util
NOTICE Adding dependency package r_cons
NOTICE Adding dependency package r_anal
NOTICE Adding dependency package r_reg
NOTICE Adding dependency package r_hash
NOTICE Adding dependency package r_egg
NOTICE Adding dependency package r_asm
NOTICE Adding dependency package r_syscall
NOTICE Adding dependency package r_db
NOTICE Adding dependency package r_io
NOTICE Adding dependency package r_bp
NOTICE Adding dependency package r_debug
NOTICE Adding dependency package r_search
NOTICE Adding dependency package r_flags
NOTICE Adding dependency package r_config
NOTICE Adding dependency package r_bin
NOTICE Adding dependency package r_parse
NOTICE Adding dependency package r_lang
NOTICE Adding dependency package r_print
NOTICE Adding dependency package r_fs
NOTICE Adding dependency package r_magic
WARNING Method call renamed to _call (don't ask where)
WARNING Method continue renamed to cont (don't ask where)
swig -small -O -o r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/local/include/libr -c++ -c++ -python r_core.i
r_core.i:39: Warning 302: Identifier 'RCoreAsmHitVector' redefined (ignored) (Renamed from 'vector< RCoreAsmHit >'),
r_core.i:38: Warning 302: previous definition of 'RCoreAsmHitVector' (Renamed from 'vector< RCoreAsmHit >').
r_core.i:41: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:40: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:45: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:40: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:46: Warning 302: Identifier 'RAnalRefVector' redefined (ignored) (Renamed from 'vector< RAnalRef >'),
r_core.i:40: Warning 302: previous definition of 'RAnalRefVector' (Renamed from 'vector< RAnalRef >').
r_core.i:61: Warning 302: Identifier 'charVector' redefined (ignored) (Renamed from 'vector< char >'),
r_core.i:57: Warning 302: previous definition of 'charVector' (Renamed from 'vector< char >').
r_core.i:62: Warning 302: Identifier 'charVector' redefined (ignored) (Renamed from 'vector< char >'),
r_core.i:57: Warning 302: previous definition of 'charVector' (Renamed from 'vector< char >').
r_core.i:91: Warning 314: 'print' is a python keyword, renaming to '_print'
r_core.i:321: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:326: Warning 314: 'from' is a python keyword, renaming to '_from'
r_core.i:579: Warning 314: 'import' is a python keyword, renaming to '_import'
r_core.i:1938: Warning 314: 'del' is a python keyword, renaming to '_del'
r_core.i:1644: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
r_core.i:1649: Warning 453: Can't apply (RAsmOp *OUTPUT). No typemaps are defined.
g++ -fPIC -shared r_core_wrap.cxx -DG_BEGIN_DECLS -DG_END_DECLS -DG_GNUC_CONST -DSWIG_PYTHON_SILENT_MEMLEAK -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -Wdate-time -D_FORTIFY_SOURCE=2 -g -Wformat -Werror=format-security -DNDEBUG -g -O2 -Wall -Wstrict-prototypes -I/usr/local/include/libr -o _r_core.so -lr_crypto -lr_magic -lr_fs -lr_socket -lr_syscall -lr_search -lr_reg -lr_egg -lr_bp -lr_parse -lr_anal -lr_io -lr_lang -lr_bin -lr_hash -lr_debug -lr_asm -lr_flags -lr_util -lr_io -lr_cons -lr_config -lr_core -L/usr/local/lib -L/usr/local/lib -L/usr/pkg/lib -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
r_core_wrap.cxx: In function 'void delete_RListIter(RListIter*)':
r_core_wrap.cxx:7559:25: warning: statement has no effect [-Wunused-value]
   r_list_iter_free(self);
                         ^
r_core_wrap.cxx: In function 'long int RDebug_wait(RDebug*, RBreakpointItem**)':
r_core_wrap.cxx:8607:31: error: too many arguments to function 'RDebugReasonType r_debug_wait(RDebug*)'
   return r_debug_wait(self, bp);
                               ^
In file included from r_core_wrap.cxx:3293:0:
/usr/local/include/libr/r_debug.h:350:24: note: declared here
 R_API RDebugReasonType r_debug_wait(RDebug *dbg);
                        ^
... r_core.so
... r_bin.so
... r_asm.so
----------------------------------------------
sudo make install
cd .. ; make install-python
make[1]: Entering directory '/home/user/radare2-bindings'
test -f python/_r_core.so
Makefile:164: recipe for target 'install-python' failed
make[1]: *** [install-python] Error 1
make[1]: Leaving directory '/home/user/radare2-bindings'
../rules.mk:56: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by Maijin** [comment]
Use markdown https://guides.github.com/features/mastering-markdown/ for paste: ```

**Comment by XVilka** [comment]
Looks like you're using very old radare2 - this issue was fixed yesterday.

**Comment by constdec** [comment]
I just used git from radare.org instructions, I will reinstall.Thanks for your time

**Comment by XVilka** [comment]
@constdec because I've retried to 1) git pull and rebuild r2 2) r2pm -i python - all works smoothly, and this is exactly a bug I was fixing recently.

**Comment by Maijin** [comment]
@constdec Next time, use https://github.com/radare/radare2-bindings for error related to bindings, Also it's highly recommended to use r2pipe.
