### ISSUE TITLE
Unsupported flirt signature version ?

### ISSUE THREAD

**Issue by fnugroho** [radare/radare2#5746]
![screenshot from 2016-09-13 13_37_54](https://cloud.githubusercontent.com/assets/19466951/18472511/17f0e744-79e2-11e6-869b-8fd6f0ef3512.png)

**Comment by Maijin** [comment]
Already known please use search on github #5246

**Comment by Maijin** [comment]
and subscribe to the issue and contribute/involve in the issue if you want to be fixed faster (Create tests, investigate structure etc.)
