### ISSUE TITLE
/z vs z/

### ISSUE THREAD

**Issue by radare** [radare/radare2#5748]
@Darkkey was confused during the training. so maybe we can do something for that :D

**Comment by jvoisin** [comment]
What about `zs` for `z`ignature `s`earch instead of the weird `z/`?
Also, I don't think that it's worth having `/z`.

**Comment by radare** [comment]
Well to be consistent/ortogonal.. Or search stuff should be under / imho

**Comment by Maijin** [comment]
well yara uses "scan"

**Comment by radare** [comment]
lldb also scans instead of searching. but this have nothing to do with the question :D

**Comment by jvoisin** [comment]
Zignature stuff should be under a single command, `z`, in my opinion.

**Comment by radare** [comment]
so its ok the way it is now for you?

**Comment by Maijin** [comment]
He said 'zs'

**Comment by radare** [comment]
In soviet russia does not
