### ISSUE TITLE
Crash using aaa analysis on large binary (acroRd32.dll) 

### ISSUE THREAD

**Issue by sborpo** [radare/radare2#5750]
Hello,
I've tried to run the command : aaa (analyze all) on acroRd32.dll ~20 Mb(the main adobe reader dll) on
 Windows 10.
after i typed these commands from the cmd:
radare2 r2 c:\acroRd32.dll
[0x60042492]> aaa
the radare printed these lines and crashed after some amount of time:
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[ ] Analyze function calls (aac)

have to say that it runs fine on other small binaries,
Does someone have a clue?
Thanks!

**Comment by VisualPrankDude** [comment]
@sborpo can you run valgrind and or give gdb trace?

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
http://radare.org/get/pkg/radare2-w32-0.10.6.zip

**Comment by radare** [comment]
Windows have a small stack so recursivity is bad for him. You can try reducing the anal.depth or check with a debugger why it crashes. Also, ensure you are using the latest git

**Comment by VisualPrankDude** [comment]
windbg and ollydbg are good debuggers.

**Comment by Maijin** [comment]
@VisualPrankDude ?

**Comment by sborpo** [comment]
Hello,
The version of radare2 that i got is : 
radare2 0.10.5 12231 @ windows-x86-32 git.0.10.5
commit: 940f2d311d8e011ad76ed54122d46beea4b6db90 build: 2016-08-17

i have debugged the process with olly and got an exception of access violation.
here is a screenshot of the call stack before the exception:

![call_stack_during_exception](https://cloud.githubusercontent.com/assets/11454647/18505175/c6cff69c-7a6e-11e6-9cd2-7689e63c9f29.jpg)

**Comment by Maijin** [comment]
That's old version ... I just posted you the link http://radare.org/get/pkg/radare2-w32-0.10.6.zip

**Comment by radare** [comment]
This is old. Please upgrade

**Comment by sborpo** [comment]
Thanks for the updated , i've upgraded it - the analysis are running more than one hour and still counting.... so now its not crashing - thanks! :)
I've tried other DLL (Qt5Core), strangely there is a huge difference between the IDA and radare2. 
IDA identifies ~17,000 functions , but radare2 ~6,506.
this number is lower than the number of exported functions of the Dll (7,161)- so when i tried to list all the export with the "iE" command - it says:
0 exports.

Am I doing something wrong? 

p.s : i run an "aaaa" command on the dll

**Comment by Maijin** [comment]
You don't need aaaa for analysis, aaa or even smaller subset (aa, aac, etc. radare.today/posts/analysis-by-default/) should be largely sufficient. 

Also I've already spotted bugs in dll analysis #5718  could you share your bin ?

**Comment by sborpo** [comment]
here is the binary  (it is zipped):
http://www.megafileupload.com/k7kg/Qt5Core.zip

Do you have a clue about the exports ? why there are 0 exports? 
Thanks!

**Comment by Maijin** [comment]
[Qt5Core.zip](https://github.com/radare/radare2/files/482438/Qt5Core.zip)

**Comment by alvarofe** [comment]
The number of export 0 is cause there is a check on r2 where if the number of function greater than 0xfff wasn't allowing to gather that information. I will check against r2r to see if there is a regression and commit.

now

![captura de pantalla 2016-10-06 a las 1 03 00]
(https://cloud.githubusercontent.com/assets/3474042/19134860/f7c422b6-8b60-11e6-8a2d-fa5ff3f17df3.png)
![captura de pantalla 2016-10-06 a las 1 03 37](https://cloud.githubusercontent.com/assets/3474042/19134867/fdf032d8-8b60-11e6-9169-3ef3049486c4.png)

**Comment by alvarofe** [comment]
Pushed in master
