### ISSUE TITLE
Reference search does not stop.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#5751]
Hi, I did this reference search:
![image](https://cloud.githubusercontent.com/assets/6576335/18480540/59db0d28-79d9-11e6-97a8-b1f4baec10af.png)

It takes forever and did not stop yet. Should it stop at 0x1800190a0?

Is there a way to do the search faster?

**Comment by radare** [comment]
check the search.in and search.{from|to} variables. confirm that you are using r2 from git, also, other vars like search.align may speedup the search… but probably not for /r that relays on instruction information.

try with:

e search.in=io.sections.exec

**Comment by Maijin** [comment]
you can also use xref: axt @ 0x180016110 , axt @ sym.XXXX

**Comment by radare** [comment]
are you in debugger mode? in which OS? are you using r2 from git? which values do you have in search.* ?

**Comment by MariasStory** [comment]
Hi guys, thanks for your suggestions. I don't have much time for debugging the case today.
Will follow the case a bit later.

**Comment by radare** [comment]
without having the file or the setup you have its difficult to understand whats going on because i cant reproduce it

**Comment by MariasStory** [comment]
Hi @radare I don't have the time to do detailed analyze of the problem and I got some kind of answer for the memory dump that I was working on.

I assume that this was a problem with the dump. Still, I am surprised that the search is so slow.

You can close the issue.

**Comment by radare** [comment]
you can profile the reason to identify why is that slow, but 99% sure is because of capstone. udis86 was much faster for the same operation. changing block size can also help,.. just giving some hints
