### ISSUE TITLE
Merge functions argument detection functionnalities and databases

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5759]
Currently we have two functions sdb, both are fulfilling similar goals but both are using same information. Merging those functionalities/databases must be done to avoid duplicate.

1) One for "e asm.emu ; e asm.emuwrite" function argument found and predicted the value made by @radare 

![image](https://cloud.githubusercontent.com/assets/1408600/18506894/5166da92-7a6e-11e6-9ad8-2b5438f42671.png)
- https://github.com/radare/radare2/blob/master/libr/anal/d/windows-x86-32
- https://github.com/radare/radare2/blob/master/libr/anal/d/windows-x86-64
- https://github.com/radare/radare2/blob/master/libr/anal/d/linux-x86-64
- https://github.com/radare/radare2/blob/master/libr/anal/d/linux-x86-32
- https://github.com/radare/radare2/blob/master/libr/anal/d/darwin-x86-64

2) One for function argument detection made by @oddcoder 

![image](https://cloud.githubusercontent.com/assets/1408600/18506998/b9f062e0-7a6e-11e6-8e16-0d4bf0f27fdf.png)
- https://github.com/radare/radare2/blob/master/libr/anal/d/types-x86-osx-64
- https://github.com/radare/radare2/blob/master/libr/anal/d/types-x86-windows-32
- https://github.com/radare/radare2/blob/master/libr/anal/d/types-x86-windows-64

**Comment by Maijin** [comment]
@radare This is this issue !

**Comment by Maijin** [comment]
It seems definitely incoherent to have 2 databases that do the same.

**Comment by Maijin** [comment]
Current output:

![image](https://cloud.githubusercontent.com/assets/1408600/19829399/5e0e4b5a-9de0-11e6-94da-5f7a7db62827.png)

The utimate goal (this issue is one step towards this):

strcmp(*s1 : 0x00177fb4 = 0x00177fb4 -> 0x00177fe4, *s2 : 0x00177fb8 = 0x00177fb8 -> 0x0804858f 250382);

**Comment by mrmacete** [comment]
If i understand well, currently both the implementations seems to supports only calling conventions in which arguments are passed on the stack:
https://github.com/radare/radare2/blob/94d47c79bbeeb48ebbcbe93d059f10297f091331/libr/anal/types.c#L121-#L131
https://github.com/radare/radare2/blob/94d47c79bbeeb48ebbcbe93d059f10297f091331/libr/core/disasm.c#L3001-#L3006

are there proposal / wip implementations for generalizing this? i think it's something to take into account before or while merging the functionalities.

**Comment by Maijin** [comment]
It's already generalised for @oddcoder implementation:  https://github.com/radare/radare2/blob/master/doc/calling-conventions.md  and https://github.com/radare/radare2/blob/master/doc/types.md

**Comment by Maijin** [comment]
You can find list of call convention in https://github.com/radare/radare2/tree/master/libr/anal/d with all file beginning by CC

**Comment by radare** [comment]
Cc @oddcoder

**Comment by mrmacete** [comment]
well, actually i found an example here: 

https://github.com/radare/radare2/blob/master/libr/core/anal_tp.c#L48

i'm working on something similar but way simpler for disasm.

**Comment by Maijin** [comment]
Closing this, now it needs bugfix and improvement.

**Comment by Maijin** [comment]
and tests obviously

**Comment by radare** [comment]
Did you missed the red travis?

**Comment by Maijin** [comment]
Maybe after enhancement it got red, Will check and fix ;)

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/19892203/16c241aa-a044-11e6-91ab-205f0aeae4b4.png)
