### ISSUE TITLE
Can't attach to a x64 process under 64-bit Windows

### ISSUE THREAD

**Issue by Forsari0** [radare/radare2#5775]
So, attaching to x86 process works just fine;
But when I'm trying to attach to a x64 process, it's failes:

> $ radare2 -b 64 -d 3788
> = attach 3788 3080
> Assuming filepath C:\Windows\System32\notepad.exe
> Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
> asm.bits 32
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> GetThreadContext: 57
> [0x00000000]>
### Version

> radare2 0.10.6-git 12555 @ windows-x86-32 git.0.10.5-253-g1449d61
> commit: 1449d61850d51c033f6875029ad40814a579e52d build: 2016-09-15

**Comment by radare** [comment]
cc @skuater

**Comment by Maijin** [comment]
```
Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/comctl32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
Cannot find share/radare2/0.10.6-git/format/dll/oleaut32.sdb
```
Still issue with sdb and windows looks like 👎

**Comment by radare** [comment]
again, this is not an issue with sdb, this is because it tires to find the files in the wrong path. dunno how tihs tarball is created. its 1 line to fix this

**Comment by kiryazev** [comment]
> radare2 0.10.6-git 12555 @ windows-x86-32 git.0.10.5-253-g1449d61
Is it really supposed to debug x64-bit processes with 32-bit debugger? It sounds unusual at least for Windows.

**Comment by skuater** [comment]
No is possible attach from r2 x32 version to a x64 process. This dont is a issue is normal.
