### ISSUE TITLE
Repeat disasm

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#5778]
![captura de pantalla 2016-09-15 a las 19 28 45](https://cloud.githubusercontent.com/assets/3474042/18560179/c80a271e-7b7a-11e6-9d65-ac4bb7e58642.png)

**Comment by radare** [comment]
can you write a testcase?

**Comment by radare** [comment]
i guess that happens when disasm size is smaller than string, this was suposed to be fixed half a year ago by ret2libc in addition to all the scrolling and such in the middle of non-disasm stuff in visual mode. and its probably related to the fixes that was added at the time.

**Comment by alvarofe** [comment]
will do, first i have to ask if i can share the bin since you know

**Comment by Maijin** [comment]
You know.

**Comment by radare** [comment]
yes i know that i will have to fix what i have been waiting for months for others to do :P

im used to that :P

**Comment by radare** [comment]
i think this should be easy to reproduce by writing a .c with a long string

**Comment by radare** [comment]
this issue is very important. and can also be reproduced this way:

"Cs $SS;pd 1"

**Comment by radare** [comment]
This is fixed in 5c7313641dacd4f71f6699e5456fab3b5fc1a06b

thanks @alvarofe
