### ISSUE TITLE
radare2 unable to analyze some function  

### ISSUE THREAD

**Issue by najeex** [radare/radare2#5784]
I am playing with [this binary](https://github.com/RPISEC/MBE/blob/master/src/lab01/lab1A) 
and see some function are not show or analyze but ida pro show all fuction. i try many command (iE,afl,afll). plz improve r2 to analayze 
and this is pastbin file http://pastebin.com/aaEfE8q6

**Comment by radare** [comment]
rtfm http://radare.today/posts/analysis-by-default/

**Comment by radare** [comment]
also can you be more specific? which function is not found exactly?

**Comment by radare** [comment]
in short:

```
r2 -e anal.hasnext=true -AA labA1
```

**Comment by Maijin** [comment]
```
sub_80488B0         .text  080488B0 00000004 00000000 00000000 R . . . . . .
sub_80488C0         .text  080488C0 0000002A 0000001C 00000000 R . . . . . .
sub_8048930         .text  08048930 0000001E                   R . . . . . .
sub_8048950         .text  08048950 0000002D 0000001C 00000000 R . . . . . .
```

**Comment by Maijin** [comment]
I suppose

**Comment by Maijin** [comment]
Ping1 @najeex
