### ISSUE TITLE
pds miss some information

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#5786]
![captura de pantalla 2016-09-17 a las 11 28 15](https://cloud.githubusercontent.com/assets/3474042/18607319/0a1ab998-7cca-11e6-95d3-63dd4c66bccb.png)
![captura de pantalla 2016-09-17 a las 11 28 26](https://cloud.githubusercontent.com/assets/3474042/18607320/0a1ddbe6-7cca-11e6-8a5a-133eaa88794d.png)

**Comment by Maijin** [comment]
Would be also really cool to have function prototypes display here :)

**Comment by Maijin** [comment]
As an option ofc

**Comment by radare** [comment]
again, this is a problem related to the recursive emulation of the disasm in the graph. for the same reason asm.emu doesnt works in there

**Comment by alvarofe** [comment]
The main issue here is cause is working by string matching a bad idea imho, cause is searching by `sym`,  `fcn.` and such, the issue here is when the user changes the name of the function. Thus the whole thing should be implemented using RAnalOp to know when is called and can be arch independent. I did some changes with the aim to improve it but is not perfect and must be implemented in another way maybe for 0.10.7

**Comment by alvarofe** [comment]
With my PR

```
[0x10000946c]> pds
0x1000094b9 call sym.imp.memset
0x1000094d8 call petitions
0x1000094e9 call sym.imp.memcpy
0x1000094f9 call 0x100001b20
0x100009510 call sym.imp.pthread_mutex_lock
0x100009523 call sym.imp.memset
0x10000955e call sym.imp.send
0x10000956c call sym.imp.__error
```


![image](https://cloud.githubusercontent.com/assets/3474042/18784316/93f0823a-8191-11e6-9018-7dc5f6d88940.png)

**Comment by alvarofe** [comment]
fixed and tested
