### ISSUE TITLE
3 feature requests pd

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#5787]
Hi,

3 possible feature requests:
1.  pd N until instrunction name
2.   pd from instruction to instruction
3.   immediate disassembly of function for r2 -c

**Comment by Susanne588586** [comment]
ok, I can get 3 through izz

**Comment by oddcoder** [comment]
please note that r2 is extendable using  r2pipe which is have support in lots of programming language (like python for example) and you can create a script that performs both feature 1 & 2 using couple of python lines :)

**Comment by Susanne588586** [comment]
sorry, but I don't want any external scripting language, when debugging my stuff. also, voices told me, that r2pipe is using -c for which some of the feature requests is

however I could pipe to stdout and use awk!

Thanks!

**Comment by Susanne588586** [comment]
ok, as from the chat, 3 can be solved by below or similar:
r2 -qc 'af;s `izz~hash_get_n_entries[3]`;pd 10' /bin/ls| awk '/push|pop/{print}'

"<pancake> also is better to use izq~entries[0]"
