### ISSUE TITLE
/a is broken (?)

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5788]
See test is working with /A but not with /a

https://github.com/radare/radare2-regressions/commit/465244c24983c47a08ed4aa936cb13657ad6b533

While working on https://github.com/radare/radare2/issues/3239

**Comment by dequis** [comment]
/a itself works if you pick a different instruction

```
$ r2 bins/elf/ioli/crackme0x00
 -- Enable asm.trace to see the tracing information inside the disassembly
[0x08048360]> s 0x1000
[0x00001000]> e search.from = 0
[0x00001000]> e search.to = 0x00000050
[0x00001000]> /a and byte [eax], al
Searching 2 bytes in [0x0-0x50]
hits: 1
```

The problem with that test is that "xor al, 0x80" can be encoded in different ways:

```
$ rasm2 -a x86.as 'xor al, 0x80'
3480
$ rasm2 -a x86.nasm 'xor al, 0x80'
3480
$ rasm2 -a x86.nz 'xor al, 0x80'
80f080
$ rasm2 -a x86.olly 'xor al, 0x80'
80f080
```

The string you're looking for in the test case is 3480, not 80f080.

At least on my machine, the asm plugin it ends up using when x86 is specified is x86.nz.

```
[0x00001000]> e asm.arch=x86.as
[0x00001000]> /a xor al, 0x80
Searching 2 bytes in [0x0-0x50]
hits: 2
0x0000003c hit6_0 3480
0x00000040 hit6_1 3480
[0x00001000]> e asm.arch=x86.nz
[0x00001000]> /a xor al, 0x80
Searching 3 bytes in [0x0-0x50]
hits: 0
```

So... close as not a bug?

Update the test to use a less ambiguous instruction?

Change x86.nz to encode `xor al, imm8` the shorter way?

**Comment by radare** [comment]
yep thats know behaviour

there are several ways to encode the same instruction, so its not a good idea to use /a usually, i prefer to use /c or /x, so imho not a bug

**Comment by radare** [comment]
we can maybe make /a encode an insutrction with all available assemblers and options and search for all the pairs at once.. but will be always not covering all cases imho

**Comment by Maijin** [comment]
Can someone fix the test then
