### ISSUE TITLE
?l print string length

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#5789]
https://github.com/radare/radare2/blob/master/libr/core/cmd_help.c#L462
https://github.com/VisualPrankDude/stuff/blob/master/radare2-misc/questionmark_l.diff

**Comment by Maijin** [comment]
What's this issue about ?

**Comment by Maijin** [comment]
I took time to label it, care to elaborate ? ...

**Comment by Maijin** [comment]
If this is just a one line fix, what about just fixing it using github edit ? https://help.github.com/articles/editing-files-in-your-repository/

**Comment by radare** [comment]
Cant add comments if you dont send a pullreq. You can do that by pressing the pencil icon in github. Or using the shell... You missed the 0x..

**Comment by radare** [comment]
Also, this patch is wrong because you are making print on accessing the variable. Use ?v $l to do that

**Comment by VisualPrankDude** [comment]
?v $l is using hex and it does not work:

[0x00404870]> ?v $l foobar; ?l foobar
0x2
6

Also it seemed to have never worked before with core->num->value = strlen (input)

**Comment by radare** [comment]
if you want dec use ?vi
but why is hex a problem?

**Comment by radare** [comment]
works for me

[0x00000000]> ?l patata
[0x00000000]> ?vi
6

**Comment by VisualPrankDude** [comment]
didn't knew about ?|
hex is not a problem, it is, in my version using ?v $l foobar or ?v $l foobarbaz is always 0x2

**Comment by radare** [comment]
but i agree that having to do ?vi after ?l to get the length seems unnatural… so maybe it is good to change that behaviour. what others think?

**Comment by Susanne588586** [comment]
others think it is a good idea :)

**Comment by radare** [comment]
@alvarofe what do you about this change? what's your use case for this?

**Comment by Maijin** [comment]
I'm curious @Susanne588586 @VisualPrankDude at which point do you need this when RE?

**Comment by alvarofe** [comment]
I can't come up with a use case for this, but is true that help says

```
?l str             returns the length of string
```

so make senses implement it in ?l instead of use ?vi afterwards.

**Comment by radare** [comment]
return != print.. but yep

**Comment by Susanne588586** [comment]
so, one can use ?vi, for others:

```
git diff
diff --git a/libr/core/cmd_help.c b/libr/core/cmd_help.c
index aa18d04..cb4e526 100644
--- a/libr/core/cmd_help.c
+++ b/libr/core/cmd_help.c
@@ -462,6 +462,9 @@ static int cmd_help(void *data, const char *input) {
        case 'l':
                for (input++; input[0]==' '; input++);
                core->num->value = strlen (input);
+                if (core->num->value != 0) { /* length 0 */
+               r_cons_printf ("%"PFMT64x"\n", core->num->value);
+                }
                break;
        case 'X':
                for (input++; input[0]==' '; input++);
```

**Comment by VisualPrankDude** [comment]
so, one can use ?vi, for others:

```
git diff
diff --git a/libr/core/cmd_help.c b/libr/core/cmd_help.c
index aa18d04..cb4e526 100644
--- a/libr/core/cmd_help.c
+++ b/libr/core/cmd_help.c
@@ -462,6 +462,9 @@ static int cmd_help(void *data, const char *input) {
        case 'l':
                for (input++; input[0]==' '; input++);
                core->num->value = strlen (input);
+                if (core->num->value != 0) { /* length 0 */
+               r_cons_printf ("%"PFMT64x"\n", core->num->value);
+                }
                break;
        case 'X':
                for (input++; input[0]==' '; input++);
```

tired of this shit !
