### ISSUE TITLE
Better output for mrc PC15 in arm

### ISSUE THREAD

**Issue by alkino** [radare/radare2#5792]
Hi o/
MRC PC15 is an extension on arm proc (http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0464f/BABHDDAA.html) with is common (I think it is on all new arm cpu but can't be sure)/

In radare2 we got: mrc p15, 0, r0, c0, c0, 5 which is correct. But not so helpful. You need to read: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0464f/BABIGAED.html

I think radare2 could help us with more describing.

Here mrc p15, 0, r0, c0, c0, 5 is mov R0, MPIDR which is not a correct instruction but far more readable.

I don't know how to handle this

```
mov R0, MPIDR
mrc p15, 0, r0, c0, c0, 5  ; Set Rn which MPIDR
```

Thanks ;)

**Comment by Maijin** [comment]
@radar Similar idea as the in/out comment: 

![image](https://cloud.githubusercontent.com/assets/1408600/18611614/03a4ffa4-7d3f-11e6-9f75-fdeb53e7f140.png)

**Comment by Maijin** [comment]
To be reported to capstone.
