### ISSUE TITLE
moving build/ in radare2-extras

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5798]
This folder - https://github.com/radare/radare2/tree/master/build never touched since 4 years ago and confusing name "build" located at root of the project, what about remove it and move it in r2e ?

**Comment by radare** [comment]
Wow 4 years

Imho this thing makes more sense and i should make some stuff in here soon or late. Theres no sense in moving to extras because this is suposed to be the build system for r2 and eventually replace the current one or provide an alternative build method.

Also having more than one build system helps to identify compilation issues

**Comment by radare** [comment]
But i agree that at least a readme or a clear foldername would make the whole thing more pleasant

**Comment by XVilka** [comment]
TBH, I'm not sure this one will provide the same flexibility level as the Makefiles + acr. I know current one is very convoluted in some places and hacky too for a few targets, but it's the most portable one.

**Comment by Maijin** [comment]
Agree with @XVilka

**Comment by Maijin** [comment]
the most problematic with this build/ folder is that it is located at the root of the project, it is unused and everyone(beginner) think it is where the logic for build is. Which is not the case.

**Comment by jvoisin** [comment]
There is no point in keeping such thing currently, nor to have different build system: we should only have a well-maintained and clear one (the **moar better gooder simpler one**).

**Comment by Maijin** [comment]
Can we move it here then https://github.com/radare/radare2/tree/master/sys ?

**Comment by radare** [comment]
ok move it there

**Comment by Maijin** [comment]
ok let me do that
