### ISSUE TITLE
Complete random behavior in p=, p=b

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5799]
Just repeat this several time:

`r2 -qc "b 2 ;wx 0xff ; p=b" -|head -n 40`

![image](https://cloud.githubusercontent.com/assets/1408600/18619620/72a9beae-7e01-11e6-9fe6-856715fde16f.png)

![image](https://cloud.githubusercontent.com/assets/1408600/18619623/7e294dda-7e01-11e6-87f5-e60e55364f8f.png)

**Comment by radare** [comment]
Its fixed in master
