### ISSUE TITLE
ir/iR relocations for MS-DOS executable?

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#5810]
[0000:3600]> ir|wc -l
2957
[0000:3600]> iR|wc -l
2957
[0000:3600]> 

not sure, because MS-DOS was before my time, but I could
swear this is not ELF.

Shall I upload teh phile?

**Comment by Maijin** [comment]
duplicate issue use search engine on github please https://github.com/radare/radare2/issues/1200

**Comment by Susanne588586** [comment]
MZ executables only consists of 2 structures: the header and the relocation table.

**Comment by Susanne588586** [comment]
why can Maijin close my issues?

**Comment by Maijin** [comment]
Read my comment.

**Comment by Susanne588586** [comment]
I agree on that, but I shall close myself my issues !

**Comment by Maijin** [comment]
:P faster.
