### ISSUE TITLE
Show in comments the string even if wide string (common thing with windows binaries)

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#5822]
![captura de pantalla 2016-09-21 a las 19 55 52](https://cloud.githubusercontent.com/assets/3474042/18722618/b7d6a2f4-8035-11e6-9a5d-22d4bba8691c.png)

```
[0x00000000]> s 0x1000d85c
[0x1000d85c]> ps
M
[0x1000d85c]> psw
MYRES
```

**Comment by Maijin** [comment]
This already works no ?

**Comment by zonkzonk** [comment]
@Maijin look closer :)

**Comment by Maijin** [comment]
I don't have the binary sadly

**Comment by alvarofe** [comment]
and more, so it seems regression on filter

```
[0x100019ce]> iz~0x1000d85c
vaddr=0x1000d85c paddr=0x0000d85c ordinal=045 sz=12 len=5 section=.data type=wide string=MYRES
[0x100019ce]> s 0x1000d85c
[0x1000d85c]> pd 10
            0x1000d85c     .string "MYRES" ; len=12
```

**Comment by Maijin** [comment]
Yeah the string is defined by analysis and xref exist, probably sone improvement needed :)

**Comment by alvarofe** [comment]
done
