### ISSUE TITLE
de-XOR strings in 'p'

### ISSUE THREAD

**Issue by nullbites** [radare/radare2#5828]
Idea for r2 related to malware analysis:

Implement a 'p' option that will xor strings/data with a string or value and print the result with the other formats (d, s, & u). 

I saw the w option can do that with wox, but this might be a neat feature to implement with the 'p' command.

**Comment by Maijin** [comment]
What is "d, s and u ) ?

**Comment by nullbites** [comment]
The sub functions of 'p' d=disassemble s=strings, sorry about not being
clear on that

**Comment by Maijin** [comment]
Iirc you can use the clipboard (y? command) to do this too. I don't see really benefit of this @radare  ?

**Comment by nullbites** [comment]
Radare is about scriptability, so going from radare to python ord and xor back into radare seems kinda messy. 

That being said I totally get it if this isn't implemented because of other tools.

**Comment by Maijin** [comment]
? The functionality of xor with strings (woD) and character (wox) already exist in at least two ways I just don't get what adding a third one in p will add more ?

**Comment by radare** [comment]
Yeah i agree on that.. But r2 aims to be ortogonal and unixlike so i see this problem can be solved in a more generic way.. Maybe having a syntax for specifying temporal changes in the core.block like it happens wih some @ modifiers. So we will not need to have a different print command for each block manipulation. And as long as i dont want to do that maybe the best way would be to allow write operations to be performed in a temporal and cached way in @.

**Comment by Maijin** [comment]
This is dup of #6091, closing here
