### ISSUE TITLE
arm binary/img as comment? / cannot set breakpoint

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#5841]
Hi,

in this ![ phile 108255a elf](https://cloud.githubusercontent.com/assets/6604362/18808587/64a00c96-8266-11e6-9294-4708bd6642b7.png) I see binary/img as a comment, is it bug or not?

``` 
file 108255A.elf 
108255A.elf: ELF 32-bit MSB relocatable, ARM, LE8 version 1 (SYSV), not stripped
...
r2 -a arm -e cfg.fortunes=0 -e scr.color=0 -e io.cache=true 108255A.elf 
Warning: Cannot initialize program headers
Warning: Cannot initialize dynamic strings
Warning: Cannot initialize dynamic section
[0x08000034]> af
[0x08000034]> pdf
Cannot find function at 0x08000034
[0x08000034]> aa
[aav: using from to 0x8000000 0x811a2d8. and entry0 (aa)
Using vmin 0x8000000 and vmax 0x8119f75
aav: using from to 0x8000000 0x811a2d8
Using vmin 0x8000000 and vmax 0x8119f75
Cannot find function 'entry0' at 0x08000034
[x] Analyze value pointers (aav)
...
           0x080000d8      4c6bc000       stclmi p0, c12, [fp], -0
            0x080000dc      f864c002       invalid
            0x080000e0      f862c1c4       invalid
            0x080000e4      05f86cc1       ldrbeq r6, [r8, 0xcc1]!
            0x080000e8      b304f86b       movwlt pc, 0x486b           ; "l^._._a_.`.`W`.`.aOa.a.bIb.b.cCc.c.d@d.d.e=e.e.f=f.f.g=g.g.h?h.h.iCi.i.jHj.j.kOk.k.lWl.m.m`m.n.nkn.o.oxo.p+p.p.q:q.q.rKr.s.s]s.t.tpt.u(u.u.v>v.v.wVw.x.xnx.y*y.y.zFz.{.{c{.|!|.|.}A}.~.~b~..#.....G.....k...0.....W.........G.....r...;.....i...3.....d...0.....c...1.....f...6.....n...?.....z...M... ....._...4.....u...L...$.....h...B.........d...@.........i...G...&.....v...V...8.........n...R...7.........u...\...D...-......." 0x0000486b 
            0x080000ec      d14c1119       invalid
            0x080000f0      0ef867b0       mrceq p7, 7, r6, c8, c0, 5
            0x080000f4      c10000f8       strdgt r0, r1, [r0, -r8]
            0x080000f8      6dc1b304       stclvs p3, c11, [r1, 0x10]
            0x080000fc      f863c002       invalid
            0x08000100      f865b1fa       invalid
            0x08000104      044c0900       strbeq r0, [ip], -0x900
```

**Comment by VisualPrankDude** [comment]
also debugging has problems, setting e asm.arch to arm doesn't work:

```
[0xd05c3bf55f7f0000]> e asm.arch=arm
[0xd05c3bf55f7f0000]> db main
Cannot get breakpoint bytes. No architecture selected?
Cannot set breakpoint at 'main'
```

**Comment by radare** [comment]
What else do you expect?

**Comment by VisualPrankDude** [comment]
@radare what else do you need, to set a breakpoint?

e cfg.bigendian=true also did not work :/

entrypoint is 0x00. Is it a valid ELF?

readelf -h 108255A.elf 
ELF Header:
  Magic:   7f 45 4c 46 01 02 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, big endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          1154933 (bytes into file)
  Flags:                             0x1673400, Version1 EABI, <unknown>
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         8
  Section header string table index: 7

**Comment by VisualPrankDude** [comment]
program header is broken, I wonder how this works

**Comment by radare** [comment]
this is thumb, not arm32, maybe the entrypoint.also why are you passing all those useless eval options in the example if they just make things hard to understand?

you cant debug ARM binaries on X86 systems unless you use an emulator or something. so thats why breakpoints dont work.. also breakpoints will not work if you dont run the program in debugger mode..

**Comment by radare** [comment]
where is this executable coming from? it looks like its full of crap and its not even a working executable.
