### ISSUE TITLE
Analysis crippled during debugging on Windows

### ISSUE THREAD

**Issue by pielgrzym** [radare/radare2#5847]
Hi,

When running radare2 with only analysis options (`r2 -A gametime.exe`) it discovers plethora of functions, symbols, xref searches work etc. The moment I enable debugger (doesn't matter if I use `doo` or run `r2 -Ad gametime.exe`), whole analysis functionality is crippled and I can see only some imported symbols (for example: `afl` returns only a handful of imported functions, xref searches do not work at all etc.).

Prerequisites to reproduce:
1. Analyzed file: https://ctf.csaw.io/static/uploads/121e6daf97e57856de8183ba1e56e55b/gametime.exe
2. Radare cross-compiled on debian unstable with `./sys/mingw32.sh` and `mingw-w64` version `4.0.6-1` for 32bit Windows
3. The issue was observed on _Microsoft Windows Server 2008 SP2 Datacenter edition_. The whole setup is very easy to recreate since it was an EC2 instance (`t2.small`) with Windows system mentioned above. Only cmder and r2 were installed. Connection was made via `xfreerdp` (if this matters at all).

**Comment by Maijin** [comment]
@skuater ^

**Comment by radare** [comment]
try again i fixed a bug that may affect this issue

works fine on linux and osx

**Comment by XVilka** [comment]
@pielgrzym ping?

**Comment by XVilka** [comment]
No answer, moving to the later milestone.

**Comment by Maijin** [comment]
too old

**Comment by ljani** [comment]
I had the same problem with some executable, which I cannot remember anymore. However I just tested with [`gametime.exe`](https://github.com/isislab/CSAW-CTF-2016-Quals/blob/master/Reverse/Gametime/gametime.exe) with r2 v2.5.0 and output from `afl` before and after `doo` seem to be equal.

**Comment by Maijin** [comment]
@ljani reopen a new issue, test with r2 from git and use the template to report issue please
