### ISSUE TITLE
pxr color reset?

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#5850]
morrn,

$ r2 -e scr.color=0  -qdc "pxr@dx" ./bin/mycustombin

does not wok.

still displaying in color.

**Comment by radare** [comment]
Theres no dx flag at all

But will chk that

**Comment by VisualPrankDude** [comment]
@radare er, bx. anyway using "dr <register name>" I could also get fpu register

**Comment by radare** [comment]
cant reproduce

**Comment by zonkzonk** [comment]
@radare knurr
