### ISSUE TITLE
Ctrl+C (^C) within attached process seems not to be implemented

### ISSUE THREAD

**Issue by daniel-rome** [radare/radare2#5855]
After attach r2 with a infinite process (e.g while(1){}) and type "dc", the ctrl+c handler (signal) seems not to be implemented.

**Comment by radare** [comment]
When process is not running in the same terminal you must handle rconsbreak() passing a callback that does a kill() to the target pid. This way the debugger will catch the event. Send sigcont or anything like that

You can verify the behaviour by running kill in another terminal by hand

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
Another option would be to add a config and set this always to false by default, the user (or r2 itself) can set it to true when necessary. This way we introduce no regression and it will be useful

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/6076

thanks!
