### ISSUE TITLE
[radare2] Different behavior when using `-d` vs `ood`. `-d` makes radare2 to throw: Cannot determine xref search boundaries, Oops invalid rangen calls (aac)

### ISSUE THREAD

**Issue by arno01** [radare/radare2#5865]
Dear devs,

I am observing a different radare2's behavior when opening a binary with `-d` or via `ood`, so that with `-d` radare2 seem to be unable to determine xref search boundaries nor it can analyze function calls (aac)

```
?V
0.10.6 aka 0.10.5-389-ge78b561 commit 12515
```

please find the output is below:
### with `-d`

```
radare2 -A -d ./c
Process with PID 25297 started...
= attach 25297 25297
bin.baddr 0x00400000
Assuming filepath /home/arno/c
asm.bits 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[Cannot determine xref search boundariesr references (aar)
[x] Analyze len bytes of instructions for references (aar)
[Oops invalid rangen calls (aac)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
```
### with `ood`

```
$ radare2 -A ./c
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
 -- This page intentionally left blank.
[0x00400430]> ood
Process with PID 25223 started...
File dbg:///home/arno/c  reopened in read-only mode
= attach 25223 25223
Assuming filepath /home/arno/c
```

Am I doing something wrong?

Cheers

**Comment by radare** [comment]
aslr affects, also in the debugger it starts analyzing in the loader, not the executable

**Comment by arno01** [comment]
I also thought that ASLR affects this, but I have tried to disable it:
```
# echo 0 | tee /proc/sys/kernel/randomize_va_space
0
```

as well as:
```
setarch `arch` -R radare2 -A -d ./c
```

But that neither one helped.

Here is the ascii recording:
https://asciinema.org/a/b1z7p7softmj0rsk3uapy2la3

**Comment by arno01** [comment]
@radare since you mentioned that it starts analyzing in the loader, not the executable, then why it works with the gdb alone? I don't really know the whole inner-working of the radare2, so if this is expected behavior I described in subj., then feel free to close this issue.

**Comment by radare** [comment]
gdb is not analyzing code at all.

symbol information should be available in r2, but functions only will appear if you analize code. you can do aa @ entry0 if you want to have similar results

also bear in mind that the memory layout is different in disk and debugger
