### ISSUE TITLE
pd -N gives unexpected output

### ISSUE THREAD

**Issue by m1ghtym0** [radare/radare2#5879]
Unfortunately I have not much time at the moment, to have a look at source of the problem myself,
but here is the output that confuses me: http://pastebin.com/JBetaNN7

I would expect the same output from those two commands, however I don't get what's it's actually displaying with the second one:
     
    pd 6 @ 0x0004137b
    0x0004137b      488d3d1e2612.    lea rdi, str._bin_sh        
    0x00041382      488d742430         lea rsi, [rsp + local_30h]  
    0x00041387      c7052f613600.     mov dword [0x003a74c0], 0   
    0x00041391      c70529613600.    mov dword [0x003a74c4], 0   
    0x0004139b      488b10                 mov rdx, qword [rax]
    0x0004139e      e86d8f0700          call sym.execve

   pd -6 @ 0x0004139e
   0x0004139e      488b052d3b36.   mov rax, qword [0x003a4ed2] 
   0x000413a5      488d3d1e2612.   lea rdi, 0x001639ca 
   0x000413ac      488d742430        lea rsi, [rsp + local_30h] 
   0x000413b1      c7052f613600.    mov dword [0x003a74ea], 0   
   0x000413bb      c70529613600.   mov dword [0x003a74ee], 0  
   0x000413c5      488b10                mov rdx, qword [rax]

Correct me if I'm wrong, but I was under the impression both outputs used to be the same.
I'll just give you another output, that you can see the second command is not doing what you might think it does at first glance (I'm not sure what it is displaying, to be honest):

    pd 12 @ 0x0004137b
    0x0004137b      488d3d1e2612.      lea rdi, str._bin_sh  
    0x00041382      488d742430           lea rsi, [rsp + local_30h]  ; 0x30 ; 
    0x00041387      c7052f613600.       mov dword [0x003a74c0], 0  
    0x00041391      c70529613600.      mov dword [0x003a74c4], 0 
    0x0004139b      488b10                   mov rdx, qword [rax]
    0x0004139e      e86d8f0700            call sym.execve
    0x000413a3      bf7f000000             mov edi, 0x7f
    0x000413a8      e8038f0700            call sym._exit 
    0x000413ad      488b15b43a36.      mov rdx, qword [0x003a4e68]
    0x000413b4      f7d8                        neg eax
    0x000413b6      c744240cffff.          mov dword [rsp + local_ch], 0xffffffff 
    0x000413be      648902                   mov dword fs:[rdx], eax

**Comment by radare** [comment]
cant reproduce are you using r2 from git?

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by m1ghtym0** [comment]
Hi

Sorry had very little time lately...
I used r2 from git, and rechecked, just to be sure;-)
Here is the full command history: http://pastebin.com/gEh1x4Le
And here is the libc: https://transfer.sh/107a9a/libc-2.19.so
Would appreciate if somebody could verify my results and reopen this issue
if it's reproducable.
