### ISSUE TITLE
Bash autocompletion

### ISSUE THREAD

**Issue by vdun** [radare/radare2#5887]
For options from : `r2 -h`

**Comment by Maijin** [comment]
???

**Comment by Maijin** [comment]
Please detail what that means.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by vdun** [comment]
I mean this: http://www.tldp.org/LDP/abs/html/tabexpansion.html
would be great to have this with bash, zsh, ...
I'm using the latest git version:
```
# r2 -v
radare2 0.10.6 12528 @ linux-x86-64 git.0.10.6-22-gec25d84
commit: ec25d8475c527615770bce31480f6614066455d0 build: 2016-09-29
```

**Comment by Maijin** [comment]
You mean that kind of file then https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose

**Comment by vdun** [comment]
yes

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/issues/5887

**Comment by webhat** [comment]
Hi,

where is the completion file?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/doc/bash_autocompletion.sh

**Comment by webhat** [comment]
Thanks!
