### ISSUE TITLE
Aseo Anal does not work properly

### ISSUE THREAD

**Issue by killabytenow** [radare/radare2#5891]
The core command 'aeso' does not work properly.

When I use it, it starts executing code at the current `PC`, but it seems (as I understand from the `libr/core/cmd_anal.c` source code) that it sets the breakpoint on the current `(core->addr+current_opcode->size)` address, which has not any sense:
```
                case 'o': // "aeso"
                        // step over
                         op = r_core_anal_op (core, addr);
                        if (op && op->type == R_ANAL_OP_TYPE_CALL) {
                                until_addr = addr + op->size;
                        }
                        r_core_esil_step (core, until_addr, until_expr);
                        r_anal_op_free (op);
```
The behaviour of this bug can be observed more precisely in the following video posted in youtube:
https://www.youtube.com/watch?v=feEyQXVIP6Y

Additionally please note that `until_expr` has not any explicit value assigned, and I think it should be substituted by `NULL`, but I am not very sure.

If you want I can make a PR for solving this issue, but I prefer to comment it before making any effort.

**Comment by killabytenow** [comment]
My dirty solution:
```
diff --git a/libr/core/cmd_anal.c b/libr/core/cmd_anal.c
index 5eea64a..9cbb2f6 100644
--- a/libr/core/cmd_anal.c
+++ b/libr/core/cmd_anal.c
@@ -2606,9 +2606,15 @@ static void cmd_anal_esil(RCore *core, const char *input) {
                        break;
                case 'o': // "aeso"
                        // step over
-                       op = r_core_anal_op (core, addr);
+                       op = r_core_anal_op (
+                                       core,
+                                       r_reg_getv (
+                                               core->anal->reg,
+                                               r_reg_get_name (
+                                                       core->anal->reg,
+                                                       R_REG_NAME_PC)));
                        if (op && op->type == R_ANAL_OP_TYPE_CALL) {
-                               until_addr = addr + op->size;
+                               until_addr = op->addr + op->size;
                        }
                        r_core_esil_step (core, until_addr, until_expr);
                        r_anal_op_free (op);
```
Is this ok, or is it risky to depend on the `op->addr` value? It works flawlessly with my AVR Anal Plugin.

**Comment by killabytenow** [comment]
I have made a mini-pull request for checking if this solution breaks the radare2-regressions tests: https://github.com/radare/radare2/pull/5893

**Comment by radare** [comment]
fixed
