### ISSUE TITLE
Would it make sense to allow space in the r_num_as_string function?

### ISSUE THREAD

**Issue by bluec0re** [radare/radare2#5896]
Currently, ? 32 produces a result like
```
32 0x20 040 32 0000:0020 32 00100000 32.0 32.000000f 32.000000
```
As space can actually be printed without any escapes, would it be possible to allow it in the r_num_as_string function?
This would produce the output
```
32 0x20 040 32 0000:0020 32 " " 00100000 32.0 32.000000f 32.000000
```

**Comment by radare** [comment]
yep it should in fact its a bit inconsistent that this column is only shown when the char is printable. mind to send a PR?

**Comment by trufae** [comment]
hello?
