### ISSUE TITLE
rahash2 uncrypt xored file failed

### ISSUE THREAD

**Issue by futex** [radare/radare2#5908]
I want to uncrypt a data file with rahash2, i use this command line:

`rahash2 -D xor -S XNplLxvSG39YeXNXYidwXaOcq9h7uJZs jhg45s >> jhg45s.dll`

Normaly after that i have a dll file (take care, it's a malware), but rahash2 failed, in return i have a unknown data type file.

I use this python code to retrieve the dll file
```
def xor(data, key):
    l = len(key)

    decoded = ""
    for i in range(0, len(data)):
            decoded += chr(data[i] ^ ord(key[i % l]))


    return decoded

data = bytearray(open('jhg45s', 'rb').read())`

key = 'XNplLxvSG39YeXNXYidwXaOcq9h7uJZs'
a = xor(data, key)
print a
```
The crypted data file is here (pass: infected):
[jhg45s.zip](https://github.com/radare/radare2/files/508074/jhg45s.zip)

**Comment by radare** [comment]
use > not >>

**Comment by radare** [comment]
the seed if its a string and not a number should be prefixed with s:

**Comment by futex** [comment]
Yes, you right with s: it's better :)

 rahash2 -D xor -S s:XNplLxvSG39YeXNXYidwXaOcq9h7uJZs jhg45s > jhg45s2.dll

file jhg45s2.dll
jhg45s2.dll: PE32 executable (DLL) (console) Intel 80386 (stripped to external PDB), for MS Windows

Thank you

**Comment by radare** [comment]
but i guess rahash2 should not allow strings without the s: otherwise its pretty easy to miss that point here. What do you think?

**Comment by Maijin** [comment]
Agree, this is confusing :S

**Comment by radare** [comment]
should be fixed in my last commit, please confirm

**Comment by Maijin** [comment]
@futex

**Comment by futex** [comment]
Nice :) thank a lot
