### ISSUE TITLE
glitch in hints

### ISSUE THREAD

**Issue by radare** [radare/radare2#5925]
looks like call reg shouldnt have a hotkey
<img width="562" alt="screen shot 2016-10-05 at 23 06 08" src="https://cloud.githubusercontent.com/assets/917142/19131824/48d0c610-8b51-11e6-91bb-2d3099fef2c7.png">

**Comment by radare** [comment]
i fixed this yesterday

**Comment by ret2libc** [comment]
oh ok :( :( thanks
