### ISSUE TITLE
TrailingSpaces issues in pdsf

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5933]
I've passed the test to BROKEN=1 as it is a mess to fix this all the time:

https://github.com/radare/radare2-regressions/blob/master/t.esil/apple#L23

**Comment by radare** [comment]
This test is important. Dont do that

**Comment by Maijin** [comment]
What to do then, leaving it red? 👎

**Comment by radare** [comment]
fix the problem or fix the test, what is the problem?

we suffered several regressions because you just marked them as broken instead of trying to investigate the reason or notify me

**Comment by Maijin** [comment]
Well that's why I'm opening an issue and not leaving it BROKEN=1 without telling you 👍

**Comment by radare** [comment]
fixed in master, pls update test

**Comment by Maijin** [comment]
Fixed, notice also NAME='iphone-arm-esil tests' contains trailing space. same file
