### ISSUE TITLE
Any plans regarding support of structure offsets and enums in the disassembly?

### ISSUE THREAD

**Issue by bluec0re** [radare/radare2#5934]
Like IDA Pro does [1] [2]. I think the later one might work with a flag (workaround?)?

e.g.:
from

``` asm
mov eax, 1
```

``` asm
mov rbx, [rax + 0x20]
```

to

``` asm
mov eax, PF_Exec
```

``` asm
mov rbx, [rax + elf_header.phoff]
```

[1] https://www.hex-rays.com/products/ida/support/idadoc/472.shtml
[2] https://www.hex-rays.com/products/ida/support/idadoc/473.shtml

**Comment by Maijin** [comment]
It's already supported with t command @XVilka @oddcoder can give you more insight

**Comment by bluec0re** [comment]
I'd already implemented it for local variables (t command), but couldn't find it during the implementation in a general manner (maybe something for the hint part?)

**Comment by bluec0re** [comment]
what's about replacing the (numeric) `immbase` implementation of hints with  `pf` format strings? This would make it much more flexible and could represent all of the current supported bases, right?

**Comment by XVilka** [comment]
At first, this is currently unsupported as-is, but can be workarounded with ahi, if improve it a bit.
But yes, full fledged support is already in plans.

**Comment by MariasStory** [comment]
I am not sure if it is the right ticket to ask.
Is this one related to the problem described in the following solution:
https://insinuator.net/2016/10/reverse-engineering-with-radare2-part-3/
Shouldn't it be done automatically?

**Comment by Maijin** [comment]
This blog post seems to use old radare2, the visual graph isn't utf8

**Comment by bluec0re** [comment]
It's using the most current git version of 10/24/2016. I'd just disabled the utf-8 output as I didn't had the time to make it work in the blog HTML output.

**Comment by radare** [comment]
are you using scr.html=true ?

**Comment by bluec0re** [comment]
Not yet as it interrupted my workflow during the post development. Something like a HTML pipe would be nice. So you would have a ASCII colored output in the console but a HTML one if you redirect it to a file or command.

**Comment by radare** [comment]
@bluec0re see latest master. i have added H> for the html pipe

**Comment by bluec0re** [comment]
Nice, thx! :smiley:
