### ISSUE TITLE
Possible UB at anal_x86_cs.c due return NULL when insufficient memory

### ISSUE THREAD

**Issue by j123123** [radare/radare2#5940]
At https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L81function getarg() which can return a NULL, the result strdup() call, or the result of calling r_str_newf(). strdup() can return NULL if insufficient memory

If we analyze r_str_newf() function here is also strdup() function, and even malloc () i.e. if we out of memory, it may well return NULL. However, getarg() function "can" return NULL and not because of lack of memory. For example here:

```
    if (!insn->detail) {
        return NULL;
    }
```

and here:

```
    if (n < 0 || n >= INSOPS) {
        return NULL;
    }
```

Returns NULL from getarg function can be either due to lack of memory, and the "usual way". There is clearly something wrong.

For example, here https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L656-L662

```
        {
            char *src = getarg (&gop, 1, 0, NULL);
            char *dst = getarg (&gop, 0, 1, NULL);
            esilprintf (op, "%s,%s,>>>,%s", src, dst, dst);
            free (src);
            free (dst);
        }
```

esilprintf () is a wrapper around printf-like functions, and inside does not check the arguments passed to it on a NULL, if getarg() returns NULL you got UB: http://stackoverflow.com/a/11589479/6616147:

> First things first: printf is expecting a valid (i.e. non-NULL) pointer for its %s argument so passing it a NULL is officially undefined. It may print "(null)" or it may delete all files on your hard drive--either is correct behavior as far as ANSI is concerned (at least, that's what Harbison and Steele tells me.)

**Comment by radare** [comment]
can you send a PR fixing this? thanks!
