### ISSUE TITLE
X86 segment override confuses rasm2

### ISSUE THREAD

**Issue by Maykeye** [radare/radare2#5967]
Example program for gcc: `int main() { __asm__ ( "movl %fs:(1), %eax\n"); }`

r2's `pd 10 @main` prints `0x004004da      648b04250100.  mov eax, dword fs:[1]`

`rasm2 -D 648b042501000000` prints the same. 

However it can't convert it back.
`rasm2 'mov eax, dword fs:[1]'` = 89e0 (mov eax, esp)

Also if you start to play with syntax, rasm2 starts misbehave even more:

`rasm2 -b 32 'mov edi, fs:[65534]'` = 89e7 (sameish)
`rasm2 -b 32 'mov edi, [fs:65534]'` = 8a3ce500000000 (even more strange `mov bh,BYTE PTR [eiz*8+0x0]`)

(output is same for -b32 or -b64)

It also doesn't report error on something silly like 

`rasm2 'mov fs:[1],ds:[1]'` (88dc)
`rasm2 'mov fs:[1],[ds:1]'` (8a23)
`rasm2 'mov [fs:1],ds:[1]'` (881c24)
`rasm2 'mov [fs:1],[ds:1]'` (8a03)

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
a___  32         x86.tab     LGPL3   x86 table lookup assembler
```

**Comment by Maijin** [comment]
@Svenito ^

**Comment by Svenito** [comment]
:thumbsup:
