### ISSUE TITLE
Jump line is not drawn if it starts on the last printed disassembled line

### ISSUE THREAD

**Issue by Maykeye** [radare/radare2#5974]
Jump line is not drawn if it starts on the last printed disassembled line. If jump source is located on any other line, it's drawn. However if it's on the very last line, jump line goes somewhere,

Take for example IOLI's crackme0x00. 

`pd 10 @ 0x080483b6`

it ends with `0x080483d4      75eb           jne 0x80483c1`. Address 0x80483c1 is on the screen. 

Expected behavior for r2 is to draw a jump line from 0x080483d4 to 0x80483c1 as it does if you ask to print more lines  ( `pd 11 @ 0x080483b6`)

Screenshot which shows that line at 0x080483d4 appears and disappears depending if it's the last instruction:

![JumpLines](https://cloud.githubusercontent.com/assets/13607441/19411811/a76f343e-9332-11e6-9c10-d31776427a27.jpg)

**Comment by radare** [comment]
Test case:
```
e asm.arch=x86
e asm.bits=32
e scr.utf8=0
e asm.lines=1
e asm.comments=0
wx 803d1ca0040833740ceb1c83c004a318a0088ffd2a118a00408b1085d275eb
pd 12~?=
pd 13~?=
```

EXPECTED_OUTPUT:

```
3
3
```

What we get:

```
2
3
```
