### ISSUE TITLE
Wrong opcodes in x86 (push [esp])

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#5976]
In rasm2 opcode for `push [esp]` is a like for `push eax`. I think, it is a wrong:
```
$ rasm2 -a x86 -b 32 -
push eax
50
push [esp]
50
push [esp+4]
54
```

In other disasm, for example keystone:
```
$ ./kstool x32 "push [esp]"
push [esp] = [ ff 34 24 ]
$ ./kstool x32 "push [esp+4]"
push [esp+4] = [ ff 74 24 04 ]
$ ./kstool x32 "push eax"
push eax = [ 50 ]
```

r2 from git:
```
$ r2 -v
radare2 0.10.6 12666 @ linux-x86-64 git.0.10.6-140-g98ea86a
commit: 98ea86a59afb6a4eeaa71bdcfa0b323524b595b7 build: 2016-10-17
```

**Comment by radare** [comment]
you can use asm.ks asm.as or asm.olly, or fix the asm.nz <http://asm.nz/> one

thx for reporting

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
a___  32         x86.tab     LGPL3   x86 table lookup assembler
```

**Comment by Svenito** [comment]
:ok:
