### ISSUE TITLE
Segfault in types

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5978]
You can try on any bin.

```
tk WORD=type
tk type.WORD=w
tk type.WORD.size=16
tk VbHeader=struct
tk struct.VbHeader=szVbMagic,wRuntimeBuild,szLangDll,szSecLangDll,wRuntimeRevision,dwLCID,dwSecLCID,lpSubMain,lpProjectData,fMdlIntCtls,fMdlIntCtls2,dwThreadFlags,dwThreadCount,wFormCount,wExternalCount,dwThunkCount,lpGuiTable,lpExternalCompTable,lpComRegisterData,bszProjectDescription,bszProjectExeName,bszProjectHelpFile,bszProjectName
tk struct.VbHeader.szVbMagic=char,0,4
tk struct.VbHeader.wRuntimeBuild=WORD,4,0
tk struct.VbHeader.szLangDll=char,6,14
tk struct.VbHeader.szSecLangDll=char,20,14
tl VbHeader @ 0x401314
pd @ 0x401314
```

GDB Backtrace http://pastebin.com/K7E5niJJ

**Comment by killabytenow** [comment]
I don't know if it is the same bug, but this two examples are enough for crashing radare:

EXAMPLE 1:
[0x004049a0]> tk VbHeader=struct
[0x004049a0]> tk struct.VbHeader=szVbMagic
[0x004049a0]> tk struct.VbHeader.szVbMagic=char,4,0
[0x004049a0]> tl VbHeader @ 0
[0x004049a0]> pd @0
Violación de segmento (`core' generado)

EXAMPLE 2:
$ r2 /bin/ls 
 -- Here be dragons.
[0x004049a0]> tk VbHeader=struct
[0x004049a0]> tl VbHeader @ 0
[0x004049a0]> pd @0
Violación de segmento (`core' generado)

**Comment by radare** [comment]
should be fixed , pls confirm and blame @oddcoder for anything else
