### ISSUE TITLE
Create a comment in Visual mode create unsafe comment for project

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5981]
Try to add a comment with a ` in visual mode with ;

then see the output of `CC`

    0x100001174 CCu "```lol"

This what's saved in project file, it should be base64

**Comment by radare** [comment]
cant reproduce

**Comment by Maijin** [comment]
https://asciinema.org/a/2xxu6ioep7wpatx5ys00f7dlf

**Comment by radare** [comment]
The project saves with CC*, so the outpiut of CC is not consumed by r2 at all. your terminal is too tall. i cant read the command you type but i assume this is what you are doing

**Comment by Maijin** [comment]
ok then it has been already fixed.
