### ISSUE TITLE
quoting is fun

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#5991]
this is a lot of error messages: 

[0x00404879]> ./ "
Searching 1 bytes from 0x00400000 to 0x0061d360: 22 
Searching 1 bytes in [0x400000-0x61d360]
hits: 79
Invalid address (a"a.)
Slurping file '$"HT$(1T.'
cannot open file
Invalid address (HD$8*":.)
Invalid address (I9@@)
sh: 1: Syntax error: Unterminated quoted string
Invalid address (I9@@)
sh: 1: Syntax error: Unterminated quoted string
Invalid address (H9G@)
Invalid address (H9G@)
Invalid address (H1L$1u"HD$ Hl$ .)
cannot open file '' to read offsets
sh: 1: Syntax error: Unterminated quoted string
Invalid address (uMu"p@.)
parse: Missing backtick in expression.
|ERROR| Invalid command '0x004176b3 hit0_45 .e"`shellshell-a.' (0x30)
Slurping file '"t#.'
cannot open file
Slurping file '"t##.'
cannot open file
parse: Missing backtick in expression.
|ERROR| Invalid command '0x0041b845 hit0_57 .^d"We`.' (0x30)
parse: Missing backtick in expression.
|ERROR| Invalid command '0x0041b85d hit0_58 .`|"XMH.' (0x30)
Invalid address (XA.)
Invalid address (F"@V"@f"@v".)
Invalid address (V"@f"@v"@".)
Invalid address (f"@v"@"@".)
Invalid address (v"@"@"@".)
0x1010246
[0x0041b8b5]> !r2 -v
radare2 0.10.6 12647 @ linux-x86-64 git.0.10.6-139-g645aea9
commit: 645aea930291308bdf02cc91a40930b8c9985c47 build: 2016-10-16

**Comment by radare** [comment]
what else do you expect? this is normal behaviour you are executing the output of the search command which are not r2 commands.

**Comment by Susanne588586** [comment]
@radare I oversaw the dot or got  intercepted.
