### ISSUE TITLE
Types link is broken

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#5999]
```
tk WORD=type
tk type.WORD=w
tk type.WORD.size=16
tk VbHeader=struct
tk struct.VbHeader=szVbMagic,wRuntimeBuild,szLangDll,szSecLangDll,wRuntimeRevision,dwLCID,dwSecLCID,lpSubMain,lpProjectData,fMdlIntCtls,fMdlIntCtls2,dwThreadFlags,dwThreadCount,wFormCount,wExternalCount,dwThunkCount,lpGuiTable,lpExternalCompTable,lpComRegisterData,bszProjectDescription,bszProjectExeName,bszProjectHelpFile,bszProjectName
tk struct.VbHeader.szVbMagic=char,0,4
tk struct.VbHeader.wRuntimeBuild=WORD,4,0
tk struct.VbHeader.szLangDll=char,6,14
tk struct.VbHeader.szSecLangDll=char,20,14
tl VbHeader @ 0x401314
pd @ 0x401314
```

Stuff is printing multiple time instead of just one time:

![image](https://cloud.githubusercontent.com/assets/1408600/19535777/687bba3a-9649-11e6-8549-b63a0b0cfca4.png)

**Comment by radare** [comment]
cc @oddcoder

**Comment by Maijin** [comment]
Just do a r2 -nn -c "Vp" /bin/ls ...

**Comment by radare** [comment]
Related with 03028730f067e332dda30f430465f6b083f13347

**Comment by Maijin** [comment]
Well sad this isn't done for 1.0.0

**Comment by radare** [comment]
tired of waiting. and i dont have the time to do it and will prefer to have more time window to properly test it. so move it to 1.1

**Comment by oddcoder** [comment]
well I just wanted to add a little note here, that the struct you defined is some how invalid 
```
tk struct.VbHeader=szVbMagic,wRuntimeBuild,szLangDll,szSecLangDll,wRuntimeRevision,dwLCID,dwSecLCID,lpSubMain,lpProjectData,fMdlIntCtls,fMdlIntCtls2,dwThreadFlags,dwThreadCount,wFormCount,wExternalCount,dwThunkCount,lpGuiTable,lpExternalCompTable,lpComRegisterData,bszProjectDescription,bszProjectExeName,bszProjectHelpFile,bszProjectName
````
then you only define the first 4, IK this isn't the reason for the bug but I was just saying because far untill now we hold no input validation because each line is evaluated individually.

**Comment by Maijin** [comment]
Yep I know, just stripped it because it's enough for reproducing the bug.

**Comment by oddcoder** [comment]
fixed via https://github.com/radare/radare2/pull/6182

**Comment by radare** [comment]
Awesome! Thanks for fixing!
