### ISSUE TITLE
[MIPS] syscall is not recognized in asm.pseudo

### ISSUE THREAD

**Issue by peperunas** [radare/radare2#6001]
`asm.pseudo = false`
![false](http://storage3.static.itmages.com/i/16/1020/h_1476963136_9142835_7e6d05153f.png)
`asm.pseudo = true`
![true](http://storage6.static.itmages.com/i/16/1020/h_1476963196_1852906_6d00e517db.png)

I tried patching it myself by adding

```
{ "syscall",  "syscall", 0},
```

in `libr/parse/p/parse_mips_pseudo.c` but it seems that the syscall "string" doesn't get even passed to the `replace()` method (I tried to output `argv[0]` each time and `syscall` isn't there)

**Comment by radare** [comment]
is this fixed by https://github.com/radare/radare2/pull/6002 <https://github.com/radare/radare2/pull/6002> ?

**Comment by Krishath** [comment]
Nope, I just found that "error" and fixed it

**Comment by radare** [comment]
👍
