### ISSUE TITLE
Add shortcut for S 0 0 $s $s foo mrwx

### ISSUE THREAD

**Issue by radare** [radare/radare2#6005]
needed to make analysis work when loading with -nn

maybe we shuold unset some options and tune anal.noncode a little bit more to ease this thing

**Comment by radare** [comment]
this should work with `e io.va=0` and it is not. we need to tune the is_valid_address() function a bit more

**Comment by Maijin** [comment]
Duplicate of https://github.com/radare/radare2/issues/5289

**Comment by radare** [comment]
I dont think this is a dupe

**Comment by Maijin** [comment]
Definitely dup with the other issue
