### ISSUE TITLE
Fixing overlapping edges in graph mode 

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#6011]
things like those
![screenshot_2016-10-21_20-24-39](https://cloud.githubusercontent.com/assets/10424605/19608188/36215ed8-97d8-11e6-8a7f-df3aef804454.png)
![screenshot_2016-10-21_20-21-01](https://cloud.githubusercontent.com/assets/10424605/19608195/3b7f4e1c-97d8-11e6-81ed-a6b515b1c7d9.png)

**Comment by radare** [comment]
There was an issue for that already iirc
