### ISSUE TITLE
Saving notes for a project using "Pn -" seems not to work

### ISSUE THREAD

**Issue by newlog** [radare/radare2#6017]
The asciinema explains the issue:

https://asciinema.org/a/8l5nw0jpc7512ri5akeip2joc

Basically, as I understand it, the note is attempted to be saved in the <project_name>.d directory, but that directory does not exist.

After @Maijin comment:

The commands I executed, follow:
1) open r2: r2 /bin/ls
2) Save/Create project: Ps dummy_project
3) Create note with default editor (vim): Pn -
4) Type text in vim
5) Save contents in vim by executing: Esc :wq
6) Save operation through vim failed

My guess: directory dummy_project.d does not exist, so vim fails to save the file when :wq

**Comment by Maijin** [comment]
You didn't save the notes after doing Pn -.

**Comment by radare** [comment]
Can we have a testcase for this? Ill take care of thisbefore the release
