### ISSUE TITLE
Colours radiff2 graphdiff output

### ISSUE THREAD

**Issue by Nanreit** [radare/radare2#6021]
All code blocks are being output by 'radiff2 -g' with fillcolor="grey" whether there are large differences or none. This can be reproduced with: `radiff2 -g main /bin/false /bin/true | xdot -`

Not sure if this is related to problems mentioned in [#5388](https://github.com/radare/radare2/issues/5388)?

**Comment by radare** [comment]
This is a regression. I have already noticed this but didnt had time to check it out.

**Comment by XVilka** [comment]
@deepakchethan can you please check this one too?

**Comment by deepakchethan** [comment]
This issue can be closed:

<img width="754" alt="Screen Shot 2019-08-26 at 7 19 34 PM" src="https://user-images.githubusercontent.com/20895544/63695511-79dfa580-c836-11e9-80d9-a862625d1212.png">

**Comment by Maijin** [comment]
❤️
