### ISSUE TITLE
--without-pull shall be passed to capstone build

### ISSUE THREAD

**Issue by tezeb** [radare/radare2#6032]
It would make more sense if '--without-pull' would work also for capstone repository if it exists. It really helps with building offline(rather then manually removing .git directory).

**Comment by radare** [comment]
there’s no —without-pull neiterht in r2 or in capstone, you can do —with-syscapstone if you dont wanna checkout capstone everytime. you can also disable git in the env by changing the PATH or changing the GIT make var.

i will try to improve this but i dont have much time lately, so feel free to send a PR with your proposal

**Comment by tezeb** [comment]
I should have been more precise with my description.

When running ./sys/install.sh, you can pass "--without-pull" as an
argument. It skips pulling from git-repo.

I will take a look and try sending a PR.

**Comment by radare** [comment]
ah ok! yep a pullreq is very welcome :)

thanks
