### ISSUE TITLE
reverse-search is not cancelled easily

### ISSUE THREAD

**Issue by viraptor** [radare/radare2#6039]
If I try to look up old line using reverse-search, the lookup state is "stuck". For example:

```
type: <ctrl+r>w
get: (reverse-i-search (w)): wa mov al, 0xff
// realise I didn't want to do that:
type: <ctrl+c>
get: [0x00409d20]>
// ok, I'm back at the prompt, let's type normal command then
type: p
get: (reverse-i-search (p)): pd 10
// Aaaaarghh.....
```

There seems to be no way of cancelling the command search without pressing enter on an empty line, which sometimes has a meaning of it's own.

version 0.10.6

**Comment by radare** [comment]
This will be easily fixed when we implement the stack-friendly r_cons_break/end., there’s another issue for that. and this may fix many other non-cancellable commands

**Comment by alvarofe** [comment]
fixed in master. Test and confirm please
