### ISSUE TITLE
Repeated commands are not reordered/saved again

### ISSUE THREAD

**Issue by viraptor** [radare/radare2#6040]
When using some command often, I access it either from browsing up in the history, or from reverse search. But when I execute an existing command it's not saved again. This may result in the command falling out of the history, even though it's used very often.

For example:

```
some command i care about
other command
<browse up to the first one> + <enter>
<ctrl+r>care about + <enter>
<up> // still shows "other command", rather than the one executed last
many
other
commands
// at this point "some command I care about" is out of history, but "other command" isn't
```

version 0.10.6

**Comment by Maijin** [comment]
This may be expected - @radare can you confirm?

**Comment by radare** [comment]
I think this was fixed long time ago
