### ISSUE TITLE
rasm mistake on rbp based indexing

### ISSUE THREAD

**Issue by viraptor** [radare/radare2#6042]
Rasm will sometimes ignore that the requested operation cannot be translated and give an approximation instead. This can be completely wrong unfortunately. For example:
```
$ rasm2 -a x86 -b 64 'mov byte [rbp - 0x100], 2'
67c68500ffffff02
$ rasm2 -a x86 -b 64 -d 67c68500ffffff02
mov byte [ebp - 0x100], 2
```
But the difference between `rbp` and `ebp` is very important in this case.

---
Edit: my mistake, the original command is allowed, it's just not translated properly. The result should be c68500ffffff02.

version 0.10.6

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```

**Comment by viraptor** [comment]
Thanks!
Done in https://github.com/radare/radare2-regressions/pull/594

**Comment by Svenito** [comment]
I'm unable to reproduce this. Can you make sure you are running the latest r2 from git and try again

```
$ r2 -v
radare2 0.10.6 12791 @ linux-x86-64 git.0.10.6-167-g118e7de
commit: 118e7de2a52b363ca8a4628668c76cf0020536fd build: 2016-10-27
$ rasm2 -a x86 -b 64 'mov byte [rbp - 0x100], 2'
c68500ffffff02
$ rasm2 -a x86 -b 64 -d c68500ffffff02
mov byte [rbp - 0x100], 2
```
