### ISSUE TITLE
Input prompt can underflow

### ISSUE THREAD

**Issue by radare** [radare/radare2#6047]
looks like recently, something got broken into r_cons and the input underflows if pressing backspace right at the begining . if doing so, the whole cursor position and input text gets crappy until enter is pressed and a new prompt is shown

**Comment by alvarofe** [comment]
I observed the same but i thought was my setting with iterm or tmux. Will try to bisect to know where it comes

**Comment by radare** [comment]
yeah its quite anoying :(

**Comment by sferrini** [comment]
Yeah, is the same for me. I thought it was just me, but this issue confirms the opposite. Is someone working on it? If not, I can have a look 😉
