### ISSUE TITLE
pdc call improvement

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6066]
From @unixfreaxjp - 
- [x] pdc doesn't resolve call, here is current output:

`0x12450()                 ; sym.__GI_memset`

This would be first step:

`sym.__GI_memset()                 ; sym.__GI_memset; void *memset(void *s, int c, size_t n)`

And could be sharper with just:

```
memset(void *s, int c, size_t n);  ;  sym.__GI_memset()
```

+ @mrmacete work need #3531

---
- [x] Also second issue, after using pdc:
  `bl sym.rand`
  go to
  `bl 0x13c60`

`asm.filter` is setted to false and not reseted back

**Comment by Maijin** [comment]
@mrmacete maybe you want to take a look at that^

**Comment by Maijin** [comment]
Well this isn't arm only, same with x86

```
               0x10000450c ()            ; sym.imp.getenv; char *getenv(const char *name);
```

**Comment by unixfreaxjp** [comment]
> Well this isn't arm only, same with x86
all, mips, ppc.

**Comment by Maijin** [comment]
@unixfreaxjp I've already fixed one bug regarding pdc, you can already update ;)

**Comment by unixfreaxjp** [comment]
@Maijin 

> @unixfreaxjp I've already fixed one bug regarding pdc, you can already update ;)

just in time while checking new issue in #radare , hop in?
```asm
07:56PM <nterprais> Hi guys, I dealing with a mips binary, and I guess it has a debug protection because when I run radare it without debug (radare2 -AA
          bin/web) I can see dissasembled code, entry0 function, etc..., but loading with debuggin (radare2 -AA -d bin/web) all the code dump are
          ffffffff's. Also I had probed with -A and -AA options using today master@git. Could you recommend me something to read or a way to start
          understand what's happening ?
<unixfreaxjp> nterprais which version you use?
08:01PM <nterprais> i used yesterday git master release
<unixfreaxjp> nterprais gotta recompile mine first to check on mipsel
```

**Comment by Maijin** [comment]
Is he debugging it with a mips plateform etc. Ask him to open a bug in another thread please.
