### ISSUE TITLE
asm.relsub in arm

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6068]
asm.relsub should work in ARM:

Current output

```
         0x000081b0      0c009fe5       ldr r0, [0x000081c4]        ; [0x81c4:4]=0x81cc sym.main
         0x000081b4      0c309fe5       ldr r3, [0x000081c8]        ; [0x81c8:4]=0x8094 sym._init
```

What would be much better:

```
         0x000081b0      0c009fe5       ldr r0, sym.main
         0x000081b4      0c309fe5       ldr r3, sym._init
```

**Comment by Maijin** [comment]
Another example:

```
ldr r2, [0x00008754] ; [0x8754:4]=0x2489c obj.inchan
ldr r2, [0x00008758] ; [0x8758:4]=0x24840 obj.silenced
```

What would be much better:

```
ldr r2, [ obj.inchan]
ldr r2, [obj.silenced] 
```

**Comment by radare** [comment]
+1

**Comment by radare** [comment]
do we have a test for this?

**Comment by radare** [comment]
ping @Maijin

**Comment by radare** [comment]
Test case for this:
```
wx 0c009fe5
e asm.arch=arm
e asm.bits=32
f sym.callback=0x14
pd 1
```

current output:
```
            0x00000000      0c009fe5       Ldr  r0,  [0x00000014] 
```

should be:
```
            0x00000000      0c009fe5       Ldr  r0,  [sym.callback]
```

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/cdba55b5f7668d9de8208b624203f5738b714123

**Comment by radare** [comment]
this happens because its a chained relsub+varsub

**Comment by Maijin** [comment]
?

**Comment by Svenito** [comment]
Seems to also affect x86

    [0x00000000]> wx 488D470C  
    [0x00000000]> f sym.callback=0xc
    [0x00000000]> pd 1
            0x00000000      488d470c       lea rax, [rdi + 0xc]        ; 0xc ; sym.callback ; sym.callback

**Comment by radare** [comment]
Rdi cant be determined at static time. So nope this is not a bug for x86. The problem happens only when its a pc-relative thing

**Comment by Svenito** [comment]
The examples don't show the flags as flag substitution happens only with addresses >256

**Comment by Svenito** [comment]
Further noticed that in the above example:

    wx 0c009fe5
    e asm.arch=arm
    e asm.bits=32
    f sym.callback=0x14
    pd 1

it should use the address stored at 0x14 to resolve the flag and not the flag at 0x14, because the instruction is

    Ldr  r0,  [0x00000014]

not

    Ldr  r0,  0x00000014

**Comment by radare** [comment]
also, the instructions posted by @Maijin are actually dereferencing a pointer and we should resolve the pointer in there, not the address of the pointer.
