### ISSUE TITLE
Add anal.timeout to avoid analyzing for a long time

### ISSUE THREAD

**Issue by radare** [radare/radare2#6070]

**Comment by Maijin** [comment]
Duplicate of #649

**Comment by radare** [comment]
well its not duplicate, is just a way to have a single issue for each issue, and not have one with several checkboxes

**Comment by Maijin** [comment]
Well still duplicate, if you search timeout, you find #649 directly :P

**Comment by Maijin** [comment]
I can reopen and put in the issue

**Comment by radare** [comment]
This issue requires the push/pop rcons.break() thing

**Comment by Maijin** [comment]
#5986

**Comment by Maijin** [comment]
#5994

**Comment by radare** [comment]
rcons{push,pop} != rcons.break{push,pop}

**Comment by Maijin** [comment]
There is no issue for this

**Comment by radare** [comment]
I think we can implement this inside RCons. checking the time if a timeout is set in is_breaked()
