### ISSUE TITLE
Add command to list all comments inside a function

### ISSUE THREAD

**Issue by radare** [radare/radare2#6075]
Check if any of the comment fits inside the boundaries of any basic block of the selected (current) function

**Comment by Maijin** [comment]
See also https://github.com/radare/radare2/issues/2673

**Comment by unixfreaxjp** [comment]
CC isn't enough?

**Comment by Maijin** [comment]
CC display for all the session not for a given function

**Comment by unixfreaxjp** [comment]
This is crazy cool, I love you guys.
