### ISSUE TITLE
emscripten distribution

### ISSUE THREAD

**Issue by dominictarr** [radare/radare2#6078]
I am trying to parse a windows Portable Executable in javascript - because it needs to work in the browser. I started writing this by hand, before a friend put me on to radare2! I realized at the same time that the avaliable spec for PE is vague, which makes it _very difficult_ to implement, but radare works great!

I also noticed that there is an emscripten build, it would be great if the output of that could be published on npm, as that would allow using r2 without the difficulty of building it, would this be possible?

**Comment by radare** [comment]
Yep that is possible, but requires some more work to expose the js apis or at least the bare ones to create rcore and call core_cmd_str() to get r2pipe via emscripten.

I have already built web apps on top of parts of r2 compiled to js with emscripten. You can see the rax2 app in the firefox marketplace as example.

https://marketplace.firefox.com/app/rax2

Feel free to try sys/emscripten.sh and send pullreqs to fix the remaining bits to get this working.

Also i would recommend you to disable the dynamic plugin support which is not supported by emscripten and put the minimum number of plugins in the core.

I also though about doing this two years ago but i was busy with other stuff and put the task on hold. So if you are in the mood. Go on!

**Comment by dominictarr** [comment]
great, okay I am on it!

**Comment by radare** [comment]
I can put and maintain the npm packages when ready too

**Comment by Maijin** [comment]
For you, the best is to check r2pipe, and the commands: "i?" for example: "iV", "isj", ... 

![image](https://cloud.githubusercontent.com/assets/1408600/19838617/9aa9406c-9ed3-11e6-825a-26819e029333.png)

And the command pfj.

![image](https://cloud.githubusercontent.com/assets/1408600/19838625/bcb91d26-9ed3-11e6-9d82-cc7c4cb4d9fe.png)

**Comment by radare** [comment]
r2pipe requires a native r2 to talk with. He wants a full r2 in js

**Comment by dominictarr** [comment]
okay, I managed to get emscripten installed... got to here:

```
...
cleaning temporally files... done

Final report:
 - PREFIX = /usr
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 0
 - USE_CAPSTONE = 0
 - HAVE_FORK = 1
 - VERSION = 0.99.9-git
 - USE_LIB_ZIP = 0
 - USE_LIB_MAGIC = 0
 - DEBUGGER = 0
 - CC = emcc --ignore-dynamic-linking
 - USERCC = emscripten
 - USEROSTYPE = auto
 - LIBVERSION = 0.99.9-git
 - BUILD = x86_64-unknown-linux-gnu
 - HOST = emscripten
 - TARGET = x86_64-unknown-linux-gnu
Generating r_version.h file

OSTYPE: linux
ERROR: Unknown platform

make[1]: *** [../../libr/config.mk:209: main] Error 1
```

**Comment by radare** [comment]
are you using sys/emscripten?

**Comment by radare** [comment]
i dont have time for this, but fixing the build for the last version of emscriptn should be difficult, did you tried again?

**Comment by dominictarr** [comment]
Sorry, I couldn't get it to work. I also tried going back to the version where emscripten was announced and couldn't get that to work either... eventually, just made an http service that shelled out to rabin2

**Comment by cloudtracer** [comment]
I've been working on some pure javascript reversing tools myself and its a daunting task. I'd be very interested in knowing if someone can get the emscripten build working, I've tried myself with the same results.

**Comment by radare** [comment]
i’ll give a try before 1.2 :)

**Comment by radare** [comment]
we can use dockcross with emscripten target with the radare2-release. that will simplfy a lot the distribution of r2 in js. i have opened an issue there and @braincode will have a look soon

**Comment by radare** [comment]
ref https://github.com/radare/radare2-release/issues/4

**Comment by radare** [comment]
Done! :D 1.2 will come with an asmjs build (fully compiled master yesterday)
