### ISSUE TITLE
Fix @x: and make it work with pf

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6091]
* [ ] @x: is broken

![image](https://cloud.githubusercontent.com/assets/1408600/19910577/3df59bce-a08e-11e6-83b5-c561008941f0.png)

* [ ] and doesn't work with pf:

```
[0x00000000]> pf ix foo bar @x:1020304050607080901020
 foo : 0x00000000 = 0
 bar : 0x00000004 = 0x00000000
```

**Comment by Maijin** [comment]
Got tests:
-> https://github.com/radare/radare2-regressions/blob/master/t/cmd_disasm#L13
-> https://github.com/radare/radare2-regressions/blob/master/t/cmd_disasm#L21
-> https://github.com/radare/radare2-regressions/commit/8807d48c36066449b58867ebcda6c2b4282971d0

**Comment by MaskRay** [comment]
A correct recursive descent command parser should be implemented. Really

**Comment by XVilka** [comment]
Yes, but not right now. There are more higher priority bugs. E.g. fixing broken tests.

**Comment by radare** [comment]
@thestr4ng3r wanna take a look at this?
