### ISSUE TITLE
nbbs -> nodes / basicblocks

### ISSUE THREAD

**Issue by radare** [radare/radare2#6095]
Shuold we change the variables and json fields of `afij` from nbbs to nodes or so

**Comment by alvarofe** [comment]
I understand `nbbs` as number of basic blocks but change it as you've already commented with me on private might break some scripts and guis that depend on this. However, updating such scripts is not a pain, is just a matter of use sed. I would go instead to document r2pipe and the different json that r2 is able to give. Dunno why would be the best way to do it.

**Comment by radare** [comment]
so let's close it, nbbs lgtm too, but i nwas looking for some feedback that nobody gave in a month. thanks
