### ISSUE TITLE
Add call resolution in pdc/pds/pdfs/pdf...

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6096]
See @unixfreaxjp screenshot:

![image](https://cloud.githubusercontent.com/assets/1408600/19926348/5afd864e-a0f4-11e6-8d3a-7536be63d831.png)

This can now be done automatically via @oddcoder and @mrmacete work:

![image](https://cloud.githubusercontent.com/assets/1408600/19926362/6a7f8572-a0f4-11e6-96ac-77fc0bf412e4.png)

The info need to be more easy to get for the user (currently `aaa ; e asm.emu=true ; e asm.emuwrite=true ; aei ; aeim ; V` and asm.emu is too verbose) 

Should be somehow enabled after `aaaa` probably since `aaaa` already deals with emulation ? `aaa` is ok too since this doesn't seems to affect performance.

**Comment by unixfreaxjp** [comment]
@Maijin noted, with thanks. I am not sure it is doable, but if it does you are all gods.
the pic was an idea, maybe to sweet, but in this case is very good to simplify and make ppl understanding the control flow of Linux/UDPfkr

**Comment by oddcoder** [comment]
what exactly is that I can barely make sence of what is the target ? 
screanshot is full of stuff

**Comment by Maijin** [comment]
The idea is simple, just replace the pds output with the second output.

**Comment by oddcoder** [comment]
aha that can be done but still we have always the same problem which is memory layout should be driven by symbolic execusion which isn't there

**Comment by Maijin** [comment]
well for now it can work without symbolic for one path

**Comment by Maijin** [comment]
This has been done in pdc, closing here for now.
