### ISSUE TITLE
Ciclomatic complexity

### ISSUE THREAD

**Issue by radare** [radare/radare2#6098]
According to @joxeankoret we should use E-N+2 or do E-N+(P) ... where P is the sum of exit and entry nodes

**Comment by joxeankoret** [comment]
The theory about the calculation of cyclomatic complexity states that the formula is M = E - N + 2P, where P is the number of "connected components." In graph theory, "connected components" is "a subgraph in which any two vertices are connected to each other by paths." So, for most flow graphs, going back to software, the graph of a function will have a single entry point and a single exit point. However, it isn't always like that and a function might have various exit points. In that case, the calculation of ciclomatic complexity can be calculated as M = E - N + (EntryPoints + ExitPoints).

So, in radare2, the more conservative approach to calculate the cyclomatic complexity would be the last way I mention. However, the approach usually taken with software is to just not care and calculate it as M = E - N + 2, where P (or 2P) is replaced by a fixed 2.

Whatever for is implemented in radare2, would be fine for me.

**Comment by radare** [comment]
Please confirm

**Comment by joxeankoret** [comment]
Perfect for me.

**Comment by Maijin** [comment]
Just noticed:

![image](https://cloud.githubusercontent.com/assets/1408600/20056260/8d4b47ea-a4e5-11e6-80a6-54acbe2b7b1a.png)

vs

![image](https://cloud.githubusercontent.com/assets/1408600/20056262/93afdfc4-a4e5-11e6-99eb-95f28241d471.png)

**Comment by radare** [comment]
i dont see any difference
