### ISSUE TITLE
Support ar:// to load archive files like .lib or .a

### ISSUE THREAD

**Issue by radare** [radare/radare2#6104]

**Comment by Maijin** [comment]
"r_fs supports cpio and ar archives..."

**Comment by radare** [comment]
i see cpio but no ar..

**Comment by Maijin** [comment]
* http://www.ibm.com/support/knowledgecenter/ssw_aix_61/com.ibm.aix.files/ar_big.htm
* https://en.wikipedia.org/wiki/Ar_(Unix)

**Comment by radare** [comment]
No need to implement our own CPIO.. `shlr/grub/fs/cpio.c`

**Comment by Maijin** [comment]
This is very important for creating zignatures for various platform

**Comment by radare** [comment]
ENOTIME AGAIN
