### ISSUE TITLE
Add af*sql and other *sql commands 

### ISSUE THREAD

**Issue by radare** [radare/radare2#6111]
this will allow us to export all analysis information into an sql database like this:

`af*sql | sqlite functions.sqlite`

and then we can just type this to perform SQL queries on it:

`!sqlite functions.sqlite`

**Comment by alvarofe** [comment]
do we want it within core? i would go maybe with r2pipe

**Comment by radare** [comment]
An rcore plugin can handle any conmand that ends with *sql and do whatever.. yep it can be done that way.. but as long as we have json in core and other output formats.. but sql is probably too much for core

**Comment by Maijin** [comment]
@jvoisin ^

**Comment by Susanne588586** [comment]
@radare this should go into an extra repo, it is not json so it is practical for people that hate javascript

**Comment by jvoisin** [comment]
I think that json is enough.

The issue with SQL is that it's structured, and odds are that we won't manage to make schema that will make every user happy, because everyone will have different needs.

**Comment by radare** [comment]
ok, so if nobody feels the need for that, let's close it
