### ISSUE TITLE
buildsystem: hurd is detected as gnulinux

### ISSUE THREAD

**Issue by sre** [radare/radare2#6115]
Hi,

FWIW hurd is detected as gnulinux and builds fails for linux_coredump.c, since asm/ptrace.h does not exist on hurd (note, that I do supply --disable-debugger for hurd, but that does not help). While there is probably no r2 user on hurd it's usually a nice testcase for cornercases. This is obviously low prio.

Here is Debian's hurd buildlog for 0.10.6:
https://buildd.debian.org/status/fetch.php?pkg=radare2&arch=hurd-i386&ver=0.10.6%2Bdfsg-1&stamp=1474962363

This part detects gnuhurd as gnulinux. I wonder if it should specify gnuhurd instead.
```
if [ "$HOST_OS" = "gnu" ]; then
USEROSTYPE="gnulinux"
HAVE_LIB_DL="1"
DL_LIBS="-ldl"
```

-- Sebastian

**Comment by radare** [comment]
can you cook a patch? disabling the coredumping on __HURD__  and try again?

acr uses this assumption because most of the things in linux are the same in hurd, and that way it was simpler to port.

**Comment by sre** [comment]
Yes, but probably not before next week. I guess coredump stuff should also be inside of "#ifdef DEBUGGER".

**Comment by radare** [comment]
So you can build for hurd by passing --without-debugger to the configure?

**Comment by sre** [comment]
I currently do pass --without-debugger for all non-linux platforms and all cpus except arm & x86 for the Debian build. It tries to build some of the debugging stuff anyways. It only results in build failures for the hurd platform, though.

**Comment by radare** [comment]
Debugger should be ok for ppc and mips too

**Comment by radare** [comment]
So withoutdebuggee doesnt skips the build of the coredump?

**Comment by sre** [comment]
> Debugger should be ok for ppc and mips too

ok, I will enable support for ppc and mips with the next release in Debian

> So without-debugger doesn't skips the build of the coredump?

Yes, coredump is also build if "DEBUGGER = 0".

**Comment by radare** [comment]
Without debugger should disable that part. Can you send a pr to fix this? I will try to find some time but imho its important to have it fixed

**Comment by radare** [comment]
should be fixed in ab289175688066b8fa67163abbea982781d8a7a6 please confirm

**Comment by sre** [comment]
I can confirm, that hurd compiles fine with 1.0 with --without-debugger.

**Comment by radare** [comment]
Glad to hear that! :D
