### ISSUE TITLE
dex checksum (adler32) and hash (sha1) computation seems not correct

### ISSUE THREAD

**Issue by klistox** [radare/radare2#6127]
I have modified a classes.dex file with r2 and when attempted to recompute and write adler32 and sha1 file header, I always get:
<pre>
$ r2 -w classes.dex 
# adler32 checksum doesn't match. Type this to fix it:
wx `#sha1 $s-32 @32` @12 ; wx `#adler32 $s-12 @12` @8
</pre>

With a correct classes.dex it is possible to verify the deviation comparing package sha1 hash and the one computed with r2 command.
<pre>
$ r2  classes.dex 
 -- Jingle sploits, jingle sploits, ropchain all the way.
[0x00000010]> s 0xc
[0x0000000c]> px 20
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x0000000c  027f 55a5 2819 3eac f67c a054 3165 9ca5  ..U.(.>..|.T1e..
0x0000001c  45b6 46de                                E.F.
[0x0000000c]> ph sha1 $s-32 @32
69287f6ddbb9e8e63298ae07cb2f6b4d221418be
</pre>

Using rahash2 we can obtain sha1 hash of the same package, note that end offset (-t) must  be file length -1!!!
<pre>
$ rahash2 -a sha1 -f 32 -t 14983 classes.dex
classes.dex: 0x00000020-0x00003a87 sha1: 027f55a528193eacf67ca05431659ca545b646de
</pre>

Since rahash2 works with inclusive offsets, I've attempted to compute hash subtracting one to the length:
<pre>
[0x0000000c]> ph sha1 $s-33 @33
f58dbfa6e7cc3e12dd05363273ad8986a3600f33
</pre>

If there is any mistake in my tests or executed commands, please tell me and apologize for making you waste time.

Finally, in file libr/bin/p/bin_dex.c:355 provided help message to solve adler32 and sha1 deviation is deprecated and must be modified with:
<pre>
wx `ph sha1 $s-32 @32` @12 ; wx `ph adler32 $s-12 @12` @8
</pre>

**Comment by radare** [comment]
imho we should fix r2 to make 32 mean 32 in length, which is in fact 33 , because the change in rahash2 that was considering inclusive offsets broke this behaviour. and we should differentiate if the boundaries are inclusive or not depending on if we are talking about [from-to] or [from+len)
