### ISSUE TITLE
Bug in rax2 -s

### ISSUE THREAD

**Issue by jttoivon** [radare/radare2#6128]
The hexstr to raw conversion seems to have some problem when the hexadecimal
consists of only one char. For example
rax2 -s 0xa | hd
doesn't print anything, but when I prepend zero:
rax2 -s 0x0a | hd
00000000  0a                                                |.|
00000001
It works as expected.

I can of course add the zero in front of the number, but this comes a
problem when I try combine tools together, in which radare is supposed to be good at.
For example:
rax2 65 66 67 | rax2 -s
prints ABC as expected, but
rax2 65 66 67 10 | rax2 -s
doesn't print anything.

I'm using the following version:
rax2 0.10.6 9999999 @ linux-x86-64 git.0.10.6
commit: HEAD build: 2016-11-04

Thanks!

**Comment by radare** [comment]
Use 0a because it expects an hexpair. Not a number

**Comment by radare** [comment]
Also spaces between hexpaies have another meaning so remove them if u want it to work

**Comment by jttoivon** [comment]
> Also spaces between hexpaies have another meaning so remove them if u want it to work
Ok, now I'm really confused.  The following commands seem to give the same result:
rax2 -s 4142430a
rax2 -s 41 42 43 0a
What is the different meaning when spaces are or aren't used? And where is this documented?
I couldn't find anything on the rax2 man page. It only mentioned the form with spaces.

Since hexpairs were mentioned, I tried the -n option which according to man page does
"Show hexpairs from integer value".  The command 
rax2 -n 65 66 67 10 | rax2 -s
seems to work since it prints ABC and new line on screen. But in reality it puts each
byte in 32-bit word padded with zeros. This works only superficially, since
the zeros aren't shown on screen. And by the way: the rax2 -h command tells that
usage is "-n    binary number". Is this really correct?

So, is there any way of converting a sequence of decimal numbers, in range 0-255, to
raw bytes?

This is probably a trivial thing, but I don't seem to get it working.

**Comment by radare** [comment]
Different arguments are processed separately. you must think in rax2 as bc .. so thats the expected behaviour because you can pipe operations or number conversions to stdin and grab the results in different lines in the output. you should remove the space between the chars. if you want to read a large list of hexpairs with spaces you can just read from stdin with rax2 -s -

use |hexdupm -C to see the *real* outpiut:

```
$ rax2 -n 65 66 67 10 | rax2 -s|hexdump -C
00000000  41 00 00 00 42 00 00 00  43 00 00 00 0a 00 00 00  |A...B...C.......|
00000010

```
