### ISSUE TITLE
File format: objcopy "binary" (raw memory dump)

### ISSUE THREAD

**Issue by ishitatsuyuki** [radare/radare2#6131]
This is a format created by objcopy, and is raw binary:

Command: `objcopy -O binary src dest`

rabin2:
```
havecode false
pic      false
canary   false
nx       false
crypto   false
va       false
bits     64
minopsz  1
maxopsz  16
pcalign  0
endian   little
stripped false
static   true
linenum  false
lsyms    false
relocs   false
binsz    2221000
```

r2 ie: `0 entrypoint`

No function at 0x0, but pd outputs valid opcode.

**Comment by Maijin** [comment]
Please add the binary

**Comment by radare** [comment]
Its a raw binary what else do u expect?

**Comment by ishitatsuyuki** [comment]
You can use create an example from your favorite ELF using the command provided.

**Comment by radare** [comment]
wontfix

**Comment by Maijin** [comment]
Next time you submit, please provide binary because we don't know what version, platform, arch, OS, etc you are using.

**Comment by XVilka** [comment]
@Maijin: in this case this would be pointless - it's raw binary after all.

**Comment by Maijin** [comment]
I know, i speak for next time
