### ISSUE TITLE
`px -x` doesn't clean up properly after seeking to its negative offset

### ISSUE THREAD

**Issue by dequis** [radare/radare2#6133]
Found this while trying to understand why px worked but p8 didn't (#2401)

```
[0x00000000]> wx 0102030405060708
[0x00000000]> s 4
[0x00000004]> p8 -2
0506
[0x00000004]> px -2
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000002  0304                                     ..
```

So far so good, px works and p8 doesn't, as expected from the other ticket. Now see this:

```
[0x00000004]> p8 -2
0304
[0x00000004]> px -2
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000002  0304                                     ..
[0x00000004]> px 2
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000004  0506                                     ..
[0x00000004]> p8 2
0506
[0x00000004]> p8 -2
0506
```

Despite calling `r_core_seek (core, off, SEEK_SET);` before and after the cmd_print switch with correct-looking offsets, it affects the output of p8 persistently. Also, when len is positive r_core_seek isn't called at all, and it still has this effect on p8. 

I think that what really is making px with negative len "work" here is the call to `r_core_block_size()`, which reallocates/wipes core->block and rereads with `r_core_block_read()` under the offset that was last seeked.

When it's called again to clean up the block size change, it still rereads a block under the negative offset so what's in core->block is wrong.

**Comment by alvarofe** [comment]
fixed, isn't?
