### ISSUE TITLE
Fix all warnings from linux and review covs/clang-analyzer

### ISSUE THREAD

**Issue by radare** [radare/radare2#6146]

**Comment by radare** [comment]
Linux warnings: [a.txt](https://github.com/radare/radare2/files/574479/a.txt)

**Comment by Maijin** [comment]
http://ci.rada.re/job/radare2-scan-build/1108/clangScanBuildBugs/

**Comment by radare** [comment]
cant we sort by column or filter or something ?

**Comment by alvarofe** [comment]
I fixed linux warning.

**Comment by radare** [comment]
Done, still some more to fix, but it's ok to wait for next release
