### ISSUE TITLE
zignatures not working for arm

### ISSUE THREAD

**Issue by twiddle** [radare/radare2#6147]
With a 'hello world' binary produced by x86 gcc, 'zg' works as expected.

The same source compiled for arm (e.g. using gcc on raspberry pi) reports 'Length is 0' errors for every symbol:

$ r2 -A -aarm -b32 hello.elf -c "zg hello hello.sig"
...
Omitting sym.main zignature is too small. Length is 0. Check cfg.minzlen.
...

Output from 'afl' seems correct, and 'zG' works as expected for the same binary.

**Comment by radare** [comment]
there’s no point in using -a and -b because ELF should be already specifying this.

there’s an issue about the zero length zignatures already. @zlowram is working on that but this will not appear until the next 1.1 release

**Comment by Maijin** [comment]
#5688

**Comment by twiddle** [comment]
If I'm understanding this correctly, #5688 seems like a separate issue.

Zignature generation seems to rely on RAnalOp structure member 'nopcode' containing the length of the instruction minus the argument, but it is always 0 on arm.

Nothing in libr/anal/p/anal_arm_cs.c seems to set it, whereas it is set in libr/anal/p/anal_x86_cs.c.

Perhaps I don't know enough about arm yet...

**Comment by radare** [comment]
What if you set this value to 1?

**Comment by twiddle** [comment]
If I set nopcode to 1, it creates zignatures:
...
zb sym.main ........04......f6......03..............
...
They are a little sparse when compared with x86, but that does appear to be the problem..
