### ISSUE TITLE
Wrong output of izzj + function detection on Win native binary not working

### ISSUE THREAD

**Issue by pinkflawd** [radare/radare2#6164]
For attached sample, there seem to be at least two problems:

- [x] izzj doesn't show izz strings on the sample
- [x] only one function is detected after aaa on the sample

Password for attached archive is infected

[HIDRV.zip](https://github.com/radare/radare2/files/580728/HIDRV.zip)

**Comment by alvarofe** [comment]
izzj issue should be fixed on master now

http://asciinema.org/a/ey3fhn6nlxpnsxcdmae0dvhwe

about anal seek to that jump and `aaa` again. We aware about anal engine issues

**Comment by pinkflawd** [comment]
Cool, yeap, strings are back with izzj, many thanks!!

**Comment by radare** [comment]
e anal.hasnext=true

**Comment by Maijin** [comment]
Great hasnext, finds 1 more function 👎

**Comment by radare** [comment]
i dont see more than 6 functions in this binary and most of them are full of crap. which results are you expecting here? this seems to me like manual work rather than something that can be automated better, there's lot of trash code

**Comment by Maijin** [comment]
http://pastebin.com/vtY7QLpA

**Comment by Maijin** [comment]
From IDAPro detection and those aren't trash detection

**Comment by radare** [comment]
i have a very stupid idea that it should work, hold my beer

**Comment by radare** [comment]
ahahaha my solution works quite well, but also… everything works fine if you just seek to the section..text before running any analysis. because the entrypoint is localted inside the INIT section. so just seeking to the entrypoint fixes the problem

**Comment by radare** [comment]
Try `.aaT @ section..text`, but anyway we should make all `aa*` commands to walk all executable sections instead of just the current one. wasnt this suposed to work like search.in? maybe we need an `anal.in`

**Comment by pinkflawd** [comment]
The sample comes from this report, http://www.sekoia.fr/blog/wp-content/uploads/2016/10/Rootkit-analysis-Use-case-on-HIDEDRV-v1.6.pdf and should be a perfectly fine binary. Attaching the graph my parser gets out of that thing. Might be an image I plotted before updating, so thats kind of what it should look like. 
What I dont know is how the aaa;afl looked like before the update. 
The options I use in the parser are:
R2PY.cmd("e anal.jmptbl = true")
R2PY.cmd("e anal.hasnext = true")
R2PY.cmd("aaa")
R2PY.cmd("afr")
R2PY.cmd("afr @@ sym*")


![hidrv](https://cloud.githubusercontent.com/assets/5487036/20265532/de858ae4-aa71-11e6-941b-4ca1453906d3.png)

**Comment by radare** [comment]
first run s section..text .. that may fix the prblem of that bin

**Comment by pinkflawd** [comment]
can try that, but honestly I do have an eerie feeling somethings awkward with Windows drivers in general. Will run more tests on this and update the thread when I tried other, might even have benign drivers for tests and such ^^

**Comment by radare** [comment]
Yep its just a temporal solution i will make a pr this week to test the fix i have in mind

**Comment by pinkflawd** [comment]
To be fair, I have close to 0 idea what it is that doesn't work properly, what I see is more error messages from my parser on drivers, as compared to userland bins.
Anyway, no pressure :)

**Comment by radare** [comment]
NO PRESSURE NO PRESSURE?!?!? WHAT DO YOU MEAN WITH THIS!??!1’11

**Comment by Maijin** [comment]
This is fixed.
