### ISSUE TITLE
Somehow truncating visual mode

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#6166]
Vs% will only print n lines. going back to V will also then only print n lines.

**Comment by radare** [comment]
Yes this is documented. This key toggles the blocksize honoring in visual

**Comment by radare** [comment]
Do u guise think this should be reset every time u enter in visual?

**Comment by Susanne588586** [comment]
hm, I fink it doesn't make sense to limit

**Comment by radare** [comment]
makes sense when you are working with bizarre io targets that only permit reads in some specific alignments and sizes and the io plugin doesnt honors this info, also useful when the backend is slow, or when you want to view only blocks of N bytes. So imho its useful

**Comment by radare** [comment]
I would like to reopen the discussion of this or close the issue if it'so k the way it is already.

I think that this is useful, but maybe not something to set in a key in visual mode, but maybe do it in a config var. and use V% for something else

**Comment by radare** [comment]
imho % is useful and i use it already, without more feedback or ideas im not gonna change that behaviour

**Comment by radare** [comment]
thats expected behaviour
