### ISSUE TITLE
Add `as` subcommand to dump syscall info in .asm or .h

### ISSUE THREAD

**Issue by radare** [radare/radare2#6171]
useful for later #include and use in your rasm2 snippets

**Comment by Maijin** [comment]
Currently there are some bugs around asl:

![image](https://cloud.githubusercontent.com/assets/1408600/20326692/202b3782-ab8a-11e6-8094-2eef382d2353.png)

**Comment by Maijin** [comment]
The idea is to get something like:

```
         write(1,."hi!\n", 4);
         exit(0);
```

Right ?

**Comment by radare** [comment]
Yes

**Comment by Maijin** [comment]
check the bug in the first comment*

**Comment by radare** [comment]
ah nope, sorry  the idea would be to print the syscalls like this:
```
#define SYS_open 3
#define SYS_close 4
...
```

or

```
.equ SYS_open, 3
.equ SYS_close, 4
...
```
