### ISSUE TITLE
agcj doesnt exist

### ISSUE THREAD

**Issue by radare** [radare/radare2#6175]
Someone tried to run that on the cloud, and i think it should exist

**Comment by Maijin** [comment]
agc is for graphviz,
agj and agCj already exist what would be goal for `agcj`?

**Comment by radare** [comment]
If it exists then make an alias on it

**Comment by Maijin** [comment]
? Won't make sense agc is for graphviz already

**Comment by radare** [comment]
G is for graph and c is for calls, theres nothing related to graphviz here.

So i dont see why agcj looks wrong for u
