### ISSUE TITLE
mis-assembly to thumb code

### ISSUE THREAD

**Issue by ukleinek** [radare/radare2#6181]
Trying to assemble to arm thumb gives wrong results:

    $ rasm2 -a arm -b 16 "add sp, #0x10"
    103d
    $ rasm2 -a arm -b 16 -d 103d
    subs r5, 0x10

In this case the assembler is right. Also the assembler isn't impressed by adding -e, while the assembler behaves as expected:

    $ rasm2 -a arm -b 16 -e "add sp, #0x10"
    103d
    $ rasm2 -a arm -b 16 -d -e 103d
    asrs r5, r7, 0x20

When using ARM (i.e.  `-a arm -b 32`) everything looks fine.

FTR, I already reported that to the [Debian bug tracker](https://bugs.debian.org/844007).

This happens with 0.10.6, 1.0.2 (from Debian) and also with radare.git (tested commit d1f5184f5404)

**Comment by radare** [comment]
If you miss instructions Implement those instructions or use keystone (r2pm -i keystone) and then use -a arm.ks

The problem here is that rasm2 understands # as a comment. So just remove it

Thanks

**Comment by ukleinek** [comment]
The statement about # being interpreted as a comment is wrong:

    $ rasm2 -a arm -e -b 16 "sub sp, #"
    0035
    $ rasm2 -a arm -e -b 16 "sub sp, #0x10"
    1035
    $ rasm2 -a arm -e -b 16 "sub sp, #0x20"
    2035

**Comment by radare** [comment]
did you tried with -a arm.ks?
