### ISSUE TITLE
Mark which functions are dangerous in libr/anal/d/types

### ISSUE THREAD

**Issue by radare** [radare/radare2#6186]
like strcpy for possible overflow or strlen for possible null deref. this info can be later used as a hint for automatic vuln finding

**Comment by radare** [comment]
The issue implies adding new commands to enumerate them, also to see which functions uses them by checking the xrefs

**Comment by radare** [comment]
moving another easy issue assigned to @oddcoder again to 1.4

**Comment by alvarofe** [comment]
This is indeed very useful for reports and such. I will look into this but don't know if I will manage to fix it in time for this release etoomuch issues

**Comment by Maijin** [comment]
Like for other db, once you have an initial stub I can complete the Database

dangerous=1

**Comment by radare** [comment]
We have more important issues than this one. Which can wait for 1.4, i would prefer to focus on bug fixing and stability during the weekend

**Comment by Maijin** [comment]
Agree

**Comment by radare** [comment]
isnt cutter doing that already? maybe we should put that logic in r2 cc @xarkes

**Comment by radare** [comment]
Microsoft did the list of dangerous functions for us https://msdn.microsoft.com/en-us/library/bb288454.aspx

**Comment by radare** [comment]
See `libr/flag/d ; make ; cat ft.r2` we need to find a way to make flags use those files to 'tag' them. For now this can be done by hand. but we need to improve

**Comment by radare** [comment]
i have already implemented this with the flag tags. so closing
