### ISSUE TITLE
Please show progress during analyze.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#6203]
It would be so useful to have a progress bar during analyze.

If it is hard to estimate the time it will take, just make some motion in the console.

Maybe a game/animation? ;-)

We should not make the console to freeze.

**Comment by radare** [comment]
it is not possible to estimate the time required to analize a binary. only the % of analized bytes

the console will not freeze when the ^C is properly implemented. also having scrollbars and such slowdowns the realwork. so im not really a big fan of having this stuff because it ends up slugging the work that matters

**Comment by Maijin** [comment]
Can we close this then ?

**Comment by MariasStory** [comment]
Hi,
![image](https://cloud.githubusercontent.com/assets/6576335/20386163/a9554c24-acba-11e6-8f59-e357bbc3f692.png)

**Comment by radare** [comment]
r2 is always working unless it shows the prompt. you can use top in another terminal if you want to confirm that is not stuck in a sleep :P  but usually if something takes a lot of time it means that it must be improved. currently the analysis can be done much faster.

**Comment by radare** [comment]
and yes, everything will be cancellable soon :P

**Comment by Maijin** [comment]
@oddcoder this is afta ^ Can't be stopped with ^C

**Comment by radare** [comment]
This will be fixed with the stack-based rconsbreak/end @alvarofe

**Comment by oddcoder** [comment]
I am not sure how to make ^c work ? should it work by default ?

**Comment by alvarofe** [comment]
i am doing it

**Comment by alvarofe** [comment]
afta now honor ^c. If anyone finds a place where it doesn't just open other issue
