### ISSUE TITLE
Implement pir like pdr but with pi

### ISSUE THREAD

**Issue by radare** [radare/radare2#6206]

**Comment by leberus** [comment]
Hi, I'd like to take this one. I just have a question:

| pdr        recursive disassemble across the function graph

this stands for the kind of algorithm which is being used to disassemble the binary? ( [](http://resources.infosecinstitute.com/linear-sweep-vs-recursive-disassembling-algorithm/) )

thanks

**Comment by radare** [comment]
yes. pir should use the same code as pdr, but showing the output like `pi` does. instead of the current one which is based on `pd`

**Comment by leberus** [comment]
I got it. I take it ;)

Thanks

El dia 29/11/2016 18:34, "radare" <notifications@github.com> va escriure:

> yes. pir should use the same code as pdr, but showing the output like `pi`
> does. instead of the current one which is based on `pd`

**Comment by leberus** [comment]
I've done a [PR](https://github.com/radare/radare2/pull/6276)

**Comment by radare** [comment]
Yep ive seen it. Will review asap

**Comment by leberus** [comment]
Yep, there is something wrong with it? (just asking, i don't wanna add pressure or whatever ;) )
