### ISSUE TITLE
SIGSEGV using r2

### ISSUE THREAD

**Issue by wehaveacat** [radare/radare2#6210]
Hello

I've tried to use r2 on [file](http://csapp.cs.cmu.edu/3e/bomb.tar)  (link from Carnegie Mellon University)
and got this:

```
andrew@NB:~/test$  r2 -A ./bomb
Segmentation fault (core dumped)
andrew@NB:~/test$ r2 -v
radare2 1.0.2 13002 @ linux-x86-64 git.1.0.2-58-gf495899
commit: f4958992580cd1ec40370a1f26cb80e79fa6fa69 build: 2016-11-16
andrew@NB:~/test$ gdb r2
(gdb) r -A ./bomb
Starting program: /usr/local/bin/r2 -A ./bomb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
```

**Comment by radare** [comment]
Yeah thats a regression introduced yesterday i was about to fix it today before finishing the coffee.

**Comment by wehaveacat** [comment]
I've just updated my local repo and made
sudo make uninstall
sudo make purge
sudo sys/install.sh 
As a result - the problem still exists

**Comment by radare** [comment]
sys/install already uninstalls, pulls and builds, no need to run anything else.

im trying with asan and valgrind and i cant reproduce the crash anymore :? do you have r2 installed in more than one path?

**Comment by wehaveacat** [comment]
After update, I tried traditional way:
./configure
make
make install 
Now it works. Thanks!
