### ISSUE TITLE
asl is broken

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6215]
For example x64 binary:

`asl` display wtf values 
![image](https://cloud.githubusercontent.com/assets/1408600/20391571/46010004-acd4-11e6-9060-0e0be22eb9d4.png)

And `asl 1` for example should display write etc.

**Comment by radare** [comment]
no, this is fine, this is how syscalls are defined in OSX. see the hex value. there’s a 0x20 on top that points to the 64bit syscalls.

**Comment by Maijin** [comment]
okok pardon my linuxism
