### ISSUE TITLE
"r_debug_reg: error writing registers" message on first continue to breakpoint of debugging session

### ISSUE THREAD

**Issue by pgrohe** [radare/radare2#6218]
Whenever I do the my first continue ("dc")to a breakpoint in a debugging session I get the following error message:

r_debug_reg: error writing registers 0 to 37906
cannot set registers!

The 2nd value of the first line is not always the same over different runs.

Once I hit that first breakpoint, if I set another and continue to that one I don't get the message again.

If I start a debugging session, do not set any breakpoint and continue execution the error does not appear.

I've been experiencing this for a few versions.  Did an uninstall & purge this evening and re-cloned from github to make sure it's not related to my version being old.

This is occurring in a 64 bit Ubuntu Gnome 16.04 VM.

Version Details:
```
testing@ubuntu:~/ringzer0/reverse-engineering/1$ r2 -V
1.0.2-81-g8c1a3dc  r2
1.0.2-81-g8c1a3dc  r_anal
1.0.2-81-g8c1a3dc  r_lib
1.0.2-81-g8c1a3dc  r_egg
1.0.2-81-g8c1a3dc  r_asm
1.0.2-81-g8c1a3dc  r_bin
1.0.2-81-g8c1a3dc  r_cons
1.0.2-81-g8c1a3dc  r_flag
1.0.2-81-g8c1a3dc  r_core
1.0.2-81-g8c1a3dc  r_crypto
1.0.2-81-g8c1a3dc  r_bp
1.0.2-81-g8c1a3dc  r_debug
1.0.2-81-g8c1a3dc  r_hash
1.0.2-81-g8c1a3dc  r_fs
1.0.2-81-g8c1a3dc  r_io
1.0.2-81-g8c1a3dc  r_magic
1.0.2-81-g8c1a3dc  r_parse
1.0.2-81-g8c1a3dc  r_reg
1.0.2-81-g8c1a3dc  r_sign
1.0.2-81-g8c1a3dc  r_search
1.0.2-81-g8c1a3dc  r_syscall
1.0.2-81-g8c1a3dc  r_util
testing@ubuntu:~/ringzer0/reverse-engineering/1$ r2 -v
radare2 1.0.2 13025 @ linux-x86-64 git.1.0.2-81-g8c1a3dc
commit: 8c1a3dca93d70e77253699aa2f0568accd55a027 build: 2016-11-17
```

Sample Output:
```
testing@ubuntu:~$ r2 -d /bin/ls
Process with PID 37906 started...
= attach 37906 37906
bin.baddr 0x00400000
Assuming filepath /bin/ls
asm.bits 64
 -- There's a branch for that.
[0x7f0e91229cc0]> db entry0 
[0x7f0e91229cc0]> dc
r_debug_reg: error writing registers 0 to 37906
cannot set registers!
= attach 37906 1
[0x004049a0]> 
```

**Comment by skuater** [comment]
fixed
