### ISSUE TITLE
Strange characters clicking with mouse in graph mode.

### ISSUE THREAD

**Issue by sferrini** [radare/radare2#6220]
I noticed that in graph mode if you click with the mouse when you have the prompt for highlighting, you get strange characters printed out:

![click](https://cloud.githubusercontent.com/assets/3370782/20437654/13eea292-adb5-11e6-9888-c228858ecdfd.gif)

**Comment by AlexKornitzer** [comment]
Any thoughts on what is causing this? It happens in all aspects of Visual mode and causes erratic behaviour. Mostly an issue when clicking to focus the window.

**Comment by radare** [comment]
e scr.wheel=0

**Comment by AlexKornitzer** [comment]
That fixes it, so is it a bug or intended functionality?

**Comment by radare** [comment]
It depends on the terminal you use. Can u share some details on this so i can test and fix?

**Comment by AlexKornitzer** [comment]
Info: Arch Linux, `alacritty` with and without tmux. Also does it with `xfce4-terminal`.

**Comment by XVilka** [comment]
@cyanpencil can you please check this one?

**Comment by sferrini** [comment]
@XVilka just tested this, on macOS seems it doesn't print characters anymore, but it does other strange behaviour like changing the colour palette.

**Comment by cyanpencil** [comment]
The change of the colour palette means that it's sending the `R` character in some way...

However I'm unable to reproduce it on my system. I'm on arch linux and tested both in urxvt and xterm. Clicking or selecting with the mouse does not print any character in visual mode, even with the command menu `:` open.

**Comment by sferrini** [comment]
@cyanpencil have you tried also in "highlighting mode" `/`?

**Comment by cyanpencil** [comment]
Ok I just tried and you are right, I was being naive, in highlight mode it prints garbage. It prints garbage also while in offset mode `o`, while setting cmg.gprompt `|` and while adding a comment `;`.

I'll see if I can fix it
