### ISSUE TITLE
xtensa esp8266 branch notation issue

### ISSUE THREAD

**Issue by sheinz** [radare/radare2#6227]
Hi,

Thanks for the great project!

I encounter a strange issue. The branch arrow points to the wrong address.
In function `sym.ieee80211_deliver_data` instruction `beqz.n a3, 0x08000083` should point to the address 0x08000083 but instead it points to 0x08000043.

[![asciicast](https://asciinema.org/a/en1ykonfwwga56a2ghju1rhif.png)](https://asciinema.org/a/en1ykonfwwga56a2ghju1rhif)[test_file.tar.gz](https://github.com/radare/radare2/files/601692/test_file.tar.gz)

I'm quite new to the radare2. I'm also having problem radare2 resolving string literals and function calls in object files. I might miss some configuration (I tried `asm.emu`, `asm.emustr`, `asm.cmtrefs`) I use it for esp8266 SDK reverse engineering.

Thanks!

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by sheinz** [comment]
Yes, I use it from git:
```
r2 -v
radare2 1.0.2 13035 @ darwin-x86-64 git.1.0.2-91-gc959aa0
commit: c959aa0fa086d192523b0f42cd3f22794f69fe09 build: 2016-11-19
```

**Comment by Maijin** [comment]
Can you give output of "ao @ 0x08000053"

**Comment by sheinz** [comment]
>Can you give output of "ao @ 0x08000053"

```
[0x08000040]> ao @ 0x08000053
address: 0x8000053
opcode: beqz.n a3, 0x08000083
prefix: 0
id: 0
bytes: acc3
val: 0x00000000
ptr: 0x00000000
refptr: 0
size: 2
type: cjmp
esil: 0,a3,==,?{,0x2d,pc,+=,}
jump: 0x08000043
fail: 0x08000055
stack: null
cond: al
family: cpu
```

**Comment by radare** [comment]
If disasm is good the esil amd jump field of ranalop is wrongly computed. You can try to fix it by changing this in libr/anal/p/anal_xtensa.c and send a pr. I dont have time, docs or sample files to test this now, but should be easy to fix with those elements.

Thanks for reporting
