### ISSUE TITLE
Registers values in visual mode have two 0x prefixes

### ISSUE THREAD

**Issue by sferrini** [radare/radare2#6228]
In visual mode, registers have two `0x` prefixes:

![screen shot 2016-11-19 at 21 51 58](https://cloud.githubusercontent.com/assets/3370782/20458366/c382859a-aea3-11e6-9a0b-781247c9176d.png)

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/ee081098351a166065aef287308c9ead975448a4
