### ISSUE TITLE
[Multicolumn] [MIPS32] Columns are overlapped

### ISSUE THREAD

**Issue by Cka3o4Huk** [radare/radare2#6232]
Hi,

Version: radare2 1.0.2 & HEAD (commit - c4ee05b)
OS: FreeBSD 12-CURRENT
Target file: MIPS32 binary
Test case:
 1) open file
`r2 -a mips -b 32 -e cfg.bigendian=true bootloader.dump`
 2) Vppppp until multicolumn

Expected results: 2-3 columns without overlapping
Actual results: 4 columns with overlapping 

![screenshot from 2016-11-20 17-42-33](https://cloud.githubusercontent.com/assets/47472/20463637/290f305e-af51-11e6-9945-fb990957831e.png)

Github doesn't allow me to upload archive with bootloader (bootloader.zip), so it's located here: http://cloud.unclebear.ru/bootloader.zip

**Comment by radare** [comment]
Use [] keys to resize the column or disable asm.bytes, etc

**Comment by Cka3o4Huk** [comment]
[] is nice. Is it possible to avoid overlapping by default? ( [] is unknown for newbies ;) )

**Comment by radare** [comment]
newbyes can just press ? and get the help message that explains this :P

**Comment by radare** [comment]
Try again with the " key, which toggles the column mode for disasm, hexdump, debugger, ...

**Comment by radare** [comment]
ping

**Comment by Cka3o4Huk** [comment]
Hi, " key doesn't change anything. BTW, i'm using [] to change size, so it's enough. 
On other hand, I'm still using single column view because it visualize data, but multicolumn doesn't. I suppose it should be discussed under another issue (data is displayed as code and columns have same lines). 

![screenshot from 2016-11-24 13-38-02](https://cloud.githubusercontent.com/assets/47472/20595525/a744a8aa-b253-11e6-9d38-39132eef9bef.png)
![screenshot from 2016-11-24 13-36-55](https://cloud.githubusercontent.com/assets/47472/20595540/b8d89f4a-b253-11e6-8c50-0a24276ad5c4.png)

**Comment by radare** [comment]
yep this is a different issue, probably introduced by aaaaaaa ?

this is metadata defined by analysis

**Comment by Cka3o4Huk** [comment]
Yes, this is metadata defined by me :)
Closing this issue.
