### ISSUE TITLE
Add graphml support (not just graphviz)

### ISSUE THREAD

**Issue by radare** [radare/radare2#6234]
for ag/agc/agC/...

**Comment by Maijin** [comment]
`e scr.graphml`

**Comment by radare** [comment]
this is not related to screen. you cant print pd or ?e in graphml syntax.. its more related to the kind of output for graph structures... so it should be maybe `e graph.format=graphml` and we can use kv,graphviz, graphml, ...

**Comment by Maijin** [comment]
Ok :) Just better to add some stuff in the issue than just title.
