### ISSUE TITLE
Fast Analysis Mode

### ISSUE THREAD

**Issue by radare** [radare/radare2#6237]
It will be good to have a way to analyze in a fast way, without storing or analysing everything. this is useful because sometimes we just want to know where all the functions start and their xrefs.

**Comment by radare** [comment]
this can be done with `aae` and `fla` .. or maybe an `aac` mode that just flags and adds empty function boundaries to be analyzed with detail later

**Comment by Maijin** [comment]
I think this has been done with aas right?

**Comment by radare** [comment]
Nope its aab but still wip. Give me some more days and this shit will rock

**Comment by Maijin** [comment]
What about this ? #8455 is done too now

**Comment by radare** [comment]
I think we can kill this issue now :)
