### ISSUE TITLE
Move FLIRT support to extras

### ISSUE THREAD

**Issue by radare** [radare/radare2#6239]
There's no need to keep holding unmaintained ida-compatibility stuff in core. r2 zignatures should be the way to go.

**Comment by XVilka** [comment]
Please don't
It's important, very important.

**Comment by radare** [comment]
it is not important

ida updates this file format in every update, signatures needs to be constructed for every version of the lib and every new version of ida, and there’s nobody working on this for a very long time, also i have never heard of anyone using this functionality at all, because if youw ant to debug or extend it you can’t because ida is closed source and the fileformat is a mess.

so imho we should not support IDA at all, its a loss of time and resources, if anybody at some point wants to use it or update it he can do it. the code will not be removed. but it is currently a wrong recommendation to tell users to use this.

if it’s that important why nobody fixed or used it in all those years?

actually, the signatures support in r2 should get more love and will be greatly optimized and enhanced. so whats the point on supporting a closed source format for something like this in *core*?

**Comment by XVilka** [comment]
There are ppl who are using it before 6.8 version, still. For example supporting KolibriOS exe in the core, but throwing de-facto standards of signatures in RE world - Yara and FLIRT, it's pointless and isolationist policy.

**Comment by radare** [comment]
Having kolibrios support is just 100 lines of C and took me about 15m to do it, about standards, i dont think a closed source thing should be considered a standard. im not here to feed them.

look at odt or pdf, those are standards, and office needs plugins for them.

im not banning the ability to support yara or flirt. but those are separate projects. as well as many plugins in r2 that are shipped in -extras because they dont relay on core.

**Comment by jvoisin** [comment]
FLIRT is the *de facto* standard for binary signatures, everyone is using it. It might be broken, but this is all that we have for now. If we decide to drop its support in radare2 core, we should at least provide a way to translate it to zignatures.

**Comment by radare** [comment]
Maybe in your world flirt is a standard for something, in the world i live i dont see any ida, or windows or any other commercial crap. /me feels bad for you

to provide a way to translate flirt into r2 zignatures we will first need to fix the flirt support, because it is actually useless, and im not talking about removing it, im talking about *MOVING* it to extras

**Comment by jvoisin** [comment]
It's almost the same as removing it :)

(I'm quite sure that OSX counts as commercial crap though)

**Comment by radare** [comment]
dont compare an operating system with a tool. besides r2 can be considered an OS…

if you dont want it to be removed then fix it. because i care -1 about supporting propietary file formats for compatibliity

**Comment by XVilka** [comment]
@radare 
>  in the world i live i dont see any ida, or windows or any other commercial crap
r2 userbase is extremely larger than your world. Please keep that in mind, r2 popularity growing constantly.

**Comment by radare** [comment]
if so, why nobody cared about fixing flirt at all? i care about stuff that people maintains.

**Comment by XVilka** [comment]
We see your point, it will be fixed before the next release, I'll add the tests.

**Comment by radare** [comment]
by who :D

**Comment by XVilka** [comment]
You tricking me! By me, I just need a few days before I start.

**Comment by radare** [comment]
like all the other PRs and issues assigned ? :D

**Comment by XVilka** [comment]
I told you the reason in telegram. And how it'll change soon :P

**Comment by radare** [comment]
yeah i know, looking forward the wave of commits :)
