### ISSUE TITLE
Correlate registry reference to function.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#6256]
HI,
Shouldn't this call be detected as/correlated to SendMessageA?
![image](https://cloud.githubusercontent.com/assets/6576335/20596818/90971286-b240-11e6-9ec7-20d60f035d0b.png)
I see this kind of calls to registry often and it is an unnecessary work to search for the function assignment.

**Comment by radare** [comment]
can you share a binary/sample test script to reproduce the case? so we can have a look to the issue?

relating ebx to its original value can only be done with esil, and this is what you get in the comment at right... but i cant see it completely because you chopped the image

**Comment by MariasStory** [comment]
Hi @radare,
Get the complete strings:
![image](https://cloud.githubusercontent.com/assets/6576335/20597279/07e87544-b243-11e6-92e5-569c6f784bd9.png)
To get this result I used:
aeim;e anal.searchstringrefs=true;e asm.emu=true; aap; aaaa
Binary: https://www.hybrid-analysis.com/sample/26757bbde17d6c32b48b388b7a73195a5c67d5ec897afabc36a170870c824938?environmentId=100

**Comment by radare** [comment]
we can enhacne  asm.emu and asm.emustr to resolve the flag at the value of each register change, this will solve the problem

**Comment by MariasStory** [comment]
Sounds good.
BZW: I would be interested to see your approach on reversing this binary with r2. Kind of a real word reversing challenge. Just to make sure that I am not missing some cool tricks. ;-)

**Comment by radare** [comment]
can you provide a link that doesnt requires login or wtf procedures to get the bin?

**Comment by Maijin** [comment]
[26757bbde17d6c32b48b388b7a73195a5c67d5ec897afabc36a170870c824938.zip](https://github.com/radare/radare2/files/611273/26757bbde17d6c32b48b388b7a73195a5c67d5ec897afabc36a170870c824938.zip)

Here you go, zip password (infected)

**Comment by MariasStory** [comment]
Thanks @Maijin  ;-)

**Comment by radare** [comment]
uhm, its not that easy.. be reference reads the dword in that address instead of refering the address.

So i dont see a way to know which address ebx was read from directly from asm.emu… and i dont like the idea of storing source pointers for each reference… any better proposal? if not you should write an r2pipe script to do that

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/20601250/ee98802e-b257-11e6-8c87-0661c0fc7e1e.png)

**Comment by radare** [comment]
i dont see why IDA considers `mov ebx, [foo] to be the same as mov ebx, foo….` this is a plain wrong assumption. the representation is IDA is wrong, but people get used to their notations and complain when using other tools.

if you emulate or debug this code you’ll see that EBX is not pointing to SendMessageA.

**Comment by Maijin** [comment]
Debugged

![image](https://cloud.githubusercontent.com/assets/1408600/20602766/fbd17f50-b25e-11e6-9dca-b664151c6bf4.png)

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/20602819/32fd80e6-b25f-11e6-8811-ccf069d0df63.png)

**Comment by radare** [comment]
as i said, 0x76cd613E is outside the addressspace of this binary. OLLY resolves the correct address because it loads the symbols of the library, and it works because EBX contains the address defined by the windows linker at load time. So the easiest solution to this problem is to make RBin create flags pointing to the destination targets of each reloc entry at load time but this can bring some false assumptions in case the linker replaces those values at runtime…

**Comment by MariasStory** [comment]
When the move to the registry is on the screen, it work:
![image](https://cloud.githubusercontent.com/assets/6576335/20604240/acbe67b4-b265-11e6-8ff0-124ea821c493.png)

When the move to the registry is out of the screen it does not work:
![image](https://cloud.githubusercontent.com/assets/6576335/20604325/1b0d6e36-b266-11e6-9fd4-86b465d2f3b1.png)

Any way, thanks for the fast (partial) solution. ;-)
