### ISSUE TITLE
Incorrect visualization of "data" block & shift of code lines in multi-column view.

### ISSUE THREAD

**Issue by Cka3o4Huk** [radare/radare2#6257]
Version: radare2 1.0.2 & HEAD (commit - c4ee05b)
OS: FreeBSD 12-CURRENT
Target file: MIPS32 binary

Test case:
 - Source file: binary file (firmware) with mix of code & data sections. 
   `r2 -a mips -b 32 -e cfg.bigendian=true bootloader.dump`
 - Use analysis or define functions / data manually
 - Switch to multi-column view (Vpppp)

Actual result:
 - data is shown as code. (To be data?)
 - second column contains lines already present in first column

Screenshot:
![screenshot from 2016-11-24 13-38-02](https://cloud.githubusercontent.com/assets/47472/20600791/bdf49946-b26e-11e6-9a3f-fbf001d9c71b.png)
![screenshot from 2016-11-24 13-36-55](https://cloud.githubusercontent.com/assets/47472/20600790/bdf4806e-b26e-11e6-85ae-dc3788ac7980.png)

Github doesn't allow me to upload archive with bootloader (bootloader.zip), so it's located here: http://cloud.unclebear.ru/bootloader.zip

**Comment by Maijin** [comment]
[bootloader.zip](https://github.com/radare/radare2/files/611490/bootloader.zip)

**Comment by Maijin** [comment]
Here it is on github.

**Comment by Cka3o4Huk** [comment]
Thank you, @Maijin !
