### ISSUE TITLE
Highlight current block in 'aga'

### ISSUE THREAD

**Issue by hteso** [radare/radare2#6260]
When executing the `aga` command it would be nice to highlight the current node in a different color, or the node of the specified address if executed like `aga [addr]`.

**Comment by Maijin** [comment]
An eval already exist, did you try it ?
    graph.gv.current: Highlight the current node in graphviz graph.

**Comment by hteso** [comment]
Doesn't seem to work for the `aga` command, or at least I can't make it work.

**Comment by Maijin** [comment]
See https://github.com/radare/radare2/commit/9d68cf74f843af790a2b88214b8e9f65f7728439

**Comment by hteso** [comment]
Yes, tested with command `ag` and it works, but I tested again with command `aga` and it doesn't.

**Comment by Maijin** [comment]
Check the commit if you want to fix it yourself

**Comment by Svenito** [comment]
Let me know if you want to fix it. No point both working on it
