### ISSUE TITLE
Bad assembly during patching

### ISSUE THREAD

**Issue by akrasuski1** [radare/radare2#6270]
If I want to patch a jump instruction into other jump, I'd write `wa je 0x400618`. However, the instruction being inserted is actually `je 0x800c20`. Apparently radare2 treats the instruction as though it was inserted at offset 0.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
confirmd, this is a regression. fixing… @maijin pls add a test like:


$ r2 -qc "wa je 0x33 @ 0x10;pi 1 @0x10" -
je 0x43

**Comment by radare** [comment]
this was a regression introducen by @svenito

we should probably test more relative instructions 

thanks

**Comment by Maijin** [comment]
Adding a test.

**Comment by Svenito** [comment]
I'll add some more relative tests too

**Comment by akrasuski1** [comment]
Thanks, seems to work now.
