### ISSUE TITLE
PDF function disassembly ends prematurely

### ISSUE THREAD

**Issue by Tzeny** [radare/radare2#6271]
After seeking to the main function and trying to disassemble it using pdf the command ends midway through the function. I also tried pdr, it yielded similar results.

This is Radare's output: [http://pastebin.com/nj3jRK1t](http://pastebin.com/nj3jRK1t)

This is the source code: [http://pastebin.com/E3fagPaM](http://pastebin.com/E3fagPaM)

Radare version:

> radare2 1.1.0-git 13121 @ linux-x86-64 git.1.0.2-177-gcb06c9c
> commit: cb06c9c26b8c7d70c71988242d943d75bdf6cdad build: 2016-11-30

I am running Ubuntu:

> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.1 LTS
> Release:	16.04
> Codename:	xenial

**Comment by radare** [comment]
please share the binary, the code generated with my gcc is analyzed properly, forward jumps are usually a bit nasty for r2

thanks

**Comment by Tzeny** [comment]
Here is the binary: [https://drive.google.com/file/d/0B-uzdV6-4C_ZZXoxU0VQcjBTLVE/view?usp=sharing](https://drive.google.com/file/d/0B-uzdV6-4C_ZZXoxU0VQcjBTLVE/view?usp=sharing)

**Comment by radare** [comment]
can we add this binary in the testsuite?

**Comment by radare** [comment]
fixed in here 72e874c2acf6b2f6fb083f92150b5096a50f1e0e

thanks!

maijin plz add a test.. af@main and counting the number of basic blocks should be enough to avoid this regression to happen again.
