### ISSUE TITLE
Cleaning up ./sys

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#6282]
We currently have a lot of scripts inside `./sys`, what about removing some of them, like:
- `afl.sh`: it's easy enough to use `install.sh` with the right variables exported
- unify `android-aarch64.sh`, `android-arm.sh`, `android-mips64.sh`, `android-mips.sh` and `android-x86.sh` in a single, argument-taking script.
- `asan.sh`: same remarks as for `afl.sh`, it's just a matter of exporting some environment variables
- `build-harden.sh` is already available in `install.sh`, with the right environment variable
- `clone-r2-bindings.sh`, since the bindings are deprecated, are we sure that we want to provide a way to install them?
- `gtkaml.sh` isn't working
- `gtk.sh` isn't useful
- is `menu.sh` used by anyone?
- `python-bindist.sh`: same remarks than about the bindings
- We should unify `uninstall.sh` and `full-uninstall.sh`

Here is the complete list:

| Script name                 | Comment  |
|------------------------|---|
| afl.sh                 |   |
| all.sh                 |   |
| android-aarch64.sh     |   |
| android-arm.sh         |   |
| android-build.sh       |   |
| android-mips.sh        |   |
| android-mips64.sh      |   |
| android-release.sh     |   |
| android-shell.sh       |   |
| android-x86.sh         |   |
| asan.sh                |   |
| build-harden.sh        |   |
| build-m32.sh           |   |
| build.sh               |   |
| cherrypull.sh          |   |
| clang-analyzer.sh      |   |
| clean.sh               |   |
| clone-r2-bindings.sh   |   |
| debian.sh              |   |
| dist-all.sh            |   |
| dist-bin.sh            |   |
| dist.sh                |   |
| emscripten.sh          |   |
| extras.sh              |   |
| farm.sh                |   |
| find-regression.sh     |   |
| full-uninstall.sh      |   |
| gtk.sh                 |   |
| gtkaml.sh              |   |
| indent-whitelist.sh    |   |
| indent.sh              |   |
| install-rev.sh         |   |
| install.sh             |   |
| ios-cydia.sh           |   |
| ios-cydia32.sh         |   |
| ios-env.sh             |   |
| ios-sdk.sh             |   |
| ios-shell.sh           |   |
| ios-simulator.sh       |   |
| ios-static-appstore.sh |   |
| ios-static.sh          |   |
| jam.sh                 |   |
| ldconfig.sh            |   |
| maemo.sh               |   |
| menu.sh                |   |
| mingw32-deps.sh        |   |
| mingw32-python-deps.sh |   |
| mingw32-python.sh      |   |
| mingw32.sh             |   |
| mingw64-deps.sh        |   |
| mingw64.sh             |   |
| osx-pkg-uninstall.sh   |   |
| osx-pkg.sh             |   |
| pie.sh                 |   |
| purge.sh               |   |
| python-bindist.sh      |   |
| python-deps.sh         |   |
| python-dist.sh         |   |
| rebuild.sh             |   |
| shellcheck.sh          |   |
| static.sh              |   |
| sync.sh                |   |
| tcc.sh                 |   |
| termux.sh              |   |
| tiny.sh                |   |
| uninstall.sh           |   |
| update.sh              |   |
| user.sh                |   |
| vala.sh                |   |
| whereis.sh             |   |
| xx.sh                  |   |

**Comment by Maijin** [comment]
I would keep asan.

For uninstall there is uninstall.sh but it doesn' work so i would go for removing that. python-r2pipe.sh is useless, there is r2pm + pip.

**Comment by Maijin** [comment]
+ 1 for bokken.sh, this doesn't work.

**Comment by jvoisin** [comment]
Damn misclick.

**Comment by radare** [comment]
Agree

**Comment by radare** [comment]
sys/python.sh is used by the `r2-python` r2pm package

**Comment by jvoisin** [comment]
Don't we want to kill the bindings anyway?

**Comment by XVilka** [comment]
@jvoisin save afl.sh and asan.sh but unify them, cut the duplications, etc. It's useful to just call them

**Comment by radare** [comment]
i have removed some today

**Comment by dferrero** [comment]
`android-aarch64.sh`, `android-arm.sh`, `android-mips64.sh`, `android-mips.sh` and `android-x86.sh` in a single, argument-taking script done in https://github.com/radare/radare2/pull/6319

**Comment by Maijin** [comment]
@jvoisin can you update the issue ?
