### ISSUE TITLE
Stepping-into x64 continues unexpectedly

### ISSUE THREAD

**Issue by TobalJackson** [radare/radare2#6286]
Hello,

I've noticed a strange behavior when stepping-into the printf call between x32 and x64 versions of the same program:
```c
#include <stdio.h>
#include <stdlib.h>

int main(){
	printf("Hello, world!");
	exit(0);
}
```
I compile this program with: 
`gcc -g -fno-stack-protector -O0 -o print_64 print1.c`
and
`gcc -g -m32 -fno-stack-protector -O0 -o print_32 print1.c`

for the 64 and 32 bit versions respectively.

My system information:
```text
-> % gcc --version
gcc (GCC) 6.2.1 20160830
-> % pacman -Qi gcc-multilib | grep -P 'Name\s+:|Version\s+:|Depends On\s+:'
Name            : gcc-multilib
Version         : 6.2.1-1
Depends On      : gcc-libs-multilib=6.2.1-1  binutils>=2.26  libmpc
-> % r2 -version
radare2 1.1.0-git 13146 @ linux-x86-64 git.1.0.2-202-gdb0f4da
commit: db0f4da4ff07a57709ea3648d7880ade9e30e56c build: 2016-12-05
```
When debugging both versions, I use:
```
aaa; db sym.main; dc; V
```

to arrive at visual debugging of main. I step until eip is at the call instruction:

```
0x08048454      e8a7feffff     call sym.imp.printf         ;[1]; int printf(const char *format);
```

on x32, and at 

```
0x00400554      e8d7feffff     call sym.imp.printf         ;[1]; int printf(const char *format); 
```

on x64.
When I step into this function using \<s\>, on x32 version it works as expected; I can step until the kernel call and see the string printed.  However, on the x64 bit version, when I step into the call, stepping into the the first instruction:

```
0x00400430      ff25e20b2000   jmp qword [reloc.printf_24] ; [0x601018:8]=0x400436 LEA reloc.printf_24 ; "6.@" @ 0x601018
```

immediately sets my `rip=0x7f5b26d18448`, which is this instruction:

```
0x7f5b26d18448      483d00f0ffff   cmp rax, -0x1000
```

and single stepping one more time brings me to what appears to be finished execution of the program.

I've recorded an example session demonstrating this behavior:
https://asciinema.org/a/awj7pl2mifajgu33nosrpyd96

**Comment by TobalJackson** [comment]
I've uploaded the source and 2 example binaries:

[print.zip](https://github.com/radare/radare2/files/632472/print.zip)

**Comment by skuater** [comment]
Sorry by the delayed answer.

The linux backend is loading with swstep = true, until become fixed plz use this command to set this value to false:
Load the file into r2 and type:
e dbg.swstep=false

then u can still working without this issue

The real issue is when r2 try to emulate a hwstep and set a break in the destination address, in x32 the generate code is a call address, and for x64 is a call ptr[address], the analysis for call ptr[address] is doing incorrectly, and r2 jump to a random address. 

How u are working in a linux u can use without problem the hwstep disabling dbg.swstep into r2.

**Comment by TobalJackson** [comment]
Hey @skuater,

Thank you for this workaround; I've just tested it and it works! Thank you, I wish you luck in hunting down the bug.

**Comment by radare** [comment]
the bug has been hunted and fixed already in master, just git pull
