### ISSUE TITLE
agf doesn't work through r2pipe

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6289]
From @m4ndingo : agf doesn't work (doesn't output anything) through r2pipe.

**Comment by radare** [comment]
works fine here, at least with the python api.

i guess you are maybe trying to graph a HUGE function which breaks the r2pipe.cs api or something

**Comment by m4ndingo** [comment]
Hello

I'm trying to send this command (aef) with r2pipe in .net but I get allways an empty result; in the shell works fine (same binary)

![agf_notwoking_onpipe](https://cloud.githubusercontent.com/assets/12532269/20939396/f8e9eaa4-bbee-11e6-85b2-6933bdccfc75.png)

**Comment by radare** [comment]
Hello

i know that it works, that's why im saying where the issue is

**Comment by Maijin** [comment]
entry0 is very small.

**Comment by radare** [comment]
maybe its an issue with the windows build... he should confirm that the same issue happens with r2pipe.py or place some printfs in the r2pipe.cs module..

**Comment by m4ndingo** [comment]
![r2pipe_agf_python_fails_too](https://cloud.githubusercontent.com/assets/12532269/20986400/dd606882-bcc8-11e6-88d2-cea28cdcd972.png)

**Comment by Maijin** [comment]
@skuater ^

**Comment by radare** [comment]
Try with just r2cmd("af;agf")

**Comment by m4ndingo** [comment]
![r2pipe_agf_python_fails_too](https://cloud.githubusercontent.com/assets/12532269/20987272/46a8cade-bccc-11e6-9c6c-710170dcf92a.png)

**Comment by Maijin** [comment]
use  scr.rows and scr.columns
