### ISSUE TITLE
rarun2 is buffering the ouput till the program ends

### ISSUE THREAD

**Issue by asutoshpalai** [radare/radare2#6303]
I am trying to redirect the io of a program to my script. So, I am using rarun2 with the listening option. But the output of my program is not sent to the script until the program has exited.

Filtering out the unnecessary details, I could distill the reproduction to this
```bash
#!/usr/bin/env bash

set -e

cat > io.c <<-C
#include <stdio.h>
int main() {
	int i;	printf("Started the binary\n");
	scanf("%d", &i);
	printf("Entered num %d\n", i);
	scanf("%d", &i);
	printf("Entered num %d\n", i);
}
C

gcc -o io io.c
rarun2 program=io listen=4000
```

In first terminal:

    $ ./issue.sh

In another terminal

    $ nc localhost 4000
    4
    5
    Started the binary
    Entered num 4
    Entered num 5

_4 and 5 are the inputs_

I think the expected output should be

    $ nc localhost 4000
    Started the binary
    4
    Entered num 4
    5
    Entered num 5

I am trying out rarun2 for the first time so I don't know if my use case is wrong. The intended use-case is to use it with r2 for debugging.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by asutoshpalai** [comment]
I have verified this on a fresh install (it wasn't installed earlier) on an Ubuntu 16.04 LTS server.

Its `r2 -v` reads
```
radare2 1.1.0-git 13171 @ linux-x86-64 git.1.0.2-226-gc041dec
commit: c041decf9b7966a7555a25bafe2159cbd70a101f build: 2016-12-10
```

I actually faced the bug on my Arch laptop and checked it after an update too.

**Comment by radare** [comment]
thats what happens if you dont fflush() after printf(). try with `rarun2 program=/bin/sh listen=8080`

**Comment by asutoshpalai** [comment]
Thanks for your reply.

But this is a stub issues reproduction program and my main aim was to debug another one which I can't modify. Is there anyway I can do that?

**Comment by radare** [comment]
You can use ldpreload to tweak the console terminal information to have 1 byte of buffer size for stdout, or calling fflush after some api hooks with it..
