### ISSUE TITLE
"V_" for help.

### ISSUE THREAD

**Issue by MariasStory** [radare/radare2#6311]
Can we make something similar to "V_" for all possible options and commands in r2?
I hope to have some command (combination of keys) that would let me find needed command or option by typing words present in it's description, like it is done in "V_".
Basically, I would press the combination of keys and have a list of all options and commands with descriptions and a possibility to filter them through typing on top of the list.
Would be also nice to have the selected command in the command line after it is selected in the list.

**Comment by Maijin** [comment]
Just use ?* with grep

**Comment by radare** [comment]
You can extend the command list of the hud if you miss any. Having all of them seems useless to me
