### ISSUE TITLE
Debugger not stopping at breakpoints

### ISSUE THREAD

**Issue by peperunas** [radare/radare2#6313]
The debugger seems not to be stopping at breakpoints.

These are the steps I do to reproduce the behaviour:

Open the binary: 
`$ r2 -d binary`
Set a breakpoint:
`> db 0xdeadb00b`
Run the application:
`> dc`

Nothing happens though.

**Comment by radare** [comment]
Are you using the last version from git? Which os and arch? It works for me

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
@peperunas ping

**Comment by peperunas** [comment]
I always use the git version.

Here is a demo: https://asciinema.org/a/eoxiz5bjv1n2s7027c0qetuxf

**Comment by radare** [comment]
Are you sure the given address is mapped at the time you set the breakpoint? Can you do an asciinema?

**Comment by peperunas** [comment]
How do I check whether it's mapped in memory?

**Comment by Maijin** [comment]
`d?`
`dm` -> Show memory maps

**Comment by peperunas** [comment]
https://asciinema.org/a/32r61b8yiuggpgprvkzet4m9t

**Comment by radare** [comment]
Tested on linux and osx and works as expected for me

**Comment by Maijin** [comment]
I always use the git version : prove it, paste r2 -v. 
Drag the binary here in a zip archive if you can share it.

**Comment by radare** [comment]
several questions:

1) why do you analyze?
2) why do you doo if that was not explained in the issue?
3) did you checked the maps after the doo? because if there’s aslr the address will be in different place

breakpoints at a given address are not nominal. if the symbol moves to another place after a reload or because of some dyld tricks its not gonna work this way

tested that everything works fine on linux and osx for me

**Comment by peperunas** [comment]
@Maijin have you seen the first asciinema demo I've posted? I clearly do a `r2 -v`.

@radare just tell me which sequence of commands should I try then. How may I completely remove r2 and reinstall it?

**Comment by Maijin** [comment]
Ah yes.

**Comment by peperunas** [comment]
I forgot to add the test binary: 

`echo "f0VMRgEBAQAAAAAAAAAAAAIAAwABAAAAdIAECDQAAAB0AQAAAAAAADQAIAACACgABAADAAEAAAAA
AAAAAIAECACABAjOAAAAzgAAAAUAAAAAEAAAAQAAANAAAADQkAQI0JAECIwAAACMAAAABgAAAAAQ
AACQvgAAAACLHdCQBAiDwwM5HdSQBAh9Bisd1JAECLiZgAQI/+CDiR3QkAQIv1qRBAiLBDXYkAQI
MdiJBDXYkAQIRoH+gQAAAHW96RYQAAC4AQAAALsAAAAAzYAAALwAAAD/AAAAL3rByMvOatXX2t0I
/ubp7IOX1ZWUiiJhbSt+cGdkOnhTVwYTDF9TRlpUUEtE1xTEoelKWVxfr+WAU25xdM9+fYCDPYiM
j5J9hpueocjCisDfx5bd2Z+ypLu47rSno/rnwIiPm4WEnYDya6CL9LIWDhEU2pqNmyMmKSyXMzU4
O/PBAHgAAC5zaHN0cnRhYgAudGV4dAAuZGF0YQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAsAAAABAAAABgAAAHSABAh0AAAAWgAAAAAAAAAAAAAABAAAAAAAAAARAAAA
AQAAAAMAAADQkAQI0AAAAIwAAAAAAAAAAAAAAAQAAAAAAAAAAQAAAAMAAAAAAAAAAAAAAFwBAAAXAAAAAAAAAAAAAAABAAAAAAAAAA==" | base64 -d > crackme`

**Comment by Maijin** [comment]
@peperunas instead of this base64, drag an archive with your bin on github.

**Comment by peperunas** [comment]
My bad!


[test.zip](https://github.com/radare/radare2/files/657391/test.zip)

**Comment by l4l** [comment]
@peperunas try to set breakpoints after entry point, after opening at debug mode it by default here. Works fine for me:
https://asciinema.org/a/bb22yny9h244xmvqocgk6uob6

**Comment by radare** [comment]
is this a cantreproduce?

**Comment by peperunas** [comment]
@radare, I'll check as soon as possible.

**Comment by peperunas** [comment]
@l4l nope, it's not working.

```
Process with PID 18610 started...
= attach 18610 18610
bin.baddr 0x08048000
USING 8048000
Assuming filepath /home/giulio/sec/CTF/sites/w3challs/crackme/striptease/striptease
Warning: Cannot initialize dynamic strings
asm.bits 32
[0x08048074]> db entry0 + 1
[0x08048074]> dc
le mot de pass est : pasbon
PTRACE_EVENT_EXIT pid=18610, status=0x0
= attach 18610 1
[0x08049159]> 
```

**Comment by radare** [comment]
Cc @leberus

**Comment by leberus** [comment]
Ill take a look tomorrow

El dia 29/01/2017 00:48, "radare" <notifications@github.com> va escriure:

**Comment by leberus** [comment]
@peperunas last output you pasted seems quite old. Could you get r2 from git again and try it again.
I've tested it on my site and unfortunately I couldn't reproduce your error (I've tested it on Linux x86_64):

```
leber@paradise:~/lab/r2/6313$ r2 -d test
Process with PID 14715 started...
= attach 14715 14715
bin.baddr 0x08048000
USING 8048000
Assuming filepath /home/leber/lab/r2/6313/test
Warning: Cannot initialize dynamic strings
asm.bits 32
 -- give | and > a try piping and redirection
[0x08048074]> db entry0 + 1
[0x08048074]> db
0x08048075 - 0x08048076 1 --x sw break enabled cmd="" cond="" name="entry0 + 1" module="/home/leber/lab/r2/6313/test"
[0x08048074]> dc
Selecting and continuing: 14715
hit breakpoint at: 8048075
[0x08048074]> dc
Selecting and continuing: 14715
le mot de pass est : pasbon
PTRACE_EVENT_EXIT pid=14715, status=0x0
[0x08049159]>
```

As I said, from your last output looks like you have an old r2 version there, so please test it from git and tell us.
Although it was working for everyone before, r2 received a lot of updates regarding debugger functionality lately, so it could be you were hitting a corner case that now it's fixed.

**Comment by peperunas** [comment]
```
Process with PID 27458 started...
= attach 27458 27458
bin.baddr 0x08048000
USING 8048000
Assuming filepath /home/giulio/sec/CTF/sites/w3challs/crackme/striptease/striptease
Warning: Cannot initialize dynamic strings
asm.bits 32
[0x08048074]> db entry0 + 1
[0x08048074]> db
0x08048075 - 0x08048076 1 --x sw break enabled cmd="" cond="" name="entry0 + 1" module="/home/giulio/sec/CTF/sites/w3challs/crackme/striptease/striptease"
[0x08048074]> dc
Selecting and continuing: 27458
le mot de pass est : pasbon
PTRACE_EVENT_EXIT pid=27458, status=0x0
[0x08049159]> 
```

Still nothing.

**Comment by peperunas** [comment]
```
Process with PID 27458 started...
= attach 27458 27458
bin.baddr 0x08048000
USING 8048000
Assuming filepath /home/giulio/sec/CTF/sites/w3challs/crackme/striptease/striptease
Warning: Cannot initialize dynamic strings
asm.bits 32
[0x08048074]> db entry0 + 1
[0x08048074]> db
0x08048075 - 0x08048076 1 --x sw break enabled cmd="" cond="" name="entry0 + 1" module="/home/giulio/sec/CTF/sites/w3challs/crackme/striptease/striptease"
[0x08048074]> dc
Selecting and continuing: 27458
le mot de pass est : pasbon
PTRACE_EVENT_EXIT pid=27458, status=0x0
[0x08049159]> 
```

**Comment by leberus** [comment]
Mm, strange.
Do you have any special options enabled for debugger? Can you show me your config regarding dbg.* values?
Thanks ;)

**Comment by peperunas** [comment]
This is my `.radare2rc`:

```
e cfg.fortunes = false
# Show comments at right of disassembly if they fit in screen
e asm.cmtright=true
e io.cache = true

# Display stack and register values on top of disasembly view (visual mode)
e cmd.stack = true

# Use UTF-8 to show cool arrows that do not look like crap :)
e scr.utf8 = true
```

and `dbg.*` confs:

```
[0x08048074]> e dbg.
dbg.aftersyscall = true
dbg.args = 
dbg.backend = native
dbg.bep = loader
dbg.bpinmaps = true
dbg.bpsize = 1
dbg.btalgo = fuzzy
dbg.btdepth = 128
dbg.clone = false
dbg.consbreak = false
dbg.execs = false
dbg.exitkills = true
dbg.follow = 64
dbg.follow.child = false
dbg.forks = false
dbg.hwbp = 0
dbg.libs = 
dbg.profile = 
dbg.slow = false
dbg.status = false
dbg.swstep = false
dbg.threads = false
dbg.trace = false
dbg.trace.inrange = false
dbg.trace.tag = 0
dbg.unlibs = 
```

**Comment by leberus** [comment]
I'm unable to reproduce it, its working for me :(. Do you have this issue with all binaries? Or just with this one?
I'll try to have some thoughts about it

**Comment by radare** [comment]
Works for me too. Tested on linux-x64 and osx

**Comment by peperunas** [comment]
It happens to every binary I try to debug. I've already removed and reinstalled r2 several times.

**Comment by peperunas** [comment]
Any idea about this? I still can't debug ANY binary with r2!

**Comment by peperunas** [comment]
My config file was full of errors and it caused all this mess.

**Comment by leberus** [comment]
nice to hear that ;)

**Comment by Maijin** [comment]
👍 Glad this is fixed, you can complain to the blogpost article that made you used those shitty old variables (I already told the guy to fix)

**Comment by usama8800** [comment]
More specifically, it was `e io.cache = true`
I had that line in my rc too and breakpoints weren't working and I changed it to `e io.cache.write = true` and now they work

**Comment by radare** [comment]
Thats expected

**Comment by Shadorain** [comment]
> More specifically, it was `e io.cache = true`
> I had that line in my rc too and breakpoints weren't working and I changed it to `e io.cache.write = true` and now they work

Oh my goodness thank you for this, read through this whole issue log because I've been having the same issue here and removing `e io.cache = true` and `e io.cache.write = true` from my config fixes it perfectly. 
Thanks!
