### ISSUE TITLE
dietline - wrong handling ESC

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#6321]
If type something like "qew qwe" in command line of r2, then press ESC:
 
  - It moves cursor to the start of the line
  - It doesn't clear the line
  - It doesn't show the next command if type it
  - After typing the next command, and pressing enter - it runs, but still no display
  - After the 2nd command ends its execution, typing one more command displays it, but pressing Enter doesn't run it.

**Comment by radare** [comment]
Happens in all terminals? Didnt tried yet

Workaround: but a macbookpro and remove the esc key from the magicbar

**Comment by XVilka** [comment]
Yes, same thing on a lot of different terminals.

**Comment by alvarofe** [comment]
The ESC thing happens here too, but you don't need to type `qwe qwe` to move the cursor to the start of the line. As soon I type something it comes back to its position and you can continue. Mind you record an asciinema to understand better the issue?

**Comment by radare** [comment]
works fine in osx for me. i dont see any issue here

**Comment by XVilka** [comment]
Will record an asciinema.

**Comment by XVilka** [comment]
I found some ESC handling in libr/cons/dietline.c, but when I added eprintf() for catching it, it wasn't shown: https://github.com/radare/radare2/blob/master/libr/cons/dietline.c#L1195

Is the right place to dig?

**Comment by radare** [comment]
yes, go deeper

**Comment by XVilka** [comment]
@deepakchethan please check this one too since you are working on dietline.

**Comment by deepakchethan** [comment]
Currently, when I type in ESC the line gets cleared and on typing some key twice, it gets back to the original place.

**Comment by deepakchethan** [comment]
In #14514 on pressing escape, it goes into vi mode or just ignores it if the config var is set not to use vi mode. So this issue will be fixed too.
