### ISSUE TITLE
Hangs on call on step over (F8)

### ISSUE THREAD

**Issue by alex-t0** [radare/radare2#6337]
I am playing with task 3 from pwnable.kr.
Binary: http://pwnable.kr/bin/bof
C Source: http://pwnable.kr/bin/bof.c

I debug step by step `func` function.

It hangs at call 0xf75fd910 inside `func` function, address 0x5664564f. I think execution passed to gets, but from visual mode there are no place where to input my string, which must overflow buffer :)

Not in visual mode program asks for input string normally.

It seems like it hangs. It is bug or I am doing something wrong?

**Comment by radare** [comment]
It waits until the read syscall returns. So i guess thats expected behaviour

**Comment by alex-t0** [comment]
How to enter string and go to the next instructions in visual mode? It does bot switch to other modes.

**Comment by radare** [comment]
it is fixed now?

**Comment by radare** [comment]
Considering it is fixed
