### ISSUE TITLE
Implement aeaj and fix aeaf

### ISSUE THREAD

**Issue by radare** [radare/radare2#6366]
aeaf expects linear functions. should walk the bbs, the order doesnt matter.

aeaj should print this info of aea in json format

**Comment by Soly** [comment]
Can you clarify what the aeaf issue is?

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/23962032/19fd9090-09ad-11e7-9aa0-8f0abada933d.png)

**Comment by radare** [comment]
The idea for this command is to find all registers used in a function, like aea does, but across all basic blocks of the function. The problem is that aeaf right now only works linearly, so it will not follow the basic blocks, and fail in most situations.

About aeaj, well. should be the output in JSON for `aea`.. and then do `aeafj` to show the output of aeaf in JSON

**Comment by radare** [comment]
btw if you are in the mood. this is a similar issue https://github.com/radare/radare2/issues/6654
