### ISSUE TITLE
[anal] Thumb: asrs -> ESIL does not lead to actual arithmetic shift

### ISSUE THREAD

**Issue by ekiwi** [radare/radare2#6388]
For example `asrs r4, r4, 2` will be translated to `r4,r4,=` which is obviously not an arithmetic shift.

As ESIL only supports logical shifts (as far as I can tell), what would be the correct way to fix this?

**Comment by radare** [comment]
open anal_arm_cs.c with your favourite editor and fix that. capstone already provides all this info, just fix the format string that creates this esil expression

thanks!

**Comment by ekiwi** [comment]
> open anal_arm_cs.c with your favourite editor and fix that. capstone already provides all this info, just fix the format string that creates this esil expression

but what would be the correct ESIL command for an **arithmetic** right shift?

**Comment by radare** [comment]
OP ("<<", esil_lsl);
        OP ("<<=", esil_lsleq);
        OP (">>", esil_lsr);
        OP (">>=", esil_lsreq);
        OP (">>>", esil_ror);
        OP ("<<<", esil_rol);

(from anal/esil.c)

**Comment by ekiwi** [comment]
These are only logical shifts and rotations. An arithmetic right shift fills the empty positions on the left with the former MSB. I don't see how I can emulate that behavior with the instructions you posted.

**Comment by radare** [comment]
iirc <<< and >>> will do that. because they rotate the bits

there are other archs that already have instructions like this too

**Comment by ekiwi** [comment]
> iirc <<< and >>> will do that. because they rotate the bits

The way I understood it, `<<<` and `>>>` are [circular shifts](https://en.wikipedia.org/wiki/Circular_shift), while what I need is an [arithmetic right shift](https://en.wikipedia.org/wiki/Arithmetic_shift).

Thus:

![rotate_right](https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Rotate_right.svg/450px-Rotate_right.svg.png)

vs

![arithmetic shift right](https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Rotate_right_arithmetically.svg/450px-Rotate_right_arithmetically.svg.png)

_(both images from wikipedia under CC BY-SA 3.0)_

**Comment by radare** [comment]
there’s no esil instruction for that. we can implement this in <<<< and >>>> or you can implement it in several esil instructions.

sorry for the confusion

implementing those two new instructions in esil is just editing the libr/anal/esil.c . i guess other archs will have similar instructions so it’s worth the effort. maybe other esil-ists in r2land can share their thoughs here

**Comment by ekiwi** [comment]
> we can implement this in <<<< and >>>>

If I have enough time I will try to do that.

`>>>>` is enough, as an arithmetic and logical _left_ shift do exactly the same thing, only the _right_ shifts differ.
