### ISSUE TITLE
Add rabin2 -k to handle OpenBSD for rabin2 -C

### ISSUE THREAD

**Issue by radare** [radare/radare2#6396]

**Comment by younix** [comment]
The OpenBSD Kernel detect its binaries with this special ELF section

.section ".note.openbsd.ident", "a"
        .p2align 2
        .long   0x8
        .long   0x4
        .long   0x1
        .ascii "OpenBSD\0"
        .long   0x
        .p2align 2

**Comment by XVilka** [comment]
@devnexen can you please check this one?

**Comment by devnexen** [comment]
Anybody, feel free to correct me, but I m not familiar with this part of the code ... when writing an elf, it does not write any specific section, basically elf = linux whatsoever ... If confirmed, I ll try to see what I can do unless someone is faster :-)

**Comment by radare** [comment]
is check for the OS option, moved to 3.3, thats not  blocking for past tomorrow release

**Comment by Maijin** [comment]
@devnexen  See eval variable "e asm.os"

**Comment by devnexen** [comment]
Ok thx, will see later if I can ... but indeed not vital for this 3.2 release.

**Comment by devnexen** [comment]
Works as expected.

**Comment by Maijin** [comment]
@devnexen so you're saying it's fixed?

**Comment by radare** [comment]
Closing i guess
