### ISSUE TITLE
Cortex-M: arm.gnu differs from arm

### ISSUE THREAD

**Issue by antoinealb** [radare/radare2#6400]
Hi,
I have this project I am testing radare2 on. It uses an STM32F407 processor, so a Cortex-M (ARMv7-M) CPU. When I disassemble the code using the `arm` machine it can't decode some instructions, but it works fine when using the `arm.gnu` plugin:

Using `arm.gnu`:
```
$ radare2 -b 16 -a arm.gnu -m0x08000000 -c "s +0x1c0" firmware/build/test.bin
syntax error: error in error handling
syntax error: error in error handling
r_config_set: variable 'asm.linescall' not found
Please. use 'cf [file]'
 -- To remove this message, put `dbxenv suppress_startup_message 7.5' in your .dbxrc
[0x080001c0]> pd 5
            0x080001c0      72b6           cpsid i
            0x080001c2      2e48           ldr r0, [pc, 184] ; (0x0800027c)
            0x080001c4      80f30988       msr PSP, r0
            0x080001c8      40f20000       movw r0, 0
            0x080001cc      ccf20000       movt r0, 49152
[0x080001c0]> q
```

Using the builtin `arm`, see the change at `0x080001c4`:

```
$ epuck2 radare2 -b 16 -a arm -m0x08000000 -c "s +0x1c0" firmware/build/test.bin
syntax error: error in error handling
syntax error: error in error handling
r_config_set: variable 'asm.linescall' not found
Please. use 'cf [file]'
 -- Too old to crash
[0x080001c0]> pd 5
            0x080001c0      72b6           cpsid i
            0x080001c2      2e48           ldr r0, [pc, 0xb8]          ; [0x800027c:4]=0x20000800
            0x080001c4      80f30988       invalid
            0x080001c8      40f20000       movw r0, 0
            0x080001cc      ccf20000       movt r0, 0xc000
[0x080001c0]> q
```

**Comment by Maijin** [comment]
Did you try changing `e asm.cpu` value? Check the possible value using `e asm.cpu=?`

**Comment by Maijin** [comment]
Also ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
Your radare2rc is fuckedup with variables from radare1 (7 years old)

**Comment by Maijin** [comment]
ping1

**Comment by radare** [comment]
@antoinealb PING

**Comment by antoinealb** [comment]
Sorry for the delay, finally found the time to install radare2 from soure, here is the output of `radare2 -v`:

```
radare2 1.2.0-git 13516 @ darwin-x86-64 git.1.1.0-242-ga8d3d5b99
commit: a8d3d5b996c1bf24c966d2e8159d8ebae6f43286 build: 2017-01-17
````

The issue is still present with this version.

**Comment by antoinealb** [comment]
Also, changing `asm.cpu` to `cortex-m` does not change the result.

**Comment by radare** [comment]
Can u confirm the issue is not in capstone?

**Comment by antoinealb** [comment]
I think radare2 does not correctly set the `CS_MODE_MCLASS` flag in Capstone. Here is my test case:

```python
#!/usr/bin/env python
from capstone import *

CODE = bytes((
    0x72, 0xb6, # cpsid i, sanity check
    0x80, 0xf3, 0x09, 0x88 # should be MSR PSP, r0
    ))

md = Cs(CS_ARCH_ARM, CS_MODE_THUMB | CS_MODE_MCLASS)
for i in md.disasm(CODE, 0):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
```

and its output:

```
0x0:	cpsid	i
0x2:	msr	psp, r0
```

If I remove the `CS_MODE_MCLASS` flag I get a missing second instruction.

See also: aquynh/capstone#235

**Comment by antoinealb** [comment]
The patch works! Thanks for the quick fix.

**Comment by radare** [comment]
This change breaks the disassembly of iOS thumb binaries

**Comment by radare** [comment]
Fixed in 4b371141aada26819242970784b873e95e4f6cc0 

please confirm

**Comment by antoinealb** [comment]
cant find the above commit. Did you rebase it or something?

**Comment by radare** [comment]
Nope

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/197443d42aecccf9e380ca8b742fbd60113df414 I suppose.

**Comment by antoinealb** [comment]
Still works, but now `-e asm.cpu=cortex` is required. Using radare2 built from commit bce083ae7c667ec89ec14f61c1d9bd7f9a882147

**Comment by radare** [comment]
yep. thats expected. unless you know a way to determine when a binary is cortex or not. i mainly work with android and ios apps and i find many regressions if i assume cortex by default

**Comment by antoinealb** [comment]
Not aware of any way. Maybe make the choice explicit (i.e `asm.cpu` must be set by the user) ?

**Comment by radare** [comment]
yes
