### ISSUE TITLE
String(DATA) xref does not work with x86 binary built with -fPIC -m32 

### ISSUE THREAD

**Issue by mgjung95** [radare/radare2#6402]
I found that string xref does not work  when target binary is compiled with -fPIC -m32 in x86.

sample code is ..
`#include <stdio.h>

void main()
{
        printf("Hello PIC!\n");
}`

build cmd > gcc -fPIC -m32 test.c

![image](https://cloud.githubusercontent.com/assets/24835236/21559293/c95934a6-ce8c-11e6-9f45-58f90f492b55.png)

![image](https://cloud.githubusercontent.com/assets/24835236/21559274/a796ca36-ce8c-11e6-848e-fa65160ee861.png)

to make PIC code, compiler generate small code for getting PC address using "fcn.08048350"
so, ebx is set 0x0804842c after calling "fcn.08048350"
     ebx +0x1bd4 - 0x1b20 = 0x08484e0 

![image](https://cloud.githubusercontent.com/assets/24835236/21559304/0ec21a08-ce8d-11e6-9032-7ab181195f9c.png)

and, IDA works with this sample.

Almost data xref will not work with PIC codes in x86 32bit ELF from this reason.
is it possible to patch this issue?

**Comment by Maijin** [comment]
Is it possible you sent the binary in a zip archive ? + Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
Probably works if u use aae but without seeing the code or the commands you used its hard to say

**Comment by mgjung95** [comment]
when I check "r2 -v", the output is...
**mgjung@mgjung-VirtualBox:~/research/swmaze_core/swmaze_core/crypto_test$ r2 -version
radare2 1.2.0-git 13331 @ linux-x86-64 git.1.1.0-64-gad48c07
commit: ad48c071a7efd6b89a7e6b1a7c3c99cc5967d541 build: 2016-12-28**

I tested like followings.
 mgjung> r2 a.out
   [0x0804841d]aaa
   [0x0804841d]aad
   [0x0804841d]pd 20

But I didn't try "aae", could you explain how to use "aae"?

And I attached zip file which includes the tested binary. 
 (need to change txt to a.zip --> zip uploading failed.)
[a.zip.txt](https://github.com/radare/radare2/files/680363/a.zip.txt)

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/231ba6d418de40bff2318085f974de7e0429b47e Added test based on the provided binary.

**Comment by Maijin** [comment]
It doesn't work using aaaa too.

**Comment by Maijin** [comment]
Same as https://github.com/radare/radare2/issues/6819
