### ISSUE TITLE
Search doesn't work when -m option is given to r2

### ISSUE THREAD

**Issue by jttoivon** [radare/radare2#6406]
If I load a file to a location, say, 0x100, then it is mapped there correctly, but
the search is always restricted to range 0 - filesize. Setting the search.from/to variables doesn't help either, see below. I'm using the following version:
```
$ r2 -version
radare2 1.1.0 9999999 @ linux-x86-64 git.1.1.0
commit: HEAD build: 2016-12-29
```

```
$ echo test > test
$ r2 -m 0x100 test
 -- Welcome to IDA 10.0.
[0x00000100]> / test
WARNING from == to?
Searching 4 bytes from 0x00000005 to 0x00000005: 74 65 73 74 
Searching 4 bytes in [0x5-0x5]
hits: 0
[0x00000100]> e search.from = 0
[0x00000100]> e search.to = 0x200
[0x00000100]> / test
Searching 4 bytes from 0x00000000 to 0x00000005: 74 65 73 74 
Searching 4 bytes in [0x0-0x5]
hits: 0
```

**Comment by radare** [comment]
see e search.in=?

**Comment by jttoivon** [comment]
Thanks! Setting `e search.in=io.maps` seems to do the trick. Maybe this should set by default, when the `-s` option is given?

**Comment by radare** [comment]
You are not using -s but maybe we should decide better which search.in mode use by default depending if loading with -n with -d, maybe with -m too, etc... didnt changed that to have some consistent behaviour, but thats up for discussion

**Comment by ewtoombs** [comment]
I'm happy to report that `e search.in = io.maps` has fixed the problem for me too. I agree, though, that this should have been taken care of automatically, somehow. Exactly how, I don't know, because I'm really really new at this too. Also, `e?` does not list `e var=?` as a possible way of using `e`. That would have been good to know.
