### ISSUE TITLE
Wrong AVR 'mul' description on pseudo asm

### ISSUE THREAD

**Issue by n0w** [radare/radare2#6411]
When setting asm.pseudo = true on AVR, the following instruction
`429f           mul r20, r18 `

gets 'translated' as:
`429f           r20 *= r18`

when it should be something like:
`429f           r1:r0 = r20*r18`

**Comment by radare** [comment]
cc @killabytenow

**Comment by radare** [comment]
there's no parse_avr_pseudo.c so it is using the x86 asm parser which is probably going to be buggy in many cases. the solution would be to copy the x86 one and adapt it for avr

**Comment by XVilka** [comment]
ping?

**Comment by radare** [comment]
Pong
