### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by Jichao** [radare/radare2#6413]
iphone5c: 
1)add cydia.radare.org
2)`apt-get install radare2`.
3)`b2`

-sh: /usr/bin/r2: Bad CPU type in executable

**Comment by radare** [comment]
the default package is compiled for 64bits, there’s a separate package for 32bits (radare2-arm32)

**Comment by Jichao** [comment]
@radare 
`apt-get install radare2-arm32` Could not find the package
`apt-cache search radare2` 

> r2frida - Frida plugin for radare2
> radare2 - unix like reverse engineering toolkit

**Comment by radare** [comment]
oh i have to use underscore in the package name to avoid cydia get confused with the version number. you can download the deb and install it by hand for now.

http://cydia.radare.org/debs/radare2-arm32_1.0.2_iphoneos-arm.deb

i’m gonna fix this and push an updated package for 1.1

thanks for noticing this.

**Comment by Jichao** [comment]
thx for your reply, I have manage to build it using `sys/ios-cydia32.sh`.

**Comment by radare** [comment]
should be fixed now. i can see the radare2-arm32 package in cydia
