### ISSUE TITLE
rahash2 failed to read from a pipe

### ISSUE THREAD

**Issue by futex** [radare/radare2#6418]
I have a base64 encoded file and is content is xored, i try to uncrypt with a piped rahash2 command line:

`rahash2 -D base64 forum.php | xargs rahash2 -E xor -S 0x7a`
`rahash2: Cannot open file
`

But the command failed (Cannot open file)

If i try with too commands line, it run perfectly
`rahash2 -D base64 forum.php > /tmp/pp` 
`rahash2 -E xor -S 0x7a /tmp/pp`

**Comment by radare** [comment]
you have to pass the filename as argument thats why it says that it cannot open a file. you can use - to tell rahash2 to read from stdin

**Comment by futex** [comment]
I have try
` rahash2 -D base64 forum.php | rahash2 -E xor -S 0x7a - `
` rahash2 -D base64 forum.php | xargs rahash2 -E xor -S 0x7a - `
` rahash2 -D base64 forum.php | xargs rahash2 -E xor -S 0x7a {} `

they failed too, rahash2: Cannot open file error

**Comment by radare** [comment]
Should be fixed in here 2f5c778abe14a39213944ba9e202ada6a886f7a8

**Comment by radare** [comment]
will be good to have tests for this. can you send a pullreq to the r2r repo with some tests for this?

**Comment by futex** [comment]
After update, it work perfectly with that command

`rahash2 -D base64 forum.php | rahash2 -E xor -S 0x7a -`

Thank you :)
