### ISSUE TITLE
The sandbox can be bypassed

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#642]
Currently, the sandbox is suboptimal:

- [x] It can be bypassed with symlinks
- [x] You can read file with the native `cat` command
- [x] `pwd` and `ls` are also working.
- [x] Should debugger commands be disabled ?
- [x] It should be possible to enable it with a command line argument, that will open the file in RO.
- [x] Trying to disable the sandbox when it's enable should display an error message
- [x] `ls | less` if ~~funny~~ buggy.
- [x] The HUD mode is broken
- [x] You can read files with `pm $FILE`
...

**Comment by condret** [comment]
the hud thing is not a real bug, it is a restriction for security

**Comment by radare** [comment]
i fixed the hud thing

**Comment by radare** [comment]
any reproducer for this symlink issue?

**Comment by jvoisin** [comment]
Seems super-secure-unbreakable now, lets close this for now.

**Comment by radare** [comment]
Awesome. Btw, would be good if someone could provide a selinux and apparmor profiles to sandbox on linux
