### ISSUE TITLE
Obtain all exported functions of dynamically loaded library

### ISSUE THREAD

**Issue by arielkoren** [radare/radare2#6420]
When debugging a program on linux with r2, it seems like i cant get all functions exported by some library (LIBC), but only the functions used by the main program. for example:

```
[0xb7fe3850]> dmm
0x08048000 /opt/protostar/bin/format0
0xb7fe3000 /lib/ld-2.11.2.so
[0xb7fe3850]> dmi 0xb7fe3000 ~ symbols
37 symbols
```

"~" means " | grep"
Obviously there should be more than 37 symbols..

What should i do if i want to find the address of the function "system" or "printf" for example

**Comment by radare** [comment]
confirmed issue. works fine with module name but not with address. this is a one line fix, wanna try to send a pr?

**Comment by arielkoren** [comment]
point me to the module and i will try to have a look this weekend

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/libr/core/cmd_debug.c#L928

**Comment by radare** [comment]
This is fixed already.. dunno why i didnt closed the issue. pls confirm, but i remember to fix it and test it
