### ISSUE TITLE
32 bit ARM assembler errors AND/EOR/ORR

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#6436]
rasm2 -a arm -b 32 'and r2,r2'
022002e0
rasm2 -a arm -b 32 'ands r2,r2'
022002e0

The 'ands' should be 022012e0. The same problem occurs for eor/eors, orr/orrs. Disassembly works:
rasm2 -a arm -b 32 -d 022012e0
ands r2, r2, r2

**Comment by radare** [comment]
Thanks for reporting. You can use the keystone plugin meanwhile
