### ISSUE TITLE
realloc misusage

### ISSUE THREAD

**Issue by l4l** [radare/radare2#6443]
After running cppcheck there's founded lot of realloc misusage like:
```c
var = malloc(..)
...
var = realloc(..)
```

When realloc fails then memory from malloc is leaked. So may be we need some fn like `r_realloc`?

And here is all problem lines:
```
libr/bin/format/elf/elf.c:2500
libr/bin/format/pe/pe.c:685
libr/bin/format/pe/pe.c:2248
libr/bin/format/pe/pe.c:2282
libr/bin/format/pe/pe.c:2497
libr/bin/p/bin_dex.c:231
libr/core/anal.c:833
libr/core/cmd_print.c:3247
libr/core/p/core_java.c:1051
libr/core/p/core_java.c:1098
libr/debug/p/debug_native.c:1317
libr/debug/p/debug_native.c:1342
libr/egg/rlcc/mpc/mpc.c:1525
libr/egg/rlcc/mpc/mpc.c:1599
libr/egg/rlcc/mpc/mpc.c:2077
libr/egg/rlcc/mpc/mpc.c:2080
libr/egg/rlcc/mpc/mpc.c:2090
libr/egg/rlcc/mpc/mpc.c:2096
libr/egg/rlcc/mpc/mpc.c:2105
libr/egg/rlcc/mpc/mpc.c:2278
libr/egg/rlcc/mpc/mpc.c:2287
libr/egg/rlcc/mpc/mpc.c:2315
libr/egg/rlcc/mpc/mpc.c:2326
libr/util/w32-sys.c:23
libr/util/w32-sys.c:125
shlr/spp/p/spp.h:27
shlr/spp/p/spp.h:359
shlr/spp/spp.c:82
shlr/squashfs/src/action.c:354
shlr/squashfs/src/action.c:405
shlr/squashfs/src/pseudo.c:495
shlr/squashfs/src/read_xattrs.c:318
shlr/squashfs/src/xattr.c:274
shlr/squashfs/src/xattr.c:299
shlr/squashfs/src/xattr.c:419
shlr/squashfs/src/xattr.c:464
shlr/tcc/libtcc.c:190
```

**Comment by VisualPrankDude** [comment]
uhm, did you verify the grep ?

**Comment by VisualPrankDude** [comment]
,git diff libr/bin/format/pe/pe.c 
diff --git a/libr/bin/format/pe/pe.c b/libr/bin/format/pe/pe.c
index 0b8350e..f84de30 100644
--- a/libr/bin/format/pe/pe.c
+++ b/libr/bin/format/pe/pe.c
@@ -2495,6 +2495,10 @@ void PE_(r_bin_pe_check_sections)(struct PE_(r_bin_pe_obj_t)* bin, struct r_bin_
        }
        //we need to create another section in order to load the entrypoint
        sections = realloc (sections, (bin->num_sections + 2) * sizeof(struct r_bin_pe_section_t));
+        if (!sections) {
+                r_sys_perror ("malloc (sections)");
+                return NULL;
+        }
        i = bin->num_sections;
        sections[i].last = 0;
        strcpy ((char *)sections[i].name, "blob");

**Comment by l4l** [comment]
What dou mean by that? I didn't use grep much:

cppcheck radare2 >/dev/null 2>&1 | grep "Common realloc"

**Comment by l4l** [comment]
Here you can see section = realloc(section, ...) as well as I mentioned
in first msg

**Comment by VisualPrankDude** [comment]
@Maijin can you please reformat my comment, forgot tags and can't edit currently

**Comment by Maijin** [comment]
got it covered ;)

**Comment by l4l** [comment]
Ah, that's better, @VisualPrankDude. But well, don't see [it in master](https://github.com/radare/radare2/blob/master/libr/bin/format/pe/pe.c#L2497)

**Comment by VisualPrankDude** [comment]
ok, then im off :)
