### ISSUE TITLE
Working with multiple bins is confusing

### ISSUE THREAD

**Issue by radare** [radare/radare2#6447]
Opening more than one bin is not a pleasant experience. Mainly because the oc command kills the current session withiut even asking confirmation or being able yo control multiple cores.

But using oc is not ideal.. we should add another arg to the o command to specify the baddr.. because specifying a different paddr is important to avoid overlapping file maps, but without a different baddr this is useless.

Also flags will override the other file ones.. this is, defining a better workflow for diffing multiple binaries, so we need an easy way to switch from ine binary to another.. this is seeking back and reloading the flags on every switch.

This way we can easily write pdr oneliners to show side by side disasm of two similar functions. This requires also some rethinking to extend the visual mode to get better for diffing and finding similar functions.

Also, autonaming fuckups the function listing with radiff, this issue aims to define better commands and workflow for working multiple files, please share your thoughts here

**Comment by trufae** [comment]
Not anymore. thanks to SIOL(R) thanks @condret
