### ISSUE TITLE
Move into aae what I have done in disasm.c

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#6459]
The correct place to handle blx/bx switch instruction set should reside in `aae`.

**Comment by ninjahacker** [comment]
You should also check against the const ARM_INS_BX rather than fixed numbers.

**Comment by alvarofe** [comment]
I did that cause I had to include capstone and it was a workaround. The idea is making in better and be only in anal. It doesn't make any sense to be in disasm.c

**Comment by alvarofe** [comment]
Original issue https://github.com/radare/radare2-regressions/pull/657

**Comment by ninjahacker** [comment]
Aha! Cool. Thanks!

**Comment by alvarofe** [comment]
TODO: implement  afB (f->bits) as anal hint since is causing some issues and likely that will resolve the issue I am facing and will make it easier plus remove a few lines in disasm.c.

**Comment by alvarofe** [comment]
[FX]  7  arm_32: arm32 blx switches bits
[FX]  8  arm_32: arm32 bx switches bits on odd location

**Comment by alvarofe** [comment]
This has been fixed in master now. @ninjahacker if you wanna play with go ahead, if you just come across a binary where it fails let me know.

**Comment by ninjahacker** [comment]
Beautiful! It behaves exactly as expected now!
