### ISSUE TITLE
Show comments in hexdump

### ISSUE THREAD

**Issue by radare** [radare/radare2#6460]
* Add hex.comments variable
* px should print the comments entered with CC at right of each row
* Check all comments in range

**Comment by m1ghtym0** [comment]
Gonna do it, when I find the time, hopefully before February;-)

**Comment by radare** [comment]
Any update on that? :)

**Comment by m1ghtym0** [comment]
Couln't find the time to work on it yet, but hopefully there might be some this week

**Comment by radare** [comment]
awesome! well done!

**Comment by Maijin** [comment]
@m1ghtym0 Can you add tests ?

**Comment by m1ghtym0** [comment]
@pancake thanks:-)
@Maijin Sure, but give me some time, there are some other things I need to get done;-)
