### ISSUE TITLE
integer overflow in r_io_extend

### ISSUE THREAD

**Issue by condret** [radare/radare2#6464]
https://github.com/radare/radare2/blob/e20ac7a1395c13e409033b3b89354c563c25f258/libr/io/io.c#L618

this potential integer overflow can shrink files

**Comment by radare** [comment]
Can you provide a test case for the testsuite? the fix is just an if, would you like to send a pr?

**Comment by condret** [comment]
i'm not sure if we just want to return false if integer overflow got detected. We could eprintf something and only extend until UT64_MAX.

**Comment by radare** [comment]
yes, error is what i would expect, a simple fix would be to cast to st64 and check if its negative

**Comment by radare** [comment]
i dont think anybody is gonna resize a file in r2 to be > 63 bit in size

**Comment by radare** [comment]
tired of waiting, fixed in de2ae8ca0f24149d1c6aae6dc73cb38653ada060
