### ISSUE TITLE
Add support for Reloc Type 1 for ELF

### ISSUE THREAD

**Issue by radare** [radare/radare2#6466]
Sample file: http://lolcathost.org/b/libvulkan_radeon.so.xz

Problem:

* Imports wrongly resolved (see rabin2 -i output)
* PLT not resolved properly so many imports are dupped

Notes

* Seems like rabin2 -R is consistent with objdump -R
* This is the R_386_32 // R_X86_64_32 type

*"R_386_32 is a relocation that places the absolute 32-bit address of the symbol into the specified memory location. R_386_PC32 is a relocation that places the PC-relative 32-bit address of the symbol into the specified memory location. R_386_32 is useful for static data, as shown here, since the compiler just loads the relocated symbol address into some register and then treats it as a pointer. R_386_PC32 is useful for function references since it can be used as an immediate argument to call. See elf_machdep.c for an example of how the relocations are processed."*

**Comment by radare** [comment]
http://eli.thegreenplace.net/2011/08/25/load-time-relocation-of-shared-libraries/

**Comment by alvarofe** [comment]
iirc this was fixed by you @radare

**Comment by Maijin** [comment]
Yes https://github.com/radare/radare2/commit/326bb77cfe0a311c442226b1e711364304b65668
