### ISSUE TITLE
RFC: Remove r_asm_from_string function

### ISSUE THREAD

**Issue by Svenito** [radare/radare2#6471]
https://github.com/radare/radare2/compare/master...Svenito:remove-r_asm_from_string

It is not called anywhere and could be removed pending anyone objecting.

**Comment by radare** [comment]
I think it was done to ease the use of the native bindings. Keep it for now but add a comment with that info. We may probably want to define a high and low level apis for all modules

**Comment by Svenito** [comment]
Done via 4fe5d34
