### ISSUE TITLE
Rebrand rap, rtr, rmt into r2p

### ISSUE THREAD

**Issue by radare** [radare/radare2#6472]
We must decide to change the name of the radare remote protocol:

* Use r2p:// instead of rap:// ?
* all defines, functions, commands should refer to a single name

See r_io.h with RMT_*
See libr/core/rtr.c

I think having r2p.c makes more sense and its more intuitive than rap://

**Comment by XVilka** [comment]
I agree. It suits better.

**Comment by radare** [comment]
In fact we should do something to get r2pipe over rap.. and unify protocols or support them all in a transparent way. Autodetecting if its http, rap or whatever at connect time

**Comment by radare** [comment]
done in 
https://github.com/radare/radare2/pull/12699
