### ISSUE TITLE
Counting in hud selector goes to -1

### ISSUE THREAD

**Issue by l4l** [radare/radare2#6474]
that should be pretty easy
```bash
r2 -A /bin/ls
VV
_
<arrow-up>
```

![screenshot- - -10-13 58 35-msk-2017](https://cloud.githubusercontent.com/assets/5658339/21803830/50b7887e-d745-11e6-8e9d-238cd54a1e23.png)

**Comment by radare** [comment]
I can reproduce and its easy to fix. Do you want to do it? Btw this test can be onelinered like this:

r2 -cV_ /bin/ls

**Comment by radare** [comment]
tired of waiting

**Comment by l4l** [comment]
¯\_(ツ)_/¯
