### ISSUE TITLE
seek undo test completely broken ?

### ISSUE THREAD

**Issue by radare** [radare/radare2#6483]
@Maijin dont mark tests as broken that easily... when was this fuckedup?

<img width="983" alt="screen shot 2017-01-11 at 12 30 16" src="https://cloud.githubusercontent.com/assets/917142/21846967/c9aafacc-d7f9-11e6-9761-24bbf9d5eb67.png">

**Comment by Maijin** [comment]
I don't think put BR on this

**Comment by Maijin** [comment]
no need issue for this
