### ISSUE TITLE
[PPC] asm.emu & asm.pseudo doesn't work correctly

### ISSUE THREAD

**Issue by wargio** [radare/radare2#6486]
Hi,

i'm using radare2 to analize a ppc64 elf and the emu/pseudo options seems broken to me.
`e asm.emu=1`

```
0x00000c40      3c200bff       lis r1, 0xbff               ; r1=0xbff -> 0x803800 
0x00000c44      6021ff80       ori r1, r1, 0xff80          ; r1=0xffff 
; NO r1 = 0xbff0000 + 0xff80
0x00000c48      3c40080c       lis r2, 0x80c               ; r2=0x80c 
0x00000c4c      6042dde0       ori r2, r2, 0xdde0          ; r2=0xddec -> 0xee420600 
; NO r2 = 0x80c0000 + 0xdde0
0x00000c50      3c600800       lis r3, 0x800               ; r3=0x800 "H" 
0x00000c54      60630000       ori r3, r3, 0               ; r3=0x800 "H" 
; NO r3 = 0x80c0000 + 0x0
```
and for pseudo
`e asm.pseudo=1`

```
 0x00000c40      3c200bff       r1 = 0xbff                  ; r1=0xbff -> 0x803800
 0x00000c44      6021ff80       r1 |= 0xff80                ; r1=0xffff
 0x00000c48      3c40080c       r2 = 0x80c                  ; r2=0x80c
 0x00000c4c      6042dde0       r2 |= 0xdde0                ; r2=0xddec -> 0xee420600
 0x00000c50      3c600800       r3 = 0x800                  ; r3=0x800 "H"
 0x00000c54      60630000       r3 |= 0                     ; r3=0x800 "H"
```
especially wrong when a
```
0x00000c28      7c832050       subf r4, r3, r4
```
is translated as 
```
7c832050       r4 = r3 + r4
```

About radare:
radare2 1.2.0-git 13695 @ windows-x86-32 git.1.1.0-172-ge23c17346
commit: e23c173460b25a6ff51ff474ace12144a595fb55 build: 2017-01-10

**Comment by radare** [comment]
there’s no pseudo plugin for powerpc, so it’s using the x86 one which is pretty different. Do you wanna write it? Just copypaste the mips one (because it handles 3 parameter instructions) and add the list of instructions for ppc64? see libr/parse/p/*

**Comment by radare** [comment]
also, pseudo is not done via emulation. you may want to implement the ESIL expressions for PPC64 too. You can use asm.esil=true to see that (or just toggle that variable in visual mode by pressing the ‘O’ key (uppercase o)

**Comment by wargio** [comment]
do i have to rebuild radare2 to add the ESIL expressions ?

**Comment by radare** [comment]
just type make in libr/anal no need to reinstall or rebuild everything. the esil expressions must be in the libr/anal/p/anal_ppc_cs.c plugin

**Comment by wargio** [comment]
I tried to edit the anal_ppc_cs.c but i don't understand why it doesn't show any changes, even if i point to the rbin/radare2 binary to do the test.

i even added `.esil=true` to the structure at the very end of the file.

Is there something else i need to edit?

**Comment by radare** [comment]
did you installed r2 with sys/install.sh ?

**Comment by wargio** [comment]
doh, nope.
`[sudo] make install`

ok. my mistake, i'll try.

**Comment by wargio** [comment]
How do i evaluate the expression `(a << lsh) | (a >> rsh)` in ESIL?
this is what i came up with, `??` are placeholder for the missing part of the expression
```a,lsh,<<,??,a,rsh,>>,??,|,r0,=```

**Comment by radare** [comment]
Use ae to evaluate expressions and see if they work as expected. Use " quotes around the command like this:

"ae a,lsh,<<,??,a,rsh,>>,??,|,r0,="
