### ISSUE TITLE
ARM R2 and R3 linked to CPSR weirdly

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#6487]
This should not happen:

[0x00000000]> ar
sb = 0x00000000
sl = 0x00000000
fp = 0x00000000
ip = 0x00000000
sp = 0x00000000
lr = 0x00000000
pc = 0x00000000
r0 = 0x00000000
r1 = 0x00000000
r2 = 0x00000000
r3 = 0x00000000
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00000000
r12 = 0x00000000
r13 = 0x00000000
r14 = 0x00000000
r15 = 0x00000000
r16 = 0x00000000
r17 = 0x00000000
cpsr = 0x00000000

[0x00000000]> ar r2=0xffffffff
[0x00000000]> ar 
sb = 0x00000000
sl = 0x00000000
fp = 0x00000000
ip = 0x00000000
sp = 0x00000000
lr = 0x00000000
pc = 0x00000000
r0 = 0x00000000
r1 = 0x00000000
r2 = 0xffffffff
r3 = 0x00000000
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00000000
r12 = 0x00000000
r13 = 0x00000000
r14 = 0x00000000
r15 = 0x00000000
r16 = 0x00000000
r17 = 0x00000000
cpsr = 0x00ffffff

[0x00000000]> ar
sb = 0x00000000
sl = 0x00000000
fp = 0x00000000
ip = 0x00000000
sp = 0x00000000
lr = 0x00000000
pc = 0x00000000
r0 = 0x00000000
r1 = 0x00000000
r2 = 0xffffffff
r3 = 0xaaaaaaaa
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00000000
r12 = 0x00000000
r13 = 0x00000000
r14 = 0x00000000
r15 = 0x00000000
r16 = 0x00000000
r17 = 0x00000000
cpsr = 0xaaffffff

[0x00000000]> ar cpsr=0xbbbbbbbb
[0x00000000]> ar
sb = 0x00000000
sl = 0x00000000
fp = 0x00000000
ip = 0x00000000
sp = 0x00000000
lr = 0x00000000
pc = 0x00000000
r0 = 0x00000000
r1 = 0x00000000
r2 = 0xbbbbbbff
r3 = 0xaaaaaabb
r4 = 0x00000000
r5 = 0x00000000
r6 = 0x00000000
r7 = 0x00000000
r8 = 0x00000000
r9 = 0x00000000
r10 = 0x00000000
r11 = 0x00000000
r12 = 0x00000000
r13 = 0x00000000
r14 = 0x00000000
r15 = 0x00000000
r16 = 0x00000000
r17 = 0x00000000
cpsr = 0xbbbbbbbb

It took some time tracking this error down in my regressions since I was simply setting registers. I falsely assumed my registers were correct.

**Comment by alvarofe** [comment]
You are having fun with arm :)

**Comment by Maijin** [comment]
use `ar register` and code style :P it will look much nicer and concise

**Comment by radare** [comment]
wtf could be a bug in the last changes in r_reg, pretty scary

**Comment by Maijin** [comment]
Even better `| ard <name>      Show only different registers`

**Comment by radare** [comment]
Should be fixed now. the regprofile was wrongly defined. see 50e6c1d4283615d9c233a615ffbeae29b82ec83f the bits definition of the cpsr is wrong. you can check how its done for x86, and will be good if you can add the 1bit registers to represent those state register.
This is in libr/anal/p/*.c and libr/debug/p/* (the register profiles may be found in analysis and debugger plugins)

**Comment by radare** [comment]
Fixed, requires updated regprofiles with correct bit definitions

**Comment by ninjahacker** [comment]
@alvarofe Yes! About a year ago I was planning on really sitting down and improving ARM since that's all I worked on and r2 was severely lacking compared to x86. Then I changed jobs and whatnot and lost a lot of the time I was going to use. I'm just now getting around to it again.
