### ISSUE TITLE
Use of linux_dbg_wait() breaks builds on other unices such as the BSDs

### ISSUE THREAD

**Issue by sevan** [radare/radare2#6493]
As the function name suggests, `linux_dbg_wait()` is for Linux.
Its use in [debug/p/debug_native.c](https://github.com/radare/radare2/blob/dc5be7a7678ae317d2e0c3b487181da75a3a30a0/libr/debug/p/debug_native.c#L360) breaks the build on operating systems such as the BSDs

`radare2-master/libr/debug/libr_debug.so: undefined reference to `linux_dbg_wait'`

As a test, when the line which this function is called on, radare builds successfully.

**Comment by leberus** [comment]
I'll fix it. Would be a matter of put an elif __linux__ for this function. I'll get my laptop in 30min

**Comment by leberus** [comment]
Hi @sevan 

could you try to compile this branch?

**Comment by sevan** [comment]
Thanks @leberus, that did the trick.

**Comment by leberus** [comment]
@sevan thanks for testing it, I've done a PR ;)
