### ISSUE TITLE
Rebasing the session

### ISSUE THREAD

**Issue by radare** [radare/radare2#6495]
We can change the baddr at startup time.. but this is not possible in the middle of a running session. we can use fR to relocate the flags, but this will not change the bininfo, analysis, meta, ...

I think that we should have a command to perform this action, and test it properly, also we should be able to rebase only the metadata from a specific range in memory, if we have more files opened we dont want to relocate everything.

**Comment by kazarmy** [comment]
How does wrongly-based metadata get into the session in the first place?

**Comment by radare** [comment]
?

**Comment by kazarmy** [comment]
Um ... what are the possible reasons to rebase metadata?

**Comment by radare** [comment]
Aslr?

**Comment by kazarmy** [comment]
ah ok

**Comment by saruman9** [comment]
In my case `fR` didn't work. Binary file - firmware for intel x86 16bit.
Before relocating:
```
[3000:36fc]> f
0x000336fc 9 str.MainTask
....
[3000:36fc]> pd 1                                       
            ;-- str.MainTask:                           
            3000:36fc     .string "MainTask" ; len=9
```
Relocating:
```
[3000:36fc]> fR 0x3000:0x36fc 0x3000:0x4000
Relocated 15 flags                         
[3000:36fc]> f
0x000376fc 9 str.MainTask
...
```
But it didn't relocate:
```
[3000:36fc]> pd 1
            ;-- str.MainTask:
            3000:36fc     .string "MainTask" ; len=9
```
radare2 1.7.0-git 16164 @ linux-x86-64 git.1.6.0-940-gcd44fb483
commit: cd44fb4839885a9326af0a2ec7081056c8f235ab build: 2017-09-26__16:07:4

**Comment by radare** [comment]
Continue worjing in https://github.com/radare/radare2/issues/13753
