### ISSUE TITLE
ESIL Math Error

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#6498]
I don't think this is deliberate.

"ae 0xfffffffe,0x00000008,+"
0x100000006

Should just be 6?

**Comment by radare** [comment]
why? you are not moving this into any register or size boundary. esil is 64bit friendly

**Comment by ninjahacker** [comment]
Sorry no issue. I was stuck in 32-bit mode and thought it was truncated to 4 bytes. We're good.
