### ISSUE TITLE
Web frontends does not work

### ISSUE THREAD

**Issue by smarek** [radare/radare2#6499]
`ERROR:process_posix.cc ...` comes from Google Chrome, I use as default browser

however `http: cannot open ...` is unknown to me, folders exist, `r2pm update; r2pm -i www-t` has ran successfully. Also no change when I try `www-p, www-m or www-enyo`

I've tried, and error appears if I install in both user and system-wide installation, I've also tried completely clearing `.config/radare2`, that did not help

Also `Cant disable sandbox` does not disappear if I add `-S` (run in sandbox mode) param to `r2`

I'm using up-to-date, commit 1ece64abdcc4f42906251dc2a4e48bac85458833 on master branch

```
> r2 -c=H -e http.ui=t binary
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/
Cant disable sandbox
[20316:20316:0112/183442.600091:ERROR:process_posix.cc(192)] Not implemented reached in bool (anonymous namespace)::WaitForExitWithTimeoutImpl(base::ProcessHandle, int *, base::TimeDelta)
Created new window in existing browser session.
[HTTP] 127.0.0.1:47452 /t
Cant disable sandbox
[HTTP] 127.0.0.1:47456 /t/
http: Cannot open '/home/user/.config/radare2/www//t/index.html'
Cant disable sandbox
```

**Comment by smarek** [comment]
Ok, so removing radare2 repository, checking out again the whole thing and reinstalling, fixed the issue, but i'd be damned, if I knew what is going on. Closing as user-trouble/wontfix

**Comment by smarek** [comment]
Ok, more poking around, problem is that `r2pm` installed `www-t` conflicts with builtin one, so, if there is `~/.config/radare2/www` available and frontend is within, on launch it will fail with `http: Cannot open /home/user/.config/radare2/www//t/index.html`

So quick fix is to **remove ~/.config/radare2/www** and things will start working instantly

**Comment by radare** [comment]
Please re-try

**Comment by radare** [comment]
it was fixed some days ago to allow the http.sandbox access your home www directory
