### ISSUE TITLE
Add blank line after every basic block

### ISSUE THREAD

**Issue by radare** [radare/radare2#650]
This option is available in IDA and enhaces readability. `e asm.bbline` ?
Also, we can add a `;---` line after every ret?

**Comment by jvoisin** [comment]
I would prefer `e asm.bbsep`, because lines could be confused with something graph-related, or jumps-arrows.

**Comment by radare** [comment]
Try also asm.lines.ret

Maybe we should rename bbsep into asm.lines.bb

**Comment by radare** [comment]
nevermind bbsep have nothing in common with asm.lines stuff

**Comment by radare** [comment]
what about `e asm.blankblock` ?
