### ISSUE TITLE
Export local vars as flags

### ISSUE THREAD

**Issue by radare** [radare/radare2#6501]
So they can be displayed in pxa, pxr, etc

Those flags should have a prefix to make clear that are variables and can be removed safely.

Something like:
```
> afv*
f-fcnvar.*
f fcnvar.foo = rbp+0x30
...
```

**Comment by condret** [comment]
This should be configureable. As long as you don't look for uninitialized vars, I see no scenario where this could be useful

**Comment by radare** [comment]
Not configurable. Flags will be displayed in pxa and pxr so you can see the layout in the stack and their boundaries and merge them easily to identify arrays and such. It is useful in many situations imho

**Comment by condret** [comment]
ah, so they don't spam the casual px

**Comment by radare** [comment]
@oddcoder can you add support for SP vars and ignore the reg ones here? also adding tests will be helpful. will be cool to have some automatic analysis integrated into the debugger

**Comment by radare** [comment]
so we dont have to import/export flags everytime we enter a function, etc
