### ISSUE TITLE
[OS X] Command line arguments order

### ISSUE THREAD

**Issue by guedou** [radare/radare2#6502]
On OS X, arguments are not processed when they appear after the main parameter.

In the following example, the `-B` argument is not processed correctly.

```shell
osx$ rasm2 -a mips "J 0x2807" -B |grep 010
010a0008
```

```shell
linux$ rasm2 -a mips "J 0x2807" -B |grep 010
```

The r2 command as the same issue:
```shell
osx$ r2 -a mips /bin/ls -qc "pd 1"
Cannot open 'pd 1'
```

**Comment by radare** [comment]
no its not about osx. this is about posix or not.

BSD getopt vs GNU getopt

getopt vs getopt_long

etc

im not gonna allow r2 accept flags after the file names, basically because it will break things like r2 -d ls -l / and be able to load multiple files in a single line, etc

long live posix

**Comment by guedou** [comment]
Thanks for your reply =)

**Comment by radare** [comment]
You are welcome :)
