### ISSUE TITLE
Use qAPI for emulation instead of unicorn

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#6503]
The full QAPI is describer [here](https://elmarco.fedorapeople.org/qemu-qapi.pdf)
It would be cool to have direct qemu support

**Comment by condret** [comment]
i think we should use both

**Comment by XVilka** [comment]
Yes, 2 different plugins. I think you need to move that issue in radare2-extras.

**Comment by radare** [comment]
Extras is fine for me
