### ISSUE TITLE
Flag labels sometimes show duplicated while disassembing around Cd data

### ISSUE THREAD

**Issue by laanwj** [radare/radare2#6506]
This tends to happen when the label is precisely after memory areas defined as hexdump with `Cd`. Some examples:

![untitled1](https://cloud.githubusercontent.com/assets/126646/21962286/8bdcf48a-db22-11e6-9222-c35fbd61ae33.png)
![untitled2](https://cloud.githubusercontent.com/assets/126646/21962287/8bf2ba0e-db22-11e6-943c-01ffe724f97a.png)

Either label only shows once in the `f` listing, at the address it shows the second time (0x1c52, 0x15f0), so it seems to me that the problem is visual only.

I haven't found out exactly why this happens yet (code is git as of 0d78c57).

**Comment by radare** [comment]
please try again with master just to confirm its not gone after the sdb update and 

this can be also an issue with the .word thing that was not previously done

can you write a test case? im trying to reproduce it without much success

**Comment by laanwj** [comment]
Verified that it still happens with git 6ef1722.

> this can be also an issue with the .word thing that was not previously done

It's a very neat feature I must say when reverse-engineering assembly code with data intermixed. Apart from this it works great and this is only a very minor issue.

> can you write a test case? im trying to reproduce it without much success

Done. Curiously it seems related to m68k, or at least depend on the architectur.

Generate test file and launch radare on it:
```
echo 600c5b242450415254981048945d4cdf | xxd -r -p > /tmp/test1
$ radare2 /tmp/test1
```

Reproduction:
```
e asm.arch=m68k
Cd 2 8 @ 0
f _delta 1 @ 8
pd 8 @ 0
            0x00000000 .word 0x0c60
            0x00000002 .word 0x245b
            0x00000004 .word 0x5024
            ;-- _delta:
            0x00000006 .word 0x5241
            ;-- _delta:
            0x00000008 .word 0x9854
            0x0000000a .word 0x4810
            0x0000000c .word 0x5d94
            0x0000000e .word 0xdf4c
```

Non-reproduction:
```
e asm.arch=x86
Cd 2 8 @ 0
f _delta 1 @ 8
pd 8 @ 0
            0x00000000 .word 0x0c60
            0x00000002 .word 0x245b
            0x00000004 .word 0x5024
            0x00000006 .word 0x5241
            ;-- _delta:
            0x00000008 .word 0x9854
            0x0000000a .word 0x4810
            0x0000000c .word 0x5d94
            0x0000000e .word 0xdf4c
```

Curiously, it looks like the content of the test file matters. The following one will be OK on both x86 and m68k:

```
$ echo 80454c46020101000000000000000000 | xxd -r -p > /tmp/test2
```

**Comment by radare** [comment]
I managed to reproduce it with this oneliner:

```
$ r2 -qa m68k -c "Cd 2 2 @ 4" -c 'wx 600c5b242450415254981048945d4cdf' -c "f _delta 1 @ 8" -c "pd 8" -
```

but not with yours

**Comment by radare** [comment]
cc @alvarofe maybe its related to your wip fix?

**Comment by radare** [comment]
@Maijin pls add this test

**Comment by alvarofe** [comment]
@Maijin did you add test for this?

**Comment by laanwj** [comment]
I've tried it out, and indeed it seems to be fixed. Thanks!
