### ISSUE TITLE
Add .incbin directive in rasm2

### ISSUE THREAD

**Issue by radare** [radare/radare2#6512]
Ref http://www.codersnotes.com/notes/the-joy-of-incbin/

**Comment by Svenito** [comment]
Definition: http://tigcc.ticalc.org/doc/gnuasm.html#SEC97B

**Comment by Svenito** [comment]
Started on this but having issues with inserting the bin data into the output data due to it being fixed size. This will probably require a refactor to use Rbuf instead of an array throughout.

**Comment by radare** [comment]
Move for 1.4 or 5

**Comment by radare** [comment]
ping

**Comment by Svenito** [comment]
Apologies. Still not made much progress on this.

**Comment by radare** [comment]
np thats why i moved it to 1.6 :) its ok

**Comment by radare** [comment]
ping

**Comment by Svenito** [comment]
Still not made much progress on this

**Comment by radare** [comment]
ok for 2.2?

**Comment by Svenito** [comment]
can we push to next release perhaps?

**Comment by radare** [comment]
Yep. Already done

**Comment by radare** [comment]
moved to 2.5, 3 months away
