### ISSUE TITLE
Fix memleak introduced in PDB

### ISSUE THREAD

**Issue by radare** [radare/radare2#6513]
introduced in 75dd4536fa3980041b22cf9da2863f0c0bbe2142

this requires some refactoring and code cleanup of the PDB parser.

**Comment by nartes** [comment]
I've compiled radare2 at two major versions 1.1.0 and 1.7.0.
Here is a [valgrind-log](https://gist.github.com/anonymous/c0573c4a892fd5a604b191e3529b94be) -
seems some memory is floating).
The current issue addresses memory leak introduced by the commit 75dd4536fa3980041b22cf9da2863f0c0bbe2142.
I didn't find any closer lower bound commit to the possibly introducing the issue. Cause there was no logs on travis that long ago. The directly preceeding one - 75dd4536fa3980041b22cf9da2863f0c0bbe2142~ - fails to build.

E.g., the log shows
```
@@ -69,14 +71,14 @@
  Command: ./install/bin/rabin2 -Pj tmp/dsadsd.pdb
  
  HEAP SUMMARY:
-     in use at exit: 769,579 bytes in 285 blocks
-   total heap usage: 83,744 allocs, 83,459 frees, 43,120,022 bytes allocated
+     in use at exit: 2,607,974 bytes in 28,200 blocks
+   total heap usage: 61,476 allocs, 33,276 frees, 43,051,387 bytes allocated
  
  LEAK SUMMARY:
-    definitely lost: 96 bytes in 2 blocks
-    indirectly lost: 32 bytes in 1 blocks
+    definitely lost: 4,332 bytes in 73 blocks
+    indirectly lost: 15,081 bytes in 487 blocks
       possibly lost: 494,593 bytes in 1 blocks
-    still reachable: 274,858 bytes in 281 blocks
+    still reachable: 2,093,968 bytes in 27,639 blocks
          suppressed: 0 bytes in 0 blocks
Rerun with --leak-check=full to see details of leaked memory
```

**Comment by nartes** [comment]
Here's asan [memory leak analyzer's](https://gist.github.com/anonymous/a2d1b027f9072d03668d776516269bf2) output.

**Comment by Maijin** [comment]
What about fixing now ?

**Comment by nartes** [comment]
@Maijin there's been a commit regarding the pdb parsers code.
```
# somewhere here
git log libr/bin/pdb
```

It says we should not define complex free procedures for the data.
E.g. just free tpi_stream instead of calling tpi_stream->_free() beforehand.
It makes memory leaks. What way to fix it?

These are few changes I've made.
https://gist.github.com/anonymous/ef7d80b6fcb8004c497d7f121d03bbbc

Here's the output from valgrind. The log displays memory leaks along the increase of repetitions.
They are 5, 10 and 20 times correspondingly.
https://gist.github.com/a0d24fd59b4f9cce049861f1f4b5fba1

There are also some leaks inside the sdb engine, need to investigate.

**Comment by Maijin** [comment]
Here is the repo https://github.com/radare/sdb

**Comment by Maijin** [comment]
@radare may give you pointer for the tpi_stream free.

**Comment by Maijin** [comment]
And do a Pull request please instead of diff log

**Comment by nartes** [comment]
@radare what way to fix this? https://github.com/radare/radare2/pull/8692/commits/4f352ad49bf60d91497e44cd788911f8ca7fc70d?diff=unified#diff-76b5f8c16e075736541d91e9aaa134ffL562

**Comment by nartes** [comment]
There's a possible issues with r_bin_reload:
```
	// TODO(nartes):  the_obj_list might be leaked along the way.
	// r_list_free (the_obj_list) is to be called after several
	// error handling if-statements. It might be fixed!
	// The following command:
	// ```
	//   dd if=/dev/urandom of=tmp/test_128Mb.blob\
	//       bs=512 count=$((2 * 1024 //   * 128))
	//   valgrind radare2 --show-leak-kinds=all --leak-check=full\
	//       -qc "o tmp/test_128Mb.blob; 2000ib" -- > /dev/null 2>&1
	// ```
	// makes bf->objs to have a non-zero length list,
	// but amount of leaked memory for 2000 tries is about 64Kb,
	// may be it's a feature and not a leak :)
```

**Comment by Maijin** [comment]
The rest of the optimization seems like to be r_bin refactoring, closing here
