### ISSUE TITLE
Remove libr/util/ht.c 

### ISSUE THREAD

**Issue by radare** [radare/radare2#6518]
And use sdb's ht. here's the list of points where the old ht is used:

* libr/anal/fcnstore.c:
* libr/flag/flag.c
* libr/config/config.c
* libr/util/mixed.c
* libr/util/strht.c
* libr/asm/arch/tms320/tms320_dasm320.c

grep for `r_hashtable*` and `ht(` / `ht64(`

**Comment by alvarofe** [comment]
I did some changes in sdb to make this easier. However I will start once @radare bump sdb and make the release cause I assume there will be issues along the way. I lost time today fixing a damn oob read :(

**Comment by radare** [comment]
soon(R)

**Comment by alvarofe** [comment]
Which was the aim of libr/util/mixed.c? is not used anywhere, safe to remove?

**Comment by radare** [comment]
i dont think its used, but it was a cool way to use hashtables and structures to index all fields of a struct in different hashtables, and be able to query them by field. it is a mix between sdb, sdb struct serialization and r_db.. that nobody ever cared about :P i would like not to loose that, but i assume it must be killed from master. so maybe move to extras/Attic ?

**Comment by alvarofe** [comment]
This can be tracked in here https://github.com/alvarofe/radare2/tree/ht, facing some build issues right now that I need to figure out how to fix them.

**Comment by alvarofe** [comment]
I am about to remove `strht.c` it can be seen at the beginning of the file the following.

```
// XXX deprecate and just use Sdb here
// strpool is more optimal than how sdb stores the strings...
// but DUPE!
```

In case someone raises a complaint about this.

**Comment by radare** [comment]
Would be cool to compare times once its green

**Comment by alvarofe** [comment]
I would say is already green but I need to find/fix two crashes I got yesterday running the test suite with ASAN. The odds are high that those crashes are as well in master. Dunno if we have some kind of benchmark to test such things

**Comment by radare** [comment]
Travis will work aproximately. Testing the overall gain is difficult, any specific part that matters? Maybe flag handling and pd?

**Comment by alvarofe** [comment]
So far I would say the times are the same, but after I fix some stuff will run locally and compare.

**Comment by alvarofe** [comment]
this has been merged and I think is done, @Maijin told me to look at r2-extras, that I will do with time other things in hand but in case of brokenness point it out to me.

**Comment by Maijin** [comment]
travis will break I will point you.
