### ISSUE TITLE
Flags are not applied to all jumps

### ISSUE THREAD

**Issue by Svenito** [radare/radare2#6520]
Added a flag to the jump target @ 0x080481aa with `f`. Label is added to the first jump @ 0x080480c5 but not to the one @ 0x080480cf - see screenshot.

Binary attached

![screenshot_2017-01-16_21-28-42](https://cloud.githubusercontent.com/assets/31278/21999658/2182d9f8-dc33-11e6-9de4-e6a543881eb0.png)

[keygenme.zip](https://github.com/radare/radare2/files/709431/keygenme.zip)

**Comment by radare** [comment]
only flags with a dot in the name are replaced

**Comment by Svenito** [comment]
ah yes, can confirm this is the case, thanks
