### ISSUE TITLE
rabin2 RPATH

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6522]
morrn,

removing a non-existing RPATH:

,bash checksec.sh --file /tmp/bash 
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH      FILE
Partial RELRO   Canary found      NX enabled    No PIE          No RPATH   No RUNPATH   /tmp/bash

```
,gdb -q rabin2 core
Tue Jan 17 11:59:09 CET 2017
Reading symbols from rabin2...done.
[New LWP 3471]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `rabin2 -O R -e -d -I -R /tmp/bash'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f737a254e89 in Elf32_r_bin_elf_del_rpath (bin=0x563e561cc990) at /home/sk/radare2/libr/..//libr/bin/p/../format/elf/elf_write.c:180
180                     if (bin->phdr[i].p_type == PT_DYNAMIC) {
(gdb) bt
#0  0x00007f737a254e89 in Elf32_r_bin_elf_del_rpath (bin=0x563e561cc990) at /home/sk/radare2/libr/..//libr/bin/p/../format/elf/elf_write.c:180
#1  0x00007f737a247aa7 in rpath_del (arch=0x563e55fc3220) at /home/sk/radare2/libr/..//libr/bin/p/bin_write_elf.c:27
#2  0x00007f737a222e46 in r_bin_wr_rpath_del (bin=0x563e55e52660) at bin_write.c:30
#3  0x0000563e55a0f44e in rabin_do_operation (op=0x7ffc1a1f7cc9 "R") at rabin2.c:423
#4  0x0000563e55a1238d in main (argc=8, argv=0x7ffc1a1f6228) at rabin2.c:1084
(gdb) l
175             Elf_(Dyn) *dyn = NULL;
176             ut64 stroff = 0LL;
177             int ndyn, i, j;
178
179             for (i = 0; i < bin->ehdr.e_phnum; i++)
180                     if (bin->phdr[i].p_type == PT_DYNAMIC) {
181                             if (!(dyn = malloc (1+bin->phdr[i].p_filesz))) {
182                                     perror ("malloc (dyn)");
183                                     return false;
184                             }

```

Greetings
--zlul

**Comment by zonkzonk** [comment]
fb31d8e64cec2d9d894ad94a0db96e46cb115338

**Comment by zonkzonk** [comment]
@pancake

,git diff -r fb31d8e64cec2d9d894ad94a0db96e46cb115338
diff --git a/binr/rabin2/rabin2.c b/binr/rabin2/rabin2.c
index 8102d8f..078aa0d 100644
--- a/binr/rabin2/rabin2.c
+++ b/binr/rabin2/rabin2.c
@@ -420,6 +420,7 @@ static int rabin_do_operation(const char *op) {
                }
                break;
        case 'R':
+                if (bin)
                r_bin_wr_rpath_del (bin);
                rc = r_bin_wr_output (bin, output);
                break;

**Comment by radare** [comment]
r_bin_wr_rpath_del should already check for null

**Comment by radare** [comment]
why dont u ever use `print` in gdb?you should print the values of the affected variables in the line that crashes..otherwise its useless

**Comment by radare** [comment]
rpath_del already checks for null, so this is not the issue.

**Comment by radare** [comment]
(and your backtrace) clearly shows that bin is not null. you can use valgrind to see better info here

**Comment by zonkzonk** [comment]
@radare rabin2 -O R -e -d -I -R /tmp/bash
so without RPATH, trying to remove it, fails.
(if bin) was added by me :)

**Comment by zonkzonk** [comment]
@radare reproduced with zzuf:

```
,r2 -v &&  zzuf -dd  -s 0:1000000 -r 0.06  -q -c -C 1 -v  -T 5 -M 100 rabin2 -O R -e -d -I -R /tmp/bash
radare2 1.2.0-git 13524 @ linux-x86-64 git.1.1.0-230-gfb31d8e
commit: fb31d8e64cec2d9d894ad94a0db96e46cb115338 build: 2017-01-18
zzuf[s=0,r=0.06]: launched `rabin2'
** zzuf debug ** calloc(1, 32) = 0x7fd03a9a8be8
** zzuf debug ** libzzuf initialised for PID 14030
** zzuf debug ** open("/tmp/bash", 0) = 3
** zzuf debug ** open("/tmp/bash", 0) = 4
** zzuf debug ** lseek(4, 0, 2) = 1037464
** zzuf debug ** ... fuzz(4, @0, 1037464)
** zzuf debug ** mmap(NULL, 1037464, 1, 1, 4, 0) = 0x7fd03572a000 "\x7fELF...
** zzuf debug ** open("/tmp/bash", 0) = 5
** zzuf debug ** lseek(5, 0, 2) = 1037464
** zzuf debug ** ... fuzz(5, @0, 1037464)
** zzuf debug ** mmap(NULL, 1037464, 1, 1, 5, 0) = 0x7fd03552e000 "\x7fELF...
** zzuf debug ** close(5) = 0
** zzuf debug ** ... fuzz(5, @0, 0)
** zzuf debug ** ... after: stream([5], NULL, 0 + 0)
** zzuf debug ** fopen("/tmp/bash", "rb") = [5]
** zzuf debug ** ... before: stream([5], NULL, 0 + 0)
** zzuf debug ** ... fuzz(5, @0, 0)
** zzuf debug ** ... after: stream([5], 0x7fd03ac75000, 0 + 0)
** zzuf debug ** fseek([5], 0, SEEK_SET) = 0
** zzuf debug ** ... before: stream([5], 0x7fd03ac75000, 0 + 0)
** zzuf debug ** ... fuzz(5, @0, 4)
** zzuf debug ** ... fuzz(5, @0, 4096)
** zzuf debug ** ... after: stream([5], 0x7fd03ac75004, 4 + 4092)
** zzuf debug ** fread(0x55aa7ca21070, 1, 4, [5]) = 4 "\x7fELF...
** zzuf debug ** ... before: stream([5], 0x7fd03ac75004, 4 + 4092)
** zzuf debug ** fclose([5]) = 0
zzuf[s=0,r=0.06]: signal 11 (SIGSEGV)
zzuf: maximum crash count reached, exiting
```

**Comment by radare** [comment]
doing -OR -edIR will ignore -O and not remove the rpath , this seems like a bug to me, but anyway

if i do -OR only this warning appears:

==14344== Conditional jump or move depends on uninitialised value(s)
==14344==    at 0x10004A7B9: r_core_cmd (cmd.c:2570)
==14344==    by 0x1000437FB: r_core_cmdf (cmd.c:2773)
==14344==    by 0x1000EA62F: bin_sections (cbin.c:1909)
==14344==    by 0x1000E7529: r_core_bin_info (cbin.c:2676)
==14344==    by 0x1000E730C: r_core_bin_set_env (cbin.c:108)
==14344==    by 0x1000ED933: r_core_bin_set_arch_bits (cbin.c:2714)
==14344==    by 0x1000EDA66: r_core_bin_update_arch_bits (cbin.c:2735)
==14344==    by 0x100002B5B: main (in /usr/local/bin/rabin2)
==14344==

which is unrealted to your issue :??

**Comment by radare** [comment]
i fixed those warnings.. canyou please paste the output of valgrind in your machine?

**Comment by zonkzonk** [comment]
ok, can't use valgrind on this machine. (broken) can someone else please test?
still in 6b46a63bcd0a0d2e6b384e3b2240b4238b3dc2dd

**Comment by zonkzonk** [comment]
sorry I totally fucked this up, here is valgrind.txt as png:
![valgrind.txt](https://cloud.githubusercontent.com/assets/5694980/22072650/ef76a6e2-dd9a-11e6-82ff-eec78be4e464.png)

**Comment by radare** [comment]
your valgirnd log shows pretty fuckedup things. are you sure you are using a clean build of r2?

**Comment by radare** [comment]
the crash you are experimenting is because there are some previous overflows on global variables with const strings, i cant think of any bug except a fuckedup build

**Comment by zonkzonk** [comment]
still in 02a858ccd53341294d28751f29c7de11dcb503c1

zzuf   -s 0:1000000 -r 0.06 -q  -C 1  rabin2 -O R  /tmp/bash
zzuf[s=0,r=0.06]: signal 11 (SIGSEGV)

**Comment by zonkzonk** [comment]
@pancake new valgrind for 02a858ccd53341294d28751f29c7de11dcb503c1: 

![meh](https://cloud.githubusercontent.com/assets/5694980/22177356/a34fbe68-e013-11e6-9348-1a29d5ca05b2.png)

**Comment by radare** [comment]
pls try again and let me know if its fixed now

**Comment by zonkzonk** [comment]
can't reproduce. :)
