### ISSUE TITLE
Remove requirement of the space before the operator '>' after the command

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#6524]
It just creates zero-size file, but do not perform redirection.
```
[0x000000]>ii>file
```
`ii >file` works OK.

**Comment by radare** [comment]
why

**Comment by XVilka** [comment]
@radare why what?

**Comment by radare** [comment]
why do you want to impose this restriction?

**Comment by XVilka** [comment]
@radare sorry, worded it inaccurately. I want to _remove_ it, not to impose it, since it's already in place.

**Comment by radare** [comment]
there’s no such thing pls provide an example.. also bear in mind that a number before  > is considered a fd, like in the shell. so the same restriction goes for posix sh
