### ISSUE TITLE
Unintuitive detection of strings with non-ascii syms

### ISSUE THREAD

**Issue by l4l** [radare/radare2#6537]
```bash
$ cat >a.c <<EOF
int main() {
    puts("\x01\x02\x03\x04""abcd");
}
EOF
$ gcc a.c
$ r2 -A a.out
[0x00400400]> pdf @ sym.main 
            ;-- main:
┌ (fcn) sym.main 21
│   sym.main ();
│              ; DATA XREF from 0x0040041d (entry0)
│           0x004004f6      55             push rbp
│           0x004004f7      4889e5         mov rbp, rsp
│           0x004004fa      bf94054000     mov edi, 0x400594
│           0x004004ff      e8ecfeffff     call sym.imp.puts          ; int puts(const char *s)
│           0x00400504      b800000000     mov eax, 0
│           0x00400509      5d             pop rbp
└           0x0040050a      c3             ret
[0x00400400]> izz | grep abcd
vaddr=0x00400598 paddr=0x00000598 ordinal=015 sz=5 len=4 section=.rodata type=ascii string=abcd
```
puts @ 0x400594
r2' str @ 0x400598

**Comment by radare** [comment]
thats expected, r2 strings are extracted by analyzing the data section, not the code.

there’s other code to find strings from code that will find that \x01.. thing

**Comment by Maijin** [comment]
ps @ 0x100000fa6 
At this point, I think we can close because supporting other characters in the anal comments may be very difficult which one and which not to have is a full debates, having printables makes sense, \x03 not really ...

**Comment by Maijin** [comment]
Also see with emu and emuwrite ;)

![image](https://cloud.githubusercontent.com/assets/1408600/23827080/b11b2064-06ab-11e7-9497-d64491c4f1ca.png)
