### ISSUE TITLE
Obey user theme colors in canal.c

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare2#6541]
[`canal.c`](https://github.com/radare/radare2/blob/master/libr/core/canal.c) should use the current radare2 theme (e.g. `eco solarized`) instead of hardcoding values like `lightgray` and `yellow`.

As an example, this is what `VV` looks like:

![image](https://cloud.githubusercontent.com/assets/7232674/22143751/2d9930fa-dec9-11e6-8230-621439f2966c.png)

And ideally `ag` should follow the same colors as above. (It's completely different at the moment.)

![rev1 main dot](https://cloud.githubusercontent.com/assets/7232674/22143716/08278ace-dec9-11e6-9e1e-71de901e48a0.png)

**Comment by Manouchehri** [comment]
Same issue as #2141?

**Comment by radare** [comment]
well, the graphdiff loop is different from the graph one. this thing should be obeyed in both.. so ok to keep it there

**Comment by radare** [comment]
not sure if graphml supports this kind of formatting, and if so, can you point some example or documentation?

**Comment by Manouchehri** [comment]
The loop can be forced to one side by setting the port.

http://graphml.graphdrawing.org/primer/graphml-primer.html#Ports

**Comment by radare** [comment]
i have fixed the problem with the nasty \x2.) chars

**Comment by radare** [comment]
the problem with ag, is that graphviz sometimes fails.. and .dot files are not always processed by `dot`.. and other parses may fail.

**Comment by radare** [comment]
adding those colors is easy, but putting those colors inside the contents of each node is not easy if possible... and its definitvely not portable. so i would say NOFIX

**Comment by radare** [comment]
We should use GML or more complete/standard graph format to achieve that
