### ISSUE TITLE
feature request xc

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#6546]
Hi,

is it possible to have regex for xc, so you can specify a function in commandline ?
```
[0x004122b0]> xc @ sub.__libc_start_main_192_190|wc -l
17
[0x004122b0]> xc @ sub.__libc_start_main| wc -l 
Invalid address (sub.__libc_start_main)
|ERROR| Invalid command 'xc @ sub.__libc_start_main' (0x78)
0
```
When having more then one function (eg. strlen), one could still display
for each matched function.

Greetings
VP

**Comment by radare** [comment]
you can use @@ and glob expressions like main*

**Comment by VisualPrankDude** [comment]
Thanks. r2 -AAc 'xc @@ sub.__libc_start_main*' /bin/ls works!
