### ISSUE TITLE
x86_64: Wrong disassembly for opcode "83 f8 yy"

### ISSUE THREAD

**Issue by qcGVkzEG** [radare/radare2#6547]
The opcode `83 f8 yy` encodes `cmp eax, yy`, where `yy` is **sign-extended**.

radare2 does not sign-extend: For instance, it displays `cmp eax, 0xff` for the instruction `83 f8 ff`, while `cmp eax, 0xffffffff` is correct (according to objdump and the hardware).

**Comment by radare** [comment]
This issue belongs to capstone, not r2

**Comment by qcGVkzEG** [comment]
Thanks! Apparently, the bug is already [fixed](https://github.com/aquynh/capstone/issues/614) in the capstone's delevopment, so there's nothing left to do.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
which version of r2 do u use? because r2 uses that capstone already
