### ISSUE TITLE
Range reference search

### ISSUE THREAD

**Issue by radare** [radare/radare2#6549]
We can implement this in `/rr $$ $$+4096`

**Comment by radare** [comment]
This command should be like /r but allowing to specify the boundaries .. this is a temporary change of search.from/search.to and search.in... which makes me think that it will be solved in a better way if we add some sugar for it like I did for @@/

this needs some discussion

**Comment by jroimartin** [comment]
I think this is already implemented with `@..`:

```
[0x00000000]> ?@?~from to
| @..from to          temporary set from and to for commands supporting ranges
```

Right?

**Comment by jroimartin** [comment]
Commit: https://github.com/radare/radare2/commit/00626b9b021eb860020387b4eb4967ccfc60dd4f

**Comment by jroimartin** [comment]
Tests: https://github.com/radare/radare2-regressions/commit/4f244baaa3f7357db15130e593111925096105ec
