### ISSUE TITLE
68k negative relative addressing disassembly wrong?

### ISSUE THREAD

**Issue by laanwj** [radare/radare2#6554]
These instructions show as addressing with positive offsets, but what actually happens is that they use a negative offset (shown in comment):
```
0x00002460      1e3370f6       move.b 0xf6(a3, d7.w), d7   ; -0x0a
0x0000245a      303370e2       move.w 0xe2(a3, d7.w), d0   ; -0x1e
0x0000266c      303208fe       move.w 0xfe(a2, d0.l), d0   ; -0x02
```
This has thrown me off track a few times. It might be a capstone bug not on in radare?

**Comment by radare** [comment]
capstone is the default disassebmler for m68k, r2 just adds the info after the ‘;’ but the issue you are explaining seems to be related to capstone. also you can use the netbsd m68k disassembler with r2pm -i m68k-net and compare results

**Comment by laanwj** [comment]
Haven't been able to check with netbsd disassembler yet, but `m68k-linux-gnu-objdump -D -b binary -mm68k files/SYSTEM.INTERP ` gives me:
```
    2460:       1e33 70f6       moveb %a3@(fffffffffffffff6,%d7:w),%d7
    245a:       3033 70e2       movew %a3@(ffffffffffffffe2,%d7:w),%d0
    266c:       3032 08fe       movew %a2@(fffffffffffffffe,%d0:l),%d0
```
Sign-extending the offset to 64 bit on a 32-bit architecture is weird. But at least it's clearly not a 8 bit positive offset.

**Comment by radare** [comment]
yeah this output looks wrong too. open an issue in the capstone repo.

**Comment by laanwj** [comment]
This was fixed upstream (https://github.com/aquynh/capstone/issues/844). I guess this can be closed, or after radare's integrated capstone is updated.
