### ISSUE TITLE
Windows: remove dependency from dirent.h (opendir(), readdir(), etc)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#6559]
Currently things like r_lib_opendir(), sandbox, some fs tools are using opendir() api from dirent.h
Using Find*File() should help to solve the problem.

**Comment by XVilka** [comment]
Not yet removed completely, no?

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/459db13ef5fe99fc95acf529269549fa0fa64603

**Comment by XVilka** [comment]
It's not yet removed completely - as long as it compiles with `#include <dirent.h` only.

**Comment by Maijin** [comment]
@m4b4

**Comment by m4b4** [comment]
I am still working on it

**Comment by radare** [comment]
Done already, thanks!
