### ISSUE TITLE
Unify __WINDOWS__ and _WIN32 usage

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#6560]
Somewhere we're using `__WINDOWS__`, somewhere - `_WIN32`. This one should be unified.

**Comment by cr1901** [comment]
For those who aren't aware: `_WIN32` is required to be supported for any compiler targeting Windows. `__WINDOWS__` appears to be r2-specific, although I have seen other compilers (OpenWatcom) support this symbol as an alternative to `_WIN32`. Is the `__WINDOWS__` symbol redundant then?

**Comment by XVilka** [comment]
@cr1901 no, `__WINDOWS__=1` is generated by configure/make. So it's OK. Just need to be used everywhere, may be.

**Comment by Maijin** [comment]
What to do in here then https://github.com/radare/radare2/blob/master/libr/util/thread_lock.c#L36
Kill _WIN32 ? If yes well it's just a sed/kill?

**Comment by radare** [comment]
Imho its Ok to remove. This was needed in the past but i dont think its needed anymore
