### ISSUE TITLE
Project notes must be parsed with SPP

### ISSUE THREAD

**Issue by radare** [radare/radare2#6568]
Project notes (`Pn -`) must be assumed to be in markdown and preprocessed with SPP. This will allow us to have a syntax to put r2 commands in there, so, be able to import the notes into r2 as comments, flags, refs, notes...

This is one of my current workflows when doing static analysis and it feels pretty stable, because the editor doesn't crashes, projects may be trashed. but user notes nope :D

**Comment by radare** [comment]
maybe rapatch should support spp too. lets discuss and evaluate all those formats to try to reduce dupped code

**Comment by Svenito** [comment]
Fixed by #6779

**Comment by XVilka** [comment]
Please note, this could be useful along with 'CC,' - comment file, not only
project notes.

**Comment by radare** [comment]
Wat
