### ISSUE TITLE
Manpages for siol

### ISSUE THREAD

**Issue by condret** [radare/radare2#6572]
Well this sounds weird, but I realized that we need some documentation here, that describes how siol works, and how it should be used. Wrong usage of the API can cause:
- weak performance
- endless loops
- segfaults
- double-frees
- weird bugs

I don't think that I should do that for these reasons:
1. If someone else does this correctly, I can be sure that someone else understood the API in its details
2. pcache still needs some love, and I'm busy with that

The good thing about writing manpages is, that you cannot break anything with them.

**Comment by Maijin** [comment]
Use a markdown doc like here - https://github.com/radare/radare2/blob/master/doc/io

**Comment by radare** [comment]
+1 for markdown. This stuff can go into doc/*

**Comment by m1ghtym0** [comment]
Will do
