### ISSUE TITLE
Fix aai percentage issue

### ISSUE THREAD

**Issue by radare** [radare/radare2#6576]
to show the % of code analyzed (considering data and basic blocks ranges) inside the current section (or just .text?)

**Comment by radare** [comment]
related to https://github.com/radare/radare2/issues/2958

**Comment by Maijin** [comment]
Isn't this `aai` ?

![image](https://cloud.githubusercontent.com/assets/1408600/22626020/c4c08762-eba3-11e6-924f-11e0e2307b09.png)

**Comment by radare** [comment]
I dont see any % in this output

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/23578978/4ffc7832-00e3-11e7-8d01-cfed86ba3621.png)

**Comment by radare** [comment]
:D

**Comment by xarkes** [comment]
Can you detail what you want ?

**Comment by radare** [comment]
The output of the command `aai` shows a bigger percentage than 100%, so there's a wrong computation here. this issue should track to fix that thing and p-% lgtm already

**Comment by Maijin** [comment]
`p-% lgtm already`
`p-%` doesn't exist, should aai be replaced by `p-%` ?

**Comment by radare** [comment]
No. Aai should be fixed. Just the percentage

**Comment by Maijin** [comment]
So this may be a problem with realsize see the following:

https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L4962 => https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L4938

#4868

**Comment by radare** [comment]
Indeed

**Comment by alvarofe** [comment]
Just testing since yesterday I couldn't (forgot)

```
air:pe alvaro$ r2 /bin/ls
Module version mismatch /Users/alvaro/.config/radare2/plugins/io_frida.dylib (1.3.0-git) vs (1.4.0-git)
 -- Use hasher to calculate hashes of portion blocks of a file
[0x100001174]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
[0x100001174]> aai
fcns    107
xrefs   1178
calls   0
strings 108
symbols 90
imports 76
covrage 0
codesz  16742
percent 0%
```

**Comment by xarkes** [comment]
Here's mine
`[antide@archlap radare2 (aai)]$ r2 /bin/ls
 -- May the segfault be with you.
[0x00404030]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
[0x00404030]> aai
fcns    246
xrefs   6470
calls   76
strings 414
symbols 117
imports 109
covrage 109682
codesz  195549
percent 56%
`

**Comment by Maijin** [comment]
@alvarofe - "What a damn habit of creating/reoping issues without saying which file"

**Comment by xarkes** [comment]
Actually the compute_coverage function does not work with Mach-O ls

**Comment by alvarofe** [comment]
maybe it doesn't work with mach0 since s->rwx iirc in is expressed in another way so s->rwx & 1 it fails.

**Comment by alvarofe** [comment]
so we should ensure the same flags throughout all sections
