### ISSUE TITLE
aac Uses Invalid Range When Used With -m

### ISSUE THREAD

**Issue by robopeter** [radare/radare2#6585]
Attempting to run "aac" on a binary blob (no elf or other header) that was loaded with the -m flag yields an "Oops invalid range" error. Running "aac ###" where ### is a large number somewhere around the size of the binary yields the expected results.  

The following chunk from cmd_anal.c seems to not make sense, but I don't know enough of what's going on to fix it: 

```
				if (binfile->size > core->offset) {
					if (binfile->size > core->offset) {
						len = binfile->size - core->offset;
					} else {
						eprintf ("Opps something went wrong aac\n");
						return;
					}
				} else {
					eprintf ("Oops invalid range\n");
					len = 0;
				}
```

First, why are there two of the same if blocks inside one another?  
Second, the third line here is going to be weird (negative?) if my offset is larger than my binary size, and really, I still want to analyze the length of the whole binary, it seems like start/end addresses should be updated, not length.

Thanks for any help with this.

**Comment by robopeter** [comment]
Maybe this is related to #5433 ? or at least some of what's being talked about there...?

**Comment by robopeter** [comment]
search.in is set to file... which is what I think I want, isnt it? I want to search the whole (relocated) file.
anal.in doesn't seem to be an option... ???

**Comment by radare** [comment]
I wrote 4 tests for this thing in t.anal/others/aac
