### ISSUE TITLE
Update r2 on Kali Linux

### ISSUE THREAD

**Issue by bennyty** [radare/radare2#6590]
I have a new install of Kali from https://www.offensive-security.com/kali-linux-vmware-virtualbox-image-download/

`Linux kali 4.6.0-kali1-686-pae #1 SMP Debian 4.6.4-1kali1 (2016-07-21) i686 GNU/Linux`

I tried to follow https://securityblog.gr/3791/install-latest-radare2-on-kali/ in order to update to the git version of r2. However:

```
root@kali:~/radare2# r2 -v
WARNING: r2 library versions mismatch! See r2 -V
radare2 1.2.0-git 13608 @ linux-x86-32 git.1.2.0-git-42-g3a13add
commit: 3a13addb77b6e99225be6b1b6c467b72f6704475 build: 2017-01-26
```

and

```
root@kali:~/radare2# r2 -V
1.2.0-git-42-g3a13add  r2
0.9.9  r_anal
0.9.9  r_lib
0.9.9  r_egg
0.9.9  r_asm
0.9.9  r_bin
0.9.9  r_cons
1.2.0-git-42-g3a13add  r_flag
0.9.9  r_core
0.9.9  r_crypto
0.9.9  r_bp
0.9.9  r_debug
0.9.9  r_hash
0.9.9  r_fs
0.9.9  r_io
0.9.9  r_magic
0.9.9  r_parse
0.9.9  r_reg
0.9.9  r_sign
0.9.9  r_search
0.9.9  r_syscall
0.9.9  r_util
WARNING: r2 library versions mismatch!
```

and r2 aborts on most commands:
EDIT: put log in gist: https://gist.github.com/bennyty/a7f46d62a00bb5806083b6298a91e878

I've tried every variation of `make clean` `make purge` `git clean` `./sys/uninstall.sh` then reinstalling (`./sys/install.sh`) that I can find or think of. Thanks.

**Comment by radare** [comment]
please remove r2 from kali first

apt-get remove radare2 radare2-lib
apt-get purge radare2 radare2-lib

(didnt tried), if you want to be sure that there’s no previous installation of r2 you can run this in git’s :

./configure —prefix=/usr
make purge

btw, the release machinery is also creating .deb packages. you can just download it and install it with dpkg -i

a new release will happen this sunday/monday, so you can wait for that if you want to go for .deb instead of git

**Comment by Maijin** [comment]
Just use `./sys/install.sh` after cleaning everything like @radare  said

**Comment by bennyty** [comment]
Thanks, I tried to remove the libs:

```
root@kali:~/radare2# apt-get update
Hit:1 http://archive-9.kali.org/kali kali-rolling InRelease
Reading package lists... Done
root@kali:~/radare2# apt-get remove radare2 radare2-lib
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package radare2-lib
root@kali:~/radare2# apt-get purge radare2 radare2-lib
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package radare2-lib
```

This is my `/etc/apt/sources.list`, maybe Kali's default sources don't include whichever repository r2 is listed in.
```
deb http://http.kali.org/kali kali-rolling main non-free contrib
```

But alas, my "r2 library versions [still] mismatch!"

I can afford to wait for the next release if that would simplify the process.

**Comment by radare** [comment]
maybe its radare2-dev or something like that check the list of installed packages (dpkg -l)

**Comment by bennyty** [comment]
Taught me something I didn't know.
For reference they are:
```
root@kali:~# dpkg -l | grep radare
ii  libradare2-0.9.9:i386                  0.9.9-0kali1+b1                      i386         libraries from the radare2 suite
ii  libradare2-common                      0.9.9-0kali1+b1                      all          arch independent files from the radare2 suite
ii  libradare2-dev                         0.9.9-0kali1+b1                      i386         devel files from the radare2 suite
```
Everything seems to work now, thanks! Is it recommended to install off of the .deb packages or build from git?

**Comment by Maijin** [comment]
Build from git. Use ./sys/install.sh
