### ISSUE TITLE
/E esil fun: 0x00400000 esil_neg: unknown reg  "zf

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6593]
morrn,

echo 'e anal.esil=1; e asm.esil=1; e esil.verbose = 1; aaaa; /E  "zf,!,?{,4213168,rip,=,}"' |  r2  /bin/ls 1>/dev/null

 esil vm is initialized:
esil output seems ok.

but I get error: 0x00400000 esil_neg: unknown reg  "zf

valgrind/asan follows later

**Comment by zonkzonk** [comment]
![asan esil](https://cloud.githubusercontent.com/assets/5694980/22368149/0d456a94-e47d-11e6-97ef-c35ea82f7308.png)

**Comment by radare** [comment]
you are quoting wrong

**Comment by radare** [comment]
NOTABUG

**Comment by zonkzonk** [comment]
@radare ok, but how to quote then?

**Comment by radare** [comment]
Like you quote any other command in r2. Covering the whole command. Not the argument

**Comment by zonkzonk** [comment]
@radare, ok adding additonal quotes, yields in the same result:
0x00400000 esil_neg: unknown reg "zf
Cannot parse esil ("zf,!,?{,4213168,rip,=,}")

isn't rpn a proble here? since esil_neg is complaining.

**Comment by radare** [comment]
you are still quoting wrongly and not pasting the command you are using
