### ISSUE TITLE
Project functionality broken if aeim is used - binary not reloaded

### ISSUE THREAD

**Issue by lawrenceakka** [radare/radare2#6596]
1) Use aeim
2) Save the project
3) Quit and reopen the project
4) r2 thinks the file is malloc:// ... The path to the original binary is lost, and the original binary is not loaded
5) 😭 

```
$ r2 -v
radare2 1.2.0-git 13610 @ darwin-x86-64 git.1.2.0-git-44-g800379c47
commit: 800379c475ba84a35c05633ca4806036975a4b23 build: 2017-01-27

$ r2 /bin/ls
[0x1000011e0]>
[0x1000011e0]> i~file
type     Executable file
file     /bin/ls
[0x1000011e0]> aeim
[0x1000011e0]>[0x1000011e0]> i~file
type     Executable file
file     /bin/ls
[0x1000011e0]># everything seems OK so far
[0x1000011e0]> Ps test
test
[0x1000011e0]> qy
Do you want to save the 'test' project? (Y/n)Y

$ r2 -p test
[0x00000000]> i~file
file     malloc://983040
[0x00000000]>xl 3
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00000000  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00000010  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00000020  0000 0000 0000 0000 0000 0000 0000 0000  ................
[0x00000000]># Where is my binary?????

```

**Comment by Maijin** [comment]
Wat ? 

Project != Binary. 

If you want to save the bin in the project file you have to specify that with e prj.files option otherwise you need to open the file again and use the project.

**Comment by lawrenceakka** [comment]
Aha! I understand.

However ...

1. Using `e prj.files=true` does not seem to help in this scenario. Saving the project copies the binary to the .config directory, though r2 generates warnings about not being able to copy the malloc:// file as well. Once `aeim` has been used however, when the project is saved and reloaded, the binary is not loaded. Is it meant to be?

2. If you `r2 -p test` and then open the binary with `o \bin\ls`, none of the analysis is loaded:

```
$ r2 /bin/ls
[0x1000011e0]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x1000011e0]> aflq
0x100000f00 0x100000f12 0x100000f27 0x100000f6c 0x100000fba 0x100000fff 0x10000104d 0x100001092 0x1000010e0 0x100001112 0x10000114d 0x100001192 0x1000011e0 0x100001b54 0x100001e24 0x100001e8c 0x1000028ec 0x1000029ba 0x100002ad5 0x100003328 0x10000338c 0x1000034cf 0x100003595 0x1000035cb 0x10000365b 0x10000372d 0x100003a4d 0x100003bd8 0x100003c42 0x100003c69 0x100003c76 0x100004020 0x1000043f1 0x100004420 0x10000443e 0x1000044f2 0x10000455e 0x100004564 0x1000045e2
[0x1000011e0]> aeim
[0x1000011e0]> Ps test
test
[0x1000011e0]> q
Do you want to save the 'test' project? (Y/n)Y
$ r2 -p test
[0x00000000]> o /bin/ls
6
[0x000011e0]> aflq
[0x000011e0]> # nothing here! Though I can see the analysis if I inspect the project rc file manually
```

Sorry if I am doing something stupid! I am trying to find a way to use `aeim` and projects together, but I cannot find a way to reload the project and preserve the existing analysis

**Comment by radare** [comment]
This is related to another issue related to projects with multiple files

**Comment by lawrenceakka** [comment]
xref to #6037

**Comment by radare** [comment]
@rlaemmert can you make it for 1.3?

**Comment by rlaemmert** [comment]
Hm we could leave file.path as it is for the whole session. Any additional opened file would be saved in a later version through o or on command inside the project rc script.

**Comment by radare** [comment]
send a pr @rlaemmert

**Comment by rlaemmert** [comment]
whats the status of opsiol?
