### ISSUE TITLE
ARM ldrex/strex assembler not supported

### ISSUE THREAD

**Issue by ninjahacker** [radare/radare2#6599]
rasm2 -a arm -b 32 'ldrex r1, [r2]'
001092e5
rasm2 -a arm -b 32 'ldr r1, [r2]'
001092e5

Disassembly is fine:

rasm2 -a arm -b 32 -d 9f1f92e1
ldrex r1, [r2]

But it isn't recognized in ESIL:
rasm2 -a arm -b 32 -dE 9f1f92e1

*blank*

**Comment by radare** [comment]
You can use arm.ks meanwhile. Or someone will eventually implement those
