### ISSUE TITLE
x86 assemblers mayhem

### ISSUE THREAD

**Issue by radare** [radare/radare2#660]
We already have several x86 assemblers, but none of them is complete. I would suggest cleaning up that and enhancing the testsuites to make this possible.

Also, I've noticed that there are two plugins that do the same. we have to choose which want to kill.  `x86.as` and `gas`.

**Comment by jvoisin** [comment]
What about removing all of them, except `x86.nz`, since `x86.olly` is ugly and we're planing to ditch `x86.udis` anyway.

**Comment by radare** [comment]
X86.olly allows to assemble a simgle instruction in different modes. I think its a nice, but totally incomplete and only supports 32bits.

But it has been useful to assemble code for intel without depending on gnu to test the nz one.

Instead of removing it should be moved to extras. Also. Its GPL

**Comment by radare** [comment]
Also, udis is faster than capstone, and way smaller. This is.. Rop search take less time.

**Comment by Maijin** [comment]
This will be fixed probably with keystone integration, is the issue still relevant ?

**Comment by XVilka** [comment]
Not really, since keystone is C++, and r2 need something embedded.

**Comment by Maijin** [comment]
true.

**Comment by Maijin** [comment]
What about:

- [ ] Keep `.nz` in the main repo and move all the others in the r2e
- [ ] Create a strong/good canned speech for github complain regarding missing opcode suggesting trying using keystone and explaining where to add the support or at least if a test is existing

**Comment by radare** [comment]
Maybe merge tab and nz?

**Comment by Maijin** [comment]
@Svenito

**Comment by Svenito** [comment]
I'm still working on merging tab and nz BTW. Doing as much as I can time permitting.

**Comment by radare** [comment]
cool! keep up the good work :)

**Comment by Maijin** [comment]
Canned Speech created if you want to use it too:

Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently. 
You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.

You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
a___  32         x86.tab     LGPL3   x86 table lookup assembler
```

**Comment by Maijin** [comment]
So for the move: olly and as ? what about also nasm so we just have nz in main repo and the rest in r2pm.

**Comment by Maijin** [comment]
@Svenito ping

**Comment by Svenito** [comment]
Back in the saddle. I assume that 

> Keep .nz/.tab merged in the main repo and move all the others in the r2e and available via r2pm

is the next item to tackle

**Comment by Maijin** [comment]
Closing this for now.
