### ISSUE TITLE
siol-compability

### ISSUE THREAD

**Issue by condret** [radare/radare2#6603]
so you guys added new stuff, and renamed other stuff. And this is why siol build fails again.

Questions:
- what is R_IO_DESC_TYPE ... for, is it really needed?
- what is io->Oxff for, isn't it the same as io->ff ?

**Comment by radare** [comment]
Oxff is used to specify which value the user wants to use to display the regions of memory that cannot be read. this was a request from a user who wanted to have 0x00 instead of 0xff.

**Comment by radare** [comment]
and this Oxff was implemented 9 months ago.., is not that "new"

**Comment by radare** [comment]
i dont know why this R_IO_DESC_TYPE (OPEN|CLOSED) was implemented., but it could be simplified to a bool. IIrc it is a way to allow the backend to tell the frontend that the stream was closed. But i cant recall the commit right now

**Comment by condret** [comment]
The R_IO_DESC_TYPE thing is set 2 times in the codebase, and never checked anywhere. I removed it, since it really does nothing

**Comment by radare** [comment]
Ok for me. But wondering who added this and why

**Comment by condret** [comment]
you added this >6 years ago

**Comment by radare** [comment]
6 years ago...

**Comment by radare** [comment]
we cant merge siol in 1 week, but its merging is progressing slowly

**Comment by condret** [comment]
we actually did the merge in less than a week
milestone achieved
