### ISSUE TITLE
RCoreFile->desc

### ISSUE THREAD

**Issue by condret** [radare/radare2#6608]
I don't think that the will manage to kill RCoreFile for 1.3, but maybe we can kill RCoreFile->desc.

I would like to replace RCoreFile->desc with RCoreFile->fd (int or ut32). I think, in order to prevent segfaults and stuff, we should go for encapsulation when it comes to io, which means that the core shall not have any pointers to rio internal stuff, like the descs. Having a fd/id should be enough for the core, as long as it uses the rio-API

**Comment by radare** [comment]
Agree on that, if we manage to have a fast way to resolve from fd to desc. Otherwise we will have to control the descriptor state (open/closed) and add a reference counter

**Comment by condret** [comment]
siol does this with sdb atm, but as i told u yesterday I want to speed that up

**Comment by condret** [comment]
o(1) is fast enough
