### ISSUE TITLE
orr not implemented for arm64 assembler

### ISSUE THREAD

**Issue by radare** [radare/radare2#6611]
```
            0x10000fb4c      e0030032       orr  w0,  wzr, 1
```

we also miss other binary ops for the arm64 assembler

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/45bbca4e29c0dd3c104f5d25bf7f83d5437f3776

**Comment by radare** [comment]
Arm64 is very different compred to arm32, even the assembler code is completelly different. Totaly incompatible archs
