### ISSUE TITLE
stdin pipe for commands such as dc

### ISSUE THREAD

**Issue by dinosaurfiles** [radare/radare2#6614]
Example on GDB. Adding a breakpoint before the stdin method(gets, scanf, etc)
`(gdb)run < "test input"`
Can we have the same functionality such as
`[0xdeadbeef]> dc < "test input"` ?

**Comment by Tzaoh** [comment]
I would like to have the chance to specify args or the stdin in r2 arguments without the need to create a profile with rarun2.
r2 -d /bin/ls arg1='aaaaa' stdin='bbbb' ?

**Comment by radare** [comment]
You can pass arguments right after the executable "r2 -d ls /" works fine, but yes i also want that. Its easy to do but im with not much spare time lately, i would use another cmdline flag. What do you think?

**Comment by Tzaoh** [comment]
Oh you are right about the args. I would love to have it. I do not have a lot of time either but I can try it slowly if you point me the right way (files to edit?). Which cmdline would you like? "-stdin="?

**Comment by radare** [comment]
What about -X stdio=/dev/tty ...

**Comment by Tzaoh** [comment]
I like it, Are you considering to have stdin too not only stdio?

**Comment by radare** [comment]
all rarun2 options will be available in -X, my only concern is that i dont like to use uppercase flags when the lowercase is not taken..

**Comment by radare** [comment]
its now implemented in master, pls check it out

the whole r2 session is piped to the other tty still. but this will be fixed soon.

thanks for reporting. also the current implementation is leaking memory and temporary files. will fix that soon. just wanted to have the functionality done quickly :)

**Comment by radare** [comment]
what about making custom rarun2 directives to be accessible as a comma separated profile for the `doo`  or `oo` argument?.

also dc is not the same as run

**Comment by Tzaoh** [comment]
Hihi, you already know about it, but I let it here, in case someone wants to try and fix it.
Aparently after an 'ood' to rexecute the hole thing, it fails.
```bash
root@kali:~/CTFs/TamuCTF2017/pwn3# r2 -X 'stdin="%p %p %p %p %p"' -d pwn3
Process with PID 19081 started...
= attach 19081 19081
bin.baddr 0x08048000
Using 0x8048000
Assuming filepath /media/sf_shared/TamuCTF2017/pwn3/pwn3
asm.bits 32
 -- Add comments using the ';' key in visual mode or the 'CC' command from the radare2 shell
[0xf7711ac0]> dc
Selecting and continuing: 19081
Enter a word to be echoed:
0x2 (nil) (nil) 0x25207025 0x70252070PTRACE_EVENT_EXIT pid=19081, status=0x0
[0xf770fc89]> ood
Wait event received by different pid 19081
Can't find profile '/tmp/.rarun2.590258e671cf1'
File dbg:///media/sf_shared/TamuCTF2017/pwn3/pwn3  reopened in read-write mode
= attach 19105 19105
Assuming filepath /media/sf_shared/TamuCTF2017/pwn3/pwn3
Cannot open '/proc/19105/maps': No such file or directory
Cannot open '/proc/19105/maps': No such file or directory
[0x00000000]>
```

I am trying to discover too how to pass the output of another shell cmd with $() or \`\`:  
``r2 -X "stdin='`python -c 'print("A" * 30)'`'" -d pwn3``
``r2 -X "stdin='$(python -c 'print("A" * 30)')'" -d pwn3``
``r2 -X "stdin=$(python -c 'print("A" * 30)')" -d pwn3``

**Comment by radare** [comment]
> On 27 Apr 2017, at 23:00, Tzaoh <notifications@github.com> wrote:
> I am trying to discover too how to pass the output of another shell cmd with $() or ``:
> r2 -X "stdin='`python -c 'print("A" * 30)'`'" -d pwn3
> r2 -X "stdin='$(python -c 'print("A" * 30)')'" -d pwn3
> r2 -X "stdin=$(python -c 'print("A" * 30)')" -d pwn3
> 

you can can do it like this:

S=$ r2 -X stdin=$S”(python -c ‘print(\”A\” * 30)’)” -d pwn3

didnt tested but it should work

**Comment by radare** [comment]
@alvarofe chk this ood issue which is related to the -X and rarun2 profile one too

**Comment by radare** [comment]
I think the solution here is to make the following extensions to `ood`:

* ood < file. -> set stdin=@file for the rarun2 profile. # problematic if we implement  < in the future.. so better go for `oodr`
* oodr arg1=/bin -> set this rule for the rarun2 profile
