### ISSUE TITLE
Unrecognized type "int"

### ISSUE THREAD

**Issue by radare** [radare/radare2#6619]
```
[0x00000000]> "td int foo(int bar);"
[0x00000000]> "td int foo(int bar);"
Unrecognized type "int"
[0x00000000]>
```

**Comment by oddcoder** [comment]
I cant reproduce https://asciinema.org/a/3rkqdyve5iy4upc8t51y3t2gi

**Comment by radare** [comment]
Type it twice

**Comment by radare** [comment]
this issue is important , so i have tagged it for release. pls keep the issue updated with your findings/fixes
