### ISSUE TITLE
Cannot define function pointers

### ISSUE THREAD

**Issue by radare** [radare/radare2#6629]
pf have no syntax to refer to a function signature.

`[0x00000000]> "td typedef int (*fun)(int bar);"`

this produces no error.. but there's no way to refer to it except showing the raw sdb database:
```
[0x00000000]> tk~fun.
func.fun.arg.0=int,bar
func.fun.args=1
func.fun.cc=cdecl
func.fun.ret=int
```

tf fun should show the function signature.. and `tf*` should display the r2 command to show that function signature.. maybe with pf grabbing the values from stack?.. but what it will be really used that for is to define that a local variable or a field in a struct is a function pointer. it must resolve the destination of the pointer hold in there as this type (and name)
```
[0x00000000]> tf fun~?
447
```

but then we cannot use that in structs:

```
[0x00000000]> "td struct fon { fun test; }"
<string>:1: error: bracket expected
```

**Comment by Maijin** [comment]
It's in the doc -> https://github.com/radare/radare2/blob/master/doc/types.md#function-prototypes

**Comment by Maijin** [comment]
Oh wait, I think it's not in the doc indeed

**Comment by oddcoder** [comment]
why would you need to define a function pointer ?

**Comment by radare** [comment]
?????

**Comment by oddcoder** [comment]
in fact pointers doesn't play nice in pf design there was a walkaround to define a pointer type
this way 
```
X.type.pointto=Y
```
it was described in the docs yet it had no use at
