### ISSUE TITLE
function analysis leads to incomplete function in the presence of __errno function call

### ISSUE THREAD

**Issue by mx-pycoder** [radare/radare2#6637]
Automated function analysis of some binaries from an Android device results in an incomplete function when a call to __errno is done in that specific function. This can be seen in these next two screenshots (in this case, this is from an 'ls' binary).

![screenshot-20170201 231937](https://cloud.githubusercontent.com/assets/10725702/22529267/158d1d7e-e8d7-11e6-9344-d787b2cebe4a.png)

![screenshot-20170201 232007](https://cloud.githubusercontent.com/assets/10725702/22529399/97db28ac-e8d7-11e6-98ba-f6fd300744d1.png)

This seems related to the 'err' function in libr/anal/d/types and I can get function analysis working for this specific case by removing the 'err' definition from this file and rebuilding radare2. It seems that the '__errno' function is mistakenly interpreted as the 'err' function. See these next two screenshots for the expected result:

![screenshot-20170201 232424](https://cloud.githubusercontent.com/assets/10725702/22529665/a0a12346-e8d8-11e6-8394-3992c6052163.png)

![screenshot-20170201 232504](https://cloud.githubusercontent.com/assets/10725702/22529669/a533348a-e8d8-11e6-8d6d-f0805461fefb.png)

Obviously, removing such a definition is not the real solution, so I've been trying to find where and howo these definitions are processed. It seems related to the sdb_querys function defined in libr/include/sdb/sdb.h, but my understanding of the code is too limited to track this down further. It did occur to me that the 'err' definition in the /libr/anal/d/types file was the only definition that includes a line that states 'func.err.noreturn=true'

I hope this will help to track down this issue.

**Comment by mx-pycoder** [comment]
I have extracted a binary (/system/bin/toolbox) from the Nexus 4 factory image occam-jdq39-factory-5880aa93.zip that can be downloaded from here https://developers.google.com/android/images. I have uploaded this file to the following google drive link:
https://drive.google.com/file/d/0B_YI2aVCObacZi1vVXYwS2Nicm8/view

Steps to reproduce the issue with this file:

  r2 toolbox
  [0x00004bf0]> aaa
  [0x00004bf0]> s sub.opendir_31c
  [0x0000531c]> afB 16
  [0x0000531c]> V
  p

Observe that the sub.opendir_31c 'stops' after the blx sym.imp.__errno function at offset 0x00005360 and has only these basic blocks:

:> afb
0x0000531c 0x00005360 00:0000 68 f 0x00005360
0x00005360 0x00005364 00:0000 4

When rebuilding with the 'err' definition removed from /libr/anal/d/types, the function analysis results in a function that continues to offset 0x00005604 with many more basic blocks.

**Comment by radare** [comment]
Fixed, by removing the definition of func.err. `err` is too simplistic to be considered a function. mainly because how noreturn works. that is "glob"-ing for a similar symbol name. removing it causes no harm, but its not the ideal solution. we should be more strict about the noreturn namings.

Thanks for reporting. ill add a test case now
