### ISSUE TITLE
Functions argument wrong recognition 

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6641]
For example:

`xmalloc` is recognized as `malloc` because it contains "malloc" which is wrong for example
This caused https://github.com/radare/radare2/issues/6637#issuecomment-276950958

But the autorename function should still work for example `sub.strcoll_e1` should be recognized as `strcoll`.

**Comment by radare** [comment]
see the first test in t.anal/arm/arm_16 as an example but we need tests to proove thats not working or its fixed

**Comment by radare** [comment]
pls provide tests

**Comment by Maijin** [comment]
Added https://github.com/radare/radare2-regressions/commit/487e5ef0dc0e6bb394b3060302001582d50db1e1

**Comment by oddcoder** [comment]
well the bright side it will recognise "sym.imp.malloc_458 as malloc
This is the a feature not a bug ;).

**Comment by Maijin** [comment]
@oddcoder look at the tests.

**Comment by oddcoder** [comment]
ok

**Comment by radare** [comment]
This is fixed now i think

**Comment by radare** [comment]
Please confirm

**Comment by Maijin** [comment]
Not fixed

**Comment by oddcoder** [comment]
yes not fixed the name is a bit misleading

**Comment by Maijin** [comment]
Ok my bad is fixed
