### ISSUE TITLE
Debugging with Docker container requires --privileged tag

### ISSUE THREAD

**Issue by hxeaven** [radare/radare2#6643]
This isn't necessarily an issue, but may be helpful for users in regards to debugging with Docker. Nothing on the docker hub page mentions this. I spent some time trying to figure this out. It requires running with privileged tag in order to properly perform debugging.

**Works**
```
$ docker run -it --privileged radare/radare2
$ r2 -d /bin/true
```

**Does not work**
```
$ docker run -it radare/radare2
$ r2 -d /bin/true
```

**Comment by radare** [comment]
you can send a pullreq updated the /Dockerfile in the root directory of r2 with this message.

**Comment by radare** [comment]
Tired of waiting
