### ISSUE TITLE
Regression in LOAD segment vaddr handling

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6650]
https://github.com/radare/radare2-regressions/pull/691

$ rabin2 -S bin |  grep LOAD0
idx=28 vaddr=0x00400000 paddr=0x00000000 sz=8796 vsz=8796 perm=m-r-x name=LOAD0
$ r2 -qc 'iS' -d bin  | grep LOAD0
idx=28 vaddr=0x00000000 paddr=0x00000000 sz=8796 vsz=8796 perm=m-r-x name=LOAD0

lose the vaddr for the segment and r2 `iS` doesnt meet rabin2 out.

broken by 4fd1e99

**Comment by SchumBlubBlub** [comment]
wait, this is even worse. It's not just this mangled elf that's the problem. I can't `db main` on a "hello world" program anymore. :fire: .

**Comment by radare** [comment]
dont use db main when you can dcu main. also it works fine for me

**Comment by leberus** [comment]
my fault, i'll check it out now

**Comment by Maijin** [comment]
There is also e dbg.bep variable that you can set to main

**Comment by SchumBlubBlub** [comment]
I tried dcu a while ago, its was really slow getting out of the loader and into main, I had to break.

**Comment by leberus** [comment]
I've found it:

+#define R_IO_PRIV  (1 « 5)
+#define R_IO_SHAR  (1 « 6)

This breaks it. I'll check how to make that it doesn't collide

**Comment by SchumBlubBlub** [comment]
> There is also e dbg.bep variable that you can set to main

@Maijin , I did, that's how I met this bug.

**Comment by leberus** [comment]
I think this can be closed. It was solved by [6672](https://github.com/radare/radare2/pull/6672), wasn't it?

**Comment by radare** [comment]
do we have tests?

**Comment by leberus** [comment]
I promise i'll write some tests for the debugger

**Comment by Maijin** [comment]
It has tests see the tags. https://github.com/SchumBlubBlub/radare2-regressions/blob/master/t.archos/Linux-x86_64/dbg_seginfo

**Comment by SchumBlubBlub** [comment]
Tests: link in OP, merged today: https://github.com/radare/radare2-regressions/pull/691

**Comment by Maijin** [comment]
I know.
