### ISSUE TITLE
analysis puts value in wrong field,  $v / $m fail

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6651]
https://github.com/radare/radare2-regressions/pull/690

https://github.com/radare/radare2book/pull/44/commits/73941c3c9425cf0f042e35e794bfcd947d091dea

**Comment by Maijin** [comment]
Tests are wrong see comment.

**Comment by Maijin** [comment]
Also won't merge this :P

**Comment by SchumBlubBlub** [comment]
@Maijin , I pushed an update in response to review. Reopen?

**Comment by SchumBlubBlub** [comment]
I could swear `$m` failed me a few days ago, but no repro it didn't happen...

**Comment by Maijin** [comment]
Omg, I just realize you PR this thing in r2book and I merged it . . . P

**Comment by SchumBlubBlub** [comment]
@Maijin  ;)
I called the commit "Easter Egg", you were lazy....

I'm discussing with radare in other issue.
