### ISSUE TITLE
ELF .dword not always recognized by aaa

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6653]
In https://github.com/radare/radare2-regressions/raw/master/bins/elf/arm1.bin ;

Sometimes work:

![image](https://cloud.githubusercontent.com/assets/1408600/22591489/2dda0d3a-ea15-11e6-8afd-2e8b42989dfd.png)

Sometimes doesn't (entry0):

![image](https://cloud.githubusercontent.com/assets/1408600/22591500/3873a45e-ea15-11e6-9ac7-5b65d41cc072.png)

**Comment by Maijin** [comment]
Added, that can be reproduce by af then aav in this order (same as aaa)

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/a071f5dd3930aad8f1c5ede7ba2189fd513bc491#diff-f95b732b47dde0f5a2b3a9fe9fdb3894

**Comment by alvarofe** [comment]
This 
```
Cd 4 @@=`f~loc._d[0]`
```
will leverage $d symbol from ELF (I will add this in code) the others I have to take a look.

Maybe it would make sense to add some kind of anal hints for code vs data. What do you think @radare ?

**Comment by Maijin** [comment]
@alvarofe please read the issue more carefuly. This already works when you do `aav` follow by `af`, but not when doing `af` then `aav`.

**Comment by Maijin** [comment]
# af + aav

![af + aav](https://cloud.githubusercontent.com/assets/1408600/22866871/3b282048-f17d-11e6-8bb6-76839ab2f3ff.png)

# aav + af

![aav + af](https://cloud.githubusercontent.com/assets/1408600/22866875/3e0ef55c-f17d-11e6-82bd-60fa5c4d4496.png)

**Comment by alvarofe** [comment]
wtf interesting.

But anyway I think anal hints for this may help for other stuff I will think about it.

**Comment by alvarofe** [comment]
`e anal.vinfun=true` fix this, without this option if the addr is within a function does not create nothing. Maybe we should make this by default.

```
anal.vinfun: Search values in functions (aav) (false by default to only find on non-code)
```

**Comment by Maijin** [comment]
That is not the issue. Why `af + aav` behave differently than `aav + af` ?

**Comment by alvarofe** [comment]
It is the issue. when you do af + aav. There is a function created and in here

```
			if (match && !vinfun) {
				if (vinfunr) {
					if (r_anal_get_fcn_in_bounds (core->anal, addr, R_ANAL_FCN_TYPE_NULL)) {
						match = false;
					}
				} else {
					if (r_anal_get_fcn_in (core->anal, addr, R_ANAL_FCN_TYPE_NULL)) {
						match = false;
					}
				}
			}

```

match is set to false.

On the other hand, when doing aav without af, there is not function and the match is never set to false. That is why you should use `anal.vinfun` to true.

**Comment by alvarofe** [comment]
I don't why is set to false by default though. @radare is who did this, I assume because of FP or something related but he will know more. We should change it to true?

**Comment by radare** [comment]
enable in a PR to see what travis says

**Comment by Maijin** [comment]
Fixing the tests now
