### ISSUE TITLE
Visual mode '&' not changing bits

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6655]
Visual mode '&' doesn't work anymore, it only change the function information here:

![image](https://cloud.githubusercontent.com/assets/1408600/22591711/41386e70-ea16-11e6-89e3-93792cc24b56.png)

![image](https://cloud.githubusercontent.com/assets/1408600/22591716/4439ac60-ea16-11e6-8b43-6f8601e4ee3d.png)

But the bits remain the same 

See https://github.com/radare/radare2/blob/master/libr/core/visual.c#L1630

**Comment by radare** [comment]
add tests for gtfo

**Comment by Maijin** [comment]
Added ! https://github.com/radare/radare2-regressions/blob/a071f5dd3930aad8f1c5ede7ba2189fd513bc491/t/cmd_visual#L76

**Comment by radare** [comment]
isnt this fixed by alvaro’s commit?

**Comment by Maijin** [comment]
Nop not yet see:

![image](https://cloud.githubusercontent.com/assets/1408600/22666372/92bc3674-ecb8-11e6-9b30-03e0fc241155.png)

**Comment by Maijin** [comment]
See 

https://asciinema.org/a/ah0eagbfz98pqbkvgmftdqsrw

and

https://asciinema.org/a/01ydwyoqho52ecj5xm3gif3jb

Still completly unusable.

**Comment by alvarofe** [comment]
I would kill this command since now with anal hints does not make any sense.

Let me shed some light and if you thing is worth it, I might write a post.

arm/thumb now is handled by anal hints. When parsing symbols, entry points and such internally the code set anal hints to track those.

```
air:elf alvaro$ r2 libmagic.so
Module version mismatch /Users/alvaro/.config/radare2/plugins/io_frida.dylib (1.2.0-git) vs (1.2.1)
 -- Dissasemble? No dissasemble, no dissassemble!!!!!
[0x00005fa8]> ah~..
 0x00005df8 - 0x00005df8 => bits=32
 0x00005e04 - 0x00005e04 => bits=32
 0x00005e10 - 0x00005e10 => bits=32
....

```

What it says is that at `0x00005df8` onwards will be treated as arm. Once you make an analysis or print disassembly all these ranges is cleaned up and it grabs the only what are important since you can coalesce them.

```
[0x00005fa8]> ah
 0x00005df8 - 0x00005df8 => bits=32
 0x00006060 - 0x00006060 => bits=16
 0x00007edc - 0x00007edc => bits=32
 0x000080fc - 0x000080fc => bits=16
 0x000083f0 - 0x000083f0 => bits=32
 0xfffffffe - 0xfffffffe => bits=16
```

This is what r2 internally will use so changing the whole asm.bits or fcn->bits does not make any sense for me now. Thus if you want to set a direction as thumb instead of arm you should follow the next steps quite easy actually.

```
[0x00005fa8]> pd 4
               ; [9] va=0x00005fa8 pa=0x00005fa8 sz=53128 vsz=53128 rwx=--r-x .text
            ;-- entry0:
            ;-- section_end..plt:
            ;-- section..text:
               ; [0x5fb4:4]=0x1104c
            0x00005fa8      04009fe5       ldr r0, [0x00005fb4]
               ; section_end.GNU_RELRO
            0x00005fac      00008fe0       add r0, pc, r0
               ; sym.imp.__cxa_finalize
            0x00005fb0      93ffffea       b sym.imp.__cxa_finalize
            0x00005fb4      4c100100       andeq r1, r1, ip, asr 32
[0x00005fa8]> ahb 16
[0x00005fa8]> pd 4
               ; [9] va=0x00005fa8 pa=0x00005fa8 sz=53128 vsz=53128 rwx=--r-x .text
            ;-- entry0:
            ;-- section_end..plt:
            ;-- section..text:
            0x00005fa8      0400           movs r4, r0
            0x00005faa      9fe5           b 0x5aec
            0x00005fac      0000           movs r0, r0
            0x00005fae      8fe0           b 0x60d0
```

As you can see you have more freedom than before.

**Comment by alvarofe** [comment]
I would go instead for `dh` within visual mode. `h` is taking for highlight but we already have `/` as vim for that. So for example `dhb 16` or something like that, would be used to set a direction as thumb.

**Comment by alvarofe** [comment]
I added `dh` for visual mode. I would maintain `&` because for other arch makes sense but for arm and thumb everything should be handled by anal hints.  I can change the workflow though let me know to close this or improve `dh`

**Comment by Maijin** [comment]
Well this would be confused for user, we need to use one not two different commands for this stuff.

**Comment by Maijin** [comment]
I'd keep dh and kill &
