### ISSUE TITLE
scr.wheel=true makes r2 act like a drunk pedophile judge

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6656]
#610, 3ebedda added mouse wheel support. This turns on escape codes CSI 1000 and CSI 1001 which prevent xterm highlight tracking, so you had either mouse wheel scroll or mouse tracking/copy-paste.(https://github.com/radare/radare2/issues/610#issuecomment-99848562). This was a shame, but worked. Then 5150cc8 and after that, changed the logic to try to have both, and since than doing `scr.wheel=true` and having any mouse clicks in the window cause mayhem:

- mouse clicking away and back to terminal (very often) (urxvt) makes r2 "stick", so you have to hit some key, then hit it again for it to respond. (click away , click back, 'q' -- nothing, 'q' -- quit visual )
- hex.cols keep changing, because the '[' which is the second byte of the `\x1b[M...` event gets read as "reduce cols"
- random commands, screen garbled, I guess depending on where click is, what bytes position x,y, and what r2 commands this is.

Looking into it, looks like in `parseMouseEvent()` https://github.com/radare/radare2/blob/master/libr/cons/input.c#L46 called when `scr.wheel=true` and mouse clicks, the function consumes the final 3 mouse event bytes (the first 3 `r_cons_readchar()` calls: CbCxCy) and then ANOTHER one, which belongs to the next event. This fucks up just everything and causes all these random behaviour.
I commented out the 4th  `r_cons_readchar()` from both code paths in function and weird behavior stopped, though again no copy paste when `scr.wheel=true`.
 
The added read is only meant to disable scr.wheel temporarily, so xterm can respond, but it can't do that simply by leaving garbage bytes in the input stream. I think this should change back to either/or until better solution comes. Maybe use keybinding to toggle `scr.wheel`.

**Comment by radare** [comment]
this behaviour was on purpose to allow people use the wheel and copypaste stuff just changing mode by doblecliking and then pressing a key like enter to come back to the wheel mode. not sure if there’s a better solution to this

**Comment by SchumBlubBlub** [comment]
I get it. But I saw yr talk on youtube, all about "ppl say this about r2, ppl say that about r2" and imho, this is exactly the kind of hack that makes r2 look really bad, and it masks all the other amazing stuff. And `scr.wheel` is on **by default**, that's what newcomers see.

When people pick up tool, and it start crumbling as they hold it up because of a tricky "feature" they know nothing... it just looks broken to them. I think it better decision to have scrolling OR copy-paste for now. And personally, I'd prefer copy paste. Of course it's your call.

**Comment by radare** [comment]
It was like this before but many people requested to have this as default and i get used to it. You can change this behaviour in the radare2rc

We can also make a poll :p

**Comment by Maijin** [comment]
This functionnality works.
