### ISSUE TITLE
What are valid modes for scr.nkey?

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6657]
```
[0x00000000]> e scr.nkey
flag
[0x00000000]> e?scr.nkey
            scr.nkey: Select the seek mode in visual
```
vs. documented
```
[0x00000000]> e?dbg.bep
             dbg.bep: break on entrypoint (loader, entry, constructor, main)
```

**Comment by radare** [comment]
Any command

**Comment by radare** [comment]
Err e scr.nkey=? Like it does for other eval keys

**Comment by SchumBlubBlub** [comment]
Sorry, I don't understand what that means.

Actually I don't even understand what this eval key *does*, from the help. 
Does it control behavior of  's++/s--'?

**Comment by radare** [comment]
> On 03 Feb 2017, at 15:01, SchumBlubBlub <notifications@github.com> wrote:
> 
> Sorry, I don't understand what that means.
> 
> 
[0x00000000]> e scr.nkey =?
scr.nkey = fun, hit, flag

> Actually I don't even understand what this eval key does, from the help.
> Does it control behavior of 's++/s--'?
> 
> 
it means that everytime you press n or N in visual mode it will seek to the next or previous (function, search hit or flag)

**Comment by radare** [comment]
feel free to send a pr enhancing the help message if thats not obvious for you

thx

**Comment by SchumBlubBlub** [comment]
Keep answering my questions, and I'll keep making the docs better....
