### ISSUE TITLE
pf format doc is wrong?

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6659]
```
[0x00000000]> pf?
|pf: pf[.k[.f[=v]]|[ v]]|[n]|[0][ [sz] fmt] [a0 a1 ...]
```
So in this example:
```
[0x00000000]> b 16; wb 0x12345678
[0x00000000]> pf 2xx
0x00000000 [0] {
  0x00000000 = 0x78563412
  0x00000004 = 0x78563412
}
0x00000008 [1] {
  0x00000008 = 0x78563412
  0x0000000c = 0x78563412
}
[0x00000000]> pf 2 xx
0x00000000 [0] {
}
0x00000000 [1] {
}
```
I understand 2 is "sz" here and xx is the fmt, so there is no space between `[sz]` and `[fmt]` like format help, and also `sz` is really `count`. 

If I did not understand right,  then what is:
```
[0x00000000]> pf 16 2xx
0x00000000 [0] {
}
0x00000000 [1] {
}
0x00000000 [2] {
}
0x00000000 [3] {
}
0x00000000 [4] {
}
0x00000000 [5] {
}
0x00000000 [6] {
}
0x00000000 [7] {
}
0x00000000 [8] {
}
0x00000000 [9] {
}
0x00000000 [10] {
}
0x00000000 [11] {
}
0x00000000 [12] {
}
0x00000000 [13] {
}
0x00000000 [14] {
}
0x00000000 [15] {
}
```
which is the same output as `pf 16 xx`. And the result is not 16 double-field structs, and 16 bytes-worth of double-field struct (two structs, of 2*4 bytes each), which are the only two things I can think mean.

So:

**Comment by radare** [comment]
send a pr fixing this, it takes less time than explaining

**Comment by SchumBlubBlub** [comment]
Ok, but what's the right behavior?

**Comment by SchumBlubBlub** [comment]
Opened PR to fix pf string but still have question about `Cf`.

Is it on purpose that `sz` argument is independent of size implied by fmt string?
Is there reason to Cf a struct that take up 16 bytes in memory, but have it advance the disassembly offset by something != 16 bytes?
