### ISSUE TITLE
Individual commands appended with ? don't give their own help

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6660]
Just a little annoyance. I should be a ble to get the help for a specific command.
The grammer may be a problem, because badly some existing commands have ? suffix as part of the name.

```
[0x00000000]> pdf?
p: Cannot find function at 0x00000000
```
```
[0x00000000]> pd?~pdf
| pdf        disassemble function
```

**Comment by radare** [comment]
no command have ? as part of the name, its just that the pdf command have no help.

pdf? is not ac ommand by itself. its just not handling the help. feel free to send a pr for that, its only 2 lines of c

**Comment by SchumBlubBlub** [comment]
> no command have ? as part of the name
```
[0x00000000]> e?
|Usage: e [var[=value]]Evaluable vars
| e?asm.bytes     show description
| e??             list config vars with description
[0x00000000]> pf?
|pf: pf[.k[.f[=v]]|[ v]]|[n]|[0][ [sz] fmt] [a0 a1 ...]
| Commands:               
| pf?                     Show this help
| pf??                    Format characters
| pf???                   pf usage examples
```

`pf??` does not give help about the `pf?` command, so `pf??` is itself a command.

> , its just that the pdf command have no help.

Yeah, I meant that every command suffixed with '?' should at least print its own description, even if there's no more detailed help. something like `xyz?` -> `xy?~xyz`.

But the way the parsing with nested switch statements this is hard to do cleanly without changing how all parsing is done. Not a good PR to start with.
