### ISSUE TITLE
radare2book claims ?doc have error

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6662]
Found here: https://github.com/radare/radare2book/blob/master/crackmes/avatao/01-reverse4/vmloop.md

```
r2 tip: You can move the selected node around in graph view using the HJKL keys. The ? documentation needs to be fixed on this part though: the move node (HJKL) and the move canvas (hjkl) keys are swapped there.
```

either the book or the ? docs are wrong.

**Comment by Maijin** [comment]
You can open issue on radare2book repo https://github.com/radare/radare2book I'm fixing this
