### ISSUE TITLE
Running drp in .radare2rc has no effect

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6667]
https://github.com/radare/radare2/issues/6652#issuecomment-277240298

**Comment by radare** [comment]
the profile is set several times because it switches between the one in the analysis, the one in the debug and its reloaded again after the process is loaded because it can be 32 or 64bit the target. radare2rc runs before that happens. is orax really anoying you that much? :D

**Comment by SchumBlubBlub** [comment]
![img](https://cloud.githubusercontent.com/assets/25528402/22594683/fc31f584-ea1b-11e6-935d-b96f25e97292.gif)
 
screws the column align, yeah annoying. Also spent hours looking through intel sw dev manuals looking for I never heard of this register. its not a thing, just an r2 cross-architecture device, right?
that SN register is abstraction.

**Comment by radare** [comment]
just change the profile to put it at the end

not na issue for me:

**Comment by radare** [comment]
you must apply this patch: feel free to test and submit the change in a PR (review all the x86 profiles)

**Comment by SchumBlubBlub** [comment]
https://github.com/radare/radare2/pull/6674 is a good enough fix for me, so drp not needed.
