### ISSUE TITLE
rasm2 cant assemble instruction

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6689]
``` 
$ rasm2 -a x86.nz "movzx eax, byte [eax]"
Cannot assemble 'movzx eax, byte [eax]' at line 3
invalid
```

Update:
```
$ rasm2 -a x86.nz 'movsx eax, al';        
Cannot assemble 'movsx eax, al' at line 3
invalid
```

**Comment by Maijin** [comment]
Can you add test for that ?

**Comment by SchumBlubBlub** [comment]
Wrote a fuzzer, theres dozens.

**Comment by Maijin** [comment]
x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```

**Comment by SchumBlubBlub** [comment]
tx. but there are 100s of cases (so far) and this is a solved problem with keystone. I don't want to spend time on it.

Glad to post the fuzzer if you like.

Is in poor shape:
```
$ rasm2 -d 8d154b2c0000
lea edx, [0x2c4b]
$ rasm2 -a x86 'lea edx, [0x2c4b]'
8d154bb10000
$ rasm2 -da x86 8d154bb10000
lea edx, [0xb14b]
```

**Comment by Maijin** [comment]
Yes please post the fuzzer

**Comment by SchumBlubBlub** [comment]
https://github.com/radare/radare2/pull/6693

I was using "-a x86", so was testing captsone. `x86.nz` does much better.

**Comment by radare** [comment]
If you have keystone installed it will override the x86.nz one as defaults. Feel free to report those issues to the keystone project

**Comment by aquynh** [comment]
lets make Keystone the default assembler :-)

**Comment by SchumBlubBlub** [comment]
> If you have keystone installed it will override the x86.nz one as defaults. 

capstone. and the problem is not the default its that "x86" is listed as capstone in "rasm2 -L", and if I request it with "rasm2 -a x86" I don't get it. once I install keystone, how do I request capstone?

> Feel free to report those  issues to the keystone project

capstone.

**Comment by radare** [comment]
Keystone cant be the default for different reasons:

- too big, dont wanna make r2 bigger (actually capstone is the reason why r2 is that big). Also because its linked more than once
- its written in c++
- most people just want to disassemble in r2land, the ones who assemble do it just for ptching, so our small assemblers are mostly ok in many situations
- keystone is not much tested by us (yet)

> On 5 Feb 2017, at 02:36, SchumBlubBlub <notifications@github.com> wrote:
> 
> If you have keystone installed it will override the x86.nz one as defaults.
> 
> capstone. and the problem is not the default its that "x86" is listed as capstone in "rasm2 -L", and if I request it with "rasm2 -a x86" I don't get it. once I install keystone, how do I request capstone?
> 

Capstone is a disassembler not an assembler. If you do -a x86 you get capstone. Its the default.

**Comment by Maijin** [comment]
`- keystone is not much tested by us (yet)`, false.

**Comment by SchumBlubBlub** [comment]
> Capstone is a disassembler not an assembler. If you do -a x86 you get capstone. Its the default.

Thanks, everything make sense now. I updated the fuzzer script above and it does find many issues in x86.nz. Because I use an disasm/asm/disasm loop, can't tell automatically if problem is in asm or disasm engine, but I manually check and at least some of it is in x86.nz, like the example I gave:
```
rasm2 -a x86.nz 'lea edx, [0x2c4b]'
8d154bb10000                               
```
opcodes are wrong.

**Comment by Svenito** [comment]
Thanks for the fuzzer. This will help me work through some of the issues and missing features of nz.

**Comment by SchumBlubBlub** [comment]
Glad to help. :handshake:
