### ISSUE TITLE
Add support for Infineon products

### ISSUE THREAD

**Issue by montekki** [radare/radare2#670]
TriCore and microcontrollers like xc2700. They are widely used in automotive.
![infineon1](https://f.cloud.github.com/assets/56672/2292350/98f94514-a057-11e3-9f00-5d7a6c648a19.jpg) 
![infineon2](https://f.cloud.github.com/assets/56672/2292355/a8ad048c-a057-11e3-8740-ccdcdbf32b08.jpg)

* http://www.keil.com/dd/docs/datashts/infineon/c166ism.pdf

**Comment by Maijin** [comment]
https://www.hightec-rt.com/en/downloads/sources/14-sources-for-tricore-v3-3-7-9-binutils-1.html ?

**Comment by Maijin** [comment]
\o/

**Comment by radare** [comment]
Theres no anal plug yet. Or even tests for it. Plz halp

**Comment by csarn** [comment]
[Bugfix for tricore disassembly](https://github.com/radare/radare2/pull/4644)

**Comment by inferiorhumanorgans** [comment]
I'm currently working on this:

https://github.com/inferiorhumanorgans/r2-c166
