### ISSUE TITLE
Thumb/arm detection bug

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6703]
See https://github.com/radare/radare2-regressions/commit/a0f244bd1f2e39d7534af841a07cccf506bf6fd9

![image](https://cloud.githubusercontent.com/assets/1408600/22631174/5bb14fcc-ec07-11e6-9939-94991bbc6cc0.png)

**Comment by radare** [comment]
cc @alvarofe

**Comment by alvarofe** [comment]
I pushed something related. Could you try now? Do we have this binary on r2r? is this test `ELF ARM: thumb/arm switch`?

**Comment by alvarofe** [comment]
It should be fixed now I think, although the test should be update imho changing the size. However, I will look better tomorrow and maybe put these fixes in other place to make it globally not just under `af` command but in `r_anal` api

**Comment by Maijin** [comment]
Only fixed for `af`, need to be fixed for `aa` too.

**Comment by alvarofe** [comment]
So with `aa` and other commands is broken. Let me tomorrow fix it properly but the issue is located

**Comment by alvarofe** [comment]
Also I've seen that I can clean up the code when swapping asm.bits and so on due to now everything is handled with anal.hints making it easy

**Comment by alvarofe** [comment]
I did push a fix for this and there is just one test when running in local failing (it might be more than that dunno) and now it detect more functions so it may be an improvement.

**Comment by Maijin** [comment]
Perfect fixed.
