### ISSUE TITLE
libr_debug.so: undefined reference to `linux_attach_new_process'

### ISSUE THREAD

**Issue by sre** [radare/radare2#6704]
Debian's buildfarm fails to build from source for arm64, mipsel & mips64el, s390x, sparc64 & m68k. I build those architectures with --disable-debugger, since I've been told its not properly working on them.

https://buildd.debian.org/status/package.php?p=radare2&suite=experimental

(1.2.0 & 1.2.1 were too late for the Debian freeze. Packages will end up in experimental until stretch is released)

**Comment by radare** [comment]
Pls confirm

**Comment by sre** [comment]
I just uploaded r2 1.2.1 with this patch cherry-picked. Let's see if buildfarm is happy now. Looks like --disable-debugger is a problem regularly. Maybe you could add a target to one of the CI systems radare uses?

**Comment by sre** [comment]
Some of the mentioned architectures are still building, but the fast ones (e.g. s390x) are already done and built successfully - Fix Confirmed.

**Comment by radare** [comment]
Awesome. Thanks
