### ISSUE TITLE
Build problem on Debian GNU Hurd

### ISSUE THREAD

**Issue by sre** [radare/radare2#6705]
Hi,

The new ioctl stuff breaks the hurd built:

https://buildd.debian.org/status/fetch.php?pkg=radare2&arch=hurd-i386&ver=1.2.1%2Bdfsg-1&stamp=1486332271&raw=0

-- Sebastian

**Comment by radare** [comment]
This is related to r2k

**Comment by radare** [comment]
<img width="823" alt="screen shot 2017-02-06 at 01 58 03" src="https://cloud.githubusercontent.com/assets/917142/22631555/c2c5ac82-ec0f-11e6-9264-390360b0b8b3.png">

**Comment by P4N74** [comment]
@sre can you please verify is [this](https://github.com/radare/radare2/pull/6706) fixes the gnu hurd build?
Thank you :)

**Comment by sre** [comment]
FYI: With the patch applied Debian's hurd-i386 buildserver build r2 successful.
