### ISSUE TITLE
Multiple io issues

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6707]
```
$ r2 -
[0x00000000]> pxQ 8 < /dev/urandom   # slurp fails
Slurping file '/dev/urandom'
cannot open file
0x00000000 0x0000000000000000
[0x00000000]> pxQ 8 < /etc/os-release # slurp fails
Slurping file '/etc/os-release'
0x00000000 0x0000000000000000
[0x00000000]> "pxQ 8~[1] < /dev/urandom" # quietly fails
0x00000000 0x0000000000000000 
[0x00000000]> o /dev/urandom
7
[0x00000000]> o 7
[0x00000000]> pxQ 8~[1]   # ok
0xe44a83bd732a64a5
[f000:fff0]> pxQ 8~[1] < /etc/os-release  # clever fail
Slurping file '/dev/urandom'
cannot open file
0xaf5da155cf286e93
[0x00000000]>  o /dev/random   # hang fail
```

Can't repro, maybe rare value from /dev/urandom trigger, fuzz?
```
[0x00000000]> pxQ 8~[1] < /dev/urandom
Slurping file '/dev/urandom'
cannot open file
0x0000000000000000
[0x00000000]> pxQ 8~[1] < /dev/urandom
Slurping file '/dev/urandom'
cannot open file
0x0000000000000000
[0x00000000]> o /dev/urandom; pxQ 8~[1];
9
0x000ffff0 0xfa3a98a09e6a774e     #suddenly works?
[f000:fff0]>  # ??? addr
```

**Comment by radare** [comment]
the < is not suposed to work it was implemented in r1 and caused many user confusion and problems with batch mode.

**Comment by radare** [comment]
so it was disabled in r2 and i vote for killing it, but some ppl is recently asking for this for the debugger.. which have a different meaning than this slurping here..

**Comment by SchumBlubBlub** [comment]
I think is useful for oneliner if it worked. ok to kill, but if not than should be sane.

**Comment by radare** [comment]
we need to discuss this properly and evaulate its use cases, pros and cons

imagine a user copypasting text and then resulting that it needs to slurp from stdin, what if stdin is a socket? what if this command is running in background? or via the webserver?

yes its useful.. but definitly comes with lot of problems

**Comment by SchumBlubBlub** [comment]
so your saying if some can get me to paste arbitrary commands into r2, than right now i'm protected from pwnage? XD. looks like no difference.

**Comment by radare** [comment]
Just enable the cfg.sandbox if u are afraid ofthis. And yes you cant protect from r2 slurping from stdin if the command is issued by r2pipe, webserver etc. So yep its quite different problem

**Comment by Maijin** [comment]
Ok not a bug.
