### ISSUE TITLE
Various command parsing glitches

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6711]
- `pf.` produces `pf*` output
- `pf* 2xi` doesn't do right thing because it doesn't handle the array right.
- `pfs` shows size of single element when array format is given, ie `pfs 16xi` -> "8 bytes"
- pfd 2xi gives malformed output, should either handle non-named formats, or give error message.
- `pfj.elf_header` and `pfj elf_header` work the same, but `pfj 2xi` works while `pfj.2xi` doesn't.

All are simple enough to fix, but I find more and more of this. Maybe at some point its time to redo the parsing of r2 to be more formal? whack-a-mole.

https://github.com/radare/radare2/pull/6681
https://github.com/radare/radare2/pull/6681/commits/06435fd729dca4cb74210a0778ff097472eb66b4

**Comment by Maijin** [comment]
So what about this ? Fixed ?
