### ISSUE TITLE
libr/reg/arena.c:r_reg_get_bytes

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6717]
linenumber 38 of r_reg_get_bytes, I see sz is not checked.
also buf in 46 returned regardless, whether malloc suceeds,
if I see that correct. 

can u proof me wrong ?

**Comment by condret** [comment]
no, I can't. Do you want to review siol?

**Comment by zonkzonk** [comment]
colse

**Comment by radare** [comment]
cosled
