### ISSUE TITLE
Parsing ASN1 Structures

### ISSUE THREAD

**Issue by wargio** [radare/radare2#6721]
- [ ] Export ASN1 to JSON
- [ ] Add Rbin Plugins (Low Prio)
- [x] ASN1 Parser - done but still not merged 
- [x] x509 (https://tools.ietf.org/rfc/rfc5280.txt)
- [x] PKCS 7 (https://www.ietf.org/rfc/rfc2315.txt)
- [x] x509 to JSON
- [x] PKCS 7 to JSON

more:
- [x] Add PE signature (PKCS 7) to iC

**Comment by condret** [comment]
ASN1? r u mad?

**Comment by leragequit** [comment]
do you want to extract embedded certs?

**Comment by radare** [comment]
I would prefer to have this in a plugin in extras

**Comment by Maijin** [comment]
It's useful for PE Certificate so I'd got for core

**Comment by radare** [comment]
well.. could be useful for ios other cases too.. if its not too big its ok to be in core then

**Comment by wargio** [comment]
Big? It's just 7 files (4 headers, 3 sources)

**Comment by Maijin** [comment]
awesome 👍

**Comment by XVilka** [comment]
@wargio what is the current status of this?

**Comment by wargio** [comment]
i think we can close this. @radare told me that is not needed to implement `Export ASN1 to JSON` and `Add Rbin Plugins (Low Prio)`.
