### ISSUE TITLE
binfile-id

### ISSUE THREAD

**Issue by condret** [radare/radare2#6722]
It would be great if we use the RIDPool API for generating the RBinFile->id, because we need to ensure, that the id is unique.
Can someone, who knows the RBin API very well, pls do this.

**Comment by radare** [comment]
The rbinobj thing is quite confusing. It would be great if we can inherit or reuse the same id from io or at least use the same code to generate them.

**Comment by condret** [comment]
what do you mean when you say the same id? from my perspective a binfile/binobj can refere to multiple RIODescs, one for the binary itself and the others for libraries that could be loaded too. (Yes I want to have complete emulation with library calls)

It is possible, that I missunderstood the whole RBin-Thing
