### ISSUE TITLE
Visual mode debugging commands in Visual Panel mode

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#6728]
So I'm attempting to debug an app using Visual Panel mode.  I'm curious why these commands:
~~~
Function	Keys:	(See	'e	key.'),	defaults	to:
		F2						toggle	breakpoint
		F7						single	step
		F8						step	over
		F9						continue
~~~
aren't available in Visual Panels mode?  I know you can use s/S for stepping, and I know you can use the Menu->Debug for Continue, Continue until, Step, and Step Over, but why can't you set a breakpoint?  And why do you have the "Continue until" available in Visual Panels, but not in Visual mode?    Currently you have to go back to Visual mode to set a breakpoint, and then back to Visual Panels mode.  So I guess my question/request is to have the same debug key commands available in both Visual and Visual Panels mode.  Side note, a "continue until RET" would be nice as well :)  Thank you.

**Comment by radare** [comment]
This is very simple to do. Wanna try?

**Comment by DigiAngel** [comment]
BRING IT :)

**Comment by radare** [comment]
Should be copypaste 5-10 lines from visual to vpanels

**Comment by DigiAngel** [comment]
Sounds like a snap!

**Comment by Maijin** [comment]
Copy/paste of visual.c https://github.com/radare/radare2/commit/a37af194503881f8ccf994d2f1d5e821ec14f325

**Comment by Maijin** [comment]
Well doesn't work that well. Need to be enhanced but you can check what commands are used in the menu and add it in the scr.XXX .

**Comment by DigiAngel** [comment]
Thanks...I'll give it a look :)

**Comment by Maijin** [comment]
Pull and retry, function keys should work better now in panel and graph mode.
