### ISSUE TITLE
siol - endless loop

### ISSUE THREAD

**Issue by condret** [radare/radare2#6745]
endless loop starts here https://github.com/radare/radare2/blob/siol/libr/core/cmd_search.c#L1862

i think I can take a closer look at this in the next few days, but if someone wants to fix this earlier, here is your chance.

**Comment by condret** [comment]
I believe its about this line https://github.com/radare/radare2/blob/siol/libr/core/cmd_search.c#L1883

**Comment by radare** [comment]
yay! getting closer to make travis happy
