### ISSUE TITLE
Implement @@@=

### ISSUE THREAD

**Issue by radare** [radare/radare2#6747]
`?e @@@= hello world`

must be the same as doing this:

`?e hello;?e world`

**Comment by Maijin** [comment]
Doc pls

**Comment by radare** [comment]
http://thegeekymormon.com/wp-content/uploads/2015/01/Christopher-Lloyd-as-Doc-Brown.jpg <http://thegeekymormon.com/wp-content/uploads/2015/01/Christopher-Lloyd-as-Doc-Brown.jpg>

**Comment by radare** [comment]
![](http://thegeekymormon.com/wp-content/uploads/2015/01/Christopher-Lloyd-as-Doc-Brown.jpg)
