### ISSUE TITLE
Msys2 io2k build error: p/io_r2k.c:20: undefined reference to `WriteKernelMemory'

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#6751]
```
gcc  -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/bochs/lib/libbochs.a -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/gdb/lib/libgdbr.a -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/qnx/lib/libqnxr.a -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/wind/libr_wind.a -shared -o libr_io.dll -Wl,-soname=libr_io.dll p/io_bfdbg.o p/io_bochs.o p/io_debug.o p/io_default.o p/io_gdb.o p/io_gzip.o p/io_http.o p/io_ihex.o p/io_mach.o p/io_malloc.o p/io_mmap.o p/io_procpid.o p/io_ptrace.o p/io_qnx.o p/io_r2k.o p/io_r2pipe.o p/io_r2web.o p/io_rap.o p/io_self.o p/io_shm.o p/io_sparse.o p/io_tcp.o p/io_w32.o p/io_w32dbg.o p/io_windbg.o p/io_zip.o io.o plugin.o map.o section.o desc.o cache.o undo.o buffer.o vio.o   -LC:/projects/radare2-hnku1/libr/util -LC:/projects/radare2-hnku1/libr/socket -lr_util -lr_socket    C:/projects/radare2-hnku1/libr/../shlr/zip/librz.a ../../shlr/gdb/lib/libgdbr.a ../../shlr/qnx/lib/libqnxr.a    -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/bochs/lib/libbochs.a -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/gdb/lib/libgdbr.a -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/qnx/lib/libqnxr.a -lws2_32 C:/projects/radare2-hnku1/libr/../shlr/wind/libr_wind.a
p/io_r2k.o: In function `r2k__write':
C:\projects\radare2-hnku1\libr\io/p/io_r2k.c:20: undefined reference to `WriteKernelMemory'
p/io_r2k.o: In function `r2k__read':
C:\projects\radare2-hnku1\libr\io/p/io_r2k.c:40: undefined reference to `ReadKernelMemory'
p/io_r2k.o: In function `r2k__close':
C:\projects\radare2-hnku1\libr\io/p/io_r2k.c:64: undefined reference to `StartStopService'
p/io_r2k.o: In function `r2k__system':
C:\projects\radare2-hnku1\libr\io/p/io_r2k.c:88: undefined reference to `GetSystemModules'
p/io_r2k.o: In function `r2k__open':
C:\projects\radare2-hnku1\libr\io/p/io_r2k.c:104: undefined reference to `Init'
p/io_r2k.o:io_r2k.c:(.rdata$.refptr.gHandleDriver[.refptr.gHandleDriver]+0x0): undefined reference to `gHandleDriver'
collect2.exe: error: ld returned 1 exit status
C:/projects/radare2-hnku1/libr/..//libr/rules.mk:73: recipe for target 'libr_io.dll' failed
mingw32-make[3]: *** [libr_io.dll] Error 1
mingw32-make[3]: Leaving directory 'C:/projects/radare2-hnku1/libr/io'
Makefile:91: recipe for target 'io' failed
mingw32-make[2]: *** [io] Error 2
mingw32-make[2]: Leaving directory 'C:/projects/radare2-hnku1/libr'
Makefile:28: recipe for target 'all' failed
mingw32-make[1]: *** [all] Error 2
mingw32-make[1]: Leaving directory 'C:/projects/radare2-hnku1/libr'
Makefile:47: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
C:/msys64/MINGW64/bin/mingw32-make windist WINBITS=w32
mingw32-make[1]: Entering directory 'C:/projects/radare2-hnku1'
[WINDIST] Installing binaries and libraries
```

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
i dont think you can build msys2 kernel drivers

**Comment by radare** [comment]
why do you use msys?

**Comment by XVilka** [comment]
It's on our AppVeyor - Mingw32 (+ msys1), Msys2 (mingw-w64) and Cygwin. On Windows so far is the best is Msys2 (and it's based on Cygwin).

**Comment by radare** [comment]
Cygwin is crap. Imho we should offer pure native or mingw support for windows. Supporting more targets requires more resources and we dont have enough windows contributors to maintain all that

**Comment by Maijin** [comment]
Poll twitter, get votes, offer supports for the one that are voted the most

**Comment by radare** [comment]
@skuater plz

**Comment by skuater** [comment]
working on it , im trying to build the fXXXed environment

**Comment by radare** [comment]
i think we should focus on mingw and msvc, there's no point in trying to make cygwin, msys, msys2 happy imho

**Comment by XVilka** [comment]
Original mingw32 is dying. If we want to choose only one - better to focus
on mingw-w64

On Apr 10, 2017 8:03 PM, "radare" <notifications@github.com> wrote:

i think we should focus on mingw and msvc, there's no point in trying to
make cygwin, msys, msys2 happy imho

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/radare/radare2/issues/6751#issuecomment-292929627>, or mute
the thread

**Comment by radare** [comment]
Yes i focus on that because is he only way to build r2 for windows on linux/mac

**Comment by skuater** [comment]
well this issue can be closed, with msys2 under windows the compilantion goes fine, but ... the result binary dont work correctly. Binaries buildeds have a rep nop into EP and TLScallbacks i think compilation options are wrong.

**Comment by kuh3h3** [comment]
Why this is closed? still not fixed,
LD libr_io.dll
p/io_r2k.o: In function `r2k__write':
C:\Users\kuh3h\Downloads\iaito\radare2\libr\io/p/io_r2k.c:20: undefined reference to `WriteKernelMemory'
p/io_r2k.o: In function `r2k__read':
C:\Users\kuh3h\Downloads\iaito\radare2\libr\io/p/io_r2k.c:40: undefined reference to `ReadKernelMemory'
p/io_r2k.o: In function `r2k__close':
C:\Users\kuh3h\Downloads\iaito\radare2\libr\io/p/io_r2k.c:64: undefined reference to `StartStopService'
p/io_r2k.o: In function `r2k__system':
C:\Users\kuh3h\Downloads\iaito\radare2\libr\io/p/io_r2k.c:88: undefined reference to `GetSystemModules'
p/io_r2k.o: In function `r2k__open':
C:\Users\kuh3h\Downloads\iaito\radare2\libr\io/p/io_r2k.c:104: undefined reference to `Init'
p/io_r2k.o:io_r2k.c:(.rdata$.refptr.gHandleDriver[.refptr.gHandleDriver]+0x0): undefined reference to `gHandleDriver'
collect2.exe: error: ld returned 1 exit status
make[3]: *** [/C/Users/kuh3h/Downloads/iaito/radare2/libr/..//libr/rules.mk:74: libr_io.dll] error 1
make[2]: *** [Makefile:94: io] error 2

**Comment by Maijin** [comment]
Open a new issue please.

**Comment by daddesio** [comment]
Hi, I was getting the exact same errors as @kuh3h3. The solution is to provide `--with-os=windows` to configure. This fixes all issues for me under msys2 (except for a minor issue when running the final `make w32dist`).

The default setting `--with-os=auto` causes mk/platform.pk to calculate OSTYPE based on the uname `OSTYPE=$(shell uname | tr 'A-Z' 'a-z')` but without stripping the NT version. On both MSYS1 and msys2, my uname is "MINGW32_NT-6.1", hence my OSTYPE is "mingw32_nt-6.1". Now, going over to libr/io/p/r2k.mk, we see this line:

```
ifeq (${OSTYPE},$(filter $(OSTYPE),windows mingw32 mingw64 cygwin))
OBJ_R2K += io_r2k_windows.o
endif
```

Now we see the problem. If OSTYPE is _exactly_ one of the four strings ("windows", "mingw32", "mingw64", "cygwin"), then add the required dependency. But OSTYPE isn't in the right format ("mingw32_nt-6.1"), so the check fails.

**Comment by radare** [comment]
Can we get a generic solution in a pr?

**Comment by Maijin** [comment]
As said, Open a new issue please....
