### ISSUE TITLE
Feature Request:  Next/previous function in Graph Mode

### ISSUE THREAD

**Issue by DigiAngel** [radare/radare2#6755]
Topic says it....so far my process to browse functions is:
~~~
r2 -AAA bleh.exe
v
p
space bar
space bar
N
space bar
space bar
N
...
~~~
would be nice to browse through functions with N/n just like we do in V mode.  Thank you.

**Comment by radare** [comment]
lgtm and its easy to do the only problem are the keys… 

n = rename function
N = toggle mini graph

which keys do you propose to put those two functionalities to make nN behave like in visual?

**Comment by DigiAngel** [comment]
Looks like the only key not bound is Y/y, although that's not in line
with trying to get things consistent accross screens.  I notice there's
not many alt/ctl type keys...so maybe ctl+N/ctl+n.  Otherwise the Y/y
combo could be a good choice.

**Comment by DigiAngel** [comment]
Works a treat thank you!
