### ISSUE TITLE
Big perf win possible after moving flags to use sdb instead of ht

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2#6757]
Was part of https://github.com/radare/radare2/pull/6724

In `r_flag_get_at()` the `!closest` case can be handled by direct lookup. right now this is done
in r_get_i, which uses `r_hashtable64`. But, the hashtable seems too buggy, making the change causes some failures in r2r, which debugging shows some value put into hashtable can't be read back :\

No fixes for this, because management wants to shift flags away [from ht to sdb](https://github.com/radare/radare2/pull/6750). So this blocked. but the perf win if very large.

For test case of https://github.com/radare/radare2/issues/5274#issuecomment-230157691, it is about 3 times faster. So someone should do this after flags refactor. 

https://github.com/radare/radare2/issues/2761

**Comment by Maijin** [comment]
There is no "management", why you just don't want to join IRC/Telegram to discuss those issues you mention.

**Comment by Maijin** [comment]
+ https://github.com/radare/radare2/issues/6543 
+ https://github.com/radare/radare2/issues/6518

**Comment by karliss** [comment]
Is this still relevant now that offset based flag lookups are done using skiplist?

**Comment by MaskRay** [comment]
If only `RFlagItem::offset` is concerned, a skip list suffices. If `RFlagItem::size` is also used (for example intersection query), an interval tree (https://github.com/radare/radare2/pull/8387) would be a better fit.

It is so terrible to see sdb being used everywhere even when a BST/skip list is better.

**Comment by Maijin** [comment]
Why terrible? 

At least it avoids reimplementing JSON print every damn fricking time for every print json same for quiet and double quiet output.

**Comment by ret2libc** [comment]
I don't think this thing is still relevant... there's no r_hashtable anymore. I'm closing this.

**Comment by radare** [comment]
Correct
