### ISSUE TITLE
Automatically indent the whole codebase

### ISSUE THREAD

**Issue by radare** [radare/radare2#6760]
(except what its not from us (gnu, grub, ...)) we want to autoindent all *.c under libr and binr . The plan is the following:

* [ ] Use uncrustify (seems like it got better than clang-format recently) and we miss some functionalities still
* [ ] Report all missing features in clang-format and uncrustify to the respective projects
* [ ] Remove all the sed/perl hacks in sys/indent.sh
* [ ] Add more files into the sys/indent-whitelist.sh
* [ ] Run sys/indent-whitelist.sh on every commit to ensure 

The process of re-indenting consists in:

* Review the output of `sys/indent.sh -u libr/core/foo.c`
* If the output looks good use the `-i`

If the output doesn't looks good:

* Improve uncrustify.cfg
* Improve indent.sh
* Improve the problematic .c to make it indent properly

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/3251
