### ISSUE TITLE
Invalid flag addresses in fatmach0s (work fine with mach0)

### ISSUE THREAD

**Issue by radare** [radare/radare2#6763]

**Comment by alvarofe** [comment]
Do we have a test case or does always happen?

**Comment by radare** [comment]
i think it only happens with thumb bins, but letme build a bin and wriet the test

**Comment by alvarofe** [comment]
The other day I spot an issue with thumb but is causing some breaks but fix others. Symbols in mach when comes from LC_FUNCTION_STARTS and the (addr & 1 != 0) is not updated, we already to this in ELF. So it may be the same issue and thus fail some analysis due to unaligned address.

**Comment by radare** [comment]
tests added
