### ISSUE TITLE
?@@? != @@?

### ISSUE THREAD

**Issue by radare** [radare/radare2#6766]
* [x] @? does nothing. should display the same output as ?@?
* [x] @@? shows @@ help
* [x] ?@@? shows nothing. should do the same as @@?
* [x] ~? shows 0, should be the same as ~??
* [x] ?~?? should show the same as ~??
* [x] ?@? shows correct help
* [x] ?@@?
* [x] ?~? shows 41 (maybe we want that as an alias for ~?? 
* [x] ?* in ??? help
* [x] $? - shows alias help because '$' is a command
* [x] ?$ - shows value of all the $ variables
* [x] %? - shows the same as %, it should display the help for the % command
* [x] &? - shows help of the & command
* [x] ?& - shows the same as ?, should be an alias for &? imho

**Comment by radare** [comment]
@Maijin comments on this?

**Comment by radare** [comment]
Related to https://github.com/radare/radare2/issues/6748

**Comment by cgvwzq** [comment]
In "~? shows 0, should be the same as ~??":

|   ?        count number of matching lines

How should we count the number of matching lines? Should the help be only displayed if there's no prefix, or can we just replace "~?" with "~#" or something similar?

**Comment by radare** [comment]
~? Should show the help of ~?? Only if ~ is the first char of the command, so theres nothing to grep. That will make the help more accessible

**Comment by radare** [comment]
Fixed them all!
