### ISSUE TITLE
discussion io-malloc

### ISSUE THREAD

**Issue by condret** [radare/radare2#6772]
Some say, that ````r2 malloc://32```` should allways open the malloc-plugin with rw-permissions.
I say that we should handle malloc, like every other plugin. Everything is a file, and we open every file with ro-permissions by default, so we should do so for malloc too.
Discuss please.

**Comment by radare** [comment]
the same goes for the debugger, you cant debug in read-only mode. and you can apply the same for the gdb windbg plugins.

We discussed on having the ability to open the backend in rw, but fake that in io by lowering perms at api level.. this is.. we can’t malloc in readonly, so the backend will be always RW, the same goes for ptrace, etc..

i think that r2 - should open malloc://32 in rw, but i think we need a way to make malloc:// writable without reopening, this is.. oo+ reopens in rw, but we have no way in r_io or siol to lock/unlock the write perms without reopening.

**Comment by condret** [comment]
what about giving the plugin an optional reopen-cb? so that the plugin can change the permissions

**Comment by radare** [comment]
Those permissions can be just “emulated” in io land, i dont think we want/need to delegate this logic to every plugin

**Comment by condret** [comment]
hm, maybe not to every, but to those, who can only be rw.

How do we provide this functionallity, but keep the API clean from garbage?

**Comment by radare** [comment]
maybe with `R_API bool r_io_desc_flags(RIODesc *, int flags)`

where flags can be the same as the ones for r_io_open()

and just check those desc->flags (holding the desc->oflags) when doing write()

also.. im not sure if we really need something else than just the `write` bit. do we? maybe a `debug/exec` bit too?

**Comment by radare** [comment]
if we add this debug bit we shuold check that from RDebug and this may be useful to attach to multiple programs and just disable the debug operations on some of them.. even if attached. not sure how useful will be that, because right now it is not useful for any common use case. just thinking out loud

**Comment by condret** [comment]
well, I think you want to be capable of locking the read-access in some scenarios, this might be the wrong layer for this, but the concept is needed for emulation

**Comment by radare** [comment]
Yep. Enforcing this at io level makes sense , but i will not remove that ability from esil having it in both sides makes sense to me

**Comment by condret** [comment]
I changed my mind about this, malloc can be rw by default. If ppl want ro-malloc, they should just map the whole malloc to 0 with a ro-map.
I will add a command for changing the permissions of a map, and maybe even something nice for visual-mode, where you can toggle the permissions

**Comment by radare** [comment]
Sounds good

**Comment by condret** [comment]
done

**Comment by radare** [comment]
this will fix a lot of tests!
