### ISSUE TITLE
Don't open 3 times on load

### ISSUE THREAD

**Issue by condret** [radare/radare2#6775]
atm, r2 opens every file 3 times on load. This is bad, and doesn't work for debugging on linux.
Don't do this, we should just pass the fd around.

I'm not sure if this is a thing on master, but it is on siol.

**Comment by condret** [comment]
https://github.com/radare/radare2/blob/siol/libr/bin/bin.c#L837

**Comment by radare** [comment]
You cant get symbols from memory, so fd is useless

**Comment by radare** [comment]
Use rsysbt to check the src of each open

**Comment by condret** [comment]
so you think, opening the things 3 times does any help here?

**Comment by condret** [comment]
ah, the bug is in the io-plugins. Will fix it today or tomorrow
