### ISSUE TITLE
Providing platform specific information with rabin2

### ISSUE THREAD

**Issue by condret** [radare/radare2#6785]
So ok, some ppl might feel uncomfortable, but this is needed.
Rabin2 must be cabable providing platfrom specific information to the user, stuff like the MBC-Type of a specific gameboy rom for example. This is mandatory for understanding what the rom does.

**Comment by Maijin** [comment]
Imho sdbization -> this.

That would avoid a LOT of shitty std/quiet/json output shitty code.

But yeah definitely +1

**Comment by Maijin** [comment]
Already done in fact see how PE display signed and overlay information.
