### ISSUE TITLE
Radare 2 stops dissasembly after nop

### ISSUE THREAD

**Issue by Tzeny** [radare/radare2#6791]
I used Radare2 to work on the CMU Bomb Lab. 

When running 

```
r2 bomb
aaa
pdf @ sym.fun7
```

on the file attached the output is missing the last lines:

![bug](https://cloud.githubusercontent.com/assets/6255363/22959514/aa3bfbbc-f33f-11e6-8ffd-0158282fbbf2.png)

Disassembling with gdb correctly displays the missing lines:

```
   0x08048edc <+72>:	lea    esi,[esi+eiz*1+0x0]
   0x08048ee0 <+76>:	xor    eax,eax
   0x08048ee2 <+78>:	mov    esp,ebp
   0x08048ee4 <+80>:	pop    ebp
   0x08048ee5 <+81>:	ret     
```

Radare version: 
```
radare2 1.3.0-git 13826 @ linux-x86-64 git.1.2.0-158-g0a6913a
commit: 0a6913a2e9b7167dfc55d2e9933f886efe8a40c1 build: 2017-02-15__05:21:57
```
Bomb lab binary:

[bomb.zip](https://github.com/radare/radare2/files/775978/bomb.zip)

**Comment by radare** [comment]
Use pdr, pdf is for lineal disassembly
