### ISSUE TITLE
x86.nz can assemble 64bit instructions in 32bit mode

### ISSUE THREAD

**Issue by radare** [radare/radare2#6793]
do we want to allow that? i just fixed the test to make it green.. but do we really want that?

```
$ git diff
diff --git a/t.asm/x86/udis86/x86-32 b/t.asm/x86/udis86/x86-32
index 9922d00..021781e 100755
--- a/t.asm/x86/udis86/x86-32
+++ b/t.asm/x86/udis86/x86-32
@@ -31,7 +31,7 @@ pa mov eax, 33
 pa mov rax, 33
 '
 EXPECT='b821000000
-b821000000
+48c7c021000000
 b821000000
 48c7c021000000
 '
```

**Comment by Svenito** [comment]
No, I'll fix this so that it will error if 64bit instructions are compiled in 32bit if it's explicitly specified. Of course, if the bits are not set, it will automatically switch to 64 bit mode as per #6792

**Comment by Svenito** [comment]
#6792 prevents this from being fixable. I can't tell if the bits were set explicitly or if they are the default (32).

**Comment by radare** [comment]
Fixed already, thanks @Svenito
