### ISSUE TITLE
Codingstyle: pointers

### ISSUE THREAD

**Issue by condret** [radare/radare2#6794]
Yesterday @radare made a few changes to the siol-branch, most of them codingstyle related.
Btw he changed the style of pointer declaration from ````RIO *io```` to ````RIO* io````. Since this change isn't done anywhere on master afaik, and in https://github.com/radare/radare2/blob/master/CONTRIBUTING.md#coding-style-guidelines it's not said to do so, I would like to kickoff a discussion about this.
My personal opinion is that ````RIO *io```` looks way better.

**Comment by radare** [comment]
we should adjust uncrustify too, my reasoning for doijng RIO* instead of RIO * is becase the * is more related to the type than the name

**Comment by condret** [comment]
yes, I know this, but I think both is readable. Well it just looks weird to me. thats all. I would like to hear others opinion related to this too

**Comment by alvarofe** [comment]
I am used to use `RIO *rio` but @radare's rationale makes sense. We should push stuff on the uncristify/clang-format or whatever to make this process easier and focus on the real issues. `siol` branch is such a good example of this when reading the code, coding style is not respected at all xD

**Comment by radare** [comment]
Old or new syntax seems good to me. Just vote and decide

**Comment by condret** [comment]
I prefere the old one

**Comment by radare** [comment]
Ok, let's keep the old one aka `type *varname`
