### ISSUE TITLE
ox breakage

### ISSUE THREAD

**Issue by condret** [radare/radare2#6796]
see this https://asciinema.org/a/0rbymzp6j4oqj78t56hg7ld1v maybe someone can give me a hint

**Comment by dequis** [comment]
What is `ox`? I can't find references to it anywhere in the git history.

`git log -p | grep 'exchange the descs'` gives me nothing

**Comment by radare** [comment]
What about dx #jokeoftheday

**Comment by condret** [comment]
it only exists on the siol branch, use opsiol from @alvarofe repo
