### ISSUE TITLE
ragg2-cc using wrong name for TEXT section

### ISSUE THREAD

**Issue by berney** [radare/radare2#6797]
Using the example hi.c file on MacOS Sierra.

```c
int main() {
  write(1, "hello!\n",7);
  exit(0);
}
```

Error running ragg2-cc

```
ragg2-cc -a x86 -b 32 -k darwin hi.c
llvm-gcc -arch i386 -nostdinc -include /usr/local/include/libr/sflib/darwin-x86-32/sflib.h -z execstack -fomit-frame-pointer -finline-functions -fno-zero-initialized-in-bss -o hi.c.
tmp -S -Os hi.c
clang: warning: -z execstack: 'linker' input unused
clang: warning: optimization flag '-finline-functions' is not supported
==============================
llvm-gcc -arch i386 -shared -c -nostdlib -Os -o hi.c.o hi.c.s
clang: warning: argument unused during compilation: '-shared'
du: hi.c.text: No such file or directory
Error loading 'hi.c.text'
hi.c.bin
```

r2 version
```
r2 -v
radare2 1.3.0-git 13314 @ darwin-x86-64 git.1.1.0-48-g20da3b5
commit: 20da3b53fef87d69393b479dd0764adc34f84566 build: 2016-12-26
```

llvm-gcc version

```
llvm-gcc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Troubleshooting the script I see that it is running the command `rabin2 -o hi.c.text -O d/S/0.__text hi.c.o`. This returns exit code 0 (e.g. success), but no `hi.c.text` file is created. If I pause the script halfway through and inspect the `hi.c.o` object file we see that the section is named `0.__TEXT.__text` not `0.__text`.

```
r2 hi.c.o
[0x00000110]> iS
[Sections]
idx=00 vaddr=0x00000110 paddr=0x00000110 sz=61 vsz=61 perm=m-rwx name=0.__TEXT.__text

1 sections
```

So the `TEXT` variable should be set to `0.__TEXT.__text`. I'm guessing this is a change in clang somewhere along the line.

**Comment by radare** [comment]
See ragg2-cc -s to get the disasm directly. It is a script that its easy to hack and fix that. Wanna try to send a pr?

**Comment by berney** [comment]
I fixed already for my local system but I'm not sure if it will break on older OSXes / llvm-gcc's, as it changes the behaviour.  I'd be happy send a PR.

**Comment by radare** [comment]
Tested in elcapitan and it works. The section name change was unrelated to the OS. Just related to r2.

**Comment by berney** [comment]
OK great. Thanks for merging.
