### ISSUE TITLE
flag2 == flag2

### ISSUE THREAD

**Issue by wargio** [radare/radare2#6800]
https://github.com/radare/radare2/blob/master/libr/parse/parse.c#L204

Just a nonsense and i don't know what should be the correct logic.

@radare might know how to fix.

```
if (p->relsub_addr) {
					flag2 = r_flag_get_i2 (f, p->relsub_addr);
					if (!flag2) {
						flag2 = r_flag_get_i (f, p->relsub_addr);
					}
					if (!flag && flag2 == flag2) {
						flag = flag2;
					}
}
```

**Comment by condret** [comment]
I would assume ```` if (!flag) ```` to be correct

**Comment by alvarofe** [comment]
Likely a mistake. At the end is just as condret said `if (!flag)` so send a PR to remove that warning

**Comment by radare** [comment]
Send pr
