### ISSUE TITLE
feature-request: compile/link-flags for #!c

### ISSUE THREAD

**Issue by condret** [radare/radare2#6807]
so that I can use code that links against other libs via #!c

**Comment by radare** [comment]
I would solve this by adding some go - style comments in the given C. Or maybe setting some envs with the % command.. what do you thibk? Honor CFLAGS and LDFLAGS makes sense

**Comment by condret** [comment]
i think we can close this, since I can use ````#!lib```` to break my xserver.

**Comment by radare** [comment]
It was easy and nice idea imho makes sense to have it

**Comment by Maijin** [comment]
We should gather enhancement issues into META with proper description instead of creating that many imho:

![image](https://cloud.githubusercontent.com/assets/1408600/23092612/f07ff1be-f5ce-11e6-8644-4729b5403905.png)
