### ISSUE TITLE
Implement lock command

### ISSUE THREAD

**Issue by radare** [radare/radare2#6814]
idea from @condret 

> lock password

the command will not be stored in the history and will clear the screen and ask for password. it will not unlock the console until the password matches.

**Comment by Maijin** [comment]
That sounds really useless . . .  CC @XVilka

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/5132 this is useful, lock is not.

**Comment by XVilka** [comment]
Ehm. What for?

**Comment by XVilka** [comment]
There are plenty of external tools for locking screen or particular terminal, for all kind of operating systems. I don't see a reason why it should be implemented in radare2.

**Comment by radare** [comment]
The same goes for having ls, cat.. its useful when u are using it not in your comfy desktop

**Comment by radare** [comment]
Also opens the door to have tutorials about bypassing password protection as a crackme

**Comment by Maijin** [comment]
Well that's just a if/else and there is already an issue open for that iirc.

**Comment by Maijin** [comment]
Can we lock the number of issues instead...

**Comment by radare** [comment]
you can fix something to improve the situation :P

**Comment by Maijin** [comment]
I'm trying :P

**Comment by radare** [comment]
useful when using r2 as init replacement

**Comment by Maijin** [comment]
what

**Comment by XVilka** [comment]
Can be this closed?

**Comment by radare** [comment]
Nope. Seems handy for me. It must ignore ^z. And also ive been thinking in adding file and process lock commands. Something like "wait untils this file exists", or wait until a process with this name exists.. some kind of wait+test shell

**Comment by Maijin** [comment]
I've seen this has been done.
