### ISSUE TITLE
Io and core plugins should provide autocompletion

### ISSUE THREAD

**Issue by radare** [radare/radare2#6817]
In order to have =!<tab>

**Comment by condret** [comment]
api for this pls. IO-plugins should not reimplement autocompletion, but register their commands

**Comment by radare** [comment]
Api proposal?

**Comment by XVilka** [comment]
See https://github.com/radare/radare2/issues/6609 + https://github.com/radare/radare2/issues/3033

**Comment by Maijin** [comment]
yeah so is dup of #6609 closing
