### ISSUE TITLE
F7/F8 keys for stepping code Ubuntu16 not working in VV visual graph mode

### ISSUE THREAD

**Issue by ragnargraybeard87** [radare/radare2#6823]
I've tried this with my current daily ubuntu16 machine and I installed a fresh VM to make sure, but still, everything else works as it always has except for stepping code in the graph mode with the Function keys. It works in the visual PDF display mode but not the graph mode, which is the best part!

It worked previously for me flawlessly with Linux Mint...

**Comment by radare** [comment]
Are you using r2 from git? Or at least some modern version of r2 and not the 5 years old one that comes with ubuntu?

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by ragnargraybeard87** [comment]
Hey guys, I'm definitely using the GiT Version. It didn't come installed with ubuntu:

$ r2 -v                                        
radare2 1.3.0-git 13857 @ linux-x86-64 git.1.2.0-192-g9c329d6
commit: 9c329d6c62c0c6e7feb91fa885cfac79d24ae6d2 build: 2017-02-20__13:32:48

**Comment by jgazoni** [comment]
Hello,
I got the same issue on my ubuntu 16.10, I updated r2 from GIT too yesterday.

radare2 1.3.0-git 13858 @ linux-x86-64 git.1.2.0-193-g639fda0
commit: 639fda068131aa9a2c023386d6718f70e5245269 build: 2017-02-21__12:02:47

**Comment by radare** [comment]
Which terminal are you using? Try with xterm

**Comment by Maijin** [comment]
Also step-in and step-over are s/S in Visual mode (See `?`) is this working ?

**Comment by Maijin** [comment]
It cannot work because the Function keys aren't implemented in the graph. This is same issue as https://github.com/radare/radare2/issues/6728 but for graph.c. See  https://github.com/radare/radare2/commit/a37af194503881f8ccf994d2f1d5e821ec14f325

**Comment by ragnargraybeard87** [comment]
THANK you Maijin... I'll have to remember to check that going forward...
They definitely used to be the function keys but your totally right and
everything's working as expected now. Thanks for your help :)

**Comment by Maijin** [comment]
Read both answer please.

**Comment by Maijin** [comment]
Pull and retry, function keys should work better now in panel and graph mode.
