### ISSUE TITLE
~ bug

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6824]
valgrind: http://sprunge.us/JCjg

```
,r2 -v
radare2 1.3.0-git 13857 @ linux-x86-64 git.1.2.0-192-g9c329d6
commit: 9c329d6c62c0c6e7feb91fa885cfac79d24ae6d2 build: 2017-02-20__20:19:05

```

**Comment by radare** [comment]
The crash have nothing to do with ~, i have fixed the first warning in the valgrind log but you didnt shared any reproducer so i cant determine if its fixed or not. please try again

**Comment by zonkzonk** [comment]
@radare can't reproduce in
,r2 -v
radare2 1.3.0-git 13860 @ linux-x86-64 git.1.2.0-195-g72794dc
commit: 72794dc build: 2017-02-22__02:24:36

Thanks!
