### ISSUE TITLE
Types: Structs in structs not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#6826]
```
struct foo {
  
};
struct bar {
  struct foo lala;
  struct foo bar;
};
```

**Comment by radare** [comment]
@oddcoder how to express this in sdb? can we have a test?

**Comment by oddcoder** [comment]
we already discussed why r2 parser does that incorrectly with @XVilka ? not sure if he fixed that or not

**Comment by XVilka** [comment]
Not yet. It requires big changes in tcc code. Still, this seem the only
way.

**Comment by radare** [comment]
I dont think this will be more than 3 lines of changes in tcc

**Comment by radare** [comment]
in C:
```
struct foo { int x; struct bar moo; }
```

in SDB:
```
foo=struct
struct.foo=x,moo
struct.foo.x=int,0,0
struct.foo.moo=bar,4,0
```

in PF:

```
pf x? x (bar)moo
```

**Comment by radare** [comment]
this is how it works now:
we miss the struct info in the format string
```
[0x00000000]> "td struct bar { int a; int b; }; struct foo { int x; struct bar moo; }"
[0x00000000]> ts
foo
bar
[0x00000000]> ts foo
pf ddd x a b
[0x00000000]> ts bar
pf dd a b
[0x00000000]>
```

**Comment by radare** [comment]
This is the funny thing:

```
[0x00000000]> "td struct foo { int x; struct bar moo; }"
--> int (x)
--> struct bar (moo)
[0x00000000]> pf
[0x00000000]> ts foo
pf d x
[0x00000000]> "td struct bar { int a; int b; };"
--> int (a)
--> int (b)
[0x00000000]> ts foo
pf ddd x a b
[0x00000000]>
```

the ts command must be enhanced to show better output:

* default output should be in C syntax
* add ts* command to print the pf line
* this pf line should use ? (structName)fieldName

tcc is already parsing this properly and loading it properly into sdb, so its not a problem in tcc

**Comment by XVilka** [comment]
Should be fixed. But please check, etc.

**Comment by Maijin** [comment]
yep

**Comment by radare** [comment]
Add tests please
