### ISSUE TITLE
Types: Array of structs not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#6827]
```
td struct bar { int a; int b; };
td struct foo { int x; struct bar moo[5]; }
```

Similar to https://github.com/radare/radare2/issues/6826

**Comment by oddcoder** [comment]
this one needs only support from tcc ...

**Comment by radare** [comment]
@oddcoder : I am not sure about pf but for the types db it should be like
```
foo=struct
struct.foo=x,moo
struct.foo.x=int,0,0
struct.foo.moo=bar,4,0
```

**Comment by radare** [comment]
tcc supports that already, but its not exported to sdb, we need a test case and tcc can be easily tweaked by adding printfs here and there to find the place to create those sdb entries. it's kinda easy.

**Comment by radare** [comment]
but we need to know if pf supports this. iiirc it does not.. and write tests

**Comment by Maijin** [comment]
Already supported by pf and tested

**Comment by Maijin** [comment]
i have stripped the header32 to show you example:

```
pf.pe_image_optional_header32 [16]? (pe_image_data_directory)dataDirectory
pf.pe_image_data_directory xx virtualAddress size
```

**Comment by oddcoder** [comment]
can you give a test case for what exactly isn't working?

**Comment by radare** [comment]
<img width="762" alt="screen shot 2017-03-12 at 23 46 08" src="https://cloud.githubusercontent.com/assets/917142/23836784/261bd20a-077e-11e7-9fdb-581ce406cbf2.png">

**Comment by radare** [comment]
Alreaddy did

**Comment by Maijin** [comment]
Already did what ?

**Comment by radare** [comment]
already explained where the problem is

**Comment by radare** [comment]
ping @oddcoder ?

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
ping @XVilka

**Comment by XVilka** [comment]
@sivaramaaa please check this one too.
