### ISSUE TITLE
Patching PEs results in a bad format

### ISSUE THREAD

**Issue by m73** [radare/radare2#6835]
This has happened twice to me now (of two times tried). I was patching, i.e. just overwriting some instructions with r2 -w. Afterwards I can't execute the binary and I'm told it's badly formatted. Also, the size of the file increases. In this last try it increased from 124K to 128K. This was done on Linux.

**Comment by radare** [comment]
test or gtfo

**Comment by m73** [comment]
Ok, sorry. I looked further into this. Turns out this is similar to "BUG 2" this issue: https://github.com/radare/radare2/issues/3707, except I was doing this on a PE file and the added length always seems to be 4K and Windows 7 says it's not a valid Win32 application when I try to run it.

So to reproduce, do a small insertion on a PE file through visual mode (for example mini.exe in the tests directory). Try to run it in Windows.

**Comment by radare** [comment]
Happens in the siol branch too?

**Comment by m73** [comment]
Yes.

**Comment by radare** [comment]
cant reproduce. please provide proper test

https://asciinema.org/a/7ecxkeiqgkh7dsny50h8tqlf1 <https://asciinema.org/a/7ecxkeiqgkh7dsny50h8tqlf1>

**Comment by m73** [comment]
Ah, sorry, I forgot building. A nonissue then!

**Comment by Maijin** [comment]
Forgot building what ?

**Comment by m73** [comment]
Running ``sys/build.sh`` after switching branch.

**Comment by m73** [comment]
On the siol branch, I can't seem to patch the PE I was going to patch to begin with in visual mode. My insertions are not reflected in the hex or disassembly at least. Not sure why I could patch the other one I tested on, but I think it has something to do with some seek address mismatch that happens between what is shown in visual mode and on the command line.

This branch is in the works though it looks like. I'll just use commands on the master branch for now for what I needed since that works.

**Comment by Maijin** [comment]
Thanks testing siol @condret please see
