### ISSUE TITLE
Simplify header information

### ISSUE THREAD

**Issue by radare** [radare/radare2#6840]
this how we should just reuse what's in r2 -nn to extract the prettyprinted form .. so imho the iH should be implemented using this to avoid duplicating the parser

```
[0x00000000]> pf.mach0_header
      magic : 0x00000000 = 0xfeedfacf
    cputype : 0x00000004 = 0x01000007
 cpusubtype : 0x00000008 = 0x80000003
   filetype : 0x0000000c = 0x00000002
      ncmds : 0x00000010 = 18
 sizeofcmds : 0x00000014 = 1800
      flags : 0x00000018 = 0x00200085
[0x00000000]> pf*mach0_header
f magic=0x00000000
f cputype=0x00000004
f cpusubtype=0x00000008
f filetype=0x0000000c
f ncmds=0x00000010
f sizeofcmds=0x00000014
f flags=0x00000018
```

**Comment by radare** [comment]
The r2 -nn thing is achieved via `rabin2 -rk'*' `

**Comment by radare** [comment]
So, imho the solution to this is to converge them into:

* unify all that stuff into iH
* iH* should be the same as rabin2 -rk* ..
* iHj must be done
* iH should be the human friendly output.. but iHH aims to be more than 

Is the current RBinField model enough to hold all that information? this is just a k=v with pa,va,name,comment ...

**Comment by radare** [comment]
Another important thing is that we want to have some comments from iH* loaded into r2, for example in DEX, the information about local function registers, function signature information, etc.. like it's done in ELF sections->comment... but for iH.. this info must be exposed by the bin plugins into the RBInFields and core/cbin.c must expose that into r2 with flags and comments.

The thing is... we probably need to do something with vaddr and paddr in the rbinfields in order to only load the data that fits the current VA model.. for example.. i would go for killing r2 -nn, and just allow a way to make r2 -n parse the header and load the info like `oa` or `.!rabin2 -r ..`.

So if we have loading with r2 -n we want to load the `rabin2 -rH` fields to know where are the header fields and load the pf format descriptions for each of those (yes, we need to add a char*format field inside RBinField too). To make rabin2 -rk fit into iH..

If we are in VA mode, we shouldnt load this info unless we are in PA or PAVA modes

**Comment by radare** [comment]
User experience fixed in 81832436e027aeac3da11fbb4bbb7d5f66a24a64

**Comment by radare** [comment]
The internals are still to be improved. But that's something we will do from time to time, so closing this issue for now

**Comment by radare** [comment]
this how we should just reuse what's in r2 -nn to extract the prettyprinted form .. so imho the iH should be implemented using this to avoid duplicating the parser

```
[0x00000000]> pf.mach0_header
      magic : 0x00000000 = 0xfeedfacf
    cputype : 0x00000004 = 0x01000007
 cpusubtype : 0x00000008 = 0x80000003
   filetype : 0x0000000c = 0x00000002
      ncmds : 0x00000010 = 18
 sizeofcmds : 0x00000014 = 1800
      flags : 0x00000018 = 0x00200085
[0x00000000]> pf*mach0_header
f magic=0x00000000
f cputype=0x00000004
f cpusubtype=0x00000008
f filetype=0x0000000c
f ncmds=0x00000010
f sizeofcmds=0x00000014
f flags=0x00000018
```

**Comment by Maijin** [comment]
See META Rabin2
