### ISSUE TITLE
r2pm cannot install packages

### ISSUE THREAD

**Issue by mr6r4y** [radare/radare2#6847]
Hi,
In the latest:
    `radare2 1.3.0-git 13902 @ linux-x86-64 git.1.2.0-236-g8d2f8c5`
    `commit: 8d2f8c5495fafeac088a6619827a01450cf926f9 build: 2017-02-25__07:10:23`

r2pm cannot determine `R2HOMEDIR` variable due to changed help message of `r2 -hh`:
    
    `export R2HOMEDIR="`r2 -hh | grep '^ RHOMEDIR' | awk '{print $2}' 2> /dev/null`"` 

That leads to incorrect path for the plugins directory and r2pm fails with Permission denied error.

**Comment by radare** [comment]
Fixed in b2af808da7bf0c2bd95368a56b0461af035ff6cb
