### ISSUE TITLE
s- not working after dc

### ISSUE THREAD

**Issue by radare** [radare/radare2#6855]

**Comment by radare** [comment]
I think that we should seek_push before running any `sr PC` or so, this way we will get the updated prompt after the breakpoint, but stored in the history for having it back

**Comment by radare** [comment]
THIS IS A QUESTION; ANYONE HAVE ANY THOUGHS ON THIS?

**Comment by XVilka** [comment]
Sounds reasonable, yes.

**Comment by radare** [comment]
Its fixed now
