### ISSUE TITLE
Support specifying calling conventions from command line

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#6856]
Like for
```
    int __usercall func@<ebx>(int x, int y@<esi>);
```
Or "__userpurge" calling convention. It is the same thing as __usercall, the only difference is that the callee cleans the stack.

**Comment by radare** [comment]
This seems like the syntax that should be used to write all the types/d/* files

**Comment by Maijin** [comment]
Not really.

But I think we can add more XXXX=YYYY to define such case check with @oddcoder

**Comment by oddcoder** [comment]
this is already there 
search for `func.X.cc=calling_convention` here https://github.com/radare/radare2/blob/master/doc/types.md
it just lack support from tcc parser inside radare, but the functionality already exist and it is in use

**Comment by oddcoder** [comment]
oh I am sorry I thought of this as something else, but yeah why would someone add new calling conventions during analysis, it is more conventient to have them in a db and load it

**Comment by radare** [comment]
Please send a pr

**Comment by XVilka** [comment]
@sivaramaaa and this one

**Comment by radare** [comment]
i think this syntax is a bit ugly and we can do better. it is important for you to be compatible with this?

**Comment by radare** [comment]
ping @sivaramaaa

**Comment by XVilka** [comment]
@radare it is syntax IDA Pro uses, so compatibility is not required. So if you have an idea of better syntax - please share.

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/commit/76c48193795c74436030ed6697188a816915a346
