### ISSUE TITLE
'aflj' showing callrefs referencing own function

### ISSUE THREAD

**Issue by pinkflawd** [radare/radare2#6858]
Function (part of aflj dump) at 4228544 contains a call reference to 4228544, thus referencing itself. Not sure whether this was intention or not? Seems wrong. 
This issue can be seen with all functions visible within aflj output.

```
{
"callrefs": [
            {
                "addr": 4228544, 
                "at": 4217103, 
                "type": "C"
            }
        ], 
        "calltype": "cdecl", 
        "cc": 1, 
        "codexrefs": [
            {
                "addr": 4217103, 
                "at": 4228544, 
                "type": "C"
            }
        ], 
        "cost": 3, 
        "datarefs": [
            4231392
        ], 
        "dataxrefs": [], 
        "diff": "NEW", 
        "difftype": "new", 
        "ebbs": 1, 
        "edges": 0, 
        "indegree": 1, 
        "name": "fcn.004085c0", 
        "nargs": 0, 
        "nbbs": 1, 
        "nlocals": 0, 
        "offset": 4228544, 
        "outdegree": 1, 
        "realsz": 6, 
        "size": 6, 
        "type": "fcn"
}
```

**Comment by pinkflawd** [comment]
Example attacked, password infected
[unpacked_4962451.zip](https://github.com/radare/radare2/files/804904/unpacked_4962451.zip)

**Comment by Maijin** [comment]
use

```
CODE
```

**Comment by lowlyw** [comment]
@pinkflawd this is a ref-to. you can check it by doing

`axt`

```
[0x0040590f]> axtj 4228544
[{"from":4217103,"type":"C","opcode":"call 0x4085c0"}]
[0x0040590f]> pd 1 @ 4217103
            0x0040590f      e8ac2c0000     call 0x4085c0
```

**Comment by pinkflawd** [comment]
Hello! I might still be wrong, but actually think this IS a bug. If nothing grave changed within the aflj output, the callrefs should list the references to local functions from within a function. Correct me if I'm wrong..

With this assumption, parsing the callrefs out of the command, I can generate call graphs like the following, or at least thats how the graph should look like:

![old_bot exe](https://cloud.githubusercontent.com/assets/5487036/23804894/1385b80e-05bc-11e7-9172-6869bbe66246.png)

Meanwhile, since I updated my graphs look like this:

![new_bot exe](https://cloud.githubusercontent.com/assets/5487036/23805018/7f5469c2-05bc-11e7-93c0-76aa016ab7f2.png)

Please note the reference to self, now visible for almost all nodes.

**Comment by rlaemmert** [comment]
is it possible that the added binary is wrong?
<code>
0x004085c0      jmp dword [sym.imp.KERNEL32.DLL_RtlUnwind]
</code>
Thats the code at the mentioned address.

**Comment by pinkflawd** [comment]
Dont think its the wrong one, why? The function at 0x4085c0 is a thunk, all it does is jump to RtlUnwind. Is this the confusion?

**Comment by rlaemmert** [comment]
you said 4228544 is referencing itself but this position is just a jmp to RtlUnwind, how do i reproduce your issue?

**Comment by radare** [comment]
ping

**Comment by pinkflawd** [comment]
I discussed this with @crowell on telegram? 4228544 is a thunk offset, which is a function for radare, which has a xref on itself. He said, I quote, "oh, shit i think i see what the issue is", but not sure what he saw then ^^

**Comment by rlaemmert** [comment]
would be cool if he can share this 'o shit' moment with us ^^
