### ISSUE TITLE
rabin2 -L <pluginname>

### ISSUE THREAD

**Issue by radare** [radare/radare2#6861]
Should display the info of the plugin in a proper structured way for humans.

display version, authors, description, paths of the plugin, etc..

**Comment by jroimartin** [comment]
@radare I'm taking care of this one.

**Comment by jroimartin** [comment]
Working implementation at https://github.com/jroimartin/radare2/tree/issue-6861

**Comment by Maijin** [comment]
Can you also add it for `iL [plugin]` too ?

**Comment by jroimartin** [comment]
@Maijin sure thing. Already implemented in the PR.

**Comment by Maijin** [comment]
Perfect !

**Comment by radare** [comment]
Fixed. Next time use "Fix #..." in the commit message next time
