### ISSUE TITLE
-I commando injection :)

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#6866]
```
r2 -I /etc/passwd /bin/ls
passwd contains in line 9: pd 5
```

**Comment by zonkzonk** [comment]
,r2 -v
radare2 1.3.0-git 13932 @ linux-x86-64 git.1.2.0-261-g1f60e30
commit: 1f60e308079f8d9b6eaca7278b69e2fcfceb4ec9 build: 2017-02-28__21:05:13

**Comment by Maijin** [comment]
`     -I file     Run script file. Before the file is loaded`

**Comment by zonkzonk** [comment]
it is from untrusted source:

```
,cd /tmp/
,ls
serverauth.4ete71lgy8  systemd-private-ede47d94d34c4642a60e0d2ebd536e4a-rtkit-daemon.service-6KXhDL
,vim nn
,touch A
,r2 -I nn /bin/ls
 -- Now with more better English!
[0x00404870]> q
,ls
nn  serverauth.4ete71lgy8  systemd-private-ede47d94d34c4642a60e0d2ebd536e4a-rtkit-daemon.service-6KXhDL
,
```

**Comment by radare** [comment]
Untrusted source? U r telling r2 to run commands from file. Thats the expected behaviour. That will not work in sandbox mode for example. I dont see any issue here
