### ISSUE TITLE
ARM 4th ADD operand ignored for emulation

### ISSUE THREAD

**Issue by yawkat** [radare/radare2#6884]
**Test case:**

```
NAME="r1=0, add r0, r1, 4, 2 -> 1"
BROKEN=
FILE=malloc://0x200
CMDS='
e asm.arch=arm
e asm.bits=32
ar r1=0
wx 040181e2
aes
ar r0
'
EXPECT='0x00000001
'
run_test
```

Actual result is `0x00000004`.

**Description:**

ARM register+immediate data instructions may include a "rotate-right" value. This value is usually inlined into the immediate value by gnu disasm (and I believe capstone), but in cases where the resulting shifted value could be encoded with a smaller shift, the shift is not applied and instead returned as a 4th parameter. The ARM asm->ESIL transformation [ignores this parameter](https://github.com/radare/radare2/blob/master/libr/anal/p/anal_arm_cs.c#L790-L820), leading to wrong emulation.

The "modified immediate constants" that provide this feature are used in many ARM instructions, including other data instructions such as AND, SUB, etc. r2 appears to support the fourth parameter for none of these.

**Comment by Maijin** [comment]
PR the test on r2r
