### ISSUE TITLE
Write extending commands do not do what they say they do

### ISSUE THREAD

**Issue by neutralinsomniac** [radare/radare2#6889]
https://asciinema.org/a/44z3e37szsws2hfncvds05j9d

Using any of the "we?" commands with an offset other than 0 results in the filesize being extended by (what appears to be) offset + size instead of just size.

Tried both with:
radare2 1.2.0 43 @ darwin-x86-64 git.1.2.0
commit: 3e16b495db6ca792dc5f3776c8ce9db105d35b70 build: 2017-01-30

and freshly built from master:
radare2 1.3.0-git 13944 @ darwin-x86-64 git.1.2.0-278-g34089ab
commit: 34089ab build: 2017-03-02__13:22:11

Linux version 1.2.0 is also the same.

Test is here https://github.com/radare/radare2-regressions/pull/726

**Comment by neutralinsomniac** [comment]
Tried both with:
radare2 1.2.0 43 @ darwin-x86-64 git.1.2.0
commit: 3e16b495db6ca792dc5f3776c8ce9db105d35b70 build: 2017-01-30

and freshly built from master:
radare2 1.3.0-git 13944 @ darwin-x86-64 git.1.2.0-278-g34089ab
commit: 34089ab363ed65f1e636f3a97374ab0d1fe31745 build: 2017-03-02__13:22:11

**Comment by Maijin** [comment]
If you could PR an additional for this in https://github.com/radare/radare2-regressions/blob/master/t/cmd_write

**Comment by neutralinsomniac** [comment]
FYI, just noticed this appears to only happen when io.cache=false

**Comment by Maijin** [comment]
This also work for `r2 -` cache or no cache

**Comment by neutralinsomniac** [comment]
siol branch appears to be unaffected by this bug:

https://asciinema.org/a/5zyvmz6bsa4fxghu6d9ahe8am

**Comment by Maijin** [comment]
CC @radare @condret 👍

**Comment by radare** [comment]
Cool! Another reason to merge siol

**Comment by Maijin** [comment]
siol is in!
