### ISSUE TITLE
Error on e.cmd=dc : “That was too deep"

### ISSUE THREAD

**Issue by Antonin-Deniau** [radare/radare2#6929]
I've got an error (Recursion i think ?)
I put a breakpoint on every function, which trigger a "dc" command,
then run the program, and i get a "r_core_cmd: That was too deep" error.

```python
import r2pipe

r2 = r2pipe.open("!#pipe")

functions = r2.cmdj("aflj")

for function in functions:
    address = function["offset"]
    print("break at {}".format(hex(address)))
    r2.cmd("db {}".format(address))

print('Set continue on break...')
r2.cmd("e cmd.bp=dc")
print("Done! you can start the debugger")
```

```
[0x936f45b2]> dc
hit breakpoint at: 1f60
hit breakpoint at: 391c
hit breakpoint at: 395e
hit breakpoint at: 1f9e
hit breakpoint at: 1fb0
hit breakpoint at: 391c
hit breakpoint at: 395e
hit breakpoint at: 22a0
hit breakpoint at: 391c
hit breakpoint at: 395e
r_core_cmd: That was too deep (dc)...
r_core_cmd: That was too deep (sr PC)...
```

It's work well without the dc command.

My build is:

Darwin XXX.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

radare2 1.2.0 13998 @ darwin-x86-64 git.1.2.0
commit: 4791574278eaa50560b20081882e8bbefe56bb70 build: 2017-03-06

**Comment by radare** [comment]
You may use tracepoints to do that, running dc inside the breakpoint will cause a nest of command calls that will end up that "too deep" error before the stack space is over

Also you are running an old r2, please update to git, but this issue will still be there

**Comment by Maijin** [comment]
see `dt?`
