### ISSUE TITLE
Stub offset validity check in debug mode

### ISSUE THREAD

**Issue by asutoshpalai** [radare/radare2#6934]
[Offset validity check](https://github.com/radare/radare2/blob/a40343f2f025a2a8434034b2eadabc23b7dcbe86/libr/io/io.c#L1160) in debug mode is stubbed. This crashes r2 in debug mode as [invalid `bbs`](https://github.com/radare/radare2/blob/a40343f2f025a2a8434034b2eadabc23b7dcbe86/libr/anal/fcn.c#L552) are added to the functions.

**Comment by radare** [comment]
can you provide an asciinema with the issue you are experiencing? this offset validity thing is disabled in debugger mode because we ignore IO and BIN information in the debugger, so it should work fine in the debugger.. at least it does for me.

**Comment by radare** [comment]
Demo to reproduce pls

**Comment by asutoshpalai** [comment]
I have attached the binary along with the core dump of r2 for the crash. Reproduced the error on 2 machines.

I loaded the binary with `r2 -d -AA ./aslr2`.

[aslr2.zip](https://github.com/radare/radare2/files/834579/aslr2.zip)

**Comment by asutoshpalai** [comment]
The core dump was produced for
```
radare2 1.3.0-git 14031 @ linux-x86-32 git.1.2.0-364-g70e808e
commit: 70e808ea3619d6168a7c472098c7c7050b2e1b75 build: 2017-03-10__03:05:19
```

Observed the same behaviour with `r2 -d ./aslr2` followed by `aaaa` both on a 32 bit system and a 64 bit system. Happy to provide any further information required.

**Comment by radare** [comment]
if it's crashing can you paste the crashlog? because without your r2 build i cant reconstruct that from the core. also running it with valgrind will help to get better logs

**Comment by radare** [comment]
<img width="1504" alt="screen shot 2017-03-13 at 00 41 24" src="https://cloud.githubusercontent.com/assets/917142/23837270/d20d8b06-0785-11e7-8f82-f2303681f68e.png">
