### ISSUE TITLE
Projects do not save datarefs. 

### ISSUE THREAD

**Issue by katshup** [radare/radare2#6938]
I've noticed that in the most current build (1.3.0) as well as 1.2.1 that saving off a project file and reloading it does not save the datarefs when running the command 'aflj'.

**Comment by katshup** [comment]
It also seems that loading project files in the current version causes all functions to be reported to have a size of 0.

**Comment by Maijin** [comment]
hum, paste r2 -v full output here.

**Comment by katshup** [comment]
radare2 1.3.0-git 13986 @ linux-x86-64 git.1.2.0-318-g2b779f9
commit: 2b779f92bba0198918217e01912c1b5846de92dd build: 2017-03-07__18:35:56

**Comment by Maijin** [comment]
Tracked here now https://github.com/radare/radare2/issues/6945
