### ISSUE TITLE
Copy / Paste doesn't work on Windows

### ISSUE THREAD

**Issue by olifozzy** [radare/radare2#6941]
Try with normal command line (cmd.exe) and with conemu without success.

It has a strange behaviour, it pastes some chars from the clipboard , not always the same ... maybe a timing issue.

As queueRAM said, it works with "e scr.fgets=true" but we loose prompt

> <queueRAM> r2tg, ollifozzy, i've had some success setting "e scr.fgets=true" under windows to allow pasting entire commands, but then your prompt is broken

**Comment by wargio** [comment]
Windows has dozen of problems.
That doesn't work because the terminal doesn't work like the *nix ones.

**Comment by XVilka** [comment]
Afair it's known issue - check the bugs from @dukebarman

**Comment by XVilka** [comment]
Check those https://github.com/radare/radare2/pull/3939 , https://github.com/radare/radare2/issues/3936

**Comment by radare** [comment]
Cc @skuater

**Comment by olifozzy** [comment]
Disabling Ctrl+V in conemu did the trick. But it's more a workaround than a solution, since it will prevent Ctrl+V from working in other tools / cmd.
Btw I mainly use right click to paste , and this still doesn't work. 
In cmd.exe , the right-click -> paste doesn't work neither.

Thanks for the tip anyway :+1:

**Comment by kazarmy** [comment]
In cmd.exe, you can also use Shift-Ins to paste.

**Comment by wargio** [comment]
but it won't work.

**Comment by kazarmy** [comment]
Oh I meant that you can use Shift-Ins to paste text onto the cmd.exe command line (not the radare2 command line) if you've disabled Ctrl-V in ConEmu. Though I checked just now and right-click -> paste works fine for me.

**Comment by skuater** [comment]
Use Ctrl+V to paste text into radare2 prompt. R2 have this shortcut to paste text.

If u use conEmu disable hooks to ctrl+v
