### ISSUE TITLE
Setting scr.fgets = true messed the prompt on Windows

### ISSUE THREAD

**Issue by olifozzy** [radare/radare2#6942]
Following #6941 
On windows, when I set scr.fgets = true, I loose the prompt.

![image](https://cloud.githubusercontent.com/assets/1614689/23680011/fae729ec-0389-11e7-9e6f-df66f361b4be.png)

**Comment by radare** [comment]
Cc @skuater

**Comment by skuater** [comment]
i think this work as expected, on linux also loose the prompt.
Cc @radare

**Comment by Maijin** [comment]
Also have trouble with that on OSX after quitting visual mode it just stuck without prompt
