### ISSUE TITLE
projects that were saved when using 'aaaa' do not work (with 'aaa' they work)

### ISSUE THREAD

**Issue by adw1n** [radare/radare2#6943]
When I create a project like this:
1.r2 challenge02
2.aaaa
3.Ps myproject
4.exit (Y)

and then I try to use the project:
5.r2 -p myproject challenge02
message I get:
WARNING: file.path change: /root/tutorials/reversing-radare2/sources/challenge02/challenge02 => malloc://983040
 -- Wait a minute! I found a bug, self-fixing ... OK
6.s main
7.pdf
I'm seeing:
![radare2_problem](https://cloud.githubusercontent.com/assets/8993001/23682025/f20cb3ca-0391-11e7-8714-d70b08954104.png)
instead of:
![radare2_expected](https://cloud.githubusercontent.com/assets/8993001/23682028/fc499718-0391-11e7-9084-d20c77ed1c0a.png)

If I do aaa before 6) it does not change anything.
The only thing I have in .radare2rc is:
e asm.pseudo = true
Without .radare2rc I'm getting exact same results.

**If I use aaa in step 2 everthing is working correctly.**

The binary (I have also tested with a different one):
https://github.com/bluec0re/reversing-radare2/blob/master/sources/challenge02/challenge02
Tested on kali linux (rolling) with 1.1 (whatever version they offer when you apt-get update and upgrade radare2) and with version from github insalled using sys/install.sh (the one that I currently have installed).
r2 -v output:
radare2 1.3.0-git 13981 @ linux-x86-64 git.1.2.0-315-g5d669ed2f
commit: 5d669ed2f8be5734d7ebd6b34d203d777c40c5e7 build: 2017-03-07__12:42:08

ls ~/.config/radare2/projects/myproject
rc  xrefs.sdb

zipped ~/.config/radare2/projects/myproject:
[myproject.zip](https://github.com/radare/radare2/files/826106/myproject.zip)

**Comment by mytbk** [comment]
It seems that using `aaaa` on any file will overide file.path to malloc://983040. I've tested it on /bin/ls.

**Comment by jeaye** [comment]
Gah, I was just spinning around on this one too. Good to see it's ticketed; I'll use `aaa` for now.

**Comment by mytbk** [comment]
I've just installed the latest git version and found `aaaa` is fixed now.

**Comment by radare** [comment]
awesome

**Comment by mytbk** [comment]
I just found that file.lastpath also changes after an aaaa, which will break r2 projects, and it's not fixed yet...

**Comment by Maijin** [comment]
Please reopen an issue if you have trouble, this is really old issue already don't dig in the graveyard 👍
