### ISSUE TITLE
bin check vs check_bytes

### ISSUE THREAD

**Issue by radare** [radare/radare2#6955]
i think plugins should only expose one of those callbacks, not both, check_byets should be enough for r_bin to work

**Comment by Maijin** [comment]
That would be very cool because this is confusing imho.

**Comment by radare** [comment]
```

static bool check_bytes(const ut8 *buf, ut64 length) {
        if (!buf || length < 27) {
                return false;
        }
        return !memcmp (buf, SPC_MAGIC, 27);
}

static bool check(RBinFile *arch) {
        const ut8 *bytes = arch ? r_buf_buffer (arch->buf) : NULL;
        ut64 sz = arch ? r_buf_size (arch->buf): 0;
        return check_bytes (bytes, sz);
}

```

**Comment by alvarofe** [comment]
Count on me to fix this, it should wait until sunday though

**Comment by radare** [comment]
I was about to do that, but faced the xtr plugins which have a different check method and i was a bit afraid of breaking but go on if you feel brave.

The binxtr plugins are somewhat mixed with the bin ones and that may be problematic, so its ok for me to move for later. Up to you :)

**Comment by alvarofe** [comment]
The same could be applied with load vs load_bytes i think
