### ISSUE TITLE
Disassemble until X

### ISSUE THREAD

**Issue by radare** [radare/radare2#6956]
The same goes for other commands like px.. which makes me think about a dynamic block size depending on a condition..

* disassemble until ret
* hexdump until fffff
* disassemble until call to X

current block size will be the upper limit.

more ideas? we probably want to implement this in a @ subcommand that sets the blocksize to something depending on user needs:

```
> pd @..ret
> x @x..ffff
> pd @..call
```

**Comment by radare** [comment]
I was thikning in `pdu addr`. but maybe makes sense to honor that @.. and support some modifiers to specify blocksize and such

**Comment by radare** [comment]
cc @thestr4ng3r this one is easy and related to the multiple-arroba you did. wanna give it a try? the idea is that @.. will change the blocksize to be the r_num_math of the stuff passed compared to the current seek

**Comment by radare** [comment]
also, note that the idea behind this syntax is to conform the one used in `s..` so just grabbing the lower part of the current address. unless the expression starts with 0x or is a flag

**Comment by radare** [comment]
i think @.. should be used like in s.., aka a temporary seek providing a partial address

also, the @... should be used as a way to change the blocksize until the given address

**Comment by radare** [comment]
needs more discussion, please share your thoughts

**Comment by mrpaja** [comment]
Gonna start with the issue this week

**Comment by mrpaja** [comment]
I guess in s.. the dots represent the sub commands of seeking? And the command @.. just means until? So:
`hexdump until :> x @..0xfff` ? 
Any advice which functions are worth taking a look at first?

**Comment by mrpaja** [comment]
Getting busy next week, anyway gonna start that one. My idea
For 
`>pd @..ret`
getting the adress similar to /c command and picking the smallest difference between ret and current address. Then, just applying pd command with a temporary blocksize. In that way, one can get more specific, like searching
`pd @..mov eax` or
`pd @..lea rax, str.Hello_World`
The current blocksize will be the upper limit.

**Comment by Maijin** [comment]
Just make a PR

**Comment by radare** [comment]
ping?

**Comment by radare** [comment]
any update on this? i can do that if not done yet

**Comment by mrpaja** [comment]
I like to work on that but was quite busy with my thesis. Please let me a couple of days time to work on.

**Comment by radare** [comment]
I did the @.. , but there's still to do the @... and we have to think about the @.

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
tired of waiting. i have implemented the @...
