### ISSUE TITLE
Ability to load/export IDA TIL Files

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6962]

**Comment by XVilka** [comment]
Related: https://github.com/williballenthin/python-idb

**Comment by Maijin** [comment]
Unrelated, IDB are loaded by r2ida using this python-idb. But TIL aren't supported by python-idb

**Comment by radare** [comment]
Put this issue in the r2ida repo

**Comment by XVilka** [comment]
Created the issue in Python-IDB instead: https://github.com/williballenthin/python-idb/issues/37

**Comment by XVilka** [comment]
Closing this one.
