### ISSUE TITLE
Function argument analysis is inaccurate

### ISSUE THREAD

**Issue by PaquitoRiviera** [radare/radare2#6970]
```asm
/ (fcn) entry0 17
|   entry0 ();
|           0x08048060      b834120000     mov eax, 0x1234             ; [1] va=0x08048060 pa=0x00000060 sz=44 vsz=44 rwx=--r-x .text
|           0x08048065      50             push eax
|           0x08048066      e806000000     call loc.good_arg_anal
|           0x0804806b      e80d000000     call loc.bad_arg_anal
\           0x08048070      c3             ret
/ (fcn) loc.good_arg_anal 12
|   loc.good_arg_anal ();
|           ; arg int arg_8h @ esp+0x8
|              ; CALL XREF from 0x08048066 (entry0)
|           0x08048071      55             push ebp
|           0x08048072      89e5           mov ebp, esp
|           0x08048074      8b442408       mov eax, dword [esp + arg_8h] ; [0x8:4]=0
|           0x08048078      6a00           push 0
|           0x0804807a      58             pop eax
|           0x0804807b      5d             pop ebp
\           0x0804807c      c3             ret
/ (fcn) loc.bad_arg_anal 15
|   loc.bad_arg_anal ();
|           ; var int local_8h @ esp+0x8
|              ; CALL XREF from 0x0804806b (entry0)
|           0x0804807d      55             push ebp
|           0x0804807e      89e5           mov ebp, esp
|           0x08048080      8b442408       mov eax, dword [esp + local_8h] ; [0x8:4]=0
|           0x08048084      6a00           push 0
|           0x08048086      6a00           push 0
|           0x08048088      58             pop eax
|           0x08048089      58             pop eax
|           0x0804808a      5d             pop ebp
\           0x0804808b      c3             ret

```
[example.zip](https://github.com/radare/radare2/files/832960/example.zip)

See how in `bad_arg_anal ` the argument is accessed from the stack just like in `good_arg_anal`, but analysis identifies this as a local variable access just because of the extra push/pop.

File contains minimal binary testcase.

Different problem, the comments (`[0x8:4]=0`) pretend to show you what the accessed value is, but show the data at a nonsense address 0x8, even with `anal.esil=true`.

**Comment by Maijin** [comment]
@oddcoder ^

**Comment by oddcoder** [comment]
yes this is not a bug, because of the extra push, the stack frame size is increased, thus esp+0x8 appeared to be inside the maximum stack frame of the `loc.bad_arg_anal` thats why it is detected as a local variable,
I cant find an obvious fix to this issue

**Comment by PaquitoRiviera** [comment]
> yes this is not a bug, 

:confused: I guess you mean it's expected behavior if using maxstack to tell args apart from vars.

https://github.com/radare/radare2/issues/6933 shows r2 knows the stack frame size at all times during function analysis, so it also definitely knows if the memory access is within the frame or not, so why is maxstack used for this instead.

Any idea why the bogus data in the comments?

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/23827831/804871d2-06bd-11e7-8d60-50c75f636369.png)

**Comment by XVilka** [comment]
@sivaramaaa please check this one
