### ISSUE TITLE
Please stop force pushing to master

### ISSUE THREAD

**Issue by PaquitoRiviera** [radare/radare2#6982]
It's really disruptive to anyone tracking master, as the r2 team actively encourages everyone to do.
This is (at least) the 3rd time in a week this has happened.

Yesterday these commits appeared in master:
49fcae1 Fix typo
70e808e Add xmalloc
cc7b081 Fix android-shell.sh
cbb5bc9 Fix 6937 - Workaround to avoid crash in agf when formatting an esilref comment
6a9039e Fix 6677 - Quoted multicommands issue
21abf22 Add purge2, used from sys/purge.sh

But now they are gone and these appeared instead:
a02f09a Fix typo  
4085fda Add xmalloc  
4cd8404 Fix android-shell.sh  
c9df405 Fix 6937 - Workaround to avoid crash in agf when formatting an esilref comment  
21abf22 Add purge2, used from sys/purge.sh  

Apperently someone decided 6a9039e shouldn't have been pushed to master, interactive rebased it away, and then force pushed without realizing that this creates different commits and clobbers published history. That's just how git works.

This happened again a few days earlier with 5057cb6. Someone force pushed to remove that commit,  which is bad enough, but then after several hours they force pushed **again**, to "undo" that mistake. Both of them forced me to waste time figuring out where all the bogus merge conflicts suddenly came from.

There's one universal rule for git: **never force push to branches people base their work on.**
To prevent this from happening again in the future, please turn on Github's [Branch Protection](https://help.github.com/articles/about-protected-branches/). If you need to undo a commit pushed to master by mistake, you can and should just use `git revert` and push normally. If you think no one will notice or have their work disrupted by a forced push, please see issue #6982. Thanks.

**Comment by Maijin** [comment]
+1 for https://help.github.com/articles/about-protected-branches/

**Comment by radare** [comment]
Agree on that, we should not push -f, i'll try to enforce the pull request model, this will slow down the merge time a bit, but I guess it's worth the effort.

Moving for 1.4, because i assume closing this issue implies enforcing github's force-push protection

**Comment by PaquitoRiviera** [comment]
ping. Going on a month's delay to toggle a toggle-box. What's the concern?

**Comment by radare** [comment]
I push -f yesterday :))

**Comment by PaquitoRiviera** [comment]
... and was that to drive home the point that even though force pushing is universally acknowledged as terrible practice, and even though it is disruptive and inconsiderate to collaborators and users alike, and even though your own co-maintainers have spoken out against doing this, and even though you agreed to stop... despite all of these things (or was it because of them?) you felt like letting everyone know that that this is YOUR project and that you'll do whatever you damn well feel like, because you are the only person who matters? did I get the message right?

**Comment by radare** [comment]
4 days to reply this. /me takes note.

Thanks for participating in this social experiment. But slowtrolls are slow and you didnt won the prize. You can go grab your sandwitch in the entrance in exchange for your precious time.

**Comment by revolter** [comment]
@radare, It looks like you're the troll here, not @PaquitoRiviera.
