### ISSUE TITLE
wrong asm.bits value when opening a particular binary on arm (RPi) in debug mode

### ISSUE THREAD

**Issue by kamou** [radare/radare2#6995]
Hello,
I've tryed the following simple steps:

```
[0xb6f0cac0]> pdi 1 @ main
0x000103d8    sym.main:
0x000103d8             0820  movs r0, 8

[0xb6f6bac0]> db main
[0xb6f6bac0]> dc
Selecting and continuing: 15982
child stopped with signal 4
got signal...
[+] signal 4 aka SIGILL received 0
[0x000103d8]> pdi 1
0x000103d8         fefefefe  mrc2 p14, 7, apsr_nzcv, c14, c14, 7
```

so it seems like the breakpoint kind of works, I guess you are using illegal instruction to break,
 but trying continue then is not possible even after removing that breakpoint.

now there's this little weird thing:
main's first inst is on 2 bytes, but the breakpoint is on 4 bytes. Might that be the problem ?

**Comment by kamou** [comment]
forget about the size,
this seems to be another problem:
```[0xb6f8fac0]> pdi 1 @ main # first call to pdi
0x000103d8    sym.main:
0x000103d8             0820  movs r0, 8
[0xb6f8fac0]> pdi 1 @ main # second call to pdi
0x000103d8    sym.main:
0x000103d8         082001e3  movw r2, 0x1008
```

**Comment by Maijin** [comment]
Please provide the file.

**Comment by alvarofe** [comment]
Mind you to share the bin to test locally? I have been changed stuff these days and it will be easier to debug. Thanks

**Comment by radare** [comment]
no need to provide anything it happens with any program in the rpi, the issue is known

wokaround: unset the bp before continuing

**Comment by kamou** [comment]
I can share the binary, no problem:
https://gist.github.com/kamou/f2ee2ce786911d0447bef69cc79e859e

@radare I **did** try to remove the bp before continuing.
the problem according to pancake is that we should sigtrap instead of sigill.
he suggested using BRK for thumb (the binary is thumb)

**Comment by kamou** [comment]
so there's this code in bp_arm.c:
```
static struct r_bp_arch_t r_bp_plugin_arm_bps[] = {
	{ 64, 4, 0, (const ut8*)"\xfe\xde\xff\xe7" }, // le - arm64
	{ 64, 1, 0, (const ut8*)"\xfe\xde\xff\xe7" }, // le - arm64 // hacky fix
//	{ 32, 1, 0, (const ut8*)"\xff\xff\xff\xff" }, // le - linux only? (undefined instruction)
//	{ 32, 1, 1, (const ut8*)"\xff\xff\xff\xff" }, // be - linux only? (undefined instruction)
	{ 32, 4, 0, (const ut8*)"\x01\x00\x9f\xef" }, // le - linux only? (undefined instruction)
	{ 32, 4, 1, (const ut8*)"\xef\x9f\x00\x01" }, // be
#if 0
	{ 4, 0, (const ut8*)"\xfe\xde\xff\xe7" }, // arm-le - from a gdb patch
	{ 4, 1, (const ut8*)"\xe7\xff\xde\xfe" }, // arm-be
        { 4, 0, (const ut8*)"\xf0\x01\xf0\xe7" }, // eabi-le - undefined instruction - for all kernels
	{ 4, 1, (const ut8*)"\xe7\xf0\x01\xf0" }, // eabi-be
#endif
	{ 16, 2, 0, (const ut8*)"\xde\x01" },         // thumb-le
	{ 16, 2, 1, (const ut8*)"\x01\xde" },         // thumb-be
	{ 16, 2, 0, (const ut8*)"\xfe\xdf" },         // arm-thumb-le
	{ 16, 2, 1, (const ut8*)"\xdf\xfe" },         // arm-thumb-be
	{ 16, 4, 1, (const ut8*)"\xff\xff\xff\xff" },         // arm-thumb-be
	{ 16, 1, 1, (const ut8*)"\xff\xff\xff\xff" },         // arm-thumb-be
	{ 0, 0, 0, NULL }
};

```

There are a few issues there, first: for 16 bits 2 bytes sized bps, there are duplicates, which ones should be kept ?

second, the last two should be:
```
	{ 16, 4,0, (const ut8*)"\xff\xff\xff\xff" },         // arm-thumb-be
	{ 16, 4, 1, (const ut8*)"\xff\xff\xff\xff" },         // arm-thumb-be
```

but the bp values are abviously wrong (I get SIGILL with it), trying to figure out what to put in there.

**Comment by radare** [comment]
those are 4 byte length instructions., so it shuodlnt be used when patching thumb code imho ae you sure those are the ones that are used? because the fix is just to use any of the ones above repeated twice

**Comment by kamou** [comment]
I realised only after my message that the binary wasn't actually thumb,
Not sure why, but r2 gave me e asm.bits = 16 when using "-d", and I blindly trusted it.
The code is not thumb at all. I'm tryng to figure out where this asm.bits is set and why it is set to 16 now...

**Comment by radare** [comment]
so… the issue is not this?

**Comment by kamou** [comment]
no. should I close this issue and open a new one ? or can I continue the analysis here and rename this issue ?

**Comment by radare** [comment]
Rename is fine

**Comment by XVilka** [comment]
@kamou can you please create r2-regressions tests for this?

**Comment by radare** [comment]
We dont run r2r on arm yet..

**Comment by Maijin** [comment]
Doesn't hurt to create tests though

**Comment by radare** [comment]
please test again, i'm considering this issue as fixed, please open a new one if not
