### ISSUE TITLE
pdr doesn't work on 32-bit radare2

### ISSUE THREAD

**Issue by kazarmy** [radare/radare2#6999]
Sample interaction using pdr:
```
[0x77930970]> s main
[0x011e1180]> af
[0x011e1180]> pdr
This block size is too big (52428800<80521084792733824). Did you mean 'pD @ 0x11e118000000080' instead?
This block size is too big (52428800<80521634548547627). Did you mean 'pD @ 0x11e12000000002b' instead?
This block size is too big (52428800<80521819232141492). Did you mean 'pD @ 0x11e122b000000b4' instead?
This block size is too big (52428800<80522592326254607). Did you mean 'pD @ 0x11e12df0000000f' instead?
| ----------- true: 0x011e122b  false: 0x011e1200
| ----------- true: 0x011e12df
| ----------- true: 0x011e12df
```
Issue for both Mingw32 and Linux. For Linux, the 32-bit version was obtained using:
```
CFLAGS=-m32 sys/user.sh
```

**Comment by kazarmy** [comment]
Fixed by #6998.

**Comment by Maijin** [comment]
Drag and drop the binary in a zip archived here please.

**Comment by kazarmy** [comment]
Ok. Attached is a PE32 binary compiled from the simplest C99-compliant program that actually has defined behavior and triggers this bug on my machine. The zip file has no password since it's not malware.
[6999.zip](https://github.com/radare/radare2/files/836568/6999.zip)

Sample interaction (can replace `s main` with `s entry0` for longer pdr output):
```
> radare2 6999.exe
 -- Wrong argument
[0x00401234]> s main
[0x00401000]> af
[0x00401000]> pdr
This block size is too big (52428800<18031990695526407). Did you mean 'pD @ 0x40100000000007' instead?
```
This bug appears to be about misreading a 32-bit value as a 64-bit value (i.e. OOB memory access) so I'm not sure whether you can reproduce the output on your machine, or whether a test will be reliable or possible (but the output is probably reproducible exactly).

**Comment by kazarmy** [comment]
The tests in [t/cmd_pdr](https://github.com/radare/radare2-regressions/blob/fd0a9692c87324dd95912ce1a8c86c16639ffad8/t/cmd_pdr) are sufficient.

**Comment by Maijin** [comment]
obviously not otherwise they would have been broken before or after your patch so please add one relevant to your case

**Comment by kazarmy** [comment]
The tests would only have been broken for 32-bit radare2 and Travis doesn't test that bitness.

**Comment by Maijin** [comment]
k.
