### ISSUE TITLE
Update Lua from 5.1 to 5.3

### ISSUE THREAD

**Issue by utkonos** [radare/radare2#7005]
configure currently checks for Lua 5.1:
`check_library HAVE_LIB_LUA5_1 lua5.1 0`

Can this be updated to use 5.3.x?

**Comment by Maijin** [comment]
Hi bro!

**Comment by utkonos** [comment]
Hey mon!

**Comment by radare** [comment]
r2 does nothing with lua, everything is in bindings, extras and r2pipe
