### ISSUE TITLE
asm.pseudo not honored if asm.cmtright=false

### ISSUE THREAD

**Issue by queueRAM** [radare/radare2#7026]
Having `asm.comments=true` and `asm.cmtright=false` causes `asm.pseudo=true` to be ignored, outputting disassembly in non-pseudo syntax. This also affects `VV` visual graph mode where `asm.cmtright` is set to `graph.cmtright`. Both `pd` commands below should output pseudo syntax.
```
$ r2 -v
radare2 1.4.0-git 14134 @ linux-x86-64 git.1.3.0-39-gd61f8f270
commit: d61f8f270848a636105a4c474d497091e1a69856 build: 2017-03-14__17:34:02
$ r2 -
[0x00000000]> wa xor ebp, ebp
Written 2 bytes (xor ebp, ebp) = wx 31ed
[0x00000000]> e asm.pseudo=true
[0x00000000]> e asm.cmtright=true
[0x00000000]> pd 1
            0x00000000      31ed           ebp = 0
[0x00000000]> e asm.cmtright=false
[0x00000000]> pd 1
            0x00000000      31ed           xor ebp, ebp
```

**Comment by Maijin** [comment]
Create a test please -> https://github.com/radare/radare2-regressions

**Comment by queueRAM** [comment]
Tests in PR radare/radare2-regressions#752

**Comment by queueRAM** [comment]
I managed to trace the problem down to the following lines of code in [libr/core/disasm.c:3599-3605](https://github.com/radare/radare2/blob/master/libr/core/disasm.c#L3599-L3605)
```C
      if (ds->show_comments && !ds->show_comment_right) {
         ds_show_refs (ds);
         ds_print_ptr (ds, len + 256, idx);
         ds_build_op_str (ds);
         ds_print_fcn_name (ds);
         ds_print_color_reset (ds);
         R_FREE (ds->opstr);
```
Here, ds_build_op_str() generates the fancy op string using the pseudo code that was previously generated, but it is immediately discarded by R_FREE(ds->opstr) on line 3605. Then later at line 3631, ds_build_op_str() is called again, this time using the underlying ds->asmop.buf_asm as input since the pseudo code was discarded by the R_FREE(). I'm not sure where to go from here with all these buffers and special cases.

**Comment by Maijin** [comment]
This has been added for an oob by @alvarofe 
https://github.com/radare/radare2/commit/4a3971d9a96b123a072f89b8da25295a94957755

**Comment by alvarofe** [comment]
Fixed by pancake on master
