### ISSUE TITLE
Graph don't fit content

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#7039]
See screenshot

![image](https://cloud.githubusercontent.com/assets/1408600/23977128/8b04245e-09ec-11e7-92b3-496903d43cc3.png)

Even increasing with + and `r` for refresh do nothing.

This is a regression !

**Comment by radare** [comment]
Nodes have a max width to avoid hellish nodes with ultra long comments that make it useless. Not a regression. Why do u need to see the whole esil?

**Comment by Maijin** [comment]
I want to see the full ; function defintion. It was working before so it's definitely a regression !

**Comment by radare** [comment]
Then add an option because i dont want that behaviour

**Comment by alvarofe** [comment]
add e asm.emustr=true to avoid those comments with registers values if you are not interested

**Comment by Maijin** [comment]
Yes that's a bit better but the call info is still truncated, So need to change 2db1ccfaf310d65c0c10aedcf8526dd426b54ee5 to disable it when the call are displayed

**Comment by Maijin** [comment]
"Then add an option because i dont want that behaviour" -> `e graph.comment =false`

**Comment by Maijin** [comment]
Fixed
