### ISSUE TITLE
debugging, process killed regardless of choice

### ISSUE THREAD

**Issue by mrexodia** [radare/radare2#7040]
```
c:\CodeBlocks\x64dbg\bin\x32>radare2 -version
radare2 1.4.0-git 14553 @ windows-x86-32 git.1.3.0-56-gea8e5688e
commit: ea8e5688e34fb7d8761092fe16d40a6d83398e3e build: 2017-03-15__23:40:52

c:\CodeBlocks\x64dbg\bin\x32>radare2 -d x32dbg.exe
Spawned new process with pid 416, tid = 3220
= attach 416 3220
bin.baddr 0x00850000
Using 0x850000
Assuming filepath C:\CodeBlocks\x64dbg\bin\x32\x32dbg.exe
asm.bits 32
[0x777f0640]> q
Do you want to quit? (Y/n) Y
Do you want to kill the process? (Y/n) n
```

Specifically the question `Do you want to kill the process?` I answer `n`, but the process is killed anyway.

**Comment by radare** [comment]
this is a windows specific issue, works fine on linux and mac

cc @skuater

**Comment by skuater** [comment]
if you launch the process using radare (r2 -d process.exe) detach api finalize the process (i think is normal behavior  on windows detach api, also x64dbg and ida do same)

If u attach to pid (r2 -d <pid>) then  u can do a "dp-" to force a detach,  after this u can exit from r2 using "q" "y" "n", and process remain in execution. At moment u can do it by this way.

Is needed implement this behavior to do it automatically  when u select "no" to end process and process is debugged via attached pid.

**Comment by skuater** [comment]
Ok ignore last part of previos comment.

Now is fixed at  pr #7053, if u attach via pid and exit from radare2 telling dont kill process, debugger detach automatically

**Comment by mrexodia** [comment]
I don't think the issue should be closed before the pull request is merged and it is confirmed as closed to be honest.

The reason this is reported as an issue is that the user is presented with a choice but this choice is completely ignored. I'm well aware how other debuggers handle this and there no choice is offered.

**Comment by radare** [comment]
So you want an option for that? R2 already asks you to kill the process on exit. I dont think theres a need for an option here.

The issue should be closed when the pr merged, agree on that

**Comment by mrexodia** [comment]
When did I say I want an option? I just say a choice is given but not respected. The API is only a possible way to control this user choice 😄

**Comment by radare** [comment]
And the dk command, the prompt when quitting, the dp to switch to another pid.. you have always the choice

**Comment by mrexodia** [comment]
Thanks a lot, it's working fine now!
