### ISSUE TITLE
^C not working with pD

### ISSUE THREAD

**Issue by jroimartin** [radare/radare2#7046]
E.g.

```
[0x000566f4]> pD $SS~svc
^C^C^C^C^C^C^C^C
```

**Comment by alvarofe** [comment]
The issue is cause this function takes a lot 

```
	ds_reflines_init (ds);
```

so even if you cancel probably you didn't grep a thing, workaround `e asm.lines=false`. I pushed a fix into master, test at close if you are happy with it, although it takes a while. I could add more check in other places.

**Comment by Maijin** [comment]
Yes work
