### ISSUE TITLE
Add obfuscated boolean field in RBinInfo

### ISSUE THREAD

**Issue by radare** [radare/radare2#7051]
This can be easily determined with some checks in RBin, maybe to autodetect if the bin is packed, or the class info obfuscated, etc obviously not 100% reliable, but handy for some use cases

**Comment by Maijin** [comment]
There is yara and p=e and iS entropy for that

**Comment by Maijin** [comment]
One could do a small script that recaps all of the commands that can help determining the obfuscation level but this should go in r2r since it would imply usage of yara.
