### ISSUE TITLE
Error when showing jump destination in visual mode

### ISSUE THREAD

**Issue by Komiblanka** [radare/radare2#7054]
When opening in visual mode, I see that a box jumps to gh but it says gb.

See attached pic for more details.

![capture](https://cloud.githubusercontent.com/assets/9326317/24068081/9b037bde-0b86-11e7-8c88-aad3965121da.png)

**Comment by radare** [comment]
We shuoldnt display those keybinding comments in the code inside the basic blocks

**Comment by Maijin** [comment]
Here it's clearly bug, those keybindings comments are very useful.

**Comment by ret2libc** [comment]
Could you share the binary?

**Comment by Maijin** [comment]
https://gist.github.com/superkojiman/556eaa2fc83a51298992/raw/7c8ced03ae5681c890d7cb842b9ccede9dedc49b/mystery.bin

**Comment by ret2libc** [comment]
Which versions of r2 are you using? It works correctly for me. Could you also paste your ~/.radare2rc if you have one? Thanks

**Comment by Maijin** [comment]
Can't reproduce too.

**Comment by Komiblanka** [comment]
I reproduced it again. These are the steps:
#r2 mystery.bin
aaa
pdf
s fcn.004005a6
VV
:afvn local_18h password<enter>
<enter>

My version of r2:
r2 -v
radare2 1.4.0-git 14169 @ linux-x86-64 git.1.3.0-74-g072551a
commit: 072551a8a7a7f97f2b000a875b2b2fa0e9c5cf48 build: 2017-03-17__19:25:52

I don't have a ~/radare2rc.
