### ISSUE TITLE
Autocomplete should be refactored

### ISSUE THREAD

**Issue by deeso** [radare/radare2#708]
Autocomplete in `core/core.c` should be refactored.  It should use `RLists` with free set to free, instead of a `char **`.  This will make it easier to manage the character strings and destroy them.  Also, this function should be refactored.  Specifically, each command location that is queried should either have there own function, or there should be a way to select the data source.

**Comment by alvarofe** [comment]
All source code should be refactored, closing this issue since it seems is tracked in other place
