### ISSUE TITLE
Shrink docker image

### ISSUE THREAD

**Issue by ryarnyah** [radare/radare2#7081]
The official docker image for radare was too heavy for me so i shrink it. If you are interested in, i can make a PR?

```
ryarnyah/r2docker   latest              50b3b2f17fff        33 minutes ago      279 MB
radare/radare2      latest              ee08dcdef5fc        5 hours ago         1.12 GB
```
https://hub.docker.com/r/ryarnyah/r2docker

**Comment by radare** [comment]
Indeed a pullreq would be welcome, also, if you want to look at the r2-docker script you can probably enhance it to support more than one type of docker image to be installed, from tiniest to the biggest one with all dev environment. But it seems that your image already have the same packages as mine

**Comment by radare** [comment]
pr?

**Comment by ryarnyah** [comment]
I'm sorry, i will work on it this weekend.
