### ISSUE TITLE
Remove io->raw?

### ISSUE THREAD

**Issue by radare** [radare/radare2#7088]
io->raw disables all the sections/maps/cache machinery, basically providing a direct path to use the target io plugin without previous steps. Condret proposes to remove it, but it's better to discuss before applying this change in master. This issue aims to track that.

Additionally, the Debug plugins contain a keepio field which sets this value to 1 or 0, which i think is wrong.

Pros:
* Faster for searching (not sure how much fast is that actually)
* Debugging IO plugins to find bugs (ignoring layers on top)

Cons:
* Sections and such are hidden, and thats not really obvious for anyone
* Messy code that's barely useful

**Comment by condret** [comment]
you can have direct access to io-plugins by disabling io.va

**Comment by radare** [comment]
i think the original meaning for keepio was to specify that the debugger backend was reusing the same io, which is conceptually a bad idea, so ok to kill all that stuff. ill do that change in a PR for master now.

**Comment by radare** [comment]
Fixed in https://github.com/radare/radare2/pull/7091
