### ISSUE TITLE
visual insert behaviour is undocumented.

### ISSUE THREAD

**Issue by ewtoombs** [radare/radare2#7100]
I had to determine these controls experimentally:

alt+q: exit insert
alt+hjkl: cursor movement while inserting

I looked everywhere in the radare2 book, the man page, and the integrated help, but I couldn't find documentation for these controls. These should really be documented somewhere.

**Comment by radare** [comment]
If that works is not on purpose because the alt key can be used by the terminal app itself is better not to use it

**Comment by radare** [comment]
i dont think alt+hjkl results in a consistent or fixed keycodes on all terminals. i did it for alt+q, but its gonna be problematic for hjkl. closing
