### ISSUE TITLE
alt+q only exits visual insert mode when the hex pane is selected.

### ISSUE THREAD

**Issue by ewtoombs** [radare/radare2#7101]
When you're inserting ASCII in the right panel, you need to hit tab before you can stop inserting with alt+q. alt+q should exit visual insert mode regardless which pane is selected.

**Comment by radare** [comment]
AltQ isnothing. The visual mode only understands q. And q is a valid char in ascii mode. You should be able to use the ESC key

**Comment by radare** [comment]
Fixed in 6b8d0b9aaf52fdd0c3a5439c7e0c25560da31add

thanks for the tip!

**Comment by ewtoombs** [comment]
oh, now I get it. I was confused because alt-hjkl do work in the ascii pane.
