### ISSUE TITLE
output of 'i' or rabin2 -I is not sorted

### ISSUE THREAD

**Issue by radare** [radare/radare2#7104]
output should be alphabetically sorted

**Comment by radare** [comment]
Fixed by @oddcoder relro pr i think

**Comment by JacobPimental** [comment]
Actually I just fixed it. Until my pull request is accepted it's still not in alphabetical order.

**Comment by Maijin** [comment]
Ok so now we have a duplicated PR.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/7190
