### ISSUE TITLE
radiff2 without instruction addresses

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#7107]
It would be neat to be able to radiff2 functions or sections of code without taking into account the address. For instance, the base load address is different or otherwise addresses are different but the instructions are the same.

**Comment by radare** [comment]
radiff2 -C does that

**Comment by Owlz** [comment]
So perhaps I'm misunderstanding the output? Here's the radiff2 -AAC:

```
                 sym._init  26 0x400468 |   MATCH  (0.961538) | 0x400428   26 sym._init
  sym.imp.__stack_chk_fail  32 0x4004a0 |   MATCH  (0.906250) | 0x400460   32 sym.imp.__stack_chk_fail
 sym.imp.__libc_start_main  48 0x4004b0 |   MATCH  (0.916667) | 0x400470   48 sym.imp.__libc_start_main
             sym.imp.fgets  48 0x4004c0 |   MATCH  (0.916667) | 0x400480   48 sym.imp.gets
sub.__gmon_start___248_4d0  16 0x4004d0 |   MATCH  (0.937500) | 0x400490   16 sub.__gmon_start___248_490
                    entry0  41 0x4004e0 |   MATCH  (0.878049) | 0x4004a0   41 entry0
  sym.deregister_tm_clones  41 0x400510 |   MATCH  (1.000000) | 0x4004d0   41 sym.deregister_tm_clones
    sym.register_tm_clones  53 0x400550 |   MATCH  (1.000000) | 0x400510   53 sym.register_tm_clones
 sym.__do_global_dtors_aux  28 0x400590 |   MATCH  (0.928571) | 0x400550   28 sym.__do_global_dtors_aux
           sym.frame_dummy  35 0x4005b0 |   MATCH  (1.000000) | 0x400570   35 sym.frame_dummy
                 sym.stuff  70 0x4005d6 |   MATCH  (0.771429) | 0x400596   63 sym.stuff
                  sym.main  21 0x40061c |   MATCH  (0.952381) | 0x4005d5   21 sym.main
       sym.__libc_csu_init 101 0x400640 |   MATCH  (0.940594) | 0x4005f0  101 sym.__libc_csu_init
       sym.__libc_csu_fini   2 0x4006b0 |   MATCH  (1.000000) | 0x400660    2 sym.__libc_csu_fini
                 sym._fini   9 0x4006b4 |   MATCH  (1.000000) | 0x400664    9 sym._fini
```

Notice ```sym.main``` is only .95 match. The code in main didn't change. Attached are the diff images. 
![1](https://cloud.githubusercontent.com/assets/7632864/24278195/a917a3e4-1018-11e7-8e3e-139336527c40.png)
![2](https://cloud.githubusercontent.com/assets/7632864/24278194/a9179782-1018-11e7-9f91-9f209773e8a6.png)

The images appear identical aside from the addresses, and the C code is also the same. However, radiff2 is noting that these are different.

Is this expected output? If so, what does .95 for sym.main mean in this case, then?

**Comment by radare** [comment]
Its says that are 95% equal, and grey color of nodes means no changes. So its ok

**Comment by radare** [comment]
Do you want byte level diffing on diffent source addresses in fileA and fileB?

**Comment by Owlz** [comment]
So my confusion is, if they're only 95% equal, with the assembly instructions being exactly the same, and the assembly addresses not mattering (per -C), what is different? So far as I can tell, they are 100% equal.

**Comment by radare** [comment]
It is 95% because offset is different, matching offset will give you this 5%

**Comment by Owlz** [comment]
Right, that's what I'm trying to say. From a reversing perspective I don't actually care that the offsets happen to be different. I'd simply like to know if the assembly is different.

**Comment by radare** [comment]
Then ignore that 5%, offset is another metric that matters
