### ISSUE TITLE
trailing text does not result in parse error

### ISSUE THREAD

**Issue by ewtoombs** [radare/radare2#7131]
Sometimes, it's nice when a simple typo at the end of a line is ignored...
```
[0x81e00000]> pa add r0, r0
0044
[0x81e00000]> pa add r0, r0]
0044
[0x81e00000]> 
```
But I don't think it's worth the confusion this can otherwise cause...
```
[0x81e00000]> e asm.bits=32
[0x81e00000]> pa add r0, r0, r1
010080e0
[0x81e00000]> pa add r0, r0, r2
020080e0
[0x81e00000]> e asm.bits=16
[0x81e00000]> pa add r0, r0, r1
0044
[0x81e00000]> pa add r0, r0, r2
0044
[0x81e00000]> ...really, Radare?
```

**Comment by radare** [comment]
Use keystone or gas assemblers if you want something really strict and tested. Default assemblers are evolving and are not that complete, but much smaller and withiut dependencies and soon or late will be better than the others. Thanks for reporting, do you wanna fix this?

**Comment by Maijin** [comment]
You can use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a arm.ks…
or in radare2 session
	e asm.assembler = arm.ks
```

**Comment by ewtoombs** [comment]
I don't think this problem is local to the assembler. I've seen it everywhere. Here's another example:
```
[0x00000000]> s 81e00000
[0x00000051]> s 0x81e00000
[0x81e00000]> 
```
The first command seeks to 81 and ignores the trailing text "e00000". Also,
```
[0x81e00000]> ?v 3+6cccccc
0x9
[0x81e00000]> 
```
Most people do not expect this kind of behaviour and most REPLs do not behave like this. This is how python reacts under similar circumstances:
$ python
>>> 3+6cccccc
  File "<stdin>", line 1
    3+6cccccc
            ^
SyntaxError: invalid syntax
>>> 
```
