### ISSUE TITLE
How do you seek to the next flag?

### ISSUE THREAD

**Issue by ewtoombs** [radare/radare2#7132]
If this is impossible, let this be a polite feature request.

**Comment by radare** [comment]
Using n and Nkeys in visual or using sn and sN commands.  See help fmi

**Comment by ewtoombs** [comment]
Riiiight! K, now I get it. Thanks for the help!

There's definitely room for improvement in the documentation, though. I think I speak for a lot of new users when I say that the meaning of
```
| sn/sp             Seek next/prev scr.nkey
```
was less than clear. Maybe something more like 
```
| sn/sp             Seek to next/prev location, as specified by scr.nkey
```
Making a new issue now...

**Comment by Maijin** [comment]
No need of ISSUE ! Just modify that directly via the web interface of github 👿
