### ISSUE TITLE
please get rid of all the noise in the travis log

### ISSUE THREAD

**Issue by PaquitoRiviera** [radare/radare2#7135]
The raw log for a *passing* travis job is currently at an amazing 870kb, with 700k of that being just the tests part. To reiterate, this is for a green build that *passes* without errors. Why?

The log reports the status of every test that passes and can be ignored, but also a full error diff for 129 known broken tests no one cares about. And I only say no one cares about them because they seem to stay broken indefinitely.

The log is unreadable because its full of redundant color codes and [everything is mangled](https://github.com/radare/radare2/pull/7125#issuecomment-289180734) by the test scripts make silly use of "\r" cursor positioning, rather then the boring conservative custom of just printing out lines.  If you don't use the raw log, it takes (comparative) ages to load, parse and render 800kb of data in the fancy folding travis ui, all for no good reason.

IMHO,  the ideal CI log for a passing commit should look something very much like this:
```
> make check
666 tests passed. :-)
<EOF>
```

Two lines. ok, maybe a few lines showing the build process, and any (and only) problems there.
Instead, we get literally thousands of lines of "NOTHING WRONG HERE! ALL OK! IGNORE ME! NO NEED FOR FURTHER ACTION!" with a bonus 100kb of progress-bars progressing just for shits and giggles.

You know what I'm talking about, you've felt the pain.

**Comment by XVilka** [comment]
NOOK option is supposed to filter out passed tests and show only errored
ones.

**Comment by Maijin** [comment]
We are working on improving this. Closing

**Comment by PaquitoRiviera** [comment]
@XVilka, yes it does, but broken tests are not treated as passed. And there are still the 3-4 other issues I described.

@Maijin , when you agree that an issue is legitimate, is it unreasonable to expect you to close an issue after it's fixed and not simply because someday it might be?

**Comment by Maijin** [comment]
This simply doesn't require an issue on r2 as this is an-going task for r2r

**Comment by radare** [comment]
Wrong repo

**Comment by PaquitoRiviera** [comment]
@XVilka found this,  https://github.com/radare/radare2-regressions/issues/384

> This simply doesn't require an issue on r2 as this is an-going task for r2r

Fair enough. So where's the ongoing issue that lists reducing log size, removing broken tests from log output,  eliminating the use of cursor positioning, removing OK tests from being printed (even with NOOK) and losing the color codes from the travis log? you've closed the issue, but I don't see these mentioned anywhere on radare2-regressions. 

Add to that list the extra hundred or so compiler warnings just casually introduced into the codebase with
https://github.com/radare/radare2/pull/7197 (lua 5.3 support)

You know, It took (a bit) of effort to check for, identify and report these problems. But in return, you closed the issue without either fixing any of them, or tracking them in a master issue elsewhere. So, you've basically and very casually, wasted the effort I spent trying to improve radare2. Is that the right or even most productive way to treat contributors?

**Comment by radare** [comment]
No need an issue for that. Its part of the common sense.

Which cursor positioning?

The loss fo colors is because you are blind.

All compiler warning are always fixed before the release, as well as coverity, clang analyzer and several other low hanging fruits that anyone can help. Even you. No need to have issues for obvious things.

You are not a contributor, so stop putting your name in the list. Contributors use to send pullreqs and solve things not complain and blame everything.
