### ISSUE TITLE
please do development files like everyone else

### ISSUE THREAD

**Issue by PaquitoRiviera** [radare/radare2#7136]
radare installs its include files in its own directory `/usr/include/libr` but for some reason it then requires that you add that directory to the compiler search path. I've never seen that before. To check, I've looked at xcb, gflags, openssl, z3, yara, unicorn and others, and I haven't found a single library that does this.

The conventional way to do this is:
1. app's own include files include their brethren using a relative path, like `#include "../r_util.h"`
2. clients applications include files using an explicit namespace directory `<libr/r_foo.h>`
3. For special casing things when building app itself vs. a third party build, add a `-DFOO_BUILDING` to the Makefile, and use `#ifdef` in the code to handle each case.

Instead, radare explicitly adds `<R2_HOME>/libr/include` to the compiler include path, and uses `#include <r_util.h>` everywhere. Then when the files are installed, every app that depends on these include files failes, because they include other files using the repo-relative location and not the install path. Meaning, the directory structure is different in the repo (`include/r_util.h`) vs. install `include/libr/r_util.h`, and instead of radare doing the standard thing, everything which compiles against radare is supposed to fix it at their end. Bug.

Different issue, why are all the sdb header files sort-of duplicated, but not quite, in two places? 

```
md5sum shlr/sdb/src/*.h
66ab3fb3b46466da584a17e989763afe  shlr/sdb/src/buffer.h
3510958b8806d3f81591e5c902c58ebd  shlr/sdb/src/cdb.h
16ab97a1800c5b30bec54cb8c78dcb0a  shlr/sdb/src/cdb_make.h
c802c334f9ee1f6341660ffba22d1fce  shlr/sdb/src/config.h
8aeac66b2f69e8b4d903ae89302149bb  shlr/sdb/src/ht.h
e07e94bafd7378ad3d7af65971614eaa  shlr/sdb/src/ls.h
456238db93613a9c099303b7a1e590a9  shlr/sdb/src/sdb.h
4ab98ebc208a1ef41bf79de108ba339c  shlr/sdb/src/sdbht.h
918a791c2c7f87207aa8665687f84562  shlr/sdb/src/sdb_version.h 
37c6003ae06afa0ab8acae6390f869a8  shlr/sdb/src/types.h
md5sum libr/include/sdb/*.h
66ab3fb3b46466da584a17e989763afe  libr/include/sdb/buffer.h
3510958b8806d3f81591e5c902c58ebd  libr/include/sdb/cdb.h
16ab97a1800c5b30bec54cb8c78dcb0a  libr/include/sdb/cdb_make.h
c802c334f9ee1f6341660ffba22d1fce  libr/include/sdb/config.h
5e1222e3541297354448fa72147f532f  libr/include/sdb/ht.h
e07e94bafd7378ad3d7af65971614eaa  libr/include/sdb/ls.h
449594b5288b84d322c81e34571e1fc7  libr/include/sdb/sdb.h
4ab98ebc208a1ef41bf79de108ba339c  libr/include/sdb/sdbht.h
918a791c2c7f87207aa8665687f84562  libr/include/sdb/sdb_version.h
37c6003ae06afa0ab8acae6390f869a8  libr/include/sdb/types.h
```

**Comment by radare** [comment]
> On 25 Mar 2017, at 17:21, PaquitoRiviera <notifications@github.com> wrote:
> 
> radare installs its include files in its own directory /usr/include/libr but for some reason it then requires that you add that directory to the compiler search path. I've never seen that before. To check, I've looked at xcb, gflags, openssl, z3, yara, unicorn and others, and I haven't found a single library that does this.
> 
hahahaha really? cmon dude, learn about pkg-config, or spend some time in packaging things.

> The conventional way to do this is:
> 
> app's own include files include their brethren using a relative path, like #include "../r_util.h”
no
> clients applications include files using an explicit namespace directory <libr/r_foo.h>
no
> For special casing things when building app itself vs. a third party build, add a -DFOO_BUILDING to the Makefile, and use #ifdef in the code to handle each case.
no
> Instead, radare explicitly adds <R2_HOME>/libr/include to the compiler include path, and uses #include <r_util.h> everywhere. Then when the files are installed, every app that depends on these include files failes, because they include other files using the repo-relative location and not the install path. Meaning, the directory structure is different in the repo (include/r_util.h) vs. install include/libr/r_util.h, and instead of radare doing the standard thing, everything which compiles against radare is supposed to fix it at their end. Bug.
> 

> Different issue, why are all the sdb header files sort-of duplicated, but not quite, in two places?
> 
because one is installed and the other is for internal use and because those are includes from an external repo

**Comment by radare** [comment]
You can check capstone, vala, openssl, glib, gtk, qt, gstreamer, libpcap, libreadline... i have been maintaining more than 300 packages in the past and the right way to do that is to provide mk files or use pkg-config. Mac for example doesnt even have /usr/include, many projects do this because installing include files in root directory is a bad idea, and there are several reasons for doing so.

**Comment by radare** [comment]
if you ask why sdb is shipped inside r2 is for the same reason i ship libmagic, grub, capstone, libzip, ..

* make it
* test and fuzz it properly, i have reported several bugs to 3rd party projects
* they dont release that often and making the build process more complicated is pointless

**Comment by PaquitoRiviera** [comment]
oh dear. Another case of abusing your users.

Fine, Let's go through everything.

> hahahaha really? cmon dude, learn about pkg-config, or spend some time in packaging things.

ad hominem forever? :surfing_man: 

> no
> no
> no

helpful.

> > Different issue, why are all the sdb header files sort-of duplicated, but not quite, in two places?

> because one is installed and the other is for internal use and because those are includes from an external repo

doesn't explain the duplication, or the different version. If it's a dependency, you shouldn't have to or duplicate the includes. If it isn't, you still shouldn't. So, I guess maybe you just shouldn't.

> You can check capstone, vala, openssl, glib, gtk, qt, gstreamer, libpcap, libreadline... 

Wait, I've already checked and gave openssl as an example myself, look at the OP.  I don't need to check again, but maybe you should. But, ok let's look at libpcap and libreadline:

> i have been maintaining more than 300 packages in the past 

Thank you, I know that can be a pain in the ass. Now, I think you're doing something wrong, and possibly some of those 300 packages have the same problem.

```
grep 'include' /usr/include/readline/*.h 
readline/history.h:#include <time.h>        /* XXX - for history timestamp code */
readline/history.h:#  include "rlstdc.h"
readline/history.h:#  include "rltypedefs.h"
readline/history.h:#  include <readline/rlstdc.h>
readline/history.h:#  include <readline/rltypedefs.h>
readline/keymaps.h:#  include "rlstdc.h"
readline/keymaps.h:#  include "chardefs.h"
readline/keymaps.h:#  include "rltypedefs.h"
readline/keymaps.h:#  include <readline/rlstdc.h>
readline/keymaps.h:#  include <readline/chardefs.h>
readline/keymaps.h:#  include <readline/rltypedefs.h>
readline/readline.h:#  include "rlstdc.h"
readline/readline.h:#  include "rltypedefs.h"
readline/readline.h:#  include "keymaps.h"
readline/readline.h:#  include "tilde.h"
readline/readline.h:#  include <readline/rlstdc.h>
readline/readline.h:#  include <readline/rltypedefs.h>
readline/readline.h:#  include <readline/keymaps.h>
readline/readline.h:#  include <readline/tilde.h>
readline/rlstdc.h:/* Adapted from BSD /usr/include/sys/cdefs.h. */

grep '#include' /usr/include/readline/pcap/*.h
pcap/pcap.h:  #include <pcap-stdinc.h> 
pcap/pcap.h:#include <pcap/bpf.h>
pcap/pcap.h:#include <stdio.h>
pcap/pcap.h:#include <Win32-Extensions.h>
```

so, either relative includes, or namespaced absolute includes, just like I said. What was your point?  :confused: 

What about that `#include <pcap-stdinc.h>`? well, that lives in `/usr/include`. right again.

What about the others, glib, gtk, gstreamer?

```
glib-2.0/gio/gio.h
26:#include <gio/giotypes.h>
28:#include <gio/gaction.h>
29:#include <gio/gactiongroup.h>
30:#include <gio/gactiongroupexporter.h>
31:#include <gio/gactionmap.h>
32:#include <gio/gappinfo.h>
33:#include <gio/gapplication.h>
34:#include <gio/gapplicationcommandline.h>
35:#include <gio/gasyncinitable.h>
36:#include <gio/gasyncresult.h>
37:#include <gio/gbufferedinputstream.h>
38:#include <gio/gbufferedoutputstream.h>
39:#include <gio/gbytesicon.h>
40:#include <gio/gcancellable.h>

# gtk
gtk-2.0/gdk/gdkevents.h
34:#include <gdk/gdkcolor.h>
35:#include <gdk/gdktypes.h>
36:#include <gdk/gdkdnd.h>
37:#include <gdk/gdkinput.h>
```

So, they include their namespace directory in the include path, but every single one of them has multiple versions co-existing. 

```
ls -1 /usr/include/glib*

/usr/include/glib-1.2
/usr/include/glib-2.0

ls -1 /usr/include/gtk* 
/usr/include/gtk-1.2
/usr/include/gtk-2.0
/usr/include/gtk-3.0

/usr/include/gstreamer-0.10
/usr/include/gstreamer-1.0
```
radare2 doesn't, and doesn't even version it's include dir. So again, non-standard.

> the right way to do that is to provide mk files or use pkg-config

That's a way around it, yeah. But why not do that *and* stick to standard practices? 

> Mac for example doesnt even have /usr/include, many projects do this because installing include files > in root directory is a bad idea, and there are several reasons for doing so.

I'm having trouble with the english here, several reasons to do something which is a bad idea? I know that's not what you meant, but not what you did. Anyway, I never asked that you install things in `/usr/include` so there's no reason for you to explain to me why you don't want to.

> if you ask why sdb is shipped inside r2

Again no, I didn't ask that. What I asked was:
`why are all the sdb header files sort-of duplicated, but not quite, in two places?`

Bundling 3rd party dependencies, especially fast moving can make a project less fragile, I agree.
but no, I didn't ask why you bundle libmagic, or capstone, or grub.  Those are 3rd party, and it can make sense to bundle you own patches. But, for some reason, the only dependency you duplicate headers for and modify them (and these are not patches applied, but actual modified copies checked in), is a dependency that you wholly own and develop yourself. That doesn't make any sense, and neither does the response: "So I can fuzz capstone".

Honestly, I don't like playing comment wars, even good people end up doing bad things when we go down this path. And dammit I wouldn't have to if you weren't so persistent in your efforts to make people who report problems look like imbeciles in need of your rare wisdom. You're not infrequently wrong I've quickly learned in my short time here, and dismissive all too often.
