### ISSUE TITLE
rasm2 produces invalid opcode for "sub rsp, 0x80"

### ISSUE THREAD

**Issue by mwl4** [radare/radare2#7137]
Default x86 platform produces invalid opcode:
```
>rasm2 -a x86 -b 64 "sub rsp, 0x80"
4881ec80
>rasm2 -a x86 -b 64 -d 4881ec80
invalid
invalid
in al, dx
invalid
```

With x86.as it gives the correct opcode:
```
>rasm2 -a x86.as -b 64 "sub rsp, 0x80"
4881ec80000000
>rasm2 -a x86 -b 64 -d 4881ec80000000
sub rsp, 0x80
```

```
>rasm2 -version
rasm2 1.3.0 64 @ windows-x86-32 git.1.3.0
commit: 83b8aa9b38e917233f7981ecc689078ca322acf1 build: 2017-03-13__03:11:11
```

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```
