### ISSUE TITLE
Optimize step back

### ISSUE THREAD

**Issue by radare** [radare/radare2#7139]
Find ways to optimize the stepback and avoid copying all the memory all the time, add more dts subcommands to handle all the states and dump them to disk in case of interest, use esil to determine the memory accesses and restore the minimum of memory, etc

**Comment by Maijin** [comment]
Don't think we need an issue for this as this is a full GSOC.

**Comment by alvarofe** [comment]
As long as we have not selected which project participated in GSOC I think that for the time being make senses having an issue to track this. Once GSOC is done and this project is picked up, we can close it.

**Comment by Maijin** [comment]
Agree.
