### ISSUE TITLE
sn/sp documentation difficult to understand

### ISSUE THREAD

**Issue by ewtoombs** [radare/radare2#7144]
I'm referring to the documentation printed by `e?`. The meaning of
```
| sn/sp             Seek next/prev scr.nkey
```
was less than clear. Maybe something more like this?
```
| sn/sp             Seek to next/prev location, as specified by scr.nkey
```

ASIDE:
I said this in a comment to a previous post, but I'll say it one more time. I know I'm posting a lot of bugs, without making much of an effort to actually help solve them, i.e. modify radare2 and submit a pr. This is because I'm in the middle of solving a problem using r2 and I don't like switching back and forth between using a tool and fixing its bugs. Meanwhile, if I don't document the bugs as I find them, I am likely to forget about them. I do plan on helping, but only after this problem is solved.

**Comment by ewtoombs** [comment]
Though I am starting to realise that perhaps with issues like this it is actually less work just to fix it and submit the pr...

**Comment by Maijin** [comment]
Just use the web editor of github STOP opening issue for that.

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/24334933/2aab714e-1274-11e7-98be-01f0a04935a1.png)
![image](https://cloud.githubusercontent.com/assets/1408600/24334934/2f747c98-1274-11e7-970b-30ee3e6a8172.png)
![image](https://cloud.githubusercontent.com/assets/1408600/24334942/3f109e66-1274-11e7-9792-5d5ea28459f0.png)
![image](https://cloud.githubusercontent.com/assets/1408600/24334946/4c347072-1274-11e7-8364-1a84d4135393.png)

**Comment by ewtoombs** [comment]
Well, no need to get so upset, Maijin. I'm still new to github and had no idea editing the code was so simple. Also, don't be so quick to refuse help, or shockingly nobody will ever try to help you.

**Comment by Maijin** [comment]
Where do you see I am upset ?
