### ISSUE TITLE
r2 is not as cool as defrag.exe

### ISSUE THREAD

**Issue by radare** [radare/radare2#7148]
Implement prc= subcommands to print p= subcommands but using color blocks instead of a horizontal bars. (see pz command for inspiration) on this

Also implement p=- and pz- to print the anal info in there

...

We need a better visual zoom view with support to highlight search results and other information with a secondary panel printing the contents in hexa/disasm/... maybe we can reuse the debugger view and instaed of showing the stack and registers show pz.

This fits good with the 2 dimensional visual modes.

More ideas are welcome.

We also need to make pz faster, instead of calculating everything all the time have some kind of cache

**Comment by XVilka** [comment]
Can you maybe show the screenshots of what do you want exactly?

**Comment by radare** [comment]
![](https://www.remosoftware.com/images/slider-img/drive-defragment/large-drive-defrag-2.jpg)

**Comment by radare** [comment]
What i would like some kind of `prc` but displaying entropy , printablechars, etc.. in color blocks instead off bars like p=e does

**Comment by radare** [comment]
I think we can close this now that p= p== and prc= are now in sync
