### ISSUE TITLE
Right way of recovering CFG with radare

### ISSUE THREAD

**Issue by roj4s** [radare/radare2#7158]
What I do for recovering Control Flow Graph with radare2, using r2pipe in python

After I open the file with p = r2pipe.open() and execute analysis with p.cmd('aaa') I execute following method

def dis_r(visited, p):           
    for i in p.cmdj('pdrj'):   #to disassemble all instructions in current function     
        print i                  
        if 'jump' in i.keys():    # for current instruction see if it redirects execution control
            jmp_addr = hex(i['jump']
            if jmp_addr in visited 
                print "Already visited"
            else:                       # if haven't visited dest address execute jump to that destination addr and execute same procedure     
                print "Jumping to " + jmp_address
                p.cmd("s " + jmp_address) # seek to dest address
                visited.add(jmp_adress) # add dest address so dont repeat work
                dis_r(visited, p)  # execute same procedure

Is it the right way of recovering a CFG of an entire program?

**Comment by Maijin** [comment]
cfg = r2.cmdj("agj")

**Comment by roj4s** [comment]
That command agj seems to output the control flow graph of current function only. Would tell me how to get whole graph of binary. Thanks in advance.

**Comment by alvarofe** [comment]
agC iirc

**Comment by Maijin** [comment]
| agC[j]                Same as agc -1. full program callgraph

**Comment by Maijin** [comment]
Use the documentation:
so r2.cmdj("agCj")

**Comment by Bowenduan** [comment]
Radare2 command 'agC' only extract call graph of functions, which is different from a CFG(where a node represents a basic block).

**Comment by Maijin** [comment]
Check `ag?`, if you have something you can't find from there, please open a new issue, this issue is from 2017 😄

**Comment by trufae** [comment]
just use pdJ, afb, afbj, ... there are many ways to get that info
