### ISSUE TITLE
Hint vars as signed/unsigned depending on instructions accessing it

### ISSUE THREAD

**Issue by radare** [radare/radare2#7160]

**Comment by radare** [comment]
UNASSIGNING ODDCODER, TIRED OF WAITING. MOVING FORWARD

**Comment by radare** [comment]
Checking if the overflow-bit is touched in the ESIL expression may be a hint here

**Comment by radare** [comment]
IDIV = signed division
IMUL = signed multiplication
JA/JB/JG = signed jumps
JS = if sign bit

To check if the instruction uses the overflow bit:
```
 :> ao~&esil,of
esil: sf,of,!,^,zf,!,&,?{,4294971951,rip,=,}
```

**Comment by radare** [comment]
We should start by adding bool RAnalOp.signed maybe?

**Comment by radare** [comment]
By knowing if an instruction is "signed", we may mark the registers used accordingly.

**Comment by radare** [comment]
For ARM64

```
ldrsw x0, [x1] -> load 32-bit int, sign extend to 64-bit
ldrsh x0, [x1] -> load 16-bit int, sign extend to 64-bit
ldrsb x0, [x1] -> load 8-bit int, sign extend to 64-bit

lt/le/gt/ge = less than/less or equal/greater than/greater or equal (signed)
lo/ls/hi/hs = lower/lower or same/higher/higher or same (unsigned)
```

**Comment by radare** [comment]
for MIPS

```
SLT and SLTI are for signed comparisons.
LB  --- lbu is unsigned.
ADD -- ADDU is unsigned
ADDI -- ADDIU is unsigned
SUB --
```

basically all instructions not specifying 'u' as unsigned are signed.

**Comment by wargio** [comment]
ppc
```
addi
addic
addic.
addis
cmp
cmpi
divw
divw.
divwo
divwo.
lha
lhau
lhaux
lhax
lwa
lwaux
lwax
mulli
sraw
sraw.
srawi
srawi.
subfic
tdi
tw
twi
```

**Comment by radare** [comment]
please send a PR for r2 implementing support for this. this has been merged

thanks!!
