### ISSUE TITLE
Add esil.stack.pattern

### ISSUE THREAD

**Issue by radare** [radare/radare2#7162]
To specify which pattern use:

* [x] debrujn (wop)
* [x] repeated hexpair pattern (can be a single char too) (wox)
* [x] incremental value (0001020304, by byte, half, word, dword, qword..) (woe)

Maybe we can just expect a command and set curseek and blocksize to run it, this will bemore generic so we can use any command to fill the stack

**Comment by XVilka** [comment]
Idea with command evaluation seems nice.
