### ISSUE TITLE
Pn inconsistencies

### ISSUE THREAD

**Issue by radare** [radare/radare2#7171]
* [ ] Pn? without project doesnt works
* [ ] P? shows Pn <b64> but its in reality Pnj like Pn? says
* [ ] Probably more commands like Pn+ will be good to have

And maybe have a project-less notes?

**Comment by dequis** [comment]
Also pn doesn't work, it says "easter egg license has expired". We should fix that.

**Comment by radare** [comment]
Fixed in master
