### ISSUE TITLE
Radare Stop Working With Big Binary File In Windows

### ISSUE THREAD

**Issue by mendax47** [radare/radare2#7173]
Every Time I Load A Binary File Up To 3 MB The Radare Stop Working.....
http://imgur.com/a/UrdFK

**Comment by radare** [comment]
Use -z or -n unless you need that info

**Comment by radare** [comment]
Which version of r2 are u using?

**Comment by mendax47** [comment]
I Am Using 1.3 (Latest Build)

**Comment by Maijin** [comment]
http://bin.rada.re/radare2-w32-1.4.0-git.zip

**Comment by mendax47** [comment]
Radare2 1.4 and Radare2 1.3 --> Same Problem.. (For aaaa Only)
-z -> Stop Working
-n -> Stuck At matching analysis for all functions (afta)* functions (aan)

But aa and aaa Work just fine.....

**Comment by Maijin** [comment]
`aaaa` is experimental.

**Comment by Maijin** [comment]
Need more details like file used etc and so on.
