### ISSUE TITLE
Implement zoom.in ala search.in but for pz and p=

### ISSUE THREAD

**Issue by radare** [radare/radare2#7177]

**Comment by Maijin** [comment]
Don't forget to close or use reference to close like "Add zoom.in Fix #7177" in your title or commit message @sivaramaaa 😉

**Comment by sivaramaaa** [comment]
This could be still improved , and can honor some more commands like p=e etc , hence i didin't close         
but anyways it's ok :) , thanks @Maijin  !!!

**Comment by Maijin** [comment]
yeah well i guess need to open another one with checklist for all the one that need to respect zoom.in a bit like the search.in issue

**Comment by Maijin** [comment]
and same for anal.in
