### ISSUE TITLE
radare2 and rabin2 not handling UTF-16 properly.

### ISSUE THREAD

**Issue by CodingFree** [radare/radare2#7184]
I have trying to find all the UTF-16 strings in a Windows binary. For the following environment:
e asm.arch=x86
e asm.os=windows
e asm.syntax=intel

This is the output in Windows, where a lot of strings are not found and there is only garbage:
https://pastebin.com/GqRGBQzx

But there are strings in UTF-16 that are not being found:
![Output in Windows](http://i.imgur.com/gyLCr0G.png)

This also happens in Linux:
http://paste.ubuntu.com/24280034/

Should I change any environment variable to analyze it properly? Should it be done automatically?

**Comment by radare** [comment]
this is not utf16

**Comment by radare** [comment]
Theres not usually text in the text section. It failed mainly because i dont use or care about pe binaries. It checks for data sections only, in which section is this string?

If the string is not found, add more -z to your rabin2 line

**Comment by Maijin** [comment]
```
| iz                 Strings in data sections
| izz                Search for Strings in the whole binary
```

```
man rabin2
    -z          Show strings inside .data section (like gnu strings does)

     -Z          Guess size of binary program

     -zz         Shows strings from raw bins

     -zzz        Dump raw strings to stdout (for huge files)
```
