### ISSUE TITLE
rasm2 won't assemble SVC instructions on AArch64

### ISSUE THREAD

**Issue by misson20000** [radare/radare2#7189]
Rasm2 refuses to assemble `svc` instructions on 64-bit ARM.
```
$ rasm2 -a arm -b 64 "svc 6"
Cannot assemble 'svc 6' at line 3
invalid
```

The arm.as plugin accepts it just fine.
```
$ ARM_AS=aarch64-linux-gnu-as rasm2 -a arm.as -b 64 "svc 6"
000000c10000d4
```

Version information:
```
$ rasm2 -v
rasm2 1.4.0-git 14322 @ linux-x86-64 git.1.3.0-226-g547479dad
commit: 547479dad2b8e67f203f4be4ba8fcda8aa9cbc9d build: 2017-03-30__15:47:30
```

**Comment by Maijin** [comment]
Greetings,

arm.as (*arm* handmade assembler) is one of the 2 arm assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix arm.as in https://github.com/radare/radare2-regressions/blob/master/t.asm/arm/capstone/arm_asm** You can do so with github web editor without even cloning the repo.

You can contribute to arm.as by completing the following files: 
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass.c
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass64.c

You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a arm.ks…
or in radare2 session
	e asm.assembler = arm.ks
```
