### ISSUE TITLE
Static code analysis results

### ISSUE THREAD

**Issue by AppChecker** [radare/radare2#7198]
Hi!

I've checked your projects with [Static code analyzer AppСhecker](https://npo-echelon.ru/en/solutions/appchecker.php)
It found several suspicious code fragments:
1)
[libr/flag/flag.c#L355](https://github.com/radare/radare2/blob/14094583fdb539436755e27476dd7bc7ed824bc2/libr/flag/flag.c#L355)
`		if (!strncmp (item->name, "section.", 4)) {
`
Only 4 characters will be compared, not 8 ( len of string "section." is 8)

see also:
https://github.com/radare/radare2/blob/14094583fdb539436755e27476dd7bc7ed824bc2/libr/asm/asm.c#L778 - len of ".att_syntax" is 11
https://github.com/radare/radare2/blob/14094583fdb539436755e27476dd7bc7ed824bc2/libr/socket/http_server.c#L95
https://github.com/radare/radare2/blob/14094583fdb539436755e27476dd7bc7ed824bc2/libr/asm/asm.c#L792 - excess space

2) [binr/rax2/rax2.c#L484](https://github.com/radare/radare2/blob/14094583fdb539436755e27476dd7bc7ed824bc2/binr/rax2/rax2.c#L484)

`			buf[strlen (buf)] = '\0';
`
'strlen' function calculates the number of bytes in a null-terminated string. This code  is useless (if string already ends with 0) or out-of-bounds reading can occur (if string doesn't end with 0)

3) [shlr/sdb/src/sdb.c#L708-L711](https://github.com/radare/radare2/blob/14094583fdb539436755e27476dd7bc7ed824bc2/shlr/sdb/src/sdb.c#L708-L711)
Is variable 'v' freed twice? (double free error).

I hope it will be useful to you

**Comment by radare** [comment]
Send a pr pls all those things seems to be wrong. I will take care when i get some spare time

Thanks

**Comment by alvarofe** [comment]
Fixed. Thanks for reporting
