### ISSUE TITLE
JSON output not properly escaped in ij

### ISSUE THREAD

**Issue by yetmorecode** [radare/radare2#7211]
When using JOSN output from "ij" command, radare does not properly escape backslashes in strings, thus delivering actually invalid JSON. In "ij" it's specifically the "file" field which can cause it.

This is from a fresh git build on calc.exe:
```
[0x10001b9b8]> ?V
1.4.0-git aka 1.3.0-271-g5326b2e commit 14369
[0x10001b9b8]> ij
{"core":{"type":"EXEC (Executable file)","file":"C:\Windows\System32\calc.exe","fd":3,"size":918528,"humansz":"897K","iorw":false,"mode":"-r--","obsz":0,"block":256,"format":"pe64"},"bin":{"arch":"x86","binsz":918528,"bintype":"pe","bits":64,"canary":false,"class":"PE32+","cmp.csum":"0x000eb7cb","compiled":"Tue Jul 14 00:57:08 2009","crypto":false,"dbg_file":"calc.pdb","endian":"little","havecode":true,"hdr.csum":"0x000eb7cb","guid":"E95BB5E08CE640A09C3DBF3DFA3ABCB42","intrp":"","lang":"","linenum":false,"lsyms":false,"machine":"AMD 64","maxopsz":16,"minopsz":1,"nx":true,"os":"windows","overlay":false,"pcalign":0,"pic":true,"relocs":false,"rpath":"","signed":false,"static":false,"stripped":true,"subsys":"Windows GUI","va":true}}
```

JSON is invalid as \ are not escaped in "file". Instead it should produce
```
[0x10001b9b8]> ij
{"core":{"type":"EXEC (Executable file)","file":"C:\\Windows\\System32\\calc.exe" ...
```

A similiar issue was fixed for the "dbg_file" field here: https://github.com/radare/radare2/issues/5342

**Comment by Maijin** [comment]
As said, provide binary please

**Comment by yetmorecode** [comment]
[radare2.exe.gz](https://github.com/radare/radare2/files/902542/radare2.exe.gz)

Had to gzip it, all zips I created were rejected for some strange reason.

**Comment by Maijin** [comment]
? Why did you sent the radare2 binary ? I'm speaking about the binary that cause this issue (calc.exe I guess.)

**Comment by yetmorecode** [comment]
calc.exe is bundled with every windows. Just run `radare2.exe C:\Windows\System32\calc.exe`

If on linux just rename some binary to have a slash in the name, e.g. `cp /bin/date ~; mv ~/date ~/d\\ate; radare2 ~/d\\ate` and then do "ij".

**Comment by Maijin** [comment]
kk I misread I though this was in dbg_file.

**Comment by yetmorecode** [comment]
^^ ok. I checked some other sites where I suspected similiar results as well, but strings in "izj" get base64 encoded and even my trickery of renaming a section didnt work in "iSj", so it seems it's already catched in a lot of places but simply not this one.

**Comment by yetmorecode** [comment]
Thx for the quick fix!

[date.gz](https://github.com/radare/radare2/files/902883/date.gz)

Similiar issue for the "rpath" field. I changed the rpath with `patchelf --set-rpath "invalid\\json" ~/date` to include an backslash:
```
[0x08049a76]> ij
... "bin":{... "rpath":"invalid\json"
```

**Comment by radare** [comment]
thanks!

tests are welcome

@maijin ^
