### ISSUE TITLE
r_cons_set_raw weirdness on Windows

### ISSUE THREAD

**Issue by mrexodia** [radare/radare2#7225]
1. `RCons.term_raw` and `term_buf` are of type `LPDWORD aka DWORD*`
2. Inside `r_cons_set_raw` it calls `SetConsoleMode (h, (DWORD)I.term_raw);`

Probably the type of `RCons.term_raw` should be changed to `DWORD` and `SetConsoleMode(h, &l.term_raw)` used but I'm not sure what the function should actually do (currently it looks like a no-op on Windows).

**Comment by pelijah** [comment]
It seems that the issue was fixed: https://github.com/radare/radare2/blob/master/libr/include/r_cons.h#L408

**Comment by mrexodia** [comment]
Yes, looks good!
