### ISSUE TITLE
fix Windows API warnings

### ISSUE THREAD

**Issue by mrexodia** [radare/radare2#7226]
When calling `sys/mingw64.sh` you will get lots of warnings around WinAPI. For example:

```
warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  BOOL ret = VirtualProtectEx (WIN32_PI (process), (LPVOID)(UINT)addr,
```

This will definitely break on win64. There are many other issues like it but I'm too lazy to list them all.

**Comment by XVilka** [comment]
@xarkes FYI.

**Comment by Maijin** [comment]
Closing here, added to the tracker.
