### ISSUE TITLE
Step Over in VV Doesn't Update Graph

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#7230]
Running a binary in r2 in graph (VV) mode and asking to step over ("S") fails to update the graph. Normal stepping ("s") does update the graph.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Owlz** [comment]
Ah, looks like that was fixed since 1.3.0. Thanks!
