### ISSUE TITLE
r2 db main on some PIC binaries doesn't work

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#7232]
So this behavior has been sporadic for me, so I'm attaching a file that exhibits this behavior. My use case is:

1. r2 -AA ./third
2. ood
3. db main
4. dc

However, the db main in some binaries (like the attached) isn't found. On the binary in question, you can `s main` prior to running it just fine, however once you `ood`, it will not adjust main appropriately.

In this case, I've found that running `db <map base> + main` gives the correct breakpoint.

I get the following errors from r2 when I `ood`:

```
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
```
[third.zip](https://github.com/radare/radare2/files/908649/third.zip)

**Comment by Maijin** [comment]
don't use `-AA` use `-A` or learn about analysis http://radare.today/posts/analysis-by-default/

**Comment by Owlz** [comment]
Rgr. Tried it with -A instead and it has the same problem.

**Comment by radare** [comment]
Did you tried with any symbol? Main is deduced from analysis, not symbols.

**Comment by Maijin** [comment]
main symbol is in the binary I checked

**Comment by radare** [comment]
main != sym.main

**Comment by Maijin** [comment]
main is here

**Comment by Maijin** [comment]
Since you were using super old r2, can you try with the recent one ?

**Comment by Owlz** [comment]
Tried it with latest version and still doesn't work. db main and db sym.main both work pre-ood. Post-ood, main doesn't work but sym.main does.

```
WARNING: bin_strings buffer is too big (0xffffa9ec5b17f788). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
WARNING: bin_strings buffer is too big (0xffffa9ec5b17f288). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
```

**Comment by radare** [comment]
So its exactly what i said. This is a oneline fix. Will do as soon as i reach my laptop
