### ISSUE TITLE
asm.spacy vs asm.bbline

### ISSUE THREAD

**Issue by radare** [radare/radare2#7233]
Seems kind of duplicated feature

* bbline adds a linea after each basic block and requires code to be analized
* spacy adds a space after each instruction that breaks a bb, doesnt requires code to be analized, creates some ascii-art artifacts and issues in the jump lines

**Comment by radare** [comment]
One option would be to merge both into a single, this is. use the fcn anal info if found, otherwise just go for the opinfo one. and fix the glitch issues.Which name would you keep bbline or spacy?

**Comment by Maijin** [comment]
bbline is better than spacy for sure

**Comment by radare** [comment]
ok, so the plan is to kill asm.spacy, and just have asm.bbline, which will do whatever its possible without analysis information if not available, and honor the analysis info if found.

**Comment by radare** [comment]
i did that already in master
