### ISSUE TITLE
drx-0 fails

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#7269]
So playing with hardware breakpoints, it seems not possible to delete one.

```
[0x004004a6]> drx 0 0x004004ad 1 x
[0x004004a6]> drx-0
Invalid DRX length (-1) must be 1, 2, 4, 8 bytes
[0x004004a6]> drx
* dr0 Gx 0x004004ad 1
- dr1 Lx 0x00000000 1
- dr2 Lx 0x00000000 1
- dr3 Lx 0x00000000 1
- dr6 Lx 0x00000001 1
- dr7 Lx 0x00000001 1
```

It appears to be attempting to validate the command as if i were adding a breakpoint, when I'm trying to remove it. This is version 1.3.0. I was not able to try against the latest git since when i run the command `ood` in the latest version (pulled today), it causes the program to go into a series of strange prompts.

**Comment by skuater** [comment]
fixed on #7275
