### ISSUE TITLE
Support hsalsa20 in rahash2

### ISSUE THREAD

**Issue by radare** [radare/radare2#7272]
https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/HSalsa20.c

**Comment by radare** [comment]
test cases https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/test-salsa.c

**Comment by radare** [comment]
"just for the record, Salsa20 is a stream cipher, while AES is a block cipher."

**Comment by wargio** [comment]
@Maijin add this to your issue list for ciphers.

**Comment by wargio** [comment]
@radare is it really needed?

**Comment by Maijin** [comment]
Added closing here
