### ISSUE TITLE
Abstract API for accessing function arguments and structure/union elements

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#7293]
Currently in libr/anal and everywhere else you can find some code duplication, and it will be useful for improving other plugins too. Something abstract, like graph api for example.

**Comment by radare** [comment]
This looks like meta

**Comment by sivaramaaa** [comment]
@XVilka Currently, I have moved most of the function argument logic into libr/core/carg.c , still some dupes have to be merged like afvd
 
Now u have an api to access function arguments ``` R_API RList *r_core_get_func_args ```

So a little bit of refactoring and implementing an API for accessing structure/union elements should be done to close this issue I guess

**Comment by sivaramaaa** [comment]
I thinks it's good to close this issue, Now we have all API's required : 

* For function accessing argument : 
```
R_API RList *r_core_get_func_args(RCore *core, const char *fcn_name)
```

* For accessing structure elements

```
R_API char *r_type_get_struct_memb(Sdb *TDB, const char *type, int offset)
```
