### ISSUE TITLE
Warnings on installation!

### ISSUE THREAD

**Issue by Sn0keR4xor** [radare/radare2#7307]
Hi, I real love the project and I'm thinking in move from gdb and objdump to r2...

while i was installing r2, i got some warnings:

p/crypto_xor.c: In function ‘xor_init’:
p/crypto_xor.c:14:6: warning: unused variable ‘i’ [-Wunused-variable]
  int i;//index for key
      ^~~~

~/git/radare2/libr/..//libr/anal/p/../..//asm/arch/tms320/c55x_plus/hashvector.c:97:25: warning: ‘ins_hash’ defined but not used [-Wunused-variable]
 static HASHCODE_ENTRY_T ins_hash[] = {
                                                         ^~~~~~~~

~/git/radare2/libr/..//libr/bin/p/bin_sfc.c:99:13: warning: ‘addsym’ defined but not used [-Wunused-function]
 static void addsym(RList *ret, const char *name, ut64 addr, ut32 size) {
                       ^~~~~~

p/../arch/arm/gnu/arm-dis.c: In function ‘print_insn_coprocessor’:
p/../arch/arm/gnu/arm-dis.c:3374:19: warning: variable ‘value_in_comment’ set but not used [-Wunused-but-set-variable]
       signed long value_in_comment = 0;
                                   ^~~~~~~~~~~~~~~~

CC debug_rap.c
p/../arch/arm/gnu/arm-dis.c: In function ‘print_insn_neon’:
p/../arch/arm/gnu/arm-dis.c:4127:16: warning: variable ‘value_in_comment’ set but not used [-Wunused-but-set-variable]
    signed long value_in_comment = 0;
                                  ^~~~~~~~~~~~~~~~
CC aarch64-dis-2.c
p/../arch/arm/gnu/arm-dis.c: In function ‘print_insn_thumb16’:
CC aarch64-opc.c
p/../arch/arm/gnu/arm-dis.c:5169:14: warning: variable ‘value_in_comment’ set but not used [-Wunused-but-set-variable]
  signed long value_in_comment = 0;
                                          ^~~~~~~~~~~~~~~~
CC debug_wind.c
p/../arch/arm/gnu/arm-dis.c: In function ‘print_insn_thumb32’:
p/../arch/arm/gnu/arm-dis.c:5477:14: warning: variable ‘value_in_comment’ set but not used [-Wunused-but-set-variable]
  signed long value_in_comment = 0;
                                     ^~~~~~~~~~~~~~~~
CC linux_debug.c
p/asm_arm_gnu.c: In function ‘disassemble’:
p/asm_arm_gnu.c:124:13: warning: variable ‘oldcpucode’ set but not used [-Wunused-but-set-variable]
  static int oldcpucode = 0;
                       ^~~~~~~~~~
CC aarch64-opc-2.c
p/debug_native.c: In function ‘r_debug_native_wait’:
p/debug_native.c:306:6: warning: unused variable ‘status’ [-Wunused-variable]
  int status = -1;
           ^~~~~~

p/debug_native.c: In function ‘r_debug_native_pids’:
p/debug_native.c:499:12: warning: variable ‘gid’ set but not used [-Wunused-but-set-variable]
   int uid, gid;
                ^~~
At top level:
p/debug_native.c:101:12: warning: ‘r_debug_handle_signals’ defined but not used [-Wunused-function]
 static int r_debug_handle_signals (RDebug *dbg) {
                              ^~~~~~~~~~~~~~~~~~~~~~
CC asm_arm_winedbg.c
CC procfs.c
CC asm_avr.c
CC linux_coredump.c
p/native/linux/linux_debug.c: In function ‘linux_handle_signals’:
p/native/linux/linux_debug.c:69:2: warning: #warning DO MORE RDEBUGREASON HERE [-Wcpp]
 #warning DO MORE RDEBUGREASON HERE
        ^~~~~~~

I'm using: gcc (Debian 6.3.0-11) 6.3.0 20170321

**Comment by radare** [comment]
all those warnings are harmless and well known, thanks for reporting, you can try sending a PR fixing them if you are in the mood.

—pancake
