### ISSUE TITLE
'afb' seems broken

### ISSUE THREAD

**Issue by HostageBrain** [radare/radare2#7308]
I've had 'radare2-w32-0.10.0' - command 'afb' worked fine - it printed list of basic blocks.
```
[0x004016c0]> afb 0x0040e91c
0x0040e91c 0x0040e932 00:0000 22 j 0x0040e9dd f 0x0040e932
0x0040e932 0x0040e940 00:0000 14 j 0x0040e960 f 0x0040e940
0x0040e940 0x0040e960 00:0000 32 j 0x0040e962
0x0040e960 0x0040e962 00:0000 2 j 0x0040e962
0x0040e962 0x0040e983 00:0000 33 j 0x0040e9dd f 0x0040e983
0x0040e983 0x0040e987 00:0000 4 j 0x0040e991
0x0040e987 0x0040e991 00:0000 10 j 0x0040e991
0x0040e991 0x0040e9db 00:0000 74 j 0x0040e987 f 0x0040e9db
0x0040e9db 0x0040e9dd 00:0000 2 j 0x0040e9dd
0x0040e9dd 0x0040e9e7 00:0000 10
```

Now I've tried 'radare2-w32-1.3.0', 'radare2-w32-1.2.0', 'radare2-w32-1.1.0' - 'afb' prints only the first basic block info:
```
[0x004016c0]> afb 0x0040e91c
0x0040e91c 0x0040e932 00:0000 22 j 0x0040e9dd f 0x0040e932
```

I've tested this on different files & on linux - looks like from version ~1.0.0 'afb' either broken or changed way how it works.
Maybe I'm doing something wrong.

**Comment by radare** [comment]
the behaviour changed.

put an @ between afb and the address to get the previous output,
