### ISSUE TITLE
Add the number of loops in a function in `afi`

### ISSUE THREAD

**Issue by radare** [radare/radare2#7309]
* useful for signature metrics
* required by diaphora
* fun to do

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
ping @rlaemmert

**Comment by XVilka** [comment]
@rlaemmert since you're assigned here, can you please update?

**Comment by rlaemmert** [comment]
yea had no time to do anything here

**Comment by radare** [comment]
ping
