### ISSUE TITLE
Allow to list and open zignatures from system and home directories

### ISSUE THREAD

**Issue by radare** [radare/radare2#7311]
Required to r2pm-ify some zignatures

* [ ] Add tests

**Comment by radare** [comment]
i did that already in c91339830e48e0d9e0aa36e1b537cb27c28ee012

still waiting for someone to push their signatures

**Comment by Maijin** [comment]
But it doesn't work as explain on telegram. When zignatures are inside the folder they aren't automatically import nor the path is added to the autocompletion so it's not done yet, reopening

**Comment by Maijin** [comment]
zig-masm32     	 [r2-zig] Get zignatures for MASM32 libraries

**Comment by radare** [comment]
why reopen?

**Comment by Maijin** [comment]
It is not fixed I just explained why

**Comment by Maijin** [comment]
https://asciinema.org/a/52js8y4qu29pnq96auqh8w0y9 Even got an asciinema.

**Comment by radare** [comment]
you see it you fix it (didnt seen the asciinema yet)

**Comment by jroimartin** [comment]
Fixed via 946b35f96730c7015c9ac9f9ef7b2971516f5e5f

**Comment by Maijin** [comment]
great !
