### ISSUE TITLE
"ahi s" regression

### ISSUE THREAD

**Issue by pachulo** [radare/radare2#7315]
- Binary for testing (from [A journey into Radare2 - part 1](https://www.megabeets.net/a-journey-into-radare-2-part-1/)): https://github.com/ITAYC0HEN/A-journey-into-Radare2/blob/master/Part%201%20-%20Simple%20crackme/megabeets_0x1

When using radare2 1.3.0 this works OK:

```
[0x08048585]> pdf @ sym.beet

...

0x080485a3  c7856effffff.  mov dword [ebp - local_92h], 0x6167654d
0x080485ad  c78572ffffff.  mov dword [ebp - local_8eh], 0x74656562
0x080485b7  66c78576ffff.  mov word [ebp - local_8ah], 0x73 ; 's'

...

[0x08048585]> ahi s @@=0x080485a3 0x080485ad 0x080485b7

...

0x080485a3   c7856effffff.  mov dword [ebp - local_92h], 'ageM'
0x080485ad   c78572ffffff.  mov dword [ebp - local_8eh], 'teeb'
0x080485b7   66c78576ffff.  mov word [ebp - local_8ah], 's' ; 's'

...

```

But I can't get it to work in version 1.4.0 (or master); it is like the "ahi s" command was never executed:

```
[0x08048585]> pdf @ sym.beet

...

0x080485a3  c7856effffff.  mov dword [ebp - local_92h], 0x6167654d
0x080485ad  c78572ffffff.  mov dword [ebp - local_8eh], 0x74656562
0x080485b7  66c78576ffff.  mov word [ebp - local_8ah], 0x73 ; 's'

...

[0x08048585]> ahi s @@=0x080485a3 0x080485ad 0x080485b7

...

0x080485a3  c7856effffff.  mov dword [ebp - local_92h], 0x6167654d
0x080485ad  c78572ffffff.  mov dword [ebp - local_8eh], 0x74656562
0x080485b7  66c78576ffff.  mov word [ebp - local_8ah], 0x73 ; 's'

...

```

Am I missing something? Is it already reported?

**Comment by radare** [comment]
seems like a regression, because there are no tests for this. and it’s easy to fix. wanna try to send a pr? and i can confirm the new behaviour is not ok

**Comment by pachulo** [comment]
OK, I will try, but I will need some guidance...for what I've seen the two main files involved in this are these:

- libr/core/cmd_anal.c
- libr/anal/hint.c

I'm not seeing any difference in the second one between tags 1.3.0 and 1.4.0, so my bet is that some change in the first one is to blame.

Am I in the right path?

**Comment by alvarofe** [comment]
from the top of my head I would say the function `filter` in libr/parse/parse.c is involved in this. You could `git bisect` to detect which commit introduced the regression and figure out how is done.

**Comment by pachulo** [comment]
@alvarofe You're right, `git bisect` took me to this commit:

- https://github.com/radare/radare2/commit/d9d83914

That is modifying the function filter in the `libr/parse/parse.c` file that you talked about.

**Comment by alvarofe** [comment]
Now you got the culprit :)

**Comment by pachulo** [comment]
Ok, I think I got more info: the real culprit seems to be this change in the commit https://github.com/radare/radare2/commit/d9d83914#diff-7b45b46dd8a84a924b91f34c2b1e6309L751

For what I've seen in the debugger, this is the difference between the old and the new parameters for my test case:
```
gef➤  print ds->opstr
$6 = 0x55555591adf0 "mov dword [edi], 0x6167654d"
gef➤  print asm_str
$4 = 0x55555591a790 "mov dword\033[36m \033[0m[\033[36medi\033[0m]\033[36m\033[0m,\033[36m\033[36m \033[33m0x6167654d\033[0m"
```
And just reverting it back to:
`r_parse_filter (core->parser, core->flags, ds->opstr, ds->str, sizeof (ds->str), core->print->big_endian);`

Solves the regression, but I'm not really sure why it was changed in the first place and what does it implies.

By the way, should I do a PR in https://github.com/radare/radare2-regressions adding a test for this?

**Comment by alvarofe** [comment]
send a PR to test this change to see what breaks. Basically the difference between asm_str and ds->opstr is output with color from what i can see. And yes, send as well a PR to r2r to avoid such regression in the future.

**Comment by pachulo** [comment]
PRs created!

The only thing that bothers me is that I realised that since the regression, ahi s was not applied when disassembling with pd, but it was when disassembling with pi (you had test cases with pi, but not with pd).

**Comment by radare** [comment]
Just add more tests so this wont happen again

**Comment by radare** [comment]
pi and pd use different disasm loops

**Comment by kazarmy** [comment]
I'll have a look. The [`filter` code that handles hints](https://github.com/radare/radare2/blob/d9d839147e5f1315dd05698f2e2088aba8b29dc7/libr/parse/parse.c#L295) doesn't seem to be color-aware so that's where I think a fix should be made. This might take a day or 2.

**Comment by radare** [comment]
We can wait, you can join the irc or telegram channel if you want some more hints :)

Thanks

**Comment by kazarmy** [comment]
Fortunately the fix is familiar so don't have to wait too long: #7343.
