### ISSUE TITLE
what the "type" and "type_num" fields in pdj 1 output stands for

### ISSUE THREAD

**Issue by roj4s** [radare/radare2#7319]
when executed pd 1 on an open file it returns something like: [{"offset":4213152,"esil":"ebp,ebp,^=,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=,0xffffffff,rbp,&=","refptr":false,"fcn_addr":4213152,"fcn_last":4213191,"size":2,"opcode":"xor ebp, ebp","bytes":"31ed","family":"cpu",**"type":"xor","type_num"**:28,"type2_num":0,"flags":["entry0"]}]

What is the meaning of the fields type and type_num in that output. Is there any place where I could find an explanation for any field in this and other outputs. Thanks in advance.

**Comment by radare** [comment]
It means type of instruction and the numeric id for that type. That comes from capstone

**Comment by radare** [comment]
You can find everything explained in C

**Comment by roj4s** [comment]
Is possible to get the exact object representation returned by capstone using r2 from python? I need to get :   (Bellow snippet taken from capstone.h file in https://github.com/aquynh/capstone/blob/master/include/capstone.h)

 Common instruction operand types - to be consistent across all architectures.
typedef enum cs_op_type {
	CS_OP_INVALID = 0,  // uninitialized/invalid operand.
	CS_OP_REG,          // Register operand.
	CS_OP_IMM,          // Immediate operand.
	CS_OP_MEM,          // Memory operand.
	CS_OP_FP,           // Floating-Point operand.
} cs_op_type;

//> Common instruction groups - to be consistent across all architectures.
typedef enum cs_group_type {
	CS_GRP_INVALID = 0,  // uninitialized/invalid group.
	CS_GRP_JUMP,    // all jump instructions (conditional+direct+indirect jumps)
	CS_GRP_CALL,    // all call instructions
	CS_GRP_RET,     // all return instructions
	CS_GRP_INT,     // all interrupt instructions (int+syscall)
	CS_GRP_IRET,    // all interrupt return instructions
} cs_group_type;

**Comment by radare** [comment]
Capstone doesnt returns any object.

**Comment by roj4s** [comment]
I think I found an answer to my own question: I can take the bytes given in the field bytes of pdj 1 and disassembly it with capstone, that way I'll have that object capstone gives for every instruction it disassemble.

**Comment by radare** [comment]
This info is in opex. Dont overengineer

**Comment by roj4s** [comment]
What's opex?

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/25282859/0b05bc26-26b2-11e7-8173-87d98791c3d5.png)

**Comment by roj4s** [comment]
nice, thanks!!
