### ISSUE TITLE
Erronous error message when using gdb (Underlaying IO descriptor is not a GDB one)

### ISSUE THREAD

**Issue by mscherer** [radare/radare2#7329]
Using gdb result in a harmless yet scary message: 

```
$ r2 -D gdb  gdb://127.0.0.1:5002 /bin/ls
= attach 4 4
ERROR: Underlaying IO descriptor is not a GDB one..
ERROR: Underlaying IO descriptor is not a GDB one..
ERROR: Underlaying IO descriptor is not a GDB one..
```

It seems something somewhere is trying to open file using the default i/o plugin, and I am not sure if that's causing trouble or not. It might be harmless, it might not, so I think it should be hidden and/or changed if that's harmless.

**Comment by mscherer** [comment]
In fact, looking around, I am not sure why it do show a message in the first place, since it do not act on it and just ignore the attach. It should at least return "false" or something ?

Also, since r_debug_attach in libr/debug/debug.c is probing all plugin by running attach, maybe the message shouldn't be shown ?

**Comment by radare** [comment]
Its ok.

You are telling radare to open 2 files, the second is a local file so it is not a gdb descriptor

**Comment by mscherer** [comment]
Ok, indeed, I didn't realized I was opening 2 files. Sorry for the trouble :/
