### ISSUE TITLE
Unicode/ASCII graphs for radiff2

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#7332]
To be able to compare without invoking dot or whatever else. As a bonus - visual graph diff mode in radare2 itself. Interactive one.

- [x] flag to specify which kind of output we want: graphviz or asciiart. and maybe sdb-k/v, csv, etc...
- [x] use the RGraph API for that
- [x] interactive visual mode
- [ ] panels support

**Comment by XVilka** [comment]
@cyanpencil please see also this one.

**Comment by XVilka** [comment]
See also https://github.com/radare/radare2/issues/3508

**Comment by XVilka** [comment]
@deepakchethan see `libr/core/canal.c` - radiff2 currently uses `r_core_anal_graph` function, which I think should use `r_agraph_*` API from `libr/core/agraph.c`, that allows to set the style of the output - dot, ASCII/Unicode, JSON, HTML, etc.

**Comment by deepakchethan** [comment]
It is done at https://github.com/radare/radare2/pull/14831, can be closed now :)
