### ISSUE TITLE
Show charsets used in string

### ISSUE THREAD

**Issue by radare** [radare/radare2#7335]
it will be cool to have, not only the encoding (utf8, ..) but also the charset used, this is:

* cyrillic
* japanese
* chinese
* ...

Info about ranges used for those glyphs would be good

**Comment by XVilka** [comment]
Related (can share some code) https://github.com/radare/radare2/issues/2032

**Comment by radare** [comment]
cc @kazarmy

**Comment by kazarmy** [comment]
Probably best to base this on Unicode's [Blocks.txt](http://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt) ([terms of use](http://www.unicode.org/copyright.html)).

**Comment by kazarmy** [comment]
Also, probably best not to show this for non-Unicode single-byte encodings such as [code page 437](https://en.wikipedia.org/wiki/Code_page_437) even after translation to Unicode, since some symbols [have multiple possible translations](https://en.wikipedia.org/wiki/Code_page_437#Notes).

**Comment by kazarmy** [comment]
Hmm,

`asm.cmtcharblk`: Show block membership for the chars in the Unicode string.

**Comment by Maijin** [comment]
You can first add this display in `iz`, `izz` and `izzj` without the need of an eval.

**Comment by kazarmy** [comment]
Regarding the `iz` commands, can I replace `wide` with `utf16le` and `wide32` with `utf32le`?

**Comment by radare** [comment]
Yep sgtm

**Comment by kazarmy** [comment]
I think there should be an eval var (like `asm.cmtcharblk`) that adds `pd` Unicode block comments.

> Info about ranges used for those glyphs would be good

Just look up the mapping at [Blocks.txt](http://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt)?

**Comment by Maijin** [comment]
Well no, because different charset can be used at different places, probably an argument for a different CX could do the trick no?

Or can you give more precision on what you trying to achieve ? Don't get it

**Comment by kazarmy** [comment]
> ... argument for a different CX ...

What's CX?

> Or can you give more precision on what you trying to achieve ?

The following:
```
[0x00401740]> ps8b @ 0x004021ff  # ps8: print utf8 string, b: suffix for show blocks
0x004021ff Basic Latin: utf8> \u00a2\u20ac\U00010348 in yellow:\e[33m 
0x0040222c Latin-1 Supplement/2: ¢
0x0040222e Currency Symbols/3: €
0x00402231 Gothic/4: 𐍈
0x00402235 Basic Latin:  \e[0m\n
```
The numbers after the slash show the number of bytes per char. If there's no slash, the number of bytes per char is 1.

**Comment by kazarmy** [comment]
This appears better:

```
[0x00401740]> psgk @ 0x004021ff
0x004021ff Basic Latin: utf8> \u00a2\u20ac\U00010348 in yellow:\e[33m 
0x0040222c Latin-1 Supplement/2: ¢
0x0040222e Currency Symbols/3: €
0x00402231 Gothic/4: 𐍈
0x00402235 Basic Latin:  \e[0m\n
Encoding: utf8
```
 - "g" stands for guess and the guessed encoding is shown on the last line
 - "k" suffix is used since "b" is already used for another kind of block

Btw, "block" is shorter and more accurate compared to "charset" so I'm sticking with it.

**Comment by Maijin** [comment]
What's CX?

Is something to create, X being a letter to choose.

**Comment by kazarmy** [comment]
Still don't get it tbh. Example?

**Comment by kazarmy** [comment]
Or do you mean something like `C8[@addr] __________ add utf-8 string`?

**Comment by Maijin** [comment]
yes something like that, although i was thinking of same stuff as ps you just shown.

So Csgk, Cs8b etc.

**Comment by kazarmy** [comment]
Can `Cs` change the information provided by `iz`/`izz`?

**Comment by Maijin** [comment]
Nop it's two different mechanism

**Comment by kazarmy** [comment]
Can I modify `Cs` so that it changes the information provided by `iz` / `izz`?

**Comment by kazarmy** [comment]
Perhaps I should change `iz`/`izz` so that it also considers the information provided by `Cs`.

**Comment by kazarmy** [comment]
Hmmm,

```
iz|izj             Strings in data sections (in JSON/Base64) -- Cs overrides
```
`Cs` with size 0 deletes.

**Comment by Maijin** [comment]
Well no, this is same as iS and S difference

**Comment by kazarmy** [comment]
Okay, it's `iz` and `Cs` then. Currently, `Cs` by itself without arguments doesn't list out strings so that needs to change.

**Comment by kazarmy** [comment]
... `Cs` being the equivalent of `S`.

**Comment by Maijin** [comment]
kk

**Comment by Maijin** [comment]
ping @kazarmy

**Comment by kazarmy** [comment]
I'll see what can be done on the weekend.

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
@cyanpencil check also this.

**Comment by Maijin** [comment]
Fixed in https://github.com/radare/radare2/pull/8237 and https://github.com/radare/radare2/pull/8242
