### ISSUE TITLE
`aoj~{opex}` need to show just "opex" part of JSON output of `aoj`, pretty printed

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#7336]
Currently it prints the whole output of json. Need to be able to extract just part of it.

**Comment by Maijin** [comment]
Don't think r2 is supposed to be used for parsing json...

**Comment by radare** [comment]
But it should

**Comment by Maijin** [comment]
![image](https://cloud.githubusercontent.com/assets/1408600/25293023/23a984e8-26d9-11e7-8d8f-85cd534d21a1.png)

**Comment by radare** [comment]
Cant find r2 in this table

**Comment by Maijin** [comment]
:/

**Comment by radare** [comment]
this is a regression. it was working when i implemented it

**Comment by radare** [comment]
This should be done by [0x1000011e0]> aoj~{opex}~{}

**Comment by radare** [comment]
```
[0x1000011e0]> aoj~{[0].opex}
```

**Comment by radare** [comment]
it returns an array not an object. just [0]. and well, not prettyprinted because nested greps doesnt work yet

**Comment by XVilka** [comment]
@ret2libc FYI - it would be awesome to handle this case (the nested greps) in the new parser.

**Comment by ret2libc** [comment]
@XVilka from the parser point of view it is very easy to handle nested greps (and I actually first implemented it that way), but unfortunately as @radare said nested greps are not supported by the rest of the code so we first need to change how grep works to make that work.

**Comment by radare** [comment]
it works as expected

```
[0x10000102c]> pd~call
        │   0x100001055      e858310000         call sym.func.1000041b2
            0x100001063      e89e340000         call sym.imp.setlocale
            0x10000106d      e83a340000         call sym.imp.isatty
        │   0x100001087      e8f0330000         call sym.imp.getenv
      │││   0x100001099      e87e330000         call sym.imp.atoi
     │  │   0x1000010b0      e8f1330000         call sym.imp.ioctl
       │    0x1000010e2      e895330000         call sym.imp.getenv
       ││   0x1000010ef      e828330000         call sym.imp.atoi
       ╰╰─> 0x1000010fa      e88f330000         call sym.imp.getuid
        │   0x100001120      e88d300000         call sym.func.1000041b2
[0x10000102c]> pd~call~get
        │   0x100001087      e8f0330000         call sym.imp.getenv
       │    0x1000010e2      e895330000         call sym.imp.getenv
       ╰╰─> 0x1000010fa      e88f330000         call sym.imp.getuid
[0x10000102c]>
```

**Comment by radare** [comment]
we should ahve tests for this btw

**Comment by ret2libc** [comment]
> it works as expected

It does not AFAIK. It works in some particular cases only because `r_cons_grep_process` transforms `~call~get` into a multi-word search, but that's all. If you perform two times the call to `r_cons_grep_process` it won't work.

example:
```
>  pd 10~lea[3]
r8
rcx
> pd 10~lea[3]~cx
r8
rcx
```

**Comment by radare** [comment]
well, its not perfect :D and there are no tests at all, anyone is welcome to help by adding tests, filling issues or fixing bugs. thanks for finding out this case, and yes. this syntax should be supported by the new parser
