### ISSUE TITLE
afll? should explain the header abbreviations

### ISSUE THREAD

**Issue by EmilyBragg** [radare/radare2#7338]
afll outputs the following fields:
> "address     size  nbbs edges    cc cost   min bound range max bound   calls locals args xref frame name"

but there is no explanation anywhere that I can find of what those fields are. Some are explanatory, but nbbs, cc, and cost in particular would be good to have a definition of available, and ideally typing afll? would show what all of the fields correspond to. Current behavior for 'afll?' is the same as 'afll'; it just ignores the '?'.

**Comment by Maijin** [comment]
nbbs = Number of basic blocks
cc = cyclomatic-complexity
etc.
It's the same as the stuff in `afi`

**Comment by Maijin** [comment]
Feel free to improve the documentation by adding `afll?` https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L1386

**Comment by EmilyBragg** [comment]
will do! I'm just starting with using radare2, and afi doesn't have documentation of what the fields are either, just the common terms (as 'afi?' doesn't have anything either).

**Comment by Maijin** [comment]
Then feel free to add a doc to `afi?` too

**Comment by EmilyBragg** [comment]
sounds good. Thanks for the prompt responses!
