### ISSUE TITLE
'iz' and 'izj' string contents do not match ('izj' contents incorrect)

### ISSUE THREAD

**Issue by EmilyBragg** [radare/radare2#7340]
'iz' returns the correct string contents; 'izj' does not. 

version information:
radare2 1.4.0-git 14552 @ linux-x86-64 git.1.4.0-18-g92dc32b
commit: 92dc32ba3cd9a3c6b5a138b4e2798dd8a00f2152  build: 2017-04-21__17:42:49
This bug also manifests in the 1.4.0-git 14436 release. 

Simple test program used is attached.
> [0x00000000]>o test.o
> [0x000003e0]>aaa
> [0x000003e0]> iz
vaddr=0x000005d8 paddr=0x000005d8

 ordinal=000 sz=6 len=5 section=.rodata type=ascii string=Hello
vaddr=0x000005de paddr=0x000005de ordinal=001 sz=10 len=9 section=.rodata type=ascii string=Hi There!

>[0x000003e0]> izj
[{"vaddr":1496,"paddr":1496,"ordinal":0,"size":6,"length":5,"section":".rodata","type":"ascii","string":"SGVsbG8="},{"vaddr":1502,"paddr":1502,"ordinal":1,"size":10,"length":9,"section":".rodata","type":"ascii","string":"SGkgVGhlcmUh"}]

Test program (compiled with g++ -o test.o ./test_program.cpp, g++ version Apple LLVM version 8.1.0 (clang-802.0.38))
```
int main(void){
	int a = 5;
	char* b = "Hello";
	double c = 1.55;
	char* e = "Hi There!";

	while (a==5) {
		if (e[1] == 'i') {
			return -1;
		} else {
			while (c > 0) c--;
		}
	
	}


	return 0;
}
```

**Comment by radare** [comment]
This is base64. Strings do match

**Comment by EmilyBragg** [comment]
Sorry about that, I've only seen base64 used for encoding data blobs in JSON, not used for strings (as they're already string-representable) . Is this for compatibility purposes across different character sets? If nothing else, it might be useful to mention the behaviour in the help text for 'iz', as if you're scripting using r2pipe it's unexpected behavior for the results to be different (without further action at least) between 'iz' and 'izj'.

**Comment by radare** [comment]
The problem is that not all strings can be represented here, escaping the binary data could be an option, but turned to be a bit problematic in some cases where different encodings are used and the parser assumes utf8. I agree that plain escaped string makes more sense and its one step less to process that. Anyone else have some thougs on this?

**Comment by radare** [comment]
I was trying to discuss if non base64 was fine for everyone
