### ISSUE TITLE
Integrate "e??", "et" and "e var=?" into "ej"

### ISSUE THREAD

**Issue by yetmorecode** [radare/radare2#7342]
For external tools it can be very helpful to known the type and valid values of a config entry. E.g. an UI could provide different widgets like a combobox or numberfields or stringfields when editing the config.

For that reason I would like to suggest adding the output of "e var=?" into "ej".

Preferably I would also like to see the type information from "et". Kind of the same argumentation goes for "e??" which provides information also very useful to endusers of potential radare2 based tools.

If "ej" shouldn't be changed from the current compact format, I could also see an "ev|evj" (verbose|verbose json) command helpful.

Here an example (name, value, type, help, [choices]):
`
[...
{"name":"zign.graph", "value":true, "help": "Use graph metrics...", "type":"bool"},
{"name":"dbg.algo", "value":"fuzzy", "help":"...", "type":"str", choices:["default", "fuzzy", "anal"]
...]
`

The more I realize how different the format is from current "ej" the more i prefer the "evj" approach. I would be willing to prepare a PR but obviously want to discuss it first. What do you think?

**Comment by radare** [comment]
👍

**Comment by radare** [comment]
Do you wanna do the PR?

**Comment by yetmorecode** [comment]
Yes, let me try. 

Just to be clear, we going for "evj" now, right?

**Comment by radare** [comment]
Yep

**Comment by yetmorecode** [comment]
Ok, most of it was pretty straight forward.

`e var=?` however is a bit more difficult. The help there is just printed from the config node setter callbacks. There is no way to access it for json export.

Can we add an `RList *options` to RConfigNode? For all types but string it would be NULL, for string types in can specify an list of options while the config node setter is still responsible for deciding what to do with it (e.g. hard filter by the values or just provide hints but allow other values).

Options would than be initialized in with an additional macro next to defining them in cconfig.c. Certain plugins/components could even go as far as adding options themselfs (instead of defining them centralized in cconfig.c).

**Comment by radare** [comment]
this list is usually generated at run time, and config aims to be something static, for example asm.cpu=? possible values depend on asm.arch plugin but search.in=? values are always the same.. if you have this in mind maybe it makes sense to move this logic into rconfig.

**Comment by yetmorecode** [comment]
I just want to expose those values somehow to the commands. I went ahead and implemented it, please have a look at the PR.

**Comment by yetmorecode** [comment]
done :+1:
