### ISSUE TITLE
aaaa slow complaint

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#7345]
morrn,

@pancake
it takes 54:19.64 min to analyse node-js (stable) binary with aaaa. attaching strace -p shows:
,su -c 'strace -v -p 1269'
Password: 
Process 1269 attached
brk(0x563db6d3d000)                     = 0x563db6d3d000
brk(0x563db6d71000)                     = 0x563db6d71000
brk(0x563db6d94000)                     = 0x563db6d94000
brk(0x563db6db7000)                     = 0x563db6db7000
brk(0x563db6de0000)                     = 0x563db6de0000
brk(0x563db6e10000)                     = 0x563db6e10000
brk(0x563db6e4a000)                     = 0x563db6e4a000
brk(0x563db6e74000)                     = 0x563db6e74000
^C

How much is long enough for a recursive analysis ?

Greetings
zlul

**Comment by zonkzonk** [comment]
r2 -v
radare2 1.4.0 14560 @ linux-x86-64 git.1.4.0-21-g8e63cba
commit: 8e63cba29aed1f92faba2bcd60d749444e9e7e4d build: 2017-04-22__21:23:44

**Comment by XVilka** [comment]
- known issue
 - please profile using kcachegrind or something like that and point precise places that took longest.

**Comment by radare** [comment]
Thats expected aaaa is experimental and not recommended for big binaries, i dont think we want an issue for this

**Comment by Maijin** [comment]
No we don't
