### ISSUE TITLE
Flags at address

### ISSUE THREAD

**Issue by hteso** [radare/radare2#7347]
It would be nice to have a command (let's say `xy`) that would return any flag referenced by the opcode at a specified address. Example:

- For the following opcode: `0x08048d6a cmp dword [arg_8h], 2` the command `xy @ 0x08048d6a` should return `arg_8h`.
- For this one: `0x08048d84 call sub.fwrite_340`, the command `xy @ 0x08048d84 ` should return `sub.fwrite_340 `

And so on. I have been told that the command `fd` does this, but it just returns the function name + offset where the address is located: `fd @ 0x08048d84` returns `main + 36`.

**Comment by Maijin** [comment]
arg_8h is not a flag
for the call:

```
fd @ `ao~jump[1]`
```

Obviously with aoj if you're going to add that in iaito

**Comment by hteso** [comment]
Thanks, that works, but only if you have already moved (seek) to that address, I need a command that gives me that same information without have to seek first.

I also need similar commands to get if the target opcode contains a reference to a:

- String
- Local var
- Arg
- etc

Yes, I need that information to give the user specific options on the context menu when they right-click on the disassembly view in Iaitō.

**Comment by Maijin** [comment]
? You can do 

```
fd @ `ao~jump[1] @ addr`
```

**Comment by yetmorecode** [comment]
> I also need similar commands to get if the target opcode contains a reference to a:
>
> String
> Local var
> Arg
> etc

I've thought about this more than once too, yet never raised it.

IMO this should just be factored into "pdj" which should include jsonified argument descriptions and references of different types to strings, vars, registers, etc. in the args.

UIs could than build structured viewers on top of the data to e.g. highlight the same register in all instructions when one is selected, jump to a string when double clicked, rename a function inline, context menus, etc. etc.

**Comment by radare** [comment]
You cant do that because many refs are computed by context like emulating portions of a function or construction pointers with multiple sequence of instructions. R2 does thst on the fly, while static references are just stored in the xrefs db.

We should include this asmemu info statically somehow in r2 to solve that. But thise refs are weak and may change by just passing different args to the function or following different control flows in the function emulation.

**Comment by radare** [comment]
Dont in fd.
