### ISSUE TITLE
cloud.radare.org/enyo webUI is not loading

### ISSUE THREAD

**Issue by jamesturner246** [radare/radare2#7351]
Dear all.

Apologies if this has already been reported, and that this is not strictly a problem with the core radare2 code, but the 'try' functionality of the radare.org website appears to not load for me.

I can reproduce the issue by connecting to http://cloud.radare.org/enyo/ on my browser.

My platform is Fedora 25, x64, using Firefox version 52.0.2. I am using Ad Block Plus, but the problem persists when I disable this plugin. Happy to provide further details, as required.

Is this an issue with the WebUI itself, or can I work around the problem by running a local webserver instance on my box?

Many thanks.

**Comment by radare** [comment]
yep its down, will try to push it online asap

you can just do this: r2 -c=H /bin/ls and you will have this thing running in local

**Comment by jamesturner246** [comment]
Perfect. Thanks very much.
