### ISSUE TITLE
pd $$ messing 

### ISSUE THREAD

**Issue by zonkzonk** [radare/radare2#7363]
morrn,

```
[0x00417420]> pd 10 @0x00417420
            ;-- str.hash_get_n_entries__active_dir_set_____0:
               ; DATA XREF from 0x0040402c (main)
            0x00417420     .string "hash_get_n_entries (active_dir_set) == 0" ; len=41
            0x00417449      0000           add byte [rax], al
            0x0041744b      0000           add byte [rax], al
            0x0041744d      0000           add byte [rax], al
            0x0041744f  ~   00756e         add byte [rbp + 0x6e], dh
            ;-- str.unparsable_value_for_LS_COLORS_environment_variable:
               ; DATA XREF from 0x00404470 (main)
            0x00417450     .string "unparsable value for LS_COLORS environment variable" ; len=52
       ||   0x00417484      0000           add byte [rax], al
       ||   0x00417486      0000           add byte [rax], al
       ||   ;-- str.dereference_command_line_symlink_to_dir:
       ||   0x00417488     .string "dereference-command-line-symlink-to-dir" ; len=40
       ||   ;-- str.8.23:
       ||   0x004174b0     .string "8.23" ; len=5

 pd $$ 0x00417420
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
asm.arch: Cannot setup '4289568' bits analysis engine
```

**Comment by zonkzonk** [comment]
[0x00417420]> !r2 -v
radare2 1.5.0-git 14585 @ linux-x86-64 git.1.4.0-46-g02398e1
commit: 02398e1e1782f3a19bb7f5551cf5b1c68cb2936b build: 2017-04-26__23:28:24

**Comment by zonkzonk** [comment]
(tried to get function blocks with afb)

**Comment by Maijin** [comment]
`pd $$ 0x00417420`

|Usage: p[dD][ajbrfils] [sz] [arch] [bits] # Print Disassembly

**Comment by zonkzonk** [comment]
pd 10 10:

Cannot set bits 10 to 'x86'
asm.arch: Cannot setup '10' bits analysis engine

**Comment by Maijin** [comment]
well if you are printing $$ for a binary which is located at 0x00417420, it will print 0x00417420 of disassembly which is huge... so obviously is looping

**Comment by Maijin** [comment]
^C works, I don't see bug in here.

**Comment by zonkzonk** [comment]
@pancake @Maijin why close, it has clearly an error message:

"asm.arch: Cannot setup '4289568' bits analysis engine"

**Comment by Maijin** [comment]
pd size_of_block architecture_name bits

You are setting an invalid bits. If you are doing x86 the value can only take 16, 32 or 64 bits.

**Comment by Maijin** [comment]
To be even more detailed:

`pd size_of_block architecture_name bits`

* size_of_block == $$ == value of current offset == 0x00417420 which means you want to print 0x00417420;
* architecture_name == 10 == This is not a proper architecture name, valid name are listed under e `asm.arch=?`
* bits == 10 == You are setting an invalid bits. If you are doing x86 the value can only take 16, 32 or 64 bits.

**Comment by radare** [comment]
yeah this seems wrong. pls reopen

**Comment by radare** [comment]
ah nvm
