### ISSUE TITLE
radare2 does not pass Linux debugger tests

### ISSUE THREAD

**Issue by jduck** [radare/radare2#7380]
The changes in dc5be7a broke dbg_fork at least. Changes to platform-specific debuggers should not be accepted unless existing debugger regression tests for that platform pass. Currently that test hangs where it used to exit gracefully (as expected).

**Comment by jduck** [comment]
cc @leberus

**Comment by leberus** [comment]
Can you point me to the test? I'll try to take a look

**Comment by jduck** [comment]
see: https://github.com/radare/radare2-regressions/tree/master/t.archos/Linux-x86_64

specifically the tests in dbg_fork

**Comment by leberus** [comment]
Thanks, I'll try to take a look during the day

El dia 30/04/2017 01:23, "Joshua J. Drake" <notifications@github.com> va
escriure:

**Comment by radare** [comment]
ping @leberus ,the day is over

**Comment by jduck** [comment]
I've tried with dbg.follow-child=true and it doesn't work with this setting either. My guess is that dbg.follow-child actually depends on dbg.forks=true too. As such, the code should be structured in such a way that "dpc" with dbg.forks=true should work. If follow-child is set, it needs to set dbg.forks also. follow-child should probably be equivalent to "dpc;dc" with dbg.forks enabled.

BTW, are there any tests for follow-child anywhere? I didn't see any in r2-regressions

**Comment by radare** [comment]
nice to hear from you. Release is today, so if you get this fixed at time it will be good for 1.5. Welcome back!

**Comment by osalvadorvilardaga** [comment]
I've fixed it more or less in local, just need to do some cleanup and adjust a couple of things, but the "core" problem is gone.
I think I'll be ready to make a PR tomorrow.

**Comment by leberus** [comment]
I've fixed it more or less in local, just need to do some cleanup and adjust a couple of things, but the "core" problem is gone.
I think I'll be ready to make a PR tomorrow.

**Comment by radare** [comment]
+1

**Comment by radare** [comment]
Tomorrow?

**Comment by leberus** [comment]
Sorry, I was really tight in time.

I started to fix it [here](https://github.com/leberus/radare2/commit/9121e0c97c451a7aef3897300e00356b1d057815)

I made some changes and now some of the tests from radare2-regressions that were failing they don't anymore. (I couldn't check all of them)


I plan to finish it tomorrow, since I got some free time this week.

**Comment by radare** [comment]
hey :D welcome back
