### ISSUE TITLE
arm assemble error mov.w r0

### ISSUE THREAD

**Issue by iddq** [radare/radare2#7387]
```
[root@centos1 radare2]# rasm2 -a arm -b 16 -D "4F F4 7A 70"
0x00000000   4                 4ff47a70  mov.w r0, 0x3e8
[root@centos1 radare2]# rasm2 -a arm -b 16 'mov.w r0, 0x3e8'
Cannot assemble 'mov.w r0, 0x3e8' at line 3
invalid
[root@centos1 radare2]#
```

**Comment by Maijin** [comment]
Greetings,

arm.as (*arm* handmade assembler) is one of the 2 arm assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix arm.as in https://github.com/radare/radare2-regressions/blob/master/t.asm/arm/capstone/arm_asm** You can do so with github web editor without even cloning the repo.

You can contribute to arm.as by completing the following files: 
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass.c
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass64.c

You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a arm.ks…
or in radare2 session
	e asm.assembler = arm.ks
```
