### ISSUE TITLE
Improvements in fs commands

### ISSUE THREAD

**Issue by yetmorecode** [radare/radare2#7389]
Nothing groundbreaking, couple of things I would like to work on but better discuss first:

- add `fss` and `fssj` commands to show current flagspace stack to support `fs-` and `fs+`
- add help for `fsj` and `fs*` (currently no help)
- add "selected" field to all entries in `fsj` instead of only where "selected=true" (for consistency)

Any thoughts?

**Comment by radare** [comment]
Yeah all those proposals sound good to me

**Comment by yetmorecode** [comment]
How about we output all flagspaces as selected in `fs` and `fsj` when all spaces are selected (i.e. `fs *`, `f->space_idx == -1`). From a user perspective i think it's more consistent to mark them all when the command says "select all".

**Comment by yetmorecode** [comment]
Also when printing the flagspaces stack, I tend to printing the currently selected space on top as well, despite it being technically not on the stack itself. Is this ok?

**Comment by yetmorecode** [comment]
Like that:
```
user@linuxdev radare2-dev $ ./binr/radare2/radare2 /bin/ls
 -- Polish reversers blame git
[0x0804be59]> fs
0  443 * strings
1   15 * symbols
2   74 * sections
3  119 * relocs
4  115 * imports
[0x0804be59]> fsj
[{"name":"strings","count":443,"selected":true},{"name":"symbols","count":15,"selected":true},{"name":"sections","count":74,"selected":true},{"name":"relocs","count":119,"selected":true},{"name":"imports","count":115,"selected":true}]
[0x0804be59]> fs strings
[0x0804be59]> fs
0  443 * strings
1   15 . symbols
2   74 . sections
3  119 . relocs
4  115 . imports
[0x0804be59]> fs *
[0x0804be59]> fs
0  443 * strings
1   15 * symbols
2   74 * sections
3  119 * relocs
4  115 * imports
```

**Comment by yetmorecode** [comment]
The other one would be like:
```
user@linuxdev radare2-dev $ ./binr/radare2/radare2 /bin/ls
 -- Have you seen the latest radare2 TV spot?
[0x0804be59]> fs
0  443 * strings
1   15 * symbols
2   74 * sections
3  119 * relocs
4  115 * imports
[0x0804be59]> fss
* # current
[0x0804be59]> fs+foo
[0x0804be59]> fs+bar
[0x0804be59]> fs+bar2
[0x0804be59]> fss
*
foo
bar
bar2 # current
[0x0804be59]>
```

**Comment by yetmorecode** [comment]
And let me bug you with one more question :P If `fs*` is used to store/restore the flagspaces (since it outputs r2 commands), we could also dump the fs stack there, or add `fss*` analog to `fs*`

**Comment by yetmorecode** [comment]
Ok, just waiting for some feedback, but that's what I would be ready to commit now:
```
user@linuxdev radare2-dev $ ./binr/radare2/radare2 /bin/ls
 -- Ceci n'est pas une r2pipe
[0x0804be59]> fs+foo
[0x0804be59]> fs+bar
[0x0804be59]> fss
0  *
1  foo
2  bar (selected)
[0x0804be59]> fssj
[{"ordinal":0,"name":"*","selected":false},{"ordinal":1,"name":"foo","selected":false},{"ordinal":2,"name":"bar","selected":true}]
[0x0804be59]> fss*
fs *
fs+foo
fs+bar
[0x0804be59]>
```

**Comment by radare** [comment]
looks good to me, send the pr

**Comment by yetmorecode** [comment]
:+1:
