### ISSUE TITLE
aetr command leads to segfault

### ISSUE THREAD

**Issue by Yzgast** [radare/radare2#7394]
When I'm trying to get an REIL form with `aetr`, the following ESIL line `rax,eax,^=,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=,0xffffffff,rax,&=` (`xor eax, eax` in assembly) lead radare2 to segmentation fault. It seems that the line is a correct ESIL representation so I'm not sure where the problem comes from.

```
[0x00400510]> aetr rip,8,rsp,-=,rsp,=[],4195536,rip,=
0000.00:      SUB     R_rsp:64 ,         8:64 ,      V_00:64
0000.01:      STR     R_rsp:64 ,              ,      V_01:64
0000.02:      STR      V_00:64 ,              ,     R_rsp:64
0001.00:      LDM     R_rsp:64 ,              ,      V_02:64
0001.01:      STM      jrip    ,              ,     R_rsp:64
0002.00:      STR     R_rip:64 ,              ,      V_03:64
0002.01:      JCC         1:01 ,              ,   4195536:64
[0x00400510]> aetr rax,eax,^=,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=,0xffffffff,rax,&=
Segmentation fault (core dumped)
```

**Comment by zonkzonk** [comment]
@Yzgast note, the extra comma before 0xffffffff fixes it for me

**Comment by zonkzonk** [comment]
@Yzgast, err, it is leading space:

  aetr rax,eax,^=,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=0xffffffff,rax,&=

**Comment by Yzgast** [comment]
It seems to fix it for me too

**Comment by condret** [comment]
wat

**Comment by radare** [comment]
fixed in msater
