### ISSUE TITLE
Jump Table Support?

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#7405]
This past DEFCON there was a challenge called "beatmeonthedl". In the main function it utilized a jump table that radare VV wasn't able to display. Would be nice to be able to view jump tables through radare2 VV.

Attaching the file.
[beatmeonthedl.zip](https://github.com/radare/radare2/files/972289/beatmeonthedl.zip)

**Comment by Maijin** [comment]
it's already supported but not enable by default because it's not tested enough. see `e anal.jmptbl=true`

**Comment by rlaemmert** [comment]
I tested that with the attached binary and it works quite well.
Just do:
```
e anal.jmptbl=true
s main
af
VV
```

**Comment by Segflow** [comment]
Not working with the attached binary

[little_tommy.zip](https://github.com/radare/radare2/files/1778348/little_tommy.zip)

**Comment by radare** [comment]
Did you enabled anal.jmptbl? Didnt checked yet but will be good to describe the version of r2 and show where the jmptable is, arch..
