### ISSUE TITLE
prebuilt binary for windows cannot start

### ISSUE THREAD

**Issue by fizrefl** [radare/radare2#7411]
I've downloaded windows binary 1.4.0 from radare.org
It crashes when trying to pass rabin2.exe (or any other file too)
I've checked this out on my 3 pc's with windows 10, 7 and 8.1. All of them are x64. 

Problem placement:  `/libr/util/lib.c` in `r_lib_opendir` method. 
Here we're trying to use `swprintf` func, but msvcrt.dll crashes, because of lack `count` param. 
When I injected the address of `_snwprintf` , radare2 started and works good.

Anybody to check this code ?

Upd. VS2015 Community on Win10 link up another lib for `swprintf` alias

**Comment by radare** [comment]
This was fixed right after the release. I can make 1.4.1 if you want or just take the bin from bin.rada.re or build your own

**Comment by fizrefl** [comment]
Thanx. I've already patched libr_utils.dll import table
