### ISSUE TITLE
r2pipe.cmdj.Error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by roj4s** [radare/radare2#7414]
import r2pipe as r2
>>> p = r2.open(f)
>>> p.cmdj('aaa')
r2pipe.cmdj.Error: Expecting value: line 1 column 1 (char 0)

Thanks in advance.

**Comment by radare** [comment]
What else do you expect?

**Comment by roj4s** [comment]
Usually I wouldn't expect an error lol ... Seems like aaa takes some params ?

**Comment by radare** [comment]
cmdj expects json in the output of the command. aaa doesnt shows any json, so it fails. Use cmd()

**Comment by roj4s** [comment]
My bad, sorry, lol. Thanks for your patience.

**Comment by radare** [comment]
👍

**Comment by geekscrapy** [comment]
If there a way to make this "safe"? I.e. cmdj returns None for example? Seems more intuitive than throwing an error? As it's not actually an error with the command

**Comment by radare** [comment]
If the output of cmdj is not a json then it should fail not return none. Because it would be a bug in r2
