### ISSUE TITLE
Add rasm2 -r

### ISSUE THREAD

**Issue by radare** [radare/radare2#7417]
To output r2 script like this with the results of the assembly:

```
$ rasm2 -r -a x86 -b 32 -o 0x8048000 -f hello.asm
e asm.arch=x86
e asm.bits=16
s 0x8048000
wx 55b82100000090ebf8
f label.main = $$+1
f entry = 0x8048000
``

**Comment by radare** [comment]
i have implemented the basics, missing seek and flags. and maybe something more

**Comment by radare** [comment]
flags is probably the only difficult part

**Comment by radare** [comment]
ping @Svenito

**Comment by Svenito** [comment]
Will get on this next week. Been tied up

**Comment by Svenito** [comment]
#7634 should close this
