### ISSUE TITLE
build fails on MSYS2 64 Bit

### ISSUE THREAD

**Issue by haarer** [radare/radare2#7436]
Hi ! 
I pulled  radare2 from git and build it using msys2 following the instructions at https://radare.gitbooks.io/radare2book/content/introduction/windows_compilation.html

The compilation of /shlr/wind/iob_pipe.c fails, complaining that sys/socket.h isn't found.
I believe this is caused by the usage of `MINGW32` in a macro to detect the compiler - it should be `__MINGW32_`_ . At least their wiki says so : )
https://sourceforge.net/p/mingw-w64/wiki2/Answer%20Check%20For%20Mingw-w64/

I tested it and change the `MINGW32`  to `__MINGW32__` it compiles fine and works like a charm.
There are some other places in the code using a `MINGW32` instead of the `__MINGW32__` -  i believe they should be fixed as well.

here's the diff for the file

 ```
shlr/wind/iob_pipe.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/shlr/wind/iob_pipe.c b/shlr/wind/iob_pipe.c
index 8de76f072..98dae10d9 100644
--- a/shlr/wind/iob_pipe.c
+++ b/shlr/wind/iob_pipe.c
@@ -4,7 +4,7 @@
 #include <string.h>
 #include <unistd.h>
 
-#if __WINDOWS__ || __CYGWIN__ || MINGW32
+#if __WINDOWS__ || __CYGWIN__ || __MINGW32__
 #include <windows.h>
 #include <fcntl.h>
 #include "transport.h"
```
EDIT: mark code as code, thanks EmilyBragg for pointing it out

**Comment by EmilyBragg** [comment]
Side note - I assume that double underscore bolds things? Otherwise, this issue seems somewhat confusing? You might want to insert code for `__MINGW32__` if so?

**Comment by XVilka** [comment]
Point is, that MINGW32 macro supposed to be set up by the configure script. See for example how `__WINDOWS__` and `__CYGWIN__` are set up.

**Comment by haarer** [comment]
AFAIK, __CYGWIN__ is set by the Cygwin toolchain. 

Am 8. Mai 2017 05:15:43 MESZ schrieb Anton Kochkov <notifications@github.com>:
>Point is, that MINGW32 macro supposed to be set up by the configure
>script. See for example how `__WINDOWS__` and `__CYGWIN__` are set up.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/radare/radare2/issues/7436#issuecomment-299763227

-- 
Gruß,
Alexander

**Comment by XVilka** [comment]
@xarkes FYI We need to eliminate using those because of the ambiguity. Not sure what @radare thinks, but may be providing unigque name, something like `__R_WIN__` `__R__CYG__` or `__R_MSVC__` could be helpful. And do all the magic only in one place - r_types.h

**Comment by haarer** [comment]
Do you think it is unsafe just using the defines from the cygwin/ mingw toolchains ?
It seems to be easier  just to change the MINGW32 to __MINGW32__ in the code. And remove the dupe __CYGWIN__ from the configure system.

Am 10. Mai 2017 04:25:29 MESZ schrieb Anton Kochkov <notifications@github.com>:
>@xarkes FYI We need to eliminate using those because of the ambiguity.
>Not sure what @radare thinks, but may be providing unigque name,
>something like `__R_WIN__` `__R__CYG__` or `__R_MSVC__` could be
>helpful. And do all the magic only in one place - r_types.h
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/radare/radare2/issues/7436#issuecomment-300355660

-- 
Gruß,
Alexander

**Comment by radare** [comment]
Send a pr

**Comment by XVilka** [comment]
Yes, it's unsafe, I think. And in case of `without-configure` build system - just define them before building.

**Comment by XVilka** [comment]
Closing because of https://github.com/radare/radare2/issues/9973
