### ISSUE TITLE
/R doesn't respect search.from

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#7444]
```
[0x00000780]> e search.from=0x780
[0x00000780]> e search.to=0xe44
[0x00000780]> /R
Invalid range 0x2eec - 0xe44
```
note it accepted search.from when `e seach.in=raw`

[lab6A.tar.gz](https://github.com/radare/radare2/files/981976/lab6A.tar.gz)

**Comment by radare** [comment]
thats expected behaviour
