### ISSUE TITLE
JSON encoder & parser

### ISSUE THREAD

**Issue by wargio** [radare/radare2#7462]
I would say to build a simple encoder & decoder based on jsmn (https://github.com/zserge/jsmn)
@radare @skuater

**Comment by Maijin** [comment]
maybe in sdb ?

**Comment by radare** [comment]
i dont think using just printfs to build json is that ugly or hard. but it's a tradeoff between performance and memory usage VS reuse code and avoid human mistakes

**Comment by wargio** [comment]
@radare I agree. Using simple prints are a good way but some structures like asn1 / pkcs1 / x509 are really hard to build them in such way. And the code is completely unreadable, if implemented in that way.

**Comment by XVilka** [comment]
Is this a duplicate of https://github.com/radare/radare2/issues/12870 ?

**Comment by Maijin** [comment]
yep
