### ISSUE TITLE
Move AppVeyor configs into yaml in the repo

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#7464]
Similar to Travis yaml file, for easier fixing/improving stuff
@xarkes

**Comment by XVilka** [comment]
@skuater you may want to give a look too.

**Comment by XVilka** [comment]
+ downloadable artifacts.

**Comment by xarkes** [comment]
Ok, I'm on it, you might want to check this PR for current progression

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
PING

**Comment by xarkes** [comment]
.appveyor.yml is in the repository. For now there is only mingw32 and msvc+meson in the configuration but I will add more in the future

**Comment by radare** [comment]
ping

**Comment by radare** [comment]
lets close it for now
