### ISSUE TITLE
Implement pdr without function analysis

### ISSUE THREAD

**Issue by radare** [radare/radare2#7470]
Will be good to be able to use pdr without having to analyze the function before.

This can be implemented in pdR, and pdr will use it when no function is found, so there will be always output for this command.

**Comment by radare** [comment]
Done in master, but needs colors, tests and such

**Comment by SajjadPourali** [comment]
Radare is not responsible when i do run pdR command.
<img width="572" alt="screen shot 2017-05-17 at 4 39 09 pm" src="https://cloud.githubusercontent.com/assets/20374762/26153170/78d1741c-3b1f-11e7-9a72-2d81b0cef194.png">
