### ISSUE TITLE
"pdf" truncates the printout of disassembly if function has unreachable instructions

### ISSUE THREAD

**Issue by FrankLorenz** [radare/radare2#7473]
I analyzed and patched the IOLI crackme's with radare2. When I patched an executable so it jumps over several lines of assembly, making it "unreachable" (dead code), I observed that r2 will no longer print out the whole disassembly of the function with `pdf @ sym.function` but omit the printout of the lower part.

Because the number of printed lines corresponds to the "realsz" value on `afi` command, I assume the bug is to use the "realsz" value instead of the "size" value when calculating the range to print out.

**Comment by FrankLorenz** [comment]
[crackme_sample.zip](https://github.com/radare/radare2/files/993077/crackme_sample.zip)

Added binary -- ZIP password is "crackme"

To reproduce, just do:
> aa
> pdf @ sym.check

**Comment by chairkov** [comment]
@radareorg @FrankLorenz  just a regression test for different size, Thanks for the hint.

```
#!/bin/sh
for a in . .. ../.. ../../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: IOLI - crackme0x05'
FILE=../../../bins/elf/ioli/crackme0x05
ARGS=
CMDS="aa ;afi @sym.check|head -5|tail -2| awk '{print $2}'| sort -u| wc -l"
EXPECT='1
'
run_test

```

**Comment by radare** [comment]
Wc is not portable use ~?

**Comment by radare** [comment]
Use pdr if you want to really print fuctions. Pdf is conceptually wrong for non linear functions
