### ISSUE TITLE
Maybe should support enter web ui from the internet 

### ISSUE THREAD

**Issue by Yousayiloveu** [radare/radare2#7484]
I just wanna share this software like a team platform, all members could easily use it , and radare2 will be running on a cloud server. I think the web ui maybe should allow the connection by supporting a 401 authorization or others.

**Comment by radare** [comment]
You can implement this in 10 lines of nodejs. Take the code from the cloud and add auth yo the express server. Its like 10 times faster than the internal r2 webserver. If u plan to expose it on the internet or use it from many authorized ppl you should probably setup it that way instead of directly exposing r2

**Comment by Yousayiloveu** [comment]
I tried to execute the command as you say, but there's a problem,  I have installed r2pipe and express though npm. 
root@localhost:~/radare2/doc/node.js# r2 -c '#!pipe node index.js' /bin/ls
/root/radare2/doc/node.js/index.js:48
        var r = r2p.rlangpipe(runWebServer);
                    ^

TypeError: r2p.rlangpipe is not a function
    at Object.<anonymous> (/root/radare2/doc/node.js/index.js:48:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
 -- Warning, your trial license is about to expire.

**Comment by Yousayiloveu** [comment]
By the way, I executed this:
> e http.root=/
> e http.bind=0.0.0.0
> e http.port=9999
> =h

When I visit the port 9999, it says "File not found"

**Comment by Yousayiloveu** [comment]
Oooops! My fault! I don't need set the http.root!

**Comment by radare** [comment]
And u misshttp.sandbox=false
