### ISSUE TITLE
gdb bitching

### ISSUE THREAD

**Issue by chairkov** [radare/radare2#7492]
so, px/ works like gdb x/. comparing x/s and x/i, then we can see:

gdb:

```
(gdb) b main
Breakpoint 1 at 0x400a02
(gdb) r
Starting program: /bin/core-grep 

Breakpoint 1, 0x0000000000400a02 in main ()
(gdb) x/40s 0x400a02
0x400a02 <main+4>:      "H\201\354", <incomplete sequence \340>
0x400a07 <main+9>:      ""
0x400a08 <main+10>:     ""
```
vs r2:

```
 -- nothing personal, just bitness
[0x7f77afa5ccd0]> db main
[0x7f77afa5ccd0]> dc
Selecting and continuing: 14214
hit breakpoint at: 4009fe
[0x004009fe]> x/40s 0x400a02
H
,H dH%(
HE1HH
D
<
```

so address prefix is missing

**Comment by chairkov** [comment]
@radare also, somwat odd: (I know it's not regs)

[0x004009fe]> x/40s rsp
Block size 483978792 is too big
This block size is too big. Did you mean 'px @ 40s rsp' instead?

**Comment by chairkov** [comment]
@pancake @radare doesn't work, no prefix shown

**Comment by radare** [comment]
it works now. , fuckoff wat? @pancake is nobody from r2land. can

**Comment by radare** [comment]
can u please add tests at least?

**Comment by chairkov** [comment]
@radare I know, great p was not from me, so ff....

**Comment by chairkov** [comment]
@radare @XVilka  is px/ now equal to gdb x/ ?

**Comment by radare** [comment]
Yes . x is the short for px
