### ISSUE TITLE
r2pm and Windows

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#7493]
Currently r2pm implemented as a shell script. Which is not an option for example for "pure Windows" msvc-compiled builds. Your ideas?

**Comment by radare** [comment]
Powershell or C

**Comment by XVilka** [comment]
PowerShell will require rewriting everything each time. C, yes, is a saviour.

**Comment by radare** [comment]
there’s not much to rewrite, r2pm is stable and complete right now and its only 500 lines of posix shellscript

**Comment by xarkes** [comment]
ping

**Comment by XVilka** [comment]
I don't think it's a good idea to make a separate scripts for r2pm. They'll diverge pretty soon. so I think implementing r2pm in C is a best choice, and the most portable one.

**Comment by radare** [comment]
Isnt working with bash on windows? I think the pkgsystem is simple enough to make a simple shell-like parser in C to do all the stuff we do in our packages.

If not, we may want to provide keywords that can be reimplemented in shellscript and ensure that all packages keep that syntax.

I would go by starting a separate r2pm-c directory in binr/ and add support for the simplest packages

**Comment by XVilka** [comment]
My thoughts on that - we do not need a binary that do not relay on the external libraries, we just need static compilation of the resulting binary, that's it. We can also check https://github.com/clibs/clib for the inspiration.

**Comment by XVilka** [comment]
Moreover, instead of using "git.exe" we can just link to the [libgit2](https://libgit2.github.com/) for a completely portable solution.

**Comment by xarkes** [comment]
In this case, we could use this as well: https://github.com/yaml/libyaml

**Comment by radare** [comment]
Omg dependencies. R2pm works with no dependencies, everything is expected to be installed. So i wont add any library as dependency

**Comment by radare** [comment]
We shuold provide binary packages for windows and thats it, i dont plan to make everything compilable because thats a real problem for windows users, and we wont include a toolchain with it

**Comment by xarkes** [comment]
Who cares if it's linked statically?

**Comment by xarkes** [comment]
If you disagree to use any lib (even with static linking) for r2pm only, then what are our options?

**Comment by radare** [comment]
I do

**Comment by radare** [comment]
Binary packages and rewrite in C to skip the bash dependency

**Comment by XVilka** [comment]
Implemented already: https://github.com/radareorg/r2pm
