### ISSUE TITLE
Expression is always false

### ISSUE THREAD

**Issue by AppChecker** [radare/radare2#7495]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bugs:

1) https://github.com/radare/radare2/blob/ad54e9ddf18dd88570fec2593920f8f0223d4e8f/libr/anal/p/anal_mips_gnu.c#L194

```cpp
   else if ((optype & 0x10) == 0x1c) {

```
0x10 can be represented as 0000 0000 0001 0000
0x1c can be represented as 0000 0000 0001 1100

There is no such value optype, that using operator '&' with 0x10 will rasult 0x1c, as  bits number 3 and 4 will be equal to 0 anyway.

2) https://github.com/radare/radare2/blob/ad54e9ddf18dd88570fec2593920f8f0223d4e8f/libr/anal/p/anal_h8300.c#L222
https://github.com/radare/radare2/blob/ad54e9ddf18dd88570fec2593920f8f0223d4e8f/libr/anal/p/anal_h8300.c#L333

```cpp
    ((buf[1] & 0xf0) == 0x08) ? 2 : 1, rd());
```
0xf0 - 0000 0000 1111 0000
0x08 - 0000 0000 0000 1000
The same as above, the fourth bit as a result of "and" operation will be 0.

Possible defects were found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by radare** [comment]
1.3.0 is too old. Please run this on git, we dont fix bugs if they are not in git

**Comment by AppChecker** [comment]
There is this code in version 1.4.0 also.
