### ISSUE TITLE
lea instruction is not displayed right

### ISSUE THREAD

**Issue by Sp4ssT63r** [radare/radare2#7500]
Hi,
while processing a crackme, i stumbled on a lea instruction that is not displayed proper.
This lea instruction takes a absolute address and a offset in a register.
I attached two screenshots one viewing radare and one of objdump.
The concerning instruction is at 0x00402c97.

![screenshot from 2017-05-16 09-07-15](https://cloud.githubusercontent.com/assets/28724730/26093676/279767f4-3a17-11e7-9e0a-845eaaaa7a5c.png)

**Comment by radare** [comment]
This is a simplificarion of the instruction for readibility, if you want to disable this filter you can disable it in asm.filter, asm.relsub, asm.varsub...

Lea instructions can only take the address of the argument. So both syntaxes look right to me.

**Comment by Sp4ssT63r** [comment]
> Lea instructions can only take the address of the argument. So both syntaxes look right to me.

I agree to you in the cases where the rbp register is not displayed when operating on local variables residing on the stack. But in that case i mentioned, some of the semantic is omitted by this simplification.

Setting asm.filter to false produces output which i would prefer, but is there a way to combine both  notations. Now i have something like lea rcx, [rax + 0x4030e0]. Can radare display something like lea rcx, [rax + obj.GoodHashes] or lea rcx, [obj.GoodHashes + rax]?

Thanks for your fast reply :)

**Comment by radare** [comment]
Oh you are right, the reg reference has been filtered out. A similar bug was fixed last week. Probably related. Can u add a test for this? If you wanna try to fix it check the git log and see the changes i did for the other case
