### ISSUE TITLE
irszM not working as expected

### ISSUE THREAD

**Issue by Frefreak** [radare/radare2#7503]
`cmd_info` doesn't set output mode correctly when number of query types is more than one.

**Comment by radare** [comment]
can you provide a testcase?

**Comment by Frefreak** [comment]
The boring binary `a.out` has only one string to make the output easier to read.
```
$ r2 a.out
 -- taking the file and moving it
[0x004003b0]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x004003b0]> iz*
fs stringsf str.test_string 12 @ 0x00400544
Cs 12 @ 0x00400544

[0x004003b0]> iM*
fs symbols
f main @ 0x004004a6

[0x004003b0]> izM*
vaddr=0x00400544 paddr=0x00000544 ordinal=000 sz=12 len=11 section=.rodata type=ascii string=test string
[Main]
vaddr=0x004004a6 paddr=0x000004a6

[0x004003b0]> 

```
The expect result for the last command (`izM*`) should output the concatenation of the previous two commands(`iz*` and `iM*`), but here is actually the same output as just `izM`.
