### ISSUE TITLE
broken r_core_print_disasm_instructions when using nb_bytes parameter

### ISSUE THREAD

**Issue by kamou** [radare/radare2#7509]
there seem to be a problem in some cases with r_core_print_disasm_instructions when using the nb_bytes parameter.

this can be easily reproduced with the following binary: https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/baby-re

just do (with PR #7508 ):
```
dcu main
af
pib
```
or even just:
```
dcu main
pI 300
```

**Comment by radare** [comment]
this is because the blocksize is not resized and prints trash. no need to use the debugger to reproduce this issue.

**Comment by kamou** [comment]
thanks for the hint, will provide a PR

**Comment by radare** [comment]
it if fixed now
