### ISSUE TITLE
Radare is unable to print output of binary in debug mode (macOS 10.12.5)

### ISSUE THREAD

**Issue by SajjadPourali** [radare/radare2#7510]
Hello,
I have a problem to executing binary when I want to do debug, radare prints `==> Process finished` but there is not available any outputs.
I have also attached the screenshot of this problem.
<img width="416" alt="screen shot 2017-05-17 at 1 11 51 am" src="https://cloud.githubusercontent.com/assets/20374762/26127465/b1eac18a-3a9e-11e7-9780-91f218091707.png">

```
sajjad@MacBook-Pro:~$/opt/radare2/bin/radare2 -v
radare2 1.5.0-git 14772 @ darwin-x86-64 git.1.4.0-228-g7d7c9cb5a
commit: 7d7c9cb5a741a2556a9daa7cbe0e86570f800a8c build: 2017-05-17__01:00:10
```

**Comment by XVilka** [comment]
You didn't set any breakpoint and run 'continue' - so the process successfully run to its end.

**Comment by SajjadPourali** [comment]
Process is successfully run but radare can not print any output.
for example in this screen shot output is "aaa",and set breakpoints.
<img width="1085" alt="screen shot 2017-05-17 at 10 23 05 am" src="https://cloud.githubusercontent.com/assets/20374762/26140416/e892cbcc-3aeb-11e7-875a-ee9dea640b42.png">

**Comment by SajjadPourali** [comment]
I think it occurred after upgrading macOS to 10.12.5.
did anyone check it on macOS 10.12.5 ?

**Comment by SajjadPourali** [comment]
I could print the output by forwarding stdio with rarun2 script. But directly stdin is not possible, and by default (without using rarun2) stdin and stdout will not be shown in terminal.
<img width="651" alt="screen shot 2017-05-19 at 12 13 49 am" src="https://cloud.githubusercontent.com/assets/20374762/26220609/8891aa02-3c28-11e7-90b3-0af886963a9f.png">

**Comment by SajjadPourali** [comment]
thanks @radare , stdout is fixed, but stdin still have problem.

1. can not get any data from input (stdin is not work)
2. when a process calling a stdin func, radare will be so slow!
this is my source and binary : 
https://0x00.ir/files.7z

**Comment by radare** [comment]
Try with -X /dev/stdin

**Comment by SajjadPourali** [comment]
I tried it but problem is persistent.
I did upload a temporary video of this problem.
https://www.youtube.com/watch?v=tOu05JDKU-s

**Comment by Maijin** [comment]
use https://asciinema.org/

**Comment by SajjadPourali** [comment]
@Maijin : in this video i shows my physical keyboard too, because i wanted to show, keys must pressed twice.

**Comment by Maijin** [comment]
ok fair enough

**Comment by SajjadPourali** [comment]
https://asciinema.org/a/0kegkfwsipq81bknwk965u2ug

**Comment by radare** [comment]
yeah even if you do r2 -X stdout=/dev/stdout  -d ./a 

the problem was that for some reason mach is ignoring our request to keep the 0,1,2 fds open and close the rest and its closing them all. you can verify this with the `dd` command. 

i fixied this. but seems like there’s still another regression to fix. ill try to have a look at this but it was introduced by @alvaro_fe

**Comment by SajjadPourali** [comment]
@radare : What do you think about reopening this issue ?

**Comment by radare** [comment]
Open another one. The output is printed already, so the issue is different
