### ISSUE TITLE
Wrong opcodes of pdf command, pdf can not detect declares in code segment.

### ISSUE THREAD

**Issue by SajjadPourali** [radare/radare2#7511]
Hello,
When i uses pdf command for dissembling part of code segment if there was available a declare (for example db,dw ...) pdf can not detect that and thus shows wrong opcodes, how can i fix this ?
I have also attached the screenshot of this problem.
<img width="1280" alt="screen shot 2017-05-17 at 1 35 31 am" src="https://cloud.githubusercontent.com/assets/20374762/26128661/704c1bd0-3aa2-11e7-9532-34f7533a09fa.png">
hopper :
<img width="1022" alt="screen shot 2017-05-17 at 1 36 45 am" src="https://cloud.githubusercontent.com/assets/20374762/26128677/804efeb2-3aa2-11e7-8423-5f9743e206f5.png">

**Comment by XVilka** [comment]
You can see the hopper doing exactly the same - it just shows data instead of 'invalid' when it can't decode an instruction. In both cases you have to mark it as data using 'Cd' commands. And the 'pdf' is not recursive, it's linear, for the recursive you have to use 'pdr'.
