### ISSUE TITLE
AT&T syntax doesn't show locals when indexing

### ISSUE THREAD

**Issue by jeaye** [radare/radare2#7516]
## Observed
For example, with Intel, I may see this:

```asm
mov dword [local_4h], 5
```

With AT&T enabled, however, the same instruction would show up as:

```asm
movl $5, 4(%esp)
```

## Expected
With `asm.varsub_only` set, I'd ideally see:

```asm
movl $5, local_4h
```

Without it set, this would make sense:

```asm
movl $5, local_4h(%esp)
```

## Version info (Arch Linux)
```text
radare2 1.4.0 0 @ linux-x86-64 git.1.4.0
commit: HEAD build: 2017-05-02__20:39:14
```

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
there is radare2-git in AUR this version you show is too old.

**Comment by jeaye** [comment]
That only helps if the change has been made in master, which it has not. :) My version is two weeks old, you're right, but running from git has the same issue.

Ther have been no previous Github issues or PRs for this problem.

**Comment by Maijin** [comment]
`2017-05-02__20:39:14`
That's not 2 weeks old

**Comment by radare** [comment]
can you please add tests for this?

**Comment by jeaye** [comment]
```text
radare2 1.5.0-git 14781 @ linux-x86-64 git.1.4.0-237-g98f03c1ff
commit: 98f03c1ff05c87ce8801076bfe667751ef83a2cc build: 2017-05-17__17:57:37
```

This is not working for me; I see the same exact AT&T disassembly as before. Will you verify with me that this is working for you?

I would be willing to add some tests, but I don't see any tests for the output of disassembly of various flavors when I look here: https://github.com/radare/radare2-regressions -- guidance would be appreciated.

**Comment by radare** [comment]
i did the tests it was easier to do them than explaining how to do them :P feel free to check the commit and add more tests if you need

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/e68401a8688b7a7a38497d4e1b668150341ae2f3
