### ISSUE TITLE
same address, different bytes

### ISSUE THREAD

**Issue by dmwit** [radare/radare2#7517]
I find the following interaction very puzzling:

    [0x00008000]> pd 2 @0xffff
                0x0000ffff      00             brk
                0x00010000      0300           slo (0x00,x)
    [0x00008000]> pd 1 @0x10000
                0x00010000      ffffff         isb 0xffff,x

So which is it? Does 0x10000 have 0x03 in it, or 0xff?

I've attached a file that can be used to reproduce this; unzip it and run `r2 test.nes` to give it a go. The test file is all zeros, except for the NES header in the first 16 bytes and a `1`, `2`, and `3` byte at the beginning of each of the three declared PRG ROMs (at file offsets 0x10, 0x4010, and 0x8010, respectively). You can see the `1` and `2` bytes at 0x8000 and 0xc000, respectively, in r2.

[test.nes.gz](https://github.com/radare/radare2/files/1009093/test.nes.gz)

**Comment by radare** [comment]
Run it with valgrind and check if it complains.

Thanks for reporting

**Comment by dmwit** [comment]
I am not too familiar with valgrind, so let me describe what I did and what I saw and hope you can interpret it better than I can. I ran `valgrind -v r2 test.nes`. It printed loads of stuff during startup about loading symbols; then nothing special while running the above two commands. On exit, it printed this summary:

    ==29180== LEAK SUMMARY:
    ==29180==    definitely lost: 24,436 bytes in 1,236 blocks
    ==29180==    indirectly lost: 0 bytes in 0 blocks
    ==29180==      possibly lost: 0 bytes in 0 blocks
    ==29180==    still reachable: 2,288 bytes in 11 blocks
    ==29180==         suppressed: 0 bytes in 0 blocks
    ==29180== Rerun with --leak-check=full to see details of leaked memory
    ==29180== 
    ==29180== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
    ==29180== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by radare** [comment]
can you try the siol branch? this is a bug related overlapping va and pa. You can use r2 -B to specify a different base address to avoid that overlap and seek to baddr+x

**Comment by dmwit** [comment]
I can confirm that the siol branch does not display this bug, with or without -B. It is unclear to me what -B is supposed to do; I sort of expected it would put PRG ROMs at the given offset, but PRG ROMs appear to be loaded at 0x8000 no matter what I specify for -B.

**Comment by radare** [comment]
If -B doesnt works for nes is because you are not using r2 from git

**Comment by dmwit** [comment]
Um. How exactly are you imagining that I tested the siol branch without using git? Try it on the siol branch yourself and see: -B does nothing.

**Comment by radare** [comment]
The siol branch is not rebased so the -B on nes would not work. Just plain git to test this

**Comment by MaskRay** [comment]
Seems to be fixed.

@dmwit I am  a haskell user that do not understand generalizing lenses :(
