### ISSUE TITLE
seek undo/redo doesn't work correctly

### ISSUE THREAD

**Issue by dmwit** [radare/radare2#7527]
Here's a short demonstration:

    [0x00008000]> s 0x8010
    [0x00008010]> pd 1
                0x00008010      00             brk
    [0x00008010]> s-
    [0x00008000]> s+
    [0x00008010]> pd 1
                0x00008010      0100           ora (0x00,x)

I've attached a file that can be used to reproduce this. It is the same file as in #7517; copying my description of the file from there:

> Unzip it and run `r2 test.nes` to give it a go. The test file is all zeros, except for the NES header in the first 16 bytes and a `1`, `2`, and `3` byte at the beginning of each of the three declared PRG ROMs (at file offsets 0x10, 0x4010, and 0x8010, respectively). You can see the `1` and `2` bytes at 0x8000 and 0xc000, respectively, in r2.

I've confirmed that this bug exists in the master and siol branches. In both cases, it seems to be showing some (but not all) of the bytes from the "undone" address at the "redone" address -- but the number of bytes affected differs in the two branches.

**Comment by dmwit** [comment]
(Really attaching the file this time.)

[test.nes.gz](https://github.com/radare/radare2/files/1012668/test.nes.gz)

**Comment by radare** [comment]
Please send a test to r2r

**Comment by radare** [comment]
Is this happening with siol?

**Comment by dmwit** [comment]
As mentioned in the original report, it happens in both master and siol. I will put together a test script a bit later today.

**Comment by dmwit** [comment]
[I've created a test script.](https://github.com/radare/radare2-regressions/pull/851)
