### ISSUE TITLE
oc without arguments shoudlnt create a new core

### ISSUE THREAD

**Issue by radare** [radare/radare2#7539]
current behaviour can be confusing to users. because an error is printed but the core is exchanged

```
[0x00000000]> oc
Missing argument
[0x00000000]> oc?
```

**Comment by kamou** [comment]
I've also removed the handling of "oc?" as the command has no sub commands. "o?" should be enough.

**Comment by kamou** [comment]
oops, fixed some indentation issue (introduced by myself) as well
