### ISSUE TITLE
libr/core/cconfig.c: access to field 'plugins' results in a dereference of a null pointer (loaded from variable 'a')

### ISSUE THREAD

**Issue by mikaoP** [radare/radare2#7543]
Here follows the path:
https://github.com/radare/radare2/blob/master/libr/core/cconfig.c#L340 with user->anal NULL
https://github.com/radare/radare2/blob/master/libr/core/cconfig.c#L356
https://github.com/radare/radare2/blob/master/libr/core/cconfig.c#L136
https://github.com/radare/radare2/blob/master/libr/core/cconfig.c#L93

**Comment by radare** [comment]
Can u send a pr fixing those issues?

**Comment by radare** [comment]
none of those lines reference plugins or is susceptible to null deref at all

**Comment by mikaoP** [comment]
well, i am just doing some static analysis

**Comment by radare** [comment]
thanks for reporting!
