### ISSUE TITLE
stdin is not working in debug mode (macOS)

### ISSUE THREAD

**Issue by SajjadPourali** [radare/radare2#7546]
Hello,
radare2 can not receive any data from stdin in debugging mode.
also when a process calling a stdin func, characters must type twice (!like when someone wants to sniff the terminal input with reading current terminal tty (cat /dev/ttys000))!

this is my source and binary : https://0x00.ir/files.7z and i did upload a temporary video of this problem : https://www.youtube.com/watch?v=tOu05JDKU-s
```
./radare2 -v
radare2 1.5.0-git 0 @ darwin-x86-64 git.1.5.0-git
commit: HEAD build: 2017-05-20__20:33:48
```
i did checked it on macOS 10.12.5

**Comment by SajjadPourali** [comment]
@radare : i can get you access from mac machine for checking directly.

**Comment by SajjadPourali** [comment]
@radare : I can get you access from mac machine for checking this issue directly.
@alvarofe : could you please verify this issue ?

**Comment by radare** [comment]
> On 28 May 2017, at 23:06, Sajjad Pourali <notifications@github.com> wrote:
> 
> @radare : I can get you access from mac machine for checking this issue directly.
> 

I have a mac and i can reproduce it. But enotime to fix all the stuff for today release. Wanna help?
> @alvarofe : could you please verify this issue ?
> 
He is very busy at work, so i dont expect him to have time for this anytime soon

**Comment by lowlyw** [comment]
@SajjadPourali MEGA PING, the download  (7z) appears to be down, can you reupload to github?

**Comment by Maijin** [comment]
Use github upload please

**Comment by alvarofe** [comment]
Was not this fixed already? there were some changes, although with SIOL on the horizon might be lost due to careless rebasing

**Comment by Maijin** [comment]
Let's close until getting the file back and if reproducible
