### ISSUE TITLE
libr/bin/p/bin_sfc.c: access to field 'mirrors' results in a dereference of a null pointer (loaded from variable 'm')

### ISSUE THREAD

**Issue by mikaoP** [radare/radare2#7547]
https://github.com/radare/radare2/blob/master/libr/bin/p/bin_sfc.c#L202
if calloc fails m is set to NULL

**Comment by radare** [comment]
send a pr fixing this it takes less time to click in the pencil button than opening an issue

**Comment by mikaoP** [comment]
done #7548
