### ISSUE TITLE
pdc produces Segmentation Fault

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#7558]
Example binary: [test.tar.gz](https://github.com/radare/radare2/files/1017125/test.tar.gz)
Run r2 like this: `r2 -A test -c "pdc @ sym.storm"`

The crash happens in core at pseudo.c:127 in the function `find_and_change()`:
```
...
} else if (ctx.comment && *in == '(' && (IS_ALPHA (in[-1]) || *ctx.right == '*') && !ctx.right) {
...
```
It's obvious that this whole condition cannot be correct, because of `!ctx.right` and `*ctx.right == '*'`, which is the cause of the segfault here. `IS_ALPHA (in[-1])` is false, but `ctx.right` is null.

I'm having some trouble understanding the whole function's code myself to fix it correctly. Here's what I found out:
For each block, `r_core_pseudo_code()` calls `pD` with some specific options and gives the output to `find_and_change()` which parses it and makes it more readable.
This is the problematic part of the `pD` output in this case:
```
     sym.corrosion ()         ; sym.corrosion
     if (dword [local_4h] == 0 
```
`find_and_change()` parses the first line here, including parsing the content of the comment for the function call. After reading the `sym.corrosion` in the comment, it will look for an opening brace, which does not exist here. However it does not stop at the end of the line, because of this code at line 36, which I have no idea what purpuse it has:
```
if (*in == '\n' || !*in) {
	if (ctx.type == TYPE_SYM && ctx.linecount < 1) {
		ctx.linecount++;
		ctx.linebegin = in + 1;
		continue;
	}
...
```
This makes it continue reading into the next line, eventually finding the `(` of the if. At this point ctx.right is null, but `IS_ALPHA (in[-1])` is false, because of the space after the if, which leads to the segfault.

**Comment by wargio** [comment]
fuck. change line `ctx.comment && *in == '(' && (IS_ALPHA (in[-1]) || *ctx.right == '*') && !ctx.right` to 

fuck. change line `ctx.comment && !ctx.right && *in == '(' && (IS_ALPHA (in[-1]) || *ctx.right == '*')`

**Comment by wargio** [comment]
i'll fix it when i'll be at home.

**Comment by wargio** [comment]
The code works in this way:

`find_and_change()` will replace symbols with the comments (see examples at https://github.com/radare/radare2/pull/7482).
anyway, `find_and_change()` will search for the following types of strings: 
```
word [esp] = str.Password: ; [0x8048581:4]=0x73736150 ; "Password: " 
```
and
```
       sym.imp.strcmp ()        ; sym.imp.strcmp
                                ; int strcmp(const char * s1 : (*0x177fe4)0x00177fb4 =, const char * s2 : (*0x804858f)0x00177fb8 = 250382)
```
So, when a `sym.` or `str.` it will search for  `"` or a `(` (functions needs to go back to find the name and the return value from the current position).

**Comment by thestr4ng3r** [comment]
I see, thanks for the info!

However this would still be broken:
```
ctx.comment && !ctx.right && *in == '(' && (IS_ALPHA (in[-1]) || *ctx.right == '*')
```
In the above case, it would be `ctx.comment` == true, `!ctx.right` == true, `*in == '('` == true, `IS_ALPHA (in[-1])` == false and `*ctx.right == '*'` segfaults.

**Comment by radare** [comment]
this

**Comment by wargio** [comment]
what ?

**Comment by radare** [comment]
not fixed?

**Comment by wargio** [comment]
yes, but you haven't merged the PR.

**Comment by wargio** [comment]
@Maijin close it
