### ISSUE TITLE
Stepping failed after ds (openbsd-i386 6.1)

### ISSUE THREAD

**Issue by Elecon-rou** [radare/radare2#7560]
Stepping failed after 'ds' command on OpenBSD
```
# radare2 -d /bin/ls
Process with PID 67032 started...
= attach 67032 67032
bin.baddr 0x0de4e000
Using 0xde4e000
Assuming filepath /bin/ls
asm.bits 32
 -- I love the smell of bugs in the morning.
[0x180c91f0]> ds
r_debug_native_wait: no idea what happened... wtf?!?!
Stepping failed!
Step failed
[0x180c91f0]> q
Do you want to quit? (Y/n)
Do you want to kill process? (Y/n)
# r2 -v
radare2 1.5.0-git 0 @ openbsd-x86-32 git.1.5.0-git
commit: HEAD build: 2017-05-21__22:22:16
```
By the way, what kind of useful info can I gather, may be results of regressions test ?

**Comment by crvintel** [comment]
Hit exactly the same problem on FreeBSD 11.0.

**Comment by radare** [comment]
this is probably a 1 line fix, because it was working before, anybody with time and bsd wanna try to fix it?

**Comment by MarceColl** [comment]
Hit the same problem on FreeBSD 11.0.

I may have some time to dedicate to this. Will start looking into it although it will be the first time I look at radare's internals so it may take some time.

**Comment by radare** [comment]
shouldnt take more than few minutes to fix, its a silly regression that its probably 99% related to just the ptrace step line…

just read libr/debug/p/debug_native.c line 146

**Comment by XVilka** [comment]
Is this still reproducible?

**Comment by semarie** [comment]
@XVilka just tested with:

```
$ r2 -v
radare2 2.7.0-git 18278 @ openbsd-x86-64 git.2.6.0-122-gbc5627239
commit: bc5627239ceffeec970cfe6854b8077b34838540 build: 2018-06-04__08:12:23
```

the error is still here (with some new others warnings).

```
$ r2 -d /usr/bin/id
Process with PID 84178 started...
= attach 84178 84178
Could not get memory map: Operation not permitted
Could not get memory map: Operation not permitted
Process with PID 93131 started...
asm.bits 64
Could not get memory map: Operation not permitted
 -- Press 'c' in visual mode to toggle the cursor mode
[0x1cf0a6c02a50]> ds
r_debug_native_wait: no idea what happened... wtf?!?!
Stepping failed!
Step failed
[0x1cf0a6c02a50]> q
Do you want to quit? (Y/n) Y
Do you want to kill the process? (Y/n) Y
uid=1000(semarie) gid=1000(semarie) groups=1000(semarie)
```

Please note that the program has been executed even if kill has been requested.

Regarding the error, I think the problem is in `r_debug_native_wait()` function. In BSD context, there is no code that change `reason` variable before checking its value (`wtf` printf). As the value is initialized with `R_DEBUG_REASON_UNKNOWN`, it is also the returned value of the function.
