### ISSUE TITLE
rabin2: C++ names not fully demangled

### ISSUE THREAD

**Issue by armijnhemel** [radare/radare2#7572]
As evident in #7571 : some of the names are not fully demangled in rabin2, when the output is compared with what c++filt would do:

```
vaddr=0x00007298 paddr=0x00007298 ord=092 fwd=NONE sz=12 bind=WEAK type=FUNC name=std::__1::basic_streambuf<char,std::__1::char_traits<char>>::seekpos
```

whereas c++filt says:

```
$ c++filt _ZNSt3__115basic_streambufIcNS_11char_traitsIcEEE7seekposENS_4fposI9mbstate_tEEj
std::__1::basic_streambuf<char, std::__1::char_traits<char> >::seekpos(std::__1::fpos<mbstate_t>, unsigned int)
```

**Comment by armijnhemel** [comment]
Notice that the demangling in rabin2 stops after 'seekpos'

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by XVilka** [comment]
Can you please send PR to radare2-regressions with "BROKEN=1" one?

**Comment by Maijin** [comment]
See https://github.com/radare/radare2-regressions/tree/master/t.formats/mangling

**Comment by armijnhemel** [comment]
Ah. I get it now. It seems that the demangling in rabin2 is the same as "c++filt -p". This is then not a bug, so closing (although being able to also demangle the parameters would be nice).

**Comment by armijnhemel** [comment]
alrighty then. #7577 it is. I will work on tests later today (paid work is interfering).
