### ISSUE TITLE
Unify Disassembly Routines(to the same location) for Future Maintenance

### ISSUE THREAD

**Issue by deeso** [radare/radare2#758]
The web interface is having trouble disassembling Java class files that are using switches (expected, kinda since it is a special case).  We need to unify the source for disassembly information and consumption of its results.  For example, in Java there are native switching instructions, so whenever a "new method" is analysed, it is essential to reset the assembler/architecture PC so that the code can be properly processed.  If the disassembly happens in too many places, then it becomes difficult to track where the bug might actually be.

**Comment by radare** [comment]
The disasm.c has been refactred a lot and now is way better to work with.
