### ISSUE TITLE
x86 pseudo proposal for cmp & test and conditional jumps

### ISSUE THREAD

**Issue by wargio** [radare/radare2#7581]
i want to propose to change the pseudo of test, cmp and conditional jumps to something better.

since seeing on pseudo (and pdc) those strange if like
```c
       if (eax == eax                 ; test
       notZero 0x400004)              ; jne

       if (dword [local_4h] == 0      ; test
       notZero 0x400503)              ; jne

       if (eax == 0x19                ; cmp
       isAbove 0x103)                 ; ja
```

is, from my point of view, wrong and misleaing, i want to propose a new nomenclature like the one i've used on PPC.

So it would look like

```c
       var = eax & eax                    ; test
       if (var != 0) goto 0x400503        ; jne

       var = dword [local_4h] & 0         ; test
       if (var != 0) goto 0x400503        ; jne

       var = eax - 0x19                      ; cmp
       if (((unsigned) var) > 0) goto 0x103  ; ja
```

**Comment by radare** [comment]
Propose changes in C, not english

**Comment by wargio** [comment]
:(
Ok... I wanted to write it before committing anything

**Comment by Maijin** [comment]
Probably would be better one-liner:

```
       if (eax & eax != 0) goto 0x400503 
       if (dword [local_4h] & 0 != 0) goto 0x400503
       if (((unsigned) eax - 0x19) > 0) goto 0x103
```

And make sure the goto are resolved :)

**Comment by radare** [comment]
Ah so you editted the issue again imand i was just seeijg "i have a proposal" without anything else.

**Comment by radare** [comment]
Any change on this will make it better than what it is now. So ok for me

**Comment by kazarmy** [comment]
`dword [local_4h] & 0 != 0`?

**Comment by Maijin** [comment]
?

**Comment by kazarmy** [comment]
Well if you AND something with 0, the result is always 0.

**Comment by wargio** [comment]
that's what `test` does.

```
Temporary = Source1 & Source2;
SF = MSB(Temporary);
if(Temporary = 0) ZF = 1;
else ZF = 0;
PF = BitwiseXNOR(Temporary[0:7]);
for(PF = 1, i = 0; i < 8; ++i) PF ^= Temporary[i];
CF = 0;
OF = 0;
AF = Undefined;
```

**Comment by kazarmy** [comment]
Oh it should be `dword [local_4h] & dword [local_4h] != 0`

**Comment by wargio** [comment]
No. it's correct what was written by Maijin
```
if ((dword [local_4h] & 0) != 0)
    goto 0x400503
```

**Comment by kazarmy** [comment]
Can't do a `test <mem>, <mem>` so ok.

**Comment by Maijin** [comment]
@wargio well that's just what you wrote but concised
