### ISSUE TITLE
N00b question - disable web server

### ISSUE THREAD

**Issue by securisec** [radare/radare2#7591]
Hello, I am trying to use radare2 (latest) in a headless vm, and was wondering if there is a way to disable using the webserver when using VV or VVV?

Thanks!

**Comment by VisualPrankDude** [comment]
remove c=H from startup flags and inspect e~http for http.allow

**Comment by VisualPrankDude** [comment]
remove -C from startup flags

**Comment by radare** [comment]
Yes the way to disable this is by not using a 5 years old radare.
