### ISSUE TITLE
issues with bicon console

### ISSUE THREAD

**Issue by SSoulaimane** [radare/radare2#7594]
I am using [bicon](https://github.com/behdad/bicon) on linux, bicon is a console that displays right-to-left text correctly.
radare2 opens and works correctly, except when I hit backspace/left arrow when there no more characters to delete/move left the cursor moves far to the left and the radare2 and terminal are unresponsive it can neither move the cursor nor kill radare2 (with Ctrl-c).
```
> r2 bin
 -- No such file or directory.
↓ cursor moves here after pressing backspace/left-arrow.
❚[0x08048074]>
```
I used many repls with bicon and never had any issues, only with radare2.

### Version info:
__bicon__: v0.5 commit g5858585
__radare2__:
```
> r2 -v
radare2 1.4.0 0 @ linux-x86-32 git.1.4.0
commit: HEAD build: 2017-05-02__20:36:04
```
```
> r2 -V
1.4.0  r2
1.4.0  r_anal
1.4.0  r_lib
1.4.0  r_egg
1.4.0  r_asm
1.4.0  r_bin
1.4.0  r_cons
1.4.0  r_flag
1.4.0  r_core
1.4.0  r_crypto
1.4.0  r_bp
1.4.0  r_debug
1.4.0  r_hash
1.4.0  r_fs
1.4.0  r_io
1.4.0  r_magic
1.4.0  r_parse
1.4.0  r_reg
1.4.0  r_sign
1.4.0  r_search
1.4.0  r_syscall
1.4.0  r_util
```

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by XVilka** [comment]
Related to https://github.com/radare/radare2/issues/2032

**Comment by SSoulaimane** [comment]
@Maijin I just rebuilt radare2 from git. The problem is persistent.
```
> r2 -v
radare2 1.5.0-git 0 @ linux-x86-32 git.1.5.0-git
commit: HEAD build: 2017-05-26__09:24:55
```
(no commit info, I didn't clone, it seemed too big, I downloaded the zip)

**Comment by radare** [comment]
How is this handled in readline? Which escape codes are used?

**Comment by radare** [comment]
Are there vertical terminals for japanese too?

**Comment by XVilka** [comment]
@SSoulaimane is it still a problem?

**Comment by XVilka** [comment]
1. @SSoulaimane ping, is this still a problem?
2. FYI here is the list tracking native BiDirectional text support in various terminal emulators: https://gist.github.com/XVilka/a0e49e1c65370ba11c17

**Comment by SSoulaimane** [comment]
Hello, the situation didn't change unfortunately, still the same behavior.
```
> r2 -v
radare2 3.1.0-git 20115 @ linux-x86-64 git.3.0.1-287-g23fb5bc19
commit: 23fb5bc197ded5a9179f54cf502945332932c38e build: 2018-11-19__16:07:24
```

**Comment by ret2libc** [comment]
Is it still reproduceable?
