### ISSUE TITLE
Hardware breakpoints support OS X

### ISSUE THREAD

**Issue by reyder** [radare/radare2#7601]
Are there any plans for supporting hw brekpoints on OS X ?

```[0x10137f000]> db 0x1000b465e
[0x10137f000]> db
0x1000b465e - 0x1000b465f 1 --x hw break enabled cmd="" cond="" name="0x1000b465e" module="/Applications/myhome.app/Contents/MacOS/myhome"
[0x10137f000]> dc
hw breakpoints not yet supported

**Comment by radare** [comment]
Already exists and work on windows, mac and linux. Just use the drx command

**Comment by reyder** [comment]
Already tried that, no results.
```
[0x1008e5000]> drx 1 0x100002560 1 x
[0x1008e5000]> drx
- dr0 Lx 0x00000000 1
- dr1 Lx 0x00000000 1
- dr2 Lx 0x00000000 1
- dr3 Lx 0x00000000 1
- dr6 Lx 0x00000000 1
- dr7 Lx 0x00000000 1

**Comment by radare** [comment]
i have "fixed" this. reading registers seems fine (tested it setting the hwbp with lldb and reading it with r2), but seems like setting it is not working always as expected. I'll check if thats just a mac issue or generic across windows and linux too. cc @skuater all the last changes, so maybe he knows whats going on

**Comment by radare** [comment]
fixed the bug
