### ISSUE TITLE
Project loading not working on Windows 

### ISSUE THREAD

**Issue by Herz3h** [radare/radare2#7610]
Hello,

There seems to be a problem when opening a project that you saved after you've done analysis (aa/aaa).

Steps to reproduce : 

1) Open any exe with r2 -A (or type aa/aaa when inside r2)
2) Ps randomproject
3) Po randomproject

The error i get is : 

```
Unknown calling convention '(null)'
See afCl for available types
```

Environment : 

radare2 1.5.0-git 15223 @ windows-x86-32 git.1.4.0-257-g71de3c477
commit: 71de3c477d5aa8f9a79da199706f1ffb7b1f10bc build: 2017-05-20__12:48:11

**Comment by xarkes** [comment]
Even though there's no other warning, it is likely related to the sdb generation on windows. Will check again after https://github.com/radare/radare2/issues/7829 is fixed.

**Comment by pelijah** [comment]
I think it is already fixed.

**Comment by Maijin** [comment]
Seeing the version used and several bugs got fixed i think we can close until further notice, don't hesitate to let us know @Herz3h ;)
