### ISSUE TITLE
MIPS parser broken on sd

### ISSUE THREAD

**Issue by GovanifY** [radare/radare2#7611]
Actual result from disassembly using r2:

```
[0x001da558]> pd 20
/ (fcn) fcn.001da558 4
|   fcn.001da558 ();
|              ; CALL XREF from 0x0016caf4 (fcn.0016cab8 + 60)
|              ; CALL XREF from 0x0016cd94 (fcn.0016cd48 + 76)
|              ; CALL XREF from 0x0016ca24 (fcn.0016c8f8 + 300)
\           0x001da558      40ffbd27       addiu sp, sp, -0xc0
            0x001da55c      7000b2ff       invalid
            0x001da560      8000b4ff       invalid
            0x001da564      9000b6ff       invalid
            0x001da568      .dword 0x0080902d ; sym.0x0080902d
            0x001da56c      9800b7ff       invalid
            0x001da570      2da00000       invalid
            0x001da574      a000beff       invalid
            0x001da578      .dword 0x00c0b02d ; sym.0x00c0b02d
            0x001da57c      6000b0ff       invalid
            0x001da580      .dword 0x00e0b82d ; sym.0x00e0b82d
            0x001da584      6800b1ff       invalid
            0x001da588      .dword 0x00a0f02d ; sym.0x00a0f02d
            0x001da58c      7800b3ff       invalid
            0x001da590      8800b5ff       invalid
            0x001da594      a800bfff       invalid
            0x001da598      b000b4e7       swc1 f20, 0xb0(sp)
```

hex:

```
0x001da558  40ff bd27 7000 b2ff 8000 b4ff 9000 b6ff  @..'p...........                                                                                                          
0x001da568  2d90 8000 9800 b7ff 2da0 0000 a000 beff  -.......-.......                                                                                                          
0x001da578  2db0 c000 6000 b0ff 2db8 e000 6800 b1ff  -...`...-...h...                                                                                                          
0x001da588  2df0 a000 7800 b3ff 8800 b5ff a800 bfff  -...x...........                      
0x001da598  b000 b4e7 0400 4e8e 0000 498e 4078 0e00  ......N...I.@x..                                                                                                                                                                                              
```

What should be disassembled:

```

var_C0= -0xC0
var_BC= -0xBC
var_B0= -0xB0
var_70= -0x70
var_6C= -0x6C
var_60= -0x60
var_58= -0x58
var_50= -0x50
var_48= -0x48
var_40= -0x40
var_38= -0x38
var_30= -0x30
var_28= -0x28
var_20= -0x20
var_18= -0x18
var_10= -0x10

addiu   $sp, -0xC0
sd      $s2, 0xC0+var_50($sp)
sd      $s4, 0xC0+var_40($sp)
sd      $s6, 0xC0+var_30($sp)
move    $s2, $a0
sd      $s7, 0xC0+var_28($sp)
move    $s4, $zero
sd      $fp, 0xC0+var_20($sp)
move    $s6, $a2
sd      $s0, 0xC0+var_60($sp)
move    $s7, $a3
sd      $s1, 0xC0+var_58($sp)
move    $fp, $a1
sd      $s3, 0xC0+var_48($sp)
sd      $s5, 0xC0+var_38($sp)
sd      $ra, 0xC0+var_18($sp)
swc1    $f20, 0xC0+var_10($sp)
```

**Comment by GovanifY** [comment]
govanify@Witcher /usr/share/doc/radare2 $ r2 -v
radare2 1.5.0-git 14798 @ linux-x86-64 git.1.4.0-330-gbfc5961a1
commit: bfc5961a1f53a2ceddf8da863d16a8c407af78f9 build: 2017-05-28__22:38:55

**Comment by Maijin** [comment]
You have the binary?

**Comment by GovanifY** [comment]
I do, I _think_ it's ok to share it as it is a ps2 era game but preferred to not actually share it just in case

Call me out if I shouldn't have shared it but I don't think it'd be much of a trouble anyways
[SLPM_666.75.zip](https://github.com/radare/radare2/files/1034457/SLPM_666.75.zip)

**Comment by radare** [comment]
this is mips64, not mips32. use -b 64 to solve the problem

**Comment by radare** [comment]
According to wikipedia:
```
CPU core: MIPS R5900 (COP0), 64-bit, little endian (mipsel). CPU is a superscalar, in-order 2-issue design with 6-stage long integer pipelines, four 32 bit GPR registers, 32 128-bit SIMD linear scalar registers, two 64-bit integer ALUs, 128-bit load-store unit (LSU) and a branch execution unit (BXU).
```

So its a mips64 and a MIPS R5900.. but the ELF header specifies MIPS, which, according to binutils, this is only for MIPS R3000, but theres another for R4500.. and the ELF type is 32, not ELF64. So it ends up setting asm.bits to 32. So imho this ELF is not properly defined, so the solution would be to add -b64 by hand.

if you think there's a better way to autodetect this is welcome!

**Comment by GovanifY** [comment]
That isn't true. PS2 have both a R5900 and R3000 so the elf is properly defined.
The code should definitelly be parsed as 32 bits too
This picture should explain good enough why(it is using pcsx2 debugger which is a working ps2 emulator and I doubt it got their opcodes wrong)

![image](https://cloud.githubusercontent.com/assets/6375438/26532170/1f2d155e-43fa-11e7-9dd2-d08f64f901f1.png)

**Comment by Maijin** [comment]
Potentially a capstone issue did you try playing with `e asm.cpu=?` and `e asm.arch=mips.gnu`

![image](https://cloud.githubusercontent.com/assets/1408600/26532200/ab9c29ee-43fa-11e7-968c-3072467f9dbd.png)

It's not great but show potential issue in disassembler engine (pbly capstone)

**Comment by Maijin** [comment]
Mind trying with capstone natively to see if you get something better ? If not then the issue definitely will have to be sent to Capstone repository

**Comment by GovanifY** [comment]
@Maijin Could check but definitely does not seem to be correct. It is indeed based on MIPS32 but seems to have a pseudo custom ISA.
It is indeed MIPS32 and should not be interpreted as MIPS64 in any case

**Comment by Maijin** [comment]
yes but it is potentially a capstone bug we need to confirm/infirm this before moving forward.

**Comment by GovanifY** [comment]
yeah, said I was going to check either way
Also a thing to note with the ps2 hardware is that it's a monstrosity of complexity, you should almost never assume anything out of it, it proves to be most of the time wrong.
Thanks for all so far

**Comment by Maijin** [comment]
np

**Comment by GovanifY** [comment]
```
govanify@Witcher ~ $ cat test.py 
from capstone import *

CODE= b"\x40\xff\xbd\x27\x70\x00\xb2\xff\x80\x00\xb4\xff\x90\x00\xb6\xff\x2d\x90\x80\x00\x98\x00\xb7\xff\x2d\xa0\x00\x00\xa0\x00\xbe\xff\x2d\xb0\xc0\x00\x60\x00\xb0\xff\x2d\xb8\xe0\x00\x68\x00\xb1\xff\x2d\xf0\xa0\x00"
md = Cs(CS_ARCH_MIPS, CS_MODE_32)
for i in md.disasm(CODE, 0x1000):
    print("0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
govanify@Witcher ~ $ python test.py 
0x1000: addiu   $sp, $sp, -0xc0
```

Looks like it indeed is a capstone issue

Should I try to fix it on their side?

**Comment by Maijin** [comment]
Yes, at least open the issue there.

**Comment by Maijin** [comment]
Thanks confirming 👍

**Comment by GovanifY** [comment]
@Maijin please re-open MIPS64 upstream seems to have the issue fixed(it should indeed be read as MIPS64)

```
govanify@Witcher ~ $ python test.py 
0x1000: addiu   $sp, $sp, -0xc0
0x1004: sd      $s2, 0x70($sp)
0x1008: sd      $s4, 0x80($sp)
0x100c: sd      $s6, 0x90($sp)
0x1010: move    $s2, $a0
0x1014: sd      $s7, 0x98($sp)
0x1018: move    $s4, $zero
0x101c: sd      $fp, 0xa0($sp)
0x1020: move    $s6, $a2
0x1024: sd      $s0, 0x60($sp)
0x1028: move    $s7, $a3
0x102c: sd      $s1, 0x68($sp)
0x1030: move    $fp, $a1          
```

**Comment by radare** [comment]
it should be good now, but the entrypoint is not properly disassembled, and those instructions seems to not be supported by capstone:
```
prop:capstone pancake$ git grep PADDUW
prop:capstone pancake$ git grep PADDU | grep Mips
prop:capstone pancake$
```

should be "padduw at, zero, zero" for 280c0070

rasm2 -a mips -b 64 -d 280c0070

**Comment by radare** [comment]
we need more tests for mips and 32/64/cpu settings, can you submit some tests? is this bin redistributable?

**Comment by GovanifY** [comment]
The bin is most likely not redistributable but it comes from a ps2 game and the padduw is generic to the toolchain used, so ripping off this part of the code shouldn't trigger any issue.
I can confirm for the padduw

**Comment by GovanifY** [comment]
I could submit tests for mips I guess, although I guess we'd have to do a check for R3000 ELF's to check if it is a mips64 executable, unsure on how to accurately check this though

**Comment by GovanifY** [comment]
also radare still show as sdc3 while in capstone master is is sd so issue is not solved until capstone is pushed to master here:

```
[0x001da558]> pd 10
/ (fcn) fcn.001da558 140
|   fcn.001da558 ();
|              ; CALL XREF from 0x0016caf4 (fcn.0016cab8)
|              ; CALL XREF from 0x0016cd94 (fcn.0016cd48)
|              ; CALL XREF from 0x0016ca24 (fcn.0016c8f8 + 300)
|           0x001da558      40ffbd27       addiu sp, sp, -0xc0
|           0x001da55c      7000b2ff       sdc3 18, 0x70(sp)
|           0x001da560      8000b4ff       sdc3 20, 0x80(sp)
|           0x001da564      9000b6ff       sdc3 22, 0x90(sp)
|           0x001da568      2d908000       move s2, a0
|           0x001da56c      9800b7ff       sdc3 23, 0x98(sp)
|           0x001da570      2da00000       move s4, zero
|           0x001da574      a000beff       sdc3 30, 0xa0(sp)
|           0x001da578      2db0c000       move s6, a2
|           0x001da57c      6000b0ff       sdc3 16, 0x60(sp)
[0x001da558]> !r2 -v
radare2 1.5.0-git 14803 @ linux-x86-64 git.1.4.0-335-gf26213074
commit: f26213074b6949a8c03b784d9d13ec84a10a5554 build: 2017-05-29__02:26:07

```

**Comment by radare** [comment]
R2 uses capstone from git. So its already the last version of it

**Comment by GovanifY** [comment]
Then it is another issue as capstone actually show sd when just inputting the binary, might be worth to check it out

**Comment by mrmacete** [comment]
ok, i double checked this: capstone `master` and capstone release it's ok, while this has been broken in capstone `next` which is the branch we compile against by default

**Comment by mrmacete** [comment]
https://github.com/aquynh/capstone/issues/938

**Comment by mrmacete** [comment]
just to summarize, to get the right disassembly: `e asm.cpu=64v2`
