### ISSUE TITLE
Unable to install unicorn on FreeBSD 11.0

### ISSUE THREAD

**Issue by crvintel** [radare/radare2#7640]
Target installation is into my user directory, rather than the system one, using r2pm.

Installation of unicorn-lib worked fine, although trying to install unicorn results in the output given in the attachment.
[unicorn.txt](https://github.com/radare/radare2/files/1041168/unicorn.txt)
 
r2pm list shows that only unicorn-lib has been installed. 

Thanks.

**Comment by radare** [comment]
do you have pkg-config installed?

**Comment by crvintel** [comment]
I use pkg-ng, so so pkg-config, but have pkg config.

**Comment by crvintel** [comment]
Sorry for the confusion. I now have pkg-config installed, although the build now fails with below. I also had to set the environment variable CC=cc or else it complained that gcc was not found. Hope this helps.
echo 'Name: unicorn' > unicorn.pc
echo 'Description: Unicorn emulator engine' >> unicorn.pc
echo 'Version: 1.0.2' >> unicorn.pc
echo 'libdir=/home/chris/.config/radare2/prefix//lib' >> unicorn.pc
echo 'includedir=/home/chris/.config/radare2/prefix//include' >> unicorn.pc
echo 'archive=${libdir}/libunicorn.a' >> unicorn.pc
echo 'Libs: -L${libdir} -lunicorn' >> unicorn.pc
echo 'Cflags: -I${includedir}' >> unicorn.pc
mkdir -p /home/chris/.config/radare2/prefix//lib
install -m0755 libunicorn.so.1 /home/chris/.config/radare2/prefix//lib
cd /home/chris/.config/radare2/prefix//lib && \
ln -sf libunicorn.so.1 libunicorn.so
install -m0644 libunicorn.a /home/chris/.config/radare2/prefix//lib
mkdir -p /home/chris/.config/radare2/prefix//include/unicorn
install -m0644 include/unicorn/*.h /home/chris/.config/radare2/prefix//include/unicorn
mkdir -p /home/chris/.config/radare2/prefix//libdata/pkgconfig
install -m0644 unicorn.pc /home/chris/.config/radare2/prefix//libdata/pkgconfig/
Install Done For unicorn
checking build system type... amd64-unknown-freebsd
checking host system type... amd64-unknown-freebsd
checking target system type... amd64-unknown-freebsd
checking for working directories... current
using prefix '/home/chris/.config/radare2/prefix/'
checking for c compiler... cc
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... yes
checking for libewf ... no
Using PKGCONFIG: pkg-config
checking pkg-config flags for libewf... yes
Using PKGCONFIG: pkg-config
checking pkg-config flags for unicorn... no
checking for libyara ... no
Using PKGCONFIG: pkg-config
checking pkg-config flags for yara... yes
creating ./Makefile
creating ./options.mk
cleaning temporally files... done

Final report:
 - PREFIX = /home/chris/.config/radare2/prefix/
gmake: Entering directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/unicorn'
gmake -C ../libr/debug clean
gmake[1]: Entering directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug'
gmake -C p clean
gmake[2]: Entering directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug/p'
Makefile:21: warning: overriding recipe for target 'debug_unicorn.so'
unicorn.mk:15: warning: ignoring old recipe for target 'debug_unicorn.so'
rm *.so *.o
rm: *.so: No such file or directory
rm: *.o: No such file or directory
gmake[2]: *** [Makefile:31: clean] Error 1
gmake[2]: Leaving directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug/p'
gmake[1]: *** [Makefile:5: clean] Error 2
gmake[1]: Leaving directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug'
gmake: *** [Makefile:6: clean] Error 2
gmake: Leaving directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/unicorn'
gmake: Entering directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/unicorn'
gmake -C ../libr/debug
gmake[1]: Entering directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug'
gmake -C p
gmake[2]: Entering directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug/p'
Makefile:21: warning: overriding recipe for target 'debug_unicorn.so'
unicorn.mk:15: warning: ignoring old recipe for target 'debug_unicorn.so'
cc -I/home/chris/.config/radare2/prefix//include/ -I/usr/local/include/libr  -g -I/usr/local/include -L/usr/local/lib -I/usr/local/include/libr -g -DHAVE_PKGCFG_UNICORN=0  -fPIC -L/home/chris/.config/radare2/prefix//lib/ -L/usr/local/lib -lr_debug -lr_anal -lr_bp -lr_io -lr_parse -lr_cons -lr_syscall -lr_hash -lr_flag -lr_socket -lr_reg -lr_util  -g  -c debug_unicorn.c -o debug_unicorn.o
cc: warning: -lr_debug: 'linker' input unused
cc: warning: -lr_anal: 'linker' input unused
cc: warning: -lr_bp: 'linker' input unused
cc: warning: -lr_io: 'linker' input unused
cc: warning: -lr_parse: 'linker' input unused
cc: warning: -lr_cons: 'linker' input unused
cc: warning: -lr_syscall: 'linker' input unused
cc: warning: -lr_hash: 'linker' input unused
cc: warning: -lr_flag: 'linker' input unused
cc: warning: -lr_socket: 'linker' input unused
cc: warning: -lr_reg: 'linker' input unused
cc: warning: -lr_util: 'linker' input unused
cc: warning: argument unused during compilation: '-L/usr/local/lib'
cc: warning: argument unused during compilation: '-L/home/chris/.config/radare2/prefix//lib/'
cc: warning: argument unused during compilation: '-L/usr/local/lib'
debug_unicorn.c:672:2: error: Cannot find unicorn library
#error Cannot find unicorn library
 ^
1 error generated.
gmake[2]: *** [Makefile:15: debug_unicorn.o] Error 1
gmake[2]: Leaving directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug/p'
gmake[1]: *** [Makefile:2: all] Error 2
gmake[1]: Leaving directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/libr/debug'
gmake: *** [Makefile:2: all] Error 2
gmake: Leaving directory '/usr/home/chris/.config/radare2/r2pm/git/radare2-extras/unicorn'
[radare2]$

**Comment by radare** [comment]
the error is quite obvious

**Comment by crvintel** [comment]
Sorry, I can't see it!

**Comment by radare** [comment]
> #error Cannot find unicorn library


so the solution is r2pm -i unicorn-lib

**Comment by crvintel** [comment]
r2pm list
unicorn-lib

Is already installed

**Comment by radare** [comment]
whats the output of $ r2pm -r pkg-config --libs unicorn

btw, why are you truing to use unicorn? esil is way superior and more well supported and integrated into r2, the unicorn plugin is quite useless

**Comment by crvintel** [comment]
Package unicorn was not found in the pkg-config search path.
Perhaps you should add the directory containing `unicorn.pc'
to the PKG_CONFIG_PATH environment variable
Package 'unicorn', required by 'virtual:world', not found

OK Thanks. I will look into using esil.

**Comment by radare** [comment]
this PKG_CONFIG_PATH is set to ~/.config/radare2/prefix/lib/pkgconfig

so it should be found. you can spawn an r2pm shell and see that env with r2pm -s

**Comment by crvintel** [comment]
Thanks for you help. I have just tried to use ESIL and that is doing exactly what I wanted. I didn't know about this as I am a new Radare2 user. So, I guess the issue can be closed.

Thanks for your help. Radare2 is a really great tool!

Chris
