### ISSUE TITLE
problem installing radare2 on ubuntu from git repository

### ISSUE THREAD

**Issue by draikes30** [radare/radare2#7648]
After installing a fresh ubuntu 14.04 or 16.04 32-bit or 64-bit virtual machine and after  cloning the radare2 repository as a regular user, I run
$ sudo sys/install.sh

The installation appears to complete successfully, however the regular user cannot execute any of the radare2 tools due to permission problems.
If I do
$ ls -l /usr/bin/r*2
all the files have permissions lrwxrwxrwx.

Root can run the tools just not a regular user.

**Comment by SajjadPourali** [comment]
@draikes30 : i can not reproduce this issue, can you help me for reproducing this issue?
**ubuntu 14.04 32-bit**
<img width="608" alt="screen shot 2017-06-01 at 12 24 21" src="https://cloud.githubusercontent.com/assets/20374762/26670079/834a9138-46c5-11e7-937d-8458d747dfa2.png">
**ubuntu 16.04 64-bit**
<img width="628" alt="screen shot 2017-06-01 at 12 25 56" src="https://cloud.githubusercontent.com/assets/20374762/26670088/8c442146-46c5-11e7-9805-c029f53a1ce6.png">

please follow radare2 symbolic link and check source permissions,i suggest you remove and purge completely radare2, get last version of radare2 from git and reinstall it, if there was available this issue, tell me step by step what do you do.

**Comment by radare** [comment]
> On 1 Jun 2017, at 05:42, draikes30 <notifications@github.com> wrote:
> 
> After installing a fresh ubuntu 14.04 or 16.04 32-bit or 64-bit virtual machine and after cloning the radare2 repository as a regular user, I run
> $ sudo sys/install.sh
> 

Wrong. Dont build with sudo

**Comment by radare** [comment]
Also sys/install.sh does symlinks to install everything, and this have those consequences. Just use make install to copy the files if you are building from a directory where the normal user doesnt have permissions
