### ISSUE TITLE
see variables at exact time

### ISSUE THREAD

**Issue by mahdifox** [radare/radare2#7656]
is it possible to see the value of variables any time we like, and variables like locals.
for example in my binary file I wonder if I can see the value of "dword [local_4h]"
or the value of eax in my 64bits testProgram ?!?!?!?!?!?
![image](https://cloud.githubusercontent.com/assets/17719466/26705666/ce2cc4be-474c-11e7-8759-68f0c1d9db51.png)

**Comment by Maijin** [comment]
use `.afvd local_4h`
You can also `e asm.varsub=false`
!!!!??!?!?!??!!
