### ISSUE TITLE
Can't start radare2.exe on Win10, v1.5

### ISSUE THREAD

**Issue by Neurrone** [radare/radare2#7677]
When doing radare2 -h on the v1.5 windows binary, I get the following message

radare2.exe - Application Error  
The application was unable to start correctly (0xc0000022). Click OK to close the application.

**Comment by radare** [comment]
Use the msvc build in cloud.radare.org/get or the one from bin.rada.re, the release machinery was producing wrong executables for some reason. Must do another tiny update and check that bug with the dockcross guise

**Comment by Neurrone** [comment]
@radare thanks that worked.

**Comment by Neurrone** [comment]
@radare still happening when downloading v1.6 from the homepage, but using the alternate link for latest git release works.

**Comment by radare** [comment]
you mean that the msvc build works but not the mingw works for you?

**Comment by Neurrone** [comment]
@radare if the download link from the homepage is to a mingw compiled build, then yes. I believe @frankbolero also observed this too.

**Comment by radare** [comment]
yep it is, whats the problem you observe? not running at all? any backtrace crash? r2 should work fine with mingw

**Comment by frankbolero** [comment]
@radare 1.6.0 from hompage crashes for me ("Windows is checking for a solution to the problem"-window exit with no error message or debug with VS2017), the link given by @Neurrone works.

When debugging it in VS2017 all I get is "Unhandled exception at 0x76180E2B (msvcrt.dll) in radare2.exe: 0xC0000005: Access violation reading location 0x00000208. occurred".

**Comment by Maijin** [comment]
Use http://bin.rada.re/radare2-w32-1.7.0-git.zip
