### ISSUE TITLE
mbn: overly strict load_index check

### ISSUE THREAD

**Issue by sroxy** [radare/radare2#7681]
I wanted to take a peek at my phone's aboot.mbn but r2 didn't
recognize it.  This change in libr/bin/p/bin_mbn.c fixes it (aboot.mbn
has value 5):

-               if (sb.load_index < 0x10 || sb.load_index > 0x40) return false; // should be 0x19 ?
+               if (sb.load_index < 1 || sb.load_index > 0x40) return false; // should be 0x19 ?

I found this reference for mbn header, load_index is called image_id there:
https://github.com/openpst/libopenpst/blob/master/include/qualcomm/mbn.h

**Comment by radare** [comment]
Send a pr, just click the pencil button

**Comment by sroxy** [comment]
Sorry I've no idea what your comment means???
The pencil button here lets me edit what I wrote but nothing else.

**Comment by radare** [comment]
Just click the pencil button frmo the file you wanna edit 

https://github.com/radare/radare2/blob/master/libr/bin/p/bin_mbn.c

when saving the changes it will fork, branch, commit and send a pullreq, simpler than reporting it by hand and we can check travis automatically this way.

**Comment by Maijin** [comment]
Can you add a test/binary in radare2-regressions repository?

**Comment by sroxy** [comment]
@Maijin I can't share binaries but you can find some here:
https://github.com/aureljared/unbrick_8960/tree/master/devices/SCH-I535
or just google for filetype:mbn

**Comment by Maijin** [comment]
But which of those would reproduce the problem?

**Comment by sroxy** [comment]
The aboot.mbn, it has image id 5.
