### ISSUE TITLE
Entry point not found on Windows

### ISSUE THREAD

**Issue by Herz3h** [radare/radare2#7689]
After putting a breakpoint on any function and running dc, i get an error message saying entry point not found.

Steps to reproduce :

Open any exe with r2 -Ad

`db sym.any_symbol (whatever symbol you choose)`

The error i get is :

Entry point not found

Environment :
radare2  0 @ windows-x86-64 git.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Maijin** [comment]
No description == useless issue.

**Comment by Herz3h** [comment]
Sorry pressed enter by mistake, added a description.

**Comment by Maijin** [comment]
Try with http://bin.rada.re/radare2-w32-1.6.0-git.zip

**Comment by Herz3h** [comment]
Just tried with that build and issue still exists there.

**Comment by Maijin** [comment]
you need db @ sym.any_symbol

**Comment by Herz3h** [comment]
Alright that seems to be the reason it was failing.

**Comment by Maijin** [comment]
We also recommend to use https://conemu.github.io/en/Screenshots.html for better r2 experience

**Comment by Herz3h** [comment]
Actually doing db @ sym.any_symbol doesn't add any breakpoint, hence why it wasn't crashing

**Comment by radare** [comment]
rtfm before reporting, db ignores the current seek. you have to use db. or pass the arg to db

**Comment by radare** [comment]
dont do -A

**Comment by radare** [comment]
you should use r2 from git. the build from windows is borken, and the -A is basically running esil emulation which breaks the io layer. this is fixed in master
