### ISSUE TITLE
Unable to pass argument that contains '@' to doo command with external command

### ISSUE THREAD

**Issue by SajjadPourali** [radare/radare2#7690]
(**\x40** is **@**)
for example: 
in regular command line : a.out \`python '"a"*20+"**\x40**\x73\x74\x76"'\` 
in radare : doo \`!python '"a"*20+"**\x40**\x73\x74\x76"'\`  `(can not pass @)`
in radare : "doo \`!python '"a"*20+"**\x40**\x73\x74\x76"'\`"  `(can not execute python script)`

**Comment by SajjadPourali** [comment]
@radare: Thank you for your response, I did use rarun2 instead these ways, but this is a bit time consuming ragg2 is awesome too,but I'm looking for a faster way like directly in doo command.
```
root@sajjad:~# radare2 -d ch33 -e dbg.profile=e.rr2
Process with PID 11465 started...
= attach 11465 11465
bin.baddr 0x08048000
Using 0x8048000
Assuming filepath /root/ch33
asm.bits 32
 -- The door is everything ...
[0xf7fd9ac0]> cat e.rr2
#!/opt/radare2/bin/rarun2
arg1=`python -c 'print "@@"*2'`
[0xf7fd9ac0]> dc
Selecting and continuing: 11465
Your message: @@@@
PTRACE_EVENT_EXIT pid=11465, status=0x0
[0xf7fd7c89]>
```
I did check radare2 reference, but I could not perform with using quotes, could you please give me an example ?

**Comment by radare** [comment]
r2 uses gnu getopt. you cant pass arguments after the programname. so move the -d ch33 to the end of the line otherwuse -e dbg… is passed as argument to ch33

**Comment by SajjadPourali** [comment]
thank you  .
