### ISSUE TITLE
Bibtex formated reference of Radare

### ISSUE THREAD

**Issue by roj4s** [radare/radare2#7704]
Hi, I've been using radare2 on my research and I'd like to include a reference. I've looked for a bibtex formated reference on site radare.org, radare book www.radare.org/get/radare.pdf, radare.gitbooks.io and here in this github repo, without success. Where can I find it?. Thanks in advance.

**Comment by XVilka** [comment]
Do you search for something like this:
```
@misc{radare2,
	author = {Radare2 Team},
	title = {Radare2 GitHub repository},
	year = {2017},
	publisher = {GitHub},
	journal = {GitHub repository},
	howpublished = {\url{https://github.com/radare/radare2}},
}
```

**Comment by roj4s** [comment]
Thanks

**Comment by Maijin** [comment]
radare.pdf is obsolete, use https://radare.gitbooks.io/radare2book/content/

**Comment by XVilka** [comment]
Well, it's pretty basic I think., something like that:
```
@book{radare2book,
	author = {Radare2 Team},
	title = {Radare2 Book},
	year = {2017},
	publisher = {GitHub},
	howpublished = {\url{https://radare.gitbooks.io/radare2book/content/}},
}
```
Closing the issue.
