### ISSUE TITLE
Java patching doesn't work in visual mode

### ISSUE THREAD

**Issue by mrckhff** [radare/radare2#7706]
Hi, first of all: thanks pancake  and to all the amazing contributors for this great software.

I'm using radare2 for patching java class bytecode.
When I try, in visual mode, to "write some java-32 assembly", radare2 always write a different instruction than I specify.

A video worth a thousand words.
Please, watch the short video showing the problem with radare2 and Java:

![radare2-bug](https://user-images.githubusercontent.com/29297885/26961649-5749d6ae-4cae-11e7-99ae-a0fae95ca802.gif)

Alternate links for the video:
http://i.imgur.com/VvxeOoq.gif
http://www48.zippyshare.com/v/D5Afo3Br/file.html

I'm using the latest version from Git
I tried with RHEL 7.2 and Kali 2017.1
I tried with radare2 v1.4.0 too.

Thanks for your help.

**Comment by XVilka** [comment]
Btw, you can use [asciinema](https://asciinema.org) to record this kind of video.

**Comment by mrckhff** [comment]
@XVilka, thanks for the title :)

By the way, here is the java app used:
http://the.bytecode.club/crackmes/1-Dark_Prince-first-crackme_Java.zip

Thanks.

**Comment by mrckhff** [comment]
@**XVilka** Is there anything I can assist you with?

**Comment by radare** [comment]
$ rasm2 -a java "if_icmpeq 0x344"
9f0000

so the issue is in the assembler, that it ignores the number thats simple to fix. and its not related to writing or so.

**Comment by radare** [comment]
works if you pass the argument in base10

**Comment by radare** [comment]
please add tests for the radare-regressions repo.

**Comment by mrckhff** [comment]
Thanks so much for your effort!!!

**Comment by radare** [comment]
Np took me few mins :p
