### ISSUE TITLE
can't detect the main (PE)

### ISSUE THREAD

**Issue by n0way0ut** [radare/radare2#7716]
it is an exe with png extension.
![platinum](https://user-images.githubusercontent.com/5345101/26995700-6530e8e6-4d6e-11e7-8757-1f10bf54fdd9.png)

**Comment by Maijin** [comment]
Other tools can't find main as well so closing here, this probably packed or something messed up in the entrypoint, definitely not standard.

**Comment by radare** [comment]
Othwr tools not doing it right is not a reason to close. I didnt had time to check the bin or its a complete messedup packed
Bin?

**Comment by Maijin** [comment]
It's messed up, nothing to see here
