### ISSUE TITLE
Breakpoint command output is sometimes duplicated

### ISSUE THREAD

**Issue by puxlit** [radare/radare2#7724]
Here's an example where output is duplicated.

```
$ r2 -c '?V;db main;dbc main ?e echoes twice;dc' -d /bin/true
= attach 26214 26214
bin.baddr 0x100000000
Using 0x100000000
asm.bits 64
hit breakpoint at: 100000f53
echoes twice
1.6.0-git aka 1.5.0-96-gba25be493 commit 15031
echoes twice
 -- Charlie! We are here.
[0x100000f53]>
```

Here's an example where output is _not_ duplicated.

```
$ r2 -c '?V;db main;dbc main ?E echoes once;dc' -d /bin/true
= attach 26229 26229
bin.baddr 0x100000000
Using 0x100000000
asm.bits 64
hit breakpoint at: 100000f53
1.6.0-git aka 1.5.0-96-gba25be493 commit 15031
 .--.     .-------------.
 | _|     |             |
 | O O   <  echoes once |
 |  |  |  |             |
 || | /   `-------------'
 |`-'|
 `---'
 -- radare2 is WYSIWYF - what you see is what you fix
[0x100000f53]>
```

I think this might be a consequence of 211688f537295aae5a44f85011358f1a1ab283f8. Output shunted via `r_cons_strcat` will be duplicated (per the commit), whereas output shunted via `r_cons_printf` (with a format string that actually contains format specifiers) won't be echoed to `stderr`.

**Comment by radare** [comment]
can you guise have a look at this? just adding a r_sys_backtrace on this line will show the problem but i have absolutely no time. also we will need have some tests for this

cc @leberus @skuater

**Comment by puxlit** [comment]
More inconsistencies surrounding `scr.echo`:

```
[0x100006000]> e scr.echo
false
[0x100006000]> dr*
fs+regs
f rax 1 0x0x00000000
f rbx 1 0x0x00000000
f rcx 1 0x0x00000000
f rdx 1 0x0x00000000
f rdi 1 0x0x00000000
f rsi 1 0x0x00000000
f rbp 1 0x0x00000000
f rsp 1 0x0x7fff5fbffee0
f r8 1 0x0x00000000
f r9 1 0x0x00000000
f r10 1 0x0x00000000
f r11 1 0x0x00000000
f r12 1 0x0x00000000
f r13 1 0x0x00000000
f r14 1 0x0x00000000
f r15 1 0x0x00000000
f rip 1 0x0x100006000
f rflags 1 0x0x00000200
fs-
[0x100006000]> .dr*
[0x100006000]> e scr.echo=true
fs+regs
fs-
[0x100006000]> .dr*
fs+regs
fs-
fs+regs
fs-
```

**Comment by radare** [comment]
scr.echo seems broken after the rcons.push/pop implementation. i would probably suggest to remove it. what do you think? anybody is using it?

**Comment by puxlit** [comment]
Nixing the forced enabling of echo in `r_core_debug_breakpoint_hit` _does_ fix the aforementioned issues.

**Comment by radare** [comment]
send a pr
