### ISSUE TITLE
Numerous 8051 disassembly errors

### ISSUE THREAD

**Issue by astuder** [radare/radare2#7737]
asm and anal for 8051 have various issues. Here a few examples:

issue|wx|output|expected|notes
----|----|---|---|---
JB bit, offset|207d03|  jb bit, 0x7d03|       jb 0x7d, pc+0x03
JNB bit, offset|305108|  jnb bit, 0x5108|      jnb 0x51, pc+0x08
JBC bit, offet|101508|  jbc bit, 0x1508|      jbc 0x15, pc+0x08
DJNZ rn, offset|dffa |   djnz r7, 0xfa // mov r2,a |       djnz r7, pc+0xfa |        also not recognized as jump
ANL direct, imm  |    53c9df | invalid |             anl 0xc9, #0xdf|
CJNE rn, imm, offset |bf0205 | cjne r7, 0x02, 0x05 | cjne r7, #0x02, pc+0x05  | jump not recognized
MOV direct, imm  |    751908 | mov 0x19, #RAM_D0 |   mov 0x19, #0x08
ORL direct, imm  |    43dc02 | orl direct, #imm  |   orl 0xdc, #0x02
CLR bit	|             c2af  |  clr bit 0xaf  |       clr 0xaf	
MOV direct, rn  |     8c83 |   mov direct, r4 |      mov 0x83, r4

I took a look at /libr/asm/arch/8051 and the code is too convoluted for quick fixes. I will probably rewrite the disasm, but it will take some time as the current implementation of 8051 anal has a dependency on it.

**Comment by XVilka** [comment]
Please don't forget to send PR to radare2-regressions.

**Comment by astuder** [comment]
Working on it. Several of the existing test were wrong as well.

Will probably submit a first pull request adding my issues and then implement complete test coverage of all opcodes before touching asm and anal.

**Comment by astuder** [comment]
See https://github.com/radare/radare2-regressions/pull/884

**Comment by radare** [comment]
awesome. thanks!

**Comment by astuder** [comment]
Regarding immediate vs direct:
An option would be to but direct into brackets, similar to x86.

Immediate: add a, 0x12
Direct: add a, [0x12]

Though, then it should also be [ri] and [dptr] instead of @ri and @dptr, so maybe going with @ makes more sense.

Let me know what you prefer and I will do the changes.

**Comment by astuder** [comment]
FWIW, IDAPro also uses # for immediate.
![ida-8051-example](https://user-images.githubusercontent.com/1166488/27258104-1cf4ae44-53a6-11e7-8131-fbaf5aae64ac.PNG)

**Comment by astuder** [comment]
Thanks for merging.

2 known issues (will create tests later today)
- addr11 is computed incorrectly. Should be PC bits 15-12 + addr 11. Currently ignores PC.
- mov direct-dest, direct-src arguments are flipped. 

Also thinking about resolving bit addresses to 0xbyte.bit format. Any precedence in another arch I can follow?

**Comment by astuder** [comment]
Updated regression tests: https://github.com/radare/radare2-regressions/pull/889

**Comment by astuder** [comment]
Closing issue as 8051 disassembler now is pretty robust.
