### ISSUE TITLE
Implement axq command

### ISSUE THREAD

**Issue by radare** [radare/radare2#7754]
quiet xrefs listing

**Comment by Maijin** [comment]
This is `axtq`

**Comment by Maijin** [comment]
oh maybe you want all so makes sense to have axq

**Comment by radare** [comment]
Shouldnt axq be an alias for axtq?

**Comment by Maijin** [comment]
no because then how to do you differentiate with `axfq`

**Comment by radare** [comment]
? i want ALL refs, not just the ones from/to the current address

**Comment by Maijin** [comment]
That's what I said...

**Comment by radare** [comment]
axfq must be FROM current function
axq must be from ALL functions

Whats the question?

**Comment by Maijin** [comment]
No question here ;P

**Comment by radare** [comment]
Done in master
