### ISSUE TITLE
Can't find radare2rc

### ISSUE THREAD

**Issue by Kalibr8** [radare/radare2#7761]
Can't find radare2rc in home directory or .config directory. Using version 1.6.0. Looked for it in /etc, /usr, /var ...can't seem to find it anywhere, including ~/radare2. Am I missing something or is it just not there?

**Comment by XVilka** [comment]
`~/.config/radare2/radare2rc` - it should be here

**Comment by radare** [comment]
See r2 -hh

**Comment by Maijin** [comment]
Just create it.

**Comment by Kalibr8** [comment]
Looked at r2 -hh.  Can't find radare2rc in any of the directories listed under scripts. In ~/.config the radare2 directory only contains an ASCII text file called history. There are no dotfiles or sub-directories. I'm using Lubuntu btw. Don't know if that's a factor in this issue, though I suspect it shouldn't be..

**Comment by radare** [comment]
Its up to the user by default r2 doesnt imposes any custom user configs

**Comment by radare** [comment]
man mkdir
man nano

**Comment by Kalibr8** [comment]
Created it. Thanks.
