### ISSUE TITLE
Cannot find wsnmp32.sdb

### ISSUE THREAD

**Issue by n0way0ut** [radare/radare2#7764]
Cannot find /usr/share/radare2/1.6.0-git/format/dll/wsnmp32.sdb

radare2 1.6.0-git 15071 @ linux-x86-64 git.1.5.0-135-g4162a24e5
commit: 4162a24e555ab2423355cf910386ddc73318383a build: 2017-06-17__21:07:22

**Comment by Maijin** [comment]
This is a warning, not an error, you can help contributing for this, See here https://github.com/radare/radare2/tree/master/libr/bin/d/dll

**Comment by n0way0ut** [comment]
how those files are generated? I hope not by hand.. :)

**Comment by Maijin** [comment]
Download the DLL -> get the export with `iE`, regex -> done. 

I don't have script anymore, now the warning only appears on very specific DLLs.

**Comment by Maijin** [comment]
ping @n0way0ut
