### ISSUE TITLE
[QUESTION] how should unix-word-rubout behave?

### ISSUE THREAD

**Issue by lowlyw** [radare/radare2#7771]
looking at how ^w is handled in dietline:

only whitespace is taken into consideration. this is not the case in gnu dietline

first test is "hello-world"
second is "hello;world"
![image](https://user-images.githubusercontent.com/20349928/27262143-64b59a0e-5405-11e7-860a-e057341dbdc5.png)
![image](https://user-images.githubusercontent.com/20349928/27262149-88f98678-5405-11e7-98a0-6a6fe4371888.png)

so there's a difference in the behaviors with alt+backspace and ctrl+w handled by bash

I'm not sure what the intended behavior for dietline should be here

dietline has no concept of word break characters except for 0x20 (space), readline has `rl_basic_word_break_characters`. How should this be handled?

attn: @radare

**Comment by XVilka** [comment]
@lowlyw can this be closed?

**Comment by radare** [comment]
ping

**Comment by lowlyw** [comment]
closing this is done
