### ISSUE TITLE
comments sys_execve/sys_exit unknown ?

### ISSUE THREAD

**Issue by Susanne588586** [radare/radare2#7773]
```
( egrep '59|60' text.s | column -t ) && ( r2 -e asm.emu=1 -qc "pd~unk"  text 2> /dev/null | column -t )
add  rax,  59  ;  sys_execve
add  rax,  60  ;  sys_exit
0x00400093  0f05  syscall  ;  59  =  unknown  ()
0x0040009f  0f05  syscall  ;  60  =  unknown  ()
```

r2 -v
radare2 1.6.0-git 15066 @ linux-x86-64 git.1.5.0-123-g0b4eb17
commit: 0b4eb1740c723996c3843791faec2fc7b1a620fe build: 2017-06-15__19:00:22

**Comment by radare** [comment]
Just update the syscall files for that target. Is this linux?

**Comment by Susanne588586** [comment]
@radare this is linux and sys_execve is defined as 59 as is sys_exit as 60. I thought, though radare2 is shipping its own? Note, it is only in the comments.

**Comment by Maijin** [comment]
Update syscall here https://github.com/radare/radare2/tree/master/libr/syscall/d

**Comment by Susanne588586** [comment]
@Maijin @radare The phile is ok. So, problem remains only in comments, still saying "unknown" while having the right syscall number.

**Comment by radare** [comment]
can you reproduce with the as command?

**Comment by radare** [comment]
can you add tests?

**Comment by Susanne588586** [comment]
[0x00400080]> e asm.emu=0
[0x00400080]> as
Syscall database not loaded
0 = unknown ()

**Comment by Susanne588586** [comment]
@Maijin @radare how to load syscalldb? with sdb?

**Comment by Susanne588586** [comment]
[0x00400080]> ko /home/sk/radare2/libr/syscall/d/linux-x86-64.sdb linux-x86-64
[0x00400080]> as
Syscall database not loaded
0 = unknown ()
[0x00400080]> k
[0x00400080]> k?
|Usage: k[s] [key[=value]]Sdb Query
| k foo=bar                 set value
| k foo                     show value
| k                         list keys
| ko [file.sdb] [ns]        open file into namespace
| kd [file.sdb] [ns]        dump namespace to disk
| ks [ns]                   enter the sdb query shell
| k anal/meta/*             ist kv from anal > meta namespaces
| k anal/**                 list namespaces under anal
| k anal/meta/meta.0x80404  get value for meta.0x80404 key
[0x00400080]> ks linux-x86-64
[sdb]> as
^D
[0x00400080]> k syscall/**
Cant find namespace syscall

**Comment by radare** [comment]
pls test again

**Comment by radare** [comment]
please confirm and for k use `k syscall/*` i added tests

**Comment by Susanne588586** [comment]
didn't work with 4e4ed9fd20275107a1544417c4b8211a10b691ec

**Comment by Susanne588586** [comment]
will test on different machine or I do a less on unistdh*

**Comment by radare** [comment]
why you close if you say that its not working?

**Comment by Susanne588586** [comment]
I got some rootkit on this machine, so I cannot screw radare2
