### ISSUE TITLE
Flags are not resolved for addresses below 0x100

### ISSUE THREAD

**Issue by astuder** [radare/radare2#7775]
Flags are not resolved in disassembly for jumps pointing at addresses below 0x100. This is reproducible for architectures 8051 and x86.

8051:
```
$ r2 -a 8051 malloc://10000
[0x00000000]> wx 0200a00201a0
[0x00000000]> f sym.short = 0x0a0
[0x00000000]> f sym.longer = 0x1a0
[0x00000000]> f
0x000000a0 0 sym.short
0x000001a0 0 sym.longer
[0x00000000]> pd 2
        ┌─< 0x00000000      0200a0         ljmp 0x00a0
       ┌──< 0x00000003      0201a0         ljmp sym.longer
[0x00000000]> wx 0201000201a0
[0x00000000]> f sym.short = 0x100
[0x00000000]> pd 2
        ┌─< 0x00000000      020100         ljmp sym.short
       ┌──< 0x00000003      0201a0         ljmp sym.longer
[0x00000000]>
```

x86:
```
$ r2 -a x86 malloc://10000
[0x00000000]> wx eaa00000000000eaa001000000
[0x00000000]> pd 2
        ┌─< 0x00000000      eaa000000000.  ljmp 0:0xa0
       ┌──< 0x00000007      eaa001000000.  ljmp 0:0x1a0
[0x00000000]> f sym.short = 0x0a0
[0x00000000]> f sym.longer = 0x1a0
[0x00000000]> f
0x000000a0 0 sym.short
0x000001a0 0 sym.longer
[0x00000000]> pd 2
        ┌─< 0x00000000      eaa000000000.  ljmp 0:0xa0
       ┌──< 0x00000007      eaa001000000.  ljmp 0:sym.longer
[0x00000000]> wx ea000100000000eaa001000000
[0x00000000]> f sym.short = 0x100
[0x00000000]> pd 2
        ┌─< 0x00000000      ea0001000000.  ljmp 0:sym.short
       ┌──< 0x00000007      eaa001000000.  ljmp 0:sym.longer
[0x00000000]>
```

**Comment by XVilka** [comment]
Please make & send tests for radare2-regressions.

**Comment by astuder** [comment]
Any suggestions where that test should go?

Adding to this script?
https://github.com/radare/radare2-regressions/blob/master/t/cmd_flags

Or creating a new file in here?
https://github.com/radare/radare2-regressions/tree/master/t.anal/others_anal

**Comment by radare** [comment]
This is in purpose to avoid false positives in many flags that point to 0 and such. We may improve that and im open to suggestions that dont mess the whole disasm into something useless

**Comment by astuder** [comment]
Unless radare has issues distinguishing between pointers and immediate values, I can't think of a scenario where this would lead to a mess. The only exception might be null pointers. 

I noticed ASCII characters pointers to 1-byte addresses in the comments. Is that related to this issue? (0x55 is an address, not a value)

```
[0x0000a2a1]> pd 1
            0x0000a2a1      f555           mov 0x55, a                 ; [0x55:1]=0 ; 'U'
[0x0000a2a1]> ao 1
address: 0xa2a1
opcode: mov 0x55, a
mnemonic: mov
prefix: 0
id: 0
bytes: f555
ptr: 0x00000055
refptr: 1
size: 2
type: mov
esil: A,0x10000,85,+,=[1],
stack: null
family: cpu

```

**Comment by radare** [comment]
well, sometimes immediats are used as addresses and viceversa. there’s no clean line to determine when 0x100 is just a number or it will be used as a pointer later in the code. thats’ why imm, ptr, … are a bit fuzzy sometimes

**Comment by XVilka** [comment]
@radare @astuder it's a VERY complex problem, nobody solved it yet for 100% correctness. You can check "Ramblr" paper for an example of modern developments in this area.

**Comment by astuder** [comment]
@radare I see your point that an immediate can later be used as a pointer. But I think there's room for improvement for explicit use of pointers.

In the first example above (ljmp) we are very confident that it's a pointer based on the op code. At least for the disassembly, resolving the flag name should be safe. Similarly, in the second example (mov direct, a), the opcode makes it clear that we are talking about an address and not an ASCII character. 

With my limited exposure to the internals of radare2, I'm certain to underestimate complexity.

The RAnalOp data structure seems to be the starting point. IMO it needs more comments or documentation as it's currently a bit of a guessing game to know what to put where to pass all available information to the analyzer. 

@XVilka thanks for pointing out the Ramblr paper. I saved it for some bed time reading.

**Comment by radare** [comment]
if you want i can make libr/parse/parse.c:215 configurable with an eval variable, and you can change it to a lower value if you want. this may help us experiment a bit before deciding where to go

**Comment by radare** [comment]
Done with asm.minvalsub

**Comment by radare** [comment]
3e7c01e5e400e981afb42a9599cff7d183a9dea5

**Comment by astuder** [comment]
Thanks!

This works fine for jumps and pointers, but as predicted, it makes quite a mess out of immediate values used in regular operations.

```
0x0000a161      7872           mov r0, #fcn.00000072      ; 'r' 
0x0000a163      e2             movx a, @r0
0x0000a164      54f0           anl a, #fcn.000000f0
0x0000a166      c4             swap a
0x0000a167      540f           anl a, #0x0f
0x0000a169      f56a           mov 0x6a, a                ; [0x6a:1]=2 ; 'j'
```

But now that I saw your commits, I will try to add a variable to separately control substitution for val and ptr/jump.
