### ISSUE TITLE
license conflicts in hexagon disassembler plugin

### ISSUE THREAD

**Issue by lowlyw** [radare/radare2#7778]
in `asm_hexagon_gnu.c`

we see `/* radare - LGPL - Copyright 2017 - pancake */`

but later in the file

```
RAsmPlugin r_asm_plugin_hexagon_gnu = {
    .name = "hexagon",
    .arch = "hexagon",
    .bits = 32,
    .endian = R_SYS_ENDIAN_BIG | R_SYS_ENDIAN_LITTLE,
    .license = "GPL3",
    .desc = "Qualcomm DSPv5",
    .disassemble = &disassemble,
};
```

what is it gpl or lgpl?

i think it's gpl, but...

**Comment by radare** [comment]
Binutils is gpl. So its gpl. Theres no conflict because theres a plugins.nogpl.cfg if you care about license issues when packaging
