### ISSUE TITLE
Unable to compile under msys2

### ISSUE THREAD

**Issue by draikes30** [radare/radare2#7781]
I am following the instructions at:
https://radare.gitbooks.io/radare2book/content/introduction/windows_compilation.html

to compile radare2 under msys2.
I installed all thenecessary packages etc, but when I get to the point where I run:
$ ./configure --with-ostype=windows ; make ; make win32dist
I run into issues.
1. The configure step works fine.
2. When I run make, I get the following error:

make -C shlr/zip
make[1]: Entering directory '/home/draikes/git/radare2/shlr/zip'
make -C zlib
make[2]: Entering directory '/home/draikes/git/radare2/shlr/zip/zlib'
gcc   -MD   -fPIC -g -Wall -D__WINDOWS__=1 -fPIC -Wall -I../../libr/include -I../include/   -shared -shared -fPIC -o libr_z.dll adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o
gzlib.o: In function `gz_open':
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:244: undefined reference to `_wopen'
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:244:(.text+0x3e0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_wopen'
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:257: undefined reference to `_lseeki64'
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:257:(.text+0x46f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_lseeki64'
gzlib.o: In function `gzrewind':
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:356: undefined reference to `_lseeki64'
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:356:(.text+0x68e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_lseeki64'
gzlib.o: In function `gzseek64':
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:397: undefined reference to `_lseeki64'
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:397:(.text+0x7d9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_lseeki64'
gzlib.o: In function `gzoffset64':
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:493: undefined reference to `_lseeki64'
/home/draikes/git/radare2/shlr/zip/zlib/gzlib.c:493:(.text+0xa93): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_lseeki64'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:70: libr_z.dll] Error 1
make[2]: Leaving directory '/home/draikes/git/radare2/shlr/zip/zlib'
make[1]: *** [Makefile:28: zlib/libr_z.lib] Error 2
make[1]: Leaving directory '/home/draikes/git/radare2/shlr/zip'
make: *** [Makefile:50: all] Error 2

3. There doesn't appear to be a make target for w32dist.

[configure.txt](https://github.com/radare/radare2/files/1086082/configure.txt)
[make.txt](https://github.com/radare/radare2/files/1086083/make.txt)

configure.txt and make.txt are the configure  and make logs respectively.

Host system windows 7 64-bit msys2 as of 06/16/2017.

**Comment by draikes30** [comment]
gcc version 6.3.0
make version 4.2.1
ld version 2.28
git version 2.13.0 (from msys2).

**Comment by XVilka** [comment]
@xarkes FYI.

**Comment by draikes30** [comment]
After reinstalling msys2, and adding the following packages:
$ pacman -S mingw-w64-x86_64-toolchain base-devel git zip make mingw-w64-x86_64-cmake

I ran the following commands to clone and build radare2:
$ git clone https://github.com/radare/radare2.git && \
cd radare2 && \
./configure --with-ostype=windows && \
make && \
make win32dist 

I then added $HOME/radare2/radare2-w32-1.6.0-git to my path and all seems to be working fine now.

The original problem seems to have been resolved by installation of the base-devel and zip packages to my msys2 installation so perhaps just the docs need to be updated.
