### ISSUE TITLE
rasm2 seems to handle 'lea' instruction wrong on x64

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [radare/radare2#7788]
When I make some tests for ragg2, I found that the binary generated by ragg2 always causes segment fault. After a little digging, I found the problem caused by asm library. The problem could be trigger by following command.

First, I asm the 'lea' instruction:
```
$ rasm2 -a x86 -b 64 "lea rax, [rbp+24h]"
8d4524
```

The, I disasm the code generated by the last commond:
```
$ rasm2 -a x86 -b 64 -D "8d4524"
0x00000000   3                   8d4524  lea eax, [rbp + 0x24]
```

Pay the attention on the dst reg: __rax__ and __eax__. This is where goes wrong.

I'm reading the source code to fix the problem, but if any one else who is familiar with asm library will fix it efficiently.

**Comment by radare** [comment]
@Svenito may fix it, and i think the fix it should ijply just add the 64bit prefix to the instruction. meanwhile you can use keystone or any other assembler for x86 if the default x86.nz doesnt works, but the fix should be easy

thanks for reporting

**Comment by Svenito** [comment]
I'll get on this today

**Comment by Svenito** [comment]
Can you let me know what version of r2 you are using? I am testing this and am getting the right result

    $ rasm2 -a x86 -b 64 "lea rax, [rbp+24h]"
    488d4524

    $ rasm2 -a x86 -b 64 -D "488d4524" 
    0x00000000   4                 488d4524  lea rax, [rbp + 0x24]
     
    $ r2 -v
    radare2 1.6.0-git 15129 @ linux-x86-64 git.1.5.0-167-gab77303
    commit: ab77303b322d26e08a791a8935faa48c88aab73e build: 2017-06-21__09:17:15
