### ISSUE TITLE
Enhancement of Visual Mode (Split View)

### ISSUE THREAD

**Issue by Shaddy** [radare/radare2#7805]
I would suggest to improve it by giving r2 the ability to create split views, similar to any other console/graphical tools such like VIM, Sublime Text, etc. and having the possibility to describe which content will be into the panel and if it will be synced with another or not.

As an example, the ability to have one view of entropy-per-block (p=e) and his correspondent disassembly/hex view/etc.

I did a crappy composition of how would it look :D.

<img width="729" alt="split_view_example" src="https://user-images.githubusercontent.com/247221/27441010-8e340072-576c-11e7-8ac2-cad98711784d.png">

**Comment by XVilka** [comment]
There is already possibility, but need to be enhanced, imho, for easier creating such kind of views.

**Comment by Shaddy** [comment]
Are you referring to view panels mode? The "bang" command I mean.

**Comment by radare** [comment]
done in master, please close if it fits your needs.

**Comment by Shaddy** [comment]
I've tested it in OSX and in Windows (under Linux subsystem). 

In first one, it seems that is working but I would not say it is in all scenarios, sometimes seems to get desynced and in my case, only prints half of the screen. Could be possible because of my window dimensions (I have to test it in different sizes)

In Linux subsystem under windows it works, but at some point starts to ask like if there were a lot of lines to print. I'm aware that r2 is not fully tested at that environment so I would not consider it important.

But, in my opinion it still has some tiny bugs, so we can close this enhancement (since the task is done) but I would start to create new issues related to it.

What do you guys prefer?

**Comment by Maijin** [comment]
create another issue (one) listing the needs using * [ ]
