### ISSUE TITLE
ragg2 faults when executing source :)

### ISSUE THREAD

**Issue by VisualPrankDude** [radare/radare2#7813]
```
,ragg2 -x mkdir.c
WARNING: No room in the static stackframe! (0 must be 11)
Segmentation fault
,ulimit -c 100000
,ulimit -f 100000
,ragg2 -x mkdir.c
WARNING: No room in the static stackframe! (0 must be 11)
Segmentation fault (core dumped)
,gdb -q ragg2 core 
Sat Jun 24 12:25:26 CEST 2017
Reading symbols from ragg2...done.
[New LWP 1971]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `ragg2 -x mkdir.c'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000564c4194efff in ?? ()
(gdb) bt
#0  0x0000564c4194efff in ?? ()
#1  0x0000564c4194f005 in ?? ()
#2  0x00007f45413a7bd7 in r_sys_run (buf=0x564c4194df10 "\350\372\377\377\377h\200\001", len=79) at sys.c:804
#3  0x00007f454197af76 in r_egg_run (egg=0x564c41934010) at egg.c:338
#4  0x0000564c40c81bbb in main (argc=3, argv=0x7fffbce1af38) at ragg2.c:461
(gdb) i r
rax            0x0      0
rbx            0x0      0
rcx            0x7f45410989c7   139935420615111
rdx            0x564c4194f000   94885517783040
rsi            0x1000   4096
rdi            0x564c4194f000   94885517783040
rbp            0x7fffbce1a8e0   0x7fffbce1a8e0
rsp            0x7fffbce1a890   0x7fffbce1a890
r8             0x564c4194d400   94885517775872
r9             0x0      0
r10            0x47e    1150
r11            0x202    514
r12            0x564c40c80750   94885504354128
r13            0x7fffbce1af30   140736362295088
r14            0x0      0
r15            0x0      0
rip            0x564c4194efff   0x564c4194efff
eflags         0x10213  [ CF AF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
```

**Comment by radare** [comment]
thats obvious and expected.,ragg2 doesnt segfaults, it segfaults the program you are running

**Comment by VisualPrankDude** [comment]
@radare @pancake here is a couple of programs all crashing ragg2, according to dmesg:

 191.527118] ragg2[975]: segfault at 559377d48fff ip 0000559377d48fff sp 00007ffe3258ef20 error 15
[  191.541869] ragg2[979]: segfault at 0 ip 00007fbe9eb769c3 sp 00007ffcece1c938 error 4 in libc-2.21.so[7fbe9eaed000+1c0000]
[  191.545396] ragg2[980]: segfault at 0 ip 00007f7e6af7b14d sp 00007ffc649e05e8 error 4 in libc-2.21.so[7f7e6aed2000+1c0000]
[  191.552208] ragg2[982]: segfault at 0 ip 00007f0cac03114d sp 00007fff4532aad8 error 4 in libc-2.21.so[7f0cabf88000+1c0000]
[  191.562125] ragg2[985]: segfault at 0 ip 00007ff0cf9669c3 sp 00007ffc8d601b38 error 4 in libc-2.21.so[7ff0cf8dd000+1c0000]
[  191.565403] ragg2[986]: segfault at 0 ip 00007f8b60ae69c3 sp 00007ffee0f405a8 error 4 in libc-2.21.so[7f8b60a5d000+1c0000]
[  191.568707] ragg2[987]: segfault at 0 ip 00007f20df1439c3 sp 00007ffc9cf60278 error 4 in libc-2.21.so[7f20df0ba000+1c0000]
[  191.571928] ragg2[988]: segfault at 0 ip 00007fb4313e39c3 sp 00007fff22190738 error 4 in libc-2.21.so[7fb43135a000+1c0000]
[  191.575313] ragg2[989]: segfault at 5595ad3fefff ip 00005595ad3fefff sp 00007ffcacd034a0 error 15
[  191.604120] ragg2[998]: segfault at 0 ip 00007f6d7fc0614d sp 00007ffd3c5064b8 error 4 in libc-2.21.so[7f6d7fb5d000+1c0000]

**Comment by VisualPrankDude** [comment]
```
diff --git a/libr/egg/egg_lang.c b/libr/egg/egg_lang.c
index 4bf9844..e4b6b90 100644
--- a/libr/egg/egg_lang.c
+++ b/libr/egg/egg_lang.c
@@ -626,9 +626,10 @@ R_API char *r_egg_mkvar(REgg *egg, char *out, const char *_str, int delta) {
                /* TODO: check for room in stackfixed area */
                str++;
                len = strlen (str) - 1;
-               if (!stackfixed || stackfixed < len) {
-                       eprintf ("WARNING: No room in the static stackframe! (%d must be %d)\n",
+               if (!stackfixed || stackfixed <= len) {
+                       eprintf ("ERROR: No room in the static stackframe! (%d must be %d)\n",
                                stackfixed, len);
+                        exit(0);
                }
                str[len] = '\0';
                snprintf (foo, sizeof (foo) - 1, ".fix%d", nargs * 16); /* XXX FIX DELTA !!!1 */

```

**Comment by radare** [comment]
this is a warning because ragg2 doesnt forces you to not doing stupid things because its suposed to be a high level for assembly language.. and -x implies mapping the bin in memory and executing it, so it obviously crashes
