### ISSUE TITLE
Breakpoints doesn't work in arm32.

### ISSUE THREAD

**Issue by SajjadPourali** [radare/radare2#7820]
<img width="600" alt="screen shot 2017-06-25 at 22 53 52" src="https://user-images.githubusercontent.com/20374762/27518610-329dde74-59f9-11e7-92a6-dabbbdaf8471.png">
it's not related to raspberry.

**Comment by radare** [comment]
You have to unset the breakpoint to continue after the first stop

You can use dcu entry0 to put temporary breakpoints

**Comment by radare** [comment]
But maybe it doesnt works either. Please check

**Comment by SajjadPourali** [comment]
Totally breakpoints doesn't work.
in root-me servers radare2-git is installed by default, and i did try it on their servers too, the problem was there too.
<img width="520" alt="screen shot 2017-06-26 at 02 27 46" src="https://user-images.githubusercontent.com/20374762/27520077-5ce50f36-5a17-11e7-9660-5d00f926c923.png">

**Comment by radare** [comment]
yeah seems like a regression. but anyway i would never do -AA with debuger because that enables the emulation layer and initializes a false stack that may break the behaviour, and usually nobody needs to analyze the whole binary when debugging

**Comment by SajjadPourali** [comment]
I did try it without -AA and it's not related to this argument.
I was trying to finding when regression is happened, radare2-0.9.6 also has this problem (i didn't check older version).
<img width="363" alt="screen shot 2017-06-26 at 18 08 41" src="https://user-images.githubusercontent.com/20374762/27542146-9ad4f836-5a9b-11e7-808a-98ad9ba302e0.png">

**Comment by radare** [comment]
0.9.6 is 5 or 6 years old. And its probably the worst version to compare with. Nah just checking the source should be enough to find the bug and fix. But i have no arm32 hw here. If anyone can check it will be nice

**Comment by roboman2444** [comment]
I think this bug still exists... Breakpoints do not work for me on arm32 with radare2.
Tested on alarm 2.6 release and also latest git (as of a few hours ago). Same behavior on both.

GDB correctly does breakpoints, however.


I am doing some fiddling with libr/debug/p/debug_native.c, so if you want me to make any changes to test it, let me know. 


Hardware breakpoints aren't a viable workaround, because they are not supported yet.


```
:~$ r2 -version
radare2 2.7.0-git 18271 @ linux-arm-32 git.2.6.0-109-g62eff87ce
commit: 62eff87ce70a0dac48857d6e62f68699d790de1a build: 2018-05-31__23:39:32
```


and here is a little demonstration
```
:~/secconctf$ r2 -d ./test -A
Process with PID 6431 started...
= attach 6431 6431
bin.baddr 0xb6f6c000
Using 0xb6f6c000
asm.bits 32
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[aav: from 0xb6f3a000 to 0xb6f5a000
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
= attach 6431 6431
6431
 -- nothing personal, just bitness
[0xb6f3ab80]> db sym.main
[0xb6f3ab80]> db
0xb6f6c578 - 0xb6f6c57c 4 --x sw break enabled cmd="" cond="" name="sym.main" module="/home/roboman2444/secconctf/test"
[0xb6f3ab80]> pdf @ sym.main
            ;-- main:
            ;-- $a:
/ (fcn) sym.main 32
|   sym.main ();
|           0xb6f6c578 b    00482de9       push {fp, lr}
|           0xb6f6c57c      04b08de2       add fp, sp, 4
|           0xb6f6c580      10309fe5       ldr r3, loc._d_14           ; [0xb6f6c598:4]=132
|           0xb6f6c584      03308fe0       add r3, pc, r3
|           0xb6f6c588      0300a0e1       mov r0, r3
|           0xb6f6c58c      8effffeb       bl sym.imp.puts             ; int puts(const char *s)
|           0xb6f6c590      00f020e3       nop
\           0xb6f6c594      0088bde8       pop {fp, pc}
[0xb6f3ab80]> dc
You arent supposed to see this
child stopped with signal 11
[+] SIGNAL 11 errno=0 addr=0xffffffffbeb69574 code=2 ret=0
[0xbeb69574]> 
```


with the test program being compiled with gcc -g test.c -o test
```c
#include <stdio.h>
void main(void){
	printf("You arent supposed to see this\n");
}
```

**Comment by Maijin** [comment]
Please reopen an issue and use the template provided. this is unrelated to the first issue
