### ISSUE TITLE
wrong base address calculated in debug mode (PIE file)

### ISSUE THREAD

**Issue by danitorregrosa** [radare/radare2#7851]
Hi!

I am trying to debug with radare2 the following google-ctf-2017's [binary](https://gitlab.binarystud.io/TobalJackson/googleCTF_06-2017/raw/1903b53fb0a224ce824eba7b03fa6f37288b1e70/pwn_inst-prof/inst_prof.bak) (ELF, x86-64, PIE).

I am running it inside a VM generated from zardus's ctf-tools' [Vagrantfile](https://raw.githubusercontent.com/zardus/ctf-tools/master/Vagrantfile), ubuntu 14.04.5 LTS with ASLR activated.

The disassembled main function shows different in "normal mode" (it shows the correct function) and in "debug mode" (it shows incorrect one), due to an error with the base address calculation.

```
$ r2 inst_prof
[0x000008c9]> pd 20 @main
            ;-- main:
            ;-- section_end..plt:
            ;-- section..text:
            ;-- main:
            0x00000860      55             push rbp                    ; section 13 va=0x00000860 pa=0x00000860 sz=882 vsz=882 rwx=--r-x .text
            0x00000861      488d357c0300.  lea rsi, str.initializing_prof... ; 0xbe4 ; "initializing prof..."
            0x00000868      ba14000000     mov edx, 0x14
            0x0000086d      bf01000000     mov edi, 1
            0x00000872      4889e5         mov rbp, rsp
            0x00000875      e836ffffff     call sym.imp.write
            0x0000087a      4883f814       cmp rax, 0x14
            ....


$ r2 -d inst_prof
Process with PID 26470 started...
= attach 26470 26470
bin.baddr 0x7f827f200000
Using 0x7f827f200000
Assuming filepath /home/vagrant/inst_prof
asm.bits 64
 -- 255 shades of (truecolor) grey
[0x7f827f201260]> pd 20 @main
            ;-- main:
            ;-- section_end..plt:
            ;-- section..text:
            ;-- main:
            0x7f827f200860      0400           add al, 0               ; section 13 va=0x7f827f200860 pa=0x00000860 sz=882 vsz=882 rwx=--r-x .text
            0x7f827f200862      0200           add al, byte [rax]
            0x7f827f200864      1469           adc al, 0x69
            0x7f827f200866      690d14000000.  imul ecx, dword [0x7f827f200884], 0x24
        ,=< 0x7f827f200870      7c01           jl 0x7f827f200873
           ....
```

It uses the base address of the loader, instead of the binary's one. Check the bin.baddr value above with this one:
```
[0x7f827f201260]> dmm
0x7f827f200000 /lib/x86_64-linux-gnu/ld-2.19.so
0x7f827f425000 /home/vagrant/inst_prof
```

I have follow the problem to the following functions:
  `r_file_abspath`, at `libr/util/file.c`
  `r_debug_get_baddr`, at `libr/debug/debug.c`
  
`r_debug_get_baddr` compares the output of `r_file_abspath(file)` to the different `map->name` values in a loop, in order to asign the base address.
`file` has the `"dbg://"` prepended, and `r_file_abspath(file)` returns also a value with `"dbg://"` prepended, failing the `map->name` try. Then it goes to "fallback resolution", that is wrong in this case because the loader section is in lower addresses....

If I modify the `r_file_abspath function` to return a real path e.g.: "/home/vagrant/inst_prof" (without the `"dbg://"`, then it loads in debug mode with the correct base address, but I think this is not the correct patch and will break other things (there is an specific commit to allow r_file_abspath to return a "dbg://" like pattern strings).

**Comment by radare** [comment]
When loading a pie binary no base address is set by default so it puts everything at baddr 0. Use -B to select the one you want

**Comment by danitorregrosa** [comment]
What you say is what radare2 does in "not-debug mode".

But in "debug mode", it sets the base address to the one returned by `r_debug_get_baddr`. If I put an address with -B, in debug mode it ignores it.

If what you say is the intended behaviour also in debug mode:
* there must be a bug somewhere because it is not using baddr 0 in debug mode as it is logged in first post.
* how do I set an address with -B, if it is an ASLR environment and the real one changes in each execution?

Thank you

**Comment by radare** [comment]
in debug mode r2 cant decide the baddr. this is done by the system.

you cant change the base address during execution, wel you can , but its not recommended, so just use -B

**Comment by JP3BGY** [comment]
What @danitorregrosa  says is that when r2 opens a pie binary in debug mode the system returns wrong baddr so ```@main``` symbol doesn't point true main function's address, isn't it?

**Comment by radare** [comment]
that shouldnt happen, how to reproduce, which version of r2 are you using?

**Comment by danitorregrosa** [comment]
@JP3BGY : Yes. Thank you.

@radare: latest one from git. The info to reproduce it is in first post.

Look also at this log, please, trying to use "-B":
```
vagrant@ctf-tools:~$ radare2 -v
radare2 1.6.0-git 1 @ linux-x86-64 git.1.6.0-git
commit: e04b82059a92b59163ebd6ae4e62887af5edcfb3 build: 2017-07-03__14:49:06

vagrant@ctf-tools:~$ radare2 -d inst_prof -B 0x7f39872cb000
Process with PID 12165 started...
= attach 12165 12165
bin.baddr 0x7ff0009be000
Using 0x7ff0009be000
Assuming filepath /home/vagrant/inst_prof
asm.bits 64
 -- Deltify your life with radare2
[0x7ff0009bf260]> dmm
0x7ff0009be000 /lib/x86_64-linux-gnu/ld-2.19.so
0x7ff000be3000 /home/vagrant/inst_prof
```

**Comment by radare** [comment]
no. you cant use -d and -B at the same time, also if you use -d you cant pass more args to r2 because it expects the rest to be part of the command you are running itself. the magic of passing arguments in any random order is a gnuism that should be erradicated.

and the base address you get is 0x7ff0009be000, which is the one from ld, because it assumes the binary will be first map in the list. never seen that before. if you are in the mood check this file (libr/debug/debug.c line 1443) inside the R_API ut64 r_debug_get_baddr(RDebug *dbg, const char *file) { function to see how it tries to determine the base address of the program you are debugging.

is this happening because of vagrant?

**Comment by danitorregrosa** [comment]
> you cant use -d and -B at the same time
Ok. I did that because you said...

>  how it tries to determine the base address of the program you are debugging
I (tried to) explain all this in my first post: There is a loop in which it try to match this string `"dbg:///home/vagrant/inst_prof"` (returned from `r_file_abspath`) with the the ones from `map->name`, which in the correct one is `"/home/vagrant/inst_prof"`, and so it fails due to "dbg://", going to `fallback resolution`.

**Comment by danitorregrosa** [comment]
Hi!

I think this could be a patch for the issue.

We need `abspath` to be a real filesystem path in order to match with `map->addr`.
Both `file` and `r_file_abspath (file)` are URIs ("dbg://..."), so I think we should not use it there.


```
diff --git a/libr/debug/debug.c b/libr/debug/debug.c
index 70ec1b1..1facca1 100644
--- a/libr/debug/debug.c
+++ b/libr/debug/debug.c
@@ -1427,7 +1427,10 @@ R_API ut64 r_debug_get_baddr(RDebug *dbg, const char *file) {
        r_debug_select (dbg, pid, pid);
 #endif
        r_debug_map_sync (dbg);
-       abspath = r_file_abspath (file);
+       abspath = r_sys_pid_to_path (pid);
+       if (!abspath) {
+               abspath = r_file_abspath (file);
+       }
        if (!abspath) {
                abspath = strdup (file);
        }
```

What do you think?

**Comment by radare** [comment]
Looks like leaky to me. But it will be good to review in a pullreq
