### ISSUE TITLE
Cannot install iaito from r2pm

### ISSUE THREAD

**Issue by cskcsk** [radare/radare2#7873]
Hello, why I can't install `iaito` from `r2pm`  ?, here my output on terminal : 
<pre><code>$ r2pm -i iaito
Cannot find
$
</pre></code>

Thank's :)

**Comment by Maijin** [comment]
-> You need to use radare2 from git
-> You need to have r2pm package updated `r2pm update`

**Comment by XVilka** [comment]
Reopen if there will be any problems after that.
