### ISSUE TITLE
Automatic disassembly of all functions to json

### ISSUE THREAD

**Issue by Silberschleier** [radare/radare2#7876]
Is it possible to disassemble all functions at once to json?
Currently I use `s <fcn address>` followed by `pdfj` for each function, but this doesn't seem to be the ideal way.

Is this feature missing or am I missing something?

**Comment by SajjadPourali** [comment]
did you tried `pdaj` ?

**Comment by radare** [comment]
pda is to disasm all instructions (seeking byte per byte) nothing to do with that

**Comment by radare** [comment]
Use pdfj @@ fcn*

But those are separated jsons, aka jsonstrean. U can also use aflj to list all funcs. Mainly because gettng the disasm of all functions in a single json object is stupid (too big)

**Comment by Silberschleier** [comment]
Thanks. `pdfj @@ *` should work for me.
Also `aflj` wouldn't work for me as I need the opcodes for my use case.
