### ISSUE TITLE
Problem with function r_json_object_add() (at radare2/libr/util/r_json.c)

### ISSUE THREAD

**Issue by j123123** [radare/radare2#7881]
function ``r_json_object_add()``
https://github.com/radare/radare2/blob/aa8a5fdb30eef4b15c876fed3e9579727b1bbe7f/libr/util/r_json.c#L121-L147
it's possible that first realloc
````
v = (RJSVar**) realloc (object->object.a, len * sizeof (RJSVar*));
````

will be successful and second
````
c = (char**) realloc (object->object.n, len * sizeof (char*));
````
is not. Then this chunk of code
````
if (!c) {
	free (v);
	return;
}
````
will free memory chunk, on which `v` variable points. And `object->object.a` now invalid. Because:
1. object->object.a even not reassigned to the new pointer (after first `realloc ()` call) but doing `realloc ()` makes this pointer possibly invalid
2. even if you reassign i.e. do `object->object.a = v;` BEFORE doing stuff like
````
c = (char**) realloc (object->object.n, len * sizeof (char*));
if (!c) {
	free (v);
	free (object->object.n);
	object->object.a = NULL;
	object->object.n = NULL;
	return;
}
````
you will be in trouble because you don't have any mechanism in the place where ``r_json_object_add()`` is used to check situation when realloc inside it failed. See https://github.com/radare/radare2/blob/c506c8ebd7ebf1a1f0f05c96550eef3644e8e256/libr/util/r_pkcs7.c#L617-L618
````
r_json_object_add (obj, "Version", r_json_number_new (si->version + 1));
r_json_object_add (obj, "Issuer", r_x509_name_json (&si->issuerAndSerialNumber.issuer));
````

**Comment by radare** [comment]
can you send a pr fixing the issue instead of explaining how to fix it or how to reproduce it?

its much better to review and comment than in an issue.

thanks

**Comment by j123123** [comment]
I will try. I just don't know exactly how to fix it better.
