### ISSUE TITLE
Bug in PC-relative literals for Thumb2 / Cortex-M (wrong literal address in disassembly) 

### ISSUE THREAD

**Issue by Wolf-DL4YHF** [radare/radare2#7883]
Greetings all,
There may be a bug in Radare2 when disassembling certain Thumb2 LDR instructions that load a 32-bit constant via PC-relative offset. Since Github doesn't allow attachments here, a short test file to reproduce the bug is here:
http://www.qsl.net/dl4yhf/Radare2_bug/thumb2_literal_test.bin

For simplicity, the file is an excerpt from a larger firmware (~ 1 MByte) for an STM32F405 (ARM Cortex-M4, supports Thumb2 instructions but no ancient 32-bit ARM code). Code addess zero was originally somewhere else, but it doesn't matter here. The problematic LDR with PC-relative addressing is at offset 0x0008 in the small file linked above.

Load the file with Radare2 and disassemble the first few bytes:
 ( radare2 -a arm -b 16 thumb2_literal_test.bin )

[0x00000000]> pd
0x00000000      80b5           push {r7, lr}
0x00000002      c9b2           uxtb r1, r1
0x00000004      4ff49072       mov.w r2, 0x120
0x00000008      dff82838       ldr.w r3, [0x00000838]      ; [0x838:4]=0x2001e57c << wrong literal address, wrong literal value - details below.

The LDR.W instruction with PC-relative addressing of the literal (32-bit constant loaded into R3) shown by Radare2 is not correct. The correct address is the address of the instruction plus FOUR plus the PC-relative offset, bitwise ANDed with 0xFFFFFFFC for 32-bit word alignment (example further below).
In *most* but not all cases, the Thumb2 disassembly from Radare2 is ok, and I'm clueless about the reason (tried to understand the table-driven Capstone ARM disassembler but gave up due to a lack of time).

For comparison, the same code disassembled with objdump, which always gives a correct address for the literal but unfortunately doesn't show the literal (the 32-bit constant value) itself - which is one of the big pro's of Radare2, if only it worked properly.

To generate the disassembly with the "ARM-objdump", use a command like
  ?/gcc_arm/bin/arm-none-eabi-objdump -D -b binary -marm -Mforce-thumb --adjust-vma=0 thumb2_literal_test.bin

00000000 <.data>:
       0:       b580            push    {r7, lr}
       2:       b2c9            uxtb    r1, r1
       4:       f44f 7290       mov.w   r2, #288        ; 0x120
       8:       f8df 3828       ldr.w   r3, [pc, #2088] ; 0x834      ; <<< 0x834 = correct literal address

The 12-bit offset, contained in the 2nd 16-bit word of the LDR instruction, is 0x0828 = #2088 .
Note that unlike Radare2, objdump shows 16-bit hex values, highest significant digit first.

For Thumb2, the PC has been incremented by 4 (not 8 as for 32-bit ARM code) when the instruction
is executed. Furthermore, the sum (address) is aligned to 32-bit words.
In this case, the correct address of the literal would be:

Literal address = (0x00000008 + 4 + 0x0828 ) & 0xFFFFFFFC = 0x834 .
But Radare2 "thinks" the literal is at 0x838, which is wrong. It *would* be ok for 32-bit ARM instructions but not for 16-bit Thumb2. So maybe Radare2 doesn't always care for the "-b 16" passed through the command line ?

I'm not sure if this specific to Radare2 or a bug in Capstone (which I don't use).

Cheers,
 Wolf .

**Comment by radare** [comment]
I did a dirty fix in anal-arm, at least it may serve you as a guide, but if capstone gives us wrong information then the fix should be done in capstone, not r2 see the https://github.com/radare/radare2/pull/7884 for the PR

**Comment by radare** [comment]
> On 8 Jul 2017, at 23:19, Wolf-DL4YHF <notifications@github.com> wrote:
> 
> Greetings all,
> There may be a bug in Radare2 when disassembling certain Thumb2 LDR instructions that load a 32-bit constant via PC-relative offset. Since Github doesn't allow attachments here, a short test file to reproduce the bug is here:
> http://www.qsl.net/dl4yhf/Radare2_bug/thumb2_literal_test.bin <http://www.qsl.net/dl4yhf/Radare2_bug/thumb2_literal_test.bin>
> 
yep, github do supports attachments, just drag and drop,

> For simplicity, the file is an excerpt from a larger firmware (~ 1 MByte) for an STM32F405 (ARM Cortex-M4, supports Thumb2 instructions but no ancient 32-bit ARM code). Code addess zero was originally somewhere else, but it doesn't matter here. The problematic LDR with PC-relative addressing is at offset 0x0008 in the small file linked above.
> 
i see, there are a bunch of inconsistencies here:

arm.gnu:             0x00000008      dff82838       ldr.w r3,  [0x00000838] ; 0x00000834
arm.cs:             0x00000008      dff82838       ldr.w r3,  [0x00000838]     ; [0x838:4]=0x2001e57c

so, gnu disasm shows also wrong info, but the analysis that is done by hand (without using gnu or capstone code) works fine, this is the one that puts this 0x834 ref. i did the fix for arm.cs at anal level, not disasm. please fill an issue into capstone repo, and bear in mind that this code is used for thumb and arm32. and i dont think capstone have testsuite to handle this so i would also appreciate a test case, with maybe a hello world program referencing a string or so.

**Comment by Wolf-DL4YHF** [comment]
Thanks for looking into this so quickly.
When time permits, I will try my luck with Capstone (directly) and 
report the issue with the test file in their forum.
Suggest to close the issue since it's not a Radare2 fault.
Cheers,
    Wolf .

**Comment by radare** [comment]
You may probably want to report this to gnu binutils as long as it seems to be broken there too

**Comment by radare** [comment]
keep this issue open to track the problem, ill close the pr because is not a good patch, it was just a test to see what travis thought show the places where the issue

**Comment by radare** [comment]
ESIL and capstone doesnt match the output:

```
            0x00000008      dff82838       ldr.w r3, [0x00000838]      ; [0x834:4]=0x3ff30
```
see that 0x834 vs 0x838. didnt had time to chk on hw to see which dword is fetched

**Comment by radare** [comment]
so imho we should test this with real hw and close the issue, but lgtm

**Comment by Wolf-DL4YHF** [comment]
Thanks - in the meantime I abandoned any plan to work around this, since 
my target hardware "died" :(
Anyway it would be nice for future projects (that require 
reverse-engineering Cortex-M firmware) to have Radare2 properly decoding 
those literals. Anyway, not many users seem to stumble across this, so 
the problem doesn't seem to be very common.

Am 19.12.2017 um 15:32 schrieb radare:

**Comment by radare** [comment]
I’m sorry for your hardware :(

Yes, this thing really matters, and im happy that is now fixed because the way pc is used in thumb is kind of a mess and confusesany people.

Thanks for reporting!

**Comment by mrmacete** [comment]
<img width="819" alt="screen shot 2017-12-19 at 18 10 01" src="https://user-images.githubusercontent.com/4139069/34169517-f1a7f52e-e4e7-11e7-980f-0064e88ccc08.png">

it looks pretty good now
