### ISSUE TITLE
Support for EVM 

### ISSUE THREAD

**Issue by radare** [radare/radare2#7885]
the ethereum virtual machine.

* [x] complete disassembler
* [ ] analyzer
* [ ] emulation (esil)
* [ ] assembler

**Comment by radare** [comment]
assembler is half-done

**Comment by Maijin** [comment]
https://github.com/comaeio/porosity ?

**Comment by montekki** [comment]
Hi all. I am looking into implementing porosity-like decompiling for ethereum maybe with r2. So i will probably implement this. However, there are some questions like, what is the state of esil and how easy it would be to get a working decompiler. Also there is a need for implementing a debugger code that will connect to a local geth rpc. Let's talk this issues.

**Comment by XVilka** [comment]
@montekki - you can check the sources of https://github.com/radare/radeco-lib as an example of WIP decompiler on top of ESIL.

**Comment by montekki** [comment]
@XVilka interesting, care to add a readme.md? btw evm is stack-based so for example single instructions like jmp never contain a dst addr, rather there is a series like

```
push 0x6a
jump
```

Esil will compute these addrs i presume?
