### ISSUE TITLE
Add command to R_BETWEEN

### ISSUE THREAD

**Issue by radare** [radare/radare2#7892]
? 1 5 10
$? = 0

? 1 400 10
$? = 1

...

wiMaybue use ?b ? maybe we want to have other comamnds to do other similar comparisons

**Comment by kriw** [comment]
Could you elaborate this?

**Comment by radare** [comment]
add a subcommand of '?' that takes 3 numbers separated by spaces (process them with r_num_math) and return 0 or 1 depending if A < B  && B < C

**Comment by kriw** [comment]
Thank you, I'll implement it.
