### ISSUE TITLE
idp* (rabin2 -Pr) formatting issue + io

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#7895]
With some specific files, the command `idp*` might print symbols which contains '<' and '>'.
So if you want to load a pdb using `.idp* file.pdb` you might have some weird behaviour like random files creation, depending on your pdb.
Also there's an issue where the opening of the file fails one time in two. I think the issue won't be here after refactoring the code to use R_IO.

**Comment by radare** [comment]
feel free to document in doc/pdb

**Comment by radare** [comment]
and we need to merge siol too :{{

**Comment by Maijin** [comment]
Document ? This is bug of pdb stuff :(

**Comment by radare** [comment]
If its documented is not a bug :D

**Comment by Maijin** [comment]
idp* might print symbols which contains '<' and '>'. why would that be documented oO
