### ISSUE TITLE
Hi, these two lines does not exist in the repo

### ISSUE THREAD

**Issue by wenhuizhang** [radare/radare2#7903]
$ sys/python-deps.sh
$ sys/python.sh

**Comment by radare** [comment]
They are now available as r2pm packages

**Comment by Maijin** [comment]
Where did you find this ?

**Comment by wenhuizhang** [comment]
In doc folder , for installation on Mac

**Comment by wenhuizhang** [comment]
How could I install  r2pm package on mac please?

**Comment by radare** [comment]
r2pm comes with r2 , just install r2 and then r2pm -s python and then use -i to install what you want..

but the thing is.. what do you exactly want to do with r2 and python? because you’ll probably only need to pip install r2pipe

**Comment by wenhuizhang** [comment]
That makes sense to me, thanks I will go with pip then.

**Comment by Maijin** [comment]
Ok thanks i removed those lines from osx.md
