### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by wenhuizhang** [radare/radare2#7906]
```
$ r2 -v
dyld: Library not loaded: /usr/local/lib/libr_core.dylib
  Referenced from: /usr/local/bin/r2
  Reason: image not found
Abort trap: 6
```

However  /usr/local/lib/libr_core.dylib and /usr/local/bin/r2 exists

**Comment by radare** [comment]
Please use sys/install.sh or learn how linux works.

solutions to this are:
* edit ldconfig
* use rpath (see configure --help)

**Comment by wenhuizhang** [comment]
Sorry for bothering , however it is a Mac, I tried to find my dyld, however it is not with latest OS, wired

**Comment by radare** [comment]
did you used sys/install.sh ?

do you have more than one installation of r2 if so, use make purge to clean all previous r2 from the system

i use mac as main platform and works fine

**Comment by wenhuizhang** [comment]
Hi, I used sys/install.sh

**Comment by wenhuizhang** [comment]
Just tried sys/user.sh, and added the bin to  the PATH, now it works, wired , I tried with previous version as well with sudo, and got a dylib could not link problem

**Comment by wenhuizhang** [comment]
Thanks :) sys/user.sh works for me

**Comment by md-pepa** [comment]
wow I'm impressed at how helpful the radare team is! Maybe you could fork your Ninja skills and solve world hunger, or dissasemble your synthetic sweaters and produce an alternative to quantum string theory?

>Please use sys/install.sh or learn how linux works.

It still doesn't' work if you download straight from the website on a Mac, so maybe all those Linux skills could be used to fix it?! You have had 555 days to ensure your route to market is free of friction, and once users do get the above error, they are greeted with such a pleasant response!

**Comment by Maijin** [comment]
Indeed it's 555 days old and it's fixed, locking here. If you encounter an issue, feel free to open an issue following the bug report.
