### ISSUE TITLE
Infinite loop when stepping though the code and ExitProcess is called

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#7907]
I have an issue with latest (radare2-w32-1.6.0.zip taken from here http://bin.rada.re/) when I'm debugging the application that calls ExitProcess. When I am single-stepping and it's called r2 goes into an infinite loop and displays 

   > ==> Process finished
   > 
   > GetThreadContext: 5
   > GetThreadContext: 5
   > GetThreadContext: 5
   > GetThreadContext: 5
   > GetThreadContext: 5
   > GetThreadContext: 5
   > Error detected in r_debug_native_continue/ContinueDebugEvent: The parameter is incorrect.
   
And it continues displaying those line indefinitely. I can't get out of this infinite loop and need to restart the r2. The issue does not occur when I do not single-step and just run (`dc`) the application. 

I've discovered this on an  old [Tut01 from Lenas Reversing](https://tuts4you.com/download.php?view.122). To reproduce it one needs to start debugging (`doo`) put a breakpoint on 0x0040108b and press F9 to reach that. After that, 2x`S` (step over) and the issue is triggered. 

OS: Win10 64-bit

**Comment by XVilka** [comment]
@xarkes FYI.

**Comment by xarkes** [comment]
Confirmed, will investigate

**Comment by xarkes** [comment]
Fixed, you can close the issue
```
[0x7755748d]> dc
(1552) loading library at 0000000077250000 (C:\Windows\SysWOW64\imm32.dll) imm32.dll
hit breakpoint at: 40108b
[0x0040108b]> dso
(1552) Unknown exception 4000001e in thread 4400
(1552) loading library at 0000000071320000 (C:\Windows\SysWOW64\uxtheme.dll) uxtheme.dll
(1552) loading library at 0000000074B10000 (C:\Windows\SysWOW64\msctf.dll) msctf.dll
(1552) loading library at 00000000751E0000 (C:\Windows\SysWOW64\oleaut32.dll) oleaut32.dll
(1552) loading library at 00000000748E0000 (C:\Windows\SysWOW64\msvcp_win.dll) msvcp_win.dll
(1552) loading library at 0000000071070000 (C:\Windows\SysWOW64\dwmapi.dll) dwmapi.dll
(1552) loading library at 0000000075D80000 (C:\Windows\SysWOW64\ole32.dll) ole32.dll
hit breakpoint at: 401090
[0x0040108b]> dso
(1552) Unknown exception 4000001e in thread 4400
(1552) Finished thread 644 Exit code 1947165380
(1552) Finished thread 3820 Exit code 1947165380
(1552) Finished thread 5112 Exit code 1947165380
(1552) Process 1552 exited with exit code 1947165380

==> Process finished
```

**Comment by radare** [comment]
Thx
