### ISSUE TITLE
Inconsistent result using "wa" command

### ISSUE THREAD

**Issue by saeedinfact** [radare/radare2#7932]
I use "wa" from time to time for manipulate an instruction, recently i noticed an inconsistency in the behavior of "wa" command which is described below:

This file is an "ELF 32-bit LSB executable", i want to change "jmp 0x804816c" to "jmp 0x804815b", even though the it is a short jump and it is relative ([see here](https://c9x.me/x86/html/file_module_x86_id_147.html)) i simply do this:
```
s 0x08048154
pd 1 //result is jmp 0x804816c
wa jmp 0x0804815b
pd 1 //result is jmp 0x804815b
```
Here is a demonstration:
![screenshot from 2017-07-16 17-17-52](https://user-images.githubusercontent.com/7834153/28247691-c1025a6c-6a4a-11e7-9db3-e0720cef5384.png)

This file is a "compiled Java class data", i want to do the same thing with "ifne 0x0277" which is also a relative jump ([see here](https://en.wikipedia.org/wiki/Java_bytecode_instruction_listings)), when i want to change it to "ifne 0x026f" i try to do the same thing:
```
s 0x00000269
pd 1 //result is ifne 0x0277
wa ifne 0x0000026f
pd 1 //result is ifne 0x04d8
// ==> inconsistent
```
Here is a demonstration:
![screenshot from 2017-07-16 17-17-56](https://user-images.githubusercontent.com/7834153/28247690-c101c728-6a4a-11e7-8e9e-44ae0e719052.png)

As you may have seen in the second screen shot, in order to achieve the latter result i have to calculate the relative address like this:
```
wa ifne 0x0000026f-$$ 
pd 1 //result is ifne 0x026f
// ==> success
```

I think it a better choice to change the second behavior to match the first one, this way not only it is more consistent but it is more convenient.

**Comment by radare** [comment]
can you please add some tests into the radare2-regressions repo for this? thanks
```
$ rasm2 -a java -o 0x269 "ifne 0x26f"
9a0006
```

here's a oneliner to confirm the fix
