### ISSUE TITLE
r_debug_reg: error reading registers on aarch64 architecture

### ISSUE THREAD

**Issue by r1git** [radare/radare2#795]
Hi,

With an hello world exe statically compiled, launched under qemu 2.0:
```
$ qemu -g 1234 hello
$ radare2 -a arm gdb://localhost:1234
Cannot set bits 16 to 'bf'
r_debug_select: 6 6
r_debug_select: 9982304 6
r_debug_reg: error reading registers pid=9982304
r_debug_reg: error reading registers pid=9982304
 -- Manually modify the DRX registers of the child process with '!dr' command
r_debug_reg: error reading registers pid=9982304
[0000:0000]> dc
r_debug_reg: error reading registers pid=9982304
r_debug_reg: error reading registers pid=9982304

==> Process finished

r_debug_select: -1 -1
```

[hello.zip]( http://pastebin.com/uEsfqi4E )

**Comment by jvoisin** [comment]
Any news about this @r1git ?

**Comment by XVilka** [comment]
@r1git any chance to test it again?

**Comment by r1git** [comment]
Sure. I'll have some time to try it again in a couple of hour.
I'll come back to you.

**Comment by radare** [comment]
Iirc nobody did that so it should fail mainly because there's no arm64 reg profile defined and i have no arm64-linux hardware to test this. I can blindly fix this if u like

**Comment by r1git** [comment]
I actually don't have a arm64 linux either, I use qemu-aarch64 -g 1234 and connect to the gdbserver on port 1234.

And now it seems to work better !
```
$ r2 -a arm -D gdb gdb://localhost:1234
[0x00400af0]> pd 3
           ;-- pc:
           0x00400af0    1d0080d2       movz x29, 0
           0x00400af4    1e0080d2       movz x30, 0
           0x00400af8    fd030091       mov x29, sp
[0x00400af0]> dc

$ qemu-aarch64 -g 1234 hello
Hello Aarch64
```

**Comment by radare** [comment]
For loading it in r2 you should pass -b64 too. I'll copypasta the reg profile from qemu later after dinner.

But if you are using qemu, the ptrace syscall is not implemented in the qemu-aarch64 so u'll need a full qemu image to boot and run r2 from inside. I think best option is to use real hw.

**Comment by r1git** [comment]
Thank you pancake.
I have to admit, I solved my issues around arm64 with static analysis with r2 along with native gdb for dynamic analysis a while ago.
Couldn't have done it without r2 for the static part, so thanks again.

**Comment by radare** [comment]
I just commited support for arm64 esil emulation, needs more detailed expressions but should work more or less.

Feel free to send patches or report issues related to arm64-esil
