### ISSUE TITLE
Support high density QR codes

### ISSUE THREAD

**Issue by radare** [radare/radare2#7962]
https://twitter.com/qrs/status/887281622021787648

maybe using a config var.. and i would probably implement this in a separate function, or adding a new parameter to the qrcode_gen function

**Comment by radare** [comment]
Also support inverse QRcodes, just printing in white whats in black and viceversa

maybe as subcommands to pq

**Comment by XVilka** [comment]
This was done, right?

**Comment by Maijin** [comment]
yeah
