### ISSUE TITLE
Wrong offset when patching in visual cursor mode.

### ISSUE THREAD

**Issue by sasdf** [radare/radare2#7976]
Addresses are calculated relative to the top of current visual mode window, rather then the address where cursor is.

Steps to reproduce
```
aaaa
Vp
c
jjjjjj
A
call sym._init
```
Result
```
Write some x86-64 assembly...

5> call sym._init
* e80bf9ffff

|           0x004028b8      e80bf9ffff     call 0x4021c8               ;[1] ; sym._init+0x8
|           0x004028bd      89f3           mov ebx, esi
|           0x004028bf      4883ec38       sub rsp, 0x38               ; '8'
|           0x004028c3      488b3e         mov rdi, qword [rsi]        ; const void *ptr
```

**Comment by radare** [comment]
works for me , are you using last r2?

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by sasdf** [comment]
Almost the newest commit.
```
radare2 1.7.0-git 15364 @ linux-x86-64 git.1.6.0-83-gabe9e015f
commit: abe9e015fa051e21f67b58f67fd75ae968437833 build: 2017-07-20__22:46:29
```

**Comment by radare** [comment]
Aaah you mean the sym._init offset that is shifted? Ok will try again to see if i can reproduce
