### ISSUE TITLE
Differentiate user from system comments

### ISSUE THREAD

**Issue by radare** [radare/radare2#7982]
When adding a comment in CC we should be able to determine who created a specific comment in order to set it to be displayed at right or on top.

The asm.cmtright variable should be removed at some point imho what do you think?

we need more CC subcommands to change the location to display the comment.

the disasm loop should change the behaviour on each comment, so it should be possible to display comments on top at right in a single offset.

**Comment by Maijin** [comment]
You mean, instead of having a asm.cmtright user will have to manually specify everytime if he wants the comment to be on the right or on the top? Seems a bit tedious no?

**Comment by radare** [comment]
yes, may be tedious but i think user comments should be on top by default and comments from sections on top and analysis comments at right

**Comment by Maijin** [comment]
No clearly I hate comment on the top. Most people use comment on the right, having this would be a regression.

**Comment by XVilka** [comment]
Just mark them at different colours.

**Comment by XVilka** [comment]
Placing comments on the top decrease the density of the presented information at one screen...

**Comment by radare** [comment]
its more readable in some situations, but its a pain to have all the comments on top without option for having some in one place and others in the other.. another situation is showing more than one comment at right is less readable than showing it on top

**Comment by radare** [comment]
cc @kazarmy

**Comment by kazarmy** [comment]
`asm.cmtright = user,section,anal` (for example) with CC subcommands that can override? Lgtm. I certainly would like multi-line source code comments to be on top.

> When adding a comment in CC we should be able to determine who created a specific comment in order to set it to be displayed at right or on top.

Could also use multiple colors for this.

> the disasm loop should change the behaviour on each comment, so it should be possible to display comments on top at right in a single offset.

No idea what this means tbh.

**Comment by kazarmy** [comment]
I do know that some comments do not appear if `asm.cmtright = false` but appears if it's `true`, but there's way too little time to do everything.

**Comment by radare** [comment]
maybe we should add anal.comments to separate the ones introduced by the analysis and the ones introduced by the user, so we can put them at right/top and also specify a different color

**Comment by Maijin** [comment]
Fixed here https://github.com/radare/radare2/commit/18f51c34601e12f6d8705b4e75b6a65fb729880c
