### ISSUE TITLE
crash radare2-w32-1.6.0 on windows

### ISSUE THREAD

**Issue by HostageBrain** [radare/radare2#7986]
`> radare2.exe rabin2.exe`
It prints 

> Cannot find temporary directory 'C:\Users\Username\AppData\Local\Temp\'

 and crashes

**Comment by HostageBrain** [comment]
w64 works, but anyway prints 

> Cannot find temporary directory 'C:\Users\Username\AppData\Local\Temp'

**Comment by HostageBrain** [comment]
Crash reproduced on windows 8.1 & windows 10

**Comment by Maijin** [comment]
What about http://bin.rada.re/radare2-w32-1.7.0-git.zip

**Comment by radare** [comment]
Use the msvc build or the nightly ones

**Comment by Maijin** [comment]
For the temp issue it's known #7947

**Comment by Maijin** [comment]
Duplicate of #7947

**Comment by HostageBrain** [comment]
radare2-w32-1.7.0-git works fine

**Comment by Maijin** [comment]
ok

**Comment by radare** [comment]
i have replaced the zip for 1.6.0 so ppl downoading from the site will get the working zip at least, hopefully 1.7 will work out of the box
