### ISSUE TITLE
noreturn functions not working on windows binaries

### ISSUE THREAD

**Issue by radare** [radare/radare2#7989]
```
[0x00401cda]> tn
ExitProcess
```

* those are all the no-return functions for windows
* i guess this list should be longer :P
* and this ExitProcess should be catching this call sub.kernel32.ExitProcess....

![image 2017-07-21 18 22 28](https://user-images.githubusercontent.com/917142/28472614-8dea13ae-6e41-11e7-8f36-6ab294f53ef9.jpg)

**Comment by radare** [comment]
cc @xarkes

**Comment by Maijin** [comment]
Since the information is stored in sdb and no sdb is read it can't work -> https://github.com/radare/radare2/issues/7829

**Comment by radare** [comment]
the bug happens on linux too by just opening a windows binary, and there's a broken test already. so its completely unrelated to the sdb problem.

**Comment by radare** [comment]
And the reason why sdb doesnt works on windows is because sdb databases cant be generated with meson. Not because any weird bug ir so

Another solution wiuld be to just do a bat script to build them all in the release script. Sdb files arent required at compile time. Just at runtime and on windows we can load them from a relative path from the executables instead of a full path.

**Comment by Maijin** [comment]
Ah it's because it's probably an exact match instead of a contains

**Comment by radare** [comment]
Yep. Also the way imports are named in PE. That sub thing shouldnt happen imho, but as long as on windows uncan have more than one import pointing to the same ordinal we cant do fixed matching

**Comment by radare** [comment]
this should be easy to fix , anyone?

**Comment by radare** [comment]
moving for 2.2 until we have a test case for this. anyone?

**Comment by radare** [comment]
PING?

**Comment by kriw** [comment]
Could I work on this issue though someone is assigned,

**Comment by Maijin** [comment]
Yes no worries @kriw

**Comment by sivaramaaa** [comment]
@kriw  Yup it's ok u could work on it , i could wait for ur implementation , but this has to be done before the release
meanwhile i will be working on this issue : [r2 /bin/ls - wrong main detection](https://github.com/radare/radare2/issues/8824) @radare

**Comment by radare** [comment]
Ok!
