### ISSUE TITLE
incongruence in rasm2 with 16 bit address mov 

### ISSUE THREAD

**Issue by MaikSoriano** [radare/radare2#8007]
`rasm2 "mov [dx], 0xff"`
gives me :      **6602ff**

but if I write:
`rasm2 -d "6602ff"`
gives me:     **add bh, bh**

**Comment by XVilka** [comment]
It's a wrong instruction.

**Comment by MaikSoriano** [comment]
shouldn't wrong instructions return "invalid"?

**Comment by Svenito** [comment]
Yes, nz should return invalid. Will fix this
