### ISSUE TITLE
Avoid `strncpy (dst, src, sizeof (dst)-1);`

### ISSUE THREAD

**Issue by MaskRay** [radare/radare2#8025]
When the source and the destination have the same size, `strcncpy(dst, src, sizeof dst - 1);` copies up to `n-1` bytes from `src` to `dst` but does not NUL-terminate `dst`. If the length of `src` >= n-1, the old value of `dst[n-1]` will be kept. This is vulnerable if `dst[n-1]` is not NUL. The use cases of `strncpy` should always be followed by a NUL-terminating assignment, otherwise, I think it is even inferior to `strcpy`.

A casual search reveals there are numerous use cases of this pattern and many of them seem to be problematic.

As an alternative API to `strncpy`, Linux kernel `lib/string.c` provides `strscpy` which is preferred to either `strncpy` or `strlcpy`. See
https://lwn.net/Articles/659214/

```c
/**
 * strscpy - Copy a C-string into a sized buffer
 * @dest: Where to copy the string to
 * @src: Where to copy the string from
 * @count: Size of destination buffer
 *
 * Copy the string, or as much of it as fits, into the dest buffer.
 * The routine returns the number of characters copied (not including
 * the trailing NUL) or -E2BIG if the destination buffer wasn't big enough.
 * The behavior is undefined if the string buffers overlap.
 * The destination buffer is always NUL terminated, unless it's zero-sized.
 *
 * Preferred to strlcpy() since the API doesn't require reading memory
 * from the src string beyond the specified "count" bytes, and since
 * the return value is easier to error-check than strlcpy()'s.
 * In addition, the implementation is robust to the string changing out
 * from underneath it, unlike the current strlcpy() implementation.
 *
 * Preferred to strncpy() since it always returns a valid string, and
 * doesn't unnecessarily force the tail of the destination buffer to be
 * zeroed.  If the zeroing is desired, it's likely cleaner to use strscpy()
 * with an overflow test, then just memset() the tail of the dest buffer.
 */
```

**Comment by radare** [comment]
This is known an old. I ensure that its always null termnated or done on a null initialized buffer with calloc or so. I dont think we want an issue for that. There are over 9000 good recommendations and we dont want to have one issue for each page of the secure c coding guideliness book
