### ISSUE TITLE
r_anal_type_func_guess is very slow

### ISSUE THREAD

**Issue by karliss** [radare/radare2#8028]
r_anal_type_func_guess is currently using O(n^3)  algorithm for checking each substring  where n is length of string. This is very slow for c++ executables with a lot of long names. Checking all the substrings also causes plenty of false positives like pthread_something=read and operand_something=rand.

Checking only prefixes and suffixes reduce `aa` time for cmake from 30 to 3 minutes.  Only test broken by checking only prefixes and suffixes was "type-matching/Function definition (autorename)" because "sub.KERNEL32.dll_ExitProcess_850" has KERNEL32.dll_ and _850 added. I assume that both of them are added by radare. A long term solutions would be to properly distinguish between different type of data instead of throwing everything into single string. Simpler solution just to get anal_type_func_guess fast would be to try detecting module name and remove it. 

I guess that currently there aren't too many test cases checking quality of analysis so there might be other cases that have both some prefix and suffix added around function name. Any ideas of what could those be?

**Comment by karliss** [comment]
@XVilka what kind of test did you mean slowness or correct behavior?

**Comment by radare** [comment]
agree on that, the analysis was way faster some years ago. You are welcome to send a pr optimizing or enhancing this function.

thanks for pointing out

**Comment by karliss** [comment]
Slow analysis can be tested by downloading https://cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.tar.gz, extracting it and running `time radare2 -c "aa" -q ./cmake`. If no one knows other situations that require the current function behavior of checking all substrings I will assume that if tests pass it's no worse than before.
