### ISSUE TITLE
r2 OMF 16bit doesn't load text segment properly

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8030]
See the file from radare2-regressions - `bins/omf/hello_world`.
It doesn't load the actual data into the text section - just FFs.

**Comment by radare** [comment]
regression? can u add a test?

**Comment by XVilka** [comment]
I've fixed it in https://github.com/radare/radare2/pull/8027, will add test soon.

**Comment by radare** [comment]
awesome

**Comment by XVilka** [comment]
Added test in https://github.com/radare/radare2-regressions/commit/1bb87fb3504f18e46311ab0751758d9ed577cce6
