### ISSUE TITLE
save and restore project

### ISSUE THREAD

**Issue by Xarlan** [radare/radare2#8040]
Hello
The current version of radare2:
$ radare2 -v
_radare2 1.7.0-git 15383 @ linux-x86-64 git.1.6.0-113-gf1a1eef
commit: f1a1eef653facfebe45ec904b726902287db5865 build: 2017-07-24__21:09:35_

What I do:
$ radare2 -A <my_file>
 izz
 afl
 ...
 Ps <my_project>      // to save my comments; the rename of function
q (press "y" to save chages)

After that, to restore <my_project> I do:
$ radare2 <my_file> -p <my_projetc>
or
$ radare2 -p <my_project>

Few times <my_project> is loaded "Ok", but the next time, when I put the same command to restore project I see the next message:
_See afCl for available types
Unknown calling convention 'cdecl'
See afCl for available types
Unknown calling convention 'cdecl'
See afCl for available types
Unknown calling convention 'cdecl'
See afCl for available types
Unknown calling convention 'cdecl'
See afCl for available types_

And as a result - it is impossible to restore correct the <my_project>

Thank you.

**Comment by radare** [comment]
already answered this in the irc a week ago, dunno if it was you.

- getopt doesnt allows to pass arguments after the optarg list, so you cant do r2 myfile -p prj, you should do r2 -p prj myfile
- the other problem is that you dont need to specify the file again when you are loading the project. so r2 -p prj is enough

i have tested this here and works fine.

also there are tests in the testsuite that are all green, so my guess is that you are using r2 wrongly and we should add more checks to avoid reaching into those situations

**Comment by Maijin** [comment]
```
Unknown calling convention 'cdecl'
See afCl for available types
```

Quite sure this is an old version of r2.

Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by Xarlan** [comment]
Hello Maijin
the output of "r2 -v":
_radare2 1.7.0-git 15383 @ linux-x86-64 git.1.6.0-113-gf1a1eef
commit: f1a1eef653facfebe45ec904b726902287db5865 build: 2017-07-24__21:09:35_

Install radare2 from git

**Comment by Maijin** [comment]
Can you provide this file then? Drag and drop it on GitHub after archiving it
