### ISSUE TITLE
64 bits DLL no exports

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#8044]
It does not work with my local kernel32.dll (64 bits)
```
$ rabin2 -E ~/kernel32.dll
[Exports]

0 exports
```
I tried with a 32 bits dll that I downloaded:
```
$ rabin2 -E ./kernel32.dll
[Exports]
...
1573 exports
```

IDA can see the exports in both cases.

**Comment by radare** [comment]
dont pass args after filename


also you can do the same with rabin2 -E kernel32.dll and save a bunch of chars

**Comment by radare** [comment]
can u add a test? we probably miss such bin in r2r

**Comment by xarkes** [comment]
Cf. https://github.com/radare/radare2-regressions/pull/931

**Comment by radare** [comment]
cc @skuater can u have a look?

**Comment by skuater** [comment]
ok i take it in few hours

**Comment by skuater** [comment]
Ok i think now is fixed plz wait to this commit is merged and test it.
