### ISSUE TITLE
Implement rundll inside rarun2

### ISSUE THREAD

**Issue by radare** [radare/radare2#8045]
This is. use r_lib_dl_open and r_lib_dl_sym to open a lib, resolve a symbol and call it.

In order to pass arguments the code inside the "call" block of the libr/io/p/io_self.c  should be moved into r_util for reusability.

This can be later reused to implement library debugging support on linux, mac and windows in a generic way.

reference https://github.com/radare/radare2/pull/7973

**Comment by radare** [comment]
cc @xarkes

**Comment by XVilka** [comment]
But this bug already is part of META Windows https://github.com/radare/radare2/issues/1194

**Comment by radare** [comment]
the good part of this design is that having rundll inside rarun2 we will be able to debug libraries on non-windows platforms, so its not windows-specific

**Comment by xarkes** [comment]
See https://github.com/radare/radare2/pull/8066
