### ISSUE TITLE
[Bug] `VV<` and `VV>` do nothing

### ISSUE THREAD

**Issue by xelxebar** [radare/radare2#8063]
## Overview

From the help menu of graph mode, `VV?`, the commands `<` (show function callgraph) and `>` (show program callgraph) are listed but seem to have no effect. 

This seems to be part of the meta-issue #6967; however, it doesn't reference an explicit issue for this bug. Also, this potentially overlaps with #8062, given the help text for the `<` command.

**Comment by radare** [comment]
It was removed on purpose. See my previous reply. Use git log to find when and where

**Comment by xelxebar** [comment]
Okay. Thanks. In that case, it might make sense to remove the help information about those commands in `libr/core/graph.c`.

**Comment by radare** [comment]
Well we can compute an aprox time of the cost of rendering this and showing a warning with y/n options before doing so. And reenable that graph. Eventually we can render partial graphs or cut them at a specific amount of nodes and slowly render more in background. Shouldnt harm to do that in a thread

**Comment by xelxebar** [comment]
Asyncronously generating the graph would be great! I would imagine that it's reasonable to assume we can immediately show the entry node. Ideally, we'd then grow the trie on the fly as needed, like you're saying.

**Comment by radare** [comment]
Fixed
