### ISSUE TITLE
Implement recalloc

### ISSUE THREAD

**Issue by radare** [radare/radare2#8070]
we want a realloc that ensures no memleaks happen so, it should free the buffer before returning and also, should initialize the new allocated memory to 0

**Comment by lowlyw** [comment]
hmm, what's the purpose of this?
the `recalloc` would have to know the previous buffer size, which it cannot do.

**Comment by MaskRay** [comment]
@lowlyw `recalloc` knows the chunk size (which is larger than the buffer size) in many malloc implementations

glibc:
```c
((long*)p)[-1] & -sizeof(long)
```

The proper usage of `realloc`:
```c
+		void **new_a = realloc (vec->a, sizeof(void *) * new_capacity); \
 +		if (!new_a) { \
 +			return NULL; \
 +		} \
 +		vec->a = new_a; \
```

**Comment by MaskRay** [comment]
I believe many use cases `recalloc` can be replaced with a vector https://github.com/radare/radare2/pull/8205

**Comment by radare** [comment]
yeah, thats why it should be a struct containing more info than just a pointer.. unless we hold data at the begining of the allocated chunk. so its not a clean solution here. rvector may work here, but i would prefer to have a single struct and generic api instead of over 9000 macro generated code like generics do in c++ which is a complete mess and unmaintainable

**Comment by MaskRay** [comment]
You are against RVector_u{8,16,32,64} implemented by macros. I agree that macros are not easy to debug b/c you cannot step into the definition. However, in consideration of that each function is very simple, this may not be a big issue.

If you allow me to implement it, the bug can be closed.

**Comment by radare** [comment]
Not just this, they also break bindings. Because you cant refer a symbol to create a signature and clal it from swig/valabind/...

**Comment by MaskRay** [comment]
What about using some `#ifdef` and add function declarations to appease swig/valabind ?
