### ISSUE TITLE
rasm x64 bswap rax encodes bswap eax

### ISSUE THREAD

**Issue by BenGardiner** [radare/radare2#8095]
The rasm assembler produces the wrong assembly for `bswap rax`. Discovered during a debugging session with @JonathanBeverley on a binary that was confirmed to execute as expected with the `480fc8` encoding shown below.

```
$ rasm2 -a x86 -b 64 'bswap rax'
0fc8
$ rasm2 -a x86 -b 64 -d "$(rasm2 -a x86 -b 64 'bswap rax')"
bswap eax
$ rasm2 -a x86 -b 64 -d "480fc8"
bswap rax
$ r2 -v
radare2 1.7.0-git 15534 @ darwin-x86-64 git.1.6.0-211-gdcad60533
commit: dcad6053350724fecef962ba640b928b65c9b6e8 build: 2017-08-01__16:15:29
```

**Comment by Maijin** [comment]
Thanks for the patch!

Just so you aware:

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.

You can also use keystone (http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```

**Comment by BenGardiner** [comment]
It's our pleasure, Maijin. Thanks for the -L tip.

**Comment by Maijin** [comment]
You can also use e asm.arch=? ; similarly the list of IO is r2 -L / oL,  the list of file format is rabin2 -L and iL and list of debugger handler is dL

**Comment by radare** [comment]
Rasm x64 is nothing. Can u pls tell us which line are you using to assemble that instruction?

**Comment by Maijin** [comment]
? What are you talking about ???
