### ISSUE TITLE
Errata in uintmax_t malloc_strtoumax in /shlr/heap/include/r_jemalloc/internal/util.h

### ISSUE THREAD

**Issue by Goyo2600** [radare/radare2#8122]
line 101
uintmax_t	malloc_strtoumax(const char *restrict nptr, char **restrict endptr, int base);
to
uintmax_t	malloc_strtoumax(const char *restrict_nptr, char **restrict_endptr, int base);

**Comment by radare** [comment]
Click the pencil button in github and do a pullreq . But most of those includes will be removed

**Comment by rlaemmert** [comment]
removed the restrict keyword so ill close this issue
