### ISSUE TITLE
Incorrect FSF address

### ISSUE THREAD

**Issue by xambroz** [radare/radare2#8123]
Some of the files contain incorrect (old) address to FSF in the license terms:
radare2-1.6.0/libr/asm/arch/sh/gnu/sh-opc.h
radare2-1.6.0/libr/hash/md4.c
radare2-1.6.0/libr/asm/arch/tricore/gnu/tricore-dis.c
radare2-1.6.0/libr/asm/arch/hexagon/gnu/opcode/hexagon.h
radare2-1.6.0/libr/asm/arch/hexagon/gnu/hexagon-dis.c
radare2-1.6.0/libr/asm/arch/sh/gnu/sh-dis.c
radare2-1.6.0/libr/asm/arch/tricore/gnu/cpu-tricore.c
radare2-1.6.0/libr/asm/arch/hexagon/gnu/hexagon-opc.c
radare2-1.6.0/libr/asm/arch/tricore/gnu/tricore-opc.c
radare2-1.6.0/libr/asm/arch/include/opcode/tricore.h

Address contained:
- in majority cases it is:
Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
- once there is:
Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

Should be:
Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1335 USA

Best regards
Michal Ambroz

**Comment by radare** [comment]
is this license chance already in binutils code? i would rather update the whole file from last binutils than changing just the license line. but i think that some of them are already updated, so you may probably report that to all those forks of binutils and binutils itself

**Comment by radare** [comment]
send a pullreq instead of reporting that way, takes the same time in your side, gives you credit for the change and reduces our review time. thanks
