### ISSUE TITLE
Building failed with error: unknown type name ‘atomic_uint_least64_t’

### ISSUE THREAD

**Issue by A1phaZer0** [radare/radare2#8138]
>../../shlr/heap/include/r_jemalloc/internal/atomic.h:132:11: error: unknown type name ‘atomic_uint_least64_t’  

Got this message and finally "radare2/libr/../global.mk:41: recipe for target 'cmd.o' failed", when I tried sys/install.sh  
OS: UbuntuMate 16.04 i686
radare2: master branch  
gcc: 5.3.1  
Many thanks.

**Comment by radare** [comment]
please try again after git pull

**Comment by A1phaZer0** [comment]
Works like a charm.
