### ISSUE TITLE
Which internal disassembler library do rasm2 use?

### ISSUE THREAD

**Issue by mudongliang** [radare/radare2#8151]
After I scan the generated libraries in `/radare2/libr/asm/p`, I find there are several libraries that related to x86 disassembler, which one is the internal disassemble library that rasm2 use? 

```
./asm/p/asm_x86_nz.so
./asm/p/asm_x86_nasm.so
./asm/p/asm_x86_cs.so
./asm/p/asm_x86_udis.so
./asm/p/asm_x86_as.so
```

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently and is the default one.  

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```

**Comment by mudongliang** [comment]
Thanks for your quick answer.
The interface to change assembler/disassembler looks good.
You recommend keystone.
Do you mean it is a very good assembler/disassembler. I am looking for one assembler/disassembler library to use in my project to disassemble x86/x86-64 instructions.

**Comment by Maijin** [comment]
No, we don't recommend keystone, we say that if you have issue with x86.nz assembler you can try keystone.

You can easily use all those assembler via https://github.com/radare/radare2-r2pipe/tree/master/python/r2pipe or RASM http://radare.today/posts/rasm/

**Comment by Maijin** [comment]
also for disassembling, r2 also have several engines:

_dAe  16 32 64   x86         BSD     Capstone X86 disassembler
_dAe  16 32 64   x86.udis    BSD     udis86 x86-16,32,64
and
in r2pm:
x86bea     	 [r2-arch] X86 BeaEngine Disassembler
x86zyan     	 [r2-arch] X86 Zyan Disassembler

Not all of them behave the same, the advantage is that you can use radare2 as a level of abstraction to build your tool so you don't have to think about how to use them independantly
