### ISSUE TITLE
Debugging plugins?

### ISSUE THREAD

**Issue by spacepluk** [radare/radare2#8158]
First of all, thanks for this excellent tool!
I'm trying to debug a VST plugin which is basically a dynamic library that get's loaded at runtime by a host application.  

I start the debugger with the host application using `r2 -d my-vst-host` and then I load the VST plugin.  After that, I can see the plugin symbols using the dmm/dmi commands.  But from there I'm having some trouble navigating the plugin's binary to put breakpoints, etc.

For example, I can't seem to find a way to search for strings in the plugin, and the autocompletion doesn't include the stuff in the plugin.

Am I doing something wrong? or is this just a weird usecase?
Thanks!

**Comment by spacepluk** [comment]
Do you mean the output of `dmm`? I must be doing something wrong:

```
[0x7fa0ab23ee9d]> dmm~vstplugin
0x7fa07b6e8000 /home/spacepluk/.vst/vstplugin.so
[0x7fa0ab23ee9d]> .!rabin2 -B 7fa07b6e8000 -z /home/spacepluk/.vst/vstplugin.so
Enter assembler opcodes separated with ';':
```

**Comment by radare** [comment]
without the -r , the output of rabin2 are not r2 commands

**Comment by Maijin** [comment]
`.!rabin2 -r -B 7fa07b6e8000 -z /home/spacepluk/.vst/vstplugin.so`
