### ISSUE TITLE
Radare2 takes ages to build

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#816]
```
$ make clean
$ time ./sys/install.sh
[...]
./sys/install.sh  106.66s user 16.45s system 50% cpu 4:03.35 total
$
```
On a _Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz_ with 8Go of RAM.

**Comment by jvoisin** [comment]
Any news about removing GNU plugins?

```
$ make clean
$ time ./sys/install.sh
[...]
./sys/install.sh  139.30s user 20.93s system 274% cpu 58.396 total
$
```

**Comment by radare** [comment]
There are still several things to be done in capstone in order to replace gnu. Mips for example, the capstone disassembler still misses many instructions. For arm i have tested a bit, and seems better, but i still want them to be there for testing

**Comment by radare** [comment]
Also, gnu code is the least of the build time problems. Capstone and grub take way more time than all the gnu disaasemblers to build.

But capstone is the main reason of that. Feel free to use --with-syscapstone if u want to short some time
