### ISSUE TITLE
Recursive help fail

### ISSUE THREAD

**Issue by radare** [radare/radare2#8164]
```
[0x00000000]> w?*~ijn
| wop[DO] [arg]                 De Bruijn Patterns
[0x00000000]> wo?*~ijn
| wop[DO] [arg]                 De Bruijn Patterns
[0x00000000]> ?*~ijn
[0x00000000]>
```

**Comment by radare** [comment]
the thing is ?* doesnt works

**Comment by XVilka** [comment]
@MaskRay FYI

**Comment by MaskRay** [comment]
Do you mean the current ad-hoc parser should be reimplemented in a generalized manner (say recursive descent parser)?

**Comment by XVilka** [comment]
@MaskRay you meant for the commands at all? Yeah, it's one of the long wanted feature which no one was brave enough to start: https://github.com/radare/radare2/issues/7967

But this issue about just listing  all help for every command, that's it.

**Comment by radare** [comment]
the only problem is that ?* doesnt works. but it does for the rest of commands. and this is a regression

**Comment by Maijin** [comment]
ping @MaskRay can you fix this regression please?

**Comment by MaskRay** [comment]
Extended https://github.com/radare/radare2/pull/8474 to fix recursive help.
