### ISSUE TITLE
Add pz+ command to print std::string values

### ISSUE THREAD

**Issue by radare** [radare/radare2#8166]
https://codeshare.frida.re/@oleavr/read-std-string/

**Comment by Maijin** [comment]
@kazarmy

**Comment by kazarmy** [comment]
This depends very much on the data structure used for `std::string`, [which can apparently even change between different library versions and whether a macro is defined](https://stackoverflow.com/a/27631366/3622667).

**Comment by kazarmy** [comment]
There are endianness issues too. Oh my.

**Comment by oleavr** [comment]
@kazarmy That snippet is only meant to show the simplest possible implementation for one C++ standard library implementation on little-endian 32- and 64-bit systems. It wasn’t meant to be a generic implementation, that’s a lot more work. 😊

**Comment by Maijin** [comment]
Can be an initial work too for `pz+` @kazarmy , this can be extended later.

**Comment by kazarmy** [comment]
kk
