### ISSUE TITLE
r2 does not display syscall name and arguments

### ISSUE THREAD

**Issue by hummelchen** [radare/radare2#8181]
Gist with sample and source code:
https://gist.github.com/hummelchen/24731d5e27b890fbe9322a86adc14806

r2 version:
radare2 1.7.0-git 15549 @ linux-x86-64 git.1.6.0-276-ge18f79ab1
commit: e18f79ab11b0a788dc9cf55bca6ee4e2c5a25016 build: 2017-08-09__12:39:59

r2 output(pd from _start):
```
;-- _start:
0x004000d4 48c7c0010000. mov rax, 1 ; section 2 va=0x004000d4 pa=0x000000d4 sz=43 vsz=43 rwx=--r-x .text
0x004000db 48c7c7010000. mov rdi, 1
0x004000e2 488d3425ff00. lea rsi, str.Hello__world__n ; loc.msg ; 0x4000ff ; "Hello, world!\n"
0x004000ea 48c7c20e0000. mov rdx, 0xe
0x004000f1 0f05 syscall
0x004000f3 4831ff xor rdi, rdi
0x004000f6 48c7c03c0000. mov rax, 0x3c ; section_end..shstrtab
}
```
I have also tried to use 'aaa' command but without success

**Comment by radare** [comment]
you have to git pull and enable asm.emustr=1

**Comment by hummelchen** [comment]
Thank you!
As for now, r2 works fine with syscalls in x86 and arm samples, but there some issues with mips support:
For example:
```
0x00400134 24040000 addiu a0, zero, 0
0x00400138 24020fa1 addiu v0, zero, 0xfa1
0x0040013c 0000000c syscall ; 0 = unknown()
```
Exit syscall is defined in radare2/libr/syscall/d/linux-mips-32:
exit=4001,1,1i

**Comment by radare** [comment]
can you please make a PR in r2r adding more syscall resolution tests, so i can fix them all in a shot instead of having to care one by one, checking different kind of parameters, number of them, archs,  32, 64, etc

that would be really helpful :)

**Comment by radare** [comment]
and open a different issue to track those with checkboxes

**Comment by Maijin** [comment]
Here @hummelchen  https://github.com/radare/radare2/tree/master/libr/syscall/d
