### ISSUE TITLE
Segfault on connection to gdbserver when the port is closed

### ISSUE THREAD

**Issue by hummelchen** [radare/radare2#8191]
r2 fails with segfault when I try to connect to closed gdbserver port and dbg.exe.path is specified:
```
Core was generated by `r2 -D gdb -e dbg.exe.path=/bin/ls gdb://127.0.0.1:1337'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x000055a866bbe0be in main (argc=6, argv=0x7fffa721abf8, envp=0x7fffa721ac30)
at radare2.c:839
839 free (fh->desc->name);
```

Core file and r2 binary: 
https://gist.github.com/hummelchen/67ef69e19e2dcbde62642116de071f7f

r2 version:
radare2 1.7.0-git 15549 @ linux-x86-64 git.1.6.0-276-ge18f79ab1
commit: e18f79a build: 2017-08-09__12:39:59

**Comment by radare** [comment]
double like double free, can you paste the valgrind log or the full gdb backtrace?

**Comment by hummelchen** [comment]
Here you are:
https://gist.githubusercontent.com/hummelchen/67ef69e19e2dcbde62642116de071f7f/raw/a48f3f7d07fdd20ab9335795a14a2d15a8e250cd/r2.out
