### ISSUE TITLE
Problems with reverse debugging

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#8198]
I try examples about reverse debugging from Radare2 book:
```
$ r2 /bin/ls
[0x004049a0]> dts+
[0x004049a0]> dso 2
[0x00000000]> dr rip
0x00000000
[0x00000000]>
```

But rip by default is 0x0. It should be equal entrypoint and start to debug with ESIL.

The other problem. I try to debug:
```
$ r2 -d /bin/ls
Process with PID 19843 started...
= attach 19843 19843
bin.baddr 0x00400000
Using 0x400000
Assuming filepath /bin/ls
asm.bits 64
 -- What is the most complex r2 command? q - then you have to deal with real life /o\
[0x7f2ff54c8c30]> dts+
Reading 8192 bytes from 0x0061d000...
Reading 4096 bytes from 0x0061f000...
Reading 8192 bytes from 0x7f2ff56ed000...
Reading 4096 bytes from 0x7f2ff56ef000...
Reading 135168 bytes from 0x7ffe1b1a7000...
[0x7f2ff54c8c30]> dso 2
hit breakpoint at: 7f2ff54c8c38
[0x7f2ff54c8c30]> dsb
```

After last command I can't stop working with ctrl+c and see these errors:
![2017-08-12_19-59-10](https://user-images.githubusercontent.com/1186777/29242613-e3c0c288-7f98-11e7-9e1e-d750a7241205.png)

**Comment by Maijin** [comment]
@RKX1209 ^ See this

**Comment by RKX1209** [comment]
At first, you need to add '-d' option when use 'dts+', and in ESIL mode, 'aets+' should be.
And second problem can be occurred when program execute some non deterministic events like system calls.
I'm gonna work this problem. Sorry for inconvenience.

**Comment by radare** [comment]
I make dso call aeso when cfg .debug is false

**Comment by radare** [comment]
are you on latest r2? try typing aeip first if you are on esil

**Comment by dukebarman** [comment]
Yeap!
```
$ r2 -v
radare2 1.7.0-git 16223 @ linux-x86-64 git.1.6.0-955-g05315c9
commit: 05315c92702b2be3754c3f66fca87162c7b8b5cb build: 2017-09-27__16:48:51
```

The first bug with ESIL is fixed for me:
```
$ r2 /bin/ls
 -- Move around the bytes with h,j,k,l! Arrow keys are neither portable nor efficient
[0x004049a0]> dts+
[0x004049a0]> dso 2
[0x004049a0]> dr rip
0x004049a2
[0x004049a0]> 
```

The second about debugger - nope :(

**Comment by XVilka** [comment]
Still reproducible :( @RKX1209 do you have time to check this please?

**Comment by radare** [comment]
yep reverse debugging is pretty buggy. ive seen a bunch of problems and i'll probably give a try after the 2.1 release

**Comment by XVilka** [comment]
Good thing for GSoC microtask, imho

**Comment by radare** [comment]
cool!
