### ISSUE TITLE
PyREBox Integration

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#8204]
Cisco-Talos group has a nice looking python project called `PyREBox`.

https://github.com/Cisco-Talos/pyrebox

Adding them as a debugger handler or something would be cool. Being able to use radare2 to drive debugging of a full windows system through the normal radare2 interface. This could also assist in some of the challenges with debugging Windows from Linux using radare2 that have been encountered, better support malware reversing using radare2, etc.

**Comment by Maijin** [comment]
Could you provide more information on what this issue is about? Sounds more something to go in r2-extras.

Are there any available tutorial for adding new handlers there, any examples of other interfaces already added etc.

**Comment by Owlz** [comment]
Yeah, now that you mention it, this likely is better suited for the plugins. There's nothing specifically for this ticket that is broken. More of a "it would be neat if..".

**Comment by Owlz** [comment]
Moving it over to radare2-extras.
