### ISSUE TITLE
Error showing full main function (?)

### ISSUE THREAD

**Issue by Tzaoh** [radare/radare2#8211]
Hi, I think having pseudo enabled is causing some problems when printing dissasembly functions (pdf command). Note the last part of the dissasembly on bot pdf and Vp cmds.

pdf cmd do not print the entire function

https://asciinema.org/a/WvsLP97bdyyolow9JyrZcvW8T

binary and config attached.
[files.zip](https://github.com/radare/radare2/files/1223230/files.zip)

Update: Aparently loading the binary without any settings causes the same problem.
![screen shot 2017-08-14 at 20 48 54](https://user-images.githubusercontent.com/5722357/29288833-360d927e-8132-11e7-865b-cb202345429c.png)

**Comment by radare** [comment]
use pdr , pdf only works for linear functions

**Comment by Tzaoh** [comment]
this is a linear function, right?

**Comment by radare** [comment]
asciinema is 404
