### ISSUE TITLE
Save/Load layout

### ISSUE THREAD

**Issue by hteso** [radare/radare2#8215]
It would be great to add two new menu entries in the visual panels mode, one to save the current layout and anther one to load it again.

**Comment by XVilka** [comment]
@Vane11ope you might want to check this one too.

**Comment by Vane11ope** [comment]
@XVilka hey thank you for assigning me in. i actually have been missing this and the idea sounds like the feature i wanna have. therefore i surely will do implement this soon enough shortly.

**Comment by Maijin** [comment]
@Vane11ope related https://github.com/radare/radare2/pull/8597

**Comment by Vane11ope** [comment]
#11380
