### ISSUE TITLE
Cannot see my comment after loading my project

### ISSUE THREAD

**Issue by klaus198376** [radare/radare2#8222]
After i had written a comment in r2 at the address 0xf7fd9a20
`CC test`
i saved it to the project bof.
`Ps bof`
When i had opened the project with
`r2 -p bof -d ./bof` 
i could not see my comment.
`pd` 
I tried to open the project inside of r2,
`Po bof` 
but i got only the message
`[0xf7fd9a20]> Po bof
Cannot find file ''` 
Output of
`[0xf7fd9a20]> Pl`
was
`bof`.

radare2 1.7.0-git 15574 @ linux-x86-64 git.1.6.0-336-g746eb0134
commit: 746eb01344ef57f94f4eda538ed34d912f5ee76b build: 2017-08-15__21:15:15

[rc.txt](https://github.com/radare/radare2/files/1226130/rc.txt)

**Comment by radare** [comment]
Because this bin is pie and comments are bind to a constant address

**Comment by radare** [comment]
Also, projects in debugger mode are kind of useless because projects expect a constant state and in debugger land everything can change at any time, even the executable code
