### ISSUE TITLE
String search defaulting to searching only part of file

### ISSUE THREAD

**Issue by zellyn** [radare/radare2#8236]
Context: I'm analyzing a ctf gameboy image that is exactly 0x8000 bytes long, in two rombanks. I know it contains the string “KOJIMA”.

Searching with `/ KOJIMA` doesn't find the string. It only searches half the file. If I set `search.in` to `io.section`, it works.

```
$ strings mission.gb | grep KOJIMA
LONG LIVE       KOJIMA.
$ wc -c mission.gb
   32768 mission.gb
$ r2 mission.gb 
syntax error: error in error handling
syntax error: error in error handling
syntax error: error in error handling
 -- Sudo make me a pancake.
[0x00000100]> / KOJIMA
Searching 6 bytes from 0x00004000 to 0x00008000: 4b 4f 4a 49 4d 41 
Searching 6 bytes in [0x4000-0x8000]
hits: 0
[0x00000100]> e search.in
file
[0x00000100]> e search.in=io.section
[0x00000100]> / KOJIMA
Searching 6 bytes from 0x00000000 to 0x00004000: 4b 4f 4a 49 4d 41 
Searching 6 bytes in [0x0-0x4000]
hits: 1
0x00002aa1 hit0_0 .LONG LIVE       KOJIMA.6#6!6.
[0x00000100]> S
[00] * 0x00000000 mr-x va=0x00000000 sz=0x4000 vsz=0x4000 rombank00
[01] . 0x00004000 mr-x va=0x00004000 sz=0x4000 vsz=0x4000 rombank01
```

**Comment by radare** [comment]
in va mode not the whole file is mapped in memory

add more details or use search.in properly

**Comment by zellyn** [comment]
As a complete beginner, I'm following noob tutorials. I want to `r2 mission.gb`, and then search for a string in the whole file. Is there a simple way to do that, so the tutorials can be updated?

**Comment by radare** [comment]
all the new IO changes may affect this issue, you may want to see io.va and maybe @Maijin have some spare time to check this issue and give a longer explanation. maybe in a blogpost?

**Comment by radare** [comment]
just use search.in=raw and then search.frmo/to

**Comment by Maijin** [comment]
you can now check `e search.in=??`

**Comment by Maijin** [comment]
Can you try ping1
