### ISSUE TITLE
PEID integration 

### ISSUE THREAD

**Issue by techvoltage** [radare/radare2#8241]
Hi, Is there a packer detection(PEID, DiE etc.) plugin currently available for radare2?

**Comment by XVilka** [comment]
There is Yara support in r2 and PEiD signatures are available in Yara format - see `r2pm -i yara-lib; r2pm -i yara`

See also this bug https://github.com/radare/radare2/issues/921

**Comment by Maijin** [comment]
Useless, you can use Yara, PEID is completely outdated, all the PEID databases cleaned and uplifted and has already been converted to yara you can find those here https://github.com/Yara-Rules/rules
