### ISSUE TITLE
Problems with xor and woD command

### ISSUE THREAD

**Issue by hummelchen** [radare/radare2#8256]
Hi,
I just found a bug in woD command, xor cipher fails with "Invalid IV."
When I was debugging this issue, it was found that the problem was in the function r_crypto_set_iv. 
This function returns 0 because cry->h->set_iv function pointer is set 0 for this cipher.
I think we should add some logic to handle ciphers which do not have any IV.

**Comment by Maijin** [comment]
It works without IV, what command do you type, what is the version of radare2 you are using and have open the file in write mode ?

**Comment by hummelchen** [comment]
radare2 1.7.0-git 15552 @ linux-x86-64 git.1.6.0-314-gc2b58d7cf
commit: c2b58d7cf0cbcbad6209c3e4c1504ba2bac60fc3 build: 2017-08-14__11:54:12
Session:
```
% cp /etc/services .
% r2 ./services 
 -- 3nl4r9e y0\/r r4d4r3
[0x00000000]> oo+
File ./services reopened in read-write mode
[0x00000000]> woD xor -s 0x90
Invalid IV.
[0x00000000]> 
```

**Comment by Maijin** [comment]
for one byte xor use `wox 0x90`
for a string use `woD xor key`

**Comment by radare** [comment]
Provide test script to reproduce

**Comment by Maijin** [comment]
Wrong usage of command, closing.
