### ISSUE TITLE
Introducing new foreach  - @@[]

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8272]
To be able to specify range and step, something like
`[0x00000000]> wx 0xff @@[0x500-0x600,8]`
where 0x500 - start of the range, 0x600 - end of it and 8 - is a step size. Or something similar.

**Comment by radare** [comment]
I think this exists already.. maybe with @@= and escaping the ? Subcommand to genereate sequences.

**Comment by radare** [comment]
But yeah makes sense to have something more handy

**Comment by multun** [comment]
just tested,
```
command @@=`?s from to step`
```
works, but I guess it generates the whole sequence before evaluating it
