### ISSUE TITLE
automagic section-apply on S

### ISSUE THREAD

**Issue by condret** [radare/radare2#8285]
ok, so there are a few tests, that fail, bc Sections now work as blueprints for creating maps. Why not having sections and maps for remapping, you may ask. Let me ask you a different question: How much pear makes and apple? Nothing, you cannot compare these 2.
Atm, S only creates another blueprint for 1 or 2 maps. It does not cause any remapping by its creation.
But some tests expect that. You can use SRs[a|p|e] for creating the remapping for a section. [a]nalysis mode, [p]atching mode and [e]emulation mode. All of these modes have different purposes.
Should we automagically apply sections on creation? in what mode should we apply them? should this be configurable? should we associate them with a rbinfile? Should use set the rbinfile-id by hand or autmagic?

**Comment by Maijin** [comment]
It's obvious that the user don't want to do mapping manually when they open a file, this needs to be automatically, however leaving the possibility to change this mapping afterwards is good. Same model as previous S automatic but modifiable by the user

**Comment by Maijin** [comment]
I remember also that we said during siol discussion that io.sectonly should be enabled by default to reduce the amount of stupid question and also because it's way more logic

**Comment by condret** [comment]
I can't remember this. I'm sure that we said that map and section cannot do both remapping

**Comment by Maijin** [comment]
Say:

![image](https://user-images.githubusercontent.com/1408600/29634520-735a4fa4-884a-11e7-84e5-192ef4c2320b.png)

Shouldn't be default, instead it should display `io.0xff` value.

**Comment by radare** [comment]
see om, its there because siol sets a map at 0, we are discussing this with alvaro and condret, and fix it now

**Comment by condret** [comment]
fix is on the way for the S

**Comment by Maijin** [comment]
S is dead closing here
