### ISSUE TITLE
Feature-request: AVL-trees

### ISSUE THREAD

**Issue by condret** [radare/radare2#8300]
would be nice if someone could implement AVL-tree in util. Want that for huge speed-improvement in io

**Comment by condret** [comment]
https://en.wikipedia.org/wiki/AVL_tree

**Comment by condret** [comment]
rb-trees would be ok too

**Comment by MaskRay** [comment]
I can write a red-black tree.

**Comment by MaskRay** [comment]
https://github.com/MaskRay/radare2/tree/feature-rbtree
