### ISSUE TITLE
V850_ADD_IMM5 stackptr value.

### ISSUE THREAD

**Issue by wargio** [radare/radare2#8308]
On V850 Anal plugin the variable called `stackptr` was always 0 because it was using the macro `F6_IMM` which does a `x & 0xFFFF0000` on a u16 variable.

this needs to be fixed to the proper value.

https://github.com/radare/radare2/blob/master/libr/anal/p/anal_v850.c#L222

**Comment by gtors** [comment]
Fixed in https://github.com/radare/radare2/commit/7b40f7aed134b6421702430b986be8af98e961e0#diff-9a17eb589d9cfc93bf2bc82130ed1844R222

**Comment by wargio** [comment]
No. it wasn't

**Comment by radare** [comment]
@gtors ?

**Comment by radare** [comment]
ping

**Comment by gtors** [comment]
@radare 
https://asciinema.org/a/M0zQJXPNh4EBNE1vaA6m9Px99
[v850.zip](https://github.com/radare/radare2/files/1503249/v850.zip)

**Comment by wargio** [comment]
thanks for the bin, but it isn't fixed. give a look to the value type. it's a u16 not u32.
i don't know the arch, so i cannot fix this issue.

**Comment by radare** [comment]
any plans for this?

**Comment by wargio** [comment]
unfortunately i don't know the architecture.. i'll search for the references and try to fix this.

**Comment by radare** [comment]
@gtors ?

**Comment by gtors** [comment]
Possibly, we can spy how it implemented in GDB:

_sim/v850/simops.c:_
```
/* addi sign_extend(imm16), reg, reg */
int
OP_600 (void)
{
  unsigned int op0, op1, result, z, s, cy, ov;

  trace_input ("addi", OP_IMM16_REG_REG, 0);

  /* Compute the result.  */

  op0 = EXTEND16 (OP[2]); <----------------- Seems it's SIMM16
  op1 = State.regs[ OP[0] ];
  result = op0 + op1;
  
  /* Compute the condition codes.  */
  z = (result == 0);
  s = (result & 0x80000000);
  cy = (result < op0 || result < op1);
  ov = ((op0 & 0x80000000) == (op1 & 0x80000000)
	&& (op0 & 0x80000000) != (result & 0x80000000));

  /* Store the result and condition codes.  */
  State.regs[OP[1]] = result;
  PSW &= ~(PSW_Z | PSW_S | PSW_CY | PSW_OV);
  PSW |= ((z ? PSW_Z : 0) | (s ? PSW_S : 0)
		| (cy ? PSW_CY : 0) | (ov ? PSW_OV : 0));
  trace_output (OP_IMM16_REG_REG);

  return 4;
}
```

Where EXTEND16 defined as:

_sim/common/sim-bits.h:_
```
#define EXTEND16(X) ((signed_word)(signed16)(X))
```
_gdb/sim/common/sim-types.h:_
```
typedef signed64 signed_word;
```
```
typedef int64_t signed64;
```
```
typedef int16_t signed16;
```

**Comment by wargio** [comment]
ok, then it's easy.

**Comment by radare** [comment]
for 2.3.0 then :P
