### ISSUE TITLE
Rename ?: to ?L for consistency

### ISSUE THREAD

**Issue by radare** [radare/radare2#8314]
to list all core plugins... or maybe just L

**Comment by plutec** [comment]
I see L right, like now, not?
```
[0x00404890]> L
   asm 0x7fba2b568be0 /usr/local/lib/radare2/1.7.0-git//asm_propeller.so 
[0x00404890]> L?
|Usage: L[-name][ file] # see oL, iL, dL, ...
| L          List all plugins loaded by RCore.lib
| L-duk      Unload plugin matching in filename
| L blah.so  Load plugin file
```

**Comment by radare** [comment]
Then we can kill ?:

**Comment by plutec** [comment]
Uhmm, I didn't know but it seems to do different things:
```
[0x00404890]> ?:
anal: The reworked analysis from scratch thing
java: Suite of java commands, java help for more info
```

**Comment by plutec** [comment]
Sorry, I understand the question. I'm stupid. XD
Under my POV it's clear ?L than ?:

**Comment by radare** [comment]
[0x1000011e0]> L
   asm 0x7fda7ce0cee0 /usr/local/lib/radare2/1.7.0-git//asm_propeller.dylib
    io 0x7fda7cc17e70 /Users/pancake/.config/radare2/plugins/io_frida.dylib
[0x1000011e0]> ?:
anal: The reworked analysis from scratch thing
java: Suite of java commands, java help for more info


L is for dynamic plugins and ?: is only for the core ones.. so thats where the confusion comes from, so feel free to suggest changes on this to make it more consistent

**Comment by MaskRay** [comment]
Add `Ls` for `?:`?
