### ISSUE TITLE
How to make radare2 appliable for several disassemble engines/libraries?

### ISSUE THREAD

**Issue by mudongliang** [radare/radare2#8316]
I have asked a question about disassemble engine/library radare2 use in Issue #8151.
How does developers make radare2 suitable/applicable for several diassemble engines/libraries?

I have a small guess, but I don't know whether it is right.
abstract the interface radare2 needs for disasmbling and retrieving properties from one instruction or one operand inside one instruction.
If so, where is the definition of those interfaces?
Or how to implement?

**Comment by Maijin** [comment]
I don't really understand the question but I guess the idea is how to add a new architecture.

You can do that following the tutorial you can found on r2book - https://radare.gitbooks.io/radare2book/content/plugins/plugins.html

See Implementing a new architecture chapters, the process is described

**Comment by mudongliang** [comment]
Actually, I try to ask how do you make radare2 choose different assemble/disassemble engines with one option for only one architecture, for example, x86 architecture.

**Comment by radare** [comment]
The asm plugins are selected with the asm.arch variable, the analysis ones with anal.arch and if you want a custom assembler plugin use the asm.assembler.

you can select them by using r2 -a <pluginame>

**Comment by mudongliang** [comment]
Got it. Thanks
