### ISSUE TITLE
WinMain() autosearch/recognize for PE files

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#832]

**Comment by XVilka** [comment]
This one depends from the ESIL.

**Comment by Maijin** [comment]
Here is a lpSubMain detector in r2pipe for VB PE, this need to be done in C:
* https://gist.github.com/Maijin/54e7ad10dd2c2eba0a2f6c69340c4581

**Comment by skuater** [comment]
implemented a MSVC SEH pattern for pe32

**Comment by radare** [comment]
Fixed in 83eff0445103e10a0e3a1f2e4d6e2778d1b54a9b

**Comment by Maijin** [comment]
Far from beeing completed :P

**Comment by skuater** [comment]
still working adding more patterns

**Comment by Maijin** [comment]
@skuater Someone found another not-recognized winmain binary 👍 
[winmain.zip](https://github.com/radare/radare2/files/801184/winmain.zip)

**Comment by Maijin** [comment]
@skuater just fixed this one https://github.com/radare/radare2/commit/1ec9e7d1042674fd50e406b592b3b21982426048

**Comment by Maijin** [comment]
The binary here: https://github.com/radare/radare2/issues/6164 need detection too.

**Comment by Maijin** [comment]
This should be done via Zignature

**Comment by Maijin** [comment]
See https://github.com/radare/radare2/issues/5331

**Comment by Maijin** [comment]
Let's close it since this need to be done on-the-go now the big one are fixed.
