### ISSUE TITLE
META - PDB Support

### ISSUE THREAD

**Issue by radare** [radare/radare2#8323]
# PDB

- [ ] Load and parse PDB when open minidump files (see `libr/bin/format/mdmp/mdmp_pe.c`).

## Related

* [x] Doc - TBD
* Tests - https://github.com/radare/radare2-regressions/tree/master/t.formats/pdb
* Commands involved - idp/idpd/rabin2 -PX
* [x] BlogPost - TBD
* .c involved:
    * libr/bin/pdb/pdb.c
    * libr/core/cmd_info.c

# Fixes

# Enhancement

- [ ] Add a R_bin plugin for pdb files

**Comment by Maijin** [comment]
@riverar maybe you want to check the e dir.pdb issue ?

**Comment by riverar** [comment]
Can tick off the pdb dir box, implemented in https://github.com/radare/radare2/commit/3031324be369610289ef9ea2c3898baa127bd3ed

**Comment by Maijin** [comment]
done

**Comment by Maijin** [comment]
This is fixed except the fileformat which is referenced in the META.
