### ISSUE TITLE
search.in values are confusing

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8334]
I added help for search.in=??
see https://github.com/radare/radare2/blob/f1b185cd74a0d5576da6601276db2899fccdd148/libr/core/cconfig.c#L1809-L1826

But some values are confusing:
Such as `raw` which seems to be similar to `block` and `file` which seems to be similar to `io.sections`

**Comment by radare** [comment]
Can you fix e asm.arch=? and make asm.arch=?? show the current output?

why do you fill an issue if the change is already done?

you may at least indent this output to not make my eyes bleed

**Comment by radare** [comment]
<3
