### ISSUE TITLE
on* shows no mapaddr

### ISSUE THREAD

**Issue by radare** [radare/radare2#8335]
Because mapaddr no longer belongs to desc

**Comment by condret** [comment]
what should happen, when there are multiple maps for the file?

**Comment by radare** [comment]
maybe we shuold make on open a file without creating any map and then on* show all the maps so they can be recreated, the problem here is that we need the fd to be reused so the output should handle that.

one solution would be to make fd=0 or fd=-1 assume the last opened file so we can do om -1 ….

also, om cant set map name, it needs a separate command so it forces to run 2 commands

**Comment by condret** [comment]
we can change om

**Comment by radare** [comment]
can u do that?

**Comment by radare** [comment]
This is important. ping

**Comment by radare** [comment]
the output of on* should run on file baddr, we should just recover the base address if there's only 1 map for each fd
