### ISSUE TITLE
Segmentation fault when 'pdsf'

### ISSUE THREAD

**Issue by A1phaZer0** [radare/radare2#8378]
radare2 1.7.0-git 15916 @ linux-x86-64 git.1.6.0-640-g01b27c1
commit: 01b27c1bf9322bbf57c69e6fa44711295e23885b build: 2017-08-29__19:34:12

```shell
r2 -A /bin/ls
pdsf
Segmentation fault 
```

**Comment by radare** [comment]
Another regresion introduced with leakfixing... fixing in 3, 2,...
