### ISSUE TITLE
The analysis is not deep enough

### ISSUE THREAD

**Issue by rootkiter** [radare/radare2#8384]
Sample :
    https://virustotal.com/#/file/acffc2877719424925aa02f603953ea5e7aa2673a7093fd72a67d389cda6148d/detection

    $r2 ./acffc2877719424925aa02f603953ea5e7aa2673a7093fd72a67d389cda6148d
    > aaaa
    > afl

This sample has 320 functions in IDA pro 6.8.  But only 116 functions in radare2... This effect is very unsatisfactory. Maybe we can make it a little bit more powerful.

**Comment by condret** [comment]
you can configure the depth of the analysis

**Comment by radare** [comment]
aaaa is lame

there are tons of better ways to analyze code, read the radare.today blogpost

**Comment by Maijin** [comment]
http://radare.today/posts/analysis-by-default/

**Comment by Maijin** [comment]
Well trying several of analysis code doesn't give much more result either, there is probably something to do with this binary to improve radare2 @radare . 
(password "infected", mips binary)
[a096fd65c5a935ffbe0cc9125e57b915.zip](https://github.com/radare/radare2/files/1265150/a096fd65c5a935ffbe0cc9125e57b915.zip)

**Comment by Maijin** [comment]
also you are using an old version of r2,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
@Maijin this is js

**Comment by Maijin** [comment]
updated

**Comment by radare** [comment]
```
$ r2 acffc2877719424925aa02f603953ea5e7aa2673a7093fd72a67d389cda6148d
> e anal.hasnext=true
> aa
> afl~?
335
```

**Comment by Maijin** [comment]
If you use aaa instead of aa you'll get refs too

**Comment by Maijin** [comment]
try to play around, there are tons of variables as said, closing.

**Comment by rootkiter** [comment]
It works. Awesome!

Thanks for your reply. 
Have a good  day.

Hello World
