### ISSUE TITLE
r_io_fd_size signed check

### ISSUE THREAD

**Issue by repnzscasb** [radare/radare2#8394]
The fix in commit c99bae1b6c5fb2c7e61dfac91ff38d682b3260b3 breaks functionality.

Consider this:

```bash
$ r2 -v
radare2 1.7.0-git 15925 @ linux-x86-64 git.1.6.0-677-g31604a8a0
commit: 31604a8a02d65b2a64e10a0b99e2dce659df0b15 build: 2017-08-31__22:56:26
$ echo AAA>base; rm dest>/dev/null
$ r2 -qc 'e io.cache=true; wx 424242; wtf! dest @0' base
Dumped 4 bytes from 0x00000000 into dest
$ cat base dest
AAA
cat: dest: No such file or directory
```

At this point "dest" should exist and contain "BBB" in place of "AAA".

If the patch from commit c99bae1b6c5fb2c7e61dfac91ff38d682b3260b3 is inverted on the latest version, the above commands will correctly create a file "dest" containing "BBB".

**Comment by MaskRay** [comment]
Fixed with https://github.com/radare/radare2/commit/800fed2e31bdc14276caad98d36d34d7cd48d111
