### ISSUE TITLE
Enumerate possible fortunes in e?

### ISSUE THREAD

**Issue by radare** [radare/radare2#8414]
[0x1000011e0]> e cfg.fortunes=?
[0x1000011e0]> e cfg.fortunes=??
[0x1000011e0]>

**Comment by radare** [comment]
```
[0x00000000]> e cfg.fortunes.type =?
tips
fuun
nsfw
crep
```

**Comment by MaskRay** [comment]
i think it's better specifying the type when declaring a config var in cconfig.c. rather than relay the type to the first assignment

CN_BOOL typed cars cannot be completed

**Comment by radare** [comment]
then you cant make this dynamically change at runtime, which is needed for many cases
