### ISSUE TITLE
/x is limited in the first section only

### ISSUE THREAD

**Issue by tantecky** [radare/radare2#8429]
Before commit 0161fa0ec2d1f20f38873d6a48ae13e08e2cc138:
```
r2 -q -c '/x f88204080d0000004485040804000000' ../bins/elf/ioli/crackme0x00
Searching 16 bytes in [0x8048360-0x804a331]
hits: 1
0x08049f2c hit0_0 f88204080d0000004485040804000000
```
After commit 0161fa0ec2d1f20f38873d6a48ae13e08e2cc138:
```
r2 -q -c '/x f88204080d0000004485040804000000' ../bins/elf/ioli/crackme0x00
Searching 16 bytes in [0x8048000-0x804a01f]
hits: 0
```

**Comment by Maijin** [comment]
Use `e search.in=??`, `e search.from` and `e search.to`

**Comment by tantecky** [comment]
By manually specifying a range of a particular section:
```
r2 -q -c 'e search.from=0x08049f0c; e search.to=0x0804a020; /x f88204080d0000004485040804000000' ../bins/elf/ioli/crackme0x00
Searching 16 bytes in [0x8049f0c-0x804a020]
hits: 1
0x08049f2c hit0_0 f88204080d0000004485040804000000
```
works, but targeting all sections at once is not possible:
```
r2 -q -c 'e search.in=sections; /x f88204080d0000004485040804000000' ../bins/elf/ioli/crackme0x00
Searching 16 bytes in [0x8048360-0xffffffffffffffff]
hits: 0
```
However if this is desired behavior by now and not an issue. Feel free to close it :)

**Comment by Maijin** [comment]
You need to use search in, from and to

**Comment by Maijin** [comment]
Now should work better after last fixes, please test and comment here, will reopen if necessary.

**Comment by tantecky** [comment]
Works like a charm:
```
r2 -q -c '/x f8820408' bins/elf/ioli/crackme0x00
Searching 4 bytes in [0x8048000-0x80485bf]
hits: 0
Searching 4 bytes in [0x8049f0c-0x804a01b]
hits: 1
Searching 4 bytes in [0x804a01c-0x804a01f]
hits: 0
0x08049f2c hit1_0 f8820408
```
I've created a PR (https://github.com/radare/radare2-regressions/pull/1003) to address this issue.

**Comment by MaskRay** [comment]
You can try

```
wx 01020102010203
/x 0102010203
```

I have made a pull request long ago and rebased numerous times. I am really annoyed

Also notice when the last byte of a map is to be matched in some cases, it is likely to fail. (because of closed-interval nonsense)

**Comment by Maijin** [comment]
open new issue pls

**Comment by radare** [comment]
yeah there are a bunch of things to fix here and there, and now i have all the time stolen by r2con back. so pls update the prs and ill chk them out
