### ISSUE TITLE
Issues in visual mode

### ISSUE THREAD

**Issue by A1phaZer0** [radare/radare2#8441]
radare2 1.7.0-git 16024 @ linux-x86-32 git.1.6.0-751-g4a83691
commit: 4a83691408e37306cb233f6486481e7ea571dcfd build: 2017-09-05__19:08:08

r2 file -> `V` -> move around with `hjkl` -> `\` split mode -> `hhhhhhhhhhh` -> `/AAGA` search string

Two issues:
1. The upper block doesn't follow the cursor although the cursor is on it. 
2. Highlight area is misplaced after searching 'AAGA', the corresponding area on the lower block is right.

![](https://i.imgur.com/D1vmwQs.png)

-----------------------upate-----------------------

More, after quit visual split mode (now in radare shell) and go to visual mode again, it's a split mode without cursor be automatically toggled on:
![](https://i.imgur.com/kPr34BF.png)

Toggle cursor on and search string `j`:
![](https://i.imgur.com/DDrUdMT.png)

Try j to move down:
![](https://i.imgur.com/6fMXYem.png)

**Comment by stanciuadrian** [comment]
I'll look at this one.

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
Yeah you gave a look, now what @stanciuadrian ?

**Comment by radare** [comment]
i dont think those issues happen anymore. please reopen if im wrong
