### ISSUE TITLE
static.sh does not produce static executables

### ISSUE THREAD

**Issue by 0ki** [radare/radare2#8442]
```
git clone https://github.com/radare/radare2.git
cd radare2/
./sys/static.sh 
file r2-static/usr/bin/radare2
````

The last command produces `r2-static/usr/bin/radare2: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), `**`dynamically linked`**`, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=bfde16dcc6f6602a15bdbbf5c0a53591dc36085c, stripped`

I would expect a static executable.

**Comment by radare** [comment]
Yeah i would expect that too

**Comment by radare** [comment]
confirmed issue

**Comment by radare** [comment]
those builds are statically linked AGAINST r2 dependencies. but cannot be static binaries mainly because libphtread cant be statically linked on mac or linux, also, ios forbids statically linking because of the dyldcache. so...
