### ISSUE TITLE
make error in linux

### ISSUE THREAD

**Issue by wangkr** [radare/radare2#8453]
file.c: In function ‘r_file_abspath’: file.c:207:2: warning: passing argument 2 of ‘realpath’ from incompatible pointe                                                                                                                               r type [enabled by default]   char *abspath = realpath (ret, &resolved_path);   ^ In file included from /home/kyrong/download/radare2-master/libr/include/r_types.                                                                                                                               h:169:0,                  from file.c:3: /usr/include/stdlib.h:734:14: note: expected ‘char * __restrict__’ but argument                                                                                                                                is of type ‘char (*)[4096]’  extern char *realpath (const char *__restrict __name,

**Comment by Maijin** [comment]
How to reproduce, ./sys/install.sh works fine here. Please provide full details about OS you build on (arch/OS/bits etc.), how you are building, which commands, and please make sure you cleaned all the older versions of radare2.

**Comment by Maijin** [comment]
Closing until more info is provided.
