### ISSUE TITLE
Internal grep for head -c (first XXX lines)

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8461]
There is `i~:0`     show first line of 'i' output but would be nice to have

`i~:0-3`     to print the first 4 lines

**Comment by Maijin** [comment]
Related https://github.com/radare/radare2/issues/2955

**Comment by queenp** [comment]
Syntactically is there a risk this could interfere with people scripting to try to calculate a line number? I'm thinking it might effectively be redefining the "-" operator between two numbers into a range operator rather than subtraction.

**Comment by Maijin** [comment]
indeed CMD~:..4 returned just fine !

**Comment by MaskRay** [comment]
A yacc file or recursive decent parser is needed, i'm annoyed by those `	ptr2 = strchr (ptr, '[');` scattered in `grep.c`. It is so difficult to understand what it is doing
