### ISSUE TITLE
Just pressing enter does not repeat last disassembly

### ISSUE THREAD

**Issue by msftsecurityteam** [radare/radare2#8469]
Hi, is there a way to get similar functionality to GDB where when you disassemble or print bytes, you print another blocksize just by pressing return? Here I have opened /bin/ls in r2 and disassembled:

[0x00005430]> b 32
[0x00005430]> pd
            ;-- entry0:
            ;-- rip:
            0x00005430      31ed           xor ebp, ebp
            0x00005432      4989d1         mov r9, rdx
            0x00005435      5e             pop rsi
            0x00005436      4889e2         mov rdx, rsp
            0x00005439      4883e4f0       and rsp, 0xfffffffffffffff0
            0x0000543d      50             push rax
            0x0000543e      54             push rsp
            0x0000543f      4c8d05ca0701.  lea r8, 0x00015c10
[0x00005430]> <------ Pressing return here doesn't continue the disassembly
[0x00005430]>

**Comment by radare** [comment]
it was fixed once in here 621c0ae0eb70d1b2b1d00b4277e80df340033d64

**Comment by msftsecurityteam** [comment]
Excuse my last (now deleted) comment. I had a stale binary on my system

**Comment by radare** [comment]
enable the cmd.repeat option and it will do
