### ISSUE TITLE
Does r2 have ARM PE support?

### ISSUE THREAD

**Issue by msftsecurityteam** [radare/radare2#8470]
Hi, I am trying to disassemble an Android kernel image. Originally it is in zImage format, and after decompressing it, I am left with the following header:

00000000  4d 5a 00 91 ff 03 00 14  00 00 08 00 00 00 00 00  |MZ..............|
00000010  00 00 9d 01 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  41 52 4d 64 40 00 00 00  |........ARMd@...|
00000040  50 45 00 00 64 aa 02 00  00 00 00 00 00 00 00 00  |PE..d...........|
00000050  01 00 00 00 a0 00 06 02  0b 02 02 14 00 f0 9c 01  |................|
00000060  00 00 00 00 00 00 00 00  50 95 42 01 00 10 00 00  |........P.B.....|
00000070  00 00 00 00 00 00 00 00  00 10 00 00 00 02 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 9d 01 00 10 00 00  00 00 00 00 0a 00 00 00  |................|

After some research, it appears this is actually an EFI/UEFI stub that is used by the loader when booting the kernel.  IDA begins to parse this kernel image and generate xref's to symbols like strings and other functions, but r2 appears to not do this. Do I need to open the binary in a certain way with r2?

**Comment by Maijin** [comment]
Yes is it does.

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by msftsecurityteam** [comment]
I am running the latest radare2 from git. Is it possible it is only parsing the EFI startup code, and not the rest of the kernel? A quick google showed someone asking a similar question for Binary Ninja here: https://github.com/Vector35/binaryninja-api/issues/76

**Comment by Maijin** [comment]
Please drag and drop the File here in a zip archive.

**Comment by msftsecurityteam** [comment]
No problem, see attached

[kernel.zip](https://github.com/radare/radare2/files/1291098/kernel.zip)

**Comment by radare** [comment]
cc @skuater

**Comment by radare** [comment]
looks supported and working to me
