### ISSUE TITLE
Add error message to r2 -d

### ISSUE THREAD

**Issue by wobbol** [radare/radare2#8471]
I forgot to make a downloaded file executable. r2 didn't handle the user error very well.

```
> whoami
user

> ls -l
-rw-r--r-- 1 user user 7460 Sep  9 15:40  a.out

> r2 -d ./a.out
fork_and_attach: execv: Permission denied
Cannot open 'dbg://./a.out' for writing.

>
```

Placing a `stat()` check before line 456 looks like the ticket.
https://github.com/radare/radare2/blob/b59b28bb3228a9e01a596206d36afb6c59b0b124/libr/io/p/io_debug.c#L456

I am new here and seem to be having a hard time finding the radare2 equivalent of `stat()`. 
Any direction is appreciated.

**Comment by Maijin** [comment]
What ? `stat()` is already used in the project https://github.com/radare/radare2/blob/master/libr/util/file.c#L94

**Comment by Maijin** [comment]
Open a Pull request with the change you propose

**Comment by wobbol** [comment]
Oh great! 
git grep stat looked like a jumbled mess and I assumed that stat was not available on all platforms.

**Comment by wobbol** [comment]
I checked the return value of execvp instead of making a mess with stat.
@Maijin, is there anything else I can do? I think I fixed it.

**Comment by Maijin** [comment]
Wait to get it reviewed by someone and it will get merge eventually or the person will provide you with what to do next.
