### ISSUE TITLE
Add a popup console "widget"

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8476]
To show the multiple possible values with scrolling, when in the one of visual modes. 
Like in console vim:
![2xvegj5](https://user-images.githubusercontent.com/203261/30260511-601cb724-96fa-11e7-8e1c-189e6f61e130.png)

One of the cases - when you have an offset, like e.g. `mov eax, [ebx + 0x18]` and in the future it will support to change the offset for a structure field offset or a named constant, and if there is a multiple choices - to show this popup menu.

 - [x] offset (`o` command) autocompletion in visual mode
 - [ ] apply type for the variable
 - [ ] ...

**Comment by XVilka** [comment]
Can also be useful for stuff like in this IDA plugin - https://github.com/alexhude/FRIEND
![](https://raw.githubusercontent.com/alexhude/FRIEND/master/Resources/screenshots/reg_ins_hints.png)

**Comment by XVilka** [comment]
Or the one from neovim: 
![image](https://user-images.githubusercontent.com/203261/33827108-207fb838-dea2-11e7-8e01-7bfca23c334b.png)

**Comment by ret2libc** [comment]
Isn't this already sovled? @cyanpencil ?

**Comment by XVilka** [comment]
It is not generic yet, works only in one place, should be reused in many.

**Comment by XVilka** [comment]
@deepakchethan can you please review this issue and tell what is missing? I believe it can be closed now. Am I right?

**Comment by radare** [comment]
Its buggy. Works , but incomplete

**Comment by XVilka** [comment]
So lets open a new bugs instead and close this one.
