### ISSUE TITLE
pf segfault

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8487]
pf segfault when referencing a struct in itself:

`pf._NT_TIB ? (_NT_TIB)Self ; pf._NT_TIB`

This has been found while working on PDB

**Comment by Maijin** [comment]
CC @xarkes @XVilka

**Comment by MaskRay** [comment]
Infinite recursion

r_print_format_struct_size /home/ray/Dev/Bin/radare2/libr/util/p_format.c:1339

**Comment by xarkes** [comment]
Yes don't worry I'll fix later

**Comment by radare** [comment]
define later

**Comment by xarkes** [comment]
Now

**Comment by Maijin** [comment]
Not fixed completly see:
```
pf._NT_TIB ?ppppip? (_EXCEPTION_REGISTRATION_RECORD)ExceptionList StackBase StackLimit SubSystemTib FiberData Version ArbitraryUserPointer (_NT_TIB)Self```

**Comment by radare** [comment]
thats an stack exhaustion issue its creating a really deep stackframe in at p_format.c:1339

should be fixed now

**Comment by Maijin** [comment]
@radare  Hum so now there is two different fix for the same issue should probably be decided:

See - pf._NT_TIB ? (_NT_TIB)Self ; pf._NT_TIB that replace ? (_NT_TIB)Self by x Self
vs your fix on `pf._NT_TIB ?ppppip? (_EXCEPTION_REGISTRATION_RECORD)ExceptionList StackBase StackLimit SubSystemTib FiberData Version ArbitraryUserPointer (_NT_TIB)Self```
`

That print struct<_NT_TIB> with some kind of recursion

**Comment by radare** [comment]
incrementing the size with -1 because the size cant be computed was wrong.

**Comment by xarkes** [comment]
I'm fixing

**Comment by elouet** [comment]
I pushed a test for this one.
