### ISSUE TITLE
r command should resize the map

### ISSUE THREAD

**Issue by radare** [radare/radare2#8498]
usually people runs 'r' when iova=0, so there should be only 1 map assigned to that fd, the r command can resize the underlying file... but doesnt resizes the map associated so its useless for the user because it forces him to do om-* and then "omm $(fdq)"

**Comment by condret** [comment]
no, maps are not hard assigned to a file as filemaps, don't do this, the idea itself is quite fragile

**Comment by radare** [comment]
its the only way to make r work. and it fixes bugs, feel free to discuss better ways to solve io issues  after release.

**Comment by condret** [comment]
ok
