### ISSUE TITLE
[rafuzz2] Other commands that crash radare2

### ISSUE THREAD

**Issue by guedou** [radare/radare2#8503]
Similarly to #8500 and #8502, the following commands crash radare2:

- [x] `=<5`
- [x] `v|||| then CTRL+D`
- [x] ```V`````````````````````````h|`iVKd|` then CTRL+D```
- [ ] ```pI 1111111111111```
- [ ] ```pC 1111111```
- [x] ```dd .,,.,,,,,,,,,```
- [x] ```dd A```
- [x] ```omn```

(rafuzz2 is the name of the tool that I built to fuzz r2 commands)

Ca'nt find any issue with those:

- [ ] ww??
- [ ] v.

**Comment by Maijin** [comment]
Please please open tests for those stuffs.

**Comment by radare** [comment]
fixed omn, will chk the rest today

**Comment by radare** [comment]
only pC and pI missing. more in few mins..

**Comment by guedou** [comment]
Aweome !

I will check why the last two are crashing next week.

**Comment by radare** [comment]
should be good now
