### ISSUE TITLE
Loading projects not working when ihex:// was used

### ISSUE THREAD

**Issue by Modiug** [radare/radare2#8504]
Version:
r2 -v
radare2 1.7.0-git 16099 @ linux-x86-64 git.1.6.0-834-g52ebe07f4
commit: 52ebe07f49aed7ec0fed726de81d45c26a8f3589 build: 2017-09-13__22:06:32

[exmple.zip](https://github.com/radare/radare2/files/1303729/exmple.zip)

To reproduce issue:
$ r2 -a 8051 ihex://Vend_Ax.hex
[0x00000000]> Ps vend_ax
vend_ax
[0x00000000]> Po vend_ax
Cannot find file ''

**Comment by Modiug** [comment]
OK, here is an ihex file (had to put it into a .zip, otherwise github did not want to support it).
[exmple.zip](https://github.com/radare/radare2/files/1303729/exmple.zip)

To reproduce issue:
$ r2 -a 8051 ihex://Vend_Ax.hex
[0x00000000]> Ps vend_ax
vend_ax
[0x00000000]> Po vend_ax
Cannot find file ''

**Comment by Maijin** [comment]
yes perfect!

**Comment by radare** [comment]
Cant be fixed for this release. @condret is working on deprecating file and lastfile config vars to allow multifile projects work properly, and therefor handle uri-based projects too

**Comment by Modiug** [comment]
No problem for me, as I used objdump to convert to binary.

Is there actually a need to support IHEX? I mean with "objdump -I ihex -O binary file.ihex file.bin" this functionality is not really needed in radare2.

**Comment by Maijin** [comment]
it is already supported. the bug needs to be fixed.

**Comment by radare** [comment]
Should work with prj.simple

**Comment by giuscri** [comment]
Can't reproduce this as of 00668df334800762038a77ca666ef46d378650f8
```
$ r2 -a 8051 ihex://Vend_Ax.hex 
Cannot set bits 64 to '8051'
Cannot set bits 64 to '8051'
 -- Reverser by Birth, r2 by Choice
[0x00000000]> Ps vend_ax
vend_ax
[0x00000000]> Po vend_ax 
[0x00000000]> Pl
qwerty
vend_ax
```

**Comment by OhioDuckFarmer** [comment]
While I can confirm that I am unable to reproduce the issue, it looks like there is another issue.  As shown below, after the loading of the project (via Po) the data is no longer available:

    $ r2 -a 8051 ihex://Vend_Ax.hex
    Cannot set bits 64 to '8051'
    Cannot set bits 64 to '8051'
     -- Hold on, this should never happen!
    [0x00000000]> px
    - offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
    0x00000000  020e 51ff ffff ffff ffff ffff ffff ffff  ..Q.............
    0x00000010  ffff ffff ffff ffff ffff ffff ffff ffff  ................
    0x00000020  ffff ffff ffff ffff ffff ffff ffff ffff  ................
    0x00000030  ffff ff02 0e7b ffff ffff ffff ffff ffff  .....{..........
    0x00000040  ffff ff02 0900 ffff ffff ff02 07ed ffff  ................
    0x00000050  ffff ff02 0900 ffff ffff ffff ffff ffff  ................
    0x00000060  ffff ffff ffff ffff ffff ffff ffff ffff  ................
    0x00000070  ffff ffff ffff ffff ffff ffff ffff ffff  ................
    0x00000080  90e6 78e0 5410 ffc4 540f 4450 f51d 13e4  ..x.T...T.DP....
    0x00000090  33f5 1f90 e6b9 e024 5eb4 0a00 4003 0203  3......$^...@...
    0x000000a0  d890 00af 75f0 03a4 c583 25f0 c583 7302  ....u.....%...s.
    0x000000b0  024d 0202 4d02 03d8 0203 d802 00cd 0203  .M..M...........
    0x000000c0  d802 0113 0201 3902 00ed 0201 0090 e600  ......9.........
    0x000000d0  e0ff c454 0f90 e740 f0e4 90e6 8af0 90e6  ...T...@........
    0x000000e0  8b04 f090 e6a0 e044 80f0 0203 d890 e67a  .......D.......z
    0x000000f0  e054 fef0 e490 e68a f090 e68b f002 03d8  .T..............
    [0x00000000]> Ps vend_ax
    vend_ax
    [0x00000000]> Po vend_ax
    [0x00000000]> Pl
    vend_ax
    [0x00000000]> px
    - offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
    0x00000000  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000010  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000020  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000030  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000040  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000050  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000060  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000070  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000080  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x00000090  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x000000a0  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x000000b0  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x000000c0  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x000000d0  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x000000e0  0000 0000 0000 0000 0000 0000 0000 0000  ................
    0x000000f0  0000 0000 0000 0000 0000 0000 0000 0000  ................
    [0x00000000]> 

The version I tested with is:

    radare2 2.4.0-git 17478 @ linux-x86-64 git.2.2.0-656-g00668df
    commit: 00668df334800762038a77ca666ef46d378650f8 build: 2018-03-03__12:05:34

**Comment by OhioDuckFarmer** [comment]
I have created a new issue for this new problem:

[Reloading of project causes source data to be blank #9574](https://github.com/radare/radare2/issues/9574)

**Comment by radare** [comment]
Try with prj.simple

**Comment by OhioDuckFarmer** [comment]
It is my understanding that we are moving away from the "use prj.simple"
response and fixing the actual full prj usage process.

**Comment by radare** [comment]
No.

**Comment by OhioDuckFarmer** [comment]
prj.simple causes a new issue.  See my additional information post that I just added.

**Comment by radare** [comment]
Ok then we r not going to enable it by default for this release.

Thanks
