### ISSUE TITLE
Graph code memory leaks

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8509]
Just build r2 with ASAN, run `r2 -AA /bin/ls`, then `s main; VV` and navigate some graph, then exit.
Sorry, cannot provide output right now, seems I have broken clipboard, cannot copy/paste from the console. But leaks are still presented and big.

![screenshot_20170914_130631](https://user-images.githubusercontent.com/203261/30412911-9a8fb564-994d-11e7-8ac5-de43b29185c4.png)

@P4N74 check this please

**Comment by P4N74** [comment]
I have already made pr for that: https://github.com/radare/radare2/pull/8397

**Comment by MaskRay** [comment]
What Python plugins are you using?

P4N74's commit looks good to me if he could remove `a_dyn_alloc` & `strdup` every attribute.

**Comment by XVilka** [comment]
@MaskRay it's lang_python from bindings. I know it has leaks, not killing objects upon exit, but not a priority for me.
