### ISSUE TITLE
View graph (VV) gives different/broken results when loading with ihex://

### ISSUE THREAD

**Issue by Modiug** [radare/radare2#8512]
$ r2 -v
radare2 1.7.0-git 16099 @ linux-x86-64 git.1.6.0-834-g52ebe07f4
commit: 52ebe07f49aed7ec0fed726de81d45c26a8f3589 build: 2017-09-13__22:06:32

To reproduce: 
unzip: [exmple.zip](https://github.com/radare/radare2/files/1303783/exmple.zip)

r2 -AA -a 8051 ihex://Vend_Ax.hex
[0x00000000]> VV

and compare to

r2 -AA -a 8051 Vend_Ax.bin
[0x00000000]> VV

Vend_Ax.bin was produced from Vend_Ax.hex by:
objcopy -I ihex -O binary Vend_Ax.hex Vend_Ax.bin

**Comment by radare** [comment]
Are the contents the same?

**Comment by condret** [comment]
show me your radare2rc

**Comment by Modiug** [comment]
@radare: If by contents you mean Vend_Ax.hex and Vend_Ax.bin: Yes, the .bin was created from .hex with objcopy as stated. If you mean the attachement from the other ihex:// issue: The Vend_Ax.hex is the same, but I added the Vend_Ax.bin.

@condret: I do not have a radare2rc. At least not that I know off. No ~/.radare2rc, no radare2rc in .config/radare2, no .radare2rc in the current directory.

**Comment by condret** [comment]
is e io.ff set to true?

**Comment by Modiug** [comment]
Yes for both versions (.hex and .bin), if that would matter.
[0x00000000]> e io.ff
true

**Comment by radare** [comment]
<img width="1125" alt="screen shot 2017-09-15 at 12 07 38" src="https://user-images.githubusercontent.com/917142/30478752-98985eb2-9a12-11e7-9a6c-d3a5152c49ea.png">

**Comment by radare** [comment]
tahts not the same

**Comment by radare** [comment]
and siol removed the ability to specify a different and siol broke io.0xff.... so this cant be workarounded.. @condret pls we need tests for 0xff too

**Comment by Modiug** [comment]
The .bin and .hex files seem to be different, because objcopy fills gaps with 0 by default. It seems radare2 fills gaps with 0xff when reading ihex://.
Try:
objcopy -I ihex -o binary --gap-fill 255 Vend_Ax.hex Vend_Ax.bin

Still different?
Why would it affect the graph visualization?

**Comment by radare** [comment]
because ff is an invalid instruction and 00 is not

**Comment by radare** [comment]
also, paste a screenshot to document the issue

**Comment by Modiug** [comment]
I now generated an Vend_Ax.bin where the gaps are filled with 0xff. The loaded binaries look the same.
See:
bin:
![startup_bin](https://user-images.githubusercontent.com/4440482/30491996-579c5d82-9a3f-11e7-8e93-601bb30e3df5.png)
ihex:
![startup_ihex](https://user-images.githubusercontent.com/4440482/30491998-57f53fa6-9a3f-11e7-9177-76dc3ca9a718.png)

However, when I then type VV, I get:
bin:
![vv_bin](https://user-images.githubusercontent.com/4440482/30492023-74780028-9a3f-11e7-9ae7-fbb1ec0964ae.png)
ihex:
![vv_ihex](https://user-images.githubusercontent.com/4440482/30492024-747ba548-9a3f-11e7-9fa1-6988500572f2.png)

**Comment by radare** [comment]
check the output of the om command, probably the analysis is different because of mapping without the exec bit

**Comment by radare** [comment]
cc @condret @MaskRay 

also we want to want to have io.0xff back

**Comment by Modiug** [comment]
Same output for ihex and bin:
[0x00000000]> om
 1 fd: 3 +0x00000000 0x00000000 - 0x00000ead -r-x

**Comment by radare** [comment]
you can use io.0xff=0 to make r2 behave like objcopy by default

**Comment by Maijin** [comment]
Maybe when opening with ihex:// this should be set by default ?

**Comment by radare** [comment]
I think the default should be 0xff to be 0 on interleaved regions and ff for unallocated. But this must be done in the ihex plugin itself

**Comment by brainstorm** [comment]
I can confirm this bug with my AVR firmwares, I've observed same insights and issues. The problems  seem to start early by i.e not detecting/enforcing arch bits correctly:

```
motor1 romanvg$ r2 -aavr -b16 flash_blc.bin
 -- Hang in there, Baby!
[0x00000026]>
```

```
motor1 romanvg$ r2 -aavr -b16 ihex://eeprom_blc.hex
Cannot set bits 64 to 'avr'
Cannot set bits 64 to 'avr'
 -- Welcome back, lazy human!
[0x00000000]>
```

**Comment by brainstorm** [comment]
I can confirm the issue, same symptoms and the analysis for my AVR ESC firmwares seems to differ a bit from the bin (left hand side) to the hex (right hand side):

<img width="1137" alt="skarmavbild 2018-04-22 kl 16 58 19" src="https://user-images.githubusercontent.com/175587/39092319-a99a9444-464e-11e8-9329-0b36faa4cd02.png">

**Comment by radare** [comment]
Whats the point in blaming the graph when its a problem with the io?

**Comment by radare** [comment]
Any noticeable difference in the io data comparing plain posix io with ihex://? Or it is a glitch? Just open both files side by side and scroll until you see a difference

**Comment by brainstorm** [comment]
I did precisely that, scrolling for a while in the beginning end and random sections, side by side, and nope, no differences eyeballing the hexes. Here are some screenshots:

<img width="1251" alt="skarmavbild 2018-04-24 kl 13 44 26" src="https://user-images.githubusercontent.com/175587/39165016-b6cff15e-47c5-11e8-873a-253d7ac92c86.png">
<img width="1233" alt="skarmavbild 2018-04-24 kl 13 44 02" src="https://user-images.githubusercontent.com/175587/39165018-b72ea032-47c5-11e8-8566-c0f4358173f5.png">
<img width="1277" alt="skarmavbild 2018-04-24 kl 13 43 37" src="https://user-images.githubusercontent.com/175587/39165019-b76a9c7c-47c5-11e8-93d9-7b39c3196e40.png">

The corresponding `hex` and `bin` were uploaded to the AVR ESIL Telegram channel a couple of days ago.

**Comment by radare** [comment]
The problem is that the analysis don't have a way to detect if the read operation fails because it reads 000000 or ffffffs, even if the hexdump shows 0000s. So if you objdump with 0xff instead of 0x00 you will get same behaviour in both files.

this is a bug in the way io.0xff eval var is managed.

**Comment by radare** [comment]
Probably the same issue as https://github.com/radare/radare2-regressions/pull/1574

**Comment by brainstorm** [comment]
Similar errors on my side with `e io.unalloc=true` in ~/.radare2rc:

```
$ r2 ~/dev/esc_ardrone/avr_russians/motor1/flash_blc.hex
 -- git pull now
[0x00000000]> aaaa
[Invalid instruction of 4054 bytes at 0x2and entry0 (aa)
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Enable constraint types analysis for variables
```

```
$ r2 ~/dev/esc_ardrone/avr_russians/motor1/flash_blc.bin
WARNING: Plugin avr should implement load_buffer method instead of load_bytes.
 -- vm is like a small cow in ascii
[0x00000026]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Finding xrefs in noncode section with anal.in = 'io.maps'
[x] Analyze value pointers (aav)
[x] Value from 0x00000000 to 0x00001f42 (aav)
[x] 0x00000000-0x00001f42 in 0x0-0x1f42 (aav)
[x] Emulate code to find computed references (aae)
[SPM: I dont know what to do with SPMCSR 00.
SPM: I dont know what to do with SPMCSR 00.
SPM: I dont know what to do with SPMCSR 00.
[x] Analyze function calls (aac)
[SPM: I dont know what to do with SPMCSR 00.ferences (aar)
SPM: I dont know what to do with SPMCSR 00.
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
SPM: I dont know what to do with SPMCSR 00.
[x] Enable constraint types analysis for variables
```

**Comment by radare** [comment]
in the debugger i also observe some differences when doing the analysis. may be related

**Comment by brainstorm** [comment]
Tested locally right now both ihex:// and .bin locally, finally the analysis is consistent (equal) on both formats, well done folks! :)

Thanks @Maijin for the heads up on testing this ;)

**Comment by radare** [comment]
awesome <3 took 3 years to catch this bug
