### ISSUE TITLE
r2 debugging mode not working

### ISSUE THREAD

**Issue by alisonliu** [radare/radare2#8515]
I am using Kali Linux and I have radare2  1.7.0-git 16064. I got "ptrace (PT_ATTACH): operation not permitted" error every time I tried to reopen the process in debugging mode using `doo [argument]` or using `r2 -d [pid]`.
<img width="787" alt="test" src="https://user-images.githubusercontent.com/22718011/30458550-f1afa6fc-9960-11e7-81aa-f774112e5177.png">

This issue just occurred recently. The value for "/proc/sys/kernel/yama/ptrace_scope" is 0 so it is not a privilege issue.

**Comment by radare** [comment]
debugger works fine, its just a warning trying to attach more than once to the same pid, which can be ignored
