### ISSUE TITLE
ob output is not correct and confusing

### ISSUE THREAD

**Issue by radare** [radare/radare2#8526]
```
cp /bin/ls ls
cat /bin/ls >> ls
r2 -n ls
> s $s/2
> oba
> ob
binfile fd=3 name=ls id=0
objid=1671 arch=x86 bits=64 boffset=0x0000 size=0x12dc0 
```

several wrong things here:

* 2 lines of output for a single binobj?
* boffset should not be 0
* be consistent with the output of 'o' and such

**Comment by radare** [comment]
also, why `r2 -` have a binobj when no bin plugin have parsed anything ?

**Comment by condret** [comment]
because of bin_any

**Comment by radare** [comment]
Also, the output of ob* and obq is not good either

**Comment by radare** [comment]
Fixed ob in master

**Comment by radare** [comment]
we need ob* and obq
