### ISSUE TITLE
could not map file properly in 16 bits

### ISSUE THREAD

**Issue by merinoffff** [radare/radare2#8551]
I'm trying to map a section in memory that gets mapped from a firmware.
```
[0000:0100]> o ./f000.bin f000:0000
4

```
```
[0x00000100]> o
[...]
 4 * -r-x 0x0000ffff ./f000.bin
```

I tried 0xf000:0000, 0xf0000000 - it's just wrong. Moreover, it get's out of 16 bit to the protected (?) mode, as you can see from the prompt.

Ugh, and hi everyone :)

**Comment by merinoffff** [comment]
Cross out protected. It's segoff.
`[0000:0100]> o ./f000.bin 0xf000:0x0000
4
[0x00000100]> e asm.segoff
false
[0x00000100]> e asm.segoff=true
[0000:0100]>
`

**Comment by radare** [comment]
0xf000:0x0000 is not the same as f000:0000

**Comment by radare** [comment]
also bear in mind that 16bit addressing have some addresses accessible from two different offsets because of the overlapped segment addressing

**Comment by merinoffff** [comment]
> 0xf000:0x0000 is not the same as f000:0000

I understand it, but not sure about radare2. In dos debuggers the later is used. In radare I guess the former. Either turns out to lead to wrong behaviour (and 0xf0000000 as well). So which is it?

> also bear in mind that 16bit addressing have some addresses accessible from two different offsets because of the overlapped segment addressing

Not sure if I get you. I'd be glad if you tossed me a link or enlightened me. Thanks in advance!

**Comment by merinoffff** [comment]
Ok, I fooled around a little and here's the whole story. I'm trying to debug a 16bit dos program, that handles firmware. So I loaded it as 16bit -e asm.bits=16. I can 'search' memory like 0xf000:0 etc, but when I load a file, it goes back to segmented mode. I'm not sure if it is expected behaviour. 

Moreover. My file is 65k long - 0xffff (f000.bin), it is exactly one segment f000:0000 from a live dos running program. And I cannot map it to the lower segment like 0x1:0x0, within 640k or 1meg (UMA) like in DOS.

If I'm misusing radare2 and there is another way of doing things please let me know. But now I'm kinda stuck within 16 bit memory addressing, which supposed to be larger (e.g. video memory in DOS - 0xA000:0000), when using 16 bit code.

**Comment by merinoffff** [comment]
I guess, I will have to rest my case. It's just that I was mislead somehow, but now it works as expected. The only thing is that it keeps disabling asm.segoff. I can fill in a separate ticket for this, sorry for inconvenience.

**Comment by radare** [comment]
sure, fill another issue to track this issue.

thanks
