### ISSUE TITLE
Breakpoints not working in esil mode

### ISSUE THREAD

**Issue by radare** [radare/radare2#8552]
```
$ r2 /bin/ls
> db $$
Cannot place a breakpoint on ... unmapped memory. see dbg.inmaps
```

**Comment by Maijin** [comment]
But works in visual mode :/

**Comment by radare** [comment]
*magic*

**Comment by condret** [comment]
breakpoints are interrupts, at least for x86, so, why should they work in esil, you can use aesu here

**Comment by XVilka** [comment]
But why not?

**Comment by fcasal** [comment]
Esil emulation now stops at breakpoints: https://github.com/radare/radare2/commit/9a83761c6df6c483160e6c1ec43c4a50b36f64e2
@Maijin it works in visual mode because it uses `dbs` instead of `db` which does not check if the address is valid

**Comment by Maijin** [comment]
Ok then closing here
