### ISSUE TITLE
main for dlang programs should be _Dmain

### ISSUE THREAD

**Issue by radare** [radare/radare2#8573]
<img width="1371" alt="screen shot 2017-09-19 at 23 01 34" src="https://user-images.githubusercontent.com/917142/30615267-ad995ce2-9d8e-11e7-8551-9c0a1b40ea7f.png">

**Comment by MaskRay** [comment]
If `dmd -betterC a.d` is used, it is still called `main`

`extern(C) void main() {}`

**Comment by radare** [comment]
betterC binaries doesnt have the Dmain symbol, so nothing changes
