### ISSUE TITLE
use multiples io plugins with radare2

### ISSUE THREAD

**Issue by ikanekb** [radare/radare2#8579]
Hi,

I am trying to use different io plugins at the same time with radare2 and I found a weird behavior:

The commands supported by the io plugins are seen in radare2 by the backslash  (e.g.: when using r2k:// the print kernel memory map is \M)

2.- if you use 2 io plugins at the same time for example "r2 r2k:// frida:///executable". The backslash are mapped only to the ones from the last io. So in my example radare will only show the ones from frida, in the other way around if the last one is r2k, only the ones from r2k.

Is it normal? 

Thanks a lot

**Comment by radare** [comment]
The backslash prefix is an alias for =! And that only works with the priorized fd. Try selecting a different fd with ‘o’

**Comment by ikanekb** [comment]
Cool and it works really well with o command, it allows firstly identify the opened files (o=) and then switch between them using the (o fd) which will remapped automatically the backslash (=!) to the supported commands on the io plugin.

Thanks a lot
