### ISSUE TITLE
pd shows invalid opcodes (winedbg session)

### ISSUE THREAD

**Issue by zaplo00** [radare/radare2#8581]
pd shows invalid opcodes if number is divisible by 2:
![example](https://i.imgur.com/pkhq239.png)

I tested with https://github.com/radare/radare2/files/1266724/dsadsd.zip
r2 commit: fc6cc69e9002a8e3cb84d94413b6736822eaa74e build: 2017-09-23__13:55:53

**Comment by radare** [comment]
cant reproduce

**Comment by zaplo00** [comment]
FYI, tested with Arch Linux x86_64 fully updated as of 23.09.2017 and radare2-git package built from AUR

**Comment by Maijin** [comment]
what's the output of r2 -v

**Comment by zaplo00** [comment]
version shown in first comment.

**Comment by radare** [comment]
try again i fixed an issue in the gdb read operation

**Comment by zaplo00** [comment]
It works now.
