### ISSUE TITLE
[WINDOWS] Radare2 does not find symbols of non-exported functions inside ntdll.dll

### ISSUE THREAD

**Issue by Sn00z3r** [radare/radare2#8584]
All,

Could be due to my limited knowledge on the radare2 framework, but I can't seem to get the symbols loaded for LdrpHandleTlsData and RtlInsertInvertedFunctionTable (two non exported functions in ntdll.dll).

IDA pro does find the symbols and loads them successfully, but radare2 prints these functions out as fcn.xxxxxx.

Best regards!

**Comment by radare** [comment]
probably because of pdb. use the idp command

**Comment by Sn00z3r** [comment]
Dear,

Correct, when I run idp* I get the following output:

Missing expand
PDB "ntdll.pdb" download failed
FixMe: Could not read file descriptor
Unable to find filedescriptor 0

Not sure how to fix it, ntdll.pdb is in path
