### ISSUE TITLE
Curvy lines like in tig

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8586]
Would be nice to have this https://github.com/jonas/tig/issues/711
![](https://user-images.githubusercontent.com/9303/30811681-e830513e-a1d6-11e7-9f80-f7ab31953d11.png)

**Comment by radare** [comment]
pls paste the utf8 hex codes for this

**Comment by nullableVoidPtr** [comment]
| character | hexcode |
|--|--|
|╭|256D|
|╮|256E|
|╯|256F|
|╰|2570|

**Comment by radare** [comment]
looks cool (and easy to implement)

**Comment by nullableVoidPtr** [comment]
What would be the config for this? `scr.utf8.curvy`?

**Comment by radare** [comment]
for example, yep

**Comment by SrimantaBarua** [comment]
Putting this in disassembly is easy. But in visual graph it's not so simple because `r_cons_canvas_gotoxy ()` doesn't play well with multi-byte characters.

**Comment by radare** [comment]
It works with str.replace before canvas.flush iirc

**Comment by SrimantaBarua** [comment]
Done, #8660
