### ISSUE TITLE
Bad disassembly of Android fill-array-data branch

### ISSUE THREAD

**Issue by cryptax** [radare/radare2#8590]
The branch offset of the `fill-array-data` opcode for Dalvik executables is badly disassembled.

Example:
```
0x0007c364      23200b0d       new-array v0, v2, [B        ; 0x133f4 ; construct a new array of the indicated type and size 
0x0007c368      260078000000   fill-array-data v0, 0x0007c3e0 ; 0x101a8 ; fill the given array with the indicated data 
```

26 -> opcode for `fill-array-data` (correct)
00 -> v0 (correct)
78000000 -> This is the "offset to table data pseudo-instruction", it is **not** the offset from the current position as radare2 seems to imply. You must go and have a look at table[0x78] to find the correct output.

So in `fill-array-data v0, 0x0007c3e` as shown from Radare, `0x0007c3e` is **wrong**. And indeed, you'll see there is not `fill-array-data-payload` at that address.

See `androguard` which does it correctly:

Code to display the byte code & disassembly in Androguard:

```python
for i in d.CLASS_La_d_d.METHOD_clinit.get_instructions():
   print 'Byte code: %s' % (''.join([ '%02x ' % (ord(x)) for x in i.get_raw()]))
   print 'Disassembly: %s %s' % (i.get_name(), i.show_buff(0))
   print '--------------'
```

which shows:
```
Byte code: 26 00 78 00 00 00 
Disassembly: fill-array-data v0, +78 (0xf0)
```

And indeed, we find fill-array-data-payload at 0x0007c368 + 0xf0 = 0x7c458.

**To reproduce**, I am using Android/Ztorg malware sha256 `2c546ad7f102f2f345f30f556b8d8162bd365a7f1a52967fce906d46a2b0dac4` and looking into `pd 10 @ @ sym.La_d_d.method._clinit___V`.

You can [download the sample from Koodous](https://koodous.com/apks/2c546ad7f102f2f345f30f556b8d8162bd365a7f1a52967fce906d46a2b0dac4), beware however that it is malicious.

**Comment by radare** [comment]
where’s this 0xf0 coming from?

**Comment by radare** [comment]
dexdump shows the same as r2, there’s no 0xf0 in dexdump or r2

**Comment by cryptax** [comment]
The 0xf0 comes from the entry at table[0x78] I guess. But it is indeed correct.

Look we have the array declaration at 0x0007c368

```
           0x0007c364      23200b0d       new-array v0, v2, [B        ; 0x133f4 ; construct a new array of the indicated type and size 
│           0x0007c368      260078000000   fill-array-data v0, 0x0007c3e0 ; 0x101a8 ; fill the given array with the indicated data 
```

**Radare2** says I have the array at `0x0007c3e0`. This is **wrong**. This actually points to a zone with more Dalvik code.

```
px 10 @ 0x0007c3e0
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x0007c3e0  0c00 2300 0b0d 2600 8300                 ..#...&...
pd 2 @ 0x0007c3e0
│           0x0007c3e0      0c00           move-result-object v0       ; move the object result of the most recent invoke-kind into the indicated registe 
│           0x0007c3e2      23000b0d       new-array v0, v0, [B        ; 0x133f4 ; construct a new array of the indicated type and size 
```

On the contrary, if like androguard says we go to 0x0007c368 + 0xf0, we have the **payload**!

```
pd 2 @ (0x0007c368+0xf0)
            0x0007c458      000301001500.  fill-array-data-payload 1, 21
; .. payload of 21 bytes                                               
            0x0007c476      0000           nop                         ; no operation 
```

**Comment by h4ng3r** [comment]
Hi, I'm quite busy right now but I think that this is an error, as @cryptax has said the address is incorrect and I'll fix it this weekend. Thanks for filling an issue, is good to know that someone is using r2 for Android ;).

**Comment by cryptax** [comment]
@h4ng3r no problem, take the time you need. It's not urgent, but it's just there to keep track of.

**Comment by radare** [comment]
??

i have already fixed this can you provide a test case?

**Comment by radare** [comment]
> On 28 Sep 2017, at 08:43, cryptax <notifications@github.com> wrote:
> 
> dexdump shows the same as r2, there’s no 0xf0 in dexdump or r2
> 
> No, dexdump does not show the same as r2. Yes, it does not show 0xf0 which is a helper. I'll explain below.
> 
> This is what dexdump shows:
> 
> 07c368: 2600 7800 0000                         |0006: fill-array-data v0, 0000007e // +00000078
> This is what radare shows:
> 
> 0x0007c368      260078000000   fill-array-data v0, 0x0007c3e0 ; 0x101a8 ; fill the given array with the indicated data 
> Note the difference in the offset: dexdump shows 0000007e // +00000078 whereas radare shows 0x0007c3e0 ; 0x101a8.
> 
> Now, the rest of the output of dexdump explains what this 0000007e is.
> If we go at the address 0x07c458 (=0x0007c368 +0xf0) in dexdump, we see indeed our array:
> 
> 07c458: 0003 0100 1500 0000 0d49 424b 4444 ... |007e: array-data (15 units)
> 07c476: 0000                                   |008d: nop // spacer
> 07c478: 0003 0100 1b00 0000 5816 5956 5c4a ... |008e: array-data (18 units)
> 07c49c: 0003 0100 0400 0000 0c31 265a          |00a0: array-data (6 units)
> 07c4a8: 0003 0100 0500 0000 576c 6d6c 0a00     |00a6: array-data (7 units)
> 07c4b6: 0000                                   |00ad: nop // spacer
> 07c4b8: 0003 0100 2900 0000 6622 3e3e 3a70 ... |00ae: array-data (25 units)
> 07c4ea: 0000                                   |00c7: nop // spacer
> 07c4ec: 0003 0100 0c00 0000 5016 5956 5c4a ... |00c8: array-data (10 units)
> 07c500: 0003 0100 0900 0000 7d47 4142 0d49 ... |00d2: array-data (9 units)
> 07c512: 0000                                   |00db: nop // spacer
> Notice the indexes 007e, 008e, 00a0 etc: they are the entries in the array table. That's why we have a 007e in dexdump!
> 
> So:
> 
> dexdump shows 007e, where 007e is the index in the table array. This is correct, conform to the specs, though perhaps less helpful than what androguard outputs because we have to search for the beginning of the table array to find our entry.
> radare shows 0x0007c3e0 which is =0x07c368 +0x78. But this is wrong because 0078 is not an offset from that location of the code.

false, this is not what r2 outputs after my fix. pls git pull and confirm

**Comment by cryptax** [comment]
oh right I didn't you had fixed. Let me check.

**Comment by Maijin** [comment]
![image](https://user-images.githubusercontent.com/1408600/30983930-2b1f5820-a48c-11e7-8a52-7512e48a76bd.png)

**Comment by cryptax** [comment]
We now have 
```
0x0007c368      260078000000   fill-array-data v0, 0x0007c452 ; 0x101a8 ; fill the given array with the indicated data
```

but 0x0007c452 is not the right address. I'd expect either 0x0007c458, which is the beginning of the fill-array-data-payload instruction, or 0x0x0007c458 + 8 which is the beginning of the array data
or `fill-array-data v0, 0000007e` (like dexdump), or `fill-array-data v0, +78` (like androguard).

```
  0x0007c458      000301001500.  fill-array-data-payload 1, 21
; .. payload of 21 bytes                                               
```

**Comment by radare** [comment]
so, substracting the instruction size like the documentation says is not correct?

**Comment by radare** [comment]
for me it makes more sense to use +8 to point to the actual data, what do you think? also, can you write a test?

**Comment by h4ng3r** [comment]
I think that will be easier for the analyzer and emulator if we point to the actual data, otherwise each time we need to do the +8.

**Comment by radare** [comment]
try again pls

**Comment by cryptax** [comment]
Yes it works! Well done!
Thanks!

```
   0x0007c368      260078000000   fill-array-data v0, 0x0007c460 ; 0x101a8 ; fill the given array with the indicated data 
...
    0x0007c458      000301001500.  fill-array-data-payload 1, 21
; .. payload of 21 bytes        

[0x00084fb0]> px 21 @ 0x0007c460
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x0007c460  0d49 424b 4444 4f46 0549 424b 4444 4f46  .IBKDDOF.IBKDDOF
0x0007c470  045e 525e 27                             .^R^'
                        
```

**Comment by radare** [comment]
Thanks!

**Comment by Maijin** [comment]
@cryptax https://github.com/radare/radare2-regressions/blob/master/t.anal/dalvik/dalvik

**Comment by Maijin** [comment]
add tests please
