### ISSUE TITLE
Not to include special characters in the string (flag) names

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8596]
Like `\n`, `\r` or `\t`.

**Comment by radare** [comment]
Wat

**Comment by XVilka** [comment]
For example if the string is `Hello World\n`, then it will print - `str.Hello_World_n`. I am suggesting not to include those symbols in the flag (string) name.

**Comment by Maijin** [comment]
why? it's useful

**Comment by radare** [comment]
Its not useful. Its as useful as putting / in a directory name

**Comment by fdennis** [comment]
I would like to contribute. But I want to clarify something first. Do you mean, for example, when disassembling a function by calling "pdf @ main", and a line looks like :

`0x08000000	5555555	mov dword [esp], str.Hello_World_n`

Or is it something else you're talking about?

**Comment by radare** [comment]
The flag in this case should be str.Hello_World without the _n

**Comment by fdennis** [comment]
Great, thanks. I am not that familiar with the source code tree but would like to contribute. Any idea on what files could be interesting for this issue or where I should start?

**Comment by radare** [comment]
see r_flag_filter and such
