### ISSUE TITLE
[Windows] Loaded pdb, but symbols are not correct

### ISSUE THREAD

**Issue by Sn00z3r** [radare/radare2#8599]
Dear,

Loaded ntdll with radare2:
>> radare2.exe -A ntdll.dll

Loaded pdb file
>> .idp*

But still functions are in the form of fcn....
What am I missing here?

Best regards!

**Comment by XVilka** [comment]
Please provide the sample file[s]. Are you sure the PDB is of the right version?

**Comment by XVilka** [comment]
@Sn00z3r PING!

**Comment by Maijin** [comment]
.idp* is now idp and should be typed before analysis. Remove -A, do idp then do `aaa`

Without the files we can't reproduce therefore I'm closing until this can be reproduced and file provided.
