### ISSUE TITLE
Adding some flags to the compiler

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#861]
What about adding some flags to gcc/clang:

- `-Wno-unused-parameter`
- `-Wno-unused-function` (at least, temporarily.)

This will greatly reduce the current noise.

**Comment by dequis** [comment]
pancake said in #883:

>We have discused on irc that it would be better not to hide the warnings in CFLAGS, because warnings are important, we can use the UNUSED define from r_types.h to use the gcc attribuets to hide the java warnings.. Also, other kind of warnings should be addressed by fixing them.

Close this?
