### ISSUE TITLE
Do not perform analysis if there is no analysis plugin

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8612]
If there is only one disasm plugin r2 still tries to perform analysis using default analysis plugin and draws completely unrelated reflines, adding meaningless comments, etc.

**Comment by Maijin** [comment]
That would be great indeed!

**Comment by Maijin** [comment]
setting-up e asm.anal=null for those architecture, the issue is that ranal RAnalPlugin arch only takes one arch as argument :/ @radare ?

**Comment by radare** [comment]
What do you mean?

**Comment by Maijin** [comment]
The current way we define what disassembler an anal plugin is used for is via RAnalPlugin->arch. But currently we can only assign 1 architecture for a given anal plugin :/

**Comment by radare** [comment]
null plugin is not binded to any arch, why do you need more?
