### ISSUE TITLE
Attaching to running process issue

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#8622]
I'm getting an 'w32_reg_read/GetThreadContext: The handle is invalid.' error when trying to attach with r2 to a running application (on Windows). 

> radare2.exe -d 33188

> = attach 33188 19324
> = attach 33188 0
> w32_reg_read/GetThreadContext: The handle is invalid.
> asm.bits 32
> w32_reg_read/GetThreadContext: The handle is invalid.
>....
>[0x00000000]>

The full log is here: https://gist.github.com/pawlos/9d7e28922beb367e93f04404cf0484f3 (there's not much more than mor of those logs).

OS: Windows 10
r2: version 1.7 from http://bin.rada.re/radare2-w32-1.7.0-git.zip

**Comment by XVilka** [comment]
@xarkes can you please check this one asap?

**Comment by xarkes** [comment]
Yeah will do

**Comment by xarkes** [comment]
I investigated. This is because `fork_and_ptraceme` sets the winbase to `DEBUG_EVENT.u.CreateProcessInfo.lpBaseOfImage` (called in io_debug.c __open()) while the winbase is never set when you pass a PID.
Will try a fix later.

**Comment by pawlos** [comment]
works now. thx
