### ISSUE TITLE
i cannot install radare2 in Fedora 26

### ISSUE THREAD

**Issue by gerohelguera** [radare/radare2#8631]
Hi, i'm with Fedora 26 (32-bit) i get radare2 from git then i execute(root) `sys/install.sh` and i get this output(the last 10 lines):
`cp: './plugins.cfg' and 'plugins.cfg' are the same file
checking build system type... i686-unknown-linux-gnu
checking host system type... i686-unknown-linux-gnu
checking target system type... i686-unknown-linux-gnu
checking for working directories... current
using prefix '/usr'
checking for c compiler... gcc
checking for dynamic library... required
checking for patch... no
error: This program is required.
`

**Comment by XVilka** [comment]
dnf install patch

**Comment by XVilka** [comment]
Reopen if wont be able to build after that.

**Comment by gerohelguera** [comment]
ok, thanks, what type of build do you recommed?
