### ISSUE TITLE
How to flag a function in a library ?

### ISSUE THREAD

**Issue by SnowI5Me** [radare/radare2#8643]
To check dynamically added functions ..  (Getprocaddress)

Thanks in advance for your help.

**Comment by XVilka** [comment]
What? Please be more precise.

**Comment by SnowI5Me** [comment]
The Getprocaddress API retrieves the selected function address from a dynamically loaded library.

Can I add this addresses automatically to the flag?

I know that my explanation is unkind.
I do not know how to explain it...

**Comment by Maijin** [comment]
I'm going to close this, until you can provide more concrete example using other tools etc, because this is very unclear what you want to achieve
