### ISSUE TITLE
[Question] How to change type of variables?

### ISSUE THREAD

**Issue by saruman9** [radare/radare2#8649]
I have a sample of old malware ([sample.zip](https://github.com/radare/radare2/files/1357361/sample.zip), pass - infected). I want to change type of variable to signed (from 0xffffffff to -1):
```
0x0040113b      b8ffffffff     mov eax, 0xffffffff         ; -1
```
In some cases enough change base of variable but not in this. How I can do this?
Or how I can change type of `-0xc1` variable to unsigned?

**Comment by radare** [comment]
ahi 10 @ 0x0040113b

**Comment by saruman9** [comment]
Yes, I do this and get wrong result, that's why I ask.
In sample, which I uploaded:
```
[0x00401000]> s 0x40113b
[0x0040113b]> pd 1
            0x0040113b      b8ffffffff     mov eax, 0xffffffff         ; -1
[0x0040113b]> ahi 10
[0x0040113b]> pd 1
            0x0040113b      b8ffffffff     mov eax, 4294967295         ; 0xffffffff ; -1

```
