### ISSUE TITLE
Errors while loading the rbin structures after sys/install.sh

### ISSUE THREAD

**Issue by darknyaz** [radare/radare2#8651]
I had radare2 preinstalled in my Kali Linux 2017.2. And it was starting normally with -nn option and some pe32 file. But after update radare2 from git repo with executing sys/install.sh script I have following errors each time I run radare2 -nn <some_pe32_file>:

> Cannot find format for struct `pe_image_file_header'
> Cannot resolve struct size
> Cannot find format for struct `pe_image_file_header'
> Cannot find format for struct `pe_image_file_header'
> Undefined struct 'pe_image_file_header'.
> Undefined struct 'pe_image_optional_header32'.
> Cannot find format for struct `pe_image_file_header'
> Cannot resolve struct size
> Cannot find format for struct `pe_image_file_header'
> Cannot find format for struct `pe_image_file_header'
> Undefined struct 'pe_image_file_header'.
> Undefined struct 'pe_image_optional_header32'.
> Cannot find format for struct `pe_image_file_header'
> Cannot resolve struct size
> Cannot find format for struct `pe_image_file_header'
> Cannot find format for struct `pe_image_file_header'
> Undefined struct 'pe_image_file_header'.
> Undefined struct 'pe_image_optional_header32'.
> Cannot find format for struct `pe_image_file_header'
> Cannot resolve struct size
> Cannot find format for struct `pe_image_file_header'
> Cannot find format for struct `pe_image_file_header'
> Undefined struct 'pe_image_file_header'.
> Undefined struct 'pe_image_optional_header32'. 

Please, help me to understand what's the problem?

Addition information: 
I cloned repo into /opt directory as root and started script as root. 
Regardless of errors it seems that all functions work: I can still parse headers, structures and etc.

**Comment by radare** [comment]
did you removed the pkg from kali first? purge it? deleting is not enough for the debian crap pkgsystem

**Comment by darknyaz** [comment]
I tried different ways. And I've just try following again:

>  apt-get --purge autoremove radare2
> sys/install.sh

All stay the same.

**Comment by XVilka** [comment]
Check `/usr/local/share/radare2` or `/usr/share/radare2` for old files and check if new ones are installed - particularily `format` directory.

**Comment by darknyaz** [comment]
In `/usr/share/radare2` there are new files, but in `/usr/local/share/radare2` there are old.

**Comment by darknyaz** [comment]
Copying new files to `/usr/local/share/radare2` doesn't help.

**Comment by Maijin** [comment]
Make sure you clean all the previous install before installing the new radare2 including pkg-config, capstone etc.

**Comment by darknyaz** [comment]
`apt-get --purge autoremove radare2` must clean previous install and configuration. Do you mean that I need to reinstall all packages from dependency tree before running `sys/install.sh`? Every time?

**Comment by Maijin** [comment]
"In /usr/share/radare2 there are new files, but in /usr/local/share/radare2 there are old."

So it seems you didn't clean everything (folder etc.), please clean everything completly on the machine including the system capstone package.

`make purge2 && make purge && make clean` etc.

And no, once you have proper environment only launching ./sys/install.sh don't even need to pull.

This issue is only on your side :/

**Comment by darknyaz** [comment]
Do you mean `libcapstone3` package when you're talking about system capstone package? I had tried to purge it but it didn't help.

I also haven't found what package stores files in `/usr/local/share/radare2`. I've deleted it and it isn't appearing when I'm installing radare2 from kali package or git repo anymore.

I had checked that packages `libcapstone3`, `libradare2-1.6`, `libradare2-common` and `radare2` had been removed with their files before I started `sys/install.sh`. I'd checked that all files from `dpkg -L` output had been deleted.

I understand that problem in my system and I appreciate you attention. But can you please explain me what do this errors point to? And how is radare2 still parsing PE32 after producing this errors?

**Comment by radare** [comment]
r2 have its own version of capstone linked statically

**Comment by radare** [comment]
if you type make purge it shuold remove all previous installations of r2 in the system. you can try with strace and check the paths that it tries to access

**Comment by darknyaz** [comment]
I've tried `make purge`. The same problem after it.

So if radare2 linked statically with capstone then why should I delete the system capstone? Is problem in the capstone? I have `libcapstone3` and `python-capstone` installed in my system.

**Comment by radare** [comment]
I dont see why this should affect at all, nobody said to uninstall capstone from system.

This is a regression and i can reproduce it on mac

**Comment by Maijin** [comment]
Ok so the initial issue with "cannot find etc." have nothing to do with install, this is linked to the hardcoded sdb stuff here https://github.com/radare/radare2/blob/master/libr/bin/format/pe/pe.c#L558 ; not really sure what causing the trouble, inverting the order doesn't fix it, but removing the if/else remove the messages

**Comment by darknyaz** [comment]
Thank you for fixing this!
