### ISSUE TITLE
Cross-Compiling for iOS: Static library libr.a is broken

### ISSUE THREAD

**Issue by YugoCode** [radare/radare2#8654]
When you use sys/ios-sdk.sh or sys/ios-static.sh the resulting libr.a seems to be broken:

`lipo -info libr.a `

> fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: archive with no architecture specification: libr.a (can't determine architecture for it)

`nm -a libr.a`

> [No output]

So here definitely something is not working right, because no symbols are printed. 

When I'm extracting the static libraries from libr.a with `ar -x libr.a ` and then linking them with `libtool -static -o newlibr.a *.a` both commands will return correct output. 

But the linking doesn't seem to be working as a lot of symbols are unresolved and Xcode also complains about them, when using the static library.

**Comment by radare** [comment]
This index is created by ranlib, it should be executed after ar. Ill have a look

**Comment by radare** [comment]
pushed the fix, but its only for 1 arch for now. will improve later

**Comment by radare** [comment]
can you update the ios-sdk.sh to do that? or the makefile by sending a PR? im kinda busy with other 9000 things right now

**Comment by YugoCode** [comment]
Sure, will do it. If I ran into some problems or questions, I will ask here.

**Comment by YugoCode** [comment]
Added support for all arm archs and the simulator(i386 and x86_64) with https://github.com/radare/radare2/pull/8775

**Comment by radare** [comment]
awesome
