### ISSUE TITLE
Fail to dump bytes in UEFI TE images in r2 2.0.0

### ISSUE THREAD

**Issue by mytbk** [radare/radare2#8677]
For example https://vimacs.lcpu.club/te.bin, which r2 opens and seeks at 0x350. In r2 1.6.0, "x" dumps 256 bytes, not all of which are 0xff, but in r2 2.0.0 it gives 0xff's. "s 0" after opening the file also gives 0xff's in r2 2.0.0.

Bisecting r2 shows 2f201bded0df2626ad57debb6a9c6a52dced682a is the bad commit, but it's too huge for me to see what caused the bug.

**Comment by radare** [comment]
Because pa != va

**Comment by mytbk** [comment]
@radare but r2 1.6.0 works well with this and can use pd to disassemble.

**Comment by Maijin** [comment]
Yes because now by default only the mapped stuff is displayed, you can have previous behavior by doing:` e io.va = false` or better open the binary flat using `r2 -nn te.bin`

**Comment by mytbk** [comment]
``e io.va = false`` is good to me
