### ISSUE TITLE
Radare freezes in Visual mode sys.in -> stepping

### ISSUE THREAD

**Issue by THEPADA** [radare/radare2#8684]
Hey,

I've an Error with radare2.
When I'm in Debug mode, stepping through a programm, everytime i get to an "call sym.imp.getline" radare freezes and i cant make an input into the console.

I would be very happy, whether one of you guys could help me out :)

A few infos:
radare -v:radare2 1.6.0 0 @ linux-x86-64 git.1.6.0
commit: HEAD build: 2017-07-12__22:52:3
uname -a: Linux myhost 4.13.4-1-ARCH #1 SMP PREEMPT Thu Sep 28 08:39:52 CEST 2017 x86_64 GNU/Linux

thanks alot :)

**Comment by radare** [comment]
it hangs because it tries to read a line, type the input and press enter and it should work

**Comment by Maijin** [comment]
And use rarun2 to redirect the stdin to a different tty to avoid this issue. man rarun2
