### ISSUE TITLE
two binaries do not respect DISTDIR

### ISSUE THREAD

**Issue by blshkv** [radare/radare2#8688]
here  we are:
```
/usr/bin/r2-indent -> /var/tmp/portage/dev-util/radare2-2.0.1/work/radare2-2.0.1/sys/indent.sh
/usr/bin/r2-docker -> /var/tmp/portage/dev-util/radare2-2.0.1/work/radare2-2.0.1/sys/r2-docker.sh
```

I'm compiling radare2 in a sandbox with DISTDIR specified. However, after the installation these two links are pointing to a wrong location.

**Comment by blshkv** [comment]
actually, the entire /sys directory is not getting installed. That's the main reason.

However, it seems that both binaries are not required for a usual user so it should be safe just not to install them (remove ```ln``` lines).

**Comment by radare** [comment]
Thanks! Good catch. Will fix now

**Comment by radare** [comment]
im not installing those scripts with make install anymore. so we can close this issue.

i’ll make them available via r2pm at some point because they require access to the r2 source directory to work
