### ISSUE TITLE
Error when installing on windows: "cannot find -lpthread"

### ISSUE THREAD

**Issue by andresantacruz** [radare/radare2#8695]
I'm following this link ( https://radare.gitbooks.io/radare2book/content/introduction/windows_compilation.html#mingw32 ) and calling sys/mingw32.bat. After some time compiling, I get the error output bellow.

> c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [libr2.dll] Error 1
> make[2]: Leaving directory `/d/OSDefault/Documents/RCETools/radare2/binr/preload'
> make[1]: *** [preload] Error 2
> make[1]: Leaving directory `/d/OSDefault/Documents/RCETools/radare2/binr'
> make: *** [all] Error 2

I don't know much about linux way of doing things so I'm probably messing something simple.

As I didn't find which specific binaries I should get from mingw, I installed some basic ones (gcc, zip, etc). Could it be some missing mingw executable?

Oh, as the compilation output goes frantically I can see a lot of warnings on code, is that expected in a right environment?

Thanks.

**Comment by andresantacruz** [comment]
Additional info I found in the output that may be useful (I think it's the output from ./configure  file):

> Using PATH = C:\MinGW\bin;"C:\Program Files\Git"\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\ptr0x\AppData\Local\Microsoft\WindowsApps;C:\Users\ptr0x\AppData\Roaming\Dashlane\4.8.9.37516\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\ptr0x\AppData\Roaming\Dashlane\4.8.9.37516\ucrt;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\MinGW\bin;C:\MinGW\msys\1.0\bin ...
> "Read version from configure.acr: 2.1.0-git"
> Using built-in specs.
> COLLECT_GCC=C:\MinGW\bin\gcc.exe
> COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
> Target: mingw32
> Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
> Thread model: win32
> gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
> mingw64_nt-10.0
> CC=
> configure-plugins: Loading ./plugins.cfg ..
> configure-plugins: Generating libr/config.h ..
> configure-plugins: Generating libr/config.mk ..
> SHARED: io.shm
> STATIC: anal.6502 anal.8051 anal.arc anal.arm_cs anal.arm_gnu anal.avr anal.bf anal.cr16 anal.cris anal.dalvik anal.ebc anal.gb anal.h8300 anal.i4004 anal.i8080 anal.java anal.m68k_cs anal.malbolge anal.mips_cs anal.mips_gnu anal.msp430 anal.nios2 anal.null anal.pic18c anal.ppc_cs anal.ppc_gnu anal.riscv anal.rsp anal.sh anal.snes anal.sparc_cs anal.sparc_gnu anal.sysz anal.tms320 anal.v810 anal.v850 anal.vax anal.ws anal.x86_cs anal.x86_udis anal.xap anal.xcore_cs anal.z80 asm.6502 asm.8051 asm.arc asm.arm_as asm.arm_cs asm.arm_gnu asm.arm_winedbg asm.avr asm.bf asm.cr16 asm.cris_gnu asm.dalvik asm.dcpu16 asm.ebc asm.evm asm.gb asm.h8300 asm.hexagon_gnu asm.hppa_gnu asm.i4004 asm.i8080 asm.java asm.lanai_gnu asm.lh5801 asm.lm32 asm.m68k_cs asm.malbolge asm.mcs96 asm.mips_cs asm.mips_gnu asm.msp430 asm.nios2 asm.pic18c asm.ppc_cs asm.ppc_gnu asm.riscv asm.rsp asm.sh asm.snes asm.sparc_cs asm.sparc_gnu asm.spc700 asm.sysz asm.tms320 asm.tricore asm.v810 asm.v850 asm.vax asm.wasm asm.ws asm.x86_as asm.x86_cs asm.x86_nasm asm.x86_nz asm.x86_udis asm.xap asm.xcore_cs asm.z80 bin.any bin.art bin.avr bin.bf bin.bflt bin.bios bin.bootimg bin.cgc bin.coff bin.dex bin.dol bin.dyldcache bin.elf bin.elf64 bin.fs bin.java bin.mach0 bin.mach064 bin.mbn bin.menuet bin.mz bin.nes bin.nin3ds bin.ninds bin.ningb bin.ningba bin.nro bin.omf bin.p9 bin.pe bin.pe64 bin.pebble bin.psxexe bin.sfc bin.smd bin.sms bin.spc700 bin.te bin.vsf bin.wasm bin.xbe bin.zimg bin_xtr.fatmach0 bin_xtr.xtr_dyldcache bp.arm bp.bf bp.mips bp.ppc bp.x86 core.anal core.java crypto.aes crypto.aes_cbc crypto.base64 crypto.base91 crypto.blowfish crypto.cps2 crypto.des crypto.punycode crypto.rc2 crypto.rc4 crypto.rc6 crypto.rol crypto.ror crypto.rot crypto.xor debug.bf debug.bochs debug.esil debug.gdb debug.io debug.native debug.null debug.qnx debug.rap debug.windbg egg.exec egg.xor fs.ext2 fs.fat fs.fb fs.hfs fs.hfsplus fs.iso9660 fs.jfs fs.minix fs.ntfs fs.posix fs.reiserfs fs.sfs fs.squash fs.tar fs.udf fs.ufs fs.xfs io.ar io.bfdbg io.bochs io.debug io.default io.gdb io.gzip io.http io.ihex io.mach io.malloc io.mmap io.null io.procpid io.ptrace io.qnx io.r2k io.r2pipe io.r2web io.rap io.rbuf io.self io.shm io.sparse io.tcp io.w32 io.w32dbg io.windbg io.winedbg io.zip lang.vala parse.6502_pseudo parse.arm_pseudo parse.att2intel parse.avr_pseudo parse.dalvik_pseudo parse.m68k_pseudo parse.mips_pseudo parse.mreplace parse.ppc_pseudo parse.sh_pseudo parse.x86_pseudo
> /usr/bin/cp: `./plugins.cfg' and `plugins.cfg' are the same file
> checking build system type... i686-unknown-windows-gnu
> checking host system type... i686-unknown-mingw64_nt-6.2-gnu
> checking target system type... i686-unknown-mingw64_nt-6.2-gnu
> checking for working directories... current
> using prefix '/usr/local'
> checking for c compiler... gcc
> checking for dynamic library... libc
> checking for patch... /usr/bin/patch
> checking for git... /mingw64/bin/git
> checking for libmagic ... no
> Using PKGCONFIG: pkg-config
> checking pkg-config flags for capstone... no
> checking for libz ... no
> checking for libzip ... no
> checking for libssl ... no
> Using PKGCONFIG: pkg-config
> checking pkg-config flags for openssl... no
> creating ./config-user.mk
> creating libr/include/r_userconf.h
> creating pkgcfg/r_io.pc
> creating pkgcfg/r_magic.pc
> creating pkgcfg/r_asm.pc
> creating pkgcfg/r_bin.pc
> creating pkgcfg/r_anal.pc
> creating pkgcfg/r_hash.pc
> creating pkgcfg/r_cons.pc
> creating pkgcfg/r_core.pc
> creating pkgcfg/r_lang.pc
> creating pkgcfg/r_socket.pc
> creating pkgcfg/r_debug.pc
> creating pkgcfg/r_reg.pc
> creating pkgcfg/r_config.pc
> creating pkgcfg/r_flag.pc
> creating pkgcfg/r_syscall.pc
> creating pkgcfg/r_util.pc
> creating pkgcfg/r_search.pc
> creating pkgcfg/r_bp.pc
> creating pkgcfg/r_parse.pc
> creating pkgcfg/r_fs.pc
> cleaning temporally files... done
> 
> Final report:
>  - PREFIX = /usr/local
>  - HAVE_LIB_GMP = 0
>  - HAVE_OPENSSL = 0
>  - USE_CAPSTONE = 0
>  - HAVE_FORK = 1
>  - VERSION = 2.1.0-git
>  - USE_LIB_ZIP = 0
>  - USE_LIB_MAGIC = 0
>  - DEBUGGER = 1
>  - CC = gcc
>  - USERCC = gcc
>  - USEROSTYPE = mingw32
>  - LIBVERSION = 2.1.0-git
>  - BUILD = i686-unknown-windows-gnu
>  - HOST = i686-unknown-mingw64_nt-6.2-gnu
>  - TARGET = i686-unknown-mingw64_nt-6.2-gnu

**Comment by xarkes** [comment]
I'm not very familiar with mingw, but you need pthread libraries. Make sure it is installed, it should be named pthread-win32 or something like this.

**Comment by xarkes** [comment]
Also please note that you can find precompiled binaries here:
http://radare.mikelloc.com/get/2.0.1/
radare2-w* are compiled with mingw, and radare2-msvc-* are obvisouly compiled with msvc

**Comment by andresantacruz** [comment]
Thanks for the reply @xarkes I didnt know about this radare repository, will check it out soon.

I'll try and get the pthread-w32 to see if it fix the problem. 

About the warning messages though, you know if it's expected?

**Comment by xarkes** [comment]
Yes it is hard to maintain code that do not generate any warning on every platform, so this is expected.

**Comment by andresantacruz** [comment]
I downloaded the pthread-w32 as you told and the compilation works. Thanks again.

**Comment by diego59x** [comment]
Thanks guys from 2017 :D
