### ISSUE TITLE
rasm2 (x86.nz in 64-bit mode) incorrectly handles displacement-only addressing

### ISSUE THREAD

**Issue by kaka012** [radare/radare2#8701]
`rasm2 -a x86 -b 64 "mov rax, [0xBEEF]"`
yields
`67488b05efbe0000` ~~(correct would be `488b0425efbe0000`)~~.
If we disassemble that
`rasm2 -a x86 -b 64 -d 67488b05efbe0000`
we get
`mov rax, qword [eip + 0xbeef]`.
This only occurs with x86.nz and only in 64-bit mode.

**Comment by kaka012** [comment]
@radare could you please re-open this issue?
It isn't currently fixed on the master branch.
Assembling `"mov rax, [0xbeef]"` still yields `mov rax, qword [eip + 0xbeef]`.

**Comment by Svenito** [comment]
I just tested this and here's what I found.

With _nz_   we get

    $> rasm2 -a x86 -b 64 -d `rasm2 -a x86.nz -b 64 "mov rax, [0xBEEF]"` 
    mov rax, qword [rip + 0xbeef]

With _Keystone_

    $> rasm2 -a x86 -b 64 -d `rasm2 -a x86.ks -b 64 "mov rax, [0xBEEF]"`
    movabs rax, qword [0xbeef]

But this is only the case for `rax`, if you try other registers

    $> rasm2 -a x86 -b 64 -d `rasm2 -a x86.ks -b 64 "mov rcx, [0xBEEF]"`
    mov rcx, qword [rip + 0xbeef]
 
    >$ rasm2 -a x86 -b 64 -d `rasm2 -a x86.nz -b 64 "mov rcx, [0xBEEF]"`
    mov rcx, qword [rip + 0xbeef]

It's the same. Because basically it is an offset from the current address, which is `rip`. 

It's a different story if you compare to `nasm` which does yield

    $> rasm2 -a x86 -b 64 -d `rasm2 -a x86.nasm -b 64 "mov rax, [0xBEEF]"`
    mov rax, qword [0xbeef]

The initial compile was incorrect, as it set the base register to `eip` rather than `rax`. This however is now fixed in the master branch.

**Comment by radare** [comment]
I would expect a mobavs when no rip is involved

**Comment by Svenito** [comment]
but only for the `rax` case? Or do we go the nasm way and just assemble to a regular `mov`?

**Comment by radare** [comment]
well, maybe we can just go and make ‘mov’ always relative and ‘movabs’ always absolute, what’s intel opinion on this?

**Comment by Svenito** [comment]
From what I've managed to pirce together `movabs` is AT&T syntax from the GAS assembler. 

http://cvs.tortall.net/pipermail/yasm-devel/2006-March/000579.html

**Comment by kaka012** [comment]
Here's what i think about all this:
From the GAS docs (https://sourceware.org/binutils/docs/as/i386_002dVariations.html):
> In 64-bit code, ‘movabs’ can be used to encode the ‘mov’ instruction with the 64-bit displacement or immediate operand.

So `movabs (%0xbeef), %rax` (AT&T syntax) = `mov rax, [0xbeef]` (Intel syntax).

If rasm2 doesn't know what the assembly base address is (no `-o` option) and it is asked to assemble an instruction with displacement-only addressing it should assemble it verbatim to make the resulting assembly relocatable:
`mov rax, [0xbeef]` -> `mov rax, [0xbeef]`.
If rasm2 is given a base address, then it should optimize for resulting byte count.
`mov rax, [0xbeef]` -> (e.g.) `mov rax, [rip + 0xbeef]` (doesn't actually lower byte count in this case).

Also: relative addressing is still wrong:
`rasm2 -a x86.nz -b 64 "mov rax, [0xbeef]; mov rax, [0xbeef]"`
yields
`488b0425efbe0000488b0425efbe0000`,
which is
```
mov rax, qword [rip + 0xbeef]
mov rax, qword [rip + 0xbeef]
```

This can't be right, since the instruction counter won't be 0x00 on both mov's.

**Comment by Svenito** [comment]
Ok, I'll reopen and take a look at this today
