### ISSUE TITLE
r2 indicates that the program SIGSEGV after doing `afta`.

### ISSUE THREAD

**Issue by zadlg** [radare/radare2#8710]
See [Issue #8709](https://github.com/radare/radare2/issues/8709#issuecomment-337719428)

EDIT: just `afta` seems to produce the bug.

**Comment by zadlg** [comment]
`afta` is modifying some stack registers (rsp/rbp), therefore the sigsegv is a true sigsegv.

**Comment by radare** [comment]
is this fixed? as long as 8709 is closed? can you provide a reproducer or a test case?

**Comment by zadlg** [comment]
It's not fixed yet.

You can reproduce, by just `r2 -d` a program, then do `afta`. In fact, it's the `aeim` which modify SP and BP. Therefore, the program segfault.

I'm fixing it

**Comment by radare** [comment]
cant reproduce, tested on mac and linux

but if you fix is on the works ill wait

**Comment by zadlg** [comment]
Weird, with a ELF32 or ELF64 I can reproduce the bug ... I'm investigating

**Comment by radare** [comment]
aha

**Comment by radare** [comment]
ping

**Comment by zadlg** [comment]
pong
I haven't forgotten the issue. Fix is coming soon

**Comment by radare** [comment]
cool thanks

**Comment by zadlg** [comment]
The problem comes from [https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3238](cmd_esil_mem). `addr` and `size` are hardly initialized at `0x100000` and `0xf0000`.
Then, at the [end of the function](https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L3375), _SP_ and _BP_ are set to `addr + (size / 2)`.

But: 
```
0x100000 + ( 0xf0000 / 2) == 0x178000
```
And this is exactly the issue I have: after `aeim` command, _BP_ and _SP_ are set to `0x178000` without any reason. 
To conclude, `addr` and `size` are not properly set. I'm looking for why there are not set to their correct values.

**Comment by zadlg** [comment]
Well, I'm the only one which have this issue.
I close it.
