### ISSUE TITLE
Missing `libr_util.so` after installing

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#8714]
I installed radare2 from git for WSL on Windows 10 but had a error about missing `libr_util.so` library. When I checked symlinks I found that symlink for `libr_util.so` library was missed

```
lrwxrwxrwx 1 root root     51 Oct 19 16:42 libr_syscall.a -> /mnt/d/radare2/libr/syscall/libr_syscall.a
lrwxrwxrwx 1 root root     52 Oct 19 16:42 libr_syscall.so -> /mnt/d/radare2/libr/syscall/libr_syscall.so
lrwxrwxrwx 1 root root     52 Oct 19 16:42 libr_syscall.so.2.1.0-git -> /mnt/d/radare2/libr/syscall/libr_syscall.so
lrwxrwxrwx 1 root root     45 Oct 19 16:42 libr_util.a -> /mnt/d/radare2/libr/util/libr_util.a
lrwxrwxrwx 1 root root     46 Oct 19 16:42 libr_util.so.2.1.0-git -> /mnt/d/radare2/libr/util/libr_util.so
lrwxrwxrwx 1 root root     19 Feb  9  2017 libvmtools.so.0 -> libvmtools.so.0.0.0
```

I added it by hand and now it works for me:
```
# sudo ln -fs /mnt/d/radare2/libr/util/libr_util.so /usr/lib/libr_util.so
```

Maybe error is in new makefile.

**Comment by radare** [comment]
how did you installed it? sys/install.sh?

**Comment by dukebarman** [comment]
Yeap, installed using `sys/install.sh`

**Comment by radare** [comment]
Yeah confirmed, i can reproduce that on mac after a make purge. fixing now, this is probably a regression from yesterday's makefile refactoring O:)

**Comment by AXDOOMER** [comment]
This error happens on OpenSuse. The user may install `glibc-utils-32bit` to fix the issue.
