### ISSUE TITLE
Missing 8051 ESIL instructions

### ISSUE THREAD

**Issue by radare** [radare/radare2#8715]
* [ ] xch a, 0x83 # c583

**Comment by radare** [comment]
https://learn.mikroe.com/ebooks/8051programming/chapter/types-of-instructions/

**Comment by astuder** [comment]
Keil has a very good reference for 8051
http://www.keil.com/support/man/docs/is51/

**Comment by astuder** [comment]
There's a subtlety with movx indirect register (op-codes E2, E3, F2, F3): The register only holds the lower 8 bits of the address. The upper 8 address bits are determined by P2 (SFR 0xa0). See
http://www.keil.com/support/man/docs/is51/is51_movx.htm

**Comment by radare** [comment]
only XCH is missing. @astuder want to help on this one?

The XCH instruction loads the accumulator with the byte value of the specified operand while simultaneously storing the previous contents of the accumulator in the specified operand.

but it have 4 variants: 0xc5, 0xc6, 0xd6 and 0xd7

**Comment by astuder** [comment]
Happy to help, but I struggle to get emulation via ESIL working at all for 8051. It's probably my ignorance on how to operate emulation in r2.

**Comment by radare** [comment]
hang onn the irc and we’ll happily explain it, or just check the book or any of the talks in youtube

**Comment by astuder** [comment]
Before tackling more complex instructions (like XCH), I'm trying to learn ESIL by fixing a few simpler instructions. 

A few questions:

1. SUBB x, y (x = x - y with carry)  currently outputs "y,x,.=". Is this a bug or is ".=" a special ESIL operator for "subtract with carry"?
2. The instruction ADD x, y (x = x + y) currently outputs "y,x,+=". Shouldn't this include some additional code to set carry and other flags? Ditto for many other arithmetic operations that influence flags.
3. ESIL documentation says to use % for accessing flags in ESIL VM, but 8051 ESIL output uses $. E.g. "1,A,>>,$c7,C,=,A,=" for RLC A. Which one is correct?
4. And shouldn't the RLC A (rotate left through carry) generate something like "1,A,<<,C,+,A,=,$c8,C="

**Comment by radare** [comment]
Can you do a pr fixing this?

**Comment by radare** [comment]
Answering in here:

1) its not a bug, y,x,= is the same as x=y, read the esil documentation, but thats how  stack based vms work.
2) yes, internally esil generates all the carry variables, but if those internal esil flag bits imply a change in the target cpu registers it must use that (see $c, etc)
3) what , who uses %? the internal var prefix is $, maybe documentation is wrong. never trust text that is not compilable
4) yes but the C= should be C,=

**Comment by astuder** [comment]
I started completing / cleaning up the 8051 ESIL implementation. The macros are quite convoluted and hard to understand. I'm tempted to rip most of it out and follow the 6502 model.

1. Note that it says ".=". From what I've learned so far, I think that's wrong.
2. Thanks. Flag handling is missing from most 8051 ops right now.
3. https://github.com/radare/radare2/blob/42973a233e333cfa4b11e7a502ca3dc8d76ec28c/doc/esil#L82
4. Typo. Thanks!

I also found the reason why registers (ar) are not updated: The 8051 implementation hooks reg_read/reg_write to memory map registers.
https://github.com/radare/radare2/blob/42973a233e333cfa4b11e7a502ca3dc8d76ec28c/libr/anal/p/anal_8051.c#L468
However, r_reg_get used by the ar command to display the register values ignores those callbacks. Seems like 8051 is the only architecture that uses them.

In my branch, I disabled memory mapping until ESIL work is complete and working.

**Comment by radare** [comment]
Oh right. That regget issue is only affecting 8051 and it shohldnt be using that api. Otherwise we will have to sync data all the time. Looking forward your pr

> On 19 Jan 2018, at 17:06, Adrian Studer <notifications@github.com> wrote:
> 
> I started completing / cleaning up the 8051 ESIL implementation. The macros are quite convoluted and hard to understand. I'm tempted to rip most of it out and follow the 6502 model.
> 
> Note that it says ".=". From what I've learned so far, I think that's wrong.
Yeah seems wrong

> Thanks. Flag handling is missing from most 8051 ops right now.

Yeah.. feel free to send small patches no need to wait for a huge single perfect commit. So we can review and discuss in there

**Comment by astuder** [comment]
Major progress:

* All instructions are implemented
* Most instructions have a test case in radare-regressesions (will push as soon as latest pull request is merged into radare2)
* SUBB, MUL and DIV are implemented but not fully verified yet

Open issues:
* I really struggled with the flags for SUBB (subtract with carry/borrow), not sure yet if it's an issue with esil's support of the borrow flag
* Memory mapped registers are currently disabled because it screwed up r2 emulation. This is a big gap for useful 8051 emulation as several commonly used ops only work via memory (mov reg-to-reg, bit manipulation, push/pop). IMO hooks for anal to be invoked on reg read/write seem to be the most practical approach.
* Will also have to review, how address spaces (IMEM, XMEM, SFR, CODE) are best implemented. Probably will require a per-CPU approach similar to AVR. E.g. with Silabs, XMEM and CODE are mapped to the same physical memory.

**Comment by radare** [comment]
Good work. Looking forward the upcoming fixes. Let me know if you need hints or fix for something. We can chat in irc/tg

**Comment by astuder** [comment]
With #9234 ESIL coverage for 8051 is complete.

SUBB may still need some refinement to properly handle OV and AC (BCD carry) flags. But I will worry about that when it actually causes issues.

Next up fixing memory mapped registers and better handling of address spaces. But I think this issue can be closed.

**Comment by XVilka** [comment]
Thank you @astuder for amazing work!
