### ISSUE TITLE
rasm2 (x86.nz) produces incorrect relative address

### ISSUE THREAD

**Issue by kaka012** [radare/radare2#8722]
From #8701:
`rasm2 -a x86.nz -b 64 "mov rax, [0xbeef]; mov rax, [0xbeef]"`
yields
`488b0425efbe0000488b0425efbe0000`,
which is
```
mov rax, qword [rip + 0xbeef]
mov rax, qword [rip + 0xbeef]
```

This can't be right, since the instruction pointer won't be 0x00 on both mov's.

**Comment by Svenito** [comment]
However `rip` won't be 0x00 on both instructions either. It will be the address where the instruction is
