### ISSUE TITLE
Integrate/Re-implement Objective-C class-dump parser

### ISSUE THREAD

**Issue by radare** [radare/radare2#873]
Usable from debugger, disk ,... (class-dump tool is GPL, so we cant integrate it in core, parsing the output is somewhat painful and ugly.

**Comment by XVilka** [comment]
@inisider I think this can be closed thx to your work, right?

**Comment by inisider** [comment]
At current stage yes.
For future will be good add generics ( or smth like this ). but here need to do investigations because of no one tool does not support it. 
And also need to add some tests

**Comment by radare** [comment]
yep. tests are prioritary, i’ll try to find some time to dig into the generics thing
