### ISSUE TITLE
Python Scripting - stop execution

### ISSUE THREAD

**Issue by markodevic** [radare/radare2#8733]
Hey,

I wanted to do something very simple like this :
```
import r2pipe
r2 = r2pipe.open("random_program")
r2.cmd("ood 1094795585")

while True: # until "the end" of the binary
    r2.cmd("ds")
    print r2.cmd("pd 1 @rip")

```
But I am unable to find how to stop the loop. After the process exit I cannot find a way to get the hand on the execution and it just loops infinitely while displaying `Step failed` or trying to execute invalid opcodes. 

Is there a clean way to catch the end of the binary or the process exit through python bindings ?

**Comment by Maijin** [comment]
Why you not open in debug mode instead of using ood ? r2pipe.open("aaaa.exe", ["-d"]) (look at the pydoc)
Also for scripting don't use `cmd("pd")`, use `cmdj("pdj")`

**Comment by radare** [comment]
use “break” to stop the loop :P

**Comment by radare** [comment]
the command ‘di’ shows the information of the targt process. one of those fields (dij) will tell you if the process is still running or wat

**Comment by markodevic** [comment]
> the command ‘di’ shows the information of the targt process. one of those fields (dij) will tell you if the process is still running or wat

That does the job nicely. Thanks !
