### ISSUE TITLE
Neverending classes.dex analysis

### ISSUE THREAD

**Issue by earada** [radare/radare2#8734]
When loading classes.dex file from a malware sample, r2 never ends the initial analysis. It prints a lot of warnings like this: `WARNING: Invalid string for index 5693`

[classes.zip](https://github.com/radare/radare2/files/1410522/classes.zip)
Password: infected

**Comment by h4ng3r** [comment]
I tried to open the file with IDA 6.9 and I got a corrupted file error. Have you been able to open it with another disassembler?

**Comment by radare** [comment]
corrupted bins shouldnt fool r2

**Comment by h4ng3r** [comment]
@radare yep totally agree, but I'm curious ;).
