### ISSUE TITLE
Reopen Current Program with backticked arguments

### ISSUE THREAD

**Issue by WarkerAnhaltRanger** [radare/radare2#8740]
Hi Devs,

it would be great if the "doo" or "ood" command could reopen a program in debug mode with backticked arguments like the run command in gdb:

doo \`python -c "print 'A'*200"\`
or
doo $(python -c "print 'A'*200")

This should restart the initial program with the given argument of 200 times A
Like in gdb a already running process should be killed (user prompt).

Thank you!

**Comment by fasetto** [comment]
You can use like this: 
```
doo `!python -c "print 'A' * 200"`
```

**Comment by radare** [comment]
in r2land we have ragg2 to do the same

ragg2 -p a200

**Comment by ITAYC0HEN** [comment]
I recommend closing this issue since this solution can work with 
```
doo `!python -c "print 'A' * 200"`
```
