### ISSUE TITLE
radare2 crashes when you execute aaT

### ISSUE THREAD

**Issue by mjz19910** [radare/radare2#8750]
I think there is a off by 2 bug, stack addresses that is.
Whenever you run `aaT` radare2 will crash.
Try it with
`radare2 -qc aaT malloc://16`

`Oct 27 19:05:21 (omit) kernel: radare2[13979]: segfault at 18 ip 00007efbf7aaa9ae sp 00007ffbffffa030 error 4 in libr_core.so.1.7.0-git[7efbf7a15000+1af000]`

I am using Ubuntu 17.04

`
Linux (omit) 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Release:        17.04
`

**Comment by Maijin** [comment]
instead of `echo xxx |` you can use `r2 -qc "aaT" malloc://16`
