### ISSUE TITLE
V! visual mode doesn't follow Evaluable vars

### ISSUE THREAD

**Issue by naisanza** [radare/radare2#8754]
~/.radare2rc:
```radare2rc
e scr.promptflag = true
e scr.promptsect = true
e scr.rainbow = true
e scr.responsive = true
e scr.utf8.curvy = true
e scr.utf8 = true
```

![peek 2017-10-29 21-43](https://user-images.githubusercontent.com/1614425/32151314-6a19c9d8-bcf2-11e7-9070-ac4ea1f80ac7.gif)

![peek 2017-10-29 21-44](https://user-images.githubusercontent.com/1614425/32151318-6bf75342-bcf2-11e7-9f18-e02e30c6d619.gif)

**Comment by radare** [comment]
Cant reproduce

**Comment by naisanza** [comment]
@radare 

Just tried it with a new vagrant `ubuntu/xenial64` with `f91049c8c10107c7f281c8028157bf105efe8d46` to check if it's outdated, and `aa;V!` still shows the graph as if `e scr.utf8 = false`

**Comment by Maijin** [comment]
Yes that's known issue:

https://github.com/radare/radare2/issues/2032 - V! panels and Unicode (UTF-8)
https://github.com/radare/radare2/issues/8672

**Comment by XVilka** [comment]
It is not exactly an issue - Unicode was disabled in panels interface on purpose, because for now it clobbers the output. My advice - to use "common" visual modes instead. `V!` is far from being usable yet.
