### ISSUE TITLE
RBinFile is not arch

### ISSUE THREAD

**Issue by radare** [radare/radare2#8758]
rename all 'arch' in libr/bin for 'bf'

**Comment by radare** [comment]
```
$ git grep RBinFile| grep arch |wc -l
     364
```

**Comment by Maijin** [comment]
Some also are `binfile` like `libr/bin/bin.c:R_API RBinObject *r_bin_object_find_by_arch_bits(RBinFile *binfile,`

Should I change to `binfile` or `bf` ?

**Comment by radare** [comment]
Bf
