### ISSUE TITLE
Providing operands list for each instruction

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8766]
Currently RAnalOp has a bit inflexible structure according to operands - 3 "src" and 1 "dst" operand,
without also a clean way to check the operand type - I suggest to make it union, RAnalOperand with an attached type of it, and just an attribute field inside - if it's destination or source (or both in the same time).

Will ease writing the analysis plugins/features.

Another thing - more a long term solution - tokenize the string of the mnemonic, in the disassembly plugin. Some architectures are using commas to separate the operands, some - another signs. So writing the parser of it in uniform way is a bit complicated task. Same applies to the syntax highlight, which would have been much easier after such tokenization.

**Comment by radare** [comment]
> On 1 Nov 2017, at 05:40, Anton Kochkov <notifications@github.com> wrote:
> 
> Currently RAnalOp has a bit inflexible structure according to operands - 3 "src" and 1 "dst" operand,
> 
This is deprecated and shouldnt be used at all, when it wss implemented, the analysis took like 3 times more and eat like 4 times more ram. Structures are crap. Thats why i went into the esil direction.
> without also a clean way to check the operand type - I suggest to make it union, RAnalOperand with an attached type of it, and just an attribute field inside - if it's destination or source (or both in the same time).
> 
Unions waste memory, so each ranalop will eat more memory and if in heap it will make everything slowr.
> Will ease writing the analysis plugins/features.
> 

Imho we should merge asm and anal and add different layers of detail for anajlydis to only get what we need to process the code. That will speedup the whole thing and (2-3x) 
> Another thing - more a long term solution - tokenize the string of the mnemonic, in the disassembly plugin. Some architectures are using commas to separate the operands, some - another signs. So writing the parser of it in uniform way is a bit complicated task. Same applies to the syntax highlight, which would have been much easier after such tokenization.
> 

I dont thi k this is necessary at all, there are several functins to split strings and thats all you need to do that. Rparse proofs thzt this is possible and easy

**Comment by XVilka** [comment]
Yes, but ESIL doesn't help to get the immediate/displacement value. I'm talking about 

I agree about mergind RAsm and RAnal - will be easier to write new plugins as well. Currently RAnal just calls disassembly inside for getting the access to the structures.

Regarding parsing - keep in mind that current RParse is easy just because it cannot properly highlight TMS320 syntax, Hexagon syntax, many other syntaxes.

**Comment by radare** [comment]
I know, thats why i did opex

> On 1 Nov 2017, at 13:28, Anton Kochkov <notifications@github.com> wrote:
> 
> Yes, but ESIL doesn't help to get the immediate/displacement value. I'm talking about
> 
> I agree about mergind RAsm and RAnal - will be easier to write new plugins as well. Currently RAnal just calls disassembly inside for getting the access to the structures.
> 

Not easy or planned for next release, but its a long plan already
> Regarding parsing - keep in mind that current RParse is easy just because it cannot properly highlight TMS320 syntax, Hexagon syntax, many other syntaxes.
> 

R2 generalizes some disasms to make them easy to read and parse,, dunno about those targets in detail

**Comment by sivaramaaa** [comment]
This is currently implemented now, We have `R_ANAL_OP_MASK_VAL`  which fills the `op->dst/src` information, it's supported for most of the major archs 

Things left to do : 

* Add this support for rest of the arch
* Maybe add this for instruction like arithmetic and other non-memory referencing instruction filling op->imm etc 

Closing this issue now, if needed pls open a new issue with updated info !

**Comment by sivaramaaa** [comment]
I see a few overlapped and few dupe fields between `RAnalValue` and `RAnalOP`

```
typedef struct r_anal_op_t {
        ...
        st64 ptr;
        ut64 val;
        const char *reg;
        const char *ireg;
        int scale;
        ut64 disp; // this one clearly has to be killed 
        ...
} RAnalOp;
```

```
typedef struct r_anal_value_t {
        ...
        ut64 base ;
        st64 delta;
        st64 imm;
        RRegItem *reg;
        RRegItem *regdelta;
} RAnalValue;
```

IMHO it would be nice if we discuss and merge few things to avoid dupes and save some memory :)

**Comment by XVilka** [comment]
Fixed.
