### ISSUE TITLE
Add a command to list all the syscalls found in a region

### ISSUE THREAD

**Issue by radare** [radare/radare2#8767]
This aims to be something like a mix of /A swi + aae and then as to resolve the syscall names

Output must be like this:
```
0xAddrOfSyscall nameOfSyscall
```

**Comment by radare** [comment]
This must be implemented in the /s command

**Comment by sivaramaaa** [comment]
Hey all , 
I am very interested to contribute r2 , but i have no clue about r2's codebase  , but i would really like to learn it with all ur  help 
I have come up with a idea of how to implement this :
First we can emulate the code until we reach a syscall and check the register/stack values to resolve the name of syscall

I would be happy to get some Suggestions

**Comment by radare** [comment]
Yep, the idea for this would be to implement the /s command that shuold honor the search.in eval var (there’s some code in cmd_search.c that may light you up how to honor this, then you should do linear emulation ignoring the memory accesses to determine the syscall that is suposed to be called on every instruction of type SWI, then use the RSyscall api to know which is the name for that syscall according to the current asm.os/asm.arch/asm.bits setup.

Do you want to implement this? feel free to join the irc/telegram channel to faster reply times :)

**Comment by sivaramaaa** [comment]
Thanks a lot , i would start working on this !!

**Comment by radare** [comment]
Any update on this @sivaramaaa ? it's easy to do, and i would like to have it as soon as possible before the release.

**Comment by sivaramaaa** [comment]
hey hi , 
I have written a function to get address of all instruction of type SWI (extracted the relevant code from do_anal_search() in cmd_search)

Now i need a little help in the  emulating the instruction , how could i do this using any r2 api ?

( sorry for the delayed update , i was having exams in my college , i tried to contact u thru irc , but u were unavailable )

**Comment by sivaramaaa** [comment]
Hey , 
I have created a PR regarding this , hope it works 
The output 
```
[0x00400e6e]> /s
0x004003e7 close
0x004014bb listen
0x004032aa close
0x0040356d close
0x00403f38 munmap
0x0040981c read
0x00430ba6 read
0x00430bb7 read
0x00430d4e read
0x00430dcc clock_getres
0x004313b5 clock_getres
0x00431405 clock_getres
0x00431433 clock_getres
0x004314ce open
0x00431612 fcntl
0x0043171e fcntl
0x004317e0 getcwd
0x00431c16 close
0x00431f18 mmap
0x00431f35 munmap
0x00431f55 munmap
0x00431f75 munmap
0x00432b64 inotify_rm_watch
0x00432c38 inotify_rm_watch
0x00432ccf inotify_rm_watch
0x00432e2e inotify_rm_watch
0x00432ef9 inotify_rm_watch
0x00432f27 inotify_rm_watch
0x00432fdd futex
0x0043cec1 close
0x0043cf48 close
0x0043e921 close
0x0043e98e rt_sigqueueinfo
0x0043ea4a rt_sigqueueinfo
0x0043ee94 munmap
0x0043f03d munmap
0x0043f2b9 read
0x0043f2d5 tgkill
0x0043f327 sigreturn
0x0043f428 rt_sigaction
0x0043f54e rt_sigprocmask
0x00457103 getdents
0x00457215 read
0x004572e2 clone
0x004574a4 quotactl
0x00457505 getuid
0x004576bd openat
0x004576f5 openat
0x00457747 read
0x004577ea read
0x0045789e writev
0x00458cd4 writev
0x0045c37d futex
0x0045ed48 futex
0x0045fbad futex
0x0046e849 get_mempolicy
0x0046fc8c futex
0x0046fea1 futex
0x00481f6c futex
0x00482125 open
0x0048ac71 open
0x0048acb1 open
0x0048acf1 open
0x0048ad35 open
0x0048ad75 open
0x0048adf5 open
0x0048ae35 open
0x0048ae75 open
0x0048e119 stat
0x00494ee8 stat

```

**Comment by sivaramaaa** [comment]
Hey , 
I have fixed all issues suggested by you , hope there is no errors this time !

**Comment by Maijin** [comment]
Send PR then ^^
