### ISSUE TITLE
io-stuff that can be improved

### ISSUE THREAD

**Issue by condret** [radare/radare2#878]
here are some suggestions for io-improvements, so that I can use it for ramulate:

fix bugs:
    - if you start reading in the middle of a map, everything after the  map will be a wall of 0xff
    - S. does not work correctly

at the moment you can raise one map to the top of io. This is good enough if you're working on 2 files at the same time. But for me this is not sufficient: just imagine 3 files that overlap. You don't want to raise the fd over and over again.
therefor I suggest:
    - each map should have a priority
    - maps with the same priority may not overlap
    - sections belong to a map?

**Comment by Maijin** [comment]
Discussion switched over to SIOL, closing here
