### ISSUE TITLE
MIPS move (pseduo-instruction) and noop shown as .dword.

### ISSUE THREAD

**Issue by MPX4132** [radare/radare2#8787]
Some "move $X, $Y" MIPS asm pseudo-instructions appear as ".dword 0x..." after analysis.

**Comment by Maijin** [comment]
What is the output without analysis.

**Comment by MPX4132** [comment]
Without analysis, the instruction is displayed correctly [(analysis on left, no analysis on right)](https://imgur.com/a/6iB52).

**Comment by radare** [comment]
[setupwizard.zip](https://github.com/radare/radare2/files/1444960/setupwizard.zip)

**Comment by MPX4132** [comment]
I'm working around it by doing "C-" to reveal the instruction.

**Comment by radare** [comment]
In Visual mode press d and then c (define code)

**Comment by Maijin** [comment]
Yeah V->d->c as @radare said, but that shouldn't be flagged as dword on first place if there is none dword there :/

**Comment by radare** [comment]
ill fix that as soon as i get some time after finishing all the stuff i have in hands right now

**Comment by MPX4132** [comment]
I found some noop shown as .dword as well.

**Comment by radare** [comment]
Should be fixed now

**Comment by MPX4132** [comment]
@radare thanks for getting back to this, and for letting me know.

**Comment by Maijin** [comment]
@MPX4132 please try and give feedbacks

**Comment by MPX4132** [comment]
@Maijin sure, I’ll check it out in a bit.
