### ISSUE TITLE
Super mario blocks break graphs

### ISSUE THREAD

**Issue by radare** [radare/radare2#8788]
<img width="577" alt="screen shot 2017-11-06 at 01 07 53" src="https://user-images.githubusercontent.com/917142/32420727-3a76dc00-c28f-11e7-9a15-11c813b06da5.png">

cc @kazarmy we need a way to disable printing non-ascii chars in disasm and enable this option when rendering the graph.. or fix the graph code to handle those properly

**Comment by kazarmy** [comment]
idk what that ⍰ represents so please send me the binary

**Comment by radare** [comment]
any non ascii char will be shown as this

**Comment by XVilka** [comment]
Related to https://github.com/radare/radare2/issues/2032 (actually a subset of it)

**Comment by radare** [comment]
Can't we just honor the scr.utf8 var when printing the strings? that will fix the issue and we can revert that later when the graph supports utf8 in node blocks

**Comment by XVilka** [comment]
The reason of the issue is `strlen`, which calculates wrongly the bytes count, instead of multibyte Unicode chars. Just need to find the corresponding one and use `r_str_len_utf8(char* str)` instead.

**Comment by kazarmy** [comment]
Even a proper `r_str_len_utf8(char* str)` won't work if there are zero-width chars (e.g. https://en.wikipedia.org/wiki/Zero-width_space) or there are multiple chars that combine into one (e.g. https://en.wikipedia.org/wiki/Combining_character). Perhaps it's best that r2 always moves the cursor to where it thinks it should be by using ANSI escape sequences.

**Comment by kazarmy** [comment]
@radare can set `asm.asciidot = true` if you don't want the escape sequences

**Comment by XVilka** [comment]
@kazarmy I think in the long run radare2 should support full Unicode features. At least counting length.

**Comment by kazarmy** [comment]
I agree. What is needed here appears to be the number of rendered glyphs though and I think this can be different between consoles.

**Comment by radare** [comment]
is this fixed now? can we have tests pls?
