### ISSUE TITLE
Search does not stop on the next match until whole file is searched

### ISSUE THREAD

**Issue by Hi-Angel** [radare/radare2#8797]
Steps to reproduce:

1. Use `r2 -n mybigfile` to open a big file, say a few GBs.
2. Use `s/ text` to find some text that should be present at the beginning. E.g. if you open a AVI video file, you can search for `s/ 00d` — it's a signature before every video frame chunk.

Expected results: radare immediately stops as the first match found.
Actual results: radare searches till the end of the file with disregard to actual position of the first match.

Version:

	radare2 2.1.0-git 16457 @ linux-x86-64 git.2.0.1-163-g9f08ccbcc
	commit: 9f08ccbcc436eab09bbd03cafa576f9ee8a7f037 build: 2017-11-04__12:31:43

**Comment by Hi-Angel** [comment]
Found a workaround: if the search went behind a match, pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> stops the search and resets the position to the expected match.

**Comment by radare** [comment]
i was testing this yesterday and it was working as expected for me :? can you provide a testcase for r2r?

**Comment by Hi-Angel** [comment]
How did you test, have you used a big file, etc…? I just tested it on master:head, and it still reproducible for me. 

> can you provide a testcase for r2r?

From googling r2r seems to be some regression tool. I do have a vague idea how to automatize it:

1. Create a file with content "hello world"
2. Use the command "s/ hello"
3. Check that the radare have loaded the file beyond the word "hello".

But I have no idea what how to use r2r, and how to even check if radare have loaded whole file *(well beyond using `smem -c "pss"` which probably isn't good idea)*.

**Comment by Maijin** [comment]
Just look at the example and create a test that reproduce the expected behavior:
-> https://github.com/radare/radare2-regressions/blob/master/t/cmd_search

` if radare have loaded whole file`, simply `i`

**Comment by Hi-Angel** [comment]
I have looked at `i` — it doesn't provide information on how much of the file is loaded, neither at the beginning or the middle of the file, nor when whole file is loaded *(e.g. when opening the file without `-n` option on command line)*.

**Comment by Maijin** [comment]
` -n, -nn      do not load RBin info (-nn only load bin structures)` if the file is loaded and doesn't have rbin info you will only see:

```
blksz    0x0
block    0x100
fd       3
file     /bin/ls
iorw     false
mode     -r-x
size     0x9720
humansz  37.8K
```

vs detailed info when rbin info are loaded i.e:

```
bintype  mach0
class    MACH064
etc.
```

**Comment by Maijin** [comment]
If you want info on the opened file you can also check `o?` see `o=`, `om` etc.

**Comment by Hi-Angel** [comment]
`o=` and `om` also doesn't make any difference between when I load a file with "hello world" content with `-n`, without `-n`, whether I do search so the file is surely loaded, or I don't.

I honestly doubt radare2 would provide such information as "how much of the file is loaded", this is very specific corner question that might be of interest only for regression test on this specific issue.

**Comment by Maijin** [comment]
https://asciinema.org/a/utaW9YkrzYT1LDVCG56EjJyI2

**Comment by Maijin** [comment]
Added a test https://github.com/radare/radare2-regressions/commit/60edeaff2ccb4bbe28d66631c4ffded4e9a20c06

**Comment by radare** [comment]
please confirm, it shoulkd be fixed now. if not, i'll look in 2.3

**Comment by Hi-Angel** [comment]
I confirm, thank you very much!

**Comment by radare** [comment]
👏👏👏
