### ISSUE TITLE
use dietline in ms

### ISSUE THREAD

**Issue by radare** [radare/radare2#8806]
the mount-shell doesnt supports autocompletion or history, we should use r_cons api like rcore does

**Comment by davidpolverari** [comment]
I was busy with work stuff, both at work and at home. But now I got some free time and I will try to implement completion.

**Comment by radare** [comment]
any updates?

**Comment by radare** [comment]
im working on this right now, will send pr in few mins

**Comment by davidpolverari** [comment]
Sorry for not being able to do it on time! I feel really bad for this, but I had some problems irl. I'm reading https://github.com/radare/radare2/commit/2a8ab337d94ec4d6f0b13aef7bf5af859251304d atm and will try to contribute if I figure out how to autocomplete paths from RFS. Again, sorry for the delay.

**Comment by davidpolverari** [comment]
r_fs_shell_prompt() in libr/fs/shell.c has a char array called path[] that contains cwd, right? As autocomplete is done inside libr/core/cmd_mount.c, should I have a function inside shell.c to return path[] contents to be consumed by getFilesFor() in cmd_mount.c?

**Comment by davidpolverari** [comment]
I started working on it the way I told you on the last comment, but I don't know if it's the right approach. I created a PR is on https://github.com/radare/radare2/pull/9837/commits/4c1a2bbd370c31843967bf45d9a3726f08e6e646 (not to be merged, just for review) with the first steps of it.

**Comment by radare** [comment]
Np take care about your real life. Just say it if you can’t. Learning to say no is something i have still to learn

**Comment by radare** [comment]
The current thing works, but its buggy and incomplete, so feel free to complete it. And Dont feel bad about jt

**Comment by XVilka** [comment]
@cyanpencil may want to take a look at this at some point. Not for this release though.

**Comment by radare** [comment]
ping @cyanpencil

**Comment by deepakchethan** [comment]
Now it supports both autocompletion and history. It uses r_cons API also.

it uses the pwd from RFSShell to keep track of the current directory.

What exactly is remaining ?

**Comment by radare** [comment]
I dont think ms supportss tab at all yet. try  this:

there' an assert, debug messages, and tab does snothing  at the end

<img width="854" alt="Screenshot 2019-06-03 at 11 46 00" src="https://user-images.githubusercontent.com/917142/58815203-2bcf5300-85f5-11e9-922c-bd39dbc2c8d4.png">

**Comment by radare** [comment]
Also, all the m subcommands doesnt handle tab either: `mg  /<tab>`

**Comment by XVilka** [comment]
@radare @deepakchethan I guess now can be closed, right?

**Comment by deepakchethan** [comment]
Yes, This is done :)
