### ISSUE TITLE
May be fold many XREFS in visual ascii/unicode graph mode?

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8815]
May be fold them, short them or hide somehow?

![screenshot_20171110_163042](https://user-images.githubusercontent.com/203261/32649295-8cd5c5c6-c634-11e7-9431-2e8756b67c92.png)

**Comment by Maijin** [comment]
Just knowing they exist and maybe number is enough imho, displaying their location isn't useful information.

XREFS(10) instead of current output maybe ?

**Comment by XVilka** [comment]
@Maijin agree, you always can see the xrefs by yourself if you want.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L4768
https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L4858

**Comment by radare** [comment]
<img width="1214" alt="screen shot 2017-12-22 at 15 25 57" src="https://user-images.githubusercontent.com/917142/34301335-725e82be-e72c-11e7-8e6b-eda128109a89.png">

**Comment by radare** [comment]
<img width="984" alt="screen shot 2017-12-22 at 15 38 27" src="https://user-images.githubusercontent.com/917142/34301756-2c2ac5c6-e72e-11e7-92c7-22e69f581111.png">
