### ISSUE TITLE
/E seems broken

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8817]
See simple snippet:

```
r2 -qc "wx 0x90;/E ," -
```

**Comment by sivaramaaa** [comment]
Hey hi , 
Regarding this issue , for testing this i think first u have to initialize esil pc and stack like this : 
```
> aei
> aeim
> aeip
> "/E ,"
```
But still u get this error ``` Cannot parse esil (,) ```
And i don't know why this is not working in any version , i atleast tried with 3 different versions 
( Is that something i am doing wrong here @radare , @Maijin  ?? ) 
Thinking to look into the code , if it's really an issue !!

**Comment by radare** [comment]
Single comma is a nop. Should be valid for esil

**Comment by sivaramaaa** [comment]
Exactly ,. But I am getting this error , is it working on ur end ??

**Comment by radare** [comment]
this is fine, but you cant search for an empty esil expression. /E works as expected, but maybe its not clear how to use it :P

**Comment by radare** [comment]
esil search is not related to code analysis or emulation at all. it emulates an esil expression on each offset and considers a hit what results in true. so you can compare multiple memory addresses, do operations with the values in there and if the result is X, then consider it a hit

**Comment by Maijin** [comment]
wat

**Comment by Maijin** [comment]
Please provide examples because the , doesn't work as well as `r2 -qc "/E rsp,rbp,=" /bin/ls`

**Comment by Maijin** [comment]
And I need examples for the testsuite

**Comment by radare** [comment]
$ r2 -e cfg.debug=1 -qc '/E $$,[1],72,==' /bin/ls

this will do the following:

$$ : current offset (incremented by 1 on each iteration)
[1] : read one byte at this address
72 : push the number 72
== : compare 72 vs current byte, if its the same, will push 1, if not will push a 0

the /E considers that if, after evaluating the esil expression, there’s 1 element in the stack, and its value is != 0 it will be considered a search match.

i have confirmed that /E works and also honored cfg.debug to get some feedback to debug the esil expressions

**Comment by Maijin** [comment]
So we need another command to search for esil to do something like `/ce rsp,rbp,=` no ?

**Comment by radare** [comment]
Yes. That would be /ce. Will do later today

**Comment by sivaramaaa** [comment]
i am up for it , do u want me to implement this !!!!

**Comment by radare** [comment]
Sorry i already implemented it before the release

**Comment by sivaramaaa** [comment]
okk , it's fine ,  i think it's not mentioned in help msg i think !!!!

**Comment by radare** [comment]
Yes it is . At least i recall doing it
