### ISSUE TITLE
Missing trivial string references in MIPS.

### ISSUE THREAD

**Issue by MPX4132** [radare/radare2#8821]
I've noticed most references specified as below are missed:
```
lui a0, 0x44 ; Load upper half-word (16 bits)
addiu a0, a0, 0x5f8 ; Fill first half-word (16 bits)
``` 
Where 0x4405f8 would point to a null-terminated string.

It seems more complex references are found, leading me to believe these might be fairly simple to detect.

**Comment by radare** [comment]
e asm.emu=true and e anal.gp and you will get all of them

**Comment by MPX4132** [comment]
Doesn't "aaaa" take care of those when it does analysis? I ran it with that and the references above weren't caught.

**Comment by radare** [comment]
no. aaaa is the most stupid way of analyzing binaries. its full of false positives, regressions and issues in most of the tests and its never recommended, its experimental. there are several other ways to find references better

**Comment by radare** [comment]
read the blog post in radare.today about "analysis by default"

**Comment by MPX4132** [comment]
@radare Oh, I'm sorry, I didn't realize it was the "stupidest method" of analysis... Maybe it should come with a more obvious warning when it's executed.

**Comment by radare** [comment]
Thats up to maijin. Disnt mean to be offensive here. Dont take my words like this :) but automatic analysis is never suposed to give the best results on any tool. Its just a matter of learning and improving.

Aaaa just runs a lot of analysis methods one after the other so it takes more time analyzing the same thing more than once and its easy way to identify issues and false positives to improve. But the best way to go is by fixing those issues while running the specific analysis you need for your target.

**Comment by MPX4132** [comment]
Oh, that makes sense. I'll check out the analysis by default article, thanks for the help.

**Comment by Maijin** [comment]
@radare is right here. We need to improve the automatic analysis by adding conditional per filetype/arch etc. that'll help too

**Comment by MPX4132** [comment]
Yeah, I wasn't aware it's a bit incomplete.
