### ISSUE TITLE
Add a command to highlight the entire line

### ISSUE THREAD

**Issue by radare** [radare/radare2#8828]
This should be an anal hint or something like that, and must be honored in the pd disasm loop. having the ability to specify the color of that line (only bg?) that will not work on some targets, but having fg can be problematic in some frontends and will break all the colorization of the instruction

**Comment by XVilka** [comment]
related to colorization of some selected graph nodes

**Comment by XVilka** [comment]
To this one https://github.com/radare/radare2/issues/8588

**Comment by radare** [comment]
this is asm.highlight which can be improved to support more colors depending on hints or so. let's close this for now and continue the work on #8588
