### ISSUE TITLE
tiling visual mode debugger 'continue' not working

### ISSUE THREAD

**Issue by montekki** [radare/radare2#8836]
Debugging commands called with 'Debug' menu in tiling mode don't seem to work, however stepping with 's' shortcut works. Also in other visual modes 'continue' commands seem to work.

**Comment by radare** [comment]
Thats super easy to fix. Please send a pr fixing

**Comment by montekki** [comment]
@Maijin it seems that  your fix hasn't fixed the issue, can you please re-test?

**Comment by Maijin** [comment]
Using latest r2: https://asciinema.org/a/hmltjP5NLNTkuDbFeMM1CinYG works.
