### ISSUE TITLE
r2pm -i r2-lua53 fails

### ISSUE THREAD

**Issue by ggonzalez** [radare/radare2#8842]
bin_lua53.c:342:3: error: field designator 'check' does not refer to any field in type 'RBinPlugin'
      (aka 'struct r_bin_plugin_t')
        .check = &check,
         ^
1 error generated.
make[1]: *** [bin_lua53.o] Error 1
make: *** [all] Error 2
ERROR: Build failed

**Comment by Maijin** [comment]
This has been fixed yesterday - https://github.com/radare/radare2-extras/commit/589d5645af2fdb5b1099c1c0e8fc3c06192c955c
