### ISSUE TITLE
Tab completion that walks directories (e.g. wf) inserts spaces

### ISSUE THREAD

**Issue by evanrichter** [radare/radare2#8856]
When using tab to complete directory names, a space is always inserted where a slash should be. This means the user has to backspace, type slash, then continue as normal with tab completion.

Steps to reproduce:

> r2 -version
> radare2 2.1.0-git 16556 @ linux-x86-64 git.2.0.1-264-g5957fcd08
> commit: 5957fcd0873f58db142e2ebb52fd52cd164c00af build: 2017-11-20__10:49:14

> r2 -
> wf /tmp<TAB>

And observe the extra space. Hopefully this is how you want issues reported, if more information is needed let me know

**Comment by radare** [comment]
Known issue boring to fix, if anyone is in the mood send a pr

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/8866
