### ISSUE TITLE
Make pdf work :P

### ISSUE THREAD

**Issue by radare** [radare/radare2#8874]
the good of pdf is that it works for linear functions, but if those contains basic blocks from different functions or so spaced ones it results in a very wrong output, where pdr is recommended.

The way to solve this is imho to add '...' in the parts of the disasm that doesnt belong to the function

**Comment by SrimantaBarua** [comment]
Current pdf output for me is that the function is clipped and ends before the other basic block / space. Is that what you are refering to? Or could you upload a sample bin?

**Comment by radare** [comment]
Thats a different issue but it should be fixed in here too. I use to take /bin/ls as sample. Nonlinear functions are expecting to make pdf fail. Thats why pdr is better

**Comment by Maijin** [comment]
oups it's not merged yet
