### ISSUE TITLE
Section dump cannot open files for writing.

### ISSUE THREAD

**Issue by llact** [radare/radare2#8878]
Unable to dump PE sections to a file as radare fails to either create a new dump file or open an existing one. See attached screenshot. <br> ![radare2error](https://user-images.githubusercontent.com/33955009/33205941-9669dbc8-d100-11e7-8235-cf699c33d8bd.PNG)
Same error occurs in both Windows and Ubuntu.

**Comment by llact** [comment]
To further this, the same problem persists with the open command as well.<br>
![radarefilecommands](https://user-images.githubusercontent.com/33955009/33212158-b6f64976-d119-11e7-8ef8-48b0374ee61e.PNG)

**Comment by radare** [comment]
works fine here. im on mac using r2 from git

type pwd to see in which directory are you, do you have permissions there?

**Comment by Maijin** [comment]
ok... ? So what ?
