### ISSUE TITLE
leave and ret doesn't translate to pseudocode

### ISSUE THREAD

**Issue by ishitatsuyuki** [radare/radare2#8883]
asm.pseudo = false
```
│           0x080487a8      c9             leave
└           0x080487a9      c3             ret
```

asm.pseudo = true
```
│           0x080487a8      c9             
└           0x080487a9      c3
```

`leave` may be two lines, but at least `ret` should be just `return`.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/libr/parse/p/parse_x86_pseudo.c

The pseudo should be something like:
leave/ret -> `return 0xXXXX;`
ret -> `return;`

**Comment by mrpaja** [comment]
I have already look at the issue. I am quite busy the next few days but afterwards I'll gonna send a pull request. Can I get it somehow assigned?

**Comment by radare** [comment]
Cant assign without giving you commit permissions. But we will remember :)
