### ISSUE TITLE
Add a command to do Vdn not in visual mode

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8888]
Add a command to do rename flag used at cursor, same as `V -> d -> n` not in visual mode

https://github.com/radareorg/cutter/issues/22

**Comment by radare** [comment]
fn?

**Comment by Maijin** [comment]
Hum yes given that local_ and arg_ aren't yet flags but will probably be in future that sgtm

**Comment by radare** [comment]
afn

**Comment by Maijin** [comment]
No that's for renaming function

**Comment by radare** [comment]
Tied to https://github.com/radare/radare2/pull/8890
