### ISSUE TITLE
How to get a nice stack view in radare2? 

### ISSUE THREAD

**Issue by Vafa-Andalibi** [radare/radare2#8891]
This is the stack view that I'm getting in radare2 after entering the visual panel mode:

![1](https://user-images.githubusercontent.com/9551535/33241651-68111858-d296-11e7-8dac-ae1dbc4af2a0.jpg)

I'm looking for something like this (this is from Immunity Debugger):
![2](https://user-images.githubusercontent.com/9551535/33241655-7838c8ac-d296-11e7-9321-5bc7945a9715.jpg)

can I get such stack view in radare2?

Thanks,

**Comment by radare** [comment]
Already replied in twitter

https://twitter.com/radareorg/status/934541730841595904

**Comment by Maijin** [comment]
`e dbg.slow =true + Vpp` too

**Comment by Maijin** [comment]
Use the command @radare sent you then, if you need to extend size of the stack in Vpp use `          stack.size: Size in bytes of stack hexdump in visual debug`

**Comment by radare** [comment]
Entering the cursor mode with c and then tab to select stack, regs or disasm
