### ISSUE TITLE
 Double free on connection to gdbserver when the dbg.exe.path is incorrect

### ISSUE THREAD

**Issue by hummelchen** [radare/radare2#8899]
r2 aborts execution when I try to connect to gdbserver port and my dbg.exe.path is incorrect:
```
% r2 gdb://127.0.0.1:1236 -e dbg.exe.path=some/bad/path                                                                                  
*** Error in `r2': double free or corruption (fasttop): 0x00005640cdb401e0 ***
```

Backtrace, memory map and valgrind log: 
https://gist.github.com/hummelchen/bc46c540c2f39d7b5c179425f6e402a5

r2 version:
radare2 2.1.0 16638 @ linux-x86-64 git.2.1.0
commit: 95f842729cd2f9f7ca85445473451a3afdbaff65 build: 2017-11-28__01:03:25

**Comment by radare** [comment]
Dont pass -args after the filename. Thats not posix
