### ISSUE TITLE
expired ssl certificate https://www.radare.org/

### ISSUE THREAD

**Issue by ilovezfs** [radare/radare2#8909]
```
www.radare.org uses an invalid security certificate.

The certificate expired on November 8, 2017 2:53 PM. The current time is November 29, 2017 3:31 AM.

Error code: SEC_ERROR_EXPIRED_CERTIFICATE 
```

**Comment by radare** [comment]
Yep im aware since the day 1. I updated it alrrady but i guess i did that wrongly because the cert wasnt changed.  Kinda busy those days but its in my todo

**Comment by ilovezfs** [comment]
@radare no worries. Just letting you know because it turned our CI red :)

**Comment by radare** [comment]
Fixed
