### ISSUE TITLE
-D gdb required?

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#8930]
So in a previous issue, I showed that I was using ``gdbserver`` and connecting with the following line:

```bash
r2 -D gdb gdb://127.0.0.1:34967
```

I was told to omit the ``-D gdb``. However, when I do this, I cannot continue the program.

For instance, when I instantiate while omitting the ``-D gdb``, the following happens:

```
= attach 825 0
= attach 825 825
825
 -- Remember to maintain your ~/.radare_history
[0x00000000]> dc
PTRACE_CONT: No such process
waitpid: No child processes
[0x00000000]> 
```

When performing the same actions while using ``-D gdb``, i get:

```
= attach 807 0
 -- Print the contents of the current block with the 'p' command
[0x004009d0]> dc
```

The program in the second example is running at that point.

**Comment by radare** [comment]
-D gdb can be replaced with just -d. But if u drop it you will only have access to io, no debug
