### ISSUE TITLE
Ascii Graph loopne not working

### ISSUE THREAD

**Issue by bannsec** [radare/radare2#8932]
It looks like the ``loopne`` assembly instruction is not being added to the ``VV`` graph. Basically, when the graph hits that it just ends.

I've attached an example. To recreate the issue, do the following:

```
r2@radare:~/radare_work$ r2 -A ./hedgehog 
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
 -- Set color to your screen with 'e scr.color=true'
[0x08048480]> s main
[0x0804927c]> VV
```

The ``loopne`` instruction is at `0x08049299`.

[hedgehog.zip](https://github.com/radare/radare2/files/1523557/hedgehog.zip)

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/libr/anal/p/anal_x86_cs.c#L2152

**Comment by Maijin** [comment]
![image](https://user-images.githubusercontent.com/1408600/33518088-7cf61860-d78f-11e7-893a-51aac6db9af8.png)

**Comment by Maijin** [comment]
The issue here is actually that is misaligned stuff:

![image](https://user-images.githubusercontent.com/1408600/33518094-939db14a-d78f-11e7-9a32-68e8ca28ead3.png)

**Comment by bannsec** [comment]
oh. lol you're right. thanks!
