### ISSUE TITLE
x86 pseudo: support one-operand imul

### ISSUE THREAD

**Issue by ishitatsuyuki** [radare/radare2#8934]
If there's only one operand, the other is implicitly defined as eax or its 16/8 bit variant. Currently, `f7e9` is wrongly shown as `ecx *=`.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/blob/master/libr/parse/p/parse_x86_pseudo.c#L56

**Comment by mrpaja** [comment]
Yeah, I can reproduce it. Here is some code to test it:


#include <stdio.h>
int sum(int a, int b) {
	return (a+b);
}
 
int main()
{
	int a = 3;
	int b = 2;
	int res = sum(a,b);

	__asm__ volatile("mov -0x4(%rbp), %eax;" 
			"movl $10, %edi;"
			 "imul %edi;"
			 "mov %eax, -0x4(%rbp);");
	printf("result %d\n", res);
	return 0;

}

I'll fix it!

**Comment by radare** [comment]
👍

**Comment by Maijin** [comment]
https://github.com/radare/radare2/pull/8965
