### ISSUE TITLE
rasm2 'mov byte [esp + eax + 0xf], 0' produces c644240f00 ('mov byte [esp + 0xf], 0')

### ISSUE THREAD

**Issue by johnchen902** [radare/radare2#8935]
## Steps to Reproduce
```
$ rasm2 -d c644040f00
mov byte [esp + eax + 0xf], 0
$ rasm2 'mov byte [esp + eax + 0xf], 0'
c644240f00
$ rasm2 -d c644240f00
mov byte [esp + 0xf], 0
```
## Version
I'm on an old one (commit 149f4b61de0ff322a010e80d10eb522840dbb327) but @xarkes said it's reproducible on master.

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```
