### ISSUE TITLE
Missing REX.W (64-bit operand) prefix when assembling with arch = x86.nz

### ISSUE THREAD

**Issue by ranweiler** [radare/radare2#8939]
## Summary
In some cases, the "handmade" (`x86.nz`) x86 assembler fails to set REX.W prefixes to indicate 64-bit operands. I originally stumbled across this while trying to edit a binary in `r2` with the `wa` command.

## Details + repro

Consider the raw instruction as I found it "in nature": `48c745f823010000`.

Disassembling using `rasm2`:
```
$ rasm2 -a x86 -b 64 -d 48c745f823010000
mov qword [rbp - 8], 0x123
```

My expectation is that I can invert this process, but with the default `x86.nz` assembler, I instead get:
```
$ rasm2 -a x86 -b 64 'mov qword ptr [rbp-8], 0x123'
c745f823010000

$ rasm2 -a x86.nz -b 64 'mov qword ptr [rbp-8], 0x123'
c745f823010000
```

Some assembly statements do not have unique bit encodings, so without further info, this _could_ be fine. But I dug into it, and based on the Intel manual and other observations, I expect the emitted instruction to have a `0x48` REX prefix with a set `W` bit, which indicates a 64-bit operand. Checking by roundtripping, we see a discrepancy:

```
$ rasm2 -a x86 -b 64 -d c745f823010000
mov dword [rbp - 8], 0x123
# expected qword, not dword!
```

Other assembler backends yield different results which _do_ match my expectation:
```
$ rasm2 -a x86.as -b 64 'mov qword ptr [rbp-8], 0x123'
48c745f823010000

# note that we drop the `ptr` keyword because we are using nasm
$ rasm2 -a x86.nasm -b 64 'mov qword [rbp-8], 0x123'
48c745f823010000
```

I also triple-checked by using this command (which I'd expect to at least agree with the `x86.as` option):
```
$ echo -e "mov qword ptr [rbp - 8], 0x123" | as -o /dev/null -64 -al -msyntax=intel -mnaked-reg
GAS LISTING                     page 1
   1 0000 48C745F8      mov qword ptr [rbp - 8],0x123
   1      23010000
```

## Environment

This was first observed on `rasm` 2.0.1 on 64-bit Linux (as shipped with Void Linux), then confirmed on a build of the latest `master` branch (04b32a252c61b36b6f27b98fd2e32458f41c298d).

Unless I'm missing something (and this is somehow expected behavior), I'd be happy to put together a PR to try and fix this, pending confirmation.

Thanks!

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```
