### ISSUE TITLE
Flat Mach-o treated as XTR format

### ISSUE THREAD

**Issue by xtsop** [radare/radare2#8949]
Flat Mach-o files are parsed as XTR format. The issue is in libr/bin/bin.c and requires to find how the binfile->curxtr is set.

**Comment by XVilka** [comment]
Please provide a test file and create a testcase in radare2-regressions

**Comment by xtsop** [comment]
Download the IPA from below.

https://appscan.ibmcloud.com/api/V2/Tools/ScanDemoFiles/MobileAnalyzerIos $
unzip demo.ipa -d demo $ cd demo/Payload/Altoro-App.app/ $ r2 Altoro-App
iAj
{{"arch":"arm","bits":32,"offset":16384,"size":448432,"machine":"v7"},{"arch":"arm","bits":32,"offset":999424,"size":448468,"machine":"v7s"},{"arch":"arm","bits":64,"offset":475136,"size":518784,"machine":"v8"}}

Please provide a link with details on how am I supposed to add the test
case (eg. Fork regressions, add xyz, push changes)

On 4 Dec 2017 04:35, "Anton Kochkov" <notifications@github.com> wrote:

Please provide a test file and create a testcase in radare2-regressions

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/radare/radare2/issues/8949#issuecomment-348858547>, or mute
the thread

**Comment by xtsop** [comment]
You can also test it against the TestApp.ios that is on
radare2-regressions/bins/mach0/

On 4 Dec 2017 04:35, "Anton Kochkov" <notifications@github.com> wrote:

Please provide a test file and create a testcase in radare2-regressions

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/radare/radare2/issues/8949#issuecomment-348858547>, or mute
the thread

**Comment by radare** [comment]
This issue should be fixed now
