### ISSUE TITLE
Enable GDB and missing architectures for Windows (AppVeyor)

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8950]
- [ ] Propeller architecture
- [x] GDB support

See https://github.com/radare/radare2/commit/410ca098030e18f9cff00d49c45499fa33b4f1db and https://github.com/radare/radare2/commit/12b9d8c3b47f470e11030f97544c864ae54d7e98

**Comment by XVilka** [comment]
@xarkes shall I do that? Will you solve the cutter side?

**Comment by xarkes** [comment]
You can do that but make sure it does not brake the dynamic linking build on Appveyor.
I will fix Appveyor build tonight/tomorrow so you can try.

**Comment by xarkes** [comment]
Now you can try @XVilka

**Comment by radare** [comment]
isnt gdb support enabled for windows already? i saw a commit in r2-2.1 for this

**Comment by XVilka** [comment]
It was disabled due to some linking problems with Cutter.

**Comment by xarkes** [comment]
You can try again, if anything is wrong, the Appveyor build will fail (so you don't merge until it's green)

**Comment by XVilka** [comment]
@xarkes done.

**Comment by xarkes** [comment]
See https://github.com/radare/radare2/pull/9178
Once this is done there shouldn't be many remaining failing tests on Appveyor.

**Comment by radare** [comment]
ping, can we get this done before monday? or move to 2.5?

**Comment by radare** [comment]
MOVING AWAY; TOO MUCH TIME WAITING FOR A REPLY

**Comment by pelijah** [comment]
ping @XVilka

**Comment by radare** [comment]
ping @XVilka

**Comment by xarkes** [comment]
Propeller was added by @pelijah here https://github.com/radare/radare2/pull/9639
