### ISSUE TITLE
anal.arch is null when opening simple.gb on windows

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8954]
anal.arch is null when opening simple.gb on windows

**Comment by Maijin** [comment]
[simple.zip](https://github.com/radare/radare2/files/1527665/simple.zip)

**Comment by radare** [comment]
thats probably a build issue on meson, is meson building the anal.gb?

**Comment by radare** [comment]
yes it is..so it should work. can you try again with master?

**Comment by Maijin** [comment]
Just retried, it is still on master

**Comment by radare** [comment]
Only on windows? Thats wtf anyone with windows can chk this? Works fine on mac and linux

**Comment by Maijin** [comment]
@xarkes probably^

**Comment by radare** [comment]
still?

**Comment by Maijin** [comment]
Yes still

**Comment by radare** [comment]
Is the anal plug compiled at all with meson on windows?

**Comment by Maijin** [comment]
yes https://github.com/radare/radare2/blob/master/libr/anal/meson.build#L33

**Comment by radare** [comment]
Then wats the problem?

**Comment by Maijin** [comment]
anal.arch is null when opening simple.gb on windows

**Comment by radare** [comment]
I know. The title is quite easy to understand.

Im trying to understand why the gb plugin is not loaded when a gb file is loaded. Because that works everywhere except for that target i never care.

**Comment by xarkes** [comment]
Just tried and after opening `simple.gb` file, `asm.arch` is indeed `gb`.

**Comment by xarkes** [comment]
Sorry I was just waking up

**Comment by xarkes** [comment]
It's pretty simple, gb is not in meson.build anal array. So it's not built. Making a PR.

**Comment by Maijin** [comment]
kk well it was in plugin meson which I thought was the place to put the meson stuff now it's been removed :p libr/meson.build seems to be missing in this one indeed

**Comment by xarkes** [comment]
Fixed in https://github.com/radare/radare2/pull/9257
