### ISSUE TITLE
asm.describe and ?d doesn't work on windows

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8956]
asm.describe and ?d doesn't work on windows

![image](https://user-images.githubusercontent.com/1408600/33570088-ff71d980-d92b-11e7-8856-621435b79da4.png)

**Comment by radare** [comment]
because of the ethernal sdb path issue

**Comment by xarkes** [comment]
ping @xarkes

**Comment by radare** [comment]
@xarkes  what about adding `dir.sdb`?

**Comment by xarkes** [comment]
To load sdb files from different locations? Why not.

**Comment by xarkes** [comment]
But here I don't think it's the issue. It is more likely a missing file.

**Comment by radare** [comment]
Because of the way the dist is done?

**Comment by xarkes** [comment]
Not sure, I'll debug it this week end.

**Comment by radare** [comment]
no time to fix this in time.

**Comment by Maijin** [comment]
Still not fixed, it works only when r2 is launched from its directory, doesn't work with installer rightclick addition or when r2 is used from prompt with a different PATH

**Comment by pelijah** [comment]
It is a global issue. r2 can't load anything if it was launched from outside of the installation directory, not only opcodes sdb.

**Comment by Maijin** [comment]
yes this impacts also fortunes, types etc.

**Comment by radare** [comment]
Im working on a fix for this

**Comment by radare** [comment]
See dir.prefix

**Comment by pelijah** [comment]
What about combining dir.prefix with r_sys_get_src_dir_w32? For example: https://github.com/pelijah/radare2/commit/d6ce8268f039ebde5c4186d3969948dbfd6e1e69
Works fine on my machine with "installed" version of r2.

**Comment by radare** [comment]
Yes. Ideally this code should have no system dependant code

**Comment by radare** [comment]
can any windows user do a pr with this fix?

**Comment by xarkes** [comment]
I think @pelijah commit with `r_sys_get_src_dir_w32` is our best bet.

**Comment by xarkes** [comment]
Having no system dependant code is hard because on Windows, one can install radare2 anywhere he wants, while on linux most users just set its installation folder during compilation (~ or /usr).
If he can PR it's nice, otherwise just copy is patch and push to master.

**Comment by pelijah** [comment]
One moment.

**Comment by radare** [comment]
closing as its fixed now
