### ISSUE TITLE
VV graph view is broken on Windows

### ISSUE THREAD

**Issue by Alex131089** [radare/radare2#8964]
VV graph view seems to be broken on Windows and thus also in Cutter.

Example with [windirstat1_1_2_setup.exe](https://sourceforge.net/projects/windirstat/files/latest/download)
Using radare1.0 : 
![image](https://user-images.githubusercontent.com/1735067/33628210-4cfff75c-da00-11e7-921b-ec6e92de2064.png)
Using radare shipped with Cutter 1.0 (radare2 2.2.0-git 16646 @ windows-x86-64 git.2.1.0-62-g410ca0980) : 
![image](https://user-images.githubusercontent.com/1735067/33628276-7afbdb3a-da00-11e7-92ae-68de306b8114.png)
radare2 1.6.0-git 14979 @ windows-x86-32 git.1.5.0-45-g3fd5112d9 doesn't even seems to produce output (agj & pdj gives something though).

Someone said "is not cutted into parts by JCC" (whatever it means).
If that's useful, someone else asked me to provide output of agj & pdj : https://dpaste.de/SstD (link expires in less than a month)

**Comment by Maijin** [comment]
Never report issues with r2 not from git -> https://ci.appveyor.com/api/buildjobs/lj1qd1os7txyas01/artifacts/radare2_installer-vs2015_64.exe

But just for info this is reproducible with latest r2 from git.

**Comment by Maijin** [comment]
Bad regressions !

**Comment by radare** [comment]
please, someone confirm if this is fixed or wat

**Comment by Alex131089** [comment]
Not fixed.

radare2 2.2.0-git 1 @ windows-x86-64 git.
commit: 499cb34d8e2faa8baa0177bf37d8d089e570c24e build: Mon 12/18/2017__15:59:04.48
aaa ; VV
![image](https://user-images.githubusercontent.com/1735067/34115975-5d7ca884-e417-11e7-8d48-f9eb4f4d9c98.png)

**Comment by wargio** [comment]
for me it's fixed: https://imgur.com/a/GYT8n

```
> .\radare2.exe -version
radare2 2.2.0-git 0 @ windows-x86-64 git.2.2.0-git
commit: HEAD build: 2017-12-18__17:02:58
```

**Comment by Alex131089** [comment]
My test, in case there's something wrong : 
- download `radare2-vs2015_64-2.2.0-git.zip` artifact from https://ci.appveyor.com/project/radare/radare2-shvdd/build/job/m85gss1mawqiig86/artifacts (first test was done with https://ci.appveyor.com/project/radare/radare2-shvdd/build/git-15131, just tried again with latest)
- extract it
- powershell & cd to the directory
- run `.\radare2.exe c:\path-to\windirstat1_1_2_setup.exe`
- type `aaa` then `VV`

**Comment by radare** [comment]
if you analyze with aab it works fine.

the problem happens with msvc32 and msvc64, cant reproduce with the mingw32/64 builds.

happens with any binary, and i've observed no bad data from `ao` but the function information is wrong and all the basic blocks are wrong.

i have fixed almost all warnings in the msvc build, but none was related. asan and valgrind say nothing.

im out of ideas right now..

**Comment by radare** [comment]
this is probably the most important issue to be fixed for 2.2, otherwise windows users are doomed. anyone with windows and msvc can pls halp on this? i cant build and test my changes in local because of this, maybe adding some printfs will help to understand the diff on the `af` analysis loop between mingw and msvc

**Comment by xarkes** [comment]
Bug is likely in `r_anal_fcn`

**Comment by radare** [comment]
Like if it was a small function :p but why behaves different depending on compiler if no warnings or undefined behsviour issues are found?

**Comment by xarkes** [comment]
Bug at fcn.c line 882 op.type seems to be an unsigned __int64 but the first 4 bytes are corrupted:
Windows:
op.type == 0xffffffff80000001
Linux:
os.type == 0x0000000080000001

**Comment by xarkes** [comment]
Ok so WTF but here is the bug:
`anal_x86_cs.c` line `2153`
`os->type = R_ANAL_OP_TYPE_CJMP` on Windows gives `0xffffffff80000001`
`os->type = R_ANAL_OP_TYPE_CJMP` on Linux gives `0x0000000080000001`
Now have fun with that.

**Comment by xarkes** [comment]
Even after adding `op->type = (ut64) R_ANAL_OP_TYPE_CJMP & UT32_MAX` the switch in `fcn.c` line `882` never reaches the correct `case: R_ANAL_OP_TYPE_CJMP` probably because `op->type` is ut64 and for some reason it thinks that `0x0000000080000001` != than `80000001`

**Comment by radare** [comment]
Try again. I did a blind fix

**Comment by xarkes** [comment]
![2017-12-23-111520_1170x996_scrot](https://user-images.githubusercontent.com/10772605/34318884-947a1e66-e7d2-11e7-90a5-1df78e0f14ab.png)
Yeay looks fixed!

**Comment by radare** [comment]
😍😍😍😍

Love those blindfixes!

Thanks xarkes for the hint :)

**Comment by xarkes** [comment]
I'm closing the issue, @Alex131089 feel free to reopen if it's not fixed on your side.

**Comment by Alex131089** [comment]
```
radare2 2.2.0-git 1 @ windows-x86-64 git.
commit: b39995956028ce6371c3921e169dffa559d67864 build: Sat 12/23/2017__ 1:55:46.90
```
![image](https://user-images.githubusercontent.com/1735067/34318988-69e49f3e-e7d5-11e7-86d3-67f7de235275.png)

Thanks :)
