### ISSUE TITLE
Analysis hangs with a specific library (shared object)

### ISSUE THREAD

**Issue by cmrd-senya** [radare/radare2#8969]
I'm using radare2 on ubuntu 16.04 x64. I'm trying to research an ARMv5 shared object. I'm using the latest radare2 release `2.1.0`.

When I run analysis `aaa`, it never gets finished.

[Here](https://framadrop.org/r/nbOYu1i_h4#MYR6djRV52Y16tB/5zaX6wOJ87RCclRCnG6FiZVPtnA=) you can download the file I'm trying to anylize.

Here is the output of my session:
```
[0x00024470]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[ ] 
[Value from 0x00000000 to 0x00134be0
aav: 0x00000000-0x00134be0 in 0x0-0x134be0
aav: 0x00000000-0x00134be0 in 0x13d000-0x149164
aav: 0x00000000-0x00134be0 in 0x149164-0x18ad658
```

After that it hangs, but I'm able to ctrl-c back to radare2's cli.

**Comment by Maijin** [comment]
[libmedia.zip](https://github.com/radare/radare2/files/1534666/libmedia.zip)

**Comment by sivaramaaa** [comment]
hi @cmrd-senya  , 
I have tested aaa command with ur binary , the analysis doesn't hang , it just a little slow with aav command 
The problem lies in the range  0x149164-0x18ad658 (which is a lil huge), it should take around 1 - 1:30 hrs to complete the analysis :P 
Maybe we can skip aav command while running aaa command for large ranges , what do u think @Maijin  ??

**Comment by Maijin** [comment]
I think this should be covered by anal.in

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/3608

**Comment by Maijin** [comment]
anal.noncode is probably not working too then

**Comment by cmrd-senya** [comment]
@sivaramaaa, thanks for your reply!

It would be okay for me to run it for 1.5 hours, but since I can't save and load project as I described at #8978, I would have to do that every single time I want to work with the file. Either issue solved would make radare2 usable for me in this case.

**Comment by Maijin** [comment]
just ctrl-C at the last aav search aav: 0x00000000-0x00134be0 in 0x149164-0x18ad658 for now and it'll work like a charm.

**Comment by Maijin** [comment]
There are still issues too because at `aav.0x00124ce4`, a string should be defined and it is not etc. But the XREF is there though

**Comment by Maijin** [comment]
aav is not respecting anal.vinfun too

**Comment by radare** [comment]
I think aav should be faster. I’ll look into it later and see how to imrpove it

Meanwhile can someone compare aav and aar times?

**Comment by Maijin** [comment]
@sivaramaaa estimation aav 1h30. aar only 21 sec

**Comment by radare** [comment]
Wow. Aav should be muuuuch faster than aar. We are doing something wrong here. Maybe the problem is chking if the ptr is in a region or so :? Didnt had time to chk the code yet

**Comment by Maijin** [comment]
aav doesn't respect anal.vinfun and anal.noncode anymore or at least wrongly if so that's why it's lsow
