### ISSUE TITLE
Support double byte text(?) current escaped

### ISSUE THREAD

**Issue by gingerbeardman** [radare/radare2#8970]
Here's a screenshot from cutter.  Also see https://github.com/radareorg/cutter/issues/170

I've highlighted some lines because strings are not legible in yellow on white.

files [example.zip](https://github.com/radareorg/cutter/files/1530639/example.zip)

![screen shot 2017-12-06 at 11 33 46](https://user-images.githubusercontent.com/49612/33659854-b523ae2c-da79-11e7-9657-3caa9ee395ae.png)

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/2032

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/4997

**Comment by radare** [comment]
@kazarmy ^

**Comment by kazarmy** [comment]
The supposed double-byte strings appear to be false positives. Please inform me if they're not.

**Comment by radare** [comment]
ping @gingerbeardman

**Comment by gingerbeardman** [comment]
I'll look into it, thanks

**Comment by radare** [comment]
any update?

**Comment by gingerbeardman** [comment]
Yes, on further consideration I'm not 100% convinced this is double byte text
