### ISSUE TITLE
Implement @% modifier to change env var temporarily

### ISSUE THREAD

**Issue by radare** [radare/radare2#8979]
`> !echo $FOO@%FOO=BAR`

**Comment by karliss** [comment]
Does this has any use beside shell command `!` ?  If it is only for `!` it is already possible to use ` !FOO=BAR var2=val2 env` . I assume it is handled by shell.

**Comment by radare** [comment]
! does a fork, so the env in r2 is not changed at all, and that will not work on windows because setting vars before the command is just a unix thing, and r2 works on more systems than just unix based ones

**Comment by karliss** [comment]
I might be misunderstanding the use case behind this issue. Isn't avoiding permanent environment changes for whole r2 the whole point of changing env temporarily?  Similar effect can be achieved on windows by `!set var=value && cmd`. Unless there is other use case beside running shell commands, having to use platform specific way of setting environment doesn't seem like too much of a problem as commands executed in shell are platform specific anyway.

**Comment by radare** [comment]
yeah, there’s not really much use for it, but its a generic way to achieve that without having to use different syntax when running ! and set the value with r_num_math from a expression to resolve flags and eval vars. so, i think it’s handy in some situations
