### ISSUE TITLE
pd for blksz 1,2 and 3 outputs 1,2 or 3 lines but blksz 4 only 1

### ISSUE THREAD

**Issue by mrpaja** [radare/radare2#8982]
Is that on purpose? Also:  b 1 sets blksz to 1 and not 0.

**Comment by radare** [comment]
Wat

**Comment by Maijin** [comment]
Can you provide more details on what you are trying to show like an asciinema ?

**Comment by mrpaja** [comment]
https://asciinema.org/a/9bBeXVXfjJn9ZAJSxaPn0conb

**Comment by radare** [comment]
pd ignores blocksize and uses its value as number of instructions.

The command u are looking for is pD
