### ISSUE TITLE
Invalid JSON on x86 aOj

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#8987]
`r2 -qc "wx 8b4c2444 ; aOj 4~{}" -` works but

`r2 -qc "wx 8b4c2444 ; aOj 5~{}" -` Is adding a comma that corrupts the json 

https://github.com/radare/radare2/blob/master/libr/core/cmd_anal.c#L1490

**Comment by radare** [comment]
i didnt knew aOj was a command at all
