### ISSUE TITLE
Typo in String search

### ISSUE THREAD

**Issue by ziyaddin** [radare/radare2#9005]
When I use the command `r2 -q -c "/ a" my_file`, it gives a result like:
```
Searching 1 bytes from 0x00000000 to 0xffffffffffffffff: 61 
Searching 1 bytes in [0x400000-0x40220c]
hits: 15
Searching 1 bytes in [0x602e08-0x603048]
hits: 0
Searching 1 bytes in [0x603048-0x603060]
hits: 0
```
As you can see, it indicates `1 bytes` instead of `1 byte`. I observed that it is related to this line:
https://github.com/radare/radare2/blob/e985e0b9edb54d7d07584367db2aadc0c58112fe/libr/core/cmd_search.c#L2076

**Comment by radare** [comment]
Just send a pr. Click the pencil button in github

**Comment by ziyaddin** [comment]
Sure. I will work on it.

**Comment by ziyaddin** [comment]
@radare how can I test my code update?

**Comment by radare** [comment]
Test a typo? Wat

**Comment by ziyaddin** [comment]
I am asking generally. As I am new to this repo, I don't know how exactly I can test my file changes? I have read the documentation, but there is no sufficient info for that.

**Comment by xarkes** [comment]
`make` ?

**Comment by ziyaddin** [comment]
Thank you @xarkes!

**Comment by radare** [comment]
any update?

**Comment by radare** [comment]
tired of waiting. fixed in master

**Comment by ziyaddin** [comment]
You just waited for my fix these 4 days? :smiley: anyways, you have better fix than mine

**Comment by radare** [comment]
I did the fix yesterday because i needed for a script i was doing. There are still things to do, so im not closing the issue. Release will be next week, so if you are in the mood to get this PR in time it will be included in 2.2

Thanks!

**Comment by ziyaddin** [comment]
@radare it seems that many files have this "byte/bytes" issue. Should we focus only on this file or all of them?

**Comment by radare** [comment]
Maybe we should just use byte(s) and avoid that conplexity

**Comment by ziyaddin** [comment]
Nice point. Will work on that.

**Comment by ziyaddin** [comment]
@radare made a PR for that #9067

**Comment by radare** [comment]
Yeah saw that. Will check tomorrow

Thanks!
