### ISSUE TITLE
rax2 -F converts only first C string from stdin

### ISSUE THREAD

**Issue by hummelchen** [radare/radare2#9014]
rax2 version:
rax2 2.2.0-git 16698 @ linux-x86-64 git.2.1.0-114-g232029320
commit: 2320293207734dfe11a9fcdded5851812cde04ef build: 2017-12-13__22:20:25

rax2 output:
```
% rax2 -F <<EOF
"\xde\xad\xbe\xef"
"\x0b\xad\xf0\x0d"
EOF
deadbeef
```

**Comment by Maijin** [comment]
@kriw ^
