### ISSUE TITLE
Integrate with retdec?

### ISSUE THREAD

**Issue by fission1110** [radare/radare2#9017]
Avast just open sourced retdec.

Inline C decompilation would be a really cool feature!

Thoughts?

https://github.com/avast-tl/retdec
https://blog.avast.com/avast-open-sources-its-machine-code-decompiler

**Comment by Maijin** [comment]
Good you discover retdec just now but the plugin to use retdec with its API was already implemented 2 years ago https://github.com/jpenalbae/r2-scripts/blob/master/decompiler/decompile.js and available in r2pm, You can reuse this with the file and contribute to the repository if you want.
