### ISSUE TITLE
r2 couldn't find a function

### ISSUE THREAD

**Issue by qsphan** [radare/radare2#9019]
I'm attaching my binary, please remove the `.txt` if necessary.
[hello.txt](https://github.com/radare/radare2/files/1557590/hello.txt)
Here is the output
~~~~
$ r2 ./hello
 -- Change your fortune types with 'e cfg.fortunes.type = fun,tips,nsfw' in your ~/.radare2rc
[0x004005c0]> s main
[0x004006b6]> pdf
p: Cannot find function at 0x004006b6
[0x004006b6]> afl
[0x004006b6]> 
~~~~

**Comment by Maijin** [comment]
Read the doc, you need to analyze first, try aaa then read radare.today/posts/analysis-by-default/

**Comment by Maijin** [comment]
And also Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.
