### ISSUE TITLE
Keep getting "Error: Wrong reply" in rap server for mac/windows/ubuntu

### ISSUE THREAD

**Issue by securisec** [radare/radare2#9021]
Ubuntu setup and version:
```
radare2 2.2.0-git 16701 @ linux-x86-64 git.2.1.0-117-g4d1acc2
commit: 4d1acc2ff59b3eaa5ad05712d321220473ccecc2 build: 2017-12-14__17:47:42
```
```
└─▪ radare2 rap://:9999 
rap: listening at port 9999 ssl off
RAP Server started (rap.loop=true)
rap: client connected
open (1): (flags: 0) len: 27 filename: '/vagrant/tuctf/rev/unknown'
unknown command 0x06
[r] Cannot open 'rap://'
```

Mac version: 
```
radare2 2.2.0-git 16701 @ darwin-x86-64 git.2.1.0-117-g4d1acc2ff
commit: 4d1acc2ff59b3eaa5ad05712d321220473ccecc2 build: 2017-12-14__12:48:05
```
```
→ radare2 -
 -- This code was intentionally left blank, try 'e asm.arch = ws'
[0x00000000]> =+ rap://10.1.0.31:9999//vagrant/tuctf/rev/unknown
Connected to 10.10.10.31 at port 9999
waiting... ok
[0x00000000]> =
6 - rap://10.:9999//vagrant/tuctf/rev/unknown
[0x00000000]> ==6
fd:6> aaa
Error: Wrong reply
```

This wrong reply seems to be consistent and OS independent. Getting the same result in Windows also.

**Comment by radare** [comment]
Works fine here
<img width="1254" alt="screen shot 2017-12-18 at 18 38 54" src="https://user-images.githubusercontent.com/917142/34119519-bbcab5ba-e422-11e7-9063-120a8a25d0c7.png">

**Comment by radare** [comment]
also, vagrant is known to introduce networking issues. even aaa works for me. some ppl wascomplaining with vagrant+webserver, but i dont use vagrant

**Comment by securisec** [comment]
Thanks @radare ! I will close this as my platform issue then.

**Comment by radare** [comment]
I have tested this on vagrant also and works fine too.

**Comment by radare** [comment]
i have also tested in local, with =+ rap:// and the only reason why the `[r] Cannot open 'rap://'` error is because the port is already used

**Comment by securisec** [comment]
I am not sure why I am still getting the error then. I am guessing it is mostly like an issue with my setup then. when working on localhost it seems to be fine, but gets crazy when i start working between different vms. i will keep trying. thanks @radare !

**Comment by securisec** [comment]
@radare would you test this against a remote windows system using one of the latest windows installer?

**Comment by securisec** [comment]
By the way, most of my issues revolve around `Error: Wrong reply`

**Comment by radare** [comment]
Maybe related to some timeouts on the reads? Please let me know if i can do something to reproduce the issue. Is the network slow? If the issue is local/remote maybe is this

**Comment by radare** [comment]
I dont have any windows. I can do wine

**Comment by securisec** [comment]
I think you were right about the ports being blocked. I had firewall turned on on my Mac and that was getting in the way. I will try more on the windows side and see if i can replicate this. While I have you here, would you consider adding the IDA dgbservers to be compatible with radare2?

**Comment by radare** [comment]
It’s not a priority or need for me because i dont use or have IDA in any of my machines, and i mostly use frida, gdbserver and lldbserver as remote debugger backends.

 But i guess some people may be happy if r2 could speak to their agent. Theres a repo named radare2-ida that contains scripts and doc to transfer data between ida/idb and r2. 

You may fill an issue there. When the plugin is done (i dont think it should be hard to do) we can evaluate into merging it into r2 instead of having it as an external plugin in a separated repo.

**Comment by securisec** [comment]
Awesome! Thanks! I am aware of the radare2-ida. I have it documented in my wiki. I will create a feature request issue in that repo. Thanks @radare !

**Comment by BlackYoup** [comment]
Hello,

I keep getting this error too (even on local linux only). It works fine indeed when you connect the way with you show in your screenshots @radare but not when you connect through `=+ rap://127.0.0.1:1234//bin/ls`.

You can see the following asciinema which demonstrates the problem: https://asciinema.org/a/DvWGSAoxTokc2mNHRI0kb4Jyr

To resume:
- connecting using `=+ rap://127.0.0.1:1234//bin/ls` gives the initial reported error
- passing the connection string as the first argument of radare2 works fine

Also, I have the same problem when I try to load a debug session with `=+ rap://127.0.0.1:1234/dbg:///bin/ls` (as explained here https://radare.gitbooks.io/radare2book/content/debugger/remoting_capabilities.html) 

Maybe I'm missing something? The port I use to connect to radare2 isn't already taken by another process.
