### ISSUE TITLE
Handle 'O' in graph like its done in Visual

### ISSUE THREAD

**Issue by radare** [radare/radare2#9030]
switch between normal disasm, pseudocode and esil

**Comment by radare** [comment]
and maybe we should have a pDs too

**Comment by sivaramaaa** [comment]
Hey hi , 
I have implemented 'O' in graph to toggle between  disasm, pseudocode and esil , made a PR
And about pDs , do u mean to handle disassemble N bytes (pD) in graph ??
I need a little clarification on that , meanwhile i will look at  the regression caused due to that anal.in thing !!

**Comment by Maijin** [comment]
@sivaramaaa nop, just add another Vpppp with pds output

**Comment by Maijin** [comment]
I think pDs stuff is totally unrelated to graph.

**Comment by radare** [comment]
It is not. Pds in graph does recursive emulation, in the shell does linear. It is very related and way more useful when the code reuses register values

**Comment by Maijin** [comment]
ok but unrelated to his anal.in fix :p I'd say better use of @sivaramaaa knowledge on continuing fix of anal issue like #8706 not sure why got assigned to this tbh

**Comment by Maijin** [comment]
And is also unrelated to the 'O' issue that is now fixed

**Comment by Maijin** [comment]
Let's open a new issue for this pDs stuff

**Comment by Maijin** [comment]
#9038
