### ISSUE TITLE
pDs graph enhancement

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#9038]
From @radare:
Pds in graph does recursive emulation, in the shell does linear. Change have to be made so it becomes way more useful when the code reuses register values

**Comment by radare** [comment]
Its already accesible via Vvpp theres nothing new to do. Just make it accessible via O

Thats not an enhancement either

**Comment by Maijin** [comment]
Vvpp by O that's what you meant :P Could have easier if you wrote that
