### ISSUE TITLE
fd command should support filtering by string

### ISSUE THREAD

**Issue by radare** [radare/radare2#9045]
maybe in a subcommand like fdw or so. the thing is that we want to get classname and method name for a given offset, so we should be able to do:
```
> fdw class
> fdw method
```

-> for de winrar.. so it will get the closest flag matchin the given word string

**Comment by sivaramaaa** [comment]
Submitted a [PR](https://github.com/radare/radare2/pull/9050) regarding this implementation 
The output of the command looks like this 
```
[0x00400c90]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[0x00400c90]> s main+20
[0x00400db4]> fdw sym
sym.main
[0x00400db4]>
```
