### ISSUE TITLE
How to print RFLAGS value?

### ISSUE THREAD

**Issue by FFY00** [radare/radare2#9049]
How do I print it's value? I'm aware of `dr` but I don't want it's hexadecimal representation, I want to check the _sub-flags_ value.

http://wiki.osdev.org/CPU_Registers_x86-64#RFLAGS_Register
https://en.wikibooks.org/wiki/X86_Assembly/X86_Architecture#EFLAGS_Register

**Comment by Maijin** [comment]
try `dr ZF` for example

**Comment by FFY00** [comment]
Oh, thanks! I've also noticed that we get the initials of each enabled flag in `drr` and to dump the value of every flag, we can use `dr 1`.
