### ISSUE TITLE
base64 encoder and decoder fail to produce/reproduce proper value/string

### ISSUE THREAD

**Issue by OhioDuckFarmer** [radare/radare2#9062]
I was working on another issue and came across the need to decode a base64 string (via the p6d command) which to my surprise did not return anything (just a blank line).  To verify my string was corrected I used an online base64 decoder, where I received the proper decoded string.  Next I looked up issue #3311 (base64 encoder is broken) and followed the simple little sample shown there.  The results I received are:
```
[0x00000000]> w hello
[0x00000000]> p6e 5
EAAA/wA=
[0x00000000]> p6d 5

[0x00000000]>
```
The same type of behavior can be seen in the following case:
```
[0x00000000]> Cf 8 xx testvar1 testvar2 @ 0x0
[0x00000000]> pd
            0x00000000 format xx testvar1 testvar2 {
 testvar1 : 0x00000000 = 0xff000010
 testvar2 : 0x00000004 = 0x00000000
} 8
            0x00000008      1000           adc byte [rax], al
            0x0000000a      00fd           add ch, bh

[0x00000000]> k anal/meta/*
meta.0x0=f
meta.f.0x0=8,-1,eHggdGVzdHZhcjEgdGVzdHZhcjI=

[0x00000000]> p6d eHggdGVzdHZhcjEgdGVzdHZhcjI=
[0x00000000]> p6d 32 eHggdGVzdHZhcjEgdGVzdHZhcjI=

[0x00000000]> 
```

The version I am using is:
```
$ r2 -v
radare2 2.2.0-git 16767 @ linux-x86-64 git.2.1.0-140-g6c221fa
commit: 6c221fa3b1d3668f3afbea2d8dc6dce62afb085c build: 2017-12-20__14:13:13
```

**Comment by radare** [comment]
u r doing it wrong. p commands are to print what’s in the current block. argument is length, not a string.

you can use it like this:

[0x00000000]> p6e@s:pepee
cGVwZWU=
[0x00000000]> p6d@s:cGVwZWU=
pepee
[0x00000000]>

**Comment by OhioDuckFarmer** [comment]
Well that explains it.  Thanks for pointing out my misunderstanding of the command.  After reading the help I thought it was supposed to be p6e [length of string] string.
