### ISSUE TITLE
`wa test r8,r8` incorrectly assembles `test rax,rax`

### ISSUE THREAD

**Issue by MaskRay** [radare/radare2#9071]
```
[0x0047aece]> wa test r8,r8
Written 3 bytes (test r8,r8) = wx 4885c0
[0x0047aece]> pi 1
test rax, rax
[0x0047aece]> 
```

radare2 dropped the ball 😢 when I intended to make my one-byte binary fix to libclang.so.5.0 https://github.com/jacobdufault/cquery/issues/192 (BTW, cquery is a really awesome C++ language server)

I have to use `r2 -nwqc 'wx 4d @ 0x47aece' build/release/lib/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-14.04/lib/libclang.so.5.0`
But apparently `r2 -nwqc 'wa test r8,r8 @ 0x47aece' build/release/lib/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-14.04/lib/libclang.so.5.0` is more readable.

![](https://ptpb.pw/9VgG.jpg)

**Comment by Maijin** [comment]
Greetings,

x86.nz (x86 handmade assembler) is one of the many x86 assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix x86.nz in https://github.com/radare/radare2-regressions/blob/master/t.asm/x86/nz/x86_asm** You can do so with github web editor without even cloning the repo.

You can contribute to x86.nz by completing the following file https://github.com/radare/radare2/blob/master/libr/asm/p/asm_x86_nz.c.
You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a x86.ks…
or in radare2 session
	e asm.assembler = x86.ks
```

Others x86 assemblers are also available trough r2pm or master (see rasm2 -L list):

```
a___  16 32 64   x86.as      LGPL3   Intel X86 GNU Assembler
a___  16 32 64   x86.nasm    LGPL3   X86 nasm assembler
a___  16 32 64   x86.nz      LGPL3   x86 handmade assembler
ad__  32         x86.olly    GPL2    OllyDBG X86 disassembler
```
