### ISSUE TITLE
tj is missing

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#9073]
`tj`: print types in json format is missing

**Comment by marrakchino** [comment]
@radare I'd like to work on this feature.
@Maijin could you please specify the expected output? Is it as simple as printing the types in json format or are there details you didn't mention? 
Thanks.

**Comment by Maijin** [comment]
Something like [{"type": "char", "size": 3}, etc. 

You can also add the pf structure associated like "c" for char etc, information is there see `tk~char`

to get something like [{"type": "char", "size": 3, "format": "c"},{"type":"char *"...

**Comment by marrakchino** [comment]
Ok @Maijin , @XVilka are you already working on this?

**Comment by Maijin** [comment]
Go ahead @marrakchino

**Comment by giuscri** [comment]
@marrakchino are you still working on that?

@Maijin what's the `size` attribute? Why size of `char` is 3? Also, if it's something meaningful shouldn't that be included in plain `t` too?

**Comment by Maijin** [comment]
@giuscri 

The size attribute is what is available in `tk` and yes size and format could also added in `t`. 

Quite sure there is already a way to print sdb in json so yeah that could be enough, can you do it?

**Comment by giuscri** [comment]
OK. I think I can implement that

**Comment by marrakchino** [comment]
@giuscri I am quite busy right now so it might take some time before I submit a PR. Tell me if you want to work on it.

**Comment by giuscri** [comment]
@marrakchino Yes, I'd like to. (:

I've sent a first pull request now, not sure if it's good enough though.
