### ISSUE TITLE
radiff2 graph diffing doesn't seem to work

### ISSUE THREAD

**Issue by montekki** [radare/radare2#9076]
radiff2 -g main /bin/false /bin/true | xdot - produces the following result:

![2017-12-27-160906_1111x1060_scrot](https://user-images.githubusercontent.com/56672/34382946-0676a518-eb23-11e7-9fe1-1668f03f68f1.png)

Only one graph, no diffing

**Comment by Maijin** [comment]
That's expected output, if you want 2 graphs you need to do:

radiff2 -g main /bin/false /bin/true | xdot -
AND
radiff2 -g main /bin/true /bin/false | xdot -

**Comment by Maijin** [comment]
And like all diffing tools:

Red different,
Yellow partially different
Grey no difference

**Comment by montekki** [comment]
Ok, i see, and why could the diffing fail?
Here I have two graphs which are obviously different in their last node. I probably have implemented something wrong in analysis

![2017-12-27-162238_1920x1080_scrot](https://user-images.githubusercontent.com/56672/34383225-e4d2720a-eb24-11e7-8e51-a3fb3dcfb29b.png)

**Comment by radare** [comment]
radiff was unmaintained 4 years ago. no one showed interest on using or maintaining it all this time, and the changes in analysis have been making the whole situation a bit more hard to maintain, so, diffing is a pending thing to care soon or late.
