### ISSUE TITLE
Please re-open #9080

### ISSUE THREAD

**Issue by beaumontk** [radare/radare2#9081]
"But there is not really need of an issue without more description or additional info."

Please see the debug output in the zip file. It should be self-explanatory.

There are plenty of issues about PDC!

Please re-open!

**Comment by beaumontk** [comment]
Why?

**Comment by Maijin** [comment]
Because I told you what to do in the other issue.

**Comment by beaumontk** [comment]
You didn't look at my debug output! 

    On Wednesday, 27 December 2017, 17:47, Maijin <notifications@github.com> wrote:
 

 Because I told you what to do in the other issue.—

**Comment by Maijin** [comment]
The debug output doesn't look like pdf or pdc and I did look at them

**Comment by Maijin** [comment]
Continue discussion on 9080
