### ISSUE TITLE
Move plugins, r2pm, etc to $HOME/.local

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#9083]
Currently r2 saves everything in `.config`, while this kind of stuff should be saved in `.local` according to XDG:

```
XDG_CACHE_HOME = $HOME/.cache
XDG_CONFIG_HOME = $HOME/.config
XDG_DATA_HOME = $HOME/.local/share
```

May be put r2pm cache in .cache too.

**Comment by radare** [comment]
agree. xdg ftw

**Comment by rishi62** [comment]
Is anyone doing this?

**Comment by Maijin** [comment]
@rishi62 just do it

**Comment by rishi62** [comment]
So i guess it should go like this
plugins,r2pm,scripts(/rc.d/bin-*) ---> $HOME/.local/share  (user_data)
history ---> $HOME/.cache 

The visual mode store a hud file is it  visual config file?
Also,I am not sure what zignatures are?The zo command says it loads zignatures from sdb files  so i guess zigns dir is user related data?

**Comment by Maijin** [comment]
see r2 -hh output for more info too

**Comment by Maijin** [comment]
@XVilka ^

**Comment by rishi62** [comment]
Currently we have one MACRO set for .config file i.e R2_HOMEDIR. Should i make different MACROS for .cache, .config, .local ? 
`R2_CONFIG_HOME ".config/radare2"`
`R2_CACHE_HOME ".cache/radare2 "`
`R2_DATA_HOME ".local/share/radare2"`

Same as XDG.

**Comment by radare** [comment]
I have started to support dir.prefix, take. A look at the commit to do that change, and also, as well get rid of hardcoded paths in r2.

I did an rsysprefix api in rutil to help on that.

**Comment by Maijin** [comment]
https://github.com/radare/radare2/commit/31d550a54b3faf4e4d35a867331a524a96511ec8
https://github.com/radare/radare2/commit/303820dbac2663b8d2b7e9cd09b00cf987a0bd5d

**Comment by pelijah** [comment]
Still requires changes in r2pm.

**Comment by xarkes** [comment]
Yes, I will start working on new version of r2pm soon (one-two weeks).
