### ISSUE TITLE
Enable Mingw32 and Cygwin builds on AppVeyor back

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#9088]
The point is, we have more jobs on AppVeyor (3 or 4 parallel jobs) than on Travis, so for commit or pull request to get a "green light" from those we're always waiting for Travis, while AppVeyor usually checks everything much faster. Maybe we now can return Mingw32 and Cygwin builds (may be WSL too?) in AppVeyor? What are your thoughts?

cc @radare @AlexKornitzer @xarkes @Maijin

**Comment by xarkes** [comment]
I'm ok with that but only if we run the tests on every job. Also I don't
want to play with mingw/cygwin it is such a pain

**Comment by Maijin** [comment]
The current way it works to generate the installer seems to be ok

**Comment by XVilka** [comment]
Closing because of https://github.com/radare/radare2/issues/9973
