### ISSUE TITLE
Graphic View for Sections

### ISSUE THREAD

**Issue by Fineas** [radare/radare2#9097]
Maybe is me the one that does not know how to do it, or it truly isn't implemented.
I would suggest a Graphical View of the Sections.
My struggle is that I must continuously increase the offset for:` pd <offset> @ section.<name>`
It would be much easier to be able to do it the same way we do it with functions: `VV` and just press the `down arrow key` to scroll threw the section itself.

I hope this also sounds like a good idea for you guys and if not, sorry to bother.

**Comment by radare** [comment]
S=

**Comment by radare** [comment]
Pd argument is not an offset

**Comment by Fineas** [comment]
my bad, `pd <num_of_bytes> @ section..<name>` *
I know about S= , but I was talking about something more like a graph view for `section..bss` or `section..data` .

**Comment by radare** [comment]
graph of a section? wtf

**Comment by radare** [comment]
any example of what you have in mind? i dont understand the proposal

**Comment by Maijin** [comment]
Please open a new issue with a mock-up or a better description of your proposal, for now I will close.
