### ISSUE TITLE
Integrate sdb into radare2

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#910]
# SDB specific
- [x] Fix every GCC warnings of [sdb](https://github.com/radare/sdb).
- [x] Close sdb [bugs](https://github.com/radare/sdb/issues).
- [x] Finalize the sdb [specification](https://pad.nopcode.org/p/sdb), and put in [into the git repository](https://github.com/radare/sdb/tree/master/doc).
# Integration
- [ ] Port `RBinInfo` into sdb.
- [x] Port `RAnal` into sdb. https://github.com/radare/radare2/issues/210
- [x] Store all format specific information (like 'Has NX', 'SafeSEH', etc) in sdb instead of RBinInfo
- [x] Multiuser access to sdb.

**Comment by radare** [comment]
this is far from done, and sdb needs love in his own repository

**Comment by radare** [comment]
i think we can close this issue, the new sdb branch will be merged soon, and we are progressively updating many parts to use sdb. no need to track them here.
