### ISSUE TITLE
Meson build MSVC - Bug and Fix - MS Documentation Update

### ISSUE THREAD

**Issue by igiagkiozis** [radare/radare2#9101]
Attempted to build radare2 with Meson with a Visual Studio 2017 target. 
1. The documentation is a tad out of date on this, the first section on Meson is fine, but there is no meson.bat in the source. At any rate, anyone that wants to compile radare2 for the aforementioned target, you can use the following command issued from the radare2 source root dir: 
>>  python meson.py build --backend vs2017 --buildtype release --default-library static
where 'build' is the desired build output directory. 
Then go in the 'radare2 source'/build directory and compile the solution. 

At present compilation will fail because there is a missing file in the meson.build in the 'radare2 source/libr/asm' directory. Namely the following should be added to 'radare2 source/libr/asm/meson.build' after line 141: 
@@ -139,6 +139,7 @@ files=[
 #'arch//z80/expressions.c',
 'arch//z80/z80.c',
 #'arch//z80/z80asm.c',
+'arch//wasm/wasm.c', **<-- This line was missing**
 ]

Cheers and thanks for the great project!

**Comment by xarkes** [comment]
There is an "under construction" script in sys/meson.py which replaces meson.bat. It aims at automating the build on Windows (which I find harder than on linux due to VC vars), building radare2, building SDB, and automating the installation script.
Sorry about the non updated documentation.

**Comment by igiagkiozis** [comment]
That's okay! Who do I contact if I'd like to contribute? (i.e. so that I can submit a pull request instead of nagging here...)

**Comment by Maijin** [comment]
CMAKE support is already done, but it's not planned to be merged in master afaik

**Comment by xarkes** [comment]
If you want to contribute you can ask questions on irc/Telegram, or just make a pull request and one of us will review it and give you hints/advices.

**Comment by XVilka** [comment]
Can be this closed?
