### ISSUE TITLE
`syntax error: error in error handling` error message

### ISSUE THREAD

**Issue by evandrix** [radare/radare2#9111]
### Work environment

OS: OSX 10.12.6

$ `r2 -v`
```
radare2 2.2.0 0 @ darwin-x86-64 git.2.2.0
commit: HEAD build: 2017-12-24__19:20:45
```

$ `r2 -V`
```
2.2.0  r2
2.2.0  r_anal
2.2.0  r_lib
2.2.0  r_egg
2.2.0  r_asm
2.2.0  r_bin
2.2.0  r_cons
2.2.0  r_flag
2.2.0  r_core
2.2.0  r_crypto
2.2.0  r_bp
2.2.0  r_debug
2.2.0  r_hash
2.2.0  r_fs
2.2.0  r_io
2.2.0  r_magic
2.2.0  r_parse
2.2.0  r_reg
2.2.0  r_sign
2.2.0  r_search
2.2.0  r_syscall
2.2.0  r_util
```

### Expected behavior
No error message should be displayed, and `r2pipe` should work properly and interface with `r2`.

### Actual behavior
Error message `syntax error: error in error handling` is displayed 3 times.

### Steps to reproduce the behavior 
$ `brew install radare2`
... then try to run it on any file at all

### Additional Logs, screenshots, compiled binaries, source-code,  configuration dump, ...

Drag and drop zip archives containing the compiled binaries here, don't use external services or link.
[r2.zip](https://github.com/radare/radare2/files/1596316/r2.zip)

**Comment by radare** [comment]
thats a known bug of the brew pkg, it was filled a while ago. using r2 from git works fine.

this error message doesnt belongs to r2

**Comment by radare** [comment]
see https://github.com/radare/radare2/issues/4793

**Comment by radare** [comment]
pls fill an issue in brew, we dont maintain that package

**Comment by evandrix** [comment]
alright, I tried to compile it from git i.e. `git clone --recursive https://github.com/radare/radare2 && cd radare2 && sys/install.sh`, but the following error happens:
```
...
LD libr_bin.dylib
$HOME/Downloads/radare2/libr/bin/p
SHLR=$HOME/Downloads/radare2/libr/..//libr/../shlr
gmake[1]: *** [Makefile:32: all] Error 2
gmake: *** [Makefile:55: all] Error 2
Oops
```

**Comment by radare** [comment]
this is not the error. the error should be some lines above, grep for ‘error:’ 

and yep. master is broken because i merged a PR that misses a file. fixing right now, wait few mins and run the same script again. also you should remove the brew pkg before doing that

**Comment by evandrix** [comment]
alright, good to know. thanks ^_^!!

**Comment by evandrix** [comment]
can confirm that it compiles beautifully without errors now 👍 

$ `r2 -v`
```
radare2 2.3.0-git 16905 @ darwin-x86-64 git.2.2.0-96-ge854df5c0
commit: e854df5c0f8cc1e9e096c007eab25f3668315058 build: 2018-01-04__02:18:53
```

$ `r2 /bin/ls`
```
 -- Add custom Have you setup your ~/.radare2rc today?
[0x1000011e0]>
```

**Comment by xzcvczx** [comment]
just fyi this appears to be being caused by lang_lua.dylib

**Comment by radare** [comment]
Wtf? Is brew compiling lua?

**Comment by xzcvczx** [comment]
yes brew builds lua as its not part of base macOS, and homebrew includes radare2-extras and radare2-bindings and so builds the lua plugin
