### ISSUE TITLE
Bad LEA disassembled opcodes

### ISSUE THREAD

**Issue by kartone** [radare/radare2#9126]
### Work environment

| Questions                                | Answers
|------------------------------------------|--------------------
| OS/arch/bits                             | Linux kali 4.14.0-kali1-amd64 
| File format of the file you reverse      | ELF
| Architecture/bits of the file.           | x86/64
| r2 -v full output                        | radare2 2.3.0-git 16905 @ linux-x86-64 git.2.2.0-96-ge854df5c0

### Expected behavior

    8d 45 fc             	lea    eax,[ebp-0x4]

### Actual behavior

    8d 45 fc              lea eax, ebp - 4 

### Steps to reproduce the behavior 

https://asciinema.org/a/X2XKN4pvQjZub0ys9uzhJ2pLY

### Compiled binaries

Bin: crackme0x02 from [IOLI crackmes serie](https://dustri.org/b/files/IOLI-crackme.tar.gz)

**Comment by radare** [comment]
Thats expected. It has been discussed recently to make the syntax more readable, we can bring back the old syntax for lea, but as long as lea is not accessing memory the [] is confusing. We should probably relay this for an asm filter or asm.syntax.

**Comment by neeocf** [comment]
I agree that [] would be confusing, but the "[r|e]bp - X" is not replaced by "local_Xh" for lea as it used to be (and it was very helpful).

**Comment by radare** [comment]
Oh! Thats a bug then

**Comment by kartone** [comment]
@neeocf That is exactly what I meant! Completely agree with you.

**Comment by radare** [comment]
FIxed by rollbacking the [] change. also it was inconsistent with the assembler and syntax of [] is memory reference which is base+delta, so other syntax would be wrong for a generic assembler
