### ISSUE TITLE
Support binary diff format too

### ISSUE THREAD

**Issue by radare** [radare/radare2#9128]
There'r standards like bsdiff and gdiff:

https://www.w3.org/TR/NOTE-gdiff-19970901

**Comment by zadlg** [comment]
I'm working on that

**Comment by zadlg** [comment]
(https://github.com/radare/radare2/compare/master...zadlg:radiff2_impl_gdiff_support?expand=1)[https://github.com/radare/radare2/compare/master...zadlg:radiff2_impl_gdiff_support?expand=1]

I've begun something. I followed the GDIFF standard, and I propose the option `-B patch_file` for a binary output

**Comment by zadlg** [comment]
Solved, cf https://github.com/radare/radare2/pull/9140

**Comment by radare** [comment]
thanks!!
