### ISSUE TITLE
GameBoy function names at addresses below $0100 act weirdly

### ISSUE THREAD

**Issue by MineRobber9000** [radare/radare2#9138]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu xenial/x86_64/64
| File format of the file you reverse (mandatory)      | GB
| Architecture/bits of the file (mandatory)            | LR35902/8
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0-git 16926 @ linux-x86-64 git.2.2.0-117-gd42e48d commit: d42e48d05e1c8f31befe54055b358c6c2c28e945 build: 2018-01-05__18:22:21
| r2 -V full output in a pastebin document (mandatory) | [as you wish](https://gist.github.com/MineRobber9000/51595b1ee9879bfdd42d156394122307)

### Expected behavior

Labeling a function at an address less than 0x0100 will cause the name to be placed in the call instruction, like:

```
call FunctionAt007B
```

### Actual behavior

Labeling a function at an address less than 0x0100 will **not** cause the name to be placed in the call instruction, but rather, off to the right, like:

```
call 0x007b                                        ; FunctionAt007B
```

### Steps to reproduce the behavior 
- Download attached ROM ([haxxor.zip](https://github.com/radare/radare2/files/1608469/haxxor.zip), shows "Haxxor" when loaded in emulator or console)
- Run the following radare2 commands: (note: the beginning part is to avoid having to set buffer size)

```
s 0x150
af
afn main
pdf
```

- Note the call to 0x007b.
- Name that function (it's a routine to copy monochrome sprites into character RAM) like so:

```
af @ 0x007b
afn CopyMonoSprite @ 0x007b
```

- Look at the disassembly of the main function once more. (if you did exactly as I did you should still be at main)

```
pdf
```

- Instead of it showing `call CopyMonoSprite` or similar, you will see `call 0x007b` with `CopyMonoSprite` off to the right as a comment.
- If you aren't sure what behavior I was expecting, do the same with `DisableLCD` (0x0194).

```
af @ 0x0194
afn DisableLCD @ 0x0194
pdf
```

### Additional Logs, screenshots, compiled binaries, source-code,  configuration dump, ...

Attached is the `haxxor.gb` file.

**Comment by radare** [comment]
this is unrelated to gb afaik

**Comment by astuder** [comment]
I think this is the same issue I reported on 8051. The cut-off where numbers in the disassembly are replaced with flags can be set with asm.minvalsub. Default is 0x100. However, lowering this parameter may create a new issue, as r2 will start interpreting immediates as pointers.

I think this problem could be resolved by consulting RAnalOp when doing the substitution. 

- Always replace jump targets (op->jump, op->fail)
- Always replace pointers (op->ptr)
- Control with asm.minsubval when to replace immediates (op->val)

Of course, this assumes that RAnalOp is used consistently across architectures.

**Comment by radare** [comment]
ptr and val are not used in the same way on all archs, but those replaced values are not taken from the AnalOp, but from the string. and it’s actually the same problem because if you do mov eax, 3 and you have a flag at offset 3, even if its not a function it will be shown and will mess the disasm.

one option would be to enforce replacing function names ALWAYS, no matter the offset, and keep honoring that minvalsub for flags

**Comment by astuder** [comment]
I agree that ptr vs. val is ambiguous. But if AnalOp is available in the context where values are substituted, I think it should pretty save to rely on op->jump to decide whether to apply minvalsub.

Not all jump targets are function entry points.

**Comment by radare** [comment]
its not that simple..

Sometimes the value is not really meaningful by itself, like a memory reference, or a relative address computed from a reference register, in those cases RAnalOp doesnt works, but RParse is able to catch that.

**Comment by astuder** [comment]
I agree on the challenge of analyzing val and ptr. 

But for JMP and CALL op-types it should be pretty save to substitute below the minvalsub threshold.

**Comment by MineRobber9000** [comment]
I agree with @astuder on this one. Jumps and calls (`JP` and `CALL` on the GBZ80 respectively) should always substitute for a label if one exists.

**Comment by radare** [comment]
Agree. Thats a good idea, we can improve that address replacement by enforcing the change for some specific instruction types. Will try that when i have some time. Can you submit a test for r2r? 

Also if you have time and want to give a try on fixing that please do.

**Comment by MineRobber9000** [comment]
Assuming by r2r, you mean radare2-regressions, sure! Where should I put the binary, and what category should I put the test in?

Where are opcodes handled in disassembly? I need closer to the opcode than just a type, although the type can be used as a general check to make sure it's an instruction we need.

The procedure would go like this:

 - Is it an opcode that has to do with the PC?
    - No? Act as normal (applying `asm.minvalsub`) and don't bother.
    - Yes? Keep reading below.
 - Is it `jp` or `call` with an absolute address?
    - Yes? Substitute the label if one exists.
    - No? Keep reading below.
 - Is it a `jr` instruction?
    - Yes? Calculate offset from next address and substitute the argument for a label if one exists.
    - No? Keep reading below.
 - Is it an indirect `jp` or `call`? Or is it a `ret` instruction (return)?
    - Yes? Pass it along without modification.
    - No? Something's gone wrong, someone's messed up, and this isn't an opcode that affects the PC.

**Comment by astuder** [comment]
Here's what I know:

Substitution of numbers in the disassembly with functions/flags is handled in the function filter in libr/parse/parse.c with the interesting part starting at line 216
https://github.com/radare/radare2/blob/master/libr/parse/parse.c#L216

This happens after disassembly and code analysis by architecture specific plugins (libr/asm/arch/gb and libr/anal/p/anal_gb.c for Gameboy). For each instruction, the analyzer populate a structure RAnalOp, which is defined in /libr/include/r_anal.h.

I think the fields of interest for our issue are probably type (type of opcode) and jump (target address). The type is surprisingly granular, but seeing how the enum _RAnalOpType is organized, I think after some bit masking types 1, 2, 3 and 4 are what we're looking for.
 
So the logic would be, if number in disassembly equal number in RAnalOp->jump and RAnalOp->type in range above, then always replace. 

The thing I haven't quite figured out yet (i.e. without running gdb) is, how to get the RAnalOp structure for the line parse.filter currently processes. I suspect that may require some gymnastics.

**Comment by MineRobber9000** [comment]
Really, all I need is some way of knowing what opcode I'm looking at. Different jumping opcodes (direct jumps, direct calls, indirect jumps, indirect calls, `ret` (jump to return address)) need to be handled differently.

**Comment by astuder** [comment]
As parse handles all architectures, you can't just look at the string. That's why I brought up RAnalOp, which contains the opcode type as an architecture independent ID.

Jumps without the actual target address in the disassembly is a whole different can of worms.

I suggested to verify the jump address in RAnalOp to reduce false positives for small numbers in case there's another operand in the instruction. E.g. 8051 has an instruction CJNE reg, imm, offset. Here I only want to substitute offsets < 0x100, but not the 8 bit immediate.

**Comment by astuder** [comment]
PS: I wonder if it would be easier to move the substitution logic into the analyzer. But I'm not familiar enough with radare2's architecture to make such a drastic change.

**Comment by radare** [comment]
you can just add a config var, implement that logic in a separate function and call it instead of the other in disasm.c that will not break anything and you can play with this feature and we can test it and replace it and remove the config option in the future if the behaviour is correct or better with the testsuite.

**Comment by astuder** [comment]
@MineRobber9000 I created a pull request with a first stab to resolve this issue. Would be great if you can give it a try.

**Comment by radare** [comment]
Sure. I have not much time, but if u do a pr it would be great.

**Comment by Maijin** [comment]
@astuder You fixed that no ?

**Comment by astuder** [comment]
Yes. Needs to be enabled with "e asm.jmpsub = true" (default false).

**Comment by astuder** [comment]
And only done / tested for pd

**Comment by Maijin** [comment]
ok then we can close here
