### ISSUE TITLE
can't change asm.cpu from rbin plugins

### ISSUE THREAD

**Issue by lowlyw** [radare/radare2#9144]
can't change asm.cpu from rbin plugins

setting

```c
bf->o->info->cpu
```

doesn't work

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/8088

**Comment by radare** [comment]
Because asm.cpu top level is an eval var from core. But rbininfo cpu should be honored as arch is

**Comment by radare** [comment]
well, the field exist but its not displayed by rabin2 -I, so its an easy fix
