### ISSUE TITLE
izzz* and izzzq not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#9151]
the '*jq' suffix is ignored for `izz`, works fine with `iz`

wip patch for someone else to take it:

```
diff --git a/libr/core/cmd_info.c b/libr/core/cmd_info.c
index f440424e4..741276600 100644
--- a/libr/core/cmd_info.c
+++ b/libr/core/cmd_info.c
@@ -305,6 +305,20 @@ static void playMsg(RCore *core, const char *n, int len) {
        }
 }

+int getMode(char ch) {
+       switch (ch) {
+       case '*':
+               return R_CORE_BIN_RADARE;
+       case 'j':
+               return R_CORE_BIN_JSON;
+       case 'q': //izzq
+               return R_CORE_BIN_SIMPLEST;
+       case 0:
+               return R_CORE_BIN_PRINT;
+       }
+       return -1;
+}
+
 static int cmd_info(void *data, const char *input) {
        RCore *core = (RCore *) data;
        bool newline = r_config_get_i (core->config, "scr.interactive");
@@ -640,26 +654,16 @@ static int cmd_info(void *data, const char *input) {
                case 'C': RBININFO ("signature", R_CORE_BIN_ACC_SIGNATURE, NULL, 0); break;
                case 'z':
                        if (input[1] == 'z') { //izz
-                               switch (input[2]) {
-                               case '*':
-                                       mode = R_CORE_BIN_RADARE;
-                                       break;
-                               case 'j':
-                                       mode = R_CORE_BIN_JSON;
-                                       break;
-                               case 'q': //izzq
-                                       if (input[3] == 'q') { //izzqq
-                                               mode = R_CORE_BIN_SIMPLEST;
+                               mode = getMode (input[2]);
+                               input++;
+                               if (mode == -1) {
+                                       mode = getMode (input[2]);
+                                       input++;
+                                       if (mode == -1) {
+                                               mode = getMode (input[2]);
                                                input++;
-                                       } else {
-                                               mode = R_CORE_BIN_SIMPLE;
                                        }
-                                       break;
-                               default:
-                                       mode = R_CORE_BIN_PRINT;
-                                       break;
                                }
-                               input++;
                                RBININFO ("strings", R_CORE_BIN_ACC_RAW_STRINGS, NULL, 0);
                        } else {
                                RBinObject *obj = r_bin_cur_object (core->bin);

```

**Comment by sivaramaaa** [comment]
@radare i have looked into this issue , detailing it below !!!
izz ---- honors '*jq' no issue with it , works perfectly fine !!!!
```
$ r2 /bin/ls

[0x00005600]> izz
vaddr=0x00000034 paddr=0x00000034 ordinal=000 sz=10 len=4 section=LOAD0 type=utf16le string=@8\t@
vaddr=0x00000238 paddr=0x00000238 ordinal=001 sz=28 len=27 section=.interp type=ascii string=/lib64/ld-linux-x86-64.so.2
....
vaddr=0x000000c5 paddr=0x0001f361 ordinal=1713 sz=12 len=11 section=.shstrtab type=ascii string=.fini_array
vaddr=0x000000f2 paddr=0x0001f38e ordinal=1718 sz=15 len=14 section=.shstrtab type=ascii string=.gnu_debuglink
[0x00005600]> izz~?
1719
[0x00005600]> izzq~?
1719
[0x00005600]> izz*~?
3438
[0x00005600]> izz*
....
Cs 6 @ 0x000000e7
f str..bss 5 @ 0x000000ed
Cs 5 @ 0x000000ed
f str..gnu_debuglink 15 @ 0x000000f2
Cs 15 @ 0x000000f2
[0x00005600]>
```
But yeah izzz* is not working , but do we really need izzz because it's nothing but iz + izz with full of duped entries (because iz is a subset of izz)

izz   Search for Strings in the whole binary , isin't that enough ??

**Comment by Maijin** [comment]
izzz is for large binaries, try izz on a memory dump ;)

**Comment by sivaramaaa** [comment]
@Maijin , yup u are right izzz purpose is for large binaries to just dump string to stdout
but in real u could take a look at cmd_info.c , there is no code for izzz xD
but u could see it is there  in /binr/rabin2.c , so i am implementing izzz for real now !!!!

**Comment by Maijin** [comment]
oki

**Comment by sivaramaaa** [comment]
I have suggestion here : what about mergring izz and izzz ??  

The key diiference bwetween the 2 is :

* izzz -    it  just dumps string without maintaining a list
* izz  -    it  maintains a list and pass it another func for processing it (honoring '*jq')

But i could make izz process the string without a need of list , by doing so izz could handle large binaries       
and we could kill izzz

I would like to do that in same PR , what do u say @Maijin  , @radare

**Comment by sivaramaaa** [comment]
But anyways i have figured it out , doing that would be a lil difficult also don't know if it's worth it !!!
So for now sticking on the plan to implement izzz
Still i would love to have suggestions for the above comment !!!!

**Comment by radare** [comment]
izzzz should not return a list because it can be really really huge. So its just printed

**Comment by sivaramaaa** [comment]
What i am suggesting is we could handle izz to without a list !!!
But in current senario since izzz is not maintaing a list , how do u propose to honor '*jq' ...

**Comment by sivaramaaa** [comment]
I thinks u would better understand it , if i do it in a PR :)

**Comment by sueliangliang** [comment]
The last 10 lines of the results obtained while executing "izz" are as follows
<img width="906" alt="image" src="https://github.com/user-attachments/assets/08134839-1a88-437a-b45b-9bbb791245f8">
However the last 10 lines of the results obtained while executing "izzz > izzz.txt && tail -f izzx.txt" are as follows:
<img width="519" alt="image" src="https://github.com/user-attachments/assets/3fb93b5b-2a79-4ad4-a486-29a18b944bfe">
Should I set the type of encoding? @radare @Maijin
