### ISSUE TITLE
Managing library functions

### ISSUE THREAD

**Issue by GiuseppeLaurenza** [radare/radare2#9158]
Hi to all,
with radare2 is possible to extract different data about functions found in the executable. In this group I think there are also library functions, is it true? Is it possible to not consider these functions?
Regards

**Comment by Maijin** [comment]
Could you provide with an expected output ?

**Comment by GiuseppeLaurenza** [comment]
@Maijin no because I do not know if the hypothesis is correct :D
If I run afl command, I obtain a table with all functions retrieved into the binary, I ask if these are all "developed code" or they also contains imported/standard functions

**Comment by Maijin** [comment]
if it's import, it begins with sym.imp.

**Comment by GiuseppeLaurenza** [comment]
ok so it is possible to parse name and discard the entry which start with sym.imp
thanks

**Comment by radare** [comment]
We can maybe add a column in the afl output to specify the section name and map name (file in debugger mode). This will be useful to grep for functions on a specific library if unhave lot of code analyzed on several loaded files.

Keep the issue opened. This is easy to fix

**Comment by GiuseppeLaurenza** [comment]
@radare ok I reopen,
I take advantage of this issue to ask which are the rule to name function? For example use sub.nameDLL means that this function is linked from external dll?

**Comment by radare** [comment]
Windows imoprts are prefixed with the library name because thats implicit in PE. But on unix a symbol can be anywhere. But i would probably prefer to use the libname as prefix

Like:

libc.system
...

**Comment by GiuseppeLaurenza** [comment]
ok, thanks for the explanation, I noticed that I can extract the function name from import table and discard them from the functions table

**Comment by Maijin** [comment]
you can get imports with `ii`, exports with `iE` etc.

**Comment by Maijin** [comment]
and if you are scripting don't forget, never use cmd, but use cmdj and commands like aflj, iij etc in  r2pipe

**Comment by GiuseppeLaurenza** [comment]
@Maijin Yes it is what I had done

**Comment by Maijin** [comment]
This has changed a lot, feel free to reopen a new issue using the enhancement templates and detail of what you expect. For now I will close, thanks!
