### ISSUE TITLE
NSO does not support symbols

### ISSUE THREAD

**Issue by GovanifY** [radare/radare2#9162]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Gentoo AMD64
| File format of the file you reverse (mandatory)      | NSO(Nintendo Switch)
| Architecture/bits of the file (mandatory)            | ARM(64)
| r2 -v full output, **not truncated** (mandatory)         | ```radare2 2.3.0-git 16958 @ linux-x86-64 git.2.2.0-167-g442753799 commit: 4427537998bac1914422121ae7424f780bd07c22 build: 2018-01-08__16:21:11```
| r2 -V full output in a pastebin document (mandatory) | https://ghostbin.com/paste/3j42p

### Expected behavior
Parse symbols
### Actual behavior
Symbols aren't parsed
### Steps to reproduce the behavior 
Check any NSO that contains symbols and wonder why there aren't any
An example NSO can be found in this issue https://github.com/radare/radare2/issues/9152

### Additional Logs, screenshots, compiled binaries, source-code,  configuration dump, ...
Seems unimplemented to me, relevant code:
https://github.com/radare/radare2/blob/master/libr/bin/p/bin_nso.c#L259
https://github.com/radare/radare2/blob/master/libr/bin/p/bin_nso.c#L110

**Comment by Maijin** [comment]
@GovanifY  Is that fixed?

**Comment by GovanifY** [comment]
@Maijin Welllll technically yes (https://github.com/radare/radare2/pull/10012) but there seems to have been regression such that NSOs show up a bunch of invalid instructions everywhere, even with the cache set to true. I'm going to look at when this regression happened and submit an issue/PR in the next days about it

**Comment by GovanifY** [comment]
https://github.com/radare/radare2/issues/12333 couldn't find the regression, submitted the issue nevertheless. I'll try to look later on if I can find why this happens
