### ISSUE TITLE
File capstone/arch/M68K/M68KDisassembler.c does not exist.

### ISSUE THREAD

**Issue by idersan** [radare/radare2#9173]
Meson encountered an error in file shlr/meson.build, line 283, column 0:
File capstone/arch/M68K/M68KDisassembler.c does not exist.

**Comment by Maijin** [comment]
ping @xarkes @pelijah

**Comment by xarkes** [comment]
What version? Try with latest master.

**Comment by Maijin** [comment]
Please follow the template next time @idersan

**Comment by pelijah** [comment]
Builds fine on Windows with the latest radare2:master and capstone:next.
