### ISSUE TITLE
Add svg support

### ISSUE THREAD

**Issue by lowlyw** [radare/radare2#9199]
svg is better because it will allow zoom more than png, also png doesn't support color tags in dot, whereas svg does, https://github.com/radare/radare2/issues/9186 https://www.graphviz.org/doc/info/shapes.html#html

**Comment by radare** [comment]
Why not add instead of change? Graphviz is used and compatible with many tools

**Comment by lowlyw** [comment]
@radare we can only have one default!

**Comment by Maijin** [comment]
See this @cyanpencil ^
