### ISSUE TITLE
Print current symbol: "is." is not working

### ISSUE THREAD

**Issue by YugoCode** [radare/radare2#9204]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.13
| File format of the file you reverse (mandatory)      | Mach-O
| Architecture/bits of the file (mandatory)            | arm64
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0-git 17048 @ darwin-x86-64 git.2.2.0-237-g876c60fc7 commit: 876c60fc7b1f1c4ef7912c763888ff3e1f968342 build: 2018-01-15__23:21:35

### Expected behavior

`is.` should print the symbol of the actual seek or the given address: `is. @ 0x1....`.

### Actual behavior

`is` prints all available symbols. `is.` does not print a symbol, only an empty string.

> Current symbol
> _

**Comment by sivaramaaa** [comment]
Hey it's working properly for me for example 
```
$ r2 /bin/ls

[0x00005600]> is
[Symbols]
115 0x0001f280 0x0021f280 GLOBAL OBJECT    8 __progname
...[TRUNCATED]
067 0x00003a50 0x00003a50   GLOBAL  FUNC   16 imp.memcpy
106 0x00000000 0x00000000   WEAK    NOTYPE   16 imp._ITM_registerTMCloneTable
110 0x00000000 0x00000000   WEAK    FUNC   16 imp.__cxa_finalize
```
Here output of **is.** 
```
[0x00005600]> is. @ 0x00003a50
Current symbol
067 0x00003a50 0x00003a50 GLOBAL   FUNC   16 imp.memcpy

[0x00005600]>
```
You just have to seek to correct offset , which has a valid symbol !!!

Closing this issue for now !!!

@YugoCode , pls provide proper binary on which u tested and the command you have tried , post it on this same thread , if the issue exist i would re-open it !!

**Comment by YugoCode** [comment]
I only tested Mach-O iOS binaries. Here is an example: [NewsBlur.zip](https://github.com/radare/radare2/files/1635538/NewsBlur.zip)

```
[0x001448bc]> is
[Symbols]
...[TRUNCATED]
013 0x0027fd04 0x0027fd04  LOCAL   FUNC    0 imp.CC_SHA1
014 0x0027ff60 0x0027ff60  LOCAL   FUNC    0 imp.CFArrayCreate
...[TRUNCATED]
```

Here is the output of `is.
`:
```
[0x0027ff60]> is.
Current symbol

```

Does it work for you on this binary?

**Comment by sivaramaaa** [comment]
Yes , the issue seems to exist with this binary !!!

**Comment by YugoCode** [comment]
I have this issue with all Mach-O binaries.

**Comment by radare** [comment]
i can reproduce the issue:

```
[0x100001200]> is.
Current symbol

[0x100001200]> pd 1
            ;-- main:
            ;-- entry0:
            ;-- func.100001200:
            0x100001200      55             push rbp
[0x100001200]>
```
^- this is macs /bin/ls

in addition. @sivaramaaa please remove the unnecessary verbose text of "Current symbol"

**Comment by sivaramaaa** [comment]
Sure , working on it !!!!
