### ISSUE TITLE
Radare debugging not working for remote arm binaries

### ISSUE THREAD

**Issue by twisted-fun** [radare/radare2#9209]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64 xenial (16.04)
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0-git 17055 @ linux-x86-64 git.2.2.0-247-g7acd7ff commit: 7acd7ff7fcc997a9eaaa21275c01346fe67a3500 build: 2018-01-16__17:27:21
| r2 -V full output in a pastebin document (mandatory) | https://pastebin.com/HvYsM8KB

### Expected behavior
After setting up remote-debugging using qemu-arm, `r2 -a arm -d gdb://host:port` should allow us to debug the binary properly

### Actual behavior
I am not able to set a break point or step through the binary

### Steps to reproduce the behavior 
```
ubuntu@ctf-machine:~/ctfs$ qemu-arm -g 1337 ch45
Give me data to dump:
AAAA
0xfffef508:  41 41 41 41
Dump again (y/n):
n
ubuntu@ctf-machine:~/ctfs$
```

```
ubuntu@ctf-machine:~$ r2 -a arm -d gdb://127.0.0.1:1337
= attach 1 0
 -- Reduce the delta where flag resolving by address is used with cfg.delta
[0x00000000]> ds
Stepping failed!
Step failed
[0x00000000]> dc
Process 2125 exited with status 0

==> Process finished

[0x00000000]>
```
[binary.zip](https://github.com/radare/radare2/files/1637931/binary.zip)

**Comment by radare** [comment]
You are missing the -b 32 or -b 16

**Comment by twisted-fun** [comment]
Same issue even after including -b 32
```
ubuntu@ctf-machine:~$ r2 -a arm -b 32 -d gdb://127.0.0.1:1337
= attach 1 0
 -- There is no F5 key in radare2 yet
[0x00000000]> ds
Stepping failed!
Step failed
[0x00000000]>
```

**Comment by d4em0n** [comment]
Fixed in #10818

**Comment by enovella** [comment]
Are you sure its working?

```sh
$ qemu-arm-static -g 1337 ./armbin
```

```sh
$ r2  -A -a arm -b 32 -d gdb://127.0.0.1:1337
[0x000101a0]> ds
[0x000101a0]> ds
[0x000101a0]> ds
[0x000101a0]> ds
[0x000101a0]> ds
[0x000101a0]> ds
[0x000101a0]> dc
Process 11543 exited with status 0

==> Process finished
```

**Comment by Maijin** [comment]
@enovella Please do not post in old thread, it's just adding confusion.
