### ISSUE TITLE
Cannot define function and view it in graph mode after aaa

### ISSUE THREAD

**Issue by johnchen902** [radare/radare2#9211]
### Work environment
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | Arch Linux
| File format of the file you reverse      | ELF
| Architecture/bits of the file            | x86/64
| r2 -v full output         | radare2 2.3.0-git 17057 @ linux-x86-64 git.2.2.0-250-g0104b092f commit: 0104b092fc368189923f9531dca25c2dfdf4b1ed build: 2018-01-17__22:31:25
| r2 -V full output in a pastebin document | https://gist.github.com/johnchen902/2918dd2a372fba187606a47fae5fbc21

### Steps to reproduce
1. Binary: [wannaheap.zip](https://github.com/radare/radare2/files/1639351/wannaheap.zip)
1. `radare2 wannaheap`
1. `aaa`
1. `s main` (should be at `0xc20`)
1. `V`
1. `dfV` (no enter after this)

### Expected behavior
Show the control flow of main.

### Actual behavior
Show `Not in a function. Type 'df' to define it here`

### Other info
1. It works (shows the control flow of main) if I run `aa` instead of `aaa`.
1. It doesn't work (shows `Not in...`) if I omit `df`.

**Comment by sivaramaaa** [comment]
Hey hi , this problem could be solved by setting a config var like this : 
```
e anal.pltujmp = false
aaa
VV
```
But yeah i am working out a solution to handle this without the need of setting this config var 

So i am not closing this issue :)

**Comment by sivaramaaa** [comment]
This issue has been fixed properly  after this [PR](https://github.com/radare/radare2/pull/9224)
