### ISSUE TITLE
rahash2: Incorrect hash.

### ISSUE THREAD

**Issue by SjRNMzU** [radare/radare2#9212]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 17.04
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64 
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0-git 17111 @ linux-x86-64 git.2.2.0-251-g8320dbd2a commit: 8320dbd2afd613359c14c12641bd8d74143a779c build: 2018-01-17__15:22:36
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/SjRNMzU/8cbe34b84257f6bbc2e3c8b0845b17eb|

### Expected behavior
The expected sha256 hash of 488b078b4f088d51ff488b3e4889174883060885c97472f20f100571120000f20f100d5112000049b800000000000000806666666666662e0f1f8400000000000fb738488b1648893a4c8b0e498d790848893ef20f105008f20f59d0660f28daf20f5cd9f2480f2cfb4c31c7f2480f2cd2660f2ed1480f43d749895108488306084883c010ffc975b7c3 (hex encoded)

is

b4f87c57b30c70b977ff49e57b349ee2653b386ef30ec701c58bd453441471fb (hex encoded)

Using `rahash2 -a sha256 -x {...}` this is correct. However I am using rahash2 to hash a symbol with a start and end address in a binary. 

The command I'm using is `rahash2 -a sha256 -f 4202096 -t $((4202096 + 138)) {binary}`. 
Whereby the bytes for symbol at 4202096 (dec) is 488b078b4f088d51ff488b3e4889174883060885c97472f20f100571120000f20f100d5112000049b800000000000000806666666666662e0f1f8400000000000fb738488b1648893a4c8b0e498d790848893ef20f105008f20f59d0660f28daf20f5cd9f2480f2cfb4c31c7f2480f2cd2660f2ed1480f43d749895108488306084883c010ffc975b7c3 (hex encoded) as printed out by `r2 -p` as well as objdump. 

### Actual behavior

rahash2 prints the wrong hash 

```
rahash2 -a sha256 -f 4202096 -t $((4202096 + 138)) {bin}
{bin}: 0x00401e70-0x00401efa sha256: 3e3596f2221eb8ae8a7cd6891fed999fc06021891ac4b9794a78df2c8144d201
```

This issue was found because I was getting a hash collision where I shouldn't have been. I was originally using r2 1.7 in which running r2hash produce as wrong hash of "6525....." - updating to the latest git build r2hash produces a different wrong hash!

Binary is here: [xcmsdb.zip](https://github.com/radare/radare2/files/1639586/xcmsdb.zip) and the symbol I'm hashing is PutTableType0Card32.

**Comment by radare** [comment]
```
$ rax2 -s 488b078b4f088d51ff488b3e4889174883060885c97472f20f100571120000f20f100d5112000049b800000000000000806666666666662e0f1f8400000000000fb738488b1648893a4c8b0e498d790848893ef20f105008f20f59d0660f28daf20f5cd9f2480f2cfb4c31c7f2480f2cd2660f2ed1480f43d749895108488306084883c010ffc975b7c3| shasum -a 256
b4f87c57b30c70b977ff49e57b349ee2653b386ef30ec701c58bd453441471fb  -
$
```

rahash2 works fine with -x:

```
$ rahash2 -a sha256 -x 488b078b4f088d51ff488b3e4889174883060885c97472f20f100571120000f20f100d5112000049b800000000000000806666666666662e0f1f8400000000000fb738488b1648893a4c8b0e498d790848893ef20f105008f20f59d0660f28daf20f5cd9f2480f2cfb4c31c7f2480f2cd2660f2ed1480f43d749895108488306084883c010ffc975b7c3
0x00000000-0x00000089 sha256: b4f87c57b30c70b977ff49e57b349ee2653b386ef30ec701c58bd453441471fb
```

ive patched ls and confirmed the behaviour is correct. because -f -t are INCLUSIVE. so you have to substract 1 to the 138 delta:

```
$ cp /bin/ls .
$ r2 -qwc'wx 488b078b4f088d51ff488b3e4889174883060885c97472f20f100571120000f20f100d5112000049b800000000000000806666666666662e0f1f8400000000000fb738488b1648893a4c8b0e498d790848893ef20f105008f20f59d0660f28daf20f5cd9f2480f2cfb4c31c7f2480f2cd2660f2ed1480f43d749895108488306084883c010ffc975b7c3' -c?p ls
0x1200
$ rahash2 -a sha256 -f 0x1200 -t '0x1200+137' ls
ls: 0x00001200-0x00001289 sha256: b4f87c57b30c70b977ff49e57b349ee2653b386ef30ec701c58bd453441471fb
$
```

**Comment by radare** [comment]
there have been lot of back and forth for that open-closed intervals in r_io, r_hash and other modules, actually we try to use closed intervals to avoid the problem checking the last byte in the -1 address, which cant be expressed otherwise unless we go for from + len, but this can result on addressing overflows which are not possible with from/to ranges.

**Comment by radare** [comment]
feel free to update the help message or rahash2 manpage accordingly
