### ISSUE TITLE
ROP search double-free

### ISSUE THREAD

**Issue by jackaaron** [radare/radare2#9213]
Hi, I believe there's a double-free bug in `libr/core/cmd_search_rop.c` in `rop_classify_arithmetic_const` that persists at least back to version 1.3.0. 

This condition can be triggered when the /R option is supplied to search for matching ROP gadgets. If ROP search identifies an arithmetic constant and a DB query for esil stat fails, a double-free occurs.

See:
`cmd_search_rop.c:543` - `op_result` allocated
`cmd_search_rop.c:583` - `op_result` freed if `sdb_querys` fails
`cmd_search_rop.c:651` - `op_result` freed again during cleanup

`op_result_r` allocated on `cmd_search_rop.c:544` follows an identical pattern.

**Comment by sivaramaaa** [comment]
Do u wanna send a PR for this ???

**Comment by radare** [comment]
Tired of waiting, ive fixed it. Next time just click the pencil button

**Comment by jackaaron** [comment]
Thank you. Will be faster next time
