### ISSUE TITLE
rasm2 big endian arm thumb inctruction incorrect 

### ISSUE THREAD

**Issue by ampotos** [radare/radare2#9219]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
|OS | Ubuntu amd64
|tool used | rasm2
|Architecture/bits   |      ARM big endian thumb instruction
|r2-v | radare2 2.3.0-git 17114 @ linux-x86-64 git.2.2.0-252-g89c309a90       commit: 89c309a90056fbc5bd5a7a19f947c231a9951fd6 build: 2018-01-18__17:16:36
| r2 -V |https://gist.github.com/ampotos/0f70bc38b2e3988c66bdded0566e5582

The bit size is not used to create the big endian opcode (it looks like it's the endianess for 32bits word).

### Expected behavior
rasm2 -a arm -b 16 -e 'blx 0x33b8'
=> f003f9da
### Actual behavior
rasm2 -a arm -b 16 -e 'blx 0x33b8'
=> f9daf003
### Steps to reproduce the behavior 

rasm2 -a arm -b 16 -e 'blx 0x33b8'

For reference: 
rasm2 -a arm -b 16  'blx 0x33b8'
=> 03f0daf9

**Comment by radare** [comment]
Thats easy to fix. Wanna try sending a pr?

**Comment by ampotos** [comment]
I will try to find the time for that in the coming days.

**Comment by Maijin** [comment]
arm.as (*arm* handmade assembler) is one of the 2 arm assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix arm.as in https://github.com/radare/radare2-regressions/blob/master/t.asm/arm/capstone/arm_asm** You can do so with github web editor without even cloning the repo.

You can contribute to arm.as by completing the following files: 
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass.c
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass64.c

You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a arm.ks…
or in radare2 session
	e asm.assembler = arm.ks
```

**Comment by ampotos** [comment]
I just did the PR on radare2-regression (https://github.com/radare/radare2-regressions/pull/1157).
I'll send a pr with fix today or tomorrow.

**Comment by radare** [comment]
👍
