### ISSUE TITLE
Improve the list of local variables and arguments

### ISSUE THREAD

**Issue by radare** [radare/radare2#9239]
<img width="671" alt="screen shot 2018-01-25 at 06 08 07" src="https://user-images.githubusercontent.com/917142/35371754-47d25bb8-0196-11e8-8394-6c735d2827ff.png">

**Comment by radare** [comment]
Also we can use different colors depending if it's 0 or not

**Comment by zuvizudar** [comment]
I want to try this.
what color should I change color of zero ?

**Comment by Maijin** [comment]
I would reuse b0x00 color See `ec` command

**Comment by zuvizudar** [comment]
I have a question.
Should I  change 
{
 bp : 0 (vars 0,  args 0)
 sp : 1 (vars 1,  args 0)
 rg  : 0 (vars 0,  args 0)
}
to
{
 vars : 0 1 0
 args : 0 0 0 
}
?

**Comment by Maijin** [comment]
that's what the issue is about yes, please use an eval variable (e XXX.XXX) to provide user with choice on how he wants the data displayed so you can keep current view.
