### ISSUE TITLE
Wrong type for m68k LINK and LPSTOP instructions

### ISSUE THREAD

**Issue by raybellis** [radare/radare2#9241]
While browsing this code:

https://github.com/radare/radare2/blob/a010d09204bacf5dbaac99bb0f1530ff613fa809/libr/anal/p/anal_m68k_cs.c#L457

I noticed that `LINK` and `LPSTOP` will both end up assigned to `R_ANAL_OP_TYPE_SHL`.

This would appear to be an error.  The `LINK` instruction is part of the standard function prologue (at least in the code I'm trying to disassemble), used to reserve space on the stack.

**Comment by Maijin** [comment]
What about doing a Pull-Request ?

**Comment by raybellis** [comment]
I would, but I don't know what the right code should look like.  All I can tell is that it currently looks wrong.

**Comment by Maijin** [comment]
It's in the same file just change what the value of R_ANAL_OP_TYPE_SHL

**Comment by radare** [comment]
according to the documentation that looks like a PUSH to me:

"Pushes the contents of the specified address 
register onto the stack. Then loads the updated stack pointer 
into the address register. Finally, adds the displacement 
value to the stack pointer.”

also:

"Note: LINK and UNLK can be used to maintain a linked list of local 
data and parameter areas on the stack for nested subroutine 
calls.”

this reminds me to the enter/leave sub/add SP instructions used in other architectures to setup the local stackframe. as long as this increases and decreases the stack frame, i would name them PUSH and POP as type. and then fill the stackop field on RAnalOp, so the disasm will look good when asm.stackptr is set

Do you want to send the PR now? its just 3 lines of patch

**Comment by radare** [comment]
Fixed in 2a5bb28a4cbe29319382ac32e18eb60119752c6d

Note that the argument is taken as unsigned short by capstone,.. but i think this must be signed, so it may be 44.. 

<img width="606" alt="screen shot 2018-01-26 at 23 44 10" src="https://user-images.githubusercontent.com/917142/35463906-6334b46a-02f3-11e8-8e80-8f289b1d45ee.png">
