### ISSUE TITLE
running aaa on project segfaults

### ISSUE THREAD

**Issue by fcasal** [radare/radare2#9248]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | 16.04.1 Ubuntu x86_64
| File format of the file you reverse      | ELF
| Architecture/bits of the file            | x86/64
| r2 -v          | radare2 2.3.0-git 17162 @ linux-x86-64 git.2.2.0-298-g893b896 commit: 893b896ca0bd54a402f5f916870b1c731d1489d1 build: 2018-01-26__14:16:22
| r2 -V | https://gist.github.com/fcasal/19efbef82d20b2ed46a80db52238d577

### TLDR
When loading a project and running 'aaa' we get a segfault.

### Expected behavior
When loading a project, the corresponding binary file should open and that is not happening.

### Actual behavior
`core->file` is NULL leading to Segmentation fault.

### Steps to reproduce the behavior 

```
mandlebro@machine:$ r2 /bin/ls
[0x004049a0]> Ps test
test
[0x004049a0]> q
Do you want to save the 'test' project? (Y/n)

mandlebro@machine:$ r2 -p test
[0x004049a0]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
TODO: esil-vm not initialized
[Segmentation fault (core dumped)ions for references (aar)
```

This is due to the call `r_io_use_fd (core->io, core->file->fd);` in `r_core_anal_search_xrefs`, the `core->file` pointer is NULL.

Backtrace:
```
   f 0     7fd785a007a0 r_core_anal_search_xrefs+551
   f 1     7fd78596c787 r_core_anal_refs+488
   f 2     7fd78596dc81 cmd_anal_all+1283
   f 3     7fd78596ed79 cmd_anal+1441
   f 4     7fd7859f56dd r_cmd_call+457
   f 5     7fd7859aede5 r_core_cmd_subst_i+11499
   f 6     7fd7859abf02 r_core_cmd_subst+859
   f 7     7fd7859b1198 r_core_cmd+966
   f 8     7fd785924e85 r_core_prompt_exec+43
   f 9     55640687915c main+13222
   f 10     7fd781563830 __libc_start_main+240
```

**Comment by radare** [comment]
Just send the fix clicking in the pencil button adding an if to skip this null deref

**Comment by fcasal** [comment]
I think the cause of the issue is related to #9149. Simply bailing out if the pointer is NULL will not perform the correct analysis anyway and so maybe the solution should be to add an error message of some kind. I'm not that familiar with radare2 codebase and so I'm not confident in determining the root cause of the issue and what the message should be.

**Comment by radare** [comment]
Im busy with humans now, will check it out after dinner. Thanks for reporting

**Comment by radare** [comment]
its ok to remove that line, basically core->file and core->files are being deprecated because the new r_io api can handle that stuff properly
