### ISSUE TITLE
resizing the terminal segfaults in 'v' mode after VV

### ISSUE THREAD

**Issue by fcasal** [radare/radare2#9254]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | 16.04.1 Ubuntu x86_64
| File format of the file you reverse      | ELF
| Architecture/bits of the file            | x86/64
| r2 -v          | radare2 2.3.0-git 17171 @ linux-x86-64 git.2.2.0-307-g1ef740d commit: 1ef740dbf3d9e1c7b710eaa2b398a61174c314de build: 2018-01-27__09:27:49
| r2 -V | https://gist.github.com/fcasal/75b79f13ad691d3145cdd7b8b1c4b73a

### TLDR
When resizing the terminal we get a segfault in 'v' mode after VV.

### Steps to reproduce the behaviour
```
mandlebro@machine:$ r2 /bin/ls
[0x004049a0]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x004049a0]> VV
             > v
             > [resize terminal]
Segmentation fault (core dumped)
```

The offending line is 2208 of vmenus.c where in `r_list_foreach (core->anal->fcns, iter, fcn)`, `core->anal` and `core->anal->fcns` seem bad.
 

Backtrace:
```
   f 0     7fa4d519d654 var_functions_show+119
   f 1     7fa4d519da1e r_core_visual_anal_refresh_column+86
   f 2     7fa4d519dc1d r_core_visual_anal_refresh+153
   f 3     7fa4d49dc56b resize+42
   f 4     7fa4d0d044b0 __restore_rt
   f 5     7fa4d10a94fe __read_nocancel+5
   f 6     7fa4d49e820d r_cons_readchar+59
   f 7     7fa4d519dea5 r_core_visual_anal+243
   f 8     7fa4d516a0c0 r_core_visual_graph+6283
   f 9     7fa4d5154ff4 r_core_visual_cmd+7068
   f 10     7fa4d5158967 r_core_visual+292
```

**Comment by radare** [comment]
Can you show th backtrace with symbols and paste the valgrind log? That may help to identify the issue. Thanks
