### ISSUE TITLE
Readline vi mode

### ISSUE THREAD

**Issue by radare** [radare/radare2#9269]
![dutvln2wsaawlk3](https://user-images.githubusercontent.com/203261/35603110-b369eb7c-0676-11e8-9fa1-31df47426bf6.jpg)

(via https://twitter.com/qrs/status/957954185055625216 )

**Comment by XVilka** [comment]
@deepakchethan this one is important, but also kind of simple. The hard part is also to document these movements in the book.

**Comment by XVilka** [comment]
@deepakchethan I started the dietline book chapter here: https://github.com/radare/radare2book/blob/master/basic_commands/dietline.md

Feel free to extend.
