### ISSUE TITLE
[Q] Rename functions permanently in debug mode

### ISSUE THREAD

**Issue by dweidenfeld** [radare/radare2#9270]
Hi, 

I am using the latest GIT version, and if I understood what I've read it is not intendet to write a binary file in debug mode, but maybe you can help me getting my workflow ready :)

My idea is to open a binary in debug mode and execute it. 
During debugging I understand the behavior of a function so I want to rename it.
After I've renamed all functions I want to save the state, so that I can continue debugging later with all renamed function etc.

Is it possible, or not?

**Comment by radare** [comment]
create a script that does that, projects in debug mode dont work well, so just create a script and load it. you can make flags to be relative to a map, so aslr is not an issue for example.

Simple projects may be able to handle that situation, but didnt tried

**Comment by dweidenfeld** [comment]
Okay, I still think this could be useful to be stored as project, but the workaround is fine for me right now :)
Thanks!
