### ISSUE TITLE
Error in debug_attatch

### ISSUE THREAD

**Issue by hayekr** [radare/radare2#9288]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS High Sierra x86-64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 0 @ darwin-x86-64 git.2.3.0 
|                                                                                            commit: HEAD build: 2018-02-01__01:00:24
| r2 -V full output in a pastebin document (mandatory) | [https://pastebin.com/X4xSx5ci](url)

### Issue

When trying to debug executable after analyzing(aaa), and disassembling main(pdf), I use the ood command to open the debugger, but I get this error. GDB is installed and signed, radare is also signed.

### Error

`posix_spawnp: unknown error 2`
`posix_spawnp: No such file or directory`
`Child killed`
`unknown error in debug_attach`
`r_core_file_reopen: Cannot reopen file: dbg:///Users/roberthayek/Desktop/Reverse Engineering/Reverse-Engineering-Tutorials/Level 0/crackme  with perms 0x0007, attempting to open read-only.`
`failed to swap exception ports`
` (ipc/send) invalid destination port`
`error setting up exception thread`
`failed to swap exception ports`
 `(ipc/send) invalid destination port`
`error setting up exception thread`

**Comment by radare** [comment]
as a workaround, dont use ood if you are doing aaaa, this is somewhat related to the projects problems.

**Comment by hayekr** [comment]
It does not work even without aaa

**Comment by hayekr** [comment]
For some reason it only works if the file that I am debugging is located in my user folder, even with aaa/aaaa commands used. I believe that there is something with the permissions of the folder I am trying to debug. This issue I do not believe is caused by radare2.

**Comment by radare** [comment]
That’s called SIP. Google for it

**Comment by cowens** [comment]
For people who got here like me by searching Google, the answer is to copy the executable to a directory you control, run ```codesign --remove-signature FILENAME```, and then run r2 with sudo. This [article](https://poweruser.blog/using-dtrace-with-sip-enabled-3826a352e64b) was very helpful and points to a way for radare2 to run on macOS without users having to jump through hoops (but it would cause the developer's to have to jump through worse hoops).

**Comment by trufae** [comment]
Would you update the doc/ file with more detailed instructions? Thanks for sharing your findings here
