### ISSUE TITLE
Symbol download doesn't work with newer Windows targets

### ISSUE THREAD

**Issue by riverar** [radare/radare2#9309]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 17083 x64
| File format of the file you reverse (mandatory)      | notepad.exe
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 17169 @ windows-x86-32 git.2.2.0-361-g8b1e0bb16 commit: 8b1e0bb16e738d9e805297bca21adcac49a6b0a9 build: Sat 02/03/2018__21:59:11.96
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/riverar/51793676c82c84eced464ab44fd73e6f

### Expected behavior
Symbols for notepad to download from symsrv successfully

### Actual behavior
```
curl exited with error 1
PDB "notepad.pdb" download failed
```

### Steps to reproduce the behavior 
- `r2 -d [pid_of_syswow64_notepad]`
- `> idpd`
- Note error appears, as mentioned above

**Comment by riverar** [comment]
Submitted a fix where we yank support for compressed symbols, as Microsoft is no longer providing them.

**Comment by radare** [comment]
Imho its good to merge. Or at least add an option handled with an envvar in rabin2 to use the old method instead of removing the code

**Comment by XVilka** [comment]
@radare it is true for Microsoft servers but not for the others.

**Comment by riverar** [comment]
Abandoning. Not needed. Turns out, my curl was super old and not returning the appropriate error codes on failure (e.g. 404). It is now, which triggers the fallback behavior correctly.
