### ISSUE TITLE
Wrong Disassembly indentation if exactly one of asm.fcnlines or asm.lines is enabled

### ISSUE THREAD

**Issue by thestr4ng3r** [radare/radare2#9316]
### Expected behavior
All disassembly lines should be perfectly aligned.

### Actual behavior
asm.fcnlines=true + asm.lines=false:
![bildschirmfoto vom 2018-02-04 20-37-55](https://user-images.githubusercontent.com/1460997/35781536-b86c781a-09eb-11e8-99ae-e017ec9f7405.png)

asm.fcnlines=false + asm.lines=true:
![bildschirmfoto vom 2018-02-04 20-37-31](https://user-images.githubusercontent.com/1460997/35781535-b55313a0-09eb-11e8-83f6-f6c84005f116.png)

### Steps to reproduce the behavior 
- Analyze
- Enable exactly one of the options
- Disassemble with pd or in view disassembly in visual mode

**Comment by radare** [comment]
Which version of r2 are you using? And which commands did you typed?

**Comment by xarkes** [comment]
I can reproduce with r2 /bin/ls -qc 'aaa; e asm.lines=false; pd 30'
```
radare2 2.3.0 17346 @ linux-x86-64 git.2.2.0-358-g4f8c9908b
commit: 4f8c9908b0212d479f5e22f851b9b893e29dec37 build: 2018-02-02__18:34:52
```

**Comment by radare** [comment]
Dont pass args  after the filename

**Comment by thestr4ng3r** [comment]
Using current master:
```
$ r2 -
 -- This computer has gone to sleep.
[0x00000000]> af+ 0 test
[0x00000000]> e asm.fcnlines=0
[0x00000000]> pd 2
(fcn) test 0
  test ();
          0x00000000      0000           add byte [rax], al
            0x00000002      0000           add byte [rax], al
[0x00000000]> e asm.fcnlines=1
[0x00000000]> e asm.lines=0
[0x00000000]> pd 2
/ (fcn) test 0
|   test ();
| 0x00000000      0000           add byte [rax], al
 0x00000002      0000           add byte [rax], al
```
I'll probably add tests and fix it soon.

**Comment by radare** [comment]
thanks!
