### ISSUE TITLE
rasm2: arm BLX instruction not encoded correctly

### ISSUE THREAD

**Issue by StefanBruens** [radare/radare2#9319]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | openSUSE-TW x86 64 
| File format of the file you reverse (mandatory)      | raw
| Architecture/bits of the file (mandatory)            | arm/32
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 0 @ linux-x86-64 git.2.3.0 commit: HEAD build: 2018-01-30__19:27:13

### ARM 32

| Status | Command | Output | |
|----------|--------------------------------------------------|--------------|--------|
| correct | rasm2 -o 0 -a arm -b 32 -d 0x000000fa | blx 8 | |
| correct | rasm2 -o 0 -a arm -b 32 -d 0x000000fb | blx 0xa | |
|||||
| correct | rasm2 -o 0 -a arm -b 32 'blx 0x8' | 000000fa | |
| **incorrect** | rasm2 -o 0 -a arm -b 32 'blx 0xa' | 000000fa   | H bit not set |

### ARM Thumb2

| Status | Command | Output | |
|----------|--------------------------------------------------|--------------|--------|
| correct | rasm2 -o 0 -a arm -b 16 -d 0x00f000e8 | blx 4  | |
| correct | rasm2 -o 8 -a arm -b 16 -d 0xfff7fcef | blx 4  | |
| correct | rasm2 -o 0xa -a arm -b 16 -d 0xfff7fcef | blx 4  | |
|||||
| correct | rasm2 -o 0 -a arm -b 16 'blx 0x4' | 00f0 00e8  | |
| **incorrect** | rasm2 -o 8 -a arm -b 16 'blx 0x4' | fff0 fcff  | should be fff7 fcef [1] |
| **incorrect** | rasm2 -o 0xa -a arm -b 16 'blx 0x4' | fff0 faff  | should be fff7 fcef [1] |

[1] checked with objdump:
` echo '00000000000000000000fff7fcef' | xxd -r -ps > /tmp/blx.bin && objdump -m armv5t -M force-thumb --target binary -D /tmp/blx.bin `
and verified manually using the ARM Architecture reference manual, section A7.1.17

**Comment by radare** [comment]
You can try with other assemblers. Like the keystone one. Install the arm.ks plugin with r2pm 

Thanks for reporting

**Comment by Maijin** [comment]
Greetings,

arm.as (*arm* handmade assembler) is one of the 2 arm assemblers available in radare2 and is updated frequently.  **Please add a test case so we can fix arm.as in https://github.com/radare/radare2-regressions/blob/master/t.asm/arm/capstone/arm_asm** You can do so with github web editor without even cloning the repo.

You can contribute to arm.as by completing the following files: 
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass.c
* https://github.com/radare/radare2/blob/master/libr/asm/arch/arm/armass64.c

You can also use keystone(http://keystone-engine.org) within radare2/rasm2 by installing the radare2 plugin via r2pm : 

```
	r2pm -i keystone-lib
	r2pm -i keystone
then
	rasm2 -a arm.ks…
or in radare2 session
	e asm.assembler = arm.ks
```

**Comment by StefanBruens** [comment]
@Maijin There is no t.asm in https://github.com/radare/radare2-regressions, although it is also mentioned in https://github.com/radare/radare2-regressions/blob/master/README.md

**Comment by Maijin** [comment]
See https://github.com/radare/radare2-regressions/blob/master/new/db/asm/arm_16
https://github.com/radare/radare2-regressions/blob/master/new/db/asm/arm_32
https://github.com/radare/radare2-regressions/blob/master/new/db/asm/arm_64

I will update my templates thanks 👍

**Comment by StefanBruens** [comment]
At least the Thumb code is still heavily broken:

| | | |
|-----------------------------------------------|----------------|---------|
| rasm2 -a arm -b 16 -o 0x0b000000  'blx 0x0b000008' | 00f002e8 | good |
| rasm2 -a arm -b 16 -o 0x0b000000  'blx 0x0b00000c' | 00f004e8 | good |
| rasm2 -a arm -b 16 -o 0xfb000000  'blx 0xfb000008'| fff3fec7 | obviously bad |
| rasm2 -a arm -b 16 -o 0xfb000000  'blx 0xfb00000c' | fff3fec7 | dito |

The same is true for BL, which has the exact same encoding, save the opcode, which is 'f8' instead of 'e8' in the last byte.

**Comment by StefanBruens** [comment]
Apparently use of strtod in getnum and casting the double to signed int is not a good idea ... the returned int value is way off.
