### ISSUE TITLE
arch parameter is case-sensitive

### ISSUE THREAD

**Issue by MaKiPL** [radare/radare2#9326]
software architecture parameter is case sensitive

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows
| File format of the file you reverse (mandatory)      | RAW binary
| Architecture/bits of the file (mandatory)            | MIPS
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.3.0 1 @ windows-x86-32 git. commit: cc7b6e2c1f029e312eb00983a7987c641443373b build: Mon 01/29/2018__10:38:30.22
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/MaKiPL/1e74cf3074324c8f78ddaf91f77cdf20

### Expected behavior

Running software with -a MIPS should set architecture to MIPS

### Actual behavior

Software throws an error that there's no MIPS architecture and forces you to use lower-case 'mips' instead

### Steps to reproduce the behavior 
-Run software: .\radare2.exe -a MIPS D:\FFVIII\FF8_2000\UNPACKED\battle\a0stg000.x

### Additional Logs, screenshots, source-code,  configuration dump, ...

N/A

**Comment by radare** [comment]
This is expected behaviour. Plugins are case sensitive, as files and any other thing in unix is. R2 is unix friendly, so case insensitive things have no room in tihs land,
