### ISSUE TITLE
Standarize indenting in the radare2 source

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#933]
We should [uncrustify]( http://uncrustify.sourceforge.net/ ) the whole radare2 source.
Or use [clang-format]( http://clang.llvm.org/docs/ClangFormat.html ) see 'doc/clang-format' as a possible rules https://github.com/radare/radare2/blob/master/doc/clang-format

**Comment by XVilka** [comment]
Lets try clang-format one more time, using 3.8 snapshots

**Comment by ret2libc** [comment]
What about indentation on multi lines statements? I think @radare wants to
use one tab when aligning multi lines, but clangformat uses spaces
Il 03/set/2015 18:49, "Anton Kochkov" <notifications@github.com> ha scritto:

**Comment by XVilka** [comment]
@ret2libc we can fill a feature request for clang-format. Imho, thats better than doing nothing. We can make clang compatible with radare2 sources. So we need to find more bugs and errors and list there -> then send to clang.

**Comment by ret2libc** [comment]
OK that sounds good!
Il 03/set/2015 18:57, "Anton Kochkov" <notifications@github.com> ha scritto:

**Comment by XVilka** [comment]
Was partially done, especially with contributing guidelines. There is a big room for improvement though and further work - e.g. whitelist more files for clang-format.

**Comment by radare** [comment]
We should probably push some pathes for clang format so maybe in two years we will be able to use it to indent the way we do.

**Comment by radare** [comment]
I think the standard format has been defined by all of us already, there's no way to automatize this by any tool, so just keeping good practices and review more should be enough to close this issue

**Comment by Maijin** [comment]
well at some point it can be tested too.

**Comment by radare** [comment]
It is already tested by humans
