### ISSUE TITLE
rabin2: no option for displaying exported ELF WEAK symbols similar to -E

### ISSUE THREAD

**Issue by armijnhemel** [radare/radare2#9343]
This is not really a bug report, but more of a feature request, although it would be good if this could somehow be done as part of rabin2 -E or similar :-)

I do know that -E says "globally exportable symbols" but weak symbols can be exported as well.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 26, x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | MIPS
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.4.0-git 17213 @ linux-x86-64 git.2.2.0-405-gb04fddc26
commit: b04fddc260b4410c560129df28ab01c14e8aa799 build: 2018-02-07__17:22:43
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/armijnhemel/4f147af26f0f24e2464102d906663eda

### Expected behavior

would be good if rabin2  could display WEAK symbols

### Actual behavior

WEAK symbols are not reported (no option available)

### Steps to reproduce the behavior 

[libc.zip](https://github.com/radare/radare2/files/1703901/libc.zip)

 ./rabin2 -E /path/to/libc.so.0  | grep WEAK | wc -l
0

$ readelf -W --dyn-syms /path/to/libc.so.0  | grep WEAK | grep -v UND | wc -l
45

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by Maijin** [comment]
Just use rabin2 -s

**Comment by Maijin** [comment]
rabin2 -s | grep WEAK

**Comment by armijnhemel** [comment]
That is what I ended up using it, but for consistency it might be nicer to have them all in one place.
