### ISSUE TITLE
rabin2: different named ELF symbols with same address only reported with one name

### ISSUE THREAD

**Issue by armijnhemel** [radare/radare2#9346]
I have a libc from a MIPS box here where various functions share the same address under different names. rabin2 does not report these correctly.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 26, x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | MIPS
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.4.0-git 17213 @ linux-x86-64 git.2.2.0-405-gb04fddc26
commit: b04fddc260b4410c560129df28ab01c14e8aa799 build: 2018-02-07__17:22:43

| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/armijnhemel/4f147af26f0f24e2464102d906663eda

### Expected behavior

rabin2 should report all declared functions under the name they have been declared under, even if the paddr is the same.

### Actual behavior

rabin2 reports functions that share the same paddr under one of the names declared in the binary.

### Steps to reproduce the behavior 

[libc.zip](https://github.com/radare/radare2/files/1704183/libc.zip)

$ readelf -W --dyn-syms libc.so.0  | grep 0004ee80
   143: 0004ee80    28 FUNC    GLOBAL DEFAULT    6 atol
  1026: 0004ee80    28 FUNC    GLOBAL DEFAULT    6 atoi

$ ./rabin2 -s libc.so.0   | grep 0004ee80
143 0x0004ee80 0x0004ee80 GLOBAL   FUNC   28 atol
1026 0x0004ee80 0x0004ee80 GLOBAL   FUNC   28 atol

readelf reports different names (which might be difficult to see here), rabin2 reports it as "atol" twice.

Another (clearer) example:

$ readelf -W --dyn-syms libc.so.0 | grep 0002edb0
   149: 0002edb0   356 FUNC    GLOBAL DEFAULT    6 getc_unlocked
   402: 0002edb0   356 FUNC    GLOBAL DEFAULT    6 __fgetc_unlocked
   980: 0002edb0   356 FUNC    GLOBAL DEFAULT    6 fgetc_unlocked

$ ./rabin2 -s libc.so.0   | grep 0002edb0
149 0x0002edb0 0x0002edb0 GLOBAL   FUNC  356 getc_unlocked
402 0x0002edb0 0x0002edb0 GLOBAL   FUNC  356 getc_unlocked
980 0x0002edb0 0x0002edb0 GLOBAL   FUNC  356 getc_unlocked

### Additional Logs, screenshots, source-code,  configuration dump, ...

Drag and drop zip archives containing the Additional info here, don't use external services or link.

**Comment by pombredanne** [comment]
This looks like a good bug to me alright.

**Comment by Maijin** [comment]
@pombredanne and?

**Comment by radare** [comment]
This is known issue and its part of the rbin refactoring we are working

You can patch the binary to rename one char of that symbol as a workaround

**Comment by pombredanne** [comment]
@Maijin I was just commenting that I can reproduce this alright and looked like a proper bug to me ;)
@radare Thank you for the quick reply! radare rocks 🚀

**Comment by armijnhemel** [comment]
Uff, sorry. I searched the bug reports, but couldn't find it :-(
Please feel free to mark it as a duplicate if it is already known.

I tried searching to code to see where it goes wrong but I cannot find it.

**Comment by ret2libc** [comment]
It seems this has been magically solved somehow.
Trying to reproduce:
```
$ ./binr/rabin2/rabin2 -v
rabin2 3.1.0 21736 @ linux-x86-64 git.3.1.0-20-g246fe4e10
commit: 246fe4e10bffccc4937350459604c58f4c917924 build: 2018-11-28__17:06:00

$ ./binr/rabin2/rabin2 -s ~/Downloads/libc.so.0  | grep 0002edb0
149 0x0002edb0 0x0002edb0 GLOBAL   FUNC  356 getc_unlocked
402 0x0002edb0 0x0002edb0 GLOBAL   FUNC  356 __fgetc_unlocked
980 0x0002edb0 0x0002edb0 GLOBAL   FUNC  356 fgetc_unlocked
```

**Comment by radare** [comment]
Maybe add a test? So it wont break magically

**Comment by ret2libc** [comment]
Yeah
