### ISSUE TITLE
iS entropy displays rounded integer

### ISSUE THREAD

**Issue by packmad** [radare/radare2#9366]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04 x86 64bit
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32, x86/64, ARM
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.4.0-git 17368 @ linux-x86-64 git.2.2.0-434-gb35f936 commit: b35f936b7306e8a978b8c9ea4baa8a7b57fbd63c build: 2018-02-10__20:58:59
| r2 -V full output in a pastebin document (mandatory) | [https://pastebin.com/AE4ccWre](https://pastebin.com/AE4ccWre)

### Actual behavior
```
> iS entropy
...
13 0x000029f0     8 0x004029f0     8 --r-x entropy=03000000 .plt.got
14 0x00002a00 70233 0x00402a00 70233 --r-x entropy=06000000 .text
...
```

The real entropy is:
.plt.got -> 3.22587278965
.text -> 6.32503919166

### Steps to reproduce the behavior 
```
iS entropy
```

**Comment by radare** [comment]
should be fixed now
