### ISSUE TITLE
-R stdin=!program doesn't work

### ISSUE THREAD

**Issue by giuscri** [radare/radare2#9374]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)         | radare2 2.4.0-git 17246 @ linux-x86-64 git.2.2.0-435-g10473c03f commit: 10473c03fbf4b56402bc1657624ace04be2176de build: 2018-02-11__14:03:04
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/giuscri/19f0ab1cf476ed796d5380f8ccf88ef0

### Expected behavior

Debuggee should not wait for input. It should consume bytes from the redirection.

### Actual behavior

radare2 seems _not_ to care about the redirection. Note that this should be a known bug as tests of redirection are marked as `BROKEN`— see https://github.com/radare/radare2-regressions/blob/master/t.archos/Linux-x86_64/feat_input_redirect#L5

### Steps to reproduce the behavior
```
$ r2 -A -d -R stdin='!python2 -c "print \"hi\""' -c dc ~/main
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
```
int main() {
	printf ("What's your name? ");
	char *name[32] = { 0 };
	scanf ("%31s", &name);
	printf ("Hello, %s\n", name);
}
```

```
$ r2 -A -d -R stdin='!python2 -c "print \"hi\""' -c dc ~/main
Process with PID 20215 started...
= attach 20215 20215
bin.baddr 0x560cf6cdb000
Using 0x560cf6cdb000
Unknown DW_FORM 0x06
asm.bits 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[x] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
= attach 20215 20215
20215
What's your name? # Waiting for input here, and it shouldn't
```
[9374.zip](https://github.com/radare/radare2/files/1714534/9374.zip)

**Comment by radare** [comment]
Dont pass flags after -d

**Comment by giuscri** [comment]
Still there though,
```
$ r2 -R stdin='!python2 "print \"hi\""' -d ./main
Process with PID 7954 started...
= attach 7954 7954
bin.baddr 0x563699796000
Using 0x563699796000
Unknown DW_FORM 0x06
asm.bits 64
 -- What has been executed cannot be unexecuted
[0x7f5472842f30]> dc
What's your name? 
```
