### ISSUE TITLE
rabin2 Issue

### ISSUE THREAD

**Issue by RajatMittal1995** [radare/radare2#9394]
Hello,
Would like help upon this error:
`rabin2: symbol lookup error: rabin2: undefined symbol: r_io_fd_get_current`

![screenshot_1](https://user-images.githubusercontent.com/9135666/36218640-150b1350-11db-11e8-9c11-843cb64f4fe8.png)

I'm trying to run command `rabin2 -I stack_bof_01`
Here, **stack_bof_01** is located at _**squashfs-root/pwnable/Intro**_ after extracting [DVRF.bin](https://github.com/praetorian-inc/DVRF/blob/master/Firmware/DVRF_v03.bin)

Thanks.

**Comment by Maijin** [comment]
Hello,

Ensure you are using radare2 from git, if you're unsure paste output of `r2 -v` here.
To install radare2 from git, first uninstall your version of radare2 and clean your distro. Then use `git clone https://github.com/radare/radare2 && cd radare2 && ./sys/install.sh`, verify your version and check if there is no error using `r2 -v`.

**Comment by radare** [comment]
You hav two installations of r2 and mixing libraries

**Comment by RajatMittal1995** [comment]
@Maijin, I installed using the steps as you shared which are same as the one in official radare documentation.
Output of `r2 -c` is `r2: symbol lookup error: r2: undefined symbol: r_sys_set_environ`

@radare, thanks. I did a fresh install, still same error persists.
I uninstalled using `./radare2-master/sys/uninstall.sh` then `sudo apt-get remove radare2` and in the end `sudo apt-get purge radare2`
After this, I did `./radare2-master/sys/install.sh` and still getting same error.

Also, not only rabin2.. there's similar error with radare2 as well. [Attaching Screenshot]
![screenshot_1](https://user-images.githubusercontent.com/9135666/36239366-e154cd18-122e-11e8-9dbe-7bf272f446a0.png)

Thanks.

**Comment by RajatMittal1995** [comment]
Update- Solution:
Performed a complete uninstall.
Installed using `sudo apt-get install radare2` , now its working perfect!
Not sure why this issue persists when using ./install.sh

**Comment by Maijin** [comment]
You just have crappy install of radare2 overlapping with the new one's

0.9.6 This is too old, 5 years old... 

So please uninstall everything, clean everything, don't forget to autoremove/autoclean etc. and you won't have this issue.

**Comment by RajatMittal1995** [comment]
Thanks Maijin, worked like a charm!
Current version `radare2 2.4.0-git 0 @ linux-x86-32 git.2.4.0-git commit: HEAD build: 2018-02-15__06:15:16`

Steps I followed:
1.`sudo apt-get remove radare2`
2.`sudo apt-get remove --auto-remove radare2`
3.`sudo apt-get purge radare2`
4.`sudo apt-get purge --auto-remove radare2`
5.`sudo apt-get remove radare2-plugins`
6.`sudo apt-get remove --auto-remove radare2-plugins`
7.`sudo apt-get purge radare2-plugins`
8.`sudo apt-get purge --auto-remove radare2-plugins`
Finally,
9. Ran `./install.sh`

**Comment by Maijin** [comment]
good

**Comment by radare** [comment]
Dont use debian :pp anyway there’s make purge in r2 that kills all previous installations of r2
