### ISSUE TITLE
Rabin crashed loading ELF with swapped segments

### ISSUE THREAD

**Issue by blackzert** [radare/radare2#9408]
Rabin2 crashed on trying to load ELF file with specially crafted segments. This is not a BUG of radar by itself, but bug in GNU Libc https://sourceware.org/bugzilla/show_bug.cgi?id=22851 but impact may affect radare2 users as well 

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86-64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)         | $ r2 -v radare2 2.4.0-git 17285 @ linux-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__10:55:21
| r2 -V full output in a pastebin document (mandatory) | https://gist.github.com/blackzert/088aea4e7eca8e3bf0a75b54eae7ece9

### Expected behavior
program should not crash ;)

### Actual behavior
programm crashed

### Steps to reproduce the behavior
$ git clone https://github.com/blackzert/aslur.git
$ cd tests/evil_elf
$ make && make evil
$ rabin2 -Q libevil.so 
Segmentation fault (core dumped)

### Additional Logs, screenshots, source-code,  configuration dump, ...
<img width="871" alt="2018-02-17 8 50 59" src="https://user-images.githubusercontent.com/20296774/36339183-bbb0ea50-13bf-11e8-9821-114e1649a2c4.png">

**Comment by radare** [comment]
this is a crash in the dynamic linked of your operating system, not in r2 code

**Comment by radare** [comment]
related 517c86060cbafa8bcf17538a0e427d78af03f11c

**Comment by radare** [comment]
please confirm
