### ISSUE TITLE
ESIL: ldp is not working

### ISSUE THREAD

**Issue by YugoCode** [radare/radare2#9443]
When emulating code I noticed that [_ldp_](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/LDP_gen.html) won't load the pair of values into the two registers. 
However [_stp_](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/STP_gen.html) is working. 

```
Example 1:
stp x29, x30, [sp, 0x10]
...
ldp x29, x30, [sp, 0x10]
```

```
Example 2:
stp x29, x30, [sp, -0x10]!
...
ldp x29, x30, [sp], 0x10
```

@giuscri 
Is this related to the problems you found with _ldr_ and _ldur_?  https://github.com/radare/radare2/issues/9197

___ 
You can find Example 2 in this method: _"method.FeedsMenuViewController.setLoginAsAlert:"_. The binary:
[NewsBlur.arm_64.1.zip](https://github.com/radare/radare2/files/1741725/NewsBlur.arm_64.1.zip)

**Comment by giuscri** [comment]
Doesn't seem related to #9197.

ESIL expression seems wrong again though:
```
$ rasm2 -b64 -aarm "ldp x29, x30, [sp, 0x10]"|rasm2 -b64 -aarm -d -E -
x29,sp,16,+,[8],x30,sp,16,+,8,+,[8]
```
That expression doesn't load anything into x29, x30. Maybe what's needed is
```
sp,16,+,[8],x29,=,sp,16,+,8,+,[8],x30,=
```

**Comment by YugoCode** [comment]
If the problem is again a wrong ESIL expression, I'm wondering for how many other instructions it is also wrong.

Is there a way to automatically validate the ESIL expressions for all the ARM64 instructions? @radare It's really laborious to debug every binary instruction by instruction to find the failing part.

**Comment by giuscri** [comment]
ldp should have been already tested. Actually test case was trivial to pass though. I've sent a PR to radare2-regressions to fix that
