### ISSUE TITLE
Broken Callgraph

### ISSUE THREAD

**Issue by hteso** [radare/radare2#945]
# Summary

Getting the callgraph of a function returns a graph with empty nodes.

# Procedure
```
radare2 true                                                                                                                                 hteso@iWiggles
 -- Nothing to see here. Move along.
[0x08048e44]> aa
[0x08048e44]> s entry0
[0x08048e44]> agc > /tmp/meow.dot
Invalid reference from 0x08048e44 to 0x0804b2d0
Invalid reference from 0x08048e44 to 0x0804b2e0
Invalid reference from 0x08048c96 to 0x000000d0
Invalid reference from 0x08048b06 to 0x00000008
...
Invalid reference from 0x0804a1e7 to 0x0804e100
Invalid reference from 0x0804a100 to 0x0804e100
[0x08048e44]>
```

# Result

After that, open the dot file with the latest xdot, or dotty, and a graph with the mentioned errors is seen as in the attached image.

![screen shot 2014-05-19 at 11 17 31](https://cloud.githubusercontent.com/assets/4849824/3012201/8df1491e-df36-11e3-9293-25906702a97b.png)

**Comment by radare** [comment]
Still happening?

**Comment by hteso** [comment]
No, no empty nodes now; but eh graph is huge.

**Comment by radare** [comment]
Because of the string refs being considered calls. So this can be closed?

**Comment by hteso** [comment]
Yep, thanks :)
