### ISSUE TITLE
Intermodular calls

### ISSUE THREAD

**Issue by gu10ng1t** [radare/radare2#9465]
How can I list all the intermodular calls (as I do on x64dbg)? If there is no way to do it easily then it's a feature request.

Debuggers like OllyDbg, x64dbg and possibly others do have this feature and it's very useful when reversing.

btw thank you for this awesome tool

**Comment by Maijin** [comment]
Can you provide screenshots, examples and describe this functionality please.

**Comment by gu10ng1t** [comment]
@Maijin [Here is a video showing that feature in olly](https://youtu.be/xfFVIz5jIeY?t=7m31s)

From the OllyDbg documentation you can see the following explanation for this feature:

"Search for|All intermodular calls" walks through the code and locates all calls with the final destination outside the current module, for example, all API calls, even loaded with GetProcAddress().

I'm sure it can be useful on every platform and not just on Windows.

**Comment by radare** [comment]
you mean callgraph?

```
> aac
> .agc*
> aggv
```

try this

**Comment by gu10ng1t** [comment]
ty @radare, the callgraphs are very useful, I really like them when I want grasp the whole thing and where it goes

well, lets detach the main expression here:
_locates all calls with the final destination outside the current module_

for example, from that callgraph is there any way to easily filter the calls from current module to itself? doing such thing would be what is expected from a find all intermodular calls command ;)

**Comment by radare** [comment]
As i said, those commands are not as userfriendly as they should be, which is the r2 way you would expect to get this done? Ill think about it and improve it for the next release right now im a bit busy with many other issues that matter for mondays release.

Thanks!

**Comment by radare** [comment]
I would call it import “graph” but i can think on other kind of graphs:

- callgraph
- xrefs graph
- refs graph
- bb graph
- data graph

For example, graphing all references to local variables in a function by making variables and addresses where those are referenced as nodes.

Etc

All this stuff is easy to do, the only complicated part is defining a clean way to achieve all that and cleanup the ag* commands once again to make it more consistent

**Comment by gu10ng1t** [comment]
That's awesome @radare. I hope you have time to do all that cool stuff.

At the moment I'm a part of a course in Reverse Engineering (CERO, from Mente Binaria project, lead by Fernando Merces). We started learning the basics of how to use x64dbg, ollydbg and a little bit of gdb. 

I did't know radare in the beginning but later on I discovered that it follows some principles that I see in vim (do lots of things through keyboard and don't waste time with mouse =p). So I became very interested in it (I can say that I felt like a true hacker haha ;)) . 

Once again thanks for your work!

**Comment by radare** [comment]
Well, i'm pretty short in time, but yep ill try to get this issue fixed before 2.5

**Comment by radare** [comment]
another thing we want is to have a graph.depth, this may allow us to render smaller graphs, and be able to expand the depth in visual graph

**Comment by ret2libc** [comment]
@gu10ng1t would something like `axt @@@i` work for you?

**Comment by gu10ng1t** [comment]
@ret2libc thank you for your suggestion, its very close to what we have on OllyDbg

I'm learning RE and if you didn't tell me it I would not know (learning curve of radare is not easy!)

if you had answered before I think @radare could close this issue hehe, but wait, don't close now hehe! @radare suggested some cool things a month ago:
 
> radare commented on 1 Mar
> I would call it import “graph” but i can think on other kind of graphs:
> 
> - callgraph
> - xrefs graph
> - refs graph
> - bb graph
> - data graph
> 
> For example, graphing all references to local variables in a function by making variables and addresses where those are referenced as nodes.
> 
> Etc
> 
> All this stuff is easy to do, the only complicated part is defining a clean way to achieve all that and cleanup the ag* commands once again to make it more consistent

I found very interesting and a good insight from the question I've made!

**Comment by radare** [comment]
I will do the cool graph things in 2.6, too busy to make them fit in 2.5, if that solves your issue yes close it. And open another one requesting all those graph changes i siggested (copypasta)

**Comment by gu10ng1t** [comment]
>  if that solves your issue yes close it

ok, you (or @ret2libc )  can close this issue!

once again thank you so much

**Comment by radare** [comment]
Whwres the new issue?

**Comment by gu10ng1t** [comment]
https://github.com/radare/radare2/issues/9867
