### ISSUE TITLE
pd syntax

### ISSUE THREAD

**Issue by radare** [radare/radare2#9466]
Recently i find out a bunch of inconsistencies.

* pd syntax is: `pd N-instructions (arch) (bits)`
* pd1 doesn't work

Solutions:

* kill the arch/bits args. because we now have `@a:` and `@b:`
* should be the same as `pd 1`

**Comment by michaelbr92** [comment]
I think that arch/bits and the parsing of the arguments are 2 different issues.  
The first is to remove all uses and settings of arch and bits for the config.  
and the second one will be to change the parsing of length in the command line.

**Comment by radare** [comment]
What dl u mean by remove all uses and settings of arch and bits?

Imho this issue is only for the 2nd thing you mentioned. And it was suposed to be a place a discuss if we all agree on that behaviour change.

**Comment by michaelbr92** [comment]
while ```pd1``` is really fast to type I think that it will be confusing in the other pd commands and in large numbers (ex. ```pd342``` in comparison to ```pd 342```)
but I agree that removing arch and bits from the command will be necessary

**Comment by radare** [comment]
If nobody is going to complain about this (except travis) i’ll do this change later tonight

**Comment by michaelbr92** [comment]
What change? the length parsing?

**Comment by radare** [comment]
And remove the space split logic to select arch and bits because we have @a: and @b:

**Comment by radare** [comment]
Fixed by @ret2libc
