### ISSUE TITLE
bb_pos makes no sense

### ISSUE THREAD

**Issue by radare** [radare/radare2#9468]
because is generated before splitting the BBs, this basically makes `wao recj@B:-1` not as cool as it should

**Comment by ret2libc** [comment]
What are you referring to exactly? I cannot find any bb_pos. Is it `bb->op_pos`?

**Comment by radare** [comment]
Yes bb->op_pos

**Comment by radare** [comment]
I added asm.bbinfo to show that infonqhen bbline is set, may help to debug

**Comment by ret2libc** [comment]
Problem was actually with how `@B` was implemented. bb->op_pos works fine.
