### ISSUE TITLE
fd* commands print only one flag name, although there are more

### ISSUE THREAD

**Issue by YugoCode** [radare/radare2#9470]
```
;-- section_end.16.__DATA.__objc_selrefs:
;-- section.17.__DATA.__objc_classrefs__DATA:
;-- reloc.NSMutableArray_16:
0x10000e210      .qword 0x0000000000000000
```

The fd* commands will print for the address _0x10000e210_ only  the first flag -> _section_end.16.__DATA.__objc_selrefs:_. They should print all the flag names.

**Comment by sivaramaaa** [comment]
@YugoCode , No fd command is not for listing all flags , it's just for printing flag at given offset
```
|Usage: fd[d]  [offset|flag|expression] # Describe flags
| fd $$         # describe flag + delta for given offset
| fd. $$        # check flags in current address (no delta)
```
U can try "f" command to list all flags 

```
f     list flags (will only list flags from selected flagspaces)
```

**Comment by YugoCode** [comment]
@sivaramaaa With all I mean "all the flags for the offset". 

As you can see in the example at address 0x10000e210 there are **three** flags. At this address the section _objc_selrefs_ ends, the section _objc_classrefs_ starts and there is a relocation. 

Now the fd* commands don't print these three (which I called all) flags, but only the first one.

**Comment by sivaramaaa** [comment]
@YugoCode , I hope it's fixed now , check it out with latest master !!!

**Comment by YugoCode** [comment]
@sivaramaaa It is now working with `fd.`, but not with `fd`. 

So these thinks need to be fixed:

- `fd` still prints only one flag, although there are more. 
-  There is no more JSON output when specifying `fd.j`
