### ISSUE TITLE
oom messes up the maps

### ISSUE THREAD

**Issue by radare** [radare/radare2#9483]
<img width="735" alt="screen shot 2018-02-23 at 18 25 13" src="https://user-images.githubusercontent.com/917142/36607487-0f0ae866-18c7-11e8-811f-2b473213a999.png">

**Comment by radare** [comment]
Having support for negative filedescriptors would be good to index them by position in array sorted asc.

so we can reuse output of other commands like `om*-1 > foo;oom;.foo`

**Comment by radare** [comment]
cc @condret

**Comment by condret** [comment]
r_io_desc_exchange is missing somewhere
