### ISSUE TITLE
Binary getting modified in write mode without explicit write operations

### ISSUE THREAD

**Issue by asutoshpalai** [radare/radare2#9489]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch linux x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | ARM (aarch64)
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17458 @ linux-x86-64 git.2.2.0-517-ge7e544cbd commit: e7e544cbd8835944faa5a0bf1ddd9555f5ffeb33 build: 2018-02-20__23:28:24

### Expected behaviour
When I have open a file in write mode, run analysis and then exit without doing anything, the file should not get modified.

### Actual behaviour
The file gets modified without any explicit modification and most probably it is corrupting it.

### Steps to reproduce the behavior 
- [adbd.zip](https://github.com/radare/radare2/files/1754127/adbd.zip)
- [asciinema of steps](https://asciinema.org/a/qqm2np4NxIySuKH986qtGcn3t)

 ```
$ cp adbd temp
$ md5sum *
f375cf3e6138b37a2f14cfda16e2f809  adbd
f375cf3e6138b37a2f14cfda16e2f809  temp
$ r2 -w -AA temp
...
[x] Type matching analysis for all functions (afta)
 -- Show offsets in graphs with 'e graph.offset = true'
[0x00404d88]> q
$  md5sum *
f375cf3e6138b37a2f14cfda16e2f809  adbd
2f5cd5fa0c353bf30b5cebbf5b1026d0  temp
```

**Comment by radare** [comment]
another problem caused by aaaaaa :P
