### ISSUE TITLE
no escape for special charecters in json serialization

### ISSUE THREAD

**Issue by michaelbr92** [radare/radare2#9493]
# no escape for special charecters in json serialization

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17284 @ darwin-x86-64 git.2.2.0-476-gf8cf84e06 commit: f8cf84e0653642d9ad34e760e0e56dd81860e799 build: 2018-02-17__11:08:27

### Expected behavior
characters as ' " '  will get escaped in json serialization
### Actual behavior
characters as ' " ' don't get escaped in some case

### Steps to reproduce the behavior 
- run command pfj z @0x80487bf
- will output [{"type":"z","offset":134514623,"value":134514623,"string":";*2$"."}]
[![asciicast](https://asciinema.org/a/PIz5N0uMs2MeUBwwCq5P6zJZH.png)](https://asciinema.org/a/PIz5N0uMs2MeUBwwCq5P6zJZH)

[megabeets_0x1.zip](https://github.com/radare/radare2/files/1754328/megabeets_0x1.zip)

**Comment by michaelbr92** [comment]
@Maijin can I bee assigned to it?

**Comment by Maijin** [comment]
I can't assign you on github but with your message you are claiming the issue ;)
