### ISSUE TITLE
Core dumped on prj via Ve

### ISSUE THREAD

**Issue by securisec** [radare/radare2#9503]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | ubuntu 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17400 @ linux-x86-64 git.2.2.0-588-g7421a73
commit: 7421a7347b94c5307e1f80bada51f3c423541479 build: 2018-02-25__04:30:49

Also notice that when `-p somefile` is used as an argument for r2, the start address is 0x00 and running aa, aaa, etc does not populate any data (not on video) 

https://asciinema.org/a/636aAxVuZWDIKStkFaHXZgzcV

**Comment by radare** [comment]
Cant reproduce. Can yuo provide a backtrace or crahslog?

Ive tried with asan and valgrind

**Comment by securisec** [comment]
Cant do it. Because after the crash, the terminal gets messed up and cant copy the messages. Do you have some instructions on how to grab what you need? Btw, i am able to re produce this on both ubuntu 64 and osx

**Comment by radare** [comment]
Use pipes

Valgrind -o logfile r2...

Or with asan:

R2 ... 2> logfile

**Comment by securisec** [comment]
In Ubuntu, i can only get the message `Segmentation fault (core dumped)`. In OSX, here is a screenshot

![image](https://user-images.githubusercontent.com/22226823/36692366-dc9079f0-1b05-11e8-95fa-4afc5bb7422a.png)

**Comment by radare** [comment]
Modify env.sh if u r using r2 from home to put the valgrind line there or the pipe redirections

**Comment by radare** [comment]
you can also attach a gdb or lldb to the r2 pid and then type bt , dis, i r,... to get the proper crashlog information

**Comment by securisec** [comment]
Hoping this is what you are looking for. 

https://pastebin.com/QuAAcZVL

**Comment by radare** [comment]
Is core->file NULL ?

**Comment by securisec** [comment]
Here is the core dump

[core.13512.zip](https://github.com/radare/radare2/files/1767617/core.13512.zip)

**Comment by radare** [comment]
so its not fixed in master?

**Comment by securisec** [comment]
Ah, sorry, didnt see the commit message. I can no longer reproduce. Thanks!
