### ISSUE TITLE
asm.emu being enabled when using O in VV but never disabled

### ISSUE THREAD

**Issue by FFY00** [radare/radare2#9512]
Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | `Ubuntu 17.10 (artful) x86/64`
| File format of the file you reverse (mandatory)      | `ELF`
| Architecture/bits of the file (mandatory)            | `x86/64`
| r2 -v full output, **not truncated** (mandatory)     | `radare2 2.4.0-git 17401 @ linux-x86-64 git.2.2.0-590-g2f76b3376 commit: 2f76b33769db26057b2e79a205dce9aef0e4a53a build: 2018-02-25__19:32:20`
### Expected behavior
Set `asm.emu` to `false` once to layout is changed. (see information bellow)

### Actual behavior
In visual mode (`VV`) when using `O` (`shift+o`) in one of the layouts `asm.emu` is set to `true` but in the following layouts it is never changed back to `false` again.

### Steps to reproduce the behavior 
  * `r2 file`
  * (go to a function)
  * `VV`
  * `O` (`shift+o`) multiple times

### Additional Logs, screenshots, source-code,  configuration dump, ...
I can fix the issue if someone points me to the actual files/methods responsible for the `O` command. Thanks :)

**Comment by radare** [comment]
O doesnt changes asm.emu at all, just toggles asm.esil which changes the disasm output to be esil instead of assembly. if you wanna rotate asm.emu use the ‘)’ key

**Comment by sivaramaaa** [comment]
Yup it doesen't change asm.emu , it toggles asm.esil and asm.pseudo !!
But i could see a point here !!!
```
r2 /bin/ls
[0x00005600]> VV  and  shift + o (twice)
[0x00005600]> q (quit from visual mode)
[0x00005600]> pd 10 
|           0x00005602      4989d1         rdx,r9,=           
|           0x00005605      5e             rsp,[8],rsi,=,8,rsp,+=
|           0x00005606      4889e2         rsp,rdx,= 
```
It would be nice if we restore the config value once user quit's  the graph or visual mode !!

what do u think @radare  ??

@FFY00  ,But idk if this is the issue u are talking about !!!

**Comment by radare** [comment]
Yep sgtm

**Comment by FFY00** [comment]
@sivaramaaa there are more than 2 profiles, keep hitting `shift+o` until you see the red comments with the emulated register values. You should be able to cycle back to the first layout with a couple hit but the problem is that `asm.emu` isn't turn back off after the profile that enables it is changed.

**Comment by sivaramaaa** [comment]
@FFY00 yup i could reproduce , but i think it's easy to fix , if u wanna checkout see these lines  https://github.com/radare/radare2/blob/a792aaafbe154c3a545e6d49747a867d7191b15f/libr/core/graph.c#L3901 that's causing issue 

Feel free to send a PR !!!

**Comment by FFY00** [comment]
Thanks, I'll try to fix the issue later when I have more time. Thanks for pointing me out to the files in question.

**Comment by radare** [comment]
i dont see the problem here, but ill chk the PR
