### ISSUE TITLE
rasm2 thumb-2 erroneous opcode for str rX,[rY,Z]

### ISSUE THREAD

**Issue by vdf-git** [radare/radare2#9524]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04 x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | arm-16 (ie. thumb-2)
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17419 @ linux-x86-64 git.2.2.0-602-g70bd99d commit: 70bd99da259438fbe552b7debfe68c571cdcd2da build: 2018-02-27__07:52:12

### Expected behavior
The command 
rasm2 -a arm -b 16 "str r0, r1, 0x74"
should produce the opcode
4867

### Actual behavior
It produces the opcode
4860
This is because the 3 MSB of the immediate are ignored. They should be ORed onto the last byte of the opcode (because of endianness

### Steps to reproduce the behavior 
A test has been submitted in https://github.com/radare/radare2-regressions/pull/1207
Problematic binary:
[rasm2.zip](https://github.com/radare/radare2/files/1761646/rasm2.zip)

**Comment by radare** [comment]
@vdf-git what about sending a pullreq instead of just commiting to your repo?
