### ISSUE TITLE
r2 is wrongly using dlopen when loading lang plugins.

### ISSUE THREAD

**Issue by kamou** [radare/radare2#9545]
tested on Fedora Workstation 27 with current master branch.
```
radare2 2.4.0-git 17520 @ linux-x86-64 git.2.2.0-641-g040dbad8a
commit: 040dbad8a391089965b9f9dbd8981e32ac43c495 build: 2018-03-01__19:40:55

```

So I'm testing with that simple code:
```
#include <Python.h>
 
static PyObject * hello(PyObject *self, PyObject *args) {
    const char *name;
    if (!PyArg_ParseTuple(args, "s", &name))
        return NULL;
 
    printf("Hello %s!\n", name);
    Py_RETURN_NONE;
}
 
static PyMethodDef methods[] = {
    {"hello", hello, METH_VARARGS, "Say hello to someone."},
    {NULL, NULL, 0, NULL}
};
 
PyMODINIT_FUNC inithello(void) {                            
    (void) Py_InitModule("hello", methods);
}

```

this is just a stupid hello world cpython module to show the problem with RTLD_LOCAL
I'm compiling it with:
`gcc -fpic --shared $(python-config --includes) hello.c -o hellomodule.so`

trying it with python:
```
$ export LD_LIBRARY_PATH=$PWD
$ python
>>> import hello
>>> hello.hello("r2world")
Hello r2world!
>>>
```

now if I try to use it in r2:
```
$ export LD_LIBRARY_PATH=$PWD
$ r2 -
 -- ((fn [f s n] (cat [(f f s n) "dare2"])) (fn [f s n] (pr s) (if (> n 0) (f f (cat [s "ra"]) (dec n)) s)) "" Infty)
[0x00000000]> #!python
python2> import hello
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: ./hellomodule.so: undefined symbol: _Py_NoneStruct
python2> 
```
looking at man dlopen:

> RTLD_LOCAL
>        This is the converse of RTLD_GLOBAL, and the default if neither flag is specified.  **Symbols defined in this shared object are not made available to resolve references in subsequently loaded shared objects.**
> 

so this means that if lang_python2 loads libpython, it will not make it available to later loaded cpython modules.
as long as those modules only have pure python dependencies (*.py), it will be ok.
but as soon as a subsequently loaded module such as the hellomodule.so needs access to libpython, they will fail to access its symbols because of RTLD_LOCAL.
so maybe the libpython should be RTLD_GLOBAL openend before lang_python2 which then could be RTLD_LOCAL if really needed.

But I guess the choice of RTLD_LOCAL was probably related to the fact r2 needed both python2 and python3 available, but I guess r2 should let the user just choose with an option or an environment variable what version of python to use.

**Comment by kamou** [comment]
maybe `dlmopen` could be an alternative

**Comment by radare** [comment]
Gnuism?

**Comment by kamou** [comment]
yes.

**Comment by XVilka** [comment]
@kamou 
```But I guess the choice of RTLD_LOCAL was probably related to the fact r2 needed both python2 and python3 available, but I guess r2 should let the user just choose with an option or an environment variable what version of python to use.```
Agree, moreover Python is walking dead nowadays, so targeting Python 3 is more important.

**Comment by kamou** [comment]
I get your point, but I personally wouldn't kill python 2 support yet. Mainly because I'm using triton which only supports python2 for now. But python 3 support is under development.
So I suggest to only switch from RTLD_LOCAL to RTLD_GLOBAL for now.
If you all agree, I can do a PR.
If you have a better idea, I'll be glad to hear it and maybe implement it.
