### ISSUE TITLE
Enable indirect addressing with offsets: pv8 @ [sp + 4]

### ISSUE THREAD

**Issue by YugoCode** [radare/radare2#9558]
Right now this is working:

```
pv8 @ x0
pv8 @ x0 + 8
pv8 @ [x0]
```

But you cannot add offsets for indirect addressing. So these all are not working:
```
pv8 @ [x0 + 8]
pv8 @ [x0, 8]
pv8 @ 8[x0]
```

Could someone add this feature please?

**Comment by YugoCode** [comment]
![Alt Text](https://media2.giphy.com/media/26gJzc8gAkTImtSLe/giphy.gif)
Whoops, my bad it works 😅

**Comment by YugoCode** [comment]
Is there a command that prints the address/result of **x1 + 8** and not the value at the address?
`pv` always prints the value at the address, but can you evaluate **sp + 0x20** with a command?

**Comment by radare** [comment]
?v does

**Comment by YugoCode** [comment]
Thank you!!! :)
