### ISSUE TITLE
Code analysis should auto-resize basic block 

### ISSUE THREAD

**Issue by giuscri** [radare/radare2#9564]
Basic blocks could be resized at run-time instead of specifying a max size.

Right now basic block maxsize is controlled by `eanal.bb.maxsize`. While `aa`, if you go past that value you'll get a warning saying
```
WARNING : block size exceeding max block size at 0x01013a00
[+] Try changing it with e anal.bb.maxsize
```
You can try to reproduce this via `$ r2 -A ./radare2-regressions/bins/anal/flare_notepad.ex`

See comments to https://github.com/radare/radare2/pull/9533 for some ideas on this.

**Comment by lowlyw** [comment]
i came across this issue in radiff2 also, this would be a nice option imo.

**Comment by radare** [comment]
@sivaramaaa can we close this?

**Comment by lewez** [comment]
Happening with this file too (was asked to post it here) https://ufile.io/isr8k

**Comment by ret2libc** [comment]
Moved to 3.5.0. It's unlikely it's going to happen for 3.3.0.

It would be a very welcome fix however.

**Comment by radare** [comment]
it think it shouldnt happen  now, l  cant repro at least
