### ISSUE TITLE
Jump table not working

### ISSUE THREAD

**Issue by Segflow** [radare/radare2#9582]
While playing with a little binary (attached below), I just noticed that radare2 don't show the jump table in the graph view, while Binary Ninja did. **anal.jmptbl** is enabled using `e anal.jmptbl=true`

### Radare2 version

Build from repo:
```
> $ r2 -v
radare2 2.4.0-git 17307 @ linux-x86-64 git.2.2.0-497-g0e24795
commit: 0e247959123aaac5247c885fed0a68d3a327a493 build: 2018-02-18__13:13:17
```

### Expected behavior
Shows the jump table in graph view

### Actual behavior
Simply shows `jmp eax` and nothing more

### Steps to reproduce the behavior 
- Load the binary attached.
- Enable **anal.jmptbl** using `e anal.jmptbl=true`
- Analyse the binary using `aaa`
- Seek to main and go to graph view

[little_tommy.zip](https://github.com/radare/radare2/files/1779050/little_tommy.zip)

**Comment by radare** [comment]
Wheres is this jmp?

**Comment by Segflow** [comment]
At the end of `main` function, block **0x80486db** 
<img width="564" alt="screen shot 2018-03-05 at 9 31 52 am" src="https://user-images.githubusercontent.com/2049730/36964799-13c70b12-2058-11e8-8f63-67bdee9f3ef3.png">

And here is how Binary Ninja:

<img width="1324" alt="screen shot 2018-03-05 at 9 33 37 am" src="https://user-images.githubusercontent.com/2049730/36964906-53b28508-2058-11e8-9729-c7d3b3a0117e.png">

**Comment by redmed666** [comment]
Hello! I could have the jump table correctly analysed.
Did you set the anal.jmptbl to true? (``` e anal.jmptbl=true```)
After that, I did a ```aa``` and I could have the complete jump table as you can see below :)

<img width="1306" alt="screen shot 2018-03-21 at 18 26 46" src="https://user-images.githubusercontent.com/15695476/37726378-805f29e6-2d35-11e8-953a-3d9c66d56507.png">

**Comment by Maijin** [comment]
@redmed666 is this with @Segflow binary?

**Comment by redmed666** [comment]
Yup

**Comment by Maijin** [comment]
ok then this can be closed, could you add a test ?

**Comment by redmed666** [comment]
Yes sure but what kind of test do you want?

**Comment by Maijin** [comment]
Check afb command on the various blocks ?

**Comment by radare** [comment]
do we have the test?
