### ISSUE TITLE
pf *z not working

### ISSUE THREAD

**Issue by radare** [radare/radare2#9584]
works for 32bit only so maybe the way to go would be to go would be *z... but i think we can detect if its widechar or utf8, ascii, etc

see
```
|  *       next char is pointer (honors asm.bits)
|  z       \0 terminated string
|  Z       \0 terminated wide string
|  s       32bit pointer to string (4 bytes)
|  S       64bit pointer to string (8 bytes)
```

<img width="1006" alt="screen shot 2018-03-05 at 00 23 34" src="https://user-images.githubusercontent.com/917142/36952125-0736e2e2-200c-11e8-92d8-f95413d69a78.png">

**Comment by radare** [comment]
cc @kazarmy

**Comment by kazarmy** [comment]
If `asm.bits=64`, can't reproduce. If `asm.bits=32`, then `pf *z` appears to be working as intended (assuming `cfg.bigendian=false`).

**Comment by radare** [comment]
I fixed this for *D yesterday. Maybe its related but we have no tests for those. Can u?

**Comment by kazarmy** [comment]
> I fixed this for *D yesterday. Maybe its related but we have no tests for those. Can u?

Probably. See test above.
