### ISSUE TITLE
ESIL produces wrong result

### ISSUE THREAD

**Issue by l0stb1t** [radare/radare2#9587]
I think I found a bug in esil
```
[0x004049a0]> "wa mov ebx, eax"
Written 2 byte(s) (mov ebx, eax) = wx 89c3
[0x004049a0]> aoe
0x4049a0 rax,rbx,=
[0x004049a0]> "wa mov ebp, eax"
Written 2 byte(s) (mov ebp, eax) = wx 89c5
[0x004049a0]> aoe
0x4049a0 rax,ebp,=,0xffffffff,rbp,&=
```
in 64bit mode, mov ebx, eax I think the correct esil string should be
```
eax,ebx=,0xffffffff,rbx,&=
```
mov ebp, eax should be
```
eax,ebp,=,0xffffffff,rbx,&=
```

**Comment by radare** [comment]
This is probably a bug in the assembler not in esil

**Comment by XVilka** [comment]
It is supposed to be solved in https://github.com/radare/radare2/blob/master/libr/anal/p/anal_x86_cs.c#L746
```c
		case X86_OP_REG:
		default:
			if (INSOP(0).type == X86_OP_MEM) {
				op->direction = 1; // read
			}
			{
				src = getarg (&gop, 1, 0, NULL, SRC_AR);
				dst = getarg (&gop, 0, 0, NULL, DST_AR);
				const char *dst64 = r_reg_32_to_64 (a->reg, dst);
				esilprintf (op, "%s,%s,=", src, dst);
				if (a->bits == 64 && dst64) {
					r_strbuf_appendf (&op->esil, ",0xffffffff,%s,&=", dst64);
				}
				break;
			}
}
```
But apparently register function doesn't consider this as a 64bit destination.

**Comment by radare** [comment]
Disassemble the instruction right after assembling and you can see what im refering to. If this is a bug in there, the problem goes to capstone, not r2

**Comment by kamou** [comment]
I think the problem is here: https://github.com/radare/radare2/blob/master/libr/anal/p/anal_x86_cs.c#L210

**Comment by kamou** [comment]
I don't know why getarg is renaming register variants when in 64 bits

**Comment by XVilka** [comment]
Ah, it was before the that `dst64` parameter was checked AFAIR.

**Comment by radare** [comment]
merg?

**Comment by radare** [comment]
dont use merge, do rebase pls :3
