### ISSUE TITLE
[ESIL] Calculated address is 64 bits instead of 32 bits when overflowed

### ISSUE THREAD

**Issue by redmed666** [radare/radare2#9595]
| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | macOS 10.13.3
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.4.0-git 17460 @ darwin-x86-64 git.2.2.0-642-g348057f5a
commit: 348057f5ae22c0694b83fd51bc16760d51b1553c build: 2018-03-02__07:38:26

### Expected behavior
When trying to access an address in memory, radare2 should take into account the maximum bit size of the targeted architecture.

So for example:

```bash
mov byte [esi + eax], dl
```
with:
```bash
eax 0x00419aa8
esi 0xffd84980
```

```esi+eax```should give 0x0019e428

### Actual behavior
When doing this calculation, radare2 is accessing 0x10019e428.

**Comment by radare** [comment]
can you paste the hexpairs that construct this snippet to make a test out of it?

thanks!

**Comment by redmed666** [comment]
Hi,

Is this ok for you?

```bash
    8b7508        mov esi, dword [ebp + 8]
    2bf0             sub esi, eax
    8a10             mov dl, byte [eax]
    49                dec ecx
    881406        mov byte [esi + eax], dl
    40                inc eax
    85c9            test ecx, ecx
    7ff5              jg 0x4182f3
```

**Comment by radare** [comment]
well those bytes are useless because they depend on the values of eax, ebp, esi... i was looking for a self-contained snippet that can test this issue.

**Comment by redmed666** [comment]
Alright, here is an example which is self-contained this time:

```
b200           mov dl, 0
be3412ffff     mov esi, 0xffff1234
889645234100   mov byte [esi + 0x412345], dl
```

So here, you will see that r2 will write 0x00 at 0x100403579 instead of 0x00403579.

**Comment by redmed666** [comment]
I've found where a patch seems to be needed.
In esil.c > esil_poke_n > line 1793 (```ret = r_anal_esil_mem_write (esil, addr, b, bytes);```).
So I could avoid the issue by doing addr & 0xffffffff in order to be sure that the address is a 32 bits one. The issue is I don't know how I can do that in order to be architecture independent.

Do you have something in mind to do that?

**Comment by redmed666** [comment]
Hi,

Do you have an idea how I could be sure that the address calculated is in the range of address of the architecture analysed? I think the functions *_esil_mem_{write, read} miss this kind of check.

**Comment by condret** [comment]
esil only knows 64bit offsets, bc off simplicity in the implementation. Otherwise emulating segmentation/bankswitching would become even harder. we can add a mask for these cases in the generated esil

**Comment by redmed666** [comment]
Ok that explains a lot :)

So, you mean that the ESIL printed would have a "&=" with a mask in order to be sure that the calculated offset is ok?

**Comment by redmed666** [comment]
Hum, this solution of the ESIL would not too much to implement? I would presume that would impact every "[]" operation, right? And all these operations will use at some point mem_{read, write} so, won't that be easier to modify these functions instead?

**Comment by radare** [comment]
Maybe we can add an addrsize variable in the ESIL vm to specify the size of the memory address bus, to apply that mask when accessing memory for read and write operations. Instead of modifying all esil expressions to behave like this. That will be clearner imho

**Comment by redmed666** [comment]
So, I would presume that would mean to add ut64 addrsize in the RAnalEsil struct, initialize it in r_anal_esil_new and use it as a mask from the *_mem_{read,write} functions?

**Comment by radare** [comment]
Then that would be called addrmask :P but yep that was the idea. Maybe addrmask makes more sense

**Comment by redmed666** [comment]
Hehe :D Ok perfect, I will work on that :) Question about the initialization of addrmask: from where could I know the size of the addresses in the context of esil?

**Comment by redmed666** [comment]
Pull request #9673 :)

**Comment by condret** [comment]
gb abuses this for the bankswitches

**Comment by condret** [comment]
i think the generated esil should look like this ´´´´dl,esi,0x412345,+,0xffffffff,&,=[1]´´´´

pls keep things like real-mode exist, 16-bitness can access 20-bit offsets.

**Comment by radare** [comment]
we will have to change a lot of esil expressions if we do it like this and to become longer. because every one with [] will require that & before. imho is better to make it into the esil state configurable by the user and set by core when used

**Comment by condret** [comment]
at least don't make the esil api use the rconfig directly, should be independent from an r2-instance. I personally prefere these operations to be setup by the plugin. lots of things depend on this working as it does atm. everything that has bankswitching or segmentation

**Comment by condret** [comment]
can we make this special implementation a set of customops, that override the default ops?

**Comment by redmed666** [comment]
So if I understood correctly, a possible solution would be to add an option in esil that the user needs to switch on in order to make it work like that? And the default would set the addrmask to 0xffffffffffffffff so that would be like before?

**Comment by redmed666** [comment]
@condret: I was wondering regarding your solution with esil: how something using a bankswitch wouldn't be impacted by that? I presume the esil produced by this case would be the same, no?

**Comment by radare** [comment]
Too much work for just a test imho this doesnt needs to be that complicated

**Comment by radare** [comment]
Yes
