### ISSUE TITLE
Disassembly Flags are getting confused 

### ISSUE THREAD

**Issue by deeso** [radare/radare2#960]
May be related to: https://github.com/radare/radare2/issues/929

In the **pe** regression test, the section flag **section..rdata** is being used instead of the **str.Hello** flag.  The conflict arises because both have the same virtual addresses, and the r_parse_filter resolves the **section..rdata** flag first.  This can be fixed with SDB and adding a priority list (e.g. where to look for addresses first) for the look-up of flags.  

The issue has been followed to this general area in the disassembly code: 
https://github.com/radare/radare2/blob/master/libr/core/disasm.c#L332
https://github.com/radare/radare2/blob/master/libr/core/disasm.c#L367
https://github.com/radare/radare2/blob/master/libr/parse/parse.c#L102

**Comment by XVilka** [comment]
Can be useful for this release, I think.

**Comment by radare** [comment]
Whats the issue and the solution you propose? Adding priorities to flagspaces?

**Comment by XVilka** [comment]
Yes, this is exactly what I thought.

**Comment by radare** [comment]
i think the current approach is good as long as few people or nobody complains about the behaviour, we can open specific issues when we found another problem
