### ISSUE TITLE
#if USE_NEW_FCN_STORE

### ISSUE THREAD

**Issue by radare** [radare/radare2#9611]
its value is 0.. and uses r_listrange so maybe we can remove it because current fcn storage works pretty fast and its been a long time without maintaining that

**Comment by MaskRay** [comment]
What is the purpose of `r_listrange_*` in `libr/anal/fcnstore.c`?

**Comment by radare** [comment]
make the RList of functions faster to be iterated. But we now have RBTree and other stuff that makes this unnecessary, so probably better to remove old unused code and go for this instead
