### ISSUE TITLE
[Visual graph] Pressing "t" doesn't branch to true

### ISSUE THREAD

**Issue by rfc2119** [radare/radare2#9612]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             |Ubuntu x86 32
| File format of the file you reverse      |ELF
| Architecture/bits of the file            | x86/32

`r2 -v`: radare2 2.5.0-git 17589 @ linux-x86-32 git.2.4.0-14-g88eb6e9
commit: 88eb6e964585a39bbd86965e3280087a34f4f176 build: 2018-03-06__22:30:02

Record link: https://asciinema.org/a/3jG9EnkfFwiYii8EYMPuCDvpV

### Expected behavior
t/f should branch as normal. Also on the lock instruction, pressing _tab_ should jump to the right block

### Actual behavior
Breakdown of the record:
**00:30 → 00:38**: I've repeatedly pressed _t_ in order to move to _gp_ block. The screen gets centered instead
**00:40 → 00:48**: Pressing t/f both jumps tp the _lock_ instruction
**00:49 → end**: Pressing _tab_ should jump to the _1f2a_ block. Instead, it centers the screen

### Steps to reproduce the behavior 
This is the __vfprintf_internal__ function in the asciinema record
[_IO_vfprintf_internal.zip](https://github.com/radare/radare2/files/1787018/_IO_vfprintf_internal.zip)

**Comment by radare** [comment]
as a workaround set this in your r2rc:

e graph.dummy=false

**Comment by ret2libc** [comment]
https://github.com/radare/radare2/commit/6428824bc6b30872f523ca1497890ce564c83180
https://github.com/radare/radare2/commit/1d81e15424a22afd738831f84ae85fa2a1c7fedd

I'll revert these 2 commits and track down the root cause of the issue.
