### ISSUE TITLE
Yank with multiple clipboards

### ISSUE THREAD

**Issue by radare** [radare/radare2#9617]
What do when you want to swap the bytes from one place to another? we need disk access to cache that in disk first.. so ideally we may want to have multiple clipboards.. addressed by index or using a stack

**Comment by XVilka** [comment]
Same as in Vim maybe?

**Comment by radare** [comment]
Yep

**Comment by condret** [comment]
atm the clipboard is a malloc:// and a RIOMap if I remember correctly

**Comment by radare** [comment]
i was also thinking in having named yanks this weekend

**Comment by XVilka** [comment]
@radare like Vim registers?

**Comment by radare** [comment]
Yes

**Comment by XVilka** [comment]
I think this also should provide a way to view all yank registers easily, command/hotkey to view all of them.

**Comment by radare** [comment]
i have implemented alias files which can be used for this
