### ISSUE TITLE
rax2 stuff inside r2 prompt

### ISSUE THREAD

**Issue by radare** [radare/radare2#962]
We need to find a way to perform this (obey cfg.bigendian) to convert a number into a string and the way back.

```
[0x00006130]> !rax2 -s 0x20646f6d736e690a
domsni
[0x00006130]> !rax2 -s 0x20646f6d736e690a | rev
insmod
```

**Comment by radare** [comment]
See ??? command there are several rax2 stuff in there

**Comment by XVilka** [comment]
@radare it was implemented already, right?

**Comment by radare** [comment]
Nope. Not all raz2 features are available from ?

Think about base conversions and other stuff. But most inportant ones are there. So i would close

**Comment by Maijin** [comment]
let's wait for a real need for this to reopen
