### ISSUE TITLE
Split "sections" RBinPlugin callback into "sections" and "mappable"

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#9625]
At the moment, you can't map parts of a file without having a section for it. This means that, for example, in bin_elf.c we have to add fake sections for segments, so that they are then mapped in IO.

See:
https://github.com/radare/radare2/blob/master/libr/bin/p/bin_elf.c#L212

I propose we split the callback in 2:
1. sections which just returns the list of sections as provided in the binary
2. mappable which returns the list of sections that needs to be mapped

In this way, we don't need to create fake sections and it's easier in other parts of r2 to just get the list of sections as expressed in the binary, without having to special case the segments.

**Comment by radare** [comment]
cc @condret

**Comment by radare** [comment]
dont we have this already solved?

**Comment by ret2libc** [comment]
The problem is a bit different here. It was more about the API than the output shown to the user. Anyway, I'm going to close it for the moment and I can re-open it after having a better look at it and see if it's still a problem.
