### ISSUE TITLE
SONAME is improperly defined in the shared libs

### ISSUE THREAD

**Issue by yurivict** [radare/radare2#9636]
For example, libr_util.so has SONAME libr_util.so. This means that when you change interface in the headers, users aren't required to update depending ports.

This is error-prone, and will cause depending ports to fail. There are interface changes between 2.2.0 and 2.4.0.

Normally, SONAME should be libr_util.so.2 or libr_util.so.2.4.

**Comment by xambroz** [comment]
Hello,
there is already undocumented modifier HAVE_LIBVERSION=1 to get the soname versioned.
make HAVE_LIBVERSION=1 

$ objdump -x /usr/lib64/libr2.so.2.4.0|grep SONAME
  SONAME               libr2.so.2.4.0

Best regards
Michal Ambroz

**Comment by yurivict** [comment]
> there is already undocumented modifier HAVE_LIBVERSION=1 to get the soname versioned.

This should be happening by default.

**Comment by radare** [comment]
We can evaluate to change this  in next release. But only for make builds. Meson builds will need to change, and this is something that doesnt works on windows

**Comment by pelijah** [comment]
I can make it for Meson but there is no way to do it optional. In this case Meson will generate such names on Windows: `r_util-2.5.0-git.dll`. This will break Cutter build for WIndows.

**Comment by pelijah** [comment]
But we can rename libs on installing step in sys/meson.py.
