### ISSUE TITLE
DYLD Shared Cache

### ISSUE THREAD

**Issue by stek29** [radare/radare2#9652]
On Apple *OS most libraries are bundled in [DSC](http://iphonedevwiki.net/index.php/Dyld_shared_cache).

It's a massive file with all Mach-O's of different libs glued together, and optimized.

Extraction is cumbersome and leaves many artifacts -- first of all, indirect calls are replaced by direct calls to preresolved locations (except a whitelist which can be found in dyld sources). Since branch destination can be too far, branch islands concept is introduced.
Also, some symbols are replaced with <redacted>, however, they're usually preserved at least in some symtabs.
Also, sometimes it can be not fully relocated from what I've seen, but I'm not sure about that. Anyway, there is relocation info in the file.

Probably some file selection mechanism is needed, or symbols can be prefixed with file's dylib id on conflict, I'm not sure on how to implement this in a good way.

**Comment by radare** [comment]
Dyldcache is supported in r2 for years

**Comment by mrmacete** [comment]
yup, and recently improved to load the whole cache (can be filtered down to a subset) see the writeup here: https://github.com/radare/radare2/pull/10094
