### ISSUE TITLE
Add support for extended regex

### ISSUE THREAD

**Issue by n4r1b** [radare/radare2#9656]
Maybe there could be an Evaluable var inside search to add support for extended regex, something like <code>search.extended</code>. Having that we could evaluate that var and modify the second parameter ("e") in function r_regex_new for ex.: https://github.com/radare/radare2/blob/2ecaaf493912a25179116d67d8752dbf87fe3c6d/libr/core/asm.c#L147 

This would allow us to do things like this:

```
[0x00401000]> "/c/ call (eax|ebx)"
0x00406632   # 2: call ebx
0x004186f5   # 2: call eax
0x0041ae4d   # 2: call ebx
0x0041ae84   # 2: call ebx
```

**Comment by radare** [comment]
I think this is achhieved by ending the regex with /e but i dont have a shell to test now. Also that depends on the libc implwmentation

**Comment by n4r1b** [comment]
I just tried with /e and at least in my PC it didn't work. Hard coding the second param of r_regex_new to "e" did the work. Anyways I thought regex depended on the implementation inside utils/regex I guess that if it depends on libc this is not the best solution but this is way beyond the scope of my knowledge

**Comment by radare** [comment]
Can you send a pr? Didnt checked the code when i replied. I was not in laptop but iirc default is util/regex so just enabling the “e” may be enough

**Comment by n4r1b** [comment]
Oky, I'll send a pr tonight

**Comment by radare** [comment]
Thanks!
