### ISSUE TITLE
radare2 2.4.0 release has issues with the color console

### ISSUE THREAD

**Issue by xambroz** [radare/radare2#9665]
Hello,
there is some issue in the 2.4.0 release which causes the radare2 fail to initialize the color of the prompt (and some other dialogs like list assembly with pdf, visual mode assembly, zoom mode etc.)

GOOD - This is how it looked like in 2.3.0 (same machine, same dependencies):
![screenshot from 2018-03-12 14-03-44](https://user-images.githubusercontent.com/723625/37285104-d3ec24de-25f5-11e8-8917-7cf726236eb5.png)

BAD - This is how it looks like with version 2.4.0:
![screenshot from 2018-03-12 13-56-38](https://user-images.githubusercontent.com/723625/37284797-d5a5d924-25f4-11e8-9ca3-14caf3e707d1.png)
You can see that starting the radare2 couple of times always gets different prefix printed out - most probably using some un-initialized memory.

It affectes also colors for example in disassembly printing "pd":
![screenshot from 2018-03-12 13-58-57](https://user-images.githubusercontent.com/723625/37284911-2d6e9c72-25f5-11e8-9967-6e620d4597ec.png)

I have tried now with the git HEAD commit 
https://github.com/radare/radare2/commit/405524d2f80188636326c5007a358bd9b8214202.
The situation seems to be slightly changed - the string is probably pertaining the value between executions, but still not initialized with the right value on the beginning:
![image](https://user-images.githubusercontent.com/723625/37287100-e0772b12-25fb-11e8-9513-77874b62612f.png)

Workaround: 
- enter the visual mode "V" and exit it with "q" ... from that time the console re-sets and color text displays OK.
- some other actions reset the color entities as well ... such as piping the output through some command
![screenshot from 2018-03-12 14-01-07](https://user-images.githubusercontent.com/723625/37285014-78db7a2c-25f5-11e8-98a4-0d9b91afba66.png)

**Comment by xarkes** [comment]
Oh. Can you try with various configurations of `scr.color`?
Does it happen when `scr.color` is set to 1? To 2? To 3?
Does calling `ecd` fixes that issue?

**Comment by radare** [comment]
If undefined behaviour buld with asan or run with valgrind and share logs. But better check only git than release

**Comment by radare** [comment]
Also share your radare2rc or try with an empty one

**Comment by xambroz** [comment]
>Also share your radare2rc or try with an empty one
```
$ cat .radare2rc 
; Automatically generated by radare
e scr.color=true
e dbg.bep = entry
e asm.syntax=intel
e asm.comments=true

; Align comments to column
e asm.cmt.col=80

; Show pseudo code
e asm.pseudo = false

; Use UTF8 arrows
e scr.utf8 = true
```

**Comment by radare** [comment]
e scr.color=2

it is no longer a boolean

**Comment by xambroz** [comment]
Sure ... but you would expect to error gracefully or interpret "true" as 1 or 2. 
Instead it starts behaving flaky with parameters saved by radare2 itself in the past or/and recommended in other materials like:

$ grep -a -n -o -R -e "scr.color[ ]*=[ ]*true" *
libr/core/rtr.o:47:scr.color=true
libr/core/libr_core.so:6081:scr.color=true
libr/core/rtr.c:189:scr.color=true
shlr/www/m/legacy.js:1:scr.color=true
shlr/www/m/legacy.js:1:scr.color=true
shlr/www/p/r2core.js:1:scr.color=true

https://github.com/radare/radare2book/blob/master/configuration/intro.md
https://github.com/radare/radare2book/blob/master/configuration/colors.md
https://github.com/radare/radare2book/blob/master/introduction/commandline_flags.md
https://github.com/radare/radare2book/blob/master/configuration/common_configuration_variables.md

and so on ...

Best regards
Michal Ambroz

**Comment by radare** [comment]
Is this the problem?

**Comment by xambroz** [comment]
Tested - works for me.
