### ISSUE TITLE
command "ecs" ends in infinite loop in scr.color = 2   

### ISSUE THREAD

**Issue by xambroz** [radare/radare2#9676]
The command "ecs" ends in infinite loop in scr.color=2.
![image](https://user-images.githubusercontent.com/723625/37316560-c6be7034-2657-11e8-8498-e0edded7d16c.png)

It works for scr.color=0 or scr.color=1.

**Comment by radare** [comment]
Cc @xarkes

**Comment by xarkes** [comment]
It used to be looping on an integer, so the condition `r <= 0xff` would eventually be true. Now that we use `ut8` it just overflows and loops infinitely.

**Comment by radare** [comment]
fixing now
