### ISSUE TITLE
Hard coded ld breaks cross compiling

### ISSUE THREAD

**Issue by jnbr** [radare/radare2#9693]
Previous releases of radare2 could be easily cross-compiled.
This is not the case for the latest version 2.4.0. 

The reason is the hard coded `ld` in `${PARTIALLD}` introduced in: https://github.com/radare/radare2/commit/dcd1ef1c6bb136337113b3ec17adb0d42dcaf4cb.
I fixed it for Voidlinux, by replacing `ld` with `${LD}`: [voidlinux-patch].

I think `${LD}` should be used instead of `ld` in all places.

[voidlinux-patch]: https://github.com/jnbr/void-packages/blob/d7ed55aa0e112a34edf1204c9d289793128b89ec/srcpkgs/radare2/patches/cross-ld.patch

**Comment by radare** [comment]
Can you send a pr fixing this? Maybe setting partialld as ld when its set?

**Comment by jnbr** [comment]
I do not understand what you mean by: 
> Maybe setting partialld as ld when its set?

#9720 should fix though.
