### ISSUE TITLE
Add command to show ascii table

### ISSUE THREAD

**Issue by radare** [radare/radare2#9699]
Maybe also add it into the rax2 manpage (or in rax2 itself)

**Comment by r00tus3r** [comment]
Please merge my pull request
https://github.com/radare/radare2/pull/9703

**Comment by davidpolverari** [comment]
I think this one was already implemented by e16b1ef1c8213e3da377096890399f43592d45ea. Should it be closed?

**Comment by radare** [comment]
Yes. Thanks! You can autoclose issues if you put “Fix #issuenumber” in the commit message
