### ISSUE TITLE
Opening ELF in write mode throws "r_io_create: Permission denied" error 

### ISSUE THREAD

**Issue by samouy** [radare/radare2#9704]
Hello there ! 

I would like to report the following issue : 

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian 9/x86/64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            |  x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.5.0-git 17670 @ linux-x86-64 git.2.4.0-151-g0f275ea9a commit: 0f275ea9a65fbea45f9a91bad1f374a343de062c build: 2018-03-15__17:52:09

### Expected behavior

`r2 -w my_binary` opens the file `my_binary` in write mode.

### Actual behavior

`r2 -w my_binary` throws the following error : 

```
r_io_create: Permission denied.
[w] Cannot open 'ch13' for writing.
```

and exits immediately.

### Steps to reproduce the behavior 

Download the following binary (a crack me challenge) :  
[bin.zip](https://github.com/radare/radare2/files/1816407/bin.zip)
(SHA256 : 26959ee1fb8356936cc1f103b2034437e05832277880fa5aed7592d85a1d392a)

Try to open it in write mode. 

### Additional Logs, screenshots, source-code,  configuration dump, ...

Binary information : 
`ch13: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, stripped`

Thanks for the help !

**Comment by thestr4ng3r** [comment]
Works for me at least:
```
[florian@florian-desktop re]$ r2 -w ch13 
Warning: Cannot initialize dynamic strings
 -- Select your character: RBin Wizard, Master Anal Paladin, or Assembly Warrior
[0x08048060]> pd 1
            ;-- entry0:
            ;-- section..text:
            ;-- eip:
            0x08048060      eb01           jmp 0x8048063               ; [01] --r-x section size 648 named .text
[0x08048060]> wa nop
Written 1 byte(s) (nop) = wx 90
[0x08048060]> pd 1
            ;-- entry0:
            ;-- section..text:
            ;-- eip:
            0x08048060      90             nop                         ; [01] --r-x section size 648 named .text
```
Are you really sure you have write permissions to that file?

**Comment by samouy** [comment]
Which permissions do you have on your side ? 
I checked and modified the file's permission and tried to reopen it with different modes : 

Fails : 
`-rwxr-xr-x 1 sam sam 884 Jun  3  2012 ch13`
`-rwxrwxr-x 1 sam sam 884 Jun  3  2012 ch13`
`-rwxrwxrwx 1 sam sam 884 Jun  3  2012 ch13`

**Comment by thestr4ng3r** [comment]
Same:
`-rwxr-xr-x 1 florian users 884 15. Mär 18:24 ch13`
Then it really seems to be a bug.

**Comment by cothan** [comment]
It works normally on my side.
```
⋊> /tmp r2 -v output                                                    14:52:12
radare2 2.5.0-git 17671 @ linux-x86-64 git.2.4.0-95-gd0baa8ebd
commit: d0baa8ebd34bceea91282b2ba686ccc8bfc2b732 build: 2018-03-13__12:43:19

⋊> /tmp unzip bin.zip                                                   14:50:28
Archive:  bin.zip
  inflating: ch13                    
⋊> /tmp r2 -w ch13                                                      14:50:32
Warning: Cannot initialize dynamic strings
 -- Almost 5am, maybe you should go to bed.
[0x08048060]> aa
[x] Analyze all flags starting with sym. and entry0 (aa)
[0x08048060]> pd 10
Free fake stack
            ;-- section..text:
╭ (fcn) entry0 21
│   entry0 ();
╰           0x08048060      eb01           jmp loc.08048063            ; [01] --r-x section size 648 named .text
            0x08048062  ~   e8b8300000     call 0x804b11f              ; CALL: 0x0, 0x0, 0x0, 0x0
├ loc.08048063 19
│   loc.08048063 ();
│           ; JMP XREF from 0x08048060 (entry0)
│           0x08048063      b830000000     mov eax, 0x30               ; '0'
│           0x08048068      bb05000000     mov ebx, 5
│           0x0804806d      b9e2800408     mov ecx, 0x80480e2
│           0x08048072      cd80           int 0x80                    ; 48 = signal (0x00000005, 0x080480e2)
╰       ╭─< 0x08048074      eb01           jmp 0x8048077
        │   0x08048076      ce             into
        │   ; JMP XREF from 0x08048074 (loc.08048063)
        ╰─> 0x08048077      cc             int3
├ loc.08048078 2
│   loc.08048078 ();
│           ; JMP XREF from 0x08048074 (loc.08048063)
╰       ╭─< 0x08048078      eb01           jmp loc.0804807b
[0x08048060]> 
```

**Comment by leberus** [comment]
I couldn't reproduce this either.
Could you try to debug it and see where it goes wrong.
Or strace it with "-e open"

**Comment by samouy** [comment]
Hello, 

thanks for your replies. After rebooting, I opened the file successfully in write mode. I don't know where this error came from... Thanks for your help guys !

**Comment by ertosns** [comment]
this can happend if the excutale is being buzy, or used, try to close all software opening target binary, then make sure it has write permissions, no need to reboot!
