### ISSUE TITLE
Make ar=/dr= accept a list of space/comma separated list of registers to show

### ISSUE THREAD

**Issue by radare** [radare/radare2#9710]
instead of 
```
[0x10000122a]> ar=rax rbx
 rax 0x00000000           rbx 0x00000000           rcx 0x00000000
 rdx 0x00000000           rsi 0x00000000           rdi 0x00000000
  r8 0x00000000            r9 0x00000000           r10 0x00000000
 r11 0x00000000           r12 0x00000000           r13 0x00000000
 r14 0x00000000           r15 0x00000000           rip 0x00000000
 rbp 0x00000000           rflags              rsp 0x00000000
```
should be
```
[0x10000122a]> ar=rax rbx
 rax 0x00000000           rbx 0x00000000   
```

**Comment by radare** [comment]
this will allow us to easily implement the command to get the register values only showing the registers involved in a function or basic block or portion of code.

**Comment by leberus** [comment]
Something like?

<pre>
$ r2 gcore-x86_64
Setting up coredump: asm.arch <-> x86 and asm.bits <-> 64
Setting up coredump: Registers have been set
Setting up coredump: 13 maps have been found and created
 -- I am Pentium of Borg. Division is futile. You will be approximated.
[0x00000000]> ar=rax rbx rcx
 rax 0xfffffffffffffdfc   rbx 0x7ffe187ca7a0       rcx 0x7fa434a03040
[0x00000000]>
</pre>

It's a bit raw, but..:

<pre>
diff --git a/libr/core/cmd_anal.c b/libr/core/cmd_anal.c
index c14167e7f..52a569f72 100644
--- a/libr/core/cmd_anal.c
+++ b/libr/core/cmd_anal.c
@@ -3005,12 +3005,24 @@ void cmd_anal_reg(RCore *core, const char *str) {
        case '=': // "ar="
                {
                        if (str[1]) {
+                               char *p = strdup (str + 1);
+                               char *reg = strtok (p, " ");
+                               RList *q_regs = r_list_new();
+                               while (reg) {
+                                       r_list_append (q_regs, reg);
+                                       reg = strtok (NULL, " ");
+                               }
+                               core->dbg->queried_regs = q_regs;
+                       }
+
+               /*      if (str[1]) {
                                st64 sz = r_num_math (core->num, str + 1);
                                if (sz > 0) {
                                        size = sz;
                                }
-                       }
+                       } */
                        __anal_reg_list (core, type, size, 2);
+                       r_list_free (core->dbg->queried_regs);
                }
                break;
        case '-': // "ar-"
diff --git a/libr/debug/dreg.c b/libr/debug/dreg.c
index 465f4a4b7..ca815cee7 100644
--- a/libr/debug/dreg.c
+++ b/libr/debug/dreg.c
@@ -138,6 +138,20 @@ R_API int r_debug_reg_list(RDebug *dbg, int type, int size, int rad, const char
                r_list_foreach (head, iter, item) {
                        ut64 value;
                        utX valueBig;
+                       // Is this register being asked ?
+                       RListIter *iterreg;
+                       RList *q_reg = dbg->queried_regs;
+                       char *q_name;
+                       bool found = false;
+                       r_list_foreach (q_reg, iterreg, q_name) {
+                               if (!strcmp (item->name, q_name)) {
+                                       found = true;
+                                       break;
+                               }
+                       }
+                       if (!found) {
+                               continue;
+                       }
                        if (type != -1) {
                                if (type != item->type && R_REG_TYPE_FLG != item->type) {
                                        continue;
diff --git a/libr/include/r_debug.h b/libr/include/r_debug.h
index 0e016f951..3a6c9044f 100644
--- a/libr/include/r_debug.h
+++ b/libr/include/r_debug.h
@@ -284,6 +284,7 @@ typedef struct r_debug_t {
        RTree *tree;
 
        RReg *reg;
+       RList *queried_regs;
        const char *creg; // current register value
        RBreakpoint *bp;
        void *user; // XXX(jjd): unused?? meant for caller's use??
</pre>

BTW, I noticed that <b>ar=</b> was meant to be used for specifying the size of the register to be queried. I am not sure if we should keep that code or just replace the behavior with this one.

**Comment by leberus** [comment]
Maybe we can use another <b>ar</b> command to specify the size.

**Comment by radare** [comment]
Oh right.. we can then use a different syntax like maybe prefix with : or comma to separate size and names

**Comment by leberus** [comment]
I thought about something like:

<pre>
ar=rax rbx
ar=eax ebx ecx
ar=:32
ar=:16
</pre>
Could we also mix different sizes?

<pre>
ar=ebx rcx
</pre>

PD: Why is this marked with the esil label. Is this meant to be done with <b>esil</b>?

**Comment by radare** [comment]
That would break compat. I was thinking in dr=32:rax rbx rcx

**Comment by leberus** [comment]
And the output of

<pre>
dr=32:rax rbx rcx
</pre>

should be:

1) Show all 32bits registers in colums + rax rbx and rcx in columns as well
2) Or show 32bits form of rax rbx and rcx

**Comment by radare** [comment]
3. Nothing because rax and rbx are not 32 bit registers :D

**Comment by leberus** [comment]
Yes, that's what I thought it would show the 32bits form of those.
So I guess we are left with:

1) <b>dr=:8/16/32/64</b> -> will show all registers in columns for the specified size
2) <b>dr=:[size][reg1] [reg2] [reg..]</b> -> will show only those registers for that specified size (in case they are valid, for example: <b>dr=:32 ebx eax</b>)
3) <b>dr=[reg1][reg2][reg..]</b> -> will show only those registers

**Comment by radare** [comment]
The idea is that whats after : will filter the regs that wouldbe shown. And the number if found will select the bits

**Comment by radare** [comment]
Noes! The other way around, to not break compat

dr=([size])(:[regs...])

**Comment by leberus** [comment]
Understood ;-)

**Comment by radare** [comment]
i think we can close this now
