### ISSUE TITLE
agj behaviour (graph.from, graph.to)

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#9716]
Currently `agj @ 0` prints all the functions from the binary into a single json array.
I think this is used to check whether the user wants to use a range.
* If addr == 0 and range is set, check that range
* If addr == 0, list all the functions
* Else list only the functions at our offset

This is not a valid behaviour to me because if a user seeks to 0 in Cutter (it can happen sometimes) then it's going to do `agj @ 0` and freeze for some seconds depending on the amount of functions.
Can we handle the address 0 as any address and find something else to list all the functions (if that's the intended behaviour) and detect range usage?

**Comment by radare** [comment]
Yep i agree the agj behaviour is confusing. Theres an issue to discuss all the commands and their use cases to cover all possible graphs we can be interested on. May be good to move the discussion there.

**Comment by radare** [comment]
related to https://github.com/radare/radare2/issues/9867

**Comment by radare** [comment]
open discussion in this pad https://hackmd.io/Nd6mgWwJRdOaCSYr7l2XQA?edit

**Comment by radare** [comment]
cc @cyanpencil

**Comment by cyanpencil** [comment]
I'm already working on a fix, I'll send a pr before tonight...
Sorry for the delay in fixing this, but it wasn't  a problem relative only to agj, but to many other ag commands and ended up rewriting most of how ag* commands are handled

**Comment by thestr4ng3r** [comment]
@cyanpencil Great, thanks for the info!
