### ISSUE TITLE
Feature request: Line highlight on seek

### ISSUE THREAD

**Issue by securisec** [radare/radare2#9754]
Currently, while seeking in Visual mode, r2 highlights only the offset. It would be nice to have an option that allows one to highlight the whole line while seeking. Visually, this highlight will stretch horizonally, and include all the columns including opcodes, comments etc. The highlight should adjust if `scr.breaklines` is enabled and work for multiline comments also. 

The cyan line in the sreenshot indicates how the highlight should look.

![image](https://user-images.githubusercontent.com/22226823/37792638-aa7acf66-2de2-11e8-9c72-8654f36f98b4.png)

**Comment by kazarmy** [comment]
Does that cyan line take up a whole line?

**Comment by kazarmy** [comment]
The offset is highlighted because it's the current value of the program counter, and not because it's the current seek value.

**Comment by kazarmy** [comment]
The seek line is always the first line in Visual mode and I'm curious to know as to why you need a line highlight for that. As for the program counter, a comment (e.g. `;-- eip:`) follows it around so it doesn't seem that a line highlight is needed there either.

**Comment by securisec** [comment]
Requesting a spanning seek line so that while navigating in visual mode,
one can easily and visually identify all the components of that particular
line like comments and such. Although I agree that this feature is really
not needed because everything can be done using the offset or current
location, it is just a little more visually appealing.

Also, thinking of future scale, a toggleable spanning line might help in
building some cool plugins. Example, moving esil emulation next to the
--eip instruction counter to stop replying on comments to annotate things
(just thinking ahead here)

**Comment by kazarmy** [comment]
`scr.breaklines` doesn't depend on content -- this does and so implementation of this is somewhat more complicated.

**Comment by kazarmy** [comment]
See #9853 for discussion.
