### ISSUE TITLE
r2pm windows

### ISSUE THREAD

**Issue by GHXST01** [radare/radare2#9781]
Probably an insanely dumb question but I just installed radare2 from the official website for windows.
The blog post I am following along with uses the r2pm to install r2frida, however I am not able to find r2pm in the install files located under `C:\Users\***\AppData\Local\Programs\radare2`

Do I get it separately from somewhere?

My apologies if I'm bothering anyone with this question.

**Comment by XVilka** [comment]
Because it is a shellscript  https://github.com/radare/radare2/blob/master/binr/r2pm/r2pm

There is an ongoing issue to rewrite it in C to be completely portable: 
- https://github.com/radare/radare2/issues/7493
 - https://github.com/radareorg/cutter/issues/420

**Comment by xarkes** [comment]
Btw the new tool can be found here: https://github.com/radareorg/r2pm

**Comment by Maijin** [comment]
Yes closing here - see https://github.com/radareorg/r2pm
