### ISSUE TITLE
R2 debugger doesn't read input from .rr2 file

### ISSUE THREAD

**Issue by Obaied** [radare/radare2#9788]
I need a way to pipe input from a file/python one-liner to dc. Preferably also a way to do that with `ood` like `ood < `python -c 'print "a"*32'`.

Here's what I have now.

```
$ cat profile.rr2

#!/usr/bin/rarun2
program=./vuln
input=AAAA

$ rarun2 profile.rr2
read input: AAAA
Success!

$ r2 -R profile.rr2 -d vuln
read input: 
```

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX x64
| File format of the file you reverse (mandatory)      | Mach-O executable i386
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.5.0-git 17696 @ darwin-x86-64 git.2.4.0-177-g8a503d0 commit: 8a503d0cbe3b70e3e588e5c10c7f65c3e6eca934 build: 2018-03-20__15:14:37

### Expected behavior
Have `r2 -R profile.rr2 -d vuln` pipe input to stdin when running the executable.

### Actual behavior
No input is piped

**Comment by Symen** [comment]
You can try `r2 -d ./vuln -e dbg.profile=profile.rr2`. `-e` should do the trick.

**Comment by radare** [comment]
Use -r or -R and dont pass flags after -d or may be taken as args of the program in some systems.

**Comment by Obaied** [comment]
It worked!
Closing this issue. Thanks to both of you
