### ISSUE TITLE
asm.emu.* -> emu.*

### ISSUE THREAD

**Issue by radare** [radare/radare2#9808]
and let the world burn in flames

**Comment by wargio** [comment]
I Agree

**Comment by kazarmy** [comment]
The `asm.emu` var becomes just `emu` though (as in `e emu=true`). This ok?

**Comment by radare** [comment]
That one is weird. Maybe i would kept it as asm.emu

What do you think?

And maybe just wait for release to change this. I was so busy irl to do it before

**Comment by kazarmy** [comment]
I prefer asm.emu since it's clear by itself that it's referring to a config var. E.g.:

```
 -x           open without exec-flag (asm.emu will not work), See io.exec
```

sounds better than:

```
 -x           open without exec-flag (emu will not work), See io.exec
```

The rest can move under emu.*

> And maybe just wait for release to change this.

Ok.

**Comment by wargio** [comment]
maybe we can have `e emu.enable = true`

**Comment by kazarmy** [comment]
`emu.enable` is a bit too long for me, and I like keeping `asm.emu` for its historical significance.

**Comment by radare** [comment]
Makes sense
