### ISSUE TITLE
Invalid read (SIGSEGV) in r_read_le32()

### ISSUE THREAD

**Issue by fumfel** [radare/radare2#9811]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 16.04 x64
| File format of the file you reverse (mandatory)      | ELF 
| Architecture/bits of the file (mandatory)            |  x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.5.0-git 17799 @ linux-x86-64 git.2.4.0-278-g8dff0e0 commit: 8dff0e010654a9a9f98ecb1ace8acef81d380c7b build: 2018-04-06__11:08:39

### Expected behavior

Disassembly of file.

### Actual behavior

SIGSEGV in `r_read_le32()`

### Steps to reproduce the behavior 
- Download: https://github.com/radare/radare2-regressions/pull/1262
- Command: `r2 -A r2_sigsegv_r_read_le32`

### Additional Logs, screenshots, source-code,  configuration dump, ...

ASAN log:

```
==4537==ERROR: AddressSanitizer: SEGV on unknown address 0x61b03031f090 (pc 0x7febd2aafaf9 bp 0x00003030060c sp 0x7ffef8e0b7e0 T0)
    #0 0x7febd2aafaf8 in r_read_le32 XYZ/radare2/libr/include/r_endian.h:176
    #1 0x7febd2aafaf8 in r_read_at_le32 XYZ/radare2/libr/include/r_endian.h:185
    #2 0x7febd2aafaf8 in r_read_le64 XYZ/radare2/libr/include/r_endian.h:199
    #3 0x7febd2aafaf8 in r_read_ble64 XYZ/radare2/libr/include/r_endian.h:322
    #4 0x7febd2aafaf8 in get_nt_file_maps XYZ/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3344
    #5 0x7febd2ac657b in Elf64_r_bin_elf_get_maps XYZ/radare2/libr/..//libr/bin/p/../format/elf/elf.c:3412
    #6 0x7febd29637d4 in r_bin_object_set_items XYZ/radare2/libr/bin/obj.c:124
    #7 0x7febd2964f82 in r_bin_object_new XYZ/radare2/libr/bin/obj.c:94
    #8 0x7febd295c81b in r_bin_file_new_from_bytes XYZ/radare2/libr/bin/file.c:495
    #9 0x7febd292d2cd in r_bin_load_io_at_offset_as_sz XYZ/radare2/libr/bin/bin.c:486
    #10 0x7febd292d6f1 in r_bin_load_io_at_offset_as XYZ/radare2/libr/bin/bin.c:503
    #11 0x7febd292e135 in r_bin_load_io XYZ/radare2/libr/bin/bin.c:361
    #12 0x7febd3d697ab in r_core_file_do_load_for_io_plugin XYZ/radare2/libr/core/file.c:410
    #13 0x7febd3d697ab in r_core_bin_load XYZ/radare2/libr/core/file.c:567
    #14 0x5578c14636c0 in main XYZ/radare2/binr/radare2/radare2.c:1064
    #15 0x7febcd58482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #16 0x5578c1469548 in _start (/usr/local/bin/radare2+0x10548)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV XYZ/radare2/libr/include/r_endian.h:176 r_read_le32
==4537==ABORTING
```

**Comment by ret2libc** [comment]
This should have been fixed by https://github.com/radare/radare2/commit/324625cb334a7ff2c0f5b06b597dae21d4903567

**Comment by radare** [comment]
thats related to the rbuf.io <http://rbuf.io/> change i did some commits ago. thanks for pointing it out. it may affect other places
