### ISSUE TITLE
Cannot compile r2 in Fedora 27

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#9816]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 27 x64

### Expected behavior
Installed radare2.

### Actual behavior
Not installed radare2.

### Steps to reproduce the behavior 
```
$ git clone https://github.com/radare/radare2
$ cd radare2/
$ sudo sys/install.sh 
```

I think that problem is in one of the last commits: https://github.com/radare/radare2/commit/0e2f6c085876eea9d6b163e55f56bb01f21a4fa0 because I could compile r2 when I had commented line:
```
18 // #include <stropts.h>
```
### Additional Logs, screenshots, source-code,  configuration dump, ...
```
p/io_gprobe.c:18:10: fatal error: stropts.h: No such file or directory
 #include <stropts.h>
          ^~~~~~~~~~~
compilation terminated.
gmake[3]: *** [/home/user/radare2/libr/../global.mk:41: p/io_gprobe.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
...
LD libr_syscall.so
LD libr_crypto.so
gmake[1]: *** [Makefile:29: all] Error 2
gmake: *** [Makefile:55: all] Error 2
```

**Comment by ret2libc** [comment]
Same here...
