### ISSUE TITLE
pdf and VV printing bugs?

### ISSUE THREAD

**Issue by wavvs** [radare/radare2#9826]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Lubuntu x64
| File format of the file you reverse (mandatory)      | ELF32
| Architecture/bits of the file (mandatory)            | x86
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.5.0-git 17812 @ linux-x86-64 git.2.4.0-291-g14909482d commit: 14909482d8f1cdcbcebb4a36c78e6d24ce009331 build: 2018-04-07__18:09:28

### Actual behavior
pdf doesn't print whole main function
actual 
![image](https://user-images.githubusercontent.com/30052411/38456784-201f9c96-3a91-11e8-83ff-240565db025a.png)
expected
![image](https://user-images.githubusercontent.com/30052411/38456833-7e36507c-3a91-11e8-98d7-4ae6066df5a4.png)

VV doesn't print graph at all
![image](https://user-images.githubusercontent.com/30052411/38456849-a9a0cecc-3a91-11e8-8ef6-102cbf763d7e.png)

Please, confirm.

### Steps to reproduce the behavior 
- CAUTION: zip contains malware
[94b59b4761147519fecf662cecba7219ac2f70682ae02685081a181758cb705f.zip](https://github.com/radare/radare2/files/1886489/94b59b4761147519fecf662cecba7219ac2f70682ae02685081a181758cb705f.zip)

**Comment by sivaramaaa** [comment]
Hey it's actually a known issue , the block size is larger than max block size so u just need adjust an config var to get proper result 
```
e anal.bb.maxsize = 2048
s main
pdf 
```
And there is already an issue to make this process automatic ,see issue [#9564](https://github.com/radare/radare2/issues/9564) 

For now a warning is issued to the user when u run anlysis , so closing this issue !!
