### ISSUE TITLE
Add missing 6502 instructions

### ISSUE THREAD

**Issue by radare** [radare/radare2#9830]
yeah those are "undocumented", but pretty common from what i see

http://nesdev.com/undocumented_opcodes.txt

**Comment by radare** [comment]
see also https://www.pagetable.com/?p=3

**Comment by mscherer** [comment]
Linked to https://github.com/radare/radare2/issues/9671  (and the pagetable.com link should be https://www.pagetable.com/?p=39 )

**Comment by Maijin** [comment]
Duplicate of #9671
