### ISSUE TITLE
When toggling cursor, show bytes

### ISSUE THREAD

**Issue by radare** [radare/radare2#9847]
When cursor is enabled enable asm.bytes if its not set. Maybe this should be the default behaviour, or maybe not, but will be good to be able to do that and add a config var to choose

**Comment by radare** [comment]
Another option would be to disable asm.bytes by default and then use Vc to toggle them in visual

**Comment by radare** [comment]
cc @cyanpencil

**Comment by cyanpencil** [comment]
I'll work on this :+1:
