### ISSUE TITLE
Implementation of import graph

### ISSUE THREAD

**Issue by gu10ng1t** [radare/radare2#9867]
> I would call it import “graph” but i can think on other kind of graphs:
> 
> - callgraph
> - xrefs graph
> - refs graph
> - bb graph
> - data graph
> 
> For example, graphing all references to local variables in a function by making variables and addresses where those are referenced as nodes.
> 
> Etc
> 
> All this stuff is easy to do, the only complicated part is defining a clean way to achieve all that and cleanup the ag* commands once again to make it more consistent 
@radare (related to #9465)

**Comment by XVilka** [comment]
@cyanpencil - kind of related to the graphs issues, regarding the consistency of `ag` commands.

**Comment by cyanpencil** [comment]
Thank you for pointing this out to me. 
Also, #8385 is related - maybe we can add them to #6967?

**Comment by radare** [comment]
This is done in master already. thanks @cyanpencil !
