### ISSUE TITLE
assert in code

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#9874]
Often in the code you can find condition checks that should never happen (but sometimes do) and that are handled just with a `return NULL` or `return UINT64_MAX`. Although the code in this way keep "working", the wrong values may propagate further in the program, making it reach an inconsistent state that could lead to various (and hard) bugs.

Examples:
https://github.com/radare/radare2/blob/master/libr/io/io.c#L383
https://github.com/radare/radare2/blob/master/libr/io/io.c#L393
https://github.com/radare/radare2/blob/master/libr/bin/bin.c#L528
https://github.com/radare/radare2/blob/master/libr/core/canal.c#L809

And there are others.

What I propose is that we use some sort of asserts instead of this custom if blocks, so that preconditions/postconditions/expectations from the programmer (not user input!!!) can be easily validated and found. I think GLib does a good job at this and we could reuse something like https://developer.gnome.org/glib/stable/glib-Warnings-and-Assertions.html#g-return-if-fail for r2 too. In that way nothing will change for the final user (g_return_if_fail just prints an error msg to the screen and returns, as the current code does) but at the same time we can be notified of these errors and/or enable G_DEBUG=fatal-criticals while we(developers) are debugging.

Thoughts? Comments?

**Comment by radare** [comment]
i prefer to add an eprintf for those cases, so the user dont loose all its work, asserts are bad practice imho, because it result in having multiple different behaviours depending on how you build r2. call that eprintf assert if you want, but safe returns make it “keep working” even if an allocation fails. (for example), but some eprintfs can become really noisy if inside a loop or chained with others

**Comment by ret2libc** [comment]
That's why I like the GLib approach, where the assert gets translated into an `if (!expr) { eprintf(...); return;` or, if you want to test r2 and find all bugs (like what we usually do when developing) it gets translated into a real assert that halts the program execution.

About the noisiness, consider that if an anomalous condition becomes noisy, it really means there's something bad that needs to be fixed! Of course, these asserts shouldn't be used to test things that are not anomalous.

**Comment by ret2libc** [comment]
Solved with https://github.com/radare/radare2/commit/ab4dbd509f15ada62dbb361da177ebd37d0e0ea7
