### ISSUE TITLE
Make rahash2 -L output grep friendly

### ISSUE THREAD

**Issue by radare** [radare/radare2#9882]
Current output is like this:
```

Available Encoders/Decoders:
  base64
  base91
  punycode

Available Crypto Algos:
  rc2
  rc4
  rc6
```

should be like this:
```
enc base64
cry aes-cbc
...
```

additionally we may add a description, license, author, size of hash if any, etc.. like its done for the other r2 plugins.

**Comment by d3db0t** [comment]
Do you mean the output should be : 
enc base64
enc base91
enc punycode

cry rc2
cry rc4
cry rc6
...
and so on? @radare

**Comment by radare** [comment]
Yes. Grep friendly

**Comment by d3db0t** [comment]
Do I need to be assigned on this issue to start working or just finish and start a PR?

**Comment by d3db0t** [comment]
I guess someone did :laughing: @radare

**Comment by radare** [comment]
900 issues and 1collision 😱

**Comment by d3db0t** [comment]
Why is my travis CI build failing? Is it something related to Regression Tests? @radare

**Comment by radare** [comment]
Just search for XX]

**Comment by d3db0t** [comment]
I added the test, what should I do now? The travis build did not restart. @radare

**Comment by d3db0t** [comment]
Travis is happy now :smile:
