### ISSUE TITLE
Find references to a range of addresses

### ISSUE THREAD

**Issue by radare** [radare/radare2#9884]
The /r command lacks the ability to speicfy a range of addresses to be matching.

* Like it's done with /V.. so maybe the /rv or /rR or /rV should be the way to go

**Comment by radare** [comment]
after thinking a bit, i think the right commands would be:

* /rV [minaddr] [maxaddr] # like /r but with a range
* /rE [minaddr] [maxaddr]

we can also make all those commands accept a range expression instead of making different commands. but this is probably something to apply to other commands and do a generic api in r_util

**Comment by ret2libc** [comment]
I like the idea of having a "range expression" instead of many different commands.
Something like `/r 0x2000:0x3000`. It would require a little bit more thinking, but it provides much more flexibility IMO.

**Comment by radare** [comment]
this was fixed already in the merged pr
