### ISSUE TITLE
/V4 offset info is lost

### ISSUE THREAD

**Issue by radare** [radare/radare2#9886]
```
[0x00000000]> /V4 0x2000000 0x2200000
hits: 557
0x2f: 0x20d0100
0x745: 0x21acff7
0x256c: 0x21404c7
0x304e: 0x2064db2
0x3df1: 0x21ea7af
0x4a0f: 0x20b1ec9
0x4d29: 0x20ce8d9
```

In the output we have this.. but the flags are looking like this:

```
[0x00000000]> f
0x020d0100 4 hit.0x020d0100
0x021acff7 4 hit.0x021acff7
0x021404c7 4 hit.0x021404c7
0x02064db2 4 hit.0x02064db2
0x021ea7af 4 hit.0x021ea7af
0x020b1ec9 4 hit.0x020b1ec9
0x020ce8d9 4 hit.0x020ce8d9
0x021ad531 4 hit.0x021ad531
```

so... maybe we should just put the real offset in the name? or create xrefs, or create 2 flags.. ?

**Comment by ret2libc** [comment]
I'd go for making the flag something like `hit.<offset>.<value>`.

**Comment by radare** [comment]
What if you want the flagsin the offset?

**Comment by ret2libc** [comment]
What do you mean?

**Comment by radare** [comment]
when you search for values you have 2 addresses , the place where the value is found and the value itself. sometimes you want to know the offset and sometimes the value, so i would like to have flags for both, or at least let the user choose 1, 2 or 1+2

**Comment by sivaramaaa** [comment]
So then we could either create 2 flags or 1 flag at offset where the value is found and a xref to "value itself"

Also if u are going to place 2 flags , we can name them something like this : 
```
hit.offset.[num]  ---->  for place where the value is found

hit.value.[num] --> for value itself
```


> least let the user choose 1, 2 or 1+2

imho having this would only increase yet another config var , we already have a lot, we have to reduce adding config vars 

@radare can u tell me an use-case for having a flag at the value itself  , it would help me understand issue more clearly :)

**Comment by radare** [comment]
search hit flag names are defined by the user, so not sure if that will work. but yep, this seems a good appraoch, the user can later remove the ones he doesnt needs.
