### ISSUE TITLE
unaligned function signature comments and wrong pre line

### ISSUE THREAD

**Issue by radare** [radare/radare2#9887]
<img width="1440" alt="screen shot 2018-04-14 at 22 49 15" src="https://user-images.githubusercontent.com/917142/38772401-1c3c6a00-4036-11e8-83bb-11c543629866.png">

**Comment by radare** [comment]
@kazarmy can you have a look at this?

**Comment by kazarmy** [comment]
This one's tricky -- the reflines for the comment line shouldn't be the reflines for the previous line nor the next line, but the reflines for a `nop` instruction between the 2 lines. As a compromise, 8f209fade29b3c5c1f4eae931c0bd04c237a669c copies the previous line's reflines.
