### ISSUE TITLE
meson: has_header_symbol ADDR_NO_RANDOMIZE in socket/run.c

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#9897]
Even in meson there should be a check to see if ADDR_NO_RANDOMIZE is available and if it is, HAVE_DECL_ADDR_NO_RANDOMIZE shall be defined, as done in the configure script.

**Comment by xarkes** [comment]
cc @pelijah

**Comment by xarkes** [comment]
Closed in #9905
