### ISSUE TITLE
Game Gear ROM aac takes too much time

### ISSUE THREAD

**Issue by xarkes** [radare/radare2#9908]
It looks like `aac` takes now much more time on this binary:
https://github.com/radareorg/cutter/files/1869155/popils.gg.zip

Maybe you can find more information here:
https://github.com/radareorg/cutter/issues/427

```
$ time r2 ./popils.gg -qc 'aaa'
eco: cannot open colorscheme profile (/home/antide/apps/cutter/darkda)
Something went wrong
Checksum: 0x0000
ProductCode: 048017
Console: Game Gear
Region: Export
RomSize: 128KB
Value from 0x00000000 to 0x00020000
aav: 0x00000000-0x00020000 in 0x0-0x20000
r2 ./popils.gg -qc 'aaa'  8.74s user 0.02s system 99% cpu 8.795 total
$ r2 -v
radare2 2.3.0-git 18144 @ linux-x86-64 git.2.2.0-281-g788db8556
commit: 788db85562ddcb398ac71a98f02c361f3df5ab04 build: 2018-04-17__11:28:15
```
And it takes too much time in the other case. The wrong command is indeed `aac`.
[EDIT] Already 2 hours and still running.

**Comment by radare** [comment]
You are using an old r2. Please update, we dont review or fix bugs in old releases

**Comment by radare** [comment]
omg i missread, sry im exhausted :P should be easy to fix
