### ISSUE TITLE
ARM remote debug PC pc confusion

### ISSUE THREAD

**Issue by KoWu** [radare/radare2#9909]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | 4.16.0-2-ARCH x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 32-bit ARM EABI5
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 17934 @ linux-x86-64 git.2.5.0-76-gbfb54eafb commit: bfb54eafb8b00213df6e66b0f53994fb2104d4e3 build: 2018-04-17__11:45:00

### Expected behavior
Stepping should work. Continuing from breakpoint should work with dc.

### Actual behavior
Continuing from breakpoint does not work (nothing happens), stepping does not work (Stepping failed!), pc is zero after hitting breakpoint (at least tui thinks so, correct pc shown with dr=). Breakpoints needs to be removed before being able to continue debugging. Error thrown on startup: ar: Unknown register 'PC'

### Steps to reproduce the behavior 
Setup:
`qemu-arm -g 6666 chall-arm`
`r2 -b 32 -a arm -e dbg.bpinmaps=false -D gdb gdb://localhost:6666 -d chall-arm`
Radare:
* Case 1
`ds` (Stepping failed!)
* Case 2
`db sym.printf`
`dc` (Breakpoint is getting hit)
`dc` (Nothing happens)

### Additional Logs, screenshots, source-code,  configuration dump, ...
I traced the ar error message down to an `ar PC=$$` call, using pc instead of PC works fine. PC / pc confusion?

[chall-arm.zip](https://github.com/radare/radare2/files/1919288/chall-arm.zip)

**Comment by radare** [comment]
You cant use -D and -d

**Comment by KoWu** [comment]
Uh okay, my fault. Remote debugging ARM is nevertheless not possible, but I think thats #9209 .
