### ISSUE TITLE
How to Dissassemble in Radare2

### ISSUE THREAD

**Issue by LeoPilot** [radare/radare2#9917]
Hi Beginner here. Just downloaded Radare2. Did a fair bit of searching to find out how to dissassemble a 68000 machine code file. But still not sure how to do it. I have a binary file. I right click and select "use Radare2 to open it" which brings up a command line interface. Then I type pd 4. I get an output which looks a bit like 68000 but has several commands I don't recognise. How do I dissassemble my file and set it to be done in 68000. Also how do I choose the endian?

Any help much appreciated.

**Comment by LeoPilot** [comment]
Thank you. I downloaded the pdf and it helped a lot. I found out I have to type "pd 4 m68k"

**Comment by radare** [comment]
if you are using a modern version of r2, the arch is not defined as an argument of pd.

use r2 -a m68k or in the shell e asm.arch=m68k and then pd 4 to disassemble 4 instructions
