### ISSUE TITLE
radare2 crashes in V! mode when resizing console window

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#9920]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/64 
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 17947 @ linux-x86-64 git.2.5.0-81-gffe3dd1, commit: ffe3dd11ef764891d9cc917482fc3c6e8a5af33e build: 2018-04-18__08:11:08

### Expected behavior
radare2 should not crash
### Actual behavior
radare2 crashes

### Steps to reproduce the behavior 

1) run `r2 /bin/ls`
2) enter `V!` mode
3) resize the console window

### Additional Logs, screenshots, source-code,  configuration dump, ...
Anim: https://www.dropbox.com/s/x7y8h2h144bc0ch/r2_crash.gif?dl=0

gdb: <img width="715" alt="zrzut ekranu 2018-04-18 o 08 25 30" src="https://user-images.githubusercontent.com/1296768/38914950-1e628b26-42e2-11e8-9d7b-dcde7ee812f2.png">

Core file: https://www.dropbox.com/s/mfmyxp75y5y2kb1/core?dl=0

It's not clearly visible on the recording but I only resize the console window: https://asciinema.org/a/1YhuMBuCCXobZP4dcl8oFvkuj

**Comment by ITAYC0HEN** [comment]
Reproduced on Arch x64, Windows 10 64bit and on WSL (bash) as well.
@Vane11ope , probably one of your latest commits since it does not happen before. Can you please check this out?

**Comment by radare** [comment]
==39250==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6060000088e4 at pc 0x000103fe06d6 bp 0x7ffeec017690 sp 0x7ffeec017688
READ of size 4 at 0x6060000088e4 thread T0
    #0 0x103fe06d5 in Layout_run panels.c:209
    #1 0x103fe01d7 in doRefresh panels.c:471
    #2 0x1046bb628 in resize cons.c:245
    #3 0x7fff6127ff59 in _sigtramp (libsystem_platform.dylib:x86_64+0x1f59)
    #4 0x7ffeec01b3ef  (<unknown module>)
    #5 0x1046dc8c2 in r_cons_readchar input.c:480
    #6 0x103fd898c in r_core_visual_panels panels.c:623
    #7 0x103e6e174 in r_core_visual_cmd visual.c:1863
    #8 0x103e88f55 in r_core_visual visual.c:3063
    #9 0x103d4abbc in cmd_visual cmd.c:1228
    #10 0x103f1a1de in r_cmd_call cmd_api.c:233
    #11 0x103d629a7 in r_core_cmd_subst_i cmd.c:2686
    #12 0x103ccb3a3 in r_core_cmd_subst cmd.c:1733
    #13 0x103cc0a52 in r_core_cmd cmd.c:3368
    #14 0x103c98ef0 in r_core_prompt_exec core.c:2154
    #15 0x103be796d in main (r2:x86_64+0x10000896d)
    #16 0x7fff60f71014 in start (libdyld.dylib:x86_64+0x1014)
