### ISSUE TITLE
Wrong opcodes in x86 (inc rax)

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2#9925]
I think, in rasm2 this opcodes are wrong:

```
$ rasm2 -a x86 -b 64 -s intel 'inc [rcx]'
48ffc0
$ rasm2 -a x86 -b 64 -s intel 'inc rax'
48ffc0
```

r2 from git:
```
$ r2 -v
radare2 2.6.0-git 17964 @ linux-x86-64 git.2.5.0-90-g56681a52
commit: 56681a52f0615c049c2e16a1b0828f39cf75e1c7 build: 2018-04-18__22:48:37
```

**Comment by radare** [comment]
I found some more yesterday. Didnt reported because enotime, but will be good to give another bump to our x86 assembler soon or late before the next release

**Comment by radare** [comment]
```
6748ff01   inc qword [ecx]
66ff01     inc word [rcx]
6766ff01   inc word [ecx]
67fe01     inc byte [ecx]
fe01       inc byte [rcx]
...
```

doesnt seems like something easy to encode...

**Comment by PaoloMonti42** [comment]
I took a look and x86.nz is the assembler with this behavior. The others throw an error, and that makes sense. I can try to fix it, what is the expected behavior? Inferring a size, or error?

**Comment by PaoloMonti42** [comment]
Weird behavior for 'mov [reg], N' but in this case it seems to default to 'word ptr'

**Comment by radare** [comment]
what's the state of this issue?

**Comment by PaoloMonti42** [comment]
Solved [here](https://github.com/radare/radare2/pull/10049)

**Comment by PaoloMonti42** [comment]
Rbp+16 could be pointing both to  a dword or a qword

**Comment by radare** [comment]
Imho it should honor regsize if no ptrsize specified

Do u mean that it works when size is specified? Im afk now

**Comment by radare** [comment]
Then we should fix ragg because this instruction was spitted by it

**Comment by PaoloMonti42** [comment]
The thing is that, until x86_nz is fixed to support 'size ptr' instructions, there will be absolutely no fix on ragg2 that will make it happy.

If you think that making them incompatible is a big problem, we can revert 
* https://github.com/radare/radare2/commit/004031aaeb5b11eb31370e2822b4255316c4be17
* https://github.com/radare/radare2-regressions/commit/5e038b38652a6d3b73f91cde62c2e1f5ffa942b3
* https://github.com/radare/radare2-regressions/commit/d9ce07559f3bc130c3d7e2aa4bdd40cf3647fd2d

until the fix is ready, but I fear that won't come soon

**Comment by PaoloMonti42** [comment]
I just realized I'm a complete idiot, 'mov size ptr [reg], imm' already works with explicit sizes, it's only inc and dec that are not supported

**Comment by radare** [comment]
R2 assembler should work without specifying sizes. Otherwise the output of the disassembler cant be assembled back. Even if not standard.. not a single assembler works completely fine, and we can be flexible

**Comment by radare** [comment]
ping @PaoloMonti42 can you finish fixing this pr? its just inc/dec, right?

**Comment by PaoloMonti42** [comment]
It would need a complete rewrite similar to my mov [reg], imm PR.
Surely not something I can do in a night, but if you settle with common cases, I can do it ASAP.

**Comment by radare** [comment]
I think fixing this will be good for the r2wars competiion at the r2con.thats why i would like to have it fixed before tomorrow

**Comment by PaoloMonti42** [comment]
I understand, but if you asked earlier I could have given it more time.
I will make "inc/dec <any size> [rax/rbx/rcx/rdx/rsi/rdi]" and "inc/dec rax/rbx/rcx/rdx/rsi/rdi" work.
Adding checks for rsp, rap, rip, r8+, 32 and 16 bits registers will be impossible

**Comment by radare** [comment]
yeah no hurry, all you can do to improve the assembler before r2con is great. thanks! 

btw the PR introduces 2 regressions.
