### ISSUE TITLE
mmap..* overlap with fmap..* in EFI modules

### ISSUE THREAD

**Issue by mytbk** [radare/radare2#9929]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | PE(EFI)
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 18058 @ linux-x86-64 git.2.5.0-91-g880dfca21 commit: 880dfca21755b0068fd0c3007c4d2637a0aff8a3 build: 2018-04-19__21:26:48

### Expected behavior

There should be no mmap..text, mmap..data, etc. which are overlapped with fmap..* sections. And I can view all the global data.

### Actual behavior

There are mmap..* sections overlapped with fmap..* sections. The data will be all zeroes if I try to view the global data which is in one of the mmap..* sections.

### Steps to reproduce the behavior 

Use radare2 to open an EFI module, and x@ some address where it's both some mmap and fmap region. For example, Shell.efi from edk2 (see below) has some address range both in mmap..text and fmap..data.

### Additional Logs, screenshots, source-code, configuration dump, ...

An example:

```
$ rabin2 -S Shell.efi 
[Sections]
00 0x00000240 422656 0x00010240 425984 -r-x .text
01 0x00067540 415168 0x00077540 417792 -rw- .data
02 0x000ccb00  4160 0x000dcb00  8192 -r-- .reloc
$ r2 Shell.efi
 -- radare2 is for lulzhats
[0x0001b637]> om
 6 fd: 3 +0x00000240 0x00010240 - 0x0007753f r-x fmap..text
 5 fd: 6 +0x00000000 0x00077540 - 0x0007823f r-x mmap..text
 4 fd: 3 +0x00067540 0x00077540 - 0x000dcaff r-- fmap..data
 3 fd: 5 +0x00000000 0x000dcb00 - 0x000dd53f rw- mmap..data
 2 fd: 3 +0x000ccb00 0x000dcb00 - 0x000ddb3f r-- fmap..reloc
 1 fd: 4 +0x00000000 0x000ddb40 - 0x000deaff r-- mmap..reloc
[0x0001b637]> x @  0x00077540
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00077540  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077550  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077560  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077570  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077580  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077590  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775a0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775b0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775c0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775d0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775e0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775f0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077600  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077610  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077620  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x00077630  0000 0000 0000 0000 0000 0000 0000 0000  ................
[0x0001b637]> om-5
[0x0001b637]> x @  0x00077540
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00077540  0000 0100 0000 0000 aa04 0000 0000 0000  ................
0x00077550  5f02 0000 0000 0000 5f02 0000 0000 0000  _......._.......
0x00077560  9268 0000 0000 0000 2d05 0000 0000 0000  .h......-.......
0x00077570  e104 0000 0000 0000 6502 0000 0000 0000  ........e.......
0x00077580  ec04 0000 0000 0000 d604 0000 0000 0000  ................
0x00077590  5f02 0000 0000 0000 0000 0000 0000 0000  _...............
0x000775a0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775b0  0000 0000 0000 0000 0000 0000 0000 0000  ................
0x000775c0  91b3 0000 0000 0000 e347 0000 0000 0000  .........G......
0x000775d0  897c 0000 0000 0000 6d4a 0000 0000 0000  .|......mJ......
0x000775e0  ed4c 0000 0000 0000 ec17 0000 0000 0000  .L..............
0x000775f0  2219 0000 0000 0000 cb26 0000 0000 0000  "........&......
0x00077600  8048 0000 0000 0000 2d21 0000 0000 0000  .H......-!......
0x00077610  cb28 0000 0000 0000 ea47 0000 0000 0000  .(.......G......
0x00077620  be79 0000 0000 0000 0a88 0000 0000 0000  .y..............
0x00077630  d50a 0000 0000 0000 5a0a 0000 0000 0000  ........Z.......
```

**Comment by mytbk** [comment]
This behavior comes after the siol change, I've been using a workaround by om- the maps. The cause of this is the sections in EFI modules have a virtual size multiple of 4KB, but the physical size usually not, thus there are some bytes fall to the mmap..* region.

**Comment by radare** [comment]
Siol supports different psize and vsize

**Comment by mytbk** [comment]
> Siol supports different psize and vsize

Yes. I mean EFI modules always have a vsize multiply of 4K, and usually larger than psize. However, for a section of an EFI module, paddr(next section)-paddr(this section)=vaddr(next section)-vaddr(this section)=psize(this section)<vsize(this section) as is shown in `rabin2 -S` output, so there are unwanted mmaps which are overlapped with fmaps.

I don't know if the PE loader of UEFI firmware handle the vsize of the sections, but I think we need to do a workaround for EFI files when analyzing them.
