### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Grillette** [radare/radare2#9931]
Hello, I have a problem installing radare2 from git.

I can make my git clone on my environment without any issue but when I run ./sys/install.sh I got some error and can't finish the install. Just see the error below and let me now if you want to see the complete output. 

`cp: './plugins.cfg' and 'plugins.cfg' are the same file
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/usr'
checking for c compiler... gcc
checking for dynamic library... required
checking for patch... no
error: This program is required.`

I have searched on the Internet for a while and manage to find some similar issue but couldn't apply any solution. 

### Work environment

OS: Manjaro 17.1.8 Hakoila
Kernel: x86_64 Linux 4.14.34-1-MANJARO

**Comment by radare** [comment]
All those strings are in one line?

**Comment by radare** [comment]
The error is pretty clear. You have to install patch. Pacman -Syu patch should help

**Comment by Grillette** [comment]
Didn't know that patch was a library. Thank you it worked fine !

**Comment by radare** [comment]
patch is not a library, is a basic unix command, like diff
