### ISSUE TITLE
Need to update cross compiler link in Windows.md

### ISSUE THREAD

**Issue by tlqaksqhr** [radare/radare2#9937]
Well, I try to download Windows x86-64 cross compiler from "http://switch.dl.sourceforge.net/" but this link seems to be dead. And, In source forge site(link is : https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Automated%20Builds/), "mingw-w64-bin_i686-linux_20110627" is not exist. 
So, I think modify these information.

p.s. I'm not good at english, so I apologize if my expression looks like rude..

**Comment by xarkes** [comment]
Quick question: why do you cross compile?
Thanks for reporting dead link though :)

**Comment by tlqaksqhr** [comment]
I wish contribute this project(whatever).  That's why I doing cross compile
Thank you for answering me :)

**Comment by pelijah** [comment]
So do you want to build r2 on Windows? Why not to use Meson?

**Comment by XVilka** [comment]
Closing because of https://github.com/radare/radare2/issues/9973
