### ISSUE TITLE
return value of r_io_buffer_read is probably inconsistent

### ISSUE THREAD

**Issue by thejh** [radare/radare2#996]
Spotted something weird in `r_io_buffer_read`. This is just from looking at the code, so I might be wrong.

In the first case, if `len > l`, it fills the rest with `0xff` and returns the requested length (including the `0xff` bytes). In the second case, if `len > l`, it also fills the rest with `0xff`, but only returns the length that was filled with valid data. Is that intended?

**Comment by XVilka** [comment]
@condret probably you'll be interested in this bug

**Comment by radare** [comment]
can you provide a pull request showing this behaviour? or it is already fixed after 2 years?

**Comment by radare** [comment]
Closing until we have a proper test case for this issue to proof that is broken and someone interested in fixing it
