### ISSUE TITLE
rax2 convert hexstr to raw error on Windows

### ISSUE THREAD

**Issue by beijiuhu** [radare/radare2#9961]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 7 Pro SP1 64Bit
| r2 -v full output, **not truncated** (mandatory)     | commit: 562bd8f65ac9bcfb30ea2d2da95b6178776471a8 build: Tue 04/10/2018__ 8:26:07.70
### Expected behavior
```
rax2 -s 0a 0a 0a
```

and
```
0a 0a 0a
```

### Actual behavior
```
rax2 -s 0a 0a 0a
```
and 
```
0d 0a 0d 0a 0d 0a
```

**Comment by radare** [comment]
remove the spaces between that or quote the whole thing, otherwise thats considered separate numbers to be converted

aka expected behaviour

**Comment by beijiuhu** [comment]
test rax2 -s "0a0a0a" > t 
test rax2 -s 0a0a0a > t

some result:

0d0a0d0a0d0a

**Comment by beijiuhu** [comment]
my radare2 download from here http://radare.mikelloc.com/get/2.5.0/radare2-msvc_64-2.5.0.zip

**Comment by radare** [comment]
Omg windows specific issue. Thanks for reporting
