### ISSUE TITLE
Use the colorscheme in Visual Types menu

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#9966]
Don't use the hardcoded colors in the `Vb` - then `t` - menu, "visual types"
![screenshot_20180426_204456](https://user-images.githubusercontent.com/203261/39306406-b3138412-4992-11e8-916d-7587d60d6c55.png)

**Comment by XVilka** [comment]
@cyanpencil can you please check this one too?

**Comment by cyanpencil** [comment]
@XVilka Right now I have to focus on the ag* command refactoring to finish before the release, but after I'm done with that I'll look into this
