### ISSUE TITLE
Remove the Mingw32/Mingw64 support

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#9973]
Since we now have native MSVC support it is just an additional burden to support Mingw32/64, and some code can be cleaned. So please discuss. And MSVC 2015 version supports Windows versions higher than Windows XP (including it).

**Comment by xarkes** [comment]
I agree, I see no advantages to keep MinGW while MSVC is available.

**Comment by radare** [comment]
How can i get msvc in mac/linux? Mingw is there because its the only easy way to crosscompile to windows from there. Imho its useful, but i agree there are some inconsistencies that can make some people complain

**Comment by xarkes** [comment]
Well indeed, but give me one good reason to cross compile when there are releases binaries? If you don't have Windows, you surely don't need Windows binaries?

**Comment by XVilka** [comment]
@radare easy - just use Wine: https://github.com/xantares/msvc-wine

**Comment by radare** [comment]
And how to wget msvc.zip?

**Comment by XVilka** [comment]
http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by radare** [comment]
Why is this thing not in r2pm yet then?

**Comment by xarkes** [comment]
Because no one needed it until you today :p
So if we add that to r2pm and documentation to cross compile with wine, then it's all good, we can remove MinGW support?

**Comment by XVilka** [comment]
I was using Cygwin and Mingw too, but these days those are not popular due
to WSL (and improved C99 in MSVC) and have too big overhead.

On Apr 29, 2018 4:19 AM, "radare" <notifications@github.com> wrote:

Mainly because i dont like to depend on privative software to do something.
And when i was maintaining r2 for windows i was doing cygwin and mingw alone


> On 28 Apr 2018, at 12:36, xarkes <notifications@github.com> wrote:
>
> Because no one needed it until you today :p
> So if we add that to r2pm and documentation to cross compile with wine,
then it's all good, we can remove MinGW support?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/radare/radare2/issues/9973#issuecomment-385202912>, or mute
the thread

**Comment by radare** [comment]
World surf league?

**Comment by pelijah** [comment]
Windows Subsystem for Linux. But it is available only on Windows 10.

**Comment by TheAifam5** [comment]
What about Clang and LLDB? :)

**Comment by xarkes** [comment]
You can use clang with meson+ninja build system. Just do `set CC=clang` and follow the instructions for building.

**Comment by pelijah** [comment]
Meson doesn't support clang on Windows.

**Comment by thestr4ng3r** [comment]
If you want to cross compile, couldn't you just use meson? It has support for that built in already, so if we drop support for mingw in acr it would still be possible without us having to maintain anything. (except maybe details in the source code that may be incompatible with mingw).

**Comment by xarkes** [comment]
@virteman Could you please explain why? If you are using Windows, you surely have Visual Studio installed, why would you use mingw or cygwin rather than the official VS tools?

**Comment by virteman** [comment]
@xarkes cygwin can be used  connect window via ssh，then I can use linux terminal run r2  other than window's cmd.exe which is a ugly termal without some keybind as linux terminal.

**Comment by xarkes** [comment]
There are many replacements for Windows cmd.exe, including WSL.
I mean that @radare argument makes more sense to me than what you are describing...

**Comment by XVilka** [comment]
@pelijah by the way, meson support for clang-cl is improving steadily and only some minor parts are now unsolved. See these bugs for keeping the track:
- [Windows Clang with ninja backend not supported](https://github.com/mesonbuild/meson/issues/4232)
- [Compiler detection is incorrect for native LLVM/Clang install on Windows](https://github.com/mesonbuild/meson/issues/2560)
- [Meson can't find the resource compiler when using clang in MSVC ABI mode](https://github.com/mesonbuild/meson/issues/4105)

**Comment by XVilka** [comment]
Resolved by https://github.com/radare/radare2/commit/bb67b54f740a08b4e45f16fb4b1e2e3454fbbe11
