### ISSUE TITLE
rp2m build failed (Kali linux chroot on android)

### ISSUE THREAD

**Issue by WarrenHood** [radare/radare2#9983]
Hi. I want to install r2frida (since I am struggling to build frida)...  Everything goes fine and then build fails after cloning a tar.xz file and it says it does not look like a tar file

**Comment by radare** [comment]
rp2m is nothing.

download it by hand and try to uncompress it in your shell. the tar.xz works fine here and it is a valid file. and if it is not is a problem with frida, not radare
