### ISSUE TITLE
Implement xxd -i in rax2 -i

### ISSUE THREAD

**Issue by radare** [radare/radare2#9986]
```
$ echo hello world > hw
$ xxd -i hw
unsigned char hw[] = {
  0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x0a
};
unsigned int hw_len = 12;
$
```

This is already implement in r2 via the pc command, we just need to expose it in rax2 and update the manpage

**Comment by PaoloMonti42** [comment]
While working on this issue, I noticed some code for the -P option, but it's actually unreachable since the flag is not checked from the argv. Is this known?
```
} else if (flags & (1 << 20)) { // -P
		char *str = r_stdin_slurp (NULL);
		if (str) {
			char *res = r_hex_from_py (str);
			if (res) {
				printf ("%s\n", res);
				fflush (stdout);
				free (res);
			} else {
				eprintf ("Invalid input.\n");
			}
			free (str);
		}
		return false;
	}
````

**Comment by radare** [comment]
you see it you fix it :P

not known issue, and no tests for this

**Comment by PaoloMonti42** [comment]
Should I submit them as separate PRs?

**Comment by radare** [comment]
Yep. But same pr with different commits looks fine to me too
