### ISSUE TITLE
Incorrect graph view when analysing a function

### ISSUE THREAD

**Issue by aldelaro5** [radare/radare2#9987]
I get incorrect graph when trying to analyse a function.

I cannot share the binary, but here's the function code: https://pastebin.com/wttcjdhW

And here's the produced graph which looks incorrect: 
[ascii_graph.txt](https://github.com/radare/radare2/files/1959275/ascii_graph.txt)

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86-64 64 bits
| File format of the file you reverse (mandatory)      | DOL
| Architecture/bits of the file (mandatory)            | PPC
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 18028 @ linux-x86-64 git.2.5.0-145-g41b2b2559 commit: 41b2b2559336ba6fce5f9179c1f1c7b11d4fff77 build: 2018-04-28__01:42:32

### Expected behavior
The graph is correctly displayed and looks like a flowchart
### Actual behavior
The graph has multiple vertical stripes of 2 blocks per stripes
### Steps to reproduce the behavior 

1. Perform the aaaaa command
2. Seek at the address of the start of the function
3. In visual mode, type d then f to define the function and go exit visual mode
4. Type VV to get the incorrect graph

**Comment by radare** [comment]
Can you share any other binary to reproduce the issue? Or just type stream of bytes to write with wx and then af

**Comment by aldelaro5** [comment]
Unfortunately, I only have propreaitary binary at the moment so I can't get another binary, I will say that this issue did happened on another binary I had and that I noticed it after the frontend cutter was behaving strangely with graphs (while they worked fine before).  So this likely used to work meaning it might be a regression?

As for typing hex bytes.....I am not sure what to do tbh.

**Comment by Maijin** [comment]
Missing reproducer, closing.
