### ISSUE TITLE
Can't translate arm to hex on windows and ubuntu

### ISSUE THREAD

**Issue by Rader2UserThank** [radare/radare2#9990]
I tried to translate arm instruction to hex , but in THUMB2

For exmaples `add R0, R1, R2` inTHUMB2 hex it  `01EB0200` but when I do `rasm2 -a arm -b 32 "add R0, R1, R2"` I get `020081e0`

When I using the windows version I tried  `rasm2 -a arm -b 16 add r0, r1, r2` but I get
 `Cannot assemble 'add' at line 3
invalid`

**Comment by radare** [comment]
And the quotes?

**Comment by Rader2UserThank** [comment]
@radare  what do you mean please?

**Comment by radare** [comment]
If you dont quote the instruction you will be assembling only “add” without any argument. Which is wrong

**Comment by Rader2UserThank** [comment]
@radare , even I type  `rasm2 -a arm -b 16 "add r0, r1, r2"` I got `invalid`

**Comment by radare** [comment]
buy a mac, works fine here

**Comment by Rader2UserThank** [comment]
@radare I tried it on win/Linux , is there any solution how to translate arm thumb2 instruction to hex with radare 2?

**Comment by radare** [comment]
This process is not called “translate” or “convert”. Its called “assemble”

And yes you should be able to do so, if the instruction is not supported send a pr fixing it or install the keystone plugin or use the gas one
