### ISSUE TITLE
r2 search doesn't work after loading a project

### ISSUE THREAD

**Issue by pawlos** [radare/radare2#9992]
The search command `/` doesn't work when project is loaded from file (`Po`).

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64, macOS High Sierra 10.13.3 
| File format of the file you reverse (mandatory)      | ELF, Mach-O
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.6.0-git 18043 @ darwin-x86-64 git.2.5.0-156-g52aabd40f, commit: 52aabd40ffd21a0f4061cfa846e1e349a301e2b9 build: 2018-04-30__13:46:38

### Expected behavior
r2 search command should work after loading a project file

### Actual behavior
r2 prints an error message

### Steps to reproduce the behavior 
1) `r2 /bin/ls`
2) `Ps ls_project`
3) execute search command `/?` - help printed; works as expected
4) quit r2 (`q`)
5) When asked "Do you want to save the 'ls_project' project? (Y/n)"  answer Y
6) open r2 again - `r2 /bin/ls`
7) load the project file (`Po ls_project`)
8) When asked "Close current session? (Y/n)" answer Y
9) execute search `/?`

> Can't search if we don't have an open file.

### Additional Logs, screenshots, source-code,  configuration dump, ...
N/A

**Comment by Hanan-Natan** [comment]
Same issue here:
``radare2 2.6.0-git 1 @ windows-x86-32 git.
commit: 562bd8f65ac9bcfb30ea2d2da95b6178776471a8 build: Tue 04/10/2018__ 8:26:09.94``

**Comment by pawlos** [comment]
Looks like the `core->io->desc` is NULL and it exits on

    if (!core || !core->io || !core->io->desc) {

in cmd_search.c

**Comment by pawlos** [comment]
[0x004049a0]> o
     3 * r-x 0x0001ee78 /bin/ls
     4 - rw- 0x00000d68 null://3432
    [0x004049a0]> om
     3 fd: 3 +0x00000000 0x00400000 - 0x0041da63 r-x fmap.LOAD0
     2 fd: 3 +0x0001de00 0x0061de00 - 0x0061e5ff r-- fmap.LOAD1
     1 fd: 4 +0x00000000 0x0061e600 - 0x0061f367 rw- mmap.LOAD1
    [0x004049a0]> Po ls_project 
    Close current session? (Y/n) y
    [0x004049a0]> o
     3 - r-x 0x0001ee78 /bin/ls
     4 - rw- 0x00000d68 null://3432
    [0x004049a0]> om
     3 fd: 4 +0x00000000 0x0061e600 - 0x0061f367 rw- mmap.LOAD1
     2 fd: 3 +0x00000000 0x00400000 - 0x0041da63 r-x fmap.LOAD0
     1 fd: 3 +0x0001de00 0x0061de00 - 0x0061e5ff r-- fmap.LOAD1
    [0x004049a0]> /?
    Can't search if we don't have an open file.

Looks the same before loading and after. What should I look for in `o` and `om`?

For now I found a workaround. If the current session will not be closed search works fine.

**Comment by radare** [comment]
Wonder why core->io->desc is not a siol antipattern. @condret

**Comment by radare** [comment]
ive removed this check, try again to see if it works for you now, it shouldnt harm to drop this assumption

**Comment by pawlos** [comment]
works without the check
